gctx.o: gctx.cpp ../../../include/osdep.h \
 ../../../libs/gkdb/src/stdbase.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gctx/src/u_int64_t.CtxLongSet.SplayMap.h \
 ../../../libs/gctx/src/u_int64_t.CtxLongSet.Map.h \
 ../../../libs/cchlp/src/u_int64_t.defs.h \
 ../../../libs/gctx/src/ctxLongSet.h ../../../libs/gkdb/src/garutils.h \
 ../../../libs/gkdb/src/dociter.h ../../../libs/gkdb/src/btiter.h \
 ../../../libs/gctx/src/ctxwords.h ../../../libs/gkdb/src/basemask.h \
 ../../../include/garver.h ../../../libs/gctx/src/gctxl_ver.h \
 ../../../libs/cchlp/src/cchlp_ver.h
