USES
 'w:\shared\models\NewSchool\Shared Delphi\Shared Delphi.model.script'
 'w:\shared\models\NewSchool\Shared Delphi Low Level\Shared Delphi Low Level.model.script'
 'w:\shared\models\NewSchool\F1 Core\F1 Core.model.script'
 'w:\shared\models\NewSchool\Shared Delphi Testing Framework\Shared Delphi Testing Framework.model.script'
 'w:\shared\models\NewSchool\F1 Поддержка тестов\F1 Поддержка тестов.model.script'
 'w:\shared\models\NewSchool\Shared Delphi Scripting\Shared Delphi Scripting.model.script'
;

<<Project>> "F1 Поддержка скриптов"
 %UID '4E202DBF00C7'
 %SUMMARY 'Скриптовая машина для F1' ;
 %INCLUDES
  'w:\shared\models\NewSchool\F1 Поддержка скриптов\ScriptEngine\ScriptEngine.model.script' /* ScriptEngine */
 ; // %INCLUDES
 %DEPENDS
  U$ '4677DDBD0193' /* "Shared Delphi" */
  U$ '4ABCC25A0322' /* "Shared Delphi Low Level" */
  U$ '4AC23B8E0397' /* "F1 Core" */
  U$ '4B30CC420206' /* "Shared Delphi Testing Framework" */
  U$ '4DB0572601B7' /* "F1 Поддержка тестов" */
  U$ '4E1F0DD40187' /* "Shared Delphi Scripting" */
 ; // %DEPENDS
 %META
  %upv "Full MDP" false
  %upv "create project" true
  %upv "defines" 'nsDefine.inc'
  %upv "fix version" 0
  %upv "full constraint" true
  %upv "ifndef" 'NoScripts'
  %upv "major version" 7
  %upv "minor version" 12
  %upv "package prefix" 'ru.garant'
  %upv "root path suffix" '/implementation/Garant/GbaNemesis'
  %upv "space key" 'NMS'
  %upv "space name" 'Nemesis'
 ; // %META
 %TOBEINCLUDED
  U$ '4677DDBD0193' /* "Shared Delphi" */
  U$ '4A7C095601DA' /* "Base Operations" */
  U$ '4A7C099B004F' /* View */
  U$ '4ABCC25A0322' /* "Shared Delphi Low Level" */
  U$ '4AC23B8E0397' /* "F1 Core" */
  U$ '4B2A10C40309' /* DUnitTuning */
  U$ '4B30CC420206' /* "Shared Delphi Testing Framework" */
  U$ '4DB0572601B7' /* "F1 Поддержка тестов" */
  U$ '4DB057A602EB' /* "F1 Words" */
  U$ '4DCA567501F2' /* "F1 Shell Words" */
  U$ '4E1F0DD40187' /* "Shared Delphi Scripting" */
  U$ '4E1F0EB100C4' /* ScriptEngine */
 ; // %TOBEINCLUDED
; // "F1 Поддержка скриптов"