# DO NOT DELETE

baseinfo.o: ../../../libs/inifile/src/inifile.h
baseinfo.o: ../../../libs/gkdb/src/gardefs.h 
baseinfo.o: ../../../libs/gkdb/src/stdbase.h ../../../libs/gkdb/src/base.h
baseinfo.o: ../../../libs/gkdb/src/doccol.h ../../../libs/gkdb/src/collect.h
baseinfo.o: ../../../libs/gkdb/src/store.h
baseinfo.o: ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h
baseinfo.o: ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h
baseinfo.o: ../../../libs/gkdb/src/gkdb_ver.h
baseinfo.o: ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/hindex.h
baseinfo.o: ../../../libs/gkdb/src/indices.h
baseinfo.o: ../../../libs/gkdb/src/document.h
