PLATFORM:=solaris

SYSLIBS=omniORB3 omnithread omniGK_stub omniDynamic3 xnet nsl hoard thread posix4

# for gdm_serv
# DEFS=__x86__  __sunos__  __OSVERSION__=5 _NO_DOS_SCREEN _USE_CORBA_CONVERTS __USE_HOARD__

# for gdm
DEFS=__x86__  __sunos__  __OSVERSION__=5 _NO_DOS_SCREEN __USE_HOARD__

include ../src/common.mk
LDFLAGS += -L/export/home/andrew/omni3/lib/sun4_sosV_5.7
