USES
 axiom:TimeMachine
 
 Reminders.script
;

: "”становить дату машины времени Ќажать на медаль и проверить наличие баллона"

  /* —тек */ timemachine:SetDate

  "Ќажать на медаль {('WarnTimeMachineWarning')} и проверить наличие баллона"
;

// $Id: TimeMachine.script,v 1.4 2015/07/24 14:03:08 lulin Exp $

// $Log: TimeMachine.script,v $
// Revision 1.4  2015/07/24 14:03:08  lulin
// - готовимс€ к распиливанию аксиоматики на различные словари.
//
// Revision 1.3  2011/05/10 14:15:49  lulin
// {RequestLink:236719181}.
// є28.
//
// Revision 1.2  2011/05/06 15:49:38  lulin
// - делаем "предложени€".
//
// Revision 1.1  2011/05/06 12:50:49  lulin
// {RequestLink:265410566}.
// - выдел€ем общий код.
//
  