@echo off
	:: (C) SIE "GARANT-SERVICE-UNIVERSITY" LLC, 1990-2016

	set GARANT=

	set ERROR_SUCCESS=0

	set DOWNLOAD_ENABLED=1
	set DOWNLOAD_ERROR_SUCCESS=%ERROR_SUCCESS%
	set DOWNLOAD_ERROR_NODELTA=1
	set DOWNLOAD_ID=F1Download
	set DOWNLOAD_PATH=%GARANT%\delta
	set DOWNLOAD_RESTORE=1
	set DOWNLOAD_RESTORE_TIME=5
	set DOWNLOAD_RESUME=0
	set DOWNLOAD_RETRY=1
	set DOWNLOAD_RETRY_COUNT=15
	set DOWNLOAD_REVISION=0
	set DOWNLOAD_SEND_REPORT=0

	set UPDATE_ENABLED=1
	set UPDATE_ERROR_SUCCESS=%ERROR_SUCCESS%
	set UPDATE_ADMIN_NAME=ADMIN
	set UPDATE_ADMIN_PASSWORD=ADMIN
	set UPDATE_NO_BACKUP=0
	set UPDATE_REMOVE_ARCHIVE=0
	set UPDATE_PATH=%GARANT%\delta
	set UPDATE_SEND_REPORT=0
	set UPDATE_SKIP_WARNING=0

	set RUN_AT_END_ENABLED=0
	set RUN_AT_END_APPLICATION=
	set RUN_AT_END_COMMANDLINE=

	set MAIL_FROM=
	set MAIL_TO=

	set MAIL_CHARSET=windows-1251
	set MAIL_PRIORITY=1
	set MAIL_REPLYTO=%MAIL_TO%

	set MAIL_SERVER=
	set MAIL_SERVER_USER=
	set MAIL_SERVER_PASS=
exit /b
