USES
 QuickTestsUtils.script
;

PROCEDURE "Переместить курсор к формуле"
	2 раза "Нажать вниз"
	2 раза "Нажать табуляцию"
;

PROCEDURE "Изменить текст формулы"
	"Контрол по имени {(acButtonOKInExprEditor)}" pop:Control:Click
;

Тест TK344130696
  	Параметры: ( "Тестирование отрисованного" ) 
	Выполнить ( 
		"Переместить курсор к формуле" 
		@ ( focused:control:push pop:editor:EditFormula ) MODAL "Изменить текст формулы"
	)
;

TK344130696