dhreader.o: dhreader.cpp dhr_ver.h ../../gkdb/src/gkdb_ver.h \
 ../../gkdb/src/bmsk_ver.h dhreader.h ../../gkdb/src/gardefs.h \
 ../../../include/osdep.h deltadef.h
elems.o: elems.cpp deltadef.h elems.h ../../gkdb/src/check.h \
 ../../cchlp/src/Logger.h ../../cchlp/src/fstring.h \
 ../../cchlp/src/SplayMap.h ../../cchlp/src/Map.h \
 ../../cchlp/src/SplaySet.h ../../cchlp/src/Set.h \
 ../../cchlp/src/typecmp.h ../../../include/osdep.h \
 ../../gkdb/src/gardefs.h ../../cchlp/src/recode.h
hendlers.o: hendlers.cpp ../../gkdb/src/check.h elems.h hendlers.h \
 deltadef.h ../../cchlp/src/Logger.h ../../cchlp/src/fstring.h \
 ../../cchlp/src/SplayMap.h ../../cchlp/src/Map.h \
 ../../cchlp/src/SplaySet.h ../../cchlp/src/Set.h \
 ../../cchlp/src/typecmp.h ../../../include/osdep.h \
 ../../gkdb/src/gardefs.h ../../cchlp/src/recode.h
wordcol.o: tempdoc.h
