!include "..\..\..\mk\msvc32.inc"

project:	flex2cpp gc gc_chk gl mf2gardb

flex2cpp:	flex2cpp.mak
		$(MAKE) flex2cpp.mak
gc:		gc.mak
		$(MAKE) gc.mak CFG="gc - Win32 $(MODE)" all
gc_chk:		gc_chk.mak
		$(MAKE) gc_chk.mak CFG="gc_chk - Win32 $(MODE)" all
gl:		gl.mak
		$(MAKE) gl.mak CFG="gl - Win32 $(MODE)" all
mf2gardb:	mf2gardb.mak
		$(MAKE) mf2gardb.mak CFG="mf2gardb - Win32 $(MODE)" all
