argsutils.o: argsutils.cpp argsutils.h
belongs.o: ../../../libs/cchlp/src/CaseString.defs.h \
 ../../../include/osdep.h \
 ../../../libs/cchlp/src/FString.FString.SplayMap.h \
 ../../../libs/cchlp/src/FString.FString.Map.h \
 ../../../libs/cchlp/src/Pix.h ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/gkdb/src/gardefs.h garcomp.h \
 ../../../libs/cchlp/src/long.long.VHMap.h \
 ../../../libs/cchlp/src/long.long.Map.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/date.SplaySet.h \
 ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/long.VHSet.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/cchlp/src/rx.h ../../../libs/cchlp/src/Regex.h \
 belongs.h
blobtable.o: gcini.h ../../../include/osdep.h garcomp.h \
 ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/cchlp/src/long.long.VHMap.h \
 ../../../libs/cchlp/src/long.long.Map.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/date.SplaySet.h \
 ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/long.VHSet.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/cchlp/src/rx.h ../../../libs/cchlp/src/Regex.h \
 blobtable.h fstringer.h ../../../libs/cchlp/src/u_int32_t.VHSet.h
cacheIndex.o: cacheIndex.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h ../../../include/osdep.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/u_int32_t.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/u_int32_t.caddr_t.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/gkdb_ver.h ../../../libs/gkdb/src/bmsk_ver.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/refcol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/cchlp/src/hidxhlp.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.SplayNode.h
classes.o: ../../../libs/cchlp/src/CaseString.defs.h \
 ../../../libs/cchlp/src/FString.FString.SplayMap.h \
 ../../../libs/cchlp/src/FString.FString.Map.h \
 ../../../libs/cchlp/src/Pix.h ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.SplayNode.h classes.h \
 ../../../libs/cchlp/src/hnode.h ../../../libs/gkdb/src/gardefs.h \
 garcomp.h ../../../libs/cchlp/src/long.long.VHMap.h \
 ../../../libs/cchlp/src/long.long.Map.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/date.SplaySet.h \
 ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/long.VHSet.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/cchlp/src/rx.h ../../../libs/cchlp/src/Regex.h
complect.o: ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h garcomp.h \
 ../../../libs/cchlp/src/long.long.VHMap.h \
 ../../../libs/cchlp/src/long.long.Map.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/date.SplaySet.h \
 ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/long.VHSet.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/cchlp/src/rx.h ../../../libs/cchlp/src/Regex.h \
 complect.h
date.Set.o: ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h
date.SplayNode.o: ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h
date.SplaySet.o: ../../../libs/cchlp/src/date.SplaySet.h ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/cchlp/src/date.SplayNode.h
dbproc.m-reader.o: dbproc.m-reader.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/gc/src/dbproc.mf.h ../../../libs/gc/src/dbproc.mh.h
dbproc.m-to-gkdb.o: dbproc.m-to-gkdb.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/gardefs.h \
 dbproc.m-reader.h ../../../libs/gc/src/dbproc.mf.h \
 ../../../libs/gc/src/dbproc.mh.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/stdbase.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/gkdb_ver.h ../../../libs/gkdb/src/bmsk_ver.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/hindex.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h ../../../libs/gkdb/src/newdoc.h \
 cacheIndex.h ../../../libs/cchlp/src/u_int32_t.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/u_int32_t.caddr_t.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h \
 ../../../libs/gkdb/src/basemask.h
dbproc.m-writer.o: dbproc.m-writer.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/gc/src/dbproc.mf.h ../../../libs/gc/src/dbproc.mh.h
dbproc.mh-mt-srw.o: dbproc.mh-mt-srw.h \
 ../../../libs/gc/src/dbproc.mh.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gc/src/topic_t.h
dbproc.mh-mt.o: dbproc.mh-mt.h \
 ../../../libs/gc/src/dbproc.mh.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gc/src/topic_t.h
dumpClassEq.o: classes.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/Pix.h ../../../libs/cchlp/src/FString.defs.h
fstringer.o: fstringer.cpp ../../../include/osdep.h fstringer.h
garcomp.o: garcomp.cpp ../../../include/garver.h garcomp.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/cchlp/src/long.long.VHMap.h \
 ../../../libs/cchlp/src/long.long.Map.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/gsscreen/src/toys.h \
 ../../../libs/gsscreen/src/gsscreen.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/date.SplaySet.h \
 ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/long.VHSet.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/cchlp/src/rx.h ../../../libs/cchlp/src/Regex.h \
 nsrccmd.h gcini.h sttop.h sources.h \
 ../../../libs/cchlp/src/CaseString.defs.h \
 ../../../libs/cchlp/src/FString.FString.SplayMap.h \
 ../../../libs/cchlp/src/FString.FString.Map.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h argsutils.h classes.h \
 publish.h belongs.h complect.h refsort.h fstringer.h loadStringMap.h \
 dbproc.m-writer.h ../../../libs/gc/src/dbproc.mf.h \
 ../../../libs/gc/src/dbproc.mh.h blobtable.h norminfo.h \
 ../../../libs/cchlp/src/FString.long.VHMap.h \
 ../../../libs/cchlp/src/FString.VHSet.h \
 ../../../libs/cchlp/src/u_int64_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int64_t.Set.h \
 ../../../libs/cchlp/src/u_int64_t.defs.h \
 ../../../libs/cchlp/src/u_int64_t.SplayNode.h \
 ../../../libs/cchlp/src/u_int32_t.VHSet.h \
 ../../../libs/cchlp/src/u_int32_t.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/u_int32_t.caddr_t.Map.h \
 ../../../libs/cchlp/src/u_int32_t.FString.SplayMap.h \
 ../../../libs/cchlp/src/u_int32_t.FString.Map.h \
 ../../../libs/cchlp/src/u_int32_t.FString.VHMap.h gc_ver.h \
 ../../../libs/gkdb/src/gkdb_ver.h ../../../libs/gkdb/src/bmsk_ver.h \
 ../../../libs/cchlp/src/cchlp_ver.h
gcini.o: gcini.cpp gcini.h ../../../include/osdep.h garcomp.h \
 ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/cchlp/src/long.long.VHMap.h \
 ../../../libs/cchlp/src/long.long.Map.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/date.SplaySet.h \
 ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/long.VHSet.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/cchlp/src/rx.h ../../../libs/cchlp/src/Regex.h
gcpass1.o: gcpass1.cpp garcomp.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/cchlp/src/long.long.VHMap.h \
 ../../../libs/cchlp/src/long.long.Map.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/date.SplaySet.h \
 ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/long.VHSet.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/cchlp/src/rx.h ../../../libs/cchlp/src/Regex.h \
 ../../../libs/cchlp/src/long.long.SplayMap.h \
 ../../../libs/cchlp/src/CaseString.defs.h \
 ../../../libs/cchlp/src/FString.FString.SplayMap.h \
 ../../../libs/cchlp/src/FString.FString.Map.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h \
 ../../../libs/cchlp/src/u_int32_t.VHSet.h fstringer.h sttop.h \
 sources.h nsrccmd.h
gkcorr.o: gkcorr.cpp ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/btiter.h
glmain.o: glmain.cpp gl.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/basemask.h glt_ver.h gll_ver.h \
 ../../../libs/cchlp/src/cchlp_ver.h \
 ../../../libs/gsscreen/src/gsscreen_ver.h ../../../include/garver.h
glproc.o: glproc.cpp ../../../include/garver.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/gkdb/src/newdoc.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/doccol.h ../../../libs/gkdb/src/collect.h \
 ../../../libs/gkdb/src/store.h ../../../libs/gkdb/src/refcol.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/gkdb_ver.h ../../../libs/gkdb/src/bmsk_ver.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/hindex.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h ../../../libs/gkdb/src/btiter.h \
 ../../../libs/cchlp/src/u_int32_t.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/u_int32_t.caddr_t.Map.h \
 ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/long.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/long.caddr_t.Map.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/u_int64_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int64_t.Set.h \
 ../../../libs/cchlp/src/u_int64_t.defs.h \
 ../../../libs/cchlp/src/u_int64_t.SplayNode.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/CaseString.defs.h \
 ../../../libs/cchlp/src/FString.FString.SplayMap.h \
 ../../../libs/cchlp/src/FString.FString.Map.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/clTreeNode.SplaySet.h \
 ../../../libs/cchlp/src/clTreeNode.Set.h \
 ../../../libs/cchlp/src/clTreeNode.defs.h \
 ../../../libs/cchlp/src/clTreeNode.h \
 ../../../libs/cchlp/src/clTreeNode.SplayNode.h \
 ../../../libs/cchlp/src/long.long.SplayMap.h \
 ../../../libs/cchlp/src/long.long.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/gsscreen/src/toys.h ../../../libs/cchlp/src/hidxhlp.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h gl.h
kwfile.o: kwfile.cpp garcomp.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/cchlp/src/long.long.VHMap.h \
 ../../../libs/cchlp/src/long.long.Map.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/date.SplaySet.h \
 ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/long.VHSet.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/cchlp/src/rx.h ../../../libs/cchlp/src/Regex.h \
 ../../../libs/cchlp/src/CaseString.defs.h \
 ../../../libs/cchlp/src/FString.FString.SplayMap.h \
 ../../../libs/cchlp/src/FString.FString.Map.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h
loadStringMap.o: loadStringMap.cpp \
 ../../../libs/cchlp/src/CaseString.defs.h ../../../include/osdep.h \
 ../../../libs/cchlp/src/FString.FString.SplayMap.h \
 ../../../libs/cchlp/src/FString.FString.Map.h \
 ../../../libs/cchlp/src/Pix.h ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/cchlp/src/hnode.h \
 garcomp.h ../../../libs/cchlp/src/long.long.VHMap.h \
 ../../../libs/cchlp/src/long.long.Map.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/date.SplaySet.h \
 ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/long.VHSet.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/cchlp/src/rx.h ../../../libs/cchlp/src/Regex.h
mf2gardb.o: mf2gardb.cpp ../../../include/osdep.h dbproc.m-to-gkdb.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/gkdb/src/gardefs.h dbproc.m-reader.h \
 ../../../libs/gc/src/dbproc.mf.h ../../../libs/gc/src/dbproc.mh.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/stdbase.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/gkdb_ver.h ../../../libs/gkdb/src/bmsk_ver.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/hindex.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h
mfcheck.o: mfcheck.cpp ../../../include/osdep.h dbproc.m-reader.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gc/src/dbproc.mf.h \
 ../../../libs/gc/src/dbproc.mh.h argsutils.h
normfile.o: normfile.cpp ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.SplayNode.h norminfo.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h
nsrcparser.o: nsrcparser.cpp garcomp.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/cchlp/src/long.long.VHMap.h \
 ../../../libs/cchlp/src/long.long.Map.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/date.SplaySet.h \
 ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/long.VHSet.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/cchlp/src/rx.h ../../../libs/cchlp/src/Regex.h \
 classes.h sources.h sttop.h ../../../libs/cchlp/src/CaseString.defs.h \
 ../../../libs/cchlp/src/FString.FString.SplayMap.h \
 ../../../libs/cchlp/src/FString.FString.Map.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h publish.h norminfo.h \
 ../../../libs/gkdb/src/pack.h \
 ../../../libs/cchlp/src/FString.long.VHMap.h \
 ../../../libs/cchlp/src/FString.VHSet.h \
 ../../../libs/cchlp/src/u_int32_t.VHSet.h \
 ../../../libs/cchlp/src/u_int32_t.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/u_int32_t.caddr_t.Map.h \
 ../../../libs/cchlp/src/u_int32_t.FString.VHMap.h \
 ../../../libs/cchlp/src/u_int32_t.FString.Map.h \
 ../../../libs/cchlp/src/u_int64_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int64_t.Set.h \
 ../../../libs/cchlp/src/u_int64_t.defs.h \
 ../../../libs/cchlp/src/u_int64_t.SplayNode.h \
 ../../../libs/cchlp/src/u_int64_t.VHSet.h refsort.h nsrccmd.h
publish.o: publish.cpp ../../../libs/cchlp/src/CaseString.defs.h \
 ../../../include/osdep.h \
 ../../../libs/cchlp/src/FString.FString.SplayMap.h \
 ../../../libs/cchlp/src/FString.FString.Map.h \
 ../../../libs/cchlp/src/Pix.h ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gkdb/src/gardefs.h fstringer.h publish.h
refsort.o: refsort.cpp ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h refsort.h
sources.o: sources.cpp ../../../libs/cchlp/src/CaseString.defs.h \
 ../../../include/osdep.h \
 ../../../libs/cchlp/src/FString.FString.SplayMap.h \
 ../../../libs/cchlp/src/FString.FString.Map.h \
 ../../../libs/cchlp/src/Pix.h ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.SplayNode.h sources.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/hnode.h ../../../libs/gc/src/gclog.h \
 ../../../libs/cchlp/src/advlog.h ../../../libs/gkdb/src/gardefs.h \
 garcomp.h ../../../libs/cchlp/src/long.long.VHMap.h \
 ../../../libs/cchlp/src/long.long.Map.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/date.SplaySet.h \
 ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/long.VHSet.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/cchlp/src/rx.h ../../../libs/cchlp/src/Regex.h
sttop.o: sttop.cpp sttop.h garcomp.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/cchlp/src/long.long.VHMap.h \
 ../../../libs/cchlp/src/long.long.Map.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/date.SplaySet.h \
 ../../../libs/cchlp/src/date.Set.h \
 ../../../libs/cchlp/src/date.defs.h \
 ../../../libs/cchlp/src/date.SplayNode.h \
 ../../../libs/cchlp/src/long.VHSet.h \
 ../../../libs/gc/src/gclog.h ../../../libs/cchlp/src/advlog.h \
 ../../../libs/gc/src/dbproc.h ../../../libs/gc/src/topic_t.h \
 ../../../libs/cchlp/src/rx.h ../../../libs/cchlp/src/Regex.h \
 sources.h ../../../libs/cchlp/src/CaseString.defs.h \
 ../../../libs/cchlp/src/FString.FString.SplayMap.h \
 ../../../libs/cchlp/src/FString.FString.Map.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h
