'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.1
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GuideFormula.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Pic1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pic1_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pic1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pic1_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pic1_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pic1_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pic1_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pic1_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pic1_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pic1_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pic1_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pic1_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pic1_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pic1_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pic1_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pic1_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Знак операции &quot;меньше или порядка&quot;.
        '''</summary>
        Friend ReadOnly Property Больше() As String
            Get
                Return ResourceManager.GetString("Больше", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Символ используется для обозначения вектора, ставится перед выражением. В некоторых случаях возможна неправильная расстановка скобок. В таких случаях вместо символа рекомендуется использовать функцию Vect..
        '''</summary>
        Friend ReadOnly Property Вектор() As String
            Get
                Return ResourceManager.GetString("Вектор", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Используется для обозначения производной. Допустимо использование нескольких знаков подряд для обозначения производных высших степеней. В некоторых случаях возможна неправильная расстоновка скобок. В таких случаях вместо символа рекомендуется использовать функцию Strokes. Использование символа &quot;`&quot; возможно только если TExprBuilder.PostSymbols=True (по умолчанию).
        '''</summary>
        Friend ReadOnly Property Волна() As String
            Get
                Return ResourceManager.GetString("Волна", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Знак операции &quot;примерно равно&quot;.
        '''</summary>
        Friend ReadOnly Property Волна2() As String
            Get
                Return ResourceManager.GetString("Волна2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Выражения состоят из операндов, разделённых знаками сравнения, операнды - из слагаемых, разделённых знаками сложения и вычитания, слагаемые - из множителей, разделённых знаками умножения и деления. В примере 1 &quot;a&quot; и &quot;b+c/d&quot; - операнды, &quot;b&quot; и &quot;c/d&quot; - слагаемые, &quot;c&quot; и &quot;d&quot; - множители. Множители могут быть одного из следующих видов:
        '''1. Числовая константа (в том числе начинающаяся с символа &quot;#&quot;, идентификатор или токен
        '''2. Выражение, заключенное в круглые, квадратные, прямые или фигурные скобки.
        '''3. Функция.
        ''' [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property Выражения() As String
            Get
                Return ResourceManager.GetString("Выражения", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Единицы ширины, использующиеся в некоторых зарезервированных функциях для указания размера пробела, подобраны так, что одна единица ширины примерно равна толщине вертикальной линии в символе &quot;+&quot;..
        '''</summary>
        Friend ReadOnly Property Единицы_ширины() As String
            Get
                Return ResourceManager.GetString("Единицы_ширины", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Запятая, отделяющая несколько подряд идущих выражений. После запятой может быть произвольное число пробелов, однако это не влияет на расстояние между выражениями, которое составляет семь единиц толщины. Перед запятой пробелов быть не должно..
        '''</summary>
        Friend ReadOnly Property Запятая() As String
            Get
                Return ResourceManager.GetString("Запятая", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Знак диаметра..
        '''</summary>
        Friend ReadOnly Property Знак_диаметра() As String
            Get
                Return ResourceManager.GetString("Знак_диаметра", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Символ используется для обозначения верхнего индекса или возведения в степень. В некоторых случаях возможна неправильная расстановка скобок или многоступенчатых индексов. В таких случаях вместо символа рекомендуется использовать функцию Pow. Если используется вместа с нижним индексом (символ &quot;_&quot; или функция Ind), то сначала указывается нижний индекс, а затем - верхний (пример 2), в противном случае индексы будут отображаться некорректно (пример 3). Использование символа &quot;^&quot; возможно только если TExprBuilder [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property Крыша() As String
            Get
                Return ResourceManager.GetString("Крыша", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Знак операции &quot;меньше&quot;.
        '''</summary>
        Friend ReadOnly Property Меньше() As String
            Get
                Return ResourceManager.GetString("Меньше", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Символ используется для обозначения нижнего индекса. В некоторых случаях возможна неправильная расстановка скобок или многоступенчатых индексов (пример 2). В таких случаях вместо символа рекомендуется использовать функцию Ind (пример 3). Использование символа &quot;_&quot; для обозначения нижнего индекса возможно только если TExprBuilder.PostSymbols=True (по умолчанию)..
        '''</summary>
        Friend ReadOnly Property Нижний_индекс() As String
            Get
                Return ResourceManager.GetString("Нижний_индекс", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Знак операции деления. Используется косая черта. В некотогрых случаях неправильно убирает скобки (пример 2). В этом случае рекомендуется пользоваться скобками !() (пример 3)..
        '''</summary>
        Friend ReadOnly Property Обратный_2слеш() As String
            Get
                Return ResourceManager.GetString("Обратный_2слеш", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Используется для обозначения производной. Допустимо использование нескольких знаков подряд для обозначения производных высших степеней. В некоторых случаях возможна неправильная расстоновка скобок. В таких случаях вместо символа рекомендуется использовать функцию Strokes. Использование символа &quot;`&quot; возможно только если TExprBuilder.PostSymbols=True (по умолчанию).
        '''</summary>
        Friend ReadOnly Property Обратный_апостроф() As String
            Get
                Return ResourceManager.GetString("Обратный_апостроф", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Знак операции деления. Всегда используется деление в виде простой дроби. В сложных выражениях, использующих различные символы умножения и деления в произвольном порядке &quot;интеллектуально&quot; распределяет множители между числителем и знаменателем (пример 2). Чтобы вынести множитель за пределы дроби, нужно дробь заключить в скобки (примеры 3, 4 и 5)..
        '''</summary>
        Friend ReadOnly Property Обратный_слеш() As String
            Get
                Return ResourceManager.GetString("Обратный_слеш", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Символ &quot;плюс&quot;, использующийя обычно для обозначения сложения.
        '''</summary>
        Friend ReadOnly Property Плюс() As String
            Get
                Return ResourceManager.GetString("Плюс", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Знак операции &quot;минус-плюс&quot;.
        '''</summary>
        Friend ReadOnly Property Плюс_минус() As String
            Get
                Return ResourceManager.GetString("Плюс_минус", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Знак операции &quot;плюс-минус&quot;.
        '''</summary>
        Friend ReadOnly Property Плюс_минус_обратно() As String
            Get
                Return ResourceManager.GetString("Плюс_минус_обратно", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на К простым выражениям относятся идентификаторы, токены и цифровые константы. Токены - это зарезервированные слова, использующиеся для обозначения специальных символов (пример 1). Регистр символов при написании токенов не важен за исключением токенов, обозначающих греческие буквы. Если первый символ такого токена имеет верхний регистр, то получается заглавная буква, если нижний - строчная. Идентификаторы воспроизводятся так, как они написаны в тексте. Идентификаторы могут состоять из английских и русских букв [остаток строки не уместился]&quot;;.
        '''</summary>
        Friend ReadOnly Property Простые_выражения() As String
            Get
                Return ResourceManager.GetString("Простые_выражения", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Конкатенация двух выражений. Символ должен либо не отделяться от обоих выражений пробелами (пример 1), либо отделяться от каждого из них одним пробелом (пример 2)..
        '''</summary>
        Friend ReadOnly Property Сивол_Конкатен() As String
            Get
                Return ResourceManager.GetString("Сивол_Конкатен", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Операция умножения. Сомножители перемножаются без знака независимо от того, допустимо ли такое перемножение. Перестановка множителей не производится..
        '''</summary>
        Friend ReadOnly Property Символ_2звезды() As String
            Get
                Return ResourceManager.GetString("Символ_2звезды", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Символ факториала. Использование символа &quot;!&quot; для обозначения факториала возможно только если TExprBuilder.PostSymbols=True (по умолчанию)..
        '''</summary>
        Friend ReadOnly Property Символ_Воск_Знак() As String
            Get
                Return ResourceManager.GetString("Символ_Воск_Знак", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Ставится перед цифровыми константами для указания, что они должны быть выведены в научном формате. Сравните пример 1 и пример 2..
        '''</summary>
        Friend ReadOnly Property Символ_Диез() As String
            Get
                Return ResourceManager.GetString("Символ_Диез", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Операция умножения. Проверяет, могут ли сомножители быть перемноженными без знака. Если могут, то знак умножения не используется (пример 1). Сомножители могут быть переставлены местами, чтобы обеспечить умножение без символа (пример 2). Если среди сомножителей несколько чисел, то числа объединяются в одно (пример 3). Если перемножение без символа невозможно ни при каком порядке множителей, используется символ точка (пример 4).
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property Символ_звезда() As String
            Get
                Return ResourceManager.GetString("Символ_звезда", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Символ &quot;минус&quot;, использующийся обычно для обозначения вычитания..
        '''</summary>
        Friend ReadOnly Property Символ_минус() As String
            Get
                Return ResourceManager.GetString("Символ_минус", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Знак операции деления..
        '''</summary>
        Friend ReadOnly Property Слеш_плюс() As String
            Get
                Return ResourceManager.GetString("Слеш_плюс", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Операция умножения. Сомножители перемножаются с помощью знака точки. Перестановка множителей не производится..
        '''</summary>
        Friend ReadOnly Property Умножение() As String
            Get
                Return ResourceManager.GetString("Умножение", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Ищет локализованную строку, похожую на Операция умножения. Сомножители перемножаются с помощью знака косого креста. Перестановка множителей не производится..
        '''</summary>
        Friend ReadOnly Property Умножение_плюс() As String
            Get
                Return ResourceManager.GetString("Умножение_плюс", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
