//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Update.rc
//
#define IDS_GARANTINI_NOTFOUND          1
#define IDS_BASESORG_NOTFOUND           2
#define IDBACK                          3
#define IDS_SELECTFOLDERWITHDELTAS      3
#define IDS_ERROR                       4
#define IDS_CONFIRM                     5
#define IDS_SUREEXIT                    6
#define IDS_SURECANCELCOPY              7
#define IDS_ERROROPENINGFILE            8
#define IDS_ERRORCREATINGFILE           9
#define IDS_ERRORREADINGFILE            10
#define IDS_ERRORWRITINGFILE            11
#define IDS_UPDATERUN                   12
#define IDS_ERROROPENINGBASE            13
#define IDS_ERRORREADINGHERE            14
#define IDS_BASENOTGL                   15
#define IDS_BASEPACKED                  16
#define IDS_CANTFINDBASEINFO            17
#define IDS_BASESORGPRIMARY             18
#define IDS_BASESORGBADCOMPLECT         19
#define IDS_BASEBADREVS                 20
#define IDS_UPDATENO                    21
#define IDS_UPDATEPART                  22
#define IDS_UPDATEFULL                  23
#define IDS_ABSENTPERIOD                24
#define IDS_ABSENTPERIODFOR             25
#define IDS_OLDDELTA                    26
#define IDS_UNSEGS                      27
#define IDS_PARTDELTALISTTITLE          28
#define IDS_NONEED                      29
#define IDS_ATTENTION                   30
#define IDS_NEEDDELTASTITLE             31
#define IDS_COLLECTPROGRESSTEXT         32
#define IDS_PARTNOTFULL                 33
#define IDS_PARTABSENT                  34
#define IDS_COLLECTERRORS               35
#define IDS_COLLECTCANCELED             36
#define IDS_COLLECTBADS                 37
#define IDS_PARTTITLE                   38
#define IDS_PARTDESC                    39
#define IDS_FILESTOCHECK                40
#define IDS_COLLECTBADSANDERRORS        41
#define IDS_COLLECTBADSANDCANCEL        42
#define IDS_DELTABADSIZE                43
#define IDS_DELTABADVER                 44
#define IDS_DELTATITLEHEADER            45
#define IDS_DELTASTOCHECK               46
#define IDS_ZIPSTOUNZIP                 47
#define IDS_UNZIPERRORS                 49
#define IDS_ZIPBADSANDCANCEL            50
#define IDS_UNZIPCANCELED               51
#define IDS_ZIPSTITLE                   52
#define IDS_SURECANCELUNZIP             53
#define IDS_SURECANCELCOLLECT           54
#define IDS_BASEUPDATED                 55
#define IDS_GUFAIL                      56
#define IDS_GLFAIL                      57
#define IDS_GLTITLE                     58
#define IDS_GUTITLE                     59
#define IDS_SURECANCELTRYEXIT           60
#define IDS_BASELOCKED                  61
#define IDS_COPYINGFILE                 62
#define IDS_SELECTFOLDERFORBACKUP       63
#define IDS_CHECKBOXBACKUP              64
#define IDS_RESTORINGFILE               65
#define IDS_BASERESTORED                66
#define IDS_BASENOTRESTORED             67
#define IDS_BASEDEAD                    68
#define IDS_DELETEBACKUP                69
#define IDS_UPDATERUNOTHER              70
#define IDS_PARTUPDATETEXT              72
#define IDS_BADPATCHVERSION             73
#define IDS_PATCHNOTAPPLIED             74
#define IDS_SHELLLOCKED                 75
#define IDS_UPDATENOLOG                 76
#define IDS_PARTUPDATELOG               77
#define IDS_BADDELTASLOG                78
#define IDS_SELECTFOLDERFORBASECOPY     79
#define IDS_DOWNLOADDELTA               80
#define	IDS_STARTBACKUPLOG		81
#define	IDS_ENDBACKUPLOG		82
#define	IDS_BACKUPREFUSAL		83
#define IDS_DUP				84
#define	IDS_ENDBACKUPLOG_ERROR		85
#define IDD_WELCOME_DIALOG              102
#define IDD_FATALERROR_DIALOG           103
#define IDD_SELECTDELTASFOLDER_DIALOG   104
#define IDD_CONFIRM_DIALOG              105
#define IDD_COPYFILES_DIALOG            106
#define IDD_PARTUPDATE_DIALOG           107
#define IDD_CANTUPDATE_DIALOG           108
#define IDD_FULLUPDATE_DIALOG           109
#define IDD_COLLECTPARTS_DIALOG         110
#define IDD_BADDELTAS_DIALOG            111
#define IDD_UNZIP_DIALOG                112
#define IDD_TRYOPENBASES_DIALOG         113
#define IDD_SELECTBACKUPFOLDER_DIALOG   114
#define IDD_RUNGUGL                     115
#define IDD_LOGIN_DIALOG                116
#define IDD_SELECTBASEFOLDER_DIALOG     117
#define IDR_MAINFRAME                   128
#define BMP_DESIGNEDFOR                 132
#define IDB_DESIGNED                    133
#define IDI_BEHAND                      134
#define IDB_NTCOMPATIBLE                135
#define IDI_BESTOP                      137
#define IDI_BEWARNING                   138
#define IDI_BEINFO                      139
#define IDC_FILE                        141
#define IDB_GARANT                      145
#define IDB_PROGRESS                    147
#define IDI_E                           148
#define IDD_WAITSERVER                  149
#define IDD_WAITSERVER2                 150
#define IDD_SELECTBASEFOLDEREX_DIALOG   151
#define IDD_WAITSERVER1                 152
#define IDD_SELECTUPDATETYPE_DIALOG     153
#define IDD_SELECTREMOTETYPE_DIALOG     154
#define IDD_SELECTSERVERTYPE_DIALOG     155
#define IDD_METHOD_DIALOG               156
#define IDS_MSG_91                      167
#define IDS_MSG_92                      168
#define IDS_MSG_93                      169
#define IDS_MSG_94                      170
#define IDS_TRANSIENT                   171
#define IDS_SERVER_NOT_FOUND            172
#define IDS_BAD_NETWORK_CONFIG          173
#define IDS_IP_ADDRESS_NOT_FOUND        174
#define IDS_DATANOTFOUND                175
#define IDS_SERVERCOPYFAILED            176
#define IDS_FORBIDDEN                   177
#define IDS_MSG_95                      178
#define IDS_NOMORE_CONNECTIONS          179
#define IDS_BADTOMFILE                  180
#define IDS_NOTENOUGHROOM               181
#define IDS_SERVERCOPY2FAILED           182
#define IDS_BASEEXSIZE                  183
#define IDS_SELECTFOLDERFORBASEEX       184
#define IDS_COPYPROCESSFAILED           185
#define IDS_NOTENOUGHROOM2              186
#define IDS_ACCESSDENIED                187
#define IDS_CANNOTFINDDATA              188
#define IDS_UPDATEFAILED                189
#define IDS_FREESPACE                   190
#define IDS_COPYOK                      191
#define IDS_COPY2CLIENT                 192
#define IDS_SMALLFREESPACE              193
#define IDS_CANTWRITE                   194
#define IDS_NOBASE                      195
#define IDS_CANTWRITE2                  196
#define IDS_XMLIMPORT                   197
#define IDS_NOTUPDATED                  198
#define IDD_WAITXML                     199
#define IDS_SERVER_IS_STARTING          200
#define IDC_TEXT                        1001
#define IDC_BEICON                      1002
#define IDC_BROWSE                      1003
#define IDC_DELTAPATH                   1004
#define IDC_BROWSE2                     1004
#define IDC_FILEPROGRESS                1007
#define IDC_MORE                        1010
#define IDC_FILESPROGRESS               1011
#define IDC_PARTSCOUNT                  1012
#define IDC_PARTS                       1013
#define IDC_WASERROR                    1014
#define IDC_BADDELTAS                   1016
#define IDC_DELTACOUNT                  1018
#define IDC_DELTAPROGRESS               1019
#define IDC_RESULT                      1020
#define IDC_ARCHIVE                     1021
#define IDC_BADZIPS                     1022
#define IDC_ZIPSPROGRESS                1023
#define IDC_ZIPSCOUNT                   1024
#define IDC_PROGRESS                    1025
#define IDC_MESSAGE                     1026
#define IDC_MESSAGE2                    1027
#define IDC_RADIOYES                    1028
#define IDC_RADIONO                     1029
#define IDC_STATICHELP                  1030
#define IDC_BACKUPPATH                  1031
#define IDC_BACKUPGROUP                 1032
#define IDC_BACKUPSIZE                  1033
#define IDC_BACKUPGROUP2                1033
#define IDC_BACKUPPATH2                 1034
#define IDC_NODISKS                     1036
#define IDC_PARTUPDATETEXT              1037
#define IDC_DOBACKUP                    1038
#define IDC_E                           1052
#define IDC_EDIT1                       1053
#define IDC_EDIT2                       1054
#define IDC_RADIO1                      1057
#define IDC_RADIO2                      1058
#define IDC_BASEPATH                    1059
#define IDC_BASESIZE                    1060
#define IDC_IMAGE_PROGRESS              1061

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
