// Document 4570511E038A Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4570511E038A

FORWARD ME_45EEB65202FC

: ME_45EEB65202FD
 CONST UID '45EEB65202FD'
 CONST Name 'LO_DOCUMENT'
 CONST Class class_Attribute
 %SUMMARY 'Документ.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_45EEB65202FD LO_DOCUMENT

: ME_45EEB65202FE
 CONST UID '45EEB65202FE'
 CONST Name 'LO_RELATED_DOCUMENT'
 CONST Class class_Attribute
 %SUMMARY 'Справка к документу.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_45EEB65202FE LO_RELATED_DOCUMENT

: ME_45EEB65202FF
 CONST UID '45EEB65202FF'
 CONST Name 'LO_EXTERNAL_OBJECT'
 CONST Class class_Attribute
 %SUMMARY 'Внешний объект.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_45EEB65202FF LO_EXTERNAL_OBJECT

: ME_45EEB6520300
 CONST UID '45EEB6520300'
 CONST Name 'LO_MULTILINK'
 CONST Class class_Attribute
 %SUMMARY 'Мультиссылка (список документов).' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_45EEB6520300 LO_MULTILINK

: ME_45EEB6520301
 CONST UID '45EEB6520301'
 CONST Name 'LO_EXTERNAL_LINK'
 CONST Class class_Attribute
 %SUMMARY 'Внешняя ссылка.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_45EEB6520301 LO_EXTERNAL_LINK

: ME_45EEB6520302
 CONST UID '45EEB6520302'
 CONST Name 'LO_QUERY'
 CONST Class class_Attribute
 %SUMMARY 'Запрос.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_45EEB6520302 LO_QUERY

: ME_45EEB6520303
 CONST UID '45EEB6520303'
 CONST Name 'LO_BOOKMARK'
 CONST Class class_Attribute
 %SUMMARY 'Закладка' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_45EEB6520303 LO_BOOKMARK

: ME_45EEB6520304
 CONST UID '45EEB6520304'
 CONST Name 'LO_EXTERNAL_OPERATION'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_45EEB6520304 LO_EXTERNAL_OPERATION

: ME_487C71B40306
 CONST UID '487C71B40306'
 CONST Name 'LO_ENO'
 CONST Class class_Attribute
 %SUMMARY 'Ссылка на ENO' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_487C71B40306 LO_ENO

: ME_49F7FEE50137
 CONST UID '49F7FEE50137'
 CONST Name 'LO_AUTOREFERAT'
 CONST Class class_Attribute
 %SUMMARY 'Автореферат' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_49F7FEE50137 LO_AUTOREFERAT

: ME_4E0D881C0295
 CONST UID '4E0D881C0295'
 CONST Name 'LO_SCRIPT'
 CONST Class class_Attribute
 %SUMMARY 'скрипт для К271754146' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_4E0D881C0295 LO_SCRIPT

: ME_55BB558F01DA
 CONST UID '55BB558F01DA'
 CONST Name 'LO_DELETED_FOLDERS_CONTENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_55BB558F01DA LO_DELETED_FOLDERS_CONTENT

: ME_45EEB65202FC
 CONST UID '45EEB65202FC'
 CONST Name 'LinkedObjectType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Тип объекта, на который указывает гипертекстовая ссылка.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EEB65202FD // LO_DOCUMENT
 ME_45EEB65202FE // LO_RELATED_DOCUMENT
 ME_45EEB65202FF // LO_EXTERNAL_OBJECT
 ME_45EEB6520300 // LO_MULTILINK
 ME_45EEB6520301 // LO_EXTERNAL_LINK
 ME_45EEB6520302 // LO_QUERY
 ME_45EEB6520303 // LO_BOOKMARK
 ME_45EEB6520304 // LO_EXTERNAL_OPERATION
 ME_487C71B40306 // LO_ENO
 ME_49F7FEE50137 // LO_AUTOREFERAT
 ME_4E0D881C0295 // LO_SCRIPT
 ME_55BB558F01DA // LO_DELETED_FOLDERS_CONTENT
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TLinkedObjectType'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_45EEB65202FC LinkedObjectType

FORWARD ME_45EEB6520309

: ME_45EEB652030B
 CONST UID '45EEB652030B'
 CONST Name 'obj_name'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Имя отсутствующего объекта.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520309 // MissingInfo
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_45EEB652030B obj_name

: ME_45EEB652030C
 CONST UID '45EEB652030C'
 CONST Name 'blocks_info'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Имена блоков (баз), в которых содержится отсутствующий объект.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520309 // MissingInfo
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_45EEB652030C blocks_info

: ME_45EEB652030A
 CONST UID '45EEB652030A'
 CONST Name 'is_one_block'
 CONST Class class_Operation
 %SUMMARY 'Отсутствующий объект содержится только в одном блоке (базе) - необходимо для правильного постоения сообщения о том, в каком(их) блоке(ах) содержится отсутствующий объект.  Если в blocks_info содержится только один блок, то возвращается true, в противном случае false.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520309 // MissingInfo
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB652030A is_one_block

: ME_46110DD20113
 CONST Name 'pid'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_46110DD20113 pid

: ME_46110DBE01ED
 CONST UID '46110DBE01ED'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520309 // MissingInfo
 ;
 : Parameters
   Seq: ( ME_46110DD20113 // pid
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false

ref; // ME_46110DBE01ED make

: ME_45EEB6520309
 CONST UID '45EEB6520309'
 CONST GUID '5553DE6A-23C5-4B12-8A98-358CF08F6E59'
 CONST Name 'MissingInfo'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Информация об отсутствующем документе.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EEB652030B // obj_name
 ME_45EEB652030C // blocks_info
 )
 ; // Attributes
 : Operations
   Seq: ( ME_45EEB652030A // is_one_block
 ME_46110DBE01ED // make
 )
 ; // Operations
 CONST "single impl" false
 CONST extprop:pas:TypeName 'IMissingInfo'
 CONST extprop:rc:SelfName 'MissingInfo'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_45EEB6520309 MissingInfo

: ME_45EEB6520306
 CONST UID '45EEB6520306'
 CONST Name 'InvalidParaId'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Неверный идентификатор параграфа' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 CONST "force usage" true

ref; // ME_45EEB6520306 InvalidParaId

FORWARD ME_45EEB6520314

: ME_45EEB6520315
 CONST UID '45EEB6520315'
 CONST Name 'TMWT_RED'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520314 // TimeMachineWarningType
 ;

ref; // ME_45EEB6520315 TMWT_RED

: ME_45EEB6520316
 CONST UID '45EEB6520316'
 CONST Name 'TMWT_YELLOW'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520314 // TimeMachineWarningType
 ;

ref; // ME_45EEB6520316 TMWT_YELLOW

: ME_45EEB6520314
 CONST UID '45EEB6520314'
 CONST Name 'TimeMachineWarningType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EEB6520315 // TMWT_RED
 ME_45EEB6520316 // TMWT_YELLOW
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TTimeMachineWarningType'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_45EEB6520314 TimeMachineWarningType

FORWARD ME_45EEB652030F

: ME_45EEB6520310
 CONST UID '45EEB6520310'
 CONST Name 'POSITION_TYPE_MASK'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB652030F // PositionInDocument
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;
 CONST Value 2147483648
 : ValueType WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 2147483648

ref; // ME_45EEB6520310 POSITION_TYPE_MASK

: ME_45EEB6520311
 CONST UID '45EEB6520311'
 CONST Name 'POSITION_TYPE_SUB_ID'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB652030F // PositionInDocument
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;
 CONST Value 0
 : ValueType WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 0

ref; // ME_45EEB6520311 POSITION_TYPE_SUB_ID

: ME_45EEB6520312
 CONST UID '45EEB6520312'
 CONST Name 'POSITION_TYPE_PARA_ID'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB652030F // PositionInDocument
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;
 CONST Value 2147483648
 : ValueType WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 2147483648

ref; // ME_45EEB6520312 POSITION_TYPE_PARA_ID

: ME_45EEB652030F
 CONST UID '45EEB652030F'
 CONST Name 'PositionInDocument'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EEB6520310 // POSITION_TYPE_MASK
 ME_45EEB6520311 // POSITION_TYPE_SUB_ID
 ME_45EEB6520312 // POSITION_TYPE_PARA_ID
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_45EEB652030F PositionInDocument

FORWARD ME_45EEB652031D

: ME_45EEB652031E
 CONST UID '45EEB652031E'
 CONST Name 'warning'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent ME_45EEB652031D // TimeMachineWarning
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_45EEB652031E warning

: ME_45EEC3F50134
 CONST UID '45EEC3F50134'
 CONST Name 'type'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB652031D // TimeMachineWarning
 ;
 : Target ME_45EEB6520314 // TimeMachineWarningType
 ;

ref; // ME_45EEC3F50134 type

: ME_45EEB652031D
 CONST UID '45EEB652031D'
 CONST Name 'TimeMachineWarning'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EEB652031E // warning
 ME_45EEC3F50134 // type
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TTimeMachineWarning'

ref; // ME_45EEB652031D TimeMachineWarning

: ME_45EEB6520321
 CONST UID '45EEB6520321'
 CONST Name 'InvalidTopicId'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Возвращается при попытке выполнить операцию с внутренним идентификатором документа, несуществующим в базе.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 CONST "force usage" true

ref; // ME_45EEB6520321 InvalidTopicId

FORWARD ME_45EEB6520323

: ME_45EEB6520324
 CONST UID '45EEB6520324'
 CONST Name 'PT_SUB'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520323 // PositionType
 ;

ref; // ME_45EEB6520324 PT_SUB

: ME_45EEB6520325
 CONST UID '45EEB6520325'
 CONST Name 'PT_PARA'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520323 // PositionType
 ;

ref; // ME_45EEB6520325 PT_PARA

: ME_45EEB6520326
 CONST UID '45EEB6520326'
 CONST Name 'PT_BOOKMARK'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520323 // PositionType
 ;

ref; // ME_45EEB6520326 PT_BOOKMARK

: ME_45EEB6520323
 CONST UID '45EEB6520323'
 CONST Name 'PositionType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EEB6520324 // PT_SUB
 ME_45EEB6520325 // PT_PARA
 ME_45EEB6520326 // PT_BOOKMARK
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TPositionType'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_45EEB6520323 PositionType

FORWARD ME_45EEB65202D4

: ME_45EEB65202D5
 CONST UID '45EEB65202D5'
 CONST Name 'type'
 CONST Class class_Attribute
 %SUMMARY 'Флаг определяющий значение поля point. Если true то point указывает на параграф, в противном случае на саб или блок.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202D4 // Position
 ;
 : Target ME_45EEB6520323 // PositionType
 ;

ref; // ME_45EEB65202D5 type

: ME_45EEB65202D6
 CONST UID '45EEB65202D6'
 CONST Name 'point'
 CONST Class class_Attribute
 %SUMMARY 'Точка входа.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202D4 // Position
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_45EEB65202D6 point

: ME_45EEB65202D4
 CONST UID '45EEB65202D4'
 CONST Name 'Position'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Точка входа в документ.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EEB65202D5 // type
 ME_45EEB65202D6 // point
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TPosition'

ref; // ME_45EEB65202D4 Position

FORWARD ME_45EEB65202EF

: ME_45EEB65202EB
 CONST UID '45EEB65202EB'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202EF // PositionList
 ;
 : Target ME_45EEB65202D4 // Position
 ;

ref; // ME_45EEB65202EB 

: ME_45EEB65202EF
 CONST UID '45EEB65202EF'
 CONST Name 'PositionList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Список меток или блоков в документе.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EEB65202EB // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'IPositionList'

ref; // ME_45EEB65202EF PositionList

FORWARD ME_45EEB65202CD

: ME_460B8E6503B0
 CONST UID '460B8E6503B0'
 CONST Name 'pid'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202CD // Topic
 ;
 : Target WL 'ME_456EA676037A' '456EA56002BF.pas.ms.script' // PId
 ;

ref; // ME_460B8E6503B0 pid

: ME_460B8E7F0100
 CONST UID '460B8E7F0100'
 CONST Name 'position'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB65202CD // Topic
 ;
 : Target ME_45EEB65202D4 // Position
 ;

ref; // ME_460B8E7F0100 position

: ME_45EEB65202CD
 CONST UID '45EEB65202CD'
 CONST Name 'Topic'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Внутренние идентификаторы элемента списка документов.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_460B8E6503B0 // pid
 ME_460B8E7F0100 // position
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TTopic'

ref; // ME_45EEB65202CD Topic

: ME_45EEB65202AA
 CONST UID '45EEB65202AA'
 CONST Name 'ParaId'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Идентификатор параграфа (тот самы волшебный, который должен прикрутить Влад)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 )
 ; // Inherits
 CONST extprop:pas:TypeName 'TParaId'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_45EEB65202AA ParaId

FORWARD ME_45EEB6520208

: ME_45EEB6520209
 CONST UID '45EEB6520209'
 CONST Name 'DT_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520208 // DocumentType
 ;

ref; // ME_45EEB6520209 DT_DOCUMENT

: ME_45EEB652020A
 CONST UID '45EEB652020A'
 CONST Name 'DT_EXPLANATORY'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520208 // DocumentType
 ;

ref; // ME_45EEB652020A DT_EXPLANATORY

: ME_45EEB652020B
 CONST UID '45EEB652020B'
 CONST Name 'DT_AUTO_REFERAT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520208 // DocumentType
 ;

ref; // ME_45EEB652020B DT_AUTO_REFERAT

: ME_45EEB652020C
 CONST UID '45EEB652020C'
 CONST Name 'DT_BOOK'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520208 // DocumentType
 ;

ref; // ME_45EEB652020C DT_BOOK

: ME_47BD42A0038B
 CONST UID '47BD42A0038B'
 CONST Name 'DT_TIP'
 CONST Class class_Attribute
 %SUMMARY 'Совет дня' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520208 // DocumentType
 ;

ref; // ME_47BD42A0038B DT_TIP

: ME_47CFEFE20042
 CONST UID '47CFEFE20042'
 CONST Name 'DT_MEDICAL_EXPLANATORY'
 CONST Class class_Attribute
 %SUMMARY 'элемент словаря мед. терминов' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520208 // DocumentType
 ;

ref; // ME_47CFEFE20042 DT_MEDICAL_EXPLANATORY

: ME_47DFE2FE01C1
 CONST UID '47DFE2FE01C1'
 CONST Name 'DT_MEDICAL_FIRM'
 CONST Class class_Attribute
 %SUMMARY 'документ с описанием фирмы из инфарм' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520208 // DocumentType
 ;

ref; // ME_47DFE2FE01C1 DT_MEDICAL_FIRM

: ME_47ED1CDA01BB
 CONST UID '47ED1CDA01BB'
 CONST Name 'DT_MEDICAL_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520208 // DocumentType
 ;

ref; // ME_47ED1CDA01BB DT_MEDICAL_DOCUMENT

: ME_4857BD8C0319
 CONST UID '4857BD8C0319'
 CONST Name 'DT_FLASH'
 CONST Class class_Attribute
 %SUMMARY 'Документ-флеш' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520208 // DocumentType
 ;

ref; // ME_4857BD8C0319 DT_FLASH

: ME_4FE860A6037D
 CONST UID '4FE860A6037D'
 CONST Name 'DT_ACTUAL_ANALYTICS'
 CONST Class class_Attribute
 %SUMMARY 'ААК' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520208 // DocumentType
 ;

ref; // ME_4FE860A6037D DT_ACTUAL_ANALYTICS

: ME_4FE860C70113
 CONST UID '4FE860C70113'
 CONST Name 'DT_ACTUAL_ANALYTICS_CONTENTS'
 CONST Class class_Attribute
 %SUMMARY 'ААК-Содержание' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520208 // DocumentType
 ;

ref; // ME_4FE860C70113 DT_ACTUAL_ANALYTICS_CONTENTS

: ME_522838A80237
 CONST UID '522838A80237'
 CONST Name 'DT_REF'
 CONST Class class_Attribute
 %SUMMARY 'Топик с www ссылками' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520208 // DocumentType
 ;

ref; // ME_522838A80237 DT_REF

: ME_45EEB6520208
 CONST UID '45EEB6520208'
 CONST Name 'DocumentType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 %SUMMARY 'тип документа' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EEB6520209 // DT_DOCUMENT
 ME_45EEB652020A // DT_EXPLANATORY
 ME_45EEB652020B // DT_AUTO_REFERAT
 ME_45EEB652020C // DT_BOOK
 ME_47BD42A0038B // DT_TIP
 ME_47CFEFE20042 // DT_MEDICAL_EXPLANATORY
 ME_47DFE2FE01C1 // DT_MEDICAL_FIRM
 ME_47ED1CDA01BB // DT_MEDICAL_DOCUMENT
 ME_4857BD8C0319 // DT_FLASH
 ME_4FE860A6037D // DT_ACTUAL_ANALYTICS
 ME_4FE860C70113 // DT_ACTUAL_ANALYTICS_CONTENTS
 ME_522838A80237 // DT_REF
 )
 ; // Attributes
 CONST "force usage" true
 CONST extprop:pas:TypeName 'TDocumentType'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_45EEB6520208 DocumentType

: ME_45EEB6520328
 CONST UID '45EEB6520328'
 CONST Name 'FolderLinkNotFound'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Не найдена ссылка на папочный элемент (возможно он был удален)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 CONST "force usage" true

ref; // ME_45EEB6520328 FolderLinkNotFound

: ME_45EED84C01FD
 CONST UID '45EED84C01FD'
 CONST Name 'RedactionID'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Идентификатор редакции объекта (сейчас будет совпадать с ObjectId).' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( WL 'ME_3DBFFD7002C2' '3DBFDB23006E.pas.ms.script' // long
 )
 ; // Inherits
 CONST extprop:pas:TypeName 'TRedactionID'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_45EED84C01FD RedactionID

FORWARD ME_45EED87E0383

: ME_4610C17001F8
 CONST UID '4610C17001F8'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED87E0383 // ActiveIntervalList
 ;
 : Target WL 'ME_456EA6DA0280' '456EA56002BF.pas.ms.script' // DateInterval
 ;

ref; // ME_4610C17001F8 

: ME_45EED87E0383
 CONST UID '45EED87E0383'
 CONST Name 'ActiveIntervalList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4610C17001F8 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'IActiveIntervalList'

ref; // ME_45EED87E0383 ActiveIntervalList

FORWARD ME_45EED8A401CD

: ME_45EED8A401CE
 CONST UID '45EED8A401CE'
 CONST Name 'warning'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent ME_45EED8A401CD // NotSureInfo
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_45EED8A401CE warning

: ME_45EED95B0094
 CONST UID '45EED95B0094'
 CONST Name 'interval'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED8A401CD // NotSureInfo
 ;
 : Target WL 'ME_456EA6DA0280' '456EA56002BF.pas.ms.script' // DateInterval
 ;

ref; // ME_45EED95B0094 interval

: ME_45EED8A401CD
 CONST UID '45EED8A401CD'
 CONST Name 'NotSureInfo'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EED8A401CE // warning
 ME_45EED95B0094 // interval
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TNotSureInfo'

ref; // ME_45EED8A401CD NotSureInfo

FORWARD ME_45EED88901BE

: ME_45EED9500372
 CONST UID '45EED9500372'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED88901BE // NotSureIntervalList
 ;
 : Target ME_45EED8A401CD // NotSureInfo
 ;

ref; // ME_45EED9500372 

: ME_45EED88901BE
 CONST UID '45EED88901BE'
 CONST Name 'NotSureIntervalList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EED9500372 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'INotSureIntervalList'

ref; // ME_45EED88901BE NotSureIntervalList

FORWARD ME_45EED8C20066

: ME_45EED8C20067
 CONST UID '45EED8C20067'
 CONST Name 'RT_ACTUAL'
 CONST Class class_Attribute
 %SUMMARY 'Документ' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED8C20066 // RedactionType
 ;

ref; // ME_45EED8C20067 RT_ACTUAL

: ME_45EED8C20068
 CONST UID '45EED8C20068'
 CONST Name 'RT_ACTUAL_ABOLISHED'
 CONST Class class_Attribute
 %SUMMARY 'документ со статусом DS_ABOLISHED (утратил силу)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED8C20066 // RedactionType
 ;

ref; // ME_45EED8C20068 RT_ACTUAL_ABOLISHED

: ME_45EED8C20069
 CONST UID '45EED8C20069'
 CONST Name 'RT_ACTUAL_PREACTIVE'
 CONST Class class_Attribute
 %SUMMARY 'документ со статусом DS_PREACTIVE (не вступил в силу)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED8C20066 // RedactionType
 ;

ref; // ME_45EED8C20069 RT_ACTUAL_PREACTIVE

: ME_45EED8C2006A
 CONST UID '45EED8C2006A'
 CONST Name 'RT_OLD'
 CONST Class class_Attribute
 %SUMMARY 'редакция в цепочке редакций до актуальной, у которой нет ни DS_ABOLISHED, ни DS_PREACTIVE' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED8C20066 // RedactionType
 ;

ref; // ME_45EED8C2006A RT_OLD

: ME_45EED8C2006B
 CONST UID '45EED8C2006B'
 CONST Name 'RT_NEW'
 CONST Class class_Attribute
 %SUMMARY 'редакция в цепочке редакций после актуальной, у которой нет ни DS_ABOLISHED, ни DS_PREACTIVE' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED8C20066 // RedactionType
 ;

ref; // ME_45EED8C2006B RT_NEW

: ME_45EED8C2006C
 CONST UID '45EED8C2006C'
 CONST Name 'RT_NEW_ABOLISHED'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED8C20066 // RedactionType
 ;

ref; // ME_45EED8C2006C RT_NEW_ABOLISHED

: ME_45EED8C2006D
 CONST UID '45EED8C2006D'
 CONST Name 'RT_NEW_PREACTIVE'
 CONST Class class_Attribute
 %SUMMARY 'редакция со статусом DS_PREACTIVE (не вступил в силу)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED8C20066 // RedactionType
 ;

ref; // ME_45EED8C2006D RT_NEW_PREACTIVE

: ME_45EED8C20066
 CONST UID '45EED8C20066'
 CONST Name 'RedactionType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Тип редакции объекта.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EED8C20067 // RT_ACTUAL
 ME_45EED8C20068 // RT_ACTUAL_ABOLISHED
 ME_45EED8C20069 // RT_ACTUAL_PREACTIVE
 ME_45EED8C2006A // RT_OLD
 ME_45EED8C2006B // RT_NEW
 ME_45EED8C2006C // RT_NEW_ABOLISHED
 ME_45EED8C2006D // RT_NEW_PREACTIVE
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TRedactionType'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_45EED8C20066 RedactionType

FORWARD ME_51FB7465014E

: ME_51FB747D0279
 CONST UID '51FB747D0279'
 CONST Name 'display_name'
 CONST Class class_Attribute
 %SUMMARY 'изменяющий документ (то что показывается)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent ME_51FB7465014E // RedactionSourceDocumentInfo
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_51FB747D0279 display_name

: ME_51FB761201F4
 CONST UID '51FB761201F4'
 CONST Name 'doc_topic'
 CONST Class class_Attribute
 %SUMMARY 'топик для перехода в изменяющий документ' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_51FB7465014E // RedactionSourceDocumentInfo
 ;
 : Target ME_45EEB65202CD // Topic
 ;

ref; // ME_51FB761201F4 doc_topic

: ME_51FB7465014E
 CONST UID '51FB7465014E'
 CONST Name 'RedactionSourceDocumentInfo'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_51FB747D0279 // display_name
 ME_51FB761201F4 // doc_topic
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TRedactionSourceDocumentInfo'

ref; // ME_51FB7465014E RedactionSourceDocumentInfo

FORWARD ME_51FB7643002D

: ME_51FB76520156
 CONST UID '51FB76520156'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_51FB7643002D // RedactionSourceDocumentInfoList
 ;
 : Target ME_51FB7465014E // RedactionSourceDocumentInfo
 ;

ref; // ME_51FB76520156 

: ME_51FB7643002D
 CONST UID '51FB7643002D'
 CONST Name 'RedactionSourceDocumentInfoList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_51FB76520156 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'IRedactionSourceDocumentInfoList'

ref; // ME_51FB7643002D RedactionSourceDocumentInfoList

: ME_45EED9780391
 CONST UID '45EED9780391'
 CONST Name 'RedactionNotFound'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Возвращается в случае попытки получения несуществующей редакции объекта.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 CONST "force usage" true

ref; // ME_45EED9780391 RedactionNotFound

: ME_45EEDAD60237
 CONST UID '45EEDAD60237'
 CONST Name 'NotAllowedInTrialMode'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 CONST "force usage" true

ref; // ME_45EEDAD60237 NotAllowedInTrialMode

FORWARD ME_47AB33FD01FF

: ME_47AB341C03C0
 CONST UID '47AB341C03C0'
 CONST Name 'LK_INTERNAL_INVALID'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47AB33FD01FF // LinkKind
 ;

ref; // ME_47AB341C03C0 LK_INTERNAL_INVALID

: ME_47AB34800330
 CONST UID '47AB34800330'
 CONST Name 'LK_REGULAR'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47AB33FD01FF // LinkKind
 ;

ref; // ME_47AB34800330 LK_REGULAR

: ME_47AB3583036F
 CONST UID '47AB3583036F'
 CONST Name 'LK_EXTERNAL'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47AB33FD01FF // LinkKind
 ;

ref; // ME_47AB3583036F LK_EXTERNAL

: ME_480492140391
 CONST UID '480492140391'
 CONST Name 'LK_ABOLISHED'
 CONST Class class_Attribute
 %SUMMARY 'Ссылка на утративший силу документ' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47AB33FD01FF // LinkKind
 ;

ref; // ME_480492140391 LK_ABOLISHED

: ME_4804923102A2
 CONST UID '4804923102A2'
 CONST Name 'LK_PREACTIVE'
 CONST Class class_Attribute
 %SUMMARY 'Ссылка на не вступивший в силу документ' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47AB33FD01FF // LinkKind
 ;

ref; // ME_4804923102A2 LK_PREACTIVE

: ME_487DABE002AA
 CONST UID '487DABE002AA'
 CONST Name 'LK_ENO'
 CONST Class class_Attribute
 %SUMMARY 'Ссылка на ЭО' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47AB33FD01FF // LinkKind
 ;

ref; // ME_487DABE002AA LK_ENO

: ME_494A40C803E7
 CONST UID '494A40C803E7'
 CONST Name 'LK_EDITION'
 CONST Class class_Attribute
 %SUMMARY 'Редакция документа' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47AB33FD01FF // LinkKind
 ;

ref; // ME_494A40C803E7 LK_EDITION

: ME_4E0D8B4601A8
 CONST UID '4E0D8B4601A8'
 CONST Name 'LK_SCRIPT'
 CONST Class class_Attribute
 %SUMMARY 'ссылка на скрипт' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47AB33FD01FF // LinkKind
 ;

ref; // ME_4E0D8B4601A8 LK_SCRIPT

: ME_47AB33FD01FF
 CONST UID '47AB33FD01FF'
 CONST Name 'LinkKind'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Вид хинта' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_47AB341C03C0 // LK_INTERNAL_INVALID
 ME_47AB34800330 // LK_REGULAR
 ME_47AB3583036F // LK_EXTERNAL
 ME_480492140391 // LK_ABOLISHED
 ME_4804923102A2 // LK_PREACTIVE
 ME_487DABE002AA // LK_ENO
 ME_494A40C803E7 // LK_EDITION
 ME_4E0D8B4601A8 // LK_SCRIPT
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TLinkKind'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_47AB33FD01FF LinkKind

: ME_45EED97B0372
 CONST UID '45EED97B0372'
 CONST Name 'InvalidDate'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 CONST "force usage" true

ref; // ME_45EED97B0372 InvalidDate

: ME_45EEDA9A00B1
 CONST UID '45EEDA9A00B1'
 CONST Name 'ExplanationDictionaryNotInstalled'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Толковый словарь не установлен в системе.'#13#10'Возвращается в случае вызова операции "поиск толкования" и отсутствии в системе толкового словаря.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 CONST "force usage" true

ref; // ME_45EEDA9A00B1 ExplanationDictionaryNotInstalled

FORWARD ME_47AB301C01DC

: ME_47AB30380383
 CONST UID '47AB30380383'
 CONST Name 'kind'
 CONST Class class_Attribute
 %SUMMARY 'вид хинта' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47AB301C01DC // LinkInfo
 ;
 : Target ME_47AB33FD01FF // LinkKind
 ;

ref; // ME_47AB30380383 kind

: ME_47AB334F0259
 CONST UID '47AB334F0259'
 CONST Name 'hint'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent ME_47AB301C01DC // LinkInfo
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_47AB334F0259 hint

: ME_47AB301C01DC
 CONST UID '47AB301C01DC'
 CONST Name 'LinkInfo'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_47AB30380383 // kind
 ME_47AB334F0259 // hint
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TLinkInfo'

ref; // ME_47AB301C01DC LinkInfo

FORWARD ME_47ED1AC7036F

: ME_47ED1AE5039C
 CONST UID '47ED1AE5039C'
 CONST Name 'FK_DOCUMENT_MASTER'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_47ED1AE5039C FK_DOCUMENT_MASTER

: ME_47ED1AEF01D8
 CONST UID '47ED1AEF01D8'
 CONST Name 'FK_DOCUMENT_DELEGATE'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_47ED1AEF01D8 FK_DOCUMENT_DELEGATE

: ME_47ED1B890245
 CONST UID '47ED1B890245'
 CONST Name 'FK_DICT_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_47ED1B890245 FK_DICT_DOCUMENT

: ME_47ED1BAB0366
 CONST UID '47ED1BAB0366'
 CONST Name 'FK_PHARM_DICT_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_47ED1BAB0366 FK_PHARM_DICT_DOCUMENT

: ME_47ED1BDE03A0
 CONST UID '47ED1BDE03A0'
 CONST Name 'FK_PHARM_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_47ED1BDE03A0 FK_PHARM_DOCUMENT

: ME_47ED1C1A02C4
 CONST UID '47ED1C1A02C4'
 CONST Name 'FK_PHARM_FIRM_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_47ED1C1A02C4 FK_PHARM_FIRM_DOCUMENT

: ME_47ED1C3302BB
 CONST UID '47ED1C3302BB'
 CONST Name 'FK_TIP_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_47ED1C3302BB FK_TIP_DOCUMENT

: ME_47ED1C4C03BB
 CONST UID '47ED1C4C03BB'
 CONST Name 'FK_TRANSLATED_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_47ED1C4C03BB FK_TRANSLATED_DOCUMENT

: ME_47ED1C6C02AE
 CONST UID '47ED1C6C02AE'
 CONST Name 'FK_SIMPLE_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_47ED1C6C02AE FK_SIMPLE_DOCUMENT

: ME_4857BF890072
 CONST UID '4857BF890072'
 CONST Name 'FK_FLASH_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_4857BF890072 FK_FLASH_DOCUMENT

: ME_4CED4A9B0255
 CONST UID '4CED4A9B0255'
 CONST Name 'FK_AUTOREFERAT_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_4CED4A9B0255 FK_AUTOREFERAT_DOCUMENT

: ME_4FE86104014A
 CONST UID '4FE86104014A'
 CONST Name 'FK_ACTUAL_ANALYTICS_CONTENTS_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_4FE86104014A FK_ACTUAL_ANALYTICS_CONTENTS_DOCUMENT

: ME_4FE8611E0388
 CONST UID '4FE8611E0388'
 CONST Name 'FK_ACTUAL_ANALYTICS_DOCUMENT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_4FE8611E0388 FK_ACTUAL_ANALYTICS_DOCUMENT

: ME_5227262802DA
 CONST UID '5227262802DA'
 CONST Name 'FK_REF'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_5227262802DA FK_REF

: ME_53E9ECF700FF
 CONST UID '53E9ECF700FF'
 CONST Name 'FK_BOOK'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_53E9ECF700FF FK_BOOK

: ME_47ED1AC7036F
 CONST UID '47ED1AC7036F'
 CONST Name 'FactoryKey'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_47ED1AE5039C // FK_DOCUMENT_MASTER
 ME_47ED1AEF01D8 // FK_DOCUMENT_DELEGATE
 ME_47ED1B890245 // FK_DICT_DOCUMENT
 ME_47ED1BAB0366 // FK_PHARM_DICT_DOCUMENT
 ME_47ED1BDE03A0 // FK_PHARM_DOCUMENT
 ME_47ED1C1A02C4 // FK_PHARM_FIRM_DOCUMENT
 ME_47ED1C3302BB // FK_TIP_DOCUMENT
 ME_47ED1C4C03BB // FK_TRANSLATED_DOCUMENT
 ME_47ED1C6C02AE // FK_SIMPLE_DOCUMENT
 ME_4857BF890072 // FK_FLASH_DOCUMENT
 ME_4CED4A9B0255 // FK_AUTOREFERAT_DOCUMENT
 ME_4FE86104014A // FK_ACTUAL_ANALYTICS_CONTENTS_DOCUMENT
 ME_4FE8611E0388 // FK_ACTUAL_ANALYTICS_DOCUMENT
 ME_5227262802DA // FK_REF
 ME_53E9ECF700FF // FK_BOOK
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TFactoryKey'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_47ED1AC7036F FactoryKey

: ME_4ADF1C2C00B8
 CONST UID '4ADF1C2C00B8'
 CONST Name 'ParaNum'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 %SUMMARY 'список измененных параграфов в порядке выдачи машиной сравнения' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( WL 'ME_3DBFFD7002C2' '3DBFDB23006E.pas.ms.script' // long
 )
 ; // Inherits
 CONST extprop:pas:TypeName 'TParaNum'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4ADF1C2C00B8 ParaNum

FORWARD ME_4B4EE046030D

: ME_4B4EE0E000B0
 CONST UID '4B4EE0E000B0'
 CONST Name 'has_next'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4B4EE046030D // DiffIterator
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4B4EE0E000B0 has_next

: ME_4B4EE1060152
 CONST UID '4B4EE1060152'
 CONST Name 'has_prev'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4B4EE046030D // DiffIterator
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4B4EE1060152 has_prev

: ME_4B4EE1330087
 CONST UID '4B4EE1330087'
 CONST Name 'next'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4B4EE046030D // DiffIterator
 ;
 : Target ME_4ADF1C2C00B8 // ParaNum
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018E' '456EA56002BF.pas.ms.script' // CanNotFindData
 )
 ; // CanRaise

ref; // ME_4B4EE1330087 next

: ME_4B601C0800C3
 CONST UID '4B601C0800C3'
 CONST Name 'acquire_next'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4B4EE046030D // DiffIterator
 ;
 : Target ME_4ADF1C2C00B8 // ParaNum
 ;

ref; // ME_4B601C0800C3 acquire_next

: ME_4B4EE156033B
 CONST UID '4B4EE156033B'
 CONST Name 'prev'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4B4EE046030D // DiffIterator
 ;
 : Target ME_4ADF1C2C00B8 // ParaNum
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018E' '456EA56002BF.pas.ms.script' // CanNotFindData
 )
 ; // CanRaise

ref; // ME_4B4EE156033B prev

: ME_4B62D7640025
 CONST UID '4B62D7640025'
 CONST Name 'acquire_prev'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4B4EE046030D // DiffIterator
 ;
 : Target ME_4ADF1C2C00B8 // ParaNum
 ;

ref; // ME_4B62D7640025 acquire_prev

: ME_4B4EE3110058
 CONST Name 'para'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4ADF1C2C00B8 // ParaNum
 ;

ref; // ME_4B4EE3110058 para

: ME_4B4EE16E00EC
 CONST UID '4B4EE16E00EC'
 CONST Name 'move_to'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4B4EE046030D // DiffIterator
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018E' '456EA56002BF.pas.ms.script' // CanNotFindData
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4B4EE3110058 // para
 )
 ; // Parameters

ref; // ME_4B4EE16E00EC move_to

: ME_4CC962A203D9
 CONST Name 'diff_data'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_4CC962A203D9 diff_data

: ME_4CC96279013F
 CONST UID '4CC96279013F'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4B4EE046030D // DiffIterator
 ;
 : Parameters
   Seq: ( ME_4CC962A203D9 // diff_data
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false

ref; // ME_4CC96279013F make

: ME_4B4EE046030D
 CONST UID '4B4EE046030D'
 CONST GUID 'A9AA18D9-F87F-4A47-988B-789AA069EEE0'
 CONST Name 'DiffIterator'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 %SUMMARY '[$175966492]'#13#10'*  Операции "Следующее изменение" и "Предыдущее изменение" должны работать относительно позиции курсора (если он на экране) или относительно верхнего края документа в фокусе.'#13#10'* Операция "Следующее изменение" должна работать только до конца документа (не переходя в начало по циклу)'#13#10'* Операция "Предыдущее изменение" должна работать только до начала документа (не переходя в конец по циклу)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Operations
   Seq: ( ME_4B4EE0E000B0 // has_next
 ME_4B4EE1060152 // has_prev
 ME_4B4EE1330087 // next
 ME_4B601C0800C3 // acquire_next
 ME_4B4EE156033B // prev
 ME_4B62D7640025 // acquire_prev
 ME_4B4EE16E00EC // move_to
 ME_4CC96279013F // make
 )
 ; // Operations
 CONST "single impl" false
 CONST extprop:pas:TypeName 'IDiffIterator'
 CONST extprop:rc:SelfName 'DiffIterator'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4B4EE046030D DiffIterator

: ME_4C5AA63D01ED
 CONST UID '4C5AA63D01ED'
 CONST Name 'LayerID'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 )
 ; // Inherits
 CONST extprop:pas:TypeName 'TLayerID'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4C5AA63D01ED LayerID

: ME_4A49F79C011A
 CONST UID '4A49F79C011A'
 CONST Name 'InvalidObjectClass'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 CONST "force usage" true

ref; // ME_4A49F79C011A InvalidObjectClass

: ME_4A6D655A02A8
 CONST UID '4A6D655A02A8'
 CONST Name 'NoPrevRedaction'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 CONST "force usage" true

ref; // ME_4A6D655A02A8 NoPrevRedaction

: ME_4C5AA67E002B
 CONST UID '4C5AA67E002B'
 CONST Name 'ChildID'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 )
 ; // Inherits
 CONST "force usage" true
 CONST extprop:pas:TypeName 'TChildID'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4C5AA67E002B ChildID

FORWARD ME_4C5AA60F039B

: ME_4C5AA6B10243
 CONST UID '4C5AA6B10243'
 CONST Name 'layer'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4C5AA60F039B // EntryPoint
 ;
 : Target ME_4C5AA63D01ED // LayerID
 ;

ref; // ME_4C5AA6B10243 layer

: ME_4C5AA6C90241
 CONST UID '4C5AA6C90241'
 CONST Name 'child'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4C5AA60F039B // EntryPoint
 ;
 : Target ME_4C5AA67E002B // ChildID
 ;

ref; // ME_4C5AA6C90241 child

: ME_4C5AA60F039B
 CONST UID '4C5AA60F039B'
 CONST Name 'EntryPoint'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4C5AA6B10243 // layer
 ME_4C5AA6C90241 // child
 )
 ; // Attributes
 CONST "need UC" true
 CONST extprop:pas:TypeName 'TEntryPoint'

ref; // ME_4C5AA60F039B EntryPoint

FORWARD ME_4C5AA77200CE

: ME_4C5AA7C3009A
 CONST UID '4C5AA7C3009A'
 CONST Name 'path'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4C5AA77200CE // Context
 ;
 : Target WL 'ME_45EEC8680109' '457450470167.pas.ms.script' // NodeIndexPath
 ;

ref; // ME_4C5AA7C3009A path

: ME_4C5AA800005A
 CONST UID '4C5AA800005A'
 CONST Name 'start'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4C5AA77200CE // Context
 ;
 : Target WL 'ME_3DBFFD7002C2' '3DBFDB23006E.pas.ms.script' // long
 ;

ref; // ME_4C5AA800005A start

: ME_4C5AA809022C
 CONST UID '4C5AA809022C'
 CONST Name 'finish'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4C5AA77200CE // Context
 ;
 : Target WL 'ME_3DBFFD7002C2' '3DBFDB23006E.pas.ms.script' // long
 ;

ref; // ME_4C5AA809022C finish

: ME_4C5AA77200CE
 CONST UID '4C5AA77200CE'
 CONST Name 'Context'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4C5AA7C3009A // path
 ME_4C5AA800005A // start
 ME_4C5AA809022C // finish
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TContext'

ref; // ME_4C5AA77200CE Context

: ME_4C5AB3040216
 CONST UID '4C5AB3040216'
 CONST Name 'EVDType'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( WL 'ME_43786B35001F' '3DBFDB23006E.pas.ms.script' // unsigned char
 )
 ; // Inherits
 CONST extprop:pas:TypeName 'TEVDType'

ref; // ME_4C5AB3040216 EVDType

: ME_4C5AB32B03A5
 CONST UID '4C5AB32B03A5'
 CONST Name 'ExternalID'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( WL 'ME_3DBFFD7002C2' '3DBFDB23006E.pas.ms.script' // long
 )
 ; // Inherits
 CONST extprop:pas:TypeName 'TExternalID'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4C5AB32B03A5 ExternalID

: ME_4C5AB363008D
 CONST UID '4C5AB363008D'
 CONST Name 'EVDStream'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( WL 'ME_4423FB5903D8' '4423F94903C8.pas.ms.script' // Stream
 )
 ; // Inherits
 CONST extprop:pas:TypeName 'TEVDStream'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4C5AB363008D EVDStream

: ME_4C5ABA9401A6
 CONST UID '4C5ABA9401A6'
 CONST Name 'InvalidEntryPoint'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;

ref; // ME_4C5ABA9401A6 InvalidEntryPoint

: ME_4C5ABAA803CA
 CONST UID '4C5ABAA803CA'
 CONST Name 'InvalidLayerID'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;

ref; // ME_4C5ABAA803CA InvalidLayerID

FORWARD ME_4C5ABDE10145

: ME_4CC183CF01BA
 CONST UID '4CC183CF01BA'
 CONST Name 'para_id'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4C5ABDE10145 // Bookmark2
 ;
 : Target ME_4C5AB32B03A5 // ExternalID
 ;

ref; // ME_4CC183CF01BA para_id

: ME_4D396B0F0134
 CONST UID '4D396B0F0134'
 CONST Name 'eid'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4C5ABDE10145 // Bookmark2
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4D396B0F0134 eid

: ME_4CC18407009E
 CONST UID '4CC18407009E'
 CONST Name 'name'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent ME_4C5ABDE10145 // Bookmark2
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_4CC18407009E name

: ME_4C5ABDE10145
 CONST UID '4C5ABDE10145'
 CONST Name 'Bookmark2'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4CC183CF01BA // para_id
 ME_4D396B0F0134 // eid
 ME_4CC18407009E // name
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TBookmark2'

ref; // ME_4C5ABDE10145 Bookmark2

FORWARD ME_4C5ABD7603D1

: ME_4C5ABE250239
 CONST UID '4C5ABE250239'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4C5ABD7603D1 // BookmarkList
 ;
 : Target ME_4C5ABDE10145 // Bookmark2
 ;

ref; // ME_4C5ABE250239 

: ME_4C5ABD7603D1
 CONST UID '4C5ABD7603D1'
 CONST Name 'BookmarkList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4C5ABE250239 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'IBookmarkList'

ref; // ME_4C5ABD7603D1 BookmarkList

FORWARD ME_4D39697600E4

: ME_4C5AA78601F5
 CONST UID '4C5AA78601F5'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4D39697600E4 // FragmentList
 ;
 : Target ME_4C5AA77200CE // Context
 ;

ref; // ME_4C5AA78601F5 

: ME_4D39697600E4
 CONST UID '4D39697600E4'
 CONST Name 'FragmentList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4C5AA78601F5 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'IFragmentList'

ref; // ME_4D39697600E4 FragmentList

FORWARD ME_4C9B41F302A7

: ME_4C9B42440141
 CONST UID '4C9B42440141'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4C9B41F302A7 // SubList
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4C9B42440141 

: ME_4C9B41F302A7
 CONST UID '4C9B41F302A7'
 CONST Name 'SubList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4C9B42440141 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'ISubList'

ref; // ME_4C9B41F302A7 SubList

FORWARD ME_4CA32AC30364

: ME_4CA32AD801DC
 CONST UID '4CA32AD801DC'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4CA32AC30364 // ContextList
 ;
 : Target ME_4D39697600E4 // FragmentList
 ;

ref; // ME_4CA32AD801DC 

: ME_4CA32AC30364
 CONST UID '4CA32AC30364'
 CONST Name 'ContextList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4CA32AD801DC // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'IContextList'

ref; // ME_4CA32AC30364 ContextList

FORWARD ME_4C8E37620115

: ME_4C8E37750112
 CONST UID '4C8E37750112'
 CONST Name 'list'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_4C8E37620115 // FoundContext
 ;
 : Target ME_4CA32AC30364 // ContextList
 ;
 CONST "pm" false

ref; // ME_4C8E37750112 list

: ME_4C8F319A0033
 CONST Name 'list'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_4C8F319A0033 list

: ME_4C8F31830221
 CONST UID '4C8F31830221'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8E37620115 // FoundContext
 ;
 : Parameters
   Seq: ( ME_4C8F319A0033 // list
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false

ref; // ME_4C8F31830221 make

: ME_4C8E37620115
 CONST UID '4C8E37620115'
 CONST GUID '2852766C-A9A5-4A40-8C9F-FD957D1D856E'
 CONST Name 'FoundContext'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4C8E37750112 // list
 )
 ; // Attributes
 : Operations
   Seq: ( ME_4C8F31830221 // make
 )
 ; // Operations
 CONST "single impl" false
 CONST extprop:pas:TypeName 'IFoundContext'
 CONST extprop:rc:SelfName 'FoundContext'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4C8E37620115 FoundContext

FORWARD ME_4C5AA5CA02DF

: ME_4C5AB66C0030
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA60F039B // EntryPoint
 ;

ref; // ME_4C5AB66C0030 id

: ME_4C5AB62C02FC
 CONST UID '4C5AB62C02FC'
 CONST Name 'get_child_type'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target ME_4C5AB3040216 // EVDType
 ;
 : CanRaise
   Seq: ( ME_4C5ABA9401A6 // InvalidEntryPoint
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5AB66C0030 // id
 )
 ; // Parameters

ref; // ME_4C5AB62C02FC get_child_type

: ME_4C5AB6B8017D
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA60F039B // EntryPoint
 ;

ref; // ME_4C5AB6B8017D id

: ME_4C5AB68E0235
 CONST UID '4C5AB68E0235'
 CONST Name 'get_child_layer_id'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target ME_4C5AA63D01ED // LayerID
 ;
 : CanRaise
   Seq: ( ME_4C5ABA9401A6 // InvalidEntryPoint
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5AB6B8017D // id
 )
 ; // Parameters

ref; // ME_4C5AB68E0235 get_child_layer_id

: ME_4C5AB7880253
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA60F039B // EntryPoint
 ;

ref; // ME_4C5AB7880253 id

: ME_4C5AB6D90193
 CONST UID '4C5AB6D90193'
 CONST Name 'get_child_external_id'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target ME_4C5AB32B03A5 // ExternalID
 ;
 : CanRaise
   Seq: ( ME_4C5ABA9401A6 // InvalidEntryPoint
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5AB7880253 // id
 )
 ; // Parameters

ref; // ME_4C5AB6D90193 get_child_external_id

: ME_4C5AB82700AD
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA60F039B // EntryPoint
 ;

ref; // ME_4C5AB82700AD id

: ME_4C5AB80A00E4
 CONST UID '4C5AB80A00E4'
 CONST Name 'get_child_evd_style'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target ME_4C5AB363008D // EVDStream
 ;
 CONST TargetStereotype 'const'
 : CanRaise
   Seq: ( ME_4C5ABA9401A6 // InvalidEntryPoint
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5AB82700AD // id
 )
 ; // Parameters

ref; // ME_4C5AB80A00E4 get_child_evd_style

: ME_4C5AB85002DD
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA60F039B // EntryPoint
 ;

ref; // ME_4C5AB85002DD id

: ME_4C5AB83001A2
 CONST UID '4C5AB83001A2'
 CONST Name 'get_child_comment'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target ME_4C5AB363008D // EVDStream
 ;
 CONST TargetStereotype 'const'
 : CanRaise
   Seq: ( ME_4C5ABA9401A6 // InvalidEntryPoint
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5AB85002DD // id
 )
 ; // Parameters

ref; // ME_4C5AB83001A2 get_child_comment

: ME_4C5AB89B02DC
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA60F039B // EntryPoint
 ;

ref; // ME_4C5AB89B02DC id

: ME_4C5AB89B030E
 CONST Name 'comment'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AB363008D // EVDStream
 ;

ref; // ME_4C5AB89B030E comment

: ME_4C5AB859016E
 CONST UID '4C5AB859016E'
 CONST Name 'set_child_comment'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : CanRaise
   Seq: ( ME_4C5ABA9401A6 // InvalidEntryPoint
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5AB89B02DC // id
 ME_4C5AB89B030E // comment
 )
 ; // Parameters

ref; // ME_4C5AB859016E set_child_comment

: ME_4CC55099007A
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA60F039B // EntryPoint
 ;

ref; // ME_4CC55099007A id

: ME_4CC5505001CE
 CONST UID '4CC5505001CE'
 CONST Name 'remove_child_comment'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Parameters
   Seq: ( ME_4CC55099007A // id
 )
 ; // Parameters

ref; // ME_4CC5505001CE remove_child_comment

: ME_4C5AB91E01EB
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA60F039B // EntryPoint
 ;

ref; // ME_4C5AB91E01EB id

: ME_4C5AB8BF0144
 CONST UID '4C5AB8BF0144'
 CONST Name 'get_child_bookmarks'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target ME_4C5ABD7603D1 // BookmarkList
 ;
 CONST TargetStereotype 'const,cached'
 : CanRaise
   Seq: ( WL 'ME_456EC825009C' '456EA56002BF.pas.ms.script' // EmptyResult
 ME_4C5ABA9401A6 // InvalidEntryPoint
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5AB91E01EB // id
 )
 ; // Parameters

ref; // ME_4C5AB8BF0144 get_child_bookmarks

: ME_4C5ABA110355
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA60F039B // EntryPoint
 ;

ref; // ME_4C5ABA110355 id

: ME_4C5AB9ED0306
 CONST UID '4C5AB9ED0306'
 CONST Name 'get_child_text'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 CONST TargetStereotype 'const'
 : CanRaise
   Seq: ( ME_4C5ABA9401A6 // InvalidEntryPoint
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5ABA110355 // id
 )
 ; // Parameters

ref; // ME_4C5AB9ED0306 get_child_text

: ME_4D09D9B603CA
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA60F039B // EntryPoint
 ;

ref; // ME_4D09D9B603CA id

: ME_4D09D82502D2
 CONST UID '4D09D82502D2'
 CONST Name 'get_child_tech_comment'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 : CanRaise
   Seq: ( ME_4C5ABA9401A6 // InvalidEntryPoint
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4D09D9B603CA // id
 )
 ; // Parameters

ref; // ME_4D09D82502D2 get_child_tech_comment

: ME_4C5ABA7800FA
 CONST Name 'layer_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA63D01ED // LayerID
 ;

ref; // ME_4C5ABA7800FA layer_id

: ME_4C5ABA2E0009
 CONST UID '4C5ABA2E0009'
 CONST Name 'all_leaf_para_count'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;
 : CanRaise
   Seq: ( ME_4C5ABAA803CA // InvalidLayerID
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5ABA7800FA // layer_id
 )
 ; // Parameters

ref; // ME_4C5ABA2E0009 all_leaf_para_count

: ME_4C5ABB1F0091
 CONST Name 'layer_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA63D01ED // LayerID
 ;

ref; // ME_4C5ABB1F0091 layer_id

: ME_4C5ABAED00E5
 CONST UID '4C5ABAED00E5'
 CONST Name 'children_count'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;
 : CanRaise
   Seq: ( ME_4C5ABAA803CA // InvalidLayerID
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5ABB1F0091 // layer_id
 )
 ; // Parameters

ref; // ME_4C5ABAED00E5 children_count

: ME_4C5ABB5E0350
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AB32B03A5 // ExternalID
 ;

ref; // ME_4C5ABB5E0350 id

: ME_4C5ABB37029A
 CONST UID '4C5ABB37029A'
 CONST Name 'find_block_or_sub'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target WL 'ME_45EEC8680109' '457450470167.pas.ms.script' // NodeIndexPath
 ;
 CONST TargetStereotype 'const,cached'
 : CanRaise
   Seq: ( WL 'ME_456EB454018E' '456EA56002BF.pas.ms.script' // CanNotFindData
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5ABB5E0350 // id
 )
 ; // Parameters

ref; // ME_4C5ABB37029A find_block_or_sub

: ME_4C5ABBAA0053
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AB32B03A5 // ExternalID
 ;

ref; // ME_4C5ABBAA0053 id

: ME_4C5ABB88003B
 CONST UID '4C5ABB88003B'
 CONST Name 'find_para'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target WL 'ME_45EEC8680109' '457450470167.pas.ms.script' // NodeIndexPath
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018E' '456EA56002BF.pas.ms.script' // CanNotFindData
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5ABBAA0053 // id
 )
 ; // Parameters

ref; // ME_4C5ABB88003B find_para

: ME_4C5ABC0502E0
 CONST Name 'context'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_4C5ABC0502E0 context

: ME_4C91EA8102E4
 CONST Name 'from_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AB32B03A5 // ExternalID
 ;

ref; // ME_4C91EA8102E4 from_id

: ME_4C5ABBC300BE
 CONST UID '4C5ABBC300BE'
 CONST Name 'find_context'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target ME_4C8E37620115 // FoundContext
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018E' '456EA56002BF.pas.ms.script' // CanNotFindData
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4C5ABC0502E0 // context
 ME_4C91EA8102E4 // from_id
 )
 ; // Parameters

ref; // ME_4C5ABBC300BE find_context

: ME_4C9B41C30202
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AA60F039B // EntryPoint
 ;

ref; // ME_4C9B41C30202 id

: ME_4C9B414301FB
 CONST UID '4C9B414301FB'
 CONST Name 'get_sub_list'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target ME_4C9B41F302A7 // SubList
 ;
 CONST TargetStereotype 'const,cached'
 : Parameters
   Seq: ( ME_4C9B41C30202 // id
 )
 ; // Parameters

ref; // ME_4C9B414301FB get_sub_list

: ME_4D0F9F8002B6
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AB32B03A5 // ExternalID
 ;

ref; // ME_4D0F9F8002B6 id

: ME_4D0F9F6500F6
 CONST UID '4D0F9F6500F6'
 CONST Name 'get_prefix_tree'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;
 : Parameters
   Seq: ( ME_4D0F9F8002B6 // id
 )
 ; // Parameters

ref; // ME_4D0F9F6500F6 get_prefix_tree

: ME_4C64F7A6018F
 CONST Name 'server_doc'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_4C64F7A6018F server_doc

: ME_4CC01562015C
 CONST Name 'handle'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_4CC01562015C handle

: ME_4CAF18AD0294
 CONST Name 'all_at_once'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4CAF18AD0294 all_at_once

: ME_4C5ABE960168
 CONST UID '4C5ABE960168'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Parameters
   Seq: ( ME_4C64F7A6018F // server_doc
 ME_4CC01562015C // handle
 ME_4CAF18AD0294 // all_at_once
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false

ref; // ME_4C5ABE960168 make

: ME_4CED49970130
 CONST Name 'server_doc'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_4CED49970130 server_doc

: ME_4CED49970192
 CONST Name 'handle'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4CED49970192 handle

: ME_4CED499701F5
 CONST Name 'all_at_once'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4CED499701F5 all_at_once

: ME_4CED497B0316
 CONST UID '4CED497B0316'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Parameters
   Seq: ( ME_4CED49970130 // server_doc
 ME_4CED49970192 // handle
 ME_4CED499701F5 // all_at_once
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false

ref; // ME_4CED497B0316 make

: ME_51E404FF0128
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AB32B03A5 // ExternalID
 ;

ref; // ME_51E404FF0128 id

: ME_51E40487028B
 CONST UID '51E40487028B'
 CONST Name 'show_sub_panel_icon'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 %SUMMARY 'Нужно ли показывать иконку для блока на сабпанели' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 : Parameters
   Seq: ( ME_51E404FF0128 // id
 )
 ; // Parameters

ref; // ME_51E40487028B show_sub_panel_icon

: ME_5582C0380085
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AB32B03A5 // ExternalID
 ;

ref; // ME_5582C0380085 id

: ME_5582C01300CB
 CONST UID '5582C01300CB'
 CONST Name 'has_same'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 %SUMMARY 'Если есть похожие к sub вернет true, иначе false.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 : Parameters
   Seq: ( ME_5582C0380085 // id
 )
 ; // Parameters

ref; // ME_5582C01300CB has_same

: ME_4C5AA5CA02DF
 CONST UID '4C5AA5CA02DF'
 CONST GUID 'EDE34F9F-F36F-48FA-82BA-FD755CE46B4B'
 CONST Name 'DocumentTextProvider'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Operations
   Seq: ( ME_4C5AB62C02FC // get_child_type
 ME_4C5AB68E0235 // get_child_layer_id
 ME_4C5AB6D90193 // get_child_external_id
 ME_4C5AB80A00E4 // get_child_evd_style
 ME_4C5AB83001A2 // get_child_comment
 ME_4C5AB859016E // set_child_comment
 ME_4CC5505001CE // remove_child_comment
 ME_4C5AB8BF0144 // get_child_bookmarks
 ME_4C5AB9ED0306 // get_child_text
 ME_4D09D82502D2 // get_child_tech_comment
 ME_4C5ABA2E0009 // all_leaf_para_count
 ME_4C5ABAED00E5 // children_count
 ME_4C5ABB37029A // find_block_or_sub
 ME_4C5ABB88003B // find_para
 ME_4C5ABBC300BE // find_context
 ME_4C9B414301FB // get_sub_list
 ME_4D0F9F6500F6 // get_prefix_tree
 ME_4C5ABE960168 // make
 ME_4CED497B0316 // make
 ME_51E40487028B // show_sub_panel_icon
 ME_5582C01300CB // has_same
 )
 ; // Operations
 CONST "single impl" false
 CONST extprop:pas:TypeName 'IDocumentTextProvider'
 CONST extprop:rc:SelfName 'DocumentTextProvider'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4C5AA5CA02DF DocumentTextProvider

FORWARD ME_4CED493F01B9

: ME_4CED496D024F
 CONST UID '4CED496D024F'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent ME_4CED493F01B9 // DocumentTextProviderList
 ;
 : Target ME_4C5AA5CA02DF // DocumentTextProvider
 ;

ref; // ME_4CED496D024F 

: ME_4CED493F01B9
 CONST UID '4CED493F01B9'
 CONST Name 'DocumentTextProviderList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4CED496D024F // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'IDocumentTextProviderList'

ref; // ME_4CED493F01B9 DocumentTextProviderList

FORWARD ME_4C6E33E40051

: ME_4C6E34E900F0
 CONST UID '4C6E34E900F0'
 CONST Name 'ROOT_CHILD'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4C6E33E40051 // TextProviderConstants
 ;
 : Target ME_4C5AA67E002B // ChildID
 ;
 CONST Value 0
 : ValueType ME_4C5AA67E002B // ChildID
 ;
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 0

ref; // ME_4C6E34E900F0 ROOT_CHILD

: ME_4C6E351A0220
 CONST UID '4C6E351A0220'
 CONST Name 'ROOT_LAYER'
 CONST Class class_Attribute
 %SUMMARY '0xFFFFFFFF' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4C6E33E40051 // TextProviderConstants
 ;
 : Target ME_4C5AA63D01ED // LayerID
 ;
 CONST Value 4294967295
 : ValueType ME_4C5AA63D01ED // LayerID
 ;
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 4294967295

ref; // ME_4C6E351A0220 ROOT_LAYER

: ME_4C6E33E40051
 CONST UID '4C6E33E40051'
 CONST Name 'TextProviderConstants'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4C6E34E900F0 // ROOT_CHILD
 ME_4C6E351A0220 // ROOT_LAYER
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_4C6E33E40051 TextProviderConstants

FORWARD ME_4D147CA200AE

: ME_4D147DAB007D
 CONST UID '4D147DAB007D'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4D147CA200AE // CommentsParaList
 ;
 : Target ME_45EEB65202AA // ParaId
 ;

ref; // ME_4D147DAB007D 

: ME_4D147CA200AE
 CONST UID '4D147CA200AE'
 CONST Name 'CommentsParaList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4D147DAB007D // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'ICommentsParaList'

ref; // ME_4D147CA200AE CommentsParaList

FORWARD ME_4D14817F0147

: ME_4D14838603BF
 CONST UID '4D14838603BF'
 CONST Name 'type'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4D14817F0147 // ExternalObjectData
 ;
 : Target WL 'ME_45ED9387018C' '45ED922F00A4.pas.ms.script' // ExternalObjectType
 ;

ref; // ME_4D14838603BF type

: ME_4D1483B501AC
 CONST UID '4D1483B501AC'
 CONST Name 'para_id'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4D14817F0147 // ExternalObjectData
 ;
 : Target ME_45EEB65202AA // ParaId
 ;

ref; // ME_4D1483B501AC para_id

: ME_4D1483F8011D
 CONST UID '4D1483F8011D'
 CONST Name 'name'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent ME_4D14817F0147 // ExternalObjectData
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_4D1483F8011D name

: ME_4D14817F0147
 CONST UID '4D14817F0147'
 CONST Name 'ExternalObjectData'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4D14838603BF // type
 ME_4D1483B501AC // para_id
 ME_4D1483F8011D // name
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TExternalObjectData'

ref; // ME_4D14817F0147 ExternalObjectData

FORWARD ME_4D14813D02BB

: ME_4D148194022A
 CONST UID '4D148194022A'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4D14813D02BB // ExternalObjectDataList
 ;
 : Target ME_4D14817F0147 // ExternalObjectData
 ;

ref; // ME_4D148194022A 

: ME_4D14813D02BB
 CONST UID '4D14813D02BB'
 CONST Name 'ExternalObjectDataList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4D148194022A // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'IExternalObjectDataList'

ref; // ME_4D14813D02BB ExternalObjectDataList

FORWARD ME_4CC80F7E02BB

: ME_4CC80F8E0211
 CONST UID '4CC80F8E0211'
 CONST Name 'diff_iterator'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent ME_4CC80F7E02BB // DiffData
 ;
 : Target ME_4B4EE046030D // DiffIterator
 ;

ref; // ME_4CC80F8E0211 diff_iterator

: ME_4CC8121E0131
 CONST UID '4CC8121E0131'
 CONST Name 'cur'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent ME_4CC80F7E02BB // DiffData
 ;
 : Target ME_4C5AA5CA02DF // DocumentTextProvider
 ;

ref; // ME_4CC8121E0131 cur

: ME_4CC8122E02BC
 CONST UID '4CC8122E02BC'
 CONST Name 'prev'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent ME_4CC80F7E02BB // DiffData
 ;
 : Target ME_4C5AA5CA02DF // DocumentTextProvider
 ;

ref; // ME_4CC8122E02BC prev

: ME_4CC80F7E02BB
 CONST UID '4CC80F7E02BB'
 CONST Name 'DiffData'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4CC80F8E0211 // diff_iterator
 ME_4CC8121E0131 // cur
 ME_4CC8122E02BC // prev
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TDiffData'

ref; // ME_4CC80F7E02BB DiffData

FORWARD ME_4D628A3C0341

: ME_4D628B32014A
 CONST UID '4D628B32014A'
 CONST Name 'handle'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4D628A3C0341 // DocumentTextProviderDescriptor
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4D628B32014A handle

: ME_4D628B580085
 CONST UID '4D628B580085'
 CONST Name 'header_leaf_count'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4D628A3C0341 // DocumentTextProviderDescriptor
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4D628B580085 header_leaf_count

: ME_4D628B7A0382
 CONST UID '4D628B7A0382'
 CONST Name 'anno_leaf_count'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4D628A3C0341 // DocumentTextProviderDescriptor
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4D628B7A0382 anno_leaf_count

: ME_4D628A3C0341
 CONST UID '4D628A3C0341'
 CONST Name 'DocumentTextProviderDescriptor'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4D628B32014A // handle
 ME_4D628B580085 // header_leaf_count
 ME_4D628B7A0382 // anno_leaf_count
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TDocumentTextProviderDescriptor'

ref; // ME_4D628A3C0341 DocumentTextProviderDescriptor

FORWARD ME_4D628F1402C0

: ME_4D6291B7034F
 CONST UID '4D6291B7034F'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4D628F1402C0 // DocumentTextProviderDescriptorList
 ;
 : Target ME_4D628A3C0341 // DocumentTextProviderDescriptor
 ;

ref; // ME_4D6291B7034F 

: ME_4D628F1402C0
 CONST UID '4D628F1402C0'
 CONST Name 'DocumentTextProviderDescriptorList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4D6291B7034F // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'IDocumentTextProviderDescriptorList'

ref; // ME_4D628F1402C0 DocumentTextProviderDescriptorList

: ME_4DCBBAC300F6
 CONST UID '4DCBBAC300F6'
 CONST Name 'SubId'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 )
 ; // Inherits
 CONST extprop:pas:TypeName 'TSubId'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4DCBBAC300F6 SubId

FORWARD ME_4DCBB953031F

: ME_4DCBBA6C00B9
 CONST UID '4DCBBA6C00B9'
 CONST Name 'doc_id'
 CONST Class class_Attribute
 %SUMMARY 'Идентификатор документа' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4DCBB953031F // DocPoint
 ;
 : Target WL 'ME_4DCD6C7401B5' '456EA56002BF.pas.ms.script' // BaseTypesObjectId
 ;

ref; // ME_4DCBBA6C00B9 doc_id

: ME_4DCBBA8503B2
 CONST UID '4DCBBA8503B2'
 CONST Name 'sub_id'
 CONST Class class_Attribute
 %SUMMARY 'Номер саба/блока' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4DCBB953031F // DocPoint
 ;
 : Target ME_4DCBBAC300F6 // SubId
 ;

ref; // ME_4DCBBA8503B2 sub_id

: ME_4DCBB953031F
 CONST UID '4DCBB953031F'
 CONST Name 'DocPoint'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Точка входа в документ (пара DocId SubId)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4DCBBA6C00B9 // doc_id
 ME_4DCBBA8503B2 // sub_id
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TDocPoint'

ref; // ME_4DCBB953031F DocPoint

FORWARD ME_4DCBBAEF025F

: ME_4DCBBB0C00C2
 CONST UID '4DCBBB0C00C2'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4DCBBAEF025F // DocPointList
 ;
 : Target ME_4DCBB953031F // DocPoint
 ;

ref; // ME_4DCBBB0C00C2 

: ME_4DCBBAEF025F
 CONST UID '4DCBBAEF025F'
 CONST Name 'DocPointList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Список точек входа в документ' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4DCBBB0C00C2 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST "force usage" true
 CONST extprop:pas:TypeName 'IDocPointList'

ref; // ME_4DCBBAEF025F DocPointList

FORWARD ME_4FEAFCB6035C

: ME_4FEAFD79015E
 CONST UID '4FEAFD79015E'
 CONST Name 'can_like'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Доступность операции оценки' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4FEAFCB6035C // Likeable
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 CONST "pm" false

ref; // ME_4FEAFD79015E can_like

: ME_4FEAFD48024F
 CONST UID '4FEAFD48024F'
 CONST Name 'like'
 CONST Class class_Operation
 %SUMMARY 'Нравится' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4FEAFCB6035C // Likeable
 ;

ref; // ME_4FEAFD48024F like

: ME_4FEAFD5D03D1
 CONST UID '4FEAFD5D03D1'
 CONST Name 'unlike'
 CONST Class class_Operation
 %SUMMARY 'Не нравится' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4FEAFCB6035C // Likeable
 ;

ref; // ME_4FEAFD5D03D1 unlike

: ME_4FEAFCB6035C
 CONST UID '4FEAFCB6035C'
 CONST GUID 'CD879569-CC93-4E02-B56F-C5C1B3FBBEBC'
 CONST Name 'Likeable'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4FEAFD79015E // can_like
 )
 ; // Attributes
 : Operations
   Seq: ( ME_4FEAFD48024F // like
 ME_4FEAFD5D03D1 // unlike
 )
 ; // Operations
 CONST extprop:pas:TypeName 'ILikeable'
 CONST extprop:rc:SelfName 'Likeable'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4FEAFCB6035C Likeable

FORWARD ME_45EED83A00C4

: ME_45EED83A00C5
 CONST UID '45EED83A00C5'
 CONST Name 'name'
 CONST Class class_Attribute
 %SUMMARY 'Имя редакции.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent ME_45EED83A00C4 // RedactionInfo
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_45EED83A00C5 name

: ME_45EED83A00C6
 CONST UID '45EED83A00C6'
 CONST Name 'time_machine_date'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED83A00C4 // RedactionInfo
 ;
 : Target WL 'ME_456EA6F00109' '456EA56002BF.pas.ms.script' // Date
 ;

ref; // ME_45EED83A00C6 time_machine_date

: ME_45EED83A00C7
 CONST UID '45EED83A00C7'
 CONST Name 'doc_date'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED83A00C4 // RedactionInfo
 ;
 : Target WL 'ME_456EA6F00109' '456EA56002BF.pas.ms.script' // Date
 ;

ref; // ME_45EED83A00C7 doc_date

: ME_4B73D65703E3
 CONST UID '4B73D65703E3'
 CONST Name 'is_comparable'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED83A00C4 // RedactionInfo
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4B73D65703E3 is_comparable

: ME_45EED91703E0
 CONST UID '45EED91703E0'
 CONST Name 'actual_type'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED83A00C4 // RedactionInfo
 ;
 : Target ME_45EED8C20066 // RedactionType
 ;

ref; // ME_45EED91703E0 actual_type

: ME_45EED928021B
 CONST UID '45EED928021B'
 CONST Name 'not_sure_intervals'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED83A00C4 // RedactionInfo
 ;
 : Target ME_45EED88901BE // NotSureIntervalList
 ;

ref; // ME_45EED928021B not_sure_intervals

: ME_45EED93D022A
 CONST UID '45EED93D022A'
 CONST Name 'active_intervals'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED83A00C4 // RedactionInfo
 ;
 : Target ME_45EED87E0383 // ActiveIntervalList
 ;

ref; // ME_45EED93D022A active_intervals

: ME_45EED96602B6
 CONST UID '45EED96602B6'
 CONST Name 'id'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED83A00C4 // RedactionInfo
 ;
 : Target ME_45EED84C01FD // RedactionID
 ;

ref; // ME_45EED96602B6 id

: ME_51FB768C0182
 CONST UID '51FB768C0182'
 CONST Name 'changing_documents'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_45EED83A00C4 // RedactionInfo
 ;
 : Target ME_51FB7643002D // RedactionSourceDocumentInfoList
 ;

ref; // ME_51FB768C0182 changing_documents

: ME_45EED83A00C4
 CONST UID '45EED83A00C4'
 CONST Name 'RedactionInfo'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Информация о редакции объекта.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EED83A00C5 // name
 ME_45EED83A00C6 // time_machine_date
 ME_45EED83A00C7 // doc_date
 ME_4B73D65703E3 // is_comparable
 ME_45EED91703E0 // actual_type
 ME_45EED928021B // not_sure_intervals
 ME_45EED93D022A // active_intervals
 ME_45EED96602B6 // id
 ME_51FB768C0182 // changing_documents
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TRedactionInfo'

ref; // ME_45EED83A00C4 RedactionInfo

FORWARD ME_4D78D5820316

: ME_4D78D5980231
 CONST UID '4D78D5980231'
 CONST Name 'text'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent ME_4D78D5820316 // DiffDocPara
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_4D78D5980231 text

: ME_4D78D5D403C8
 CONST UID '4D78D5D403C8'
 CONST Name 'style'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent ME_4D78D5820316 // DiffDocPara
 ;
 : Target ME_4C5AB363008D // EVDStream
 ;

ref; // ME_4D78D5D403C8 style

: ME_4ECE1EBC0240
 CONST UID '4ECE1EBC0240'
 CONST Name 'data'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent ME_4D78D5820316 // DiffDocPara
 ;
 : Target WL 'ME_4423FB5903D8' '4423F94903C8.pas.ms.script' // Stream
 ;

ref; // ME_4ECE1EBC0240 data

: ME_4D78D603019C
 CONST UID '4D78D603019C'
 CONST Name 'type'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4D78D5820316 // DiffDocPara
 ;
 : Target ME_4C5AB3040216 // EVDType
 ;

ref; // ME_4D78D603019C type

: ME_4E8DB10F0058
 CONST UID '4E8DB10F0058'
 CONST Name 'id'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4D78D5820316 // DiffDocPara
 ;
 : Target WL 'ME_3DBFFD7002C2' '3DBFDB23006E.pas.ms.script' // long
 ;

ref; // ME_4E8DB10F0058 id

: ME_4D78D5820316
 CONST UID '4D78D5820316'
 CONST Name 'DiffDocPara'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4D78D5980231 // text
 ME_4D78D5D403C8 // style
 ME_4ECE1EBC0240 // data
 ME_4D78D603019C // type
 ME_4E8DB10F0058 // id
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TDiffDocPara'

ref; // ME_4D78D5820316 DiffDocPara

FORWARD ME_4D78D65C01FF

: ME_4D78D67002E9
 CONST UID '4D78D67002E9'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4D78D65C01FF // DiffDocParaList
 ;
 : Target ME_4D78D5820316 // DiffDocPara
 ;

ref; // ME_4D78D67002E9 

: ME_4D78D65C01FF
 CONST UID '4D78D65C01FF'
 CONST Name 'DiffDocParaList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4D78D67002E9 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'IDiffDocParaList'

ref; // ME_4D78D65C01FF DiffDocParaList

FORWARD ME_4D78D72003B3

: ME_4D78D7450221
 CONST UID '4D78D7450221'
 CONST Name 'id'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4D78D72003B3 // ChangedBlock
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4D78D7450221 id

: ME_4D78D78A0268
 CONST UID '4D78D78A0268'
 CONST Name 'header'
 CONST Class class_Attribute
 %SUMMARY 'Название структурной единицы с точностью до минимального блока, входящего в оглавление,'#13#10'которым  предваряется измененный фрагмент (блок)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4D78D72003B3 // ChangedBlock
 ;
 : Target ME_4D78D65C01FF // DiffDocParaList
 ;

ref; // ME_4D78D78A0268 header

: ME_4D78D7A500F3
 CONST UID '4D78D7A500F3'
 CONST Name 'right_text_para_list'
 CONST Class class_Attribute
 %SUMMARY 'Измененный фрагмент правой редакции' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4D78D72003B3 // ChangedBlock
 ;
 : Target ME_4D78D65C01FF // DiffDocParaList
 ;

ref; // ME_4D78D7A500F3 right_text_para_list

: ME_4D78D7D60153
 CONST UID '4D78D7D60153'
 CONST Name 'left_text_para_list'
 CONST Class class_Attribute
 %SUMMARY 'Измененный фрагмент левой редакции' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4D78D72003B3 // ChangedBlock
 ;
 : Target ME_4D78D65C01FF // DiffDocParaList
 ;

ref; // ME_4D78D7D60153 left_text_para_list

: ME_4D78D72003B3
 CONST UID '4D78D72003B3'
 CONST Name 'ChangedBlock'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4D78D7450221 // id
 ME_4D78D78A0268 // header
 ME_4D78D7A500F3 // right_text_para_list
 ME_4D78D7D60153 // left_text_para_list
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TChangedBlock'

ref; // ME_4D78D72003B3 ChangedBlock

FORWARD ME_45EED8DE0121

: ME_45EED90F0334
 CONST UID '45EED90F0334'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EED8DE0121 // RedactionInfoList
 ;
 : Target ME_45EED83A00C4 // RedactionInfo
 ;

ref; // ME_45EED90F0334 

: ME_45EED8DE0121
 CONST UID '45EED8DE0121'
 CONST Name 'RedactionInfoList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Список редакций.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_45EED90F0334 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'IRedactionInfoList'

ref; // ME_45EED8DE0121 RedactionInfoList

FORWARD ME_45EEB65202A0

FORWARD ME_45EED80E0086

FORWARD ME_4A8A8F640192

FORWARD ME_51A6183C010F

FORWARD ME_45EEB6520191

: ME_45EEB65201E3
 CONST UID '45EEB65201E3'
 CONST Name 'name'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Имя документа.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_45EEB65201E3 name

: ME_45EEB65201E4
 CONST UID '45EEB65201E4'
 CONST Name 'short_name'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Краткое имя документа.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_45EEB65201E4 short_name

: ME_45EEB65201E5
 CONST UID '45EEB65201E5'
 CONST Name 'warning'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Предупреждение к документу.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_45EEB65201E5 warning

: ME_45EEB65201E6
 CONST UID '45EEB65201E6'
 CONST Name 'size'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'размер документа в байтах' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;
 CONST "pm" false

ref; // ME_45EEB65201E6 size

: ME_45EEB65201E7
 CONST UID '45EEB65201E7'
 CONST Name 'internal_id'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'внутренний номер документа в базе' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;
 CONST "pm" false

ref; // ME_45EEB65201E7 internal_id

: ME_48285D28025E
 CONST UID '48285D28025E'
 CONST Name 'not_tm'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'True - если документ не подключен к машине времени' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 CONST "pm" false

ref; // ME_48285D28025E not_tm

: ME_496B249601F3
 CONST UID '496B249601F3'
 CONST Name 'file_position'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018E' '456EA56002BF.pas.ms.script' // CanNotFindData
 )
 ; // CanRaise
 CONST "pm" false

ref; // ME_496B249601F3 file_position

: ME_4BC323A60337
 CONST UID '4BC323A60337'
 CONST Name 'new_revision_available'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Доступна новая ревизия документа (для супермобильной версии)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 CONST "pm" false

ref; // ME_4BC323A60337 new_revision_available

: ME_4D7E231702E4
 CONST UID '4D7E231702E4'
 CONST Name 'change_status'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Статус изменения документа' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;
 CONST "pm" false

ref; // ME_4D7E231702E4 change_status

: ME_45EEBECB019A
 CONST UID '45EEBECB019A'
 CONST Name 'status'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Статус документа' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_456EC8A60000' '456EA56002BF.pas.ms.script' // ItemStatus
 ;
 CONST "pm" false

ref; // ME_45EEBECB019A status

: ME_45EEBF0F014B
 CONST UID '45EEBF0F014B'
 CONST Name 'text_languages'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_456EE8920119' '456EA56002BF.pas.ms.script' // LanguagesList
 ;
 CONST "pm" false

ref; // ME_45EEBF0F014B text_languages

: ME_45EEC00F006F
 CONST UID '45EEC00F006F'
 CONST Name 'attributes_root'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;
 CONST "pm" false

ref; // ME_45EEC00F006F attributes_root

: ME_45EED8FA017F
 CONST UID '45EED8FA017F'
 CONST Name 'redactions_list'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_45EED8DE0121 // RedactionInfoList
 ;
 CONST "pm" false

ref; // ME_45EED8FA017F redactions_list

: ME_45EED98D00E1
 CONST UID '45EED98D00E1'
 CONST Name 'current_state'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_45EED80E0086 // DocumentState
 ;
 CONST "pm" false

ref; // ME_45EED98D00E1 current_state

: ME_460B80CF0201
 CONST UID '460B80CF0201'
 CONST Name 'doc_type'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_45EEB6520208 // DocumentType
 ;
 CONST "pm" false

ref; // ME_460B80CF0201 doc_type

: ME_460B8F6A02B2
 CONST UID '460B8F6A02B2'
 CONST Name 'translation'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_45EEB6520191 // Document
 ;
 CONST "pm" false

ref; // ME_460B8F6A02B2 translation

: ME_460B8F8F0002
 CONST UID '460B8F8F0002'
 CONST Name 'annotation'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_45EEB6520191 // Document
 ;
 CONST "pm" false

ref; // ME_460B8F8F0002 annotation

: ME_460B8FD603AB
 CONST UID '460B8FD603AB'
 CONST Name 'related_doc'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_45EEB6520191 // Document
 ;
 CONST "pm" false

ref; // ME_460B8FD603AB related_doc

: ME_47ED1B17039A
 CONST UID '47ED1B17039A'
 CONST Class class_Attribute
 : Stereotype st_factory_switch::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_47ED1AC7036F // FactoryKey
 ;

ref; // ME_47ED1B17039A 

: ME_4C77A3370186
 CONST UID '4C77A3370186'
 CONST Name 'contents_root'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018E' '456EA56002BF.pas.ms.script' // CanNotFindData
 )
 ; // CanRaise
 CONST "pm" false

ref; // ME_4C77A3370186 contents_root

: ME_4D147C7602A6
 CONST UID '4D147C7602A6'
 CONST Name 'bookmark_list'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_4C5ABD7603D1 // BookmarkList
 ;
 CONST "pm" false

ref; // ME_4D147C7602A6 bookmark_list

: ME_4D147CCA0051
 CONST UID '4D147CCA0051'
 CONST Name 'comments_para_list'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_4D147CA200AE // CommentsParaList
 ;
 CONST "pm" false

ref; // ME_4D147CCA0051 comments_para_list

: ME_4D14816D015F
 CONST UID '4D14816D015F'
 CONST Name 'external_object_data_list'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_4D14813D02BB // ExternalObjectDataList
 ;
 CONST "pm" false

ref; // ME_4D14816D015F external_object_data_list

: ME_45EEB6520195
 CONST Name 'para'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB65202AA // ParaId
 ;

ref; // ME_45EEB6520195 para

: ME_45EEB6520196
 CONST Name 'is_para'
 CONST Class class_Parameter
 : Stereotype st_in ;
 %SUMMARY 'Флаг указывающий на то что в первом параметре указывается параграф, в противном случае саб.' ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB6520196 is_para

: ME_45EEB6520194
 CONST UID '45EEB6520194'
 CONST Name 'create_bookmark'
 CONST Class class_Operation
 %SUMMARY 'Создает экземпляр Закладки на заданный идентификатор параграфа. Присваивает ей в качестве названия короткое имя документа. А в качестве full_name имя документа и имя ближайшего (сверху) саба или блока (как в списках).' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_45EEB65202A0 // Bookmark
 ;
 : Parameters
   Seq: ( ME_45EEB6520195 // para
 ME_45EEB6520196 // is_para
 )
 ; // Parameters

ref; // ME_45EEB6520194 create_bookmark

: ME_4628C079025A
 CONST Name 'filters'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target ME_45EED80E0086 // DocumentState
 ;

ref; // ME_4628C079025A filters

: ME_45EEB6520197
 CONST UID '45EEB6520197'
 CONST Name 'create_view'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 %SUMMARY 'Возвращает документ - редакцию, заказанную через  filters.'#13#10'Если текущая редакция равна заказанной - возвращает NULL' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_45EEB6520191 // Document
 ;
 : Parameters
   Seq: ( ME_4628C079025A // filters
 )
 ; // Parameters

ref; // ME_45EEB6520197 create_view

: ME_45EEB652019A
 CONST Name 'pos_list'
 CONST Class class_Parameter
 : Stereotype st_in ;
 %SUMMARY 'Список позиций.' ;
 : Target ME_45EEB65202EF // PositionList
 ;

ref; // ME_45EEB652019A pos_list

: ME_45EEB652019B
 CONST Name 'category'
 CONST Class class_Parameter
 : Stereotype st_in ;
 %SUMMARY 'Категория фильтрации' ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_45EEB652019B category

: ME_45EEB652019C
 CONST Name 'out_list'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_45EEBA2C02BF' '457450470167.pas.ms.script' // CatalogBase
 ;

ref; // ME_45EEB652019C out_list

: ME_45EEB6520199
 CONST UID '45EEB6520199'
 CONST Name 'get_correspondents_to_part'
 CONST Class class_Operation
 %SUMMARY 'Возвращает список корреспондентов к фрагменту документа (список параграфов) для указанной категории (category).'#13#10''#13#10'для редакций, отлчных от "главной", возвращает NULL' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Parameters
   Seq: ( ME_45EEB652019A // pos_list
 ME_45EEB652019B // category
 ME_45EEB652019C // out_list
 )
 ; // Parameters

ref; // ME_45EEB6520199 get_correspondents_to_part

: ME_45EEB652019E
 CONST Name 'block_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFD7002C2' '3DBFDB23006E.pas.ms.script' // long
 ;

ref; // ME_45EEB652019E block_id

: ME_45EEB652019D
 CONST UID '45EEB652019D'
 CONST Name 'get_internet_image_url'
 CONST Class class_Operation
 %SUMMARY 'Получить url для отсканированного WWW-образа документа.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_45ED93720286' '45ED922F00A4.pas.ms.script' // ExternalLink
 ;
 : Parameters
   Seq: ( ME_45EEB652019E // block_id
 )
 ; // Parameters

ref; // ME_45EEB652019D get_internet_image_url

: ME_47C6B1C90393
 CONST Name 'doc_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_47C6B1C90393 doc_id

: ME_47C6B1C903D1
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB65202CD // Topic
 ;

ref; // ME_47C6B1C903D1 id

: ME_47C6B1CA0018
 CONST Name 'rid'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EED84C01FD // RedactionID
 ;

ref; // ME_47C6B1CA0018 rid

: ME_47C6B1CA0047
 CONST Name 'obj_type'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_47C6B1CA0047 obj_type

: ME_47C6B1CA0076
 CONST Name 'obj'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_4242EBBB03B9' '3DBFDB23006E.pas.ms.script' // object
 ;

ref; // ME_47C6B1CA0076 obj

: ME_45EEB65201A3
 CONST UID '45EEB65201A3'
 CONST Name 'get_linked_object'
 CONST Class class_Operation
 %SUMMARY 'Получить интерфейс объекта, на который указывает гипертекстовая ссылка, по внутреннему идентификатору.'#13#10'Возвращается интерфейс на объект (obj) и тип объекта (obj_type).'#13#10'Дополнительно можно получить интерфейс (missing_info) с информацией, в каких блоках (базах) содержится отсутствующий объект (метод get_missing_info)'#13#10'Будет использоваться для перехода по гипертекстовой ссылке.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : CanRaise
   Seq: ( ME_45EEB6520321 // InvalidTopicId
 ME_45EEB6520328 // FolderLinkNotFound
 ME_45EEDAD60237 // NotAllowedInTrialMode
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_47C6B1C90393 // doc_id
 ME_47C6B1C903D1 // id
 ME_47C6B1CA0018 // rid
 ME_47C6B1CA0047 // obj_type
 ME_47C6B1CA0076 // obj
 )
 ; // Parameters

ref; // ME_45EEB65201A3 get_linked_object

: ME_462CD97A0149
 CONST Name 'date'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_456EA6F00109' '456EA56002BF.pas.ms.script' // Date
 ;

ref; // ME_462CD97A0149 date

: ME_462CD97A01E6
 CONST Name 'start'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_456EA6F00109' '456EA56002BF.pas.ms.script' // Date
 ;

ref; // ME_462CD97A01E6 start

: ME_462CD97A02A1
 CONST Name 'finish'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_456EA6F00109' '456EA56002BF.pas.ms.script' // Date
 ;

ref; // ME_462CD97A02A1 finish

: ME_462CD97A034D
 CONST Name 'info'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target ME_45EEB6520191 // Document
 ;

ref; // ME_462CD97A034D info

: ME_462CD97B0001
 CONST Name 'warning'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_462CD97B0001 warning

: ME_45EEB65201AA
 CONST UID '45EEB65201AA'
 CONST Name 'get_not_sure_info'
 CONST Class class_Operation
 %SUMMARY 'Возвращает информацию об интервале неуверенности документа. Если указанная в параметра date дата не попадает в интревал бросает CanNotFindData' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Parameters
   Seq: ( ME_462CD97A0149 // date
 ME_462CD97A01E6 // start
 ME_462CD97A02A1 // finish
 ME_462CD97A034D // info
 ME_462CD97B0001 // warning
 )
 ; // Parameters

ref; // ME_45EEB65201AA get_not_sure_info

: ME_45EEB65201B1
 CONST Name 'pos_list'
 CONST Class class_Parameter
 : Stereotype st_in ;
 %SUMMARY 'Список позиций.' ;
 : Target ME_45EEB65202EF // PositionList
 ;

ref; // ME_45EEB65201B1 pos_list

: ME_45EEB65201B2
 CONST Name 'category'
 CONST Class class_Parameter
 : Stereotype st_in ;
 %SUMMARY 'Категория фильтрации.' ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_45EEB65201B2 category

: ME_45EEB65201B3
 CONST Name 'out_list'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_45EEBA2C02BF' '457450470167.pas.ms.script' // CatalogBase
 ;

ref; // ME_45EEB65201B3 out_list

: ME_45EEB65201B0
 CONST UID '45EEB65201B0'
 CONST Name 'get_respondents_to_part'
 CONST Class class_Operation
 %SUMMARY 'Возвращает список респондентов к фрагменту документа (список параграфов) для указанной категории (category).'#13#10''#13#10'для редакций, отлчных от "главной", возвращает NULL' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Parameters
   Seq: ( ME_45EEB65201B1 // pos_list
 ME_45EEB65201B2 // category
 ME_45EEB65201B3 // out_list
 )
 ; // Parameters

ref; // ME_45EEB65201B0 get_respondents_to_part

: ME_45EEB65201BF
 CONST Name 'date'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_456EA6F00109' '456EA56002BF.pas.ms.script' // Date
 ;

ref; // ME_45EEB65201BF date

: ME_45EEB65201BE
 CONST UID '45EEB65201BE'
 CONST Name 'get_time_machine_warning'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_45EEB652031D // TimeMachineWarning
 ;
 : Parameters
   Seq: ( ME_45EEB65201BF // date
 )
 ; // Parameters

ref; // ME_45EEB65201BE get_time_machine_warning

: ME_45EEB65201C1
 CONST Name 'category'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_45EEB65201C1 category

: ME_45EEB65201C0
 CONST UID '45EEB65201C0'
 CONST Name 'has_correspondents'
 CONST Class class_Operation
 %SUMMARY 'Проверка наличия корреспондентов (любогй категории) у текущего документа.'#13#10'Возвращает true в случае, если список корреспондентов для документа по категории CR_ALL не пуст.'#13#10''#13#10'для редакций, отличных от "главной", возвращает FALSE' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 : Parameters
   Seq: ( ME_45EEB65201C1 // category
 )
 ; // Parameters

ref; // ME_45EEB65201C0 has_correspondents

: ME_45EEB65201C2
 CONST UID '45EEB65201C2'
 CONST Name 'has_internet_image'
 CONST Class class_Operation
 %SUMMARY 'Проверка наличия WWW-образа у текущего документа.'#13#10'Возвращает true в случае, если у текущего документа есть WWW-образ.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB65201C2 has_internet_image

: ME_45EEB65201C3
 CONST UID '45EEB65201C3'
 CONST Name 'has_next_redaction'
 CONST Class class_Operation
 %SUMMARY 'Функция показывает наличие следующей редакции для объекта.'#13#10'Следующая редакция считается относительно текущего состояния (current_redaction).'#13#10'Возвращает True в случае наличия хотябы одной более поздней (чем текущая) редакции.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB65201C3 has_next_redaction

: ME_45EEB65201C4
 CONST UID '45EEB65201C4'
 CONST Name 'has_prev_redaction'
 CONST Class class_Operation
 %SUMMARY 'Функция показывает наличие предыдущей редакции для объекта.'#13#10'Предыдущая редакция считается относительно текущего состояния (current_redaction).'#13#10'Возвращает True в случае наличия хотябы одной более ранней (чем текущая) редакции.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB65201C4 has_prev_redaction

: ME_45EEB65201C5
 CONST UID '45EEB65201C5'
 CONST Name 'has_related_doc'
 CONST Class class_Operation
 %SUMMARY 'Проверка наличия справки у текущего документа.'#13#10'Возвращает true в случае, если у текущего документа есть справка.'#13#10''#13#10'для редакций, отличных от "главной", поведение такое же как и для "главной"' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB65201C5 has_related_doc

: ME_45EEB65201C7
 CONST Name 'category'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_45EEB65201C7 category

: ME_45EEB65201C6
 CONST UID '45EEB65201C6'
 CONST Name 'has_respondents'
 CONST Class class_Operation
 %SUMMARY 'Проверка наличия респондентов (любогй категории) у текущего документа.'#13#10'Возвращает true в случае, если список респондентов для документа по категории CR_ALL не пуст.'#13#10''#13#10'для редакций, отличных от "главной", возвращает FALSE' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 : Parameters
   Seq: ( ME_45EEB65201C7 // category
 )
 ; // Parameters

ref; // ME_45EEB65201C6 has_respondents

: ME_45EEB65201C8
 CONST UID '45EEB65201C8'
 CONST Name 'has_annotation'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB65201C8 has_annotation

: ME_45EEB65201C9
 CONST UID '45EEB65201C9'
 CONST Name 'has_attributes'
 CONST Class class_Operation
 %SUMMARY 'для документов типа DT_BOOK возвращает false,'#13#10'для остальных true' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB65201C9 has_attributes

: ME_45EEB65201CA
 CONST UID '45EEB65201CA'
 CONST Name 'has_warning'
 CONST Class class_Operation
 %SUMMARY 'Присутствие предупреждения.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB65201CA has_warning

: ME_45EEB65201CB
 CONST UID '45EEB65201CB'
 CONST Name 'is_alive'
 CONST Class class_Operation
 %SUMMARY 'Специальный метод, позволяющий выяснить "жив" ли документ на сервере приложений. Если документ "жив" - возвращается `true` (как правило такая проверка нужна, когда документ может быть удален, например во время обновления базы). Результаты данного метода не кешируются на адаптере, т.е. вызов этого метода всегда обращается к серверу приложений.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB65201CB is_alive

: ME_45EEB65201CD
 CONST Name 'date'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_456EA6F00109' '456EA56002BF.pas.ms.script' // Date
 ;

ref; // ME_45EEB65201CD date

: ME_45EEB65201CC
 CONST UID '45EEB65201CC'
 CONST Name 'is_date_in_not_sure_interval'
 CONST Class class_Operation
 %SUMMARY 'Метод позволяет определить попадает ли date в интервал неуверенности документа.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 : Parameters
   Seq: ( ME_45EEB65201CD // date
 )
 ; // Parameters

ref; // ME_45EEB65201CC is_date_in_not_sure_interval

: ME_45EEB65201CF
 CONST Name 'bookmark'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB65202A0 // Bookmark
 ;

ref; // ME_45EEB65201CF bookmark

: ME_45EEB65201CE
 CONST UID '45EEB65201CE'
 CONST Name 'is_my_bookmark'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 : Parameters
   Seq: ( ME_45EEB65201CF // bookmark
 )
 ; // Parameters

ref; // ME_45EEB65201CE is_my_bookmark

: ME_45EEB65201D1
 CONST Name 'doc'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB6520191 // Document
 ;

ref; // ME_45EEB65201D1 doc

: ME_45EEB65201D0
 CONST UID '45EEB65201D0'
 CONST Name 'is_same_document'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 : Parameters
   Seq: ( ME_45EEB65201D1 // doc
 )
 ; // Parameters

ref; // ME_45EEB65201D0 is_same_document

: ME_45EEB65201D3
 CONST Name 'view'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB6520191 // Document
 ;

ref; // ME_45EEB65201D3 view

: ME_45EEB65201D2
 CONST UID '45EEB65201D2'
 CONST Name 'is_same_redaction'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 : Parameters
   Seq: ( ME_45EEB65201D3 // view
 )
 ; // Parameters

ref; // ME_45EEB65201D2 is_same_redaction

: ME_45EEB65201D5
 CONST Name 'view'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB6520191 // Document
 ;

ref; // ME_45EEB65201D5 view

: ME_45EEB65201D4
 CONST UID '45EEB65201D4'
 CONST Name 'is_same_view'
 CONST Class class_Operation
 %SUMMARY 'Возвращает равенство документов с учетом их состояния (в отличии от is_same_entity, который возвращает равенство без учета состояния). Состоянием документа является суперпозиция номера редакции, языка и списка извлечений.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 : Parameters
   Seq: ( ME_45EEB65201D5 // view
 )
 ; // Parameters

ref; // ME_45EEB65201D4 is_same_view

: ME_45EEB65201D6
 CONST UID '45EEB65201D6'
 CONST Name 'may_show_attributes'
 CONST Class class_Operation
 %SUMMARY 'Проверка возможности отображения атрибутов документа для текущего документа.'#13#10'Возвращает true в случае, если показ атрибутов разрешен.'#13#10''#13#10'для редакций проверяются атрибуты, соответсвующие редакции (т.е. соответсвующие топику редакции )' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB65201D6 may_show_attributes

: ME_45EEB65201D8
 CONST Name 'category'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_45EEB65201D8 category

: ME_45EEB65201D9
 CONST Name 'out_list'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_45EEBA2C02BF' '457450470167.pas.ms.script' // CatalogBase
 ;

ref; // ME_45EEB65201D9 out_list

: ME_45EEB65201D7
 CONST UID '45EEB65201D7'
 CONST Name 'get_correspondents'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Parameters
   Seq: ( ME_45EEB65201D8 // category
 ME_45EEB65201D9 // out_list
 )
 ; // Parameters

ref; // ME_45EEB65201D7 get_correspondents

: ME_45EEB65201DB
 CONST Name 'category'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_45EEB65201DB category

: ME_45EEB65201DC
 CONST Name 'out_list'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_45EEBA2C02BF' '457450470167.pas.ms.script' // CatalogBase
 ;

ref; // ME_45EEB65201DC out_list

: ME_45EEB65201DA
 CONST UID '45EEB65201DA'
 CONST Name 'get_respondents'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Parameters
   Seq: ( ME_45EEB65201DB // category
 ME_45EEB65201DC // out_list
 )
 ; // Parameters

ref; // ME_45EEB65201DA get_respondents

: ME_45EEB65201DF
 CONST UID '45EEB65201DF'
 CONST Name 'has_translation'
 CONST Class class_Operation
 %SUMMARY 'Есть ли у документа перевод' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB65201DF has_translation

: ME_45EEB65201E0
 CONST UID '45EEB65201E0'
 CONST Name 'has_same_documents'
 CONST Class class_Operation
 %SUMMARY 'Проверка наличия похожих документов' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_45EEB65201E0 has_same_documents

: ME_45EEB65201E2
 CONST Name 'out_list'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_45EEBA2C02BF' '457450470167.pas.ms.script' // CatalogBase
 ;

ref; // ME_45EEB65201E2 out_list

: ME_45EEB65201E1
 CONST UID '45EEB65201E1'
 CONST Name 'get_same_documents'
 CONST Class class_Operation
 %SUMMARY 'Получить список похожих документов' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Parameters
   Seq: ( ME_45EEB65201E2 // out_list
 )
 ; // Parameters

ref; // ME_45EEB65201E1 get_same_documents

: ME_462774050102
 CONST UID '462774050102'
 CONST Name 'get_server_doc'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 CONST "dll export" false

ref; // ME_462774050102 get_server_doc

: ME_47569514007B
 CONST Name 'document'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_47569514007B document

: ME_460A76FD02B9
 CONST UID '460A76FD02B9'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_multi_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Parameters
   Seq: ( ME_47569514007B // document
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false
 CONST "transparent multy" false

ref; // ME_460A76FD02B9 make

: ME_4616307501E5
 CONST Name 'pid'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_4616307501E5 pid

: ME_4616307503AB
 CONST Name 'is_edition'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4616307503AB is_edition

: ME_4616307601A7
 CONST Name 'name'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFE240068' '3DBFDB23006E.pas.ms.script' // string
 ;

ref; // ME_4616307601A7 name

: ME_4616303E031E
 CONST UID '4616303E031E'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_multi_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Parameters
   Seq: ( ME_4616307501E5 // pid
 ME_4616307503AB // is_edition
 ME_4616307601A7 // name
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false
 CONST "transparent multy" false

ref; // ME_4616303E031E make

: ME_46CD4B9D030D
 CONST UID '46CD4B9D030D'
 CONST Name 'is_morpho_search_supported'
 CONST Class class_Operation
 %SUMMARY 'индексирован ли документ для морфопоиска' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_46CD4B9D030D is_morpho_search_supported

: ME_47AB300901FA
 CONST Name 'doc_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_47AB300901FA doc_id

: ME_47AB300902F4
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB65202CD // Topic
 ;

ref; // ME_47AB300902F4 id

: ME_47AB300903DE
 CONST Name 'rid'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EED84C01FD // RedactionID
 ;

ref; // ME_47AB300903DE rid

: ME_47AB2FC90361
 CONST UID '47AB2FC90361'
 CONST Name 'get_link_info'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_47AB301C01DC // LinkInfo
 ;
 : Parameters
   Seq: ( ME_47AB300901FA // doc_id
 ME_47AB300902F4 // id
 ME_47AB300903DE // rid
 )
 ; // Parameters

ref; // ME_47AB2FC90361 get_link_info

: ME_4D3D69FE03D4
 CONST Name 'pid'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_456EA676037A' '456EA56002BF.pas.ms.script' // PId
 ;

ref; // ME_4D3D69FE03D4 pid

: ME_47C6B9F101AF
 CONST Name 'missing_info'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target ME_45EEB6520309 // MissingInfo
 ;

ref; // ME_47C6B9F101AF missing_info

: ME_47C6AA260009
 CONST UID '47C6AA260009'
 CONST Name 'get_missing_info_for_object'
 CONST Class class_Operation
 %SUMMARY 'Возвращает расширенную информацию по отсутствующему объекту (pid - идентификатор и класс объекта по ссылке)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Parameters
   Seq: ( ME_4D3D69FE03D4 // pid
 ME_47C6B9F101AF // missing_info
 )
 ; // Parameters

ref; // ME_47C6AA260009 get_missing_info_for_object

: ME_47EBB17D009B
 CONST UID '47EBB17D009B'
 CONST Name 'get_drug_list'
 CONST Class class_Operation
 %SUMMARY 'Получить список выпускаемых фирмой препаратов' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_45EEBA2C02BF' '457450470167.pas.ms.script' // CatalogBase
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018E' '456EA56002BF.pas.ms.script' // CanNotFindData
 )
 ; // CanRaise

ref; // ME_47EBB17D009B get_drug_list

: ME_4857C59403C6
 CONST UID '4857C59403C6'
 CONST Name 'get_flash'
 CONST Class class_Operation
 %SUMMARY 'Получение флеш-ролика' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_45ED932A0044' '45ED922F00A4.pas.ms.script' // ExternalObject
 ;

ref; // ME_4857C59403C6 get_flash

: ME_4A8A9AF7024D
 CONST Name 'para'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB65202AA // ParaId
 ;

ref; // ME_4A8A9AF7024D para

: ME_4A8A9AD600BC
 CONST UID '4A8A9AD600BC'
 CONST Name 'create_journal_bookmark'
 CONST Class class_Operation
 %SUMMARY 'Создать журнальную закладку' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_4A8A8F640192 // JournalBookmark
 ;
 : Parameters
   Seq: ( ME_4A8A9AF7024D // para
 )
 ; // Parameters

ref; // ME_4A8A9AD600BC create_journal_bookmark

: ME_4A9F9CF3006A
 CONST UID '4A9F9CF3006A'
 CONST Name 'get_auto_referat_doc_count'
 CONST Class class_Operation
 %SUMMARY 'вернуть число документов для автореферата' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_4538E9230233' '3DBFDB23006E.pas.ms.script' // size
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018A' '456EA56002BF.pas.ms.script' // Unsupported
 )
 ; // CanRaise

ref; // ME_4A9F9CF3006A get_auto_referat_doc_count

: ME_4CAF1A6700A2
 CONST Name 'all_at_once'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4CAF1A6700A2 all_at_once

: ME_4CAF1A4B0096
 CONST UID '4CAF1A4B0096'
 CONST Name 'get_text_provider'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018A' '456EA56002BF.pas.ms.script' // Unsupported
 WL 'ME_456EB454018E' '456EA56002BF.pas.ms.script' // CanNotFindData
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4CAF1A6700A2 // all_at_once
 )
 ; // Parameters

ref; // ME_4CAF1A4B0096 get_text_provider

: ME_4D6289D601A0
 CONST UID '4D6289D601A0'
 CONST Name 'get_text_provider_desc_list'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_4D628F1402C0 // DocumentTextProviderDescriptorList
 ;
 CONST TargetStereotype 'const,cached'
 : CanRaise
   Seq: ( WL 'ME_456EB454018A' '456EA56002BF.pas.ms.script' // Unsupported
 )
 ; // CanRaise

ref; // ME_4D6289D601A0 get_text_provider_desc_list

: ME_4D62921A0371
 CONST Name 'handle'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4D62921A0371 handle

: ME_4D6291D500E7
 CONST UID '4D6291D500E7'
 CONST Name 'get_text_provider_by_desc'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_4C5AA5CA02DF // DocumentTextProvider
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018A' '456EA56002BF.pas.ms.script' // Unsupported
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4D62921A0371 // handle
 )
 ; // Parameters

ref; // ME_4D6291D500E7 get_text_provider_by_desc

: ME_4CED4A1203C4
 CONST Name 'all_at_once'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4CED4A1203C4 all_at_once

: ME_4CED4A090217
 CONST UID '4CED4A090217'
 CONST Name 'get_text_provider_list'
 CONST Class class_Operation
 : Stereotype st_chg::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_4CED493F01B9 // DocumentTextProviderList
 ;
 CONST TargetStereotype 'const,cached'
 : CanRaise
   Seq: ( WL 'ME_456EB454018A' '456EA56002BF.pas.ms.script' // Unsupported
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4CED4A1203C4 // all_at_once
 )
 ; // Parameters

ref; // ME_4CED4A090217 get_text_provider_list

: ME_4D023C95027A
 CONST UID '4D023C95027A'
 CONST Name 'get_autoreferat_header_evd'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_4423FB5903D8' '4423F94903C8.pas.ms.script' // Stream
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018A' '456EA56002BF.pas.ms.script' // Unsupported
 )
 ; // CanRaise

ref; // ME_4D023C95027A get_autoreferat_header_evd

: ME_4D02499F002C
 CONST Name 'handle'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4D02499F002C handle

: ME_4D023D3B02B4
 CONST UID '4D023D3B02B4'
 CONST Name 'get_annotation_header_evd'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_4423FB5903D8' '4423F94903C8.pas.ms.script' // Stream
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018A' '456EA56002BF.pas.ms.script' // Unsupported
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4D02499F002C // handle
 )
 ; // Parameters

ref; // ME_4D023D3B02B4 get_annotation_header_evd

: ME_4CC8135C000E
 CONST Name 'pid'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_4CC8135C000E pid

: ME_4CC8134700E6
 CONST UID '4CC8134700E6'
 CONST Name 'diff'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_4CC80F7E02BB // DiffData
 ;
 : Parameters
   Seq: ( ME_4CC8135C000E // pid
 )
 ; // Parameters
 CONST "dll export" false

ref; // ME_4CC8134700E6 diff

: ME_4CE3E9DF02B0
 CONST UID '4CE3E9DF02B0'
 CONST Name 'get_evd_stream'
 CONST Class class_Operation
 %SUMMARY 'возвращает evd поток документа - совета дня или evd поток заглушки для отсутствующего в базе документа или документа запрещенного к просмотру' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_4423FB5903D8' '4423F94903C8.pas.ms.script' // Stream
 ;

ref; // ME_4CE3E9DF02B0 get_evd_stream

: ME_4D3D6F9500AA
 CONST Name 'missing_info'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target ME_45EEB6520309 // MissingInfo
 ;

ref; // ME_4D3D6F9500AA missing_info

: ME_4D3D6F030110
 CONST UID '4D3D6F030110'
 CONST Name 'get_self_missing_info'
 CONST Class class_Operation
 %SUMMARY 'Получить расширенную информацию по текущему документу (в случае его отсутствия - в каких блоках этот документ присутствует)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Parameters
   Seq: ( ME_4D3D6F9500AA // missing_info
 )
 ; // Parameters

ref; // ME_4D3D6F030110 get_self_missing_info

: ME_4DCBB6B803A5
 CONST Name 'doc_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4DCBB6B803A5 doc_id

: ME_4DCBB6B900C4
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB65202CD // Topic
 ;

ref; // ME_4DCBB6B900C4 id

: ME_4DCBB65D028F
 CONST UID '4DCBB65D028F'
 CONST Name 'get_multi_link_info'
 CONST Class class_Operation
 %SUMMARY 'Получить данные по мульnиссылке в виде списка (DocId, SubId)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_4DCBBAEF025F // DocPointList
 ;
 : CanRaise
   Seq: ( WL 'ME_456EB454018E' '456EA56002BF.pas.ms.script' // CanNotFindData
 WL 'ME_462F037A0337' '456EA56002BF.pas.ms.script' // InternalDatabaseError
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4DCBB6B803A5 // doc_id
 ME_4DCBB6B900C4 // id
 )
 ; // Parameters

ref; // ME_4DCBB65D028F get_multi_link_info

: ME_4F1E5DE102BE
 CONST UID '4F1E5DE102BE'
 CONST Name 'dont_show_document_status_changes_warning'
 CONST Class class_Operation
 %SUMMARY 'Не показывать статус изменения данного документа в текущей сессии' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;

ref; // ME_4F1E5DE102BE dont_show_document_status_changes_warning

: ME_528376540040
 CONST UID '528376540040'
 CONST Name 'get_redaction_pid'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 CONST "dll export" false

ref; // ME_528376540040 get_redaction_pid

: ME_53C3BD6F0050
 CONST UID '53C3BD6F0050'
 CONST Name 'has_chronology'
 CONST Class class_Operation
 %SUMMARY 'есть ли у документа хронология рассмотрения судебного дела'#13#10'K555095873' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_53C3BD6F0050 has_chronology

: ME_53E9F34E0322
 CONST Name 'doc_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_53E9F34E0322 doc_id

: ME_53E9F34E03B0
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB65202CD // Topic
 ;

ref; // ME_53E9F34E03B0 id

: ME_53E9F34F0056
 CONST Name 'rid'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EED84C01FD // RedactionID
 ;

ref; // ME_53E9F34F0056 rid

: ME_53E9F3420066
 CONST UID '53E9F3420066'
 CONST Name 'get_link'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Target ME_51A6183C010F // Link
 ;
 : Parameters
   Seq: ( ME_53E9F34E0322 // doc_id
 ME_53E9F34E03B0 // id
 ME_53E9F34F0056 // rid
 )
 ; // Parameters

ref; // ME_53E9F3420066 get_link

: ME_5582DAA7015C
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4C5AB32B03A5 // ExternalID
 ;

ref; // ME_5582DAA7015C id

: ME_5582DAA701F1
 CONST Name 'out_list'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_45EEBA2C02BF' '457450470167.pas.ms.script' // CatalogBase
 ;

ref; // ME_5582DAA701F1 out_list

: ME_5582DAA202AD
 CONST UID '5582DAA202AD'
 CONST Name 'get_same_to_point'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB6520191 // Document
 ;
 : Parameters
   Seq: ( ME_5582DAA7015C // id
 ME_5582DAA701F1 // out_list
 )
 ; // Parameters

ref; // ME_5582DAA202AD get_same_to_point

: ME_456EB3E10178_ME_45EEB6520191
 : Original WL 'ME_456EB3E10178' '456EA56002BF.pas.ms.script' // save_to
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
ref; // ME_456EB3E10178_ME_45EEB6520191 save_to

: ME_456EB3E1017A_ME_45EEB6520191
 : Original WL 'ME_456EB3E1017A' '456EA56002BF.pas.ms.script' // append_to
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
ref; // ME_456EB3E1017A_ME_45EEB6520191 append_to

: ME_456EB3E1017C_ME_45EEB6520191
 : Original WL 'ME_456EB3E1017C' '456EA56002BF.pas.ms.script' // is_saved
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_456EB3E1017C_ME_45EEB6520191 is_saved

: ME_456EB3E1017D_ME_45EEB6520191
 : Original WL 'ME_456EB3E1017D' '456EA56002BF.pas.ms.script' // is_changed
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_456EB3E1017D_ME_45EEB6520191 is_changed

: ME_456EE084033C_ME_45EEB6520191
 : Original WL 'ME_456EE084033C' '456EA56002BF.pas.ms.script' // eid
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_456EE084033C_ME_45EEB6520191 eid

: ME_45EEC17501B6_ME_45EEB6520191
 : Original WL 'ME_45EEC17501B6' '45EEAA800226.pas.ms.script' // get_control_status
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
ref; // ME_45EEC17501B6_ME_45EEB6520191 get_control_status

: ME_45EEC17501B7_ME_45EEB6520191
 : Original WL 'ME_45EEC17501B7' '45EEAA800226.pas.ms.script' // reset_control_status
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
ref; // ME_45EEC17501B7_ME_45EEB6520191 reset_control_status

: ME_45EEC17501B8_ME_45EEB6520191
 : Original WL 'ME_45EEC17501B8' '45EEAA800226.pas.ms.script' // open
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
ref; // ME_45EEC17501B8_ME_45EEB6520191 open

: ME_45EEC17501B9_ME_45EEB6520191
 : Original WL 'ME_45EEC17501B9' '45EEAA800226.pas.ms.script' // is_same_controllable
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
ref; // ME_45EEC17501B9_ME_45EEB6520191 is_same_controllable

: ME_45EEC17501BB_ME_45EEB6520191
 : Original WL 'ME_45EEC17501BB' '45EEAA800226.pas.ms.script' // controlled
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_45EEC17501BB_ME_45EEB6520191 controlled

: ME_45EEC17501BC_ME_45EEB6520191
 : Original WL 'ME_45EEC17501BC' '45EEAA800226.pas.ms.script' // short_name
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_45EEC17501BC_ME_45EEB6520191 short_name

: ME_45FA9A9C00F5_ME_45EEB6520191
 : Original WL 'ME_45FA9A9C00F5' '45EEAA800226.pas.ms.script' // type
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_45FA9A9C00F5_ME_45EEB6520191 type

: ME_48EF5B3402B5_ME_45EEB6520191
 : Original WL 'ME_48EF5B3402B5' '45EEAA800226.pas.ms.script' // can_set_to_control
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_48EF5B3402B5_ME_45EEB6520191 can_set_to_control

: ME_4BFE1E970136_ME_45EEB6520191
 : Original WL 'ME_4BFE1E970136' '45EEAA800226.pas.ms.script' // name
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4BFE1E970136_ME_45EEB6520191 name

: ME_4FEAFD48024F_ME_45EEB6520191
 : Original ME_4FEAFD48024F // like
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4FEAFD48024F_ME_45EEB6520191 like

: ME_4FEAFD5D03D1_ME_45EEB6520191
 : Original ME_4FEAFD5D03D1 // unlike
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4FEAFD5D03D1_ME_45EEB6520191 unlike

: ME_4FEAFD79015E_ME_45EEB6520191
 : Original ME_4FEAFD79015E // can_like
 ;
 : Implementor ME_45EEB6520191 // Document
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4FEAFD79015E_ME_45EEB6520191 can_like

: ME_45EEB6520191
 CONST UID '45EEB6520191'
 CONST GUID '2906776F-DD41-403A-AF10-DDD0F9BD6590'
 CONST Name 'Document'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Интерфейс обеспечивающий работу с документом.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( WL 'ME_456EB3E10177' '456EA56002BF.pas.ms.script' // EntityBase
 WL 'ME_45EEC17501B5' '45EEAA800226.pas.ms.script' // Controllable
 ME_4FEAFCB6035C // Likeable
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_45EEB65201E3 // name
 ME_45EEB65201E4 // short_name
 ME_45EEB65201E5 // warning
 ME_45EEB65201E6 // size
 ME_45EEB65201E7 // internal_id
 ME_48285D28025E // not_tm
 ME_496B249601F3 // file_position
 ME_4BC323A60337 // new_revision_available
 ME_4D7E231702E4 // change_status
 ME_45EEBECB019A // status
 ME_45EEBF0F014B // text_languages
 ME_45EEC00F006F // attributes_root
 ME_45EED8FA017F // redactions_list
 ME_45EED98D00E1 // current_state
 ME_460B80CF0201 // doc_type
 ME_460B8F6A02B2 // translation
 ME_460B8F8F0002 // annotation
 ME_460B8FD603AB // related_doc
 ME_47ED1B17039A // 
 ME_4C77A3370186 // contents_root
 ME_4D147C7602A6 // bookmark_list
 ME_4D147CCA0051 // comments_para_list
 ME_4D14816D015F // external_object_data_list
 )
 ; // Attributes
 : Operations
   Seq: ( ME_45EEB6520194 // create_bookmark
 ME_45EEB6520197 // create_view
 ME_45EEB6520199 // get_correspondents_to_part
 ME_45EEB652019D // get_internet_image_url
 ME_45EEB65201A3 // get_linked_object
 ME_45EEB65201AA // get_not_sure_info
 ME_45EEB65201B0 // get_respondents_to_part
 ME_45EEB65201BE // get_time_machine_warning
 ME_45EEB65201C0 // has_correspondents
 ME_45EEB65201C2 // has_internet_image
 ME_45EEB65201C3 // has_next_redaction
 ME_45EEB65201C4 // has_prev_redaction
 ME_45EEB65201C5 // has_related_doc
 ME_45EEB65201C6 // has_respondents
 ME_45EEB65201C8 // has_annotation
 ME_45EEB65201C9 // has_attributes
 ME_45EEB65201CA // has_warning
 ME_45EEB65201CB // is_alive
 ME_45EEB65201CC // is_date_in_not_sure_interval
 ME_45EEB65201CE // is_my_bookmark
 ME_45EEB65201D0 // is_same_document
 ME_45EEB65201D2 // is_same_redaction
 ME_45EEB65201D4 // is_same_view
 ME_45EEB65201D6 // may_show_attributes
 ME_45EEB65201D7 // get_correspondents
 ME_45EEB65201DA // get_respondents
 ME_45EEB65201DF // has_translation
 ME_45EEB65201E0 // has_same_documents
 ME_45EEB65201E1 // get_same_documents
 ME_462774050102 // get_server_doc
 ME_460A76FD02B9 // make
 ME_4616303E031E // make
 ME_46CD4B9D030D // is_morpho_search_supported
 ME_47AB2FC90361 // get_link_info
 ME_47C6AA260009 // get_missing_info_for_object
 ME_47EBB17D009B // get_drug_list
 ME_4857C59403C6 // get_flash
 ME_4A8A9AD600BC // create_journal_bookmark
 ME_4A9F9CF3006A // get_auto_referat_doc_count
 ME_4CAF1A4B0096 // get_text_provider
 ME_4D6289D601A0 // get_text_provider_desc_list
 ME_4D6291D500E7 // get_text_provider_by_desc
 ME_4CED4A090217 // get_text_provider_list
 ME_4D023C95027A // get_autoreferat_header_evd
 ME_4D023D3B02B4 // get_annotation_header_evd
 ME_4CC8134700E6 // diff
 ME_4CE3E9DF02B0 // get_evd_stream
 ME_4D3D6F030110 // get_self_missing_info
 ME_4DCBB65D028F // get_multi_link_info
 ME_4F1E5DE102BE // dont_show_document_status_changes_warning
 ME_528376540040 // get_redaction_pid
 ME_53C3BD6F0050 // has_chronology
 ME_53E9F3420066 // get_link
 ME_5582DAA202AD // get_same_to_point
 )
 ; // Operations
 : Implemented
   Seq: ( ME_456EB3E10178_ME_45EEB6520191 // save_to
 ME_456EB3E1017A_ME_45EEB6520191 // append_to
 ME_456EB3E1017C_ME_45EEB6520191 // is_saved
 ME_456EB3E1017D_ME_45EEB6520191 // is_changed
 ME_456EE084033C_ME_45EEB6520191 // eid
 ME_45EEC17501B6_ME_45EEB6520191 // get_control_status
 ME_45EEC17501B7_ME_45EEB6520191 // reset_control_status
 ME_45EEC17501B8_ME_45EEB6520191 // open
 ME_45EEC17501B9_ME_45EEB6520191 // is_same_controllable
 ME_45EEC17501BB_ME_45EEB6520191 // controlled
 ME_45EEC17501BC_ME_45EEB6520191 // short_name
 ME_45FA9A9C00F5_ME_45EEB6520191 // type
 ME_48EF5B3402B5_ME_45EEB6520191 // can_set_to_control
 ME_4BFE1E970136_ME_45EEB6520191 // name
 ME_4FEAFD48024F_ME_45EEB6520191 // like
 ME_4FEAFD5D03D1_ME_45EEB6520191 // unlike
 ME_4FEAFD79015E_ME_45EEB6520191 // can_like
 )
 ; // Implemented
 : Forwarded
   Seq: ( ME_45EEB65202A0 // Bookmark
 ME_45EED80E0086 // DocumentState
 ME_4A8A8F640192 // JournalBookmark
 ME_51A6183C010F // Link
 )
 ; // Forwarded
 CONST "single impl" false
 CONST extprop:pas:TypeName 'IDocument'
 CONST extprop:rc:SelfName 'Document'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_45EEB6520191 Document

: ME_45EEB65202A2
 CONST UID '45EEB65202A2'
 CONST Name 'name'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 %SUMMARY 'Названите закладки. Используется в качестве caption в Папках.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB65202A0 // Bookmark
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_45EEB65202A2 name

: ME_45EEB65202A3
 CONST UID '45EEB65202A3'
 CONST Name 'comment'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 %SUMMARY 'полное имя документа и блока/саба на который указывает закладка. Используется в качестве hint  в Папках.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB65202A0 // Bookmark
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_45EEB65202A3 comment

: ME_460B8DAF01AE
 CONST UID '460B8DAF01AE'
 CONST Name 'paragraph'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB65202A0 // Bookmark
 ;
 : Target ME_45EEB65202AA // ParaId
 ;
 CONST "pm" false

ref; // ME_460B8DAF01AE paragraph

: ME_460B8E3401FB
 CONST UID '460B8E3401FB'
 CONST Name 'pid'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EEB65202A0 // Bookmark
 ;
 : Target WL 'ME_456EA676037A' '456EA56002BF.pas.ms.script' // PId
 ;
 CONST "pm" false

ref; // ME_460B8E3401FB pid

: ME_460B8EF302A4
 CONST UID '460B8EF302A4'
 CONST Name 'document'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_45EEB65202A0 // Bookmark
 ;
 : Target ME_45EEB6520191 // Document
 ;
 CONST "pm" false

ref; // ME_460B8EF302A4 document

: ME_4610F9F40317
 CONST Name 'bookmark'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_4610F9F40317 bookmark

: ME_4610F9F40385
 CONST Name 'doc_bookmark'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_4610F9F40385 doc_bookmark

: ME_46160CE200BB
 CONST Name 'folders_node'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_45EED5F0008E' '4570501E037A.pas.ms.script' // FoldersNode
 ;

ref; // ME_46160CE200BB folders_node

: ME_4610F983004B
 CONST UID '4610F983004B'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EEB65202A0 // Bookmark
 ;
 : Parameters
   Seq: ( ME_4610F9F40317 // bookmark
 ME_4610F9F40385 // doc_bookmark
 ME_46160CE200BB // folders_node
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false

ref; // ME_4610F983004B make

: ME_456EB3E10178_ME_45EEB65202A0
 : Original WL 'ME_456EB3E10178' '456EA56002BF.pas.ms.script' // save_to
 ;
 : Implementor ME_45EEB65202A0 // Bookmark
 ;
 CONST OpKind opkind_Implemented
ref; // ME_456EB3E10178_ME_45EEB65202A0 save_to

: ME_456EB3E1017A_ME_45EEB65202A0
 : Original WL 'ME_456EB3E1017A' '456EA56002BF.pas.ms.script' // append_to
 ;
 : Implementor ME_45EEB65202A0 // Bookmark
 ;
 CONST OpKind opkind_Implemented
ref; // ME_456EB3E1017A_ME_45EEB65202A0 append_to

: ME_456EB3E1017C_ME_45EEB65202A0
 : Original WL 'ME_456EB3E1017C' '456EA56002BF.pas.ms.script' // is_saved
 ;
 : Implementor ME_45EEB65202A0 // Bookmark
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_456EB3E1017C_ME_45EEB65202A0 is_saved

: ME_456EB3E1017D_ME_45EEB65202A0
 : Original WL 'ME_456EB3E1017D' '456EA56002BF.pas.ms.script' // is_changed
 ;
 : Implementor ME_45EEB65202A0 // Bookmark
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_456EB3E1017D_ME_45EEB65202A0 is_changed

: ME_456EE084033C_ME_45EEB65202A0
 : Original WL 'ME_456EE084033C' '456EA56002BF.pas.ms.script' // eid
 ;
 : Implementor ME_45EEB65202A0 // Bookmark
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_456EE084033C_ME_45EEB65202A0 eid

: ME_45EEB65202A0
 CONST UID '45EEB65202A0'
 CONST GUID '830AC32A-C3AC-4AA1-A5A1-0ACAE229DD2A'
 CONST Name 'Bookmark'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Закладка на документ. Используется для сохранения документа (и позиции) в папках.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( WL 'ME_456EB3E10177' '456EA56002BF.pas.ms.script' // EntityBase
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_45EEB65202A2 // name
 ME_45EEB65202A3 // comment
 ME_460B8DAF01AE // paragraph
 ME_460B8E3401FB // pid
 ME_460B8EF302A4 // document
 )
 ; // Attributes
 : Operations
   Seq: ( ME_4610F983004B // make
 )
 ; // Operations
 : Implemented
   Seq: ( ME_456EB3E10178_ME_45EEB65202A0 // save_to
 ME_456EB3E1017A_ME_45EEB65202A0 // append_to
 ME_456EB3E1017C_ME_45EEB65202A0 // is_saved
 ME_456EB3E1017D_ME_45EEB65202A0 // is_changed
 ME_456EE084033C_ME_45EEB65202A0 // eid
 )
 ; // Implemented
 CONST "single impl" false
 CONST extprop:pas:TypeName 'IBookmark'
 CONST extprop:rc:SelfName 'Bookmark'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_45EEB65202A0 Bookmark

: ME_460A40CB01F0
 CONST UID '460A40CB01F0'
 CONST Name 'language'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : Target WL 'ME_456EB2F1034B' '456EA56002BF.pas.ms.script' // Languages
 ;
 CONST "pm" false

ref; // ME_460A40CB01F0 language

: ME_4A81280E02DE
 CONST UID '4A81280E02DE'
 CONST Name 'prev_redactions_list'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : Target ME_45EED8DE0121 // RedactionInfoList
 ;
 CONST "pm" false

ref; // ME_4A81280E02DE prev_redactions_list

: ME_4B556B8F02C1
 CONST UID '4B556B8F02C1'
 CONST Name 'cur_and_next_redactions_list'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY '[$178324034]' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : Target ME_45EED8DE0121 // RedactionInfoList
 ;
 CONST "pm" false

ref; // ME_4B556B8F02C1 cur_and_next_redactions_list

: ME_45EED80E0087
 CONST UID '45EED80E0087'
 CONST Name 'set_prev_redaction'
 CONST Class class_Operation
 %SUMMARY 'Операция устанавливает в качестве текущей предыдущую редакцию объекта.'#13#10'Если предыдущей редакции нет, то возвращается RedactionNotFound.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : CanRaise
   Seq: ( ME_45EED9780391 // RedactionNotFound
 )
 ; // CanRaise

ref; // ME_45EED80E0087 set_prev_redaction

: ME_45EED80E0088
 CONST UID '45EED80E0088'
 CONST Name 'set_next_redaction'
 CONST Class class_Operation
 %SUMMARY 'Операция устанавливает в качестве текущей следующую редакцию объекта.'#13#10'Если следующей редакции нет, то возвращается RedactionNotFound.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : CanRaise
   Seq: ( ME_45EED9780391 // RedactionNotFound
 )
 ; // CanRaise

ref; // ME_45EED80E0088 set_next_redaction

: ME_45EED80E008A
 CONST Name 'date'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_456EA6F00109' '456EA56002BF.pas.ms.script' // Date
 ;

ref; // ME_45EED80E008A date

: ME_45EED80E0089
 CONST UID '45EED80E0089'
 CONST Name 'set_redaction_on_date'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : CanRaise
   Seq: ( ME_45EED9780391 // RedactionNotFound
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_45EED80E008A // date
 )
 ; // Parameters

ref; // ME_45EED80E0089 set_redaction_on_date

: ME_45EED80E008C
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EED84C01FD // RedactionID
 ;

ref; // ME_45EED80E008C id

: ME_45EED80E008B
 CONST UID '45EED80E008B'
 CONST Name 'set_redaction_on_id'
 CONST Class class_Operation
 %SUMMARY 'Операция устанавливает в качестве текущей редакцию с заданным идентификатором.'#13#10'Возвращает True в случае если текущая редакиция изменилась и False, если осталась той же самой, что и до вызова метода.'#13#10'Если задан неверный идентификатор редакции, то возвращается InvalidRedactionId.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : CanRaise
   Seq: ( ME_45EED9780391 // RedactionNotFound
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_45EED80E008C // id
 )
 ; // Parameters

ref; // ME_45EED80E008B set_redaction_on_id

: ME_45EED80E008D
 CONST UID '45EED80E008D'
 CONST Name 'set_actual_redaction'
 CONST Class class_Operation
 %SUMMARY 'Операция устанавливает в качестве текущей редакцию, актуальную редакцию для данного документа.'#13#10'Возвращает True в случае если текущая редакиция изменилась и False, если осталась той же самой, что и до вызова метода.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : CanRaise
   Seq: ( ME_45EED9780391 // RedactionNotFound
 )
 ; // CanRaise

ref; // ME_45EED80E008D set_actual_redaction

: ME_46289947018D
 CONST UID '46289947018D'
 CONST Name 'redaction'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : Target ME_45EED84C01FD // RedactionID
 ;

ref; // ME_46289947018D redaction

: ME_46320AD6033A
 CONST UID '46320AD6033A'
 CONST Name 'get_current_redaction'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : Target ME_45EED83A00C4 // RedactionInfo
 ;

ref; // ME_46320AD6033A get_current_redaction

: ME_4628CAFF0282
 CONST Name 'other'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EED80E0086 // DocumentState
 ;

ref; // ME_4628CAFF0282 other

: ME_4628CAEB0169
 CONST UID '4628CAEB0169'
 CONST Name 'is_same_redactions'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 : Parameters
   Seq: ( ME_4628CAFF0282 // other
 )
 ; // Parameters

ref; // ME_4628CAEB0169 is_same_redactions

: ME_4628D6BE01A4
 CONST Name 'source_doc'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target ME_45EEB6520191 // Document
 ;

ref; // ME_4628D6BE01A4 source_doc

: ME_4628CE6F02EA
 CONST UID '4628CE6F02EA'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : Parameters
   Seq: ( ME_4628D6BE01A4 // source_doc
 )
 ; // Parameters
 CONST "const_type" 'read-write'

ref; // ME_4628CE6F02EA make

: ME_4756B7190023
 CONST UID '4756B7190023'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 CONST "const_type" 'read-write'
 CONST "dll export" false

ref; // ME_4756B7190023 make

: ME_4CC972D302BD
 CONST Name 'id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EED84C01FD // RedactionID
 ;

ref; // ME_4CC972D302BD id

: ME_4CC972C00194
 CONST UID '4CC972C00194'
 CONST Name 'diff_with_redaction_by_id'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : Target ME_4CC80F7E02BB // DiffData
 ;
 : Parameters
   Seq: ( ME_4CC972D302BD // id
 )
 ; // Parameters

ref; // ME_4CC972C00194 diff_with_redaction_by_id

: ME_4A8130CE0320
 CONST UID '4A8130CE0320'
 CONST Name 'clone'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : Target ME_45EED80E0086 // DocumentState
 ;

ref; // ME_4A8130CE0320 clone

: ME_4B545717011B
 CONST UID '4B545717011B'
 CONST Name 'set_prev_active_redaction'
 CONST Class class_Operation
 %SUMMARY 'GetБлижайшаяДействующаяРедакцияВниз. [$178325284]' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : CanRaise
   Seq: ( ME_45EED9780391 // RedactionNotFound
 )
 ; // CanRaise

ref; // ME_4B545717011B set_prev_active_redaction

: ME_4B54571C028B
 CONST UID '4B54571C028B'
 CONST Name 'can_compare_with_any_other_redaction'
 CONST Class class_Operation
 %SUMMARY '[$178325284]' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4B54571C028B can_compare_with_any_other_redaction

: ME_4EE7512C0058
 CONST UID '4EE7512C0058'
 CONST Name 'is_actual'
 CONST Class class_Operation
 %SUMMARY 'возвращает true, если эта редакция актуальная, т. е. имеет тип:'#13#10'- RT_ACTUAL'#13#10'- RT_ACTUAL_ABOLISHED'#13#10'- RT_ACTUAL_PREACTIVE' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_45EED80E0086 // DocumentState
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4EE7512C0058 is_actual

: ME_45EED80E0086
 CONST UID '45EED80E0086'
 CONST GUID '71C2A950-3D61-44A9-A0FA-845C4A9F5B97'
 CONST Name 'DocumentState'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Интерфейс для работы с редакциями объекта.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_460A40CB01F0 // language
 ME_4A81280E02DE // prev_redactions_list
 ME_4B556B8F02C1 // cur_and_next_redactions_list
 )
 ; // Attributes
 : Operations
   Seq: ( ME_45EED80E0087 // set_prev_redaction
 ME_45EED80E0088 // set_next_redaction
 ME_45EED80E0089 // set_redaction_on_date
 ME_45EED80E008B // set_redaction_on_id
 ME_45EED80E008D // set_actual_redaction
 ME_46289947018D // redaction
 ME_46320AD6033A // get_current_redaction
 ME_4628CAEB0169 // is_same_redactions
 ME_4628CE6F02EA // make
 ME_4756B7190023 // make
 ME_4CC972C00194 // diff_with_redaction_by_id
 ME_4A8130CE0320 // clone
 ME_4B545717011B // set_prev_active_redaction
 ME_4B54571C028B // can_compare_with_any_other_redaction
 ME_4EE7512C0058 // is_actual
 )
 ; // Operations
 CONST "single impl" false
 CONST extprop:pas:TypeName 'IDocumentState'
 CONST extprop:rc:SelfName 'DocumentState'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_45EED80E0086 DocumentState

: ME_4ED7B9ED0009
 CONST UID '4ED7B9ED0009'
 CONST Name 'AllChangesInTables'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;

ref; // ME_4ED7B9ED0009 AllChangesInTables

: ME_4A8A8F7A0191
 CONST UID '4A8A8F7A0191'
 CONST Name 'name'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Имя' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4A8A8F640192 // JournalBookmark
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_4A8A8F7A0191 name

: ME_4A8A8F890057
 CONST UID '4A8A8F890057'
 CONST Name 'full_name'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Полное имя (хинт)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4A8A8F640192 // JournalBookmark
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_4A8A8F890057 full_name

: ME_4A8A8FA300D3
 CONST UID '4A8A8FA300D3'
 CONST Name 'para_id'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4A8A8F640192 // JournalBookmark
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;
 CONST "pm" false

ref; // ME_4A8A8FA300D3 para_id

: ME_4A8A8FDD0333
 CONST UID '4A8A8FDD0333'
 CONST Name 'document'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4A8A8F640192 // JournalBookmark
 ;
 : Target ME_45EEB6520191 // Document
 ;
 CONST "pm" false

ref; // ME_4A8A8FDD0333 document

: ME_4A8A93C6027E
 CONST Name 'doc_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_456EA5EF01A5' '456EA56002BF.pas.ms.script' // ObjectId
 ;

ref; // ME_4A8A93C6027E doc_id

: ME_4A8A93C602AE
 CONST Name 'para_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB65202AA // ParaId
 ;

ref; // ME_4A8A93C602AE para_id

: ME_4A8A90180004
 CONST UID '4A8A90180004'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4A8A8F640192 // JournalBookmark
 ;
 : Parameters
   Seq: ( ME_4A8A93C6027E // doc_id
 ME_4A8A93C602AE // para_id
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false

ref; // ME_4A8A90180004 make

: ME_4A8A9A9500C8
 CONST Name 'journal_bookmark'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_4A8A9A9500C8 journal_bookmark

: ME_4A8A9A95009B
 CONST UID '4A8A9A95009B'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4A8A8F640192 // JournalBookmark
 ;
 : Parameters
   Seq: ( ME_4A8A9A9500C8 // journal_bookmark
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false

ref; // ME_4A8A9A95009B make

: ME_4A8AA1170230
 CONST UID '4A8AA1170230'
 CONST Name 'get_journal_bookmark'
 CONST Class class_Operation
 %SUMMARY 'Получить  серверную журнальную закладку' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4A8A8F640192 // JournalBookmark
 ;
 CONST TargetStereotype 'const,cached'
 CONST "dll export" false

ref; // ME_4A8AA1170230 get_journal_bookmark

: ME_456EB3E10178_ME_4A8A8F640192
 : Original WL 'ME_456EB3E10178' '456EA56002BF.pas.ms.script' // save_to
 ;
 : Implementor ME_4A8A8F640192 // JournalBookmark
 ;
 CONST OpKind opkind_Implemented
ref; // ME_456EB3E10178_ME_4A8A8F640192 save_to

: ME_456EB3E1017A_ME_4A8A8F640192
 : Original WL 'ME_456EB3E1017A' '456EA56002BF.pas.ms.script' // append_to
 ;
 : Implementor ME_4A8A8F640192 // JournalBookmark
 ;
 CONST OpKind opkind_Implemented
ref; // ME_456EB3E1017A_ME_4A8A8F640192 append_to

: ME_456EB3E1017C_ME_4A8A8F640192
 : Original WL 'ME_456EB3E1017C' '456EA56002BF.pas.ms.script' // is_saved
 ;
 : Implementor ME_4A8A8F640192 // JournalBookmark
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_456EB3E1017C_ME_4A8A8F640192 is_saved

: ME_456EB3E1017D_ME_4A8A8F640192
 : Original WL 'ME_456EB3E1017D' '456EA56002BF.pas.ms.script' // is_changed
 ;
 : Implementor ME_4A8A8F640192 // JournalBookmark
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_456EB3E1017D_ME_4A8A8F640192 is_changed

: ME_456EE084033C_ME_4A8A8F640192
 : Original WL 'ME_456EE084033C' '456EA56002BF.pas.ms.script' // eid
 ;
 : Implementor ME_4A8A8F640192 // JournalBookmark
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_456EE084033C_ME_4A8A8F640192 eid

: ME_4A8A8F640192
 CONST UID '4A8A8F640192'
 CONST GUID '7EC5D2E1-6B5C-4C7E-AE21-C98E21A8D018'
 CONST Name 'JournalBookmark'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Журнальная закладка' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( WL 'ME_456EB3E10177' '456EA56002BF.pas.ms.script' // EntityBase
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_4A8A8F7A0191 // name
 ME_4A8A8F890057 // full_name
 ME_4A8A8FA300D3 // para_id
 ME_4A8A8FDD0333 // document
 )
 ; // Attributes
 : Operations
   Seq: ( ME_4A8A90180004 // make
 ME_4A8A9A95009B // make
 ME_4A8AA1170230 // get_journal_bookmark
 )
 ; // Operations
 : Implemented
   Seq: ( ME_456EB3E10178_ME_4A8A8F640192 // save_to
 ME_456EB3E1017A_ME_4A8A8F640192 // append_to
 ME_456EB3E1017C_ME_4A8A8F640192 // is_saved
 ME_456EB3E1017D_ME_4A8A8F640192 // is_changed
 ME_456EE084033C_ME_4A8A8F640192 // eid
 )
 ; // Implemented
 CONST "single impl" false
 CONST extprop:pas:TypeName 'IJournalBookmark'
 CONST extprop:rc:SelfName 'JournalBookmark'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4A8A8F640192 JournalBookmark

: ME_4DE8CFB302F4
 CONST UID '4DE8CFB302F4'
 CONST Name 'DocumentLayerID'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Inherits
   Seq: ( ME_4C5AA63D01ED // LayerID
 )
 ; // Inherits
 CONST "force usage" true
 CONST extprop:pas:TypeName 'TDocumentLayerID'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4DE8CFB302F4 DocumentLayerID

: ME_5217397D0258
 CONST Name 'doc_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_5217397D0258 doc_id

: ME_5217397D026D
 CONST Name 'topic'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB65202CD // Topic
 ;

ref; // ME_5217397D026D topic

: ME_5217397D0284
 CONST Name 'redaction_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EED84C01FD // RedactionID
 ;

ref; // ME_5217397D0284 redaction_id

: ME_51A6185B0344
 CONST UID '51A6185B0344'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_51A6183C010F // Link
 ;
 : Parameters
   Seq: ( ME_5217397D0258 // doc_id
 ME_5217397D026D // topic
 ME_5217397D0284 // redaction_id
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false

ref; // ME_51A6185B0344 make

: ME_51A61ED6005B
 CONST UID '51A61ED6005B'
 CONST Name 'get_object_type'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_51A6183C010F // Link
 ;
 : Target ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_51A61ED6005B get_object_type

: ME_51A61EF0013E
 CONST UID '51A61EF0013E'
 CONST Name 'get_object'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_51A6183C010F // Link
 ;
 : Target WL 'ME_4242EBBB03B9' '3DBFDB23006E.pas.ms.script' // object
 ;
 : CanRaise
   Seq: ( ME_45EEB6520321 // InvalidTopicId
 ME_45EEB6520328 // FolderLinkNotFound
 ME_45EEDAD60237 // NotAllowedInTrialMode
 )
 ; // CanRaise

ref; // ME_51A61EF0013E get_object

: ME_51A745CE0034
 CONST UID '51A745CE0034'
 CONST Name 'get_link_info'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_51A6183C010F // Link
 ;
 : Target ME_47AB301C01DC // LinkInfo
 ;

ref; // ME_51A745CE0034 get_link_info

: ME_51AC814F0388
 CONST UID '51AC814F0388'
 CONST Name 'get_linked_hint'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_51A6183C010F // Link
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_51AC814F0388 get_linked_hint

: ME_53E9EF9A03AB
 CONST UID '53E9EF9A03AB'
 CONST Name 'get_kind'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_51A6183C010F // Link
 ;
 : Target ME_47AB33FD01FF // LinkKind
 ;

ref; // ME_53E9EF9A03AB get_kind

: ME_55A3CC6A0097
 CONST Name 'document'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB6520191 // Document
 ;

ref; // ME_55A3CC6A0097 document

: ME_55A6510F00B6
 CONST Name 'doc_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_55A6510F00B6 doc_id

: ME_55A3CC6A00BF
 CONST Name 'topic'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB65202CD // Topic
 ;

ref; // ME_55A3CC6A00BF topic

: ME_55A3CC6A00E7
 CONST Name 'redaction_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EED84C01FD // RedactionID
 ;

ref; // ME_55A3CC6A00E7 redaction_id

: ME_55A3CC60010D
 CONST UID '55A3CC60010D'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_51A6183C010F // Link
 ;
 : Parameters
   Seq: ( ME_55A3CC6A0097 // document
 ME_55A6510F00B6 // doc_id
 ME_55A3CC6A00BF // topic
 ME_55A3CC6A00E7 // redaction_id
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false

ref; // ME_55A3CC60010D make

: ME_51A6183C010F
 CONST UID '51A6183C010F'
 CONST GUID 'FBA5DE98-0FAD-4647-B2DE-AB788A6DDFE6'
 CONST Name 'Link'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Operations
   Seq: ( ME_51A6185B0344 // make
 ME_51A61ED6005B // get_object_type
 ME_51A61EF0013E // get_object
 ME_51A745CE0034 // get_link_info
 ME_51AC814F0388 // get_linked_hint
 ME_53E9EF9A03AB // get_kind
 ME_55A3CC60010D // make
 )
 ; // Operations
 CONST "single impl" false
 CONST extprop:pas:TypeName 'ILink'
 CONST extprop:rc:SelfName 'Link'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_51A6183C010F Link

FORWARD ME_4A8A9DCF030D

: ME_4A8A9DE10221
 CONST UID '4A8A9DE10221'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent ME_4A8A9DCF030D // JournalBookmarkList
 ;
 : Target ME_4A8A8F640192 // JournalBookmark
 ;

ref; // ME_4A8A9DE10221 

: ME_4A8A9DCF030D
 CONST UID '4A8A9DCF030D'
 CONST Name 'JournalBookmarkList'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_4A8A9DE10221 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST extprop:pas:TypeName 'IJournalBookmarkList'

ref; // ME_4A8A9DCF030D JournalBookmarkList

FORWARD ME_4D78D8200190

: ME_4D78D86C0070
 CONST UID '4D78D86C0070'
 CONST Name 'get_all_leaf_para_count'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4D78D8200190 // DiffDocDataProvider
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4D78D86C0070 get_all_leaf_para_count

: ME_4D78D893019F
 CONST UID '4D78D893019F'
 CONST Name 'get_header_para_list'
 CONST Class class_Operation
 %SUMMARY 'Заголовок документа состоит из:'#13#10''#13#10'Фраза "Обзор изменений документа"'#13#10'Длинное имя документа (!Name)'#13#10'Фраза "Подготовлено экспертами компании "Гарант" '#13#10'Фраза "Далее приведены изменившиеся фрагменты редакций:"' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4D78D8200190 // DiffDocDataProvider
 ;
 : Target ME_4D78D65C01FF // DiffDocParaList
 ;

ref; // ME_4D78D893019F get_header_para_list

: ME_4F3257CA0054
 CONST Name 'para'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target ME_4D78D5820316 // DiffDocPara
 ;

ref; // ME_4F3257CA0054 para

: ME_4D78DB060332
 CONST UID '4D78DB060332'
 CONST Name 'get_date_para_right'
 CONST Class class_Operation
 %SUMMARY 'параграф с датами изменений документа для правого документа' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4D78D8200190 // DiffDocDataProvider
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 : Parameters
   Seq: ( ME_4F3257CA0054 // para
 )
 ; // Parameters

ref; // ME_4D78DB060332 get_date_para_right

: ME_4F3257C303A1
 CONST Name 'para'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target ME_4D78D5820316 // DiffDocPara
 ;

ref; // ME_4F3257C303A1 para

: ME_4D78DB34007D
 CONST UID '4D78DB34007D'
 CONST Name 'get_date_para_left'
 CONST Class class_Operation
 %SUMMARY 'параграф с датами изменений документа для левого документа' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4D78D8200190 // DiffDocDataProvider
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;
 : Parameters
   Seq: ( ME_4F3257C303A1 // para
 )
 ; // Parameters

ref; // ME_4D78DB34007D get_date_para_left

: ME_4D78DB3B00AF
 CONST UID '4D78DB3B00AF'
 CONST Name 'get_redaction_name_right'
 CONST Class class_Operation
 %SUMMARY 'Каждая таблица имеет заголовок содержащий имена редакций (это имя редакции для правого документа)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4D78D8200190 // DiffDocDataProvider
 ;
 : Target ME_4D78D5820316 // DiffDocPara
 ;

ref; // ME_4D78DB3B00AF get_redaction_name_right

: ME_4D78DB6C025D
 CONST UID '4D78DB6C025D'
 CONST Name 'get_redaction_name_left'
 CONST Class class_Operation
 %SUMMARY 'Каждая таблица имеет заголовок содержащий имена редакций (это имя редакции для левого документа)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4D78D8200190 // DiffDocDataProvider
 ;
 : Target ME_4D78D5820316 // DiffDocPara
 ;

ref; // ME_4D78DB6C025D get_redaction_name_left

: ME_4D78DB960024
 CONST UID '4D78DB960024'
 CONST Name 'get_changed_block_count'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4D78D8200190 // DiffDocDataProvider
 ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4D78DB960024 get_changed_block_count

: ME_4D78E03802C0
 CONST Name 'i'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4D78E03802C0 i

: ME_4D78DBB90348
 CONST UID '4D78DBB90348'
 CONST Name 'get_changed_block'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4D78D8200190 // DiffDocDataProvider
 ;
 : Target ME_4D78D72003B3 // ChangedBlock
 ;
 : Parameters
   Seq: ( ME_4D78E03802C0 // i
 )
 ; // Parameters

ref; // ME_4D78DBB90348 get_changed_block

: ME_4D78DFE7027D
 CONST Name 'left'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB6520191 // Document
 ;

ref; // ME_4D78DFE7027D left

: ME_4D78DFE702B0
 CONST Name 'right'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_45EEB6520191 // Document
 ;

ref; // ME_4D78DFE702B0 right

: ME_4D78DFAF0175
 CONST UID '4D78DFAF0175'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4D78D8200190 // DiffDocDataProvider
 ;
 : CanRaise
   Seq: ( ME_4ED7B9ED0009 // AllChangesInTables
 )
 ; // CanRaise
 : Parameters
   Seq: ( ME_4D78DFE7027D // left
 ME_4D78DFE702B0 // right
 )
 ; // Parameters
 CONST "const_type" 'read-write'

ref; // ME_4D78DFAF0175 make

: ME_4D78D8200190
 CONST UID '4D78D8200190'
 CONST GUID 'E9D2FB7F-1DE5-4C75-8998-72B6C443FF03'
 CONST Name 'DiffDocDataProvider'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Operations
   Seq: ( ME_4D78D86C0070 // get_all_leaf_para_count
 ME_4D78D893019F // get_header_para_list
 ME_4D78DB060332 // get_date_para_right
 ME_4D78DB34007D // get_date_para_left
 ME_4D78DB3B00AF // get_redaction_name_right
 ME_4D78DB6C025D // get_redaction_name_left
 ME_4D78DB960024 // get_changed_block_count
 ME_4D78DBB90348 // get_changed_block
 ME_4D78DFAF0175 // make
 )
 ; // Operations
 CONST "single impl" false
 CONST extprop:pas:TypeName 'IDiffDocDataProvider'
 CONST extprop:rc:SelfName 'DiffDocDataProvider'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4D78D8200190 DiffDocDataProvider

FORWARD ME_559E9DF3002D

: ME_559EA12200C9
 CONST UID '559EA12200C9'
 CONST Class class_Attribute
 : Stereotype st_factory_switch::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_559E9DF3002D // ObjectFromLink
 ;
 : Target ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_559EA12200C9 

: ME_559EA0D2028B
 CONST UID '559EA0D2028B'
 CONST Name 'get_object'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_559E9DF3002D // ObjectFromLink
 ;
 : Target WL 'ME_4242EBBB03B9' '3DBFDB23006E.pas.ms.script' // object
 ;

ref; // ME_559EA0D2028B get_object

: ME_559EA0DE038A
 CONST UID '559EA0DE038A'
 CONST Name 'get_object_type'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_559E9DF3002D // ObjectFromLink
 ;
 : Target ME_45EEB65202FC // LinkedObjectType
 ;

ref; // ME_559EA0DE038A get_object_type

: ME_559F780E0220
 CONST Name 'server_link'
 CONST Class class_Parameter
 : Stereotype st_in ;

ref; // ME_559F780E0220 server_link

: ME_559EA10A018E
 CONST UID '559EA10A018E'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_multi_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_559E9DF3002D // ObjectFromLink
 ;
 : Parameters
   Seq: ( ME_559F780E0220 // server_link
 )
 ; // Parameters
 CONST "const_type" 'read-write'
 CONST "dll export" false
 CONST "transparent multy" false

ref; // ME_559EA10A018E make

: ME_559E9DF3002D
 CONST UID '559E9DF3002D'
 CONST GUID '51778307-FE15-45BF-9A86-62A66BF81725'
 CONST Name 'ObjectFromLink'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4570511E038A // Document
 ;
 : Attributes
   Seq: ( ME_559EA12200C9 // 
 )
 ; // Attributes
 : Operations
   Seq: ( ME_559EA0D2028B // get_object
 ME_559EA0DE038A // get_object_type
 ME_559EA10A018E // make
 )
 ; // Operations
 CONST "single impl" false
 CONST extprop:pas:TypeName 'IObjectFromLink'
 CONST extprop:rc:SelfName 'ObjectFromLink'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_559E9DF3002D ObjectFromLink

: ME_4570511E038A
 CONST UID '4570511E038A'
 CONST Name 'Document'
 CONST Class class_Category
 : Stereotype st_Interfaces ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_456EA3D2031C' '456EA3D2031C.pas.ms.script' // GblAdapterLib
 ;
 : Children
   Seq: ( ME_45EEB65202FC // LinkedObjectType
 ME_45EEB6520309 // MissingInfo
 ME_45EEB6520306 // InvalidParaId
 ME_45EEB6520314 // TimeMachineWarningType
 ME_45EEB652031D // TimeMachineWarning
 ME_45EEB6520321 // InvalidTopicId
 ME_45EEB6520323 // PositionType
 ME_45EEB65202D4 // Position
 ME_45EEB65202EF // PositionList
 ME_45EEB65202CD // Topic
 ME_45EEB65202AA // ParaId
 ME_45EEB6520208 // DocumentType
 ME_45EEB6520328 // FolderLinkNotFound
 ME_45EED84C01FD // RedactionID
 ME_45EED87E0383 // ActiveIntervalList
 ME_45EED8A401CD // NotSureInfo
 ME_45EED88901BE // NotSureIntervalList
 ME_45EED8C20066 // RedactionType
 ME_51FB7465014E // RedactionSourceDocumentInfo
 ME_51FB7643002D // RedactionSourceDocumentInfoList
 ME_45EED9780391 // RedactionNotFound
 ME_45EEDAD60237 // NotAllowedInTrialMode
 ME_47AB33FD01FF // LinkKind
 ME_45EED97B0372 // InvalidDate
 ME_45EEDA9A00B1 // ExplanationDictionaryNotInstalled
 ME_47AB301C01DC // LinkInfo
 ME_47ED1AC7036F // FactoryKey
 ME_4ADF1C2C00B8 // ParaNum
 ME_4B4EE046030D // DiffIterator
 ME_4C5AA63D01ED // LayerID
 ME_4A49F79C011A // InvalidObjectClass
 ME_4A6D655A02A8 // NoPrevRedaction
 ME_4C5AA67E002B // ChildID
 ME_4C5AA60F039B // EntryPoint
 ME_4C5AA77200CE // Context
 ME_4C5AB3040216 // EVDType
 ME_4C5AB32B03A5 // ExternalID
 ME_4C5AB363008D // EVDStream
 ME_4C5ABA9401A6 // InvalidEntryPoint
 ME_4C5ABAA803CA // InvalidLayerID
 ME_4C5ABDE10145 // Bookmark2
 ME_4C5ABD7603D1 // BookmarkList
 ME_4D39697600E4 // FragmentList
 ME_4C9B41F302A7 // SubList
 ME_4CA32AC30364 // ContextList
 ME_4C8E37620115 // FoundContext
 ME_4C5AA5CA02DF // DocumentTextProvider
 ME_4CED493F01B9 // DocumentTextProviderList
 ME_4D147CA200AE // CommentsParaList
 ME_4D14817F0147 // ExternalObjectData
 ME_4D14813D02BB // ExternalObjectDataList
 ME_4CC80F7E02BB // DiffData
 ME_4D628A3C0341 // DocumentTextProviderDescriptor
 ME_4D628F1402C0 // DocumentTextProviderDescriptorList
 ME_4DCBBAC300F6 // SubId
 ME_4DCBB953031F // DocPoint
 ME_4DCBBAEF025F // DocPointList
 ME_4FEAFCB6035C // Likeable
 ME_45EED83A00C4 // RedactionInfo
 ME_4D78D5820316 // DiffDocPara
 ME_4D78D65C01FF // DiffDocParaList
 ME_4D78D72003B3 // ChangedBlock
 ME_45EED8DE0121 // RedactionInfoList
 ME_45EEB6520191 // Document
 ME_45EEB65202A0 // Bookmark
 ME_45EED80E0086 // DocumentState
 ME_4ED7B9ED0009 // AllChangesInTables
 ME_4A8A8F640192 // JournalBookmark
 ME_4DE8CFB302F4 // DocumentLayerID
 ME_51A6183C010F // Link
 ME_4A8A9DCF030D // JournalBookmarkList
 ME_4D78D8200190 // DiffDocDataProvider
 ME_559E9DF3002D // ObjectFromLink
 )
 ; // Children
 : Constants
   Seq: ( ME_45EEB652030F // PositionInDocument
 ME_4C6E33E40051 // TextProviderConstants
 )
 ; // Constants
 : Depends
   Seq: ( WL 'ME_4423F94903C8' '4423F94903C8.pas.ms.script' // IO
 WL 'ME_456EA56002BF' '456EA56002BF.pas.ms.script' // BaseTypes
 WL 'ME_4570501E037A' '4570501E037A.pas.ms.script' // Folders
 WL 'ME_457450470167' '457450470167.pas.ms.script' // DynamicTree
 WL 'ME_45ED922F00A4' '45ED922F00A4.pas.ms.script' // ExternalObject
 WL 'ME_45EEAA800226' '45EEAA800226.pas.ms.script' // UnderControl
 )
 ; // Depends
 CONST "no hands" false
 CONST cpp:Path 'garant6x\implementation\Garant\GblAdapterLib\Document\Document.cpp'
 CONST cpp:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\Document'
 CONST dll.cpp:Path 'garant6x\implementation\Garant\GblAdapterLib\Document\Document_tie.cpp'
 CONST dll.cpp:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\Document'
 CONST dll.h:Path 'garant6x\implementation\Garant\GblAdapterLib\Document\Document_tie.h'
 CONST dll.h:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\Document'
 CONST fctr.cpp:Path 'garant6x\implementation\Garant\GblAdapterLib\Document\DocumentFactories.cpp'
 CONST fctr.cpp:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\Document'
 CONST fctr.h:Path 'garant6x\implementation\Garant\GblAdapterLib\Document\DocumentFactories.h'
 CONST fctr.h:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\Document'
 CONST h:Path 'garant6x\implementation\Garant\GblAdapterLib\Document\Document.h'
 CONST h:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\Document'
 CONST i.h:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\Document'
 CONST intf.pas:Path 'garant6x\implementation\Garant\tie\Garant\GblAdapterLib\DocumentUnit.pas'
 CONST pas:Path 'garant6x\implementation\Garant\GblAdapterLib\DocumentUnit.pas'
 CONST extprop:pas:UnitName 'DocumentUnit'

ref; // ME_4570511E038A Document
