// Settings_i 45EEAA6E01A9 Impl Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_45EEAA6E01A9

FORWARD ME_4889E960019F

: ME_488DCB920012
 CONST UID '488DCB920012'
 CONST Class class_Dependency
 : Stereotype st_friend::Dependency ;
 : Parent ME_4889E960019F // StoreSettingsToServer
 ;

ref; // ME_488DCB920012 

: ME_4889E960019F
 CONST UID '4889E960019F'
 CONST Name 'StoreSettingsToServer'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'класс периодически сбрасывающий изменённые настройки на сервер' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_45EEAA6E01A9 // Settings_i
 ;
 : Dependencies
   Seq: ( ME_488DCB920012 // 
 )
 ; // Dependencies
 CONST "need objcounter" false
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST cpp:Path 'garant6x\implementation\Garant\GblAdapterLib\impl\Settings_i\StoreSettingsToServer.cpp'
 CONST h:Path 'garant6x\implementation\Garant\GblAdapterLib\impl\Settings_i\StoreSettingsToServer.h'
 CONST intf.pas:Path 'garant6x\implementation\Garant\tie\Garant\GblAdapterLib\StoreSettingsToServer.pas'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4889E960019F StoreSettingsToServer

FORWARD ME_488DD13303A4

: ME_488DD16702A2
 CONST UID '488DD16702A2'
 CONST Name 'conf_id'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_488DD13303A4 // ServerSettingData
 ;
 : Target WL 'ME_3DBFFD7002C2' '3DBFDB23006E.pas.ms.script' // long
 ;

ref; // ME_488DD16702A2 conf_id

: ME_488DD18301C9
 CONST UID '488DD18301C9'
 CONST Name 'prop_id'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_488DD13303A4 // ServerSettingData
 ;
 : Target WL 'ME_3DBFFD7002C2' '3DBFDB23006E.pas.ms.script' // long
 ;

ref; // ME_488DD18301C9 prop_id

: ME_488DD19C0358
 CONST UID '488DD19C0358'
 CONST Name 'prop_value'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_488DD13303A4 // ServerSettingData
 ;

ref; // ME_488DD19C0358 prop_value

: ME_488DD1A9000F
 CONST UID '488DD1A9000F'
 CONST Name 'time'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_488DD13303A4 // ServerSettingData
 ;
 : Target WL 'ME_3DBFFD860205' '3DBFDB23006E.pas.ms.script' // long long
 ;

ref; // ME_488DD1A9000F time

: ME_489816C3023E
 CONST UID '489816C3023E'
 CONST Name 'ctor'
 CONST Class class_Operation
 : Stereotype st_ctor::Operation ;
 %SUMMARY 'используется для поиска элемента в кешированных данных' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_488DD13303A4 // ServerSettingData
 ;

ref; // ME_489816C3023E ctor

: ME_488DD13303A4
 CONST UID '488DD13303A4'
 CONST Name 'ServerSettingData'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 %SUMMARY 'данные для сохранения настройки на сервере' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_45EEAA6E01A9 // Settings_i
 ;
 : Attributes
   Seq: ( ME_488DD16702A2 // conf_id
 ME_488DD18301C9 // prop_id
 ME_488DD19C0358 // prop_value
 ME_488DD1A9000F // time
 )
 ; // Attributes
 : Operations
   Seq: ( ME_489816C3023E // ctor
 )
 ; // Operations
 CONST "Need init ctor" true
 CONST extprop:pas:TypeName 'TServerSettingData'

ref; // ME_488DD13303A4 ServerSettingData

FORWARD ME_488DD1E30293

: ME_488DD2830065
 CONST UID '488DD2830065'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_488DD1E30293 // CachedDataForServer
 ;
 : Target ME_488DD13303A4 // ServerSettingData
 ;

ref; // ME_488DD2830065 

: ME_488DD1E30293
 CONST UID '488DD1E30293'
 CONST Name 'CachedDataForServer'
 CONST Class class_Class
 : Stereotype st_Set ;
 CONST Kind kind_NormalClass
 %SUMMARY 'данные для отправки на сервер' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_45EEAA6E01A9 // Settings_i
 ;
 : Attributes
   Seq: ( ME_488DD2830065 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'

ref; // ME_488DD1E30293 CachedDataForServer

FORWARD ME_4898316C03A1

: ME_489831930115
 CONST UID '489831930115'
 CONST Name 'SSS_INTIME'
 CONST Class class_Attribute
 %SUMMARY 'сразу писать настройки на сервер' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4898316C03A1 // SettingsSaveStrategy
 ;

ref; // ME_489831930115 SSS_INTIME

: ME_489831C2011C
 CONST UID '489831C2011C'
 CONST Name 'SSS_CACHE'
 CONST Class class_Attribute
 %SUMMARY 'сохранять настройки в кеше с периодическим сбросом на сервер' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4898316C03A1 // SettingsSaveStrategy
 ;

ref; // ME_489831C2011C SSS_CACHE

: ME_489831DE03E0
 CONST UID '489831DE03E0'
 CONST Name 'SSS_NOTSAVE'
 CONST Class class_Attribute
 %SUMMARY 'не сохранять настройки на сервере' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4898316C03A1 // SettingsSaveStrategy
 ;

ref; // ME_489831DE03E0 SSS_NOTSAVE

: ME_4898316C03A1
 CONST UID '4898316C03A1'
 CONST Name 'SettingsSaveStrategy'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 %SUMMARY 'стратегия сохранения настроек' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_45EEAA6E01A9 // Settings_i
 ;
 : Attributes
   Seq: ( ME_489831930115 // SSS_INTIME
 ME_489831C2011C // SSS_CACHE
 ME_489831DE03E0 // SSS_NOTSAVE
 )
 ; // Attributes
 CONST extprop:pas:TypeName 'TSettingsSaveStrategy'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4898316C03A1 SettingsSaveStrategy

FORWARD ME_488EBACB0163

: ME_488EBB03035A
 CONST UID '488EBB03035A'
 CONST Name 'DELTA_OPTION_NAME'
 CONST Class class_Attribute
 %SUMMARY 'название опции, задающей таймаут сбрасывания настроек на сервер' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_488EBACB0163 // ServerCacheValues
 ;
 : Target WL 'ME_452257A0036F' '3DBFDB23006E.pas.ms.script' // a-string
 ;
 CONST Value '-SettingsFlushTimeout'
 : ValueType WL 'ME_452257A0036F' '3DBFDB23006E.pas.ms.script' // a-string
 ;
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '-SettingsFlushTimeout'

ref; // ME_488EBB03035A DELTA_OPTION_NAME

: ME_488EBB8B0014
 CONST UID '488EBB8B0014'
 CONST Name 'DELTA_OPTION_VALUE'
 CONST Class class_Attribute
 %SUMMARY 'значение таймаута по-умолчанию' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_488EBACB0163 // ServerCacheValues
 ;
 : Target WL 'ME_3DBFFD7002C2' '3DBFDB23006E.pas.ms.script' // long
 ;
 CONST Value 600
 : ValueType WL 'ME_3DBFFD7002C2' '3DBFDB23006E.pas.ms.script' // long
 ;
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 600

ref; // ME_488EBB8B0014 DELTA_OPTION_VALUE

: ME_488EBACB0163
 CONST UID '488EBACB0163'
 CONST Name 'ServerCacheValues'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 %SUMMARY 'константы, связанные с использованием кеша настроек для сбрасывания на сервер. Если таймаут меньше нуля, настройеки на сервер вообще не пишутся, если равен нулю, то пишутся сразу без использования кеша' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_45EEAA6E01A9 // Settings_i
 ;
 : Attributes
   Seq: ( ME_488EBB03035A // DELTA_OPTION_NAME
 ME_488EBB8B0014 // DELTA_OPTION_VALUE
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_488EBACB0163 ServerCacheValues

: ME_45EEAA6E01A9
 CONST UID '45EEAA6E01A9'
 CONST Name 'Settings_i'
 CONST Class class_Category
 : Stereotype st_Impl ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_456EA3D2031C' '456EA3D2031C.pas.ms.script' // GblAdapterLib
 ;
 : Children
   Seq: ( ME_4889E960019F // StoreSettingsToServer
 ME_488DD13303A4 // ServerSettingData
 ME_488DD1E30293 // CachedDataForServer
 ME_4898316C03A1 // SettingsSaveStrategy
 )
 ; // Children
 : Constants
   Seq: ( ME_488EBACB0163 // ServerCacheValues
 )
 ; // Constants
 : Depends
   Seq: ( WL 'ME_4423F94903C8' '4423F94903C8.pas.ms.script' // IO
 WL 'ME_456EA56002BF' '456EA56002BF.pas.ms.script' // BaseTypes
 WL 'ME_45702A7F01F4' '45702A7F01F4.pas.ms.script' // Start_i
 WL 'ME_45EEAA69036E' '45EEAA69036E.pas.ms.script' // Settings
 WL 'ME_460BAAA30119' '460BAAA30119.pas.ms.script' // ApplicationHelper
 )
 ; // Depends
 CONST cpp:Path 'garant6x\implementation\Garant\GblAdapterLib\impl\Settings_i\Settings_i.cpp'
 CONST cpp:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\impl\Settings_i'
 CONST fctr.cpp:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\impl\Settings_i'
 CONST fctr.h:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\impl\Settings_i'
 CONST h:Path 'garant6x\implementation\Garant\GblAdapterLib\impl\Settings_i\Settings_i.h'
 CONST h:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\impl\Settings_i'
 CONST i.h:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\impl\Settings_i'

ref; // ME_45EEAA6E01A9 Settings_i
