// DocumentHelper 4628939B0216 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4628939B0216
%%Inner ME_4628939B0216
%%Inner ME_4628939B0216

FORWARD ME_4628939B0216

ME ME_4FE870160102
 MEPROP UID '4FE870160102'
 MEPROP Name 'DocumentTypeToFactoryKey'
 MEPROP Class class_Class
 MELINK Stereotype st_TypeConvertor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4628939B0216 // DocumentHelper
 ;
 UP "is sorted" false
 UP h:Path 'garant6x\implementation\Garant\GblAdapterLib\DocumentHelper\DocumentTypeToFactoryKey.h'

ENDME // ME_4FE870160102 DocumentTypeToFactoryKey

ME ME_4628939B0216
 MEPROP UID '4628939B0216'
 MEPROP Name 'DocumentHelper'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_456EA3D2031C' // GblAdapterLib
 ;
 MELIST Children
   Seq: ( WL? 'ME_462895DD0240' // RedactionInfoListHelper
 WL? 'ME_47ED11E002A7' // DocumentFactoryKeyHelper
 HWL ME_4FE870160102 // DocumentTypeToFactoryKey
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4570511E038A' // Document
 WL? 'ME_460BAAA30119' // ApplicationHelper
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'main' 'uses' )
 ; // DiagramsNames
 UP cpp:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\DocumentHelper'
 UP h:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\DocumentHelper'

ENDME // ME_4628939B0216 DocumentHelper
