// VT 467A75D90346 Library Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346
%%Inner ME_467A75D90346

ME ME_467A75D90346
 MEPROP UID '467A75D90346'
 MEPROP Name 'VT'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Library ;
 %SUMMARY 'Библиотека визуальных компонентов.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4677DDBD0193' // Shared Delphi
 ;
 MELIST Children
   Seq: ( WL? 'ME_47F485150151' // vtCommon
 WL? 'ME_499ABF4F02A1' // elClone
 WL? 'ME_4981A49103DD' // Flash
 WL? 'ME_50C61A7F0303' // Hints
 WL? 'ME_4B97E7FD006C' // Outliner
 WL? 'ME_4A9B9BAA0207' // Labels
 WL? 'ME_4AC5DA5A01AD' // Radio
 WL? 'ME_48297E42011A' // ComboTree
 WL? 'ME_4A83EE0E0002' // Combos
 WL? 'ME_4C43D64C0168' // Buttons
 WL? 'ME_4C52C05501D8' // Editors
 WL? 'ME_4E159FE900E2' // StatusBar
 WL? 'ME_4E732D5D02FE' // HideFields
 WL? 'ME_50220AA101CA' // Scrollbar
 WL? 'ME_4AC5DADB00C9' // DateEdit
 WL? 'ME_525FBBB20170' // Gradient
 WL? 'ME_53E492040261' // Stuff
 WL? 'ME_57E1256601B2' // DropDown
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4677E16A022A' // K2
 WL? 'ME_4677E18600C2' // dd
 WL? 'ME_467A8734039C' // EVD
 WL? 'ME_4684F91300DD' // Vcl
 WL? 'ME_469F3E37025A' // Rtl
 WL? 'ME_47540FF802AC' // Orpheus
 WL? 'ME_4790B4F00236' // AFW
 WL? 'ME_4790C3B8021E' // VCM
 WL? 'ME_4790D09A0378' // L3
 WL? 'ME_4797632D0273' // Everest
 WL? 'ME_4C43E84F0304' // tb97
 WL? 'ME_4CC81F680162' // SkinnedControls
 WL? 'ME_4D4927B5008B' // VT$Core
 WL? 'ME_4D5E61FC01F0' // AFW$Core
 WL? 'ME_4E2F0E1B03BB' // L3$Domain
 WL? 'ME_4E36644A0023' // Стандартные компоненты
 WL? 'ME_5226F61C0109' // Samples
 WL? 'ME_547CC9D40158' // VT$Panels
 WL? 'ME_54F5AAED0073' // L3$Visual
 WL? 'ME_550012C403C4' // L3$AFW
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "UseNewGen" true
 UP "defines" 'vtDefine.inc'
 UP "exec mode" 'concluded'
 UP "gui" 'gui'
 UP "is namespace" true
 UP "vendor" '/Garant'
 UP intf.pas:PathOnly '\common\components\gui\Garant\VT'

ENDME // ME_467A75D90346 VT
