// l3DataObject 4680F5600033 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4680F5600033

FORWARD ME_4680F5AA0274

: ME_48F33B1D012A
 CONST UID '48F33B1D012A'
 CONST Name 'f_DragBitmap'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target WL 'ME_476F70910097' '467C0CAA02AB.pas.ms.script' // Il3Bitmap
 ;

ref; // ME_48F33B1D012A f_DragBitmap

: ME_48F33B4D011D
 CONST UID '48F33B4D011D'
 CONST Name 'Formats'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target WL 'ME_47BB29D40117' '47913B47006E.pas.ms.script' // Tl3LongintList
 ;
 CONST "needs field" true
 CONST "pm" true
 CONST "reads field" true

ref; // ME_48F33B4D011D Formats

: ME_48F33B570390
 CONST UID '48F33B570390'
 CONST Name 'f_FilesNames'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target WL 'ME_4773DCE302FF' '47913B47006E.pas.ms.script' // Tl3StringList
 ;

ref; // ME_48F33B570390 f_FilesNames

: ME_48F340CD00A8
 CONST Name 'aFormats'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A449C50391' '4677FBA70343.pas.ms.script' // Tl3ClipboardFormats
 ;

ref; // ME_48F340CD00A8 aFormats

: ME_48F340C901DE
 CONST UID '48F340C901DE'
 CONST Name 'Create'
 CONST Class class_Operation
 : Stereotype st_ctor::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Parameters
   Seq: ( ME_48F340CD00A8 // aFormats
 )
 ; // Parameters

ref; // ME_48F340C901DE Create

: ME_48F3496B01CE
 CONST Name 'aFormatEtcIn'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A5B1B10388' '4677FBA70343.pas.ms.script' // TFormatEtc
 ;

ref; // ME_48F3496B01CE aFormatEtcIn

: ME_48F3496B0213
 CONST Name 'medium'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_46A5B1570253' '4677FBA70343.pas.ms.script' // Tl3StoragePlace
 ;

ref; // ME_48F3496B0213 medium

: ME_48F3495D0398
 CONST UID '48F3495D0398'
 CONST Name 'DoGetData'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target WL 'ME_469F9A0001B0' '4677FBA70343.pas.ms.script' // HResult
 ;
 : Parameters
   Seq: ( ME_48F3496B01CE // aFormatEtcIn
 ME_48F3496B0213 // medium
 )
 ; // Parameters

ref; // ME_48F3495D0398 DoGetData

: ME_48F349BD025F
 CONST Name 'aFormatEtcIn'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A5B1B10388' '4677FBA70343.pas.ms.script' // TFormatEtc
 ;

ref; // ME_48F349BD025F aFormatEtcIn

: ME_48F349BD02AB
 CONST Name 'medium'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A5B1570253' '4677FBA70343.pas.ms.script' // Tl3StoragePlace
 ;

ref; // ME_48F349BD02AB medium

: ME_48F349AE00F1
 CONST UID '48F349AE00F1'
 CONST Name 'DoGetDataHere'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target WL 'ME_469F9A0001B0' '4677FBA70343.pas.ms.script' // HResult
 ;
 : Parameters
   Seq: ( ME_48F349BD025F // aFormatEtcIn
 ME_48F349BD02AB // medium
 )
 ; // Parameters

ref; // ME_48F349AE00F1 DoGetDataHere

: ME_48F350480006
 CONST Name 'aNames'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4773DCE302FF' '47913B47006E.pas.ms.script' // Tl3StringList
 ;

ref; // ME_48F350480006 aNames

: ME_48F3504301B7
 CONST UID '48F3504301B7'
 CONST Name 'WriteFilesAndSetNames'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Parameters
   Seq: ( ME_48F350480006 // aNames
 )
 ; // Parameters

ref; // ME_48F3504301B7 WriteFilesAndSetNames

: ME_48F350F802F7
 CONST UID '48F350F802F7'
 CONST Name 'Bitmap'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target WL 'ME_476F70910097' '467C0CAA02AB.pas.ms.script' // Il3Bitmap
 ;

ref; // ME_48F350F802F7 Bitmap

: ME_48F351BE0015
 CONST UID '48F351BE0015'
 CONST Name 'AcceptableTymed'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_48F351BE0015 AcceptableTymed

: ME_48F351EB00E1
 CONST UID '48F351EB00E1'
 CONST Name 'CheckFormats'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;

ref; // ME_48F351EB00E1 CheckFormats

: ME_48F359820348
 CONST Name 'aFormatEtc'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A5B1B10388' '4677FBA70343.pas.ms.script' // TFormatEtc
 ;

ref; // ME_48F359820348 aFormatEtc

: ME_48F359680368
 CONST UID '48F359680368'
 CONST Name 'DoQueryGetData'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target WL 'ME_469F9A0001B0' '4677FBA70343.pas.ms.script' // HResult
 ;
 : Parameters
   Seq: ( ME_48F359820348 // aFormatEtc
 )
 ; // Parameters

ref; // ME_48F359680368 DoQueryGetData

: ME_48F35AF2038F
 CONST Name 'aBitmap'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476F70910097' '467C0CAA02AB.pas.ms.script' // Il3Bitmap
 ;

ref; // ME_48F35AF2038F aBitmap

: ME_48F35AEC0254
 CONST UID '48F35AEC0254'
 CONST Name 'SetDragBitmap'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Parameters
   Seq: ( ME_48F35AF2038F // aBitmap
 )
 ; // Parameters

ref; // ME_48F35AEC0254 SetDragBitmap

FORWARD ME_4680F5FF01EA

: ME_48F33EDA0031
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target ME_4680F5FF01EA // Tl3DataObjectEnum
 ;

ref; // ME_48F33EDA0031 

: ME_48F33EFD0363
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target ME_4680F5FF01EA // Tl3DataObjectEnum
 ;

ref; // ME_48F33EFD0363 

: ME_48F348BC0264
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target WL 'ME_4773D64E036C' '47913B47006E.pas.ms.script' // l3Base
 ;

ref; // ME_48F348BC0264 

: ME_48F3491B007A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_48F3491B007A 

: ME_48F34D52023C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F5AA0274 // Tl3DataObject
 ;
 : Target WL 'ME_48F34C980291' '4AB0C3F60375.pas.ms.script' // PDropFiles
 ;

ref; // ME_48F34D52023C 

: ME_476F77AA034A_ME_4680F5AA0274
 : Original WL 'ME_476F77AA034A' '467C0CAA02AB.pas.ms.script' // Image
 ;
 : Implementor ME_4680F5AA0274 // Tl3DataObject
 ;
 CONST OpKind opkind_Implemented
ref; // ME_476F77AA034A_ME_4680F5AA0274 Image

: ME_48F32DD50284_ME_4680F5AA0274
 : Original WL 'ME_48F32DD50284' '46A0E6C5023A.pas.ms.script' // GetData
 ;
 : Implementor ME_4680F5AA0274 // Tl3DataObject
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F32DD50284_ME_4680F5AA0274 GetData

: ME_48F32E0200AF_ME_4680F5AA0274
 : Original WL 'ME_48F32E0200AF' '46A0E6C5023A.pas.ms.script' // GetDataHere
 ;
 : Implementor ME_4680F5AA0274 // Tl3DataObject
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F32E0200AF_ME_4680F5AA0274 GetDataHere

: ME_48F32E20007F_ME_4680F5AA0274
 : Original WL 'ME_48F32E20007F' '46A0E6C5023A.pas.ms.script' // QueryGetData
 ;
 : Implementor ME_4680F5AA0274 // Tl3DataObject
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F32E20007F_ME_4680F5AA0274 QueryGetData

: ME_48F32E330154_ME_4680F5AA0274
 : Original WL 'ME_48F32E330154' '46A0E6C5023A.pas.ms.script' // GetCanonicalFormatEtc
 ;
 : Implementor ME_4680F5AA0274 // Tl3DataObject
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F32E330154_ME_4680F5AA0274 GetCanonicalFormatEtc

: ME_48F32E4D0179_ME_4680F5AA0274
 : Original WL 'ME_48F32E4D0179' '46A0E6C5023A.pas.ms.script' // SetData
 ;
 : Implementor ME_4680F5AA0274 // Tl3DataObject
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F32E4D0179_ME_4680F5AA0274 SetData

: ME_48F330A10257_ME_4680F5AA0274
 : Original WL 'ME_48F330A10257' '46A0E6C5023A.pas.ms.script' // EnumFormatEtc
 ;
 : Implementor ME_4680F5AA0274 // Tl3DataObject
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F330A10257_ME_4680F5AA0274 EnumFormatEtc

: ME_48F330C40367_ME_4680F5AA0274
 : Original WL 'ME_48F330C40367' '46A0E6C5023A.pas.ms.script' // DAdvise
 ;
 : Implementor ME_4680F5AA0274 // Tl3DataObject
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F330C40367_ME_4680F5AA0274 DAdvise

: ME_48F3312B0381_ME_4680F5AA0274
 : Original WL 'ME_48F3312B0381' '46A0E6C5023A.pas.ms.script' // DUnadvise
 ;
 : Implementor ME_4680F5AA0274 // Tl3DataObject
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F3312B0381_ME_4680F5AA0274 DUnadvise

: ME_48F3313E0339_ME_4680F5AA0274
 : Original WL 'ME_48F3313E0339' '46A0E6C5023A.pas.ms.script' // EnumDAdvise
 ;
 : Implementor ME_4680F5AA0274 // Tl3DataObject
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F3313E0339_ME_4680F5AA0274 EnumDAdvise

: ME_479731C50290_ME_4680F5AA0274
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 : Implementor ME_4680F5AA0274 // Tl3DataObject
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_4680F5AA0274 Cleanup

: ME_47A042E100E2_ME_4680F5AA0274
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 : Implementor ME_4680F5AA0274 // Tl3DataObject
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_4680F5AA0274 InitFields

: ME_4680F5AA0274
 CONST UID '4680F5AA0274'
 CONST Name 'Tl3DataObject'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Базовый класс для работы с IDataObject.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5600033 // l3DataObject
 ;
 : Inherits
   Seq: ( WL 'ME_47BC391D0259' '47913B47006E.pas.ms.script' // Tl3SimpleObject
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4680F4790135' '4677FBA70343.pas.ms.script' // IDataObject
 WL 'ME_4680F52502B9' '467C0CAA02AB.pas.ms.script' // Il3DragImageSource
 )
 ; // Implements
 : Attributes
   Seq: ( ME_48F33B1D012A // f_DragBitmap
 ME_48F33B4D011D // Formats
 ME_48F33B570390 // f_FilesNames
 )
 ; // Attributes
 : Operations
   Seq: ( ME_48F340C901DE // Create
 ME_48F3495D0398 // DoGetData
 ME_48F349AE00F1 // DoGetDataHere
 ME_48F3504301B7 // WriteFilesAndSetNames
 ME_48F350F802F7 // Bitmap
 ME_48F351BE0015 // AcceptableTymed
 ME_48F351EB00E1 // CheckFormats
 ME_48F359680368 // DoQueryGetData
 ME_48F35AEC0254 // SetDragBitmap
 )
 ; // Operations
 : Implemented
   Seq: ( ME_476F77AA034A_ME_4680F5AA0274 // Image
 ME_48F32DD50284_ME_4680F5AA0274 // GetData
 ME_48F32E0200AF_ME_4680F5AA0274 // GetDataHere
 ME_48F32E20007F_ME_4680F5AA0274 // QueryGetData
 ME_48F32E330154_ME_4680F5AA0274 // GetCanonicalFormatEtc
 ME_48F32E4D0179_ME_4680F5AA0274 // SetData
 ME_48F330A10257_ME_4680F5AA0274 // EnumFormatEtc
 ME_48F330C40367_ME_4680F5AA0274 // DAdvise
 ME_48F3312B0381_ME_4680F5AA0274 // DUnadvise
 ME_48F3313E0339_ME_4680F5AA0274 // EnumDAdvise
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_4680F5AA0274 // Cleanup
 ME_47A042E100E2_ME_4680F5AA0274 // InitFields
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_48F33EDA0031 // 
 ME_48F33EFD0363 // 
 ME_48F348BC0264 // 
 ME_48F3491B007A // 
 ME_48F34D52023C // 
 )
 ; // Dependencies
 CONST "author" 'Люлин А.В.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST "started" '13.12.2006 14:00'
 CONST intf.pas:Path 'common\components\rtl\Garant\L3\l3DataObject.pas'
 CONST extprop:rc:SelfName 'DataObject'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'l3DataObject'

ref; // ME_4680F5AA0274 Tl3DataObject

: ME_4680F70C0255
 CONST UID '4680F70C0255'
 CONST Name 'Tl3BitmapDataObject'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Данные картинки.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5600033 // l3DataObject
 ;
 : Inherits
   Seq: ( ME_4680F5AA0274 // Tl3DataObject
 )
 ; // Inherits
 CONST "finished" false
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\L3\NOT_FINISHED_l3BitmapDataObject.pas'
 CONST extprop:rc:SelfName 'BitmapDataObject'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'l3BitmapDataObject'

ref; // ME_4680F70C0255 Tl3BitmapDataObject

FORWARD ME_4680F7A602E3

: ME_48F8C8C201F0
 CONST UID '48F8C8C201F0'
 CONST Name 'DataType'
 CONST Class class_Class
 : Stereotype st_ImpurityParamType ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4680F7A602E3 // l3InterfacedDataObject
 ;
 CONST extprop:pas:TypeName '_DataType_'

ref; // ME_48F8C8C201F0 DataType

: ME_4CE2768202FE
 CONST UID '4CE2768202FE'
 CONST Name 'DataType'
 CONST Class class_Attribute
 : Stereotype st_impurity_param::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4680F7A602E3 // l3InterfacedDataObject
 ;
 : Target ME_48F8C8C201F0 // DataType
 ;

ref; // ME_4CE2768202FE DataType

: ME_4CE2769C0280
 CONST UID '4CE2769C0280'
 CONST Name 'Data'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4680F7A602E3 // l3InterfacedDataObject
 ;
 : Target ME_48F8C8C201F0 // DataType
 ;
 CONST "needs field" true
 CONST "pm" true
 CONST "reads field" true

ref; // ME_4CE2769C0280 Data

FORWARD ME_4CE27E5A011A

: ME_4CE27E8E026F
 CONST Name 'aData'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_48F8C8C201F0 // DataType
 ;

ref; // ME_4CE27E8E026F aData

: ME_4CE27E8E02F2
 CONST Name 'aFormats'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A449C50391' '4677FBA70343.pas.ms.script' // Tl3ClipboardFormats
 ;

ref; // ME_4CE27E8E02F2 aFormats

: ME_4CE27E8902F1
 CONST UID '4CE27E8902F1'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4CE27E5A011A // Create
 ;
 : Parameters
   Seq: ( ME_4CE27E8E026F // aData
 ME_4CE27E8E02F2 // aFormats
 )
 ; // Parameters

ref; // ME_4CE27E8902F1 DoIt

: ME_4CE27E5A011A
 CONST UID '4CE27E5A011A'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4680F7A602E3 // l3InterfacedDataObject
 ;
 : Operations
   Seq: ( ME_4CE27E8902F1 // DoIt
 )
 ; // Operations

ref; // ME_4CE27E5A011A Create

FORWARD ME_4CE27E4901C4

: ME_AE09DA4464E8
 CONST Name 'aData'
 CONST IsSummoned true
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_48F8C8C201F0 // DataType
 ;

ref; // ME_AE09DA4464E8 aData

: ME_39A791C176A9
 CONST Name 'aFormats'
 CONST IsSummoned true
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A449C50391' '4677FBA70343.pas.ms.script' // Tl3ClipboardFormats
 ;

ref; // ME_39A791C176A9 aFormats

: ME_415CA0F75FF6
 CONST UID '415CA0F75FF6'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY 'Сигнатура фабрики l3InterfacedDataObject.Make' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4CE27E4901C4 // Make
 ;
 : Target WL 'ME_4680F4790135' '4677FBA70343.pas.ms.script' // IDataObject
 ;
 : Parameters
   Seq: ( ME_AE09DA4464E8 // aData
 ME_39A791C176A9 // aFormats
 )
 ; // Parameters

ref; // ME_415CA0F75FF6 DoIt

: ME_4CE27E4901C4
 CONST UID '4CE27E4901C4'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4680F7A602E3 // l3InterfacedDataObject
 ;
 : Inherits
   Seq: ( ME_4CE27E5A011A // Create
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4680F4790135' '4677FBA70343.pas.ms.script' // IDataObject
 )
 ; // Implements
 : Operations
   Seq: ( ME_415CA0F75FF6 // DoIt
 )
 ; // Operations
 CONST "check nil" false
 CONST "need AfterCreate" 'undefined'
 CONST "need Aggregate" 'undefined'
 CONST "need As" false

ref; // ME_4CE27E4901C4 Make

: ME_48F4B1930217
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F7A602E3 // l3InterfacedDataObject
 ;
 : Target WL 'ME_4773D64E036C' '47913B47006E.pas.ms.script' // l3Base
 ;

ref; // ME_48F4B1930217 

: ME_479731C50290_ME_4680F7A602E3
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 : Implementor ME_4680F7A602E3 // l3InterfacedDataObject
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_4680F7A602E3 Cleanup

: ME_4A60B23E00C3_ME_4680F7A602E3
 : Original WL 'ME_4A60B23E00C3' '47BB24D30205.pas.ms.script' // COMQueryInterface
 ;
 : Implementor ME_4680F7A602E3 // l3InterfacedDataObject
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4A60B23E00C3_ME_4680F7A602E3 COMQueryInterface

: ME_4680F7A602E3
 CONST UID '4680F7A602E3'
 CONST Name 'l3InterfacedDataObject'
 CONST Class class_Class
 : Stereotype st_Impurity ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Для хранения в буфере обмена интерфейса' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5600033 // l3DataObject
 ;
 : Inherits
   Seq: ( ME_4680F5AA0274 // Tl3DataObject
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_4CE2768202FE // DataType
 ME_4CE2769C0280 // Data
 )
 ; // Attributes
 : Operations
   Seq: ( ME_4CE27E5A011A // Create
 ME_4CE27E4901C4 // Make
 )
 ; // Operations
 : Overridden
   Seq: ( ME_479731C50290_ME_4680F7A602E3 // Cleanup
 ME_4A60B23E00C3_ME_4680F7A602E3 // COMQueryInterface
 )
 ; // Overridden
 : Children
   Seq: ( ME_48F8C8C201F0 // DataType
 )
 ; // Children
 : Dependencies
   Seq: ( ME_48F4B1930217 // 
 )
 ; // Dependencies
 CONST "author" 'Люлин А.В.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '13.12.2006 14:10'
 CONST intf.pas:Path 'common\components\rtl\Garant\L3\l3InterfacedDataObject.imp.pas'
 CONST extprop:pas:TypeName '_l3InterfacedDataObject_'
 CONST extprop:pas:UnitName 'l3InterfacedDataObject.imp'

ref; // ME_4680F7A602E3 l3InterfacedDataObject

FORWARD ME_4680F8DE02E2

: ME_48F4B33501DE
 CONST UID '48F4B33501DE'
 CONST Name 'GetFormats'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_4680F8DE02E2 // l3TreeDataObject
 ;
 : Target WL 'ME_46A449C50391' '4677FBA70343.pas.ms.script' // Tl3ClipboardFormats
 ;

ref; // ME_48F4B33501DE GetFormats

: ME_48F4B354026F
 CONST Name 'aData'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_48F8C8C201F0 // DataType
 ;

ref; // ME_48F4B354026F aData

: ME_48F4B34B0192
 CONST UID '48F4B34B0192'
 CONST Name 'Create'
 CONST Class class_Operation
 : Stereotype st_vctor::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4680F8DE02E2 // l3TreeDataObject
 ;
 : Parameters
   Seq: ( ME_48F4B354026F // aData
 )
 ; // Parameters

ref; // ME_48F4B34B0192 Create

: ME_48F4B44F021D
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F8DE02E2 // l3TreeDataObject
 ;
 : Target WL 'ME_4773D64E036C' '47913B47006E.pas.ms.script' // l3Base
 ;

ref; // ME_48F4B44F021D 

: ME_48F4B4A101C5
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F8DE02E2 // l3TreeDataObject
 ;
 : Target WL 'ME_47725360003C' '4682595B0268.pas.ms.script' // Pl3TreeData
 ;

ref; // ME_48F4B4A101C5 

: ME_48F4B508009E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F8DE02E2 // l3TreeDataObject
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_48F4B508009E 

FORWARD ME_48F4B5300085

: ME_48F4B5520210
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F8DE02E2 // l3TreeDataObject
 ;
 : Target ME_48F4B5300085 // l3TreeConst
 ;

ref; // ME_48F4B5520210 

: ME_48F4B5AF0091
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F8DE02E2 // l3TreeDataObject
 ;
 : Target WL 'ME_48A41FF10094' '4AB0C3F60375.pas.ms.script' // Windows
 ;

ref; // ME_48F4B5AF0091 

: ME_48F3495D0398_ME_4680F8DE02E2
 : Original ME_48F3495D0398 // DoGetData
 ;
 : Implementor ME_4680F8DE02E2 // l3TreeDataObject
 ;
 CONST OpKind opkind_Overridden
ref; // ME_48F3495D0398_ME_4680F8DE02E2 DoGetData

: ME_48F351BE0015_ME_4680F8DE02E2
 : Original ME_48F351BE0015 // AcceptableTymed
 ;
 : Implementor ME_4680F8DE02E2 // l3TreeDataObject
 ;
 CONST OpKind opkind_Overridden
ref; // ME_48F351BE0015_ME_4680F8DE02E2 AcceptableTymed

: ME_4680F8DE02E2
 CONST UID '4680F8DE02E2'
 CONST Name 'l3TreeDataObject'
 CONST Class class_Class
 : Stereotype st_Impurity ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Объект данных дерева' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5600033 // l3DataObject
 ;
 : Inherits
   Seq: ( ME_4680F7A602E3 // l3InterfacedDataObject
 )
 ; // Inherits
 : Operations
   Seq: ( ME_48F4B33501DE // GetFormats
 ME_48F4B34B0192 // Create
 )
 ; // Operations
 : Overridden
   Seq: ( ME_48F3495D0398_ME_4680F8DE02E2 // DoGetData
 ME_48F351BE0015_ME_4680F8DE02E2 // AcceptableTymed
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_48F4B44F021D // 
 ME_48F4B4A101C5 // 
 ME_48F4B508009E // 
 ME_48F4B5520210 // 
 ME_48F4B5AF0091 // 
 )
 ; // Dependencies
 CONST "author" 'Люлин А.В.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '14.12.2006 14:07'
 CONST intf.pas:Path 'common\components\rtl\Garant\L3\l3TreeDataObject.imp.pas'
 CONST extprop:pas:TypeName '_l3TreeDataObject_'
 CONST extprop:pas:UnitName 'l3TreeDataObject.imp'

ref; // ME_4680F8DE02E2 l3TreeDataObject

FORWARD ME_4680F7E70110

: ME_48F37ABE0354
 CONST Name 'aFormat'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A449A301E3' '4677FBA70343.pas.ms.script' // Tl3ClipboardFormat
 ;

ref; // ME_48F37ABE0354 aFormat

: ME_48F37ABE0371
 CONST Name 'aPool'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47E150FF028A' '4AB0997B00A2.pas.ms.script' // TStream
 ;

ref; // ME_48F37ABE0371 aPool

: ME_48F37AAF012F
 CONST UID '48F37AAF012F'
 CONST Name 'Store'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent ME_4680F7E70110 // Tl3StorableDataObject
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_48F37ABE0354 // aFormat
 ME_48F37ABE0371 // aPool
 )
 ; // Parameters

ref; // ME_48F37AAF012F Store

: ME_48F37ADD03BC
 CONST Name 'aFormat'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A449A301E3' '4677FBA70343.pas.ms.script' // Tl3ClipboardFormat
 ;

ref; // ME_48F37ADD03BC aFormat

: ME_48F37ADD03DC
 CONST Name 'aPool'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A5B0060013' '4677FBA70343.pas.ms.script' // IStream
 ;

ref; // ME_48F37ADD03DC aPool

: ME_48F37AC50290
 CONST UID '48F37AC50290'
 CONST Name 'Store'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent ME_4680F7E70110 // Tl3StorableDataObject
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_48F37ADD03BC // aFormat
 ME_48F37ADD03DC // aPool
 )
 ; // Parameters

ref; // ME_48F37AC50290 Store

: ME_48F37DA50143
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F7E70110 // Tl3StorableDataObject
 ;
 : Target WL 'ME_47A080670100' '47913B47006E.pas.ms.script' // l3Stream
 ;

ref; // ME_48F37DA50143 

: ME_48F37DF903BE
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F7E70110 // Tl3StorableDataObject
 ;
 : Target WL 'ME_47AB1FDE03E4' '47913B47006E.pas.ms.script' // l3Memory
 ;

ref; // ME_48F37DF903BE 

: ME_48F37E1703B7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F7E70110 // Tl3StorableDataObject
 ;
 : Target WL 'ME_4773D64E036C' '47913B47006E.pas.ms.script' // l3Base
 ;

ref; // ME_48F37E1703B7 

: ME_48F37E37000C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F7E70110 // Tl3StorableDataObject
 ;
 : Target WL 'ME_47A082F101DB' '476BE98C01B8.pas.ms.script' // Ext Chars
 ;

ref; // ME_48F37E37000C 

: ME_48F3495D0398_ME_4680F7E70110
 : Original ME_48F3495D0398 // DoGetData
 ;
 : Implementor ME_4680F7E70110 // Tl3StorableDataObject
 ;
 CONST OpKind opkind_Overridden
ref; // ME_48F3495D0398_ME_4680F7E70110 DoGetData

: ME_48F349AE00F1_ME_4680F7E70110
 : Original ME_48F349AE00F1 // DoGetDataHere
 ;
 : Implementor ME_4680F7E70110 // Tl3StorableDataObject
 ;
 CONST OpKind opkind_Overridden
ref; // ME_48F349AE00F1_ME_4680F7E70110 DoGetDataHere

: ME_48F351BE0015_ME_4680F7E70110
 : Original ME_48F351BE0015 // AcceptableTymed
 ;
 : Implementor ME_4680F7E70110 // Tl3StorableDataObject
 ;
 CONST OpKind opkind_Overridden
ref; // ME_48F351BE0015_ME_4680F7E70110 AcceptableTymed

: ME_4680F7E70110
 CONST UID '4680F7E70110'
 CONST Name 'Tl3StorableDataObject'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Класс для реализации интерфейса IDataObject для выделения текста редактора.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5600033 // l3DataObject
 ;
 : Inherits
   Seq: ( ME_4680F5AA0274 // Tl3DataObject
 )
 ; // Inherits
 : Operations
   Seq: ( ME_48F37AAF012F // Store
 ME_48F37AC50290 // Store
 )
 ; // Operations
 : Overridden
   Seq: ( ME_48F3495D0398_ME_4680F7E70110 // DoGetData
 ME_48F349AE00F1_ME_4680F7E70110 // DoGetDataHere
 ME_48F351BE0015_ME_4680F7E70110 // AcceptableTymed
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_48F37DA50143 // 
 ME_48F37DF903BE // 
 ME_48F37E1703B7 // 
 ME_48F37E37000C // 
 )
 ; // Dependencies
 CONST "author" 'Люлин А.В.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '13.12.2006 14:32'
 CONST intf.pas:Path 'common\components\rtl\Garant\L3\l3StorableDataObject.pas'
 CONST extprop:rc:SelfName 'StorableDataObject'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'l3StorableDataObject'

ref; // ME_4680F7E70110 Tl3StorableDataObject

: ME_48F3548300E3
 CONST UID '48F3548300E3'
 CONST Name 'f_DataObject'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_lnk
 : Parent ME_4680F5FF01EA // Tl3DataObjectEnum
 ;
 : Target ME_4680F5AA0274 // Tl3DataObject
 ;

ref; // ME_48F3548300E3 f_DataObject

: ME_48F3548702B0
 CONST UID '48F3548702B0'
 CONST Name 'f_Index'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_lnk
 : Parent ME_4680F5FF01EA // Tl3DataObjectEnum
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_48F3548702B0 f_Index

: ME_48F33CD1007B
 CONST Name 'aDataObject'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4680F5AA0274 // Tl3DataObject
 ;

ref; // ME_48F33CD1007B aDataObject

: ME_48F33CD1004D
 CONST UID '48F33CD1004D'
 CONST Name 'Make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4680F5FF01EA // Tl3DataObjectEnum
 ;
 : Target WL 'ME_4680F4A100A7' '4677FBA70343.pas.ms.script' // IEnumFormatEtc
 ;
 : Parameters
   Seq: ( ME_48F33CD1007B // aDataObject
 )
 ; // Parameters
 CONST "check nil" false
 CONST "need AfterCreate" 'undefined'
 CONST "need Aggregate" 'undefined'
 CONST "need As" false

ref; // ME_48F33CD1004D Make

: ME_48F33CE70195
 CONST Name 'aDataObject'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4680F5AA0274 // Tl3DataObject
 ;

ref; // ME_48F33CE70195 aDataObject

: ME_48F33CE302EC
 CONST UID '48F33CE302EC'
 CONST Name 'Create'
 CONST Class class_Operation
 : Stereotype st_ctor::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4680F5FF01EA // Tl3DataObjectEnum
 ;
 : Parameters
   Seq: ( ME_48F33CE70195 // aDataObject
 )
 ; // Parameters

ref; // ME_48F33CE302EC Create

: ME_48F355B203AE
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F5FF01EA // Tl3DataObjectEnum
 ;
 : Target WL 'ME_47A066980016' '537B83AD01F0.pas.ms.script' // l3MinMax
 ;

ref; // ME_48F355B203AE 

: ME_4F9BF68600A5
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4680F5FF01EA // Tl3DataObjectEnum
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_4F9BF68600A5 

: ME_48F33755005D_ME_4680F5FF01EA
 : Original WL 'ME_48F33755005D' '46A0E6C5023A.pas.ms.script' // Next
 ;
 : Implementor ME_4680F5FF01EA // Tl3DataObjectEnum
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F33755005D_ME_4680F5FF01EA Next

: ME_48F33790021D_ME_4680F5FF01EA
 : Original WL 'ME_48F33790021D' '46A0E6C5023A.pas.ms.script' // Skip
 ;
 : Implementor ME_4680F5FF01EA // Tl3DataObjectEnum
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F33790021D_ME_4680F5FF01EA Skip

: ME_48F337A20394_ME_4680F5FF01EA
 : Original WL 'ME_48F337A20394' '46A0E6C5023A.pas.ms.script' // Reset
 ;
 : Implementor ME_4680F5FF01EA // Tl3DataObjectEnum
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F337A20394_ME_4680F5FF01EA Reset

: ME_48F337B1039E_ME_4680F5FF01EA
 : Original WL 'ME_48F337B1039E' '46A0E6C5023A.pas.ms.script' // Clone
 ;
 : Implementor ME_4680F5FF01EA // Tl3DataObjectEnum
 ;
 CONST OpKind opkind_Implemented
 CONST "calling conventions" 'stdcall'
ref; // ME_48F337B1039E_ME_4680F5FF01EA Clone

: ME_479731C50290_ME_4680F5FF01EA
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 : Implementor ME_4680F5FF01EA // Tl3DataObjectEnum
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_4680F5FF01EA Cleanup

: ME_4680F5FF01EA
 CONST UID '4680F5FF01EA'
 CONST Name 'Tl3DataObjectEnum'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Реализация итератора для данных Tl3DataObject.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5600033 // l3DataObject
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4680F4A100A7' '4677FBA70343.pas.ms.script' // IEnumFormatEtc
 )
 ; // Implements
 : Attributes
   Seq: ( ME_48F3548300E3 // f_DataObject
 ME_48F3548702B0 // f_Index
 )
 ; // Attributes
 : Operations
   Seq: ( ME_48F33CD1004D // Make
 ME_48F33CE302EC // Create
 )
 ; // Operations
 : Implemented
   Seq: ( ME_48F33755005D_ME_4680F5FF01EA // Next
 ME_48F33790021D_ME_4680F5FF01EA // Skip
 ME_48F337A20394_ME_4680F5FF01EA // Reset
 ME_48F337B1039E_ME_4680F5FF01EA // Clone
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_4680F5FF01EA // Cleanup
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_48F355B203AE // 
 ME_4F9BF68600A5 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\L3\l3DataObjectEnum.pas'
 CONST extprop:rc:SelfName 'DataObjectEnum'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'l3DataObjectEnum'

ref; // ME_4680F5FF01EA Tl3DataObjectEnum

: ME_48F4B5600372
 CONST UID '48F4B5600372'
 CONST Name 'CF_TreeNode'
 CONST Class class_Attribute
 %SUMMARY 'формат для на одного узла в буфере' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_48F4B5300085 // l3TreeConst
 ;
 : Target WL 'ME_46A449A301E3' '4677FBA70343.pas.ms.script' // Tl3ClipboardFormat
 ;
 CONST Value 0
 : ValueType WL 'ME_46A449A301E3' '4677FBA70343.pas.ms.script' // Tl3ClipboardFormat
 ;
 CONST extprop:pas:Value 0

ref; // ME_48F4B5600372 CF_TreeNode

: ME_48F4B57002CD
 CONST UID '48F4B57002CD'
 CONST Name 'CF_TreeNodes'
 CONST Class class_Attribute
 %SUMMARY 'формат для нескольких узлов в буфере' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_48F4B5300085 // l3TreeConst
 ;
 : Target WL 'ME_46A449A301E3' '4677FBA70343.pas.ms.script' // Tl3ClipboardFormat
 ;
 CONST Value 0
 : ValueType WL 'ME_46A449A301E3' '4677FBA70343.pas.ms.script' // Tl3ClipboardFormat
 ;
 CONST extprop:pas:Value 0

ref; // ME_48F4B57002CD CF_TreeNodes

: ME_48F4B57C010F
 CONST UID '48F4B57C010F'
 CONST Name 'ini'
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_48F4B5300085 // l3TreeConst
 ;

ref; // ME_48F4B57C010F ini

: ME_48F4B5A0031E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_48F4B5300085 // l3TreeConst
 ;
 : Target WL 'ME_48A41FF10094' '4AB0C3F60375.pas.ms.script' // Windows
 ;

ref; // ME_48F4B5A0031E 

: ME_48F4B5300085
 CONST UID '48F4B5300085'
 CONST Name 'l3TreeConst'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4680F5600033 // l3DataObject
 ;
 : Attributes
   Seq: ( ME_48F4B5600372 // CF_TreeNode
 ME_48F4B57002CD // CF_TreeNodes
 )
 ; // Attributes
 : Operations
   Seq: ( ME_48F4B57C010F // ini
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_48F4B5A0031E // 
 )
 ; // Dependencies
 CONST "author" 'Люлин А.В.'
 CONST "no hands" true
 CONST "started" '26.12.2007 16:18'
 CONST intf.pas:Path 'common\components\rtl\Garant\L3\l3TreeConst.pas'
 CONST extprop:rc:SelfName 'TreeConst'

ref; // ME_48F4B5300085 l3TreeConst

FORWARD ME_55E5CAA801A1

: ME_55E5CAF200C6
 CONST UID '55E5CAF200C6'
 CONST Name 'f_String'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent ME_55E5CAA801A1 // Tl3CStringDataObject
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55E5CAF200C6 f_String

FORWARD ME_55E5CB0A0231

: ME_55E5CB1A0300
 CONST Name 'aString'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55E5CB1A0300 aString

: ME_55E5CB1102D4
 CONST UID '55E5CB1102D4'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55E5CB0A0231 // Create
 ;
 : Parameters
   Seq: ( ME_55E5CB1A0300 // aString
 )
 ; // Parameters

ref; // ME_55E5CB1102D4 DoIt

: ME_55E5CB0A0231
 CONST UID '55E5CB0A0231'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_55E5CAA801A1 // Tl3CStringDataObject
 ;
 : Operations
   Seq: ( ME_55E5CB1102D4 // DoIt
 )
 ; // Operations

ref; // ME_55E5CB0A0231 Create

FORWARD ME_55E5CB2C01E4

: ME_99E27A2E9AA0
 CONST Name 'aString'
 CONST IsSummoned true
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_99E27A2E9AA0 aString

: ME_709153B31130
 CONST UID '709153B31130'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY 'Сигнатура фабрики Tl3CStringDataObject.Make' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55E5CB2C01E4 // Make
 ;
 : Target WL 'ME_4680F4790135' '4677FBA70343.pas.ms.script' // IDataObject
 ;
 : Parameters
   Seq: ( ME_99E27A2E9AA0 // aString
 )
 ; // Parameters

ref; // ME_709153B31130 DoIt

: ME_55E5CB2C01E4
 CONST UID '55E5CB2C01E4'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_55E5CAA801A1 // Tl3CStringDataObject
 ;
 : Inherits
   Seq: ( ME_55E5CB0A0231 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4680F4790135' '4677FBA70343.pas.ms.script' // IDataObject
 )
 ; // Implements
 : Operations
   Seq: ( ME_709153B31130 // DoIt
 )
 ; // Operations
 CONST "check nil" false
 CONST "need AfterCreate" 'undefined'
 CONST "need Aggregate" 'undefined'
 CONST "need As" false

ref; // ME_55E5CB2C01E4 Make

: ME_55E5CBCF014B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55E5CAA801A1 // Tl3CStringDataObject
 ;
 : Target WL 'ME_46A5B0060013' '4677FBA70343.pas.ms.script' // IStream
 ;

ref; // ME_55E5CBCF014B 

: ME_55E5CBEC0188
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55E5CAA801A1 // Tl3CStringDataObject
 ;
 : Target WL 'ME_4ADEE49C02DF' '4AB0C3C60310.pas.ms.script' // Supports
 ;

ref; // ME_55E5CBEC0188 

: ME_55E5DDC80026
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55E5CAA801A1 // Tl3CStringDataObject
 ;
 : Target WL 'ME_4773DED9004C' '47913B47006E.pas.ms.script' // Tl3_String
 ;

ref; // ME_55E5DDC80026 

: ME_55E5DDD8020D
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55E5CAA801A1 // Tl3CStringDataObject
 ;
 : Target WL 'ME_49082AE80393' '476BE98C01B8.pas.ms.script' // Code Pages
 ;

ref; // ME_55E5DDD8020D 

: ME_55E6FF840369
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55E5CAA801A1 // Tl3CStringDataObject
 ;
 : Target WL 'ME_47878E0E0191' '54B90AC6014B.pas.ms.script' // l3String
 ;

ref; // ME_55E6FF840369 

: ME_56BDD78C01A7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55E5CAA801A1 // Tl3CStringDataObject
 ;
 : Target WL 'ME_48A41FF10094' '4AB0C3F60375.pas.ms.script' // Windows
 ;

ref; // ME_56BDD78C01A7 

: ME_4680FC190114_ME_55E5CAA801A1
 : Original WL 'ME_4680FC190114' '4677FBA70343.pas.ms.script' // IsQuestionNeedBeforeFlush
 ;
 : Implementor ME_55E5CAA801A1 // Tl3CStringDataObject
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_4680FC190114_ME_55E5CAA801A1 IsQuestionNeedBeforeFlush

: ME_48F37AC50290_ME_55E5CAA801A1
 : Original ME_48F37AC50290 // Store
 ;
 : Implementor ME_55E5CAA801A1 // Tl3CStringDataObject
 ;
 CONST OpKind opkind_Implemented
ref; // ME_48F37AC50290_ME_55E5CAA801A1 Store

: ME_55E5CAA801A1
 CONST UID '55E5CAA801A1'
 CONST Name 'Tl3CStringDataObject'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4680F5600033 // l3DataObject
 ;
 : Inherits
   Seq: ( ME_4680F7E70110 // Tl3StorableDataObject
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4680FBF2003C' '4677FBA70343.pas.ms.script' // Il3DataObjectInfo
 )
 ; // Implements
 : Attributes
   Seq: ( ME_55E5CAF200C6 // f_String
 )
 ; // Attributes
 : Operations
   Seq: ( ME_55E5CB0A0231 // Create
 ME_55E5CB2C01E4 // Make
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4680FC190114_ME_55E5CAA801A1 // IsQuestionNeedBeforeFlush
 ME_48F37AC50290_ME_55E5CAA801A1 // Store
 )
 ; // Implemented
 : Dependencies
   Seq: ( ME_55E5CBCF014B // 
 ME_55E5CBEC0188 // 
 ME_55E5DDC80026 // 
 ME_55E5DDD8020D // 
 ME_55E6FF840369 // 
 ME_56BDD78C01A7 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\L3\l3CStringDataObject.pas'
 CONST extprop:rc:SelfName 'CStringDataObject'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'l3CStringDataObject'

ref; // ME_55E5CAA801A1 Tl3CStringDataObject

: ME_4680F5600033
 CONST UID '4680F5600033'
 CONST Name 'l3DataObject'
 CONST Class class_Category
 : Stereotype st_Unit ;
 %SUMMARY 'Классы для работы с IDataObject.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4790D09A0378' '4790D09A0378.pas.ms.script' // L3
 ;
 : Children
   Seq: ( ME_4680F5AA0274 // Tl3DataObject
 ME_4680F70C0255 // Tl3BitmapDataObject
 ME_4680F7A602E3 // l3InterfacedDataObject
 ME_4680F8DE02E2 // l3TreeDataObject
 ME_4680F7E70110 // Tl3StorableDataObject
 ME_4680F5FF01EA // Tl3DataObjectEnum
 ME_48F4B5300085 // l3TreeConst
 ME_55E5CAA801A1 // Tl3CStringDataObject
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4677FBA70343' '4677FBA70343.pas.ms.script' // l3Interfaces
 WL 'ME_467C0CAA02AB' '467C0CAA02AB.pas.ms.script' // l3InternalInterfaces
 WL 'ME_4682595B0268' '4682595B0268.pas.ms.script' // l3TreeInterfaces
 WL 'ME_476BE98C01B8' '476BE98C01B8.pas.ms.script' // l3Chars
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_4AB0997B00A2' '4AB0997B00A2.pas.ms.script' // Common
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_4AB0C3F60375' '4AB0C3F60375.pas.ms.script' // Win
 WL 'ME_537B83AD01F0' '537B83AD01F0.pas.ms.script' // l3Math
 WL 'ME_54B90AC6014B' '54B90AC6014B.pas.ms.script' // StringUtils
 )
 ; // Depends
 CONST "UseNewGen" true

ref; // ME_4680F5600033 l3DataObject
