// TnsNodeStorable 468271030094 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_468271030094

ME ME_52EBD7C800C5
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_468271030094 // TnsNodeStorable
 ;
 MELINK Target WL 'ME_45EEDC6F01D7' '4570501E037A.ms.model.script' // FoldersItemType
 ;

ENDME // ME_52EBD7C800C5 

ME ME_52EBD7CA03CF
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_468271030094 // TnsNodeStorable
 ;
 MELINK Target WL 'ME_45EEB65202A0' '4570511E038A.ms.model.script' // Bookmark
 ;

ENDME // ME_52EBD7CA03CF 

ME ME_52EBD7CC02A4
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_468271030094 // TnsNodeStorable
 ;
 MELINK Target WL? 'ME_47877EB202FB' // SysUtils
 ;

ENDME // ME_52EBD7CC02A4 

ME ME_52EBD7CE012A
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_468271030094 // TnsNodeStorable
 ;
 MELINK Target WL 'ME_456EB3E10177' '456EA56002BF.ms.model.script' // EntityBase
 ;

ENDME // ME_52EBD7CE012A 

ME ME_52EBD7D0003E
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_468271030094 // TnsNodeStorable
 ;
 MELINK Target WL 'ME_456FE63B01D4' '456F02A50196.ms.model.script' // Node
 ;

ENDME // ME_52EBD7D0003E 

ME ME_52EBD7D10379
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_468271030094 // TnsNodeStorable
 ;
 MELINK Target WL 'ME_47C6B03200AF' '47C5207602D1.ms.model.script' // IevSub
 ;

ENDME // ME_52EBD7D10379 

ME ME_52EBD7D40035
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_468271030094 // TnsNodeStorable
 ;
 MELINK Target WL 'ME_484AB26803DB' '469D0AC7005E.ms.model.script' // Hyperlink Const
 ;

ENDME // ME_52EBD7D40035 

MEREF ME_48F494F102DD_ME_468271030094_over
 MELINK Original WL 'ME_48F494F102DD' '48F4945A02FF.ms.model.script' // GetAddress
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_48F494F102DD_ME_468271030094_over GetAddress

MEREF ME_48F4D8230366_ME_468271030094_G
 MELINK Original WL? 'ME_48F4D8230366' // TevNodeStorable
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_48F4D8230366_ME_468271030094_G TevNodeStorable

%%InheritedBy ME_48F4D8230366 ME_468271030094

ME ME_468271030094
 MEPROP UID '468271030094'
 MEPROP Name 'TnsNodeStorable'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_52DE57B200A5' // Tree$WithDnD
 ;
 MELIST Inherits
   Seq: ( ME_48F4D8230366_ME_468271030094_G // TevNodeStorable
 )
 ; // Inherits
 MELIST Overridden
   Seq: ( ME_48F494F102DD_ME_468271030094_over // GetAddress
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_52EBD7C800C5 // FoldersItemType
 ME_52EBD7CA03CF // Bookmark
 ME_52EBD7CC02A4 // SysUtils
 ME_52EBD7CE012A // EntityBase
 ME_52EBD7D0003E // Node
 ME_52EBD7D10379 // IevSub
 ME_52EBD7D40035 // Hyperlink Const
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Components\nsNodeStorable.pas'
 UP extprop:rc:SelfName 'NodeStorable'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nsNodeStorable'

ENDME // ME_468271030094 TnsNodeStorable
