// ExprMake 4739A0A5032E Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4739A0A5032E
%%Inner ME_4739A0A5032E

ME ME_4739A0A5032E
 MEPROP UID '4739A0A5032E'
 MEPROP Name 'ExprMake'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 %SUMMARY 'Библиотека ExprMake предназначена для автоматизации построения формул с помощью библиотеки ExprDraw.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_473987420315' // Expr
 ;
 MELIST Children
   Seq: ( WL? 'ME_4BB3497F03CC' // TexprTokensList
 WL? 'ME_4739A8C90148' // ExprMake
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4677FBA70343' // l3Interfaces
 WL? 'ME_47398897018F' // ExprDraw
 WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_4AB0C3C60310' // Sys
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_4739A0A5032E ExprMake
