// l3Drawer 4739AB8601AA Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4739AB8601AA

FORWARD ME_4739AF6301B6

FORWARD ME_4739AF7A0250

: ME_4739AFA2004E
 CONST UID '4739AFA2004E'
 CONST Name 'l3_dmGDIPlus'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_4739AF7A0250 // Tl3DrawerMode
 ;

ref; // ME_4739AFA2004E l3_dmGDIPlus

: ME_4739AFA90333
 CONST UID '4739AFA90333'
 CONST Name 'l3_dmGDI'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_4739AF7A0250 // Tl3DrawerMode
 ;

ref; // ME_4739AFA90333 l3_dmGDI

: ME_4739AF7A0250
 CONST UID '4739AF7A0250'
 CONST Name 'Tl3DrawerMode'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4739AF6301B6 // l3Drawer
 ;
 : Attributes
   Seq: ( HWL ME_4739AFA2004E // l3_dmGDIPlus
 HWL ME_4739AFA90333 // l3_dmGDI
 )
 ; // Attributes
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4739AF7A0250 Tl3DrawerMode

FORWARD ME_4739ABDB029D

: ME_4739AEE803E0
 CONST UID '4739AEE803E0'
 CONST Name 'Canvas'
 CONST Class class_Attribute
 %SUMMARY 'Канва для рисования.' ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_4739ABDB029D // Tl3Drawer
 ;
 : Target WL 'ME_515581580039' '55C4AEC801CA.pas.ms.script' // TCanvas
 ;

ref; // ME_4739AEE803E0 Canvas

: ME_4739AF1C02C3
 CONST UID '4739AF1C02C3'
 CONST Name 'PenColor'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_4739ABDB029D // Tl3Drawer
 ;
 : Target WL 'ME_46A44A9E0112' '4677FBA70343.pas.ms.script' // Tl3Color
 ;

ref; // ME_4739AF1C02C3 PenColor

: ME_4739AF29005E
 CONST UID '4739AF29005E'
 CONST Name 'BrushColor'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_4739ABDB029D // Tl3Drawer
 ;
 : Target WL 'ME_46A44A9E0112' '4677FBA70343.pas.ms.script' // Tl3Color
 ;

ref; // ME_4739AF29005E BrushColor

: ME_4739AFBA039C
 CONST UID '4739AFBA039C'
 CONST Name 'Mode'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_4739ABDB029D // Tl3Drawer
 ;
 : Target HWL ME_4739AF7A0250 // Tl3DrawerMode
 ;

ref; // ME_4739AFBA039C Mode

: ME_4739AC1A02F7
 CONST Name 'X1'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739AC1A02F7 X1

: ME_4739AC1A0315
 CONST Name 'Y1'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739AC1A0315 Y1

: ME_4739AC1A033E
 CONST Name 'X2'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739AC1A033E X2

: ME_4739AC1A035C
 CONST Name 'Y2'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739AC1A035C Y2

: ME_4739AC0801D9
 CONST UID '4739AC0801D9'
 CONST Name 'DrawLine'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4739ABDB029D // Tl3Drawer
 ;
 : Parameters
   Seq: ( ME_4739AC1A02F7 // X1
 ME_4739AC1A0315 // Y1
 ME_4739AC1A033E // X2
 ME_4739AC1A035C // Y2
 )
 ; // Parameters

ref; // ME_4739AC0801D9 DrawLine

: ME_4739AC8F02F6
 CONST Name 'X1'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739AC8F02F6 X1

: ME_4739AC8F0314
 CONST Name 'Y1'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739AC8F0314 Y1

: ME_4739AC8F033C
 CONST Name 'X2'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739AC8F033C X2

: ME_4739AC8F0364
 CONST Name 'Y2'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739AC8F0364 Y2

: ME_4739AC7E016B
 CONST UID '4739AC7E016B'
 CONST Name 'DrawEllipse'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4739ABDB029D // Tl3Drawer
 ;
 : Parameters
   Seq: ( ME_4739AC8F02F6 // X1
 ME_4739AC8F0314 // Y1
 ME_4739AC8F033C // X2
 ME_4739AC8F0364 // Y2
 )
 ; // Parameters

ref; // ME_4739AC7E016B DrawEllipse

: ME_4739ACAC0153
 CONST Name 'X1'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739ACAC0153 X1

: ME_4739ACAC017B
 CONST Name 'Y1'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739ACAC017B Y1

: ME_4739ACAC01A3
 CONST Name 'X2'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739ACAC01A3 X2

: ME_4739ACAC01CB
 CONST Name 'Y2'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739ACAC01CB Y2

: ME_4739AC99032C
 CONST UID '4739AC99032C'
 CONST Name 'DrawRect'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4739ABDB029D // Tl3Drawer
 ;
 : Parameters
   Seq: ( ME_4739ACAC0153 // X1
 ME_4739ACAC017B // Y1
 ME_4739ACAC01A3 // X2
 ME_4739ACAC01CB // Y2
 )
 ; // Parameters

ref; // ME_4739AC99032C DrawRect

: ME_4739ACDC01AC
 CONST Name 'Points'
 CONST Class class_Parameter
 : Stereotype st_const ;
 : Target WL 'ME_4739AD740178' '46A5E026007E.pas.ms.script' // TPointsArray
 ;

ref; // ME_4739ACDC01AC Points

: ME_4739ACBB02E5
 CONST UID '4739ACBB02E5'
 CONST Name 'DrawPolygon'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4739ABDB029D // Tl3Drawer
 ;
 : Parameters
   Seq: ( ME_4739ACDC01AC // Points
 )
 ; // Parameters

ref; // ME_4739ACBB02E5 DrawPolygon

: ME_4739ADFB024F
 CONST Name 'X1'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739ADFB024F X1

: ME_4739ADFB0281
 CONST Name 'Y1'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739ADFB0281 Y1

: ME_4739ADFB02A9
 CONST Name 'X2'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739ADFB02A9 X2

: ME_4739ADFB02DB
 CONST Name 'Y2'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739ADFB02DB Y2

: ME_4739ADEF01F7
 CONST UID '4739ADEF01F7'
 CONST Name 'FillEllipse'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4739ABDB029D // Tl3Drawer
 ;
 : Parameters
   Seq: ( ME_4739ADFB024F // X1
 ME_4739ADFB0281 // Y1
 ME_4739ADFB02A9 // X2
 ME_4739ADFB02DB // Y2
 )
 ; // Parameters

ref; // ME_4739ADEF01F7 FillEllipse

: ME_4739AE43011C
 CONST Name 'X1'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739AE43011C X1

: ME_4739AE43014E
 CONST Name 'Y1'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739AE43014E Y1

: ME_4739AE430180
 CONST Name 'X2'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739AE430180 X2

: ME_4739AE4301B2
 CONST Name 'Y2'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4739AE4301B2 Y2

: ME_4739AE3300F1
 CONST UID '4739AE3300F1'
 CONST Name 'FillRect'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4739ABDB029D // Tl3Drawer
 ;
 : Parameters
   Seq: ( ME_4739AE43011C // X1
 ME_4739AE43014E // Y1
 ME_4739AE430180 // X2
 ME_4739AE4301B2 // Y2
 )
 ; // Parameters

ref; // ME_4739AE3300F1 FillRect

: ME_47726974001F
 CONST Name 'Points'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4739AD740178' '46A5E026007E.pas.ms.script' // TPointsArray
 ;

ref; // ME_47726974001F Points

: ME_4739AE6C0279
 CONST UID '4739AE6C0279'
 CONST Name 'FillPolygon'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4739ABDB029D // Tl3Drawer
 ;
 : Parameters
   Seq: ( ME_47726974001F // Points
 )
 ; // Parameters

ref; // ME_4739AE6C0279 FillPolygon

: ME_4739ABDB029D
 CONST UID '4739ABDB029D'
 CONST Name 'Tl3Drawer'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY '"Универсальный отрисовщик", использующий по возможности функции GDI+' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4739AF6301B6 // l3Drawer
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_4739AEE803E0 // Canvas
 HWL ME_4739AF1C02C3 // PenColor
 HWL ME_4739AF29005E // BrushColor
 HWL ME_4739AFBA039C // Mode
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_4739AC0801D9 // DrawLine
 HWL ME_4739AC7E016B // DrawEllipse
 HWL ME_4739AC99032C // DrawRect
 HWL ME_4739ACBB02E5 // DrawPolygon
 HWL ME_4739ADEF01F7 // FillEllipse
 HWL ME_4739AE3300F1 // FillRect
 HWL ME_4739AE6C0279 // FillPolygon
 )
 ; // Operations
 CONST "author" 'Жучков А.Ю.'
 CONST "started" '2007/11/06 09:34:31'
 CONST extprop:rc:SelfName 'Drawer'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4739ABDB029D Tl3Drawer

: ME_4739AF6301B6
 CONST UID '4739AF6301B6'
 CONST Name 'l3Drawer'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_4739AB8601AA // l3Drawer
 ;
 : Children
   Seq: ( HWL ME_4739AF7A0250 // Tl3DrawerMode
 HWL ME_4739ABDB029D // Tl3Drawer
 )
 ; // Children
 CONST "author" 'Жучков А.Ю.'
 CONST "finished" false
 CONST "started" '2007/11/06 09:34:31'
 CONST intf.pas:Path 'common\components\rtl\Garant\L3\NOT_FINISHED_l3Drawer.pas'
 CONST extprop:rc:SelfName 'Drawer'

ref; // ME_4739AF6301B6 l3Drawer

: ME_4739AB8601AA
 CONST UID '4739AB8601AA'
 CONST Name 'l3Drawer'
 CONST Class class_Category
 : Stereotype st_Unit ;
 %SUMMARY '"Универсальный отрисовщик", использующий по возможности функции GDI+' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4790D09A0378' '4790D09A0378.pas.ms.script' // L3
 ;
 : Children
   Seq: ( HWL ME_4739AF6301B6 // l3Drawer
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 WL 'ME_4677FBA70343' '4677FBA70343.pas.ms.script' // l3Interfaces
 WL 'ME_46A5E026007E' '46A5E026007E.pas.ms.script' // l3Core
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_55C4AEC801CA' '55C4AEC801CA.pas.ms.script' // Graphics
 )
 ; // Depends

ref; // ME_4739AB8601AA l3Drawer
