// l3Defaults 4799EC9300AF Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4799EC9300AF

ME ME_4799EC9300AF
 MEPROP UID '4799EC9300AF'
 MEPROP Name 'l3Defaults'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 %SUMMARY 'Значения по умолчанию библиотеки L3.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4790D09A0378' // L3
 ;
 MELIST Children
   Seq: ( WL? 'ME_4799ED060093' // l3Defaults
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4AB0C3C60310' // Sys
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "is namespace" true

ENDME // ME_4799EC9300AF l3Defaults
