// Tl3BaseRecList 479DF7E200A3 SimpleClass Class

INCLUDE '479DF9D50043.pas.ms.script'

INCLUDE '47B433E500BC.pas.ms.script'

FORWARD ME_479DF7E200A3

INCLUDE '4807744200AA.pas.ms.script'

: ME_47BF07ED0281
 CONST UID '47BF07ED0281'
 CONST Name 'A'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_46A606AC03B2 // Integer
 ;

 @SELF
; // ME_47BF07ED0281 A

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_47BF07ED02CA
 CONST UID '47BF07ED02CA'
 CONST Name 'B'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'

 @SELF
; // ME_47BF07ED02CA B

: ME_47BF07ED0313
 CONST UID '47BF07ED0313'
 CONST Name 'aDataSize'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_46A618AF0053 // Cardinal
 ;

 @SELF
; // ME_47BF07ED0313 aDataSize

: ME_47BF07D000E6
 CONST UID '47BF07D000E6'
 CONST Name 'CompareItem'
 CONST Class 'Operation'
 CONST Stereotype ''
 %SUMMARY 'aDataSize - размер сравниваемой части записи, если 0, то вся запись' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Target ME_46A606AC03B2 // Integer
 ;
 : Parameters
   [ ME_47BF07ED0281 // A
 ME_47BF07ED02CA // B
 ME_47BF07ED0313 // aDataSize
 ]
 ; // Parameters

 @SELF
; // ME_47BF07D000E6 CompareItem

: ME_479DF7E200A3
 CONST UID '479DF7E200A3'
 CONST Name 'Tl3BaseRecList'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_479DF9D50043 // Tl3ProtoPtrRecList
 ]
 ; // Inherits
 : Operations
   [ ME_47BF07D000E6 // CompareItem
 ]
 ; // Operations
 : Implemented
   [ ME_47BC677E02B1 // DoCompare
 ]
 ; // Implemented
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_479DF7E200A3 Tl3BaseRecList
