// l3UntypedList 47B433E500BC Impurity Class

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_47B433E500BC
%%Inner ME_47B433E500BC
%%Inner ME_47B433E500BC

FORWARD ME_47B433E500BC

FORWARD ME_47B99B600208

ME ME_47B99B7E0000
 MEPROP UID '47B99B7E0000'
 MEPROP Name 'aLong'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_47B99B600208 // VOID
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_47B99B7E0000 aLong

ME ME_47B99B8E0147
 MEPROP UID '47B99B8E0147'
 MEPROP Name 'aByte'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_47B99B600208 // VOID
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_47B99B8E0147 aByte

ME ME_47B99B600208
 MEPROP UID '47B99B600208'
 MEPROP Name 'VOID'
 MEPROP Class class_Class
 MELINK Stereotype st_Struct ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Специальный тип, заменяющий void в C++.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELIST Attributes
   Seq: ( HWL ME_47B99B7E0000 // aLong
 HWL ME_47B99B8E0147 // aByte
 )
 ; // Attributes

ENDME // ME_47B99B600208 VOID

ME ME_4B87AD4701FD
 MEPROP UID '4B87AD4701FD'
 MEPROP Name 'l3Items_FillItem_NeedsList'
 MEPROP Class class_Class
 MELINK Stereotype st_Define ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Функции обработки элементов списка требуют знания о самом списке' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 UP extprop:rc:SelfName 'Items_FillItem_NeedsList'

ENDME // ME_4B87AD4701FD l3Items_FillItem_NeedsList

ME ME_4D5BFD5202BE
 MEPROP UID '4D5BFD5202BE'
 MEPROP Name 'l3Items_CompareItemsRec_NeedsRList'
 MEPROP Class class_Class
 MELINK Stereotype st_Define ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 UP extprop:rc:SelfName 'Items_CompareItemsRec_NeedsRList'

ENDME // ME_4D5BFD5202BE l3Items_CompareItemsRec_NeedsRList

ME ME_47BEE7FD01DC
 MEPROP UID '47BEE7FD01DC'
 MEPROP Name 'ItemSize'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;
 UP "needs field" false
 UP "pm" true

ENDME // ME_47BEE7FD01DC ItemSize

ME ME_47B99BAF004B
 MEPROP UID '47B99BAF004B'
 MEPROP Name 'ItemType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELINK Target HWL ME_47B99B600208 // VOID
 ;

ENDME // ME_47B99BAF004B ItemType

ME ME_47BC108C03C9
 MEPROP UID '47BC108C03C9'
 MEPROP Name 'Clear'
 MEPROP Class class_Operation
 %SUMMARY 'Очищает список.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;

ENDME // ME_47BC108C03C9 Clear

ME ME_47BC67A9001D
 MEPROP Name 'A'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;

ENDME // ME_47BC67A9001D A

ME ME_47BC67A90080
 MEPROP Name 'B'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;

ENDME // ME_47BC67A90080 B

ME ME_47BC67A900E4
 MEPROP Name 'DataSize'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A618AF0053' '4807744200AA.ms.model.script' // Cardinal
 ;

ENDME // ME_47BC67A900E4 DataSize

ME ME_47BC677E02B1
 MEPROP UID '47BC677E02B1'
 MEPROP Name 'DoCompare'
 MEPROP Class class_Operation
 %SUMMARY 'Сравнивает элементы.' ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;
 MELIST Parameters
   Seq: ( ME_47BC67A9001D // A
 ME_47BC67A90080 // B
 ME_47BC67A900E4 // DataSize
 )
 ; // Parameters

ENDME // ME_47BC677E02B1 DoCompare

ME ME_47BEEBFF02EC
 MEPROP Name 'aLo'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4767A382039E' '4677FBA70343.ms.model.script' // Tl3Index
 ;

ENDME // ME_47BEEBFF02EC aLo

ME ME_47BEEBFF035C
 MEPROP Name 'aHi'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4767A382039E' '4677FBA70343.ms.model.script' // Tl3Index
 ;

ENDME // ME_47BEEBFF035C aHi

ME ME_47BEEBFF03CE
 MEPROP Name 'Action'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_469FA03900D4' '4678193C009C.ms.model.script' // Tl3IteratorAction
 ;

ENDME // ME_47BEEBFF03CE Action

ME ME_47BEEBE602B1
 MEPROP UID '47BEEBE602B1'
 MEPROP Name 'Iterate'
 MEPROP Class class_Operation
 %SUMMARY 'перебирает все элементы хранилища с aLo по aHi.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;
 MELIST Parameters
   Seq: ( ME_47BEEBFF02EC // aLo
 ME_47BEEBFF035C // aHi
 ME_47BEEBFF03CE // Action
 )
 ; // Parameters

ENDME // ME_47BEEBE602B1 Iterate

ME ME_47BEEC1A0183
 MEPROP Name 'Action'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_469FA03900D4' '4678193C009C.ms.model.script' // Tl3IteratorAction
 ;

ENDME // ME_47BEEC1A0183 Action

ME ME_47BEEC10022E
 MEPROP UID '47BEEC10022E'
 MEPROP Name 'IterateAll'
 MEPROP Class class_Operation
 %SUMMARY 'перебирает все элементы хранилища.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;
 MELIST Parameters
   Seq: ( ME_47BEEC1A0183 // Action
 )
 ; // Parameters

ENDME // ME_47BEEC10022E IterateAll

ME ME_47BEF07E0044
 MEPROP Name 'anIndex'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_47BEF07E0044 anIndex

ME ME_47BEF07E00C2
 MEPROP Name 'aData'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;

ENDME // ME_47BEF07E00C2 aData

ME ME_47BEF05C0032
 MEPROP UID '47BEF05C0032'
 MEPROP Name 'DoInsert'
 MEPROP Class class_Operation
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELIST CanRaise
   Seq: ( WL 'ME_479F1C5600EA' '478CF30500C1.ms.model.script' // EListError
 )
 ; // CanRaise
 MELIST Parameters
   Seq: ( ME_47BEF07E0044 // anIndex
 ME_47BEF07E00C2 // aData
 )
 ; // Parameters

ENDME // ME_47BEF05C0032 DoInsert

ME ME_47BEF39B01E3
 MEPROP Name 'aData'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;

ENDME // ME_47BEF39B01E3 aData

ME ME_47BEF3910285
 MEPROP UID '47BEF3910285'
 MEPROP Name 'DoAdd'
 MEPROP Class class_Operation
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;
 MELIST CanRaise
   Seq: ( WL 'ME_4787B1BA031F' '4787B0A8007B.ms.model.script' // El3DuplicateItem
 )
 ; // CanRaise
 MELIST Parameters
   Seq: ( ME_47BEF39B01E3 // aData
 )
 ; // Parameters

ENDME // ME_47BEF3910285 DoAdd

ME ME_47BEF5170309
 MEPROP Name 'aData'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;

ENDME // ME_47BEF5170309 aData

ME ME_47BEF5130164
 MEPROP UID '47BEF5130164'
 MEPROP Name 'Add'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;
 MELIST Parameters
   Seq: ( ME_47BEF5170309 // aData
 )
 ; // Parameters

ENDME // ME_47BEF5130164 Add

ME ME_47BF0A5C03E1
 MEPROP Name 'aData'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;

ENDME // ME_47BF0A5C03E1 aData

ME ME_47BF0B5E033A
 MEPROP Name 'theIndex'
 MEPROP Class class_Parameter
 MELINK Stereotype st_out ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_47BF0B5E033A theIndex

ME ME_47BF0A3100F6
 MEPROP UID '47BF0A3100F6'
 MEPROP Name 'Find'
 MEPROP Class class_Operation
 %SUMMARY 'Находит данные, при помощи основной операции сравнения.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 MELIST Parameters
   Seq: ( ME_47BF0A5C03E1 // aData
 ME_47BF0B5E033A // theIndex
 )
 ; // Parameters

ENDME // ME_47BF0A3100F6 Find

ME ME_47BF0C870007
 MEPROP Name 'anIndex'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_47BF0C870007 anIndex

ME ME_47BF0C87009A
 MEPROP Name 'aData'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;

ENDME // ME_47BF0C87009A aData

ME ME_47BF0C7C01D6
 MEPROP UID '47BF0C7C01D6'
 MEPROP Name 'Insert'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELIST Parameters
   Seq: ( ME_47BF0C870007 // anIndex
 ME_47BF0C87009A // aData
 )
 ; // Parameters

ENDME // ME_47BF0C7C01D6 Insert

ME ME_47B5C41F0148
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELINK Target WL? 'ME_4773D64E036C' // l3Base
 ;

ENDME // ME_47B5C41F0148 

ME ME_4DD4EC3A038B
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELINK Target WL 'ME_479F1E0803A0' '479F1DEA0057.ms.model.script' // Errors
 ;

ENDME // ME_4DD4EC3A038B 

ME ME_4DD4EC640377
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELINK Target WL? 'ME_47877EB202FB' // SysUtils
 ;

ENDME // ME_4DD4EC640377 

ME ME_4DD4EC8B01C7
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47B433E500BC // l3UntypedList
 ;
 MELINK Target WL? 'ME_47A066980016' // l3MinMax
 ;

ENDME // ME_4DD4EC8B01C7 

MEREF ME_47B48A510176_ME_47B433E500BC_impl
 MELINK Original WL 'ME_47B48A510176' '47B45152003F.ms.model.script' // MoveItems
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_47B48A510176_ME_47B433E500BC_impl MoveItems

MEREF ME_47B5976F024E_ME_47B433E500BC_impl
 MELINK Original WL 'ME_47B5976F024E' '47B45152003F.ms.model.script' // ReAllocList
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_47B5976F024E_ME_47B433E500BC_impl ReAllocList

MEREF ME_47B5984B019D_ME_47B433E500BC_impl
 MELINK Original WL 'ME_47B5984B019D' '47B45152003F.ms.model.script' // GetCapacity
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_47B5984B019D_ME_47B433E500BC_impl GetCapacity

MEREF ME_47B5C4080270_ME_47B433E500BC_impl
 MELINK Original WL 'ME_47B5C4080270' '47B45152003F.ms.model.script' // DoExchange
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_47B5C4080270_ME_47B433E500BC_impl DoExchange

MEREF ME_47B935AF0066_ME_47B433E500BC_impl
 MELINK Original WL 'ME_47B935AF0066' '47B45152003F.ms.model.script' // FillItem
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_47B935AF0066_ME_47B433E500BC_impl FillItem

MEREF ME_47B94A5C006E_ME_47B433E500BC_impl
 MELINK Original WL 'ME_47B94A5C006E' '47B45152003F.ms.model.script' // FreeItem
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_47B94A5C006E_ME_47B433E500BC_impl FreeItem

MEREF ME_47B99D4503A2_ME_47B433E500BC_impl
 MELINK Original WL 'ME_47B99D4503A2' '47B45152003F.ms.model.script' // CompareExistingItems
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_47B99D4503A2_ME_47B433E500BC_impl CompareExistingItems

MEREF ME_47BEDF2A02EA_ME_47B433E500BC_impl
 MELINK Original WL 'ME_47BEDF2A02EA' '47B45152003F.ms.model.script' // GetItemSlot
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_47BEDF2A02EA_ME_47B433E500BC_impl GetItemSlot

MEREF ME_47BEE088001A_ME_47B433E500BC_impl
 MELINK Original WL 'ME_47BEE088001A' '47B45152003F.ms.model.script' // Count
 ;
 MEPROP OpKind opkind_Implemented
 UP "needs field" false
 UP "pm" true
 UP "reads field" true
ENDMEREF // ME_47BEE088001A_ME_47B433E500BC_impl Count

MEREF ME_47B45152003F_ME_47B433E500BC_G
 MELINK Original WL? 'ME_47B45152003F' // l3Items
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_47B45152003F_ME_47B433E500BC_G l3Items

%%InheritedBy ME_47B45152003F ME_47B433E500BC

ME ME_47B433E500BC
 MEPROP UID '47B433E500BC'
 MEPROP Name 'l3UntypedList'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_Impurity ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent WL? 'ME_4B880BC203B6' // RecLists
 ;
 MELIST Inherits
   Seq: ( ME_47B45152003F_ME_47B433E500BC_G // l3Items
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_47BEE7FD01DC // ItemSize
 HWL ME_47B99BAF004B // ItemType
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_47BC108C03C9 // Clear
 HWL ME_47BC677E02B1 // DoCompare
 HWL ME_47BEEBE602B1 // Iterate
 HWL ME_47BEEC10022E // IterateAll
 HWL ME_47BEF05C0032 // DoInsert
 HWL ME_47BEF3910285 // DoAdd
 HWL ME_47BEF5130164 // Add
 HWL ME_47BF0A3100F6 // Find
 HWL ME_47BF0C7C01D6 // Insert
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_47B48A510176_ME_47B433E500BC_impl // MoveItems
 ME_47B5976F024E_ME_47B433E500BC_impl // ReAllocList
 ME_47B5984B019D_ME_47B433E500BC_impl // GetCapacity
 ME_47B5C4080270_ME_47B433E500BC_impl // DoExchange
 ME_47B935AF0066_ME_47B433E500BC_impl // FillItem
 ME_47B94A5C006E_ME_47B433E500BC_impl // FreeItem
 ME_47B99D4503A2_ME_47B433E500BC_impl // CompareExistingItems
 ME_47BEDF2A02EA_ME_47B433E500BC_impl // GetItemSlot
 ME_47BEE088001A_ME_47B433E500BC_impl // Count
 )
 ; // Implemented
 MELIST Children
   Seq: ( HWL ME_47B99B600208 // VOID
 HWL ME_4B87AD4701FD // l3Items_FillItem_NeedsList
 HWL ME_4D5BFD5202BE // l3Items_CompareItemsRec_NeedsRList
 )
 ; // Children
 MELIST Dependencies
   Seq: ( ME_47B5C41F0148 // l3Base
 ME_4DD4EC3A038B // Errors
 ME_4DD4EC640377 // SysUtils
 ME_4DD4EC8B01C7 // l3MinMax
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP intf.pas:Path 'common\components\rtl\Garant\L3\l3UntypedList.imp.pas'
 UP extprop:pas:TypeName '_l3UntypedList_'
 UP extprop:pas:UnitName 'l3UntypedList.imp'

ENDME // ME_47B433E500BC l3UntypedList
