// Tl3ObjectRefList 47BAA8EB00CD SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4773DAAA02AA_ME_47BAA8EB00CD_G
 MELINK Original WL? 'ME_4773DAAA02AA' // Tl3ObjectRefList1
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4773DAAA02AA_ME_47BAA8EB00CD_G Tl3ObjectRefList1

%%InheritedBy ME_4773DAAA02AA ME_47BAA8EB00CD

ME ME_47BAA8EB00CD
 MEPROP UID '47BAA8EB00CD'
 MEPROP Name 'Tl3ObjectRefList'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_47913B47006E' // l3CoreObjects
 ;
 MELIST Inherits
   Seq: ( ME_4773DAAA02AA_ME_47BAA8EB00CD_G // Tl3ObjectRefList1
 )
 ; // Inherits
 UP "author" 'Ëþëèí À.Â.'
 UP "no hands" true
 UP "started" '19.02.2008 14:37'
 UP intf.pas:Path 'common\components\rtl\Garant\L3\l3ObjectRefList.pas'
 UP extprop:rc:SelfName 'ObjectRefList'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'l3ObjectRefList'

ENDME // ME_47BAA8EB00CD Tl3ObjectRefList
