// m2MemLib 47BF045E0138 UtilityPack Class

FORWARD ME_47BF045E0138

INCLUDE '4807744200AA.pas.ms.script'

: ME_47BF053D022C
 CONST UID '47BF053D022C'
 CONST Name 'ADest'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_46A608F00301 // Pointer
 ;

 @SELF
; // ME_47BF053D022C ADest

: ME_47BF053D0244
 CONST UID '47BF053D0244'
 CONST Name 'ASour'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_46A608F00301 // Pointer
 ;

 @SELF
; // ME_47BF053D0244 ASour

: ME_47BF053D025D
 CONST UID '47BF053D025D'
 CONST Name 'ASize'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_46A606AC03B2 // Integer
 ;

 @SELF
; // ME_47BF053D025D ASize

: ME_47BF05230001
 CONST UID '47BF05230001'
 CONST Name 'm2MEMCompare'
 CONST Class 'Operation'
 CONST Stereotype ''
 %SUMMARY 'сравнивает два куска памяти.' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Target ME_46A606AC03B2 // Integer
 ;
 : Parameters
   [ ME_47BF053D022C // ADest
 ME_47BF053D0244 // ASour
 ME_47BF053D025D // ASize
 ]
 ; // Parameters

 @SELF
; // ME_47BF05230001 m2MEMCompare

: ME_47BF045E0138
 CONST UID '47BF045E0138'
 CONST Name 'm2MemLib'
 CONST Class 'Class'
 CONST Stereotype 'UtilityPack'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_47BF05230001 // m2MEMCompare
 ]
 ; // Operations
 CONST "finished" false
 CONST "no hands" false

 @SELF
; // ME_47BF045E0138 m2MemLib
