// Tl3VCLStringsItems 47E21D500381 SimpleClass Class

INCLUDE '47913F970159.pas.ms.script'

INCLUDE '47E21D07033A.pas.ms.script'

INCLUDE '478CF30500C1.pas.ms.script'

INCLUDE '47913F4E02E0.pas.ms.script'

: ME_47E21D500381
 CONST UID '47E21D500381'
 CONST Name 'Tl3VCLStringsItems'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_47913F970159 // l3Unknown
 ME_47E21D07033A // Tl3CastableStrings
 ]
 ; // Inherits
 : Implemented
   [ ME_47E21AB50104 // Clear
 ME_47E21AD40366 // Insert
 ME_47E21AF20186 // Get
 ME_47E21B0A0167 // Put
 ME_47E21B2403D5 // GetCount
 ]
 ; // Implemented
 : Overridden
   [ ME_47A6FEE600FC // IsCacheable
 ME_47E21BAA029A // GetObject
 ME_47E21BC40258 // PutObject
 ]
 ; // Overridden
 CONST "author" 'Ëþëèí À.Â.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '29.12.2006 14:25'

 @SELF
; // ME_47E21D500381 Tl3VCLStringsItems
