// l3NotifierBase 47F07AE10156 Impurity Class

INCLUDE '4677FBA70343.pas.ms.script'

INCLUDE '4A5CB93700CF.pas.ms.script'

INCLUDE '51612ED700B4.pas.ms.script'

FORWARD ME_47F07AE10156

INCLUDE '4807744200AA.pas.ms.script'

: ME_47F07CCE0379
 CONST UID '47F07CCE0379'
 CONST Name 'HasNotified'
 CONST Class 'Attribute'
 CONST Stereotype 'readonly'
 %SUMMARY 'наличие уведомляемых объектов.' ;
 CONST Visibility 'ProtectedAccess'
 CONST Abstraction 'final'
 CONST LinkType 'agr'
 : Target ME_46A603BB0391 // Boolean
 ;
 CONST "needs field" false
 CONST "pm" true

 @SELF
; // ME_47F07CCE0379 HasNotified

INCLUDE '47F07C1B03E4.pas.ms.script'

: ME_47F07C5D007E
 CONST UID '47F07C5D007E'
 CONST Name 'NotifiedObjList'
 CONST Class 'Attribute'
 CONST Stereotype 'readonly'
 CONST Visibility 'ProtectedAccess'
 CONST Abstraction 'final'
 CONST LinkType 'agr'
 : Target ME_47F07C1B03E4 // Tl3NotifyPtrList
 ;
 CONST "needs field" true
 CONST "pm" true
 CONST "reads field" true

 @SELF
; // ME_47F07C5D007E NotifiedObjList

: ME_3EB94D4BAD07
 CONST UID '3EB94D4BAD07'
 CONST Name 'f_NotifiedObjList'
 CONST Class 'Attribute'
 CONST Stereotype ''
 %SUMMARY 'Поле для свойства NotifiedObjList' ;
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'ref'
 : Target ME_47F07C1B03E4 // Tl3NotifyPtrList
 ;

 @SELF
; // ME_3EB94D4BAD07 f_NotifiedObjList

: ME_47F07AE10156
 CONST UID '47F07AE10156'
 CONST Name 'l3NotifierBase'
 CONST Class 'Class'
 CONST Stereotype 'Impurity'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Implements
   [ ME_46782E7F0307 // Il3ChangeNotifier
 ME_4A5CB93700CF // Ml3Unknown
 ]
 ; // Implements
 : Attributes
   [ ME_47F07CCE0379 // HasNotified
 ME_47F07C5D007E // NotifiedObjList
 ME_3EB94D4BAD07 // f_NotifiedObjList
 ]
 ; // Attributes
 : Implemented
   [ ME_46A44F6B035E // Subscribe
 ME_46A44FFE0143 // Unsubscribe
 ]
 ; // Implemented
 : Overridden
   [ ME_479731C50290 // Cleanup
 ]
 ; // Overridden
 CONST "author" 'Люлин А.В.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '31.03.2008 09:48'

 @SELF
; // ME_47F07AE10156 l3NotifierBase
