// sdsDrugDocument 47F075910035 ControllerUnit Category

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_47F075910035
 MEPROP UID '47F075910035'
 MEPROP Name 'sdsDrugDocument'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_ControllerUnit ;
 %SUMMARY 'БОС описания препарата.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_49410AA9008B' '49410AA9008B.ms.model.script' // Drug
 ;
 MELIST Children
   Seq: ( WL 'ME_47F075CD00DC' '47F075CD00DC.ms.model.script' // sdsBaseDrugDocument
 WL 'ME_47F4A2F801D8' '47F4A2F801D8.ms.model.script' // TsdsDrugDocument
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_45700BFD0251' '45700BFD0251.ms.model.script' // DynamicDocList
 WL 'ME_457450470167' '457450470167.ms.model.script' // DynamicTree
 WL 'ME_4678193C009C' '4678193C009C.ms.model.script' // l3Types
 WL 'ME_47750CE700D0' '47750CE700D0.ms.model.script' // afwFacade
 WL 'ME_47D0290B016D' '47D0290B016D.ms.model.script' // l3Utils
 WL 'ME_47EA4BB502F9' '47EA4BB502F9.ms.model.script' // afwMixIns
 WL 'ME_47EA50050263' '47EA50050263.ms.model.script' // BaseDocument
 WL 'ME_47EA5024034B' '47EA5024034B.ms.model.script' // ListDataSources
 WL 'ME_47F260DC003F' '47F260DC003F.ms.model.script' // ns
 WL 'ME_48F747EC0073' '48F747EC0073.ms.model.script' // Common
 WL 'ME_491B305A0096' '491B305A0096.ms.model.script' // DocumentAndListInterfaces
 WL 'ME_491D7C9603B2' '491D7C9603B2.ms.model.script' // MedicInterfaces
 WL 'ME_491D7CDC0221' '491D7CDC0221.ms.model.script' // Medic
 WL 'ME_491DCA2C00A9' '491DCA2C00A9.ms.model.script' // Search
 WL 'ME_4A9FCCDB035B' '4A9FCCDB035B.ms.model.script' // DrugData
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.ms.model.script' // Sys
 WL 'ME_4B1FC2FF03CD' '4B1FC2FF03CD.ms.model.script' // DocumentInterfaces
 )
 ; // Depends

ENDME // ME_47F075910035 sdsDrugDocument
