// nsTypes 47F2170002B2 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_47F2170002B2

FORWARD ME_4D4161F5012E

FORWARD ME_4D41621B01DE

: ME_4D416242028A
 CONST UID '4D416242028A'
 CONST Name 'rIl3CString'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4D41621B01DE // TnsStringPair
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_4D416242028A rIl3CString

: ME_4D4162630190
 CONST UID '4D4162630190'
 CONST Name 'rIString'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_4D41621B01DE // TnsStringPair
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_4D4162630190 rIString

: ME_4D41621B01DE
 CONST UID '4D41621B01DE'
 CONST Name 'TnsStringPair'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4D4161F5012E // nsTypesNew
 ;
 : Attributes
   Seq: ( ME_4D416242028A // rIl3CString
 ME_4D4162630190 // rIString
 )
 ; // Attributes

ref; // ME_4D41621B01DE TnsStringPair

FORWARD ME_573359B1010D

: ME_573359C502E9
 CONST UID '573359C502E9'
 CONST Name 'LLO_AND'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_573359B1010D // TListLogicOperation
 ;

ref; // ME_573359C502E9 LLO_AND

: ME_573359D30114
 CONST UID '573359D30114'
 CONST Name 'LLO_OR'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_573359B1010D // TListLogicOperation
 ;

ref; // ME_573359D30114 LLO_OR

: ME_573359DA0251
 CONST UID '573359DA0251'
 CONST Name 'LLO_AND_NOT'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_573359B1010D // TListLogicOperation
 ;

ref; // ME_573359DA0251 LLO_AND_NOT

: ME_573359F900FF
 CONST UID '573359F900FF'
 CONST Name 'LLO_NONE'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_573359B1010D // TListLogicOperation
 ;

ref; // ME_573359F900FF LLO_NONE

: ME_573359B1010D
 CONST UID '573359B1010D'
 CONST Name 'TListLogicOperation'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4D4161F5012E // nsTypesNew
 ;
 : Attributes
   Seq: ( ME_573359C502E9 // LLO_AND
 ME_573359D30114 // LLO_OR
 ME_573359DA0251 // LLO_AND_NOT
 ME_573359F900FF // LLO_NONE
 )
 ; // Attributes
 CONST "register in scripts" true
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_573359B1010D TListLogicOperation

FORWARD ME_47F21723038D

: ME_4A2000B20292
 CONST UID '4A2000B20292'
 CONST Name 'ns_ffRTF'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47F21723038D // TnsFileFormat
 ;

ref; // ME_4A2000B20292 ns_ffRTF

: ME_4A2000BB03AB
 CONST UID '4A2000BB03AB'
 CONST Name 'ns_ffTxt'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47F21723038D // TnsFileFormat
 ;

ref; // ME_4A2000BB03AB ns_ffTxt

: ME_4A2000C202EC
 CONST UID '4A2000C202EC'
 CONST Name 'ns_ffHTML'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47F21723038D // TnsFileFormat
 ;

ref; // ME_4A2000C202EC ns_ffHTML

: ME_4A2000CB03DC
 CONST UID '4A2000CB03DC'
 CONST Name 'ns_ffXML'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47F21723038D // TnsFileFormat
 ;

ref; // ME_4A2000CB03DC ns_ffXML

: ME_4A2000D20208
 CONST UID '4A2000D20208'
 CONST Name 'ns_ffEvd'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47F21723038D // TnsFileFormat
 ;

ref; // ME_4A2000D20208 ns_ffEvd

: ME_4A2000D8036E
 CONST UID '4A2000D8036E'
 CONST Name 'ns_ffNull'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47F21723038D // TnsFileFormat
 ;

ref; // ME_4A2000D8036E ns_ffNull

: ME_57335B4B01D5
 CONST UID '57335B4B01D5'
 CONST Name 'ns_ffPDF'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47F21723038D // TnsFileFormat
 ;

ref; // ME_57335B4B01D5 ns_ffPDF

: ME_47F21723038D
 CONST UID '47F21723038D'
 CONST Name 'TnsFileFormat'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 %SUMMARY '- форматы файла.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4D4161F5012E // nsTypesNew
 ;
 : Attributes
   Seq: ( ME_4A2000B20292 // ns_ffRTF
 ME_4A2000BB03AB // ns_ffTxt
 ME_4A2000C202EC // ns_ffHTML
 ME_4A2000CB03DC // ns_ffXML
 ME_4A2000D20208 // ns_ffEvd
 ME_4A2000D8036E // ns_ffNull
 ME_57335B4B01D5 // ns_ffPDF
 )
 ; // Attributes
 CONST "register in scripts" true
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_47F21723038D TnsFileFormat

: ME_4D4161F5012E
 CONST UID '4D4161F5012E'
 CONST Name 'nsTypesNew'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_47F2170002B2 // nsTypes
 ;
 : Children
   Seq: ( ME_4D41621B01DE // TnsStringPair
 ME_573359B1010D // TListLogicOperation
 ME_47F21723038D // TnsFileFormat
 )
 ; // Children
 CONST "author" 'Люлин А.В.'
 CONST "no hands" true
 CONST "started" '27.11.2011 15:16'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Model\nsTypesNew.pas'
 CONST extprop:rc:SelfName 'TypesNew'

ref; // ME_4D4161F5012E nsTypesNew

FORWARD ME_4BA763B0004B

FORWARD ME_491B32C1015D

: ME_4BA764960061
 CONST UID '4BA764960061'
 CONST Name 'None'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_491B32C1015D // TDocumentPositionType
 ;

ref; // ME_4BA764960061 None

: ME_4BA764A10126
 CONST UID '4BA764A10126'
 CONST Name 'Sub'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_491B32C1015D // TDocumentPositionType
 ;

ref; // ME_4BA764A10126 Sub

: ME_4BA764AA008A
 CONST UID '4BA764AA008A'
 CONST Name 'Marker'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_491B32C1015D // TDocumentPositionType
 ;

ref; // ME_4BA764AA008A Marker

: ME_4BA764B303D6
 CONST UID '4BA764B303D6'
 CONST Name 'Bookmark'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_491B32C1015D // TDocumentPositionType
 ;

ref; // ME_4BA764B303D6 Bookmark

: ME_4BA764BC0286
 CONST UID '4BA764BC0286'
 CONST Name 'Para'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_491B32C1015D // TDocumentPositionType
 ;

ref; // ME_4BA764BC0286 Para

: ME_4BA764C601B8
 CONST UID '4BA764C601B8'
 CONST Name 'Mark'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_491B32C1015D // TDocumentPositionType
 ;

ref; // ME_4BA764C601B8 Mark

: ME_4BA764CF0319
 CONST UID '4BA764CF0319'
 CONST Name 'DocumentPlace'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_491B32C1015D // TDocumentPositionType
 ;

ref; // ME_4BA764CF0319 DocumentPlace

: ME_491B32C1015D
 CONST UID '491B32C1015D'
 CONST Name 'TDocumentPositionType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Типы позиционирования в документе' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4BA763B0004B // bsTypesNew
 ;
 : Attributes
   Seq: ( ME_4BA764960061 // None
 ME_4BA764A10126 // Sub
 ME_4BA764AA008A // Marker
 ME_4BA764B303D6 // Bookmark
 ME_4BA764BC0286 // Para
 ME_4BA764C601B8 // Mark
 ME_4BA764CF0319 // DocumentPlace
 )
 ; // Attributes
 CONST "children prefix" 'dpt'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:ElementPrefix 'dpt'

ref; // ME_491B32C1015D TDocumentPositionType

FORWARD ME_491B329F0330

: ME_4BA7644401DA
 CONST UID '4BA7644401DA'
 CONST Name 'rRefType'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent ME_491B329F0330 // TbsDocPos
 ;
 : Target ME_491B32C1015D // TDocumentPositionType
 ;

ref; // ME_4BA7644401DA rRefType

: ME_4BA7646F0091
 CONST UID '4BA7646F0091'
 CONST Name 'rPos'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent ME_491B329F0330 // TbsDocPos
 ;
 : Target WL 'ME_48FD996601CE' '4AB0C3C60310.pas.ms.script' // Longword
 ;

ref; // ME_4BA7646F0091 rPos

: ME_4C066CEF00C3
 CONST UID '4C066CEF00C3'
 CONST Name 'rPara'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent ME_491B329F0330 // TbsDocPos
 ;
 : Target WL 'ME_495239F201D9' '4912DD020283.pas.ms.script' // IeePara
 ;

ref; // ME_4C066CEF00C3 rPara

FORWARD ME_4BA782140193

: ME_4BA7821E0096
 CONST Name 'aType'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_491B32C1015D // TDocumentPositionType
 ;

ref; // ME_4BA7821E0096 aType

: ME_4BA7821E00B2
 CONST Name 'aPos'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_48FD996601CE' '4AB0C3C60310.pas.ms.script' // Longword
 ;

ref; // ME_4BA7821E00B2 aPos

: ME_4BA7821C001E
 CONST UID '4BA7821C001E'
 CONST Name 'C'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4BA782140193 // C
 ;
 : Parameters
   Seq: ( ME_4BA7821E0096 // aType
 ME_4BA7821E00B2 // aPos
 )
 ; // Parameters

ref; // ME_4BA7821C001E C

: ME_4C066F4401BE
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4BA782140193 // C
 ;
 : Target WL 'ME_45EEB652030F' '4570511E038A.pas.ms.script' // PositionInDocument
 ;

ref; // ME_4C066F4401BE 

: ME_4C066F4600F8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4BA782140193 // C
 ;
 : Target WL 'ME_47F2612701D0' '47D0290B016D.pas.ms.script' // l3Bits
 ;

ref; // ME_4C066F4600F8 

: ME_4BA782140193
 CONST UID '4BA782140193'
 CONST Name 'C'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_491B329F0330 // TbsDocPos
 ;
 : Operations
   Seq: ( ME_4BA7821C001E // C
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4C066F4401BE // PositionInDocument
 ME_4C066F4600F8 // l3Bits
 )
 ; // Dependencies

ref; // ME_4BA782140193 C

FORWARD ME_4BA7822703B2

: ME_4BA7823000B4
 CONST UID '4BA7823000B4'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4BA7822703B2 // E
 ;

ref; // ME_4BA7823000B4 DoIt

: ME_4BA7822703B2
 CONST UID '4BA7822703B2'
 CONST Name 'E'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Пустая позиция' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_491B329F0330 // TbsDocPos
 ;
 : Operations
   Seq: ( ME_4BA7823000B4 // DoIt
 )
 ; // Operations

ref; // ME_4BA7822703B2 E

FORWARD ME_4BA7823901C7

: ME_4BA782450061
 CONST Name 'aPos'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_48FD996601CE' '4AB0C3C60310.pas.ms.script' // Longword
 ;

ref; // ME_4BA782450061 aPos

: ME_4BA782400080
 CONST UID '4BA782400080'
 CONST Name 'C'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4BA7823901C7 // S
 ;
 : Parameters
   Seq: ( ME_4BA782450061 // aPos
 )
 ; // Parameters

ref; // ME_4BA782400080 C

: ME_4BA7823901C7
 CONST UID '4BA7823901C7'
 CONST Name 'S'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Позиция указывающая на Sub' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_491B329F0330 // TbsDocPos
 ;
 : Operations
   Seq: ( ME_4BA782400080 // C
 )
 ; // Operations

ref; // ME_4BA7823901C7 S

FORWARD ME_4BA789E200FF

: ME_4BA789EC00F9
 CONST Name 'aPos'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_495239F201D9' '4912DD020283.pas.ms.script' // IeePara
 ;

ref; // ME_4BA789EC00F9 aPos

: ME_4BA789E803D4
 CONST UID '4BA789E803D4'
 CONST Name 'C'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4BA789E200FF // P
 ;
 : Parameters
   Seq: ( ME_4BA789EC00F9 // aPos
 )
 ; // Parameters

ref; // ME_4BA789E803D4 C

: ME_4BA789E200FF
 CONST UID '4BA789E200FF'
 CONST Name 'P'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_491B329F0330 // TbsDocPos
 ;
 : Operations
   Seq: ( ME_4BA789E803D4 // C
 )
 ; // Operations

ref; // ME_4BA789E200FF P

FORWARD ME_4C064CB90097

: ME_4C064CD20060
 CONST Name 'aPos'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_48FD996601CE' '4AB0C3C60310.pas.ms.script' // Longword
 ;

ref; // ME_4C064CD20060 aPos

: ME_4C064CC4031E
 CONST UID '4C064CC4031E'
 CONST Name 'C'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4C064CB90097 // PID
 ;
 : Parameters
   Seq: ( ME_4C064CD20060 // aPos
 )
 ; // Parameters

ref; // ME_4C064CC4031E C

: ME_4C064CB90097
 CONST UID '4C064CB90097'
 CONST Name 'PID'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_491B329F0330 // TbsDocPos
 ;
 : Operations
   Seq: ( ME_4C064CC4031E // C
 )
 ; // Operations

ref; // ME_4C064CB90097 PID

FORWARD ME_50103641035D

: ME_5010365302F9
 CONST Name 'anOther'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_491B329F0330 // TbsDocPos
 ;

ref; // ME_5010365302F9 anOther

: ME_5010364A00A2
 CONST UID '5010364A00A2'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_50103641035D // EQ
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_5010365302F9 // anOther
 )
 ; // Parameters

ref; // ME_5010364A00A2 DoIt

: ME_50103641035D
 CONST UID '50103641035D'
 CONST Name 'EQ'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_491B329F0330 // TbsDocPos
 ;
 : Operations
   Seq: ( ME_5010364A00A2 // DoIt
 )
 ; // Operations

ref; // ME_50103641035D EQ

: ME_4C066EFA0117
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_491B329F0330 // TbsDocPos
 ;
 : Target WL 'ME_45EEB652030F' '4570511E038A.pas.ms.script' // PositionInDocument
 ;

ref; // ME_4C066EFA0117 

: ME_4C066F3901CE
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_491B329F0330 // TbsDocPos
 ;
 : Target WL 'ME_47F2612701D0' '47D0290B016D.pas.ms.script' // l3Bits
 ;

ref; // ME_4C066F3901CE 

: ME_491B329F0330
 CONST UID '491B329F0330'
 CONST Name 'TbsDocPos'
 CONST Class class_Class
 : Stereotype st_StaticObject ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4BA763B0004B // bsTypesNew
 ;
 : Attributes
   Seq: ( ME_4BA7644401DA // rRefType
 ME_4BA7646F0091 // rPos
 ME_4C066CEF00C3 // rPara
 )
 ; // Attributes
 : Operations
   Seq: ( ME_4BA782140193 // C
 ME_4BA7822703B2 // E
 ME_4BA7823901C7 // S
 ME_4BA789E200FF // P
 ME_4C064CB90097 // PID
 ME_50103641035D // EQ
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4C066EFA0117 // PositionInDocument
 ME_4C066F3901CE // l3Bits
 )
 ; // Dependencies
 CONST extprop:rc:SelfName 'bsDocPos'

ref; // ME_491B329F0330 TbsDocPos

: ME_4BA763B0004B
 CONST UID '4BA763B0004B'
 CONST Name 'bsTypesNew'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Типы бизнес уровня. Кусок от bsTypes. На самом деле БОЛЬШАЯ ПОМОЙКА. Новые типы добавлять сюда нельзя' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_47F2170002B2 // nsTypes
 ;
 : Children
   Seq: ( ME_491B32C1015D // TDocumentPositionType
 ME_491B329F0330 // TbsDocPos
 )
 ; // Children
 CONST "author" 'Люлин А.В.'
 CONST "no hands" true
 CONST "started" '22.03.2010 15:34'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Model\bsTypesNew.pas'

ref; // ME_4BA763B0004B bsTypesNew

FORWARD ME_4A6854C70390

FORWARD ME_47F244C1009A

: ME_47F2488F02D0
 CONST UID '47F2488F02D0'
 CONST Name 'nne_ResetChildrenCount'
 CONST Class class_Attribute
 %SUMMARY '- событие сброса детей.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47F244C1009A // TreeConstants
 ;
 CONST Value 1000
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 1000

ref; // ME_47F2488F02D0 nne_ResetChildrenCount

: ME_47F244C1009A
 CONST UID '47F244C1009A'
 CONST Name 'TreeConstants'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Константы для работы с деревом' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 : Attributes
   Seq: ( ME_47F2488F02D0 // nne_ResetChildrenCount
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_47F244C1009A TreeConstants

: ME_47F2791D019A
 CONST UID '47F2791D019A'
 CONST Name 'TListLogicOperation'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Логические операции со списком.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 : Inherits
   Seq: ( ME_573359B1010D // TListLogicOperation
 )
 ; // Inherits
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_47F2791D019A TListLogicOperation

: ME_48FF569700F6
 CONST UID '48FF569700F6'
 CONST Name 'StringRoutines'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST "spell names" false

ref; // ME_48FF569700F6 StringRoutines

FORWARD ME_48FF63BC0129

: ME_48FF63C500E2
 CONST UID '48FF63C500E2'
 CONST Name 'rtsNone'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_48FF63BC0129 // TnsResetTreeStatus
 ;

ref; // ME_48FF63C500E2 rtsNone

: ME_48FF63CD00F0
 CONST UID '48FF63CD00F0'
 CONST Name 'rtsRoot'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_48FF63BC0129 // TnsResetTreeStatus
 ;

ref; // ME_48FF63CD00F0 rtsRoot

: ME_48FF63D501AF
 CONST UID '48FF63D501AF'
 CONST Name 'rtsFullRoot'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_48FF63BC0129 // TnsResetTreeStatus
 ;

ref; // ME_48FF63D501AF rtsFullRoot

: ME_48FF63DF00B1
 CONST UID '48FF63DF00B1'
 CONST Name 'rtsOneLevel'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_48FF63BC0129 // TnsResetTreeStatus
 ;

ref; // ME_48FF63DF00B1 rtsOneLevel

: ME_48FF63BC0129
 CONST UID '48FF63BC0129'
 CONST Name 'TnsResetTreeStatus'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 : Attributes
   Seq: ( ME_48FF63C500E2 // rtsNone
 ME_48FF63CD00F0 // rtsRoot
 ME_48FF63D501AF // rtsFullRoot
 ME_48FF63DF00B1 // rtsOneLevel
 )
 ; // Attributes
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_48FF63BC0129 TnsResetTreeStatus

FORWARD ME_490200F300DD

: ME_490201000142
 CONST UID '490201000142'
 CONST Name 'ns_ftNone'
 CONST Class class_Attribute
 %SUMMARY 'никаких дополнительных фильтров' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_490200F300DD // TnsFilterType
 ;

ref; // ME_490201000142 ns_ftNone

: ME_4902010A0055
 CONST UID '4902010A0055'
 CONST Name 'ns_ftTrim'
 CONST Class class_Attribute
 %SUMMARY 'При создании дерева атрибутов нужно накладывать дополнительный фильтр ITrimFilter' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_490200F300DD // TnsFilterType
 ;

ref; // ME_4902010A0055 ns_ftTrim

: ME_490201130195
 CONST UID '490201130195'
 CONST Name 'ns_ftTrimLeaf'
 CONST Class class_Attribute
 %SUMMARY 'При создании дерева атрибутов нужно накладывать дополнительный фильтр ITrimLeafFilter' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_490200F300DD // TnsFilterType
 ;

ref; // ME_490201130195 ns_ftTrimLeaf

: ME_4902011E0151
 CONST UID '4902011E0151'
 CONST Name 'ns_ftBlocks'
 CONST Class class_Attribute
 %SUMMARY 'При создании дерева атрибутов нужно накладывать дополнительный фильтр IBlocksFilter' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_490200F300DD // TnsFilterType
 ;

ref; // ME_4902011E0151 ns_ftBlocks

: ME_4A8BE3F00024
 CONST UID '4A8BE3F00024'
 CONST Name 'ns_ftInpharm'
 CONST Class class_Attribute
 %SUMMARY 'Для фильтрации узла инфарама' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_490200F300DD // TnsFilterType
 ;

ref; // ME_4A8BE3F00024 ns_ftInpharm

: ME_490200F300DD
 CONST UID '490200F300DD'
 CONST Name 'TnsFilterType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 %SUMMARY 'дополнительный тип фильтрации для деревьев атрибутов' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 : Attributes
   Seq: ( ME_490201000142 // ns_ftNone
 ME_4902010A0055 // ns_ftTrim
 ME_490201130195 // ns_ftTrimLeaf
 ME_4902011E0151 // ns_ftBlocks
 ME_4A8BE3F00024 // ns_ftInpharm
 )
 ; // Attributes
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_490200F300DD TnsFilterType

: ME_490B011B02DB
 CONST UID '490B011B02DB'
 CONST Name 'TnsNavigatorItemParams'
 CONST Class class_Class
 : Stereotype st_Struct ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;

ref; // ME_490B011B02DB TnsNavigatorItemParams

: ME_490C3BB20118
 CONST UID '490C3BB20118'
 CONST Name 'TnsMedicMainMenuNodeType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_490C3BB20118 TnsMedicMainMenuNodeType

: ME_491C0E4503A2
 CONST UID '491C0E4503A2'
 CONST Name 'DateTimeRoutines'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST "spell names" false

ref; // ME_491C0E4503A2 DateTimeRoutines

: ME_4921865D0256
 CONST UID '4921865D0256'
 CONST Name 'TWarningType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4921865D0256 TWarningType

: ME_4921866C01A1
 CONST UID '4921866C01A1'
 CONST Name 'TWarningTypeSet'
 CONST Class class_Class
 : Stereotype st_SetOf ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 : Inherits
   Seq: ( ME_4921865D0256 // TWarningType
 )
 ; // Inherits

ref; // ME_4921866C01A1 TWarningTypeSet

FORWARD ME_49522F6C0324

: ME_49522F770385
 CONST UID '49522F770385'
 CONST Name 'ekDisk'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_49522F6C0324 // TnsExportKind
 ;

ref; // ME_49522F770385 ekDisk

: ME_49522F7F018B
 CONST UID '49522F7F018B'
 CONST Name 'ekShell'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_49522F6C0324 // TnsExportKind
 ;

ref; // ME_49522F7F018B ekShell

: ME_49522F860033
 CONST UID '49522F860033'
 CONST Name 'ekEMail'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_49522F6C0324 // TnsExportKind
 ;

ref; // ME_49522F860033 ekEMail

: ME_49522F6C0324
 CONST UID '49522F6C0324'
 CONST Name 'TnsExportKind'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 : Attributes
   Seq: ( ME_49522F770385 // ekDisk
 ME_49522F7F018B // ekShell
 ME_49522F860033 // ekEMail
 )
 ; // Attributes
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_49522F6C0324 TnsExportKind

: ME_4988427E020A
 CONST UID '4988427E020A'
 CONST Name 'DocPosTypeToEdtSubType Etc'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST "spell names" false

ref; // ME_4988427E020A DocPosTypeToEdtSubType Etc

: ME_498C7D1A035D
 CONST UID '498C7D1A035D'
 CONST Name 'TnsLongProcessType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_498C7D1A035D TnsLongProcessType

: ME_4AA11E600367
 CONST UID '4AA11E600367'
 CONST Name 'ETryOpenMissingDocument'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;

ref; // ME_4AA11E600367 ETryOpenMissingDocument

: ME_4AE7093402CF
 CONST UID '4AE7093402CF'
 CONST Name 'TnsDeleteResult'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4AE7093402CF TnsDeleteResult

: ME_4AE7370403CB
 CONST UID '4AE7370403CB'
 CONST Name 'TnsChangeRedactionType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4AE7370403CB TnsChangeRedactionType

: ME_4AE9E3B40320
 CONST UID '4AE9E3B40320'
 CONST Name 'TnsShowSynchroForm'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4AE9E3B40320 TnsShowSynchroForm

FORWARD ME_53A4046B00C7

: ME_53A404710299
 CONST UID '53A404710299'
 CONST Name 'okInCurrentTab'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_53A4046B00C7 // TnsDocumentAndLinkOpenKind
 ;

ref; // ME_53A404710299 okInCurrentTab

: ME_53A4047C017A
 CONST UID '53A4047C017A'
 CONST Name 'okInNewTab'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_53A4046B00C7 // TnsDocumentAndLinkOpenKind
 ;

ref; // ME_53A4047C017A okInNewTab

: ME_53A4048D000E
 CONST UID '53A4048D000E'
 CONST Name 'okInNewWindow'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_53A4046B00C7 // TnsDocumentAndLinkOpenKind
 ;

ref; // ME_53A4048D000E okInNewWindow

: ME_53A4046B00C7
 CONST UID '53A4046B00C7'
 CONST Name 'TnsDocumentAndLinkOpenKind'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 : Attributes
   Seq: ( ME_53A404710299 // okInCurrentTab
 ME_53A4047C017A // okInNewTab
 ME_53A4048D000E // okInNewWindow
 )
 ; // Attributes
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_53A4046B00C7 TnsDocumentAndLinkOpenKind

: ME_57335B010093
 CONST UID '57335B010093'
 CONST Name 'TnsFileFormat'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A6854C70390 // nsTypes
 ;
 : Inherits
   Seq: ( ME_47F21723038D // TnsFileFormat
 )
 ; // Inherits
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_57335B010093 TnsFileFormat

: ME_4AAF9718001D
 CONST UID '4AAF9718001D'
 CONST Name 'nsAStr'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST extprop:rc:SelfName 'AStr'

ref; // ME_4AAF9718001D nsAStr

: ME_4AB882990057
 CONST UID '4AB882990057'
 CONST Name 'nsCStr'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST extprop:rc:SelfName 'CStr'

ref; // ME_4AB882990057 nsCStr

: ME_4ADEE542029C
 CONST UID '4ADEE542029C'
 CONST Name 'nsWStr'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST extprop:rc:SelfName 'WStr'

ref; // ME_4ADEE542029C nsWStr

: ME_4CF4DE5F0071
 CONST UID '4CF4DE5F0071'
 CONST Name 'nsEStr'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4A6854C70390 // nsTypes
 ;
 CONST extprop:rc:SelfName 'EStr'

ref; // ME_4CF4DE5F0071 nsEStr

: ME_4D4162C70077
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4A6854C70390 // nsTypes
 ;
 : Target ME_4D4161F5012E // nsTypesNew
 ;

ref; // ME_4D4162C70077 

: ME_4A6854C70390
 CONST UID '4A6854C70390'
 CONST Name 'nsTypes'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_47F2170002B2 // nsTypes
 ;
 : Operations
   Seq: ( ME_4AAF9718001D // nsAStr
 ME_4AB882990057 // nsCStr
 ME_4ADEE542029C // nsWStr
 ME_4CF4DE5F0071 // nsEStr
 )
 ; // Operations
 : Children
   Seq: ( ME_47F2791D019A // TListLogicOperation
 ME_48FF63BC0129 // TnsResetTreeStatus
 ME_490200F300DD // TnsFilterType
 ME_490B011B02DB // TnsNavigatorItemParams
 ME_490C3BB20118 // TnsMedicMainMenuNodeType
 ME_4921865D0256 // TWarningType
 ME_4921866C01A1 // TWarningTypeSet
 ME_49522F6C0324 // TnsExportKind
 ME_498C7D1A035D // TnsLongProcessType
 ME_4AA11E600367 // ETryOpenMissingDocument
 ME_4AE7093402CF // TnsDeleteResult
 ME_4AE7370403CB // TnsChangeRedactionType
 ME_4AE9E3B40320 // TnsShowSynchroForm
 ME_53A4046B00C7 // TnsDocumentAndLinkOpenKind
 ME_57335B010093 // TnsFileFormat
 )
 ; // Children
 : Constants
   Seq: ( ME_47F244C1009A // TreeConstants
 ME_48FF569700F6 // StringRoutines
 ME_491C0E4503A2 // DateTimeRoutines
 ME_4988427E020A // DocPosTypeToEdtSubType Etc
 )
 ; // Constants
 : Dependencies
   Seq: ( ME_4D4162C70077 // nsTypesNew
 )
 ; // Dependencies
 CONST "finished" false
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Model\NOT_FINISHED_nsTypes.pas'
 CONST extprop:rc:SelfName 'Types'

ref; // ME_4A6854C70390 nsTypes

: ME_47F2170002B2
 CONST UID '47F2170002B2'
 CONST Name 'nsTypes'
 CONST Class class_Category
 : Stereotype st_Unit ;
 %SUMMARY 'Типы используемые в оболочке' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_47E9EEC60260' '47E9EEC60260.pas.ms.script' // Model
 ;
 : Children
   Seq: ( ME_4D4161F5012E // nsTypesNew
 ME_4BA763B0004B // bsTypesNew
 ME_4A6854C70390 // nsTypes
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 WL 'ME_4423F94903C8' '4423F94903C8.pas.ms.script' // IO
 WL 'ME_4570511E038A' '4570511E038A.pas.ms.script' // Document
 WL 'ME_4677FBA70343' '4677FBA70343.pas.ms.script' // l3Interfaces
 WL 'ME_47D0290B016D' '47D0290B016D.pas.ms.script' // l3Utils
 WL 'ME_4912DD020283' '4912DD020283.pas.ms.script' // eeInterfaces
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 )
 ; // Depends
 CONST "is namespace" true

ref; // ME_47F2170002B2 nsTypes
