// TdsListInfo 47FEF9AA00CC ViewAreaControllerImp Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_47FEF9AA00CC

ME ME_4922A8E40072
 MEPROP UID '4922A8E40072'
 MEPROP Name 'InitDataType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_47FEF9AA00CC // TdsListInfo
 ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_4922A8E40072 InitDataType

ME ME_4922A8EE02F3
 MEPROP UID '4922A8EE02F3'
 MEPROP Name 'f_Info'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_47FEF9AA00CC // TdsListInfo
 ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_4922A8EE02F3 f_Info

ME ME_5018071F0299
 MEPROP UID '5018071F0299'
 MEPROP Name 'UseCaseControllerType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_lnk
 MELINK Parent HWL ME_47FEF9AA00CC // TdsListInfo
 ;
 MELINK Target WL 'ME_5018061500D8' '4D1B444C015E.ms.model.script' // IsdsListNameHolder
 ;

ENDME // ME_5018071F0299 UseCaseControllerType

ME ME_4900615A011B
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47FEF9AA00CC // TdsListInfo
 ;
 MELINK Target WL? 'ME_47878E0E0191' // l3String
 ;

ENDME // ME_4900615A011B 

MEREF ME_49005EDD006C_ME_47FEF9AA00CC_impl
 MELINK Original WL 'ME_49005EDD006C' '4D1B444C015E.ms.model.script' // Info
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDMEREF // ME_49005EDD006C_ME_47FEF9AA00CC_impl Info

MEREF ME_49005EEC0338_ME_47FEF9AA00CC_impl
 MELINK Original WL 'ME_49005EEC0338' '4D1B444C015E.ms.model.script' // ListName
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDMEREF // ME_49005EEC0338_ME_47FEF9AA00CC_impl ListName

MEREF ME_49005EF9034C_ME_47FEF9AA00CC_impl
 MELINK Original WL 'ME_49005EF9034C' '4D1B444C015E.ms.model.script' // ShortListName
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDMEREF // ME_49005EF9034C_ME_47FEF9AA00CC_impl ShortListName

MEREF ME_479731C50290_ME_47FEF9AA00CC_over
 MELINK Original WL 'ME_479731C50290' '51612ED700B4.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_479731C50290_ME_47FEF9AA00CC_over Cleanup

MEREF ME_492ACF630072_ME_47FEF9AA00CC_over
 MELINK Original WL 'ME_492ACF630072' '501802270075.ms.model.script' // GotData
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_492ACF630072_ME_47FEF9AA00CC_over GotData

MEREF ME_50180358024F_ME_47FEF9AA00CC_G
 MELINK Original WL? 'ME_50180358024F' // vcmFormDataSourceWithFlexUseCaseControllerType
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_50180358024F_ME_47FEF9AA00CC_G vcmFormDataSourceWithFlexUseCaseControllerType

MEREF ME_49005E89009D_ME_47FEF9AA00CC_R
 MELINK Original WL 'ME_49005E89009D' '4D1B444C015E.ms.model.script' // IdsListInfo
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_49005E89009D_ME_47FEF9AA00CC_R IdsListInfo

%%ImplementedBy ME_49005E89009D ME_47FEF9AA00CC

%%InheritedBy ME_50180358024F ME_47FEF9AA00CC

ME ME_47FEF9AA00CC
 MEPROP UID '47FEF9AA00CC'
 MEPROP Name 'TdsListInfo'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_ViewAreaControllerImp ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Информация о списке.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL? 'ME_47EA5024034B' // ListDataSources
 ;
 MELIST Inherits
   Seq: ( ME_50180358024F_ME_47FEF9AA00CC_G // vcmFormDataSourceWithFlexUseCaseControllerType
 )
 ; // Inherits
 MELIST Implements
   Seq: ( ME_49005E89009D_ME_47FEF9AA00CC_R // IdsListInfo
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_4922A8E40072 // InitDataType
 HWL ME_4922A8EE02F3 // f_Info
 HWL ME_5018071F0299 // UseCaseControllerType
 )
 ; // Attributes
 MELIST Implemented
   Seq: ( ME_49005EDD006C_ME_47FEF9AA00CC_impl // Info
 ME_49005EEC0338_ME_47FEF9AA00CC_impl // ListName
 ME_49005EF9034C_ME_47FEF9AA00CC_impl // ShortListName
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_47FEF9AA00CC_over // Cleanup
 ME_492ACF630072_ME_47FEF9AA00CC_over // GotData
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_4900615A011B // l3String
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "author" 'Морозов М.А.'
 UP "no hands" true
 UP "started" '29.07.2005 17.07'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Business\List\dsListInfo.pas'
 UP extprop:rc:SelfName 'dsListInfo'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'dsListInfo'

ENDME // ME_47FEF9AA00CC TdsListInfo
