// SyncObjs 48078324039E UtilityPack Class

FORWARD ME_48078324039E

: ME_4807833801D7
 CONST UID '4807833801D7'
 CONST Name 'TCriticalSection'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 %SUMMARY 'TCriticalSection allows a thread in a multi-threaded application to temporarily block other threads from accessing a block of code.' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_4807833801D7 TCriticalSection

: ME_483BE09901F5
 CONST UID '483BE09901F5'
 CONST Name 'TSimpleEvent'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 %SUMMARY 'TSimpleEvent represents an unnamed manual event object.' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_483BE09901F5 TSimpleEvent

: ME_491D9DB8010F
 CONST UID '491D9DB8010F'
 CONST Name 'TEvent'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 %SUMMARY 'TEvent represents an external event.' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_491D9DB8010F TEvent

: ME_48078324039E
 CONST UID '48078324039E'
 CONST Name 'SyncObjs'
 CONST Class 'Class'
 CONST Stereotype 'UtilityPack'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Children
   [ ME_4807833801D7 // TCriticalSection
 ME_483BE09901F5 // TSimpleEvent
 ME_491D9DB8010F // TEvent
 ]
 ; // Children
 CONST "no hands" false

 @SELF
; // ME_48078324039E SyncObjs
