// Editors 4829D7D50156 Views Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156
%%Inner ME_4829D7D50156

ME ME_4829D7D50156
 MEPROP UID '4829D7D50156'
 MEPROP Name 'Editors'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Views ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4797632D0273' // Everest
 ;
 MELIST Children
   Seq: ( WL? 'ME_48E229CC03DF' // TevEditorWindowHotSpot
 WL? 'ME_487B5D2D004E' // TevCursorController
 WL? 'ME_487B5D7202DC' // TevWindowCursor
 WL? 'ME_487B5D8D00ED' // TevBlockCursor
 WL? 'ME_482D98A20190' // TevCustomMemoTextSource
 WL? 'ME_487B5DD202DF' // TnevSelection
 WL? 'ME_482D888D039E' // TevCustomMemoContainer
 WL? 'ME_482D894F00D6' // TevCustomEditDocumentContainer
 WL? 'ME_482D8A0D02E3' // TevEditDocumentContainer
 WL? 'ME_4864C01000A7' // TevMemoProcessor
 WL? 'ME_482D988102EC' // TevCustomEditTextSource
 WL? 'ME_4B28D63A00EC' // TevCustomEditorWindowPrim
 WL? 'ME_48452014010D' // TevMemoContextMenu
 WL? 'ME_4829D92A037B' // TevCustomEditorWindow
 WL? 'ME_4A26509001EA' // TevCustomEditorWindowModelPart
 WL? 'ME_4829D8C50010' // TevMultiSelectEditorWindow
 WL? 'ME_4B877C5101C1' // TevCustomEditorModelPart
 WL? 'ME_482D8B94020E' // TevEditProcessor
 WL? 'ME_4829D89703D2' // TevCustomEditor
 WL? 'ME_4829D85C03C1' // TevEditorWithOperations
 WL? 'ME_4829D81D02E5' // TevCustomMemo
 WL? 'ME_4829D7E80085' // TevCustomEdit
 WL? 'ME_48E385660374' // evRange
 WL? 'ME_4845367E03B1' // TevTunedEditor
 WL? 'ME_48E3B50501DB' // TevMultiSelection
 WL? 'ME_48ECCE2903AD' // TevMultiSelectionLocation
 WL? 'ME_48E3BA3300DE' // evRangeTools
 WL? 'ME_48E497E40042' // TevMultiSelectEditorWindowHotSpot
 WL? 'ME_48ECD38B0204' // TevMultiSelectionRange
 WL? 'ME_48ECDC5E005D' // TevMultiSelectionDataFormatting
 WL? 'ME_48ECDF6602FD' // TevMultiSelectionText
 WL? 'ME_48E3B83B0187' // TevMultiSelectionBlock
 WL? 'ME_48ECD64B005A' // TevLeafParaMultiSelectionBlock
 WL? 'ME_48ECD68E0010' // TevTextParaMultiSelectionBlock
 WL? 'ME_484658060127' // TevEdit
 WL? 'ME_484544370206' // TevEditor
 WL? 'ME_48454EBB0050' // TevMemo
 WL? 'ME_4BBD91060298' // evEditorInterfacesMisc
 WL? 'ME_4BBD91980212' // evBitmapReader
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4677FBA70343' // l3Interfaces
 WL? 'ME_4678137501EA' // k2Interfaces
 WL? 'ME_4678193C009C' // l3Types
 WL? 'ME_4678209200A6' // nevBase
 WL? 'ME_467823B7002C' // afwInterfaces
 WL? 'ME_467BA8C8017E' // afwControl
 WL? 'ME_467BAB7F021E' // vcmExternalInterfaces
 WL? 'ME_467C0CAA02AB' // l3InternalInterfaces
 WL? 'ME_467C182A01BE' // k2TagTool
 WL? 'ME_467FC43F01F9' // k2CoreObjects
 WL? 'ME_469D0AC7005E' // Types
 WL? 'ME_46A5E026007E' // l3Core
 WL? 'ME_472745450206' // l3Units
 WL? 'ME_4728A7020026' // Types
 WL? 'ME_476BE0350329' // Styles
 WL? 'ME_476BE98C01B8' // l3Chars
 WL? 'ME_476F78840219' // Messages
 WL? 'ME_47750CE700D0' // afwFacade
 WL? 'ME_47877A6F000A' // Visual
 WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_4799D29F033F' // Implementation
 WL? 'ME_47AC75550330' // k2Tags
 WL? 'ME_47BB24D30205' // Стандартные примеси
 WL? 'ME_47C5207602D1' // nevTools
 WL? 'ME_47C52679006D' // nevUtils
 WL? 'ME_47C695A10172' // evTypes
 WL? 'ME_47ECA80B000D' // Generators
 WL? 'ME_47ECAB0B0265' // evMsgCode
 WL? 'ME_47ECACA70141' // Generators
 WL? 'ME_47ECB04A01F8' // Processors
 WL? 'ME_47ECB8BD00A8' // Generators
 WL? 'ME_47F086170200' // DocumentContainers
 WL? 'ME_47F088300159' // evInternalInterfaces
 WL? 'ME_47F1F38601A3' // ParaUtils
 WL? 'ME_47F1F90A0391' // Searchers
 WL? 'ME_47F2458300E4' // evDef
 WL? 'ME_4802FF41005C' // DataObjects
 WL? 'ME_480DBA6900E6' // k2Facade
 WL? 'ME_4811D4EC0237' // Views
 WL? 'ME_482BFB50007B' // TextSources
 WL? 'ME_48452B7D0314' // evExcept
 WL? 'ME_48453A40017C' // evOp
 WL? 'ME_48492FC0029D' // Standard
 WL? 'ME_484A470100DD' // Standard
 WL? 'ME_48E0E52B00D7' // CoreControls
 WL? 'ME_48E3836D00C8' // evEditorInterfaces
 WL? 'ME_48E3A9B902F6' // evSelectConst
 WL? 'ME_48F4E61C0060' // Interfaces
 WL? 'ME_49A58A1A03C4' // k2PrimObjects
 WL? 'ME_49A6646B0044' // k2BaseTypes
 WL? 'ME_4A1FCBA0014C' // nevGUIInterfaces
 WL? 'ME_4A23935A0282' // afwNavigation
 WL? 'ME_4A251D6E00BD' // nevNavigation
 WL? 'ME_4A4DE16302A2' // k2Core
 WL? 'ME_4AB0997B00A2' // Common
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_4AB0C3F60375' // Win
 WL? 'ME_4B893514021E' // Pretty Things
 WL? 'ME_4CC81FAC02D6' // Core
 WL? 'ME_4E451815031E' // CellUtils
 WL? 'ME_4E5CF70B01E2' // Требования к редактору Эверест
 WL? 'ME_4E60BA4D00A6' // Fonts
 WL? 'ME_4E787E1E02F8' // Редактор с выпадающим деревом
 WL? 'ME_4E96FFD70348' // Поля ввода
 WL? 'ME_537B83AD01F0' // l3Math
 WL? 'ME_54B90AC6014B' // StringUtils
 WL? 'ME_55001317029B' // VCLHelpers
 WL? 'ME_55C4AEC801CA' // Graphics
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' 'Usecases' )
 ; // DiagramsNames

ENDME // ME_4829D7D50156 Editors
