// evOp 48453A40017C Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_48453A40017C

: ME_48453A750156
 CONST UID '48453A750156'
 CONST Name 'Operations'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_48453A40017C // evOp
 ;
 CONST "spell names" false
 CONST intf.pas:PathOnly '\common\components\gui\Garant\Everest'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_48453A750156 Operations

: ME_48453A40017C
 CONST UID '48453A40017C'
 CONST Name 'evOp'
 CONST Class class_Category
 : Stereotype st_Interfaces ;
 %SUMMARY 'Описание кодов операций.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4797632D0273' '4797632D0273.pas.ms.script' // Everest
 ;
 : Constants
   Seq: ( ME_48453A750156 // Operations
 )
 ; // Constants
 CONST "author" 'Люлин А.В.'
 CONST "finished" false
 CONST "is namespace" true
 CONST "no hands" false
 CONST "started" '20.03.97 16:51'
 CONST intf.pas:Path 'common\components\gui\Garant\Everest\NOT_FINISHED_evOp.pas'
 CONST intf.pas:PathOnly '\common\components\gui\Garant\Everest'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\48453A40017C.pas.ms.script'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\48453A40017C.pas.ms.script.runner'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_48453A40017C evOp
