// Информационная поддержка 484E610E0335 UseCases Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_484E610E0335
%%Inner ME_484E610E0335
%%Inner ME_484E610E0335
%%Inner ME_484E610E0335
%%Inner ME_484E610E0335
%%Inner ME_484E610E0335
%%Inner ME_484E610E0335

FORWARD ME_484E610E0335

FORWARD ME_484E635201F4

ME ME_4EF0BAC0030E
 MEPROP UID '4EF0BAC0030E'
 MEPROP Name 'На тулбаре формы ПРАЙМ Моя новостная лента должна быть операция Редактировать индивидуальную ленту'
 MEPROP Class class_Class
 MELINK Stereotype st_UseCaseRequirement ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{RequestLink:296626376}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_484E635201F4 // ПРАЙМ
 ;

ENDME // ME_4EF0BAC0030E На тулбаре формы ПРАЙМ Моя новостная лента должна быть операция Редактировать индивидуальную ленту

ME ME_484E635201F4
 MEPROP UID '484E635201F4'
 MEPROP Name 'ПРАЙМ'
 MEPROP Class class_Class
 MELINK Stereotype st_UseCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Модуль «Прайм» разрабатывается с целью удовлетворения потребности пользователей в специализированной актуальной информации об изменениях в законодательства РФ, новых судебных решениях, новых законопроектах.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_484E610E0335 // Информационная поддержка
 ;
 MELIST Children
   Seq: ( HWL ME_4EF0BAC0030E // На тулбаре формы ПРАЙМ Моя новостная лента должна быть операция Редактировать индивидуальную ленту
 )
 ; // Children
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames

ENDME // ME_484E635201F4 ПРАЙМ

FORWARD ME_484E638701D9

ME ME_4E92C51C0028
 MEPROP UID '4E92C51C0028'
 MEPROP Name 'Консультации должны поддерживать ссылки на документы Гаранта'
 MEPROP Class class_Class
 MELINK Stereotype st_UseCaseRequirement ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{RequestLink:290948856}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_484E638701D9 // Консультации
 ;

ENDME // ME_4E92C51C0028 Консультации должны поддерживать ссылки на документы Гаранта

ME ME_4F68893A005B
 MEPROP UID '4F68893A005B'
 MEPROP Name 'Правый отступ вложенных документов должен быть равен НУЛЮ'
 MEPROP Class class_Class
 MELINK Stereotype st_UseCaseRequirement ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{RequestLink:336665133}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_484E638701D9 // Консультации
 ;

ENDME // ME_4F68893A005B Правый отступ вложенных документов должен быть равен НУЛЮ

ME ME_484E638701D9
 MEPROP UID '484E638701D9'
 MEPROP Name 'Консультации'
 MEPROP Class class_Class
 MELINK Stereotype st_UseCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Реализация новой услуги «Консультации».' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_484E610E0335 // Информационная поддержка
 ;
 MELIST Children
   Seq: ( HWL ME_4E92C51C0028 // Консультации должны поддерживать ссылки на документы Гаранта
 HWL ME_4F68893A005B // Правый отступ вложенных документов должен быть равен НУЛЮ
 )
 ; // Children
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames

ENDME // ME_484E638701D9 Консультации

ME ME_484E63DE00A2
 MEPROP UID '484E63DE00A2'
 MEPROP Name 'Проверка доступности Сервера консультаций'
 MEPROP Class class_Class
 MELINK Stereotype st_UseCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Для проверки доступности Сервера консультаций создается отдельная утилита, ConsultingChecker, которая может быть запущена на стороне клиента для проверки возможности подключения к услуге консультаций.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_484E610E0335 // Информационная поддержка
 ;

ENDME // ME_484E63DE00A2 Проверка доступности Сервера консультаций

ME ME_484E640200F5
 MEPROP UID '484E640200F5'
 MEPROP Name 'Взаимодействие СК с ОПП'
 MEPROP Class class_Class
 MELINK Stereotype st_UseCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'В рамках задачи оказания консультационных услуг на стороне компании Гарант требовалось организовать взаимодействие с внешней подсистемой ОПП (Консультационный отдел Пащака)' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_484E610E0335 // Информационная поддержка
 ;

ENDME // ME_484E640200F5 Взаимодействие СК с ОПП

ME ME_484E6472032F
 MEPROP UID '484E6472032F'
 MEPROP Name 'Сохранение-Восстановление консультаций'
 MEPROP Class class_Class
 MELINK Stereotype st_UseCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Описание специальных процессов происходящих на Сервере консультаций, управление или настройка которых возможна со стороны.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_484E610E0335 // Информационная поддержка
 ;

ENDME // ME_484E6472032F Сохранение-Восстановление консультаций

ME ME_484E64DF0172
 MEPROP UID '484E64DF0172'
 MEPROP Name 'Дополнительная информация в консультациях'
 MEPROP Class class_Class
 MELINK Stereotype st_UseCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Вместе с запросом на консультацию в компанию Гарант должна передаваться дополнительная информация' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_484E610E0335 // Информационная поддержка
 ;

ENDME // ME_484E64DF0172 Дополнительная информация в консультациях

FORWARD ME_484E65860289

ME ME_484E65860289
 MEPROP UID '484E65860289'
 MEPROP Name 'Сервер консультаций'
 MEPROP Class class_Class
 MELINK Stereotype st_UseCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Описания форматов обмена и хранения и принципов работы с СК' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_484E610E0335 // Информационная поддержка
 ;

ENDME // ME_484E65860289 Сервер консультаций

ME ME_484E610E0335
 MEPROP UID '484E610E0335'
 MEPROP Name 'Информационная поддержка'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_UseCases ;
 %SUMMARY 'ПРАЙМ и Консультации.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_481EF5C4020D' '481EF5C4020D.ms.model.script' // Оболочка
 ;
 MELIST Children
   Seq: ( HWL ME_484E635201F4 // ПРАЙМ
 HWL ME_484E638701D9 // Консультации
 HWL ME_484E63DE00A2 // Проверка доступности Сервера консультаций
 HWL ME_484E640200F5 // Взаимодействие СК с ОПП
 HWL ME_484E6472032F // Сохранение-Восстановление консультаций
 HWL ME_484E64DF0172 // Дополнительная информация в консультациях
 HWL ME_484E65860289 // Сервер консультаций
 )
 ; // Children
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames

ENDME // ME_484E610E0335 Информационная поддержка
