// SandBox 4861FFCA02CE Library Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4861FFCA02CE
%%Inner ME_4861FFCA02CE
%%Inner ME_4861FFCA02CE
%%Inner ME_4861FFCA02CE
%%Inner ME_4861FFCA02CE
%%Inner ME_4861FFCA02CE
%%Inner ME_4861FFCA02CE
%%Inner ME_4861FFCA02CE
%%Inner ME_4861FFCA02CE
%%Inner ME_4861FFCA02CE

ME ME_4861FFCA02CE
 MEPROP UID '4861FFCA02CE'
 MEPROP Name 'SandBox'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Library ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4AB10D480337' '4AB10D480337.ms.model.script' // Shared Delphi Sand Box
 ;
 MELIST Children
   Seq: ( WL 'ME_4861FFE8022A' '4861FFE8022A.ms.model.script' // Pure
 WL 'ME_4861FFF4005B' '4861FFF4005B.ms.model.script' // Concret
 WL 'ME_486203BB00E8' '486203BB00E8.ms.model.script' // Meta
 WL 'ME_51545DDC0252' '51545DDC0252.ms.model.script' // Containers
 WL 'ME_5161376C021A' '5161376C021A.ms.model.script' // Reference Counting
 WL 'ME_516D4F3100AB' '516D4F3100AB.ms.model.script' // Basic Interfaces
 WL 'ME_517C0F37039A' '517C0F37039A.ms.model.script' // Rounded
 WL 'ME_51DEB06A03CB' '51DEB06A03CB.ms.model.script' // STLLike
 WL 'ME_51DEB22001AC' '51DEB22001AC.ms.model.script' // FinalContainers
 WL 'ME_55196110004E' '55196110004E.ms.model.script' // Services
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_4684F91300DD' '4684F91300DD.ms.model.script' // Vcl
 WL 'ME_469F3E37025A' '469F3E37025A.ms.model.script' // Rtl
 WL 'ME_4790D09A0378' '4790D09A0378.ms.model.script' // L3
 WL 'ME_4CC81F680162' '4CC81F680162.ms.model.script' // SkinnedControls
 WL 'ME_515AC89F01E1' '515AC89F01E1.ms.model.script' // L3$Basic Concepts
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "defines" 'sbDefine.inc'
 UP "exec mode" 'concluded'
 UP "gui" 'prj'
 UP "is namespace" true
 UP "vendor" 'none'
 UP intf.pas:PathOnly '\common\components\SandBox'

ENDME // ME_4861FFCA02CE SandBox
