// l3Operations 48BD24D4011D Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_48BD24D4011D

FORWARD ME_48BD24F800DF

: ME_48BD25040010
 CONST UID '48BD25040010'
 CONST Name 'l3_ocShortCut'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_48BD24F800DF // Operations
 ;
 CONST Value 'ccShortCut'
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 'ccShortCut'

ref; // ME_48BD25040010 l3_ocShortCut

: ME_48BD24F800DF
 CONST UID '48BD24F800DF'
 CONST Name 'Operations'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_48BD24D4011D // l3Operations
 ;
 : Attributes
   Seq: ( HWL ME_48BD25040010 // l3_ocShortCut
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_48BD24F800DF Operations

: ME_48BD24D4011D
 CONST UID '48BD24D4011D'
 CONST Name 'l3Operations'
 CONST Class class_Category
 : Stereotype st_Interfaces ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4790D09A0378' '4790D09A0378.pas.ms.script' // L3
 ;
 : Constants
   Seq: ( HWL ME_48BD24F800DF // Operations
 )
 ; // Constants
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 )
 ; // Depends
 CONST "UseNewGen" true
 CONST "author" 'Ëþëèí À.Â.'
 CONST "finished" false
 CONST "is namespace" true
 CONST "started" '27.05.2005 15:10'
 CONST intf.pas:Path 'common\components\rtl\Garant\L3\NOT_FINISHED_l3Operations.pas'

ref; // ME_48BD24D4011D l3Operations
