// Users 4901E79300F5 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4901E79300F5

FORWARD ME_49E8213D00F6

: ME_49E83D460323
 CONST UID '49E83D460323'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_49E8213D00F6 // TnsGroupTreeStruct
 ;
 : Target WL 'ME_48FF556602BA' '48F747EC0073.pas.ms.script' // DataAdapter
 ;

ref; // ME_49E83D460323 

: ME_49E83DCB00D8
 CONST UID '49E83DCB00D8'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_49E8213D00F6 // TnsGroupTreeStruct
 ;
 : Target WL 'ME_47FB50E4008E' '48F747EC0073.pas.ms.script' // nsConst
 ;

ref; // ME_49E83DCB00D8 

: ME_48FF64F60078_ME_49E8213D00F6
 CONST UID '48FF64F60078'
 CONST Name 'ReAqurieUnfilteredRoot'
 : Original WL 'ME_48FF64F60078' '48FD8B2702F6.pas.ms.script' // ReAqurieUnfilteredRoot
 ;
 : Implementor ME_49E8213D00F6 // TnsGroupTreeStruct
 ;
 CONST OpKind opkind_Implemented
ref; // ME_48FF64F60078_ME_49E8213D00F6 ReAqurieUnfilteredRoot

: ME_48FF56D003E6_ME_49E8213D00F6
 CONST UID '48FF56D003E6'
 CONST Name 'SettingsID'
 : Original WL 'ME_48FF56D003E6' '48FD8B2702F6.pas.ms.script' // SettingsID
 ;
 : Implementor ME_49E8213D00F6 // TnsGroupTreeStruct
 ;
 CONST OpKind opkind_Overridden
ref; // ME_48FF56D003E6_ME_49E8213D00F6 SettingsID

: ME_49E8213D00F6
 CONST UID '49E8213D00F6'
 CONST Name 'TnsGroupTreeStruct'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4901E79300F5 // Users
 ;
 : Inherits
   Seq: ( WL 'ME_468361010204' '48FD8B2702F6.pas.ms.script' // TnsDataResetTreeStruct
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_48FF64F60078_ME_49E8213D00F6 // ReAqurieUnfilteredRoot
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_48FF56D003E6_ME_49E8213D00F6 // SettingsID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_49E83D460323 // 
 ME_49E83DCB00D8 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Admin\nsGroupTreeStruct.pas'
 CONST extprop:rc:SelfName 'GroupTreeStruct'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'nsGroupTreeStruct'

ref; // ME_49E8213D00F6 TnsGroupTreeStruct

FORWARD ME_49F16EBF02AD

: ME_49F56569010B
 CONST UID '49F56569010B'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_49F16EBF02AD // TnsUserTreeStructWithDrag
 ;
 : Target WL 'ME_49F552BA0035' '49F17D370263.pas.ms.script' // TbsUserDataObject
 ;

ref; // ME_49F56569010B 

: ME_49F596B102B3
 CONST UID '49F596B102B3'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_49F16EBF02AD // TnsUserTreeStructWithDrag
 ;
 : Target WL 'ME_49F592D400E6' '49F17D370263.pas.ms.script' // TbsUserTreeData
 ;

ref; // ME_49F596B102B3 

: ME_48FEE6210205_ME_49F16EBF02AD
 CONST UID '48FEE6210205'
 CONST Name 'DoMakeDataObject'
 : Original WL 'ME_48FEE6210205' '48FD8B2702F6.pas.ms.script' // DoMakeDataObject
 ;
 : Implementor ME_49F16EBF02AD // TnsUserTreeStructWithDrag
 ;
 CONST OpKind opkind_Overridden
ref; // ME_48FEE6210205_ME_49F16EBF02AD DoMakeDataObject

: ME_49F16EBF02AD
 CONST UID '49F16EBF02AD'
 CONST Name 'TnsUserTreeStructWithDrag'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4901E79300F5 // Users
 ;
 : Inherits
   Seq: ( WL 'ME_4906E96C0364' '4ACF68160358.pas.ms.script' // TnsUserTreeStruct
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_48FEE6210205_ME_49F16EBF02AD // DoMakeDataObject
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_49F56569010B // 
 ME_49F596B102B3 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Admin\nsUserTreeStructWithDrag.pas'
 CONST extprop:rc:SelfName 'UserTreeStructWithDrag'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'nsUserTreeStructWithDrag'

ref; // ME_49F16EBF02AD TnsUserTreeStructWithDrag

FORWARD ME_49F16EE7010F

: ME_49F5B739033E
 CONST UID '49F5B739033E'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_49F16EE7010F // TnsGroupTreeStructWithDrop
 ;
 : Target WL 'ME_49F17AE6005F' '47ECAAF901F8.pas.ms.script' // IbsUserTreeData
 ;

ref; // ME_49F5B739033E 

: ME_49F5BA9800A7
 CONST UID '49F5BA9800A7'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_49F16EE7010F // TnsGroupTreeStructWithDrop
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_49F5BA9800A7 

: ME_49F5BAB60373
 CONST UID '49F5BAB60373'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_49F16EE7010F // TnsGroupTreeStructWithDrop
 ;
 : Target WL 'ME_48FF556602BA' '48F747EC0073.pas.ms.script' // DataAdapter
 ;

ref; // ME_49F5BAB60373 

: ME_49F5BADD00A6
 CONST UID '49F5BADD00A6'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_49F16EE7010F // TnsGroupTreeStructWithDrop
 ;
 : Target WL 'ME_4651A5AE00FA' '45EEAA96039C.pas.ms.script' // UidList
 ;

ref; // ME_49F5BADD00A6 

FORWARD ME_49E5BB5F02B7

: ME_49F5BD0001EC
 CONST UID '49F5BD0001EC'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_49F16EE7010F // TnsGroupTreeStructWithDrop
 ;
 : Target ME_49E5BB5F02B7 // nsUserNodes
 ;

ref; // ME_49F5BD0001EC 

: ME_48FEE78E01B2_ME_49F16EE7010F
 CONST UID '48FEE78E01B2'
 CONST Name 'DoCanAcceptData'
 : Original WL 'ME_48FEE78E01B2' '48FD8B2702F6.pas.ms.script' // DoCanAcceptData
 ;
 : Implementor ME_49F16EE7010F // TnsGroupTreeStructWithDrop
 ;
 CONST OpKind opkind_Overridden
ref; // ME_48FEE78E01B2_ME_49F16EE7010F DoCanAcceptData

: ME_48FEE9D303B6_ME_49F16EE7010F
 CONST UID '48FEE9D303B6'
 CONST Name 'DoDropData'
 : Original WL 'ME_48FEE9D303B6' '48FD8B2702F6.pas.ms.script' // DoDropData
 ;
 : Implementor ME_49F16EE7010F // TnsGroupTreeStructWithDrop
 ;
 CONST OpKind opkind_Overridden
ref; // ME_48FEE9D303B6_ME_49F16EE7010F DoDropData

: ME_49F16EE7010F
 CONST UID '49F16EE7010F'
 CONST Name 'TnsGroupTreeStructWithDrop'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4901E79300F5 // Users
 ;
 : Inherits
   Seq: ( ME_49E8213D00F6 // TnsGroupTreeStruct
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_48FEE78E01B2_ME_49F16EE7010F // DoCanAcceptData
 ME_48FEE9D303B6_ME_49F16EE7010F // DoDropData
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_49F5B739033E // 
 ME_49F5BA9800A7 // 
 ME_49F5BAB60373 // 
 ME_49F5BADD00A6 // 
 ME_49F5BD0001EC // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Admin\nsGroupTreeStructWithDrop.pas'
 CONST extprop:rc:SelfName 'GroupTreeStructWithDrop'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'nsGroupTreeStructWithDrop'

ref; // ME_49F16EE7010F TnsGroupTreeStructWithDrop

FORWARD ME_4AD5ACC50294

: ME_4B1CD66C0189
 CONST UID '4B1CD66C0189'
 CONST Name 'aNode'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_468259900322' '4682595B0268.pas.ms.script' // Il3SimpleNode
 ;

ref; // ME_4B1CD66C0189 aNode

: ME_4B1CD6600026
 CONST UID '4B1CD6600026'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4AD5ACC50294 // GetUserID
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Parameters
   Seq: ( ME_4B1CD66C0189 // aNode
 )
 ; // Parameters

ref; // ME_4B1CD6600026 DoIt

: ME_4B1CD74A0065
 CONST UID '4B1CD74A0065'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4AD5ACC50294 // GetUserID
 ;
 : Target WL 'ME_4ADEE49C02DF' '4AB0C3C60310.pas.ms.script' // Supports
 ;

ref; // ME_4B1CD74A0065 

: ME_4B1CDA4D016F
 CONST UID '4B1CDA4D016F'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4AD5ACC50294 // GetUserID
 ;
 : Target WL 'ME_45EED730037A' '45EEAA96039C.pas.ms.script' // ProfileNode
 ;

ref; // ME_4B1CDA4D016F 

: ME_4B1CE05A02B5
 CONST UID '4B1CE05A02B5'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4AD5ACC50294 // GetUserID
 ;
 : Target WL 'ME_47FB50E4008E' '48F747EC0073.pas.ms.script' // nsConst
 ;

ref; // ME_4B1CE05A02B5 

: ME_4AD5ACC50294
 CONST UID '4AD5ACC50294'
 CONST Name 'GetUserID'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_49E5BB5F02B7 // nsUserNodes
 ;
 : Operations
   Seq: ( ME_4B1CD6600026 // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4B1CD74A0065 // 
 ME_4B1CDA4D016F // 
 ME_4B1CE05A02B5 // 
 )
 ; // Dependencies

ref; // ME_4AD5ACC50294 GetUserID

FORWARD ME_4B1CD6EE038B

: ME_4B1CD70900A8
 CONST UID '4B1CD70900A8'
 CONST Name 'aUserID'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4B1CD70900A8 aUserID

: ME_4B1CD70900CC
 CONST UID '4B1CD70900CC'
 CONST Name 'aTreeStruct'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46825CC00249' '4682595B0268.pas.ms.script' // Il3SimpleTree
 ;

ref; // ME_4B1CD70900CC aTreeStruct

: ME_4B1CD6F90165
 CONST UID '4B1CD6F90165'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4B1CD6EE038B // GetUserByID
 ;
 : Target WL 'ME_468259900322' '4682595B0268.pas.ms.script' // Il3SimpleNode
 ;
 : Parameters
   Seq: ( ME_4B1CD70900A8 // aUserID
 ME_4B1CD70900CC // aTreeStruct
 )
 ; // Parameters

ref; // ME_4B1CD6F90165 DoIt

: ME_4B1CD80C032E
 CONST UID '4B1CD80C032E'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4B1CD6EE038B // GetUserByID
 ;
 : Target WL 'ME_4B1CD77B0238' '47E246C90144.pas.ms.script' // l3L2SNA
 ;

ref; // ME_4B1CD80C032E 

: ME_4B1CD6EE038B
 CONST UID '4B1CD6EE038B'
 CONST Name 'GetUserByID'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_49E5BB5F02B7 // nsUserNodes
 ;
 : Operations
   Seq: ( ME_4B1CD6F90165 // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4B1CD80C032E // 
 )
 ; // Dependencies

ref; // ME_4B1CD6EE038B GetUserByID

: ME_49E5BB5F02B7
 CONST UID '49E5BB5F02B7'
 CONST Name 'nsUserNodes'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4901E79300F5 // Users
 ;
 : Operations
   Seq: ( ME_4AD5ACC50294 // GetUserID
 ME_4B1CD6EE038B // GetUserByID
 )
 ; // Operations
 CONST "author" 'Морозов М.А.'
 CONST "no hands" true
 CONST "started" '2004/02/12 13:28:43'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Admin\nsUserNodes.pas'
 CONST extprop:rc:SelfName 'UserNodes'

ref; // ME_49E5BB5F02B7 nsUserNodes

: ME_4901E79300F5
 CONST UID '4901E79300F5'
 CONST Name 'Users'
 CONST Class class_Category
 : Stereotype st_Unit ;
 %SUMMARY 'Структуры данных для работы с учётными записями пользователей' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_493FBE3E033A' '493FBE3E033A.pas.ms.script' // Admin
 ;
 : Children
   Seq: ( ME_49E8213D00F6 // TnsGroupTreeStruct
 ME_49F16EBF02AD // TnsUserTreeStructWithDrag
 ME_49F16EE7010F // TnsGroupTreeStructWithDrop
 ME_49E5BB5F02B7 // nsUserNodes
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_457450470167' '457450470167.pas.ms.script' // DynamicTree
 WL 'ME_45EEAA96039C' '45EEAA96039C.pas.ms.script' // Security
 WL 'ME_4677FBA70343' '4677FBA70343.pas.ms.script' // l3Interfaces
 WL 'ME_4678193C009C' '4678193C009C.pas.ms.script' // l3Types
 WL 'ME_4682595B0268' '4682595B0268.pas.ms.script' // l3TreeInterfaces
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_47E246C90144' '47E246C90144.pas.ms.script' // l3Trees
 WL 'ME_47ECAAF901F8' '47ECAAF901F8.pas.ms.script' // bsInterfaces
 WL 'ME_48F747EC0073' '48F747EC0073.pas.ms.script' // Common
 WL 'ME_48FD8B2702F6' '48FD8B2702F6.pas.ms.script' // Tree
 WL 'ME_49F17D370263' '49F17D370263.pas.ms.script' // UsersDataObjects
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_4ACF68160358' '4ACF68160358.pas.ms.script' // Users$CommonForAdminAndF1
 )
 ; // Depends
 CONST "ifdef" 'Admin'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\4901E79300F5.pas.ms.script'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\4901E79300F5.pas.ms.script.runner'

ref; // ME_4901E79300F5 Users
