// DayTips 491D560F01F4 ControllerUnit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_491D560F01F4

FORWARD ME_4992891800CF

: ME_499289CF03A7
 CONST UID '499289CF03A7'
 CONST Name 'f_TipsTree'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_46825CC00249' '4682595B0268.pas.ms.script' // Il3SimpleTree
 ;

ref; // ME_499289CF03A7 f_TipsTree

: ME_499289E00058
 CONST UID '499289E00058'
 CONST Name 'f_CurrentNode'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_468259900322' '4682595B0268.pas.ms.script' // Il3SimpleNode
 ;

ref; // ME_499289E00058 f_CurrentNode

: ME_49928A3E007F
 CONST UID '49928A3E007F'
 CONST Name 'f_DontShow'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_49928A3E007F f_DontShow

: ME_49928A97027C
 CONST UID '49928A97027C'
 CONST Name 'Create'
 CONST Class class_Operation
 : Stereotype st_ctor::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;

ref; // ME_49928A97027C Create

: ME_49928AA3039A
 CONST UID '49928AA3039A'
 CONST Name 'MakePrim'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;

ref; // ME_49928AA3039A MakePrim

: ME_4993F1F80032
 CONST UID '4993F1F80032'
 CONST Name 'Make'
 CONST Class class_Operation
 : Stereotype st_static::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_4991C6FF00C7' '4991C6930254.pas.ms.script' // InsStartupTips
 ;

ref; // ME_4993F1F80032 Make

: ME_49928AD80373
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_47F260EC02C7' '521C9DA50125.pas.ms.script' // StdRes
 ;

ref; // ME_49928AD80373 

: ME_49928AEE0176
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_48FF556602BA' '48F747EC0073.pas.ms.script' // DataAdapter
 ;

ref; // ME_49928AEE0176 

: ME_49928B1500D8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_47752AF90375' '47750CE700D0.pas.ms.script' // afwFacade
 ;

ref; // ME_49928B1500D8 

: ME_49928B1D0064
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_47FB50E4008E' '48F747EC0073.pas.ms.script' // nsConst
 ;

ref; // ME_49928B1D0064 

: ME_49928C4501B7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_49928C4501B7 

: ME_49928C59007D
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_45EEC8680109' '457450470167.pas.ms.script' // NodeIndexPath
 ;

ref; // ME_49928C59007D 

: ME_49928C8001B8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_45EEB6520191' '4570511E038A.pas.ms.script' // Document
 ;

ref; // ME_49928C8001B8 

: ME_49928C900220
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_456EB3E10177' '456EA56002BF.pas.ms.script' // EntityBase
 ;

ref; // ME_49928C900220 

: ME_499297BF035B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_46835B4001A4' '48FD8B2702F6.pas.ms.script' // TnsTreeStruct
 ;

ref; // ME_499297BF035B 

: ME_499297E30231
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_499297E30231 

: ME_499297F800ED
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_47F25BC801DB' '47D0E1500033.pas.ms.script' // vcmBase
 ;

ref; // ME_499297F800ED 

FORWARD ME_49254B6F0325

: ME_4992981D03AD
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target HWL ME_49254B6F0325 // TdeTips
 ;

ref; // ME_4992981D03AD 

: ME_49929A8F0396
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_4909AEB00352' '48FD8B2702F6.pas.ms.script' // TnsINodeWrap
 ;

ref; // ME_49929A8F0396 

: ME_49929ABF03AB
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_47F9C7C9010E' '4F4B8FA60272.pas.ms.script' // nsExternalObjectPrim
 ;

ref; // ME_49929ABF03AB 

: ME_49929C12013C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4992891800CF // TnsStartupTips
 ;
 : Target WL 'ME_48FF569700F6' '47F2170002B2.pas.ms.script' // StringRoutines
 ;

ref; // ME_49929C12013C 

: ME_4991C74701F8_ME_4992891800CF
 : Original WL 'ME_4991C74701F8' '4991C6930254.pas.ms.script' // TipCaption
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_4991C74701F8_ME_4992891800CF TipCaption

: ME_4991C75C00D5_ME_4992891800CF
 : Original WL 'ME_4991C75C00D5' '4991C6930254.pas.ms.script' // DontShow
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_4991C75C00D5_ME_4992891800CF DontShow

: ME_4991C7680235_ME_4992891800CF
 : Original WL 'ME_4991C7680235' '4991C6930254.pas.ms.script' // Next
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4991C7680235_ME_4992891800CF Next

: ME_4991C76E02ED_ME_4992891800CF
 : Original WL 'ME_4991C76E02ED' '4991C6930254.pas.ms.script' // Prev
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4991C76E02ED_ME_4992891800CF Prev

: ME_4991C77601E9_ME_4992891800CF
 : Original WL 'ME_4991C77601E9' '4991C6930254.pas.ms.script' // ShowDetails
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4991C77601E9_ME_4992891800CF ShowDetails

: ME_4991C78200E7_ME_4992891800CF
 : Original WL 'ME_4991C78200E7' '4991C6930254.pas.ms.script' // GotoWeb
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4991C78200E7_ME_4992891800CF GotoWeb

: ME_479731C50290_ME_4992891800CF
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_4992891800CF Cleanup

: ME_47EA4E9002C6_ME_4992891800CF
 : Original WL 'ME_47EA4E9002C6' '47EA4BB502F9.pas.ms.script' // FinishDataUpdate
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47EA4E9002C6_ME_4992891800CF FinishDataUpdate

: ME_4992891800CF
 CONST UID '4992891800CF'
 CONST Name 'TnsStartupTips'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Советик дня' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_491D560F01F4 // DayTips
 ;
 : Inherits
   Seq: ( WL 'ME_47BC391D0259' '47913B47006E.pas.ms.script' // Tl3SimpleObject
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_47EA4BEF0140' '47EA4BB502F9.pas.ms.script' // afwApplicationDataUpdate
 WL 'ME_4991C6FF00C7' '4991C6930254.pas.ms.script' // InsStartupTips
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_499289CF03A7 // f_TipsTree
 HWL ME_499289E00058 // f_CurrentNode
 HWL ME_49928A3E007F // f_DontShow
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_49928A97027C // Create
 HWL ME_49928AA3039A // MakePrim
 HWL ME_4993F1F80032 // Make
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4991C74701F8_ME_4992891800CF // TipCaption
 ME_4991C75C00D5_ME_4992891800CF // DontShow
 ME_4991C7680235_ME_4992891800CF // Next
 ME_4991C76E02ED_ME_4992891800CF // Prev
 ME_4991C77601E9_ME_4992891800CF // ShowDetails
 ME_4991C78200E7_ME_4992891800CF // GotoWeb
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_4992891800CF // Cleanup
 ME_47EA4E9002C6_ME_4992891800CF // FinishDataUpdate
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_49928AD80373 // StdRes
 ME_49928AEE0176 // DataAdapter
 ME_49928B1500D8 // afwFacade
 ME_49928B1D0064 // nsConst
 ME_49928C4501B7 // NodeBase
 ME_49928C59007D // NodeIndexPath
 ME_49928C8001B8 // Document
 ME_49928C900220 // EntityBase
 ME_499297BF035B // TnsTreeStruct
 ME_499297E30231 // SysUtils
 ME_499297F800ED // vcmBase
 ME_4992981D03AD // TdeTips
 ME_49929A8F0396 // TnsINodeWrap
 ME_49929ABF03AB // nsExternalObjectPrim
 ME_49929C12013C // StringRoutines
 )
 ; // Dependencies
 CONST "author" 'Лукьянец Р.В.'
 CONST "no hands" true
 CONST "started" '2008/02/14 13:46:41'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\DayTips\nsStartupTips.pas'
 CONST extprop:rc:SelfName 'StartupTips'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'nsStartupTips'

ref; // ME_4992891800CF TnsStartupTips

: ME_4B1E714A0125_ME_49254B6F0325
 : Original WL 'ME_4B1E714A0125' '4C6ABB3201AC.pas.ms.script' // DefaultDocType
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4B1E714A0125_ME_49254B6F0325 DefaultDocType

: ME_49254B6F0325
 CONST UID '49254B6F0325'
 CONST Name 'TdeTips'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_491D560F01F4 // DayTips
 ;
 : Inherits
   Seq: ( WL 'ME_4B1E70D20312' '492543E30278.pas.ms.script' // TdeCommonDiction
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4B1E714A0125_ME_49254B6F0325 // DefaultDocType
 )
 ; // Overridden
 CONST "author" 'Люлин А.В.'
 CONST "no hands" true
 CONST "started" '08.12.2009 18:37'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\DayTips\deTips.pas'
 CONST extprop:rc:SelfName 'deTips'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'deTips'

ref; // ME_49254B6F0325 TdeTips

FORWARD ME_4CE53CC80300

: ME_4CE53E7702F2
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4CE53CC80300 // TnsTipsDocumentContainer
 ;
 : Target WL 'ME_483E708900B4' '47C695A10172.pas.ms.script' // Clipboard Formats
 ;

ref; // ME_4CE53E7702F2 

: ME_4CE53F7A02A1
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4CE53CC80300 // TnsTipsDocumentContainer
 ;
 : Target WL 'ME_46A5B0060013' '4677FBA70343.pas.ms.script' // IStream
 ;

ref; // ME_4CE53F7A02A1 

: ME_4E69E09C0253
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4CE53CC80300 // TnsTipsDocumentContainer
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_4E69E09C0253 

: ME_47F27DA80172_ME_4CE53CC80300
 : Original WL 'ME_47F27DA80172' '47F086170200.pas.ms.script' // GetDocument
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47F27DA80172_ME_4CE53CC80300 GetDocument

: ME_4B1FBF87020C_ME_4CE53CC80300
 : Original WL 'ME_4B1FBF87020C' '4C6A7BA001A5.pas.ms.script' // AfterCreate
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4B1FBF87020C_ME_4CE53CC80300 AfterCreate

: ME_4CE53CC80300
 CONST UID '4CE53CC80300'
 CONST Name 'TnsTipsDocumentContainer'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Контейнер документа для советов дня' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_491D560F01F4 // DayTips
 ;
 : Inherits
   Seq: ( WL 'ME_4680E83D00C8' '4680E826036D.pas.ms.script' // TeeDocumentContainer
 WL 'ME_4C6A955F00D6' '4C6A7BA001A5.pas.ms.script' // nsDocumentContainer
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_47F27DA80172_ME_4CE53CC80300 // GetDocument
 ME_4B1FBF87020C_ME_4CE53CC80300 // AfterCreate
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_4CE53E7702F2 // Clipboard Formats
 ME_4CE53F7A02A1 // IStream
 ME_4E69E09C0253 // String
 )
 ; // Dependencies
 CONST "author" 'Люлин А.В.'
 CONST "no hands" true
 CONST "started" '18.11.2010 17:49'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\DayTips\nsTipsDocumentContainer.pas'
 CONST extprop:rc:SelfName 'TipsDocumentContainer'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'nsTipsDocumentContainer'

ref; // ME_4CE53CC80300 TnsTipsDocumentContainer

: ME_491D560F01F4
 CONST UID '491D560F01F4'
 CONST Name 'DayTips'
 CONST Class class_Category
 : Stereotype st_ControllerUnit ;
 %SUMMARY 'Работа с советами дня' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_493FF75500F3' '493FF75500F3.pas.ms.script' // DayTips
 ;
 : Children
   Seq: ( WL 'ME_491D56370182' '491D56370182.pas.ms.script' // TdsTipsDocument
 WL 'ME_49254BC1019C' '49254BC1019C.pas.ms.script' // TdsTips
 WL 'ME_493D0AFD02F6' '493D0AFD02F6.pas.ms.script' // TsdsTips
 HWL ME_4992891800CF // TnsStartupTips
 HWL ME_49254B6F0325 // TdeTips
 HWL ME_4CE53CC80300 // TnsTipsDocumentContainer
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 WL 'ME_4423F94903C8' '4423F94903C8.pas.ms.script' // IO
 WL 'ME_456EA56002BF' '456EA56002BF.pas.ms.script' // BaseTypes
 WL 'ME_4570511E038A' '4570511E038A.pas.ms.script' // Document
 WL 'ME_457450470167' '457450470167.pas.ms.script' // DynamicTree
 WL 'ME_4677FBA70343' '4677FBA70343.pas.ms.script' // l3Interfaces
 WL 'ME_4680E826036D' '4680E826036D.pas.ms.script' // eeDocumentContainer
 WL 'ME_4682595B0268' '4682595B0268.pas.ms.script' // l3TreeInterfaces
 WL 'ME_47750CE700D0' '47750CE700D0.pas.ms.script' // afwFacade
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_47C5207602D1' '47C5207602D1.pas.ms.script' // nevTools
 WL 'ME_47C695A10172' '47C695A10172.pas.ms.script' // evTypes
 WL 'ME_47D0E1500033' '47D0E1500033.pas.ms.script' // Implementation
 WL 'ME_47EA4BB502F9' '47EA4BB502F9.pas.ms.script' // afwMixIns
 WL 'ME_47EA50050263' '47EA50050263.pas.ms.script' // BaseDocument
 WL 'ME_47F2170002B2' '47F2170002B2.pas.ms.script' // nsTypes
 WL 'ME_47F260DC003F' '47F260DC003F.pas.ms.script' // ns
 WL 'ME_48F747EC0073' '48F747EC0073.pas.ms.script' // Common
 WL 'ME_48FD8B2702F6' '48FD8B2702F6.pas.ms.script' // Tree
 WL 'ME_4906F67500B0' '4906F67500B0.pas.ms.script' // DayTipsData
 WL 'ME_491B305A0096' '491B305A0096.pas.ms.script' // DocumentAndListInterfaces
 WL 'ME_492540AF02CD' '492540AF02CD.pas.ms.script' // CommonDictionInterfaces
 WL 'ME_492543E30278' '492543E30278.pas.ms.script' // CommonDiction
 WL 'ME_4979D3B10102' '4979D3B10102.pas.ms.script' // Diction
 WL 'ME_4991C6930254' '4991C6930254.pas.ms.script' // DayTipsInterfaces
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_4B1FC2FF03CD' '4B1FC2FF03CD.pas.ms.script' // DocumentInterfaces
 WL 'ME_4C6A7BA001A5' '4C6A7BA001A5.pas.ms.script' // F1DocumentContainers
 WL 'ME_4F4B8FA60272' '4F4B8FA60272.pas.ms.script' // Implementation
 WL 'ME_521C9DA50125' '521C9DA50125.pas.ms.script' // Application Resources
 )
 ; // Depends

ref; // ME_491D560F01F4 DayTips
