// TdsSynchroView 4922B4F803AC ViewAreaControllerImp Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4922B4F803AC

ME ME_497897CE0015
 MEPROP UID '497897CE0015'
 MEPROP Name 'UseCaseControllerType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_lnk
 MELINK Parent HWL ME_4922B4F803AC // TdsSynchroView
 ;
 MELINK Target WL 'ME_4922A6C502D3' '4D1B444C015E.ms.model.script' // IsdsList
 ;

ENDME // ME_497897CE0015 UseCaseControllerType

ME ME_4922B57101E1
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4922B4F803AC // TdsSynchroView
 ;
 MELINK Target WL? 'ME_47877EB202FB' // SysUtils
 ;

ENDME // ME_4922B57101E1 

ME ME_29FB34EB69B7_ME_4922B4F803AC
 MELINK Original WL 'ME_29FB34EB69B7' '4D1B444C015E.ms.model.script' // IsAnnotationActive
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_29FB34EB69B7_ME_4922B4F803AC IsAnnotationActive

ME ME_373C115F3AFE_ME_4922B4F803AC
 MELINK Original WL 'ME_373C115F3AFE' '4D1B444C015E.ms.model.script' // IsRelatedDocActive
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_373C115F3AFE_ME_4922B4F803AC IsRelatedDocActive

ME ME_3C61AE5A0421_ME_4922B4F803AC
 MELINK Original WL 'ME_3C61AE5A0421' '4D1B444C015E.ms.model.script' // HasAnnotation
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_3C61AE5A0421_ME_4922B4F803AC HasAnnotation

ME ME_42EFA4B2ADEC_ME_4922B4F803AC
 MELINK Original WL 'ME_42EFA4B2ADEC' '4D1B444C015E.ms.model.script' // IsSimilarDocumentsActive
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_42EFA4B2ADEC_ME_4922B4F803AC IsSimilarDocumentsActive

ME ME_47ECD5280007_ME_4922B4F803AC
 MELINK Original WL 'ME_47ECD5280007' '4922BFA000DD.ms.model.script' // OpenDocument
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_47ECD5280007_ME_4922B4F803AC OpenDocument

ME ME_47ECD54803CB_ME_4922B4F803AC
 MELINK Original WL 'ME_47ECD54803CB' '4922BFA000DD.ms.model.script' // HasDocument
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_47ECD54803CB_ME_4922B4F803AC HasDocument

ME ME_47ECD5490012_ME_4922B4F803AC
 MELINK Original WL 'ME_47ECD5490012' '4922BFA000DD.ms.model.script' // IsDocumentActive
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_47ECD5490012_ME_4922B4F803AC IsDocumentActive

ME ME_47F08A0E035F_ME_4922B4F803AC
 MELINK Original WL 'ME_47F08A0E035F' '4922BFA000DD.ms.model.script' // HasAttributes
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_47F08A0E035F_ME_4922B4F803AC HasAttributes

ME ME_47F08A2A03E6_ME_4922B4F803AC
 MELINK Original WL 'ME_47F08A2A03E6' '4922BFA000DD.ms.model.script' // IsAttributesActive
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_47F08A2A03E6_ME_4922B4F803AC IsAttributesActive

ME ME_47F08A7F0108_ME_4922B4F803AC
 MELINK Original WL 'ME_47F08A7F0108' '4922BFA000DD.ms.model.script' // OpenAttributes
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_47F08A7F0108_ME_4922B4F803AC OpenAttributes

ME ME_4922AD950294_ME_4922B4F803AC
 MELINK Original WL 'ME_4922AD950294' '4D1B444C015E.ms.model.script' // UserCRListInfo
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_4922AD950294_ME_4922B4F803AC UserCRListInfo

ME ME_49BAD288AA03_ME_4922B4F803AC
 MELINK Original WL 'ME_49BAD288AA03' '4D1B444C015E.ms.model.script' // OpenUserCR2
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_49BAD288AA03_ME_4922B4F803AC OpenUserCR2

ME ME_75D79769A7B5_ME_4922B4F803AC
 MELINK Original WL 'ME_75D79769A7B5' '4D1B444C015E.ms.model.script' // OpenRelatedDoc
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_75D79769A7B5_ME_4922B4F803AC OpenRelatedDoc

ME ME_9CD4919A8B42_ME_4922B4F803AC
 MELINK Original WL 'ME_9CD4919A8B42' '4D1B444C015E.ms.model.script' // HasUserCR1
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_9CD4919A8B42_ME_4922B4F803AC HasUserCR1

ME ME_AC36781982C2_ME_4922B4F803AC
 MELINK Original WL 'ME_AC36781982C2' '4D1B444C015E.ms.model.script' // HasRelatedDoc
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_AC36781982C2_ME_4922B4F803AC HasRelatedDoc

ME ME_ACF8AED74764_ME_4922B4F803AC
 MELINK Original WL 'ME_ACF8AED74764' '4D1B444C015E.ms.model.script' // IsUserCR2Active
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_ACF8AED74764_ME_4922B4F803AC IsUserCR2Active

ME ME_AF7C3B1F66A1_ME_4922B4F803AC
 MELINK Original WL 'ME_AF7C3B1F66A1' '4D1B444C015E.ms.model.script' // IsUserCR1Active
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_AF7C3B1F66A1_ME_4922B4F803AC IsUserCR1Active

ME ME_B3FF3DCB306E_ME_4922B4F803AC
 MELINK Original WL 'ME_B3FF3DCB306E' '4D1B444C015E.ms.model.script' // HasSimilarDocuments
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_B3FF3DCB306E_ME_4922B4F803AC HasSimilarDocuments

ME ME_B92D4E5C4AF7_ME_4922B4F803AC
 MELINK Original WL 'ME_B92D4E5C4AF7' '4D1B444C015E.ms.model.script' // OpenUserCR1
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_B92D4E5C4AF7_ME_4922B4F803AC OpenUserCR1

ME ME_C90DF8D59396_ME_4922B4F803AC
 MELINK Original WL 'ME_C90DF8D59396' '4D1B444C015E.ms.model.script' // OpenAnnotation
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_C90DF8D59396_ME_4922B4F803AC OpenAnnotation

ME ME_DF69147C5AF9_ME_4922B4F803AC
 MELINK Original WL 'ME_DF69147C5AF9' '4D1B444C015E.ms.model.script' // HasUserCR2
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_DF69147C5AF9_ME_4922B4F803AC HasUserCR2

ME ME_EB3722A70D75_ME_4922B4F803AC
 MELINK Original WL 'ME_EB3722A70D75' '4D1B444C015E.ms.model.script' // OpenSimilarDocuments
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_EB3722A70D75_ME_4922B4F803AC OpenSimilarDocuments

%%ImplementedBy ME_4922AC8B022E ME_4922B4F803AC

%%InheritedBy ME_5017EAF4027D ME_4922B4F803AC

ME ME_4922B4F803AC
 MEPROP UID '4922B4F803AC'
 MEPROP Name 'TdsSynchroView'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_ViewAreaControllerImp ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Бизнес объект формы "fcSynchroView"' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL? 'ME_47EA5024034B' // ListDataSources
 ;
 MELIST Inherits
   Seq: ( WL? 'ME_5017EAF4027D' // vcmFormDataSourcePrimWithFlexUseCaseControllerType
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_4922AC8B022E' '4D1B444C015E.ms.model.script' // IdsSynchroView
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_497897CE0015 // UseCaseControllerType
 )
 ; // Attributes
 MELIST Implemented
   Seq: ( ME_29FB34EB69B7_ME_4922B4F803AC // IsAnnotationActive
 ME_373C115F3AFE_ME_4922B4F803AC // IsRelatedDocActive
 ME_3C61AE5A0421_ME_4922B4F803AC // HasAnnotation
 ME_42EFA4B2ADEC_ME_4922B4F803AC // IsSimilarDocumentsActive
 ME_47ECD5280007_ME_4922B4F803AC // OpenDocument
 ME_47ECD54803CB_ME_4922B4F803AC // HasDocument
 ME_47ECD5490012_ME_4922B4F803AC // IsDocumentActive
 ME_47F08A0E035F_ME_4922B4F803AC // HasAttributes
 ME_47F08A2A03E6_ME_4922B4F803AC // IsAttributesActive
 ME_47F08A7F0108_ME_4922B4F803AC // OpenAttributes
 ME_4922AD950294_ME_4922B4F803AC // UserCRListInfo
 ME_49BAD288AA03_ME_4922B4F803AC // OpenUserCR2
 ME_75D79769A7B5_ME_4922B4F803AC // OpenRelatedDoc
 ME_9CD4919A8B42_ME_4922B4F803AC // HasUserCR1
 ME_AC36781982C2_ME_4922B4F803AC // HasRelatedDoc
 ME_ACF8AED74764_ME_4922B4F803AC // IsUserCR2Active
 ME_AF7C3B1F66A1_ME_4922B4F803AC // IsUserCR1Active
 ME_B3FF3DCB306E_ME_4922B4F803AC // HasSimilarDocuments
 ME_B92D4E5C4AF7_ME_4922B4F803AC // OpenUserCR1
 ME_C90DF8D59396_ME_4922B4F803AC // OpenAnnotation
 ME_DF69147C5AF9_ME_4922B4F803AC // HasUserCR2
 ME_EB3722A70D75_ME_4922B4F803AC // OpenSimilarDocuments
 )
 ; // Implemented
 MELIST Dependencies
   Seq: ( ME_4922B57101E1 // SysUtils
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "author" 'Морозов М.А'
 UP "no hands" true
 UP "started" '11.08.2005 14.48'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Business\List\dsSynchroView.pas'
 UP extprop:rc:SelfName 'dsSynchroView'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'dsSynchroView'

ENDME // ME_4922B4F803AC TdsSynchroView
