// sdsCommonDiction 4936B666032A UseCaseControllerImp Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4936B666032A

: ME_4947AD90005D
 CONST UID '4947AD90005D'
 CONST Name 'InitDataType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_47EA0784000D' '4B1FC2FF03CD.pas.ms.script' // IdeDocInfo
 ;

ref; // ME_4947AD90005D InitDataType

: ME_4936B8AC00A7
 CONST Name 'aSource'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47EA0784000D' '4B1FC2FF03CD.pas.ms.script' // IdeDocInfo
 ;

ref; // ME_4936B8AC00A7 aSource

: ME_4936B89C037F
 CONST UID '4936B89C037F'
 CONST Name 'MakeDocInfo'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_4947AD8201F6' '492540AF02CD.pas.ms.script' // IdeCommonDiction
 ;
 : Parameters
   Seq: ( ME_4936B8AC00A7 // aSource
 )
 ; // Parameters

ref; // ME_4936B89C037F MakeDocInfo

: ME_4936B8BC00E9
 CONST Name 'aDoc'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47EA0784000D' '4B1FC2FF03CD.pas.ms.script' // IdeDocInfo
 ;

ref; // ME_4936B8BC00E9 aDoc

: ME_4936B8B600F2
 CONST UID '4936B8B600F2'
 CONST Name 'BeforeAssignDocument'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Parameters
   Seq: ( ME_4936B8BC00E9 // aDoc
 )
 ; // Parameters

ref; // ME_4936B8B600F2 BeforeAssignDocument

: ME_4936B8C20119
 CONST UID '4936B8C20119'
 CONST Name 'AfterAssignDocument'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;

ref; // ME_4936B8C20119 AfterAssignDocument

: ME_4936BA0D0286
 CONST UID '4936BA0D0286'
 CONST Name 'MakeContents'
 CONST Class class_Operation
 %SUMMARY 'Создаёт область оглавления' ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_4925416003BC' '492540AF02CD.pas.ms.script' // IdsCommonDiction
 ;

ref; // ME_4936BA0D0286 MakeContents

: ME_4936B73F0319
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_4936B73F0319 

: ME_4936B76801B0
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_49312C5F0078' '47D0E1500033.pas.ms.script' // vcmFormSetRefreshParams
 ;

ref; // ME_4936B76801B0 

: ME_4936B7A002D6
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_4936B78E0024' '492543E30278.pas.ms.script' // dCommonDiction
 ;

ref; // ME_4936B7A002D6 

: ME_4936B7B702D7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_47752AF90375' '47750CE700D0.pas.ms.script' // afwFacade
 ;

ref; // ME_4936B7B702D7 

: ME_4936B7DA0343
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_492545F700BF' '492540AF02CD.pas.ms.script' // IdCommonDiction
 ;

ref; // ME_4936B7DA0343 

: ME_4936B7FD01DF
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_45EEB6520191' '4570511E038A.pas.ms.script' // Document
 ;

ref; // ME_4936B7FD01DF 

: ME_4936BC2F0177
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_4773D64E036C' '47913B47006E.pas.ms.script' // l3Base
 ;

ref; // ME_4936BC2F0177 

: ME_4B220EC30017
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_4B220E9B0348' '492543E30278.pas.ms.script' // TdCommonDiction
 ;

ref; // ME_4B220EC30017 

: ME_4D81DFD70116
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_4923F66E0262' '4923F66E0262.pas.ms.script' // TdsSaveLoad
 ;

ref; // ME_4D81DFD70116 

: ME_4D81FC950354
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4936B666032A // sdsCommonDiction
 ;
 : Target WL 'ME_4D7A7ADE0122' '4D7A7ADE0122.pas.ms.script' // TdsChild
 ;

ref; // ME_4D81FC950354 

: ME_4B0EB10C02A3_ME_4936B666032A
 : Original WL 'ME_4B0EB10C02A3' '492540AF02CD.pas.ms.script' // CurrentNode
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4B0EB10C02A3_ME_4936B666032A CurrentNode

: ME_4B0EB7B10270_ME_4936B666032A
 : Original WL 'ME_4B0EB7B10270' '492540AF02CD.pas.ms.script' // deCommonDiction
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4B0EB7B10270_ME_4936B666032A deCommonDiction

: ME_4D78AFC702D5_ME_4936B666032A
 : Original WL 'ME_4D78AFC702D5' '492540AF02CD.pas.ms.script' // dsSaveLoad
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_4D78AFC702D5_ME_4936B666032A dsSaveLoad

: ME_4D7A7A9D016D_ME_4936B666032A
 : Original WL 'ME_4D7A7A9D016D' '492540AF02CD.pas.ms.script' // dsChild
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_4D7A7A9D016D_ME_4936B666032A dsChild

: ME_500D34960277_ME_4936B666032A
 : Original WL 'ME_500D34960277' '492540AF02CD.pas.ms.script' // dsContents
 ;
 CONST OpKind opkind_Implemented
 CONST "Need Has" false
 CONST "is reference" true
 CONST "pm" true
ref; // ME_500D34960277_ME_4936B666032A dsContents

: ME_47F37DF001FE_ME_4936B666032A
 : Original WL 'ME_47F37DF001FE' '47D0E1500033.pas.ms.script' // DataExchange
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47F37DF001FE_ME_4936B666032A DataExchange

: ME_4925B9370022_ME_4936B666032A
 : Original WL 'ME_4925B9370022' '47EA106D035E.pas.ms.script' // DoChangeDocument
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4925B9370022_ME_4936B666032A DoChangeDocument

: ME_49352CEF0222_ME_4936B666032A
 : Original WL 'ME_49352CEF0222' '47F0849400D0.pas.ms.script' // GetHasAttributes
 ;
 CONST OpKind opkind_Overridden
ref; // ME_49352CEF0222_ME_4936B666032A GetHasAttributes

: ME_4A60B23E00C3_ME_4936B666032A
 : Original WL 'ME_4A60B23E00C3' '47BB24D30205.pas.ms.script' // COMQueryInterface
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4A60B23E00C3_ME_4936B666032A COMQueryInterface

: ME_55C1DD070354_ME_4936B666032A
 : Original WL 'ME_55C1DD070354' '47D0E1500033.pas.ms.script' // GetDataForClone
 ;
 CONST OpKind opkind_Overridden
ref; // ME_55C1DD070354_ME_4936B666032A GetDataForClone

: ME_4936B666032A
 CONST UID '4936B666032A'
 CONST Name 'sdsCommonDiction'
 CONST Class class_Class
 : Stereotype st_UseCaseControllerImp ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Бизнес объект сборки "Обобщенный словарь"' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent WL 'ME_492543E30278' '492543E30278.pas.ms.script' // CommonDiction
 ;
 : Inherits
   Seq: ( WL 'ME_47F0849400D0' '47F0849400D0.pas.ms.script' // sdsBaseDocumentWithAttributes
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4936823400AE' '492540AF02CD.pas.ms.script' // IsdsCommonDiction
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_4947AD90005D // InitDataType
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_4936B89C037F // MakeDocInfo
 HWL ME_4936B8B600F2 // BeforeAssignDocument
 HWL ME_4936B8C20119 // AfterAssignDocument
 HWL ME_4936BA0D0286 // MakeContents
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4B0EB10C02A3_ME_4936B666032A // CurrentNode
 ME_4B0EB7B10270_ME_4936B666032A // deCommonDiction
 ME_4D78AFC702D5_ME_4936B666032A // dsSaveLoad
 ME_4D7A7A9D016D_ME_4936B666032A // dsChild
 ME_500D34960277_ME_4936B666032A // dsContents
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_47F37DF001FE_ME_4936B666032A // DataExchange
 ME_4925B9370022_ME_4936B666032A // DoChangeDocument
 ME_49352CEF0222_ME_4936B666032A // GetHasAttributes
 ME_4A60B23E00C3_ME_4936B666032A // COMQueryInterface
 ME_55C1DD070354_ME_4936B666032A // GetDataForClone
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_4936B73F0319 // SysUtils
 ME_4936B76801B0 // vcmFormSetRefreshParams
 ME_4936B7A002D6 // dCommonDiction
 ME_4936B7B702D7 // afwFacade
 ME_4936B7DA0343 // IdCommonDiction
 ME_4936B7FD01DF // Document
 ME_4936BC2F0177 // l3Base
 ME_4B220EC30017 // TdCommonDiction
 ME_4D81DFD70116 // TdsSaveLoad
 ME_4D81FC950354 // TdsChild
 )
 ; // Dependencies
 CONST "author" 'Лукьянец Р.В.'
 CONST "no hands" true
 CONST "started" '2008/03/05 09:35:14'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\CommonDiction\sdsCommonDiction.imp.pas'
 CONST extprop:pas:TypeName '_sdsCommonDiction_'
 CONST extprop:pas:UnitName 'sdsCommonDiction.imp'

ref; // ME_4936B666032A sdsCommonDiction
