// LegalDomain 49549627008C VCMSubsystem Category

INCLUDE 'ElementsRTTI.ms.dict'

: ME_49549627008C
 CONST UID '49549627008C'
 CONST Name 'LegalDomain'
 CONST Class class_Category
 : Stereotype st_VCMSubsystem ;
 %SUMMARY '"Предментая область"' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent WL 'ME_498B35810374' '498B35810374.pas.ms.script' // F1 Базовые определения предметной области
 ;
 : Children
   Seq: ( WL 'ME_47E9EEC60260' '47E9EEC60260.pas.ms.script' // Model
 WL 'ME_4F4B8F830023' '4F4B8F830023.pas.ms.script' // ExternalObjects
 WL 'ME_4677FF4B0036' '4677FF4B0036.pas.ms.script' // Data
 WL 'ME_4954F58900E8' '4954F58900E8.pas.ms.script' // List
 WL 'ME_4EEA091C01B4' '4EEA091C01B4.pas.ms.script' // View$Prim
 WL 'ME_4EAAE543007F' '4EAAE543007F.pas.ms.script' // View
 WL 'ME_493FAECB025F' '493FAECB025F.pas.ms.script' // Tree
 WL 'ME_4954FAA00232' '4954FAA00232.pas.ms.script' // Search
 WL 'ME_51DD5AB6022D' '51DD5AB6022D.pas.ms.script' // Components
 WL 'ME_4CEBA36A00AA' '4CEBA36A00AA.pas.ms.script' // f1DocumentTagsImplementation
 WL 'ME_53BA5A5D03A0' '53BA5A5D03A0.pas.ms.script' // TabInterface
 WL 'ME_55B62380030A' '55B62380030A.pas.ms.script' // Logging
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_447878770121' '447878770121.pas.ms.script' // GCI
 WL 'ME_456EA3D2031C' '456EA3D2031C.pas.ms.script' // GblAdapterLib
 WL 'ME_4677E16A022A' '4677E16A022A.pas.ms.script' // K2
 WL 'ME_4677E18600C2' '4677E18600C2.pas.ms.script' // dd
 WL 'ME_467A75D90346' '467A75D90346.pas.ms.script' // VT
 WL 'ME_467A8734039C' '467A8734039C.pas.ms.script' // EVD
 WL 'ME_4680E7D50168' '4680E7D50168.pas.ms.script' // Everest Engine
 WL 'ME_4684F91300DD' '4684F91300DD.pas.ms.script' // Vcl
 WL 'ME_47540FF802AC' '47540FF802AC.pas.ms.script' // Orpheus
 WL 'ME_4790B4F00236' '4790B4F00236.pas.ms.script' // AFW
 WL 'ME_4790C3B8021E' '4790C3B8021E.pas.ms.script' // VCM
 WL 'ME_4790D09A0378' '4790D09A0378.pas.ms.script' // L3
 WL 'ME_4797632D0273' '4797632D0273.pas.ms.script' // Everest
 WL 'ME_481EF5C4020D' '481EF5C4020D.pas.ms.script' // Оболочка
 WL 'ME_48561E5A01F7' '48561E5A01F7.pas.ms.script' // Специальные версии и возможности
 WL 'ME_48EEE54C0072' '48EEE54C0072.pas.ms.script' // EverestCommon
 WL 'ME_490838AA02D0' '490838AA02D0.pas.ms.script' // Nemesis
 WL 'ME_4954C00703D0' '4954C00703D0.pas.ms.script' // OfficeLike
 WL 'ME_49B1511700CA' '49B1511700CA.pas.ms.script' // Shared Delphi Core
 WL 'ME_4B63155B0328' '4B63155B0328.pas.ms.script' // MDProcess$ForDelphi
 WL 'ME_4D4927B5008B' '4D4927B5008B.pas.ms.script' // VT$Core
 WL 'ME_4E13416D0227' '4E13416D0227.pas.ms.script' // VCM$Visual
 WL 'ME_4E2F0E1B03BB' '4E2F0E1B03BB.pas.ms.script' // L3$Domain
 WL 'ME_4E57BF810311' '4E57BF810311.pas.ms.script' // Требования к системным библиотекам для F1
 WL 'ME_4E5BC50E02E1' '4E5BC50E02E1.pas.ms.script' // Shared Delphi Требования к низкоуровневым библиотекам
 WL 'ME_54CF97B10370' '54CF97B10370.pas.ms.script' // ScriptEngine$Core
 WL 'ME_54F5AAED0073' '54F5AAED0073.pas.ms.script' // L3$Visual
 WL 'ME_562E251101C2' '562E251101C2.pas.ms.script' // Shared Delphi Rtl
 )
 ; // Depends
 CONST intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis'

ref; // ME_49549627008C LegalDomain
