// PrimListInfo 497DEC900012 VCMForm Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_497DEC900012

FORWARD ME_4B14E32102A2

ME ME_4B14E37502D7
 MEPROP Name 'aList'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEDB730265' '45700BFD0251.ms.model.script' // DynList
 ;

ENDME // ME_4B14E37502D7 aList

ME ME_4B14E35A0092
 MEPROP UID '4B14E35A0092'
 MEPROP Name 'Log'
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4B14E32102A2 // TnsListReferenceActivateEvent
 ;
 MELIST Parameters
   Seq: ( ME_4B14E37502D7 // aList
 )
 ; // Parameters

ENDME // ME_4B14E35A0092 Log

ME ME_4B14E35202A2
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B14E32102A2 // TnsListReferenceActivateEvent
 ;
 MELINK Target WL 'ME_45ED58FF0201' '45ED58CF03E6.ms.model.script' // LogEvent
 ;

ENDME // ME_4B14E35202A2 

ME ME_4B14E32102A2
 MEPROP UID '4B14E32102A2'
 MEPROP Name 'TnsListReferenceActivateEvent'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4B0A6109010C' '4B0A60DF01F2.ms.model.script' // TnsLogEvent
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_4B14E35A0092 // Log
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_4B14E35202A2 // LogEvent
 )
 ; // Dependencies
 UP extprop:rc:SelfName 'ListReferenceActivateEvent'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_4B14E32102A2 TnsListReferenceActivateEvent

ME ME_51C19D3D0008
 MEPROP UID '51C19D3D0008'
 MEPROP Name 'ListInfoViewer'
 MEPROP Class class_Class
 MELINK Stereotype st_Control ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 UP "ControlClass" 'TnscEditor'
 UP "pm" true
 UP "put to dfm" false

ENDME // ME_51C19D3D0008 ListInfoViewer

ME ME_51C19D6F006C
 MEPROP UID '51C19D6F006C'
 MEPROP Name 'TextSource'
 MEPROP Class class_Class
 MELINK Stereotype st_Component ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 UP "ComponentClass" 'TnscTextSource'
 UP "need Caption" false
 UP "pm" true
 UP "put to dfm" false

ENDME // ME_51C19D6F006C TextSource

ME ME_497DECC40277
 MEPROP UID '497DECC40277'
 MEPROP Name 'dsListInfo'
 MEPROP Class class_Attribute
 MELINK Stereotype st_ViewArea::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_lnk
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_49005E89009D' '4D1B444C015E.ms.model.script' // IdsListInfo
 ;

ENDME // ME_497DECC40277 dsListInfo

ME ME_49AE653900A2
 MEPROP UID '49AE653900A2'
 MEPROP Name 'sdsListPrim'
 MEPROP Class class_Attribute
 MELINK Stereotype st_UseCase::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_lnk
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_49AE63CF0130' '4D1B444C015E.ms.model.script' // IsdsListPrim
 ;

ENDME // ME_49AE653900A2 sdsListPrim

FORWARD ME_4C88CF0C0337

ME ME_4C88CF1C00AC
 MEPROP UID '4C88CF1C00AC'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4C88CF0C0337 // MakePreview
 ;
 MELINK Target WL 'ME_473D8DF50230' '467823B7002C.ms.model.script' // IafwComplexDocumentPreview
 ;

ENDME // ME_4C88CF1C00AC DoIt

ME ME_4C88CF0C0337
 MEPROP UID '4C88CF0C0337'
 MEPROP Name 'MakePreview'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELIST Operations
   Seq: ( HWL ME_4C88CF1C00AC // DoIt
 )
 ; // Operations

ENDME // ME_4C88CF0C0337 MakePreview

ME ME_51C1A3A902F1
 MEPROP UID '51C1A3A902F1'
 MEPROP Name 'TextSourceMakeDocumentContainer'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELIST Inherits
   Seq: ( WL 'ME_51C1A49003E5' '47542EA70394.ms.model.script' // TeeMakeDocumentContainerEvent
 )
 ; // Inherits

ENDME // ME_51C1A3A902F1 TextSourceMakeDocumentContainer

ME ME_4AF8599E02D0
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_4AF8597D0271' '4A9807DB01A5.ms.model.script' // Filters
 ;

ENDME // ME_4AF8599E02D0 

ME ME_4B14E3290380
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target HWL ME_4B14E32102A2 // TnsListReferenceActivateEvent
 ;

ENDME // ME_4B14E3290380 

ME ME_4BD6B869004D
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_4AE836C303BC' '4F71AD0E01FE.ms.model.script' // Switcher$SetCaption
 ;

ENDME // ME_4BD6B869004D 

ME ME_51C2B1A10186
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_4A4DE48C0344' '4A4DE16302A2.ms.model.script' // k2Prim
 ;

ENDME // ME_51C2B1A10186 

ME ME_51C2B22D0030
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_47AB1FDE03E4' '47913B47006E.ms.model.script' // l3Memory
 ;

ENDME // ME_51C2B22D0030 

ME ME_51C2B2640113
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_47878E0E0191' '54B90AC6014B.ms.model.script' // l3String
 ;

ENDME // ME_51C2B2640113 

ME ME_51C2B2A901D0
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_483E708900B4' '47C695A10172.ms.model.script' // Clipboard Formats
 ;

ENDME // ME_51C2B2A901D0 

ME ME_51C2B2DA00C7
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_4773D64E036C' '47913B47006E.ms.model.script' // l3Base
 ;

ENDME // ME_51C2B2DA00C7 

ME ME_51C2B38200D6
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_4857B5260267' '48492FC0029D.ms.model.script' // Document
 ;

ENDME // ME_51C2B38200D6 

ME ME_51C2B3DE031E
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_48A41FF10094' '4AB0C3F60375.ms.model.script' // Windows
 ;

ENDME // ME_51C2B3DE031E 

ME ME_51C2B3E2000E
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_47ECBD5D03BB' '476F78840219.ms.model.script' // Msg Codes
 ;

ENDME // ME_51C2B3E2000E 

ME ME_51C2B42E030C
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_4954CA1102DB' '47F475660140.ms.model.script' // TnsListHAFMacroReplacer
 ;

ENDME // ME_51C2B42E030C 

ME ME_51C2B49E02FD
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_47CD3486030A' '47CD3441002F.ms.model.script' // TnevMiscMessages
 ;

ENDME // ME_51C2B49E02FD 

ME ME_51C2B4C30241
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_48FF55B500CC' '48F747EC0073.ms.model.script' // TDataAdapter
 ;

ENDME // ME_51C2B4C30241 

ME ME_51C2B4F800DF
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_47E11FC3021E' '4799D29F033F.ms.model.script' // Controls
 ;

ENDME // ME_51C2B4F800DF 

ME ME_51C2B4FB0151
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_47E13C6B0341' '4799D29F033F.ms.model.script' // Forms
 ;

ENDME // ME_51C2B4FB0151 

ME ME_51C2BB620335
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_485683750360' '48492FC0029D.ms.model.script' // TextPara
 ;

ENDME // ME_51C2BB620335 

ME ME_51C2EE400003
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_4954878B03CF' '47EA968D0155.ms.model.script' // TevFormatHAFMacroReplacer
 ;

ENDME // ME_51C2EE400003 

ME ME_531F1D13022C
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497DEC900012 // PrimListInfo
 ;
 MELINK Target WL 'ME_4678160E01BE' '47913B47006E.ms.model.script' // Ik2TagGenerator
 ;

ENDME // ME_531F1D13022C 

ME ME_497F16AC015A_ME_497DEC900012
 MELINK Original WL 'ME_497F16AC015A' '4A7C0BB70162.ms.model.script' // DoTabActivate
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_497F16AC015A_ME_497DEC900012 DoTabActivate

ME ME_4AF858F30202_ME_497DEC900012
 MELINK Original WL 'ME_4AF858F30202' '4A9807DB01A5.ms.model.script' // BecomeActive
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" false
 UP "AutoLock" false
 UP "LongProcess" false
 UP "Needs Broadcast" false
 UP "has states" false
 UP "is FormActivate" false
 UP "is query" true
 UP "no prefix" false
ENDME // ME_4AF858F30202_ME_497DEC900012 BecomeActive

ME ME_E4208250FA5A_ME_497DEC900012
 MELINK Original WL 'ME_E4208250FA5A' '4FFB165600FE.ms.model.script' // liListInfoQueryClose
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_E4208250FA5A_ME_497DEC900012 liListInfoQueryClose

ME ME_47D1602000C6_ME_497DEC900012
 MELINK Original WL 'ME_47D1602000C6' '4AB0997B00A2.ms.model.script' // Create
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47D1602000C6_ME_497DEC900012 Create

ME ME_497469C90140_ME_497DEC900012
 MELINK Original WL 'ME_497469C90140' '5000041101C8.ms.model.script' // NotifyDataSourceChanged
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_497469C90140_ME_497DEC900012 NotifyDataSourceChanged

ME ME_4A8E8F2E0195_ME_497DEC900012
 MELINK Original WL 'ME_4A8E8F2E0195' '5000041101C8.ms.model.script' // InitControls
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_4A8E8F2E0195_ME_497DEC900012 InitControls

ME ME_497DEC900012
 MEPROP UID '497DEC900012'
 MEPROP Name 'PrimListInfo'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_VCMForm ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Информация о списке' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_497DDB0A0168' '497DDB0A0168.ms.model.script' // List
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49525B34022A' '4AADF9450143.ms.model.script' // TvcmEntityForm
 WL 'ME_4FFB165600FE' '4FFB165600FE.ms.model.script' // ListInfoUserTypes
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_497F0F17036D' '4A7C0BB70162.ms.model.script' // PageControlNotification
 WL 'ME_4AF858E8029A' '4A9807DB01A5.ms.model.script' // ListInfo
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_51C19D3D0008 // ListInfoViewer
 HWL ME_51C19D6F006C // TextSource
 HWL ME_497DECC40277 // dsListInfo
 HWL ME_49AE653900A2 // sdsListPrim
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_4C88CF0C0337 // MakePreview
 HWL ME_51C1A3A902F1 // TextSourceMakeDocumentContainer
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_497F16AC015A_ME_497DEC900012 // DoTabActivate
 ME_4AF858F30202_ME_497DEC900012 // BecomeActive
 ME_E4208250FA5A_ME_497DEC900012 // liListInfoQueryClose
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_47D1602000C6_ME_497DEC900012 // Create
 ME_497469C90140_ME_497DEC900012 // NotifyDataSourceChanged
 ME_4A8E8F2E0195_ME_497DEC900012 // InitControls
 )
 ; // Overridden
 MELIST Children
   Seq: ( HWL ME_4B14E32102A2 // TnsListReferenceActivateEvent
 )
 ; // Children
 MELIST Dependencies
   Seq: ( ME_4AF8599E02D0 // Filters
 ME_4B14E3290380 // TnsListReferenceActivateEvent
 ME_4BD6B869004D // Switcher$SetCaption
 ME_51C2B1A10186 // k2Prim
 ME_51C2B22D0030 // l3Memory
 ME_51C2B2640113 // l3String
 ME_51C2B2A901D0 // Clipboard Formats
 ME_51C2B2DA00C7 // l3Base
 ME_51C2B38200D6 // Document
 ME_51C2B3DE031E // Windows
 ME_51C2B3E2000E // Msg Codes
 ME_51C2B42E030C // TnsListHAFMacroReplacer
 ME_51C2B49E02FD // TnevMiscMessages
 ME_51C2B4C30241 // TDataAdapter
 ME_51C2B4F800DF // Controls
 ME_51C2B4FB0151 // Forms
 ME_51C2BB620335 // TextPara
 ME_51C2EE400003 // TevFormatHAFMacroReplacer
 ME_531F1D13022C // Ik2TagGenerator
 )
 ; // Dependencies
 UP "NeedsHackRef" false
 UP "ZoneType" 'Any'
 UP "author" 'Люлин А.В.'
 UP "finished dfm" true
 UP "no hands" true
 UP "resizeable" false
 UP "restrict form def" 'undefined'
 UP "started" '26.01.2009 20:02'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\List\Forms\PrimListInfo_Form.pas'
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View\List\Forms'
 UP extprop:pas:TypeName 'TPrimListInfoForm'
 UP extprop:rc:SelfName 'PrimListInfoForm'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'PrimListInfo_Form'
 UP extprop:NeedsInitEntities true

ENDME // ME_497DEC900012 PrimListInfo
