// PrimTreeAttributeSelect 497ECC0E0325 VCMForm Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_497ECC0E0325

: ME_4BD6F94500AC
 CONST UID '4BD6F94500AC'
 CONST Name 'astNone'
 CONST Class class_Class
 : Stereotype st_UserType ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Поиск: Выбор реквизита' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 CONST "ImageIndex" '-1'
 CONST "Weight" '-1'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms\PrimTreeAttributeSelect_astNone_UserType.pas'
 CONST extprop:pas:UnitName 'PrimTreeAttributeSelect_astNone_UserType'

ref; // ME_4BD6F94500AC astNone

: ME_4BD6F9540396
 CONST UID '4BD6F9540396'
 CONST Name 'astOneLevel'
 CONST Class class_Class
 : Stereotype st_UserType ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Ситуации второго уровня' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( HWL ME_4BD6F94500AC // astNone
 )
 ; // Inherits
 CONST "ImageIndex" '-1'
 CONST "VisibleToUser" false
 CONST "Weight" '-1'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms\PrimTreeAttributeSelect_astOneLevel_UserType.pas'
 CONST extprop:pas:UnitName 'PrimTreeAttributeSelect_astOneLevel_UserType'

ref; // ME_4BD6F9540396 astOneLevel

: ME_4BD6F97301F4
 CONST UID '4BD6F97301F4'
 CONST Name 'astFirstLevel'
 CONST Class class_Class
 : Stereotype st_UserType ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Ситуации первого уровня' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( HWL ME_4BD6F9540396 // astOneLevel
 )
 ; // Inherits
 CONST "ImageIndex" '-1'
 CONST "VisibleToUser" false
 CONST "Weight" '-1'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms\PrimTreeAttributeSelect_astFirstLevel_UserType.pas'
 CONST extprop:pas:UnitName 'PrimTreeAttributeSelect_astFirstLevel_UserType'

ref; // ME_4BD6F97301F4 astFirstLevel

FORWARD ME_4BD6F992021A

: ME_4BD6F9A8011C
 CONST UID '4BD6F9A8011C'
 CONST Name 'UseToolbarOfUserTypeName'
 CONST Class class_Attribute
 : Stereotype st_link::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 CONST LinkType lt_lnk
 : Parent HWL ME_4BD6F992021A // astTaxesPublishSearch
 ;
 : Target HWL ME_4BD6F94500AC // astNone
 ;

ref; // ME_4BD6F9A8011C UseToolbarOfUserTypeName

: ME_4BD6F992021A
 CONST UID '4BD6F992021A'
 CONST Name 'astTaxesPublishSearch'
 CONST Class class_Class
 : Stereotype st_UserType ;
 CONST Kind kind_NormalClass
 %SUMMARY 'СМИ по налогам и бухучету' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( HWL ME_4BD6F97301F4 // astFirstLevel
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_4BD6F9A8011C // UseToolbarOfUserTypeName
 )
 ; // Attributes
 CONST "ImageIndex" '-1'
 CONST "VisibleToUser" false
 CONST "Weight" '-1'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms\PrimTreeAttributeSelect_astTaxesPublishSearch_UserType.pas'
 CONST extprop:pas:UnitName 'PrimTreeAttributeSelect_astTaxesPublishSearch_UserType'

ref; // ME_4BD6F992021A astTaxesPublishSearch

FORWARD ME_4C2B075E0155

: ME_4AE831FA00F9_ME_4C2B075E0155
 : Original WL 'ME_4AE831FA00F9' '4AE831B30019.pas.ms.script' // ExternalCharPressed
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AE831FA00F9_ME_4C2B075E0155 ExternalCharPressed

: ME_4C2B075E0155
 CONST UID '4C2B075E0155'
 CONST Name 'ExcludeExternalCharPressedForOneLevel'
 CONST Class class_Class
 : Stereotype st_ExcludeUserTypes ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( HWL ME_4BD6F9540396 // astOneLevel
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4AE831E70016' '4AE831B30019.pas.ms.script' // AttributeTree$Select
 )
 ; // Implements
 : Implemented
   Seq: ( ME_4AE831FA00F9_ME_4C2B075E0155 // ExternalCharPressed
 )
 ; // Implemented

ref; // ME_4C2B075E0155 ExcludeExternalCharPressedForOneLevel

FORWARD ME_4C2B1BE20259

: ME_4C2B1B9100B5_ME_4C2B1BE20259
 : Original WL 'ME_4C2B1B9100B5' '4AE831B30019.pas.ms.script' // FindFirstSelected
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" true
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4C2B1B9100B5_ME_4C2B1BE20259 FindFirstSelected

: ME_4C2B1BE20259
 CONST UID '4C2B1BE20259'
 CONST Name 'ExludeFindFirstSelectedForOneLevel'
 CONST Class class_Class
 : Stereotype st_ExcludeUserTypes ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( HWL ME_4BD6F9540396 // astOneLevel
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4C2B1B8003E4' '4AE831B30019.pas.ms.script' // Folder
 )
 ; // Implements
 : Implemented
   Seq: ( ME_4C2B1B9100B5_ME_4C2B1BE20259 // FindFirstSelected
 )
 ; // Implemented

ref; // ME_4C2B1BE20259 ExludeFindFirstSelectedForOneLevel

FORWARD ME_53A950A801A6

: ME_53A9515E0061
 CONST UID '53A9515E0061'
 CONST Name 'UseToolbarOfUserTypeName'
 CONST Class class_Attribute
 : Stereotype st_link::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 CONST LinkType lt_lnk
 : Parent HWL ME_53A950A801A6 // astPharmPublishSearch
 ;
 : Target HWL ME_4BD6F94500AC // astNone
 ;

ref; // ME_53A9515E0061 UseToolbarOfUserTypeName

: ME_53A950A801A6
 CONST UID '53A950A801A6'
 CONST Name 'astPharmPublishSearch'
 CONST Class class_Class
 : Stereotype st_UserType ;
 CONST Kind kind_NormalClass
 %SUMMARY 'СМИ по медицине и здравоохранению' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( HWL ME_4BD6F992021A // astTaxesPublishSearch
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_53A9515E0061 // UseToolbarOfUserTypeName
 )
 ; // Attributes
 CONST "ImageIndex" '-1'
 CONST "VisibleToUser" false
 CONST "Weight" '-1'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms\PrimTreeAttributeSelect_astPharmPublishSearch_UserType.pas'
 CONST extprop:pas:UnitName 'PrimTreeAttributeSelect_astPharmPublishSearch_UserType'

ref; // ME_53A950A801A6 astPharmPublishSearch

FORWARD ME_527746CF030B

: ME_4ACDE6290267
 CONST UID '4ACDE6290267'
 CONST Name 'ContextFilter'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527746CF030B // BackgroundPanel
 ;
 CONST "ControlClass" 'TnscContextFilter'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_4ACDE6290267 ContextFilter

FORWARD ME_4ACDE63F00C5

: ME_4AEAEABF034E_ME_4ACDE63F00C5
 : Original WL 'ME_4AEAEABF034E' '4AE831B30019.pas.ms.script' // DefaultAction
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AEAEABF034E_ME_4ACDE63F00C5 DefaultAction

: ME_4AFAFB4602D9_ME_4ACDE63F00C5
 : Original WL 'ME_4AFAFB4602D9' '4AE831B30019.pas.ms.script' // LogicOr
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4AFAFB4602D9_ME_4ACDE63F00C5 LogicOr

: ME_4AFAFB5800B9_ME_4ACDE63F00C5
 : Original WL 'ME_4AFAFB5800B9' '4AE831B30019.pas.ms.script' // LogicAnd
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4AFAFB5800B9_ME_4ACDE63F00C5 LogicAnd

: ME_4AFAFB7002B5_ME_4ACDE63F00C5
 : Original WL 'ME_4AFAFB7002B5' '4AE831B30019.pas.ms.script' // LogicNot
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4AFAFB7002B5_ME_4ACDE63F00C5 LogicNot

: ME_4BDAF7880236_ME_4ACDE63F00C5
 : Original WL 'ME_4BDAF7880236' '4BDAF7510113.pas.ms.script' // ExpandAll
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4BDAF7880236_ME_4ACDE63F00C5 ExpandAll

: ME_4BDAF7A2005C_ME_4ACDE63F00C5
 : Original WL 'ME_4BDAF7A2005C' '4BDAF7510113.pas.ms.script' // CollapseAll
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4BDAF7A2005C_ME_4ACDE63F00C5 CollapseAll

: ME_4BDAF7B803CF_ME_4ACDE63F00C5
 : Original WL 'ME_4BDAF7B803CF' '4BDAF7510113.pas.ms.script' // Wrap
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4BDAF7B803CF_ME_4ACDE63F00C5 Wrap

: ME_4C44444E0066_ME_4ACDE63F00C5
 : Original WL 'ME_4C44444E0066' '4AE831B30019.pas.ms.script' // LogicOrShortcut
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4C44444E0066_ME_4ACDE63F00C5 LogicOrShortcut

: ME_4C4445300216_ME_4ACDE63F00C5
 : Original WL 'ME_4C4445300216' '4AE831B30019.pas.ms.script' // DropSelection
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4C4445300216_ME_4ACDE63F00C5 DropSelection

: ME_4ACDE63F00C5
 CONST UID '4ACDE63F00C5'
 CONST Name 'AttributeTree'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527746CF030B // BackgroundPanel
 ;
 : Implements
   Seq: ( WL 'ME_4AEAEAB60182' '4AE831B30019.pas.ms.script' // Attribute
 WL 'ME_4BDAF7790158' '4BDAF7510113.pas.ms.script' // Tree
 WL 'ME_4C44452402C9' '4AE831B30019.pas.ms.script' // Selection
 )
 ; // Implements
 : Implemented
   Seq: ( ME_4AEAEABF034E_ME_4ACDE63F00C5 // DefaultAction
 ME_4AFAFB4602D9_ME_4ACDE63F00C5 // LogicOr
 ME_4AFAFB5800B9_ME_4ACDE63F00C5 // LogicAnd
 ME_4AFAFB7002B5_ME_4ACDE63F00C5 // LogicNot
 ME_4BDAF7880236_ME_4ACDE63F00C5 // ExpandAll
 ME_4BDAF7A2005C_ME_4ACDE63F00C5 // CollapseAll
 ME_4BDAF7B803CF_ME_4ACDE63F00C5 // Wrap
 ME_4C44444E0066_ME_4ACDE63F00C5 // LogicOrShortcut
 ME_4C4445300216_ME_4ACDE63F00C5 // DropSelection
 )
 ; // Implemented
 CONST "ControlClass" 'TnscTreeViewHotTruck'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_4ACDE63F00C5 AttributeTree

: ME_527746CF030B
 CONST UID '527746CF030B'
 CONST Name 'BackgroundPanel'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Attributes
   Seq: ( HWL ME_4ACDE6290267 // ContextFilter
 HWL ME_4ACDE63F00C5 // AttributeTree
 )
 ; // Attributes
 CONST "ControlClass" 'TvtPanel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527746CF030B BackgroundPanel

: ME_497ECC8E0036
 CONST UID '497ECC8E0036'
 CONST Name 'dsTreeAttributeSelect'
 CONST Class class_Attribute
 : Stereotype st_ViewArea::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 CONST LinkType lt_lnk
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4924352E01C3' '491DAF4202EE.pas.ms.script' // IdsTreeAttributeSelect
 ;

ref; // ME_497ECC8E0036 dsTreeAttributeSelect

: ME_4AEF38D40105
 CONST UID '4AEF38D40105'
 CONST Name 'f_NeedRefilterTree'
 CONST Class class_Attribute
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_lnk
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_4AEF38D40105 f_NeedRefilterTree

: ME_52774DA600FD
 CONST UID '52774DA600FD'
 CONST Name 'DS'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4924352E01C3' '491DAF4202EE.pas.ms.script' // IdsTreeAttributeSelect
 ;
 CONST "pm" true

ref; // ME_52774DA600FD DS

: ME_52774DDF02AF
 CONST UID '52774DDF02AF'
 CONST Name 'TaggedTreeInfo'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_49006C6F02C8' '4990510C0026.pas.ms.script' // InsTaggedTreeInfo
 ;
 CONST "pm" true

ref; // ME_52774DDF02AF TaggedTreeInfo

: ME_52774E0A018E
 CONST UID '52774E0A018E'
 CONST Name 'RootInfo'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4909E0980010' '47ECAAF901F8.pas.ms.script' // InsRootInfo
 ;
 CONST "pm" true

ref; // ME_52774E0A018E RootInfo

: ME_5277509B008E
 CONST UID '5277509B008E'
 CONST Name 'f_OrState'
 CONST Class class_Attribute
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5277509B008E f_OrState

: ME_527750A60194
 CONST UID '527750A60194'
 CONST Name 'f_AndState'
 CONST Class class_Attribute
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_527750A60194 f_AndState

: ME_527750AE0202
 CONST UID '527750AE0202'
 CONST Name 'f_NotState'
 CONST Class class_Attribute
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_527750AE0202 f_NotState

: ME_5277512702E8
 CONST UID '5277512702E8'
 CONST Name 'f_CaptionMap'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_492438C90376' '499192F203B4.pas.ms.script' // InsStringValueMap
 ;

ref; // ME_5277512702E8 f_CaptionMap

: ME_527751400121
 CONST UID '527751400121'
 CONST Name 'f_Painted'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_527751400121 f_Painted

: ME_52777F37036D
 CONST UID '52777F37036D'
 CONST Name 'f_LockCurrentChange'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_52777F37036D f_LockCurrentChange

FORWARD ME_4ACDE6BF0255

: ME_4ACDE95E00EE
 CONST UID '4ACDE95E00EE'
 CONST Name 'Filters'
 CONST Class class_Attribute
 : Stereotype st_var::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 : Target WL 'ME_4902013F03CC' '47ECAAF901F8.pas.ms.script' // InsAttributeTreeFilters
 ;
 CONST "IsResult" false

ref; // ME_4ACDE95E00EE Filters

: ME_4ACDE97D0289
 CONST UID '4ACDE97D0289'
 CONST Name 'Tree'
 CONST Class class_Attribute
 : Stereotype st_var::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 : Target WL 'ME_46835C050374' '4682595B0268.pas.ms.script' // Il3FilterableTree
 ;
 CONST "IsResult" false

ref; // ME_4ACDE97D0289 Tree

: ME_4ACDE98E02DA
 CONST UID '4ACDE98E02DA'
 CONST Name 'Index'
 CONST Class class_Attribute
 : Stereotype st_var::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "IsResult" false

ref; // ME_4ACDE98E02DA Index

: ME_4ACDE6ED0177
 CONST Name 'aFilterType'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_490200F300DD' '47F2170002B2.pas.ms.script' // TnsFilterType
 ;

ref; // ME_4ACDE6ED0177 aFilterType

: ME_4ACDE6E9028A
 CONST UID '4ACDE6E9028A'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 : Parameters
   Seq: ( ME_4ACDE6ED0177 // aFilterType
 )
 ; // Parameters

ref; // ME_4ACDE6E9028A DoIt

: ME_4ACDED460185
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_4ACDED460185 

: ME_4ACDED720066
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 : Target WL 'ME_47F260EC02C7' '521C9DA50125.pas.ms.script' // StdRes
 ;

ref; // ME_4ACDED720066 

: ME_4ACDEFD90017
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 : Target WL 'ME_4908462903E0' '49083E150027.pas.ms.script' // TnscContextFilterState
 ;

ref; // ME_4ACDEFD90017 

: ME_4ACDF01C011C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 : Target WL 'ME_47878E0E0191' '54B90AC6014B.pas.ms.script' // l3String
 ;

ref; // ME_4ACDF01C011C 

: ME_4ACDE6BF0255
 CONST UID '4ACDE6BF0255'
 CONST Name 'SetFilter'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Накладывает фильтр на дерево' ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Attributes
   Seq: ( HWL ME_4ACDE95E00EE // Filters
 HWL ME_4ACDE97D0289 // Tree
 HWL ME_4ACDE98E02DA // Index
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_4ACDE6E9028A // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4ACDED460185 // SysUtils
 ME_4ACDED720066 // StdRes
 ME_4ACDEFD90017 // TnscContextFilterState
 ME_4ACDF01C011C // l3String
 )
 ; // Dependencies

ref; // ME_4ACDE6BF0255 SetFilter

FORWARD ME_4ACDF3B90238

: ME_4ACDF3CD0189
 CONST UID '4ACDF3CD0189'
 CONST Name 'DoIt'
 CONST Class class_Operation
 %SUMMARY 'Аналог проверки TefTreeAttributeSelectUT(UserType) <> astNone, только с учётом astTaxesPublishSearch' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4ACDF3B90238 // IsOldSchoolNone
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_4ACDF3CD0189 DoIt

: ME_4ACDF3B90238
 CONST UID '4ACDF3B90238'
 CONST Name 'IsOldSchoolNone'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Аналог проверки TefTreeAttributeSelectUT(UserType) <> astNone, только с учётом astTaxesPublishSearch' ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_4ACDF3CD0189 // DoIt
 )
 ; // Operations

ref; // ME_4ACDF3B90238 IsOldSchoolNone

FORWARD ME_4F88602F0276

: ME_4F88605A039E
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_4F88605A039E aControl

: ME_4F88605B0006
 CONST Name 'aX'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4F88605B0006 aX

: ME_4F88605B0053
 CONST Name 'aY'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4F88605B0053 aY

: ME_4F88605B0093
 CONST Name 'theTarget'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_46A451250363' '4AB0C3C60310.pas.ms.script' // IUnknown
 ;

ref; // ME_4F88605B0093 theTarget

: ME_4F8860400108
 CONST UID '4F8860400108'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4F88602F0276 // EntitiesenAttributeGetTarget
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_4F88605A039E // aControl
 ME_4F88605B0006 // aX
 ME_4F88605B0053 // aY
 ME_4F88605B0093 // theTarget
 )
 ; // Parameters

ref; // ME_4F8860400108 DoIt

: ME_4F88602F0276
 CONST UID '4F88602F0276'
 CONST Name 'EntitiesenAttributeGetTarget'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Implements
   Seq: ( WL 'ME_4AEAEAB60182' '4AE831B30019.pas.ms.script' // Attribute
 )
 ; // Implements
 : Operations
   Seq: ( HWL ME_4F8860400108 // DoIt
 )
 ; // Operations

ref; // ME_4F88602F0276 EntitiesenAttributeGetTarget

: ME_52774A9A001E
 CONST UID '52774A9A001E'
 CONST Name 'ContextFilterChange'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits

ref; // ME_52774A9A001E ContextFilterChange

: ME_52774AA6031C
 CONST UID '52774AA6031C'
 CONST Name 'ContextFilterWrongContext'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits

ref; // ME_52774AA6031C ContextFilterWrongContext

: ME_52774AB301C7
 CONST UID '52774AB301C7'
 CONST Name 'AttributeTreeIsCommandProcessed'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( WL 'ME_514B3AD903AA' '4CFFE3470249.pas.ms.script' // TCommandProcessedEvent
 )
 ; // Inherits

ref; // ME_52774AB301C7 AttributeTreeIsCommandProcessed

: ME_52774ABF000B
 CONST UID '52774ABF000B'
 CONST Name 'AttributeTreeAfterFirstPaint'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits

ref; // ME_52774ABF000B AttributeTreeAfterFirstPaint

: ME_52774ACB00D3
 CONST UID '52774ACB00D3'
 CONST Name 'AttributeTreeLMouseDown'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( WL 'ME_515183DD03C3' '4799D29F033F.pas.ms.script' // TMouseEvent
 )
 ; // Inherits

ref; // ME_52774ACB00D3 AttributeTreeLMouseDown

: ME_52774AD4024A
 CONST UID '52774AD4024A'
 CONST Name 'AttributeTreeGetItemImage'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( WL 'ME_47D63B6D0157' '47D036150077.pas.ms.script' // Tl3GetItemImage
 )
 ; // Inherits

ref; // ME_52774AD4024A AttributeTreeGetItemImage

: ME_52774AF002C7
 CONST UID '52774AF002C7'
 CONST Name 'AttributeTreeActionElement'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( WL 'ME_51432026033F' '4CFFE3470249.pas.ms.script' // TActionElement
 )
 ; // Inherits

ref; // ME_52774AF002C7 AttributeTreeActionElement

: ME_52774AF800AF
 CONST UID '52774AF800AF'
 CONST Name 'AttributeTreeCurrentChanged'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( WL 'ME_4A9D4FB0034A' '494B949E022B.pas.ms.script' // TeeCurrentChanged
 )
 ; // Inherits

ref; // ME_52774AF800AF AttributeTreeCurrentChanged

: ME_52774B01032D
 CONST UID '52774B01032D'
 CONST Name 'AttributeTreeTreeChanged'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( WL 'ME_5146EBE00019' '515DA5860015.pas.ms.script' // TvtTreeChangedEvent
 )
 ; // Inherits

ref; // ME_52774B01032D AttributeTreeTreeChanged

: ME_52774B080270
 CONST UID '52774B080270'
 CONST Name 'AttributeTreeNewCharPressed'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Inherits
   Seq: ( WL 'ME_5143230F01E4' '494B949E022B.pas.ms.script' // TeeNewCharPressed
 )
 ; // Inherits

ref; // ME_52774B080270 AttributeTreeNewCharPressed

: ME_52775595015F
 CONST UID '52775595015F'
 CONST Name 'SendContextChangeMessage'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;

ref; // ME_52775595015F SendContextChangeMessage

FORWARD ME_527756DF00E1

: ME_527756E701B6
 CONST Name 'aTree'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46825CC00249' '4682595B0268.pas.ms.script' // Il3SimpleTree
 ;

ref; // ME_527756E701B6 aTree

: ME_527756E30339
 CONST UID '527756E30339'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_527756DF00E1 // SetupNewTreeStruct
 ;
 : Parameters
   Seq: ( ME_527756E701B6 // aTree
 )
 ; // Parameters

ref; // ME_527756E30339 DoIt

: ME_527756DF00E1
 CONST UID '527756DF00E1'
 CONST Name 'SetupNewTreeStruct'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_527756E30339 // DoIt
 )
 ; // Operations

ref; // ME_527756DF00E1 SetupNewTreeStruct

FORWARD ME_52775711033A

: ME_5277571D019F
 CONST Name 'aNode'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_468259900322' '4682595B0268.pas.ms.script' // Il3SimpleNode
 ;

ref; // ME_5277571D019F aNode

: ME_5277571D01BC
 CONST Name 'aExpand'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_5277571D01BC aExpand

: ME_527757160296
 CONST UID '527757160296'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_52775711033A // SetCurrentNode
 ;
 : Parameters
   Seq: ( ME_5277571D019F // aNode
 ME_5277571D01BC // aExpand
 )
 ; // Parameters

ref; // ME_527757160296 DoIt

: ME_52775711033A
 CONST UID '52775711033A'
 CONST Name 'SetCurrentNode'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_527757160296 // DoIt
 )
 ; // Operations

ref; // ME_52775711033A SetCurrentNode

FORWARD ME_52775732027C

: ME_5277573B030C
 CONST Name 'aDropSelection'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_5277573B030C aDropSelection

: ME_527757370293
 CONST UID '527757370293'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_52775732027C // DropAllLogicSelection
 ;
 : Parameters
   Seq: ( ME_5277573B030C // aDropSelection
 )
 ; // Parameters

ref; // ME_527757370293 DoIt

: ME_52775732027C
 CONST UID '52775732027C'
 CONST Name 'DropAllLogicSelection'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_527757370293 // DoIt
 )
 ; // Operations

ref; // ME_52775732027C DropAllLogicSelection

: ME_52775768034C
 CONST UID '52775768034C'
 CONST Name 'NotifyMultipleChanges'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;

ref; // ME_52775768034C NotifyMultipleChanges

FORWARD ME_52775777039C

: ME_52775780037A
 CONST Name 'aQuery'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_45EEE145027B' '45EEAA8E034E.pas.ms.script' // Query
 ;

ref; // ME_52775780037A aQuery

: ME_5277577C0291
 CONST UID '5277577C0291'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_52775777039C // SaveToQuery
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_52775780037A // aQuery
 )
 ; // Parameters

ref; // ME_5277577C0291 DoIt

: ME_52775777039C
 CONST UID '52775777039C'
 CONST Name 'SaveToQuery'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_5277577C0291 // DoIt
 )
 ; // Operations

ref; // ME_52775777039C SaveToQuery

FORWARD ME_5277579C0100

: ME_527757AA03B9
 CONST Name 'anIndex'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_527757AA03B9 anIndex

: ME_527757AA03D6
 CONST Name 'LogicOperationOnly'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_527757AA03D6 LogicOperationOnly

: ME_527757A502A9
 CONST UID '527757A502A9'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5277579C0100 // ActivateElement
 ;
 : Parameters
   Seq: ( ME_527757AA03B9 // anIndex
 ME_527757AA03D6 // LogicOperationOnly
 )
 ; // Parameters

ref; // ME_527757A502A9 DoIt

: ME_5277579C0100
 CONST UID '5277579C0100'
 CONST Name 'ActivateElement'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_527757A502A9 // DoIt
 )
 ; // Operations

ref; // ME_5277579C0100 ActivateElement

FORWARD ME_527757CF036E

: ME_527757DA02EE
 CONST Name 'aQuery'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_45EEE145027B' '45EEAA8E034E.pas.ms.script' // Query
 ;

ref; // ME_527757DA02EE aQuery

: ME_527757D40147
 CONST UID '527757D40147'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_527757CF036E // LoadFromQuery
 ;
 : Parameters
   Seq: ( ME_527757DA02EE // aQuery
 )
 ; // Parameters

ref; // ME_527757D40147 DoIt

: ME_527757CF036E
 CONST UID '527757CF036E'
 CONST Name 'LoadFromQuery'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_527757D40147 // DoIt
 )
 ; // Operations

ref; // ME_527757CF036E LoadFromQuery

FORWARD ME_527757EA030A

: ME_527757F10295
 CONST Name 'aSender'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4807745602C8' '4AB0C3C60310.pas.ms.script' // TObject
 ;

ref; // ME_527757F10295 aSender

: ME_527757EF0123
 CONST UID '527757EF0123'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_527757EA030A // DoContextFilterChange
 ;
 : Parameters
   Seq: ( ME_527757F10295 // aSender
 )
 ; // Parameters

ref; // ME_527757EF0123 DoIt

: ME_527757EA030A
 CONST UID '527757EA030A'
 CONST Name 'DoContextFilterChange'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_527757EF0123 // DoIt
 )
 ; // Operations

ref; // ME_527757EA030A DoContextFilterChange

: ME_527757FE02EE
 CONST UID '527757FE02EE'
 CONST Name 'InvalidateOtherTree'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;

ref; // ME_527757FE02EE InvalidateOtherTree

FORWARD ME_52775827028F

: ME_5277582F02D2
 CONST Name 'aTag'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_5277582F02D2 aTag

: ME_5277582B03E4
 CONST UID '5277582B03E4'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_52775827028F // SetRootForFullForm
 ;
 : Parameters
   Seq: ( ME_5277582F02D2 // aTag
 )
 ; // Parameters

ref; // ME_5277582B03E4 DoIt

: ME_52775827028F
 CONST UID '52775827028F'
 CONST Name 'SetRootForFullForm'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_5277582B03E4 // DoIt
 )
 ; // Operations

ref; // ME_52775827028F SetRootForFullForm

FORWARD ME_5277584002E5

: ME_527758480202
 CONST Name 'aTag'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_527758480202 aTag

: ME_5277584403BF
 CONST UID '5277584403BF'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5277584002E5 // SetRootForFirstLevelForm
 ;
 : Parameters
   Seq: ( ME_527758480202 // aTag
 )
 ; // Parameters

ref; // ME_5277584403BF DoIt

: ME_5277584002E5
 CONST UID '5277584002E5'
 CONST Name 'SetRootForFirstLevelForm'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_5277584403BF // DoIt
 )
 ; // Operations

ref; // ME_5277584002E5 SetRootForFirstLevelForm

FORWARD ME_5277585E00BE

: ME_5277586202AE
 CONST UID '5277586202AE'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5277585E00BE // GetRootInfo
 ;
 : Target WL 'ME_4909E0980010' '47ECAAF901F8.pas.ms.script' // InsRootInfo
 ;

ref; // ME_5277586202AE DoIt

: ME_5277585E00BE
 CONST UID '5277585E00BE'
 CONST Name 'GetRootInfo'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_5277586202AE // DoIt
 )
 ; // Operations

ref; // ME_5277585E00BE GetRootInfo

FORWARD ME_527758940054

: ME_527758A90134
 CONST Name 'aNode'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_527758A90134 aNode

: ME_527758A90151
 CONST Name 'aOldOp'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49006BB201CB' '4990510C0026.pas.ms.script' // TLogicOperation
 ;

ref; // ME_527758A90151 aOldOp

: ME_527758A9016F
 CONST Name 'aNewOp'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49006BB201CB' '4990510C0026.pas.ms.script' // TLogicOperation
 ;

ref; // ME_527758A9016F aNewOp

: ME_527758A20048
 CONST UID '527758A20048'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_527758940054 // NotifyOperationChange
 ;
 : Parameters
   Seq: ( ME_527758A90134 // aNode
 ME_527758A90151 // aOldOp
 ME_527758A9016F // aNewOp
 )
 ; // Parameters

ref; // ME_527758A20048 DoIt

: ME_527758940054
 CONST UID '527758940054'
 CONST Name 'NotifyOperationChange'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_527758A20048 // DoIt
 )
 ; // Operations

ref; // ME_527758940054 NotifyOperationChange

FORWARD ME_527758E80127

: ME_527758F50053
 CONST Name 'aNode'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_527758F50053 aNode

: ME_527758F50071
 CONST Name 'aOp'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49006BB201CB' '4990510C0026.pas.ms.script' // TLogicOperation
 ;

ref; // ME_527758F50071 aOp

: ME_527758F5008F
 CONST Name 'aWithNotify'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value true
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value true

ref; // ME_527758F5008F aWithNotify

: ME_527758EC0393
 CONST UID '527758EC0393'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_527758E80127 // FormLogicOperation
 ;
 : Parameters
   Seq: ( ME_527758F50053 // aNode
 ME_527758F50071 // aOp
 ME_527758F5008F // aWithNotify
 )
 ; // Parameters

ref; // ME_527758EC0393 DoIt

: ME_527758E80127
 CONST UID '527758E80127'
 CONST Name 'FormLogicOperation'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_527758EC0393 // DoIt
 )
 ; // Operations

ref; // ME_527758E80127 FormLogicOperation

: ME_5277590003E1
 CONST UID '5277590003E1'
 CONST Name 'DropSelectedOperation'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;

ref; // ME_5277590003E1 DropSelectedOperation

FORWARD ME_527759200129

: ME_52775926033A
 CONST Name 'aNewOp'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49006BB201CB' '4990510C0026.pas.ms.script' // TLogicOperation
 ;

ref; // ME_52775926033A aNewOp

: ME_52775924023E
 CONST UID '52775924023E'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_527759200129 // ChangeOperationOnSelected
 ;
 : Parameters
   Seq: ( ME_52775926033A // aNewOp
 )
 ; // Parameters

ref; // ME_52775924023E DoIt

: ME_527759200129
 CONST UID '527759200129'
 CONST Name 'ChangeOperationOnSelected'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_52775924023E // DoIt
 )
 ; // Operations

ref; // ME_527759200129 ChangeOperationOnSelected

FORWARD ME_527759B902F8

: ME_527759C8006B
 CONST Name 'aNewIndex'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_527759C8006B aNewIndex

: ME_527759C80088
 CONST Name 'aOldIndex'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_527759C80088 aOldIndex

: ME_527759C800A5
 CONST Name 'aForceUpdateParent'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_527759C800A5 aForceUpdateParent

: ME_527759BF0124
 CONST UID '527759BF0124'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_527759B902F8 // CurrentChangedPrim
 ;
 : Parameters
   Seq: ( ME_527759C8006B // aNewIndex
 ME_527759C80088 // aOldIndex
 ME_527759C800A5 // aForceUpdateParent
 )
 ; // Parameters

ref; // ME_527759BF0124 DoIt

: ME_527759B902F8
 CONST UID '527759B902F8'
 CONST Name 'CurrentChangedPrim'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_527759BF0124 // DoIt
 )
 ; // Operations

ref; // ME_527759B902F8 CurrentChangedPrim

FORWARD ME_527759E3016D

: ME_527759EC0385
 CONST Name 'aNode'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_527759EC0385 aNode

: ME_527759E8036C
 CONST UID '527759E8036C'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_527759E3016D // SetLogicOperationOnNode
 ;
 : Parameters
   Seq: ( ME_527759EC0385 // aNode
 )
 ; // Parameters

ref; // ME_527759E8036C DoIt

: ME_527759E3016D
 CONST UID '527759E3016D'
 CONST Name 'SetLogicOperationOnNode'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_527759E8036C // DoIt
 )
 ; // Operations

ref; // ME_527759E3016D SetLogicOperationOnNode

FORWARD ME_52775A88036E

: ME_52775A930138
 CONST Name 'aParams'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683E07E004B' '467BAB7F021E.pas.ms.script' // IvcmTestParamsPrim
 ;

ref; // ME_52775A930138 aParams

: ME_52775A930156
 CONST Name 'aOp'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49006BB201CB' '4990510C0026.pas.ms.script' // TLogicOperation
 ;

ref; // ME_52775A930156 aOp

: ME_52775A8D0147
 CONST UID '52775A8D0147'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_52775A88036E // LogicOperationTest
 ;
 : Parameters
   Seq: ( ME_52775A930138 // aParams
 ME_52775A930156 // aOp
 )
 ; // Parameters

ref; // ME_52775A8D0147 DoIt

: ME_52775A88036E
 CONST UID '52775A88036E'
 CONST Name 'LogicOperationTest'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_52775A8D0147 // DoIt
 )
 ; // Operations

ref; // ME_52775A88036E LogicOperationTest

FORWARD ME_52775B27001A

: ME_52775B5500FB
 CONST Name 'aNode'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_468259900322' '4682595B0268.pas.ms.script' // Il3SimpleNode
 ;

ref; // ME_52775B5500FB aNode

: ME_52775B50023F
 CONST UID '52775B50023F'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_52775B27001A // GetFirstLevelParent$1
 ;
 : Target WL 'ME_468259900322' '4682595B0268.pas.ms.script' // Il3SimpleNode
 ;
 : Parameters
   Seq: ( ME_52775B5500FB // aNode
 )
 ; // Parameters

ref; // ME_52775B50023F DoIt

: ME_52775B27001A
 CONST UID '52775B27001A'
 CONST Name 'GetFirstLevelParent'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_52775B50023F // DoIt
 )
 ; // Operations

ref; // ME_52775B27001A GetFirstLevelParent$1

FORWARD ME_52775B3700D4

: ME_52775B66007B
 CONST Name 'aNode'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_52775B66007B aNode

: ME_52775B6101AE
 CONST UID '52775B6101AE'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_52775B3700D4 // GetFirstLevelParent$2
 ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;
 : Parameters
   Seq: ( ME_52775B66007B // aNode
 )
 ; // Parameters

ref; // ME_52775B6101AE DoIt

: ME_52775B3700D4
 CONST UID '52775B3700D4'
 CONST Name 'GetFirstLevelParent'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_52775B6101AE // DoIt
 )
 ; // Operations

ref; // ME_52775B3700D4 GetFirstLevelParent$2

FORWARD ME_52775B3F025E

: ME_52775B7703CC
 CONST Name 'aIndex'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_52775B7703CC aIndex

: ME_52775B740230
 CONST UID '52775B740230'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_52775B3F025E // GetFirstLevelParent$3
 ;
 : Target WL 'ME_468259900322' '4682595B0268.pas.ms.script' // Il3SimpleNode
 ;
 : Parameters
   Seq: ( ME_52775B7703CC // aIndex
 )
 ; // Parameters

ref; // ME_52775B740230 DoIt

: ME_52775B3F025E
 CONST UID '52775B3F025E'
 CONST Name 'GetFirstLevelParent'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_52775B740230 // DoIt
 )
 ; // Operations

ref; // ME_52775B3F025E GetFirstLevelParent$3

FORWARD ME_52775B9402B2

: ME_52775BBD013D
 CONST Name 'aParams'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683E07E004B' '467BAB7F021E.pas.ms.script' // IvcmTestParamsPrim
 ;

ref; // ME_52775BBD013D aParams

: ME_52775BBD015A
 CONST Name 'aLO'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49006BB201CB' '4990510C0026.pas.ms.script' // TLogicOperation
 ;

ref; // ME_52775BBD015A aLO

: ME_52775BBA0271
 CONST UID '52775BBA0271'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_52775B9402B2 // LOToolbarTest
 ;
 : Parameters
   Seq: ( ME_52775BBD013D // aParams
 ME_52775BBD015A // aLO
 )
 ; // Parameters

ref; // ME_52775BBA0271 DoIt

: ME_52775B9402B2
 CONST UID '52775B9402B2'
 CONST Name 'LOToolbarTest'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'метод установки параметров в _OnTest для операций публикуемых в toolbar-е. Отличие в том, что они не показываются для ситуаций первого второго уровня.'#13#10''#13#10'Отключено при переносе на модель.'#13#10'Решили, что нет нужды делать разную логику для тулбаров и контекстного меню.' ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_52775BBA0271 // DoIt
 )
 ; // Operations
 CONST "ifdef" 'disabled_function'

ref; // ME_52775B9402B2 LOToolbarTest

FORWARD ME_52777B680276

: ME_52777B7A01B8
 CONST Name 'aNode'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_52777B7A01B8 aNode

: ME_52777B6F0231
 CONST UID '52777B6F0231'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_52777B680276 // CountItemImage
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Parameters
   Seq: ( ME_52777B7A01B8 // aNode
 )
 ; // Parameters

ref; // ME_52777B6F0231 DoIt

: ME_52777B680276
 CONST UID '52777B680276'
 CONST Name 'CountItemImage'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_52777B6F0231 // DoIt
 )
 ; // Operations

ref; // ME_52777B680276 CountItemImage

FORWARD ME_5279F70F0146

: ME_5279F7240380
 CONST Name 'aState'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_4992FC0C02CA' '4683F37902CF.pas.ms.script' // IvcmBase
 ;

ref; // ME_5279F7240380 aState

: ME_5279F724039D
 CONST Name 'aStateType'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CBFD032D' '467BAB7F021E.pas.ms.script' // TvcmStateType
 ;

ref; // ME_5279F724039D aStateType

: ME_5279F72403BA
 CONST Name 'Saved'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5279F72403BA Saved

: ME_5279F71E022A
 CONST UID '5279F71E022A'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5279F70F0146 // vcmEntityFormSaveState
 ;
 : Parameters
   Seq: ( ME_5279F7240380 // aState
 ME_5279F724039D // aStateType
 ME_5279F72403BA // Saved
 )
 ; // Parameters

ref; // ME_5279F71E022A DoIt

: ME_5279F70F0146
 CONST UID '5279F70F0146'
 CONST Name 'vcmEntityFormSaveState'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Operations
   Seq: ( HWL ME_5279F71E022A // DoIt
 )
 ; // Operations
 CONST extprop:rc:SelfName 'EntityFormSaveState'

ref; // ME_5279F70F0146 vcmEntityFormSaveState

: ME_4AE8329D00E8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_47878E0E0191' '54B90AC6014B.pas.ms.script' // l3String
 ;

ref; // ME_4AE8329D00E8 

: ME_4AE87B5E0017
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_4AE87B5E0017 

: ME_4AE87B6F0149
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_4AE87B6F0149 

: ME_4AE87BE100E5
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_49243E5C035C' '47F282AE0082.pas.ms.script' // nsLogicOperationToFlags
 ;

ref; // ME_4AE87BE100E5 

: ME_4AEF3C110257
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_49006BB201CB' '4990510C0026.pas.ms.script' // TLogicOperation
 ;

ref; // ME_4AEF3C110257 

: ME_4AF2CFA20339
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4AEF128901C3' '4AE831B30019.pas.ms.script' // AttributeTree
 ;

ref; // ME_4AF2CFA20339 

: ME_4AF3FF040124
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4804BDA10127' '47E246C90144.pas.ms.script' // Tl3Tree
 ;

ref; // ME_4AF3FF040124 

: ME_4AF4001A010E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4909E1DD038F' '49006FAB024A.pas.ms.script' // TnsAttrBranchStruct
 ;

ref; // ME_4AF4001A010E 

: ME_4AF4004001EF
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4AA7888B0076' '47913B47006E.pas.ms.script' // l3CStr
 ;

ref; // ME_4AF4004001EF 

: ME_4AF41A860358
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4AF4007401DC' '4AE831B30019.pas.ms.script' // ContextParams
 ;

ref; // ME_4AF41A860358 

: ME_4C2B1C5C028F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_468259900322' '4682595B0268.pas.ms.script' // Il3SimpleNode
 ;

ref; // ME_4C2B1C5C028F 

: ME_4C2B20EA0000
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4C2B202402C3' '48F747EC0073.pas.ms.script' // nsSetCurrentFirstSelected
 ;

ref; // ME_4C2B20EA0000 

: ME_52774B6402A8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_47E11FC3021E' '4799D29F033F.pas.ms.script' // Controls
 ;

ref; // ME_52774B6402A8 

: ME_52774B670274
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_47E13C6B0341' '4799D29F033F.pas.ms.script' // Forms
 ;

ref; // ME_52774B670274 

: ME_52777BBA01CC
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_48D2191902CB' '48D21909003A.pas.ms.script' // ActionCodes
 ;

ref; // ME_52777BBA01CC 

: ME_52777BE10316
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_484D2CBA0213' '484A470100DD.pas.ms.script' // TextStyle
 ;

ref; // ME_52777BE10316 

: ME_52778101030A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4AE58E7C00A4' '4AA005310028.pas.ms.script' // TnsSelectedAttributesIterators
 ;

ref; // ME_52778101030A 

: ME_5277812100F8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4AF4111F0184' '4A85282C0252.pas.ms.script' // nsTreeAttributeNodesNew
 ;

ref; // ME_5277812100F8 

: ME_527781D40228
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_468364C70131' '49006FAB024A.pas.ms.script' // TnsAttributeTreeStruct
 ;

ref; // ME_527781D40228 

: ME_527789210166
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_492440D20009' '48F747EC0073.pas.ms.script' // nsValueMaps
 ;

ref; // ME_527789210166 

: ME_52778924011E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4924422E0249' '48F747EC0073.pas.ms.script' // nsValueMapsIDs
 ;

ref; // ME_52778924011E 

: ME_5277895B03CE
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4909DC950238' '49006FAB024A.pas.ms.script' // TnsFirstLevelStruct
 ;

ref; // ME_5277895B03CE 

: ME_527789720154
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_47F25BC801DB' '47D0E1500033.pas.ms.script' // vcmBase
 ;

ref; // ME_527789720154 

: ME_5277898A003A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4EC391C00307' '4EEA0958023A.pas.ms.script' // SearchRes
 ;

ref; // ME_5277898A003A 

: ME_527789A502ED
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_492437620004' '492437620004.pas.ms.script' // TdsTreeAttributeSelect
 ;

ref; // ME_527789A502ED 

: ME_527789BB034F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4AE593970016' '4AA005310028.pas.ms.script' // TdeSearch
 ;

ref; // ME_527789BB034F 

: ME_527789E50119
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4AE8A02C03E7' '4A85282C0252.pas.ms.script' // nsQuery
 ;

ref; // ME_527789E50119 

: ME_527789FA02D4
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_48FF556602BA' '48F747EC0073.pas.ms.script' // DataAdapter
 ;

ref; // ME_527789FA02D4 

: ME_52778A98036F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_523309E20374' '46837A08002C.pas.ms.script' // InsQueryContainer
 ;

ref; // ME_52778A98036F 

: ME_54B7B47F03D9
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_4D80CDFB03A2' '4D80CDE4033D.pas.ms.script' // TreeAttributeSelect
 ;

ref; // ME_54B7B47F03D9 

: ME_54F835FA0062
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 : Target WL 'ME_54F835DA0012' '4A85282C0252.pas.ms.script' // tasSaveLoadProxy
 ;

ref; // ME_54F835FA0062 

: ME_48FF6D200201_ME_497ECC0E0325
 : Original WL 'ME_48FF6D200201' '47ECAAF901F8.pas.ms.script' // Updated
 ;
 CONST OpKind opkind_Implemented
ref; // ME_48FF6D200201_ME_497ECC0E0325 Updated

: ME_497465F501B7_ME_497ECC0E0325
 : Original WL 'ME_497465F501B7' '4974652502DA.pas.ms.script' // CurrentChangedNotification
 ;
 CONST OpKind opkind_Implemented
ref; // ME_497465F501B7_ME_497ECC0E0325 CurrentChangedNotification

: ME_4AE831FA00F9_ME_497ECC0E0325
 : Original WL 'ME_4AE831FA00F9' '4AE831B30019.pas.ms.script' // ExternalCharPressed
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AE831FA00F9_ME_497ECC0E0325 ExternalCharPressed

: ME_4AE8703B02A2_ME_497ECC0E0325
 : Original WL 'ME_4AE8703B02A2' '4AE831B30019.pas.ms.script' // SetCurrent
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AE8703B02A2_ME_497ECC0E0325 SetCurrent

: ME_4AE870DD01D0_ME_497ECC0E0325
 : Original WL 'ME_4AE870DD01D0' '4AE831B30019.pas.ms.script' // DropAllLogicSelection
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AE870DD01D0_ME_497ECC0E0325 DropAllLogicSelection

: ME_4AE879D00143_ME_497ECC0E0325
 : Original WL 'ME_4AE879D00143' '4AE831B30019.pas.ms.script' // IsQueryEmpty
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AE879D00143_ME_497ECC0E0325 IsQueryEmpty

: ME_4AE8913D00A7_ME_497ECC0E0325
 : Original WL 'ME_4AE8913D00A7' '4AE831B30019.pas.ms.script' // SaveToQuery
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AE8913D00A7_ME_497ECC0E0325 SaveToQuery

: ME_4AEAE67802ED_ME_497ECC0E0325
 : Original WL 'ME_4AEAE67802ED' '4AE831B30019.pas.ms.script' // Invalidate
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AEAE67802ED_ME_497ECC0E0325 Invalidate

: ME_4AEAEABF034E_ME_497ECC0E0325
 : Original WL 'ME_4AEAEABF034E' '4AE831B30019.pas.ms.script' // DefaultAction
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AEAEABF034E_ME_497ECC0E0325 DefaultAction

: ME_4AEF213001F0_ME_497ECC0E0325
 : Original WL 'ME_4AEF213001F0' '4AE831B30019.pas.ms.script' // SetQuery
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AEF213001F0_ME_497ECC0E0325 SetQuery

: ME_4AEF38310030_ME_497ECC0E0325
 : Original WL 'ME_4AEF38310030' '4AE831B30019.pas.ms.script' // DropLogicSelection
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AEF38310030_ME_497ECC0E0325 DropLogicSelection

: ME_4AEF3857010A_ME_497ECC0E0325
 : Original WL 'ME_4AEF3857010A' '4AE831B30019.pas.ms.script' // LoadQuery
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AEF3857010A_ME_497ECC0E0325 LoadQuery

: ME_4AEF3871010E_ME_497ECC0E0325
 : Original WL 'ME_4AEF3871010E' '4AE831B30019.pas.ms.script' // SetOneLevelCurrent
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AEF3871010E_ME_497ECC0E0325 SetOneLevelCurrent

: ME_4AEF38920247_ME_497ECC0E0325
 : Original WL 'ME_4AEF38920247' '4AE831B30019.pas.ms.script' // SetContext
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AEF38920247_ME_497ECC0E0325 SetContext

: ME_4AF3EBC001C4_ME_497ECC0E0325
 : Original WL 'ME_4AF3EBC001C4' '4AE831B30019.pas.ms.script' // SetRoot
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AF3EBC001C4_ME_497ECC0E0325 SetRoot

: ME_4AF3FE7D0138_ME_497ECC0E0325
 : Original WL 'ME_4AF3FE7D0138' '4AE831B30019.pas.ms.script' // ChangeRoot
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AF3FE7D0138_ME_497ECC0E0325 ChangeRoot

: ME_4AF40A0E01D3_ME_497ECC0E0325
 : Original WL 'ME_4AF40A0E01D3' '4AE831B30019.pas.ms.script' // SyncContextParams
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AF40A0E01D3_ME_497ECC0E0325 SyncContextParams

: ME_4AF8604B021E_ME_497ECC0E0325
 : Original WL 'ME_4AF8604B021E' '4AE831B30019.pas.ms.script' // AddNodeIfEmpty
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AF8604B021E_ME_497ECC0E0325 AddNodeIfEmpty

: ME_4AF92B09017F_ME_497ECC0E0325
 : Original WL 'ME_4AF92B09017F' '4AE831B30019.pas.ms.script' // ClearQuery
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "Needs Broadcast" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false
ref; // ME_4AF92B09017F_ME_497ECC0E0325 ClearQuery

: ME_4C2B1B9100B5_ME_497ECC0E0325
 : Original WL 'ME_4C2B1B9100B5' '4AE831B30019.pas.ms.script' // FindFirstSelected
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" true
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4C2B1B9100B5_ME_497ECC0E0325 FindFirstSelected

: ME_479731C50290_ME_497ECC0E0325
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_497ECC0E0325 Cleanup

: ME_47A042E100E2_ME_497ECC0E0325
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_497ECC0E0325 InitFields

: ME_497469C90140_ME_497ECC0E0325
 : Original WL 'ME_497469C90140' '5000041101C8.pas.ms.script' // NotifyDataSourceChanged
 ;
 CONST OpKind opkind_Overridden
ref; // ME_497469C90140_ME_497ECC0E0325 NotifyDataSourceChanged

: ME_49807428008C_ME_497ECC0E0325
 : Original WL 'ME_49807428008C' '4AADF9450143.pas.ms.script' // DoLoadState
 ;
 CONST OpKind opkind_Overridden
ref; // ME_49807428008C_ME_497ECC0E0325 DoLoadState

: ME_4A8E8F2E0195_ME_497ECC0E0325
 : Original WL 'ME_4A8E8F2E0195' '5000041101C8.pas.ms.script' // InitControls
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4A8E8F2E0195_ME_497ECC0E0325 InitControls

: ME_4D78E2BB0211_ME_497ECC0E0325
 : Original WL 'ME_4D78E2BB0211' '4AADF9450143.pas.ms.script' // NotifyUserTypeSet
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4D78E2BB0211_ME_497ECC0E0325 NotifyUserTypeSet

: ME_497ECC0E0325
 CONST UID '497ECC0E0325'
 CONST Name 'PrimTreeAttributeSelect'
 CONST Class class_Class
 : Stereotype st_VCMForm ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent WL 'ME_4A85282C0252' '4A85282C0252.pas.ms.script' // LiteSearch
 ;
 : Inherits
   Seq: ( WL 'ME_4974652502DA' '4974652502DA.pas.ms.script' // TreeAttribute
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_48FF6D050234' '47ECAAF901F8.pas.ms.script' // InsTreeDataListener
 WL 'ME_4AE831E70016' '4AE831B30019.pas.ms.script' // AttributeTree$Select
 WL 'ME_4AE879C5022F' '4AE831B30019.pas.ms.script' // SearchParameters
 WL 'ME_4AE8912B03B3' '4AE831B30019.pas.ms.script' // AttributeTree$SaveToQuery
 WL 'ME_4AEAEAB60182' '4AE831B30019.pas.ms.script' // Attribute
 WL 'ME_4AEF388A0016' '4AE831B30019.pas.ms.script' // Context
 WL 'ME_4AF3EB1C03A9' '4AE831B30019.pas.ms.script' // AttributeTree$SetRoot
 WL 'ME_4AF3FE6B0386' '4AE831B30019.pas.ms.script' // AttributeTree$ChangeRoot
 WL 'ME_4C2B1B8003E4' '4AE831B30019.pas.ms.script' // Folder
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_527746CF030B // BackgroundPanel
 HWL ME_497ECC8E0036 // dsTreeAttributeSelect
 HWL ME_4AEF38D40105 // f_NeedRefilterTree
 HWL ME_52774DA600FD // DS
 HWL ME_52774DDF02AF // TaggedTreeInfo
 HWL ME_52774E0A018E // RootInfo
 HWL ME_5277509B008E // f_OrState
 HWL ME_527750A60194 // f_AndState
 HWL ME_527750AE0202 // f_NotState
 HWL ME_5277512702E8 // f_CaptionMap
 HWL ME_527751400121 // f_Painted
 HWL ME_52777F37036D // f_LockCurrentChange
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_4ACDE6BF0255 // SetFilter
 HWL ME_4ACDF3B90238 // IsOldSchoolNone
 HWL ME_4F88602F0276 // EntitiesenAttributeGetTarget
 HWL ME_52774A9A001E // ContextFilterChange
 HWL ME_52774AA6031C // ContextFilterWrongContext
 HWL ME_52774AB301C7 // AttributeTreeIsCommandProcessed
 HWL ME_52774ABF000B // AttributeTreeAfterFirstPaint
 HWL ME_52774ACB00D3 // AttributeTreeLMouseDown
 HWL ME_52774AD4024A // AttributeTreeGetItemImage
 HWL ME_52774AF002C7 // AttributeTreeActionElement
 HWL ME_52774AF800AF // AttributeTreeCurrentChanged
 HWL ME_52774B01032D // AttributeTreeTreeChanged
 HWL ME_52774B080270 // AttributeTreeNewCharPressed
 HWL ME_52775595015F // SendContextChangeMessage
 HWL ME_527756DF00E1 // SetupNewTreeStruct
 HWL ME_52775711033A // SetCurrentNode
 HWL ME_52775732027C // DropAllLogicSelection
 HWL ME_52775768034C // NotifyMultipleChanges
 HWL ME_52775777039C // SaveToQuery
 HWL ME_5277579C0100 // ActivateElement
 HWL ME_527757CF036E // LoadFromQuery
 HWL ME_527757EA030A // DoContextFilterChange
 HWL ME_527757FE02EE // InvalidateOtherTree
 HWL ME_52775827028F // SetRootForFullForm
 HWL ME_5277584002E5 // SetRootForFirstLevelForm
 HWL ME_5277585E00BE // GetRootInfo
 HWL ME_527758940054 // NotifyOperationChange
 HWL ME_527758E80127 // FormLogicOperation
 HWL ME_5277590003E1 // DropSelectedOperation
 HWL ME_527759200129 // ChangeOperationOnSelected
 HWL ME_527759B902F8 // CurrentChangedPrim
 HWL ME_527759E3016D // SetLogicOperationOnNode
 HWL ME_52775A88036E // LogicOperationTest
 HWL ME_52775B27001A // GetFirstLevelParent$1
 HWL ME_52775B3700D4 // GetFirstLevelParent$2
 HWL ME_52775B3F025E // GetFirstLevelParent$3
 HWL ME_52775B9402B2 // LOToolbarTest
 HWL ME_52777B680276 // CountItemImage
 HWL ME_5279F70F0146 // vcmEntityFormSaveState
 )
 ; // Operations
 : Implemented
   Seq: ( ME_48FF6D200201_ME_497ECC0E0325 // Updated
 ME_497465F501B7_ME_497ECC0E0325 // CurrentChangedNotification
 ME_4AE831FA00F9_ME_497ECC0E0325 // ExternalCharPressed
 ME_4AE8703B02A2_ME_497ECC0E0325 // SetCurrent
 ME_4AE870DD01D0_ME_497ECC0E0325 // DropAllLogicSelection
 ME_4AE879D00143_ME_497ECC0E0325 // IsQueryEmpty
 ME_4AE8913D00A7_ME_497ECC0E0325 // SaveToQuery
 ME_4AEAE67802ED_ME_497ECC0E0325 // Invalidate
 ME_4AEAEABF034E_ME_497ECC0E0325 // DefaultAction
 ME_4AEF213001F0_ME_497ECC0E0325 // SetQuery
 ME_4AEF38310030_ME_497ECC0E0325 // DropLogicSelection
 ME_4AEF3857010A_ME_497ECC0E0325 // LoadQuery
 ME_4AEF3871010E_ME_497ECC0E0325 // SetOneLevelCurrent
 ME_4AEF38920247_ME_497ECC0E0325 // SetContext
 ME_4AF3EBC001C4_ME_497ECC0E0325 // SetRoot
 ME_4AF3FE7D0138_ME_497ECC0E0325 // ChangeRoot
 ME_4AF40A0E01D3_ME_497ECC0E0325 // SyncContextParams
 ME_4AF8604B021E_ME_497ECC0E0325 // AddNodeIfEmpty
 ME_4AF92B09017F_ME_497ECC0E0325 // ClearQuery
 ME_4C2B1B9100B5_ME_497ECC0E0325 // FindFirstSelected
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_497ECC0E0325 // Cleanup
 ME_47A042E100E2_ME_497ECC0E0325 // InitFields
 ME_497469C90140_ME_497ECC0E0325 // NotifyDataSourceChanged
 ME_49807428008C_ME_497ECC0E0325 // DoLoadState
 ME_4A8E8F2E0195_ME_497ECC0E0325 // InitControls
 ME_4D78E2BB0211_ME_497ECC0E0325 // NotifyUserTypeSet
 )
 ; // Overridden
 : Children
   Seq: ( HWL ME_4BD6F94500AC // astNone
 HWL ME_4BD6F9540396 // astOneLevel
 HWL ME_4BD6F97301F4 // astFirstLevel
 HWL ME_4BD6F992021A // astTaxesPublishSearch
 HWL ME_4C2B075E0155 // ExcludeExternalCharPressedForOneLevel
 HWL ME_4C2B1BE20259 // ExludeFindFirstSelectedForOneLevel
 HWL ME_53A950A801A6 // astPharmPublishSearch
 )
 ; // Children
 : Dependencies
   Seq: ( ME_4AE8329D00E8 // l3String
 ME_4AE87B5E0017 // NodeBase
 ME_4AE87B6F0149 // SysUtils
 ME_4AE87BE100E5 // nsLogicOperationToFlags
 ME_4AEF3C110257 // TLogicOperation
 ME_4AF2CFA20339 // AttributeTree
 ME_4AF3FF040124 // Tl3Tree
 ME_4AF4001A010E // TnsAttrBranchStruct
 ME_4AF4004001EF // l3CStr
 ME_4AF41A860358 // ContextParams
 ME_4C2B1C5C028F // Il3SimpleNode
 ME_4C2B20EA0000 // nsSetCurrentFirstSelected
 ME_52774B6402A8 // Controls
 ME_52774B670274 // Forms
 ME_52777BBA01CC // ActionCodes
 ME_52777BE10316 // TextStyle
 ME_52778101030A // TnsSelectedAttributesIterators
 ME_5277812100F8 // nsTreeAttributeNodesNew
 ME_527781D40228 // TnsAttributeTreeStruct
 ME_527789210166 // nsValueMaps
 ME_52778924011E // nsValueMapsIDs
 ME_5277895B03CE // TnsFirstLevelStruct
 ME_527789720154 // vcmBase
 ME_5277898A003A // SearchRes
 ME_527789A502ED // TdsTreeAttributeSelect
 ME_527789BB034F // TdeSearch
 ME_527789E50119 // nsQuery
 ME_527789FA02D4 // DataAdapter
 ME_52778A98036F // InsQueryContainer
 ME_54B7B47F03D9 // TreeAttributeSelect
 ME_54F835FA0062 // tasSaveLoadProxy
 )
 ; // Dependencies
 CONST "NeedsHackRef" false
 CONST "ZoneType" 'Any'
 CONST "author" 'Люлин А.В.'
 CONST "finished dfm" true
 CONST "no hands" true
 CONST "resizeable" false
 CONST "restrict form def" 'undefined'
 CONST "started" '27.01.2009 11:56'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms\PrimTreeAttributeSelect_Form.pas'
 CONST intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms'
 CONST extprop:pas:TypeName 'TPrimTreeAttributeSelectForm'
 CONST extprop:rc:SelfName 'PrimTreeAttributeSelectForm'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'PrimTreeAttributeSelect_Form'
 CONST extprop:NeedsInitEntities true

ref; // ME_497ECC0E0325 PrimTreeAttributeSelect
