// PrimUserProperty 497F02D20216 VCMForm Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_497F02D20216

: ME_4BD71D5C01A9
 CONST UID '4BD71D5C01A9'
 CONST Name 'admUseProperties'
 CONST Class class_Class
 : Stereotype st_UserType ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Свойства пользователя' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 CONST "CanClose" false
 CONST "ImageIndex" '-1'
 CONST "Weight" '-1'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\Admin\Forms\PrimUserProperty_admUseProperties_UserType.pas'
 CONST extprop:pas:UnitName 'PrimUserProperty_admUseProperties_UserType'

ref; // ME_4BD71D5C01A9 admUseProperties

FORWARD ME_527BDE0D02FB

: ME_527BDE2800A6
 CONST UID '527BDE2800A6'
 CONST Name 'edPasswordHint'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_527BDE0D02FB // Hints
 ;
 CONST Value '''Новый Пароль: должен совпадать с подтверждением пароля'''
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '''Новый Пароль: должен совпадать с подтверждением пароля'''

ref; // ME_527BDE2800A6 edPasswordHint

: ME_527BDE430168
 CONST UID '527BDE430168'
 CONST Name 'edUserNameHint'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_527BDE0D02FB // Hints
 ;
 CONST Value '''Имя пользователя: не должно быть пустым'''
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '''Имя пользователя: не должно быть пустым'''

ref; // ME_527BDE430168 edUserNameHint

: ME_527BDE54005C
 CONST UID '527BDE54005C'
 CONST Name 'edLoginHint'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_527BDE0D02FB // Hints
 ;
 CONST Value '''Новое регистрационное имя'''
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '''Новое регистрационное имя'''

ref; // ME_527BDE54005C edLoginHint

: ME_527BDE6603CD
 CONST UID '527BDE6603CD'
 CONST Name 'edEmailHint'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_527BDE0D02FB // Hints
 ;
 CONST Value '''Электронная почта: адрес, на который будет выслан забытый Вами пароль'''
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '''Электронная почта: адрес, на который будет выслан забытый Вами пароль'''

ref; // ME_527BDE6603CD edEmailHint

: ME_527BDE86024D
 CONST UID '527BDE86024D'
 CONST Name 'edConfirmHint'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_527BDE0D02FB // Hints
 ;
 CONST Value '''Подтверждение пароля: должно совпадать с новым паролем'''
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '''Подтверждение пароля: должно совпадать с новым паролем'''

ref; // ME_527BDE86024D edConfirmHint

: ME_527BDE93033C
 CONST UID '527BDE93033C'
 CONST Name 'edGroupHint'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_527BDE0D02FB // Hints
 ;
 CONST Value '''Группа пользователя'''
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '''Группа пользователя'''

ref; // ME_527BDE93033C edGroupHint

: ME_527BDE0D02FB
 CONST UID '527BDE0D02FB'
 CONST Name 'Hints'
 CONST Class class_Class
 : Stereotype st_LocalConst ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Attributes
   Seq: ( HWL ME_527BDE2800A6 // edPasswordHint
 HWL ME_527BDE430168 // edUserNameHint
 HWL ME_527BDE54005C // edLoginHint
 HWL ME_527BDE6603CD // edEmailHint
 HWL ME_527BDE86024D // edConfirmHint
 HWL ME_527BDE93033C // edGroupHint
 )
 ; // Attributes
 CONST "Need map interface" false
 CONST "Need mapping support" false
 CONST "elements prefix" 'PrimUserProperty'
 CONST "ifdef" 'Admin'
 CONST "spell names" false
 CONST extprop:pas:ElementPrefixBase 'PrimUserProperty'
 CONST extprop:pas:ElementPrefix 'PrimUserProperty_'

ref; // ME_527BDE0D02FB Hints

FORWARD ME_527BDB7C03C0

FORWARD ME_527BDB99021C

: ME_527BDC210395
 CONST UID '527BDC210395'
 CONST Name 'UserNameLabel'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 %SUMMARY '*ФИО пользователя:' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB99021C // f_TopPanel
 ;
 CONST "ControlClass" 'TvtLabel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527BDC210395 UserNameLabel

: ME_527BDC320349
 CONST UID '527BDC320349'
 CONST Name 'PasswordLabel'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Пароль:' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB99021C // f_TopPanel
 ;
 CONST "ControlClass" 'TvtLabel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527BDC320349 PasswordLabel

: ME_527BDC4300EA
 CONST UID '527BDC4300EA'
 CONST Name 'LoginLabel'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 %SUMMARY '*Регистрационное имя:' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB99021C // f_TopPanel
 ;
 CONST "ControlClass" 'TvtLabel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527BDC4300EA LoginLabel

: ME_527BDC540026
 CONST UID '527BDC540026'
 CONST Name 'EMailLabel'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Электронная почта:' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB99021C // f_TopPanel
 ;
 CONST "ControlClass" 'TvtLabel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527BDC540026 EMailLabel

: ME_527BDC63012B
 CONST UID '527BDC63012B'
 CONST Name 'ConfirmPasswordLabel'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Подтверждение пароля:' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB99021C // f_TopPanel
 ;
 CONST "ControlClass" 'TvtLabel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527BDC63012B ConfirmPasswordLabel

: ME_527BDC7400E7
 CONST UID '527BDC7400E7'
 CONST Name 'GroupLabel'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Группа:' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB99021C // f_TopPanel
 ;
 CONST "ControlClass" 'TvtLabel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527BDC7400E7 GroupLabel

: ME_527BDC870064
 CONST UID '527BDC870064'
 CONST Name 'edPassword'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB99021C // f_TopPanel
 ;
 CONST "ControlClass" 'TnscComboBoxWithPwdChar'
 CONST "pm" true
 CONST "put to dfm" false
 CONST extprop:rc:SelfName 'Password'

ref; // ME_527BDC870064 edPassword

: ME_527BDC9A00FD
 CONST UID '527BDC9A00FD'
 CONST Name 'edUserName'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB99021C // f_TopPanel
 ;
 CONST "ControlClass" 'TnscEdit'
 CONST "pm" true
 CONST "put to dfm" false
 CONST extprop:rc:SelfName 'UserName'

ref; // ME_527BDC9A00FD edUserName

: ME_527BDCAC039C
 CONST UID '527BDCAC039C'
 CONST Name 'edLogin'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB99021C // f_TopPanel
 ;
 CONST "ControlClass" 'TnscEdit'
 CONST "pm" true
 CONST "put to dfm" false
 CONST extprop:rc:SelfName 'Login'

ref; // ME_527BDCAC039C edLogin

: ME_527BDCC00247
 CONST UID '527BDCC00247'
 CONST Name 'edEmail'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB99021C // f_TopPanel
 ;
 CONST "ControlClass" 'TnscEdit'
 CONST "pm" true
 CONST "put to dfm" false
 CONST extprop:rc:SelfName 'Email'

ref; // ME_527BDCC00247 edEmail

: ME_527BDCD302CD
 CONST UID '527BDCD302CD'
 CONST Name 'edConfirm'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB99021C // f_TopPanel
 ;
 CONST "ControlClass" 'TnscComboBoxWithPwdChar'
 CONST "pm" true
 CONST "put to dfm" false
 CONST extprop:rc:SelfName 'Confirm'

ref; // ME_527BDCD302CD edConfirm

: ME_527BDCE4027E
 CONST UID '527BDCE4027E'
 CONST Name 'edGroup'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB99021C // f_TopPanel
 ;
 CONST "ControlClass" 'TvtComboBoxQS'
 CONST "pm" true
 CONST "put to dfm" false
 CONST extprop:rc:SelfName 'Group'

ref; // ME_527BDCE4027E edGroup

: ME_527BDB99021C
 CONST UID '527BDB99021C'
 CONST Name 'f_TopPanel'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB7C03C0 // pnMainData
 ;
 : Attributes
   Seq: ( HWL ME_527BDC210395 // UserNameLabel
 HWL ME_527BDC320349 // PasswordLabel
 HWL ME_527BDC4300EA // LoginLabel
 HWL ME_527BDC540026 // EMailLabel
 HWL ME_527BDC63012B // ConfirmPasswordLabel
 HWL ME_527BDC7400E7 // GroupLabel
 HWL ME_527BDC870064 // edPassword
 HWL ME_527BDC9A00FD // edUserName
 HWL ME_527BDCAC039C // edLogin
 HWL ME_527BDCC00247 // edEmail
 HWL ME_527BDCD302CD // edConfirm
 HWL ME_527BDCE4027E // edGroup
 )
 ; // Attributes
 CONST "ControlClass" 'TvtPanel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527BDB99021C f_TopPanel

FORWARD ME_527BDBDC0365

: ME_527BDD1402A3
 CONST UID '527BDD1402A3'
 CONST Name 'edPrivilegedUser'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Привилегированный пользователь' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDBDC0365 // f_MiddlePanel
 ;
 CONST "ControlClass" 'TvtCheckBox'
 CONST "pm" true
 CONST "put to dfm" false
 CONST extprop:rc:SelfName 'PrivilegedUser'

ref; // ME_527BDD1402A3 edPrivilegedUser

: ME_527BDD2E020B
 CONST UID '527BDD2E020B'
 CONST Name 'edBuyConsulting'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Разрешено использование услуги Правового консалтинга' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDBDC0365 // f_MiddlePanel
 ;
 CONST "ControlClass" 'TvtCheckBox'
 CONST "pm" true
 CONST "put to dfm" false
 CONST extprop:rc:SelfName 'BuyConsulting'

ref; // ME_527BDD2E020B edBuyConsulting

: ME_527BDBDC0365
 CONST UID '527BDBDC0365'
 CONST Name 'f_MiddlePanel'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB7C03C0 // pnMainData
 ;
 : Attributes
   Seq: ( HWL ME_527BDD1402A3 // edPrivilegedUser
 HWL ME_527BDD2E020B // edBuyConsulting
 )
 ; // Attributes
 CONST "ControlClass" 'TvtPanel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527BDBDC0365 f_MiddlePanel

FORWARD ME_527BDBEF0097

: ME_527BDDA40161
 CONST UID '527BDDA40161'
 CONST Name 'edDontDeleteIdleUser'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Не удалять при бездействии' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDBEF0097 // f_DontDeleteIdleUserPanel
 ;
 CONST "ControlClass" 'TvtCheckBox'
 CONST "pm" true
 CONST "put to dfm" false
 CONST extprop:rc:SelfName 'DontDeleteIdleUser'

ref; // ME_527BDDA40161 edDontDeleteIdleUser

: ME_527BDBEF0097
 CONST UID '527BDBEF0097'
 CONST Name 'f_DontDeleteIdleUserPanel'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB7C03C0 // pnMainData
 ;
 : Attributes
   Seq: ( HWL ME_527BDDA40161 // edDontDeleteIdleUser
 )
 ; // Attributes
 CONST "ControlClass" 'TvtPanel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527BDBEF0097 f_DontDeleteIdleUserPanel

FORWARD ME_527BDC02005D

: ME_527BDDCB02C6
 CONST UID '527BDDCB02C6'
 CONST Name 'InfoLabel'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 %SUMMARY '* - поля, обязательные для заполнения' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDC02005D // f_BottomPanel
 ;
 CONST "ControlClass" 'TvtLabel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527BDDCB02C6 InfoLabel

: ME_527BDDE701FE
 CONST UID '527BDDE701FE'
 CONST Name 'edHasSharedFilters'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Фильтры этого пользователя являются общими' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDC02005D // f_BottomPanel
 ;
 CONST "ControlClass" 'TvtCheckBox'
 CONST "pm" true
 CONST "put to dfm" false
 CONST extprop:rc:SelfName 'HasSharedFilters'

ref; // ME_527BDDE701FE edHasSharedFilters

: ME_527BDC02005D
 CONST UID '527BDC02005D'
 CONST Name 'f_BottomPanel'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB7C03C0 // pnMainData
 ;
 : Attributes
   Seq: ( HWL ME_527BDDCB02C6 // InfoLabel
 HWL ME_527BDDE701FE // edHasSharedFilters
 )
 ; // Attributes
 CONST "ControlClass" 'TvtPanel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527BDC02005D f_BottomPanel

: ME_527BDB7C03C0
 CONST UID '527BDB7C03C0'
 CONST Name 'pnMainData'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Attributes
   Seq: ( HWL ME_527BDB99021C // f_TopPanel
 HWL ME_527BDBDC0365 // f_MiddlePanel
 HWL ME_527BDBEF0097 // f_DontDeleteIdleUserPanel
 HWL ME_527BDC02005D // f_BottomPanel
 )
 ; // Attributes
 CONST "ControlClass" 'TvtPanel'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_527BDB7C03C0 pnMainData

: ME_497F0333004D
 CONST UID '497F0333004D'
 CONST Name 'dsUserProperty'
 CONST Class class_Attribute
 : Stereotype st_ViewArea::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 CONST LinkType lt_lnk
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_491DA3AF0290' '491D961C0122.pas.ms.script' // IdsUserProperty
 ;

ref; // ME_497F0333004D dsUserProperty

: ME_4C8A12790145
 CONST UID '4C8A12790145'
 CONST Name 'f_IsCorrectInfo'
 CONST Class class_Attribute
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_4C8A12790145 f_IsCorrectInfo

: ME_527BD9CA037A
 CONST UID '527BD9CA037A'
 CONST Name 'f_PasswordChanged'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_527BD9CA037A f_PasswordChanged

: ME_527BD9D4009A
 CONST UID '527BD9D4009A'
 CONST Name 'f_LockCheckBox'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_527BD9D4009A f_LockCheckBox

FORWARD ME_4C8A0FEE00C1

: ME_4C8A10000384
 CONST Name 'aDataSource'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_491DA3AF0290' '491D961C0122.pas.ms.script' // IdsUserProperty
 ;

ref; // ME_4C8A10000384 aDataSource

: ME_4C8A0FFD005A
 CONST UID '4C8A0FFD005A'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4C8A0FEE00C1 // SaveChangedProfile
 ;
 : Parameters
   Seq: ( ME_4C8A10000384 // aDataSource
 )
 ; // Parameters

ref; // ME_4C8A0FFD005A DoIt

: ME_4C8A0FEE00C1
 CONST UID '4C8A0FEE00C1'
 CONST Name 'SaveChangedProfile'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Operations
   Seq: ( HWL ME_4C8A0FFD005A // DoIt
 )
 ; // Operations

ref; // ME_4C8A0FEE00C1 SaveChangedProfile

FORWARD ME_4C8A10120190

: ME_4C8A103200FF
 CONST Name 'aUserProperty'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_491DA3AF0290' '491D961C0122.pas.ms.script' // IdsUserProperty
 ;

ref; // ME_4C8A103200FF aUserProperty

: ME_4C8A1029029D
 CONST UID '4C8A1029029D'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4C8A10120190 // CheckUnsaved
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_4C8A103200FF // aUserProperty
 )
 ; // Parameters

ref; // ME_4C8A1029029D DoIt

: ME_4C8A10120190
 CONST UID '4C8A10120190'
 CONST Name 'CheckUnsaved'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Возвращает признак отсутсвия несохраненных изменений (при необходимости выдавая запрос пользователю)' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Operations
   Seq: ( HWL ME_4C8A1029029D // DoIt
 )
 ; // Operations

ref; // ME_4C8A10120190 CheckUnsaved

: ME_4C8A12540363
 CONST UID '4C8A12540363'
 CONST Name 'RestoreFields'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;

ref; // ME_4C8A12540363 RestoreFields

: ME_527BD93C01C3
 CONST UID '527BD93C01C3'
 CONST Name 'edLoginChange'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits
 CONST extprop:rc:SelfName 'LoginChange'

ref; // ME_527BD93C01C3 edLoginChange

: ME_527BD9440399
 CONST UID '527BD9440399'
 CONST Name 'edPasswordChange'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits
 CONST extprop:rc:SelfName 'PasswordChange'

ref; // ME_527BD9440399 edPasswordChange

: ME_527BD94D0009
 CONST UID '527BD94D0009'
 CONST Name 'edConfirmChange'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits
 CONST extprop:rc:SelfName 'ConfirmChange'

ref; // ME_527BD94D0009 edConfirmChange

: ME_527BD954035C
 CONST UID '527BD954035C'
 CONST Name 'edUserNameChange'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits
 CONST extprop:rc:SelfName 'UserNameChange'

ref; // ME_527BD954035C edUserNameChange

: ME_527BD95C03CE
 CONST UID '527BD95C03CE'
 CONST Name 'edEmailChange'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits
 CONST extprop:rc:SelfName 'EmailChange'

ref; // ME_527BD95C03CE edEmailChange

: ME_527BD9660133
 CONST UID '527BD9660133'
 CONST Name 'edBuyConsultingClick'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits
 CONST extprop:rc:SelfName 'BuyConsultingClick'

ref; // ME_527BD9660133 edBuyConsultingClick

: ME_527BD96D033A
 CONST UID '527BD96D033A'
 CONST Name 'edPrivilegedUserClick'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits
 CONST extprop:rc:SelfName 'PrivilegedUserClick'

ref; // ME_527BD96D033A edPrivilegedUserClick

: ME_527BD9750041
 CONST UID '527BD9750041'
 CONST Name 'edGroupChange'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits
 CONST extprop:rc:SelfName 'GroupChange'

ref; // ME_527BD9750041 edGroupChange

: ME_527BD97D0353
 CONST UID '527BD97D0353'
 CONST Name 'edHasSharedFiltersClick'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits
 CONST extprop:rc:SelfName 'HasSharedFiltersClick'

ref; // ME_527BD97D0353 edHasSharedFiltersClick

: ME_527BD9860158
 CONST UID '527BD9860158'
 CONST Name 'edDontDeleteIdleUserClick'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits
 CONST extprop:rc:SelfName 'DontDeleteIdleUserClick'

ref; // ME_527BD9860158 edDontDeleteIdleUserClick

: ME_527BDA0E0133
 CONST UID '527BDA0E0133'
 CONST Name 'DoCheckUnsavedProperties'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;

ref; // ME_527BDA0E0133 DoCheckUnsavedProperties

FORWARD ME_527BDB0900E7

: ME_527BDB1101BB
 CONST UID '527BDB1101BB'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_527BDB0900E7 // ShowDontDeleteIdleUsers
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_527BDB1101BB DoIt

: ME_527BDB0900E7
 CONST UID '527BDB0900E7'
 CONST Name 'ShowDontDeleteIdleUsers'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Operations
   Seq: ( HWL ME_527BDB1101BB // DoIt
 )
 ; // Operations

ref; // ME_527BDB0900E7 ShowDontDeleteIdleUsers

: ME_527BDB1F021C
 CONST UID '527BDB1F021C'
 CONST Name 'InitUserFields'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;

ref; // ME_527BDB1F021C InitUserFields

: ME_527BDB2A0394
 CONST UID '527BDB2A0394'
 CONST Name 'CheckFields'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;

ref; // ME_527BDB2A0394 CheckFields

: ME_4AC5F2CB0193
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_48FF556602BA' '48F747EC0073.pas.ms.script' // DataAdapter
 ;

ref; // ME_4AC5F2CB0193 

: ME_4AC5F2EB00A3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_49E8213D00F6' '4901E79300F5.pas.ms.script' // TnsGroupTreeStruct
 ;

ref; // ME_4AC5F2EB00A3 

: ME_527CB6C000BC
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_4773D64E036C' '47913B47006E.pas.ms.script' // l3Base
 ;

ref; // ME_527CB6C000BC 

: ME_527CB6C300C4
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_47878E0E0191' '54B90AC6014B.pas.ms.script' // l3String
 ;

ref; // ME_527CB6C300C4 

: ME_527CB6C6000F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_49E5BB5F02B7' '4901E79300F5.pas.ms.script' // nsUserNodes
 ;

ref; // ME_527CB6C6000F 

: ME_527CB6C903D9
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_45EED4A10234' '45EEAA96039C.pas.ms.script' // LoginDuplicate
 ;

ref; // ME_527CB6C903D9 

: ME_527CB6CF0296
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_47FB50E4008E' '48F747EC0073.pas.ms.script' // nsConst
 ;

ref; // ME_527CB6CF0296 

: ME_527CB6D1028F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_47A082F101DB' '476BE98C01B8.pas.ms.script' // Ext Chars
 ;

ref; // ME_527CB6D1028F 

: ME_527CB6D30282
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_4A6854C70390' '47F2170002B2.pas.ms.script' // nsTypes
 ;

ref; // ME_527CB6D30282 

: ME_527CB6D50335
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_4C88F30900A7' '48F747EC0073.pas.ms.script' // nsVerifyValue
 ;

ref; // ME_527CB6D50335 

: ME_527CB6D801CD
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_4A8432960266' '48297E42011A.pas.ms.script' // ctTypes
 ;

ref; // ME_527CB6D801CD 

: ME_527CB6DA01FC
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_47E11FC3021E' '4799D29F033F.pas.ms.script' // Controls
 ;

ref; // ME_527CB6DA01FC 

: ME_527D01A3022F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_497F02D20216 // PrimUserProperty
 ;
 : Target WL 'ME_47F25BC801DB' '47D0E1500033.pas.ms.script' // vcmBase
 ;

ref; // ME_527D01A3022F 

: ME_49F6DC2600C0_ME_497F02D20216
 : Original WL 'ME_49F6DC2600C0' '491D961C0122.pas.ms.script' // CheckUnsavedProperties
 ;
 CONST OpKind opkind_Implemented
ref; // ME_49F6DC2600C0_ME_497F02D20216 CheckUnsavedProperties

: ME_497469C90140_ME_497F02D20216
 : Original WL 'ME_497469C90140' '5000041101C8.pas.ms.script' // NotifyDataSourceChanged
 ;
 CONST OpKind opkind_Overridden
ref; // ME_497469C90140_ME_497F02D20216 NotifyDataSourceChanged

: ME_4980407F0076_ME_497F02D20216
 : Original WL 'ME_4980407F0076' '4AADF9450143.pas.ms.script' // CallCloseQuery
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4980407F0076_ME_497F02D20216 CallCloseQuery

: ME_4A8E8F2E0195_ME_497F02D20216
 : Original WL 'ME_4A8E8F2E0195' '5000041101C8.pas.ms.script' // InitControls
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4A8E8F2E0195_ME_497F02D20216 InitControls

: ME_529332B40230_ME_497F02D20216
 : Original WL 'ME_529332B40230' '4AADF9450143.pas.ms.script' // SetupFormLayout
 ;
 CONST OpKind opkind_Overridden
ref; // ME_529332B40230_ME_497F02D20216 SetupFormLayout

: ME_576149F20025_ME_497F02D20216
 : Original WL 'ME_576149F20025' '4AADF9450143.pas.ms.script' // IsVCMScalingNeeded
 ;
 CONST OpKind opkind_Overridden
ref; // ME_576149F20025_ME_497F02D20216 IsVCMScalingNeeded

: ME_497F02D20216
 CONST UID '497F02D20216'
 CONST Name 'PrimUserProperty'
 CONST Class class_Class
 : Stereotype st_VCMForm ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_49480CD20303' '49480CD20303.pas.ms.script' // Admin
 ;
 : Inherits
   Seq: ( WL 'ME_49525B34022A' '4AADF9450143.pas.ms.script' // TvcmEntityForm
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_49F6DBFC01FD' '491D961C0122.pas.ms.script' // IbsUserPropertyListener
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_527BDB7C03C0 // pnMainData
 HWL ME_497F0333004D // dsUserProperty
 HWL ME_4C8A12790145 // f_IsCorrectInfo
 HWL ME_527BD9CA037A // f_PasswordChanged
 HWL ME_527BD9D4009A // f_LockCheckBox
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_4C8A0FEE00C1 // SaveChangedProfile
 HWL ME_4C8A10120190 // CheckUnsaved
 HWL ME_4C8A12540363 // RestoreFields
 HWL ME_527BD93C01C3 // edLoginChange
 HWL ME_527BD9440399 // edPasswordChange
 HWL ME_527BD94D0009 // edConfirmChange
 HWL ME_527BD954035C // edUserNameChange
 HWL ME_527BD95C03CE // edEmailChange
 HWL ME_527BD9660133 // edBuyConsultingClick
 HWL ME_527BD96D033A // edPrivilegedUserClick
 HWL ME_527BD9750041 // edGroupChange
 HWL ME_527BD97D0353 // edHasSharedFiltersClick
 HWL ME_527BD9860158 // edDontDeleteIdleUserClick
 HWL ME_527BDA0E0133 // DoCheckUnsavedProperties
 HWL ME_527BDB0900E7 // ShowDontDeleteIdleUsers
 HWL ME_527BDB1F021C // InitUserFields
 HWL ME_527BDB2A0394 // CheckFields
 )
 ; // Operations
 : Implemented
   Seq: ( ME_49F6DC2600C0_ME_497F02D20216 // CheckUnsavedProperties
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_497469C90140_ME_497F02D20216 // NotifyDataSourceChanged
 ME_4980407F0076_ME_497F02D20216 // CallCloseQuery
 ME_4A8E8F2E0195_ME_497F02D20216 // InitControls
 ME_529332B40230_ME_497F02D20216 // SetupFormLayout
 ME_576149F20025_ME_497F02D20216 // IsVCMScalingNeeded
 )
 ; // Overridden
 : Children
   Seq: ( HWL ME_4BD71D5C01A9 // admUseProperties
 )
 ; // Children
 : Constants
   Seq: ( HWL ME_527BDE0D02FB // Hints
 )
 ; // Constants
 : Dependencies
   Seq: ( ME_4AC5F2CB0193 // DataAdapter
 ME_4AC5F2EB00A3 // TnsGroupTreeStruct
 ME_527CB6C000BC // l3Base
 ME_527CB6C300C4 // l3String
 ME_527CB6C6000F // nsUserNodes
 ME_527CB6C903D9 // LoginDuplicate
 ME_527CB6CF0296 // nsConst
 ME_527CB6D1028F // Ext Chars
 ME_527CB6D30282 // nsTypes
 ME_527CB6D50335 // nsVerifyValue
 ME_527CB6D801CD // ctTypes
 ME_527CB6DA01FC // Controls
 ME_527D01A3022F // vcmBase
 )
 ; // Dependencies
 CONST "NeedsHackRef" true
 CONST "ZoneType" 'Any'
 CONST "author" 'Люлин А.В.'
 CONST "finished dfm" true
 CONST "no hands" true
 CONST "resizeable" false
 CONST "restrict form def" 'undefined'
 CONST "started" '27.01.2009 15:50'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\Admin\Forms\PrimUserProperty_Form.pas'
 CONST intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View\Admin\Forms'
 CONST extprop:pas:TypeName 'TPrimUserPropertyForm'
 CONST extprop:rc:SelfName 'PrimUserPropertyForm'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'PrimUserProperty_Form'

ref; // ME_497F02D20216 PrimUserProperty
