// StatusBar 49871D5103B9 Views Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_49871D5103B9
%%Inner ME_49871D5103B9
%%Inner ME_49871D5103B9
%%Inner ME_49871D5103B9
%%Inner ME_49871D5103B9
%%Inner ME_49871D5103B9
%%Inner ME_49871D5103B9
%%Inner ME_49871D5103B9
%%Inner ME_49871D5103B9

FORWARD ME_49871D5103B9

ME ME_49871E3F01D0
 MEPROP UID '49871E3F01D0'
 MEPROP Name 'TnscStatusBarOperationDefsList'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_49871D5103B9 // StatusBar
 ;
 UP "finished" false
 UP intf.pas:Path 'common\components\gui\Garant\Nemesis\NOT_FINISHED_nscStatusBarOperationDefsList.pas'
 UP extprop:rc:SelfName 'StatusBarOperationDefsList'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nscStatusBarOperationDefsList'

ENDME // ME_49871E3F01D0 TnscStatusBarOperationDefsList

FORWARD ME_4FEC3C34003F

ME ME_4FEC3F0F0322
 MEPROP UID '4FEC3F0F0322'
 MEPROP Name 'f_ShowCaption'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 ;
 MELINK Target WL 'ME_3DBFFE100240' '3DBFDB23006E.ms.model.script' // boolean
 ;

ENDME // ME_4FEC3F0F0322 f_ShowCaption

ME ME_4FEC3F4A0347
 MEPROP UID '4FEC3F4A0347'
 MEPROP Name 'f_Caption'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_4FEC3F4A0347 f_Caption

ME ME_4FEC3F64008C
 MEPROP UID '4FEC3F64008C'
 MEPROP Name 'f_UseTooltip'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 ;
 MELINK Target WL 'ME_3DBFFE100240' '3DBFDB23006E.ms.model.script' // boolean
 ;

ENDME // ME_4FEC3F64008C f_UseTooltip

ME ME_4FEC3F860101
 MEPROP UID '4FEC3F860101'
 MEPROP Name 'f_RequireAutoPopup'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 ;
 MELINK Target WL 'ME_3DBFFE100240' '3DBFDB23006E.ms.model.script' // boolean
 ;

ENDME // ME_4FEC3F860101 f_RequireAutoPopup

ME ME_4FEC3FCD01D0
 MEPROP UID '4FEC3FCD01D0'
 MEPROP Name 'f_AutoPopupTimeout'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 ;
 MELINK Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.ms.model.script' // unsigned long
 ;

ENDME // ME_4FEC3FCD01D0 f_AutoPopupTimeout

ME ME_4FEC400A012F
 MEPROP UID '4FEC400A012F'
 MEPROP Name 'f_ToolTipKind'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 ;
 MELINK Target WL 'ME_498035FA00E9' '490838E10313.ms.model.script' // TnscToolTipKind
 ;

ENDME // ME_4FEC400A012F f_ToolTipKind

ME ME_4FEC54210207
 MEPROP UID '4FEC54210207'
 MEPROP Name 'f_Enabled'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 ;
 MELINK Target WL 'ME_3DBFFE100240' '3DBFDB23006E.ms.model.script' // boolean
 ;

ENDME // ME_4FEC54210207 f_Enabled

ME ME_506038EB01CD
 MEPROP UID '506038EB01CD'
 MEPROP Name 'f_SubscribedList'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 ;
 MELINK Target HWL ME_49871E3F01D0 // TnscStatusBarOperationDefsList
 ;

ENDME // ME_506038EB01CD f_SubscribedList

FORWARD ME_4FEC3D23013F

ME ME_4FEC3D520137
 MEPROP Name 'aShowCaption'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FEC3D520137 aShowCaption

ME ME_4FEC5B380390
 MEPROP Name 'aCaption'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_4FEC5B380390 aCaption

ME ME_4FEC3F7C0075
 MEPROP Name 'aUseTooltip'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FEC3F7C0075 aUseTooltip

ME ME_4FEC3FA800A7
 MEPROP Name 'aRequireAutoPopup'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FEC3FA800A7 aRequireAutoPopup

ME ME_4FEC3D520241
 MEPROP Name 'anAutoPopupTimeout'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A618AF0053' '4807744200AA.ms.model.script' // Cardinal
 ;

ENDME // ME_4FEC3D520241 anAutoPopupTimeout

ME ME_4FEC5C8502D6
 MEPROP Name 'aToolTipKind'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_498035FA00E9' '490838E10313.ms.model.script' // TnscToolTipKind
 ;

ENDME // ME_4FEC5C8502D6 aToolTipKind

ME ME_4FEC3D2C02B2
 MEPROP UID '4FEC3D2C02B2'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4FEC3D23013F // Create
 ;
 MELIST Parameters
   Seq: ( ME_4FEC3D520137 // aShowCaption
 ME_4FEC5B380390 // aCaption
 ME_4FEC3F7C0075 // aUseTooltip
 ME_4FEC3FA800A7 // aRequireAutoPopup
 ME_4FEC3D520241 // anAutoPopupTimeout
 ME_4FEC5C8502D6 // aToolTipKind
 )
 ; // Parameters

ENDME // ME_4FEC3D2C02B2 DoIt

ME ME_4FEC3D23013F
 MEPROP UID '4FEC3D23013F'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 ;
 MELIST Operations
   Seq: ( HWL ME_4FEC3D2C02B2 // DoIt
 )
 ; // Operations

ENDME // ME_4FEC3D23013F Create

%%InheritedBy ME_4FEC3D23013F ME_4FEC3D9A0253

ME ME_4FEC3D9A0253
 MEPROP UID '4FEC3D9A0253'
 MEPROP Name 'Make'
 MEPROP Class class_Class
 MELINK Stereotype st_Factory ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 ;
 MELIST Inherits
   Seq: ( HWL ME_4FEC3D23013F // Create
 )
 ; // Inherits

ENDME // ME_4FEC3D9A0253 Make

ME ME_506039230134
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 ;
 MELINK Target WL 'ME_4DFF098B00CC' '4773D64E036C.ms.model.script' // l3Free
 ;

ENDME // ME_506039230134 

ME ME_4980370D001D_ME_4FEC3C34003F
 MELINK Original WL 'ME_4980370D001D' '490838E10313.ms.model.script' // Caption
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4980370D001D_ME_4FEC3C34003F Caption

ME ME_4980371E0167_ME_4FEC3C34003F
 MELINK Original WL 'ME_4980371E0167' '490838E10313.ms.model.script' // UseToolTip
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4980371E0167_ME_4FEC3C34003F UseToolTip

ME ME_4980372D0191_ME_4FEC3C34003F
 MELINK Original WL 'ME_4980372D0191' '490838E10313.ms.model.script' // RequireAutoPopup
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4980372D0191_ME_4FEC3C34003F RequireAutoPopup

ME ME_4980373B02B6_ME_4FEC3C34003F
 MELINK Original WL 'ME_4980373B02B6' '490838E10313.ms.model.script' // AutoPopupTimeout
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4980373B02B6_ME_4FEC3C34003F AutoPopupTimeout

ME ME_4980374B0266_ME_4FEC3C34003F
 MELINK Original WL 'ME_4980374B0266' '490838E10313.ms.model.script' // TootTipKind
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4980374B0266_ME_4FEC3C34003F TootTipKind

ME ME_4ADC59C6003B_ME_4FEC3C34003F
 MELINK Original WL 'ME_4ADC59C6003B' '490838E10313.ms.model.script' // ShowCaption
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4ADC59C6003B_ME_4FEC3C34003F ShowCaption

ME ME_4BCEAF1A00EE_ME_4FEC3C34003F
 MELINK Original WL 'ME_4BCEAF1A00EE' '490838E10313.ms.model.script' // Enabled
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4BCEAF1A00EE_ME_4FEC3C34003F Enabled

ME ME_5060385E0190_ME_4FEC3C34003F
 MELINK Original WL 'ME_5060385E0190' '490838E10313.ms.model.script' // SubscribedList
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_5060385E0190_ME_4FEC3C34003F SubscribedList

ME ME_5060388903AB_ME_4FEC3C34003F
 MELINK Original WL 'ME_5060388903AB' '490838E10313.ms.model.script' // SubscribeOnNotification
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5060388903AB_ME_4FEC3C34003F SubscribeOnNotification

ME ME_479731C50290_ME_4FEC3C34003F
 MELINK Original WL 'ME_479731C50290' '51612ED700B4.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_4FEC3C34003F Cleanup

%%ImplementedBy ME_4980350B00FA ME_4FEC3C34003F

%%InheritedBy ME_46780E690001 ME_4FEC3C34003F

ME ME_4FEC3C34003F
 MEPROP UID '4FEC3C34003F'
 MEPROP Name 'TnscStatusBarItemDef'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_49871D5103B9 // StatusBar
 ;
 MELIST Inherits
   Seq: ( WL 'ME_46780E690001' '47913B47006E.ms.model.script' // Tl3CacheableBase
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_4980350B00FA' '490838E10313.ms.model.script' // InscStatusBarItemDef
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_4FEC3F0F0322 // f_ShowCaption
 HWL ME_4FEC3F4A0347 // f_Caption
 HWL ME_4FEC3F64008C // f_UseTooltip
 HWL ME_4FEC3F860101 // f_RequireAutoPopup
 HWL ME_4FEC3FCD01D0 // f_AutoPopupTimeout
 HWL ME_4FEC400A012F // f_ToolTipKind
 HWL ME_4FEC54210207 // f_Enabled
 HWL ME_506038EB01CD // f_SubscribedList
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_4FEC3D23013F // Create
 HWL ME_4FEC3D9A0253 // Make
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_4980370D001D_ME_4FEC3C34003F // Caption
 ME_4980371E0167_ME_4FEC3C34003F // UseToolTip
 ME_4980372D0191_ME_4FEC3C34003F // RequireAutoPopup
 ME_4980373B02B6_ME_4FEC3C34003F // AutoPopupTimeout
 ME_4980374B0266_ME_4FEC3C34003F // TootTipKind
 ME_4ADC59C6003B_ME_4FEC3C34003F // ShowCaption
 ME_4BCEAF1A00EE_ME_4FEC3C34003F // Enabled
 ME_5060385E0190_ME_4FEC3C34003F // SubscribedList
 ME_5060388903AB_ME_4FEC3C34003F // SubscribeOnNotification
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_4FEC3C34003F // Cleanup
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_506039230134 // l3Free
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "no hands" true
 UP intf.pas:Path 'common\components\gui\Garant\Nemesis\nscStatusBarItemDef.pas'
 UP extprop:rc:SelfName 'StatusBarItemDef'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nscStatusBarItemDef'

ENDME // ME_4FEC3C34003F TnscStatusBarItemDef

FORWARD ME_4FEC3C5B007C

ME ME_4FF3275E0226
 MEPROP UID '4FF3275E0226'
 MEPROP Name 'f_SeparatorPos'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4FEC3C5B007C // TnscStatusBarDelimiterDef
 ;
 MELINK Target WL 'ME_4FF314BE007F' '490838E10313.ms.model.script' // TsbdSeparatorPos
 ;

ENDME // ME_4FF3275E0226 f_SeparatorPos

ME ME_4FF3277C03D5
 MEPROP UID '4FF3277C03D5'
 MEPROP Name 'f_SeparatorVisible'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4FEC3C5B007C // TnscStatusBarDelimiterDef
 ;
 MELINK Target WL 'ME_3DBFFE100240' '3DBFDB23006E.ms.model.script' // boolean
 ;

ENDME // ME_4FF3277C03D5 f_SeparatorVisible

ME ME_4FF3279603BB
 MEPROP UID '4FF3279603BB'
 MEPROP Name 'f_Width'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4FEC3C5B007C // TnscStatusBarDelimiterDef
 ;
 MELINK Target WL 'ME_450A61050251' '3DBFDB23006E.ms.model.script' // integer
 ;

ENDME // ME_4FF3279603BB f_Width

FORWARD ME_4FEC49660337

ME ME_4FF31C50019B
 MEPROP Name 'aSeparatorVisible'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_3DBFFE100240' '3DBFDB23006E.ms.model.script' // boolean
 ;

ENDME // ME_4FF31C50019B aSeparatorVisible

ME ME_4FF324EC0321
 MEPROP Name 'aSeparatorPos'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4FF314BE007F' '490838E10313.ms.model.script' // TsbdSeparatorPos
 ;
 MEPROP Value 'spMiddle'
 MELINK ValueType WL 'ME_4FF314BE007F' '490838E10313.ms.model.script' // TsbdSeparatorPos
 ;
 UP extprop:pas:Value 'nscNewInterfaces.spMiddle'

ENDME // ME_4FF324EC0321 aSeparatorPos

ME ME_4FF324EC0390
 MEPROP Name 'aWidth'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;
 MEPROP Value 0
 MELINK ValueType WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;
 UP extprop:pas:Value 0

ENDME // ME_4FF324EC0390 aWidth

ME ME_4FEC497001EF
 MEPROP UID '4FEC497001EF'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4FEC49660337 // Create
 ;
 MELIST Parameters
   Seq: ( ME_4FF31C50019B // aSeparatorVisible
 ME_4FF324EC0321 // aSeparatorPos
 ME_4FF324EC0390 // aWidth
 )
 ; // Parameters

ENDME // ME_4FEC497001EF DoIt

ME ME_4FEC49660337
 MEPROP UID '4FEC49660337'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4FEC3C5B007C // TnscStatusBarDelimiterDef
 ;
 MELIST Operations
   Seq: ( HWL ME_4FEC497001EF // DoIt
 )
 ; // Operations

ENDME // ME_4FEC49660337 Create

%%InheritedBy ME_4FEC49660337 ME_4FEC4982036E

ME ME_4FEC4982036E
 MEPROP UID '4FEC4982036E'
 MEPROP Name 'Make'
 MEPROP Class class_Class
 MELINK Stereotype st_Factory ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4FEC3C5B007C // TnscStatusBarDelimiterDef
 ;
 MELIST Inherits
   Seq: ( HWL ME_4FEC49660337 // Create
 )
 ; // Inherits

ENDME // ME_4FEC4982036E Make

ME ME_4FF315450358_ME_4FEC3C5B007C
 MELINK Original WL 'ME_4FF315450358' '490838E10313.ms.model.script' // SeparatorPos
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4FF315450358_ME_4FEC3C5B007C SeparatorPos

ME ME_4FF3157D0385_ME_4FEC3C5B007C
 MELINK Original WL 'ME_4FF3157D0385' '490838E10313.ms.model.script' // IsSeparatorVisible
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4FF3157D0385_ME_4FEC3C5B007C IsSeparatorVisible

ME ME_4FF3159402B4_ME_4FEC3C5B007C
 MELINK Original WL 'ME_4FF3159402B4' '490838E10313.ms.model.script' // Width
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4FF3159402B4_ME_4FEC3C5B007C Width

%%ImplementedBy ME_4FEC3BB5027F ME_4FEC3C5B007C

%%InheritedBy ME_4FEC3C34003F ME_4FEC3C5B007C

ME ME_4FEC3C5B007C
 MEPROP UID '4FEC3C5B007C'
 MEPROP Name 'TnscStatusBarDelimiterDef'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_49871D5103B9 // StatusBar
 ;
 MELIST Inherits
   Seq: ( HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_4FEC3BB5027F' '490838E10313.ms.model.script' // InscStatusBarDelimiterDef
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_4FF3275E0226 // f_SeparatorPos
 HWL ME_4FF3277C03D5 // f_SeparatorVisible
 HWL ME_4FF3279603BB // f_Width
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_4FEC49660337 // Create
 HWL ME_4FEC4982036E // Make
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_4FF315450358_ME_4FEC3C5B007C // SeparatorPos
 ME_4FF3157D0385_ME_4FEC3C5B007C // IsSeparatorVisible
 ME_4FF3159402B4_ME_4FEC3C5B007C // Width
 )
 ; // Implemented
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "no hands" true
 UP intf.pas:Path 'common\components\gui\Garant\Nemesis\nscStatusBarDelimiterDef.pas'
 UP extprop:rc:SelfName 'StatusBarDelimiterDef'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nscStatusBarDelimiterDef'

ENDME // ME_4FEC3C5B007C TnscStatusBarDelimiterDef

FORWARD ME_49871E4F01AF

ME ME_4FEC4A090334
 MEPROP UID '4FEC4A090334'
 MEPROP Name 'f_Operation'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_49871E4F01AF // TnscStatusBarOperationDef
 ;
 MELINK Target WL 'ME_4683D016009C' '467BAB7F021E.ms.model.script' // TvcmOpSelector
 ;

ENDME // ME_4FEC4A090334 f_Operation

FORWARD ME_4FEC4A26030E

ME ME_4FEC64C10123
 MEPROP Name 'anOperation'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4683D016009C' '467BAB7F021E.ms.model.script' // TvcmOpSelector
 ;

ENDME // ME_4FEC64C10123 anOperation

ME ME_4FEC4A460157
 MEPROP Name 'aShowCaption'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FEC4A460157 aShowCaption

ME ME_4FF59DCB00B8
 MEPROP Name 'aCaption'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_4FF59DCB00B8 aCaption

ME ME_4FEC4A5F0105
 MEPROP Name 'aUseToolTip'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FEC4A5F0105 aUseToolTip

ME ME_4FEC4A5F0161
 MEPROP Name 'aRequireAutoPopup'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FEC4A5F0161 aRequireAutoPopup

ME ME_4FEC4A46025E
 MEPROP Name 'anAutoPopupTimeout'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A618AF0053' '4807744200AA.ms.model.script' // Cardinal
 ;

ENDME // ME_4FEC4A46025E anAutoPopupTimeout

ME ME_4FEC5C7002A9
 MEPROP Name 'aToolTipKind'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_498035FA00E9' '490838E10313.ms.model.script' // TnscToolTipKind
 ;

ENDME // ME_4FEC5C7002A9 aToolTipKind

ME ME_4FEC4A3F0164
 MEPROP UID '4FEC4A3F0164'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4FEC4A26030E // Create
 ;
 MELIST Parameters
   Seq: ( ME_4FEC64C10123 // anOperation
 ME_4FEC4A460157 // aShowCaption
 ME_4FF59DCB00B8 // aCaption
 ME_4FEC4A5F0105 // aUseToolTip
 ME_4FEC4A5F0161 // aRequireAutoPopup
 ME_4FEC4A46025E // anAutoPopupTimeout
 ME_4FEC5C7002A9 // aToolTipKind
 )
 ; // Parameters

ENDME // ME_4FEC4A3F0164 DoIt

ME ME_4FEC4A26030E
 MEPROP UID '4FEC4A26030E'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_49871E4F01AF // TnscStatusBarOperationDef
 ;
 MELIST Operations
   Seq: ( HWL ME_4FEC4A3F0164 // DoIt
 )
 ; // Operations

ENDME // ME_4FEC4A26030E Create

%%InheritedBy ME_4FEC4A26030E ME_4FEC4A6C02E8

ME ME_4FEC4A6C02E8
 MEPROP UID '4FEC4A6C02E8'
 MEPROP Name 'Make'
 MEPROP Class class_Class
 MELINK Stereotype st_Factory ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_49871E4F01AF // TnscStatusBarOperationDef
 ;
 MELIST Inherits
   Seq: ( HWL ME_4FEC4A26030E // Create
 )
 ; // Inherits

ENDME // ME_4FEC4A6C02E8 Make

FORWARD ME_4FEC5B7B00CE

ME ME_4FEC5F360324
 MEPROP Name 'anOperation'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4683CF3401F5' '467BAB7F021E.ms.model.script' // TvcmOPID
 ;

ENDME // ME_4FEC5F360324 anOperation

ME ME_4FEC60EA0174
 MEPROP Name 'aShowCaption'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FEC60EA0174 aShowCaption

ME ME_4FEC60EA019B
 MEPROP Name 'aCaption'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4683F4B103DC' '4683F37902CF.ms.model.script' // TvcmStringID
 ;

ENDME // ME_4FEC60EA019B aCaption

ME ME_4FEC6E2D008D
 MEPROP Name 'aUseToolTip'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FEC6E2D008D aUseToolTip

ME ME_4FEC60EA01EA
 MEPROP Name 'aRequireAutoPopup'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FEC60EA01EA aRequireAutoPopup

ME ME_4FEC60EA0212
 MEPROP Name 'anAutoPopupTimeout'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A618AF0053' '4807744200AA.ms.model.script' // Cardinal
 ;

ENDME // ME_4FEC60EA0212 anAutoPopupTimeout

ME ME_4FEC6E2D00F3
 MEPROP Name 'aToolTipKind'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_498035FA00E9' '490838E10313.ms.model.script' // TnscToolTipKind
 ;

ENDME // ME_4FEC6E2D00F3 aToolTipKind

ME ME_4FEC5BBA0070
 MEPROP UID '4FEC5BBA0070'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4FEC5B7B00CE // MakeS
 ;
 MELINK Target WL 'ME_4FE9F428027C' '490838E10313.ms.model.script' // InscStatusBarOperationDef
 ;
 MELIST Parameters
   Seq: ( ME_4FEC5F360324 // anOperation
 ME_4FEC60EA0174 // aShowCaption
 ME_4FEC60EA019B // aCaption
 ME_4FEC6E2D008D // aUseToolTip
 ME_4FEC60EA01EA // aRequireAutoPopup
 ME_4FEC60EA0212 // anAutoPopupTimeout
 ME_4FEC6E2D00F3 // aToolTipKind
 )
 ; // Parameters

ENDME // ME_4FEC5BBA0070 DoIt

ME ME_4FEC5B7B00CE
 MEPROP UID '4FEC5B7B00CE'
 MEPROP Name 'MakeS'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_49871E4F01AF // TnscStatusBarOperationDef
 ;
 MELIST Operations
   Seq: ( HWL ME_4FEC5BBA0070 // DoIt
 )
 ; // Operations
 UP "is static" true

ENDME // ME_4FEC5B7B00CE MakeS

FORWARD ME_4FF59E080381

ME ME_4FF59E2F01CE
 MEPROP Name 'anOperation'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4683CF3401F5' '467BAB7F021E.ms.model.script' // TvcmOPID
 ;

ENDME // ME_4FF59E2F01CE anOperation

ME ME_4FF59E2F0241
 MEPROP Name 'aUseToolTip'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FF59E2F0241 aUseToolTip

ME ME_4FF59E2F0268
 MEPROP Name 'aRequireAutoPopup'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FF59E2F0268 aRequireAutoPopup

ME ME_4FF59E2F0292
 MEPROP Name 'anAutoPopupTimeout'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A618AF0053' '4807744200AA.ms.model.script' // Cardinal
 ;

ENDME // ME_4FF59E2F0292 anAutoPopupTimeout

ME ME_4FF59E2F02BB
 MEPROP Name 'aToolTipKind'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_498035FA00E9' '490838E10313.ms.model.script' // TnscToolTipKind
 ;

ENDME // ME_4FF59E2F02BB aToolTipKind

ME ME_4FF59E2D0301
 MEPROP UID '4FF59E2D0301'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4FF59E080381 // MakeSDefaultCaption
 ;
 MELINK Target WL 'ME_4FE9F428027C' '490838E10313.ms.model.script' // InscStatusBarOperationDef
 ;
 MELIST Parameters
   Seq: ( ME_4FF59E2F01CE // anOperation
 ME_4FF59E2F0241 // aUseToolTip
 ME_4FF59E2F0268 // aRequireAutoPopup
 ME_4FF59E2F0292 // anAutoPopupTimeout
 ME_4FF59E2F02BB // aToolTipKind
 )
 ; // Parameters

ENDME // ME_4FF59E2D0301 DoIt

ME ME_4FF59E080381
 MEPROP UID '4FF59E080381'
 MEPROP Name 'MakeSDefaultCaption'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_49871E4F01AF // TnscStatusBarOperationDef
 ;
 MELIST Operations
   Seq: ( HWL ME_4FF59E2D0301 // DoIt
 )
 ; // Operations
 UP "is static" true

ENDME // ME_4FF59E080381 MakeSDefaultCaption

FORWARD ME_4FFAFB0B03CC

ME ME_4FFAFB22021E
 MEPROP Name 'anOperation'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4683CF3401F5' '467BAB7F021E.ms.model.script' // TvcmOPID
 ;

ENDME // ME_4FFAFB22021E anOperation

ME ME_4FFAFB220243
 MEPROP Name 'aUseToolTip'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FFAFB220243 aUseToolTip

ME ME_4FFAFB220268
 MEPROP Name 'aRequireAutoPopup'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4FFAFB220268 aRequireAutoPopup

ME ME_4FFAFB22028E
 MEPROP Name 'anAutoPopupTimeout'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A618AF0053' '4807744200AA.ms.model.script' // Cardinal
 ;

ENDME // ME_4FFAFB22028E anAutoPopupTimeout

ME ME_4FFAFB2202B5
 MEPROP Name 'aToolTipKind'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_498035FA00E9' '490838E10313.ms.model.script' // TnscToolTipKind
 ;

ENDME // ME_4FFAFB2202B5 aToolTipKind

ME ME_4FFAFB1F038C
 MEPROP UID '4FFAFB1F038C'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4FFAFB0B03CC // MakeSNoCaption
 ;
 MELINK Target WL 'ME_4FE9F428027C' '490838E10313.ms.model.script' // InscStatusBarOperationDef
 ;
 MELIST Parameters
   Seq: ( ME_4FFAFB22021E // anOperation
 ME_4FFAFB220243 // aUseToolTip
 ME_4FFAFB220268 // aRequireAutoPopup
 ME_4FFAFB22028E // anAutoPopupTimeout
 ME_4FFAFB2202B5 // aToolTipKind
 )
 ; // Parameters

ENDME // ME_4FFAFB1F038C DoIt

ME ME_4FFAFB0B03CC
 MEPROP UID '4FFAFB0B03CC'
 MEPROP Name 'MakeSNoCaption'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_49871E4F01AF // TnscStatusBarOperationDef
 ;
 MELIST Operations
   Seq: ( HWL ME_4FFAFB1F038C // DoIt
 )
 ; // Operations
 UP "is static" true

ENDME // ME_4FFAFB0B03CC MakeSNoCaption

ME ME_4FEC6C0702BD
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_49871E4F01AF // TnscStatusBarOperationDef
 ;
 MELINK Target WL 'ME_4AC0B9CF018A' '47F25BC801DB.ms.model.script' // vcmCStr
 ;

ENDME // ME_4FEC6C0702BD 

ME ME_4FE9F49C0299_ME_49871E4F01AF
 MELINK Original WL 'ME_4FE9F49C0299' '490838E10313.ms.model.script' // Operation
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4FE9F49C0299_ME_49871E4F01AF Operation

%%ImplementedBy ME_4FE9F428027C ME_49871E4F01AF

%%InheritedBy ME_4FEC3C34003F ME_49871E4F01AF

ME ME_49871E4F01AF
 MEPROP UID '49871E4F01AF'
 MEPROP Name 'TnscStatusBarOperationDef'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_49871D5103B9 // StatusBar
 ;
 MELIST Inherits
   Seq: ( HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_4FE9F428027C' '490838E10313.ms.model.script' // InscStatusBarOperationDef
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_4FEC4A090334 // f_Operation
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_4FEC4A26030E // Create
 HWL ME_4FEC4A6C02E8 // Make
 HWL ME_4FEC5B7B00CE // MakeS
 HWL ME_4FF59E080381 // MakeSDefaultCaption
 HWL ME_4FFAFB0B03CC // MakeSNoCaption
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_4FE9F49C0299_ME_49871E4F01AF // Operation
 )
 ; // Implemented
 MELIST Dependencies
   Seq: ( ME_4FEC6C0702BD // vcmCStr
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "no hands" true
 UP intf.pas:Path 'common\components\gui\Garant\Nemesis\nscStatusBarOperationDef.pas'
 UP extprop:rc:SelfName 'StatusBarOperationDef'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nscStatusBarOperationDef'

ENDME // ME_49871E4F01AF TnscStatusBarOperationDef

ME ME_49871D5103B9
 MEPROP UID '49871D5103B9'
 MEPROP Name 'StatusBar'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Views ;
 %SUMMARY 'Работа со строкой состояния' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_490838AA02D0' // Nemesis
 ;
 MELIST Children
   Seq: ( HWL ME_49871E3F01D0 // TnscStatusBarOperationDefsList
 WL? 'ME_4E15A08E030D' // TnscStatusBar
 HWL ME_4FEC3C34003F // TnscStatusBarItemDef
 HWL ME_4FEC3C5B007C // TnscStatusBarDelimiterDef
 HWL ME_49871E4F01AF // TnscStatusBarOperationDef
 WL? 'ME_5058B67D0085' // TnscSizeGripPanel
 WL? 'ME_503DE6F30027' // TnscStatusBarButton
 WL? 'ME_503DEACA03BB' // TnscStatusBarPanel
 WL? 'ME_5058B74F01A1' // TnscStatusBarSep
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4677FBA70343' // l3Interfaces
 WL? 'ME_467823B7002C' // afwInterfaces
 WL? 'ME_467BAB7F021E' // vcmExternalInterfaces
 WL? 'ME_4683F37902CF' // vcmInterfaces
 WL? 'ME_476F78840219' // Messages
 WL? 'ME_47750CE700D0' // afwFacade
 WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_4799D29F033F' // Implementation
 WL? 'ME_47BB24D30205' // Стандартные примеси
 WL? 'ME_47D0E1500033' // Implementation
 WL? 'ME_490838E10313' // nscNewInterfaces
 WL? 'ME_4A6D65B9022A' // Containers
 WL? 'ME_4AADF9450143' // Visual
 WL? 'ME_4AB0997B00A2' // Common
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_4AB34028023E' // Components
 WL? 'ME_4C43E8750153' // Buttons
 WL? 'ME_4E159FE900E2' // StatusBar
 WL? 'ME_4F635E1901E5' // l3Listeners
 WL? 'ME_5028887002FD' // Toolbar
 WL? 'ME_5028898902A2' // tb97utils
 WL? 'ME_505DA8FC03CF' // StatusBarUtils
 WL? 'ME_537B83AD01F0' // l3Math
 WL? 'ME_54B90AC6014B' // StringUtils
 WL? 'ME_55C4AEC801CA' // Graphics
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "UseNewGen" true

ENDME // ME_49871D5103B9 StatusBar
