// Tree 499C0BD60338 TestUnit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_499C0BD60338

FORWARD ME_499C0C1A009E

: ME_499C0C240318
 CONST UID '499C0C240318'
 CONST Name 'CurrentNodeLevel'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_lnk
 : Parent ME_499C0C1A009E // TeeTreeViewExport
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_499C0C240318 CurrentNodeLevel

: ME_499C0C3600B4
 CONST UID '499C0C3600B4'
 CONST Name 'CurrentNodeIndex'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_lnk
 : Parent ME_499C0C1A009E // TeeTreeViewExport
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_499C0C3600B4 CurrentNodeIndex

: ME_499C0C420199
 CONST UID '499C0C420199'
 CONST Name 'CurrentNodeExpanded'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_lnk
 : Parent ME_499C0C1A009E // TeeTreeViewExport
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_499C0C420199 CurrentNodeExpanded

: ME_499C1DC600BD
 CONST UID '499C1DC600BD'
 CONST Name 'IsCurrentOperationEnabled'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Эта функция регистрируется на TeeTreeViewExport, хотя по хорошему надо бы на'#13#10'TnscTasksPanelTreeView, но этот класс объявлен в implementation секции модуля'#13#10'nscTasksPanelView и недоступен. Поэтому, свойство будет существовать практически для всех деревьев, но будет иметь смысл только если его получать в дереве Панели задач, на других деревьях будет пустое (Empty) значение' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_lnk
 : Parent ME_499C0C1A009E // TeeTreeViewExport
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_499C1DC600BD IsCurrentOperationEnabled

: ME_499C1E8801DF
 CONST UID '499C1E8801DF'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_499C0C1A009E // TeeTreeViewExport
 ;
 : Target WL 'ME_499C1A4E03C8' '499C1A100121.pas.ms.script' // InscOperationNode
 ;

ref; // ME_499C1E8801DF 

: ME_499C204C003F
 CONST UID '499C204C003F'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_499C0C1A009E // TeeTreeViewExport
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_499C204C003F 

: ME_46A5AA4B003C_ME_499C0C1A009E
 CONST UID '46A5AA4B003C'
 CONST Name 'Invalidate'
 : Original WL 'ME_46A5AA4B003C' '4677FBA70343.pas.ms.script' // Invalidate
 ;
 : Implementor ME_499C0C1A009E // TeeTreeViewExport
 ;
ref; // ME_46A5AA4B003C_ME_499C0C1A009E Invalidate

: ME_477243870072_ME_499C0C1A009E
 CONST UID '477243870072'
 CONST Name 'RootChanged'
 : Original WL 'ME_477243870072' '4682595B0268.pas.ms.script' // RootChanged
 ;
 : Implementor ME_499C0C1A009E // TeeTreeViewExport
 ;
ref; // ME_477243870072_ME_499C0C1A009E RootChanged

: ME_499C0C1A009E
 CONST UID '499C0C1A009E'
 CONST Name 'TeeTreeViewExport'
 CONST Class class_Class
 : Stereotype st_TestClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_499C0BD60338 // Tree
 ;
 : Inherits
   @ ( WL 'ME_499C0B7B012E' '494B947D0127.pas.ms.script' // TeeTreeViewExport
 ) .SequenceCode.It
 ; // Inherits
 : Attributes
   @ ( ME_499C0C240318 // CurrentNodeLevel
 ME_499C0C3600B4 // CurrentNodeIndex
 ME_499C0C420199 // CurrentNodeExpanded
 ME_499C1DC600BD // IsCurrentOperationEnabled
 ) .SequenceCode.It
 ; // Attributes
 : Implemented
   @ ( ME_46A5AA4B003C_ME_499C0C1A009E // Invalidate
 ME_477243870072_ME_499C0C1A009E // RootChanged
 ) .SequenceCode.It
 ; // Implemented
 : Dependencies
   @ ( ME_499C1E8801DF // 
 ME_499C204C003F // 
 ) .SequenceCode.It
 ; // Dependencies
 CONST "is friend" false
 : Generators
 @ (
 gen_intf.pas
 ) .SequenceCode.It
 ; // Generators
 CONST intf.pas:Path 'common\components\gui\Garant\Nemesis\eeTreeViewExport_p.pas'

ref; // ME_499C0C1A009E TeeTreeViewExport

: ME_499C0BD60338
 CONST UID '499C0BD60338'
 CONST Name 'Tree'
 CONST Class class_Category
 : Stereotype st_TestUnit ;
 %SUMMARY 'Тесты деревьев' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_499ABFAA038C' '499ABFAA038C.pas.ms.script' // NemesisTest
 ;
 : Children
   @ ( ME_499C0C1A009E // TeeTreeViewExport
 ) .SequenceCode.It
 ; // Children
 : Depends
   @ ( WL 'ME_494B947D0127' '494B947D0127.pas.ms.script' // Tree
 WL 'ME_499C1A100121' '499C1A100121.pas.ms.script' // nscTaskPanelInterfaces
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 ) .SequenceCode.It
 ; // Depends
 : Generators
 @ (
 gen_pas.script
 gen_pas.script.runner
 ) .SequenceCode.It
 ; // Generators
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\499C0BD60338.pas.ms.script'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\499C0BD60338.pas.ms.script.runner'

ref; // ME_499C0BD60338 Tree
