// vcmUserControls 499EAAE502A8 Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_499EAAE502A8

FORWARD ME_499560120345

: ME_499E958E03B0
 CONST UID '499E958E03B0'
 CONST Name 'Caption'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'пользовательское имя объекта' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_499560120345 // IvcmBaseObjectDef
 ;
 : Target WL 'ME_4683C9AC03AC' '467BAB7F021E.pas.ms.script' // IvcmCString
 ;
 CONST "pm" false

ref; // ME_499E958E03B0 Caption

: ME_499E95A60064
 CONST UID '499E95A60064'
 CONST Name 'Name'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'имя объекта' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_499560120345 // IvcmBaseObjectDef
 ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;
 CONST "pm" false

ref; // ME_499E95A60064 Name

: ME_499560120345
 CONST UID '499560120345'
 CONST GUID 'C2874075-FAA7-4C00-B3BE-F6FD56ED5433'
 CONST Name 'IvcmBaseObjectDef'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_499EAAE502A8 // vcmUserControls
 ;
 : Inherits
   Seq: ( WL 'ME_4683CEAD00CF' '467BAB7F021E.pas.ms.script' // IvcmBase
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_499E958E03B0 // Caption
 ME_499E95A60064 // Name
 )
 ; // Attributes
 CONST extprop:rc:SelfName 'ObjectDef'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_499560120345 IvcmBaseObjectDef

FORWARD ME_499301BF0067

: ME_499561850334
 CONST UID '499561850334'
 CONST Name 'ImageIndex'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_499301BF0067 // IvcmUserFriendlyControl
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "pm" false

ref; // ME_499561850334 ImageIndex

: ME_4995616701BB
 CONST UID '4995616701BB'
 CONST Name 'Hint'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'подсказка для пункта меню, представляющего объект' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_499301BF0067 // IvcmUserFriendlyControl
 ;
 : Target WL 'ME_4683C9AC03AC' '467BAB7F021E.pas.ms.script' // IvcmCString
 ;
 CONST "pm" false

ref; // ME_4995616701BB Hint

: ME_4995617802E8
 CONST UID '4995617802E8'
 CONST Name 'LongHint'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'детальная подсказка для пункта меню, представляющего объект' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_499301BF0067 // IvcmUserFriendlyControl
 ;
 : Target WL 'ME_4683C9AC03AC' '467BAB7F021E.pas.ms.script' // IvcmCString
 ;
 CONST "pm" false

ref; // ME_4995617802E8 LongHint

: ME_499E958E03B0_ME_499301BF0067
 : Original ME_499E958E03B0 // Caption
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499E958E03B0_ME_499301BF0067 Caption

: ME_499E95A60064_ME_499301BF0067
 : Original ME_499E95A60064 // Name
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499E95A60064_ME_499301BF0067 Name

: ME_499301BF0067
 CONST UID '499301BF0067'
 CONST GUID 'F12A7495-DA83-4EEE-A5C1-77957F72E98A'
 CONST Name 'IvcmUserFriendlyControl'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Базовый интерфейс для объектов имеющих отображение для пользователя' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_499EAAE502A8 // vcmUserControls
 ;
 : Inherits
   Seq: ( ME_499560120345 // IvcmBaseObjectDef
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_499561850334 // ImageIndex
 ME_4995616701BB // Hint
 ME_4995617802E8 // LongHint
 )
 ; // Attributes
 : Implemented
   Seq: ( ME_499E958E03B0_ME_499301BF0067 // Caption
 ME_499E95A60064_ME_499301BF0067 // Name
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'UserFriendlyControl'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_499301BF0067 IvcmUserFriendlyControl

FORWARD ME_4995619C030A

: ME_499561F90285
 CONST UID '499561F90285'
 CONST Name 'ID'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'идентификатор объекта' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995619C030A // IvcmIdentifiedUserFriendlyControl
 ;
 : Target WL 'ME_4683C8750015' '467BAB7F021E.pas.ms.script' // TvcmControlID
 ;
 CONST "pm" false

ref; // ME_499561F90285 ID

: ME_4995616701BB_ME_4995619C030A
 : Original ME_4995616701BB // Hint
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4995616701BB_ME_4995619C030A Hint

: ME_4995617802E8_ME_4995619C030A
 : Original ME_4995617802E8 // LongHint
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4995617802E8_ME_4995619C030A LongHint

: ME_499561850334_ME_4995619C030A
 : Original ME_499561850334 // ImageIndex
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499561850334_ME_4995619C030A ImageIndex

: ME_499E958E03B0_ME_4995619C030A
 : Original ME_499E958E03B0 // Caption
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499E958E03B0_ME_4995619C030A Caption

: ME_499E95A60064_ME_4995619C030A
 : Original ME_499E95A60064 // Name
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499E95A60064_ME_4995619C030A Name

: ME_4995619C030A
 CONST UID '4995619C030A'
 CONST GUID '218D3AE5-6CA7-4CF3-B27B-B277C74C4165'
 CONST Name 'IvcmIdentifiedUserFriendlyControl'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Базовый интерфейс для объектов имеющих отображение для пользователя и идентификатор' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_499EAAE502A8 // vcmUserControls
 ;
 : Inherits
   Seq: ( ME_499301BF0067 // IvcmUserFriendlyControl
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_499561F90285 // ID
 )
 ; // Attributes
 : Implemented
   Seq: ( ME_4995616701BB_ME_4995619C030A // Hint
 ME_4995617802E8_ME_4995619C030A // LongHint
 ME_499561850334_ME_4995619C030A // ImageIndex
 ME_499E958E03B0_ME_4995619C030A // Caption
 ME_499E95A60064_ME_4995619C030A // Name
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'IdentifiedUserFriendlyControl'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4995619C030A IvcmIdentifiedUserFriendlyControl

FORWARD ME_4995624100A6

FORWARD ME_4683F5BC0213

: ME_4683F5CE0205
 CONST UID '4683F5CE0205'
 CONST Name 'vcm_ooShowInMainToolbar'
 CONST Class class_Attribute
 %SUMMARY 'Операция будет показана на панели'#13#10'                                  инструментов главной формы' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4683F5BC0213 // TvcmOperationOption
 ;

ref; // ME_4683F5CE0205 vcm_ooShowInMainToolbar

: ME_4683F5DC03BE
 CONST UID '4683F5DC03BE'
 CONST Name 'vcm_ooShowInChildToolbar'
 CONST Class class_Attribute
 %SUMMARY 'Операция будет показана на панели'#13#10'                                  инструментов формы сущности' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4683F5BC0213 // TvcmOperationOption
 ;

ref; // ME_4683F5DC03BE vcm_ooShowInChildToolbar

: ME_4683F5EB021B
 CONST UID '4683F5EB021B'
 CONST Name 'vcm_ooShowInContextMenu'
 CONST Class class_Attribute
 %SUMMARY 'Операция будет показана в контекстном меню' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4683F5BC0213 // TvcmOperationOption
 ;

ref; // ME_4683F5EB021B vcm_ooShowInContextMenu

: ME_4683F5FE0150
 CONST UID '4683F5FE0150'
 CONST Name 'vcm_ooShowInMainMenu'
 CONST Class class_Attribute
 %SUMMARY 'Операция будет показана в главном меню'#13#10'                                  главной формы.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4683F5BC0213 // TvcmOperationOption
 ;

ref; // ME_4683F5FE0150 vcm_ooShowInMainMenu

: ME_4683F63302BF
 CONST UID '4683F63302BF'
 CONST Name 'vcm_ooShowInChildMenu'
 CONST Class class_Attribute
 %SUMMARY 'Операция будет показана в меню формы'#13#10'                                  сущности' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4683F5BC0213 // TvcmOperationOption
 ;

ref; // ME_4683F63302BF vcm_ooShowInChildMenu

: ME_4683F5BC0213
 CONST UID '4683F5BC0213'
 CONST Name 'TvcmOperationOption'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Режим отбражения операции в меню и на панели инструментов.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Attributes
   Seq: ( ME_4683F5CE0205 // vcm_ooShowInMainToolbar
 ME_4683F5DC03BE // vcm_ooShowInChildToolbar
 ME_4683F5EB021B // vcm_ooShowInContextMenu
 ME_4683F5FE0150 // vcm_ooShowInMainMenu
 ME_4683F63302BF // vcm_ooShowInChildMenu
 )
 ; // Attributes
 CONST "force usage" true
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4683F5BC0213 TvcmOperationOption

FORWARD ME_4683F5860071

: ME_4683F59301F6
 CONST UID '4683F59301F6'
 CONST Name 'vcm_omTest'
 CONST Class class_Attribute
 %SUMMARY 'Режим проверки доступности операции' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4683F5860071 // TvcmOperationMode
 ;

ref; // ME_4683F59301F6 vcm_omTest

: ME_4683F5A100A2
 CONST UID '4683F5A100A2'
 CONST Name 'vcm_omExecute'
 CONST Class class_Attribute
 %SUMMARY 'Режим непосредственного выполенения'#13#10'                      операции' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4683F5860071 // TvcmOperationMode
 ;

ref; // ME_4683F5A100A2 vcm_omExecute

: ME_4683F5AD0027
 CONST UID '4683F5AD0027'
 CONST Name 'vcm_omAggregateExecute'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4683F5860071 // TvcmOperationMode
 ;

ref; // ME_4683F5AD0027 vcm_omAggregateExecute

: ME_4683F5860071
 CONST UID '4683F5860071'
 CONST Name 'TvcmOperationMode'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Режим выполнения операции.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Attributes
   Seq: ( ME_4683F59301F6 // vcm_omTest
 ME_4683F5A100A2 // vcm_omExecute
 ME_4683F5AD0027 // vcm_omAggregateExecute
 )
 ; // Attributes
 CONST "force usage" true
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4683F5860071 TvcmOperationMode

FORWARD ME_4992F7350274

: ME_4992F73C02B1
 CONST UID '4992F73C02B1'
 CONST Name 'vcm_octShortCut'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4992F7350274 // TvcmOperationCallType
 ;

ref; // ME_4992F73C02B1 vcm_octShortCut

: ME_4992F7410143
 CONST UID '4992F7410143'
 CONST Name 'vcm_octMainMenu'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4992F7350274 // TvcmOperationCallType
 ;

ref; // ME_4992F7410143 vcm_octMainMenu

: ME_4992F74600EC
 CONST UID '4992F74600EC'
 CONST Name 'vcm_octContextMenu'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4992F7350274 // TvcmOperationCallType
 ;

ref; // ME_4992F74600EC vcm_octContextMenu

: ME_4992F74C0019
 CONST UID '4992F74C0019'
 CONST Name 'vcm_octToolbar'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4992F7350274 // TvcmOperationCallType
 ;

ref; // ME_4992F74C0019 vcm_octToolbar

: ME_4992F7350274
 CONST UID '4992F7350274'
 CONST Name 'TvcmOperationCallType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Attributes
   Seq: ( ME_4992F73C02B1 // vcm_octShortCut
 ME_4992F7410143 // vcm_octMainMenu
 ME_4992F74600EC // vcm_octContextMenu
 ME_4992F74C0019 // vcm_octToolbar
 )
 ; // Attributes
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4992F7350274 TvcmOperationCallType

FORWARD ME_47F2534B010F

: ME_4992F8F40195
 CONST UID '4992F8F40195'
 CONST Name 'First'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47F2534B010F // TvcmUserType
 ;
 CONST Value 0
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 0

ref; // ME_4992F8F40195 First

: ME_4992F8FC03BF
 CONST UID '4992F8FC03BF'
 CONST Name 'Last'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_47F2534B010F // TvcmUserType
 ;
 CONST Value 31
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 31

ref; // ME_4992F8FC03BF Last

: ME_47F2534B010F
 CONST UID '47F2534B010F'
 CONST Name 'TvcmUserType'
 CONST Class class_Class
 : Stereotype st_Range ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Тип формы.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Inherits
   Seq: ( WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_4992F8F40195 // First
 ME_4992F8FC03BF // Last
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_47F2534B010F TvcmUserType

: ME_4992F915036D
 CONST UID '4992F915036D'
 CONST Name 'TvcmUserTypes'
 CONST Class class_Class
 : Stereotype st_SetOf ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Inherits
   Seq: ( ME_47F2534B010F // TvcmUserType
 )
 ; // Inherits

ref; // ME_4992F915036D TvcmUserTypes

: ME_51E00A6B0010
 CONST UID '51E00A6B0010'
 CONST Name 'TvcmOperationOptions'
 CONST Class class_Class
 : Stereotype st_SetOf ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Inherits
   Seq: ( ME_4683F5BC0213 // TvcmOperationOption
 )
 ; // Inherits

ref; // ME_51E00A6B0010 TvcmOperationOptions

: ME_49956402012E
 CONST UID '49956402012E'
 CONST Name 'VisibleToUser'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" false

ref; // ME_49956402012E VisibleToUser

: ME_4995640A00AE
 CONST UID '4995640A00AE'
 CONST Name 'IsCaptionUnique'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'определяет является ли имя операции уникальным в пределах всех'#13#10'             операций формы' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" false

ref; // ME_4995640A00AE IsCaptionUnique

: ME_49956423028E
 CONST UID '49956423028E'
 CONST Name 'StatesCount'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "pm" false

ref; // ME_49956423028E StatesCount

: ME_499564440267
 CONST UID '499564440267'
 CONST Name 'IsDefault'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" false

ref; // ME_499564440267 IsDefault

: ME_499D8B6E01F5
 CONST UID '499D8B6E01F5'
 CONST Name 'GroupID'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'группа внутри категории' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "pm" false

ref; // ME_499D8B6E01F5 GroupID

: ME_4995621C01EE
 CONST UID '4995621C01EE'
 CONST Name 'Category'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'категория объекта' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;
 CONST "pm" false

ref; // ME_4995621C01EE Category

: ME_499562870140
 CONST UID '499562870140'
 CONST Name 'OperationType'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target WL 'ME_4683CC350070' '467BAB7F021E.pas.ms.script' // TvcmOperationType
 ;
 CONST "pm" false

ref; // ME_499562870140 OperationType

: ME_499562ED0005
 CONST UID '499562ED0005'
 CONST Name 'ShortCut'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target WL 'ME_499562B802E7' '4AB0997B00A2.pas.ms.script' // TShortCut
 ;
 CONST "pm" false

ref; // ME_499562ED0005 ShortCut

: ME_499563A80185
 CONST UID '499563A80185'
 CONST Name 'SecondaryShortCuts'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target WL 'ME_499563790006' '4799D29F033F.pas.ms.script' // TShortCutList
 ;
 CONST "pm" false

ref; // ME_499563A80185 SecondaryShortCuts

: ME_499563F6016E
 CONST UID '499563F6016E'
 CONST Name 'ExcludeUserTypes'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target ME_4992F915036D // TvcmUserTypes
 ;
 CONST "pm" false

ref; // ME_499563F6016E ExcludeUserTypes

FORWARD ME_4995642C012A

: ME_49956433019E
 CONST UID '49956433019E'
 CONST Name 'anIndex'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4995642C012A // State
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_49956433019E anIndex

: ME_4995642C012A
 CONST UID '4995642C012A'
 CONST Name 'State'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target ME_499301BF0067 // IvcmUserFriendlyControl
 ;
 : Attributes
   Seq: ( ME_49956433019E // anIndex
 )
 ; // Attributes
 CONST "pm" false

ref; // ME_4995642C012A State

: ME_51D14A30003C
 CONST UID '51D14A30003C'
 CONST Name 'ContextMenuWeight'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "pm" false

ref; // ME_51D14A30003C ContextMenuWeight

: ME_51E00A7A0129
 CONST UID '51E00A7A0129'
 CONST Name 'Options'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995624100A6 // IvcmOperationDef
 ;
 : Target ME_51E00A6B0010 // TvcmOperationOptions
 ;
 CONST "pm" false

ref; // ME_51E00A7A0129 Options

: ME_4995616701BB_ME_4995624100A6
 : Original ME_4995616701BB // Hint
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4995616701BB_ME_4995624100A6 Hint

: ME_4995617802E8_ME_4995624100A6
 : Original ME_4995617802E8 // LongHint
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4995617802E8_ME_4995624100A6 LongHint

: ME_499561850334_ME_4995624100A6
 : Original ME_499561850334 // ImageIndex
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499561850334_ME_4995624100A6 ImageIndex

: ME_499561F90285_ME_4995624100A6
 : Original ME_499561F90285 // ID
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499561F90285_ME_4995624100A6 ID

: ME_499E958E03B0_ME_4995624100A6
 : Original ME_499E958E03B0 // Caption
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499E958E03B0_ME_4995624100A6 Caption

: ME_499E95A60064_ME_4995624100A6
 : Original ME_499E95A60064 // Name
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499E95A60064_ME_4995624100A6 Name

: ME_4995624100A6
 CONST UID '4995624100A6'
 CONST GUID '1563410C-852B-4365-A993-8A50640BADA1'
 CONST Name 'IvcmOperationDef'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Описание операции' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_499EAAE502A8 // vcmUserControls
 ;
 : Inherits
   Seq: ( ME_4995619C030A // IvcmIdentifiedUserFriendlyControl
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_49956402012E // VisibleToUser
 ME_4995640A00AE // IsCaptionUnique
 ME_49956423028E // StatesCount
 ME_499564440267 // IsDefault
 ME_499D8B6E01F5 // GroupID
 ME_4995621C01EE // Category
 ME_499562870140 // OperationType
 ME_499562ED0005 // ShortCut
 ME_499563A80185 // SecondaryShortCuts
 ME_499563F6016E // ExcludeUserTypes
 ME_4995642C012A // State
 ME_51D14A30003C // ContextMenuWeight
 ME_51E00A7A0129 // Options
 )
 ; // Attributes
 : Implemented
   Seq: ( ME_4995616701BB_ME_4995624100A6 // Hint
 ME_4995617802E8_ME_4995624100A6 // LongHint
 ME_499561850334_ME_4995624100A6 // ImageIndex
 ME_499561F90285_ME_4995624100A6 // ID
 ME_499E958E03B0_ME_4995624100A6 // Caption
 ME_499E95A60064_ME_4995624100A6 // Name
 )
 ; // Implemented
 : Children
   Seq: ( ME_4683F5BC0213 // TvcmOperationOption
 ME_4683F5860071 // TvcmOperationMode
 ME_4992F7350274 // TvcmOperationCallType
 ME_47F2534B010F // TvcmUserType
 ME_4992F915036D // TvcmUserTypes
 ME_51E00A6B0010 // TvcmOperationOptions
 )
 ; // Children
 CONST extprop:rc:SelfName 'OperationDef'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4995624100A6 IvcmOperationDef

FORWARD ME_499566D90215

FORWARD ME_4992F80B015F

: ME_4992F81501B2
 CONST UID '4992F81501B2'
 CONST Name 'vcm_tbpTop'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4992F80B015F // TvcmToolBarPos
 ;

ref; // ME_4992F81501B2 vcm_tbpTop

: ME_4992F81A02E1
 CONST UID '4992F81A02E1'
 CONST Name 'vcm_tbpBottom'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4992F80B015F // TvcmToolBarPos
 ;

ref; // ME_4992F81A02E1 vcm_tbpBottom

: ME_4992F81F025D
 CONST UID '4992F81F025D'
 CONST Name 'vcm_tbpLeft'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4992F80B015F // TvcmToolBarPos
 ;

ref; // ME_4992F81F025D vcm_tbpLeft

: ME_4992F825017B
 CONST UID '4992F825017B'
 CONST Name 'vcm_tbpRight'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4992F80B015F // TvcmToolBarPos
 ;

ref; // ME_4992F825017B vcm_tbpRight

: ME_4992F82A0100
 CONST UID '4992F82A0100'
 CONST Name 'vcm_tbpNone'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4992F80B015F // TvcmToolBarPos
 ;

ref; // ME_4992F82A0100 vcm_tbpNone

: ME_4992F80B015F
 CONST UID '4992F80B015F'
 CONST Name 'TvcmToolBarPos'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_499566D90215 // IvcmOperationalIdentifiedUserFriendlyControl
 ;
 : Attributes
   Seq: ( ME_4992F81501B2 // vcm_tbpTop
 ME_4992F81A02E1 // vcm_tbpBottom
 ME_4992F81F025D // vcm_tbpLeft
 ME_4992F825017B // vcm_tbpRight
 ME_4992F82A0100 // vcm_tbpNone
 )
 ; // Attributes
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4992F80B015F TvcmToolBarPos

: ME_4992F8670231
 CONST UID '4992F8670231'
 CONST Name 'TvcmToolBarPoses'
 CONST Class class_Class
 : Stereotype st_SetOf ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_499566D90215 // IvcmOperationalIdentifiedUserFriendlyControl
 ;
 : Inherits
   Seq: ( ME_4992F80B015F // TvcmToolBarPos
 )
 ; // Inherits

ref; // ME_4992F8670231 TvcmToolBarPoses

FORWARD ME_4992F83801C5

: ME_4992F8460258
 CONST UID '4992F8460258'
 CONST Name 'First'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4992F83801C5 // TvcmEffectiveToolBarPos
 ;
 CONST Value 'Low(TvcmToolBarPos)'
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 'Low(TvcmToolBarPos)'

ref; // ME_4992F8460258 First

: ME_4992F8520006
 CONST UID '4992F8520006'
 CONST Name 'Last'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4992F83801C5 // TvcmEffectiveToolBarPos
 ;
 CONST Value 'Pred(High(TvcmToolBarPos))'
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 'Pred(High(TvcmToolBarPos))'

ref; // ME_4992F8520006 Last

: ME_4992F83801C5
 CONST UID '4992F83801C5'
 CONST Name 'TvcmEffectiveToolBarPos'
 CONST Class class_Class
 : Stereotype st_Range ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_499566D90215 // IvcmOperationalIdentifiedUserFriendlyControl
 ;
 : Inherits
   Seq: ( ME_4992F80B015F // TvcmToolBarPos
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_4992F8460258 // First
 ME_4992F8520006 // Last
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_4992F83801C5 TvcmEffectiveToolBarPos

: ME_4992F87800BC
 CONST UID '4992F87800BC'
 CONST Name 'TvcmEffectiveToolBarPoses'
 CONST Class class_Class
 : Stereotype st_SetOf ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_499566D90215 // IvcmOperationalIdentifiedUserFriendlyControl
 ;
 : Inherits
   Seq: ( ME_4992F83801C5 // TvcmEffectiveToolBarPos
 )
 ; // Inherits

ref; // ME_4992F87800BC TvcmEffectiveToolBarPoses

FORWARD ME_4995644E03A9

: ME_4995645B02C7
 CONST UID '4995645B02C7'
 CONST Name 'Next'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'следующий описатель операции' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4995644E03A9 // IvcmOperationsDefIterator
 ;
 : Target ME_4995624100A6 // IvcmOperationDef
 ;
 CONST "pm" false

ref; // ME_4995645B02C7 Next

: ME_4995644E03A9
 CONST UID '4995644E03A9'
 CONST GUID '3B8CFB31-F1BF-469A-A248-1C613BA636C9'
 CONST Name 'IvcmOperationsDefIterator'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Итератор описаний операций' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_499566D90215 // IvcmOperationalIdentifiedUserFriendlyControl
 ;
 : Attributes
   Seq: ( ME_4995645B02C7 // Next
 )
 ; // Attributes
 CONST extprop:rc:SelfName 'OperationsDefIterator'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4995644E03A9 IvcmOperationsDefIterator

: ME_499566FA0159
 CONST UID '499566FA0159'
 CONST Name 'OperationsDefIterator'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'итератор описаний операций. Может быть nil' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_499566D90215 // IvcmOperationalIdentifiedUserFriendlyControl
 ;
 : Target ME_4995644E03A9 // IvcmOperationsDefIterator
 ;
 CONST "pm" false

ref; // ME_499566FA0159 OperationsDefIterator

: ME_4995671E031A
 CONST UID '4995671E031A'
 CONST Name 'ToolbarPos'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'любой объект, обладающий набором операций, может отображать их в тулбаре' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_499566D90215 // IvcmOperationalIdentifiedUserFriendlyControl
 ;
 : Target ME_4992F80B015F // TvcmToolBarPos
 ;
 CONST "pm" false

ref; // ME_4995671E031A ToolbarPos

: ME_4995616701BB_ME_499566D90215
 : Original ME_4995616701BB // Hint
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4995616701BB_ME_499566D90215 Hint

: ME_4995617802E8_ME_499566D90215
 : Original ME_4995617802E8 // LongHint
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4995617802E8_ME_499566D90215 LongHint

: ME_499561850334_ME_499566D90215
 : Original ME_499561850334 // ImageIndex
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499561850334_ME_499566D90215 ImageIndex

: ME_499561F90285_ME_499566D90215
 : Original ME_499561F90285 // ID
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499561F90285_ME_499566D90215 ID

: ME_499E958E03B0_ME_499566D90215
 : Original ME_499E958E03B0 // Caption
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499E958E03B0_ME_499566D90215 Caption

: ME_499E95A60064_ME_499566D90215
 : Original ME_499E95A60064 // Name
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499E95A60064_ME_499566D90215 Name

: ME_499566D90215
 CONST UID '499566D90215'
 CONST GUID '0F52E633-4306-4D75-93D1-5F259A9B3D45'
 CONST Name 'IvcmOperationalIdentifiedUserFriendlyControl'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Базовый интерфейс для объектов имеющих отображение для пользователя и операции' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_499EAAE502A8 // vcmUserControls
 ;
 : Inherits
   Seq: ( ME_4995619C030A // IvcmIdentifiedUserFriendlyControl
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_499566FA0159 // OperationsDefIterator
 ME_4995671E031A // ToolbarPos
 )
 ; // Attributes
 : Implemented
   Seq: ( ME_4995616701BB_ME_499566D90215 // Hint
 ME_4995617802E8_ME_499566D90215 // LongHint
 ME_499561850334_ME_499566D90215 // ImageIndex
 ME_499561F90285_ME_499566D90215 // ID
 ME_499E958E03B0_ME_499566D90215 // Caption
 ME_499E95A60064_ME_499566D90215 // Name
 )
 ; // Implemented
 : Children
   Seq: ( ME_4992F80B015F // TvcmToolBarPos
 ME_4992F8670231 // TvcmToolBarPoses
 ME_4992F83801C5 // TvcmEffectiveToolBarPos
 ME_4992F87800BC // TvcmEffectiveToolBarPoses
 ME_4995644E03A9 // IvcmOperationsDefIterator
 )
 ; // Children
 CONST extprop:rc:SelfName 'OperationalIdentifiedUserFriendlyControl'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_499566D90215 IvcmOperationalIdentifiedUserFriendlyControl

: ME_499EAAE502A8
 CONST UID '499EAAE502A8'
 CONST Name 'vcmUserControls'
 CONST Class class_Category
 : Stereotype st_Interfaces ;
 %SUMMARY 'Управляющие элементы, взаимодействующие с пользователем' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4790C3B8021E' '4790C3B8021E.pas.ms.script' // VCM
 ;
 : Children
   Seq: ( ME_499560120345 // IvcmBaseObjectDef
 ME_499301BF0067 // IvcmUserFriendlyControl
 ME_4995619C030A // IvcmIdentifiedUserFriendlyControl
 ME_4995624100A6 // IvcmOperationDef
 ME_499566D90215 // IvcmOperationalIdentifiedUserFriendlyControl
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 WL 'ME_467BAB7F021E' '467BAB7F021E.pas.ms.script' // vcmExternalInterfaces
 WL 'ME_4799D29F033F' '4799D29F033F.pas.ms.script' // Implementation
 WL 'ME_4AB0997B00A2' '4AB0997B00A2.pas.ms.script' // Common
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 )
 ; // Depends
 CONST "author" 'Люлин А.В.'
 CONST "is namespace" true
 CONST "no hands" true
 CONST "started" '20.02.2009 16:07'
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\vcmUserControls.pas'

ref; // ME_499EAAE502A8 vcmUserControls
