// Tl3ProtoDataContainer 4A54DD4E036F SimpleClass Class

INCLUDE '49E7754802A9.pas.ms.script'

INCLUDE '4A54DFCC0370.pas.ms.script'

: ME_4A54DD4E036F
 CONST UID '4A54DD4E036F'
 CONST Name 'Tl3ProtoDataContainer'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 %SUMMARY 'Самый примитивный контейнер данных' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'abstract'
 : Inherits
   [ ME_49E7754802A9 // Tl3ProtoObject
 ME_4A54DFCC0370 // l3DataContainer
 ]
 ; // Inherits
 CONST "author" 'Люлин А.В.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '08.07.2009 21:55'

 @SELF
; // ME_4A54DD4E036F Tl3ProtoDataContainer
