// nevParaListViewBounds 4A5CD0CB0038 Impurity Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4A5CD0CB0038

MEREF ME_4A5CCD9D028D_ME_4A5CD0CB0038_over
 MELINK Original WL 'ME_4A5CCD9D028D' '4A5CCD5F00C1.ms.model.script' // GetViewBounds
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_4A5CCD9D028D_ME_4A5CD0CB0038_over GetViewBounds

MEREF ME_4A5CD0B302BD_ME_4A5CD0CB0038_R
 MELINK Original WL 'ME_4A5CD0B302BD' '47E3DF460095.ms.model.script' // MnevViewBounds
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4A5CD0B302BD_ME_4A5CD0CB0038_R MnevViewBounds

%%ImplementedBy ME_4A5CD0B302BD ME_4A5CD0CB0038

ME ME_4A5CD0CB0038
 MEPROP UID '4A5CD0CB0038'
 MEPROP Name 'nevParaListViewBounds'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_Impurity ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_47E3DF460095' // Cursors
 ;
 MELIST Implements
   Seq: ( ME_4A5CD0B302BD_ME_4A5CD0CB0038_R // MnevViewBounds
 )
 ; // Implements
 MELIST Overridden
   Seq: ( ME_4A5CCD9D028D_ME_4A5CD0CB0038_over // GetViewBounds
 )
 ; // Overridden
 UP intf.pas:Path 'common\components\gui\Garant\Everest\nevParaListViewBounds.imp.pas'
 UP extprop:pas:TypeName '_nevParaListViewBounds_'
 UP extprop:pas:UnitName 'nevParaListViewBounds.imp'

ENDME // ME_4A5CD0CB0038 nevParaListViewBounds
