// Chat 4A66B91A01E4 Library Category

INCLUDE 'ElementsRTTI.ms.dict'

: ME_4A66B91A01E4
 CONST UID '4A66B91A01E4'
 CONST Name 'Chat'
 CONST Class class_Category
 : Stereotype st_Library ;
 %SUMMARY '¬нутренн€€ механика (контроллеры+данные)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4A66B8720216' '4A66B8720216.pas.ms.script' // Chat
 ;
 : Children
   Seq: ( WL 'ME_4A66B9840002' '4A66B9840002.pas.ms.script' // ChatTypes
 WL 'ME_4A66DD3C01E8' '4A66DD3C01E8.pas.ms.script' // ChatInterfaces
 WL 'ME_4A66EB280367' '4A66EB280367.pas.ms.script' // ChatImpl
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_456EA3D2031C' '456EA3D2031C.pas.ms.script' // GblAdapterLib
 WL 'ME_4677FBA70343' '4677FBA70343.pas.ms.script' // l3Interfaces
 WL 'ME_4677FF4B0036' '4677FF4B0036.pas.ms.script' // Data
 WL 'ME_467A8734039C' '467A8734039C.pas.ms.script' // EVD
 WL 'ME_4682595B0268' '4682595B0268.pas.ms.script' // l3TreeInterfaces
 WL 'ME_469F3E37025A' '469F3E37025A.pas.ms.script' // Rtl
 WL 'ME_4790B4F00236' '4790B4F00236.pas.ms.script' // AFW
 WL 'ME_4790C3B8021E' '4790C3B8021E.pas.ms.script' // VCM
 WL 'ME_4790D09A0378' '4790D09A0378.pas.ms.script' // L3
 WL 'ME_47E9EEC60260' '47E9EEC60260.pas.ms.script' // Model
 WL 'ME_4E2F0E1B03BB' '4E2F0E1B03BB.pas.ms.script' // L3$Domain
 WL 'ME_521C9DA50125' '521C9DA50125.pas.ms.script' // Application Resources
 WL 'ME_54B90AC6014B' '54B90AC6014B.pas.ms.script' // StringUtils
 WL 'ME_55B62380030A' '55B62380030A.pas.ms.script' // Logging
 )
 ; // Depends
 CONST "exec mode" 'concluded'
 CONST "gui" 'prj'
 CONST "is namespace" true
 CONST "vendor" 'none'
 CONST dfm:PathOnly '\garant6x\implementation\Garant\GbaNemesis\Chat'
 CONST intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\Chat'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\4A66B91A01E4.pas.ms.script'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\4A66B91A01E4.pas.ms.script.runner'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_4A66B91A01E4 Chat
