// Base Forms 4A7C0BB70162 VCMForms Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162
%%Inner ME_4A7C0BB70162

FORWARD ME_4A7C0BB70162

FORWARD ME_4B0B997901E9

ME ME_4B0B99A102D2
 MEPROP Name 'aDoc'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB6520191' '4570511E038A.ms.model.script' // Document
 ;

ENDME // ME_4B0B99A102D2 aDoc

ME ME_4B0B99960016
 MEPROP UID '4B0B99960016'
 MEPROP Name 'Log'
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B0B997901E9 // TnsExportToFileEvent
 ;
 MELIST Parameters
   Seq: ( ME_4B0B99A102D2 // aDoc
 )
 ; // Parameters

ENDME // ME_4B0B99960016 Log

ME ME_4B0B9D44020F
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B0B997901E9 // TnsExportToFileEvent
 ;
 MELINK Target WL 'ME_45ED58FF0201' '45ED58CF03E6.ms.model.script' // LogEvent
 ;

ENDME // ME_4B0B9D44020F 

%%InheritedBy ME_4B0A6109010C ME_4B0B997901E9

ME ME_4B0B997901E9
 MEPROP UID '4B0B997901E9'
 MEPROP Name 'TnsExportToFileEvent'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4A7C0BB70162 // Base Forms
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4B0A6109010C' '4B0A60DF01F2.ms.model.script' // TnsLogEvent
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_4B0B99960016 // Log
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_4B0B9D44020F // LogEvent
 )
 ; // Dependencies
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\nsExportToFileEvent.pas'
 UP extprop:rc:SelfName 'ExportToFileEvent'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nsExportToFileEvent'

ENDME // ME_4B0B997901E9 TnsExportToFileEvent

FORWARD ME_4B0B99CA0261

ME ME_4B0B99FD01E1
 MEPROP Name 'aDoc'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB6520191' '4570511E038A.ms.model.script' // Document
 ;

ENDME // ME_4B0B99FD01E1 aDoc

ME ME_4B0B99FD0200
 MEPROP Name 'ForSelection'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4B0B99FD0200 ForSelection

ME ME_4B0B99FD021F
 MEPROP Name 'IntoActive'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4B0B99FD021F IntoActive

ME ME_4B0B99D901AD
 MEPROP UID '4B0B99D901AD'
 MEPROP Name 'Log'
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B0B99CA0261 // TnsExportToWordEvent
 ;
 MELIST Parameters
   Seq: ( ME_4B0B99FD01E1 // aDoc
 ME_4B0B99FD0200 // ForSelection
 ME_4B0B99FD021F // IntoActive
 )
 ; // Parameters

ENDME // ME_4B0B99D901AD Log

ME ME_4B0B9D4000FD
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B0B99CA0261 // TnsExportToWordEvent
 ;
 MELINK Target WL 'ME_45ED58FF0201' '45ED58CF03E6.ms.model.script' // LogEvent
 ;

ENDME // ME_4B0B9D4000FD 

%%InheritedBy ME_4B0A6109010C ME_4B0B99CA0261

ME ME_4B0B99CA0261
 MEPROP UID '4B0B99CA0261'
 MEPROP Name 'TnsExportToWordEvent'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4A7C0BB70162 // Base Forms
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4B0A6109010C' '4B0A60DF01F2.ms.model.script' // TnsLogEvent
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_4B0B99D901AD // Log
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_4B0B9D4000FD // LogEvent
 )
 ; // Dependencies
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\nsExportToWordEvent.pas'
 UP extprop:rc:SelfName 'ExportToWordEvent'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nsExportToWordEvent'

ENDME // ME_4B0B99CA0261 TnsExportToWordEvent

FORWARD ME_4B0B9A490271

ME ME_4B0B9A70031C
 MEPROP Name 'aDoc'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB6520191' '4570511E038A.ms.model.script' // Document
 ;

ENDME // ME_4B0B9A70031C aDoc

ME ME_4B0B9A6603E7
 MEPROP UID '4B0B9A6603E7'
 MEPROP Name 'Log'
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B0B9A490271 // TnsSendDocumentByEMailEvent
 ;
 MELIST Parameters
   Seq: ( ME_4B0B9A70031C // aDoc
 )
 ; // Parameters

ENDME // ME_4B0B9A6603E7 Log

ME ME_4B0B9D3601E7
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B0B9A490271 // TnsSendDocumentByEMailEvent
 ;
 MELINK Target WL 'ME_45ED58FF0201' '45ED58CF03E6.ms.model.script' // LogEvent
 ;

ENDME // ME_4B0B9D3601E7 

%%InheritedBy ME_4B0A6109010C ME_4B0B9A490271

ME ME_4B0B9A490271
 MEPROP UID '4B0B9A490271'
 MEPROP Name 'TnsSendDocumentByEMailEvent'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4A7C0BB70162 // Base Forms
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4B0A6109010C' '4B0A60DF01F2.ms.model.script' // TnsLogEvent
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_4B0B9A6603E7 // Log
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_4B0B9D3601E7 // LogEvent
 )
 ; // Dependencies
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\nsSendDocumentByEMailEvent.pas'
 UP extprop:rc:SelfName 'SendDocumentByEMailEvent'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nsSendDocumentByEMailEvent'

ENDME // ME_4B0B9A490271 TnsSendDocumentByEMailEvent

FORWARD ME_4B0B9A9D00D1

ME ME_4B0B9ABC017A
 MEPROP Name 'aDoc'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB6520191' '4570511E038A.ms.model.script' // Document
 ;

ENDME // ME_4B0B9ABC017A aDoc

ME ME_4B0B9AB201A9
 MEPROP UID '4B0B9AB201A9'
 MEPROP Name 'Log'
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B0B9A9D00D1 // TnsDocumentPrintPreviewEvent
 ;
 MELIST Parameters
   Seq: ( ME_4B0B9ABC017A // aDoc
 )
 ; // Parameters

ENDME // ME_4B0B9AB201A9 Log

ME ME_4B0B9D3C01BE
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B0B9A9D00D1 // TnsDocumentPrintPreviewEvent
 ;
 MELINK Target WL 'ME_45ED58FF0201' '45ED58CF03E6.ms.model.script' // LogEvent
 ;

ENDME // ME_4B0B9D3C01BE 

%%InheritedBy ME_4B0A6109010C ME_4B0B9A9D00D1

ME ME_4B0B9A9D00D1
 MEPROP UID '4B0B9A9D00D1'
 MEPROP Name 'TnsDocumentPrintPreviewEvent'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4A7C0BB70162 // Base Forms
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4B0A6109010C' '4B0A60DF01F2.ms.model.script' // TnsLogEvent
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_4B0B9AB201A9 // Log
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_4B0B9D3C01BE // LogEvent
 )
 ; // Dependencies
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\nsDocumentPrintPreviewEvent.pas'
 UP extprop:rc:SelfName 'DocumentPrintPreviewEvent'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nsDocumentPrintPreviewEvent'

ENDME // ME_4B0B9A9D00D1 TnsDocumentPrintPreviewEvent

FORWARD ME_4B0A8AB30113

ME ME_4B0A8B060122
 MEPROP Name 'aDoc'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB6520191' '4570511E038A.ms.model.script' // Document
 ;

ENDME // ME_4B0A8B060122 aDoc

ME ME_4B0A8B06014F
 MEPROP Name 'aContext'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_4B0A8B06014F aContext

ME ME_4B0A8AF000C9
 MEPROP UID '4B0A8AF000C9'
 MEPROP Name 'Log'
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B0A8AB30113 // TnsSearchInDocumentEvent
 ;
 MELIST Parameters
   Seq: ( ME_4B0A8B060122 // aDoc
 ME_4B0A8B06014F // aContext
 )
 ; // Parameters

ENDME // ME_4B0A8AF000C9 Log

ME ME_4B0A8B4D020F
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B0A8AB30113 // TnsSearchInDocumentEvent
 ;
 MELINK Target WL 'ME_45ED59730069' '45ED58CF03E6.ms.model.script' // LogEventData
 ;

ENDME // ME_4B0A8B4D020F 

ME ME_4B4EDD9001F1
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B0A8AB30113 // TnsSearchInDocumentEvent
 ;
 MELINK Target WL 'ME_4AAF9718001D' '4A6854C70390.ms.model.script' // nsAStr
 ;

ENDME // ME_4B4EDD9001F1 

ME ME_5280A65D0235
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B0A8AB30113 // TnsSearchInDocumentEvent
 ;
 MELINK Target WL 'ME_45ED58FF0201' '45ED58CF03E6.ms.model.script' // LogEvent
 ;

ENDME // ME_5280A65D0235 

%%InheritedBy ME_4B0A6109010C ME_4B0A8AB30113

ME ME_4B0A8AB30113
 MEPROP UID '4B0A8AB30113'
 MEPROP Name 'TnsSearchInDocumentEvent'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4A7C0BB70162 // Base Forms
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4B0A6109010C' '4B0A60DF01F2.ms.model.script' // TnsLogEvent
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_4B0A8AF000C9 // Log
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_4B0A8B4D020F // LogEventData
 ME_4B4EDD9001F1 // nsAStr
 ME_5280A65D0235 // LogEvent
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\nsSearchInDocumentEvent.pas'
 UP extprop:rc:SelfName 'SearchInDocumentEvent'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nsSearchInDocumentEvent'

ENDME // ME_4B0A8AB30113 TnsSearchInDocumentEvent

FORWARD ME_5280813401EA

ME ME_528085A8017D
 MEPROP Name 'aDoc'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB6520191' '4570511E038A.ms.model.script' // Document
 ;

ENDME // ME_528085A8017D aDoc

ME ME_528085A801A0
 MEPROP Name 'aContext'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_528085A801A0 aContext

ME ME_528085A801C5
 MEPROP Name 'aFoundCount'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_528085A801C5 aFoundCount

ME ME_528081740164
 MEPROP UID '528081740164'
 MEPROP Name 'Log'
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5280813401EA // TnsSearchInDocumentDoneEvent
 ;
 MELIST Parameters
   Seq: ( ME_528085A8017D // aDoc
 ME_528085A801A0 // aContext
 ME_528085A801C5 // aFoundCount
 )
 ; // Parameters

ENDME // ME_528081740164 Log

ME ME_528081BB00EB
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5280813401EA // TnsSearchInDocumentDoneEvent
 ;
 MELINK Target WL 'ME_45ED58FF0201' '45ED58CF03E6.ms.model.script' // LogEvent
 ;

ENDME // ME_528081BB00EB 

ME ME_528081F602CB
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5280813401EA // TnsSearchInDocumentDoneEvent
 ;
 MELINK Target WL 'ME_45ED59730069' '45ED58CF03E6.ms.model.script' // LogEventData
 ;

ENDME // ME_528081F602CB 

ME ME_528081FC00FB
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5280813401EA // TnsSearchInDocumentDoneEvent
 ;
 MELINK Target WL 'ME_4AAF9718001D' '4A6854C70390.ms.model.script' // nsAStr
 ;

ENDME // ME_528081FC00FB 

%%InheritedBy ME_4B0A6109010C ME_5280813401EA

ME ME_5280813401EA
 MEPROP UID '5280813401EA'
 MEPROP Name 'TnsSearchInDocumentDoneEvent'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4A7C0BB70162 // Base Forms
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4B0A6109010C' '4B0A60DF01F2.ms.model.script' // TnsLogEvent
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_528081740164 // Log
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_528081BB00EB // LogEvent
 ME_528081F602CB // LogEventData
 ME_528081FC00FB // nsAStr
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\nsSearchInDocumentDoneEvent.pas'
 UP extprop:rc:SelfName 'SearchInDocumentDoneEvent'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nsSearchInDocumentDoneEvent'

ENDME // ME_5280813401EA TnsSearchInDocumentDoneEvent

FORWARD ME_5280A6CC0073

ME ME_5280A6FA0224
 MEPROP Name 'aDoc'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB6520191' '4570511E038A.ms.model.script' // Document
 ;

ENDME // ME_5280A6FA0224 aDoc

ME ME_5280A6FA023E
 MEPROP Name 'aContext'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_5280A6FA023E aContext

ME ME_5280A6F5009C
 MEPROP UID '5280A6F5009C'
 MEPROP Name 'Log'
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5280A6CC0073 // TnsSearchInDocumentNextEvent
 ;
 MELIST Parameters
   Seq: ( ME_5280A6FA0224 // aDoc
 ME_5280A6FA023E // aContext
 )
 ; // Parameters

ENDME // ME_5280A6F5009C Log

ME ME_5280A72C00FC
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5280A6CC0073 // TnsSearchInDocumentNextEvent
 ;
 MELINK Target WL 'ME_45ED58FF0201' '45ED58CF03E6.ms.model.script' // LogEvent
 ;

ENDME // ME_5280A72C00FC 

ME ME_5280A805032B
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5280A6CC0073 // TnsSearchInDocumentNextEvent
 ;
 MELINK Target WL 'ME_45ED59730069' '45ED58CF03E6.ms.model.script' // LogEventData
 ;

ENDME // ME_5280A805032B 

ME ME_5280A8090334
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5280A6CC0073 // TnsSearchInDocumentNextEvent
 ;
 MELINK Target WL 'ME_4AAF9718001D' '4A6854C70390.ms.model.script' // nsAStr
 ;

ENDME // ME_5280A8090334 

%%InheritedBy ME_4B0A6109010C ME_5280A6CC0073

ME ME_5280A6CC0073
 MEPROP UID '5280A6CC0073'
 MEPROP Name 'TnsSearchInDocumentNextEvent'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4A7C0BB70162 // Base Forms
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4B0A6109010C' '4B0A60DF01F2.ms.model.script' // TnsLogEvent
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_5280A6F5009C // Log
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_5280A72C00FC // LogEvent
 ME_5280A805032B // LogEventData
 ME_5280A8090334 // nsAStr
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\nsSearchInDocumentNextEvent.pas'
 UP extprop:rc:SelfName 'SearchInDocumentNextEvent'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nsSearchInDocumentNextEvent'

ENDME // ME_5280A6CC0073 TnsSearchInDocumentNextEvent

FORWARD ME_5280A7050003

ME ME_5280A71502AD
 MEPROP Name 'aDoc'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB6520191' '4570511E038A.ms.model.script' // Document
 ;

ENDME // ME_5280A71502AD aDoc

ME ME_5280A71502C7
 MEPROP Name 'aContext'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_5280A71502C7 aContext

ME ME_5280A7140235
 MEPROP UID '5280A7140235'
 MEPROP Name 'Log'
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5280A7050003 // TnsSearchInDocumentPrevEvent
 ;
 MELIST Parameters
   Seq: ( ME_5280A71502AD // aDoc
 ME_5280A71502C7 // aContext
 )
 ; // Parameters

ENDME // ME_5280A7140235 Log

ME ME_5280A7350354
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5280A7050003 // TnsSearchInDocumentPrevEvent
 ;
 MELINK Target WL 'ME_45ED58FF0201' '45ED58CF03E6.ms.model.script' // LogEvent
 ;

ENDME // ME_5280A7350354 

ME ME_5280A82C020B
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5280A7050003 // TnsSearchInDocumentPrevEvent
 ;
 MELINK Target WL 'ME_4AAF9718001D' '4A6854C70390.ms.model.script' // nsAStr
 ;

ENDME // ME_5280A82C020B 

ME ME_5280A830028B
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5280A7050003 // TnsSearchInDocumentPrevEvent
 ;
 MELINK Target WL 'ME_45ED59730069' '45ED58CF03E6.ms.model.script' // LogEventData
 ;

ENDME // ME_5280A830028B 

%%InheritedBy ME_4B0A6109010C ME_5280A7050003

ME ME_5280A7050003
 MEPROP UID '5280A7050003'
 MEPROP Name 'TnsSearchInDocumentPrevEvent'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4A7C0BB70162 // Base Forms
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4B0A6109010C' '4B0A60DF01F2.ms.model.script' // TnsLogEvent
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_5280A7140235 // Log
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_5280A7350354 // LogEvent
 ME_5280A82C020B // nsAStr
 ME_5280A830028B // LogEventData
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\nsSearchInDocumentPrevEvent.pas'
 UP extprop:rc:SelfName 'SearchInDocumentPrevEvent'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'nsSearchInDocumentPrevEvent'

ENDME // ME_5280A7050003 TnsSearchInDocumentPrevEvent

ME ME_4A7C0BB70162
 MEPROP UID '4A7C0BB70162'
 MEPROP Name 'Base Forms'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_VCMForms ;
 %SUMMARY 'Абстрактные формы для поддержки базовых операций' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4A7C099B004F' '4A7C099B004F.ms.model.script' // View
 ;
 MELIST Children
   Seq: ( WL 'ME_4A7C0BF5008B' '4A7C0BF5008B.ms.model.script' // DocumentPresentation
 WL 'ME_4A8AACAE0356' '4A8AACAE0356.ms.model.script' // TextWithComments
 WL 'ME_497F0F17036D' '497F0F17036D.ms.model.script' // PageControlNotification
 WL 'ME_4AD5E6A60262' '4AD5E6A60262.ms.model.script' // BaseSearchPresentation
 WL 'ME_4A853E260311' '4A853E260311.ms.model.script' // Text
 WL 'ME_4AE1A69E0156' '4AE1A69E0156.ms.model.script' // BaseTextOperations
 HWL ME_4B0B997901E9 // TnsExportToFileEvent
 HWL ME_4B0B99CA0261 // TnsExportToWordEvent
 HWL ME_4B0B9A490271 // TnsSendDocumentByEMailEvent
 HWL ME_4B0B9A9D00D1 // TnsDocumentPrintPreviewEvent
 WL 'ME_4B4DB88E01B6' '4B4DB88E01B6.ms.model.script' // DocumentBaseSearcher
 HWL ME_4B0A8AB30113 // TnsSearchInDocumentEvent
 WL 'ME_4BD1E3DE02FB' '4BD1E3DE02FB.ms.model.script' // DocumentUserTypes
 WL 'ME_4C0686B8005B' '4C0686B8005B.ms.model.script' // BlockSelector
 WL 'ME_4C3F3CC20022' '4C3F3CC20022.ms.model.script' // FoldersRes
 WL 'ME_4D5A701702B4' '4D5A701702B4.ms.model.script' // nsTextWithCommentsRes
 WL 'ME_4D776CFE031E' '4D776CFE031E.ms.model.script' // AttributesUserTypes
 WL 'ME_4D8C88C102D9' '4D8C88C102D9.ms.model.script' // nsBaseTextOperationsConst
 WL 'ME_4DA8763E0201' '4DA8763E0201.ms.model.script' // WarningUserTypes
 WL 'ME_4A7B03ED01E3' '4A7B03ED01E3.ms.model.script' // WorkWithRedactions
 WL 'ME_4EB7BDAB01D0' '4EB7BDAB01D0.ms.model.script' // BaseSearchPresentationFor296635421
 WL 'ME_4F5E12C20114' '4F5E12C20114.ms.model.script' // BaloonWarningUserTypes
 WL 'ME_4FF59A2F016E' '4FF59A2F016E.ms.model.script' // ListUserTypes
 WL 'ME_4FFB039302AA' '4FFB039302AA.ms.model.script' // ContentsUserTypes
 WL 'ME_4FFB165600FE' '4FFB165600FE.ms.model.script' // ListInfoUserTypes
 WL 'ME_4FFBDD570171' '4FFBDD570171.ms.model.script' // SynchroViewUserTypes
 WL 'ME_4FFBDE68006D' '4FFBDE68006D.ms.model.script' // ListAnalizeUserTypes
 WL 'ME_4FFBE354038B' '4FFBE354038B.ms.model.script' // DocumentWithFlashUserTypes
 WL 'ME_5009475801E4' '5009475801E4.ms.model.script' // RedactionsUserTypes
 HWL ME_5280813401EA // TnsSearchInDocumentDoneEvent
 HWL ME_5280A6CC0073 // TnsSearchInDocumentNextEvent
 HWL ME_5280A7050003 // TnsSearchInDocumentPrevEvent
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_456EA56002BF' '456EA56002BF.ms.model.script' // BaseTypes
 WL 'ME_4570511E038A' '4570511E038A.ms.model.script' // Document
 WL 'ME_457450470167' '457450470167.ms.model.script' // DynamicTree
 WL 'ME_45ED58CF03E6' '45ED58CF03E6.ms.model.script' // Logging
 WL 'ME_45EEAA800226' '45EEAA800226.ms.model.script' // UnderControl
 WL 'ME_4677FBA70343' '4677FBA70343.ms.model.script' // l3Interfaces
 WL 'ME_4678137501EA' '4678137501EA.ms.model.script' // k2Interfaces
 WL 'ME_4678193C009C' '4678193C009C.ms.model.script' // l3Types
 WL 'ME_4678209200A6' '4678209200A6.ms.model.script' // nevBase
 WL 'ME_467823B7002C' '467823B7002C.ms.model.script' // afwInterfaces
 WL 'ME_467BAB7F021E' '467BAB7F021E.ms.model.script' // vcmExternalInterfaces
 WL 'ME_467C0CAA02AB' '467C0CAA02AB.ms.model.script' // l3InternalInterfaces
 WL 'ME_467FC9F80281' '467FC9F80281.ms.model.script' // DocumentTagNodes
 WL 'ME_4683F37902CF' '4683F37902CF.ms.model.script' // vcmInterfaces
 WL 'ME_476BE0350329' '476BE0350329.ms.model.script' // Styles
 WL 'ME_476F78840219' '476F78840219.ms.model.script' // Messages
 WL 'ME_47750CE700D0' '47750CE700D0.ms.model.script' // afwFacade
 WL 'ME_47913B47006E' '47913B47006E.ms.model.script' // l3CoreObjects
 WL 'ME_4799D29F033F' '4799D29F033F.ms.model.script' // Implementation
 WL 'ME_47AC75550330' '47AC75550330.ms.model.script' // k2Tags
 WL 'ME_47BB24D30205' '47BB24D30205.ms.model.script' // Стандартные примеси
 WL 'ME_47C5207602D1' '47C5207602D1.ms.model.script' // nevTools
 WL 'ME_47C695A10172' '47C695A10172.ms.model.script' // evTypes
 WL 'ME_47D0E1500033' '47D0E1500033.ms.model.script' // Implementation
 WL 'ME_47EA50050263' '47EA50050263.ms.model.script' // BaseDocument
 WL 'ME_47ECA80B000D' '47ECA80B000D.ms.model.script' // Generators
 WL 'ME_47ECACA70141' '47ECACA70141.ms.model.script' // Generators
 WL 'ME_47F1F38601A3' '47F1F38601A3.ms.model.script' // ParaUtils
 WL 'ME_47F1F90A0391' '47F1F90A0391.ms.model.script' // Searchers
 WL 'ME_47F2170002B2' '47F2170002B2.ms.model.script' // nsTypes
 WL 'ME_47F260DC003F' '47F260DC003F.ms.model.script' // ns
 WL 'ME_47F485150151' '47F485150151.ms.model.script' // vtCommon
 WL 'ME_48200CF8039E' '48200CF8039E.ms.model.script' // Печать, Экспорт
 WL 'ME_4829D7D50156' '4829D7D50156.ms.model.script' // Editors
 WL 'ME_48453A40017C' '48453A40017C.ms.model.script' // evOp
 WL 'ME_484900780017' '484900780017.ms.model.script' // Работа с документом
 WL 'ME_48492FC0029D' '48492FC0029D.ms.model.script' // Standard
 WL 'ME_484FA67302D7' '484FA67302D7.ms.model.script' // GUI
 WL 'ME_48F747EC0073' '48F747EC0073.ms.model.script' // Common
 WL 'ME_490838E10313' '490838E10313.ms.model.script' // nscNewInterfaces
 WL 'ME_4908545802CA' '4908545802CA.ms.model.script' // DocumentContainers
 WL 'ME_4912DD020283' '4912DD020283.ms.model.script' // eeInterfaces
 WL 'ME_4912E16B01B4' '4912E16B01B4.ms.model.script' // Engine Core
 WL 'ME_491B305A0096' '491B305A0096.ms.model.script' // DocumentAndListInterfaces
 WL 'ME_495119A901CE' '495119A901CE.ms.model.script' // Editor
 WL 'ME_495127DD017C' '495127DD017C.ms.model.script' // Text
 WL 'ME_495237D80268' '495237D80268.ms.model.script' // F1Specific
 WL 'ME_49523C640160' '49523C640160.ms.model.script' // eeInterfacesEx
 WL 'ME_4952683C007B' '4952683C007B.ms.model.script' // Editor
 WL 'ME_497ED74F0032' '497ED74F0032.ms.model.script' // Common
 WL 'ME_49804E310263' '49804E310263.ms.model.script' // PresentationInterfaces
 WL 'ME_4990135D02F1' '4990135D02F1.ms.model.script' // FoldersDomainInterfaces
 WL 'ME_4A4DE16302A2' '4A4DE16302A2.ms.model.script' // k2Core
 WL 'ME_4A77058200BA' '4A77058200BA.ms.model.script' // Editions
 WL 'ME_4A7C0A8202A9' '4A7C0A8202A9.ms.model.script' // View
 WL 'ME_4A9807DB01A5' '4A9807DB01A5.ms.model.script' // Strange
 WL 'ME_4A9F98B901A5' '4A9F98B901A5.ms.model.script' // BaseSearchInterfaces
 WL 'ME_4AADF9450143' '4AADF9450143.ms.model.script' // Visual
 WL 'ME_4AB0997B00A2' '4AB0997B00A2.ms.model.script' // Common
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.ms.model.script' // Sys
 WL 'ME_4AB0C3F60375' '4AB0C3F60375.ms.model.script' // Win
 WL 'ME_4ABB68530117' '4ABB68530117.ms.model.script' // Printing
 WL 'ME_4AE89F8A004B' '4AE89F8A004B.ms.model.script' // Strange
 WL 'ME_4AEEE2A40281' '4AEEE2A40281.ms.model.script' // Strange
 WL 'ME_4B0A60DF01F2' '4B0A60DF01F2.ms.model.script' // Logging
 WL 'ME_4D8A25430335' '4D8A25430335.ms.model.script' // ContextSearchInEVDDocument
 WL 'ME_4DCD537F0284' '4DCD537F0284.ms.model.script' // DocumentFilters
 WL 'ME_4DDA34AA023B' '4DDA34AA023B.ms.model.script' // Dialogs
 WL 'ME_4E030FC801EB' '4E030FC801EB.ms.model.script' // BatchServices
 WL 'ME_4F4B8FA60272' '4F4B8FA60272.ms.model.script' // Implementation
 WL 'ME_4F9BB1120134' '4F9BB1120134.ms.model.script' // Сюда вынес все сообщения из StdRes с Choices
 WL 'ME_521C9DA50125' '521C9DA50125.ms.model.script' // Application Resources
 WL 'ME_54B90AC6014B' '54B90AC6014B.ms.model.script' // StringUtils
 WL 'ME_553893E60323' '553893E60323.ms.model.script' // Services
 WL 'ME_55C4AEB903E1' '55C4AEB903E1.ms.model.script' // Printing
 WL 'ME_56163ADC014A' '56163ADC014A.ms.model.script' // BaseSearchUtils
 WL 'ME_563874EF0183' '563874EF0183.ms.model.script' // SearchServices
 WL 'ME_5795D66F0385' '5795D66F0385.ms.model.script' // F1Services
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' 'Logging' )
 ; // DiagramsNames

ENDME // ME_4A7C0BB70162 Base Forms
