// View 4A811B89032D VCMViews Category

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_4A811B89032D
 MEPROP UID '4A811B89032D'
 MEPROP Name 'View'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_VCMViews ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4A811B590020' '4A811B590020.ms.model.script' // WorkJournal
 ;
 MELIST Children
   Seq: ( WL 'ME_4C3F34640373' '4C3F34640373.ms.model.script' // Strange
 WL 'ME_4A811BCC031F' '4A811BCC031F.ms.model.script' // WorkJournal
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_456EA3D2031C' '456EA3D2031C.ms.model.script' // GblAdapterLib
 WL 'ME_4677FBA70343' '4677FBA70343.ms.model.script' // l3Interfaces
 WL 'ME_4677FF4B0036' '4677FF4B0036.ms.model.script' // Data
 WL 'ME_467A75D90346' '467A75D90346.ms.model.script' // VT
 WL 'ME_467A8734039C' '467A8734039C.ms.model.script' // EVD
 WL 'ME_4680E7D50168' '4680E7D50168.ms.model.script' // Everest Engine
 WL 'ME_4790B4F00236' '4790B4F00236.ms.model.script' // AFW
 WL 'ME_4790C3B8021E' '4790C3B8021E.ms.model.script' // VCM
 WL 'ME_4790D09A0378' '4790D09A0378.ms.model.script' // L3
 WL 'ME_4799D29F033F' '4799D29F033F.ms.model.script' // Implementation
 WL 'ME_490838AA02D0' '490838AA02D0.ms.model.script' // Nemesis
 WL 'ME_4954C0500033' '4954C0500033.ms.model.script' // UserInteraction
 WL 'ME_4954FAA00232' '4954FAA00232.ms.model.script' // Search
 WL 'ME_4A7C099B004F' '4A7C099B004F.ms.model.script' // View
 WL 'ME_4A825D4902F1' '4A825D4902F1.ms.model.script' // WorkJournal
 WL 'ME_4A9FFD3F01AD' '4A9FFD3F01AD.ms.model.script' // Search
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.ms.model.script' // Sys
 WL 'ME_4AB0C3F60375' '4AB0C3F60375.ms.model.script' // Win
 WL 'ME_4E13416D0227' '4E13416D0227.ms.model.script' // VCM$Visual
 WL 'ME_4E2F0E1B03BB' '4E2F0E1B03BB.ms.model.script' // L3$Domain
 )
 ; // Depends
 UP "exec mode" 'concluded'
 UP "gui" 'prj'
 UP "is namespace" true
 UP "vendor" 'none'
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'

ENDME // ME_4A811B89032D View
