// System 4A8E792A0108 VCMControls Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4A8E792A0108

FORWARD ME_4A8E794D0133

FORWARD ME_4C7D38560348

: ME_4C7D386802AE
 CONST UID '4C7D386802AE'
 CONST Name 'On'
 CONST Class class_Class
 : Stereotype st_VCMOperationState ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4C7D38560348 // CantReceiveLegalServiceAnswer
 ;
 CONST "Checked" 'undefined'
 CONST "Enabled" 'undefined'
 CONST "Hint" 'Произошла ошибка связи при получении ответов службы Правовой поддержки онлайн. '' + ''В связи с этим ответы на ранее заданные Вами вопросы не могут быть доставлены.'' + #13#10#13#10 + ''Для решения технических вопросов обратитесь, к Вашему системному администратору. '' + ''Если проблемы с интернет-соединением возникают только для системы ГАРАНТ, обратитесь в обслуживающую Вас организацию:'' + #13#10 + ''<текст из dealer.inf>'
 CONST "ImageIndex" 185
 CONST "Visible" 'undefined'

ref; // ME_4C7D386802AE On

: ME_4C7D38BB0233
 CONST UID '4C7D38BB0233'
 CONST Name 'Off'
 CONST Class class_Class
 : Stereotype st_VCMOperationState ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Связь восстановлена' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4C7D38560348 // CantReceiveLegalServiceAnswer
 ;
 CONST "Checked" 'undefined'
 CONST "Enabled" 'undefined'
 CONST "ImageIndex" 186
 CONST "Visible" 'undefined'

ref; // ME_4C7D38BB0233 Off

: ME_4C7D38D100AB
 CONST UID '4C7D38D100AB'
 CONST Name 'Disabled'
 CONST Class class_Class
 : Stereotype st_VCMOperationState ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4C7D38560348 // CantReceiveLegalServiceAnswer
 ;
 CONST "Checked" 'undefined'
 CONST "Enabled" false
 CONST "Visible" 'undefined'

ref; // ME_4C7D38D100AB Disabled

: ME_4C7D38560348
 CONST UID '4C7D38560348'
 CONST Name 'CantReceiveLegalServiceAnswer'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Статус связи с ППО' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4A8E794D0133 // System
 ;
 : Children
   Seq: ( ME_4C7D386802AE // On
 ME_4C7D38BB0233 // Off
 ME_4C7D38D100AB // Disabled
 )
 ; // Children
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" false
 CONST "has states" true
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false

ref; // ME_4C7D38560348 CantReceiveLegalServiceAnswer

: ME_4A8E794D0133
 CONST UID '4A8E794D0133'
 CONST Name 'System'
 CONST Class class_Class
 : Stereotype st_VCMOperations ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Система' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A8E792A0108 // System
 ;
 : Operations
   Seq: ( ME_4C7D38560348 // CantReceiveLegalServiceAnswer
 )
 ; // Operations

ref; // ME_4A8E794D0133 System

FORWARD ME_4C8A2A4B03A8

: ME_4C8A2A5C03E4
 CONST UID '4C8A2A5C03E4'
 CONST Name 'IncreaseFont'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A2A4B03A8 // Fonts
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" true
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false

ref; // ME_4C8A2A5C03E4 IncreaseFont

: ME_4C8A2A72034C
 CONST UID '4C8A2A72034C'
 CONST Name 'DecreaseFont'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A2A4B03A8 // Fonts
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" true
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false

ref; // ME_4C8A2A72034C DecreaseFont

: ME_4C8A2A4B03A8
 CONST UID '4C8A2A4B03A8'
 CONST Name 'Fonts'
 CONST Class class_Class
 : Stereotype st_VCMOperations ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A8E792A0108 // System
 ;
 : Operations
   Seq: ( ME_4C8A2A5C03E4 // IncreaseFont
 ME_4C8A2A72034C // DecreaseFont
 )
 ; // Operations

ref; // ME_4C8A2A4B03A8 Fonts

FORWARD ME_4C8A43A101CA

: ME_4C8A43B3015E
 CONST UID '4C8A43B3015E'
 CONST Name 'HotInformation'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A43A101CA // Help
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false

ref; // ME_4C8A43B3015E HotInformation

: ME_4C8A43C40120
 CONST UID '4C8A43C40120'
 CONST Name 'HelpShortCuts'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A43A101CA // Help
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false

ref; // ME_4C8A43C40120 HelpShortCuts

: ME_4C8A43E30011
 CONST UID '4C8A43E30011'
 CONST Name 'HelpNewFeatures'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A43A101CA // Help
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false

ref; // ME_4C8A43E30011 HelpNewFeatures

: ME_4C8A43FE01BD
 CONST UID '4C8A43FE01BD'
 CONST Name 'ContactInformation'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A43A101CA // Help
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false

ref; // ME_4C8A43FE01BD ContactInformation

: ME_4C8A440F025D
 CONST UID '4C8A440F025D'
 CONST Name 'ReplyBook'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A43A101CA // Help
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false

ref; // ME_4C8A440F025D ReplyBook

: ME_4C8A4428006F
 CONST UID '4C8A4428006F'
 CONST Name 'GarantInternet'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A43A101CA // Help
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false

ref; // ME_4C8A4428006F GarantInternet

: ME_4C8A4442036F
 CONST UID '4C8A4442036F'
 CONST Name 'About'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A43A101CA // Help
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false

ref; // ME_4C8A4442036F About

: ME_4C8A43A101CA
 CONST UID '4C8A43A101CA'
 CONST Name 'Help'
 CONST Class class_Class
 : Stereotype st_VCMOperations ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A8E792A0108 // System
 ;
 : Operations
   Seq: ( ME_4C8A43B3015E // HotInformation
 ME_4C8A43C40120 // HelpShortCuts
 ME_4C8A43E30011 // HelpNewFeatures
 ME_4C8A43FE01BD // ContactInformation
 ME_4C8A440F025D // ReplyBook
 ME_4C8A4428006F // GarantInternet
 ME_4C8A4442036F // About
 )
 ; // Operations

ref; // ME_4C8A43A101CA Help

FORWARD ME_4C8A44B70008

: ME_4C8A44DD0291
 CONST UID '4C8A44DD0291'
 CONST Name 'BookmarkList'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A44B70008 // System$Bookmarks
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false

ref; // ME_4C8A44DD0291 BookmarkList

: ME_4C8A44B70008
 CONST UID '4C8A44B70008'
 CONST Name 'System'
 CONST Class class_Class
 : Stereotype st_VCMOperations ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A8E792A0108 // System
 ;
 : Operations
   Seq: ( ME_4C8A44DD0291 // BookmarkList
 )
 ; // Operations

ref; // ME_4C8A44B70008 System$Bookmarks

FORWARD ME_4C8A4525032B

: ME_4C8A454E0063
 CONST UID '4C8A454E0063'
 CONST Name 'BuildControlledList'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Построить список изменившихся документов на контроле' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A4525032B // WarnOnControl
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" true
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false

ref; // ME_4C8A454E0063 BuildControlledList

: ME_4C8A456A0188
 CONST UID '4C8A456A0188'
 CONST Name 'OpenUnderControlTree'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Открыть вкладку "Документы на контроле"' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A4525032B // WarnOnControl
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" true
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false

ref; // ME_4C8A456A0188 OpenUnderControlTree

: ME_4C8A4584039B
 CONST UID '4C8A4584039B'
 CONST Name 'HideReminder'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Скрыть предупреждающий знак' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4C8A4525032B // WarnOnControl
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" true
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false

ref; // ME_4C8A4584039B HideReminder

: ME_4C8A4525032B
 CONST UID '4C8A4525032B'
 CONST Name 'WarnOnControl'
 CONST Class class_Class
 : Stereotype st_VCMOperations ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A8E792A0108 // System
 ;
 : Operations
   Seq: ( ME_4C8A454E0063 // BuildControlledList
 ME_4C8A456A0188 // OpenUnderControlTree
 ME_4C8A4584039B // HideReminder
 )
 ; // Operations

ref; // ME_4C8A4525032B WarnOnControl

FORWARD ME_4F86AADE0325

: ME_4F86AAF903B5
 CONST UID '4F86AAF903B5'
 CONST Name 'RemMWControlledChangingWarning'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4F86AADE0325 // Reminder$ForMainWindow
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false

ref; // ME_4F86AAF903B5 RemMWControlledChangingWarning

: ME_4F86AB3A03E4
 CONST UID '4F86AB3A03E4'
 CONST Name 'RemMWOldBaseWarning'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4F86AADE0325 // Reminder$ForMainWindow
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false

ref; // ME_4F86AB3A03E4 RemMWOldBaseWarning

: ME_4F86AB490283
 CONST UID '4F86AB490283'
 CONST Name 'RemMWTrialModeWarning'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4F86AADE0325 // Reminder$ForMainWindow
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false

ref; // ME_4F86AB490283 RemMWTrialModeWarning

: ME_4F86AB5600B9
 CONST UID '4F86AB5600B9'
 CONST Name 'RemNewChatMessages'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4F86AADE0325 // Reminder$ForMainWindow
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false

ref; // ME_4F86AB5600B9 RemNewChatMessages

: ME_4F86AB6502AA
 CONST UID '4F86AB6502AA'
 CONST Name 'RemOnlineDead'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4F86AADE0325 // Reminder$ForMainWindow
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false

ref; // ME_4F86AB6502AA RemOnlineDead

: ME_542D70330042
 CONST UID '542D70330042'
 CONST Name 'remUnreadConsultations'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4F86AADE0325 // Reminder$ForMainWindow
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false

ref; // ME_542D70330042 remUnreadConsultations

: ME_4F86AADE0325
 CONST UID '4F86AADE0325'
 CONST Name 'Reminder'
 CONST Class class_Class
 : Stereotype st_VCMOperations ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A8E792A0108 // System
 ;
 : Operations
   Seq: ( ME_4F86AAF903B5 // RemMWControlledChangingWarning
 ME_4F86AB3A03E4 // RemMWOldBaseWarning
 ME_4F86AB490283 // RemMWTrialModeWarning
 ME_4F86AB5600B9 // RemNewChatMessages
 ME_4F86AB6502AA // RemOnlineDead
 ME_542D70330042 // remUnreadConsultations
 )
 ; // Operations

ref; // ME_4F86AADE0325 Reminder$ForMainWindow

FORWARD ME_4F882119031B

: ME_4F88213001DE
 CONST UID '4F88213001DE'
 CONST Name 'MemUsage'
 CONST Class class_Class
 : Stereotype st_VCMOperation ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4F882119031B // Common$MemUsage
 ;
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" true
 CONST "no prefix" false

ref; // ME_4F88213001DE MemUsage

: ME_4F882119031B
 CONST UID '4F882119031B'
 CONST Name 'Common'
 CONST Class class_Class
 : Stereotype st_VCMOperations ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A8E792A0108 // System
 ;
 : Operations
   Seq: ( ME_4F88213001DE // MemUsage
 )
 ; // Operations

ref; // ME_4F882119031B Common$MemUsage

: ME_4A8E792A0108
 CONST UID '4A8E792A0108'
 CONST Name 'System'
 CONST Class class_Category
 : Stereotype st_VCMControls ;
 %SUMMARY '"Системные"' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4F7D7B980383' '4F7D7B980383.pas.ms.script' // View
 ;
 : Children
   Seq: ( ME_4A8E794D0133 // System
 ME_4C8A2A4B03A8 // Fonts
 ME_4C8A43A101CA // Help
 ME_4C8A44B70008 // System$Bookmarks
 ME_4C8A4525032B // WarnOnControl
 ME_4F86AADE0325 // Reminder$ForMainWindow
 ME_4F882119031B // Common$MemUsage
 )
 ; // Children
 CONST "is namespace" true
 CONST "no hands" false
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\F1_Without_Usecases_System_Controls.pas'
 CONST extprop:pas:UnitName 'F1_Without_Usecases_System_Controls'

ref; // ME_4A8E792A0108 System
