// DrugData 4A9FCCDB035B Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4A9FCCDB035B
%%Inner ME_4A9FCCDB035B
%%Inner ME_4A9FCCDB035B

FORWARD ME_4A9FCCDB035B

FORWARD ME_47EB3E410033

ME ME_47FF3A7E02A7
 MEPROP UID '47FF3A7E02A7'
 MEPROP Name 'f_NodeForPositioning'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_ref
 MELINK Parent HWL ME_47EB3E410033 // TdDrugList
 ;
 MELINK Target WL 'ME_468259900322' '4682595B0268.ms.model.script' // Il3SimpleNode
 ;

ENDME // ME_47FF3A7E02A7 f_NodeForPositioning

ME ME_47F37FDA00B9
 MEPROP UID '47F37FDA00B9'
 MEPROP Name 'f_List'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_47EB3E410033 // TdDrugList
 ;
 MELINK Target WL 'ME_45EEDB730265' '45700BFD0251.ms.model.script' // DynList
 ;

ENDME // ME_47F37FDA00B9 f_List

ME ME_4B220E3B03E3
 MEPROP UID '4B220E3B03E3'
 MEPROP Name 'IvcmRealData'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_47EB3E410033 // TdDrugList
 ;
 MELINK Target WL 'ME_47EB3BEB00F1' '491D7C9603B2.ms.model.script' // IdDrugList
 ;

ENDME // ME_4B220E3B03E3 IvcmRealData

ME ME_494176F40163
 MEPROP UID '494176F40163'
 MEPROP Name 'Make'
 MEPROP Class class_Operation
 MELINK Stereotype st_factory::Operation ;
 %SUMMARY 'Фабричный метод' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47EB3E410033 // TdDrugList
 ;

ENDME // ME_494176F40163 Make

ME ME_47EB5C780228
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47EB3E410033 // TdDrugList
 ;
 MELINK Target WL 'ME_47EB55FD007A' '4982B6510327.ms.model.script' // TvcmFormDataSourceRef
 ;

ENDME // ME_47EB5C780228 

ME ME_0048137F6167_ME_47EB3E410033
 MELINK Original WL 'ME_0048137F6167' '491D7C9603B2.ms.model.script' // dsFiltersRef
 ;
 MEPROP OpKind opkind_Implemented
 UP "needs field" true
 UP "pm" true
ENDME // ME_0048137F6167_ME_47EB3E410033 dsFiltersRef

ME ME_38AF3FCA8739_ME_47EB3E410033
 MELINK Original WL 'ME_38AF3FCA8739' '491D7C9603B2.ms.model.script' // dsDrugListRef
 ;
 MEPROP OpKind opkind_Implemented
 UP "needs field" true
 UP "pm" true
ENDME // ME_38AF3FCA8739_ME_47EB3E410033 dsDrugListRef

ME ME_47F37CF2000D_ME_47EB3E410033
 MELINK Original WL 'ME_47F37CF2000D' '491D7C9603B2.ms.model.script' // List
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_47F37CF2000D_ME_47EB3E410033 List

ME ME_47FF3A4C03E7_ME_47EB3E410033
 MELINK Original WL 'ME_47FF3A4C03E7' '491D7C9603B2.ms.model.script' // NodeForPositioning
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_47FF3A4C03E7_ME_47EB3E410033 NodeForPositioning

ME ME_6DCE2C2DE35F_ME_47EB3E410033
 MELINK Original WL 'ME_6DCE2C2DE35F' '491D7C9603B2.ms.model.script' // dsListInfoRef
 ;
 MEPROP OpKind opkind_Implemented
 UP "needs field" true
 UP "pm" true
ENDME // ME_6DCE2C2DE35F_ME_47EB3E410033 dsListInfoRef

ME ME_8C15EA0B7407_ME_47EB3E410033
 MELINK Original WL 'ME_8C15EA0B7407' '491D7C9603B2.ms.model.script' // dsSynchroViewRef
 ;
 MEPROP OpKind opkind_Implemented
 UP "needs field" true
 UP "pm" true
ENDME // ME_8C15EA0B7407_ME_47EB3E410033 dsSynchroViewRef

ME ME_B53EF7286977_ME_47EB3E410033
 MELINK Original WL 'ME_B53EF7286977' '491D7C9603B2.ms.model.script' // DrugList_SynchroView_Form
 ;
 MEPROP OpKind opkind_Implemented
 UP "needs field" true
 UP "pm" true
ENDME // ME_B53EF7286977_ME_47EB3E410033 DrugList_SynchroView_Form

ME ME_47A042E100E2_ME_47EB3E410033
 MELINK Original WL 'ME_47A042E100E2' '47913F4E02E0.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_47EB3E410033 InitFields

ME ME_4B16B8CF0307_ME_47EB3E410033
 MELINK Original WL 'ME_4B16B8CF0307' '4B16B85D03A1.ms.model.script' // AssignData
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_4B16B8CF0307_ME_47EB3E410033 AssignData

%%ImplementedBy ME_47EB3BEB00F1 ME_47EB3E410033

%%InheritedBy ME_47F07A9F0098 ME_47EB3E410033

ME ME_47EB3E410033
 MEPROP UID '47EB3E410033'
 MEPROP Name 'TdDrugList'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Данные сборки "Список лекартсвенных препаратов".' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4A9FCCDB035B // DrugData
 ;
 MELIST Inherits
   Seq: ( WL 'ME_47F07A9F0098' '47F07A9F0098.ms.model.script' // dBaseDrugDocument
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_47EB3BEB00F1' '491D7C9603B2.ms.model.script' // IdDrugList
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_47FF3A7E02A7 // f_NodeForPositioning
 HWL ME_47F37FDA00B9 // f_List
 HWL ME_4B220E3B03E3 // IvcmRealData
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_494176F40163 // Make
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_0048137F6167_ME_47EB3E410033 // dsFiltersRef
 ME_38AF3FCA8739_ME_47EB3E410033 // dsDrugListRef
 ME_47F37CF2000D_ME_47EB3E410033 // List
 ME_47FF3A4C03E7_ME_47EB3E410033 // NodeForPositioning
 ME_6DCE2C2DE35F_ME_47EB3E410033 // dsListInfoRef
 ME_8C15EA0B7407_ME_47EB3E410033 // dsSynchroViewRef
 ME_B53EF7286977_ME_47EB3E410033 // DrugList_SynchroView_Form
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_47A042E100E2_ME_47EB3E410033 // InitFields
 ME_4B16B8CF0307_ME_47EB3E410033 // AssignData
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_47EB5C780228 // TvcmFormDataSourceRef
 )
 ; // Dependencies
 UP "no hands" true
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Drug\dDrugList.pas'
 UP extprop:rc:SelfName 'dDrugList'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'dDrugList'

ENDME // ME_47EB3E410033 TdDrugList

FORWARD ME_47F4CCAD037F

ME ME_4B1937860328
 MEPROP UID '4B1937860328'
 MEPROP Name 'f_ContentsTree'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_ref
 MELINK Parent HWL ME_47F4CCAD037F // TdDrugDocument
 ;
 MELINK Target WL 'ME_49145BA70313' '491B305A0096.ms.model.script' // IdeSimpleTree
 ;

ENDME // ME_4B1937860328 f_ContentsTree

ME ME_4B220E4E01FC
 MEPROP UID '4B220E4E01FC'
 MEPROP Name 'IvcmRealData'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_47F4CCAD037F // TdDrugDocument
 ;
 MELINK Target WL 'ME_49365A300185' '491D7C9603B2.ms.model.script' // IdDrugDocument
 ;

ENDME // ME_4B220E4E01FC IvcmRealData

FORWARD ME_4B1936C003CB

ME ME_4B1936C70313
 MEPROP UID '4B1936C70313'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B1936C003CB // Make
 ;

ENDME // ME_4B1936C70313 DoIt

ME ME_4B1936C003CB
 MEPROP UID '4B1936C003CB'
 MEPROP Name 'Make'
 MEPROP Class class_Class
 MELINK Stereotype st_Factory ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47F4CCAD037F // TdDrugDocument
 ;
 MELIST Operations
   Seq: ( HWL ME_4B1936C70313 // DoIt
 )
 ; // Operations

ENDME // ME_4B1936C003CB Make

ME ME_4B1937BE0268
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47F4CCAD037F // TdDrugDocument
 ;
 MELINK Target WL 'ME_4ADEE49C02DF' '47877EB202FB.ms.model.script' // Supports
 ;

ENDME // ME_4B1937BE0268 

ME ME_4B1937CC013D
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47F4CCAD037F // TdDrugDocument
 ;
 MELINK Target WL 'ME_4982B6510327' '4982B6510327.ms.model.script' // vcmFormDataSourceRef
 ;

ENDME // ME_4B1937CC013D 

ME ME_3A7D008F28B6_ME_47F4CCAD037F
 MELINK Original WL 'ME_3A7D008F28B6' '491D7C9603B2.ms.model.script' // dsContentsRef
 ;
 MEPROP OpKind opkind_Implemented
 UP "needs field" true
 UP "pm" true
ENDME // ME_3A7D008F28B6_ME_47F4CCAD037F dsContentsRef

ME ME_493925D603CF_ME_47F4CCAD037F
 MELINK Original WL 'ME_493925D603CF' '491D7C9603B2.ms.model.script' // ContentsTree
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDME // ME_493925D603CF_ME_47F4CCAD037F ContentsTree

ME ME_479731C50290_ME_47F4CCAD037F
 MELINK Original WL 'ME_479731C50290' '51612ED700B4.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_47F4CCAD037F Cleanup

ME ME_4B16B8CF0307_ME_47F4CCAD037F
 MELINK Original WL 'ME_4B16B8CF0307' '4B16B85D03A1.ms.model.script' // AssignData
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_4B16B8CF0307_ME_47F4CCAD037F AssignData

%%ImplementedBy ME_49365A300185 ME_47F4CCAD037F

%%InheritedBy ME_47F07A9F0098 ME_47F4CCAD037F

ME ME_47F4CCAD037F
 MEPROP UID '47F4CCAD037F'
 MEPROP Name 'TdDrugDocument'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Данные описания препарата.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4A9FCCDB035B // DrugData
 ;
 MELIST Inherits
   Seq: ( WL 'ME_47F07A9F0098' '47F07A9F0098.ms.model.script' // dBaseDrugDocument
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_49365A300185' '491D7C9603B2.ms.model.script' // IdDrugDocument
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_4B1937860328 // f_ContentsTree
 HWL ME_4B220E4E01FC // IvcmRealData
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_4B1936C003CB // Make
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_3A7D008F28B6_ME_47F4CCAD037F // dsContentsRef
 ME_493925D603CF_ME_47F4CCAD037F // ContentsTree
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_47F4CCAD037F // Cleanup
 ME_4B16B8CF0307_ME_47F4CCAD037F // AssignData
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_4B1937BE0268 // Supports
 ME_4B1937CC013D // vcmFormDataSourceRef
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "no hands" true
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Drug\dDrugDocument.pas'
 UP extprop:rc:SelfName 'dDrugDocument'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'dDrugDocument'

ENDME // ME_47F4CCAD037F TdDrugDocument

ME ME_4A9FCCDB035B
 MEPROP UID '4A9FCCDB035B'
 MEPROP Name 'DrugData'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_49410AA9008B' '49410AA9008B.ms.model.script' // Drug
 ;
 MELIST Children
   Seq: ( WL 'ME_47F07A9F0098' '47F07A9F0098.ms.model.script' // dBaseDrugDocument
 HWL ME_47EB3E410033 // TdDrugList
 HWL ME_47F4CCAD037F // TdDrugDocument
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_45700BFD0251' '45700BFD0251.ms.model.script' // DynamicDocList
 WL 'ME_4678193C009C' '4678193C009C.ms.model.script' // l3Types
 WL 'ME_4682595B0268' '4682595B0268.ms.model.script' // l3TreeInterfaces
 WL 'ME_47D0290B016D' '47D0290B016D.ms.model.script' // l3Utils
 WL 'ME_47D0E1500033' '47D0E1500033.ms.model.script' // Implementation
 WL 'ME_47EA07FA02CE' '47EA07FA02CE.ms.model.script' // bsTypes
 WL 'ME_47EA50050263' '47EA50050263.ms.model.script' // BaseDocument
 WL 'ME_47F260DC003F' '47F260DC003F.ms.model.script' // ns
 WL 'ME_491B305A0096' '491B305A0096.ms.model.script' // DocumentAndListInterfaces
 WL 'ME_491D7C9603B2' '491D7C9603B2.ms.model.script' // MedicInterfaces
 WL 'ME_4982BE090383' '4982BE090383.ms.model.script' // vcmControllers
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.ms.model.script' // Sys
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_4A9FCCDB035B DrugData
