// MainMenuTrees 4A9FB4EE00FE Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4A9FB4EE00FE

FORWARD ME_490B0E9A02A2

: ME_4E738B17023D
 CONST UID '4E738B17023D'
 CONST Name 'f_Section'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent ME_490B0E9A02A2 // TsmTree
 ;
 : Target WL 'ME_4E36C7590390' '4DD24BD40021.pas.ms.script' // Section
 ;

ref; // ME_4E738B17023D f_Section

: ME_4E738EF703A8
 CONST UID '4E738EF703A8'
 CONST Name 'f_SectionType'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_490B0E9A02A2 // TsmTree
 ;
 : Target WL 'ME_4E3011A101F7' '4DD24BD40021.pas.ms.script' // SectionType
 ;

ref; // ME_4E738EF703A8 f_SectionType

FORWARD ME_4E73127A01C7

: ME_4E7312C403D9
 CONST Name 'aRoot'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4771111001F9' '476BF10A0280.pas.ms.script' // Il3RootNode
 ;

ref; // ME_4E7312C403D9 aRoot

: ME_4E7312C50025
 CONST Name 'aSectionType'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4E3011A101F7' '4DD24BD40021.pas.ms.script' // SectionType
 ;

ref; // ME_4E7312C50025 aSectionType

: ME_4E7312AA02AC
 CONST UID '4E7312AA02AC'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4E73127A01C7 // AddItems2011
 ;
 : Parameters
   Seq: ( ME_4E7312C403D9 // aRoot
 ME_4E7312C50025 // aSectionType
 )
 ; // Parameters

ref; // ME_4E7312AA02AC DoIt

: ME_4E7312EE0290
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4E73127A01C7 // AddItems2011
 ;
 : Target WL 'ME_4E730AE6014C' '4909EECE01D5.pas.ms.script' // TnsMainMenu2011Node
 ;

ref; // ME_4E7312EE0290 

: ME_4E731314024F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4E73127A01C7 // AddItems2011
 ;
 : Target WL 'ME_4B1E8FAE0380' '48F747EC0073.pas.ms.script' // DefDataAdapter
 ;

ref; // ME_4E731314024F 

: ME_4E738AFF0071
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4E73127A01C7 // AddItems2011
 ;
 : Target WL 'ME_4E36C7590390' '4DD24BD40021.pas.ms.script' // Section
 ;

ref; // ME_4E738AFF0071 

: ME_4E73127A01C7
 CONST UID '4E73127A01C7'
 CONST Name 'AddItems2011'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent ME_490B0E9A02A2 // TsmTree
 ;
 : Operations
   Seq: ( ME_4E7312AA02AC // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4E7312EE0290 // 
 ME_4E731314024F // 
 ME_4E738AFF0071 // 
 )
 ; // Dependencies
 CONST "is static" false

ref; // ME_4E73127A01C7 AddItems2011

: ME_490B0F4001D4
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_490B0E9A02A2 // TsmTree
 ;
 : Target WL 'ME_490B0F4F021C' '4909EECE01D5.pas.ms.script' // TnsMainMenuNode
 ;

ref; // ME_490B0F4001D4 

: ME_4B38FA9401FC
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_490B0E9A02A2 // TsmTree
 ;
 : Target WL 'ME_4AC0B9CF018A' '47D0E1500033.pas.ms.script' // vcmCStr
 ;

ref; // ME_4B38FA9401FC 

: ME_4E730D94016B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_490B0E9A02A2 // TsmTree
 ;
 : Target WL 'ME_4E730AE6014C' '4909EECE01D5.pas.ms.script' // TnsMainMenu2011Node
 ;

ref; // ME_4E730D94016B 

: ME_4908AAED02BD_ME_490B0E9A02A2
 : Original WL 'ME_4908AAED02BD' '4908A8A20107.pas.ms.script' // BeforeReset
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4908AAED02BD_ME_490B0E9A02A2 BeforeReset

: ME_5000565C019C_ME_490B0E9A02A2
 : Original WL 'ME_5000565C019C' '47913B47006E.pas.ms.script' // ClearFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_5000565C019C_ME_490B0E9A02A2 ClearFields

: ME_490B0E9A02A2
 CONST UID '490B0E9A02A2'
 CONST Name 'TsmTree'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A9FB4EE00FE // MainMenuTrees
 ;
 : Inherits
   Seq: ( WL 'ME_4909EF3B02B1' '4909EECE01D5.pas.ms.script' // TnsBaseMainMenuTree
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4E70D70C0055' '48563BA400A9.pas.ms.script' // Основное меню должно уметь зависеть от должности пользователя
 )
 ; // Implements
 : Attributes
   Seq: ( ME_4E738B17023D // f_Section
 ME_4E738EF703A8 // f_SectionType
 )
 ; // Attributes
 : Operations
   Seq: ( ME_4E73127A01C7 // AddItems2011
 )
 ; // Operations
 : Overridden
   Seq: ( ME_4908AAED02BD_ME_490B0E9A02A2 // BeforeReset
 ME_5000565C019C_ME_490B0E9A02A2 // ClearFields
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_490B0F4001D4 // 
 ME_4B38FA9401FC // 
 ME_4E730D94016B // 
 )
 ; // Dependencies
 CONST "author" 'Морозов М.А.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\MainMenu\smTree.pas'
 CONST extprop:rc:SelfName 'smTree'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'smTree'

ref; // ME_490B0E9A02A2 TsmTree

FORWARD ME_490C2AE8028E

: ME_490C2B4600A2
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_490C2AE8028E // TsmLawNewsTree
 ;
 : Target WL 'ME_47FB50E4008E' '48F747EC0073.pas.ms.script' // nsConst
 ;

ref; // ME_490C2B4600A2 

: ME_4E7316330357
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_490C2AE8028E // TsmLawNewsTree
 ;
 : Target WL 'ME_4E3011A101F7' '4DD24BD40021.pas.ms.script' // SectionType
 ;

ref; // ME_4E7316330357 

: ME_4909EF6E0361_ME_490C2AE8028E
 : Original WL 'ME_4909EF6E0361' '4909EECE01D5.pas.ms.script' // MakeRoot
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4909EF6E0361_ME_490C2AE8028E MakeRoot

: ME_490C2AE8028E
 CONST UID '490C2AE8028E'
 CONST Name 'TsmLawNewsTree'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Дерево "Изменения в законодательстве" для простого основного меню' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A9FB4EE00FE // MainMenuTrees
 ;
 : Inherits
   Seq: ( ME_490B0E9A02A2 // TsmTree
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4E70D70C0055' '48563BA400A9.pas.ms.script' // Основное меню должно уметь зависеть от должности пользователя
 )
 ; // Implements
 : Overridden
   Seq: ( ME_4909EF6E0361_ME_490C2AE8028E // MakeRoot
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_490C2B4600A2 // 
 ME_4E7316330357 // 
 )
 ; // Dependencies
 CONST "author" 'Морозов М.А.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\MainMenu\smLawNewsTree.pas'
 CONST extprop:rc:SelfName 'smLawNewsTree'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'smLawNewsTree'

ref; // ME_490C2AE8028E TsmLawNewsTree

FORWARD ME_4AFBF77E0200

: ME_4AFBF7AB006B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4AFBF77E0200 // TsmNewSchoolReferencesTree
 ;
 : Target WL 'ME_4ABB8B1B031D' '4908A8A20107.pas.ms.script' // nsMakeTreeLevel
 ;

ref; // ME_4AFBF7AB006B 

: ME_4AFBF7AE0291
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4AFBF77E0200 // TsmNewSchoolReferencesTree
 ;
 : Target WL 'ME_4AA7888B0076' '47913B47006E.pas.ms.script' // l3CStr
 ;

ref; // ME_4AFBF7AE0291 

: ME_4AFBF7B102B6
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4AFBF77E0200 // TsmNewSchoolReferencesTree
 ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_4AFBF7B102B6 

: ME_4AFBF7B401DE
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4AFBF77E0200 // TsmNewSchoolReferencesTree
 ;
 : Target WL 'ME_4909AEB00352' '48FD8B2702F6.pas.ms.script' // TnsINodeWrap
 ;

ref; // ME_4AFBF7B401DE 

: ME_4AFBF7B70389
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4AFBF77E0200 // TsmNewSchoolReferencesTree
 ;
 : Target WL 'ME_490AF9B0039B' '4908A8A20107.pas.ms.script' // TnsNewCachableNode
 ;

ref; // ME_4AFBF7B70389 

: ME_4AFBF7BC01BD
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4AFBF77E0200 // TsmNewSchoolReferencesTree
 ;
 : Target WL 'ME_456EC91500FA' '456EA56002BF.pas.ms.script' // NavigatorMenuItemType
 ;

ref; // ME_4AFBF7BC01BD 

: ME_4AFBF7C00012
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4AFBF77E0200 // TsmNewSchoolReferencesTree
 ;
 : Target WL 'ME_490B011B02DB' '47F2170002B2.pas.ms.script' // TnsNavigatorItemParams
 ;

ref; // ME_4AFBF7C00012 

: ME_4E738C9302F0
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4AFBF77E0200 // TsmNewSchoolReferencesTree
 ;
 : Target WL 'ME_4E3011A101F7' '4DD24BD40021.pas.ms.script' // SectionType
 ;

ref; // ME_4E738C9302F0 

: ME_4909EF6E0361_ME_4AFBF77E0200
 : Original WL 'ME_4909EF6E0361' '4909EECE01D5.pas.ms.script' // MakeRoot
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4909EF6E0361_ME_4AFBF77E0200 MakeRoot

: ME_4AFBF77E0200
 CONST UID '4AFBF77E0200'
 CONST Name 'TsmNewSchoolReferencesTree'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A9FB4EE00FE // MainMenuTrees
 ;
 : Inherits
   Seq: ( ME_490B0E9A02A2 // TsmTree
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4E70D70C0055' '48563BA400A9.pas.ms.script' // Основное меню должно уметь зависеть от должности пользователя
 )
 ; // Implements
 : Overridden
   Seq: ( ME_4909EF6E0361_ME_4AFBF77E0200 // MakeRoot
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_4AFBF7AB006B // 
 ME_4AFBF7AE0291 // 
 ME_4AFBF7B102B6 // 
 ME_4AFBF7B401DE // 
 ME_4AFBF7B70389 // 
 ME_4AFBF7BC01BD // 
 ME_4AFBF7C00012 // 
 ME_4E738C9302F0 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\MainMenu\smNewSchoolReferencesTree.pas'
 CONST extprop:rc:SelfName 'smNewSchoolReferencesTree'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'smNewSchoolReferencesTree'

ref; // ME_4AFBF77E0200 TsmNewSchoolReferencesTree

FORWARD ME_4E73239003D0

: ME_4E7323D9023E
 CONST UID '4E7323D9023E'
 CONST Name 'f_SectionType'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4E73239003D0 // TsmChangeableTree
 ;
 : Target WL 'ME_4E3011A101F7' '4DD24BD40021.pas.ms.script' // SectionType
 ;

ref; // ME_4E7323D9023E f_SectionType

FORWARD ME_4E73249703A9

: ME_4E732871010D
 CONST Name 'aSectionType'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4E3011A101F7' '4DD24BD40021.pas.ms.script' // SectionType
 ;

ref; // ME_4E732871010D aSectionType

: ME_4E7324AB0253
 CONST UID '4E7324AB0253'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4E73249703A9 // Create
 ;
 : Parameters
   Seq: ( ME_4E732871010D // aSectionType
 )
 ; // Parameters

ref; // ME_4E7324AB0253 DoIt

: ME_4E73249703A9
 CONST UID '4E73249703A9'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4E73239003D0 // TsmChangeableTree
 ;
 : Operations
   Seq: ( ME_4E7324AB0253 // DoIt
 )
 ; // Operations

ref; // ME_4E73249703A9 Create

FORWARD ME_4E7324A00304

: ME_FB06A4A8497C
 CONST Name 'aSectionType'
 CONST IsSummoned true
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4E3011A101F7' '4DD24BD40021.pas.ms.script' // SectionType
 ;

ref; // ME_FB06A4A8497C aSectionType

: ME_C913DBB42B14
 CONST UID 'C913DBB42B14'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY 'Сигнатура фабрики TsmChangeableTree.Make' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4E7324A00304 // Make
 ;
 : Target WL 'ME_46825CC00249' '4682595B0268.pas.ms.script' // Il3SimpleTree
 ;
 : Parameters
   Seq: ( ME_FB06A4A8497C // aSectionType
 )
 ; // Parameters

ref; // ME_C913DBB42B14 DoIt

: ME_4E7324A00304
 CONST UID '4E7324A00304'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4E73239003D0 // TsmChangeableTree
 ;
 : Inherits
   Seq: ( ME_4E73249703A9 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_46825CC00249' '4682595B0268.pas.ms.script' // Il3SimpleTree
 )
 ; // Implements
 : Operations
   Seq: ( ME_C913DBB42B14 // DoIt
 )
 ; // Operations
 CONST "check nil" false
 CONST "need AfterCreate" 'undefined'
 CONST "need Aggregate" 'undefined'
 CONST "need As" false

ref; // ME_4E7324A00304 Make

: ME_4909EF6E0361_ME_4E73239003D0
 : Original WL 'ME_4909EF6E0361' '4909EECE01D5.pas.ms.script' // MakeRoot
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4909EF6E0361_ME_4E73239003D0 MakeRoot

: ME_4E73239003D0
 CONST UID '4E73239003D0'
 CONST Name 'TsmChangeableTree'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4A9FB4EE00FE // MainMenuTrees
 ;
 : Inherits
   Seq: ( ME_490B0E9A02A2 // TsmTree
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4E70D70C0055' '48563BA400A9.pas.ms.script' // Основное меню должно уметь зависеть от должности пользователя
 )
 ; // Implements
 : Attributes
   Seq: ( ME_4E7323D9023E // f_SectionType
 )
 ; // Attributes
 : Operations
   Seq: ( ME_4E73249703A9 // Create
 ME_4E7324A00304 // Make
 )
 ; // Operations
 : Overridden
   Seq: ( ME_4909EF6E0361_ME_4E73239003D0 // MakeRoot
 )
 ; // Overridden
 CONST "author" 'Люлин А.В.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '16.09.2011 14:23'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\MainMenu\smChangeableTree.pas'
 CONST extprop:rc:SelfName 'smChangeableTree'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'smChangeableTree'

ref; // ME_4E73239003D0 TsmChangeableTree

: ME_4A9FB4EE00FE
 CONST UID '4A9FB4EE00FE'
 CONST Name 'MainMenuTrees'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_493FE6FF0361' '493FE6FF0361.pas.ms.script' // MainMenu
 ;
 : Children
   Seq: ( ME_490B0E9A02A2 // TsmTree
 ME_490C2AE8028E // TsmLawNewsTree
 ME_4AFBF77E0200 // TsmNewSchoolReferencesTree
 ME_4E73239003D0 // TsmChangeableTree
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_456EA56002BF' '456EA56002BF.pas.ms.script' // BaseTypes
 WL 'ME_457450470167' '457450470167.pas.ms.script' // DynamicTree
 WL 'ME_4677FBA70343' '4677FBA70343.pas.ms.script' // l3Interfaces
 WL 'ME_467BAB7F021E' '467BAB7F021E.pas.ms.script' // vcmExternalInterfaces
 WL 'ME_4682595B0268' '4682595B0268.pas.ms.script' // l3TreeInterfaces
 WL 'ME_4683F37902CF' '4683F37902CF.pas.ms.script' // vcmInterfaces
 WL 'ME_476BF10A0280' '476BF10A0280.pas.ms.script' // l3Tree_TLB
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_47D0E1500033' '47D0E1500033.pas.ms.script' // Implementation
 WL 'ME_47EA4BB502F9' '47EA4BB502F9.pas.ms.script' // afwMixIns
 WL 'ME_47ECAAF901F8' '47ECAAF901F8.pas.ms.script' // bsInterfaces
 WL 'ME_47F2170002B2' '47F2170002B2.pas.ms.script' // nsTypes
 WL 'ME_48563BA400A9' '48563BA400A9.pas.ms.script' // Навигация
 WL 'ME_48F747EC0073' '48F747EC0073.pas.ms.script' // Common
 WL 'ME_48FD8B2702F6' '48FD8B2702F6.pas.ms.script' // Tree
 WL 'ME_4907236C0171' '4907236C0171.pas.ms.script' // Rubricator
 WL 'ME_4908A8A20107' '4908A8A20107.pas.ms.script' // OldTree
 WL 'ME_4909EECE01D5' '4909EECE01D5.pas.ms.script' // MainMenu
 WL 'ME_4DD24BD40021' '4DD24BD40021.pas.ms.script' // MainMenu
 )
 ; // Depends

ref; // ME_4A9FB4EE00FE MainMenuTrees
