// SendConsultation 4AA53D3A002B VCMFormSetFactory Class

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4AA53D3A002B

FORWARD ME_4AA53D3A002B

FORWARD ME_4FFAE62E0209

FORWARD ME_4FFAE7500345

MEREF ME_492F006F00BE_ME_4FFAE7500345_impl
 MELINK Original WL 'ME_492F006F00BE' '491C3E540050.ms.model.script' // dsQuery
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDMEREF // ME_492F006F00BE_ME_4FFAE7500345_impl dsQuery

MEREF ME_492F00890059_ME_4FFAE7500345_impl
 MELINK Original WL 'ME_492F00890059' '491C3E540050.ms.model.script' // dsSaveLoad
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDMEREF // ME_492F00890059_ME_4FFAE7500345_impl dsSaveLoad

MEREF ME_4BD5C37D030C_ME_4FFAE7500345_G
 MELINK Original WL 'ME_4BD5C37D030C' '497EBA4301CA.ms.model.script' // utqcSendConsultation
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4BD5C37D030C_ME_4FFAE7500345_G utqcSendConsultation

MEREF ME_4BD97FFF0005_ME_4FFAE7500345_G
 MELINK Original WL 'ME_4BD97FFF0005' '4BD97FDB031A.ms.model.script' // QueryCard
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4BD97FFF0005_ME_4FFAE7500345_G QueryCard

MEREF ME_492F005A02C7_ME_4FFAE7500345_R
 MELINK Original WL 'ME_492F005A02C7' '491C3E540050.ms.model.script' // IsdsQuery
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_492F005A02C7_ME_4FFAE7500345_R IsdsQuery

%%ImplementedBy ME_492F005A02C7 ME_4FFAE7500345

%%InheritedBy ME_4BD5C37D030C ME_4FFAE7500345
%%InheritedBy ME_4BD97FFF0005 ME_4FFAE7500345

ME ME_4FFAE7500345
 MEPROP UID '4FFAE7500345'
 MEPROP Name 'QueryCard'
 MEPROP Class class_Class
 MELINK Stereotype st_VCMZone ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4FFAE62E0209 // SaveLoad
 ;
 MELIST Inherits
   Seq: ( ME_4BD5C37D030C_ME_4FFAE7500345_G // utqcSendConsultation
 ME_4BD97FFF0005_ME_4FFAE7500345_G // QueryCard
 )
 ; // Inherits
 MELIST Implements
   Seq: ( ME_492F005A02C7_ME_4FFAE7500345_R // IsdsQuery
 )
 ; // Implements
 MELIST Implemented
   Seq: ( ME_492F006F00BE_ME_4FFAE7500345_impl // dsQuery
 ME_492F00890059_ME_4FFAE7500345_impl // dsSaveLoad
 )
 ; // Implemented
 UP "ActivateIfUpdate" 'None'
 UP "Caption" '''Поиск с правовой поддержкой'''
 UP "Need GetFormCount" false
 UP "Need OnFormWeight" 'undefined'
 UP "ZoneType" 'Parent'

ENDME // ME_4FFAE7500345 QueryCard

MEREF ME_492F006F00BE_ME_4FFAE62E0209_impl
 MELINK Original WL 'ME_492F006F00BE' '491C3E540050.ms.model.script' // dsQuery
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDMEREF // ME_492F006F00BE_ME_4FFAE62E0209_impl dsQuery

MEREF ME_492F00890059_ME_4FFAE62E0209_impl
 MELINK Original WL 'ME_492F00890059' '491C3E540050.ms.model.script' // dsSaveLoad
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDMEREF // ME_492F00890059_ME_4FFAE62E0209_impl dsSaveLoad

MEREF ME_4BD5BC700046_ME_4FFAE62E0209_G
 MELINK Original WL 'ME_4BD5BC700046' '4F5DFE09009E.ms.model.script' // slqtConsult
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4BD5BC700046_ME_4FFAE62E0209_G slqtConsult

MEREF ME_4D77A59D03E6_ME_4FFAE62E0209_G
 MELINK Original WL 'ME_4D77A59D03E6' '4BD97FDB031A.ms.model.script' // SaveLoad
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4D77A59D03E6_ME_4FFAE62E0209_G SaveLoad

MEREF ME_492F005A02C7_ME_4FFAE62E0209_R
 MELINK Original WL 'ME_492F005A02C7' '491C3E540050.ms.model.script' // IsdsQuery
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_492F005A02C7_ME_4FFAE62E0209_R IsdsQuery

%%ImplementedBy ME_492F005A02C7 ME_4FFAE62E0209

%%InheritedBy ME_4BD5BC700046 ME_4FFAE62E0209
%%InheritedBy ME_4D77A59D03E6 ME_4FFAE62E0209

ME ME_4FFAE62E0209
 MEPROP UID '4FFAE62E0209'
 MEPROP Name 'SaveLoad'
 MEPROP Class class_Class
 MELINK Stereotype st_VCMZone ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4AA53D3A002B // SendConsultation
 ;
 MELIST Inherits
   Seq: ( ME_4BD5BC700046_ME_4FFAE62E0209_G // slqtConsult
 ME_4D77A59D03E6_ME_4FFAE62E0209_G // SaveLoad
 )
 ; // Inherits
 MELIST Implements
   Seq: ( ME_492F005A02C7_ME_4FFAE62E0209_R // IsdsQuery
 )
 ; // Implements
 MELIST Implemented
   Seq: ( ME_492F006F00BE_ME_4FFAE62E0209_impl // dsQuery
 ME_492F00890059_ME_4FFAE62E0209_impl // dsSaveLoad
 )
 ; // Implemented
 MELIST Children
   Seq: ( HWL ME_4FFAE7500345 // QueryCard
 )
 ; // Children
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "ActivateIfUpdate" 'None'
 UP "Need GetFormCount" false
 UP "Need OnFormWeight" 'undefined'
 UP "ZoneType" 'Parent'

ENDME // ME_4FFAE62E0209 SaveLoad

FORWARD ME_C649B12203E0

ME ME_4A185158B971
 MEPROP UID '4A185158B971'
 MEPROP Name 'fszQueryCard_Parent_utqcSendConsultationCaption'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY 'Заголовок зоны "QueryCard" фабрики сборки форм "SendConsultation"' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_C649B12203E0 // QueryCardCaptionLocalConstants
 ;
 MEPROP Value '''Поиск с правовой поддержкой'''
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '''Поиск с правовой поддержкой'''

ENDME // ME_4A185158B971 fszQueryCard_Parent_utqcSendConsultationCaption

ME ME_C649B12203E0
 MEPROP UID 'C649B12203E0'
 MEPROP Name 'QueryCardCaptionLocalConstants'
 UP IsSummoned true
 MEPROP Class class_Const
 MELINK Stereotype st_LocalConst ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Локализуемые константы для зоны QueryCard сборки форм SendConsultation' ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4AA53D3A002B // SendConsultation
 ;
 MELIST Attributes
   Seq: ( HWL ME_4A185158B971 // fszQueryCard_Parent_utqcSendConsultationCaption
 )
 ; // Attributes
 UP "Need map interface" false
 UP "Need mapping support" false
 UP "spell names" false

ENDME // ME_C649B12203E0 QueryCardCaptionLocalConstants

FORWARD ME_83A95AFD27A0

ME ME_99948C597286
 MEPROP UID '99948C597286'
 MEPROP Name 'fsSendConsultationCaption'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY 'Заголовок фабрики сборки форм "SendConsultation"' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_83A95AFD27A0 // SendConsultationCaptionLocalConstants
 ;
 MEPROP Value '''Правовая поддержка'''
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '''Правовая поддержка'''

ENDME // ME_99948C597286 fsSendConsultationCaption

ME ME_83A95AFD27A0
 MEPROP UID '83A95AFD27A0'
 MEPROP Name 'SendConsultationCaptionLocalConstants'
 UP IsSummoned true
 MEPROP Class class_Const
 MELINK Stereotype st_LocalConst ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Локализуемые константы для фабрики сборки форм SendConsultation' ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4AA53D3A002B // SendConsultation
 ;
 MELIST Attributes
   Seq: ( HWL ME_99948C597286 // fsSendConsultationCaption
 )
 ; // Attributes
 UP "Need map interface" false
 UP "Need mapping support" false
 UP "spell names" false

ENDME // ME_83A95AFD27A0 SendConsultationCaptionLocalConstants

MEREF ME_50096E800075_ME_CAD3716E6F7B_G
 MELINK Original WL 'ME_50096E800075' '4FFC337003AF.ms.model.script' // TvcmNeedMakeFormEvent
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_50096E800075_ME_CAD3716E6F7B_G TvcmNeedMakeFormEvent

%%InheritedBy ME_50096E800075 ME_CAD3716E6F7B

ME ME_CAD3716E6F7B
 MEPROP UID 'CAD3716E6F7B'
 MEPROP Name 'SaveLoad_Parent_slqtConsult_NeedMakeForm'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Обработчик OnNeedMakeForm для SaveLoad' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4AA53D3A002B // SendConsultation
 ;
 MELIST Inherits
   Seq: ( ME_50096E800075_ME_CAD3716E6F7B_G // TvcmNeedMakeFormEvent
 )
 ; // Inherits
 UPLINK Speller HWL ME_4FFAE62E0209 // SaveLoad
 ;

ENDME // ME_CAD3716E6F7B SaveLoad_Parent_slqtConsult_NeedMakeForm

MEREF ME_50096E800075_ME_0BD7FE614FE1_G
 MELINK Original WL 'ME_50096E800075' '4FFC337003AF.ms.model.script' // TvcmNeedMakeFormEvent
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_50096E800075_ME_0BD7FE614FE1_G TvcmNeedMakeFormEvent

%%InheritedBy ME_50096E800075 ME_0BD7FE614FE1

ME ME_0BD7FE614FE1
 MEPROP UID '0BD7FE614FE1'
 MEPROP Name 'QueryCard_Parent_utqcSendConsultation_NeedMakeForm'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Обработчик OnNeedMakeForm для QueryCard' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4AA53D3A002B // SendConsultation
 ;
 MELIST Inherits
   Seq: ( ME_50096E800075_ME_0BD7FE614FE1_G // TvcmNeedMakeFormEvent
 )
 ; // Inherits
 UPLINK Speller HWL ME_4FFAE7500345 // QueryCard
 ;

ENDME // ME_0BD7FE614FE1 QueryCard_Parent_utqcSendConsultation_NeedMakeForm

ME ME_4FFAE6370055
 MEPROP Class class_Dependency
 MELINK Stereotype st_OwnerForm::Dependency ;
 MELINK Parent HWL ME_4AA53D3A002B // SendConsultation
 ;
 MELINK Target HWL ME_4FFAE62E0209 // SaveLoad
 ;

ENDME // ME_4FFAE6370055 

MEREF ME_47A042E100E2_ME_4AA53D3A002B_over
 MELINK Original WL 'ME_47A042E100E2' '47913F4E02E0.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_47A042E100E2_ME_4AA53D3A002B_over InitFields

MEREF ME_4FFE854A009B_ME_4AA53D3A002B_over
 MELINK Original WL 'ME_4FFE854A009B' '4FFE84F00388.ms.model.script' // GetInstance
 ;
 MEPROP OpKind opkind_Overridden
 UP "is static" true
ENDMEREF // ME_4FFE854A009B_ME_4AA53D3A002B_over GetInstance

MEREF ME_47B97312006D_ME_4AA53D3A002B_G
 MELINK Original WL? 'ME_47B97312006D' // TvcmFormSetFactory
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_47B97312006D_ME_4AA53D3A002B_G TvcmFormSetFactory

%%InheritedBy ME_47B97312006D ME_4AA53D3A002B

ME ME_4AA53D3A002B
 MEPROP UID '4AA53D3A002B'
 MEPROP Name 'SendConsultation'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_VCMFormSetFactory ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL? 'ME_4ABCFB7F017B' // Consultation$FP
 ;
 MELIST Inherits
   Seq: ( ME_47B97312006D_ME_4AA53D3A002B_G // TvcmFormSetFactory
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_CAD3716E6F7B // SaveLoad_Parent_slqtConsult_NeedMakeForm
 HWL ME_0BD7FE614FE1 // QueryCard_Parent_utqcSendConsultation_NeedMakeForm
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_47A042E100E2_ME_4AA53D3A002B_over // InitFields
 ME_4FFE854A009B_ME_4AA53D3A002B_over // GetInstance
 )
 ; // Overridden
 MELIST Children
   Seq: ( HWL ME_4FFAE62E0209 // SaveLoad
 )
 ; // Children
 MELIST Constants
   Seq: ( HWL ME_C649B12203E0 // QueryCardCaptionLocalConstants
 HWL ME_83A95AFD27A0 // SendConsultationCaptionLocalConstants
 )
 ; // Constants
 MELIST Dependencies
   Seq: ( ME_4FFAE6370055 // SaveLoad
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "Caption" 'Правовая поддержка'
 UP "DefaultStatusForm" '-1'
 UP "Need GetMainCaption" false
 UP "Need GetMainImageIndex" false
 UP "finished dfm" true
 UP "singleton" true
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\Consultation\fsSendConsultation.pas'
 UP extprop:pas:TypeName 'Tfs_SendConsultation'
 UP extprop:rc:SelfName 'fs_SendConsultation'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'fsSendConsultation'
 UP extprop:pas:InitFields ' inherited;'#13#10' with AddZone(''SaveLoad'', vcm_ztParent, fm_cfSaveLoad) do'#13#10' begin'#13#10'  UserType := slqtConsult;'#13#10'  with AddZone(''QueryCard'', vcm_ztParent, fm_enQueryCard) do'#13#10'  begin'#13#10'   Caption := str_fszQueryCard_Parent_utqcSendConsultationCaption.AsCStr;'#13#10'   UserType := utqcSendConsultation;'#13#10'   OnNeedMakeForm := QueryCardParentUtqcSendConsultationNeedMakeForm;'#13#10'  end;'#13#10'  OnNeedMakeForm := SaveLoadParentSlqtConsultNeedMakeForm;'#13#10' end;'#13#10' Caption := str_fsSendConsultationCaption.AsCStr;'#13#10' OwnerForm := 0;'

ENDME // ME_4AA53D3A002B SendConsultation
