// View 4AA66B2C02FC VCMViews Category

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_4AA66B2C02FC
 MEPROP UID '4AA66B2C02FC'
 MEPROP Name 'View'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_VCMViews ;
 %SUMMARY 'Представление' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4AA66AFA01B1' '4AA66AFA01B1.ms.model.script' // Rubricator
 ;
 MELIST Children
   Seq: ( WL 'ME_4C4432FA016A' '4C4432FA016A.ms.model.script' // Strange
 WL 'ME_4AA66B460175' '4AA66B460175.ms.model.script' // Rubricator
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_456EA3D2031C' '456EA3D2031C.ms.model.script' // GblAdapterLib
 WL 'ME_4677FF4B0036' '4677FF4B0036.ms.model.script' // Data
 WL 'ME_467A75D90346' '467A75D90346.ms.model.script' // VT
 WL 'ME_467A8734039C' '467A8734039C.ms.model.script' // EVD
 WL 'ME_4680E7D50168' '4680E7D50168.ms.model.script' // Everest Engine
 WL 'ME_4682595B0268' '4682595B0268.ms.model.script' // l3TreeInterfaces
 WL 'ME_4790B4F00236' '4790B4F00236.ms.model.script' // AFW
 WL 'ME_4790C3B8021E' '4790C3B8021E.ms.model.script' // VCM
 WL 'ME_4790D09A0378' '4790D09A0378.ms.model.script' // L3
 WL 'ME_4797632D0273' '4797632D0273.ms.model.script' // Everest
 WL 'ME_4799D29F033F' '4799D29F033F.ms.model.script' // Implementation
 WL 'ME_47E9EEC60260' '47E9EEC60260.ms.model.script' // Model
 WL 'ME_490838AA02D0' '490838AA02D0.ms.model.script' // Nemesis
 WL 'ME_4954C0500033' '4954C0500033.ms.model.script' // UserInteraction
 WL 'ME_4A7C099B004F' '4A7C099B004F.ms.model.script' // View
 WL 'ME_4A92C59801C7' '4A92C59801C7.ms.model.script' // View
 WL 'ME_4AA7A7D903AE' '4AA7A7D903AE.ms.model.script' // Rubricator
 WL 'ME_4AB0997B00A2' '4AB0997B00A2.ms.model.script' // Common
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.ms.model.script' // Sys
 WL 'ME_4ABB680E0218' '4ABB680E0218.ms.model.script' // Common$Lib
 WL 'ME_4C6A65ED0374' '4C6A65ED0374.ms.model.script' // F1DocumentProcessing
 WL 'ME_4E13416D0227' '4E13416D0227.ms.model.script' // VCM$Visual
 WL 'ME_4E1352670215' '4E1352670215.ms.model.script' // Nemesis$Tails
 WL 'ME_4E2F0E1B03BB' '4E2F0E1B03BB.ms.model.script' // L3$Domain
 WL 'ME_4E36644A0023' '4E36644A0023.ms.model.script' // Стандартные компоненты
 WL 'ME_4F4B8F830023' '4F4B8F830023.ms.model.script' // ExternalObjects
 WL 'ME_533D53FF00C2' '533D53FF00C2.ms.model.script' // Visual$ChromeLike
 WL 'ME_53BA5A5D03A0' '53BA5A5D03A0.ms.model.script' // TabInterface
 WL 'ME_54B90AC6014B' '54B90AC6014B.ms.model.script' // StringUtils
 WL 'ME_55C4AEC801CA' '55C4AEC801CA.ms.model.script' // Graphics
 )
 ; // Depends
 UP "exec mode" 'concluded'
 UP "gui" 'prj'
 UP "is namespace" true
 UP "vendor" 'none'
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'

ENDME // ME_4AA66B2C02FC View
