// CommonPost 4AA919DA010C VCMUseCaseRealization Class

INCLUDE 'ElementsRTTI.ms.dict'

: ME_4AA919DA010C
 CONST UID '4AA919DA010C'
 CONST Name 'CommonPost'
 CONST Class class_Class
 : Stereotype st_VCMUseCaseRealization ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Ôàéë' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent WL 'ME_542015B5012C' '542015B5012C.pas.ms.script' // PostingOrder
 ;
 : Inherits
   Seq: ( WL 'ME_4AA919B200AB' '4AA919B200AB.pas.ms.script' // CommonPost
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_484E635201F4' '484E610E0335.pas.ms.script' // ÏÐÀÉÌ
 )
 ; // Implements
 CONST "author" 'Ëþëèí À.Â.'
 CONST "no hands" true
 CONST "started" '15.09.2009 19:19'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\moCommonPost.pas'
 CONST intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'
 CONST extprop:pas:TypeName 'Tmo_CommonPost'
 CONST extprop:rc:SelfName 'mo_CommonPost'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'moCommonPost'

ref; // ME_4AA919DA010C CommonPost
