// CommonSearch$UC 4AA93171022B VCMFormsPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4AA931390118_ME_4AA93171022B_G
 MELINK Original WL? 'ME_4AA931390118' // CommonSearch
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4AA931390118_ME_4AA93171022B_G CommonSearch

%%InheritedBy ME_4AA931390118 ME_4AA93171022B

ME ME_4AA93171022B
 MEPROP UID '4AA93171022B'
 MEPROP Name 'CommonSearch'
 MEPROP OriginalName 'CommonSearch$UC'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_VCMFormsPack ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL? 'ME_4958E382019E' // Search$Presentation for F1 and Monitorings
 ;
 MELIST Inherits
   Seq: ( ME_4AA931390118_ME_4AA93171022B_G // CommonSearch
 )
 ; // Inherits
 UP "author" 'Ëþëèí À.Â.'
 UP "started" '10.09.2009 21:04'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\Search\moCommonSearch.pas'
 UP extprop:pas:TypeName 'Tmo_CommonSearch'
 UP extprop:rc:SelfName 'mo_CommonSearch'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'moCommonSearch'

ENDME // ME_4AA93171022B CommonSearch$UC
