// Components 4AB34028023E Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4AB34028023E

FORWARD ME_4AB34044026A

: ME_52A1FB5C0299
 CONST UID '52A1FB5C0299'
 CONST Name 'RvcmModulesCollection'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34044026A // TvcmModulesCollection
 ;
 : Inherits
   Seq: ( HWL ME_4AB34044026A // TvcmModulesCollection
 )
 ; // Inherits
 CONST "isClassRef" true
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_52A1FB5C0299 RvcmModulesCollection

: ME_4AB34044026A
 CONST UID '4AB34044026A'
 CONST Name 'TvcmModulesCollection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Children
   Seq: ( HWL ME_52A1FB5C0299 // RvcmModulesCollection
 )
 ; // Children
 : Injected
   Seq: ( WL 'ME_5770FF8C03B5' '4E200FED0213.pas.ms.script' // TtfwModuleOperationWordEx
 )
 ; // Injected
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmModulesCollection.pas'
 CONST extprop:rc:SelfName 'ModulesCollection'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmModulesCollection'

ref; // ME_4AB34044026A TvcmModulesCollection

: ME_4AB3405E0326
 CONST UID '4AB3405E0326'
 CONST Name 'TvcmRepEntitiesCollection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmRepEntitiesCollection.pas'
 CONST extprop:rc:SelfName 'RepEntitiesCollection'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmRepEntitiesCollection'

ref; // ME_4AB3405E0326 TvcmRepEntitiesCollection

: ME_4C77C99500F6
 CONST UID '4C77C99500F6'
 CONST Name 'TvcmBaseOperationState'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmBaseOperationState.pas'
 CONST extprop:rc:SelfName 'OperationState'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmBaseOperationState'

ref; // ME_4C77C99500F6 TvcmBaseOperationState

: ME_5620D0B90294
 CONST UID '5620D0B90294'
 CONST Name 'TvcmOperationParams'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( WL 'ME_4FFC3347011F' '4FFC33380166.pas.ms.script' // TvcmBaseCollectionItem
 )
 ; // Inherits
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmOperationParams.pas'
 CONST extprop:rc:SelfName 'OperationParams'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmOperationParams'

ref; // ME_5620D0B90294 TvcmOperationParams

FORWARD ME_55D30E6601A8

FORWARD ME_56116D4D02C6

: ME_56116D5303C0
 CONST UID '56116D5303C0'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_56116D4D02C6 // NeedToBeStored
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_56116D5303C0 DoIt

: ME_56116D4D02C6
 CONST UID '56116D4D02C6'
 CONST Name 'NeedToBeStored'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 : Operations
   Seq: ( HWL ME_56116D5303C0 // DoIt
 )
 ; // Operations

ref; // ME_56116D4D02C6 NeedToBeStored

FORWARD ME_56116D7B0216

: ME_56116D8D02F9
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_56116D8D02F9 aControl

: ME_56116D8D030E
 CONST Name 'aTarget'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A451250363' '4AB0C3C60310.pas.ms.script' // IUnknown
 ;

ref; // ME_56116D8D030E aTarget

: ME_56116D8D0323
 CONST Name 'anOperationID'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683C8750015' '467BAB7F021E.pas.ms.script' // TvcmControlID
 ;

ref; // ME_56116D8D0323 anOperationID

: ME_56116D8D0349
 CONST Name 'aMode'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683F5860071' '499EAAE502A8.pas.ms.script' // TvcmOperationMode
 ;

ref; // ME_56116D8D0349 aMode

: ME_56116D8D038B
 CONST Name 'aParams'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4987048B02EF' '4683F37902CF.pas.ms.script' // IvcmParams
 ;

ref; // ME_56116D8D038B aParams

: ME_56116D810142
 CONST UID '56116D810142'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_56116D7B0216 // Operation
 ;
 : Parameters
   Seq: ( ME_56116D8D02F9 // aControl
 ME_56116D8D030E // aTarget
 ME_56116D8D0323 // anOperationID
 ME_56116D8D0349 // aMode
 ME_56116D8D038B // aParams
 )
 ; // Parameters

ref; // ME_56116D810142 DoIt

: ME_56116D7B0216
 CONST UID '56116D7B0216'
 CONST Name 'Operation'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'выполняет операцию сущности' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 : Operations
   Seq: ( HWL ME_56116D810142 // DoIt
 )
 ; // Operations

ref; // ME_56116D7B0216 Operation

FORWARD ME_56116DA502E0

: ME_56116DAD0147
 CONST Name 'anOperations'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_559D25D60004' '47D0E1500033.pas.ms.script' // TvcmOperationDefList
 ;

ref; // ME_56116DAD0147 anOperations

: ME_56116DAB014C
 CONST UID '56116DAB014C'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_56116DA502E0 // GetOperations
 ;
 : Parameters
   Seq: ( ME_56116DAD0147 // anOperations
 )
 ; // Parameters

ref; // ME_56116DAB014C DoIt

: ME_56116DA502E0
 CONST UID '56116DA502E0'
 CONST Name 'GetOperations'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'возвращает список описателей операций' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 : Operations
   Seq: ( HWL ME_56116DAB014C // DoIt
 )
 ; // Operations

ref; // ME_56116DA502E0 GetOperations

: ME_56116DBA001A
 CONST UID '56116DBA001A'
 CONST Name 'RegisterInRep'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;

ref; // ME_56116DBA001A RegisterInRep

FORWARD ME_56116DD0036F

: ME_56116DE100AE
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_56116DE100AE aControl

: ME_56116DE100C2
 CONST Name 'anOperation'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_56116DE100C2 anOperation

: ME_56116DE100D6
 CONST Name 'anExecute'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476953D2039F' '467BAB7F021E.pas.ms.script' // TvcmControlExecuteEvent
 ;

ref; // ME_56116DE100D6 anExecute

: ME_56116DE100EA
 CONST Name 'aTest'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47694CD40080' '467BAB7F021E.pas.ms.script' // TvcmControlTestEvent
 ;

ref; // ME_56116DE100EA aTest

: ME_56116DE10108
 CONST Name 'aGetState'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49886B8400D0' '467BAB7F021E.pas.ms.script' // TvcmControlGetStateEvent
 ;

ref; // ME_56116DE10108 aGetState

: ME_56116DD60284
 CONST UID '56116DD60284'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_56116DD0036F // PublishOp
 ;
 : Parameters
   Seq: ( ME_56116DE100AE // aControl
 ME_56116DE100C2 // anOperation
 ME_56116DE100D6 // anExecute
 ME_56116DE100EA // aTest
 ME_56116DE10108 // aGetState
 )
 ; // Parameters

ref; // ME_56116DD60284 DoIt

: ME_56116DD0036F
 CONST UID '56116DD0036F'
 CONST Name 'PublishOp'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'опубликовать операцию' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 : Operations
   Seq: ( HWL ME_56116DD60284 // DoIt
 )
 ; // Operations

ref; // ME_56116DD0036F PublishOp

FORWARD ME_56116E0A026F

: ME_56116E19028C
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_56116E19028C aControl

: ME_56116E1902A0
 CONST Name 'anOperation'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_56116E1902A0 anOperation

: ME_56116E1902B5
 CONST Name 'anExecute'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_52A1D97A009E' '47D0E1500033.pas.ms.script' // TvcmExecuteEvent
 ;

ref; // ME_56116E1902B5 anExecute

: ME_56116E1902C9
 CONST Name 'aTest'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47694CD40080' '467BAB7F021E.pas.ms.script' // TvcmControlTestEvent
 ;

ref; // ME_56116E1902C9 aTest

: ME_56116E1902DE
 CONST Name 'aGetState'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49886B8400D0' '467BAB7F021E.pas.ms.script' // TvcmControlGetStateEvent
 ;

ref; // ME_56116E1902DE aGetState

: ME_56116E100319
 CONST UID '56116E100319'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_56116E0A026F // PublishOpWithResult
 ;
 : Parameters
   Seq: ( ME_56116E19028C // aControl
 ME_56116E1902A0 // anOperation
 ME_56116E1902B5 // anExecute
 ME_56116E1902C9 // aTest
 ME_56116E1902DE // aGetState
 )
 ; // Parameters

ref; // ME_56116E100319 DoIt

: ME_56116E0A026F
 CONST UID '56116E0A026F'
 CONST Name 'PublishOpWithResult'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'опубликовать операцию' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 : Operations
   Seq: ( HWL ME_56116E100319 // DoIt
 )
 ; // Operations

ref; // ME_56116E0A026F PublishOpWithResult

FORWARD ME_56116E2E0246

: ME_56116DFC00FA
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_56116DFC00FA aControl

: ME_56116E350052
 CONST UID '56116E350052'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_56116E2E0246 // UnlinkControl
 ;
 : Parameters
   Seq: ( ME_56116DFC00FA // aControl
 )
 ; // Parameters

ref; // ME_56116E350052 DoIt

: ME_56116E2E0246
 CONST UID '56116E2E0246'
 CONST Name 'UnlinkControl'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'отвязать контрол' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 : Operations
   Seq: ( HWL ME_56116E350052 // DoIt
 )
 ; // Operations

ref; // ME_56116E2E0246 UnlinkControl

: ME_56116EB201D8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 : Target WL 'ME_4767748503B5' '4767743E00E5.pas.ms.script' // TTypeInfo
 ;

ref; // ME_56116EB201D8 

: ME_56116EBC00CA
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_56116EBC00CA 

FORWARD ME_4D7A109601C2

: ME_56116ECE020F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 : Target HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;

ref; // ME_56116ECE020F 

FORWARD ME_5603F60C018E

: ME_56116EF001B4
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 : Target HWL ME_5603F60C018E // TvcmOperationsCollectionItem
 ;

ref; // ME_56116EF001B4 

: ME_56116F5A01EF
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 : Target WL 'ME_4AB33E14004E' '47D0E1500033.pas.ms.script' // TvcmModule
 ;

ref; // ME_56116F5A01EF 

: ME_5611807D017B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 : Target WL 'ME_47E7ABAE0110' '4799D29F033F.pas.ms.script' // Menus
 ;

ref; // ME_5611807D017B 

: ME_5607EE71032D_ME_55D30E6601A8
 : Original WL 'ME_5607EE71032D' '4FFC33380166.pas.ms.script' // GetItemClass
 ;
 CONST OpKind opkind_Overridden
 CONST "is static" true
ref; // ME_5607EE71032D_ME_55D30E6601A8 GetItemClass

: ME_560A9DA80335_ME_55D30E6601A8
 : Original WL 'ME_560A9DA80335' '4AB0997B00A2.pas.ms.script' // GetAttrCount
 ;
 CONST OpKind opkind_Overridden
ref; // ME_560A9DA80335_ME_55D30E6601A8 GetAttrCount

: ME_560A9DCD009D_ME_55D30E6601A8
 : Original WL 'ME_560A9DCD009D' '4AB0997B00A2.pas.ms.script' // GetAttr
 ;
 CONST OpKind opkind_Overridden
ref; // ME_560A9DCD009D_ME_55D30E6601A8 GetAttr

: ME_560A9DEB0155_ME_55D30E6601A8
 : Original WL 'ME_560A9DEB0155' '4AB0997B00A2.pas.ms.script' // GetItemAttr
 ;
 CONST OpKind opkind_Overridden
ref; // ME_560A9DEB0155_ME_55D30E6601A8 GetItemAttr

: ME_55D30E6601A8
 CONST UID '55D30E6601A8'
 CONST Name 'TvcmBaseOperationsCollection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Коллекция операций' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( WL 'ME_4FFC4C800030' '4FFC33380166.pas.ms.script' // TvcmBaseCollection
 )
 ; // Inherits
 : Operations
   Seq: ( HWL ME_56116D4D02C6 // NeedToBeStored
 HWL ME_56116D7B0216 // Operation
 HWL ME_56116DA502E0 // GetOperations
 HWL ME_56116DBA001A // RegisterInRep
 HWL ME_56116DD0036F // PublishOp
 HWL ME_56116E0A026F // PublishOpWithResult
 HWL ME_56116E2E0246 // UnlinkControl
 )
 ; // Operations
 : Overridden
   Seq: ( ME_5607EE71032D_ME_55D30E6601A8 // GetItemClass
 ME_560A9DA80335_ME_55D30E6601A8 // GetAttrCount
 ME_560A9DCD009D_ME_55D30E6601A8 // GetAttr
 ME_560A9DEB0155_ME_55D30E6601A8 // GetItemAttr
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_56116EB201D8 // TTypeInfo
 ME_56116EBC00CA // SysUtils
 ME_56116ECE020F // TvcmBaseOperationsCollectionItem
 ME_56116EF001B4 // TvcmOperationsCollectionItem
 ME_56116F5A01EF // TvcmModule
 ME_5611807D017B // Menus
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\vcmBaseOperationsCollection.pas'
 CONST extprop:rc:SelfName 'OperationsCollection'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmBaseOperationsCollection'

ref; // ME_55D30E6601A8 TvcmBaseOperationsCollection

: ME_4E01E6DF003A
 CONST UID '4E01E6DF003A'
 CONST Name 'TvcmMessagesCollectionItem'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmMessagesCollectionItem.pas'
 CONST extprop:rc:SelfName 'MessagesCollectionItem'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmMessagesCollectionItem'

ref; // ME_4E01E6DF003A TvcmMessagesCollectionItem

FORWARD ME_5620D2420197

: ME_5621097F0137
 CONST UID '5621097F0137'
 CONST Name 'RvcmBaseOperationStates'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5620D2420197 // TvcmBaseOperationStates
 ;
 : Inherits
   Seq: ( HWL ME_5620D2420197 // TvcmBaseOperationStates
 )
 ; // Inherits
 CONST "isClassRef" true
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5621097F0137 RvcmBaseOperationStates

: ME_5620D2420197
 CONST UID '5620D2420197'
 CONST Name 'TvcmBaseOperationStates'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Children
   Seq: ( HWL ME_5621097F0137 // RvcmBaseOperationStates
 )
 ; // Children
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmBaseOperationStates.pas'
 CONST extprop:rc:SelfName 'OperationStates'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmBaseOperationStates'

ref; // ME_5620D2420197 TvcmBaseOperationStates

FORWARD ME_51D128930090

: ME_51D12A260102
 CONST UID '51D12A260102'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_51D128930090 // TvcmEntitiesDefIteratorForContextMenu
 ;
 : Target WL 'ME_49956D4A00C6' '4683F37902CF.pas.ms.script' // IvcmEntityDef
 ;

ref; // ME_51D12A260102 ItemType

: ME_51D12A3D034C
 CONST UID '51D12A3D034C'
 CONST Name 'f_Iter'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent HWL ME_51D128930090 // TvcmEntitiesDefIteratorForContextMenu
 ;
 : Target WL 'ME_49956DA70152' '4683F37902CF.pas.ms.script' // IvcmEntitiesDefIterator
 ;

ref; // ME_51D12A3D034C f_Iter

: ME_51D12AEE023B
 CONST UID '51D12AEE023B'
 CONST Name 'f_Index'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_51D128930090 // TvcmEntitiesDefIteratorForContextMenu
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_51D12AEE023B f_Index

FORWARD ME_51D12A5F02EE

: ME_51D12A73021A
 CONST Name 'anIter'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49956DA70152' '4683F37902CF.pas.ms.script' // IvcmEntitiesDefIterator
 ;

ref; // ME_51D12A73021A anIter

: ME_51D12A6B00E4
 CONST UID '51D12A6B00E4'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_51D12A5F02EE // Create
 ;
 : Parameters
   Seq: ( ME_51D12A73021A // anIter
 )
 ; // Parameters

ref; // ME_51D12A6B00E4 DoIt

: ME_51D12A5F02EE
 CONST UID '51D12A5F02EE'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_51D128930090 // TvcmEntitiesDefIteratorForContextMenu
 ;
 : Operations
   Seq: ( HWL ME_51D12A6B00E4 // DoIt
 )
 ; // Operations

ref; // ME_51D12A5F02EE Create

: ME_51D12A7C0049
 CONST UID '51D12A7C0049'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_51D128930090 // TvcmEntitiesDefIteratorForContextMenu
 ;
 : Inherits
   Seq: ( HWL ME_51D12A5F02EE // Create
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_49956DA70152' '4683F37902CF.pas.ms.script' // IvcmEntitiesDefIterator
 )
 ; // Implements
 CONST "check nil" true

ref; // ME_51D12A7C0049 Make

FORWARD ME_51D148890323

: ME_51D1489F01EB
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_51D128930090 // TvcmEntitiesDefIteratorForContextMenu
 ;
 : Target HWL ME_51D148890323 // TvcmEntityDefForContextMenu
 ;

ref; // ME_51D1489F01EB 

: ME_47B07CF403D0_ME_51D128930090
 : Original WL 'ME_47B07CF403D0' '47913B47006E.pas.ms.script' // IsSameItems
 ;
 CONST OpKind opkind_Implemented
 CONST "ifndef" 'l3Items_IsAtomic'
ref; // ME_47B07CF403D0_ME_51D128930090 IsSameItems

: ME_47B2C42A0163_ME_51D128930090
 : Original WL 'ME_47B2C42A0163' '47913B47006E.pas.ms.script' // AssignItem
 ;
 CONST OpKind opkind_Implemented
 CONST "ifdef" 'l3Items_NeedsAssignItem'
 CONST "ifndef" 'l3Items_NoSort'
ref; // ME_47B2C42A0163_ME_51D128930090 AssignItem

: ME_47B99D4503A2_ME_51D128930090
 : Original WL 'ME_47B99D4503A2' '47BB24D30205.pas.ms.script' // CompareExistingItems
 ;
 CONST OpKind opkind_Implemented
ref; // ME_47B99D4503A2_ME_51D128930090 CompareExistingItems

: ME_49956DB300D6_ME_51D128930090
 : Original WL 'ME_49956DB300D6' '4683F37902CF.pas.ms.script' // Next
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_49956DB300D6_ME_51D128930090 Next

: ME_51D128930090
 CONST UID '51D128930090'
 CONST Name 'TvcmEntitiesDefIteratorForContextMenu'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( WL 'ME_47B9AF6E0228' '47913B47006E.pas.ms.script' // l3InterfaceRefListPrim
 WL 'ME_4A54DD4E036F' '47913B47006E.pas.ms.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_49956DA70152' '4683F37902CF.pas.ms.script' // IvcmEntitiesDefIterator
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_51D12A260102 // ItemType
 HWL ME_51D12A3D034C // f_Iter
 HWL ME_51D12AEE023B // f_Index
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_51D12A5F02EE // Create
 HWL ME_51D12A7C0049 // Make
 )
 ; // Operations
 : Implemented
   Seq: ( ME_47B07CF403D0_ME_51D128930090 // IsSameItems
 ME_47B2C42A0163_ME_51D128930090 // AssignItem
 ME_47B99D4503A2_ME_51D128930090 // CompareExistingItems
 ME_49956DB300D6_ME_51D128930090 // Next
 )
 ; // Implemented
 : Dependencies
   Seq: ( ME_51D1489F01EB // TvcmEntityDefForContextMenu
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\vcmEntitiesDefIteratorForContextMenu.pas'
 CONST extprop:rc:SelfName 'EntitiesDefIteratorForContextMenu'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmEntitiesDefIteratorForContextMenu'

ref; // ME_51D128930090 TvcmEntitiesDefIteratorForContextMenu

: ME_51D148AA0323
 CONST UID '51D148AA0323'
 CONST Name 'f_En'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent HWL ME_51D148890323 // TvcmEntityDefForContextMenu
 ;
 : Target WL 'ME_49956D4A00C6' '4683F37902CF.pas.ms.script' // IvcmEntityDef
 ;

ref; // ME_51D148AA0323 f_En

FORWARD ME_51D148D100C2

: ME_51D148E3011A
 CONST Name 'anEn'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49956D4A00C6' '4683F37902CF.pas.ms.script' // IvcmEntityDef
 ;

ref; // ME_51D148E3011A anEn

: ME_51D148DA01EF
 CONST UID '51D148DA01EF'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_51D148D100C2 // Create
 ;
 : Parameters
   Seq: ( ME_51D148E3011A // anEn
 )
 ; // Parameters

ref; // ME_51D148DA01EF DoIt

: ME_51D148D100C2
 CONST UID '51D148D100C2'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_51D148890323 // TvcmEntityDefForContextMenu
 ;
 : Operations
   Seq: ( HWL ME_51D148DA01EF // DoIt
 )
 ; // Operations

ref; // ME_51D148D100C2 Create

: ME_51D148E7019F
 CONST UID '51D148E7019F'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_51D148890323 // TvcmEntityDefForContextMenu
 ;
 : Inherits
   Seq: ( HWL ME_51D148D100C2 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_49956D4A00C6' '4683F37902CF.pas.ms.script' // IvcmEntityDef
 )
 ; // Implements

ref; // ME_51D148E7019F Make

FORWARD ME_51D14918034E

: ME_51D1492D02B3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_51D148890323 // TvcmEntityDefForContextMenu
 ;
 : Target HWL ME_51D14918034E // TvcmOperationsDefIteratorForContextMenu
 ;

ref; // ME_51D1492D02B3 

: ME_4995616701BB_ME_51D148890323
 : Original WL 'ME_4995616701BB' '499EAAE502A8.pas.ms.script' // Hint
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4995616701BB_ME_51D148890323 Hint

: ME_4995617802E8_ME_51D148890323
 : Original WL 'ME_4995617802E8' '499EAAE502A8.pas.ms.script' // LongHint
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4995617802E8_ME_51D148890323 LongHint

: ME_499561850334_ME_51D148890323
 : Original WL 'ME_499561850334' '499EAAE502A8.pas.ms.script' // ImageIndex
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499561850334_ME_51D148890323 ImageIndex

: ME_499561F90285_ME_51D148890323
 : Original WL 'ME_499561F90285' '499EAAE502A8.pas.ms.script' // ID
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499561F90285_ME_51D148890323 ID

: ME_499566FA0159_ME_51D148890323
 : Original WL 'ME_499566FA0159' '499EAAE502A8.pas.ms.script' // OperationsDefIterator
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499566FA0159_ME_51D148890323 OperationsDefIterator

: ME_4995671E031A_ME_51D148890323
 : Original WL 'ME_4995671E031A' '499EAAE502A8.pas.ms.script' // ToolbarPos
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4995671E031A_ME_51D148890323 ToolbarPos

: ME_49956D95016A_ME_51D148890323
 : Original WL 'ME_49956D95016A' '4683F37902CF.pas.ms.script' // Options
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_49956D95016A_ME_51D148890323 Options

: ME_499E958E03B0_ME_51D148890323
 : Original WL 'ME_499E958E03B0' '499EAAE502A8.pas.ms.script' // Caption
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499E958E03B0_ME_51D148890323 Caption

: ME_499E95A60064_ME_51D148890323
 : Original WL 'ME_499E95A60064' '499EAAE502A8.pas.ms.script' // Name
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_499E95A60064_ME_51D148890323 Name

: ME_51D12DBB014B_ME_51D148890323
 : Original WL 'ME_51D12DBB014B' '4683F37902CF.pas.ms.script' // ContextMenuWeight
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_51D12DBB014B_ME_51D148890323 ContextMenuWeight

: ME_51D148890323
 CONST UID '51D148890323'
 CONST Name 'TvcmEntityDefForContextMenu'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( WL 'ME_4AE5CA2D0034' '47913B47006E.pas.ms.script' // Tl3CProtoObject
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_49956D4A00C6' '4683F37902CF.pas.ms.script' // IvcmEntityDef
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_51D148AA0323 // f_En
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_51D148D100C2 // Create
 HWL ME_51D148E7019F // Make
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4995616701BB_ME_51D148890323 // Hint
 ME_4995617802E8_ME_51D148890323 // LongHint
 ME_499561850334_ME_51D148890323 // ImageIndex
 ME_499561F90285_ME_51D148890323 // ID
 ME_499566FA0159_ME_51D148890323 // OperationsDefIterator
 ME_4995671E031A_ME_51D148890323 // ToolbarPos
 ME_49956D95016A_ME_51D148890323 // Options
 ME_499E958E03B0_ME_51D148890323 // Caption
 ME_499E95A60064_ME_51D148890323 // Name
 ME_51D12DBB014B_ME_51D148890323 // ContextMenuWeight
 )
 ; // Implemented
 : Dependencies
   Seq: ( ME_51D1492D02B3 // TvcmOperationsDefIteratorForContextMenu
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\vcmEntityDefForContextMenu.pas'
 CONST extprop:rc:SelfName 'EntityDefForContextMenu'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmEntityDefForContextMenu'

ref; // ME_51D148890323 TvcmEntityDefForContextMenu

: ME_51D14988013B
 CONST UID '51D14988013B'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_51D14918034E // TvcmOperationsDefIteratorForContextMenu
 ;
 : Target WL 'ME_4995624100A6' '499EAAE502A8.pas.ms.script' // IvcmOperationDef
 ;

ref; // ME_51D14988013B ItemType

: ME_51D149AA03A4
 CONST UID '51D149AA03A4'
 CONST Name 'f_Iter'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent HWL ME_51D14918034E // TvcmOperationsDefIteratorForContextMenu
 ;
 : Target WL 'ME_4995644E03A9' '499EAAE502A8.pas.ms.script' // IvcmOperationsDefIterator
 ;

ref; // ME_51D149AA03A4 f_Iter

: ME_51D149F40273
 CONST UID '51D149F40273'
 CONST Name 'f_Index'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_51D14918034E // TvcmOperationsDefIteratorForContextMenu
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_51D149F40273 f_Index

FORWARD ME_51D149B9038D

: ME_51D149C70193
 CONST Name 'anIter'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4995644E03A9' '499EAAE502A8.pas.ms.script' // IvcmOperationsDefIterator
 ;

ref; // ME_51D149C70193 anIter

: ME_51D149C10000
 CONST UID '51D149C10000'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_51D149B9038D // Create
 ;
 : Parameters
   Seq: ( ME_51D149C70193 // anIter
 )
 ; // Parameters

ref; // ME_51D149C10000 DoIt

: ME_51D149B9038D
 CONST UID '51D149B9038D'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_51D14918034E // TvcmOperationsDefIteratorForContextMenu
 ;
 : Operations
   Seq: ( HWL ME_51D149C10000 // DoIt
 )
 ; // Operations

ref; // ME_51D149B9038D Create

: ME_51D149CE0372
 CONST UID '51D149CE0372'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_51D14918034E // TvcmOperationsDefIteratorForContextMenu
 ;
 : Inherits
   Seq: ( HWL ME_51D149B9038D // Create
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4995644E03A9' '499EAAE502A8.pas.ms.script' // IvcmOperationsDefIterator
 )
 ; // Implements
 CONST "check nil" true

ref; // ME_51D149CE0372 Make

: ME_47B07CF403D0_ME_51D14918034E
 : Original WL 'ME_47B07CF403D0' '47913B47006E.pas.ms.script' // IsSameItems
 ;
 CONST OpKind opkind_Implemented
 CONST "ifndef" 'l3Items_IsAtomic'
ref; // ME_47B07CF403D0_ME_51D14918034E IsSameItems

: ME_47B2C42A0163_ME_51D14918034E
 : Original WL 'ME_47B2C42A0163' '47913B47006E.pas.ms.script' // AssignItem
 ;
 CONST OpKind opkind_Implemented
 CONST "ifdef" 'l3Items_NeedsAssignItem'
 CONST "ifndef" 'l3Items_NoSort'
ref; // ME_47B2C42A0163_ME_51D14918034E AssignItem

: ME_47B99D4503A2_ME_51D14918034E
 : Original WL 'ME_47B99D4503A2' '47BB24D30205.pas.ms.script' // CompareExistingItems
 ;
 CONST OpKind opkind_Implemented
ref; // ME_47B99D4503A2_ME_51D14918034E CompareExistingItems

: ME_4995645B02C7_ME_51D14918034E
 : Original WL 'ME_4995645B02C7' '499EAAE502A8.pas.ms.script' // Next
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4995645B02C7_ME_51D14918034E Next

: ME_51D14918034E
 CONST UID '51D14918034E'
 CONST Name 'TvcmOperationsDefIteratorForContextMenu'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( WL 'ME_47B9AF6E0228' '47913B47006E.pas.ms.script' // l3InterfaceRefListPrim
 WL 'ME_4A54DD4E036F' '47913B47006E.pas.ms.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4995644E03A9' '499EAAE502A8.pas.ms.script' // IvcmOperationsDefIterator
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_51D14988013B // ItemType
 HWL ME_51D149AA03A4 // f_Iter
 HWL ME_51D149F40273 // f_Index
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_51D149B9038D // Create
 HWL ME_51D149CE0372 // Make
 )
 ; // Operations
 : Implemented
   Seq: ( ME_47B07CF403D0_ME_51D14918034E // IsSameItems
 ME_47B2C42A0163_ME_51D14918034E // AssignItem
 ME_47B99D4503A2_ME_51D14918034E // CompareExistingItems
 ME_4995645B02C7_ME_51D14918034E // Next
 )
 ; // Implemented
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\vcmOperationsDefIteratorForContextMenu.pas'
 CONST extprop:rc:SelfName 'OperationsDefIteratorForContextMenu'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmOperationsDefIteratorForContextMenu'

ref; // ME_51D14918034E TvcmOperationsDefIteratorForContextMenu

: ME_52A08E6701A1
 CONST UID '52A08E6701A1'
 CONST Name 'TvcmModulesCollectionItem'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmModulesCollectionItem.pas'
 CONST extprop:rc:SelfName 'ModulesCollectionItem'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmModulesCollectionItem'

ref; // ME_52A08E6701A1 TvcmModulesCollectionItem

: ME_52A1EA6801B0
 CONST UID '52A1EA6801B0'
 CONST Name 'TvcmComponent'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( WL 'ME_47541E17024E' '47913B47006E.pas.ms.script' // Tl3InterfacedComponent
 )
 ; // Inherits
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmComponent.pas'
 CONST extprop:rc:SelfName 'Component'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmComponent'

ref; // ME_52A1EA6801B0 TvcmComponent

: ME_55D30F7D02AA
 CONST UID '55D30F7D02AA'
 CONST Name 'TvcmTargetedControlsCollection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmTargetedControlsCollection.pas'
 CONST extprop:rc:SelfName 'TargetedControlsCollection'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmTargetedControlsCollection'

ref; // ME_55D30F7D02AA TvcmTargetedControlsCollection

: ME_52A1F31601D0
 CONST UID '52A1F31601D0'
 CONST Name 'TvcmStringCollection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmStringCollection.pas'
 CONST extprop:rc:SelfName 'StringCollection'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmStringCollection'

ref; // ME_52A1F31601D0 TvcmStringCollection

: ME_52A1F6C102E8
 CONST UID '52A1F6C102E8'
 CONST Name 'TvcmFormsCollection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmFormsCollection.pas'
 CONST extprop:rc:SelfName 'FormsCollection'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmFormsCollection'

ref; // ME_52A1F6C102E8 TvcmFormsCollection

: ME_52A1F7AE03B2
 CONST UID '52A1F7AE03B2'
 CONST Name 'TvcmMessagesCollection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmMessagesCollection.pas'
 CONST extprop:rc:SelfName 'MessagesCollection'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmMessagesCollection'

ref; // ME_52A1F7AE03B2 TvcmMessagesCollection

: ME_52A5714300FB
 CONST UID '52A5714300FB'
 CONST Name 'TvcmRepEntitiesCollectionItem'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmRepEntitiesCollectionItem.pas'
 CONST extprop:rc:SelfName 'RepEntitiesCollectionItem'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmRepEntitiesCollectionItem'

ref; // ME_52A5714300FB TvcmRepEntitiesCollectionItem

FORWARD ME_4DDBBD1103C3

FORWARD ME_55D30CC30066

: ME_55D30CE300DE
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_55D30CE300DE aControl

: ME_55D30CE300F2
 CONST Name 'aX'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_55D30CE300F2 aX

: ME_55D30CE30106
 CONST Name 'aY'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_55D30CE30106 aY

: ME_55D30CE30124
 CONST Name 'theTarget'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_46A451250363' '4AB0C3C60310.pas.ms.script' // IUnknown
 ;

ref; // ME_55D30CE30124 theTarget

: ME_55D30CDA0108
 CONST UID '55D30CDA0108'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30CC30066 // TvcmGetTargetEvent
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_55D30CE300DE // aControl
 ME_55D30CE300F2 // aX
 ME_55D30CE30106 // aY
 ME_55D30CE30124 // theTarget
 )
 ; // Parameters

ref; // ME_55D30CDA0108 DoIt

: ME_55D30CC30066
 CONST UID '55D30CC30066'
 CONST Name 'TvcmGetTargetEvent'
 CONST Class class_Class
 : Stereotype st_Function ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4DDBBD1103C3 // TvcmBaseEntitiesCollectionItem
 ;
 : Operations
   Seq: ( HWL ME_55D30CDA0108 // DoIt
 )
 ; // Operations
 CONST "of object" true

ref; // ME_55D30CC30066 TvcmGetTargetEvent

FORWARD ME_55D30D410267

: ME_55D30E8A0376
 CONST UID '55D30E8A0376'
 CONST Name 'Operations'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Target HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 ;
 CONST "needs stored directive" true
 CONST "pm" true
 CONST "reads field" true

ref; // ME_55D30E8A0376 Operations

: ME_55D30F1A0385
 CONST UID '55D30F1A0385'
 CONST Name 'ToolbarPos'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Target WL 'ME_4992F80B015F' '499EAAE502A8.pas.ms.script' // TvcmToolBarPos
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_55D30F1A0385 ToolbarPos

: ME_55D30FB2030A
 CONST UID '55D30FB2030A'
 CONST Name 'Controls'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Target HWL ME_55D30F7D02AA // TvcmTargetedControlsCollection
 ;
 CONST "needs stored directive" true
 CONST "pm" true
 CONST "reads field" true

ref; // ME_55D30FB2030A Controls

: ME_55D30FF20196
 CONST UID '55D30FF20196'
 CONST Name 'OnGetTarget'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Target HWL ME_55D30CC30066 // TvcmGetTargetEvent
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_55D30FF20196 OnGetTarget

: ME_55D3104B0336
 CONST UID '55D3104B0336'
 CONST Name 'EntityDef'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Target WL 'ME_49956D4A00C6' '4683F37902CF.pas.ms.script' // IvcmEntityDef
 ;
 CONST "needs field" true
 CONST "pm" true

ref; // ME_55D3104B0336 EntityDef

: ME_55D310AA0170
 CONST UID '55D310AA0170'
 CONST Name 'Options'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Target WL 'ME_4992FA3601A9' '4683F37902CF.pas.ms.script' // TvcmEntityOperationsOptions
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_55D310AA0170 Options

: ME_55D3115100B3
 CONST UID '55D3115100B3'
 CONST Name 'ContextMenuWeight'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_55D3115100B3 ContextMenuWeight

: ME_55D3116F02D5
 CONST UID '55D3116F02D5'
 CONST Name 'EntityID'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_55D3116F02D5 EntityID

FORWARD ME_55D3127F038A

: ME_55D3128601A0
 CONST UID '55D3128601A0'
 CONST Name 'aControl'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_55D3127F038A // SupportedBy
 ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_55D3128601A0 aControl

: ME_55D3127F038A
 CONST UID '55D3127F038A'
 CONST Name 'SupportedBy'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Attributes
   Seq: ( HWL ME_55D3128601A0 // aControl
 )
 ; // Attributes
 CONST "pm" true

ref; // ME_55D3127F038A SupportedBy

FORWARD ME_55D30ECE00AD

: ME_55D30ED800C4
 CONST UID '55D30ED800C4'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30ECE00AD // GetOperationsStored
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_55D30ED800C4 DoIt

: ME_55D30ECE00AD
 CONST UID '55D30ECE00AD'
 CONST Name 'GetOperationsStored'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D30ED800C4 // DoIt
 )
 ; // Operations

ref; // ME_55D30ECE00AD GetOperationsStored

FORWARD ME_55D3156703C9

: ME_55D315700344
 CONST UID '55D315700344'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D3156703C9 // IDRep
 ;
 : Target WL 'ME_55D3259B0376' '47D0E1500033.pas.ms.script' // TvcmRep
 ;

ref; // ME_55D315700344 DoIt

: ME_55D3156703C9
 CONST UID '55D3156703C9'
 CONST Name 'IDRep'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D315700344 // DoIt
 )
 ; // Operations

ref; // ME_55D3156703C9 IDRep

FORWARD ME_55D3158D0030

: ME_55D31598027C
 CONST UID '55D31598027C'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D3158D0030 // GetOperationsCollectionClass
 ;
 : Target WL 'ME_52A1ED79003E' '4FFC33380166.pas.ms.script' // RvcmBaseCollection
 ;

ref; // ME_55D31598027C DoIt

: ME_55D3158D0030
 CONST UID '55D3158D0030'
 CONST Name 'GetOperationsCollectionClass'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D31598027C // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_55D3158D0030 GetOperationsCollectionClass

FORWARD ME_55D315AF00FF

: ME_55D315C40005
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_55D315C40005 aControl

: ME_55D315C40023
 CONST Name 'aX'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_55D315C40023 aX

: ME_55D315C40041
 CONST Name 'aY'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_55D315C40041 aY

: ME_55D315BD0023
 CONST UID '55D315BD0023'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D315AF00FF // GetEntityForControl
 ;
 : Target WL 'ME_4991AD08005B' '4683F37902CF.pas.ms.script' // IvcmEntity
 ;
 : Parameters
   Seq: ( ME_55D315C40005 // aControl
 ME_55D315C40023 // aX
 ME_55D315C40041 // aY
 )
 ; // Parameters

ref; // ME_55D315BD0023 DoIt

: ME_55D315AF00FF
 CONST UID '55D315AF00FF'
 CONST Name 'GetEntityForControl'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D315BD0023 // DoIt
 )
 ; // Operations

ref; // ME_55D315AF00FF GetEntityForControl

FORWARD ME_55D315DD021A

: ME_55D315EF0018
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_55D315EF0018 aControl

: ME_55D315EF0036
 CONST Name 'aTarget'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A451250363' '4AB0C3C60310.pas.ms.script' // IUnknown
 ;

ref; // ME_55D315EF0036 aTarget

: ME_55D315EF004A
 CONST Name 'anOperationID'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683C8750015' '467BAB7F021E.pas.ms.script' // TvcmControlID
 ;

ref; // ME_55D315EF004A anOperationID

: ME_55D315EF0068
 CONST Name 'aMode'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683F5860071' '499EAAE502A8.pas.ms.script' // TvcmOperationMode
 ;

ref; // ME_55D315EF0068 aMode

: ME_55D315EF009A
 CONST Name 'aParams'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4987048B02EF' '4683F37902CF.pas.ms.script' // IvcmParams
 ;

ref; // ME_55D315EF009A aParams

: ME_55D315E300DA
 CONST UID '55D315E300DA'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D315DD021A // Operation
 ;
 : Parameters
   Seq: ( ME_55D315EF0018 // aControl
 ME_55D315EF0036 // aTarget
 ME_55D315EF004A // anOperationID
 ME_55D315EF0068 // aMode
 ME_55D315EF009A // aParams
 )
 ; // Parameters

ref; // ME_55D315E300DA DoIt

: ME_55D315DD021A
 CONST UID '55D315DD021A'
 CONST Name 'Operation'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D315E300DA // DoIt
 )
 ; // Operations

ref; // ME_55D315DD021A Operation

FORWARD ME_55D3160A0358

: ME_55D316110180
 CONST UID '55D316110180'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D3160A0358 // IsFormItem
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_55D316110180 DoIt

: ME_55D3160A0358
 CONST UID '55D3160A0358'
 CONST Name 'IsFormItem'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D316110180 // DoIt
 )
 ; // Operations

ref; // ME_55D3160A0358 IsFormItem

FORWARD ME_55D3166700B9

: ME_55D316710223
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_55D316710223 aControl

: ME_55D3166E02A5
 CONST UID '55D3166E02A5'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D3166700B9 // SupportedExBy
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Parameters
   Seq: ( ME_55D316710223 // aControl
 )
 ; // Parameters

ref; // ME_55D3166E02A5 DoIt

: ME_55D3166700B9
 CONST UID '55D3166700B9'
 CONST Name 'SupportedExBy'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D3166E02A5 // DoIt
 )
 ; // Operations

ref; // ME_55D3166700B9 SupportedExBy

FORWARD ME_55D31692032D

: ME_55D3169C00AD
 CONST UID '55D3169C00AD'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D31692032D // HasInternalOperations
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_55D3169C00AD DoIt

: ME_55D31692032D
 CONST UID '55D31692032D'
 CONST Name 'HasInternalOperations'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D3169C00AD // DoIt
 )
 ; // Operations
 CONST "ifdef" 'DesignTimeLibrary'

ref; // ME_55D31692032D HasInternalOperations

: ME_55D316B201E7
 CONST UID '55D316B201E7'
 CONST Name 'HasOnlyInternalOperations'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Inherits
   Seq: ( HWL ME_55D31692032D // HasInternalOperations
 )
 ; // Inherits
 CONST "ifdef" 'DesignTimeLibrary'

ref; // ME_55D316B201E7 HasOnlyInternalOperations

: ME_55D316CE0191
 CONST UID '55D316CE0191'
 CONST Name 'RegisterInRep'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;

ref; // ME_55D316CE0191 RegisterInRep

FORWARD ME_55D316E10142

: ME_55D316EB0374
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_55D316EB0374 aControl

: ME_55D316EB0392
 CONST Name 'aGetTarget'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476954260249' '467BAB7F021E.pas.ms.script' // TvcmControlGetTargetEvent
 ;

ref; // ME_55D316EB0392 aGetTarget

: ME_55D316E702A0
 CONST UID '55D316E702A0'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D316E10142 // PublishEntity
 ;
 : Parameters
   Seq: ( ME_55D316EB0374 // aControl
 ME_55D316EB0392 // aGetTarget
 )
 ; // Parameters

ref; // ME_55D316E702A0 DoIt

: ME_55D316E10142
 CONST UID '55D316E10142'
 CONST Name 'PublishEntity'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D316E702A0 // DoIt
 )
 ; // Operations

ref; // ME_55D316E10142 PublishEntity

FORWARD ME_55D317030302

: ME_55D3170B0254
 CONST Name 'aGetTarget'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_55D30CC30066 // TvcmGetTargetEvent
 ;

ref; // ME_55D3170B0254 aGetTarget

: ME_55D31709025E
 CONST UID '55D31709025E'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D317030302 // PublishFormEntity
 ;
 : Parameters
   Seq: ( ME_55D3170B0254 // aGetTarget
 )
 ; // Parameters

ref; // ME_55D31709025E DoIt

: ME_55D317030302
 CONST UID '55D317030302'
 CONST Name 'PublishFormEntity'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D31709025E // DoIt
 )
 ; // Operations

ref; // ME_55D317030302 PublishFormEntity

FORWARD ME_55D317480019

: ME_55D31761010B
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_55D31761010B aControl

: ME_55D317610147
 CONST Name 'anOperation'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_55D317610147 anOperation

: ME_55D31754023F
 CONST Name 'anExecute'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476953D2039F' '467BAB7F021E.pas.ms.script' // TvcmControlExecuteEvent
 ;

ref; // ME_55D31754023F anExecute

: ME_55D317540253
 CONST Name 'aTest'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47694CD40080' '467BAB7F021E.pas.ms.script' // TvcmControlTestEvent
 ;

ref; // ME_55D317540253 aTest

: ME_55D317540271
 CONST Name 'aGetState'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49886B8400D0' '467BAB7F021E.pas.ms.script' // TvcmControlGetStateEvent
 ;

ref; // ME_55D317540271 aGetState

: ME_55D317510217
 CONST UID '55D317510217'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D317480019 // PublishOp$1
 ;
 : Parameters
   Seq: ( ME_55D31761010B // aControl
 ME_55D317610147 // anOperation
 ME_55D31754023F // anExecute
 ME_55D317540253 // aTest
 ME_55D317540271 // aGetState
 )
 ; // Parameters

ref; // ME_55D317510217 DoIt

: ME_55D317480019
 CONST UID '55D317480019'
 CONST Name 'PublishOp'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D317510217 // DoIt
 )
 ; // Operations

ref; // ME_55D317480019 PublishOp$1

FORWARD ME_55D317760220

: ME_55D31783000A
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_55D31783000A aControl

: ME_55D317830028
 CONST Name 'anOperation'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_55D317830028 anOperation

: ME_55D317830046
 CONST Name 'anExecute'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_52A1D97A009E' '47D0E1500033.pas.ms.script' // TvcmExecuteEvent
 ;

ref; // ME_55D317830046 anExecute

: ME_55D317830064
 CONST Name 'aTest'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47694CD40080' '467BAB7F021E.pas.ms.script' // TvcmControlTestEvent
 ;

ref; // ME_55D317830064 aTest

: ME_55D317830096
 CONST Name 'aGetState'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49886B8400D0' '467BAB7F021E.pas.ms.script' // TvcmControlGetStateEvent
 ;

ref; // ME_55D317830096 aGetState

: ME_55D3177D0388
 CONST UID '55D3177D0388'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D317760220 // PublishOp$2
 ;
 : Parameters
   Seq: ( ME_55D31783000A // aControl
 ME_55D317830028 // anOperation
 ME_55D317830046 // anExecute
 ME_55D317830064 // aTest
 ME_55D317830096 // aGetState
 )
 ; // Parameters

ref; // ME_55D3177D0388 DoIt

: ME_55D317760220
 CONST UID '55D317760220'
 CONST Name 'PublishOp'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D3177D0388 // DoIt
 )
 ; // Operations

ref; // ME_55D317760220 PublishOp$2

FORWARD ME_55D317B50256

: ME_55D317C6003F
 CONST Name 'aItem'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4FFC3347011F' '4FFC33380166.pas.ms.script' // TvcmBaseCollectionItem
 ;

ref; // ME_55D317C6003F aItem

: ME_55D317C10252
 CONST UID '55D317C10252'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D317B50256 // IsItemCaptionUnique
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_55D317C6003F // aItem
 )
 ; // Parameters

ref; // ME_55D317C10252 DoIt

: ME_55D317B50256
 CONST UID '55D317B50256'
 CONST Name 'IsItemCaptionUnique'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_55D317C10252 // DoIt
 )
 ; // Operations

ref; // ME_55D317B50256 IsItemCaptionUnique

: ME_478CF34E02CE_ME_55D30D410267
 : Original WL 'ME_478CF34E02CE' '4AB0997B00A2.pas.ms.script' // Assign
 ;
 CONST OpKind opkind_Overridden
ref; // ME_478CF34E02CE_ME_55D30D410267 Assign

: ME_479731C50290_ME_55D30D410267
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_55D30D410267 Cleanup

: ME_479F2B3302C1_ME_55D30D410267
 : Original WL 'ME_479F2B3302C1' '47913B47006E.pas.ms.script' // BeforeAddToCache
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479F2B3302C1_ME_55D30D410267 BeforeAddToCache

: ME_4D555CF50027_ME_55D30D410267
 : Original WL 'ME_4D555CF50027' '4AB0997B00A2.pas.ms.script' // Create
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4D555CF50027_ME_55D30D410267 Create

: ME_55CCBA3C0190_ME_55D30D410267
 : Original WL 'ME_55CCBA3C0190' '4FFC33380166.pas.ms.script' // ChangeName
 ;
 CONST OpKind opkind_Overridden
ref; // ME_55CCBA3C0190_ME_55D30D410267 ChangeName

: ME_55CCBA8003C7_ME_55D30D410267
 : Original WL 'ME_55CCBA8003C7' '4FFC33380166.pas.ms.script' // ChangeCaption
 ;
 CONST OpKind opkind_Overridden
ref; // ME_55CCBA8003C7_ME_55D30D410267 ChangeCaption

: ME_55CCBAAB00F4_ME_55D30D410267
 : Original WL 'ME_55CCBAAB00F4' '4FFC33380166.pas.ms.script' // MakeID
 ;
 CONST OpKind opkind_Overridden
ref; // ME_55CCBAAB00F4_ME_55D30D410267 MakeID

: ME_55CCBAC800F0_ME_55D30D410267
 : Original WL 'ME_55CCBAC800F0' '4FFC33380166.pas.ms.script' // GetID
 ;
 CONST OpKind opkind_Overridden
ref; // ME_55CCBAC800F0_ME_55D30D410267 GetID

: ME_561145D802BB_ME_55D30D410267
 : Original WL 'ME_561145D802BB' '47913B47006E.pas.ms.script' // QueryInterface
 ;
 CONST OpKind opkind_Overridden
ref; // ME_561145D802BB_ME_55D30D410267 QueryInterface

: ME_55D30D410267
 CONST UID '55D30D410267'
 CONST Name 'TvcmBaseEntitiesCollectionItemPrim'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4DDBBD1103C3 // TvcmBaseEntitiesCollectionItem
 ;
 : Inherits
   Seq: ( WL 'ME_4FFC3347011F' '4FFC33380166.pas.ms.script' // TvcmBaseCollectionItem
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_55D30E8A0376 // Operations
 HWL ME_55D30F1A0385 // ToolbarPos
 HWL ME_55D30FB2030A // Controls
 HWL ME_55D30FF20196 // OnGetTarget
 HWL ME_55D3104B0336 // EntityDef
 HWL ME_55D310AA0170 // Options
 HWL ME_55D3115100B3 // ContextMenuWeight
 HWL ME_55D3116F02D5 // EntityID
 HWL ME_55D3127F038A // SupportedBy
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_55D30ECE00AD // GetOperationsStored
 HWL ME_55D3156703C9 // IDRep
 HWL ME_55D3158D0030 // GetOperationsCollectionClass
 HWL ME_55D315AF00FF // GetEntityForControl
 HWL ME_55D315DD021A // Operation
 HWL ME_55D3160A0358 // IsFormItem
 HWL ME_55D3166700B9 // SupportedExBy
 HWL ME_55D31692032D // HasInternalOperations
 HWL ME_55D316B201E7 // HasOnlyInternalOperations
 HWL ME_55D316CE0191 // RegisterInRep
 HWL ME_55D316E10142 // PublishEntity
 HWL ME_55D317030302 // PublishFormEntity
 HWL ME_55D317480019 // PublishOp$1
 HWL ME_55D317760220 // PublishOp$2
 HWL ME_55D317B50256 // IsItemCaptionUnique
 )
 ; // Operations
 : Overridden
   Seq: ( ME_478CF34E02CE_ME_55D30D410267 // Assign
 ME_479731C50290_ME_55D30D410267 // Cleanup
 ME_479F2B3302C1_ME_55D30D410267 // BeforeAddToCache
 ME_4D555CF50027_ME_55D30D410267 // Create
 ME_55CCBA3C0190_ME_55D30D410267 // ChangeName
 ME_55CCBA8003C7_ME_55D30D410267 // ChangeCaption
 ME_55CCBAAB00F4_ME_55D30D410267 // MakeID
 ME_55CCBAC800F0_ME_55D30D410267 // GetID
 ME_561145D802BB_ME_55D30D410267 // QueryInterface
 )
 ; // Overridden
 CONST extprop:rc:SelfName 'EntitiesCollectionItemPrim'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_55D30D410267 TvcmBaseEntitiesCollectionItemPrim

FORWARD ME_55D33EF20068

: ME_55D33F0A00AC
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4DDBBD1103C3 // TvcmBaseEntitiesCollectionItem
 ;
 : Target HWL ME_55D33EF20068 // TvcmEntitiesCollectionItemEntity
 ;

ref; // ME_55D33F0A00AC 

FORWARD ME_55D3528A022B

: ME_55D3529C01AC
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4DDBBD1103C3 // TvcmBaseEntitiesCollectionItem
 ;
 : Target HWL ME_55D3528A022B // TvcmControlsCollectionItem
 ;

ref; // ME_55D3529C01AC 

: ME_56112E5F0122
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4DDBBD1103C3 // TvcmBaseEntitiesCollectionItem
 ;
 : Target WL 'ME_47E13C6B0341' '4799D29F033F.pas.ms.script' // Forms
 ;

ref; // ME_56112E5F0122 

: ME_56113B2F0070
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4DDBBD1103C3 // TvcmBaseEntitiesCollectionItem
 ;
 : Target WL 'ME_56113B1400C7' '47D0E1500033.pas.ms.script' // TvcmBaseEntityDef
 ;

ref; // ME_56113B2F0070 

: ME_56113B7600D5
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4DDBBD1103C3 // TvcmBaseEntitiesCollectionItem
 ;
 : Target WL 'ME_56113B640340' '47D0E1500033.pas.ms.script' // vcmOperationableIdentifiedUserFriendly
 ;

ref; // ME_56113B7600D5 

: ME_4DDBBD1103C3
 CONST UID '4DDBBD1103C3'
 CONST Name 'TvcmBaseEntitiesCollectionItem'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Не дорисовал из-за ссылки на vcmForm'#13#10'Потом надо как-то разрулить цикл' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 )
 ; // Inherits
 : Children
   Seq: ( HWL ME_55D30CC30066 // TvcmGetTargetEvent
 HWL ME_55D30D410267 // TvcmBaseEntitiesCollectionItemPrim
 )
 ; // Children
 : Dependencies
   Seq: ( ME_55D33F0A00AC // TvcmEntitiesCollectionItemEntity
 ME_55D3529C01AC // TvcmControlsCollectionItem
 ME_56112E5F0122 // Forms
 ME_56113B2F0070 // TvcmBaseEntityDef
 ME_56113B7600D5 // vcmOperationableIdentifiedUserFriendly
 )
 ; // Dependencies
 CONST "need UC" true
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\vcmBaseEntitiesCollectionItem.pas'
 CONST extprop:rc:SelfName 'EntitiesCollectionItem'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmBaseEntitiesCollectionItem'

ref; // ME_4DDBBD1103C3 TvcmBaseEntitiesCollectionItem

: ME_52A72EB701C5
 CONST UID '52A72EB701C5'
 CONST Name 'TvcmModuleDef'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmModuleDef.pas'
 CONST extprop:rc:SelfName 'ModuleDef'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmModuleDef'

ref; // ME_52A72EB701C5 TvcmModuleDef

: ME_52A72F6A0171
 CONST UID '52A72F6A0171'
 CONST Name 'TvcmFormsCollectionItem'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmFormsCollectionItem.pas'
 CONST extprop:rc:SelfName 'FormsCollectionItem'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmFormsCollectionItem'

ref; // ME_52A72F6A0171 TvcmFormsCollectionItem

: ME_52A824420357
 CONST UID '52A824420357'
 CONST Name 'TvcmMenuItemsCollection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmMenuItemsCollection.pas'
 CONST extprop:rc:SelfName 'MenuItemsCollection'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmMenuItemsCollection'

ref; // ME_52A824420357 TvcmMenuItemsCollection

: ME_52AB1CF803B2
 CONST UID '52AB1CF803B2'
 CONST Name 'TvcmMenuItemsCollectionItem'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmMenuItemsCollectionItem.pas'
 CONST extprop:rc:SelfName 'MenuItemsCollectionItem'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmMenuItemsCollectionItem'

ref; // ME_52AB1CF803B2 TvcmMenuItemsCollectionItem

FORWARD ME_559E5F080019

: ME_559E5F32026E
 CONST UID '559E5F32026E'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_559E5F080019 // TvcmUserFriendlyControlList
 ;
 : Target WL 'ME_499301BF0067' '499EAAE502A8.pas.ms.script' // IvcmUserFriendlyControl
 ;

ref; // ME_559E5F32026E ItemType

: ME_559E5F080019
 CONST UID '559E5F080019'
 CONST Name 'TvcmUserFriendlyControlList'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.pas.ms.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_47B57D830369' '47913B47006E.pas.ms.script' // l3InterfaceRefList
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_559E5F32026E // ItemType
 )
 ; // Attributes
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\vcmUserFriendlyControlList.pas'
 CONST extprop:rc:SelfName 'UserFriendlyControlList'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmUserFriendlyControlList'

ref; // ME_559E5F080019 TvcmUserFriendlyControlList

: ME_5620D3930294
 CONST UID '5620D3930294'
 CONST Name 'TvcmActiveControlsCollection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmActiveControlsCollection.pas'
 CONST extprop:rc:SelfName 'ActiveControlsCollection'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmActiveControlsCollection'

ref; // ME_5620D3930294 TvcmActiveControlsCollection

FORWARD ME_5620C9B40399

: ME_5620C9CA01E4
 CONST UID '5620C9CA01E4'
 CONST Name 'vcm_DefaultOperationOptions'
 CONST Class class_Attribute
 %SUMMARY 'Набор параметров по умолчанию для свойсва TvcmOperationsCollectionItem.Options' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620C9B40399 // vcm_DefaultOperationOptions
 ;
 CONST Value '[vcm_ooShowInMainToolbar, vcm_ooShowInChildToolbar, vcm_ooShowInContextMenu, vcm_ooShowInMainMenu, vcm_ooShowInChildMenu]'
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '[vcm_ooShowInMainToolbar, vcm_ooShowInChildToolbar, vcm_ooShowInContextMenu, vcm_ooShowInMainMenu, vcm_ooShowInChildMenu]'

ref; // ME_5620C9CA01E4 vcm_DefaultOperationOptions

: ME_5620C9B40399
 CONST UID '5620C9B40399'
 CONST Name 'vcm_DefaultOperationOptions'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Attributes
   Seq: ( HWL ME_5620C9CA01E4 // vcm_DefaultOperationOptions
 )
 ; // Attributes
 CONST "spell names" false
 CONST extprop:rc:SelfName '_DefaultOperationOptions'

ref; // ME_5620C9B40399 vcm_DefaultOperationOptions

FORWARD ME_5620CA450068

: ME_5620CA56012A
 CONST Name 'State'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_4683F4D501E9' '467BAB7F021E.pas.ms.script' // TvcmOperationStateIndex
 ;

ref; // ME_5620CA56012A State

: ME_5620CA5300C6
 CONST UID '5620CA5300C6'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CA450068 // TvcmGetStateEvent
 ;
 : Parameters
   Seq: ( ME_5620CA56012A // State
 )
 ; // Parameters

ref; // ME_5620CA5300C6 DoIt

: ME_5620CA450068
 CONST UID '5620CA450068'
 CONST Name 'TvcmGetStateEvent'
 CONST Class class_Class
 : Stereotype st_Function ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Operations
   Seq: ( HWL ME_5620CA5300C6 // DoIt
 )
 ; // Operations
 CONST "of object" true

ref; // ME_5620CA450068 TvcmGetStateEvent

: ME_5620CABB02F5
 CONST UID '5620CABB02F5'
 CONST Name 'TvcmContextTestEvent'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Вызывается в момент проверки доступности операции из контекстного меню' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Inherits
   Seq: ( WL 'ME_47E765A20100' '4683F37902CF.pas.ms.script' // TvcmTestEvent
 )
 ; // Inherits

ref; // ME_5620CABB02F5 TvcmContextTestEvent

: ME_5620CB260263
 CONST UID '5620CB260263'
 CONST Name 'TvcmContextExecuteEvent'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Вызывается при выполнении операции из контекстного меню' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Inherits
   Seq: ( WL 'ME_52A1D97A009E' '47D0E1500033.pas.ms.script' // TvcmExecuteEvent
 )
 ; // Inherits

ref; // ME_5620CB260263 TvcmContextExecuteEvent

FORWARD ME_5620CB5800A0

: ME_5620CB620264
 CONST UID '5620CB620264'
 CONST Name 'vcm_htContext'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CB5800A0 // TvcmHandleType
 ;

ref; // ME_5620CB620264 vcm_htContext

: ME_5620CB6802BE
 CONST UID '5620CB6802BE'
 CONST Name 'vcm_htGlobal'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CB5800A0 // TvcmHandleType
 ;

ref; // ME_5620CB6802BE vcm_htGlobal

: ME_5620CB6D0372
 CONST UID '5620CB6D0372'
 CONST Name 'vcm_htControl'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CB5800A0 // TvcmHandleType
 ;

ref; // ME_5620CB6D0372 vcm_htControl

: ME_5620CB5800A0
 CONST UID '5620CB5800A0'
 CONST Name 'TvcmHandleType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Attributes
   Seq: ( HWL ME_5620CB620264 // vcm_htContext
 HWL ME_5620CB6802BE // vcm_htGlobal
 HWL ME_5620CB6D0372 // vcm_htControl
 )
 ; // Attributes
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5620CB5800A0 TvcmHandleType

: ME_5620CB7B03DE
 CONST UID '5620CB7B03DE'
 CONST Name 'TvcmHandleTypes'
 CONST Class class_Class
 : Stereotype st_SetOf ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Inherits
   Seq: ( HWL ME_5620CB5800A0 // TvcmHandleType
 )
 ; // Inherits

ref; // ME_5620CB7B03DE TvcmHandleTypes

FORWARD ME_5620CFFC0045

: ME_5620CEB201FB
 CONST UID '5620CEB201FB'
 CONST Name 'OperationType'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_4683CC350070' '467BAB7F021E.pas.ms.script' // TvcmOperationType
 ;
 CONST "needs field" true
 CONST "needs stored directive" true
 CONST "pm" true

ref; // ME_5620CEB201FB OperationType

: ME_5620CF2802E3
 CONST UID '5620CF2802E3'
 CONST Name 'Options'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_51E00A6B0010' '499EAAE502A8.pas.ms.script' // TvcmOperationOptions
 ;
 CONST "pm" true

ref; // ME_5620CF2802E3 Options

: ME_5620CF82017C
 CONST UID '5620CF82017C'
 CONST Name 'ContextMenuWeight'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "needs field" true
 CONST "pm" true

ref; // ME_5620CF82017C ContextMenuWeight

: ME_5620CFC10224
 CONST UID '5620CFC10224'
 CONST Name 'OperationID'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5620CFC10224 OperationID

: ME_5620D0330150
 CONST UID '5620D0330150'
 CONST Name 'AutoLock'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_5620D0330150 AutoLock

: ME_5620D127038B
 CONST UID '5620D127038B'
 CONST Name 'AutoFocus'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 %SUMMARY 'Установка фокуса до выполнения операции.'#13#10''#13#10'Если AutoFocus = True, перед выполнением операции, фокус передаётся форме или контролу, с которым связана эта операция' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_5620D127038B AutoFocus

: ME_5620D1760396
 CONST UID '5620D1760396'
 CONST Name 'LongProcess'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 %SUMMARY 'Обрамление выполнения операции курсором crHourGlass. Нужно только для длительных внутренних (vcm_otInternal) операций, т.к. все вызовы через Action и так обрамлены подобным образом.'#13#10''#13#10'Если LongProcess = True, перед выполнением операции курсор заменяется на crHourGlass, а после выполнения возвращается к первоначальному виду' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_5620D1760396 LongProcess

: ME_5620D1DE0361
 CONST UID '5620D1DE0361'
 CONST Name 'f_GroupID'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_5620D1DE0361 f_GroupID

: ME_5620D26602B5
 CONST UID '5620D26602B5'
 CONST Name 'States'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target HWL ME_5620D2420197 // TvcmBaseOperationStates
 ;
 CONST "needs field" true
 CONST "pm" true

ref; // ME_5620D26602B5 States

: ME_5620D2A101D3
 CONST UID '5620D2A101D3'
 CONST Name 'State'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_4683F4D501E9' '467BAB7F021E.pas.ms.script' // TvcmOperationStateIndex
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5620D2A101D3 State

: ME_5620D30100C9
 CONST UID '5620D30100C9'
 CONST Name 'f_Enabled'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5620D30100C9 f_Enabled

: ME_5620D32B0029
 CONST UID '5620D32B0029'
 CONST Name 'f_VisibleToUser'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_5620D32B0029 f_VisibleToUser

: ME_5620D36F0377
 CONST UID '5620D36F0377'
 CONST Name 'f_OpDef'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_4995624100A6' '499EAAE502A8.pas.ms.script' // IvcmOperationDef
 ;

ref; // ME_5620D36F0377 f_OpDef

: ME_5620D3AC01C5
 CONST UID '5620D3AC01C5'
 CONST Name 'Controls'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target HWL ME_5620D3930294 // TvcmActiveControlsCollection
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5620D3AC01C5 Controls

: ME_5620D3E900E0
 CONST UID '5620D3E900E0'
 CONST Name 'OnGetState'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target HWL ME_5620CA450068 // TvcmGetStateEvent
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_5620D3E900E0 OnGetState

: ME_5620D41E0142
 CONST UID '5620D41E0142'
 CONST Name 'OnTest'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 %SUMMARY 'Вызывается для перерисовки состояния операции.'#13#10''#13#10'Данный обработчик вызывается для определения доступности операции. В массиве aParams можно вернуть изменившее состояние.'#13#10''#13#10'Индекс параметра   Тип        Значение'#13#10'-----------------  ---------  --------------------------------'#13#10'vcm_opEnabled      Boolean    Доступность выполнения операции'#13#10'vcm_opVisible      Boolean    Видимость операции в меню и на панели инструментов'#13#10'vcm_opChecked      Boolean    Операция помечена'#13#10'vcm_opLongHint     AnsiString     Текст подсказки, отображаемой в статусной строке'#13#10'vcm_opCaption      AnsiString     Заголовок пункта меню'#13#10''#13#10'Для типа операции vcm_otCombo в aParams.Op.SubItems нужно вернуть список строк, представляющий список элементов выпадающего списка.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_47E765A20100' '4683F37902CF.pas.ms.script' // TvcmTestEvent
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_5620D41E0142 OnTest

: ME_5620D48C0185
 CONST UID '5620D48C0185'
 CONST Name 'OnExecute'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 %SUMMARY 'Обработчик операции. Вызывается из меню главной формы или панели инструментов.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_52A1D97A009E' '47D0E1500033.pas.ms.script' // TvcmExecuteEvent
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_5620D48C0185 OnExecute

: ME_5620D51000AB
 CONST UID '5620D51000AB'
 CONST Name 'f_FormGetState'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_49886B8400D0' '467BAB7F021E.pas.ms.script' // TvcmControlGetStateEvent
 ;

ref; // ME_5620D51000AB f_FormGetState

: ME_5620D5350264
 CONST UID '5620D5350264'
 CONST Name 'f_FormTest'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_47694CD40080' '467BAB7F021E.pas.ms.script' // TvcmControlTestEvent
 ;

ref; // ME_5620D5350264 f_FormTest

: ME_5620D55C03E1
 CONST UID '5620D55C03E1'
 CONST Name 'f_FormExecute'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_476953D2039F' '467BAB7F021E.pas.ms.script' // TvcmControlExecuteEvent
 ;

ref; // ME_5620D55C03E1 f_FormExecute

: ME_5620D5B80280
 CONST UID '5620D5B80280'
 CONST Name 'OnContextTest'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 %SUMMARY 'Вызывается из контекстного меню.'#13#10'          '#13#10'Данный обработчик вызывается для определения доступности операции. В массиве aParams можно вернуть изменившее состояние.'#13#10''#13#10'Индекс параметра   Тип        Значение'#13#10'-----------------  ---------  --------------------------------'#13#10'vcm_opEnabled      Boolean    Доступность выполнения операции'#13#10'vcm_opVisible      Boolean    Видимость операции в меню и на панели инструментов'#13#10'vcm_opChecked      Boolean    Операция помечена'#13#10'vcm_opLongHint     AnsiString     Текст подсказки, отображаемой в статусной строке'#13#10'vcm_opCaption      AnsiString     Заголовок пункта меню'#13#10''#13#10'Для типа операции vcm_otCombo в aParams.Op.SubItems нужно вернуть список строк, представляющий список элементов выпадающего списка.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target HWL ME_5620CABB02F5 // TvcmContextTestEvent
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_5620D5B80280 OnContextTest

: ME_5620D625002F
 CONST UID '5620D625002F'
 CONST Name 'OnContextExecute'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 %SUMMARY 'Обработчик операции. Вызывается из контекстного меню.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target HWL ME_5620CB260263 // TvcmContextExecuteEvent
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_5620D625002F OnContextExecute

: ME_5620D68A0067
 CONST UID '5620D68A0067'
 CONST Name 'IsCaptionUnique'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_5620D68A0067 IsCaptionUnique

: ME_5620D6D40299
 CONST UID '5620D6D40299'
 CONST Name 'SaveShortcut'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_499562B802E7' '4AB0997B00A2.pas.ms.script' // TShortCut
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5620D6D40299 SaveShortcut

: ME_5620D71D03D0
 CONST UID '5620D71D03D0'
 CONST Name 'SaveSecondaryShortcuts'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5620D71D03D0 SaveSecondaryShortcuts

: ME_5620D7470392
 CONST UID '5620D7470392'
 CONST Name 'IsDefault'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "needs field" true
 CONST "needs stored directive" true
 CONST "pm" true

ref; // ME_5620D7470392 IsDefault

: ME_5620E01800F3
 CONST UID '5620E01800F3'
 CONST Name 'VisibleToUser'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" true

ref; // ME_5620E01800F3 VisibleToUser

: ME_5620E17102F2
 CONST UID '5620E17102F2'
 CONST Name 'OperationDef'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Описатель операции' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_4995624100A6' '499EAAE502A8.pas.ms.script' // IvcmOperationDef
 ;
 CONST "pm" true

ref; // ME_5620E17102F2 OperationDef

: ME_5620E23201F0
 CONST UID '5620E23201F0'
 CONST Name 'Category'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Категория операции.'#13#10'Задается на стадии проектирования формы. Используется для группировки операций.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 CONST "ifndef" 'DesignTimeLibrary'
 CONST "pm" true

ref; // ME_5620E23201F0 Category

: ME_5620E28E0284
 CONST UID '5620E28E0284'
 CONST Name 'GroupID'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "needs stored directive" true
 CONST "pm" true

ref; // ME_5620E28E0284 GroupID

: ME_5620E402012B
 CONST UID '5620E402012B'
 CONST Name 'ExcludeUserTypes'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_4992F9450176' '4683F37902CF.pas.ms.script' // TvcmEffectiveUserTypes
 ;
 CONST "pm" true

ref; // ME_5620E402012B ExcludeUserTypes

: ME_5620E5640206
 CONST UID '5620E5640206'
 CONST Name 'CurrentState'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target HWL ME_4C77C99500F6 // TvcmBaseOperationState
 ;
 CONST "pm" true

ref; // ME_5620E5640206 CurrentState

: ME_5620E6F00105
 CONST UID '5620E6F00105'
 CONST Name 'Linked'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" true

ref; // ME_5620E6F00105 Linked

: ME_5624C3E003C7
 CONST UID '5624C3E003C7'
 CONST Name 'f_Options'
 CONST Class class_Attribute
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Target WL 'ME_51E00A6B0010' '499EAAE502A8.pas.ms.script' // TvcmOperationOptions
 ;

ref; // ME_5624C3E003C7 f_Options

FORWARD ME_5620E1270164

: ME_5620E12F0055
 CONST UID '5620E12F0055'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E1270164 // GetDefaultOptions
 ;
 : Target WL 'ME_51E00A6B0010' '499EAAE502A8.pas.ms.script' // TvcmOperationOptions
 ;

ref; // ME_5620E12F0055 DoIt

: ME_5620E1270164
 CONST UID '5620E1270164'
 CONST Name 'GetDefaultOptions'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E12F0055 // DoIt
 )
 ; // Operations

ref; // ME_5620E1270164 GetDefaultOptions

FORWARD ME_5620E2C30048

: ME_5620E2CC03A3
 CONST UID '5620E2CC03A3'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E2C30048 // GetGroupIDStored
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5620E2CC03A3 DoIt

: ME_5620E2C30048
 CONST UID '5620E2C30048'
 CONST Name 'GetGroupIDStored'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E2CC03A3 // DoIt
 )
 ; // Operations

ref; // ME_5620E2C30048 GetGroupIDStored

FORWARD ME_5620E36701EE

: ME_5620E37300D8
 CONST UID '5620E37300D8'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E36701EE // GetOperationTypeStored
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5620E37300D8 DoIt

: ME_5620E36701EE
 CONST UID '5620E36701EE'
 CONST Name 'GetOperationTypeStored'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E37300D8 // DoIt
 )
 ; // Operations

ref; // ME_5620E36701EE GetOperationTypeStored

FORWARD ME_5620E5C101B2

: ME_5620E5D00238
 CONST UID '5620E5D00238'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E5C101B2 // GetIsDefaultStored
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5620E5D00238 DoIt

: ME_5620E5C101B2
 CONST UID '5620E5C101B2'
 CONST Name 'GetIsDefaultStored'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E5D00238 // DoIt
 )
 ; // Operations

ref; // ME_5620E5C101B2 GetIsDefaultStored

: ME_5620E5FF00DA
 CONST UID '5620E5FF00DA'
 CONST Name 'OnSecondaryShortCutsChange'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Inherits
   Seq: ( WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 )
 ; // Inherits

ref; // ME_5620E5FF00DA OnSecondaryShortCutsChange

FORWARD ME_5620E72703A2

: ME_5620E72F012B
 CONST UID '5620E72F012B'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E72703A2 // IsHandledToControl
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5620E72F012B DoIt

: ME_5620E72703A2
 CONST UID '5620E72703A2'
 CONST Name 'IsHandledToControl'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'операция опубликована компонентом' ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E72F012B // DoIt
 )
 ; // Operations

ref; // ME_5620E72703A2 IsHandledToControl

FORWARD ME_5620E6910372

: ME_5620E69A03C0
 CONST UID '5620E69A03C0'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E6910372 // GetLinkedAction
 ;
 : Target WL 'ME_47E761BB02FE' '47E7617C0275.pas.ms.script' // TvcmAction
 ;

ref; // ME_5620E69A03C0 DoIt

: ME_5620E6910372
 CONST UID '5620E6910372'
 CONST Name 'GetLinkedAction'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Action к которому привязана операция' ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E69A03C0 // DoIt
 )
 ; // Operations

ref; // ME_5620E6910372 GetLinkedAction

FORWARD ME_5620E66E0367

: ME_5620E6760335
 CONST UID '5620E6760335'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E66E0367 // ControllerCommand
 ;
 : Target WL 'ME_476F71A701AB' '4AB0C3C60310.pas.ms.script' // Word
 ;

ref; // ME_5620E6760335 DoIt

: ME_5620E66E0367
 CONST UID '5620E66E0367'
 CONST Name 'ControllerCommand'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'идентификатор комманды-shortcut' ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E6760335 // DoIt
 )
 ; // Operations

ref; // ME_5620E66E0367 ControllerCommand

FORWARD ME_5620E65A00D3

: ME_5620E6600155
 CONST UID '5620E6600155'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E65A00D3 // ParentID
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_5620E6600155 DoIt

: ME_5620E65A00D3
 CONST UID '5620E65A00D3'
 CONST Name 'ParentID'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E6600155 // DoIt
 )
 ; // Operations

ref; // ME_5620E65A00D3 ParentID

FORWARD ME_5620E643039B

: ME_5620E64901F7
 CONST UID '5620E64901F7'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E643039B // IsLinkedToModule
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5620E64901F7 DoIt

: ME_5620E643039B
 CONST UID '5620E643039B'
 CONST Name 'IsLinkedToModule'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E64901F7 // DoIt
 )
 ; // Operations

ref; // ME_5620E643039B IsLinkedToModule

FORWARD ME_5620E6250019

: ME_5620E63102EA
 CONST Name 'aValue'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_499562B802E7' '4AB0997B00A2.pas.ms.script' // TShortCut
 ;

ref; // ME_5620E63102EA aValue

: ME_5620E6310312
 CONST Name 'aCommandID'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476F71A701AB' '4AB0C3C60310.pas.ms.script' // Word
 ;
 CONST Value 0
 : ValueType WL 'ME_476F71A701AB' '4AB0C3C60310.pas.ms.script' // Word
 ;
 CONST extprop:pas:Value 0

ref; // ME_5620E6310312 aCommandID

: ME_5620E62F00C4
 CONST UID '5620E62F00C4'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E6250019 // ResetShortCutHandler
 ;
 : Parameters
   Seq: ( ME_5620E63102EA // aValue
 ME_5620E6310312 // aCommandID
 )
 ; // Parameters

ref; // ME_5620E62F00C4 DoIt

: ME_5620E6250019
 CONST UID '5620E6250019'
 CONST Name 'ResetShortCutHandler'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E62F00C4 // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_5620E6250019 ResetShortCutHandler

FORWARD ME_5620E7B10292

: ME_5620E7BC02BA
 CONST Name 'State'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_4683F4D501E9' '467BAB7F021E.pas.ms.script' // TvcmOperationStateIndex
 ;

ref; // ME_5620E7BC02BA State

: ME_5620E7BA01C0
 CONST UID '5620E7BA01C0'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E7B10292 // DoFormGetState
 ;
 : Parameters
   Seq: ( ME_5620E7BC02BA // State
 )
 ; // Parameters

ref; // ME_5620E7BA01C0 DoIt

: ME_5620E7B10292
 CONST UID '5620E7B10292'
 CONST Name 'DoFormGetState'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E7BA01C0 // DoIt
 )
 ; // Operations

ref; // ME_5620E7B10292 DoFormGetState

FORWARD ME_5620E7CC00CF

: ME_5620E7D50242
 CONST Name 'aParams'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683E07E004B' '467BAB7F021E.pas.ms.script' // IvcmTestParamsPrim
 ;

ref; // ME_5620E7D50242 aParams

: ME_5620E7D20242
 CONST UID '5620E7D20242'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E7CC00CF // DoFormTest
 ;
 : Parameters
   Seq: ( ME_5620E7D50242 // aParams
 )
 ; // Parameters

ref; // ME_5620E7D20242 DoIt

: ME_5620E7CC00CF
 CONST UID '5620E7CC00CF'
 CONST Name 'DoFormTest'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E7D20242 // DoIt
 )
 ; // Operations

ref; // ME_5620E7CC00CF DoFormTest

FORWARD ME_5620E7E70331

: ME_5620E7F20274
 CONST Name 'aParams'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47F2108E028C' '4683F37902CF.pas.ms.script' // IvcmExecuteParams
 ;

ref; // ME_5620E7F20274 aParams

: ME_5620E7EF008A
 CONST UID '5620E7EF008A'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E7E70331 // DoFormExecute
 ;
 : Parameters
   Seq: ( ME_5620E7F20274 // aParams
 )
 ; // Parameters

ref; // ME_5620E7EF008A DoIt

: ME_5620E7E70331
 CONST UID '5620E7E70331'
 CONST Name 'DoFormExecute'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E7EF008A // DoIt
 )
 ; // Operations

ref; // ME_5620E7E70331 DoFormExecute

FORWARD ME_5620E802035A

: ME_5620E81200D9
 CONST Name 'aParams'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683E07E004B' '467BAB7F021E.pas.ms.script' // IvcmTestParamsPrim
 ;

ref; // ME_5620E81200D9 aParams

: ME_5620E80B03DB
 CONST UID '5620E80B03DB'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E802035A // FakeControlTest
 ;
 : Parameters
   Seq: ( ME_5620E81200D9 // aParams
 )
 ; // Parameters

ref; // ME_5620E80B03DB DoIt

: ME_5620E802035A
 CONST UID '5620E802035A'
 CONST Name 'FakeControlTest'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E80B03DB // DoIt
 )
 ; // Operations

ref; // ME_5620E802035A FakeControlTest

: ME_5620E8DC016C
 CONST UID '5620E8DC016C'
 CONST Name 'ClearOp'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;

ref; // ME_5620E8DC016C ClearOp

FORWARD ME_5620E8B900F5

: ME_5620E8C703A7
 CONST Name 'aShortCut'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_499562B802E7' '4AB0997B00A2.pas.ms.script' // TShortCut
 ;

ref; // ME_5620E8C703A7 aShortCut

: ME_5620E8C703CF
 CONST Name 'aSecondaryShortCuts'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_499563790006' '4799D29F033F.pas.ms.script' // TShortCutList
 ;

ref; // ME_5620E8C703CF aSecondaryShortCuts

: ME_5620E8C4034D
 CONST UID '5620E8C4034D'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E8B900F5 // SetShortCuts
 ;
 : Parameters
   Seq: ( ME_5620E8C703A7 // aShortCut
 ME_5620E8C703CF // aSecondaryShortCuts
 )
 ; // Parameters

ref; // ME_5620E8C4034D DoIt

: ME_5620E8B900F5
 CONST UID '5620E8B900F5'
 CONST Name 'SetShortCuts'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E8C4034D // DoIt
 )
 ; // Operations

ref; // ME_5620E8B900F5 SetShortCuts

FORWARD ME_5620E87503A8

: ME_5620E883019F
 CONST UID '5620E883019F'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E87503A8 // StatesClass
 ;
 : Target HWL ME_5621097F0137 // RvcmBaseOperationStates
 ;

ref; // ME_5620E883019F DoIt

: ME_5620E87503A8
 CONST UID '5620E87503A8'
 CONST Name 'StatesClass'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E883019F // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_5620E87503A8 StatesClass

FORWARD ME_5620E8300061

: ME_5620E83702EB
 CONST UID '5620E83702EB'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620E8300061 // OwnerUserType
 ;
 : Target WL 'ME_4992F9230369' '4683F37902CF.pas.ms.script' // TvcmEffectiveUserType
 ;

ref; // ME_5620E83702EB DoIt

: ME_5620E8300061
 CONST UID '5620E8300061'
 CONST Name 'OwnerUserType'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Возвращает пользовательский тип "формы" на которой определена операция' ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620E83702EB // DoIt
 )
 ; // Operations

ref; // ME_5620E8300061 OwnerUserType

FORWARD ME_5620EED40232

: ME_5620EEDB0322
 CONST UID '5620EEDB0322'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620EED40232 // OwnerForm
 ;
 : Target WL 'ME_484529DC0276' '4799D29F033F.pas.ms.script' // TCustomForm
 ;

ref; // ME_5620EEDB0322 DoIt

: ME_5620EED40232
 CONST UID '5620EED40232'
 CONST Name 'OwnerForm'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Возвращает "форму" на которой определена операция' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620EEDB0322 // DoIt
 )
 ; // Operations

ref; // ME_5620EED40232 OwnerForm

FORWARD ME_5620EF040199

: ME_5620EF6F0285
 CONST Name 'aShortCut'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_499562B802E7' '4AB0997B00A2.pas.ms.script' // TShortCut
 ;

ref; // ME_5620EF6F0285 aShortCut

: ME_5620EF6F02A3
 CONST Name 'aSecondaryShortCuts'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_56210AE80069' '4AB0997B00A2.pas.ms.script' // TCustomShortCutList
 ;

ref; // ME_5620EF6F02A3 aSecondaryShortCuts

: ME_5620EF450284
 CONST UID '5620EF450284'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620EF040199 // ReplaceShortCuts$1
 ;
 : Parameters
   Seq: ( ME_5620EF6F0285 // aShortCut
 ME_5620EF6F02A3 // aSecondaryShortCuts
 )
 ; // Parameters

ref; // ME_5620EF450284 DoIt

: ME_5620EF040199
 CONST UID '5620EF040199'
 CONST Name 'ReplaceShortCuts'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620EF450284 // DoIt
 )
 ; // Operations
 CONST "ifdef" 'XE'

ref; // ME_5620EF040199 ReplaceShortCuts$1

FORWARD ME_5620EF9D02F1

: ME_5620EFDE036C
 CONST Name 'aShortCut'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_499562B802E7' '4AB0997B00A2.pas.ms.script' // TShortCut
 ;

ref; // ME_5620EFDE036C aShortCut

: ME_5620EFDE0394
 CONST Name 'aSecondaryShortCuts'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_499563790006' '4799D29F033F.pas.ms.script' // TShortCutList
 ;

ref; // ME_5620EFDE0394 aSecondaryShortCuts

: ME_5620EFDC0236
 CONST UID '5620EFDC0236'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620EF9D02F1 // ReplaceShortCuts$2
 ;
 : Parameters
   Seq: ( ME_5620EFDE036C // aShortCut
 ME_5620EFDE0394 // aSecondaryShortCuts
 )
 ; // Parameters

ref; // ME_5620EFDC0236 DoIt

: ME_5620EF9D02F1
 CONST UID '5620EF9D02F1'
 CONST Name 'ReplaceShortCuts'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620EFDC0236 // DoIt
 )
 ; // Operations
 CONST "ifndef" 'XE'

ref; // ME_5620EF9D02F1 ReplaceShortCuts$2

: ME_5620F0050158
 CONST UID '5620F0050158'
 CONST Name 'StoreDesignTimeShortcuts'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;

ref; // ME_5620F0050158 StoreDesignTimeShortcuts

FORWARD ME_5620F09B013E

: ME_5620F0A20328
 CONST UID '5620F0A20328'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620F09B013E // SomePropStored
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5620F0A20328 DoIt

: ME_5620F09B013E
 CONST UID '5620F09B013E'
 CONST Name 'SomePropStored'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620F0A20328 // DoIt
 )
 ; // Operations

ref; // ME_5620F09B013E SomePropStored

FORWARD ME_5620F16701DD

: ME_5620F1700008
 CONST Name 'aShortCut'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_499562B802E7' '4AB0997B00A2.pas.ms.script' // TShortCut
 ;

ref; // ME_5620F1700008 aShortCut

: ME_5620F16E004E
 CONST UID '5620F16E004E'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620F16701DD // RemoveShortCut
 ;
 : Parameters
   Seq: ( ME_5620F1700008 // aShortCut
 )
 ; // Parameters

ref; // ME_5620F16E004E DoIt

: ME_5620F16701DD
 CONST UID '5620F16701DD'
 CONST Name 'RemoveShortCut'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620F16E004E // DoIt
 )
 ; // Operations

ref; // ME_5620F16701DD RemoveShortCut

FORWARD ME_5620F28501E2

: ME_5620F29102FA
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_5620F29102FA aControl

: ME_5620F28F00E8
 CONST UID '5620F28F00E8'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620F28501E2 // UnlinkControl
 ;
 : Parameters
   Seq: ( ME_5620F29102FA // aControl
 )
 ; // Parameters

ref; // ME_5620F28F00E8 DoIt

: ME_5620F28501E2
 CONST UID '5620F28501E2'
 CONST Name 'UnlinkControl'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620F28F00E8 // DoIt
 )
 ; // Operations

ref; // ME_5620F28501E2 UnlinkControl

FORWARD ME_5620F2B50162

: ME_5620F2BF01A8
 CONST Name 'aTypes'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5620CB7B03DE // TvcmHandleTypes
 ;

ref; // ME_5620F2BF01A8 aTypes

: ME_5620F2BD00C2
 CONST UID '5620F2BD00C2'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620F2B50162 // Handled
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_5620F2BF01A8 // aTypes
 )
 ; // Parameters

ref; // ME_5620F2BD00C2 DoIt

: ME_5620F2B50162
 CONST UID '5620F2B50162'
 CONST Name 'Handled'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620F2BD00C2 // DoIt
 )
 ; // Operations

ref; // ME_5620F2B50162 Handled

FORWARD ME_5620F10C0381

: ME_5620F1200060
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_5620F1200060 aControl

: ME_5620F1200088
 CONST Name 'aTarget'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A451250363' '4AB0C3C60310.pas.ms.script' // IUnknown
 ;

ref; // ME_5620F1200088 aTarget

: ME_5620F12000A6
 CONST Name 'aMode'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683F5860071' '499EAAE502A8.pas.ms.script' // TvcmOperationMode
 ;

ref; // ME_5620F12000A6 aMode

: ME_5620F12000CE
 CONST Name 'aParams'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4987048B02EF' '4683F37902CF.pas.ms.script' // IvcmParams
 ;

ref; // ME_5620F12000CE aParams

: ME_5620F12000F6
 CONST Name 'aForce'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5620F12000F6 aForce

: ME_5620F11503AF
 CONST UID '5620F11503AF'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620F10C0381 // Operation
 ;
 : Parameters
   Seq: ( ME_5620F1200060 // aControl
 ME_5620F1200088 // aTarget
 ME_5620F12000A6 // aMode
 ME_5620F12000CE // aParams
 ME_5620F12000F6 // aForce
 )
 ; // Parameters

ref; // ME_5620F11503AF DoIt

: ME_5620F10C0381
 CONST UID '5620F10C0381'
 CONST Name 'Operation'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Выполнение операции' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620F11503AF // DoIt
 )
 ; // Operations

ref; // ME_5620F10C0381 Operation

FORWARD ME_5620F19403B6

: ME_5620F1A801FE
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_5620F1A801FE aControl

: ME_5620F1A80226
 CONST Name 'anExecute'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476953D2039F' '467BAB7F021E.pas.ms.script' // TvcmControlExecuteEvent
 ;

ref; // ME_5620F1A80226 anExecute

: ME_5620F1A80244
 CONST Name 'aTest'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47694CD40080' '467BAB7F021E.pas.ms.script' // TvcmControlTestEvent
 ;

ref; // ME_5620F1A80244 aTest

: ME_5620F1A8026C
 CONST Name 'aGetState'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49886B8400D0' '467BAB7F021E.pas.ms.script' // TvcmControlGetStateEvent
 ;

ref; // ME_5620F1A8026C aGetState

: ME_5620F1A20366
 CONST UID '5620F1A20366'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620F19403B6 // PublishOp$1
 ;
 : Parameters
   Seq: ( ME_5620F1A801FE // aControl
 ME_5620F1A80226 // anExecute
 ME_5620F1A80244 // aTest
 ME_5620F1A8026C // aGetState
 )
 ; // Parameters

ref; // ME_5620F1A20366 DoIt

: ME_5620F19403B6
 CONST UID '5620F19403B6'
 CONST Name 'PublishOp'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'опубликовать операцию' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620F1A20366 // DoIt
 )
 ; // Operations

ref; // ME_5620F19403B6 PublishOp$1

FORWARD ME_5620F1DF01BF

: ME_5620F1F500D9
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_5620F1F500D9 aControl

: ME_5620F1F50101
 CONST Name 'anExecute'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_52A1D97A009E' '47D0E1500033.pas.ms.script' // TvcmExecuteEvent
 ;

ref; // ME_5620F1F50101 anExecute

: ME_5620F1F50129
 CONST Name 'aTest'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47694CD40080' '467BAB7F021E.pas.ms.script' // TvcmControlTestEvent
 ;

ref; // ME_5620F1F50129 aTest

: ME_5620F1F50147
 CONST Name 'aGetState'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49886B8400D0' '467BAB7F021E.pas.ms.script' // TvcmControlGetStateEvent
 ;

ref; // ME_5620F1F50147 aGetState

: ME_5620F1EE033B
 CONST UID '5620F1EE033B'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620F1DF01BF // PublishOp$2
 ;
 : Parameters
   Seq: ( ME_5620F1F500D9 // aControl
 ME_5620F1F50101 // anExecute
 ME_5620F1F50129 // aTest
 ME_5620F1F50147 // aGetState
 )
 ; // Parameters

ref; // ME_5620F1EE033B DoIt

: ME_5620F1DF01BF
 CONST UID '5620F1DF01BF'
 CONST Name 'PublishOp'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'опубликовать операцию' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 ;
 : Operations
   Seq: ( HWL ME_5620F1EE033B // DoIt
 )
 ; // Operations

ref; // ME_5620F1DF01BF PublishOp$2

: ME_478CF34E02CE_ME_5620CFFC0045
 : Original WL 'ME_478CF34E02CE' '4AB0997B00A2.pas.ms.script' // Assign
 ;
 CONST OpKind opkind_Overridden
ref; // ME_478CF34E02CE_ME_5620CFFC0045 Assign

: ME_479731C50290_ME_5620CFFC0045
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_5620CFFC0045 Cleanup

: ME_479F2B3302C1_ME_5620CFFC0045
 : Original WL 'ME_479F2B3302C1' '47913B47006E.pas.ms.script' // BeforeAddToCache
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479F2B3302C1_ME_5620CFFC0045 BeforeAddToCache

: ME_4D555CF50027_ME_5620CFFC0045
 : Original WL 'ME_4D555CF50027' '4AB0997B00A2.pas.ms.script' // Create
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4D555CF50027_ME_5620CFFC0045 Create

: ME_55CCBA3C0190_ME_5620CFFC0045
 : Original WL 'ME_55CCBA3C0190' '4FFC33380166.pas.ms.script' // ChangeName
 ;
 CONST OpKind opkind_Overridden
ref; // ME_55CCBA3C0190_ME_5620CFFC0045 ChangeName

: ME_55CCBA8003C7_ME_5620CFFC0045
 : Original WL 'ME_55CCBA8003C7' '4FFC33380166.pas.ms.script' // ChangeCaption
 ;
 CONST OpKind opkind_Overridden
ref; // ME_55CCBA8003C7_ME_5620CFFC0045 ChangeCaption

: ME_55CCBAAB00F4_ME_5620CFFC0045
 : Original WL 'ME_55CCBAAB00F4' '4FFC33380166.pas.ms.script' // MakeID
 ;
 CONST OpKind opkind_Overridden
ref; // ME_55CCBAAB00F4_ME_5620CFFC0045 MakeID

: ME_55CCBAC800F0_ME_5620CFFC0045
 : Original WL 'ME_55CCBAC800F0' '4FFC33380166.pas.ms.script' // GetID
 ;
 CONST OpKind opkind_Overridden
ref; // ME_55CCBAC800F0_ME_5620CFFC0045 GetID

: ME_561145D802BB_ME_5620CFFC0045
 : Original WL 'ME_561145D802BB' '47913B47006E.pas.ms.script' // QueryInterface
 ;
 CONST OpKind opkind_Overridden
ref; // ME_561145D802BB_ME_5620CFFC0045 QueryInterface

: ME_5620CFFC0045
 CONST UID '5620CFFC0045'
 CONST Name 'TvcmBaseOperationsCollectionItemPrim'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Inherits
   Seq: ( HWL ME_5620D0B90294 // TvcmOperationParams
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_5620CEB201FB // OperationType
 HWL ME_5620CF2802E3 // Options
 HWL ME_5620CF82017C // ContextMenuWeight
 HWL ME_5620CFC10224 // OperationID
 HWL ME_5620D0330150 // AutoLock
 HWL ME_5620D127038B // AutoFocus
 HWL ME_5620D1760396 // LongProcess
 HWL ME_5620D1DE0361 // f_GroupID
 HWL ME_5620D26602B5 // States
 HWL ME_5620D2A101D3 // State
 HWL ME_5620D30100C9 // f_Enabled
 HWL ME_5620D32B0029 // f_VisibleToUser
 HWL ME_5620D36F0377 // f_OpDef
 HWL ME_5620D3AC01C5 // Controls
 HWL ME_5620D3E900E0 // OnGetState
 HWL ME_5620D41E0142 // OnTest
 HWL ME_5620D48C0185 // OnExecute
 HWL ME_5620D51000AB // f_FormGetState
 HWL ME_5620D5350264 // f_FormTest
 HWL ME_5620D55C03E1 // f_FormExecute
 HWL ME_5620D5B80280 // OnContextTest
 HWL ME_5620D625002F // OnContextExecute
 HWL ME_5620D68A0067 // IsCaptionUnique
 HWL ME_5620D6D40299 // SaveShortcut
 HWL ME_5620D71D03D0 // SaveSecondaryShortcuts
 HWL ME_5620D7470392 // IsDefault
 HWL ME_5620E01800F3 // VisibleToUser
 HWL ME_5620E17102F2 // OperationDef
 HWL ME_5620E23201F0 // Category
 HWL ME_5620E28E0284 // GroupID
 HWL ME_5620E402012B // ExcludeUserTypes
 HWL ME_5620E5640206 // CurrentState
 HWL ME_5620E6F00105 // Linked
 HWL ME_5624C3E003C7 // f_Options
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_5620E1270164 // GetDefaultOptions
 HWL ME_5620E2C30048 // GetGroupIDStored
 HWL ME_5620E36701EE // GetOperationTypeStored
 HWL ME_5620E5C101B2 // GetIsDefaultStored
 HWL ME_5620E5FF00DA // OnSecondaryShortCutsChange
 HWL ME_5620E72703A2 // IsHandledToControl
 HWL ME_5620E6910372 // GetLinkedAction
 HWL ME_5620E66E0367 // ControllerCommand
 HWL ME_5620E65A00D3 // ParentID
 HWL ME_5620E643039B // IsLinkedToModule
 HWL ME_5620E6250019 // ResetShortCutHandler
 HWL ME_5620E7B10292 // DoFormGetState
 HWL ME_5620E7CC00CF // DoFormTest
 HWL ME_5620E7E70331 // DoFormExecute
 HWL ME_5620E802035A // FakeControlTest
 HWL ME_5620E8DC016C // ClearOp
 HWL ME_5620E8B900F5 // SetShortCuts
 HWL ME_5620E87503A8 // StatesClass
 HWL ME_5620E8300061 // OwnerUserType
 HWL ME_5620EED40232 // OwnerForm
 HWL ME_5620EF040199 // ReplaceShortCuts$1
 HWL ME_5620EF9D02F1 // ReplaceShortCuts$2
 HWL ME_5620F0050158 // StoreDesignTimeShortcuts
 HWL ME_5620F09B013E // SomePropStored
 HWL ME_5620F16701DD // RemoveShortCut
 HWL ME_5620F28501E2 // UnlinkControl
 HWL ME_5620F2B50162 // Handled
 HWL ME_5620F10C0381 // Operation
 HWL ME_5620F19403B6 // PublishOp$1
 HWL ME_5620F1DF01BF // PublishOp$2
 )
 ; // Operations
 : Overridden
   Seq: ( ME_478CF34E02CE_ME_5620CFFC0045 // Assign
 ME_479731C50290_ME_5620CFFC0045 // Cleanup
 ME_479F2B3302C1_ME_5620CFFC0045 // BeforeAddToCache
 ME_4D555CF50027_ME_5620CFFC0045 // Create
 ME_55CCBA3C0190_ME_5620CFFC0045 // ChangeName
 ME_55CCBA8003C7_ME_5620CFFC0045 // ChangeCaption
 ME_55CCBAAB00F4_ME_5620CFFC0045 // MakeID
 ME_55CCBAC800F0_ME_5620CFFC0045 // GetID
 ME_561145D802BB_ME_5620CFFC0045 // QueryInterface
 )
 ; // Overridden
 CONST extprop:rc:SelfName 'OperationsCollectionItemPrim'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5620CFFC0045 TvcmBaseOperationsCollectionItemPrim

: ME_5624C4B001B0
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_49944BD5012F' '49944A1502FE.pas.ms.script' // vcm_AllOperationOptions
 ;

ref; // ME_5624C4B001B0 

FORWARD ME_560419D10368

: ME_5624C4E503B8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target HWL ME_560419D10368 // TvcmEntitiesCollectionItem
 ;

ref; // ME_5624C4E503B8 

: ME_5624C5170081
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_4A3FAF1F00EC' '4A3FAF1003DA.pas.ms.script' // Command Tables
 ;

ref; // ME_5624C5170081 

: ME_5624C51903B5
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_475415C50224' '4754101B004F.pas.ms.script' // TOvcController
 ;

ref; // ME_5624C51903B5 

: ME_5624C5E8001E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_47E7ABAE0110' '4799D29F033F.pas.ms.script' // Menus
 ;

ref; // ME_5624C5E8001E 

: ME_5624C60E038E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target HWL ME_52A08E6701A1 // TvcmModulesCollectionItem
 ;

ref; // ME_5624C60E038E 

: ME_5624C62602E1
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target HWL ME_4DDBBD1103C3 // TvcmBaseEntitiesCollectionItem
 ;

ref; // ME_5624C62602E1 

: ME_5624C635027A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target HWL ME_52A72EB701C5 // TvcmModuleDef
 ;

ref; // ME_5624C635027A 

: ME_5624C79900D1
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_4A8D789702FA' '4A8D6EF403E4.pas.ms.script' // vcmOVCCommands
 ;

ref; // ME_5624C79900D1 

: ME_5624C7D10052
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_4F82EFD20255' '47E7617C0275.pas.ms.script' // TvcmModuleAction
 ;

ref; // ME_5624C7D10052 

: ME_5624C7E20389
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_4F82EFAB02D4' '47E7617C0275.pas.ms.script' // TvcmEntityAction
 ;

ref; // ME_5624C7E20389 

: ME_5624C86C01EE
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_47752AF90375' '47750CE700D0.pas.ms.script' // afwFacade
 ;

ref; // ME_5624C86C01EE 

: ME_5624C90602F7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_5624C8FA031C' '4678193C009C.pas.ms.script' // Tl3Method
 ;

ref; // ME_5624C90602F7 

FORWARD ME_5624C95902C8

: ME_5624C96A035E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target HWL ME_5624C95902C8 // TvcmActiveControlsCollectionItem
 ;

ref; // ME_5624C96A035E 

: ME_5624C9B2033C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_47E11FC3021E' '4799D29F033F.pas.ms.script' // Controls
 ;

ref; // ME_5624C9B2033C 

: ME_5624C9B50326
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_4767748503B5' '4767743E00E5.pas.ms.script' // TTypeInfo
 ;

ref; // ME_5624C9B50326 

: ME_5624CA0A00A7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_5624C8410121' '47D0E1500033.pas.ms.script' // TvcmBaseOperationDef
 ;

ref; // ME_5624CA0A00A7 

: ME_5624CA0D0101
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_4AA9377803B5' '47D0E1500033.pas.ms.script' // vcmUtils
 ;

ref; // ME_5624CA0D0101 

: ME_5624CA0F038B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_55D3257800A1' '47D0E1500033.pas.ms.script' // vcmRepositoryEx
 ;

ref; // ME_5624CA0F038B 

: ME_5624CA16034F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Target WL 'ME_4AB33E14004E' '47D0E1500033.pas.ms.script' // TvcmModule
 ;

ref; // ME_5624CA16034F 

: ME_4D7A109601C2
 CONST UID '4D7A109601C2'
 CONST Name 'TvcmBaseOperationsCollectionItem'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 )
 ; // Inherits
 : Children
   Seq: ( HWL ME_5620CA450068 // TvcmGetStateEvent
 HWL ME_5620CABB02F5 // TvcmContextTestEvent
 HWL ME_5620CB260263 // TvcmContextExecuteEvent
 HWL ME_5620CB5800A0 // TvcmHandleType
 HWL ME_5620CB7B03DE // TvcmHandleTypes
 HWL ME_5620CFFC0045 // TvcmBaseOperationsCollectionItemPrim
 )
 ; // Children
 : Constants
   Seq: ( HWL ME_5620C9B40399 // vcm_DefaultOperationOptions
 )
 ; // Constants
 : Dependencies
   Seq: ( ME_5624C4B001B0 // vcm_AllOperationOptions
 ME_5624C4E503B8 // TvcmEntitiesCollectionItem
 ME_5624C5170081 // Command Tables
 ME_5624C51903B5 // TOvcController
 ME_5624C5E8001E // Menus
 ME_5624C60E038E // TvcmModulesCollectionItem
 ME_5624C62602E1 // TvcmBaseEntitiesCollectionItem
 ME_5624C635027A // TvcmModuleDef
 ME_5624C79900D1 // vcmOVCCommands
 ME_5624C7D10052 // TvcmModuleAction
 ME_5624C7E20389 // TvcmEntityAction
 ME_5624C86C01EE // afwFacade
 ME_5624C90602F7 // Tl3Method
 ME_5624C96A035E // TvcmActiveControlsCollectionItem
 ME_5624C9B2033C // Controls
 ME_5624C9B50326 // TTypeInfo
 ME_5624CA0A00A7 // TvcmBaseOperationDef
 ME_5624CA0D0101 // vcmUtils
 ME_5624CA0F038B // vcmRepositoryEx
 ME_5624CA16034F // TvcmModule
 )
 ; // Dependencies
 CONST "finished" false
 CONST "need UC" true
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmBaseOperationsCollectionItem.pas'
 CONST extprop:rc:SelfName 'OperationsCollectionItem'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmBaseOperationsCollectionItem'

ref; // ME_4D7A109601C2 TvcmBaseOperationsCollectionItem

: ME_55D33EF20068
 CONST UID '55D33EF20068'
 CONST Name 'TvcmEntitiesCollectionItemEntity'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmEntitiesCollectionItemEntity.pas'
 CONST extprop:rc:SelfName 'EntitiesCollectionItemEntity'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmEntitiesCollectionItemEntity'

ref; // ME_55D33EF20068 TvcmEntitiesCollectionItemEntity

: ME_55D3528A022B
 CONST UID '55D3528A022B'
 CONST Name 'TvcmControlsCollectionItem'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmControlsCollectionItem.pas'
 CONST extprop:rc:SelfName 'ControlsCollectionItem'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmControlsCollectionItem'

ref; // ME_55D3528A022B TvcmControlsCollectionItem

: ME_5603F60C018E
 CONST UID '5603F60C018E'
 CONST Name 'TvcmOperationsCollectionItem'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmOperationsCollectionItem.pas'
 CONST extprop:rc:SelfName 'OperationsCollectionItem'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmOperationsCollectionItem'

ref; // ME_5603F60C018E TvcmOperationsCollectionItem

FORWARD ME_5603F69F0035

: ME_5603F6AF0121
 CONST UID '5603F6AF0121'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_5603F69F0035 // TvcmOperationsCollectionItemList
 ;
 : Target HWL ME_5603F60C018E // TvcmOperationsCollectionItem
 ;

ref; // ME_5603F6AF0121 ItemType

: ME_5603F69F0035
 CONST UID '5603F69F0035'
 CONST Name 'TvcmOperationsCollectionItemList'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.pas.ms.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_47B57B7800A7' '47913B47006E.pas.ms.script' // l3ObjectPtrList
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_5603F6AF0121 // ItemType
 )
 ; // Attributes
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\vcmOperationsCollectionItemList.pas'
 CONST extprop:rc:SelfName 'OperationsCollectionItemList'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmOperationsCollectionItemList'

ref; // ME_5603F69F0035 TvcmOperationsCollectionItemList

: ME_560419D10368
 CONST UID '560419D10368'
 CONST Name 'TvcmEntitiesCollectionItem'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmEntitiesCollectionItem.pas'
 CONST extprop:rc:SelfName 'EntitiesCollectionItem'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmEntitiesCollectionItem'

ref; // ME_560419D10368 TvcmEntitiesCollectionItem

FORWARD ME_56040A5B022E

: ME_56040A8B036C
 CONST UID '56040A8B036C'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_56040A5B022E // TvcmEntitiesCollectionItemList
 ;
 : Target HWL ME_560419D10368 // TvcmEntitiesCollectionItem
 ;

ref; // ME_56040A8B036C ItemType

: ME_56040A5B022E
 CONST UID '56040A5B022E'
 CONST Name 'TvcmEntitiesCollectionItemList'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.pas.ms.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_47B57B7800A7' '47913B47006E.pas.ms.script' // l3ObjectPtrList
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_56040A8B036C // ItemType
 )
 ; // Attributes
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\vcmEntitiesCollectionItemList.pas'
 CONST extprop:rc:SelfName 'EntitiesCollectionItemList'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmEntitiesCollectionItemList'

ref; // ME_56040A5B022E TvcmEntitiesCollectionItemList

: ME_560AC98C026A
 CONST UID '560AC98C026A'
 CONST Name 'TvcmEntities'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmEntities.pas'
 CONST extprop:rc:SelfName 'Entities'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmEntities'

ref; // ME_560AC98C026A TvcmEntities

FORWARD ME_52A72E6B00B1

FORWARD ME_560A9E3700DF

: ME_560A9E48019F
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560A9E48019F anEntity

: ME_560A9E4801BD
 CONST Name 'aGetTarget'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_55D30CC30066 // TvcmGetTargetEvent
 ;

ref; // ME_560A9E4801BD aGetTarget

: ME_560A9E41022F
 CONST UID '560A9E41022F'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560A9E3700DF // PublishFormEntity
 ;
 : Target HWL ME_4DDBBD1103C3 // TvcmBaseEntitiesCollectionItem
 ;
 : Parameters
   Seq: ( ME_560A9E48019F // anEntity
 ME_560A9E4801BD // aGetTarget
 )
 ; // Parameters

ref; // ME_560A9E41022F DoIt

: ME_560A9E3700DF
 CONST UID '560A9E3700DF'
 CONST Name 'PublishFormEntity'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'опубликовать сущность' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560A9E41022F // DoIt
 )
 ; // Operations

ref; // ME_560A9E3700DF PublishFormEntity

FORWARD ME_560A9E5C0285

: ME_560A9E6E00A8
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560A9E6E00A8 anEntity

: ME_560A9E6A00D7
 CONST UID '560A9E6A00D7'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560A9E5C0285 // GroupItemsInContextMenu
 ;
 : Parameters
   Seq: ( ME_560A9E6E00A8 // anEntity
 )
 ; // Parameters

ref; // ME_560A9E6A00D7 DoIt

: ME_560A9E5C0285
 CONST UID '560A9E5C0285'
 CONST Name 'GroupItemsInContextMenu'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560A9E6A00D7 // DoIt
 )
 ; // Operations

ref; // ME_560A9E5C0285 GroupItemsInContextMenu

FORWARD ME_560A9E7F00B4

: ME_560A9E880343
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560A9E880343 anEntity

: ME_560A9E85033D
 CONST UID '560A9E85033D'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560A9E7F00B4 // ToolbarAtBottom
 ;
 : Parameters
   Seq: ( ME_560A9E880343 // anEntity
 )
 ; // Parameters

ref; // ME_560A9E85033D DoIt

: ME_560A9E7F00B4
 CONST UID '560A9E7F00B4'
 CONST Name 'ToolbarAtBottom'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560A9E85033D // DoIt
 )
 ; // Operations

ref; // ME_560A9E7F00B4 ToolbarAtBottom

FORWARD ME_560A9E9E005D

: ME_560A9EAB0053
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560A9EAB0053 anEntity

: ME_560A9EAB0067
 CONST Name 'aWeight'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_560A9EAB0067 aWeight

: ME_560A9EA602A2
 CONST UID '560A9EA602A2'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560A9E9E005D // ContextMenuWeight$1
 ;
 : Parameters
   Seq: ( ME_560A9EAB0053 // anEntity
 ME_560A9EAB0067 // aWeight
 )
 ; // Parameters

ref; // ME_560A9EA602A2 DoIt

: ME_560A9E9E005D
 CONST UID '560A9E9E005D'
 CONST Name 'ContextMenuWeight'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'установить вес сущности в контекстном меню' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560A9EA602A2 // DoIt
 )
 ; // Operations

ref; // ME_560A9E9E005D ContextMenuWeight$1

FORWARD ME_560A9EC5026F

: ME_560A9ED300AB
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560A9ED300AB anEntity

: ME_560A9ED300C9
 CONST Name 'anOperation'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560A9ED300C9 anOperation

: ME_560A9ED300FB
 CONST Name 'aWeight'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_560A9ED300FB aWeight

: ME_560A9ED30141
 CONST Name 'aNoPrefix'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_560A9ED30141 aNoPrefix

: ME_560A9ECC03AD
 CONST UID '560A9ECC03AD'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560A9EC5026F // ContextMenuWeight$2
 ;
 : Parameters
   Seq: ( ME_560A9ED300AB // anEntity
 ME_560A9ED300C9 // anOperation
 ME_560A9ED300FB // aWeight
 ME_560A9ED30141 // aNoPrefix
 )
 ; // Parameters

ref; // ME_560A9ECC03AD DoIt

: ME_560A9EC5026F
 CONST UID '560A9EC5026F'
 CONST Name 'ContextMenuWeight'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'установить вес операции в контекстном меню' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560A9ECC03AD // DoIt
 )
 ; // Operations

ref; // ME_560A9EC5026F ContextMenuWeight$2

FORWARD ME_560A9F53006F

: ME_560A9F640349
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560A9F640349 anEntity

: ME_560A9F640367
 CONST Name 'anOperation'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560A9F640367 anOperation

: ME_560A9F64037B
 CONST Name 'anExecute'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_52A1D97A009E' '47D0E1500033.pas.ms.script' // TvcmExecuteEvent
 ;

ref; // ME_560A9F64037B anExecute

: ME_560A9F6403A3
 CONST Name 'aTest'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47694CD40080' '467BAB7F021E.pas.ms.script' // TvcmControlTestEvent
 ;

ref; // ME_560A9F6403A3 aTest

: ME_560A9F650001
 CONST Name 'aGetState'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_49886B8400D0' '467BAB7F021E.pas.ms.script' // TvcmControlGetStateEvent
 ;

ref; // ME_560A9F650001 aGetState

: ME_560A9F65003F
 CONST Name 'aNoPrefix'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_560A9F65003F aNoPrefix

: ME_560A9F5A0180
 CONST UID '560A9F5A0180'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560A9F53006F // PublishOpWithResult
 ;
 : Parameters
   Seq: ( ME_560A9F640349 // anEntity
 ME_560A9F640367 // anOperation
 ME_560A9F64037B // anExecute
 ME_560A9F6403A3 // aTest
 ME_560A9F650001 // aGetState
 ME_560A9F65003F // aNoPrefix
 )
 ; // Parameters

ref; // ME_560A9F5A0180 DoIt

: ME_560A9F53006F
 CONST UID '560A9F53006F'
 CONST Name 'PublishOpWithResult'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'опубликовать операцию' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560A9F5A0180 // DoIt
 )
 ; // Operations

ref; // ME_560A9F53006F PublishOpWithResult

FORWARD ME_560A9F87021C

: ME_560A9F960087
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560A9F960087 anEntity

: ME_560A9F96009B
 CONST Name 'anOperation'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560A9F96009B anOperation

: ME_560A9F9600AF
 CONST Name 'aNoPrefix'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_560A9F9600AF aNoPrefix

: ME_560A9F8D00B6
 CONST UID '560A9F8D00B6'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560A9F87021C // GetOperationByName
 ;
 : Target HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Parameters
   Seq: ( ME_560A9F960087 // anEntity
 ME_560A9F96009B // anOperation
 ME_560A9F9600AF // aNoPrefix
 )
 ; // Parameters

ref; // ME_560A9F8D00B6 DoIt

: ME_560A9F87021C
 CONST UID '560A9F87021C'
 CONST Name 'GetOperationByName'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560A9F8D00B6 // DoIt
 )
 ; // Operations

ref; // ME_560A9F87021C GetOperationByName

FORWARD ME_560A9FD5004C

: ME_560A9FE301C6
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560A9FE301C6 anEntity

: ME_560A9FE301DA
 CONST Name 'anOperation'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560A9FE301DA anOperation

: ME_560A9FE301EE
 CONST Name 'aValue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_560A9FE301EE aValue

: ME_560A9FE30202
 CONST Name 'aNoPrefix'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_560A9FE30202 aNoPrefix

: ME_560A9FDA03E0
 CONST UID '560A9FDA03E0'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560A9FD5004C // ShowInContextMenu
 ;
 : Parameters
   Seq: ( ME_560A9FE301C6 // anEntity
 ME_560A9FE301DA // anOperation
 ME_560A9FE301EE // aValue
 ME_560A9FE30202 // aNoPrefix
 )
 ; // Parameters

ref; // ME_560A9FDA03E0 DoIt

: ME_560A9FD5004C
 CONST UID '560A9FD5004C'
 CONST Name 'ShowInContextMenu'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560A9FDA03E0 // DoIt
 )
 ; // Operations

ref; // ME_560A9FD5004C ShowInContextMenu

FORWARD ME_560AA00103A8

: ME_560AA0100263
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560AA0100263 anEntity

: ME_560AA0100277
 CONST Name 'anOperation'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560AA0100277 anOperation

: ME_560AA010028B
 CONST Name 'aValue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_560AA010028B aValue

: ME_560AA01002A9
 CONST Name 'aNoPrefix'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_560AA01002A9 aNoPrefix

: ME_560AA0080042
 CONST UID '560AA0080042'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560AA00103A8 // ShowInToolbar
 ;
 : Parameters
   Seq: ( ME_560AA0100263 // anEntity
 ME_560AA0100277 // anOperation
 ME_560AA010028B // aValue
 ME_560AA01002A9 // aNoPrefix
 )
 ; // Parameters

ref; // ME_560AA0080042 DoIt

: ME_560AA00103A8
 CONST UID '560AA00103A8'
 CONST Name 'ShowInToolbar'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560AA0080042 // DoIt
 )
 ; // Operations

ref; // ME_560AA00103A8 ShowInToolbar

FORWARD ME_560AA031026A

: ME_560AA03B0347
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560AA03B0347 anEntity

: ME_560AA03800B4
 CONST UID '560AA03800B4'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560AA031026A // CheckEntityForControl
 ;
 : Target HWL ME_4DDBBD1103C3 // TvcmBaseEntitiesCollectionItem
 ;
 : Parameters
   Seq: ( ME_560AA03B0347 // anEntity
 )
 ; // Parameters

ref; // ME_560AA03800B4 DoIt

: ME_560AA031026A
 CONST UID '560AA031026A'
 CONST Name 'CheckEntityForControl'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560AA03800B4 // DoIt
 )
 ; // Operations

ref; // ME_560AA031026A CheckEntityForControl

FORWARD ME_560AA05F01E7

: ME_560AA06D0277
 CONST Name 'aList'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_559D24E403DE' '47D0E1500033.pas.ms.script' // TvcmEntitiesDefList
 ;

ref; // ME_560AA06D0277 aList

: ME_560AA06A030B
 CONST UID '560AA06A030B'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560AA05F01E7 // GetEntitiesDef
 ;
 : Parameters
   Seq: ( ME_560AA06D0277 // aList
 )
 ; // Parameters

ref; // ME_560AA06A030B DoIt

: ME_560AA05F01E7
 CONST UID '560AA05F01E7'
 CONST Name 'GetEntitiesDef'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'возвращает список описателей сущностей' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560AA06A030B // DoIt
 )
 ; // Operations

ref; // ME_560AA05F01E7 GetEntitiesDef

FORWARD ME_560AA09401E0

: ME_560AA09C0312
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_560AA09C0312 aControl

: ME_560AA09A03A8
 CONST UID '560AA09A03A8'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560AA09401E0 // LinkControl
 ;
 : Parameters
   Seq: ( ME_560AA09C0312 // aControl
 )
 ; // Parameters

ref; // ME_560AA09A03A8 DoIt

: ME_560AA09401E0
 CONST UID '560AA09401E0'
 CONST Name 'LinkControl'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560AA09A03A8 // DoIt
 )
 ; // Operations

ref; // ME_560AA09401E0 LinkControl

: ME_560AA0B60313
 CONST UID '560AA0B60313'
 CONST Name 'UnlinkControl'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Inherits
   Seq: ( HWL ME_560AA09401E0 // LinkControl
 )
 ; // Inherits

ref; // ME_560AA0B60313 UnlinkControl

: ME_560AA0C50016
 CONST UID '560AA0C50016'
 CONST Name 'RegisterInRep'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;

ref; // ME_560AA0C50016 RegisterInRep

FORWARD ME_560AA0E20102

: ME_560AA0EC0206
 CONST Name 'aItem'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4FFC3347011F' '4FFC33380166.pas.ms.script' // TvcmBaseCollectionItem
 ;

ref; // ME_560AA0EC0206 aItem

: ME_560AA0E7038C
 CONST UID '560AA0E7038C'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560AA0E20102 // IsItemCaptionUnique
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_560AA0EC0206 // aItem
 )
 ; // Parameters

ref; // ME_560AA0E7038C DoIt

: ME_560AA0E20102
 CONST UID '560AA0E20102'
 CONST Name 'IsItemCaptionUnique'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY 'поиск операции по названию' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Operations
   Seq: ( HWL ME_560AA0E7038C // DoIt
 )
 ; // Operations

ref; // ME_560AA0E20102 IsItemCaptionUnique

: ME_560AC8C202CB
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Target WL 'ME_476A833902E6' '4683F37902CF.pas.ms.script' // States
 ;

ref; // ME_560AC8C202CB 

: ME_560AC9260166
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Target WL 'ME_4995624100A6' '499EAAE502A8.pas.ms.script' // IvcmOperationDef
 ;

ref; // ME_560AC9260166 

: ME_560AC9940195
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Target HWL ME_560AC98C026A // TvcmEntities
 ;

ref; // ME_560AC9940195 

: ME_560ADC4E0249
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_560ADC4E0249 

: ME_476954790060_ME_52A72E6B00B1
 : Original WL 'ME_476954790060' '467BAB7F021E.pas.ms.script' // PublishEntity
 ;
 CONST OpKind opkind_Implemented
ref; // ME_476954790060_ME_52A72E6B00B1 PublishEntity

: ME_5607EE71032D_ME_52A72E6B00B1
 : Original WL 'ME_5607EE71032D' '4FFC33380166.pas.ms.script' // GetItemClass
 ;
 CONST OpKind opkind_Overridden
 CONST "is static" true
ref; // ME_5607EE71032D_ME_52A72E6B00B1 GetItemClass

: ME_560A9DA80335_ME_52A72E6B00B1
 : Original WL 'ME_560A9DA80335' '4AB0997B00A2.pas.ms.script' // GetAttrCount
 ;
 CONST OpKind opkind_Overridden
ref; // ME_560A9DA80335_ME_52A72E6B00B1 GetAttrCount

: ME_560A9DCD009D_ME_52A72E6B00B1
 : Original WL 'ME_560A9DCD009D' '4AB0997B00A2.pas.ms.script' // GetAttr
 ;
 CONST OpKind opkind_Overridden
ref; // ME_560A9DCD009D_ME_52A72E6B00B1 GetAttr

: ME_560A9DEB0155_ME_52A72E6B00B1
 : Original WL 'ME_560A9DEB0155' '4AB0997B00A2.pas.ms.script' // GetItemAttr
 ;
 CONST OpKind opkind_Overridden
ref; // ME_560A9DEB0155_ME_52A72E6B00B1 GetItemAttr

: ME_52A72E6B00B1
 CONST UID '52A72E6B00B1'
 CONST Name 'TvcmBaseEntitiesCollection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( WL 'ME_4FFC4C800030' '4FFC33380166.pas.ms.script' // TvcmBaseCollection
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_467BABDA0020' '467BAB7F021E.pas.ms.script' // IvcmOperationsPublisher
 )
 ; // Implements
 : Operations
   Seq: ( HWL ME_560A9E3700DF // PublishFormEntity
 HWL ME_560A9E5C0285 // GroupItemsInContextMenu
 HWL ME_560A9E7F00B4 // ToolbarAtBottom
 HWL ME_560A9E9E005D // ContextMenuWeight$1
 HWL ME_560A9EC5026F // ContextMenuWeight$2
 HWL ME_560A9F53006F // PublishOpWithResult
 HWL ME_560A9F87021C // GetOperationByName
 HWL ME_560A9FD5004C // ShowInContextMenu
 HWL ME_560AA00103A8 // ShowInToolbar
 HWL ME_560AA031026A // CheckEntityForControl
 HWL ME_560AA05F01E7 // GetEntitiesDef
 HWL ME_560AA09401E0 // LinkControl
 HWL ME_560AA0B60313 // UnlinkControl
 HWL ME_560AA0C50016 // RegisterInRep
 HWL ME_560AA0E20102 // IsItemCaptionUnique
 )
 ; // Operations
 : Implemented
   Seq: ( ME_476954790060_ME_52A72E6B00B1 // PublishEntity
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_5607EE71032D_ME_52A72E6B00B1 // GetItemClass
 ME_560A9DA80335_ME_52A72E6B00B1 // GetAttrCount
 ME_560A9DCD009D_ME_52A72E6B00B1 // GetAttr
 ME_560A9DEB0155_ME_52A72E6B00B1 // GetItemAttr
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_560AC8C202CB // States
 ME_560AC9260166 // IvcmOperationDef
 ME_560AC9940195 // TvcmEntities
 ME_560ADC4E0249 // SysUtils
 )
 ; // Dependencies
 CONST "need UC" true
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\vcmBaseEntitiesCollection.pas'
 CONST extprop:rc:SelfName 'EntitiesCollection'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmBaseEntitiesCollection'

ref; // ME_52A72E6B00B1 TvcmBaseEntitiesCollection

FORWARD ME_52A1EA2A0184

: ME_5608151A02D6
 CONST UID '5608151A02D6'
 CONST Name 'f_Linked'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_52A1EA2A0184 // TvcmBaseEntities
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5608151A02D6 f_Linked

: ME_560815340395
 CONST UID '560815340395'
 CONST Name 'Entities'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_52A1EA2A0184 // TvcmBaseEntities
 ;
 : Target HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 ;
 CONST "needs field" true
 CONST "needs stored directive" true
 CONST "pm" true

ref; // ME_560815340395 Entities

FORWARD ME_52A1ED12039D

: ME_52A1ED9A0104
 CONST UID '52A1ED9A0104'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A1ED12039D // GetEntitiesCollectionClass
 ;
 : Target WL 'ME_52A1ED79003E' '4FFC33380166.pas.ms.script' // RvcmBaseCollection
 ;

ref; // ME_52A1ED9A0104 DoIt

: ME_52A1ED12039D
 CONST UID '52A1ED12039D'
 CONST Name 'GetEntitiesCollectionClass'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_52A1EA2A0184 // TvcmBaseEntities
 ;
 : Operations
   Seq: ( HWL ME_52A1ED9A0104 // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_52A1ED12039D GetEntitiesCollectionClass

FORWARD ME_560815920320

: ME_5608159E0273
 CONST Name 'aName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_5608159E0273 aName

: ME_5608159C0077
 CONST UID '5608159C0077'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560815920320 // GetItemByName
 ;
 : Target HWL ME_4DDBBD1103C3 // TvcmBaseEntitiesCollectionItem
 ;
 : Parameters
   Seq: ( ME_5608159E0273 // aName
 )
 ; // Parameters

ref; // ME_5608159C0077 DoIt

: ME_560815920320
 CONST UID '560815920320'
 CONST Name 'GetItemByName'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A1EA2A0184 // TvcmBaseEntities
 ;
 : Operations
   Seq: ( HWL ME_5608159C0077 // DoIt
 )
 ; // Operations

ref; // ME_560815920320 GetItemByName

: ME_560815A70133
 CONST UID '560815A70133'
 CONST Name 'LinkControls'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A1EA2A0184 // TvcmBaseEntities
 ;

ref; // ME_560815A70133 LinkControls

: ME_560815B2001B
 CONST UID '560815B2001B'
 CONST Name 'UnlinkControls'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A1EA2A0184 // TvcmBaseEntities
 ;

ref; // ME_560815B2001B UnlinkControls

FORWARD ME_560815BD02F4

: ME_560815C602D6
 CONST Name 'aList'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_559D24E403DE' '47D0E1500033.pas.ms.script' // TvcmEntitiesDefList
 ;

ref; // ME_560815C602D6 aList

: ME_560815C40312
 CONST UID '560815C40312'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560815BD02F4 // GetEntitiesDef
 ;
 : Parameters
   Seq: ( ME_560815C602D6 // aList
 )
 ; // Parameters

ref; // ME_560815C40312 DoIt

: ME_560815BD02F4
 CONST UID '560815BD02F4'
 CONST Name 'GetEntitiesDef'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A1EA2A0184 // TvcmBaseEntities
 ;
 : Operations
   Seq: ( HWL ME_560815C40312 // DoIt
 )
 ; // Operations

ref; // ME_560815BD02F4 GetEntitiesDef

FORWARD ME_560815DA00A6

: ME_560815E70011
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560815E70011 anEntity

: ME_560815E7002F
 CONST Name 'anOperation'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560815E7002F anOperation

: ME_560815E003C7
 CONST UID '560815E003C7'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560815DA00A6 // GetOperationByName
 ;
 : Target HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 ;
 : Parameters
   Seq: ( ME_560815E70011 // anEntity
 ME_560815E7002F // anOperation
 )
 ; // Parameters

ref; // ME_560815E003C7 DoIt

: ME_560815DA00A6
 CONST UID '560815DA00A6'
 CONST Name 'GetOperationByName'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A1EA2A0184 // TvcmBaseEntities
 ;
 : Operations
   Seq: ( HWL ME_560815E003C7 // DoIt
 )
 ; // Operations

ref; // ME_560815DA00A6 GetOperationByName

FORWARD ME_560815F40305

: ME_560815FE016D
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_560815FE016D anEntity

: ME_560815FE01A9
 CONST Name 'anEvent'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_55D30CC30066 // TvcmGetTargetEvent
 ;

ref; // ME_560815FE01A9 anEvent

: ME_560815FB01B3
 CONST UID '560815FB01B3'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_560815F40305 // SetTargetGetter
 ;
 : Parameters
   Seq: ( ME_560815FE016D // anEntity
 ME_560815FE01A9 // anEvent
 )
 ; // Parameters

ref; // ME_560815FB01B3 DoIt

: ME_560815F40305
 CONST UID '560815F40305'
 CONST Name 'SetTargetGetter'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A1EA2A0184 // TvcmBaseEntities
 ;
 : Operations
   Seq: ( HWL ME_560815FB01B3 // DoIt
 )
 ; // Operations

ref; // ME_560815F40305 SetTargetGetter

FORWARD ME_5608160F00E1

: ME_5608161900F5
 CONST Name 'anEntity'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4683CDED0141' '467BAB7F021E.pas.ms.script' // TvcmString
 ;

ref; // ME_5608161900F5 anEntity

: ME_560816190131
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_560816190131 aControl

: ME_5608161500E9
 CONST UID '5608161500E9'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5608160F00E1 // MakeSupportedByControl
 ;
 : Parameters
   Seq: ( ME_5608161900F5 // anEntity
 ME_560816190131 // aControl
 )
 ; // Parameters

ref; // ME_5608161500E9 DoIt

: ME_5608160F00E1
 CONST UID '5608160F00E1'
 CONST Name 'MakeSupportedByControl'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_52A1EA2A0184 // TvcmBaseEntities
 ;
 : Operations
   Seq: ( HWL ME_5608161500E9 // DoIt
 )
 ; // Operations

ref; // ME_5608160F00E1 MakeSupportedByControl

: ME_5608262A01D0
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_52A1EA2A0184 // TvcmBaseEntities
 ;
 : Target WL 'ME_47E13C6B0341' '4799D29F033F.pas.ms.script' // Forms
 ;

ref; // ME_5608262A01D0 

: ME_5608262D021F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_52A1EA2A0184 // TvcmBaseEntities
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_5608262D021F 

: ME_479731C50290_ME_52A1EA2A0184
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_52A1EA2A0184 Cleanup

: ME_47D1602000C6_ME_52A1EA2A0184
 : Original WL 'ME_47D1602000C6' '4AB0997B00A2.pas.ms.script' // Create
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47D1602000C6_ME_52A1EA2A0184 Create

: ME_4F884378016A_ME_52A1EA2A0184
 : Original WL 'ME_4F884378016A' '4AB0997B00A2.pas.ms.script' // Notification
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4F884378016A_ME_52A1EA2A0184 Notification

: ME_52A1EA2A0184
 CONST UID '52A1EA2A0184'
 CONST Name 'TvcmBaseEntities'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Компонент для определения списка сущностей' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( HWL ME_52A1EA6801B0 // TvcmComponent
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_5608151A02D6 // f_Linked
 HWL ME_560815340395 // Entities
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_52A1ED12039D // GetEntitiesCollectionClass
 HWL ME_560815920320 // GetItemByName
 HWL ME_560815A70133 // LinkControls
 HWL ME_560815B2001B // UnlinkControls
 HWL ME_560815BD02F4 // GetEntitiesDef
 HWL ME_560815DA00A6 // GetOperationByName
 HWL ME_560815F40305 // SetTargetGetter
 HWL ME_5608160F00E1 // MakeSupportedByControl
 )
 ; // Operations
 : Overridden
   Seq: ( ME_479731C50290_ME_52A1EA2A0184 // Cleanup
 ME_47D1602000C6_ME_52A1EA2A0184 // Create
 ME_4F884378016A_ME_52A1EA2A0184 // Notification
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_5608262A01D0 // Forms
 ME_5608262D021F // SysUtils
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\vcmBaseEntities.pas'
 CONST extprop:rc:SelfName 'Entities'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmBaseEntities'

ref; // ME_52A1EA2A0184 TvcmBaseEntities

FORWARD ME_4E3012700155

: ME_52A1D70F0135
 CONST UID '52A1D70F0135'
 CONST Name 'TvcmFormActivate'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4E3012700155 // TvcmRepOperationsCollectionItem
 ;
 CONST extprop:rc:SelfName 'FormActivate'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_52A1D70F0135 TvcmFormActivate

: ME_4E3012700155
 CONST UID '4E3012700155'
 CONST Name 'TvcmRepOperationsCollectionItem'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 : Inherits
   Seq: ( HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 )
 ; // Inherits
 : Children
   Seq: ( HWL ME_52A1D70F0135 // TvcmFormActivate
 )
 ; // Children
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmRepOperationsCollectionItem.pas'
 CONST extprop:rc:SelfName 'RepOperationsCollectionItem'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmRepOperationsCollectionItem'

ref; // ME_4E3012700155 TvcmRepOperationsCollectionItem

: ME_5624C95902C8
 CONST UID '5624C95902C8'
 CONST Name 'TvcmActiveControlsCollectionItem'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB34028023E // Components
 ;
 CONST "finished" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmActiveControlsCollectionItem.pas'
 CONST extprop:rc:SelfName 'ActiveControlsCollectionItem'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmActiveControlsCollectionItem'

ref; // ME_5624C95902C8 TvcmActiveControlsCollectionItem

: ME_4AB34028023E
 CONST UID '4AB34028023E'
 CONST Name 'Components'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4790C3B8021E' '4790C3B8021E.pas.ms.script' // VCM
 ;
 : Children
   Seq: ( HWL ME_4AB34044026A // TvcmModulesCollection
 HWL ME_4AB3405E0326 // TvcmRepEntitiesCollection
 HWL ME_4C77C99500F6 // TvcmBaseOperationState
 HWL ME_5620D0B90294 // TvcmOperationParams
 HWL ME_55D30E6601A8 // TvcmBaseOperationsCollection
 HWL ME_4E01E6DF003A // TvcmMessagesCollectionItem
 HWL ME_5620D2420197 // TvcmBaseOperationStates
 HWL ME_51D128930090 // TvcmEntitiesDefIteratorForContextMenu
 HWL ME_51D148890323 // TvcmEntityDefForContextMenu
 HWL ME_51D14918034E // TvcmOperationsDefIteratorForContextMenu
 HWL ME_52A08E6701A1 // TvcmModulesCollectionItem
 HWL ME_52A1EA6801B0 // TvcmComponent
 HWL ME_55D30F7D02AA // TvcmTargetedControlsCollection
 HWL ME_52A1F31601D0 // TvcmStringCollection
 HWL ME_52A1F6C102E8 // TvcmFormsCollection
 HWL ME_52A1F7AE03B2 // TvcmMessagesCollection
 HWL ME_52A5714300FB // TvcmRepEntitiesCollectionItem
 HWL ME_4DDBBD1103C3 // TvcmBaseEntitiesCollectionItem
 HWL ME_52A72EB701C5 // TvcmModuleDef
 HWL ME_52A72F6A0171 // TvcmFormsCollectionItem
 HWL ME_52A824420357 // TvcmMenuItemsCollection
 HWL ME_52AB1CF803B2 // TvcmMenuItemsCollectionItem
 HWL ME_559E5F080019 // TvcmUserFriendlyControlList
 HWL ME_5620D3930294 // TvcmActiveControlsCollection
 HWL ME_4D7A109601C2 // TvcmBaseOperationsCollectionItem
 HWL ME_55D33EF20068 // TvcmEntitiesCollectionItemEntity
 HWL ME_55D3528A022B // TvcmControlsCollectionItem
 HWL ME_5603F60C018E // TvcmOperationsCollectionItem
 HWL ME_5603F69F0035 // TvcmOperationsCollectionItemList
 HWL ME_560419D10368 // TvcmEntitiesCollectionItem
 HWL ME_56040A5B022E // TvcmEntitiesCollectionItemList
 HWL ME_560AC98C026A // TvcmEntities
 HWL ME_52A72E6B00B1 // TvcmBaseEntitiesCollection
 HWL ME_52A1EA2A0184 // TvcmBaseEntities
 HWL ME_4E3012700155 // TvcmRepOperationsCollectionItem
 HWL ME_5624C95902C8 // TvcmActiveControlsCollectionItem
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 WL 'ME_4678193C009C' '4678193C009C.pas.ms.script' // l3Types
 WL 'ME_467BAB7F021E' '467BAB7F021E.pas.ms.script' // vcmExternalInterfaces
 WL 'ME_4683F37902CF' '4683F37902CF.pas.ms.script' // vcmInterfaces
 WL 'ME_474144E20301' '474144E20301.pas.ms.script' // Draw
 WL 'ME_4754101B004F' '4754101B004F.pas.ms.script' // OvcBase
 WL 'ME_4767743E00E5' '4767743E00E5.pas.ms.script' // TypInfo
 WL 'ME_47750CE700D0' '47750CE700D0.pas.ms.script' // afwFacade
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_4799D29F033F' '4799D29F033F.pas.ms.script' // Implementation
 WL 'ME_47D0E1500033' '47D0E1500033.pas.ms.script' // Implementation
 WL 'ME_47E7617C0275' '47E7617C0275.pas.ms.script' // Actions
 WL 'ME_49944A1502FE' '49944A1502FE.pas.ms.script' // vcmInternalConst
 WL 'ME_499EAAE502A8' '499EAAE502A8.pas.ms.script' // vcmUserControls
 WL 'ME_4A3FAF1003DA' '4A3FAF1003DA.pas.ms.script' // OvcCmd
 WL 'ME_4A8D6EF403E4' '4A8D6EF403E4.pas.ms.script' // Containers
 WL 'ME_4AB0997B00A2' '4AB0997B00A2.pas.ms.script' // Common
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_4FFC33380166' '4FFC33380166.pas.ms.script' // Collections
 WL 'ME_5028887002FD' '5028887002FD.pas.ms.script' // Toolbar
 WL 'ME_5028898902A2' '5028898902A2.pas.ms.script' // tb97utils
 WL 'ME_52A0859B00E2' '52A0859B00E2.pas.ms.script' // Buttons
 )
 ; // Depends
 CONST "path prefix" '/implementation/Components'
 CONST intf.pas:PathOnly '\common\components\gui\Garant\VCM\implementation\Components'

ref; // ME_4AB34028023E Components
