// StyleEditorContainer 4ABA142401CA VCMFinalForm Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4ABA142401CA

ME ME_3DBF74BFD9AD
 MEPROP UID '3DBF74BFD9AD'
 MEPROP GUID '27578D68-B109-4681-A8A0-250B1511D051'
 MEPROP Name 'StyleEditorContainer'
 MEPROP OriginalName 'StyleEditorContainer$Def'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_VCMFormDefinition ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Идентификатор формы StyleEditorContainer' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4ABA142401CA // StyleEditorContainer
 ;
 MELIST Implementors
   Seq: ( HWL ME_4ABA142401CA // StyleEditorContainer
 )
 ; // Implementors
 UP extprop:pas:TypeName 'StyleEditorContainerFormDef'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_3DBF74BFD9AD StyleEditorContainer$Def

ME ME_4ABA142401CA
 MEPROP UID '4ABA142401CA'
 MEPROP Name 'StyleEditorContainer'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_VCMFinalForm ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Редактор стилей' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL 'ME_4AA79F72010A' '4AA79F72010A.ms.model.script' // Settings
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4C52B21801B6' '4C52B21801B6.ms.model.script' // PrimStyleEditorContainerOptions
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_3DBF74BFD9AD // StyleEditorContainer$Def
 )
 ; // Implements
 MELIST Children
   Seq: ( HWL ME_3DBF74BFD9AD // StyleEditorContainer$Def
 )
 ; // Children
 UP "NeedsHackRef" true
 UP "ZoneType" 'ManualModal'
 UP "finished dfm" true
 UP "resizeable" false
 UP "restrict form def" 'undefined'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\Settings\Forms\StyleEditorContainer_Form.pas'
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View\Settings\Forms'
 UP extprop:pas:TypeName 'TStyleEditorContainerForm'
 UP extprop:rc:SelfName 'StyleEditorContainerForm'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'StyleEditorContainer_Form'

ENDME // ME_4ABA142401CA StyleEditorContainer
