// TeeMemo 4AC5D3DB0371 GuiControl Class

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4AC5D3DB0371
%%Inner ME_4AC5D3DB0371

FORWARD ME_4AC5D3DB0371

FORWARD ME_54C26D790097

MEREF ME_47D1602000C6_ME_54C26D790097_over
 MELINK Original WL 'ME_47D1602000C6' '478CF30500C1.ms.model.script' // Create
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_47D1602000C6_ME_54C26D790097_over Create

MEREF ME_4829D81D02E5_ME_54C26D790097_G
 MELINK Original WL? 'ME_4829D81D02E5' // TevCustomMemo
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4829D81D02E5_ME_54C26D790097_G TevCustomMemo

%%InheritedBy ME_4829D81D02E5 ME_54C26D790097

ME ME_54C26D790097
 MEPROP UID '54C26D790097'
 MEPROP Name 'TeeCustomMemo'
 MEPROP Class class_Class
 MELINK Stereotype st_GuiControl ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4AC5D3DB0371 // TeeMemo
 ;
 MELIST Inherits
   Seq: ( ME_4829D81D02E5_ME_54C26D790097_G // TevCustomMemo
 )
 ; // Inherits
 MELIST Overridden
   Seq: ( ME_47D1602000C6_ME_54C26D790097_over // Create
 )
 ; // Overridden
 UP "need UC" true
 UP extprop:rc:SelfName 'eeCustomMemo'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_54C26D790097 TeeCustomMemo

MEREF ME_54C27E8C0136_ME_54C27E9C0222_G
 MELINK Original WL 'ME_54C27E8C0136' '47E11FC3021E.ms.model.script' // TBevelKind
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_54C27E8C0136_ME_54C27E9C0222_G TBevelKind

%%InheritedBy ME_54C27E8C0136 ME_54C27E9C0222

ME ME_54C27E9C0222
 MEPROP UID '54C27E9C0222'
 MEPROP Name 'TBevelKind'
 MEPROP Class class_Class
 MELINK Stereotype st_Typedef ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4AC5D3DB0371 // TeeMemo
 ;
 MELIST Inherits
   Seq: ( ME_54C27E8C0136_ME_54C27E9C0222_G // TBevelKind
 )
 ; // Inherits
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_54C27E9C0222 TBevelKind

MEREF ME_54C26D790097_ME_4AC5D3DB0371_G
 MELINK Original HWL ME_54C26D790097 // TeeCustomMemo
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_54C26D790097_ME_4AC5D3DB0371_G TeeCustomMemo

%%InheritedBy ME_54C26D790097 ME_4AC5D3DB0371

ME ME_4AC5D3DB0371
 MEPROP UID '4AC5D3DB0371'
 MEPROP Name 'TeeMemo'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_GuiControl ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4952683C007B' // Editor
 ;
 MELIST Inherits
   Seq: ( ME_54C26D790097_ME_4AC5D3DB0371_G // TeeCustomMemo
 )
 ; // Inherits
 MELIST Children
   Seq: ( HWL ME_54C26D790097 // TeeCustomMemo
 HWL ME_54C27E9C0222 // TBevelKind
 )
 ; // Children
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "need UC" true
 UP intf.pas:Path 'common\components\gui\Garant\Everest_Engine\eeMemo.pas'
 UP extprop:rc:SelfName 'eeMemo'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'eeMemo'

ENDME // ME_4AC5D3DB0371 TeeMemo
