// MainMenuWithBaseSearchSupport 4AC99EBE0106 VCMForm Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4AC99EBE0106

ME ME_4F20127D0261
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4AC99EBE0106 // MainMenuWithBaseSearchSupport
 ;
 MELINK Target WL 'ME_4F2012220355' '4958DD470101.ms.model.script' // TnsMainMenuFormGUIDFactory
 ;

ENDME // ME_4F20127D0261 

ME ME_496B4C41023E_ME_4AC99EBE0106
 MELINK Original WL 'ME_496B4C41023E' '4A9F98B901A5.ms.model.script' // WindowRequired
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_496B4C41023E_ME_4AC99EBE0106 WindowRequired

ME ME_496B4C500246_ME_4AC99EBE0106
 MELINK Original WL 'ME_496B4C500246' '4A9F98B901A5.ms.model.script' // WindowCloseable
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_496B4C500246_ME_4AC99EBE0106 WindowCloseable

ME ME_496B4CA000B6_ME_4AC99EBE0106
 MELINK Original WL 'ME_496B4CA000B6' '4A9F98B901A5.ms.model.script' // CanCloseWindow
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_496B4CA000B6_ME_4AC99EBE0106 CanCloseWindow

ME ME_496B4CD9005F_ME_4AC99EBE0106
 MELINK Original WL 'ME_496B4CD9005F' '4A9F98B901A5.ms.model.script' // IsQueryCard
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_496B4CD9005F_ME_4AC99EBE0106 IsQueryCard

ME ME_496B4CE30132_ME_4AC99EBE0106
 MELINK Original WL 'ME_496B4CE30132' '4A9F98B901A5.ms.model.script' // TreatSuccessSearchAsManualOpen
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_496B4CE30132_ME_4AC99EBE0106 TreatSuccessSearchAsManualOpen

ME ME_496B4CED0306_ME_4AC99EBE0106
 MELINK Original WL 'ME_496B4CED0306' '4A9F98B901A5.ms.model.script' // AutoActivateWindow
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_496B4CED0306_ME_4AC99EBE0106 AutoActivateWindow

ME ME_4ACA17770179_ME_4AC99EBE0106
 MELINK Original WL 'ME_4ACA17770179' '4A9F98B901A5.ms.model.script' // SupportDisabled
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_4ACA17770179_ME_4AC99EBE0106 SupportDisabled

ME ME_4ACA195801CB_ME_4AC99EBE0106
 MELINK Original WL 'ME_4ACA195801CB' '4A9F98B901A5.ms.model.script' // ContainerForBaseSearch
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4ACA195801CB_ME_4AC99EBE0106 ContainerForBaseSearch

ME ME_4AD6EAA3034A_ME_4AC99EBE0106
 MELINK Original WL 'ME_4AD6EAA3034A' '4A9F98B901A5.ms.model.script' // ContextSearcher
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4AD6EAA3034A_ME_4AC99EBE0106 ContextSearcher

ME ME_4F1D607E0027_ME_4AC99EBE0106
 MELINK Original WL 'ME_4F1D607E0027' '4A9F98B901A5.ms.model.script' // NeedSaveActiveClassBeforeSearch
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" false
ENDME // ME_4F1D607E0027_ME_4AC99EBE0106 NeedSaveActiveClassBeforeSearch

ME ME_4F20313F00E3_ME_4AC99EBE0106
 MELINK Original WL 'ME_4F20313F00E3' '4A9F98B901A5.ms.model.script' // IsIt
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_4F20313F00E3_ME_4AC99EBE0106 IsIt

ME ME_49803F5503AA_ME_4AC99EBE0106
 MELINK Original WL 'ME_49803F5503AA' '4AADF9450143.ms.model.script' // DoInit
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_49803F5503AA_ME_4AC99EBE0106 DoInit

ME ME_49807428008C_ME_4AC99EBE0106
 MELINK Original WL 'ME_49807428008C' '4AADF9450143.ms.model.script' // DoLoadState
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_49807428008C_ME_4AC99EBE0106 DoLoadState

ME ME_4B0E845502C1_ME_4AC99EBE0106
 MELINK Original WL 'ME_4B0E845502C1' '47E13C6B0341.ms.model.script' // NeedAutoScroll
 ;
 MEPROP OpKind opkind_Overridden
 UP "ifdef" 'l3HackedVCL'
ENDME // ME_4B0E845502C1_ME_4AC99EBE0106 NeedAutoScroll

ME ME_4EBBC63E032A_ME_4AC99EBE0106
 MELINK Original WL 'ME_4EBBC63E032A' '4AADF9450143.ms.model.script' // CreateFormGUID
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_4EBBC63E032A_ME_4AC99EBE0106 CreateFormGUID

ME ME_57AD7BC3004F_ME_4AC99EBE0106
 MELINK Original WL 'ME_57AD7BC3004F' '4EB7BDAB01D0.ms.model.script' // NeedDropActiveClass
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_57AD7BC3004F_ME_4AC99EBE0106 NeedDropActiveClass

%%ImplementedBy ME_496B4C2700D5 ME_4AC99EBE0106
%%ImplementedBy ME_4EB7BA320128 ME_4AC99EBE0106
%%ImplementedBy ME_4EB7BDAB01D0 ME_4AC99EBE0106
%%ImplementedBy ME_4F203112036A ME_4AC99EBE0106

%%InheritedBy ME_4958DD7002B6 ME_4AC99EBE0106

ME ME_4AC99EBE0106
 MEPROP UID '4AC99EBE0106'
 MEPROP Name 'MainMenuWithBaseSearchSupport'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_VCMForm ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Основное меню с поддержкой базового поиска' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent WL 'ME_4958DD470101' '4958DD470101.ms.model.script' // MainMenu
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4958DD7002B6' '4958DD7002B6.ms.model.script' // PrimMainMenu
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_496B4C2700D5' '4A9F98B901A5.ms.model.script' // InsBaseSearchPresentation
 WL 'ME_4EB7BA320128' '484FA67302D7.ms.model.script' // Данный выбор не запоминается, когда мы сами инициируем вызов "Основного Меню"
 WL 'ME_4EB7BDAB01D0' '4EB7BDAB01D0.ms.model.script' // BaseSearchPresentationFor296635421
 WL 'ME_4F203112036A' '4A9F98B901A5.ms.model.script' // InsMainMenuLikeBaseSearchOwner
 )
 ; // Implements
 MELIST Implemented
   Seq: ( ME_496B4C41023E_ME_4AC99EBE0106 // WindowRequired
 ME_496B4C500246_ME_4AC99EBE0106 // WindowCloseable
 ME_496B4CA000B6_ME_4AC99EBE0106 // CanCloseWindow
 ME_496B4CD9005F_ME_4AC99EBE0106 // IsQueryCard
 ME_496B4CE30132_ME_4AC99EBE0106 // TreatSuccessSearchAsManualOpen
 ME_496B4CED0306_ME_4AC99EBE0106 // AutoActivateWindow
 ME_4ACA17770179_ME_4AC99EBE0106 // SupportDisabled
 ME_4ACA195801CB_ME_4AC99EBE0106 // ContainerForBaseSearch
 ME_4AD6EAA3034A_ME_4AC99EBE0106 // ContextSearcher
 ME_4F1D607E0027_ME_4AC99EBE0106 // NeedSaveActiveClassBeforeSearch
 ME_4F20313F00E3_ME_4AC99EBE0106 // IsIt
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_49803F5503AA_ME_4AC99EBE0106 // DoInit
 ME_49807428008C_ME_4AC99EBE0106 // DoLoadState
 ME_4B0E845502C1_ME_4AC99EBE0106 // NeedAutoScroll
 ME_4EBBC63E032A_ME_4AC99EBE0106 // CreateFormGUID
 ME_57AD7BC3004F_ME_4AC99EBE0106 // NeedDropActiveClass
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_4F20127D0261 // TnsMainMenuFormGUIDFactory
 )
 ; // Dependencies
 UP "NeedsHackRef" true
 UP "ZoneType" 'Any'
 UP "author" 'Люлин А.В.'
 UP "finished dfm" true
 UP "no hands" true
 UP "resizeable" false
 UP "restrict form def" 'undefined'
 UP "started" '05.10.2009 11:23'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\MainMenu\Forms\MainMenuWithBaseSearchSupport_Form.pas'
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View\MainMenu\Forms'
 UP extprop:pas:TypeName 'TMainMenuWithBaseSearchSupportForm'
 UP extprop:rc:SelfName 'MainMenuWithBaseSearchSupportForm'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'MainMenuWithBaseSearchSupport_Form'

ENDME // ME_4AC99EBE0106 MainMenuWithBaseSearchSupport
