// MainMenuWithBaseSearchSupport 4AC99EBE0106 VCMForm Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4AC99EBE0106

: ME_4F20127D0261
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4AC99EBE0106 // MainMenuWithBaseSearchSupport
 ;
 : Target WL 'ME_4F2012220355' '4958DD470101.pas.ms.script' // TnsMainMenuFormGUIDFactory
 ;

ref; // ME_4F20127D0261 

: ME_496B4C41023E_ME_4AC99EBE0106
 : Original WL 'ME_496B4C41023E' '4A9F98B901A5.pas.ms.script' // WindowRequired
 ;
 CONST OpKind opkind_Implemented
ref; // ME_496B4C41023E_ME_4AC99EBE0106 WindowRequired

: ME_496B4C500246_ME_4AC99EBE0106
 : Original WL 'ME_496B4C500246' '4A9F98B901A5.pas.ms.script' // WindowCloseable
 ;
 CONST OpKind opkind_Implemented
ref; // ME_496B4C500246_ME_4AC99EBE0106 WindowCloseable

: ME_496B4CA000B6_ME_4AC99EBE0106
 : Original WL 'ME_496B4CA000B6' '4A9F98B901A5.pas.ms.script' // CanCloseWindow
 ;
 CONST OpKind opkind_Implemented
ref; // ME_496B4CA000B6_ME_4AC99EBE0106 CanCloseWindow

: ME_496B4CD9005F_ME_4AC99EBE0106
 : Original WL 'ME_496B4CD9005F' '4A9F98B901A5.pas.ms.script' // IsQueryCard
 ;
 CONST OpKind opkind_Implemented
ref; // ME_496B4CD9005F_ME_4AC99EBE0106 IsQueryCard

: ME_496B4CE30132_ME_4AC99EBE0106
 : Original WL 'ME_496B4CE30132' '4A9F98B901A5.pas.ms.script' // TreatSuccessSearchAsManualOpen
 ;
 CONST OpKind opkind_Implemented
ref; // ME_496B4CE30132_ME_4AC99EBE0106 TreatSuccessSearchAsManualOpen

: ME_496B4CED0306_ME_4AC99EBE0106
 : Original WL 'ME_496B4CED0306' '4A9F98B901A5.pas.ms.script' // AutoActivateWindow
 ;
 CONST OpKind opkind_Implemented
ref; // ME_496B4CED0306_ME_4AC99EBE0106 AutoActivateWindow

: ME_4ACA17770179_ME_4AC99EBE0106
 : Original WL 'ME_4ACA17770179' '4A9F98B901A5.pas.ms.script' // SupportDisabled
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4ACA17770179_ME_4AC99EBE0106 SupportDisabled

: ME_4ACA195801CB_ME_4AC99EBE0106
 : Original WL 'ME_4ACA195801CB' '4A9F98B901A5.pas.ms.script' // ContainerForBaseSearch
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4ACA195801CB_ME_4AC99EBE0106 ContainerForBaseSearch

: ME_4AD6EAA3034A_ME_4AC99EBE0106
 : Original WL 'ME_4AD6EAA3034A' '4A9F98B901A5.pas.ms.script' // ContextSearcher
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4AD6EAA3034A_ME_4AC99EBE0106 ContextSearcher

: ME_4F1D607E0027_ME_4AC99EBE0106
 : Original WL 'ME_4F1D607E0027' '4A9F98B901A5.pas.ms.script' // NeedSaveActiveClassBeforeSearch
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_4F1D607E0027_ME_4AC99EBE0106 NeedSaveActiveClassBeforeSearch

: ME_4F20313F00E3_ME_4AC99EBE0106
 : Original WL 'ME_4F20313F00E3' '4A9F98B901A5.pas.ms.script' // IsIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F20313F00E3_ME_4AC99EBE0106 IsIt

: ME_49803F5503AA_ME_4AC99EBE0106
 : Original WL 'ME_49803F5503AA' '4AADF9450143.pas.ms.script' // DoInit
 ;
 CONST OpKind opkind_Overridden
ref; // ME_49803F5503AA_ME_4AC99EBE0106 DoInit

: ME_4B0E845502C1_ME_4AC99EBE0106
 : Original WL 'ME_4B0E845502C1' '4799D29F033F.pas.ms.script' // NeedAutoScroll
 ;
 CONST OpKind opkind_Overridden
 CONST "ifdef" 'l3HackedVCL'
ref; // ME_4B0E845502C1_ME_4AC99EBE0106 NeedAutoScroll

: ME_4EBBC63E032A_ME_4AC99EBE0106
 : Original WL 'ME_4EBBC63E032A' '4AADF9450143.pas.ms.script' // CreateFormGUID
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4EBBC63E032A_ME_4AC99EBE0106 CreateFormGUID

: ME_4AC99EBE0106
 CONST UID '4AC99EBE0106'
 CONST Name 'MainMenuWithBaseSearchSupport'
 CONST Class class_Class
 : Stereotype st_VCMForm ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Основное меню с поддержкой базового поиска' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent WL 'ME_4958DD470101' '4958DD470101.pas.ms.script' // MainMenu
 ;
 : Inherits
   Seq: ( WL 'ME_4958DD7002B6' '4958DD7002B6.pas.ms.script' // PrimMainMenu
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_496B4C2700D5' '4A9F98B901A5.pas.ms.script' // InsBaseSearchPresentation
 WL 'ME_4EB7BA320128' '484FA67302D7.pas.ms.script' // Данный выбор не запоминается, когда мы сами инициируем вызов "Основного Меню"
 WL 'ME_4EB7BDAB01D0' '4EB7BDAB01D0.pas.ms.script' // BaseSearchPresentationFor296635421
 WL 'ME_4F203112036A' '4A9F98B901A5.pas.ms.script' // InsMainMenuLikeBaseSearchOwner
 )
 ; // Implements
 : Implemented
   Seq: ( ME_496B4C41023E_ME_4AC99EBE0106 // WindowRequired
 ME_496B4C500246_ME_4AC99EBE0106 // WindowCloseable
 ME_496B4CA000B6_ME_4AC99EBE0106 // CanCloseWindow
 ME_496B4CD9005F_ME_4AC99EBE0106 // IsQueryCard
 ME_496B4CE30132_ME_4AC99EBE0106 // TreatSuccessSearchAsManualOpen
 ME_496B4CED0306_ME_4AC99EBE0106 // AutoActivateWindow
 ME_4ACA17770179_ME_4AC99EBE0106 // SupportDisabled
 ME_4ACA195801CB_ME_4AC99EBE0106 // ContainerForBaseSearch
 ME_4AD6EAA3034A_ME_4AC99EBE0106 // ContextSearcher
 ME_4F1D607E0027_ME_4AC99EBE0106 // NeedSaveActiveClassBeforeSearch
 ME_4F20313F00E3_ME_4AC99EBE0106 // IsIt
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_49803F5503AA_ME_4AC99EBE0106 // DoInit
 ME_4B0E845502C1_ME_4AC99EBE0106 // NeedAutoScroll
 ME_4EBBC63E032A_ME_4AC99EBE0106 // CreateFormGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_4F20127D0261 // TnsMainMenuFormGUIDFactory
 )
 ; // Dependencies
 CONST "NeedsHackRef" true
 CONST "ZoneType" 'Any'
 CONST "author" 'Люлин А.В.'
 CONST "finished dfm" true
 CONST "no hands" true
 CONST "resizeable" false
 CONST "restrict form def" 'undefined'
 CONST "started" '05.10.2009 11:23'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\MainMenu\Forms\MainMenuWithBaseSearchSupport_Form.pas'
 CONST intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View\MainMenu\Forms'
 CONST extprop:pas:TypeName 'TMainMenuWithBaseSearchSupportForm'
 CONST extprop:rc:SelfName 'MainMenuWithBaseSearchSupportForm'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'MainMenuWithBaseSearchSupport_Form'

ref; // ME_4AC99EBE0106 MainMenuWithBaseSearchSupport
