// nscInterfaces 4AC9AFCE00DC Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4AC9AFCE00DC

: ME_4AC9AFDC013C
 CONST UID '4AC9AFDC013C'
 CONST GUID 'CF244F53-75D1-4817-816B-B9E5E9E51FD0'
 CONST Name 'InscArrangeGrid'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4AC9AFCE00DC // nscInterfaces
 ;
 CONST extprop:rc:SelfName 'ArrangeGrid'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4AC9AFDC013C InscArrangeGrid

: ME_4AC9CB3003B4
 CONST UID '4AC9CB3003B4'
 CONST GUID '511A2195-53E3-4933-8061-D46C12DF9B13'
 CONST Name 'InscTabTable'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4AC9AFCE00DC // nscInterfaces
 ;
 CONST extprop:rc:SelfName 'TabTable'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4AC9CB3003B4 InscTabTable

: ME_4AC9AFCE00DC
 CONST UID '4AC9AFCE00DC'
 CONST Name 'nscInterfaces'
 CONST Class class_Category
 : Stereotype st_Interfaces ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_490838AA02D0' '490838AA02D0.pas.ms.script' // Nemesis
 ;
 : Children
   Seq: ( ME_4AC9AFDC013C // InscArrangeGrid
 ME_4AC9CB3003B4 // InscTabTable
 )
 ; // Children
 CONST "UseNewGen" true
 CONST "finished" false
 CONST "is namespace" true
 CONST "no hands" false
 CONST intf.pas:Path 'common\components\gui\Garant\Nemesis\NOT_FINISHED_nscInterfaces.pas'

ref; // ME_4AC9AFCE00DC nscInterfaces
