// Environment 4B2A4FFC0126 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4B2A4FFC0126

FORWARD ME_4B2A50570311

FORWARD ME_4B2A50640392

: ME_4B2A507E003B
 CONST UID '4B2A507E003B'
 CONST Name 'cNSRCFileIn'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4B2A50640392 // Constants
 ;
 CONST Value '''document.nsr'''
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '''document.nsr'''

ref; // ME_4B2A507E003B cNSRCFileIn

: ME_4B337C4801AD
 CONST UID '4B337C4801AD'
 CONST Name 'cBadTextUnicode'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4B2A50640392 // Constants
 ;
 CONST Value '''badtext.uni'''
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '''badtext.uni'''

ref; // ME_4B337C4801AD cBadTextUnicode

: ME_4B2A50640392
 CONST UID '4B2A50640392'
 CONST Name 'Constants'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4B2A50570311 // TestGlobals
 ;
 : Attributes
   Seq: ( ME_4B2A507E003B // cNSRCFileIn
 ME_4B337C4801AD // cBadTextUnicode
 )
 ; // Attributes
 CONST "spell names" false
 CONST dfm:PathOnly '\common\components\rtl\Garant\Daily'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\Daily'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_4B2A50640392 Constants

: ME_4B2A50570311
 CONST UID '4B2A50570311'
 CONST Name 'TestGlobals'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4B2A4FFC0126 // Environment
 ;
 : Constants
   Seq: ( ME_4B2A50640392 // Constants
 )
 ; // Constants
 CONST "no hands" false
 CONST dfm:PathOnly '\common\components\rtl\Garant\Daily'
 CONST intf.pas:Path 'common\components\rtl\Garant\Daily\TestGlobals.pas'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\Daily'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_4B2A50570311 TestGlobals

: ME_4B2A4FFC0126
 CONST UID '4B2A4FFC0126'
 CONST Name 'Environment'
 CONST Class class_Category
 : Stereotype st_Unit ;
 %SUMMARY 'Настройки тестов' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4B2A15810261' '4B2A15810261.pas.ms.script' // DailyTest
 ;
 : Children
   Seq: ( ME_4B2A50570311 // TestGlobals
 )
 ; // Children
 CONST dfm:PathOnly '\common\components\rtl\Garant\Daily'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\Daily'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\4B2A4FFC0126.pas.ms.script'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\4B2A4FFC0126.pas.ms.script.runner'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_4B2A4FFC0126 Environment
