// nsAppConfigRes 4B97B148028B UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4B97B148028B
%%Inner ME_4B97B148028B
%%Inner ME_4B97B148028B
%%Inner ME_4B97B148028B
%%Inner ME_4B97B148028B
%%Inner ME_4B97B148028B
%%Inner ME_4B97B148028B
%%Inner ME_4B97B148028B
%%Inner ME_4B97B148028B

FORWARD ME_4B97B148028B

FORWARD ME_4B97B1890142

ME ME_4B97B1B60281
 MEPROP UID '4B97B1B60281'
 MEPROP Name 'AnyPathWord'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4B97B1890142 // WordPositionNames
 ;
 MEPROP Value '''В любой части слова'''
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '''В любой части слова'''

ENDME // ME_4B97B1B60281 AnyPathWord

ME ME_4B97B1C001E1
 MEPROP UID '4B97B1C001E1'
 MEPROP Name 'AtBeginWord'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4B97B1890142 // WordPositionNames
 ;
 MEPROP Value '''С начала слова'''
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '''С начала слова'''

ENDME // ME_4B97B1C001E1 AtBeginWord

ME ME_4B97B1C90337
 MEPROP UID '4B97B1C90337'
 MEPROP Name 'AtBeginString'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4B97B1890142 // WordPositionNames
 ;
 MEPROP Value '''С начала строки'''
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '''С начала строки'''

ENDME // ME_4B97B1C90337 AtBeginString

MEREF ME_46A61BCB033D_ME_4B97B1890142_G
 MELINK Original WL 'ME_46A61BCB033D' '4677FBA70343.ms.model.script' // Tl3WordPosition
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_46A61BCB033D_ME_4B97B1890142_G Tl3WordPosition

%%InheritedBy ME_46A61BCB033D ME_4B97B1890142

ME ME_4B97B1890142
 MEPROP UID '4B97B1890142'
 MEPROP Name 'WordPositionNames'
 MEPROP Class class_Const
 MELINK Stereotype st_LocalConst ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Inherits
   Seq: ( ME_46A61BCB033D_ME_4B97B1890142_G // Tl3WordPosition
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_4B97B1B60281 // AnyPathWord
 HWL ME_4B97B1C001E1 // AtBeginWord
 HWL ME_4B97B1C90337 // AtBeginString
 )
 ; // Attributes
 UP "Need map interface" true
 UP "Need mapping support" false
 UP "children prefix" 'nsc_wp'
 UP "spell names" false
 UP extprop:pas:ElementPrefix 'nsc_wp'

ENDME // ME_4B97B1890142 WordPositionNames

FORWARD ME_4B97CF0C00D4

ME ME_4B97CF5D0164
 MEPROP UID '4B97CF5D0164'
 MEPROP Name 'AllLevels'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4B97CF0C00D4 // TreeLevelDistNames
 ;
 MEPROP Value '''Во всех уровнях'''
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '''Во всех уровнях'''

ENDME // ME_4B97CF5D0164 AllLevels

ME ME_4B97CF660076
 MEPROP UID '4B97CF660076'
 MEPROP Name 'OneLevel'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4B97CF0C00D4 // TreeLevelDistNames
 ;
 MEPROP Value '''В пределах одного уровня'''
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '''В пределах одного уровня'''

ENDME // ME_4B97CF660076 OneLevel

MEREF ME_46A61C8B002B_ME_4B97CF0C00D4_G
 MELINK Original WL 'ME_46A61C8B002B' '4677FBA70343.ms.model.script' // Tl3TreeLevelDist
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_46A61C8B002B_ME_4B97CF0C00D4_G Tl3TreeLevelDist

%%InheritedBy ME_46A61C8B002B ME_4B97CF0C00D4

ME ME_4B97CF0C00D4
 MEPROP UID '4B97CF0C00D4'
 MEPROP Name 'TreeLevelDistNames'
 MEPROP Class class_Const
 MELINK Stereotype st_LocalConst ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Inherits
   Seq: ( ME_46A61C8B002B_ME_4B97CF0C00D4_G // Tl3TreeLevelDist
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_4B97CF5D0164 // AllLevels
 HWL ME_4B97CF660076 // OneLevel
 )
 ; // Attributes
 UP "Need map interface" true
 UP "Need mapping support" false
 UP "children prefix" 'nsc_tld'
 UP "spell names" false
 UP extprop:pas:ElementPrefix 'nsc_tld'

ENDME // ME_4B97CF0C00D4 TreeLevelDistNames

FORWARD ME_4B97D3D303BE

ME ME_4B97D4210322
 MEPROP UID '4B97D4210322'
 MEPROP Name 'AnyOrder'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4B97D3D303BE // WordOrderNames
 ;
 MEPROP Value '''В любом порядке'''
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '''В любом порядке'''

ENDME // ME_4B97D4210322 AnyOrder

ME ME_4B97D42E01FD
 MEPROP UID '4B97D42E01FD'
 MEPROP Name 'AsWrote'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4B97D3D303BE // WordOrderNames
 ;
 MEPROP Value '''С учетом порядка'''
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '''С учетом порядка'''

ENDME // ME_4B97D42E01FD AsWrote

MEREF ME_46A61C340026_ME_4B97D3D303BE_G
 MELINK Original WL 'ME_46A61C340026' '4677FBA70343.ms.model.script' // Tl3WordOrder
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_46A61C340026_ME_4B97D3D303BE_G Tl3WordOrder

%%InheritedBy ME_46A61C340026 ME_4B97D3D303BE

ME ME_4B97D3D303BE
 MEPROP UID '4B97D3D303BE'
 MEPROP Name 'WordOrderNames'
 MEPROP Class class_Const
 MELINK Stereotype st_LocalConst ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Inherits
   Seq: ( ME_46A61C340026_ME_4B97D3D303BE_G // Tl3WordOrder
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_4B97D4210322 // AnyOrder
 HWL ME_4B97D42E01FD // AsWrote
 )
 ; // Attributes
 UP "Need map interface" true
 UP "Need mapping support" false
 UP "children prefix" 'nsc_wo'
 UP "spell names" false
 UP extprop:pas:ElementPrefix 'nsc_wo'

ENDME // ME_4B97D3D303BE WordOrderNames

FORWARD ME_4B97D7D60086

ME ME_4B97D8050285
 MEPROP UID '4B97D8050285'
 MEPROP Name 'TreeLevelDistHint'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4B97D7D60086 // ContextParamsMessages
 ;
 MEPROP Value '''Находятся ли искомые слова на разных уровнях иерархического дерева или в пределах одного уровня'''
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '''Находятся ли искомые слова на разных уровнях иерархического дерева или в пределах одного уровня'''

ENDME // ME_4B97D8050285 TreeLevelDistHint

ME ME_4B97D82103B8
 MEPROP UID '4B97D82103B8'
 MEPROP Name 'WordOrderHint'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4B97D7D60086 // ContextParamsMessages
 ;
 MEPROP Value '''Должны ли слова строго следовать друг за другом или нет'''
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '''Должны ли слова строго следовать друг за другом или нет'''

ENDME // ME_4B97D82103B8 WordOrderHint

ME ME_4B97D84C0144
 MEPROP UID '4B97D84C0144'
 MEPROP Name 'WordPositionHint'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4B97D7D60086 // ContextParamsMessages
 ;
 MEPROP Value '''Положение контекста в слове, строке'''
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '''Положение контекста в слове, строке'''

ENDME // ME_4B97D84C0144 WordPositionHint

ME ME_4B97D7D60086
 MEPROP UID '4B97D7D60086'
 MEPROP Name 'ContextParamsMessages'
 MEPROP Class class_Const
 MELINK Stereotype st_LocalConst ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Attributes
   Seq: ( HWL ME_4B97D8050285 // TreeLevelDistHint
 HWL ME_4B97D82103B8 // WordOrderHint
 HWL ME_4B97D84C0144 // WordPositionHint
 )
 ; // Attributes
 UP "Need map interface" false
 UP "Need mapping support" false
 UP "children prefix" 'nsc_cpm'
 UP "spell names" false
 UP extprop:pas:ElementPrefix 'nsc_cpm'

ENDME // ME_4B97D7D60086 ContextParamsMessages

FORWARD ME_3905605C6778

ME ME_EB2093C3AD36
 MEPROP UID 'EB2093C3AD36'
 MEPROP Name 'AnyPathWord'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '''В любой части слова''' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_3905605C6778 // LCImplWordPositionNames
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''nsc_wpAnyPathWord''; rValue : ''В любой части слова'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''nsc_wpAnyPathWord''; rValue : ''В любой части слова'')'
 UPLINK Speller HWL ME_4B97B1B60281 // AnyPathWord
 ;

ENDME // ME_EB2093C3AD36 AnyPathWord

ME ME_54BC1E3E1F88
 MEPROP UID '54BC1E3E1F88'
 MEPROP Name 'AtBeginWord'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '''С начала слова''' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_3905605C6778 // LCImplWordPositionNames
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''nsc_wpAtBeginWord''; rValue : ''С начала слова'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''nsc_wpAtBeginWord''; rValue : ''С начала слова'')'
 UPLINK Speller HWL ME_4B97B1C001E1 // AtBeginWord
 ;

ENDME // ME_54BC1E3E1F88 AtBeginWord

ME ME_A00B490D6100
 MEPROP UID 'A00B490D6100'
 MEPROP Name 'AtBeginString'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '''С начала строки''' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_3905605C6778 // LCImplWordPositionNames
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''nsc_wpAtBeginString''; rValue : ''С начала строки'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''nsc_wpAtBeginString''; rValue : ''С начала строки'')'
 UPLINK Speller HWL ME_4B97B1C90337 // AtBeginString
 ;

ENDME // ME_A00B490D6100 AtBeginString

ME ME_3905605C6778
 MEPROP UID '3905605C6778'
 MEPROP Name 'LCImplWordPositionNames'
 UP IsSummoned true
 MEPROP Class class_Const
 MELINK Stereotype st_Constants ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Локализуемые строки WordPositionNames' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Attributes
   Seq: ( HWL ME_EB2093C3AD36 // AnyPathWord
 HWL ME_54BC1E3E1F88 // AtBeginWord
 HWL ME_A00B490D6100 // AtBeginString
 )
 ; // Attributes
 UP "children prefix" 'nsc_wp'
 UP "elements prefix" 'str'
 UP "spell names" false
 UP extprop:pas:ElementPrefixBase 'str'
 UP extprop:pas:ElementPrefix 'str_nsc_wp'
 UPLINK Speller HWL ME_4B97B1890142 // WordPositionNames
 ;

ENDME // ME_3905605C6778 LCImplWordPositionNames

FORWARD ME_7B428F54A9B3

ME ME_5CEAD74715D8
 MEPROP UID '5CEAD74715D8'
 MEPROP Name 'AnyPathWord'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_7B428F54A9B3 // WordPositionNamesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'AnyPathWord'
 MELINK ValueType HWL ME_3905605C6778 // LCImplWordPositionNames
 ;
 UP extprop:pas:Value 'str_nsc_wpAnyPathWord'

ENDME // ME_5CEAD74715D8 AnyPathWord

ME ME_D441997F9E63
 MEPROP UID 'D441997F9E63'
 MEPROP Name 'AtBeginWord'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_7B428F54A9B3 // WordPositionNamesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'AtBeginWord'
 MELINK ValueType HWL ME_3905605C6778 // LCImplWordPositionNames
 ;
 UP extprop:pas:Value 'str_nsc_wpAtBeginWord'

ENDME // ME_D441997F9E63 AtBeginWord

ME ME_42D09A26516A
 MEPROP UID '42D09A26516A'
 MEPROP Name 'AtBeginString'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_7B428F54A9B3 // WordPositionNamesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'AtBeginString'
 MELINK ValueType HWL ME_3905605C6778 // LCImplWordPositionNames
 ;
 UP extprop:pas:Value 'str_nsc_wpAtBeginString'

ENDME // ME_42D09A26516A AtBeginString

MEREF ME_4B3B49B40262_ME_7B428F54A9B3_G
 MELINK Original WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4B3B49B40262_ME_7B428F54A9B3_G Pl3StringIDEx

MEREF ME_46A61BCB033D_ME_7B428F54A9B3_R
 MELINK Original WL 'ME_46A61BCB033D' '4677FBA70343.ms.model.script' // Tl3WordPosition
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_46A61BCB033D_ME_7B428F54A9B3_R Tl3WordPosition

%%ImplementedBy ME_46A61BCB033D ME_7B428F54A9B3

%%InheritedBy ME_4B3B49B40262 ME_7B428F54A9B3

ME ME_7B428F54A9B3
 MEPROP UID '7B428F54A9B3'
 MEPROP Name 'WordPositionNamesMap'
 UP IsSummoned true
 MEPROP Class class_Const
 MELINK Stereotype st_ConstantArray ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Карта преобразования локализованных строк WordPositionNames' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Inherits
   Seq: ( ME_4B3B49B40262_ME_7B428F54A9B3_G // Pl3StringIDEx
 )
 ; // Inherits
 MELIST Implements
   Seq: ( ME_46A61BCB033D_ME_7B428F54A9B3_R // Tl3WordPosition
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_5CEAD74715D8 // AnyPathWord
 HWL ME_D441997F9E63 // AtBeginWord
 HWL ME_42D09A26516A // AtBeginString
 )
 ; // Attributes
 UP "Need map interface" true
 UP "Need mapping support" false

ENDME // ME_7B428F54A9B3 WordPositionNamesMap

FORWARD ME_54A4B8A0B9D2

ME ME_461D5314CE38
 MEPROP Name 'aStrings'
 UP IsSummoned true
 MEPROP Class class_Parameter
 MELINK Target WL 'ME_4683CEE9034C' '467823B7002C.ms.model.script' // IafwStrings
 ;

ENDME // ME_461D5314CE38 aStrings

ME ME_C2DB53EB6783
 MEPROP UID 'C2DB53EB6783'
 MEPROP Name 'FillStrings'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 %SUMMARY 'Заполнение списка строк значениями' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54A4B8A0B9D2 // WordPositionNamesMapHelper
 ;
 MELIST Parameters
   Seq: ( ME_461D5314CE38 // aStrings
 )
 ; // Parameters

ENDME // ME_C2DB53EB6783 FillStrings

ME ME_B1178C20DC43
 MEPROP Name 'aDisplayName'
 UP IsSummoned true
 MEPROP Class class_Parameter
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_B1178C20DC43 aDisplayName

ME ME_AF278AD4DE32
 MEPROP UID 'AF278AD4DE32'
 MEPROP Name 'DisplayNameToValue'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 %SUMMARY 'Преобразование строкового значения к порядковому' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54A4B8A0B9D2 // WordPositionNamesMapHelper
 ;
 MELINK Target WL 'ME_46A61BCB033D' '4677FBA70343.ms.model.script' // Tl3WordPosition
 ;
 MELIST Parameters
   Seq: ( ME_B1178C20DC43 // aDisplayName
 )
 ; // Parameters

ENDME // ME_AF278AD4DE32 DisplayNameToValue

ME ME_54A4B8A0B9D2
 MEPROP UID '54A4B8A0B9D2'
 MEPROP Name 'WordPositionNamesMapHelper'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Утилитный класс для преобразования значений WordPositionNamesMap' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Operations
   Seq: ( HWL ME_C2DB53EB6783 // FillStrings
 HWL ME_AF278AD4DE32 // DisplayNameToValue
 )
 ; // Operations
 UP extprop:rc:isAcceptableForScripts true
 UPLINK SpelledFor HWL ME_7B428F54A9B3 // WordPositionNamesMap
 ;

ENDME // ME_54A4B8A0B9D2 WordPositionNamesMapHelper

FORWARD ME_0D20FE889A83

ME ME_A9CABCB40D53
 MEPROP UID 'A9CABCB40D53'
 MEPROP Name 'Make'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_factory::Operation ;
 %SUMMARY 'Фабричный метод для TWordPositionNamesMapImplPrim' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_0D20FE889A83 // TWordPositionNamesMapImplPrim
 ;
 MELINK Target WL 'ME_46A5FCD303C1' '4677FBA70343.ms.model.script' // Il3IntegerValueMap
 ;

ENDME // ME_A9CABCB40D53 Make

MEREF ME_46A5EFE602DE_ME_0D20FE889A83_impl
 MELINK Original WL 'ME_46A5EFE602DE' '4677FBA70343.ms.model.script' // MapID
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDMEREF // ME_46A5EFE602DE_ME_0D20FE889A83_impl MapID

MEREF ME_46A5F0130365_ME_0D20FE889A83_impl
 MELINK Original WL 'ME_46A5F0130365' '4677FBA70343.ms.model.script' // GetDisplayNames
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_46A5F0130365_ME_0D20FE889A83_impl GetDisplayNames

MEREF ME_46A5F03800A2_ME_0D20FE889A83_impl
 MELINK Original WL 'ME_46A5F03800A2' '4677FBA70343.ms.model.script' // MapSize
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_46A5F03800A2_ME_0D20FE889A83_impl MapSize

MEREF ME_46A5FCF900E0_ME_0D20FE889A83_impl
 MELINK Original WL 'ME_46A5FCF900E0' '4677FBA70343.ms.model.script' // DisplayNameToValue
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_46A5FCF900E0_ME_0D20FE889A83_impl DisplayNameToValue

MEREF ME_46A5FD1B000D_ME_0D20FE889A83_impl
 MELINK Original WL 'ME_46A5FD1B000D' '4677FBA70343.ms.model.script' // ValueToDisplayName
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_46A5FD1B000D_ME_0D20FE889A83_impl ValueToDisplayName

MEREF ME_4AE5CA2D0034_ME_0D20FE889A83_G
 MELINK Original WL? 'ME_4AE5CA2D0034' // Tl3CProtoObject
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4AE5CA2D0034_ME_0D20FE889A83_G Tl3CProtoObject

MEREF ME_46A5FCD303C1_ME_0D20FE889A83_R
 MELINK Original WL 'ME_46A5FCD303C1' '4677FBA70343.ms.model.script' // Il3IntegerValueMap
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_46A5FCD303C1_ME_0D20FE889A83_R Il3IntegerValueMap

%%ImplementedBy ME_46A5FCD303C1 ME_0D20FE889A83

%%InheritedBy ME_4AE5CA2D0034 ME_0D20FE889A83

ME ME_0D20FE889A83
 MEPROP UID '0D20FE889A83'
 MEPROP Name 'TWordPositionNamesMapImplPrim'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Класс для реализации мапы для WordPositionNamesMap' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Inherits
   Seq: ( ME_4AE5CA2D0034_ME_0D20FE889A83_G // Tl3CProtoObject
 )
 ; // Inherits
 MELIST Implements
   Seq: ( ME_46A5FCD303C1_ME_0D20FE889A83_R // Il3IntegerValueMap
 )
 ; // Implements
 MELIST Operations
   Seq: ( HWL ME_A9CABCB40D53 // Make
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_46A5EFE602DE_ME_0D20FE889A83_impl // MapID
 ME_46A5F0130365_ME_0D20FE889A83_impl // GetDisplayNames
 ME_46A5F03800A2_ME_0D20FE889A83_impl // MapSize
 ME_46A5FCF900E0_ME_0D20FE889A83_impl // DisplayNameToValue
 ME_46A5FD1B000D_ME_0D20FE889A83_impl // ValueToDisplayName
 )
 ; // Implemented
 UP extprop:rc:SelfName 'WordPositionNamesMapImplPrim'
 UP extprop:rc:isAcceptableForScripts true
 UPLINK SpelledFor HWL ME_7B428F54A9B3 // WordPositionNamesMap
 ;

ENDME // ME_0D20FE889A83 TWordPositionNamesMapImplPrim

FORWARD ME_9A1AB3598928

ME ME_87664887B1EE
 MEPROP UID '87664887B1EE'
 MEPROP Name 'Make'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_factory::Operation ;
 %SUMMARY 'Фабричный метод для TWordPositionNamesMapImpl' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_9A1AB3598928 // TWordPositionNamesMapImpl
 ;
 MELINK Target WL 'ME_46A5FCD303C1' '4677FBA70343.ms.model.script' // Il3IntegerValueMap
 ;

ENDME // ME_87664887B1EE Make

MEREF ME_0D20FE889A83_ME_9A1AB3598928_G
 MELINK Original HWL ME_0D20FE889A83 // TWordPositionNamesMapImplPrim
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_0D20FE889A83_ME_9A1AB3598928_G TWordPositionNamesMapImplPrim

%%InheritedBy ME_0D20FE889A83 ME_9A1AB3598928

ME ME_9A1AB3598928
 MEPROP UID '9A1AB3598928'
 MEPROP Name 'TWordPositionNamesMapImpl'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Класс для реализации мапы для WordPositionNamesMap' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Inherits
   Seq: ( ME_0D20FE889A83_ME_9A1AB3598928_G // TWordPositionNamesMapImplPrim
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_87664887B1EE // Make
 )
 ; // Operations
 UP "singleton" true
 UP extprop:rc:SelfName 'WordPositionNamesMapImpl'
 UP extprop:rc:isAcceptableForScripts true
 UPLINK SpelledFor HWL ME_7B428F54A9B3 // WordPositionNamesMap
 ;

ENDME // ME_9A1AB3598928 TWordPositionNamesMapImpl

FORWARD ME_EAC1D4682D0B

ME ME_D3AAB46A7B08
 MEPROP UID 'D3AAB46A7B08'
 MEPROP Name 'AllLevels'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '''Во всех уровнях''' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_EAC1D4682D0B // LCImplTreeLevelDistNames
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''nsc_tldAllLevels''; rValue : ''Во всех уровнях'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''nsc_tldAllLevels''; rValue : ''Во всех уровнях'')'
 UPLINK Speller HWL ME_4B97CF5D0164 // AllLevels
 ;

ENDME // ME_D3AAB46A7B08 AllLevels

ME ME_BACFF26B2CDC
 MEPROP UID 'BACFF26B2CDC'
 MEPROP Name 'OneLevel'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '''В пределах одного уровня''' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_EAC1D4682D0B // LCImplTreeLevelDistNames
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''nsc_tldOneLevel''; rValue : ''В пределах одного уровня'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''nsc_tldOneLevel''; rValue : ''В пределах одного уровня'')'
 UPLINK Speller HWL ME_4B97CF660076 // OneLevel
 ;

ENDME // ME_BACFF26B2CDC OneLevel

ME ME_EAC1D4682D0B
 MEPROP UID 'EAC1D4682D0B'
 MEPROP Name 'LCImplTreeLevelDistNames'
 UP IsSummoned true
 MEPROP Class class_Const
 MELINK Stereotype st_Constants ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Локализуемые строки TreeLevelDistNames' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Attributes
   Seq: ( HWL ME_D3AAB46A7B08 // AllLevels
 HWL ME_BACFF26B2CDC // OneLevel
 )
 ; // Attributes
 UP "children prefix" 'nsc_tld'
 UP "elements prefix" 'str'
 UP "spell names" false
 UP extprop:pas:ElementPrefixBase 'str'
 UP extprop:pas:ElementPrefix 'str_nsc_tld'
 UPLINK Speller HWL ME_4B97CF0C00D4 // TreeLevelDistNames
 ;

ENDME // ME_EAC1D4682D0B LCImplTreeLevelDistNames

FORWARD ME_9A2E8A142A43

ME ME_09EFD0F2B289
 MEPROP UID '09EFD0F2B289'
 MEPROP Name 'AllLevels'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_9A2E8A142A43 // TreeLevelDistNamesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'AllLevels'
 MELINK ValueType HWL ME_EAC1D4682D0B // LCImplTreeLevelDistNames
 ;
 UP extprop:pas:Value 'str_nsc_tldAllLevels'

ENDME // ME_09EFD0F2B289 AllLevels

ME ME_8AE48DC0EE63
 MEPROP UID '8AE48DC0EE63'
 MEPROP Name 'OneLevel'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_9A2E8A142A43 // TreeLevelDistNamesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'OneLevel'
 MELINK ValueType HWL ME_EAC1D4682D0B // LCImplTreeLevelDistNames
 ;
 UP extprop:pas:Value 'str_nsc_tldOneLevel'

ENDME // ME_8AE48DC0EE63 OneLevel

MEREF ME_4B3B49B40262_ME_9A2E8A142A43_G
 MELINK Original WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4B3B49B40262_ME_9A2E8A142A43_G Pl3StringIDEx

MEREF ME_46A61C8B002B_ME_9A2E8A142A43_R
 MELINK Original WL 'ME_46A61C8B002B' '4677FBA70343.ms.model.script' // Tl3TreeLevelDist
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_46A61C8B002B_ME_9A2E8A142A43_R Tl3TreeLevelDist

%%ImplementedBy ME_46A61C8B002B ME_9A2E8A142A43

%%InheritedBy ME_4B3B49B40262 ME_9A2E8A142A43

ME ME_9A2E8A142A43
 MEPROP UID '9A2E8A142A43'
 MEPROP Name 'TreeLevelDistNamesMap'
 UP IsSummoned true
 MEPROP Class class_Const
 MELINK Stereotype st_ConstantArray ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Карта преобразования локализованных строк TreeLevelDistNames' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Inherits
   Seq: ( ME_4B3B49B40262_ME_9A2E8A142A43_G // Pl3StringIDEx
 )
 ; // Inherits
 MELIST Implements
   Seq: ( ME_46A61C8B002B_ME_9A2E8A142A43_R // Tl3TreeLevelDist
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_09EFD0F2B289 // AllLevels
 HWL ME_8AE48DC0EE63 // OneLevel
 )
 ; // Attributes
 UP "Need map interface" true
 UP "Need mapping support" false

ENDME // ME_9A2E8A142A43 TreeLevelDistNamesMap

FORWARD ME_444575E246EA

ME ME_251D5667739D
 MEPROP Name 'aStrings'
 UP IsSummoned true
 MEPROP Class class_Parameter
 MELINK Target WL 'ME_4683CEE9034C' '467823B7002C.ms.model.script' // IafwStrings
 ;

ENDME // ME_251D5667739D aStrings

ME ME_968A40ED5C3C
 MEPROP UID '968A40ED5C3C'
 MEPROP Name 'FillStrings'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 %SUMMARY 'Заполнение списка строк значениями' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_444575E246EA // TreeLevelDistNamesMapHelper
 ;
 MELIST Parameters
   Seq: ( ME_251D5667739D // aStrings
 )
 ; // Parameters

ENDME // ME_968A40ED5C3C FillStrings

ME ME_C34806CBD8F6
 MEPROP Name 'aDisplayName'
 UP IsSummoned true
 MEPROP Class class_Parameter
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_C34806CBD8F6 aDisplayName

ME ME_C310C0288899
 MEPROP UID 'C310C0288899'
 MEPROP Name 'DisplayNameToValue'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 %SUMMARY 'Преобразование строкового значения к порядковому' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_444575E246EA // TreeLevelDistNamesMapHelper
 ;
 MELINK Target WL 'ME_46A61C8B002B' '4677FBA70343.ms.model.script' // Tl3TreeLevelDist
 ;
 MELIST Parameters
   Seq: ( ME_C34806CBD8F6 // aDisplayName
 )
 ; // Parameters

ENDME // ME_C310C0288899 DisplayNameToValue

ME ME_444575E246EA
 MEPROP UID '444575E246EA'
 MEPROP Name 'TreeLevelDistNamesMapHelper'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Утилитный класс для преобразования значений TreeLevelDistNamesMap' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Operations
   Seq: ( HWL ME_968A40ED5C3C // FillStrings
 HWL ME_C310C0288899 // DisplayNameToValue
 )
 ; // Operations
 UP extprop:rc:SelfName 'reeLevelDistNamesMapHelper'
 UP extprop:rc:isAcceptableForScripts true
 UPLINK SpelledFor HWL ME_9A2E8A142A43 // TreeLevelDistNamesMap
 ;

ENDME // ME_444575E246EA TreeLevelDistNamesMapHelper

FORWARD ME_5EAAE9B60711

ME ME_A43DCD52A1CD
 MEPROP UID 'A43DCD52A1CD'
 MEPROP Name 'Make'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_factory::Operation ;
 %SUMMARY 'Фабричный метод для TTreeLevelDistNamesMapImplPrim' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5EAAE9B60711 // TTreeLevelDistNamesMapImplPrim
 ;
 MELINK Target WL 'ME_46A5FCD303C1' '4677FBA70343.ms.model.script' // Il3IntegerValueMap
 ;

ENDME // ME_A43DCD52A1CD Make

MEREF ME_46A5EFE602DE_ME_5EAAE9B60711_impl
 MELINK Original WL 'ME_46A5EFE602DE' '4677FBA70343.ms.model.script' // MapID
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDMEREF // ME_46A5EFE602DE_ME_5EAAE9B60711_impl MapID

MEREF ME_46A5F0130365_ME_5EAAE9B60711_impl
 MELINK Original WL 'ME_46A5F0130365' '4677FBA70343.ms.model.script' // GetDisplayNames
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_46A5F0130365_ME_5EAAE9B60711_impl GetDisplayNames

MEREF ME_46A5F03800A2_ME_5EAAE9B60711_impl
 MELINK Original WL 'ME_46A5F03800A2' '4677FBA70343.ms.model.script' // MapSize
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_46A5F03800A2_ME_5EAAE9B60711_impl MapSize

MEREF ME_46A5FCF900E0_ME_5EAAE9B60711_impl
 MELINK Original WL 'ME_46A5FCF900E0' '4677FBA70343.ms.model.script' // DisplayNameToValue
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_46A5FCF900E0_ME_5EAAE9B60711_impl DisplayNameToValue

MEREF ME_46A5FD1B000D_ME_5EAAE9B60711_impl
 MELINK Original WL 'ME_46A5FD1B000D' '4677FBA70343.ms.model.script' // ValueToDisplayName
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_46A5FD1B000D_ME_5EAAE9B60711_impl ValueToDisplayName

MEREF ME_4AE5CA2D0034_ME_5EAAE9B60711_G
 MELINK Original WL? 'ME_4AE5CA2D0034' // Tl3CProtoObject
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4AE5CA2D0034_ME_5EAAE9B60711_G Tl3CProtoObject

MEREF ME_46A5FCD303C1_ME_5EAAE9B60711_R
 MELINK Original WL 'ME_46A5FCD303C1' '4677FBA70343.ms.model.script' // Il3IntegerValueMap
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_46A5FCD303C1_ME_5EAAE9B60711_R Il3IntegerValueMap

%%ImplementedBy ME_46A5FCD303C1 ME_5EAAE9B60711

%%InheritedBy ME_4AE5CA2D0034 ME_5EAAE9B60711

ME ME_5EAAE9B60711
 MEPROP UID '5EAAE9B60711'
 MEPROP Name 'TTreeLevelDistNamesMapImplPrim'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Класс для реализации мапы для TreeLevelDistNamesMap' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Inherits
   Seq: ( ME_4AE5CA2D0034_ME_5EAAE9B60711_G // Tl3CProtoObject
 )
 ; // Inherits
 MELIST Implements
   Seq: ( ME_46A5FCD303C1_ME_5EAAE9B60711_R // Il3IntegerValueMap
 )
 ; // Implements
 MELIST Operations
   Seq: ( HWL ME_A43DCD52A1CD // Make
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_46A5EFE602DE_ME_5EAAE9B60711_impl // MapID
 ME_46A5F0130365_ME_5EAAE9B60711_impl // GetDisplayNames
 ME_46A5F03800A2_ME_5EAAE9B60711_impl // MapSize
 ME_46A5FCF900E0_ME_5EAAE9B60711_impl // DisplayNameToValue
 ME_46A5FD1B000D_ME_5EAAE9B60711_impl // ValueToDisplayName
 )
 ; // Implemented
 UP extprop:rc:SelfName 'TreeLevelDistNamesMapImplPrim'
 UP extprop:rc:isAcceptableForScripts true
 UPLINK SpelledFor HWL ME_9A2E8A142A43 // TreeLevelDistNamesMap
 ;

ENDME // ME_5EAAE9B60711 TTreeLevelDistNamesMapImplPrim

FORWARD ME_4E9251221D21

ME ME_41A4AF57FA8C
 MEPROP UID '41A4AF57FA8C'
 MEPROP Name 'Make'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_factory::Operation ;
 %SUMMARY 'Фабричный метод для TTreeLevelDistNamesMapImpl' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4E9251221D21 // TTreeLevelDistNamesMapImpl
 ;
 MELINK Target WL 'ME_46A5FCD303C1' '4677FBA70343.ms.model.script' // Il3IntegerValueMap
 ;

ENDME // ME_41A4AF57FA8C Make

MEREF ME_5EAAE9B60711_ME_4E9251221D21_G
 MELINK Original HWL ME_5EAAE9B60711 // TTreeLevelDistNamesMapImplPrim
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_5EAAE9B60711_ME_4E9251221D21_G TTreeLevelDistNamesMapImplPrim

%%InheritedBy ME_5EAAE9B60711 ME_4E9251221D21

ME ME_4E9251221D21
 MEPROP UID '4E9251221D21'
 MEPROP Name 'TTreeLevelDistNamesMapImpl'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Класс для реализации мапы для TreeLevelDistNamesMap' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Inherits
   Seq: ( ME_5EAAE9B60711_ME_4E9251221D21_G // TTreeLevelDistNamesMapImplPrim
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_41A4AF57FA8C // Make
 )
 ; // Operations
 UP "singleton" true
 UP extprop:rc:SelfName 'TreeLevelDistNamesMapImpl'
 UP extprop:rc:isAcceptableForScripts true
 UPLINK SpelledFor HWL ME_9A2E8A142A43 // TreeLevelDistNamesMap
 ;

ENDME // ME_4E9251221D21 TTreeLevelDistNamesMapImpl

FORWARD ME_D07C47D13B55

ME ME_3FAF82CC9579
 MEPROP UID '3FAF82CC9579'
 MEPROP Name 'AnyOrder'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '''В любом порядке''' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_D07C47D13B55 // LCImplWordOrderNames
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''nsc_woAnyOrder''; rValue : ''В любом порядке'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''nsc_woAnyOrder''; rValue : ''В любом порядке'')'
 UPLINK Speller HWL ME_4B97D4210322 // AnyOrder
 ;

ENDME // ME_3FAF82CC9579 AnyOrder

ME ME_2390CD2FE6E0
 MEPROP UID '2390CD2FE6E0'
 MEPROP Name 'AsWrote'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '''С учетом порядка''' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_D07C47D13B55 // LCImplWordOrderNames
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''nsc_woAsWrote''; rValue : ''С учетом порядка'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''nsc_woAsWrote''; rValue : ''С учетом порядка'')'
 UPLINK Speller HWL ME_4B97D42E01FD // AsWrote
 ;

ENDME // ME_2390CD2FE6E0 AsWrote

ME ME_D07C47D13B55
 MEPROP UID 'D07C47D13B55'
 MEPROP Name 'LCImplWordOrderNames'
 UP IsSummoned true
 MEPROP Class class_Const
 MELINK Stereotype st_Constants ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Локализуемые строки WordOrderNames' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Attributes
   Seq: ( HWL ME_3FAF82CC9579 // AnyOrder
 HWL ME_2390CD2FE6E0 // AsWrote
 )
 ; // Attributes
 UP "children prefix" 'nsc_wo'
 UP "elements prefix" 'str'
 UP "spell names" false
 UP extprop:pas:ElementPrefixBase 'str'
 UP extprop:pas:ElementPrefix 'str_nsc_wo'
 UPLINK Speller HWL ME_4B97D3D303BE // WordOrderNames
 ;

ENDME // ME_D07C47D13B55 LCImplWordOrderNames

FORWARD ME_758E40454E7A

ME ME_A6A764001454
 MEPROP UID 'A6A764001454'
 MEPROP Name 'AnyOrder'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_758E40454E7A // WordOrderNamesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'AnyOrder'
 MELINK ValueType HWL ME_D07C47D13B55 // LCImplWordOrderNames
 ;
 UP extprop:pas:Value 'str_nsc_woAnyOrder'

ENDME // ME_A6A764001454 AnyOrder

ME ME_BFD031FADE01
 MEPROP UID 'BFD031FADE01'
 MEPROP Name 'AsWrote'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_758E40454E7A // WordOrderNamesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'AsWrote'
 MELINK ValueType HWL ME_D07C47D13B55 // LCImplWordOrderNames
 ;
 UP extprop:pas:Value 'str_nsc_woAsWrote'

ENDME // ME_BFD031FADE01 AsWrote

MEREF ME_4B3B49B40262_ME_758E40454E7A_G
 MELINK Original WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4B3B49B40262_ME_758E40454E7A_G Pl3StringIDEx

MEREF ME_46A61C340026_ME_758E40454E7A_R
 MELINK Original WL 'ME_46A61C340026' '4677FBA70343.ms.model.script' // Tl3WordOrder
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_46A61C340026_ME_758E40454E7A_R Tl3WordOrder

%%ImplementedBy ME_46A61C340026 ME_758E40454E7A

%%InheritedBy ME_4B3B49B40262 ME_758E40454E7A

ME ME_758E40454E7A
 MEPROP UID '758E40454E7A'
 MEPROP Name 'WordOrderNamesMap'
 UP IsSummoned true
 MEPROP Class class_Const
 MELINK Stereotype st_ConstantArray ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Карта преобразования локализованных строк WordOrderNames' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Inherits
   Seq: ( ME_4B3B49B40262_ME_758E40454E7A_G // Pl3StringIDEx
 )
 ; // Inherits
 MELIST Implements
   Seq: ( ME_46A61C340026_ME_758E40454E7A_R // Tl3WordOrder
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_A6A764001454 // AnyOrder
 HWL ME_BFD031FADE01 // AsWrote
 )
 ; // Attributes
 UP "Need map interface" true
 UP "Need mapping support" false

ENDME // ME_758E40454E7A WordOrderNamesMap

FORWARD ME_2C955AD033BA

ME ME_CC1DD28CBE03
 MEPROP Name 'aStrings'
 UP IsSummoned true
 MEPROP Class class_Parameter
 MELINK Target WL 'ME_4683CEE9034C' '467823B7002C.ms.model.script' // IafwStrings
 ;

ENDME // ME_CC1DD28CBE03 aStrings

ME ME_6E3894B77C4A
 MEPROP UID '6E3894B77C4A'
 MEPROP Name 'FillStrings'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 %SUMMARY 'Заполнение списка строк значениями' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_2C955AD033BA // WordOrderNamesMapHelper
 ;
 MELIST Parameters
   Seq: ( ME_CC1DD28CBE03 // aStrings
 )
 ; // Parameters

ENDME // ME_6E3894B77C4A FillStrings

ME ME_E88EC44C036D
 MEPROP Name 'aDisplayName'
 UP IsSummoned true
 MEPROP Class class_Parameter
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_E88EC44C036D aDisplayName

ME ME_4CD8F3EDFF4B
 MEPROP UID '4CD8F3EDFF4B'
 MEPROP Name 'DisplayNameToValue'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 %SUMMARY 'Преобразование строкового значения к порядковому' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_2C955AD033BA // WordOrderNamesMapHelper
 ;
 MELINK Target WL 'ME_46A61C340026' '4677FBA70343.ms.model.script' // Tl3WordOrder
 ;
 MELIST Parameters
   Seq: ( ME_E88EC44C036D // aDisplayName
 )
 ; // Parameters

ENDME // ME_4CD8F3EDFF4B DisplayNameToValue

ME ME_2C955AD033BA
 MEPROP UID '2C955AD033BA'
 MEPROP Name 'WordOrderNamesMapHelper'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Утилитный класс для преобразования значений WordOrderNamesMap' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Operations
   Seq: ( HWL ME_6E3894B77C4A // FillStrings
 HWL ME_4CD8F3EDFF4B // DisplayNameToValue
 )
 ; // Operations
 UP extprop:rc:isAcceptableForScripts true
 UPLINK SpelledFor HWL ME_758E40454E7A // WordOrderNamesMap
 ;

ENDME // ME_2C955AD033BA WordOrderNamesMapHelper

FORWARD ME_1E42BDDCD137

ME ME_84AA99BB8254
 MEPROP UID '84AA99BB8254'
 MEPROP Name 'Make'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_factory::Operation ;
 %SUMMARY 'Фабричный метод для TWordOrderNamesMapImplPrim' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_1E42BDDCD137 // TWordOrderNamesMapImplPrim
 ;
 MELINK Target WL 'ME_46A5FCD303C1' '4677FBA70343.ms.model.script' // Il3IntegerValueMap
 ;

ENDME // ME_84AA99BB8254 Make

MEREF ME_46A5EFE602DE_ME_1E42BDDCD137_impl
 MELINK Original WL 'ME_46A5EFE602DE' '4677FBA70343.ms.model.script' // MapID
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" true
ENDMEREF // ME_46A5EFE602DE_ME_1E42BDDCD137_impl MapID

MEREF ME_46A5F0130365_ME_1E42BDDCD137_impl
 MELINK Original WL 'ME_46A5F0130365' '4677FBA70343.ms.model.script' // GetDisplayNames
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_46A5F0130365_ME_1E42BDDCD137_impl GetDisplayNames

MEREF ME_46A5F03800A2_ME_1E42BDDCD137_impl
 MELINK Original WL 'ME_46A5F03800A2' '4677FBA70343.ms.model.script' // MapSize
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_46A5F03800A2_ME_1E42BDDCD137_impl MapSize

MEREF ME_46A5FCF900E0_ME_1E42BDDCD137_impl
 MELINK Original WL 'ME_46A5FCF900E0' '4677FBA70343.ms.model.script' // DisplayNameToValue
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_46A5FCF900E0_ME_1E42BDDCD137_impl DisplayNameToValue

MEREF ME_46A5FD1B000D_ME_1E42BDDCD137_impl
 MELINK Original WL 'ME_46A5FD1B000D' '4677FBA70343.ms.model.script' // ValueToDisplayName
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_46A5FD1B000D_ME_1E42BDDCD137_impl ValueToDisplayName

MEREF ME_4AE5CA2D0034_ME_1E42BDDCD137_G
 MELINK Original WL? 'ME_4AE5CA2D0034' // Tl3CProtoObject
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4AE5CA2D0034_ME_1E42BDDCD137_G Tl3CProtoObject

MEREF ME_46A5FCD303C1_ME_1E42BDDCD137_R
 MELINK Original WL 'ME_46A5FCD303C1' '4677FBA70343.ms.model.script' // Il3IntegerValueMap
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_46A5FCD303C1_ME_1E42BDDCD137_R Il3IntegerValueMap

%%ImplementedBy ME_46A5FCD303C1 ME_1E42BDDCD137

%%InheritedBy ME_4AE5CA2D0034 ME_1E42BDDCD137

ME ME_1E42BDDCD137
 MEPROP UID '1E42BDDCD137'
 MEPROP Name 'TWordOrderNamesMapImplPrim'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Класс для реализации мапы для WordOrderNamesMap' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Inherits
   Seq: ( ME_4AE5CA2D0034_ME_1E42BDDCD137_G // Tl3CProtoObject
 )
 ; // Inherits
 MELIST Implements
   Seq: ( ME_46A5FCD303C1_ME_1E42BDDCD137_R // Il3IntegerValueMap
 )
 ; // Implements
 MELIST Operations
   Seq: ( HWL ME_84AA99BB8254 // Make
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_46A5EFE602DE_ME_1E42BDDCD137_impl // MapID
 ME_46A5F0130365_ME_1E42BDDCD137_impl // GetDisplayNames
 ME_46A5F03800A2_ME_1E42BDDCD137_impl // MapSize
 ME_46A5FCF900E0_ME_1E42BDDCD137_impl // DisplayNameToValue
 ME_46A5FD1B000D_ME_1E42BDDCD137_impl // ValueToDisplayName
 )
 ; // Implemented
 UP extprop:rc:SelfName 'WordOrderNamesMapImplPrim'
 UP extprop:rc:isAcceptableForScripts true
 UPLINK SpelledFor HWL ME_758E40454E7A // WordOrderNamesMap
 ;

ENDME // ME_1E42BDDCD137 TWordOrderNamesMapImplPrim

FORWARD ME_3DB0B8BFFFFD

ME ME_FCC33F9BFF23
 MEPROP UID 'FCC33F9BFF23'
 MEPROP Name 'Make'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_factory::Operation ;
 %SUMMARY 'Фабричный метод для TWordOrderNamesMapImpl' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_3DB0B8BFFFFD // TWordOrderNamesMapImpl
 ;
 MELINK Target WL 'ME_46A5FCD303C1' '4677FBA70343.ms.model.script' // Il3IntegerValueMap
 ;

ENDME // ME_FCC33F9BFF23 Make

MEREF ME_1E42BDDCD137_ME_3DB0B8BFFFFD_G
 MELINK Original HWL ME_1E42BDDCD137 // TWordOrderNamesMapImplPrim
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_1E42BDDCD137_ME_3DB0B8BFFFFD_G TWordOrderNamesMapImplPrim

%%InheritedBy ME_1E42BDDCD137 ME_3DB0B8BFFFFD

ME ME_3DB0B8BFFFFD
 MEPROP UID '3DB0B8BFFFFD'
 MEPROP Name 'TWordOrderNamesMapImpl'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Класс для реализации мапы для WordOrderNamesMap' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELIST Inherits
   Seq: ( ME_1E42BDDCD137_ME_3DB0B8BFFFFD_G // TWordOrderNamesMapImplPrim
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_FCC33F9BFF23 // Make
 )
 ; // Operations
 UP "singleton" true
 UP extprop:rc:SelfName 'WordOrderNamesMapImpl'
 UP extprop:rc:isAcceptableForScripts true
 UPLINK SpelledFor HWL ME_758E40454E7A // WordOrderNamesMap
 ;

ENDME // ME_3DB0B8BFFFFD TWordOrderNamesMapImpl

ME ME_0A7D3720E287
 UP IsSummoned true
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;

ENDME // ME_0A7D3720E287 

ME ME_836473B635C6
 UP IsSummoned true
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELINK Target WL 'ME_4E01D1E002AE' '4E01D1980071.ms.model.script' // Tl3MessageID
 ;

ENDME // ME_836473B635C6 

ME ME_D582B72C8749
 UP IsSummoned true
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELINK Target WL? 'ME_47878E0E0191' // l3String
 ;

ENDME // ME_D582B72C8749 

ME ME_CA5F8138CFF2
 UP IsSummoned true
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELINK Target WL 'ME_4787A405013D' '47877EB202FB.ms.model.script' // Exception
 ;

ENDME // ME_CA5F8138CFF2 

ME ME_40F6CDCCEEBF
 UP IsSummoned true
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4B97B148028B // nsAppConfigRes
 ;
 MELINK Target WL 'ME_4AC1F98A0155' '4773D64E036C.ms.model.script' // l3FillChar
 ;

ENDME // ME_40F6CDCCEEBF 

ME ME_4B97B148028B
 MEPROP UID '4B97B148028B'
 MEPROP Name 'nsAppConfigRes'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_UtilityPack ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Ресурсы для nsAppConfig' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL? 'ME_4ABA137C00E5' // Config
 ;
 MELIST Children
   Seq: ( HWL ME_54A4B8A0B9D2 // WordPositionNamesMapHelper
 HWL ME_0D20FE889A83 // TWordPositionNamesMapImplPrim
 HWL ME_9A1AB3598928 // TWordPositionNamesMapImpl
 HWL ME_444575E246EA // TreeLevelDistNamesMapHelper
 HWL ME_5EAAE9B60711 // TTreeLevelDistNamesMapImplPrim
 HWL ME_4E9251221D21 // TTreeLevelDistNamesMapImpl
 HWL ME_2C955AD033BA // WordOrderNamesMapHelper
 HWL ME_1E42BDDCD137 // TWordOrderNamesMapImplPrim
 HWL ME_3DB0B8BFFFFD // TWordOrderNamesMapImpl
 )
 ; // Children
 MELIST Constants
   Seq: ( HWL ME_4B97B1890142 // WordPositionNames
 HWL ME_4B97CF0C00D4 // TreeLevelDistNames
 HWL ME_4B97D3D303BE // WordOrderNames
 HWL ME_4B97D7D60086 // ContextParamsMessages
 HWL ME_3905605C6778 // LCImplWordPositionNames
 HWL ME_7B428F54A9B3 // WordPositionNamesMap
 HWL ME_EAC1D4682D0B // LCImplTreeLevelDistNames
 HWL ME_9A2E8A142A43 // TreeLevelDistNamesMap
 HWL ME_D07C47D13B55 // LCImplWordOrderNames
 HWL ME_758E40454E7A // WordOrderNamesMap
 )
 ; // Constants
 MELIST Dependencies
   Seq: ( ME_0A7D3720E287 // Tl3StringIDEx
 ME_836473B635C6 // Tl3MessageID
 ME_D582B72C8749 // l3String
 ME_CA5F8138CFF2 // Exception
 ME_40F6CDCCEEBF // l3FillChar
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "author" 'Люлин А.В.'
 UP "no hands" true
 UP "started" '10.03.2010 17:49'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Config\nsAppConfigRes.pas'
 UP extprop:rc:SelfName 'AppConfigRes'

ENDME // ME_4B97B148028B nsAppConfigRes
