// MixIns 4BCE9EA0028A Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4BCE9EA0028A

FORWARD ME_4BCE9EF8033F

: ME_4BCE9F17020A
 CONST UID '4BCE9F17020A'
 CONST Name 'FormClass'
 CONST Class class_Class
 : Stereotype st_ImpurityParamType ;
 CONST Kind kind_NormalClass
 %SUMMARY ' ласс формы' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 CONST extprop:pas:TypeName '_FormClass_'

ref; // ME_4BCE9F17020A FormClass

: ME_4C9B2C6403B8
 CONST UID '4C9B2C6403B8'
 CONST Name 'FormClassRef'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 : Inherits
   Seq: ( ME_4BCE9F17020A // FormClass
 )
 ; // Inherits
 CONST "isClassRef" true
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4C9B2C6403B8 FormClassRef

: ME_4BCE9F9102AA
 CONST UID '4BCE9F9102AA'
 CONST Name 'FormClass'
 CONST Class class_Attribute
 : Stereotype st_impurity_param::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 : Target ME_4BCE9F17020A // FormClass
 ;

ref; // ME_4BCE9F9102AA FormClass

: ME_4C0E55EC033C
 CONST UID '4C0E55EC033C'
 CONST Name 'f_FixedHeight'
 CONST Class class_Attribute
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4C0E55EC033C f_FixedHeight

FORWARD ME_4BCE9FC203E4

: ME_4BCE9FDE0103
 CONST UID '4BCE9FDE0103'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4BCE9FC203E4 // MakeForm
 ;
 : Target ME_4BCE9F17020A // FormClass
 ;

ref; // ME_4BCE9FDE0103 DoIt

: ME_4BCE9FF8020F
 CONST UID '4BCE9FF8020F'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4BCE9FC203E4 // MakeForm
 ;
 : Target WL 'ME_47F25BC801DB' '47D0E1500033.pas.ms.script' // vcmBase
 ;

ref; // ME_4BCE9FF8020F 

: ME_4BCE9FC203E4
 CONST UID '4BCE9FC203E4'
 CONST Name 'MakeForm'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 : Operations
   Seq: ( ME_4BCE9FDE0103 // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4BCE9FF8020F // 
 )
 ; // Dependencies

ref; // ME_4BCE9FC203E4 MakeForm

FORWARD ME_4C9B2B7F0266

: ME_4C9B2B8F02BA
 CONST UID '4C9B2B8F02BA'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4C9B2B7F0266 // MakeFormClass
 ;
 : Target ME_4C9B2C6403B8 // FormClassRef
 ;

ref; // ME_4C9B2B8F02BA DoIt

: ME_4C9B2B7F0266
 CONST UID '4C9B2B7F0266'
 CONST Name 'MakeFormClass'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 : Operations
   Seq: ( ME_4C9B2B8F02BA // DoIt
 )
 ; // Operations

ref; // ME_4C9B2B7F0266 MakeFormClass

: ME_4C08CF700318
 CONST UID '4C08CF700318'
 CONST Name 'FormExtent'
 CONST Class class_Operation
 %SUMMARY '–азмеры формы' ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 : Target WL 'ME_4739AD110072' '4728A7020026.pas.ms.script' // TPoint
 ;

ref; // ME_4C08CF700318 FormExtent

: ME_4C08D62B0149
 CONST UID '4C08D62B0149'
 CONST Name 'aForm'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_4BCE9F17020A // FormClass
 ;

ref; // ME_4C08D62B0149 aForm

: ME_4C08D61F0231
 CONST UID '4C08D61F0231'
 CONST Name 'FormMade'
 CONST Class class_Operation
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 : Parameters
   Seq: ( ME_4C08D62B0149 // aForm
 )
 ; // Parameters

ref; // ME_4C08D61F0231 FormMade

: ME_4DA2F7900393
 CONST UID '4DA2F7900393'
 CONST Name 'UseFormExtentAsClientSize'
 CONST Class class_Operation
 %SUMMARY '»спользовать заданные размеры формы как размеры клиентской области - размеры формы пересчитываютс€ относительно этих ограничений.' ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_4DA2F7900393 UseFormExtentAsClientSize

: ME_4BCE9F890019
 CONST UID '4BCE9F890019'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 : Target WL 'ME_47F25BC801DB' '47D0E1500033.pas.ms.script' // vcmBase
 ;

ref; // ME_4BCE9F890019 

: ME_4BCEA5AB0052
 CONST UID '4BCEA5AB0052'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_4BCEA5AB0052 

: ME_4BCEAD7103DD
 CONST UID '4BCEAD7103DD'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 : Target WL 'ME_47E13C6B0341' '4799D29F033F.pas.ms.script' // Forms
 ;

ref; // ME_4BCEAD7103DD 

: ME_4C08D02C033F
 CONST UID '4C08D02C033F'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4BCE9EF8033F // FormProducer
 ;
 : Target WL 'ME_4773D64E036C' '47913B47006E.pas.ms.script' // l3Base
 ;

ref; // ME_4C08D02C033F 

: ME_4BCE9EF8033F
 CONST UID '4BCE9EF8033F'
 CONST Name 'FormProducer'
 CONST Class class_Class
 : Stereotype st_Impurity ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4BCE9EA0028A // MixIns
 ;
 : Attributes
   Seq: ( ME_4BCE9F9102AA // FormClass
 ME_4C0E55EC033C // f_FixedHeight
 )
 ; // Attributes
 : Operations
   Seq: ( ME_4BCE9FC203E4 // MakeForm
 ME_4C9B2B7F0266 // MakeFormClass
 ME_4C08CF700318 // FormExtent
 ME_4C08D61F0231 // FormMade
 ME_4DA2F7900393 // UseFormExtentAsClientSize
 )
 ; // Operations
 : Children
   Seq: ( ME_4BCE9F17020A // FormClass
 ME_4C9B2C6403B8 // FormClassRef
 )
 ; // Children
 : Dependencies
   Seq: ( ME_4BCE9F890019 // 
 ME_4BCEA5AB0052 // 
 ME_4BCEAD7103DD // 
 ME_4C08D02C033F // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\gui\Garant\Daily\FormProducer.imp.pas'
 CONST extprop:pas:TypeName '_FormProducer_'
 CONST extprop:pas:UnitName 'FormProducer.imp'

ref; // ME_4BCE9EF8033F FormProducer

: ME_4BCE9EA0028A
 CONST UID '4BCE9EA0028A'
 CONST Name 'MixIns'
 CONST Class class_Category
 : Stereotype st_Unit ;
 %SUMMARY 'ѕримеси' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4B30C5FF0172' '4B30C5FF0172.pas.ms.script' // TestFormsTest
 ;
 : Children
   Seq: ( ME_4BCE9EF8033F // FormProducer
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4728A7020026' '4728A7020026.pas.ms.script' // Types
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_4799D29F033F' '4799D29F033F.pas.ms.script' // Implementation
 WL 'ME_47D0E1500033' '47D0E1500033.pas.ms.script' // Implementation
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 )
 ; // Depends
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\4BCE9EA0028A.pas.ms.script'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\4BCE9EA0028A.pas.ms.script.runner'

ref; // ME_4BCE9EA0028A MixIns
