// InternetSupport 4BD132D103B9 Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4BD132D103B9

FORWARD ME_4BD1331201C8

: ME_4BD133C102AD
 CONST UID '4BD133C102AD'
 CONST Name 'revision_check_enabled'
 CONST Class class_Operation
 %SUMMARY '–азрешена ли онлайн проверка ревизий документов (дл€ супермобильной версии)' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4BD1331201C8 // InternetSupport
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4BD133C102AD revision_check_enabled

: ME_4BD137AB00F4
 CONST Name 'doc_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4BD137AB00F4 doc_id

: ME_4BD137AB011C
 CONST Name 'para_id'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_3DBFFDE101CA' '3DBFDB23006E.pas.ms.script' // unsigned long
 ;

ref; // ME_4BD137AB011C para_id

: ME_4BD133E40285
 CONST UID '4BD133E40285'
 CONST Name 'get_url_for_document'
 CONST Class class_Operation
 %SUMMARY 'получить URL дл€ заданного документа' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4BD1331201C8 // InternetSupport
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 : Parameters
   Seq: ( ME_4BD137AB00F4 // doc_id
 ME_4BD137AB011C // para_id
 )
 ; // Parameters

ref; // ME_4BD133E40285 get_url_for_document

: ME_4BD1393B0146
 CONST UID '4BD1393B0146'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 %SUMMARY 'фабрика' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4BD1331201C8 // InternetSupport
 ;
 CONST "const_type" 'read-write'

ref; // ME_4BD1393B0146 make

: ME_4BD1396400A3
 CONST UID '4BD1396400A3'
 CONST Name 'is_internet_agent_enabled'
 CONST Class class_Operation
 %SUMMARY '–азрешен ли »нтернет-јгент.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4BD1331201C8 // InternetSupport
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4BD1396400A3 is_internet_agent_enabled

: ME_4BD1456303BC
 CONST UID '4BD1456303BC'
 CONST Name 'get_url_for_internet_version'
 CONST Class class_Operation
 %SUMMARY 'получить URL дл€ интранет версии' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4BD1331201C8 // InternetSupport
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_4BD1456303BC get_url_for_internet_version

: ME_4D6648D000C3
 CONST UID '4D6648D000C3'
 CONST Name 'show_warning'
 CONST Class class_Operation
 %SUMMARY 'Ќужно ли показывать бл€мбу об отключении онлайн проверки' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4BD1331201C8 // InternetSupport
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4D6648D000C3 show_warning

: ME_4BD1331201C8
 CONST UID '4BD1331201C8'
 CONST GUID '7DF56131-CBD6-47F5-B8B1-495409AFE6E4'
 CONST Name 'InternetSupport'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 %SUMMARY 'поддержка работы пользователей через internet' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4BD132D103B9 // InternetSupport
 ;
 : Operations
   Seq: ( ME_4BD133C102AD // revision_check_enabled
 ME_4BD133E40285 // get_url_for_document
 ME_4BD1393B0146 // make
 ME_4BD1396400A3 // is_internet_agent_enabled
 ME_4BD1456303BC // get_url_for_internet_version
 ME_4D6648D000C3 // show_warning
 )
 ; // Operations
 CONST "single impl" false
 CONST extprop:pas:TypeName 'IInternetSupport'
 CONST extprop:rc:SelfName 'InternetSupport'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4BD1331201C8 InternetSupport

FORWARD ME_4F71CF610077

: ME_4F71D0930146
 CONST UID '4F71D0930146'
 CONST Name 'make'
 CONST Class class_Operation
 : Stereotype st_factory::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4F71CF610077 // DecisionsArchiveSupport
 ;
 CONST "const_type" 'read-write'

ref; // ME_4F71D0930146 make

: ME_4F71D47D0086
 CONST UID '4F71D47D0086'
 CONST Name 'get_archive_url'
 CONST Class class_Operation
 %SUMMARY 'получить ссылку дл€ перехода на архив судебных решений' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4F71CF610077 // DecisionsArchiveSupport
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_4F71D47D0086 get_archive_url

: ME_4F71DD6B03AA
 CONST UID '4F71DD6B03AA'
 CONST Name 'archive_available'
 CONST Class class_Operation
 %SUMMARY 'архив судебных решений доступен' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4F71CF610077 // DecisionsArchiveSupport
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_4F71DD6B03AA archive_available

: ME_56F26D0E026E
 CONST UID '56F26D0E026E'
 CONST Name 'search_server_available'
 CONST Class class_Operation
 %SUMMARY 'проверка доступности сервера поиска в архивах' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4F71CF610077 // DecisionsArchiveSupport
 ;
 : Target WL 'ME_3DBFFE100240' '3DBFDB23006E.pas.ms.script' // boolean
 ;

ref; // ME_56F26D0E026E search_server_available

: ME_56F26D7D0117
 CONST Name 'query'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;

ref; // ME_56F26D7D0117 query

: ME_56F26D590288
 CONST UID '56F26D590288'
 CONST Name 'get_search_server_url'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_4F71CF610077 // DecisionsArchiveSupport
 ;
 : Target WL 'ME_431841610361' '4423F94903C8.pas.ms.script' // String
 ;
 : Parameters
   Seq: ( ME_56F26D7D0117 // query
 )
 ; // Parameters

ref; // ME_56F26D590288 get_search_server_url

: ME_4F71CF610077
 CONST UID '4F71CF610077'
 CONST GUID 'CD81011E-549D-406A-964C-9FE291552EB4'
 CONST Name 'DecisionsArchiveSupport'
 CONST Class class_Class
 : Stereotype st_Interface ;
 CONST Kind kind_NormalClass
 %SUMMARY '»нтерфейс доступа к архивам судебных решений' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4BD132D103B9 // InternetSupport
 ;
 : Operations
   Seq: ( ME_4F71D0930146 // make
 ME_4F71D47D0086 // get_archive_url
 ME_4F71DD6B03AA // archive_available
 ME_56F26D0E026E // search_server_available
 ME_56F26D590288 // get_search_server_url
 )
 ; // Operations
 CONST "single impl" false
 CONST extprop:pas:TypeName 'IDecisionsArchiveSupport'
 CONST extprop:rc:SelfName 'DecisionsArchiveSupport'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F71CF610077 DecisionsArchiveSupport

: ME_4BD132D103B9
 CONST UID '4BD132D103B9'
 CONST Name 'InternetSupport'
 CONST Class class_Category
 : Stereotype st_Interfaces ;
 %SUMMARY '¬озможности, доступные через интернет' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_456EA3D2031C' '456EA3D2031C.pas.ms.script' // GblAdapterLib
 ;
 : Children
   Seq: ( ME_4BD1331201C8 // InternetSupport
 ME_4F71CF610077 // DecisionsArchiveSupport
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4423F94903C8' '4423F94903C8.pas.ms.script' // IO
 )
 ; // Depends
 CONST "no hands" false
 CONST cpp:Path 'garant6x\implementation\Garant\GblAdapterLib\InternetSupport\InternetSupport.cpp'
 CONST cpp:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\InternetSupport'
 CONST h:Path 'garant6x\implementation\Garant\GblAdapterLib\InternetSupport\InternetSupport.h'
 CONST h:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\InternetSupport'
 CONST intf.pas:Path 'garant6x\implementation\Garant\tie\Garant\GblAdapterLib\InternetSupportUnit.pas'
 CONST pas:Path 'garant6x\implementation\Garant\GblAdapterLib\InternetSupportUnit.pas'
 CONST extprop:pas:UnitName 'InternetSupportUnit'

ref; // ME_4BD132D103B9 InternetSupport
