// Generators 4C407B410029 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4C407B410029
%%Inner ME_4C407B410029
%%Inner ME_4C407B410029
%%Inner ME_4C407B410029
%%Inner ME_4C407B410029
%%Inner ME_4C407B410029
%%Inner ME_4C407B410029

ME ME_4C407B410029
 MEPROP UID '4C407B410029'
 MEPROP Name 'Generators'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_48EEE54C0072' // EverestCommon
 ;
 MELIST Children
   Seq: ( WL? 'ME_4C3FED3103B2' // TevOEMTableFlagFilter
 WL? 'ME_4C56D4E002D2' // TevUnblockEmptyParaFilter
 WL? 'ME_4CA2FFC10275' // TevStrictContentsElementEliminator
 WL? 'ME_4CA311770238' // TevBlocksEliminator
 WL? 'ME_4CF7B733015E' // TevEmptyTableEliminator
 WL? 'ME_4D9343CE038C' // TevLeafParaDecorationsHolderEliminator
 WL? 'ME_4E7754BD01BA' // TevDocumentSubsChildrenCountEliminator
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_4678137501EA' // k2Interfaces
 WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_47AC75550330' // k2Tags
 WL? 'ME_47ECA80B000D' // Generators
 WL? 'ME_47ECB8BD00A8' // Generators
 WL? 'ME_480DBA6900E6' // k2Facade
 WL? 'ME_48492FC0029D' // Standard
 WL? 'ME_484A470100DD' // Standard
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_54B90AC6014B' // StringUtils
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_4C407B410029 Generators
