// K227478018 4C46F5FE0082 TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4C46F5FE0082

MEREF ME_4C08CF700318_ME_4C46F5FE0082_over
 MELINK Original WL 'ME_4C08CF700318' '4BCE9EF8033F.ms.model.script' // FormExtent
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_4C08CF700318_ME_4C46F5FE0082_over FormExtent

MEREF ME_4C46F52A0317_ME_4C46F5FE0082_G
 MELINK Original WL? 'ME_4C46F52A0317' // TDrawLineTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4C46F52A0317_ME_4C46F5FE0082_G TDrawLineTest

%%InheritedBy ME_4C46F52A0317 ME_4C46F5FE0082

ME ME_4C46F5FE0082
 MEPROP UID '4C46F5FE0082'
 MEPROP Name 'K227478018'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '[$227478018]' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4C288F1202F8' // 7.6
 ;
 MELIST Inherits
   Seq: ( ME_4C46F52A0317_ME_4C46F5FE0082_G // TDrawLineTest
 )
 ; // Inherits
 MELIST Overridden
   Seq: ( ME_4C08CF700318_ME_4C46F5FE0082_over // FormExtent
 )
 ; // Overridden
 UP intf.pas:Path 'common\components\rtl\Garant\Daily\K227478018.pas'
 UP extprop:pas:TypeName 'TK227478018'
 UP extprop:rc:SelfName 'K227478018'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_4C46F5FE0082 K227478018
