// K226006206 4C73E85C02D6 TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4B8542C302E3_ME_4C73E85C02D6_G
 MELINK Original WL? 'ME_4B8542C302E3' // TEVDtoBothNSRCWriterTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4B8542C302E3_ME_4C73E85C02D6_G TEVDtoBothNSRCWriterTest

%%InheritedBy ME_4B8542C302E3 ME_4C73E85C02D6

ME ME_4C73E85C02D6
 MEPROP UID '4C73E85C02D6'
 MEPROP Name 'K226006206'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{RequestLink:226006206}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4C288F1202F8' // 7.6
 ;
 MELIST Inherits
   Seq: ( ME_4B8542C302E3_ME_4C73E85C02D6_G // TEVDtoBothNSRCWriterTest
 )
 ; // Inherits
 UP "author" 'Ëþëèí À.Â.'
 UP "no hands" true
 UP "started" '24.08.2010 19:42'
 UP intf.pas:Path 'common\components\rtl\Garant\Daily\K226006206.pas'
 UP extprop:pas:TypeName 'TK226006206'
 UP extprop:rc:SelfName 'K226006206'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_4C73E85C02D6 K226006206
