// PrimNavigatorOptions 4C87A47E0036 VCMForm Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4C87A47E0036

ME ME_4C87A98F0350
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4C87A47E0036 // PrimNavigatorOptions
 ;
 MELINK Target WL 'ME_468259900322' '4682595B0268.ms.model.script' // Il3SimpleNode
 ;

ENDME // ME_4C87A98F0350 

ME ME_4C87A9B2002F
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4C87A47E0036 // PrimNavigatorOptions
 ;
 MELINK Target WL 'ME_45EEB95901C5' '457450470167.ms.model.script' // NodeBase
 ;

ENDME // ME_4C87A9B2002F 

ME ME_4C87A9D70073
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4C87A47E0036 // PrimNavigatorOptions
 ;
 MELINK Target WL 'ME_4ADDF53403CA' '47F60E8E019C.ms.model.script' // nsGetHint
 ;

ENDME // ME_4C87A9D70073 

ME ME_4C87A9F00343
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4C87A47E0036 // PrimNavigatorOptions
 ;
 MELINK Target WL 'ME_4ADEE49C02DF' '47877EB202FB.ms.model.script' // Supports
 ;

ENDME // ME_4C87A9F00343 

ME ME_524006770296
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4C87A47E0036 // PrimNavigatorOptions
 ;
 MELINK Target WL 'ME_490723DC0096' '4907236C0171.ms.model.script' // TnsNavigatorTreeStruct
 ;

ENDME // ME_524006770296 

ME ME_4951285702E1_ME_4C87A47E0036
 MELINK Original WL 'ME_4951285702E1' '495127DD017C.ms.model.script' // Cut
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" false
 UP "AutoLock" false
 UP "LongProcess" false
 UP "ShowInContextMenu" true
 UP "ShowInToolbar" true
 UP "has states" false
 UP "is FormActivate" true
 UP "is query" true
 UP "no prefix" false
ENDME // ME_4951285702E1_ME_4C87A47E0036 Cut

ME ME_49EDFA3701B0_ME_4C87A47E0036
 MELINK Original WL 'ME_49EDFA3701B0' '495127DD017C.ms.model.script' // Paste
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" false
 UP "AutoLock" false
 UP "LongProcess" false
 UP "ShowInContextMenu" true
 UP "ShowInToolbar" false
 UP "has states" false
 UP "is FormActivate" true
 UP "is query" true
 UP "no prefix" false
ENDME // ME_49EDFA3701B0_ME_4C87A47E0036 Paste

ME ME_49EDFCA2006D_ME_4C87A47E0036
 MELINK Original WL 'ME_49EDFCA2006D' '495127DD017C.ms.model.script' // Undo
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" false
 UP "AutoLock" false
 UP "LongProcess" false
 UP "ShowInContextMenu" true
 UP "ShowInToolbar" false
 UP "has states" false
 UP "is FormActivate" true
 UP "is query" true
 UP "no prefix" false
ENDME // ME_49EDFCA2006D_ME_4C87A47E0036 Undo

ME ME_49EDFCB100BC_ME_4C87A47E0036
 MELINK Original WL 'ME_49EDFCB100BC' '495127DD017C.ms.model.script' // Redo
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" false
 UP "AutoLock" false
 UP "LongProcess" false
 UP "ShowInContextMenu" true
 UP "ShowInToolbar" false
 UP "has states" false
 UP "is FormActivate" true
 UP "is query" true
 UP "no prefix" false
ENDME // ME_49EDFCB100BC_ME_4C87A47E0036 Redo

ME ME_49EE01AA02BE_ME_4C87A47E0036
 MELINK Original WL 'ME_49EE01AA02BE' '495127DD017C.ms.model.script' // SelectAll
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" false
 UP "AutoLock" false
 UP "LongProcess" false
 UP "ShowInContextMenu" true
 UP "ShowInToolbar" false
 UP "has states" false
 UP "is FormActivate" true
 UP "is query" true
 UP "no prefix" false
ENDME // ME_49EE01AA02BE_ME_4C87A47E0036 SelectAll

ME ME_49EE01BC022E_ME_4C87A47E0036
 MELINK Original WL 'ME_49EE01BC022E' '495127DD017C.ms.model.script' // Deselect
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" false
 UP "AutoLock" false
 UP "LongProcess" false
 UP "ShowInContextMenu" true
 UP "ShowInToolbar" false
 UP "has states" false
 UP "is FormActivate" true
 UP "is query" true
 UP "no prefix" false
ENDME // ME_49EE01BC022E_ME_4C87A47E0036 Deselect

ME ME_4C7D0C7B0185_ME_4C87A47E0036
 MELINK Original WL 'ME_4C7D0C7B0185' '495127DD017C.ms.model.script' // Copy
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" false
 UP "AutoLock" false
 UP "LongProcess" false
 UP "ShowInContextMenu" true
 UP "ShowInToolbar" false
 UP "has states" false
 UP "is FormActivate" true
 UP "is query" true
 UP "no prefix" false
ENDME // ME_4C7D0C7B0185_ME_4C87A47E0036 Copy

ME ME_4C7D0CC90052_ME_4C87A47E0036
 MELINK Original WL 'ME_4C7D0CC90052' '494F898C013E.ms.model.script' // Delete
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" false
 UP "AutoLock" false
 UP "LongProcess" false
 UP "ShowInContextMenu" true
 UP "ShowInToolbar" false
 UP "has states" false
 UP "is FormActivate" true
 UP "is query" true
 UP "no prefix" false
ENDME // ME_4C7D0CC90052_ME_4C87A47E0036 Delete

ME ME_4C87A50402CC_ME_4C87A47E0036
 MELINK Original WL 'ME_4C87A50402CC' '4AEEE2A40281.ms.model.script' // Info
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" false
 UP "AutoLock" false
 UP "LongProcess" false
 UP "ShowInContextMenu" true
 UP "ShowInToolbar" false
 UP "has states" false
 UP "is FormActivate" false
 UP "is query" false
 UP "no prefix" false
ENDME // ME_4C87A50402CC_ME_4C87A47E0036 Info

ME ME_4C87A52E02F7_ME_4C87A47E0036
 MELINK Original WL 'ME_4C87A52E02F7' '4AEEE2A40281.ms.model.script' // Execute
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" false
 UP "AutoLock" false
 UP "LongProcess" false
 UP "ShowInContextMenu" true
 UP "ShowInToolbar" false
 UP "has states" false
 UP "is FormActivate" false
 UP "is query" false
 UP "no prefix" false
ENDME // ME_4C87A52E02F7_ME_4C87A47E0036 Execute

%%ImplementedBy ME_494F89AA0017 ME_4C87A47E0036
%%ImplementedBy ME_4951282D0269 ME_4C87A47E0036
%%ImplementedBy ME_4C87A4F301A7 ME_4C87A47E0036

%%InheritedBy ME_4AEEE269033F ME_4C87A47E0036

ME ME_4C87A47E0036
 MEPROP UID '4C87A47E0036'
 MEPROP Name 'PrimNavigatorOptions'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_VCMForm ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Ìåíþ' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_497ED74F0032' '497ED74F0032.ms.model.script' // Common
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4AEEE269033F' '4AEEE269033F.ms.model.script' // PrimNavigator
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_494F89AA0017' '494F898C013E.ms.model.script' // Edit
 WL 'ME_4951282D0269' '495127DD017C.ms.model.script' // Edit
 WL 'ME_4C87A4F301A7' '4AEEE2A40281.ms.model.script' // NavigatorElement
 )
 ; // Implements
 MELIST Implemented
   Seq: ( ME_4951285702E1_ME_4C87A47E0036 // Cut
 ME_49EDFA3701B0_ME_4C87A47E0036 // Paste
 ME_49EDFCA2006D_ME_4C87A47E0036 // Undo
 ME_49EDFCB100BC_ME_4C87A47E0036 // Redo
 ME_49EE01AA02BE_ME_4C87A47E0036 // SelectAll
 ME_49EE01BC022E_ME_4C87A47E0036 // Deselect
 ME_4C7D0C7B0185_ME_4C87A47E0036 // Copy
 ME_4C7D0CC90052_ME_4C87A47E0036 // Delete
 ME_4C87A50402CC_ME_4C87A47E0036 // Info
 ME_4C87A52E02F7_ME_4C87A47E0036 // Execute
 )
 ; // Implemented
 MELIST Dependencies
   Seq: ( ME_4C87A98F0350 // Il3SimpleNode
 ME_4C87A9B2002F // NodeBase
 ME_4C87A9D70073 // nsGetHint
 ME_4C87A9F00343 // Supports
 ME_524006770296 // TnsNavigatorTreeStruct
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "NeedsHackRef" true
 UP "ZoneType" 'Navigator'
 UP "author" 'Ëþëèí À.Â.'
 UP "finished dfm" true
 UP "no hands" true
 UP "resizeable" false
 UP "restrict form def" 'undefined'
 UP "started" '09.0.2010 18:58'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\Common\Forms\PrimNavigatorOptions_Form.pas'
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View\Common\Forms'
 UP extprop:pas:TypeName 'TPrimNavigatorOptionsForm'
 UP extprop:rc:SelfName 'PrimNavigatorOptionsForm'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'PrimNavigatorOptions_Form'
 UP extprop:NeedsInitEntities true

ENDME // ME_4C87A47E0036 PrimNavigatorOptions
