// BaseSearch 4CC979AB0180 VCMUseCase Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4CC979AB0180

: ME_4CC97A9F0310
 CONST UID '4CC97A9F0310'
 CONST Name 'BaseSearch'
 CONST Class class_Class
 : Stereotype st_VCMUseCaseRealization ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Базовый поиск' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4CC979AB0180 // BaseSearch
 ;
 : Inherits
   Seq: ( WL 'ME_4CC97D020011' '4CC97BDA02DF.pas.ms.script' // BaseSearch
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_484407B70220' '484407720166.pas.ms.script' // Базовый поиск
 )
 ; // Implements
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST dfm:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\moBaseSearch.pas'
 CONST intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'
 CONST extprop:pas:TypeName 'Tmo_BaseSearch'
 CONST extprop:rc:SelfName 'mo_BaseSearch'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'moBaseSearch'

ref; // ME_4CC97A9F0310 BaseSearch$UC

: ME_4CC979AB0180
 CONST UID '4CC979AB0180'
 CONST Name 'BaseSearch'
 CONST Class class_Category
 : Stereotype st_VCMUseCase ;
 %SUMMARY '[$14209]' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent WL 'ME_4F7E92C400AF' '4F7E92C400AF.pas.ms.script' // F1 Основные прецеденты
 ;
 : Children
   Seq: ( ME_4CC97A9F0310 // BaseSearch$UC
 WL 'ME_4CC97B6702A4' '4CC97B6702A4.pas.ms.script' // View
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_456EA3D2031C' '456EA3D2031C.pas.ms.script' // GblAdapterLib
 WL 'ME_467A75D90346' '467A75D90346.pas.ms.script' // VT
 WL 'ME_467A8734039C' '467A8734039C.pas.ms.script' // EVD
 WL 'ME_4680E7D50168' '4680E7D50168.pas.ms.script' // Everest Engine
 WL 'ME_4684F91300DD' '4684F91300DD.pas.ms.script' // Vcl
 WL 'ME_4790B4F00236' '4790B4F00236.pas.ms.script' // AFW
 WL 'ME_4790C3B8021E' '4790C3B8021E.pas.ms.script' // VCM
 WL 'ME_4790D09A0378' '4790D09A0378.pas.ms.script' // L3
 WL 'ME_4797632D0273' '4797632D0273.pas.ms.script' // Everest
 WL 'ME_481EF5C4020D' '481EF5C4020D.pas.ms.script' // Оболочка
 WL 'ME_484407720166' '484407720166.pas.ms.script' // Поиск
 WL 'ME_490838AA02D0' '490838AA02D0.pas.ms.script' // Nemesis
 WL 'ME_49549627008C' '49549627008C.pas.ms.script' // LegalDomain
 WL 'ME_4954C00703D0' '4954C00703D0.pas.ms.script' // OfficeLike
 WL 'ME_4A78010000B7' '4A78010000B7.pas.ms.script' // Search
 WL 'ME_4A7C095601DA' '4A7C095601DA.pas.ms.script' // Base Operations
 WL 'ME_4A8567F2039C' '4A8567F2039C.pas.ms.script' // SearchLite
 WL 'ME_4A92C561015D' '4A92C561015D.pas.ms.script' // Common
 WL 'ME_4B63155B0328' '4B63155B0328.pas.ms.script' // MDProcess$ForDelphi
 WL 'ME_4CC7FE0401B5' '4CC7FE0401B5.pas.ms.script' // NewInterface2010
 WL 'ME_4CFCE4F203CE' '4CFCE4F203CE.pas.ms.script' // VGScene
 WL 'ME_4E13416D0227' '4E13416D0227.pas.ms.script' // VCM$Visual
 WL 'ME_4E1352670215' '4E1352670215.pas.ms.script' // Nemesis$Tails
 WL 'ME_4E2F0E1B03BB' '4E2F0E1B03BB.pas.ms.script' // L3$Domain
 WL 'ME_547CC9D40158' '547CC9D40158.pas.ms.script' // VT$Panels
 WL 'ME_54CF97B10370' '54CF97B10370.pas.ms.script' // ScriptEngine$Core
 WL 'ME_54DB92A80279' '54DB92A80279.pas.ms.script' // ScriptEngine$RTLandVCL
 WL 'ME_550012C403C4' '550012C403C4.pas.ms.script' // L3$AFW
 WL 'ME_562E251101C2' '562E251101C2.pas.ms.script' // Shared Delphi Rtl
 )
 ; // Depends
 CONST dfm:PathOnly '\garant6x\implementation\Garant\GbaNemesis'
 CONST intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\4CC979AB0180.pas.ms.script'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\4CC979AB0180.pas.ms.script.runner'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_4CC979AB0180 BaseSearch
