// Attributes 4D39AD3200C1 VCMForms Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4D39AD3200C1

FORWARD ME_4979DA14019A

FORWARD ME_4B150CFE01CB

: ME_4B150D3B00BE
 CONST Name 'aDoc'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_45EEB6520191' '4570511E038A.pas.ms.script' // Document
 ;

ref; // ME_4B150D3B00BE aDoc

: ME_4B150D310061
 CONST UID '4B150D310061'
 CONST Name 'Log'
 CONST Class class_Operation
 : Stereotype st_static::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4B150CFE01CB // TnsViewDocumentAttributesEvent
 ;
 : Parameters
   Seq: ( ME_4B150D3B00BE // aDoc
 )
 ; // Parameters

ref; // ME_4B150D310061 Log

: ME_4B150D50010A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4B150CFE01CB // TnsViewDocumentAttributesEvent
 ;
 : Target WL 'ME_45ED58FF0201' '45ED58CF03E6.pas.ms.script' // LogEvent
 ;

ref; // ME_4B150D50010A 

: ME_4B150CFE01CB
 CONST UID '4B150CFE01CB'
 CONST Name 'TnsViewDocumentAttributesEvent'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4979DA14019A // PrimAttributes
 ;
 : Inherits
   Seq: ( WL 'ME_4B0A6109010C' '4B0A60DF01F2.pas.ms.script' // TnsLogEvent
 )
 ; // Inherits
 : Operations
   Seq: ( ME_4B150D310061 // Log
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4B150D50010A // LogEvent
 )
 ; // Dependencies
 CONST extprop:rc:SelfName 'ViewDocumentAttributesEvent'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4B150CFE01CB TnsViewDocumentAttributesEvent

FORWARD ME_4C864E34020B

: ME_46A5AA4B003C_ME_4C864E34020B
 : Original WL 'ME_46A5AA4B003C' '4677FBA70343.pas.ms.script' // Invalidate
 ;
 CONST OpKind opkind_Implemented
ref; // ME_46A5AA4B003C_ME_4C864E34020B Invalidate

: ME_477243870072_ME_4C864E34020B
 : Original WL 'ME_477243870072' '4682595B0268.pas.ms.script' // RootChanged
 ;
 CONST OpKind opkind_Implemented
ref; // ME_477243870072_ME_4C864E34020B RootChanged

: ME_4951285702E1_ME_4C864E34020B
 : Original WL 'ME_4951285702E1' '495127DD017C.pas.ms.script' // Cut
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4951285702E1_ME_4C864E34020B Cut

: ME_49512B5D0009_ME_4C864E34020B
 : Original WL 'ME_49512B5D0009' '495127DD017C.pas.ms.script' // FindContext
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_49512B5D0009_ME_4C864E34020B FindContext

: ME_495130C40123_ME_4C864E34020B
 : Original WL 'ME_495130C40123' '495127DD017C.pas.ms.script' // FindNext
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_495130C40123_ME_4C864E34020B FindNext

: ME_49EDFCA2006D_ME_4C864E34020B
 : Original WL 'ME_49EDFCA2006D' '495127DD017C.pas.ms.script' // Undo
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_49EDFCA2006D_ME_4C864E34020B Undo

: ME_49EDFCB100BC_ME_4C864E34020B
 : Original WL 'ME_49EDFCB100BC' '495127DD017C.pas.ms.script' // Redo
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_49EDFCB100BC_ME_4C864E34020B Redo

: ME_49FEDE4703B8_ME_4C864E34020B
 : Original WL 'ME_49FEDE4703B8' '495127DD017C.pas.ms.script' // FindPrev
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_49FEDE4703B8_ME_4C864E34020B FindPrev

: ME_4C7D0C7B0185_ME_4C864E34020B
 : Original WL 'ME_4C7D0C7B0185' '495127DD017C.pas.ms.script' // Copy
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" true
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4C7D0C7B0185_ME_4C864E34020B Copy

: ME_4C864E34020B
 CONST UID '4C864E34020B'
 CONST Name 'tvAttributes'
 CONST Class class_Class
 : Stereotype st_Control ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4979DA14019A // PrimAttributes
 ;
 : Inherits
   Seq: ( WL 'ME_52DE57DF007B' '52DE57B200A5.pas.ms.script' // TnscTreeViewWithAdapterDragDrop
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4951282D0269' '495127DD017C.pas.ms.script' // Edit
 WL 'ME_4BDAF7790158' '4BDAF7510113.pas.ms.script' // Tree
 )
 ; // Implements
 : Implemented
   Seq: ( ME_46A5AA4B003C_ME_4C864E34020B // Invalidate
 ME_477243870072_ME_4C864E34020B // RootChanged
 ME_4951285702E1_ME_4C864E34020B // Cut
 ME_49512B5D0009_ME_4C864E34020B // FindContext
 ME_495130C40123_ME_4C864E34020B // FindNext
 ME_49EDFCA2006D_ME_4C864E34020B // Undo
 ME_49EDFCB100BC_ME_4C864E34020B // Redo
 ME_49FEDE4703B8_ME_4C864E34020B // FindPrev
 ME_4C7D0C7B0185_ME_4C864E34020B // Copy
 )
 ; // Implemented
 CONST "ControlClass" 'TnscTreeViewWithAdapterDragDrop'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_4C864E34020B tvAttributes

: ME_4979DA630067
 CONST UID '4979DA630067'
 CONST Name 'CoDS'
 CONST Class class_Attribute
 : Stereotype st_ViewArea::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 CONST LinkType lt_lnk
 : Parent ME_4979DA14019A // PrimAttributes
 ;
 : Target WL 'ME_49255D040142' '491B305A0096.pas.ms.script' // IdsAttributes
 ;

ref; // ME_4979DA630067 CoDS

: ME_833591437CF5
 CONST UID '833591437CF5'
 CONST Name 'f_tvAttributes'
 CONST IsSummoned true
 CONST Class class_Attribute
 %SUMMARY 'Поле для свойства tvAttributes' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent ME_4979DA14019A // PrimAttributes
 ;
 : Target WL 'ME_52DE57DF007B' '52DE57B200A5.pas.ms.script' // TnscTreeViewWithAdapterDragDrop
 ;

ref; // ME_833591437CF5 f_tvAttributes

: ME_F1BA23F5F37B
 CONST UID 'F1BA23F5F37B'
 CONST Name 'Ini_Reg_Class'
 CONST IsSummoned true
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация PrimAttributes' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4979DA14019A // PrimAttributes
 ;
 CONST "ifndef" 'NoScripts'

ref; // ME_F1BA23F5F37B Ini_Reg_Class

: ME_4B1418C9027B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4979DA14019A // PrimAttributes
 ;
 : Target WL 'ME_48F72B630069' '48F5EE2702FF.pas.ms.script' // TnsSingleAttributeData
 ;

ref; // ME_4B1418C9027B 

: ME_4B150D2803AA
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4979DA14019A // PrimAttributes
 ;
 : Target ME_4B150CFE01CB // TnsViewDocumentAttributesEvent
 ;

ref; // ME_4B150D2803AA 

: ME_4BD6BAB001E7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4979DA14019A // PrimAttributes
 ;
 : Target WL 'ME_4AE836C303BC' '4F71AD0E01FE.pas.ms.script' // Switcher$SetCaption
 ;

ref; // ME_4BD6BAB001E7 

: ME_4BD6BADC007A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4979DA14019A // PrimAttributes
 ;
 : Target WL 'ME_498874FD012C' '4AEEE2A40281.pas.ms.script' // Document$MangleForSpell
 ;

ref; // ME_4BD6BADC007A 

: ME_F00FB77EE170
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4979DA14019A // PrimAttributes
 ;
 : Target WL 'ME_561F9F9400BC' '561F9F7D02A7.pas.ms.script' // TtfwClassRef
 ;

ref; // ME_F00FB77EE170 

: ME_37BE60CD03ED_ME_4979DA14019A
 : Original WL 'ME_37BE60CD03ED' '4A7C0BB70162.pas.ms.script' // fDocAttributeQueryClose
 ;
 CONST OpKind opkind_Implemented
ref; // ME_37BE60CD03ED_ME_4979DA14019A fDocAttributeQueryClose

: ME_497F16AC015A_ME_4979DA14019A
 : Original WL 'ME_497F16AC015A' '4A7C0BB70162.pas.ms.script' // DoTabActivate
 ;
 CONST OpKind opkind_Implemented
ref; // ME_497F16AC015A_ME_4979DA14019A DoTabActivate

: ME_4979DA14019A
 CONST UID '4979DA14019A'
 CONST Name 'PrimAttributes'
 CONST Class class_Class
 : Stereotype st_VCMForm ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Атрибуты документа' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4D39AD3200C1 // Attributes
 ;
 : Inherits
   Seq: ( WL 'ME_497F142501FA' '4D383D6E01B6.pas.ms.script' // BaseDocumentForDocumentModule
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_497F0F17036D' '4A7C0BB70162.pas.ms.script' // PageControlNotification
 WL 'ME_4D776CFE031E' '4A7C0BB70162.pas.ms.script' // AttributesUserTypes
 )
 ; // Implements
 : Attributes
   Seq: ( ME_4C864E34020B // tvAttributes
 ME_4979DA630067 // CoDS
 ME_833591437CF5 // f_tvAttributes
 )
 ; // Attributes
 : Operations
   Seq: ( ME_F1BA23F5F37B // Ini_Reg_Class
 )
 ; // Operations
 : Implemented
   Seq: ( ME_37BE60CD03ED_ME_4979DA14019A // fDocAttributeQueryClose
 ME_497F16AC015A_ME_4979DA14019A // DoTabActivate
 )
 ; // Implemented
 : Children
   Seq: ( ME_4B150CFE01CB // TnsViewDocumentAttributesEvent
 )
 ; // Children
 : Dependencies
   Seq: ( ME_4B1418C9027B // TnsSingleAttributeData
 ME_4B150D2803AA // TnsViewDocumentAttributesEvent
 ME_4BD6BAB001E7 // Switcher$SetCaption
 ME_4BD6BADC007A // Document$MangleForSpell
 ME_F00FB77EE170 // TtfwClassRef
 )
 ; // Dependencies
 CONST "NeedsHackRef" false
 CONST "ZoneType" 'Any'
 CONST "author" 'Люлин А.В.'
 CONST "finished dfm" true
 CONST "no hands" true
 CONST "resizeable" false
 CONST "restrict form def" 'undefined'
 CONST "started" '23.01.2009 18:18'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\PrimAttributes_Form.pas'
 CONST extprop:pas:TypeName 'TPrimAttributesForm'
 CONST extprop:rc:SelfName 'PrimAttributesForm'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'PrimAttributes_Form'
 CONST extprop:NeedsInitEntities true
 CONST extprop:HasAnyVCMController true

ref; // ME_4979DA14019A PrimAttributes

FORWARD ME_4C8647C8024E

FORWARD ME_511A3E2A0297

: ME_46A5AA4B003C_ME_511A3E2A0297
 : Original WL 'ME_46A5AA4B003C' '4677FBA70343.pas.ms.script' // Invalidate
 ;
 CONST OpKind opkind_Implemented
ref; // ME_46A5AA4B003C_ME_511A3E2A0297 Invalidate

: ME_477243870072_ME_511A3E2A0297
 : Original WL 'ME_477243870072' '4682595B0268.pas.ms.script' // RootChanged
 ;
 CONST OpKind opkind_Implemented
ref; // ME_477243870072_ME_511A3E2A0297 RootChanged

: ME_4951285702E1_ME_511A3E2A0297
 : Original WL 'ME_4951285702E1' '495127DD017C.pas.ms.script' // Cut
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4951285702E1_ME_511A3E2A0297 Cut

: ME_49512B5D0009_ME_511A3E2A0297
 : Original WL 'ME_49512B5D0009' '495127DD017C.pas.ms.script' // FindContext
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_49512B5D0009_ME_511A3E2A0297 FindContext

: ME_495130C40123_ME_511A3E2A0297
 : Original WL 'ME_495130C40123' '495127DD017C.pas.ms.script' // FindNext
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_495130C40123_ME_511A3E2A0297 FindNext

: ME_49EDFCA2006D_ME_511A3E2A0297
 : Original WL 'ME_49EDFCA2006D' '495127DD017C.pas.ms.script' // Undo
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_49EDFCA2006D_ME_511A3E2A0297 Undo

: ME_49EDFCB100BC_ME_511A3E2A0297
 : Original WL 'ME_49EDFCB100BC' '495127DD017C.pas.ms.script' // Redo
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_49EDFCB100BC_ME_511A3E2A0297 Redo

: ME_49FEDE4703B8_ME_511A3E2A0297
 : Original WL 'ME_49FEDE4703B8' '495127DD017C.pas.ms.script' // FindPrev
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_49FEDE4703B8_ME_511A3E2A0297 FindPrev

: ME_4C7D0C7B0185_ME_511A3E2A0297
 : Original WL 'ME_4C7D0C7B0185' '495127DD017C.pas.ms.script' // Copy
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" 'undefined'
 CONST "ShowInToolbar" 'undefined'
 CONST "has states" true
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4C7D0C7B0185_ME_511A3E2A0297 Copy

: ME_511A3E2A0297
 CONST UID '511A3E2A0297'
 CONST Name 'tvAttributes'
 CONST Class class_Class
 : Stereotype st_ControlOverride ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Inherits
   Seq: ( ME_4C864E34020B // tvAttributes
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_46A5AA4B003C_ME_511A3E2A0297 // Invalidate
 ME_477243870072_ME_511A3E2A0297 // RootChanged
 ME_4951285702E1_ME_511A3E2A0297 // Cut
 ME_49512B5D0009_ME_511A3E2A0297 // FindContext
 ME_495130C40123_ME_511A3E2A0297 // FindNext
 ME_49EDFCA2006D_ME_511A3E2A0297 // Undo
 ME_49EDFCB100BC_ME_511A3E2A0297 // Redo
 ME_49FEDE4703B8_ME_511A3E2A0297 // FindPrev
 ME_4C7D0C7B0185_ME_511A3E2A0297 // Copy
 )
 ; // Implemented
 CONST "ControlClass" 'TnscTreeView'
 CONST "pm" true
 CONST "put to dfm" false

ref; // ME_511A3E2A0297 tvAttributes

FORWARD ME_4C864C08016E

: ME_4C864C160168
 CONST UID '4C864C160168'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4C864C08016E // MakePreview
 ;
 : Target WL 'ME_467BB4640328' '467823B7002C.pas.ms.script' // IafwDocumentPreview
 ;

ref; // ME_4C864C160168 DoIt

: ME_4C864C08016E
 CONST UID '4C864C08016E'
 CONST Name 'MakePreview'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Operations
   Seq: ( ME_4C864C160168 // DoIt
 )
 ; // Operations

ref; // ME_4C864C08016E MakePreview

FORWARD ME_4C864DD70182

: ME_4C864DE40083
 CONST UID '4C864DE40083'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4C864DD70182 // HasTree
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_4C864DE40083 DoIt

: ME_4C864DD70182
 CONST UID '4C864DD70182'
 CONST Name 'HasTree'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Operations
   Seq: ( ME_4C864DE40083 // DoIt
 )
 ; // Operations

ref; // ME_4C864DD70182 HasTree

FORWARD ME_511A3C6F0383

: ME_511A3D3A01CA
 CONST Name 'Sender'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4807745602C8' '4AB0C3C60310.pas.ms.script' // TObject
 ;

ref; // ME_511A3D3A01CA Sender

: ME_511A3D3A0208
 CONST Name 'Index'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_511A3D3A0208 Index

: ME_511A3D3A0250
 CONST Name 'aImages'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_473DA2AF0168' '4799D29F033F.pas.ms.script' // TCustomImageList
 ;

ref; // ME_511A3D3A0250 aImages

: ME_511A3D360247
 CONST UID '511A3D360247'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_511A3C6F0383 // tvAttributesGetItemImage
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Parameters
   Seq: ( ME_511A3D3A01CA // Sender
 ME_511A3D3A0208 // Index
 ME_511A3D3A0250 // aImages
 )
 ; // Parameters

ref; // ME_511A3D360247 DoIt

: ME_511A3C6F0383
 CONST UID '511A3C6F0383'
 CONST Name 'tvAttributesGetItemImage'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Operations
   Seq: ( ME_511A3D360247 // DoIt
 )
 ; // Operations

ref; // ME_511A3C6F0383 tvAttributesGetItemImage

FORWARD ME_511A3D5D01FA

: ME_511A3D8303A0
 CONST Name 'theTree'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_46825CC00249' '4682595B0268.pas.ms.script' // Il3SimpleTree
 ;

ref; // ME_511A3D8303A0 theTree

: ME_511A3D830071
 CONST UID '511A3D830071'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_511A3D5D01FA // tvAttributesMakeTreeSource
 ;
 : Parameters
   Seq: ( ME_511A3D8303A0 // theTree
 )
 ; // Parameters

ref; // ME_511A3D830071 DoIt

: ME_511A3D5D01FA
 CONST UID '511A3D5D01FA'
 CONST Name 'tvAttributesMakeTreeSource'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Operations
   Seq: ( ME_511A3D830071 // DoIt
 )
 ; // Operations

ref; // ME_511A3D5D01FA tvAttributesMakeTreeSource

: ME_BE4B3C1AAA12
 CONST UID 'BE4B3C1AAA12'
 CONST Name 'Ini_Reg_Class'
 CONST IsSummoned true
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация PrimAttributesOptions' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 CONST "ifndef" 'NoScripts'

ref; // ME_BE4B3C1AAA12 Ini_Reg_Class

: ME_4C864DF70054
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_47752AF90375' '47750CE700D0.pas.ms.script' // afwFacade
 ;

ref; // ME_4C864DF70054 

: ME_4C864E0C0307
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_4773D64E036C' '47913B47006E.pas.ms.script' // l3Base
 ;

ref; // ME_4C864E0C0307 

: ME_4C864E5D0353
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_48FC8B3D01BC' '4802FF41005C.pas.ms.script' // TevTreeDataObject
 ;

ref; // ME_4C864E5D0353 

: ME_4C864E79006E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_48FC655F025C' '4802FF41005C.pas.ms.script' // TevTreeStorableData
 ;

ref; // ME_4C864E79006E 

: ME_4C864E9C00FB
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_48F72B630069' '48F5EE2702FF.pas.ms.script' // TnsSingleAttributeData
 ;

ref; // ME_4C864E9C00FB 

: ME_4C864EBF0350
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_46825CC00249' '4682595B0268.pas.ms.script' // Il3SimpleTree
 ;

ref; // ME_4C864EBF0350 

: ME_4C86508700C1
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_45EEC3DE0232' '457450470167.pas.ms.script' // FlagsConst
 ;

ref; // ME_4C86508700C1 

: ME_4D3EAA2600D3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_4799D2E6027B' '55C4AEB903E1.pas.ms.script' // Printers
 ;

ref; // ME_4D3EAA2600D3 

: ME_500572B80283
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_4B50566202C6' '47EA50050263.pas.ms.script' // TnsDocumentRes
 ;

ref; // ME_500572B80283 

: ME_511A6AAC03E1
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_4912DD2C0082' '4912DD020283.pas.ms.script' // IeeNode
 ;

ref; // ME_511A6AAC03E1 

: ME_511A6B00010E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_47E11FC3021E' '4799D29F033F.pas.ms.script' // Controls
 ;

ref; // ME_511A6B00010E 

: ME_511A6B060305
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_47E13C6B0341' '4799D29F033F.pas.ms.script' // Forms
 ;

ref; // ME_511A6B060305 

: ME_511A6B31020C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_47D036300337' '47D036150077.pas.ms.script' // TvtViewOption
 ;

ref; // ME_511A6B31020C 

: ME_511CFADA024A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_47F22D5701A7' '491DCA2C00A9.pas.ms.script' // TnsDocumentPreview
 ;

ref; // ME_511CFADA024A 

: ME_511CFB0E0380
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_48F8A8480224' '4802FF41005C.pas.ms.script' // TevTreeStorable
 ;

ref; // ME_511CFB0E0380 

: ME_511CFB3502D8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_47F2317F015E' '491DCA2C00A9.pas.ms.script' // TnsHAFPainter
 ;

ref; // ME_511CFB3502D8 

: ME_511CFB5602D0
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_4954878B03CF' '47EA968D0155.pas.ms.script' // TevFormatHAFMacroReplacer
 ;

ref; // ME_511CFB5602D0 

: ME_511CFB8B0190
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_4958968201A7' '47EA50050263.pas.ms.script' // TnsDocInfoHAFMacroReplacer
 ;

ref; // ME_511CFB8B0190 

: ME_511CFF790012
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_49E615DB01E9' '4678209200A6.pas.ms.script' // PreviewKeys
 ;

ref; // ME_511CFF790012 

: ME_511CFFAF01F2
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_4AC0B9CF018A' '47D0E1500033.pas.ms.script' // vcmCStr
 ;

ref; // ME_511CFFAF01F2 

: ME_5243F3C3004B
 CONST Class class_Dependency
 : Stereotype st_ContextMenuWeight::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_49521D8203A0' '494F898C013E.pas.ms.script' // File
 ;
 CONST "Value" 10

ref; // ME_5243F3C3004B 

: ME_5243F3DE0124
 CONST Class class_Dependency
 : Stereotype st_ContextMenuWeight::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_4951282D0269' '495127DD017C.pas.ms.script' // Edit
 ;
 CONST "Value" 20

ref; // ME_5243F3DE0124 

: ME_5243F3FA0213
 CONST Class class_Dependency
 : Stereotype st_ContextMenuWeight::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_4C864A770147' '498874B90391.pas.ms.script' // Attribute
 ;
 CONST "Value" 30

ref; // ME_5243F3FA0213 

: ME_5243F4640073
 CONST Class class_Dependency
 : Stereotype st_ContextMenuWeight::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_4BDAF7790158' '4BDAF7510113.pas.ms.script' // Tree
 ;
 CONST "Value" 40

ref; // ME_5243F4640073 

: ME_5243F79600F3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_4BDAF7790158' '4BDAF7510113.pas.ms.script' // Tree
 ;

ref; // ME_5243F79600F3 

: ME_55BF979A025A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_48FF556602BA' '48F747EC0073.pas.ms.script' // DataAdapter
 ;

ref; // ME_55BF979A025A 

: ME_AE7A8771F66C
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C8647C8024E // PrimAttributesOptions
 ;
 : Target WL 'ME_561F9F9400BC' '561F9F7D02A7.pas.ms.script' // TtfwClassRef
 ;

ref; // ME_AE7A8771F66C 

: ME_49521D8E0295_ME_4C8647C8024E
 : Original WL 'ME_49521D8E0295' '494F898C013E.pas.ms.script' // Print
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" true
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_49521D8E0295_ME_4C8647C8024E Print

: ME_495220DE0298_ME_4C8647C8024E
 : Original WL 'ME_495220DE0298' '494F898C013E.pas.ms.script' // PrintDialog
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" false
 CONST "ShowInToolbar" true
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_495220DE0298_ME_4C8647C8024E PrintDialog

: ME_495220F2033A_ME_4C8647C8024E
 : Original WL 'ME_495220F2033A' '494F898C013E.pas.ms.script' // PrintPreview
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" true
 CONST "ShowInToolbar" true
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_495220F2033A_ME_4C8647C8024E PrintPreview

: ME_4C7D0C7B0185_ME_4C8647C8024E
 : Original WL 'ME_4C7D0C7B0185' '495127DD017C.pas.ms.script' // Copy
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" true
 CONST "ShowInToolbar" true
 CONST "has states" true
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4C7D0C7B0185_ME_4C8647C8024E Copy

: ME_4C864A87020E_ME_4C8647C8024E
 : Original WL 'ME_4C864A87020E' '498874B90391.pas.ms.script' // Copy
 ;
 CONST OpKind opkind_Implemented
 CONST "AutoFocus" false
 CONST "AutoLock" false
 CONST "LongProcess" false
 CONST "ShowInContextMenu" true
 CONST "ShowInToolbar" false
 CONST "has states" false
 CONST "is FormActivate" false
 CONST "is query" false
 CONST "no prefix" false
ref; // ME_4C864A87020E_ME_4C8647C8024E Copy

: ME_497469C90140_ME_4C8647C8024E
 : Original WL 'ME_497469C90140' '5000041101C8.pas.ms.script' // NotifyDataSourceChanged
 ;
 CONST OpKind opkind_Overridden
ref; // ME_497469C90140_ME_4C8647C8024E NotifyDataSourceChanged

: ME_49803F5503AA_ME_4C8647C8024E
 : Original WL 'ME_49803F5503AA' '4AADF9450143.pas.ms.script' // DoInit
 ;
 CONST OpKind opkind_Overridden
ref; // ME_49803F5503AA_ME_4C8647C8024E DoInit

: ME_4A8E8F2E0195_ME_4C8647C8024E
 : Original WL 'ME_4A8E8F2E0195' '5000041101C8.pas.ms.script' // InitControls
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4A8E8F2E0195_ME_4C8647C8024E InitControls

: ME_4C8647C8024E
 CONST UID '4C8647C8024E'
 CONST Name 'PrimAttributesOptions'
 CONST Class class_Class
 : Stereotype st_VCMForm ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4D39AD3200C1 // Attributes
 ;
 : Inherits
   Seq: ( ME_4979DA14019A // PrimAttributes
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4951282D0269' '495127DD017C.pas.ms.script' // Edit
 WL 'ME_49521D8203A0' '494F898C013E.pas.ms.script' // File
 WL 'ME_4C864A770147' '498874B90391.pas.ms.script' // Attribute
 )
 ; // Implements
 : Attributes
   Seq: ( ME_511A3E2A0297 // tvAttributes
 )
 ; // Attributes
 : Operations
   Seq: ( ME_4C864C08016E // MakePreview
 ME_4C864DD70182 // HasTree
 ME_511A3C6F0383 // tvAttributesGetItemImage
 ME_511A3D5D01FA // tvAttributesMakeTreeSource
 ME_BE4B3C1AAA12 // Ini_Reg_Class
 )
 ; // Operations
 : Implemented
   Seq: ( ME_49521D8E0295_ME_4C8647C8024E // Print
 ME_495220DE0298_ME_4C8647C8024E // PrintDialog
 ME_495220F2033A_ME_4C8647C8024E // PrintPreview
 ME_4C7D0C7B0185_ME_4C8647C8024E // Copy
 ME_4C864A87020E_ME_4C8647C8024E // Copy
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_497469C90140_ME_4C8647C8024E // NotifyDataSourceChanged
 ME_49803F5503AA_ME_4C8647C8024E // DoInit
 ME_4A8E8F2E0195_ME_4C8647C8024E // InitControls
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_4C864DF70054 // afwFacade
 ME_4C864E0C0307 // l3Base
 ME_4C864E5D0353 // TevTreeDataObject
 ME_4C864E79006E // TevTreeStorableData
 ME_4C864E9C00FB // TnsSingleAttributeData
 ME_4C864EBF0350 // Il3SimpleTree
 ME_4C86508700C1 // FlagsConst
 ME_4D3EAA2600D3 // Printers
 ME_500572B80283 // TnsDocumentRes
 ME_511A6AAC03E1 // IeeNode
 ME_511A6B00010E // Controls
 ME_511A6B060305 // Forms
 ME_511A6B31020C // TvtViewOption
 ME_511CFADA024A // TnsDocumentPreview
 ME_511CFB0E0380 // TevTreeStorable
 ME_511CFB3502D8 // TnsHAFPainter
 ME_511CFB5602D0 // TevFormatHAFMacroReplacer
 ME_511CFB8B0190 // TnsDocInfoHAFMacroReplacer
 ME_511CFF790012 // PreviewKeys
 ME_511CFFAF01F2 // vcmCStr
 ME_5243F3C3004B // File
 ME_5243F3DE0124 // Edit
 ME_5243F3FA0213 // Attribute
 ME_5243F4640073 // Tree
 ME_5243F79600F3 // Tree
 ME_55BF979A025A // DataAdapter
 ME_AE7A8771F66C // TtfwClassRef
 )
 ; // Dependencies
 CONST "NeedsHackRef" true
 CONST "ZoneType" 'Any'
 CONST "author" 'Люлин А.В.'
 CONST "finished dfm" true
 CONST "no hands" true
 CONST "resizeable" false
 CONST "restrict form def" 'undefined'
 CONST "started" '07.09.2010 18:10'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\PrimAttributesOptions_Form.pas'
 CONST extprop:pas:TypeName 'TPrimAttributesOptionsForm'
 CONST extprop:rc:SelfName 'PrimAttributesOptionsForm'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'PrimAttributesOptions_Form'
 CONST extprop:NeedsInitEntities true

ref; // ME_4C8647C8024E PrimAttributesOptions

: ME_4D39AD3200C1
 CONST UID '4D39AD3200C1'
 CONST Name 'Attributes'
 CONST Class class_Category
 : Stereotype st_VCMForms ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4A9F76D70283' '4A9F76D70283.pas.ms.script' // View
 ;
 : Children
   Seq: ( ME_4979DA14019A // PrimAttributes
 ME_4C8647C8024E // PrimAttributesOptions
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 WL 'ME_4570511E038A' '4570511E038A.pas.ms.script' // Document
 WL 'ME_457450470167' '457450470167.pas.ms.script' // DynamicTree
 WL 'ME_45ED58CF03E6' '45ED58CF03E6.pas.ms.script' // Logging
 WL 'ME_4678209200A6' '4678209200A6.pas.ms.script' // nevBase
 WL 'ME_467823B7002C' '467823B7002C.pas.ms.script' // afwInterfaces
 WL 'ME_4682595B0268' '4682595B0268.pas.ms.script' // l3TreeInterfaces
 WL 'ME_47750CE700D0' '47750CE700D0.pas.ms.script' // afwFacade
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_4799D29F033F' '4799D29F033F.pas.ms.script' // Implementation
 WL 'ME_47D036150077' '47D036150077.pas.ms.script' // l3ControlsTypes
 WL 'ME_47D0E1500033' '47D0E1500033.pas.ms.script' // Implementation
 WL 'ME_47EA50050263' '47EA50050263.pas.ms.script' // BaseDocument
 WL 'ME_47EA968D0155' '47EA968D0155.pas.ms.script' // Printing
 WL 'ME_4802FF41005C' '4802FF41005C.pas.ms.script' // DataObjects
 WL 'ME_48F5EE2702FF' '48F5EE2702FF.pas.ms.script' // DocumentDataObjects
 WL 'ME_48F747EC0073' '48F747EC0073.pas.ms.script' // Common
 WL 'ME_4912DD020283' '4912DD020283.pas.ms.script' // eeInterfaces
 WL 'ME_491B305A0096' '491B305A0096.pas.ms.script' // DocumentAndListInterfaces
 WL 'ME_491DCA2C00A9' '491DCA2C00A9.pas.ms.script' // Search
 WL 'ME_494F898C013E' '494F898C013E.pas.ms.script' // Usual
 WL 'ME_495127DD017C' '495127DD017C.pas.ms.script' // Text
 WL 'ME_498874B90391' '498874B90391.pas.ms.script' // Strange
 WL 'ME_499C2614028C' '499C2614028C.pas.ms.script' // Tree
 WL 'ME_4A7C0BB70162' '4A7C0BB70162.pas.ms.script' // Base Forms
 WL 'ME_4A8EC95E015F' '4A8EC95E015F.pas.ms.script' // InternalOperations
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_4AEEE2A40281' '4AEEE2A40281.pas.ms.script' // Strange
 WL 'ME_4B0A60DF01F2' '4B0A60DF01F2.pas.ms.script' // Logging
 WL 'ME_4BDAF7510113' '4BDAF7510113.pas.ms.script' // Tree
 WL 'ME_4D383D6E01B6' '4D383D6E01B6.pas.ms.script' // BaseDocument
 WL 'ME_4F71AD0E01FE' '4F71AD0E01FE.pas.ms.script' // InternalOperations
 WL 'ME_52DE57B200A5' '52DE57B200A5.pas.ms.script' // Tree$WithDnD
 WL 'ME_55C4AEB903E1' '55C4AEB903E1.pas.ms.script' // Printing
 WL 'ME_561F9F7D02A7' '561F9F7D02A7.pas.ms.script' // ScriptEngine
 )
 ; // Depends

ref; // ME_4D39AD3200C1 Attributes
