// DocumentListFromFile 4DA44B030054 VCMUseCaseRealization Class

INCLUDE 'ElementsRTTI.ms.dict'

: ME_4DA44B030054
 CONST UID '4DA44B030054'
 CONST Name 'DocumentListFromFile'
 CONST Class class_Class
 : Stereotype st_VCMUseCaseRealization ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Список документов из файла' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent WL 'ME_4DA44AAD00AD' '4DA44AAD00AD.pas.ms.script' // DocumentListFromFile
 ;
 : Inherits
   Seq: ( WL 'ME_4DA44B2C01BB' '4DA44B2C01BB.pas.ms.script' // PrimDocumentListFromFile
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_484CE5E503D4' '484CE48E02E6.pas.ms.script' // Просмотр списка
 )
 ; // Implements
 CONST "author" 'Люлин А.В.'
 CONST "no hands" true
 CONST "started" '12.04.2011 16:54'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\moDocumentListFromFile.pas'
 CONST intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'
 CONST extprop:pas:TypeName 'Tmo_DocumentListFromFile'
 CONST extprop:rc:SelfName 'mo_DocumentListFromFile'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'moDocumentListFromFile'

ref; // ME_4DA44B030054 DocumentListFromFile
