// ScriptDebugger 4DB14DDC01A9 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4DB14DDC01A9

FORWARD ME_4DB1629901E8

FORWARD ME_4DB14E0A029D

ME ME_4DB14E2D007D
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4DB14E0A029D // TtfwScriptDebugger_Form
 ;
 MELINK Target WL 'ME_4DAECE5D0060' '4B30FC850092.ms.model.script' // TvcmInsiderTest
 ;

ENDME // ME_4DB14E2D007D 

ME ME_4DB1661901AB
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4DB14E0A029D // TtfwScriptDebugger_Form
 ;
 MELINK Target WL 'ME_4DAEEA9E0049' '4DAEEA14018A.ms.model.script' // TtfwScriptEngine
 ;

ENDME // ME_4DB1661901AB 

ME ME_4DB14E0A029D
 MEPROP UID '4DB14E0A029D'
 MEPROP Name 'TtfwScriptDebugger_Form'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4DB1629901E8 // tfwScriptDebugger
 ;
 MELIST Dependencies
   Seq: ( ME_4DB14E2D007D // TvcmInsiderTest
 ME_4DB1661901AB // TtfwScriptEngine
 )
 ; // Dependencies
 UP "author" 'Ëþëèí À.Â.'
 UP "finished" false
 UP "started" '22.04.2011 13:45'
 UP extprop:rc:SelfName 'ScriptDebugger_Form'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_4DB14E0A029D TtfwScriptDebugger_Form

ME ME_4DB1629901E8
 MEPROP UID '4DB1629901E8'
 MEPROP Name 'tfwScriptDebugger'
 MEPROP Class class_Class
 MELINK Stereotype st_UtilityPack ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4DB14DDC01A9 // ScriptDebugger
 ;
 MELIST Children
   Seq: ( HWL ME_4DB14E0A029D // TtfwScriptDebugger_Form
 )
 ; // Children
 UP "author" 'Ëþëèí À.Â.'
 UP "finished" false
 UP "started" '22.04.2011 15:12'
 UP intf.pas:Path 'common\components\rtl\Garant\DUnitTuning\NOT_FINISHED_tfwScriptDebugger.pas'
 UP extprop:rc:SelfName 'ScriptDebugger'

ENDME // ME_4DB1629901E8 tfwScriptDebugger

ME ME_4DB14DDC01A9
 MEPROP UID '4DB14DDC01A9'
 MEPROP Name 'ScriptDebugger'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4B2A10C40309' '4B2A10C40309.ms.model.script' // DUnitTuning
 ;
 MELIST Children
   Seq: ( HWL ME_4DB1629901E8 // tfwScriptDebugger
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_4B30FC850092' '4B30FC850092.ms.model.script' // VCM_TFW
 WL 'ME_4DAEEA14018A' '4DAEEA14018A.ms.model.script' // Scripting Axiomatics
 WL 'ME_4DAF19F600C5' '4DAF19F600C5.ms.model.script' // tfwScriptingInterfaces
 )
 ; // Depends
 UP "ifdef" 'InsiderTest'
 UP "ifndef" 'NoScripts'

ENDME // ME_4DB14DDC01A9 ScriptDebugger
