// Was_Wait 4DB94B3103DB ScriptKeyword Class

INCLUDE '53EDC0E701BC.pas.ms.script'

INCLUDE '5093D47602BF.pas.ms.script'

INCLUDE '4DAF19F600C5.pas.ms.script'

INCLUDE '54D229E702B6.pas.ms.script'

FORWARD ME_4DB94B3103DB

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_38BB7E627EFD
 CONST UID '38BB7E627EFD'
 CONST Name 'Ini_Reg'
 CONST Class 'Operation'
 CONST Stereotype 'ini'
 %SUMMARY 'Регистрация Was_Wait' ;
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_38BB7E627EFD Ini_Reg

: ME_4DB94B3103DB
 CONST UID '4DB94B3103DB'
 CONST Name 'Was_Wait'
 CONST Class 'Class'
 CONST Stereotype 'ScriptKeyword'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_53EDC0E701BC // TtfwRegisterableWord
 ]
 ; // Inherits
 : Implements
   [ ME_5093D47602BF // afwImpurity
 ]
 ; // Implements
 : Operations
   [ ME_38BB7E627EFD // Ini_Reg
 ]
 ; // Operations
 : Implemented
   [ ME_4DAEEDE10285 // DoDoIt
 ]
 ; // Implemented
 : Overridden
   [ ME_4DB0614603C8 // GetWordNameForRegister
 ]
 ; // Overridden
 CONST "NameForScript" 'waited:?'
 CONST "author" 'Люлин А.В.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '28.04.2011 15:11'

 @SELF
; // ME_4DB94B3103DB Was_Wait
