// DEFAULT 4DBAF3D60039 ScriptKeyword Class

INCLUDE '53EDC0E701BC.pas.ms.script'

INCLUDE '4DAF19F600C5.pas.ms.script'

INCLUDE '54D229E702B6.pas.ms.script'

FORWARD ME_4DBAF3D60039

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_0C36A52A2CA7
 CONST UID '0C36A52A2CA7'
 CONST Name 'Ini_Reg'
 CONST Class 'Operation'
 CONST Stereotype 'ini'
 %SUMMARY 'Регистрация DEFAULT' ;
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_0C36A52A2CA7 Ini_Reg

: ME_4DBAF3D60039
 CONST UID '4DBAF3D60039'
 CONST Name 'DEFAULT'
 CONST Class 'Class'
 CONST Stereotype 'ScriptKeyword'
 %SUMMARY 'Внутреннее слово для определения ветки по умолчанию в скомпилированном Case. Не предназначено для прямого вызова.' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_53EDC0E701BC // TtfwRegisterableWord
 ]
 ; // Inherits
 : Operations
   [ ME_0C36A52A2CA7 // Ini_Reg
 ]
 ; // Operations
 : Implemented
   [ ME_4DAEEDE10285 // DoDoIt
 ]
 ; // Implemented
 : Overridden
   [ ME_4DB0614603C8 // GetWordNameForRegister
 ME_4DBAF4630154 // IsDefaultBranch
 ]
 ; // Overridden
 CONST "author" 'Люлин А.В.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '29.04.2011 21:23'

 @SELF
; // ME_4DBAF3D60039 DEFAULT
