// DocumentFilters 4DCD537F0284 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4DCD537F0284

ME ME_4DCD537F0284
 MEPROP UID '4DCD537F0284'
 MEPROP Name 'DocumentFilters'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4C6A65ED0374' // F1DocumentProcessing
 ;
 MELIST Children
   Seq: ( WL? 'ME_4DCD5932009E' // Tf1MultilinkResolver
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_456EA56002BF' // BaseTypes
 WL? 'ME_4570511E038A' // Document
 WL? 'ME_4678137501EA' // k2Interfaces
 WL? 'ME_469D0AC7005E' // Types
 WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_47AC75550330' // k2Tags
 WL? 'ME_47ECB8BD00A8' // Generators
 WL? 'ME_48492FC0029D' // Standard
 WL? 'ME_484A470100DD' // Standard
 WL? 'ME_49A58A1A03C4' // k2PrimObjects
 WL? 'ME_4A4DE16302A2' // k2Core
 WL? 'ME_4AB0C3C60310' // Sys
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_4DCD537F0284 DocumentFilters
