// Стандартные компоненты 4E36644A0023 Requirements Category

INCLUDE 'ElementsRTTI.ms.dict'

: ME_4E36644A0023
 CONST UID '4E36644A0023'
 CONST Name 'Стандартные компоненты'
 CONST Class class_Category
 : Stereotype st_Requirements ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4E78C3EC018D' '4E78C3EC018D.pas.ms.script' // Shared Delphi Требования
 ;
 : Children
   Seq: ( WL 'ME_4E365B6002CA' '4E365B6002CA.pas.ms.script' // Отображение списков
 WL 'ME_4E36C0130013' '4E36C0130013.pas.ms.script' // Контролы с закладками
 WL 'ME_4E57B8C2010F' '4E57B8C2010F.pas.ms.script' // Требования к схеме документа EVD
 WL 'ME_4E5CF70B01E2' '4E5CF70B01E2.pas.ms.script' // Требования к редактору Эверест
 WL 'ME_4E650454009C' '4E650454009C.pas.ms.script' // Требования к контролам VGScene
 WL 'ME_4E96FFD70348' '4E96FFD70348.pas.ms.script' // Поля ввода
 WL 'ME_4E79FA920283' '4E79FA920283.pas.ms.script' // Плавающие окна
 WL 'ME_4E8587AE01D0' '4E8587AE01D0.pas.ms.script' // Требования к диалоговым окнам
 WL 'ME_4E787E1E02F8' '4E787E1E02F8.pas.ms.script' // Редактор с выпадающим деревом
 WL 'ME_4F266203018F' '4F266203018F.pas.ms.script' // NSRC
 )
 ; // Children

ref; // ME_4E36644A0023 Стандартные компоненты
