// DataBase 4E4B5C5E0032 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4E4B5C5E0032

FORWARD ME_4E4B5C770387

: ME_4E4B5C8E01C8
 CONST UID '4E4B5C8E01C8'
 CONST Name 'InitBaseEngine'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_4E4B5C770387 // ddHTinit
 ;

ref; // ME_4E4B5C8E01C8 InitBaseEngine

: ME_4E4B5C770387
 CONST UID '4E4B5C770387'
 CONST Name 'ddHTinit'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_4E4B5C5E0032 // DataBase
 ;
 : Operations
   Seq: ( HWL ME_4E4B5C8E01C8 // InitBaseEngine
 )
 ; // Operations
 CONST "finished" false
 CONST intf.pas:Path 'common\components\rtl\Garant\dd\NOT_FINISHED_ddHTinit.pas'

ref; // ME_4E4B5C770387 ddHTinit

: ME_4E4B5C5E0032
 CONST UID '4E4B5C5E0032'
 CONST Name 'DataBase'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4677E18600C2' '4677E18600C2.pas.ms.script' // dd
 ;
 : Children
   Seq: ( HWL ME_4E4B5C770387 // ddHTinit
 )
 ; // Children
 CONST "finished" false

ref; // ME_4E4B5C5E0032 DataBase
