// Shared Delphi Требования к низкоуровневым библиотекам 4E5BC50E02E1 Project Category

INCLUDE 'ElementsRTTI.ms.dict'

: ME_4E5BC50E02E1
 CONST UID '4E5BC50E02E1'
 CONST Name 'Shared Delphi Требования к низкоуровневым библиотекам'
 CONST Class class_Category
 : Stereotype st_Project ;
 %SUMMARY 'Требования и базовые понятия системных библиотек' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Children
   @ ( WL 'ME_4E2F0E1B03BB' '4E2F0E1B03BB.pas.ms.script' // L3$Domain
 WL 'ME_515AC89F01E1' '515AC89F01E1.pas.ms.script' // L3$Basic Concepts
 ) .SequenceCode.It
 ; // Children
 : Depends
   @ ( WL 'ME_49B1511700CA' '49B1511700CA.pas.ms.script' // Shared Delphi Core
 WL 'ME_4E78C3EC018D' '4E78C3EC018D.pas.ms.script' // Shared Delphi Требования
 ) .SequenceCode.It
 ; // Depends
 CONST "Full MDP" false
 CONST "create project" true
 CONST "fix version" 0
 CONST "force usage" true
 CONST "full constraint" true
 CONST "major version" 1
 CONST "minor version" 0
 CONST "package prefix" 'ru.garant'
 CONST "root path suffix" '/components'
 CONST "space key" 'SHD'
 CONST "space name" 'Shared (delphi)'
 : Generators
 @ (
 gen_forth_structure
 gen_intf.pas
 gen_pas.script
 gen_pas.script.runner
 ) .SequenceCode.It
 ; // Generators
 CONST forth_structure:Path 'shared\models\NewSchool\Shared Delphi Требования к низкоуровневым библиотекам\Shared Delphi Требования к низкоуровневым библиотекам.model.script'
 CONST intf.pas:Path 'common\components\common Требования к низкоуровневым библиотекам_prj.info'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\4E5BC50E02E1.pas.ms.script'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\4E5BC50E02E1.pas.ms.script.runner'

ref; // ME_4E5BC50E02E1 Shared Delphi Требования к низкоуровневым библиотекам
