// Требования к утилите экспорта 4E7729D3033C Requirements Category

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_4E7729D3033C
 MEPROP UID '4E7729D3033C'
 MEPROP Name 'Требования к утилите экспорта'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Requirements ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4E77299200D0' // archi$PipeOut2
 ;

ENDME // ME_4E7729D3033C Требования к утилите экспорта
