// vcm_History_DeleteBackItem 4E82CEBA0299 ScriptKeyword Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4DB94A660083_ME_4E82CEBA0299_R
 MELINK Original WL? 'ME_4DB94A660083' // VCMWord
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4DB94A660083_ME_4E82CEBA0299_R VCMWord

%%ImplementedBy ME_4DB94A660083 ME_4E82CEBA0299

ME ME_4E82CEBA0299
 MEPROP UID '4E82CEBA0299'
 MEPROP Name 'vcm_History_DeleteBackItem'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_ScriptKeyword ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Удаляет один элемент истории из списка Back.'#13#10' *Пример:*'#13#10'{code}'#13#10' моп::Поиск_Поиск_лекарственного_средства'#13#10' ''AT_PHARM_NAME'' ''Аргинин'' Search:SetAttribute'#13#10' ''AT_PHARM_ATC'' ''A. Пищеварительный тракт и обмен веществ'' Search:SetAttribute'#13#10' ''AT_PHARM_ATC'' ''B. Препараты влияющие на кроветворение и кровь'' Search:SetAttribute'#13#10' Ok'#13#10' OnTest'#13#10' vcm:history:DeleteBackItem'#13#10'{code}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4F69B9040391' // VCMWords
 ;
 MELIST Implements
   Seq: ( ME_4DB94A660083_ME_4E82CEBA0299_R // VCMWord
 )
 ; // Implements
 UP "author" 'Люлин А.В.'
 UP "ifndef" 'NoVCM'
 UP "no hands" true
 UP "started" '28.09.2011 11:37'
 UP intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Scripting\kwVcmHistoryDeleteBackItem.pas'
 UP extprop:pas:TypeName 'TkwVcmHistoryDeleteBackItem'
 UP extprop:rc:SelfName 'VcmHistoryDeleteBackItem'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'kwVcmHistoryDeleteBackItem'

ENDME // ME_4E82CEBA0299 vcm_History_DeleteBackItem
