// Tdd_lcPageNumberEliminator 4EA5353F022A SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4D53D8A100AE_ME_4EA5353F022A_G
 MELINK Original WL 'ME_4D53D8A100AE' '49E496880120.ms.model.script' // TevdChildBufferedFilter
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4D53D8A100AE_ME_4EA5353F022A_G TevdChildBufferedFilter

%%InheritedBy ME_4D53D8A100AE ME_4EA5353F022A

ME ME_4EA5353F022A
 MEPROP UID '4EA5353F022A'
 MEPROP Name 'Tdd_lcPageNumberEliminator'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Удаляет псевдономера страниц из текста судебных постановлений' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4B324F930103' // Filters
 ;
 MELIST Inherits
   Seq: ( ME_4D53D8A100AE_ME_4EA5353F022A_G // TevdChildBufferedFilter
 )
 ; // Inherits
 UP "finished" false
 UP intf.pas:Path 'common\components\rtl\Garant\dd\NOT_FINISHED_dd_lcPageNumberEliminator.pas'
 UP extprop:rc:SelfName 'dd_lcPageNumberEliminator'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'dd_lcPageNumberEliminator'

ENDME // ME_4EA5353F022A Tdd_lcPageNumberEliminator
