// Dialogs 4ECB871B0028 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4ECB871B0028
%%Inner ME_4ECB871B0028
%%Inner ME_4ECB871B0028
%%Inner ME_4ECB871B0028
%%Inner ME_4ECB871B0028
%%Inner ME_4ECB871B0028

ME ME_4ECB871B0028
 MEPROP UID '4ECB871B0028'
 MEPROP Name 'Dialogs'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4DE803840174' '4DE803840174.ms.model.script' // Dlg
 ;
 MELIST Children
   Seq: ( WL 'ME_4ECB874E0247' '4ECB874E0247.ms.model.script' // d_GetContents
 WL 'ME_4F8D26D303CB' '4F8D26D303CB.ms.model.script' // D_Srch
 WL 'ME_4F8D5C7802F6' '4F8D5C7802F6.ms.model.script' // D_SchRes
 WL 'ME_4F910CF600C9' '4F910CF600C9.ms.model.script' // D_GetNum
 WL 'ME_50163EBB0377' '50163EBB0377.ms.model.script' // D_NameEd
 WL 'ME_53EC88D6039A' '53EC88D6039A.ms.model.script' // D_ShowInfo
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_4E202BD501B7' '4E202BD501B7.ms.model.script' // BaseForms
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames

ENDME // ME_4ECB871B0028 Dialogs
