// StringProcessing 4ED7958E0045 ScriptKeywords Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4ED7958E0045

FORWARD ME_55682D8F01C7

FORWARD ME_56F3EEE50232

: ME_56F3EEFA0215
 CONST UID '56F3EEFA0215'
 CONST Name 'f_String'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent ME_56F3EEE50232 // TtfwStringIterator
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_56F3EEFA0215 f_String

FORWARD ME_56F3EF17004C

: ME_56F3EF27039D
 CONST Name 'aString'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_56F3EF27039D aString

: ME_56F3EF1D03E2
 CONST UID '56F3EF1D03E2'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_56F3EF17004C // Create
 ;
 : Parameters
   Seq: ( ME_56F3EF27039D // aString
 )
 ; // Parameters

ref; // ME_56F3EF1D03E2 DoIt

: ME_56F3EF17004C
 CONST UID '56F3EF17004C'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_56F3EEE50232 // TtfwStringIterator
 ;
 : Operations
   Seq: ( ME_56F3EF1D03E2 // DoIt
 )
 ; // Operations

ref; // ME_56F3EF17004C Create

: ME_56F3EF2B012F
 CONST UID '56F3EF2B012F'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_56F3EEE50232 // TtfwStringIterator
 ;
 : Inherits
   Seq: ( ME_56F3EF17004C // Create
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4DCC12FC0125' '4DAF19F600C5.pas.ms.script' // ItfwValueList
 )
 ; // Implements

ref; // ME_56F3EF2B012F Make

: ME_52E23B7A00EC_ME_56F3EEE50232
 : Original WL 'ME_52E23B7A00EC' '4DAF19F600C5.pas.ms.script' // ForEach
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52E23B7A00EC_ME_56F3EEE50232 ForEach

: ME_52E23BB102FA_ME_56F3EEE50232
 : Original WL 'ME_52E23BB102FA' '4DAF19F600C5.pas.ms.script' // ForEachBack
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52E23BB102FA_ME_56F3EEE50232 ForEachBack

: ME_55CDF40C03D4_ME_56F3EEE50232
 : Original WL 'ME_55CDF40C03D4' '4DAF19F600C5.pas.ms.script' // SetItem
 ;
 CONST OpKind opkind_Implemented
ref; // ME_55CDF40C03D4_ME_56F3EEE50232 SetItem

: ME_55E849210175_ME_56F3EEE50232
 : Original WL 'ME_55E849210175' '4DAF19F600C5.pas.ms.script' // ItemsCountInSlice
 ;
 CONST OpKind opkind_Implemented
ref; // ME_55E849210175_ME_56F3EEE50232 ItemsCountInSlice

: ME_56F3EEE50232
 CONST UID '56F3EEE50232'
 CONST Name 'TtfwStringIterator'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_52E29ED5016B' '54F0A4A302FF.pas.ms.script' // TtfwIteratableParent
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4DCC12FC0125' '4DAF19F600C5.pas.ms.script' // ItfwValueList
 )
 ; // Implements
 : Attributes
   Seq: ( ME_56F3EEFA0215 // f_String
 )
 ; // Attributes
 : Operations
   Seq: ( ME_56F3EF17004C // Create
 ME_56F3EF2B012F // Make
 )
 ; // Operations
 : Implemented
   Seq: ( ME_52E23B7A00EC_ME_56F3EEE50232 // ForEach
 ME_52E23BB102FA_ME_56F3EEE50232 // ForEachBack
 ME_55CDF40C03D4_ME_56F3EEE50232 // SetItem
 ME_55E849210175_ME_56F3EEE50232 // ItemsCountInSlice
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'StringIterator'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_56F3EEE50232 TtfwStringIterator

FORWARD ME_55682E07017A

FORWARD ME_0093B3082714

: ME_4DAEEDE10285_ME_0093B3082714
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_0093B3082714 DoDoIt

: ME_0093B3082714
 CONST UID '0093B3082714'
 CONST Name 'StartsStr'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта StartsStr' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_0093B3082714 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'StartsStr'
 CONST extprop:pas:TypeName 'TkwStartsStr'
 CONST extprop:rc:SelfName 'StartsStr'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55682E07017A // StartsStr
 ;

ref; // ME_0093B3082714 StartsStr

FORWARD ME_55682E2503B9

FORWARD ME_9996D7566EDE

: ME_4DAEEDE10285_ME_9996D7566EDE
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_9996D7566EDE DoDoIt

: ME_9996D7566EDE
 CONST UID '9996D7566EDE'
 CONST Name 'StartsText'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта StartsText' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_9996D7566EDE // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'StartsText'
 CONST extprop:pas:TypeName 'TkwStartsText'
 CONST extprop:rc:SelfName 'StartsText'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55682E2503B9 // StartsText
 ;

ref; // ME_9996D7566EDE StartsText

FORWARD ME_55682E4401ED

FORWARD ME_397C461D6C30

: ME_4DAEEDE10285_ME_397C461D6C30
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_397C461D6C30 DoDoIt

: ME_397C461D6C30
 CONST UID '397C461D6C30'
 CONST Name 'EndsStr'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта EndsStr' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_397C461D6C30 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'EndsStr'
 CONST extprop:pas:TypeName 'TkwEndsStr'
 CONST extprop:rc:SelfName 'EndsStr'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55682E4401ED // EndsStr
 ;

ref; // ME_397C461D6C30 EndsStr

FORWARD ME_55682E4F033B

FORWARD ME_8997C15C6CA8

: ME_4DAEEDE10285_ME_8997C15C6CA8
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_8997C15C6CA8 DoDoIt

: ME_8997C15C6CA8
 CONST UID '8997C15C6CA8'
 CONST Name 'EndsText'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта EndsText' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_8997C15C6CA8 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'EndsText'
 CONST extprop:pas:TypeName 'TkwEndsText'
 CONST extprop:rc:SelfName 'EndsText'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55682E4F033B // EndsText
 ;

ref; // ME_8997C15C6CA8 EndsText

FORWARD ME_55682E5E01E1

FORWARD ME_2309401B7CC1

: ME_4DAEEDE10285_ME_2309401B7CC1
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_2309401B7CC1 DoDoIt

: ME_2309401B7CC1
 CONST UID '2309401B7CC1'
 CONST Name 'SameStr'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта SameStr' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_2309401B7CC1 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'SameStr'
 CONST extprop:pas:TypeName 'TkwSameStr'
 CONST extprop:rc:SelfName 'SameStr'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55682E5E01E1 // SameStr
 ;

ref; // ME_2309401B7CC1 SameStr

FORWARD ME_55682E72033C

FORWARD ME_9FC28ACB9AA1

: ME_4DAEEDE10285_ME_9FC28ACB9AA1
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_9FC28ACB9AA1 DoDoIt

: ME_9FC28ACB9AA1
 CONST UID '9FC28ACB9AA1'
 CONST Name 'SameText'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта SameText' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_9FC28ACB9AA1 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'SameText'
 CONST extprop:pas:TypeName 'TkwSameText'
 CONST extprop:rc:SelfName 'SameText'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55682E72033C // SameText
 ;

ref; // ME_9FC28ACB9AA1 SameText

FORWARD ME_55682E84007F

FORWARD ME_C670925F6482

: ME_4DAEEDE10285_ME_C670925F6482
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_C670925F6482 DoDoIt

: ME_C670925F6482
 CONST UID 'C670925F6482'
 CONST Name 'CompareStr'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта CompareStr' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_C670925F6482 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'CompareStr'
 CONST extprop:pas:TypeName 'TkwCompareStr'
 CONST extprop:rc:SelfName 'CompareStr'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55682E84007F // CompareStr
 ;

ref; // ME_C670925F6482 CompareStr

FORWARD ME_55682E9700FE

FORWARD ME_0E02A0729BA6

: ME_4DAEEDE10285_ME_0E02A0729BA6
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_0E02A0729BA6 DoDoIt

: ME_0E02A0729BA6
 CONST UID '0E02A0729BA6'
 CONST Name 'CompareText'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта CompareText' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_0E02A0729BA6 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'CompareText'
 CONST extprop:pas:TypeName 'TkwCompareText'
 CONST extprop:rc:SelfName 'CompareText'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55682E9700FE // CompareText
 ;

ref; // ME_0E02A0729BA6 CompareText

FORWARD ME_55682EA703B4

FORWARD ME_09008856C703

: ME_4DAEEDE10285_ME_09008856C703
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_09008856C703 DoDoIt

: ME_09008856C703
 CONST UID '09008856C703'
 CONST Name 'StrToInt'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта StrToInt' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_09008856C703 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'StrToInt'
 CONST extprop:pas:TypeName 'TkwStrToInt'
 CONST extprop:rc:SelfName 'StrToInt'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55682EA703B4 // StrToInt
 ;

ref; // ME_09008856C703 StrToInt

FORWARD ME_5568365E0395

FORWARD ME_DD57CECF347C

: ME_4DAEEDE10285_ME_DD57CECF347C
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_DD57CECF347C DoDoIt

: ME_DD57CECF347C
 CONST UID 'DD57CECF347C'
 CONST Name 'Cat'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта Cat' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_DD57CECF347C // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'Cat'
 CONST extprop:pas:TypeName 'TkwCat'
 CONST extprop:rc:SelfName 'Cat'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_5568365E0395 // Cat
 ;

ref; // ME_DD57CECF347C Cat

FORWARD ME_556840910148

FORWARD ME_5F306006344B

: ME_4DAEEDE10285_ME_5F306006344B
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_5F306006344B DoDoIt

: ME_5F306006344B
 CONST UID '5F306006344B'
 CONST Name 'string_ConsistsOf'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:ConsistsOf' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_5F306006344B // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:ConsistsOf'
 CONST extprop:pas:TypeName 'TkwStringConsistsOf'
 CONST extprop:rc:SelfName 'StringConsistsOf'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_556840910148 // string_ConsistsOf
 ;

ref; // ME_5F306006344B string_ConsistsOf

FORWARD ME_5568411F01E1

FORWARD ME_2256016890B3

: ME_4DAEEDE10285_ME_2256016890B3
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_2256016890B3 DoDoIt

: ME_2256016890B3
 CONST UID '2256016890B3'
 CONST Name 'string_HasAnyOf'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:HasAnyOf' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_2256016890B3 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:HasAnyOf'
 CONST extprop:pas:TypeName 'TkwStringHasAnyOf'
 CONST extprop:rc:SelfName 'StringHasAnyOf'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_5568411F01E1 // string_HasAnyOf
 ;

ref; // ME_2256016890B3 string_HasAnyOf

FORWARD ME_5568417001D5

FORWARD ME_851E99BEB53B

: ME_4DAEEDE10285_ME_851E99BEB53B
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_851E99BEB53B DoDoIt

: ME_851E99BEB53B
 CONST UID '851E99BEB53B'
 CONST Name 'string_Pos'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:Pos' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_851E99BEB53B // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:Pos'
 CONST extprop:pas:TypeName 'TkwStringPos'
 CONST extprop:rc:SelfName 'StringPos'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_5568417001D5 // string_Pos
 ;

ref; // ME_851E99BEB53B string_Pos

FORWARD ME_556841C601CF

FORWARD ME_24901BF384F4

: ME_4DAEEDE10285_ME_24901BF384F4
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_24901BF384F4 DoDoIt

: ME_24901BF384F4
 CONST UID '24901BF384F4'
 CONST Name 'string_PosEx'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:PosEx' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_24901BF384F4 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:PosEx'
 CONST extprop:pas:TypeName 'TkwStringPosEx'
 CONST extprop:rc:SelfName 'StringPosEx'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_556841C601CF // string_PosEx
 ;

ref; // ME_24901BF384F4 string_PosEx

FORWARD ME_5568423E01F3

FORWARD ME_AA63BC1F51EC

: ME_4DAEEDE10285_ME_AA63BC1F51EC
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_AA63BC1F51EC DoDoIt

: ME_AA63BC1F51EC
 CONST UID 'AA63BC1F51EC'
 CONST Name 'string_Split'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:Split' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_AA63BC1F51EC // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:Split'
 CONST extprop:pas:TypeName 'TkwStringSplit'
 CONST extprop:rc:SelfName 'StringSplit'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_5568423E01F3 // string_Split
 ;

ref; // ME_AA63BC1F51EC string_Split

FORWARD ME_5568520B03B5

FORWARD ME_8CA688C2805E

: ME_4DAEEDE10285_ME_8CA688C2805E
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_8CA688C2805E DoDoIt

: ME_8CA688C2805E
 CONST UID '8CA688C2805E'
 CONST Name 'string_Replace'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:Replace' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_8CA688C2805E // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:Replace'
 CONST extprop:pas:TypeName 'TkwStringReplace'
 CONST extprop:rc:SelfName 'StringReplace'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_5568520B03B5 // string_Replace
 ;

ref; // ME_8CA688C2805E string_Replace

FORWARD ME_5568523F03BE

FORWARD ME_FF1E0A42BBEF

: ME_4DAEEDE10285_ME_FF1E0A42BBEF
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_FF1E0A42BBEF DoDoIt

: ME_FF1E0A42BBEF
 CONST UID 'FF1E0A42BBEF'
 CONST Name 'string_ReplaceFirst'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:ReplaceFirst' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_FF1E0A42BBEF // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:ReplaceFirst'
 CONST extprop:pas:TypeName 'TkwStringReplaceFirst'
 CONST extprop:rc:SelfName 'StringReplaceFirst'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_5568523F03BE // string_ReplaceFirst
 ;

ref; // ME_FF1E0A42BBEF string_ReplaceFirst

FORWARD ME_556852510081

FORWARD ME_6F240EDBC3AE

: ME_4DAEEDE10285_ME_6F240EDBC3AE
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_6F240EDBC3AE DoDoIt

: ME_6F240EDBC3AE
 CONST UID '6F240EDBC3AE'
 CONST Name 'text_Replace'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта text:Replace' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_6F240EDBC3AE // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'text:Replace'
 CONST extprop:pas:TypeName 'TkwTextReplace'
 CONST extprop:rc:SelfName 'TextReplace'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_556852510081 // text_Replace
 ;

ref; // ME_6F240EDBC3AE text_Replace

FORWARD ME_5568525F008C

FORWARD ME_0527F8C9DF24

: ME_4DAEEDE10285_ME_0527F8C9DF24
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_0527F8C9DF24 DoDoIt

: ME_0527F8C9DF24
 CONST UID '0527F8C9DF24'
 CONST Name 'text_ReplaceFirst'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта text:ReplaceFirst' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_0527F8C9DF24 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'text:ReplaceFirst'
 CONST extprop:pas:TypeName 'TkwTextReplaceFirst'
 CONST extprop:rc:SelfName 'TextReplaceFirst'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_5568525F008C // text_ReplaceFirst
 ;

ref; // ME_0527F8C9DF24 text_ReplaceFirst

FORWARD ME_55685FAB0248

FORWARD ME_9597582C9BD4

: ME_4DAEEDE10285_ME_9597582C9BD4
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_9597582C9BD4 DoDoIt

: ME_9597582C9BD4
 CONST UID '9597582C9BD4'
 CONST Name 'string_Char'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:[i]' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_9597582C9BD4 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:[i]'
 CONST extprop:pas:TypeName 'TkwStringChar'
 CONST extprop:rc:SelfName 'StringChar'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55685FAB0248 // string_Char
 ;

ref; // ME_9597582C9BD4 string_Char

FORWARD ME_55685FD801DF

FORWARD ME_6CAF85926E0C

: ME_4DAEEDE10285_ME_6CAF85926E0C
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_6CAF85926E0C DoDoIt

: ME_6CAF85926E0C
 CONST UID '6CAF85926E0C'
 CONST Name 'string_CodePage'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:CodePage' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_6CAF85926E0C // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:CodePage'
 CONST extprop:pas:TypeName 'TkwStringCodePage'
 CONST extprop:rc:SelfName 'StringCodePage'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55685FD801DF // string_CodePage
 ;

ref; // ME_6CAF85926E0C string_CodePage

FORWARD ME_55685FF101AC

FORWARD ME_0BA6E62BEF84

: ME_4DAEEDE10285_ME_0BA6E62BEF84
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_0BA6E62BEF84 DoDoIt

: ME_0BA6E62BEF84
 CONST UID '0BA6E62BEF84'
 CONST Name 'string_Len'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:Len' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_0BA6E62BEF84 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:Len'
 CONST extprop:pas:TypeName 'TkwStringLen'
 CONST extprop:rc:SelfName 'StringLen'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55685FF101AC // string_Len
 ;

ref; // ME_0BA6E62BEF84 string_Len

FORWARD ME_556860130209

FORWARD ME_CA33F456975C

: ME_4DAEEDE10285_ME_CA33F456975C
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_CA33F456975C DoDoIt

: ME_CA33F456975C
 CONST UID 'CA33F456975C'
 CONST Name 'string_ToChar'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:ToChar' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_CA33F456975C // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:ToChar'
 CONST extprop:pas:TypeName 'TkwStringToChar'
 CONST extprop:rc:SelfName 'StringToChar'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_556860130209 // string_ToChar
 ;

ref; // ME_CA33F456975C string_ToChar

FORWARD ME_556866CA0045

: ME_4C3CAF64FEF3
 CONST UID '4C3CAF64FEF3'
 CONST Name 'char_ToString'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта char:ToString' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 CONST "NameForScript" 'char:ToString'
 CONST extprop:pas:TypeName 'TkwCharToString'
 CONST extprop:rc:SelfName 'CharToString'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_556866CA0045 // char_ToString
 ;

ref; // ME_4C3CAF64FEF3 char_ToString

FORWARD ME_55687BBF0087

FORWARD ME_355A8C3D70FA

: ME_4DAEEDE10285_ME_355A8C3D70FA
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_355A8C3D70FA DoDoIt

: ME_355A8C3D70FA
 CONST UID '355A8C3D70FA'
 CONST Name 'char_Dupe'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта char:Dupe' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_355A8C3D70FA // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'char:Dupe'
 CONST extprop:pas:TypeName 'TkwCharDupe'
 CONST extprop:rc:SelfName 'CharDupe'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_55687BBF0087 // char_Dupe
 ;

ref; // ME_355A8C3D70FA char_Dupe

FORWARD ME_5603F61302F1

FORWARD ME_F3116B965978

: ME_4DAEEDE10285_ME_F3116B965978
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_F3116B965978 DoDoIt

: ME_F3116B965978
 CONST UID 'F3116B965978'
 CONST Name 'string_Inc'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:++' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_F3116B965978 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:++'
 CONST extprop:pas:TypeName 'TkwStringInc'
 CONST extprop:rc:SelfName 'StringInc'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_5603F61302F1 // string_Inc
 ;

ref; // ME_F3116B965978 string_Inc

FORWARD ME_5603F655014B

FORWARD ME_EFB7A59A9041

: ME_4DAEEDE10285_ME_EFB7A59A9041
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_EFB7A59A9041 DoDoIt

: ME_EFB7A59A9041
 CONST UID 'EFB7A59A9041'
 CONST Name 'string_Shift'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:+' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_EFB7A59A9041 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:+'
 CONST extprop:pas:TypeName 'TkwStringShift'
 CONST extprop:rc:SelfName 'StringShift'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_5603F655014B // string_Shift
 ;

ref; // ME_EFB7A59A9041 string_Shift

FORWARD ME_5603F68D018F

FORWARD ME_4E9A5EC5FAC6

: ME_4DAEEDE10285_ME_4E9A5EC5FAC6
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_4E9A5EC5FAC6 DoDoIt

: ME_4E9A5EC5FAC6
 CONST UID '4E9A5EC5FAC6'
 CONST Name 'string_FirstChar'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:[]' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_4E9A5EC5FAC6 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:[]'
 CONST extprop:pas:TypeName 'TkwStringFirstChar'
 CONST extprop:rc:SelfName 'StringFirstChar'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_5603F68D018F // string_FirstChar
 ;

ref; // ME_4E9A5EC5FAC6 string_FirstChar

FORWARD ME_569E3511013C

FORWARD ME_95D9D233CD72

: ME_4DAEEDE10285_ME_95D9D233CD72
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_95D9D233CD72 DoDoIt

: ME_95D9D233CD72
 CONST UID '95D9D233CD72'
 CONST Name 'string_Trim'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:Trim' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_95D9D233CD72 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:Trim'
 CONST extprop:pas:TypeName 'TkwStringTrim'
 CONST extprop:rc:SelfName 'StringTrim'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_569E3511013C // string_Trim
 ;

ref; // ME_95D9D233CD72 string_Trim

FORWARD ME_569E3529023A

FORWARD ME_2D2FC66E49DD

: ME_4DAEEDE10285_ME_2D2FC66E49DD
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_2D2FC66E49DD DoDoIt

: ME_2D2FC66E49DD
 CONST UID '2D2FC66E49DD'
 CONST Name 'string_TrimLeft'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:TrimLeft' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_2D2FC66E49DD // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:TrimLeft'
 CONST extprop:pas:TypeName 'TkwStringTrimLeft'
 CONST extprop:rc:SelfName 'StringTrimLeft'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_569E3529023A // string_TrimLeft
 ;

ref; // ME_2D2FC66E49DD string_TrimLeft

FORWARD ME_569E353501BE

FORWARD ME_807D7A8440DD

: ME_4DAEEDE10285_ME_807D7A8440DD
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_807D7A8440DD DoDoIt

: ME_807D7A8440DD
 CONST UID '807D7A8440DD'
 CONST Name 'string_TrimRight'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:TrimRight' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_807D7A8440DD // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:TrimRight'
 CONST extprop:pas:TypeName 'TkwStringTrimRight'
 CONST extprop:rc:SelfName 'StringTrimRight'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_569E353501BE // string_TrimRight
 ;

ref; // ME_807D7A8440DD string_TrimRight

FORWARD ME_569E3542031A

FORWARD ME_D5F09D866A34

: ME_4DAEEDE10285_ME_D5F09D866A34
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_D5F09D866A34 DoDoIt

: ME_D5F09D866A34
 CONST UID 'D5F09D866A34'
 CONST Name 'string_DeleteDoubleSpaces'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:DeleteDoubleSpaces' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_D5F09D866A34 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:DeleteDoubleSpaces'
 CONST extprop:pas:TypeName 'TkwStringDeleteDoubleSpaces'
 CONST extprop:rc:SelfName 'StringDeleteDoubleSpaces'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_569E3542031A // string_DeleteDoubleSpaces
 ;

ref; // ME_D5F09D866A34 string_DeleteDoubleSpaces

FORWARD ME_569E355C01F2

FORWARD ME_30A1EAD7A5D9

: ME_4DAEEDE10285_ME_30A1EAD7A5D9
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_30A1EAD7A5D9 DoDoIt

: ME_30A1EAD7A5D9
 CONST UID '30A1EAD7A5D9'
 CONST Name 'string_DeleteDoubleChars'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:DeleteDoubleChars' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_30A1EAD7A5D9 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:DeleteDoubleChars'
 CONST extprop:pas:TypeName 'TkwStringDeleteDoubleChars'
 CONST extprop:rc:SelfName 'StringDeleteDoubleChars'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_569E355C01F2 // string_DeleteDoubleChars
 ;

ref; // ME_30A1EAD7A5D9 string_DeleteDoubleChars

FORWARD ME_569E357D015D

FORWARD ME_2E3FD122E430

: ME_4DAEEDE10285_ME_2E3FD122E430
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_2E3FD122E430 DoDoIt

: ME_2E3FD122E430
 CONST UID '2E3FD122E430'
 CONST Name 'string_Substring'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:Substring' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_2E3FD122E430 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:Substring'
 CONST extprop:pas:TypeName 'TkwStringSubstring'
 CONST extprop:rc:SelfName 'StringSubstring'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_569E357D015D // string_Substring
 ;

ref; // ME_2E3FD122E430 string_Substring

FORWARD ME_56AB7AC10249

FORWARD ME_B79BEA825961

: ME_4DAEEDE10285_ME_B79BEA825961
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_B79BEA825961 DoDoIt

: ME_B79BEA825961
 CONST UID 'B79BEA825961'
 CONST Name 'string_Lower'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:Lower' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_B79BEA825961 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:Lower'
 CONST extprop:pas:TypeName 'TkwStringLower'
 CONST extprop:rc:SelfName 'StringLower'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_56AB7AC10249 // string_Lower
 ;

ref; // ME_B79BEA825961 string_Lower

FORWARD ME_56AB7AD00352

FORWARD ME_8BA4B632B802

: ME_4DAEEDE10285_ME_8BA4B632B802
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_8BA4B632B802 DoDoIt

: ME_8BA4B632B802
 CONST UID '8BA4B632B802'
 CONST Name 'string_Upper'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:Upper' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_8BA4B632B802 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:Upper'
 CONST extprop:pas:TypeName 'TkwStringUpper'
 CONST extprop:rc:SelfName 'StringUpper'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_56AB7AD00352 // string_Upper
 ;

ref; // ME_8BA4B632B802 string_Upper

FORWARD ME_56F3E6A203DB

FORWARD ME_F137872D0D02

: ME_4DAEEDE10285_ME_F137872D0D02
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_F137872D0D02 DoDoIt

: ME_F137872D0D02
 CONST UID 'F137872D0D02'
 CONST Name 'string_ToUnicode'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:ToUnicode' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_F137872D0D02 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:ToUnicode'
 CONST extprop:pas:TypeName 'TkwStringToUnicode'
 CONST extprop:rc:SelfName 'StringToUnicode'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_56F3E6A203DB // string_ToUnicode
 ;

ref; // ME_F137872D0D02 string_ToUnicode

FORWARD ME_56F3E6BE0100

FORWARD ME_58C52E8D04B3

: ME_4DAEEDE10285_ME_58C52E8D04B3
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_58C52E8D04B3 DoDoIt

: ME_58C52E8D04B3
 CONST UID '58C52E8D04B3'
 CONST Name 'string_Hash'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:Hash' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_58C52E8D04B3 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:Hash'
 CONST extprop:pas:TypeName 'TkwStringHash'
 CONST extprop:rc:SelfName 'StringHash'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_56F3E6BE0100 // string_Hash
 ;

ref; // ME_58C52E8D04B3 string_Hash

FORWARD ME_56F3E6D102C5

FORWARD ME_15AF617143C8

: ME_4DAEEDE10285_ME_15AF617143C8
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_15AF617143C8 DoDoIt

: ME_15AF617143C8
 CONST UID '15AF617143C8'
 CONST Name 'string_SmallHash'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:SmallHash' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_15AF617143C8 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:SmallHash'
 CONST extprop:pas:TypeName 'TkwStringSmallHash'
 CONST extprop:rc:SelfName 'StringSmallHash'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_56F3E6D102C5 // string_SmallHash
 ;

ref; // ME_15AF617143C8 string_SmallHash

FORWARD ME_56F3EF7C0205

FORWARD ME_AE2A1F9F2367

: ME_4DAEEDE10285_ME_AE2A1F9F2367
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_AE2A1F9F2367 DoDoIt

: ME_AE2A1F9F2367
 CONST UID 'AE2A1F9F2367'
 CONST Name 'string_Iterator'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:Iterator' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_AE2A1F9F2367 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:Iterator'
 CONST extprop:pas:TypeName 'TkwStringIterator'
 CONST extprop:rc:SelfName 'StringIterator'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_56F3EF7C0205 // string_Iterator
 ;

ref; // ME_AE2A1F9F2367 string_Iterator

FORWARD ME_56F40BBA029D

FORWARD ME_B0A153973998

: ME_4DAEEDE10285_ME_B0A153973998
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_B0A153973998 DoDoIt

: ME_B0A153973998
 CONST UID 'B0A153973998'
 CONST Name 'string_Hash_New'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:Hash:New' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_B0A153973998 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:Hash:New'
 CONST extprop:pas:TypeName 'TkwStringHashNew'
 CONST extprop:rc:SelfName 'StringHashNew'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_56F40BBA029D // string_Hash_New
 ;

ref; // ME_B0A153973998 string_Hash_New

FORWARD ME_56F40BD3026A

FORWARD ME_A91467BC2C27

: ME_4DAEEDE10285_ME_A91467BC2C27
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_A91467BC2C27 DoDoIt

: ME_A91467BC2C27
 CONST UID 'A91467BC2C27'
 CONST Name 'string_SmallHash_New'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:SmallHash:New' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_A91467BC2C27 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:SmallHash:New'
 CONST extprop:pas:TypeName 'TkwStringSmallHashNew'
 CONST extprop:rc:SelfName 'StringSmallHashNew'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_56F40BD3026A // string_SmallHash_New
 ;

ref; // ME_A91467BC2C27 string_SmallHash_New

FORWARD ME_5718A63E039C

FORWARD ME_FDCE9825C3FB

: ME_4DAEEDE10285_ME_FDCE9825C3FB
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_FDCE9825C3FB DoDoIt

: ME_FDCE9825C3FB
 CONST UID 'FDCE9825C3FB'
 CONST Name 'string_Transliterate'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта string:Transliterate' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_FDCE9825C3FB // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'string:Transliterate'
 CONST extprop:pas:TypeName 'TkwStringTransliterate'
 CONST extprop:rc:SelfName 'StringTransliterate'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : SpelledFor ME_5718A63E039C // string_Transliterate
 ;

ref; // ME_FDCE9825C3FB string_Transliterate

: ME_55682E210194
 CONST Name 'aSubStr'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55682E210194 aSubStr

: ME_55682E07017A
 CONST UID '55682E07017A'
 CONST Name 'StartsStr'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_55682E210194 // aSubStr
 )
 ; // Parameters
 : Speller ME_0093B3082714 // StartsStr
 ;

ref; // ME_55682E07017A StartsStr

: ME_55682E2D0343
 CONST Name 'aSubStr'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55682E2D0343 aSubStr

: ME_55682E2503B9
 CONST UID '55682E2503B9'
 CONST Name 'StartsText'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_55682E2D0343 // aSubStr
 )
 ; // Parameters
 : Speller ME_9996D7566EDE // StartsText
 ;

ref; // ME_55682E2503B9 StartsText

: ME_55682E4B032C
 CONST Name 'aSubStr'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55682E4B032C aSubStr

: ME_55682E4401ED
 CONST UID '55682E4401ED'
 CONST Name 'EndsStr'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_55682E4B032C // aSubStr
 )
 ; // Parameters
 : Speller ME_397C461D6C30 // EndsStr
 ;

ref; // ME_55682E4401ED EndsStr

: ME_55682E55035C
 CONST Name 'aSubStr'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55682E55035C aSubStr

: ME_55682E4F033B
 CONST UID '55682E4F033B'
 CONST Name 'EndsText'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_55682E55035C // aSubStr
 )
 ; // Parameters
 : Speller ME_8997C15C6CA8 // EndsText
 ;

ref; // ME_55682E4F033B EndsText

: ME_55682E6E03CB
 CONST Name 'anOther'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55682E6E03CB anOther

: ME_55682E5E01E1
 CONST UID '55682E5E01E1'
 CONST Name 'SameStr'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_55682E6E03CB // anOther
 )
 ; // Parameters
 : Speller ME_2309401B7CC1 // SameStr
 ;

ref; // ME_55682E5E01E1 SameStr

: ME_55682E7A01F4
 CONST Name 'anOther'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55682E7A01F4 anOther

: ME_55682E72033C
 CONST UID '55682E72033C'
 CONST Name 'SameText'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_55682E7A01F4 // anOther
 )
 ; // Parameters
 : Speller ME_9FC28ACB9AA1 // SameText
 ;

ref; // ME_55682E72033C SameText

: ME_55682E9300E2
 CONST Name 'anOther'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55682E9300E2 anOther

: ME_55682E84007F
 CONST UID '55682E84007F'
 CONST Name 'CompareStr'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Parameters
   Seq: ( ME_55682E9300E2 // anOther
 )
 ; // Parameters
 : Speller ME_C670925F6482 // CompareStr
 ;

ref; // ME_55682E84007F CompareStr

: ME_55682E9D0304
 CONST Name 'anOther'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55682E9D0304 anOther

: ME_55682E9700FE
 CONST UID '55682E9700FE'
 CONST Name 'CompareText'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Parameters
   Seq: ( ME_55682E9D0304 // anOther
 )
 ; // Parameters
 : Speller ME_0E02A0729BA6 // CompareText
 ;

ref; // ME_55682E9700FE CompareText

: ME_55682EA703B4
 CONST UID '55682EA703B4'
 CONST Name 'StrToInt'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Speller ME_09008856C703 // StrToInt
 ;

ref; // ME_55682EA703B4 StrToInt

: ME_5568367E01AD
 CONST Name 'anOther'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_5568367E01AD anOther

: ME_5568365E0395
 CONST UID '5568365E0395'
 CONST Name 'Cat'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Parameters
   Seq: ( ME_5568367E01AD // anOther
 )
 ; // Parameters
 : Speller ME_DD57CECF347C // Cat
 ;

ref; // ME_5568365E0395 Cat

: ME_556849F70316
 CONST Name 'aDelims'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_556849F70316 aDelims

: ME_556840910148
 CONST UID '556840910148'
 CONST Name 'string_ConsistsOf'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 %SUMMARY 'Проверяет, что строка aString состоит ТОЛЬКО из символов строки aDelims' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_556849F70316 // aDelims
 )
 ; // Parameters
 : Speller ME_5F306006344B // string_ConsistsOf
 ;

ref; // ME_556840910148 string_ConsistsOf

: ME_55684A0D020D
 CONST Name 'aDelims'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55684A0D020D aDelims

: ME_5568411F01E1
 CONST UID '5568411F01E1'
 CONST Name 'string_HasAnyOf'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 %SUMMARY 'Проверяет, что строка aString содержит хотя бы один символ из aDelims' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_55684A0D020D // aDelims
 )
 ; // Parameters
 : Speller ME_2256016890B3 // string_HasAnyOf
 ;

ref; // ME_5568411F01E1 string_HasAnyOf

: ME_5568419400E1
 CONST Name 'anOther'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_5568419400E1 anOther

: ME_5568417001D5
 CONST UID '5568417001D5'
 CONST Name 'string_Pos'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 %SUMMARY '''мама рыла яму'' ''ры'' string:Pos .' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Parameters
   Seq: ( ME_5568419400E1 // anOther
 )
 ; // Parameters
 : Speller ME_851E99BEB53B // string_Pos
 ;

ref; // ME_5568417001D5 string_Pos

: ME_556841E50088
 CONST Name 'anOther'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_556841E50088 anOther

: ME_556841E50102
 CONST Name 'aPos'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_556841E50102 aPos

: ME_556841C601CF
 CONST UID '556841C601CF'
 CONST Name 'string_PosEx'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 %SUMMARY '6 ''мама рыла рыло'' ''ры'' string:PosEx .' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Parameters
   Seq: ( ME_556841E50088 // anOther
 ME_556841E50102 // aPos
 )
 ; // Parameters
 : Speller ME_24901BF384F4 // string_PosEx
 ;

ref; // ME_556841C601CF string_PosEx

: ME_55684276020F
 CONST Name 'anOther'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55684276020F anOther

: ME_556C684102A1
 CONST Name 'theTail'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_556C684102A1 theTail

: ME_5568423E01F3
 CONST UID '5568423E01F3'
 CONST Name 'string_Split'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 %SUMMARY 'Разделяет строку на две по заданному разделителю.'#13#10''#13#10'Пример:'#13#10'{code}'#13#10'''ABC:DEF'' '':'' string:Split'#13#10'{code}'#13#10'Получаем на стеке:'#13#10'''ABC'' '':DEF''' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Parameters
   Seq: ( ME_55684276020F // anOther
 ME_556C684102A1 // theTail
 )
 ; // Parameters
 : Speller ME_AA63BC1F51EC // string_Split
 ;

ref; // ME_5568423E01F3 string_Split

: ME_556852380233
 CONST Name 'aFrom'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_556852380233 aFrom

: ME_5568523802A4
 CONST Name 'aMain'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_5568523802A4 aMain

: ME_5568520B03B5
 CONST UID '5568520B03B5'
 CONST Name 'string_Replace'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Parameters
   Seq: ( ME_556852380233 // aFrom
 ME_5568523802A4 // aMain
 )
 ; // Parameters
 : Speller ME_8CA688C2805E // string_Replace
 ;

ref; // ME_5568520B03B5 string_Replace

: ME_55685248032B
 CONST Name 'aFrom'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55685248032B aFrom

: ME_55685248039B
 CONST Name 'aMain'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55685248039B aMain

: ME_5568523F03BE
 CONST UID '5568523F03BE'
 CONST Name 'string_ReplaceFirst'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Parameters
   Seq: ( ME_55685248032B // aFrom
 ME_55685248039B // aMain
 )
 ; // Parameters
 : Speller ME_FF1E0A42BBEF // string_ReplaceFirst
 ;

ref; // ME_5568523F03BE string_ReplaceFirst

: ME_5568525B00DA
 CONST Name 'aFrom'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_5568525B00DA aFrom

: ME_5568525B0147
 CONST Name 'aMain'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_5568525B0147 aMain

: ME_556852510081
 CONST UID '556852510081'
 CONST Name 'text_Replace'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Parameters
   Seq: ( ME_5568525B00DA // aFrom
 ME_5568525B0147 // aMain
 )
 ; // Parameters
 : Speller ME_6F240EDBC3AE // text_Replace
 ;

ref; // ME_556852510081 text_Replace

: ME_5568526900DB
 CONST Name 'aFrom'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_5568526900DB aFrom

: ME_55685269014F
 CONST Name 'aMain'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55685269014F aMain

: ME_5568525F008C
 CONST UID '5568525F008C'
 CONST Name 'text_ReplaceFirst'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Parameters
   Seq: ( ME_5568526900DB // aFrom
 ME_55685269014F // aMain
 )
 ; // Parameters
 : Speller ME_0527F8C9DF24 // text_ReplaceFirst
 ;

ref; // ME_5568525F008C text_ReplaceFirst

: ME_55685FC00312
 CONST Name 'anIndex'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_55685FC00312 anIndex

: ME_55685FAB0248
 CONST UID '55685FAB0248'
 CONST Name 'string_Char'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_482C48430205' '4AB0C3C60310.pas.ms.script' // Char
 ;
 : Parameters
   Seq: ( ME_55685FC00312 // anIndex
 )
 ; // Parameters
 CONST "NameForScript" 'string:[i]'
 : Speller ME_9597582C9BD4 // string_Char
 ;

ref; // ME_55685FAB0248 string_Char

: ME_55685FD801DF
 CONST UID '55685FD801DF'
 CONST Name 'string_CodePage'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Speller ME_6CAF85926E0C // string_CodePage
 ;

ref; // ME_55685FD801DF string_CodePage

: ME_55685FF101AC
 CONST UID '55685FF101AC'
 CONST Name 'string_Len'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Speller ME_0BA6E62BEF84 // string_Len
 ;

ref; // ME_55685FF101AC string_Len

: ME_556860130209
 CONST UID '556860130209'
 CONST Name 'string_ToChar'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_482C48430205' '4AB0C3C60310.pas.ms.script' // Char
 ;
 : Speller ME_CA33F456975C // string_ToChar
 ;

ref; // ME_556860130209 string_ToChar

: ME_556866E4001E
 CONST Name 'aChar'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_482C48430205' '4AB0C3C60310.pas.ms.script' // Char
 ;

ref; // ME_556866E4001E aChar

: ME_556866CA0045
 CONST UID '556866CA0045'
 CONST Name 'char_ToString'
 CONST Class class_Operation
 : Stereotype st_creator::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Parameters
   Seq: ( ME_556866E4001E // aChar
 )
 ; // Parameters
 : Speller ME_4C3CAF64FEF3 // char_ToString
 ;

ref; // ME_556866CA0045 char_ToString

: ME_55686F4301AB
 CONST UID '55686F4301AB'
 CONST Name 'VarDecLen'
 CONST Class class_Operation
 : Stereotype st_globalvarworker::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 CONST "NameForScript" 'string:--Len!'

ref; // ME_55686F4301AB VarDecLen

: ME_55686F75015A
 CONST UID '55686F75015A'
 CONST Name 'VarInc'
 CONST Class class_Operation
 : Stereotype st_globalvarworker::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 CONST "NameForScript" 'string:++!'

ref; // ME_55686F75015A VarInc

: ME_556875BF0172
 CONST Name 'aDelim'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_556875BF0172 aDelim

: ME_55686F9A037E
 CONST UID '55686F9A037E'
 CONST Name 'RSplitTo'
 CONST Class class_Operation
 : Stereotype st_globalvarworker::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Parameters
   Seq: ( ME_556875BF0172 // aDelim
 )
 ; // Parameters
 CONST "NameForScript" 'string:RSplitTo!'

ref; // ME_55686F9A037E RSplitTo

: ME_55686FDD0265
 CONST Name 'aNum'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_55686FDD0265 aNum

: ME_55686FC6020D
 CONST UID '55686FC6020D'
 CONST Name 'VarShift'
 CONST Class class_Operation
 : Stereotype st_globalvarworker::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Parameters
   Seq: ( ME_55686FDD0265 // aNum
 )
 ; // Parameters
 CONST "NameForScript" 'string:+!'

ref; // ME_55686FC6020D VarShift

: ME_556875B302CB
 CONST Name 'aDelim'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_556875B302CB aDelim

: ME_55686FEE03A7
 CONST UID '55686FEE03A7'
 CONST Name 'SplitTo'
 CONST Class class_Operation
 : Stereotype st_globalvarworker::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Parameters
   Seq: ( ME_556875B302CB // aDelim
 )
 ; // Parameters
 CONST "NameForScript" 'string:SplitTo!'

ref; // ME_55686FEE03A7 SplitTo

: ME_55687C890287
 CONST Name 'aCount'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_55687C890287 aCount

: ME_55687BBF0087
 CONST UID '55687BBF0087'
 CONST Name 'char_Dupe'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 %SUMMARY 'Размножаем символ столько раз, сколько указано' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Parameters
   Seq: ( ME_55687C890287 // aCount
 )
 ; // Parameters
 : Speller ME_355A8C3D70FA // char_Dupe
 ;

ref; // ME_55687BBF0087 char_Dupe

: ME_5603F5980215
 CONST UID '5603F5980215'
 CONST Name 'VarPushCharAndInc'
 CONST Class class_Operation
 : Stereotype st_globalvarworker::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_482C48430205' '4AB0C3C60310.pas.ms.script' // Char
 ;
 CONST "NameForScript" 'string:[]++!'

ref; // ME_5603F5980215 VarPushCharAndInc

: ME_5603F61302F1
 CONST UID '5603F61302F1'
 CONST Name 'string_Inc'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 CONST "NameForScript" 'string:++'
 : Speller ME_F3116B965978 // string_Inc
 ;

ref; // ME_5603F61302F1 string_Inc

: ME_5603F67201E9
 CONST Name 'aDelta'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_5603F67201E9 aDelta

: ME_5603F655014B
 CONST UID '5603F655014B'
 CONST Name 'string_Shift'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Parameters
   Seq: ( ME_5603F67201E9 // aDelta
 )
 ; // Parameters
 CONST "NameForScript" 'string:+'
 : Speller ME_EFB7A59A9041 // string_Shift
 ;

ref; // ME_5603F655014B string_Shift

: ME_5603F68D018F
 CONST UID '5603F68D018F'
 CONST Name 'string_FirstChar'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_482C48430205' '4AB0C3C60310.pas.ms.script' // Char
 ;
 CONST "NameForScript" 'string:[]'
 : Speller ME_4E9A5EC5FAC6 // string_FirstChar
 ;

ref; // ME_5603F68D018F string_FirstChar

: ME_569E3511013C
 CONST UID '569E3511013C'
 CONST Name 'string_Trim'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Speller ME_95D9D233CD72 // string_Trim
 ;

ref; // ME_569E3511013C string_Trim

: ME_569E3529023A
 CONST UID '569E3529023A'
 CONST Name 'string_TrimLeft'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Speller ME_2D2FC66E49DD // string_TrimLeft
 ;

ref; // ME_569E3529023A string_TrimLeft

: ME_569E353501BE
 CONST UID '569E353501BE'
 CONST Name 'string_TrimRight'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Speller ME_807D7A8440DD // string_TrimRight
 ;

ref; // ME_569E353501BE string_TrimRight

: ME_569E3542031A
 CONST UID '569E3542031A'
 CONST Name 'string_DeleteDoubleSpaces'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Speller ME_D5F09D866A34 // string_DeleteDoubleSpaces
 ;

ref; // ME_569E3542031A string_DeleteDoubleSpaces

: ME_569E3577011C
 CONST Name 'aChar'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_569E3577011C aChar

: ME_569E355C01F2
 CONST UID '569E355C01F2'
 CONST Name 'string_DeleteDoubleChars'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Parameters
   Seq: ( ME_569E3577011C // aChar
 )
 ; // Parameters
 : Speller ME_30A1EAD7A5D9 // string_DeleteDoubleChars
 ;

ref; // ME_569E355C01F2 string_DeleteDoubleChars

: ME_569E359701A5
 CONST Name 'aPos'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_569E359701A5 aPos

: ME_569E35970213
 CONST Name 'aLength'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_569E35970213 aLength

: ME_569E357D015D
 CONST UID '569E357D015D'
 CONST Name 'string_Substring'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Parameters
   Seq: ( ME_569E359701A5 // aPos
 ME_569E35970213 // aLength
 )
 ; // Parameters
 : Speller ME_2E3FD122E430 // string_Substring
 ;

ref; // ME_569E357D015D string_Substring

: ME_56AB7AC10249
 CONST UID '56AB7AC10249'
 CONST Name 'string_Lower'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Speller ME_B79BEA825961 // string_Lower
 ;

ref; // ME_56AB7AC10249 string_Lower

: ME_56AB7AD00352
 CONST UID '56AB7AD00352'
 CONST Name 'string_Upper'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Speller ME_8BA4B632B802 // string_Upper
 ;

ref; // ME_56AB7AD00352 string_Upper

: ME_56F3E6A203DB
 CONST UID '56F3E6A203DB'
 CONST Name 'string_ToUnicode'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;
 : Speller ME_F137872D0D02 // string_ToUnicode
 ;

ref; // ME_56F3E6A203DB string_ToUnicode

: ME_56F3E6BE0100
 CONST UID '56F3E6BE0100'
 CONST Name 'string_Hash'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Speller ME_58C52E8D04B3 // string_Hash
 ;

ref; // ME_56F3E6BE0100 string_Hash

: ME_56F3E6D102C5
 CONST UID '56F3E6D102C5'
 CONST Name 'string_SmallHash'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Speller ME_15AF617143C8 // string_SmallHash
 ;

ref; // ME_56F3E6D102C5 string_SmallHash

: ME_56F3E8880129
 CONST UID '56F3E8880129'
 CONST Name 'Hash16Table'
 CONST Class class_Operation
 : Stereotype st_globalkeyword::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_4DCC12FC0125' '4DAF19F600C5.pas.ms.script' // ItfwValueList
 ;

ref; // ME_56F3E8880129 Hash16Table

: ME_56F3EF7C0205
 CONST UID '56F3EF7C0205'
 CONST Name 'string_Iterator'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_4DCC12FC0125' '4DAF19F600C5.pas.ms.script' // ItfwValueList
 ;
 : Speller ME_AE2A1F9F2367 // string_Iterator
 ;

ref; // ME_56F3EF7C0205 string_Iterator

: ME_56F40BBA029D
 CONST UID '56F40BBA029D'
 CONST Name 'string_Hash_New'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Speller ME_B0A153973998 // string_Hash_New
 ;

ref; // ME_56F40BBA029D string_Hash_New

: ME_56F40BD3026A
 CONST UID '56F40BD3026A'
 CONST Name 'string_SmallHash_New'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Speller ME_A91467BC2C27 // string_SmallHash_New
 ;

ref; // ME_56F40BD3026A string_SmallHash_New

: ME_5718A63E039C
 CONST UID '5718A63E039C'
 CONST Name 'string_Transliterate'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 : Speller ME_FDCE9825C3FB // string_Transliterate
 ;

ref; // ME_5718A63E039C string_Transliterate

: ME_55682DD10033
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_47878E0E0191' '54B90AC6014B.pas.ms.script' // l3String
 ;

ref; // ME_55682DD10033 

: ME_55683DB20118
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_476F9605006B' '4678193C009C.pas.ms.script' // Indexes
 ;

ref; // ME_55683DB20118 

: ME_556851ED032E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_47A082F101DB' '476BE98C01B8.pas.ms.script' // Ext Chars
 ;

ref; // ME_556851ED032E 

: ME_56028ED70054
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_5579351F0143' '47913B47006E.pas.ms.script' // Tl3ConstString
 ;

ref; // ME_56028ED70054 

: ME_56F3E68102BB
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_53FF366C021B' '47BF042D029B.pas.ms.script' // m2HasLib
 ;

ref; // ME_56F3E68102BB 

FORWARD ME_56F3E80A018E

: ME_56F3E85603D3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target ME_56F3E80A018E // TtfwHash16Table
 ;

ref; // ME_56F3E85603D3 

: ME_E29135ED23EF
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_injects::Dependency ;
 : Parent ME_55682D8F01C7 // tfwIl3CStringPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_E29135ED23EF 

: ME_46780DEF03E5_ME_55682D8F01C7
 : Original WL 'ME_46780DEF03E5' '4677FBA70343.pas.ms.script' // AsWStr
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_46780DEF03E5_ME_55682D8F01C7 AsWStr

: ME_55682D8F01C7
 CONST UID '55682D8F01C7'
 CONST Name 'tfwIl3CStringPack'
 CONST Class class_Class
 : Stereotype st_ScriptKeywordsPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4ED7958E0045 // StringProcessing
 ;
 : Inherits
   Seq: ( WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 )
 ; // Inherits
 : Operations
   Seq: ( ME_55682E07017A // StartsStr
 ME_55682E2503B9 // StartsText
 ME_55682E4401ED // EndsStr
 ME_55682E4F033B // EndsText
 ME_55682E5E01E1 // SameStr
 ME_55682E72033C // SameText
 ME_55682E84007F // CompareStr
 ME_55682E9700FE // CompareText
 ME_55682EA703B4 // StrToInt
 ME_5568365E0395 // Cat
 ME_556840910148 // string_ConsistsOf
 ME_5568411F01E1 // string_HasAnyOf
 ME_5568417001D5 // string_Pos
 ME_556841C601CF // string_PosEx
 ME_5568423E01F3 // string_Split
 ME_5568520B03B5 // string_Replace
 ME_5568523F03BE // string_ReplaceFirst
 ME_556852510081 // text_Replace
 ME_5568525F008C // text_ReplaceFirst
 ME_55685FAB0248 // string_Char
 ME_55685FD801DF // string_CodePage
 ME_55685FF101AC // string_Len
 ME_556860130209 // string_ToChar
 ME_556866CA0045 // char_ToString
 ME_55686F4301AB // VarDecLen
 ME_55686F75015A // VarInc
 ME_55686F9A037E // RSplitTo
 ME_55686FC6020D // VarShift
 ME_55686FEE03A7 // SplitTo
 ME_55687BBF0087 // char_Dupe
 ME_5603F5980215 // VarPushCharAndInc
 ME_5603F61302F1 // string_Inc
 ME_5603F655014B // string_Shift
 ME_5603F68D018F // string_FirstChar
 ME_569E3511013C // string_Trim
 ME_569E3529023A // string_TrimLeft
 ME_569E353501BE // string_TrimRight
 ME_569E3542031A // string_DeleteDoubleSpaces
 ME_569E355C01F2 // string_DeleteDoubleChars
 ME_569E357D015D // string_Substring
 ME_56AB7AC10249 // string_Lower
 ME_56AB7AD00352 // string_Upper
 ME_56F3E6A203DB // string_ToUnicode
 ME_56F3E6BE0100 // string_Hash
 ME_56F3E6D102C5 // string_SmallHash
 ME_56F3E8880129 // Hash16Table
 ME_56F3EF7C0205 // string_Iterator
 ME_56F40BBA029D // string_Hash_New
 ME_56F40BD3026A // string_SmallHash_New
 ME_5718A63E039C // string_Transliterate
 )
 ; // Operations
 : Implemented
   Seq: ( ME_46780DEF03E5_ME_55682D8F01C7 // AsWStr
 )
 ; // Implemented
 : Children
   Seq: ( ME_56F3EEE50232 // TtfwStringIterator
 ME_0093B3082714 // StartsStr
 ME_9996D7566EDE // StartsText
 ME_397C461D6C30 // EndsStr
 ME_8997C15C6CA8 // EndsText
 ME_2309401B7CC1 // SameStr
 ME_9FC28ACB9AA1 // SameText
 ME_C670925F6482 // CompareStr
 ME_0E02A0729BA6 // CompareText
 ME_09008856C703 // StrToInt
 ME_DD57CECF347C // Cat
 ME_5F306006344B // string_ConsistsOf
 ME_2256016890B3 // string_HasAnyOf
 ME_851E99BEB53B // string_Pos
 ME_24901BF384F4 // string_PosEx
 ME_AA63BC1F51EC // string_Split
 ME_8CA688C2805E // string_Replace
 ME_FF1E0A42BBEF // string_ReplaceFirst
 ME_6F240EDBC3AE // text_Replace
 ME_0527F8C9DF24 // text_ReplaceFirst
 ME_9597582C9BD4 // string_Char
 ME_6CAF85926E0C // string_CodePage
 ME_0BA6E62BEF84 // string_Len
 ME_CA33F456975C // string_ToChar
 ME_4C3CAF64FEF3 // char_ToString
 ME_355A8C3D70FA // char_Dupe
 ME_F3116B965978 // string_Inc
 ME_EFB7A59A9041 // string_Shift
 ME_4E9A5EC5FAC6 // string_FirstChar
 ME_95D9D233CD72 // string_Trim
 ME_2D2FC66E49DD // string_TrimLeft
 ME_807D7A8440DD // string_TrimRight
 ME_D5F09D866A34 // string_DeleteDoubleSpaces
 ME_30A1EAD7A5D9 // string_DeleteDoubleChars
 ME_2E3FD122E430 // string_Substring
 ME_B79BEA825961 // string_Lower
 ME_8BA4B632B802 // string_Upper
 ME_F137872D0D02 // string_ToUnicode
 ME_58C52E8D04B3 // string_Hash
 ME_15AF617143C8 // string_SmallHash
 ME_AE2A1F9F2367 // string_Iterator
 ME_B0A153973998 // string_Hash_New
 ME_A91467BC2C27 // string_SmallHash_New
 ME_FDCE9825C3FB // string_Transliterate
 )
 ; // Children
 : Dependencies
   Seq: ( ME_55682DD10033 // l3String
 ME_55683DB20118 // Indexes
 ME_556851ED032E // Ext Chars
 ME_56028ED70054 // Tl3ConstString
 ME_56F3E68102BB // m2HasLib
 ME_56F3E85603D3 // TtfwHash16Table
 ME_E29135ED23EF // Il3CString
 )
 ; // Dependencies
 CONST "ifndef" 'NoScripts'
 CONST "no class name" true
 CONST "no_pop" true
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\tfwIl3CStringPack.pas'
 CONST extprop:rc:SelfName 'Il3CStringPack'

ref; // ME_55682D8F01C7 tfwIl3CStringPack

FORWARD ME_56F3E8BE02A5

: ME_56F3E8D60391
 CONST UID '56F3E8D60391'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_56F3E8BE02A5 // Create
 ;

ref; // ME_56F3E8D60391 DoIt

: ME_56F3E8BE02A5
 CONST UID '56F3E8BE02A5'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_56F3E80A018E // TtfwHash16Table
 ;
 : Operations
   Seq: ( ME_56F3E8D60391 // DoIt
 )
 ; // Operations

ref; // ME_56F3E8BE02A5 Create

: ME_56F3E8C900CA
 CONST UID '56F3E8C900CA'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_56F3E80A018E // TtfwHash16Table
 ;
 : Inherits
   Seq: ( ME_56F3E8BE02A5 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4DCC12FC0125' '4DAF19F600C5.pas.ms.script' // ItfwValueList
 )
 ; // Implements

ref; // ME_56F3E8C900CA Make

: ME_56F3E86C00C5
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_56F3E80A018E // TtfwHash16Table
 ;
 : Target WL 'ME_53FF366C021B' '47BF042D029B.pas.ms.script' // m2HasLib
 ;

ref; // ME_56F3E86C00C5 

: ME_52E23B7A00EC_ME_56F3E80A018E
 : Original WL 'ME_52E23B7A00EC' '4DAF19F600C5.pas.ms.script' // ForEach
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52E23B7A00EC_ME_56F3E80A018E ForEach

: ME_52E23BB102FA_ME_56F3E80A018E
 : Original WL 'ME_52E23BB102FA' '4DAF19F600C5.pas.ms.script' // ForEachBack
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52E23BB102FA_ME_56F3E80A018E ForEachBack

: ME_55CDF40C03D4_ME_56F3E80A018E
 : Original WL 'ME_55CDF40C03D4' '4DAF19F600C5.pas.ms.script' // SetItem
 ;
 CONST OpKind opkind_Implemented
ref; // ME_55CDF40C03D4_ME_56F3E80A018E SetItem

: ME_55E849210175_ME_56F3E80A018E
 : Original WL 'ME_55E849210175' '4DAF19F600C5.pas.ms.script' // ItemsCountInSlice
 ;
 CONST OpKind opkind_Implemented
ref; // ME_55E849210175_ME_56F3E80A018E ItemsCountInSlice

: ME_56F3E80A018E
 CONST UID '56F3E80A018E'
 CONST Name 'TtfwHash16Table'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4ED7958E0045 // StringProcessing
 ;
 : Inherits
   Seq: ( WL 'ME_52E29ED5016B' '54F0A4A302FF.pas.ms.script' // TtfwIteratableParent
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4DCC12FC0125' '4DAF19F600C5.pas.ms.script' // ItfwValueList
 )
 ; // Implements
 : Operations
   Seq: ( ME_56F3E8BE02A5 // Create
 ME_56F3E8C900CA // Make
 )
 ; // Operations
 : Implemented
   Seq: ( ME_52E23B7A00EC_ME_56F3E80A018E // ForEach
 ME_52E23BB102FA_ME_56F3E80A018E // ForEachBack
 ME_55CDF40C03D4_ME_56F3E80A018E // SetItem
 ME_55E849210175_ME_56F3E80A018E // ItemsCountInSlice
 )
 ; // Implemented
 : Dependencies
   Seq: ( ME_56F3E86C00C5 // m2HasLib
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\tfwHash16Table.pas'
 CONST extprop:rc:SelfName 'Hash16Table'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'tfwHash16Table'

ref; // ME_56F3E80A018E TtfwHash16Table

: ME_4ED7958E0045
 CONST UID '4ED7958E0045'
 CONST Name 'StringProcessing'
 CONST Class class_Category
 : Stereotype st_ScriptKeywords ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_551175240043' '551175240043.pas.ms.script' // ScriptEngine$Axiomatics
 ;
 : Children
   Seq: ( ME_55682D8F01C7 // tfwIl3CStringPack
 ME_56F3E80A018E // TtfwHash16Table
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 WL 'ME_4677FBA70343' '4677FBA70343.pas.ms.script' // l3Interfaces
 WL 'ME_4678193C009C' '4678193C009C.pas.ms.script' // l3Types
 WL 'ME_476BE98C01B8' '476BE98C01B8.pas.ms.script' // l3Chars
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_47BF042D029B' '47BF042D029B.pas.ms.script' // m2
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_4DAF19F600C5' '4DAF19F600C5.pas.ms.script' // tfwScriptingInterfaces
 WL 'ME_54B90AC6014B' '54B90AC6014B.pas.ms.script' // StringUtils
 WL 'ME_54F079B5035C' '54F079B5035C.pas.ms.script' // CompiledWords
 WL 'ME_54F0A4A302FF' '54F0A4A302FF.pas.ms.script' // Array
 WL 'ME_55CCADD2013D' '55CCADD2013D.pas.ms.script' // ClassLikeMapping
 )
 ; // Depends
 CONST "ifndef" 'NoScripts'

ref; // ME_4ED7958E0045 StringProcessing
