// TableTools 4EF1A15303DD TestUnit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4EF1A15303DD

FORWARD ME_4E310F43015A

: ME_17E70F8DB88F
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4E310F43015A // K104434922
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_17E70F8DB88F 

: ME_4C937013031D_ME_4E310F43015A
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4E310F43015A // K104434922
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4E310F43015A GetFolder

: ME_4DAED6F60146_ME_4E310F43015A
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4E310F43015A // K104434922
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4E310F43015A GetModelElementGUID

: ME_4E310F43015A
 CONST UID '4E310F43015A'
 CONST Name 'K104434922'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '[$104434922]' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4E310F43015A // GetFolder
 ME_4DAED6F60146_ME_4E310F43015A // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_17E70F8DB88F // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K104434922.pas'
 CONST extprop:pas:TypeName 'TK104434922'
 CONST extprop:rc:SelfName 'K104434922'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4E310F43015A K104434922

FORWARD ME_4E8EDEE500A6

: ME_EFF052568C6A
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4E8EDEE500A6 // K290947845
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_EFF052568C6A 

: ME_4C937013031D_ME_4E8EDEE500A6
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4E8EDEE500A6 // K290947845
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4E8EDEE500A6 GetFolder

: ME_4DAED6F60146_ME_4E8EDEE500A6
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4E8EDEE500A6 // K290947845
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4E8EDEE500A6 GetModelElementGUID

: ME_4E8EDEE500A6
 CONST UID '4E8EDEE500A6'
 CONST Name 'K290947845'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:290947845}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4E8EDEE500A6 // GetFolder
 ME_4DAED6F60146_ME_4E8EDEE500A6 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_EFF052568C6A // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K290947845.pas'
 CONST extprop:pas:TypeName 'TK290947845'
 CONST extprop:rc:SelfName 'K290947845'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4E8EDEE500A6 K290947845

FORWARD ME_4ECCEB2A01A9

: ME_AAF1FA704021
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4ECCEB2A01A9 // K290951663
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_AAF1FA704021 

: ME_4C937013031D_ME_4ECCEB2A01A9
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4ECCEB2A01A9 // K290951663
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4ECCEB2A01A9 GetFolder

: ME_4DAED6F60146_ME_4ECCEB2A01A9
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4ECCEB2A01A9 // K290951663
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4ECCEB2A01A9 GetModelElementGUID

: ME_4ECCEB2A01A9
 CONST UID '4ECCEB2A01A9'
 CONST Name 'K290951663'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:290951663}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4ECCEB2A01A9 // GetFolder
 ME_4DAED6F60146_ME_4ECCEB2A01A9 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_AAF1FA704021 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K290951663.pas'
 CONST extprop:pas:TypeName 'TK290951663'
 CONST extprop:rc:SelfName 'K290951663'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4ECCEB2A01A9 K290951663

FORWARD ME_4E97DA6401A2

: ME_1C2ACE396630
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4E97DA6401A2 // K290951686
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_1C2ACE396630 

: ME_4C937013031D_ME_4E97DA6401A2
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4E97DA6401A2 // K290951686
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4E97DA6401A2 GetFolder

: ME_4DAED6F60146_ME_4E97DA6401A2
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4E97DA6401A2 // K290951686
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4E97DA6401A2 GetModelElementGUID

: ME_4E97DA6401A2
 CONST UID '4E97DA6401A2'
 CONST Name 'K290951686'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '[$290951686]' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4E97DA6401A2 // GetFolder
 ME_4DAED6F60146_ME_4E97DA6401A2 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_1C2ACE396630 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K290951686.pas'
 CONST extprop:pas:TypeName 'TK290951686'
 CONST extprop:rc:SelfName 'K290951686'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4E97DA6401A2 K290951686

FORWARD ME_4EF2F4C502FE

: ME_52895775CCAB
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4EF2F4C502FE // K297703832
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_52895775CCAB 

: ME_4C937013031D_ME_4EF2F4C502FE
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4EF2F4C502FE // K297703832
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4EF2F4C502FE GetFolder

: ME_4DAED6F60146_ME_4EF2F4C502FE
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4EF2F4C502FE // K297703832
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4EF2F4C502FE GetModelElementGUID

: ME_4EF2F4C502FE
 CONST UID '4EF2F4C502FE'
 CONST Name 'K297703832'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:297703832}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4EF2F4C502FE // GetFolder
 ME_4DAED6F60146_ME_4EF2F4C502FE // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_52895775CCAB // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K297703832.pas'
 CONST extprop:pas:TypeName 'TK297703832'
 CONST extprop:rc:SelfName 'K297703832'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4EF2F4C502FE K297703832

FORWARD ME_4EF86F3203E5

: ME_192BA9D5616E
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4EF86F3203E5 // K323061070
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_192BA9D5616E 

: ME_4C937013031D_ME_4EF86F3203E5
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4EF86F3203E5 // K323061070
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4EF86F3203E5 GetFolder

: ME_4DAED6F60146_ME_4EF86F3203E5
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4EF86F3203E5 // K323061070
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4EF86F3203E5 GetModelElementGUID

: ME_4EF86F3203E5
 CONST UID '4EF86F3203E5'
 CONST Name 'K323061070'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{RequestLink:323061070}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4EF86F3203E5 // GetFolder
 ME_4DAED6F60146_ME_4EF86F3203E5 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_192BA9D5616E // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K323061070.pas'
 CONST extprop:pas:TypeName 'TK323061070'
 CONST extprop:rc:SelfName 'K323061070'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4EF86F3203E5 K323061070

FORWARD ME_4F1FD3B801C1

: ME_9B3DDE99310B
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F1FD3B801C1 // TK330140470
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_9B3DDE99310B 

: ME_4C937013031D_ME_4F1FD3B801C1
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F1FD3B801C1 // TK330140470
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F1FD3B801C1 GetFolder

: ME_4DAED6F60146_ME_4F1FD3B801C1
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F1FD3B801C1 // TK330140470
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F1FD3B801C1 GetModelElementGUID

: ME_4F1FD3B801C1
 CONST UID '4F1FD3B801C1'
 CONST Name 'TK330140470'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:330140470}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F1FD3B801C1 // GetFolder
 ME_4DAED6F60146_ME_4F1FD3B801C1 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_9B3DDE99310B // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K330140470.pas'
 CONST extprop:rc:SelfName 'K330140470'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'K330140470'

ref; // ME_4F1FD3B801C1 TK330140470

FORWARD ME_4F2946A6031A

: ME_E8980E28153B
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F2946A6031A // K330140904
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_E8980E28153B 

: ME_4C937013031D_ME_4F2946A6031A
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F2946A6031A // K330140904
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F2946A6031A GetFolder

: ME_4DAED6F60146_ME_4F2946A6031A
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F2946A6031A // K330140904
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F2946A6031A GetModelElementGUID

: ME_4F2946A6031A
 CONST UID '4F2946A6031A'
 CONST Name 'K330140904'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:330140904}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F2946A6031A // GetFolder
 ME_4DAED6F60146_ME_4F2946A6031A // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_E8980E28153B // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K330140904.pas'
 CONST extprop:pas:TypeName 'TK330140904'
 CONST extprop:rc:SelfName 'K330140904'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F2946A6031A K330140904

FORWARD ME_4F2A8BDC02A8

: ME_ACC93B56C473
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F2A8BDC02A8 // K333550210
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_ACC93B56C473 

: ME_4C937013031D_ME_4F2A8BDC02A8
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F2A8BDC02A8 // K333550210
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F2A8BDC02A8 GetFolder

: ME_4DAED6F60146_ME_4F2A8BDC02A8
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F2A8BDC02A8 // K333550210
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F2A8BDC02A8 GetModelElementGUID

: ME_4F2A8BDC02A8
 CONST UID '4F2A8BDC02A8'
 CONST Name 'K333550210'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:333550210}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F2A8BDC02A8 // GetFolder
 ME_4DAED6F60146_ME_4F2A8BDC02A8 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_ACC93B56C473 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K333550210.pas'
 CONST extprop:pas:TypeName 'TK333550210'
 CONST extprop:rc:SelfName 'K333550210'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F2A8BDC02A8 K333550210

FORWARD ME_4F30E48602B2

: ME_23F8ADB20CE3
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F30E48602B2 // TK336137132
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_23F8ADB20CE3 

: ME_4C937013031D_ME_4F30E48602B2
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F30E48602B2 // TK336137132
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F30E48602B2 GetFolder

: ME_4DAED6F60146_ME_4F30E48602B2
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F30E48602B2 // TK336137132
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F30E48602B2 GetModelElementGUID

: ME_4F30E48602B2
 CONST UID '4F30E48602B2'
 CONST Name 'TK336137132'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:336137132}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F30E48602B2 // GetFolder
 ME_4DAED6F60146_ME_4F30E48602B2 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_23F8ADB20CE3 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K336137132.pas'
 CONST extprop:rc:SelfName 'K336137132'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'K336137132'

ref; // ME_4F30E48602B2 TK336137132

FORWARD ME_4F30E49D0064

: ME_92FDDC0C5337
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F30E49D0064 // TK336137156
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_92FDDC0C5337 

: ME_4C937013031D_ME_4F30E49D0064
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F30E49D0064 // TK336137156
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F30E49D0064 GetFolder

: ME_4DAED6F60146_ME_4F30E49D0064
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F30E49D0064 // TK336137156
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F30E49D0064 GetModelElementGUID

: ME_4F30E49D0064
 CONST UID '4F30E49D0064'
 CONST Name 'TK336137156'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:336137156}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F30E49D0064 // GetFolder
 ME_4DAED6F60146_ME_4F30E49D0064 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_92FDDC0C5337 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K336137156.pas'
 CONST extprop:rc:SelfName 'K336137156'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'K336137156'

ref; // ME_4F30E49D0064 TK336137156

FORWARD ME_4F327E31026E

: ME_97199BEDBADE
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F327E31026E // TK336659951
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_97199BEDBADE 

: ME_4C937013031D_ME_4F327E31026E
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F327E31026E // TK336659951
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F327E31026E GetFolder

: ME_4DAED6F60146_ME_4F327E31026E
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F327E31026E // TK336659951
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F327E31026E GetModelElementGUID

: ME_4F327E31026E
 CONST UID '4F327E31026E'
 CONST Name 'TK336659951'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:336659951}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F327E31026E // GetFolder
 ME_4DAED6F60146_ME_4F327E31026E // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_97199BEDBADE // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K336659951.pas'
 CONST extprop:rc:SelfName 'K336659951'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'K336659951'

ref; // ME_4F327E31026E TK336659951

FORWARD ME_4F339DA501A7

: ME_C145EA34E0FA
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F339DA501A7 // K336660676
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_C145EA34E0FA 

: ME_4C937013031D_ME_4F339DA501A7
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F339DA501A7 // K336660676
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F339DA501A7 GetFolder

: ME_4DAED6F60146_ME_4F339DA501A7
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F339DA501A7 // K336660676
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F339DA501A7 GetModelElementGUID

: ME_4F339DA501A7
 CONST UID '4F339DA501A7'
 CONST Name 'K336660676'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:336660676}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F339DA501A7 // GetFolder
 ME_4DAED6F60146_ME_4F339DA501A7 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_C145EA34E0FA // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K336660676.pas'
 CONST extprop:pas:TypeName 'TK336660676'
 CONST extprop:rc:SelfName 'K336660676'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F339DA501A7 K336660676

FORWARD ME_4F339DC80012

: ME_4EFD362FADBF
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F339DC80012 // K235864238
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_4EFD362FADBF 

: ME_4C937013031D_ME_4F339DC80012
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F339DC80012 // K235864238
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F339DC80012 GetFolder

: ME_4DAED6F60146_ME_4F339DC80012
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F339DC80012 // K235864238
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F339DC80012 GetModelElementGUID

: ME_4F339DC80012
 CONST UID '4F339DC80012'
 CONST Name 'K235864238'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:235864238}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F339DC80012 // GetFolder
 ME_4DAED6F60146_ME_4F339DC80012 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_4EFD362FADBF // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K235864238.pas'
 CONST extprop:pas:TypeName 'TK235864238'
 CONST extprop:rc:SelfName 'K235864238'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F339DC80012 K235864238

FORWARD ME_4F339DEC030C

: ME_4836BF287496
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F339DEC030C // K235864247
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_4836BF287496 

: ME_4C937013031D_ME_4F339DEC030C
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F339DEC030C // K235864247
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F339DEC030C GetFolder

: ME_4DAED6F60146_ME_4F339DEC030C
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F339DEC030C // K235864247
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F339DEC030C GetModelElementGUID

: ME_4F339DEC030C
 CONST UID '4F339DEC030C'
 CONST Name 'K235864247'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:235864247}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F339DEC030C // GetFolder
 ME_4DAED6F60146_ME_4F339DEC030C // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_4836BF287496 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K235864247.pas'
 CONST extprop:pas:TypeName 'TK235864247'
 CONST extprop:rc:SelfName 'K235864247'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F339DEC030C K235864247

FORWARD ME_4F4B277E035B

: ME_5279F3A46612
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4B277E035B // K341838531
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_5279F3A46612 

: ME_4C937013031D_ME_4F4B277E035B
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F4B277E035B // K341838531
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F4B277E035B GetFolder

: ME_4DAED6F60146_ME_4F4B277E035B
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F4B277E035B // K341838531
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F4B277E035B GetModelElementGUID

: ME_4F4B277E035B
 CONST UID '4F4B277E035B'
 CONST Name 'K341838531'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:341838531}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F4B277E035B // GetFolder
 ME_4DAED6F60146_ME_4F4B277E035B // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_5279F3A46612 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K341838531.pas'
 CONST extprop:pas:TypeName 'TK341838531'
 CONST extprop:rc:SelfName 'K341838531'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F4B277E035B K341838531

FORWARD ME_4F50C48F01E0

: ME_D5727155648E
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F50C48F01E0 // K342862858
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_D5727155648E 

: ME_4C937013031D_ME_4F50C48F01E0
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F50C48F01E0 // K342862858
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F50C48F01E0 GetFolder

: ME_4DAED6F60146_ME_4F50C48F01E0
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F50C48F01E0 // K342862858
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F50C48F01E0 GetModelElementGUID

: ME_4F50C48F01E0
 CONST UID '4F50C48F01E0'
 CONST Name 'K342862858'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:342862858}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F50C48F01E0 // GetFolder
 ME_4DAED6F60146_ME_4F50C48F01E0 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_D5727155648E // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K342862858.pas'
 CONST extprop:pas:TypeName 'TK342862858'
 CONST extprop:rc:SelfName 'K342862858'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F50C48F01E0 K342862858

FORWARD ME_4F6ABC16018E

: ME_AC95DC897CFA
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F6ABC16018E // TK349116289
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_AC95DC897CFA 

: ME_4C937013031D_ME_4F6ABC16018E
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F6ABC16018E // TK349116289
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F6ABC16018E GetFolder

: ME_4DAED6F60146_ME_4F6ABC16018E
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F6ABC16018E // TK349116289
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F6ABC16018E GetModelElementGUID

: ME_4F6ABC16018E
 CONST UID '4F6ABC16018E'
 CONST Name 'TK349116289'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:349116289}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F6ABC16018E // GetFolder
 ME_4DAED6F60146_ME_4F6ABC16018E // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_AC95DC897CFA // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K349116289.pas'
 CONST extprop:rc:SelfName 'K349116289'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'K349116289'

ref; // ME_4F6ABC16018E TK349116289

FORWARD ME_4F759A710336

: ME_980118EE072B
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F759A710336 // K354255065
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_980118EE072B 

: ME_4C937013031D_ME_4F759A710336
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F759A710336 // K354255065
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F759A710336 GetFolder

: ME_4DAED6F60146_ME_4F759A710336
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F759A710336 // K354255065
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F759A710336 GetModelElementGUID

: ME_4F759A710336
 CONST UID '4F759A710336'
 CONST Name 'K354255065'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:354255065}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F759A710336 // GetFolder
 ME_4DAED6F60146_ME_4F759A710336 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_980118EE072B // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K354255065.pas'
 CONST extprop:pas:TypeName 'TK354255065'
 CONST extprop:rc:SelfName 'K354255065'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F759A710336 K354255065

FORWARD ME_4F8D0A22020F

: ME_FAD09F95223C
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F8D0A22020F // K358354724
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_FAD09F95223C 

: ME_4C937013031D_ME_4F8D0A22020F
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4F8D0A22020F // K358354724
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4F8D0A22020F GetFolder

: ME_4DAED6F60146_ME_4F8D0A22020F
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4F8D0A22020F // K358354724
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4F8D0A22020F GetModelElementGUID

: ME_4F8D0A22020F
 CONST UID '4F8D0A22020F'
 CONST Name 'K358354724'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:358354724}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4F8D0A22020F // GetFolder
 ME_4DAED6F60146_ME_4F8D0A22020F // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_FAD09F95223C // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K358354724.pas'
 CONST extprop:pas:TypeName 'TK358354724'
 CONST extprop:rc:SelfName 'K358354724'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F8D0A22020F K358354724

FORWARD ME_4FB49FB602A4

: ME_ADE1CF8D64B7
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4FB49FB602A4 // K358365470
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_ADE1CF8D64B7 

: ME_4C937013031D_ME_4FB49FB602A4
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4FB49FB602A4 // K358365470
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4FB49FB602A4 GetFolder

: ME_4DAED6F60146_ME_4FB49FB602A4
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4FB49FB602A4 // K358365470
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4FB49FB602A4 GetModelElementGUID

: ME_4FB49FB602A4
 CONST UID '4FB49FB602A4'
 CONST Name 'K358365470'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:358365470}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4FB49FB602A4 // GetFolder
 ME_4DAED6F60146_ME_4FB49FB602A4 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_ADE1CF8D64B7 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K358365470.pas'
 CONST extprop:pas:TypeName 'TK358365470'
 CONST extprop:rc:SelfName 'K358365470'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4FB49FB602A4 K358365470

FORWARD ME_4FCE1487026F

: ME_CBEEEBF900C9
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4FCE1487026F // K370383707
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_CBEEEBF900C9 

: ME_4C937013031D_ME_4FCE1487026F
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_4FCE1487026F // K370383707
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_4FCE1487026F GetFolder

: ME_4DAED6F60146_ME_4FCE1487026F
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_4FCE1487026F // K370383707
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_4FCE1487026F GetModelElementGUID

: ME_4FCE1487026F
 CONST UID '4FCE1487026F'
 CONST Name 'K370383707'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:370383707}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_4FCE1487026F // GetFolder
 ME_4DAED6F60146_ME_4FCE1487026F // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_CBEEEBF900C9 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K370383707.pas'
 CONST extprop:pas:TypeName 'TK370383707'
 CONST extprop:rc:SelfName 'K370383707'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4FCE1487026F K370383707

FORWARD ME_5012632F0145

: ME_853922189CF0
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_5012632F0145 // TK380044630
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_853922189CF0 

: ME_4C937013031D_ME_5012632F0145
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_5012632F0145 // TK380044630
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_5012632F0145 GetFolder

: ME_4DAED6F60146_ME_5012632F0145
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_5012632F0145 // TK380044630
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_5012632F0145 GetModelElementGUID

: ME_5012632F0145
 CONST UID '5012632F0145'
 CONST Name 'TK380044630'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:380044630}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_5012632F0145 // GetFolder
 ME_4DAED6F60146_ME_5012632F0145 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_853922189CF0 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K380044630.pas'
 CONST extprop:rc:SelfName 'K380044630'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'K380044630'

ref; // ME_5012632F0145 TK380044630

FORWARD ME_5048AA03036F

: ME_99DD3560D482
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_5048AA03036F // K390585154
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_99DD3560D482 

: ME_4C937013031D_ME_5048AA03036F
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_5048AA03036F // K390585154
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_5048AA03036F GetFolder

: ME_4DAED6F60146_ME_5048AA03036F
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_5048AA03036F // K390585154
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_5048AA03036F GetModelElementGUID

: ME_5048AA03036F
 CONST UID '5048AA03036F'
 CONST Name 'K390585154'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:390585154}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_5048AA03036F // GetFolder
 ME_4DAED6F60146_ME_5048AA03036F // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_99DD3560D482 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K390585154.pas'
 CONST extprop:pas:TypeName 'TK390585154'
 CONST extprop:rc:SelfName 'K390585154'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5048AA03036F K390585154

FORWARD ME_505822EB0095

: ME_0A13C616DA07
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_505822EB0095 // TK395647218
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_0A13C616DA07 

: ME_4C937013031D_ME_505822EB0095
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_505822EB0095 // TK395647218
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_505822EB0095 GetFolder

: ME_4DAED6F60146_ME_505822EB0095
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_505822EB0095 // TK395647218
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_505822EB0095 GetModelElementGUID

: ME_505822EB0095
 CONST UID '505822EB0095'
 CONST Name 'TK395647218'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:395647218}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_505822EB0095 // GetFolder
 ME_4DAED6F60146_ME_505822EB0095 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_0A13C616DA07 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K395647218.pas'
 CONST extprop:rc:SelfName 'K395647218'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'K395647218'

ref; // ME_505822EB0095 TK395647218

FORWARD ME_506A965C0032

: ME_A77178C4093E
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_506A965C0032 // K395658761
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_A77178C4093E 

: ME_4C937013031D_ME_506A965C0032
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_506A965C0032 // K395658761
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_506A965C0032 GetFolder

: ME_4DAED6F60146_ME_506A965C0032
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_506A965C0032 // K395658761
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_506A965C0032 GetModelElementGUID

: ME_506A965C0032
 CONST UID '506A965C0032'
 CONST Name 'K395658761'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:395658761}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_506A965C0032 // GetFolder
 ME_4DAED6F60146_ME_506A965C0032 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_A77178C4093E // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K395658761.pas'
 CONST extprop:pas:TypeName 'TK395658761'
 CONST extprop:rc:SelfName 'K395658761'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_506A965C0032 K395658761

FORWARD ME_506AE10B03CF

: ME_AFD684824BE7
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_506AE10B03CF // K395654924
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_AFD684824BE7 

: ME_4C937013031D_ME_506AE10B03CF
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_506AE10B03CF // K395654924
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_506AE10B03CF GetFolder

: ME_4DAED6F60146_ME_506AE10B03CF
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_506AE10B03CF // K395654924
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_506AE10B03CF GetModelElementGUID

: ME_506AE10B03CF
 CONST UID '506AE10B03CF'
 CONST Name 'K395654924'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:395654924}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_506AE10B03CF // GetFolder
 ME_4DAED6F60146_ME_506AE10B03CF // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_AFD684824BE7 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K395654924.pas'
 CONST extprop:pas:TypeName 'TK395654924'
 CONST extprop:rc:SelfName 'K395654924'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_506AE10B03CF K395654924

FORWARD ME_506BE91B0045

: ME_4E5402103DE0
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_506BE91B0045 // K395659375
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_4E5402103DE0 

: ME_4C937013031D_ME_506BE91B0045
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_506BE91B0045 // K395659375
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_506BE91B0045 GetFolder

: ME_4DAED6F60146_ME_506BE91B0045
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_506BE91B0045 // K395659375
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_506BE91B0045 GetModelElementGUID

: ME_506BE91B0045
 CONST UID '506BE91B0045'
 CONST Name 'K395659375'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:395659375}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_506BE91B0045 // GetFolder
 ME_4DAED6F60146_ME_506BE91B0045 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_4E5402103DE0 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K395659375.pas'
 CONST extprop:pas:TypeName 'TK395659375'
 CONST extprop:rc:SelfName 'K395659375'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_506BE91B0045 K395659375

FORWARD ME_50750748009E

: ME_E6A6E44ED87F
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_50750748009E // K400531159
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_E6A6E44ED87F 

: ME_4C937013031D_ME_50750748009E
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_50750748009E // K400531159
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_50750748009E GetFolder

: ME_4DAED6F60146_ME_50750748009E
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_50750748009E // K400531159
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_50750748009E GetModelElementGUID

: ME_50750748009E
 CONST UID '50750748009E'
 CONST Name 'K400531159'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:400531159}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_50750748009E // GetFolder
 ME_4DAED6F60146_ME_50750748009E // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_E6A6E44ED87F // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K400531159.pas'
 CONST extprop:pas:TypeName 'TK400531159'
 CONST extprop:rc:SelfName 'K400531159'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_50750748009E K400531159

FORWARD ME_509277C40387

: ME_98FC94F7FA44
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_509277C40387 // K407150344
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_98FC94F7FA44 

: ME_4C937013031D_ME_509277C40387
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_509277C40387 // K407150344
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_509277C40387 GetFolder

: ME_4DAED6F60146_ME_509277C40387
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_509277C40387 // K407150344
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_509277C40387 GetModelElementGUID

: ME_509277C40387
 CONST UID '509277C40387'
 CONST Name 'K407150344'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:407150344}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_509277C40387 // GetFolder
 ME_4DAED6F60146_ME_509277C40387 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_98FC94F7FA44 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K407150344.pas'
 CONST extprop:pas:TypeName 'TK407150344'
 CONST extprop:rc:SelfName 'K407150344'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_509277C40387 K407150344

FORWARD ME_50B4827A00F2

: ME_40AAB2457805
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_50B4827A00F2 // K410628348
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_40AAB2457805 

: ME_4C937013031D_ME_50B4827A00F2
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_50B4827A00F2 // K410628348
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_50B4827A00F2 GetFolder

: ME_4DAED6F60146_ME_50B4827A00F2
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_50B4827A00F2 // K410628348
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_50B4827A00F2 GetModelElementGUID

: ME_50B4827A00F2
 CONST UID '50B4827A00F2'
 CONST Name 'K410628348'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:410628348}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_50B4827A00F2 // GetFolder
 ME_4DAED6F60146_ME_50B4827A00F2 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_40AAB2457805 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K410628348.pas'
 CONST extprop:pas:TypeName 'TK410628348'
 CONST extprop:rc:SelfName 'K410628348'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_50B4827A00F2 K410628348

FORWARD ME_517921480169

: ME_57D0A7A23124
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_517921480169 // K431359667
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_57D0A7A23124 

: ME_4C937013031D_ME_517921480169
 CONST UID '4C937013031D'
 CONST Name 'GetFolder'
 : Original WL 'ME_4C937013031D' '4B2A0D6A0077.pas.ms.script' // GetFolder
 ;
 : Implementor ME_517921480169 // K431359667
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4C937013031D_ME_517921480169 GetFolder

: ME_4DAED6F60146_ME_517921480169
 CONST UID '4DAED6F60146'
 CONST Name 'GetModelElementGUID'
 : Original WL 'ME_4DAED6F60146' '4B2A0D6A0077.pas.ms.script' // GetModelElementGUID
 ;
 : Implementor ME_517921480169 // K431359667
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DAED6F60146_ME_517921480169 GetModelElementGUID

: ME_517921480169
 CONST UID '517921480169'
 CONST Name 'K431359667'
 CONST Class class_Class
 : Stereotype st_TestCase ;
 CONST Kind kind_NormalClass
 %SUMMARY '{Requestlink:431359667}' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EF1A15303DD // TableTools
 ;
 : Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.pas.ms.script' // TArchiInsiderTest
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4C937013031D_ME_517921480169 // GetFolder
 ME_4DAED6F60146_ME_517921480169 // GetModelElementGUID
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_57D0A7A23124 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\Archi\Tests\K431359667.pas'
 CONST extprop:pas:TypeName 'TK431359667'
 CONST extprop:rc:SelfName 'K431359667'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_517921480169 K431359667

: ME_4EF1A15303DD
 CONST UID '4EF1A15303DD'
 CONST Name 'TableTools'
 CONST Class class_Category
 : Stereotype st_TestUnit ;
 %SUMMARY 'Тесты работы с таблицами' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4DE765AE02EB' '4DE765AE02EB.pas.ms.script' // ArchiInsiderTests
 ;
 : Children
   Seq: ( ME_4E310F43015A // K104434922
 ME_4E8EDEE500A6 // K290947845
 ME_4ECCEB2A01A9 // K290951663
 ME_4E97DA6401A2 // K290951686
 ME_4EF2F4C502FE // K297703832
 ME_4EF86F3203E5 // K323061070
 ME_4F1FD3B801C1 // TK330140470
 ME_4F2946A6031A // K330140904
 ME_4F2A8BDC02A8 // K333550210
 ME_4F30E48602B2 // TK336137132
 ME_4F30E49D0064 // TK336137156
 ME_4F327E31026E // TK336659951
 ME_4F339DA501A7 // K336660676
 ME_4F339DC80012 // K235864238
 ME_4F339DEC030C // K235864247
 ME_4F4B277E035B // K341838531
 ME_4F50C48F01E0 // K342862858
 ME_4F6ABC16018E // TK349116289
 ME_4F759A710336 // K354255065
 ME_4F8D0A22020F // K358354724
 ME_4FB49FB602A4 // K358365470
 ME_4FCE1487026F // K370383707
 ME_5012632F0145 // TK380044630
 ME_5048AA03036F // K390585154
 ME_505822EB0095 // TK395647218
 ME_506A965C0032 // K395658761
 ME_506AE10B03CF // K395654924
 ME_506BE91B0045 // K395659375
 ME_50750748009E // K400531159
 ME_509277C40387 // K407150344
 ME_50B4827A00F2 // K410628348
 ME_517921480169 // K431359667
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4B2A0D6A0077' '4B2A0D6A0077.pas.ms.script' // Source
 WL 'ME_4DE3425B01DA' '4DE3425B01DA.pas.ms.script' // ArchiScriptSupport
 )
 ; // Depends

ref; // ME_4EF1A15303DD TableTools
