// m2InternalInterfaces 4EFAE5C10224 Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4EFAE5C10224

FORWARD ME_4EFAE5FE00C7

: ME_4EFAE62A0025
 CONST UID '4EFAE62A0025'
 CONST Name 'Access'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'режим доступа' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4EFAE5FE00C7 // Im2StoreStat
 ;
 : Target WL 'ME_4DE60F5E00A6' '4AB0C3C60310.pas.ms.script' // LongInt
 ;
 CONST "pm" true

ref; // ME_4EFAE62A0025 Access

: ME_4EFAE64E031B
 CONST UID '4EFAE64E031B'
 CONST Name 'LocksSupported'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'какие замки доступны?' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4EFAE5FE00C7 // Im2StoreStat
 ;
 : Target WL 'ME_4DE60F5E00A6' '4AB0C3C60310.pas.ms.script' // LongInt
 ;
 CONST "pm" true

ref; // ME_4EFAE64E031B LocksSupported

: ME_4EFAE66C02BA
 CONST UID '4EFAE66C02BA'
 CONST Name 'Size'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'размер' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4EFAE5FE00C7 // Im2StoreStat
 ;
 : Target WL 'ME_47208C70028B' '4AB0C3C60310.pas.ms.script' // Int64
 ;
 CONST "pm" true

ref; // ME_4EFAE66C02BA Size

: ME_4EFAF2DF01C3
 CONST UID '4EFAF2DF01C3'
 CONST Name 'Position'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Позиция' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4EFAE5FE00C7 // Im2StoreStat
 ;
 : Target WL 'ME_47208C70028B' '4AB0C3C60310.pas.ms.script' // Int64
 ;
 CONST "pm" true

ref; // ME_4EFAF2DF01C3 Position

: ME_5412F6940100
 CONST UID '5412F6940100'
 CONST Name 'Name'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_4EFAE5FE00C7 // Im2StoreStat
 ;
 : Target WL 'ME_498849D803A8' '4AB0C3C60310.pas.ms.script' // WideString
 ;
 CONST "pm" false

ref; // ME_5412F6940100 Name

: ME_4EFAE5FE00C7
 CONST UID '4EFAE5FE00C7'
 CONST GUID '1B212038-ED47-447A-811D-CA3891B5B5E0'
 CONST Name 'Im2StoreStat'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Информация о хранилище' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4EFAE5C10224 // m2InternalInterfaces
 ;
 : Attributes
   Seq: ( ME_4EFAE62A0025 // Access
 ME_4EFAE64E031B // LocksSupported
 ME_4EFAE66C02BA // Size
 ME_4EFAF2DF01C3 // Position
 ME_5412F6940100 // Name
 )
 ; // Attributes
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\L3\m2'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'
 CONST extprop:rc:SelfName 'm2StoreStat'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4EFAE5FE00C7 Im2StoreStat

: ME_4EFAE5C10224
 CONST UID '4EFAE5C10224'
 CONST Name 'm2InternalInterfaces'
 CONST Class class_Category
 : Stereotype st_Interfaces ;
 %SUMMARY 'Внутренние интерфейсы библиотеки m2' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4790D09A0378' '4790D09A0378.pas.ms.script' // L3
 ;
 : Children
   Seq: ( ME_4EFAE5FE00C7 // Im2StoreStat
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 )
 ; // Depends
 CONST "author" 'Люлин А.В.'
 CONST "defines" 'm2Define.inc'
 CONST "is namespace" true
 CONST "no hands" false
 CONST "path prefix" '/m2'
 CONST "started" '31.10.2001 12:01'
 CONST intf.pas:Path 'common\components\rtl\Garant\L3\m2\m2InternalInterfaces.pas'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\L3\m2'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\4EFAE5C10224.pas.ms.script'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\4EFAE5C10224.pas.ms.script.runner'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_4EFAE5C10224 m2InternalInterfaces
