// TtfwConstLike 4F3BC124004D SimpleClass Class

INCLUDE '4DB9B6D20168.pas.ms.script'

INCLUDE '4DB6C8F30161.pas.ms.script'

FORWARD ME_4F3BC124004D

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_5C173D4988C9
 CONST UID '5C173D4988C9'
 CONST Name 'Ini_Reg_Class'
 CONST Class 'Operation'
 CONST Stereotype 'ini'
 %SUMMARY 'Регистрация TtfwConstLike' ;
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 CONST "ifndef" 'NoScripts'

 @SELF
; // ME_5C173D4988C9 Ini_Reg_Class

: ME_4F3BC124004D
 CONST UID '4F3BC124004D'
 CONST Name 'TtfwConstLike'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'abstract'
 : Inherits
   [ ME_4DB9B6D20168 // TtfwNewWord
 ]
 ; // Inherits
 : Operations
   [ ME_5C173D4988C9 // Ini_Reg_Class
 ]
 ; // Operations
 : Implemented
   [ ME_4DB6C99F026E // EndBracket
 ]
 ; // Implemented
 : Overridden
   [ ME_4DB9B446039A // AfterWordMaxCount
 ME_4DBAEE0D028D // CompiledWordClass
 ]
 ; // Overridden
 CONST "author" 'Люлин А.В.'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '15.02.2012 18:29'

 @SELF
; // ME_4F3BC124004D TtfwConstLike
