// ScrollTests 4F4E055A0054 TestUnit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4F4E055A0054
%%Inner ME_4F4E055A0054
%%Inner ME_4F4E055A0054
%%Inner ME_4F4E055A0054
%%Inner ME_4F4E055A0054
%%Inner ME_4F4E055A0054
%%Inner ME_4F4E055A0054
%%Inner ME_4F4E055A0054
%%Inner ME_4F4E055A0054
%%Inner ME_4F4E055A0054
%%Inner ME_4F4E055A0054
%%Inner ME_4F4E055A0054
%%Inner ME_4F4E055A0054

FORWARD ME_4F4E055A0054

%%InheritedBy ME_4DE4827600CA ME_4F4E05E60072

ME ME_4F4E05E60072
 MEPROP UID '4F4E05E60072'
 MEPROP Name 'K159367236'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:159367236}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K159367236.pas'
 UP extprop:pas:TypeName 'TK159367236'
 UP extprop:rc:SelfName 'K159367236'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_4F4E05E60072 K159367236

%%InheritedBy ME_4DE4827600CA ME_4E8D60820179

ME ME_4E8D60820179
 MEPROP UID '4E8D60820179'
 MEPROP Name 'K289276523'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '[$289276523]' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K289276523.pas'
 UP extprop:pas:TypeName 'TK289276523'
 UP extprop:rc:SelfName 'K289276523'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_4E8D60820179 K289276523

%%InheritedBy ME_4DE4827600CA ME_4ECE02FF027B

ME ME_4ECE02FF027B
 MEPROP UID '4ECE02FF027B'
 MEPROP Name 'K299140051'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{RequestLink:299140051}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K299140051.pas'
 UP extprop:pas:TypeName 'TK299140051'
 UP extprop:rc:SelfName 'K299140051'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_4ECE02FF027B K299140051

%%InheritedBy ME_4DE4827600CA ME_4F55F2BD029C

ME ME_4F55F2BD029C
 MEPROP UID '4F55F2BD029C'
 MEPROP Name 'K342866806'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:342866806}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K342866806.pas'
 UP extprop:pas:TypeName 'TK342866806'
 UP extprop:rc:SelfName 'K342866806'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_4F55F2BD029C K342866806

%%InheritedBy ME_4DE4827600CA ME_4F560F5A0088

ME ME_4F560F5A0088
 MEPROP UID '4F560F5A0088'
 MEPROP Name 'K343640765'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:343640765}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K343640765.pas'
 UP extprop:pas:TypeName 'TK343640765'
 UP extprop:rc:SelfName 'K343640765'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_4F560F5A0088 K343640765

%%InheritedBy ME_4DE4827600CA ME_4FF584D60379

ME ME_4FF584D60379
 MEPROP UID '4FF584D60379'
 MEPROP Name 'K370383768'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:370383768}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K370383768.pas'
 UP extprop:pas:TypeName 'TK370383768'
 UP extprop:rc:SelfName 'K370383768'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_4FF584D60379 K370383768

%%InheritedBy ME_4DE4827600CA ME_502DF19E0267

ME ME_502DF19E0267
 MEPROP UID '502DF19E0267'
 MEPROP Name 'K382421131'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:382421131}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K382421131.pas'
 UP extprop:pas:TypeName 'TK382421131'
 UP extprop:rc:SelfName 'K382421131'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_502DF19E0267 K382421131

%%InheritedBy ME_4DE4827600CA ME_508FB257033B

ME ME_508FB257033B
 MEPROP UID '508FB257033B'
 MEPROP Name 'K407150878'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:407150878}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K407150878.pas'
 UP extprop:pas:TypeName 'TK407150878'
 UP extprop:rc:SelfName 'K407150878'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_508FB257033B K407150878

%%InheritedBy ME_4DE4827600CA ME_50A0C5B90295

ME ME_50A0C5B90295
 MEPROP UID '50A0C5B90295'
 MEPROP Name 'K407736033'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:407736033}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K407736033.pas'
 UP extprop:pas:TypeName 'TK407736033'
 UP extprop:rc:SelfName 'K407736033'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_50A0C5B90295 K407736033

%%InheritedBy ME_4DE4827600CA ME_50AF42CD0309

ME ME_50AF42CD0309
 MEPROP UID '50AF42CD0309'
 MEPROP Name 'K404361004'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:404361004}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K404361004.pas'
 UP extprop:pas:TypeName 'TK404361004'
 UP extprop:rc:SelfName 'K404361004'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_50AF42CD0309 K404361004

%%InheritedBy ME_4DE4827600CA ME_50D961520067

ME ME_50D961520067
 MEPROP UID '50D961520067'
 MEPROP Name 'K421123801'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:421123801}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K421123801.pas'
 UP extprop:pas:TypeName 'TK421123801'
 UP extprop:rc:SelfName 'K421123801'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_50D961520067 K421123801

%%InheritedBy ME_4DE4827600CA ME_50EFBD870384

ME ME_50EFBD870384
 MEPROP UID '50EFBD870384'
 MEPROP Name 'K423593340'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:423593340}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K423593340.pas'
 UP extprop:pas:TypeName 'TK423593340'
 UP extprop:rc:SelfName 'K423593340'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_50EFBD870384 K423593340

%%InheritedBy ME_4DE4827600CA ME_5110BFC6038E

ME ME_5110BFC6038E
 MEPROP UID '5110BFC6038E'
 MEPROP Name 'K425036023'
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:425036023}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4F4E055A0054 // ScrollTests
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4DE4827600CA' '4DE3425B01DA.ms.model.script' // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K425036023.pas'
 UP extprop:pas:TypeName 'TK425036023'
 UP extprop:rc:SelfName 'K425036023'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_5110BFC6038E K425036023

ME ME_4F4E055A0054
 MEPROP UID '4F4E055A0054'
 MEPROP Name 'ScrollTests'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_TestUnit ;
 %SUMMARY 'Тесты прокрутки.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4DE765AE02EB' '4DE765AE02EB.ms.model.script' // ArchiInsiderTests
 ;
 MELIST Children
   Seq: ( HWL ME_4F4E05E60072 // K159367236
 HWL ME_4E8D60820179 // K289276523
 HWL ME_4ECE02FF027B // K299140051
 HWL ME_4F55F2BD029C // K342866806
 HWL ME_4F560F5A0088 // K343640765
 HWL ME_4FF584D60379 // K370383768
 HWL ME_502DF19E0267 // K382421131
 HWL ME_508FB257033B // K407150878
 HWL ME_50A0C5B90295 // K407736033
 HWL ME_50AF42CD0309 // K404361004
 HWL ME_50D961520067 // K421123801
 HWL ME_50EFBD870384 // K423593340
 HWL ME_5110BFC6038E // K425036023
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_4DE3425B01DA' '4DE3425B01DA.ms.model.script' // ArchiScriptSupport
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP Version 0

ENDME // ME_4F4E055A0054 ScrollTests
