// FileProcessing 4F4FD6CC0295 ScriptKeywords Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4F4FD6CC0295

FORWARD ME_4F4FD7EA00EB

FORWARD ME_4F4FD77B03CC

: ME_4F4FD78A01EF
 CONST UID '4F4FD78A01EF'
 CONST Name 'f_Filer'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_4F4FD77B03CC // TtfwFile
 ;
 : Target WL 'ME_4B4F61AD01AA' '47913B47006E.pas.ms.script' // Tl3CustomDosFiler
 ;

ref; // ME_4F4FD78A01EF f_Filer

FORWARD ME_4F4FD849026C

: ME_4F4FD85C007C
 CONST Name 'aFileName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4F4FD85C007C aFileName

: ME_4F4FD85202B5
 CONST UID '4F4FD85202B5'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD849026C // CreateRead
 ;
 : Parameters
   Seq: ( ME_4F4FD85C007C // aFileName
 )
 ; // Parameters

ref; // ME_4F4FD85202B5 DoIt

: ME_4F4FD849026C
 CONST UID '4F4FD849026C'
 CONST Name 'CreateRead'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD77B03CC // TtfwFile
 ;
 : Operations
   Seq: ( ME_4F4FD85202B5 // DoIt
 )
 ; // Operations

ref; // ME_4F4FD849026C CreateRead

FORWARD ME_4F4FD85F033A

: ME_4F4FD88403DE
 CONST Name 'aFileName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4F4FD88403DE aFileName

: ME_4F4FD8800331
 CONST UID '4F4FD8800331'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD85F033A // CreateWrite
 ;
 : Parameters
   Seq: ( ME_4F4FD88403DE // aFileName
 )
 ; // Parameters

ref; // ME_4F4FD8800331 DoIt

: ME_4F4FD85F033A
 CONST UID '4F4FD85F033A'
 CONST Name 'CreateWrite'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD77B03CC // TtfwFile
 ;
 : Operations
   Seq: ( ME_4F4FD8800331 // DoIt
 )
 ; // Operations

ref; // ME_4F4FD85F033A CreateWrite

: ME_4F4FD88C01B2
 CONST UID '4F4FD88C01B2'
 CONST Name 'MakeRead'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD77B03CC // TtfwFile
 ;
 : Inherits
   Seq: ( ME_4F4FD849026C // CreateRead
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4F4E4E7101D6' '4DAF19F600C5.pas.ms.script' // ItfwFile
 )
 ; // Implements

ref; // ME_4F4FD88C01B2 MakeRead

: ME_4F4FD89C00DB
 CONST UID '4F4FD89C00DB'
 CONST Name 'MakeWrite'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD77B03CC // TtfwFile
 ;
 : Inherits
   Seq: ( ME_4F4FD85F033A // CreateWrite
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4F4E4E7101D6' '4DAF19F600C5.pas.ms.script' // ItfwFile
 )
 ; // Implements

ref; // ME_4F4FD89C00DB MakeWrite

FORWARD ME_570E70230377

: ME_570E703102A4
 CONST Name 'aFileName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_570E703102A4 aFileName

: ME_570E70300295
 CONST UID '570E70300295'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_570E70230377 // CreateAppend
 ;
 : Parameters
   Seq: ( ME_570E703102A4 // aFileName
 )
 ; // Parameters

ref; // ME_570E70300295 DoIt

: ME_570E70230377
 CONST UID '570E70230377'
 CONST Name 'CreateAppend'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD77B03CC // TtfwFile
 ;
 : Operations
   Seq: ( ME_570E70300295 // DoIt
 )
 ; // Operations

ref; // ME_570E70230377 CreateAppend

: ME_570E7037029C
 CONST UID '570E7037029C'
 CONST Name 'MakeAppend'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD77B03CC // TtfwFile
 ;
 : Inherits
   Seq: ( ME_570E70230377 // CreateAppend
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4F4E4E7101D6' '4DAF19F600C5.pas.ms.script' // ItfwFile
 )
 ; // Implements

ref; // ME_570E7037029C MakeAppend

: ME_4F4FD7BB0384
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4FD77B03CC // TtfwFile
 ;
 : Target WL 'ME_48F4BE400154' '4678193C009C.pas.ms.script' // Tl3FileMode
 ;

ref; // ME_4F4FD7BB0384 

: ME_4F4FD8DA01C1
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4FD77B03CC // TtfwFile
 ;
 : Target WL 'ME_4DE89E560091' '4AB0C3C60310.pas.ms.script' // Format
 ;

ref; // ME_4F4FD8DA01C1 

: ME_4F4FD9E7017E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4FD77B03CC // TtfwFile
 ;
 : Target WL 'ME_47878E0E0191' '54B90AC6014B.pas.ms.script' // l3String
 ;

ref; // ME_4F4FD9E7017E 

: ME_4F4E4E7E0350_ME_4F4FD77B03CC
 : Original WL 'ME_4F4E4E7E0350' '4DAF19F600C5.pas.ms.script' // ReadLn
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F4E4E7E0350_ME_4F4FD77B03CC ReadLn

: ME_4F4E4EA7007D_ME_4F4FD77B03CC
 : Original WL 'ME_4F4E4EA7007D' '4DAF19F600C5.pas.ms.script' // WriteLn
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F4E4EA7007D_ME_4F4FD77B03CC WriteLn

: ME_4F4FDC540264_ME_4F4FD77B03CC
 : Original WL 'ME_4F4FDC540264' '4DAF19F600C5.pas.ms.script' // WriteChar
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F4FDC540264_ME_4F4FD77B03CC WriteChar

: ME_4F4FE16A0269_ME_4F4FD77B03CC
 : Original WL 'ME_4F4FE16A0269' '4DAF19F600C5.pas.ms.script' // ReadWStrLn
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F4FE16A0269_ME_4F4FD77B03CC ReadWStrLn

: ME_4F4FE19301A1_ME_4F4FD77B03CC
 : Original WL 'ME_4F4FE19301A1' '4DAF19F600C5.pas.ms.script' // WriteWStrLn
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F4FE19301A1_ME_4F4FD77B03CC WriteWStrLn

: ME_4F4FE1B40314_ME_4F4FD77B03CC
 : Original WL 'ME_4F4FE1B40314' '4DAF19F600C5.pas.ms.script' // WriteWStr
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F4FE1B40314_ME_4F4FD77B03CC WriteWStr

: ME_4F50821201E7_ME_4F4FD77B03CC
 : Original WL 'ME_4F50821201E7' '4DAF19F600C5.pas.ms.script' // EOF
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F50821201E7_ME_4F4FD77B03CC EOF

: ME_52E23B7A00EC_ME_4F4FD77B03CC
 : Original WL 'ME_52E23B7A00EC' '4DAF19F600C5.pas.ms.script' // ForEach
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52E23B7A00EC_ME_4F4FD77B03CC ForEach

: ME_52E23BB102FA_ME_4F4FD77B03CC
 : Original WL 'ME_52E23BB102FA' '4DAF19F600C5.pas.ms.script' // ForEachBack
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52E23BB102FA_ME_4F4FD77B03CC ForEachBack

: ME_479731C50290_ME_4F4FD77B03CC
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_4F4FD77B03CC Cleanup

: ME_4F4FD77B03CC
 CONST UID '4F4FD77B03CC'
 CONST Name 'TtfwFile'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Inherits
   Seq: ( WL 'ME_4AE5CA2D0034' '47913B47006E.pas.ms.script' // Tl3CProtoObject
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4F4E4E7101D6' '4DAF19F600C5.pas.ms.script' // ItfwFile
 )
 ; // Implements
 : Attributes
   Seq: ( ME_4F4FD78A01EF // f_Filer
 )
 ; // Attributes
 : Operations
   Seq: ( ME_4F4FD849026C // CreateRead
 ME_4F4FD85F033A // CreateWrite
 ME_4F4FD88C01B2 // MakeRead
 ME_4F4FD89C00DB // MakeWrite
 ME_570E70230377 // CreateAppend
 ME_570E7037029C // MakeAppend
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4F4E4E7E0350_ME_4F4FD77B03CC // ReadLn
 ME_4F4E4EA7007D_ME_4F4FD77B03CC // WriteLn
 ME_4F4FDC540264_ME_4F4FD77B03CC // WriteChar
 ME_4F4FE16A0269_ME_4F4FD77B03CC // ReadWStrLn
 ME_4F4FE19301A1_ME_4F4FD77B03CC // WriteWStrLn
 ME_4F4FE1B40314_ME_4F4FD77B03CC // WriteWStr
 ME_4F50821201E7_ME_4F4FD77B03CC // EOF
 ME_52E23B7A00EC_ME_4F4FD77B03CC // ForEach
 ME_52E23BB102FA_ME_4F4FD77B03CC // ForEachBack
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_4F4FD77B03CC // Cleanup
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_4F4FD7BB0384 // Tl3FileMode
 ME_4F4FD8DA01C1 // Format
 ME_4F4FD9E7017E // l3String
 )
 ; // Dependencies
 CONST extprop:rc:SelfName 'File'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F4FD77B03CC TtfwFile

: ME_55B5FB5F0397
 CONST Name 'aName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B5FB5F0397 aName

: ME_55B5FB4B0008
 CONST UID '55B5FB4B0008'
 CONST Name 'OpenRead'
 CONST Class class_Operation
 : Stereotype st_creator::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B5FB5F0397 // aName
 )
 ; // Parameters

ref; // ME_55B5FB4B0008 OpenRead

: ME_55B5FB8200DD
 CONST Name 'aName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B5FB8200DD aName

: ME_55B5FB780316
 CONST UID '55B5FB780316'
 CONST Name 'OpenWrite'
 CONST Class class_Operation
 : Stereotype st_creator::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B5FB8200DD // aName
 )
 ; // Parameters

ref; // ME_55B5FB780316 OpenWrite

: ME_55B5FB9E01EF
 CONST UID '55B5FB9E01EF'
 CONST Name 'EOF'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_55B5FB9E01EF EOF

: ME_55B5FBE20353
 CONST UID '55B5FBE20353'
 CONST Name 'ReadLn'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55B5FBE20353 ReadLn

: ME_55B5FC080154
 CONST Name 'aValue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55B5FC080154 aValue

: ME_55B5FBFE02E9
 CONST UID '55B5FBFE02E9'
 CONST Name 'WriteLn'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B5FC080154 // aValue
 )
 ; // Parameters

ref; // ME_55B5FBFE02E9 WriteLn

: ME_55B5FC220390
 CONST Name 'aValue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_482C48430205' '4AB0C3C60310.pas.ms.script' // Char
 ;

ref; // ME_55B5FC220390 aValue

: ME_55B5FC1C0184
 CONST UID '55B5FC1C0184'
 CONST Name 'WriteChar'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B5FC220390 // aValue
 )
 ; // Parameters

ref; // ME_55B5FC1C0184 WriteChar

: ME_55B5FC5A007D
 CONST Name 'aValue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_55B5FC5A007D aValue

: ME_55B5FC500169
 CONST UID '55B5FC500169'
 CONST Name 'WriteStr'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B5FC5A007D // aValue
 )
 ; // Parameters

ref; // ME_55B5FC500169 WriteStr

: ME_55B6044A038E
 CONST UID '55B6044A038E'
 CONST Name 'ReadLines'
 CONST Class class_Operation
 : Stereotype st_wordworker::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 CONST "SupressNextImmediate" 'None'

ref; // ME_55B6044A038E ReadLines

: ME_55B6048C02D6
 CONST Name 'aName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B6048C02D6 aName

: ME_55B6047F005B
 CONST UID '55B6047F005B'
 CONST Name 'DeleteFile'
 CONST Class class_Operation
 : Stereotype st_globalkeyword::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_55B6048C02D6 // aName
 )
 ; // Parameters

ref; // ME_55B6047F005B DeleteFile

: ME_55B604D30106
 CONST Name 'aNewName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B604D30106 aNewName

: ME_55B604D3017B
 CONST Name 'anOldName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B604D3017B anOldName

: ME_55B6049F0019
 CONST UID '55B6049F0019'
 CONST Name 'RenameFile'
 CONST Class class_Operation
 : Stereotype st_globalkeyword::Operation ;
 %SUMMARY 'RenameFile - переименовывает файл.'#13#10'*Формат:* aOldFileName aNewFileName RenameFile'#13#10'* aNewFileName - новое имя файла.'#13#10'* aOldFileName - старое имя файла.'#13#10'В стек помещается результат операции: true - если успешно, false - если переименование не получилось.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_55B604D30106 // aNewName
 ME_55B604D3017B // anOldName
 )
 ; // Parameters

ref; // ME_55B6049F0019 RenameFile

: ME_55B6055E02D4
 CONST Name 'aSourceDir'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B6055E02D4 aSourceDir

: ME_55B6055E034A
 CONST Name 'aDestDir'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B6055E034A aDestDir

: ME_55B6055E03AE
 CONST Name 'aFileMask'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B6055E03AE aFileMask

: ME_55B604FC0108
 CONST UID '55B604FC0108'
 CONST Name 'CopyFilesByMask'
 CONST Class class_Operation
 : Stereotype st_globalkeyword::Operation ;
 %SUMMARY 'CopyFilesByMask- копирует файлы по маске..'#13#10'*Формат:* '#13#10'{code}'#13#10' aFileMask aDestDir aSourceDir  CopyFilesByMask'#13#10'{code}'#13#10'* aSourceDir - директория откуда копируем.'#13#10'* aDestDir - директория куда копируем.'#13#10'* aFileMask - маска, по которой копируем файлы.'#13#10'Результат слово не возвращает. Если появляется ошибка, то будет Exception' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B6055E02D4 // aSourceDir
 ME_55B6055E034A // aDestDir
 ME_55B6055E03AE // aFileMask
 )
 ; // Parameters

ref; // ME_55B604FC0108 CopyFilesByMask

: ME_55B605E30082
 CONST Name 'aSourceFile'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B605E30082 aSourceFile

: ME_55B605E300DC
 CONST Name 'aDestFile'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B605E300DC aDestFile

: ME_55B605E30140
 CONST Name 'aCopyMode'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_55B605E30140 aCopyMode

: ME_55B605890120
 CONST UID '55B605890120'
 CONST Name 'CopyFile'
 CONST Class class_Operation
 : Stereotype st_globalkeyword::Operation ;
 %SUMMARY 'CopyFile - копирует файл.'#13#10'*Формат:*  aCopyMode aDestFile aSourceFile CopyFile'#13#10'* aSourceFile - имя исходного файла'#13#10'* aDestFile - имя файла, куда копируем'#13#10'* aCopyMode - режим копирования файла.'#13#10'Результат слово не возвращает. Если появляется ошибка, то будет Exception' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B605E30082 // aSourceFile
 ME_55B605E300DC // aDestFile
 ME_55B605E30140 // aCopyMode
 )
 ; // Parameters

ref; // ME_55B605890120 CopyFile

: ME_55B606CD001A
 CONST Name 'aName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B606CD001A aName

: ME_55B606A70227
 CONST UID '55B606A70227'
 CONST Name 'PureDir'
 CONST Class class_Operation
 : Stereotype st_globalkeyword::Operation ;
 %SUMMARY 'PureDir - очищает директорию.'#13#10'*Формат:* aDirName PureDir'#13#10'* aDirName  - имя директории.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B606CD001A // aName
 )
 ; // Parameters

ref; // ME_55B606A70227 PureDir

: ME_55B6071B0030
 CONST Name 'aDirName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B6071B0030 aDirName

: ME_55B6071B0092
 CONST Name 'aMask'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B6071B0092 aMask

: ME_55B606F1003D
 CONST UID '55B606F1003D'
 CONST Name 'DeleteFilesByMask'
 CONST Class class_Operation
 : Stereotype st_globalkeyword::Operation ;
 %SUMMARY 'DeleteFilesByMask - очищает директорию.'#13#10'*Формат:* aMask aDirName DeleteFilesByMask'#13#10'* aDirName  - имя директории.'#13#10'* aMask - маска, по которой отбираются файлы.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B6071B0030 // aDirName
 ME_55B6071B0092 // aMask
 )
 ; // Parameters

ref; // ME_55B606F1003D DeleteFilesByMask

: ME_55B607B003D6
 CONST Name 'aDirName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B607B003D6 aDirName

: ME_55B607B100A9
 CONST Name 'aFileMask'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B607B100A9 aFileMask

: ME_55B607B10103
 CONST Name 'aProc'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4DAEED140007' '4DAF19F600C5.pas.ms.script' // TtfwWord
 ;

ref; // ME_55B607B10103 aProc

: ME_55B6075302CC
 CONST UID '55B6075302CC'
 CONST Name 'ProcessFilesWithMask'
 CONST Class class_Operation
 : Stereotype st_globalkeyword::Operation ;
 %SUMMARY 'ProcessFilesWithMask - перебирает файлы по маске в заданной директории и вызывает для каждого найденного функцию.'#13#10'*Формат:*'#13#10'aProc aFileMask aDirName ProcessFilesWithMask'#13#10'* aProc - функция, которая вызывается для каждого файла. В стек при вызове помещается имя файла.'#13#10'* aFileMask - маска, по которой отбираются файлы, например ''*.script'''#13#10'* aDirName - путь, по которому ищутся файлы.'#13#10'*Пример:*'#13#10'{code}'#13#10': PrintFileName'#13#10' .'#13#10';'#13#10''#13#10'@ PrintFileName ''*.script'' ''w:\archi\source\projects\Archi\TestSet\Scripts\'' ProcessFilesWithMask'#13#10'{code}'#13#10'В результате будет создан файл с имя_скрипта.prn с именами файлов с полными путями.'#13#10'*Примечание:* Если ни один файл не найден, то функция не будет вызвана ни разу. Ни дирректории, ни ссылки на файлы, ни имена дисков в поиск не попадают. Поиск во вложенных директориях не прозводится. Имя файла передается с полным путем.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B607B003D6 // aDirName
 ME_55B607B100A9 // aFileMask
 ME_55B607B10103 // aProc
 )
 ; // Parameters

ref; // ME_55B6075302CC ProcessFilesWithMask

: ME_55B6080103A0
 CONST Name 'aDirName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55B6080103A0 aDirName

: ME_55B608020035
 CONST Name 'aProc'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4DAEED140007' '4DAF19F600C5.pas.ms.script' // TtfwWord
 ;

ref; // ME_55B608020035 aProc

: ME_55B607D400E0
 CONST UID '55B607D400E0'
 CONST Name 'ProcessSubDirs'
 CONST Class class_Operation
 : Stereotype st_globalkeyword::Operation ;
 %SUMMARY 'ProcessSubDirs - перебирает директории в заданной директории и вызывает для каждого найденного функцию.'#13#10'*Формат:*'#13#10'aProc aDirName ProcessSubDirs'#13#10'* aProc - функция, которая вызывается для каждой директории. В стек при вызове помещается имя директории.'#13#10'* aDirName - путь, по которому ищутся директории.'#13#10'*Пример:*'#13#10'{code}'#13#10': PrintFileName'#13#10' .'#13#10';'#13#10''#13#10'@ PrintFileName ''w:\archi\source\projects\Archi\TestSet\'' ProcessSubDirs'#13#10'{code}'#13#10'В результате будет создан файл с имя_скрипта.prn с именами директорий с полными путями.'#13#10'*Примечание:* Если ни одна директория  не найдена, то функция не будет вызвана ни разу.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B6080103A0 // aDirName
 ME_55B608020035 // aProc
 )
 ; // Parameters

ref; // ME_55B607D400E0 ProcessSubDirs

: ME_55B609A3029D
 CONST Name 'aValue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4DB00A510300' '55BF153300A4.pas.ms.script' // TtfwStackValue
 ;

ref; // ME_55B609A3029D aValue

: ME_55B60993020B
 CONST UID '55B60993020B'
 CONST Name 'WriteWStr'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B609A3029D // aValue
 )
 ; // Parameters

ref; // ME_55B60993020B WriteWStr

: ME_55B618940267
 CONST UID '55B618940267'
 CONST Name 'ReadWStrLn'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_47209E670266' '4678193C009C.pas.ms.script' // Tl3PCharLen
 ;

ref; // ME_55B618940267 ReadWStrLn

: ME_55B618BA0311
 CONST Name 'aValue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4DB00A510300' '55BF153300A4.pas.ms.script' // TtfwStackValue
 ;

ref; // ME_55B618BA0311 aValue

: ME_55B618AB03C3
 CONST UID '55B618AB03C3'
 CONST Name 'WriteWStrLn'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_55B618BA0311 // aValue
 )
 ; // Parameters

ref; // ME_55B618AB03C3 WriteWStrLn

: ME_56420DC20183
 CONST Name 'aFileName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_56420DC20183 aFileName

: ME_56420DAD0276
 CONST UID '56420DAD0276'
 CONST Name 'FileSize'
 CONST Class class_Operation
 : Stereotype st_globalkeyword::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Parameters
   Seq: ( ME_56420DC20183 // aFileName
 )
 ; // Parameters

ref; // ME_56420DAD0276 FileSize

: ME_56420E360080
 CONST Name 'aFile1'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_56420E360080 aFile1

: ME_56420E3600EE
 CONST Name 'aFile2'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_56420E3600EE aFile2

: ME_56420E36015C
 CONST Name 'aHeaderBegin'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_56420E36015C aHeaderBegin

: ME_56420DEC002D
 CONST UID '56420DEC002D'
 CONST Name 'CompareFiles'
 CONST Class class_Operation
 : Stereotype st_globalkeyword::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_56420E360080 // aFile1
 ME_56420E3600EE // aFile2
 ME_56420E36015C // aHeaderBegin
 )
 ; // Parameters

ref; // ME_56420DEC002D CompareFiles

: ME_570E700B014F
 CONST Name 'aName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_570E700B014F aName

: ME_570E700201A7
 CONST UID '570E700201A7'
 CONST Name 'OpenAppend'
 CONST Class class_Operation
 : Stereotype st_creator::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Parameters
   Seq: ( ME_570E700B014F // aName
 )
 ; // Parameters

ref; // ME_570E700201A7 OpenAppend

: ME_55B5FAD602C0
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target ME_4F4FD77B03CC // TtfwFile
 ;

ref; // ME_55B5FAD602C0 

: ME_55B5FAF602A4
 CONST Class class_Dependency
 : Stereotype st_injects::Dependency ;
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_4DAEED140007' '4DAF19F600C5.pas.ms.script' // TtfwWord
 ;

ref; // ME_55B5FAF602A4 

: ME_55B5FC6D01FE
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_47878E0E0191' '54B90AC6014B.pas.ms.script' // l3String
 ;

ref; // ME_55B5FC6D01FE 

: ME_55B5FCBC0256
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_509116F601C3' '4AB0C3C60310.pas.ms.script' // RenameFile
 ;

ref; // ME_55B5FCBC0256 

: ME_55B5FCCF00CF
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_53FDBED602A4' '47D0290B016D.pas.ms.script' // CopyFilesByMask
 ;

ref; // ME_55B5FCCF00CF 

: ME_55B5FCE103D3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_502550E80220' '4AB0C3C60310.pas.ms.script' // TSearchRec
 ;

ref; // ME_55B5FCE103D3 

: ME_55B5FCF601AE
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_4F191FDD0358' '47D0290B016D.pas.ms.script' // ConcatDirName
 ;

ref; // ME_55B5FCF601AE 

: ME_55B5FD0E0078
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_4F4E5D6C038D' '4DAF19F600C5.pas.ms.script' // C$File
 ;

ref; // ME_55B5FD0E0078 

: ME_5601702B012C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_5579351F0143' '47913B47006E.pas.ms.script' // Tl3ConstString
 ;

ref; // ME_5601702B012C 

: ME_56420DE10149
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4F4FD7EA00EB // FileProcessingPack
 ;
 : Target WL 'ME_47A080670100' '47913B47006E.pas.ms.script' // l3Stream
 ;

ref; // ME_56420DE10149 

: ME_4F4E4E7E0350_ME_4F4FD7EA00EB
 : Original WL 'ME_4F4E4E7E0350' '4DAF19F600C5.pas.ms.script' // ReadLn
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F4E4E7E0350_ME_4F4FD7EA00EB ReadLn

: ME_4F4E4EA7007D_ME_4F4FD7EA00EB
 : Original WL 'ME_4F4E4EA7007D' '4DAF19F600C5.pas.ms.script' // WriteLn
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F4E4EA7007D_ME_4F4FD7EA00EB WriteLn

: ME_4F4FDC540264_ME_4F4FD7EA00EB
 : Original WL 'ME_4F4FDC540264' '4DAF19F600C5.pas.ms.script' // WriteChar
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F4FDC540264_ME_4F4FD7EA00EB WriteChar

: ME_4F4FE16A0269_ME_4F4FD7EA00EB
 : Original WL 'ME_4F4FE16A0269' '4DAF19F600C5.pas.ms.script' // ReadWStrLn
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F4FE16A0269_ME_4F4FD7EA00EB ReadWStrLn

: ME_4F4FE19301A1_ME_4F4FD7EA00EB
 : Original WL 'ME_4F4FE19301A1' '4DAF19F600C5.pas.ms.script' // WriteWStrLn
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F4FE19301A1_ME_4F4FD7EA00EB WriteWStrLn

: ME_4F4FE1B40314_ME_4F4FD7EA00EB
 : Original WL 'ME_4F4FE1B40314' '4DAF19F600C5.pas.ms.script' // WriteWStr
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F4FE1B40314_ME_4F4FD7EA00EB WriteWStr

: ME_4F50821201E7_ME_4F4FD7EA00EB
 : Original WL 'ME_4F50821201E7' '4DAF19F600C5.pas.ms.script' // EOF
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F50821201E7_ME_4F4FD7EA00EB EOF

: ME_52E23B7A00EC_ME_4F4FD7EA00EB
 : Original WL 'ME_52E23B7A00EC' '4DAF19F600C5.pas.ms.script' // ForEach
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52E23B7A00EC_ME_4F4FD7EA00EB ForEach

: ME_52E23BB102FA_ME_4F4FD7EA00EB
 : Original WL 'ME_52E23BB102FA' '4DAF19F600C5.pas.ms.script' // ForEachBack
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52E23BB102FA_ME_4F4FD7EA00EB ForEachBack

: ME_4F4FD7EA00EB
 CONST UID '4F4FD7EA00EB'
 CONST Name 'FileProcessingPack'
 CONST Class class_Class
 : Stereotype st_ScriptKeywordsPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F4FD6CC0295 // FileProcessing
 ;
 : Implements
   Seq: ( WL 'ME_4F4E4E7101D6' '4DAF19F600C5.pas.ms.script' // ItfwFile
 )
 ; // Implements
 : Operations
   Seq: ( ME_55B5FB4B0008 // OpenRead
 ME_55B5FB780316 // OpenWrite
 ME_55B5FB9E01EF // EOF
 ME_55B5FBE20353 // ReadLn
 ME_55B5FBFE02E9 // WriteLn
 ME_55B5FC1C0184 // WriteChar
 ME_55B5FC500169 // WriteStr
 ME_55B6044A038E // ReadLines
 ME_55B6047F005B // DeleteFile
 ME_55B6049F0019 // RenameFile
 ME_55B604FC0108 // CopyFilesByMask
 ME_55B605890120 // CopyFile
 ME_55B606A70227 // PureDir
 ME_55B606F1003D // DeleteFilesByMask
 ME_55B6075302CC // ProcessFilesWithMask
 ME_55B607D400E0 // ProcessSubDirs
 ME_55B60993020B // WriteWStr
 ME_55B618940267 // ReadWStrLn
 ME_55B618AB03C3 // WriteWStrLn
 ME_56420DAD0276 // FileSize
 ME_56420DEC002D // CompareFiles
 ME_570E700201A7 // OpenAppend
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4F4E4E7E0350_ME_4F4FD7EA00EB // ReadLn
 ME_4F4E4EA7007D_ME_4F4FD7EA00EB // WriteLn
 ME_4F4FDC540264_ME_4F4FD7EA00EB // WriteChar
 ME_4F4FE16A0269_ME_4F4FD7EA00EB // ReadWStrLn
 ME_4F4FE19301A1_ME_4F4FD7EA00EB // WriteWStrLn
 ME_4F4FE1B40314_ME_4F4FD7EA00EB // WriteWStr
 ME_4F50821201E7_ME_4F4FD7EA00EB // EOF
 ME_52E23B7A00EC_ME_4F4FD7EA00EB // ForEach
 ME_52E23BB102FA_ME_4F4FD7EA00EB // ForEachBack
 )
 ; // Implemented
 : Children
   Seq: ( ME_4F4FD77B03CC // TtfwFile
 )
 ; // Children
 : Dependencies
   Seq: ( ME_55B5FAD602C0 // TtfwFile
 ME_55B5FAF602A4 // TtfwWord
 ME_55B5FC6D01FE // l3String
 ME_55B5FCBC0256 // RenameFile
 ME_55B5FCCF00CF // CopyFilesByMask
 ME_55B5FCE103D3 // TSearchRec
 ME_55B5FCF601AE // ConcatDirName
 ME_55B5FD0E0078 // C$File
 ME_5601702B012C // Tl3ConstString
 ME_56420DE10149 // l3Stream
 )
 ; // Dependencies
 CONST "ifndef" 'NoScripts'
 CONST "no_pop" true
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\FileProcessingPack.pas'

ref; // ME_4F4FD7EA00EB FileProcessingPack

: ME_4F4FD6CC0295
 CONST UID '4F4FD6CC0295'
 CONST Name 'FileProcessing'
 CONST Class class_Category
 : Stereotype st_ScriptKeywords ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_551175240043' '551175240043.pas.ms.script' // ScriptEngine$Axiomatics
 ;
 : Children
   Seq: ( ME_4F4FD7EA00EB // FileProcessingPack
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 WL 'ME_4677FBA70343' '4677FBA70343.pas.ms.script' // l3Interfaces
 WL 'ME_4678193C009C' '4678193C009C.pas.ms.script' // l3Types
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_47D0290B016D' '47D0290B016D.pas.ms.script' // l3Utils
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_4DAF19F600C5' '4DAF19F600C5.pas.ms.script' // tfwScriptingInterfaces
 WL 'ME_54B90AC6014B' '54B90AC6014B.pas.ms.script' // StringUtils
 WL 'ME_55BF153300A4' '55BF153300A4.pas.ms.script' // tfwTypeInfo
 )
 ; // Depends
 CONST "ifndef" 'NoScripts'

ref; // ME_4F4FD6CC0295 FileProcessing
