// Tl3CBTListenersList 4F66F88103D4 SimpleClass Class

INCLUDE '47B57D630029.pas.ms.script'

INCLUDE '4A54DD4E036F.pas.ms.script'

FORWARD ME_4F66F88103D4

INCLUDE '4677FBA70343.pas.ms.script'

: ME_4F66FA1C02E8
 CONST UID '4F66FA1C02E8'
 CONST Name 'ItemType'
 CONST Class 'Attribute'
 CONST Stereotype 'impurity value'
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'abstract'
 CONST LinkType 'ref'
 : Target ME_46A5BB250099 // Il3CBTListener
 ;

 @SELF
; // ME_4F66FA1C02E8 ItemType

: ME_4F66F88103D4
 CONST UID '4F66F88103D4'
 CONST Name 'Tl3CBTListenersList'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_47B57D630029 // l3InterfacePtrList
 ME_4A54DD4E036F // Tl3ProtoDataContainer
 ]
 ; // Inherits
 : Attributes
   [ ME_4F66FA1C02E8 // ItemType
 ]
 ; // Attributes
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_4F66F88103D4 Tl3CBTListenersList
