// FormDefinitions 4F6B66F8001B VCMControls Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4F6B66F8001B

FORWARD ME_4F6B670E017C

FORWARD ME_9070E6134DC0

: ME_0DA3262A4388
 CONST UID '0DA3262A4388'
 CONST Name 'fm_ChildForm'
 CONST IsSummoned true
 CONST Class class_Attribute
 %SUMMARY 'Идентификатор формы TChildForm' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_9070E6134DC0 // ChildIDs
 ;
 : Target WL 'ME_4FFC30A800DF' '4683F37902CF.pas.ms.script' // TvcmFormDescriptor
 ;
 CONST Value '(rFormID : (rName : ''ChildForm''; rID : 0); rFactory : nil)'
 : ValueType WL 'ME_4FFC30A800DF' '4683F37902CF.pas.ms.script' // TvcmFormDescriptor
 ;
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '(rFormID : (rName : ''ChildForm''; rID : 0); rFactory : nil)'

ref; // ME_0DA3262A4388 fm_ChildForm

: ME_9070E6134DC0
 CONST UID '9070E6134DC0'
 CONST Name 'ChildIDs'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4F6B670E017C // Child
 ;
 : Attributes
   Seq: ( ME_0DA3262A4388 // fm_ChildForm
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_9070E6134DC0 ChildIDs

: ME_4F6B670E017C
 CONST UID '4F6B670E017C'
 CONST GUID 'CFF21CFB-D277-44C2-940B-C1A99F33511F'
 CONST Name 'Child'
 CONST Class class_Class
 : Stereotype st_VCMFormDefinition ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4F6B66F8001B // FormDefinitions
 ;
 : Constants
   Seq: ( ME_9070E6134DC0 // ChildIDs
 )
 ; // Constants
 CONST extprop:pas:TypeName 'ChildFormDef'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F6B670E017C Child

FORWARD ME_4F6B6714032D

FORWARD ME_ABFE473370F1

: ME_E90A73C09CA4
 CONST UID 'E90A73C09CA4'
 CONST Name 'fm_ParentForm'
 CONST IsSummoned true
 CONST Class class_Attribute
 %SUMMARY 'Идентификатор формы TParentForm' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_ABFE473370F1 // ParentIDs
 ;
 : Target WL 'ME_4FFC30A800DF' '4683F37902CF.pas.ms.script' // TvcmFormDescriptor
 ;
 CONST Value '(rFormID : (rName : ''ParentForm''; rID : 0); rFactory : nil)'
 : ValueType WL 'ME_4FFC30A800DF' '4683F37902CF.pas.ms.script' // TvcmFormDescriptor
 ;
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '(rFormID : (rName : ''ParentForm''; rID : 0); rFactory : nil)'

ref; // ME_E90A73C09CA4 fm_ParentForm

: ME_ABFE473370F1
 CONST UID 'ABFE473370F1'
 CONST Name 'ParentIDs'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4F6B6714032D // Parent
 ;
 : Attributes
   Seq: ( ME_E90A73C09CA4 // fm_ParentForm
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_ABFE473370F1 ParentIDs

: ME_4F6B6714032D
 CONST UID '4F6B6714032D'
 CONST GUID 'DEC20464-3FB2-4ABC-921C-08A93E75DAD5'
 CONST Name 'Parent'
 CONST Class class_Class
 : Stereotype st_VCMFormDefinition ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4F6B66F8001B // FormDefinitions
 ;
 : Constants
   Seq: ( ME_ABFE473370F1 // ParentIDs
 )
 ; // Constants
 CONST extprop:pas:TypeName 'ParentFormDef'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_4F6B6714032D Parent

FORWARD ME_BBEB9821B6DA

: ME_584E5BC3E8D4
 CONST UID '584E5BC3E8D4'
 CONST Name 'Ini_Reg'
 CONST IsSummoned true
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация Tkw_Form_Child_ID' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_BBEB9821B6DA // Tkw_Form_Child_ID
 ;

ref; // ME_584E5BC3E8D4 Ini_Reg

: ME_4DB0614603C8_ME_BBEB9821B6DA
 : Original WL 'ME_4DB0614603C8' '4F3E3F5F0160.pas.ms.script' // GetWordNameForRegister
 ;
 : Implementor ME_BBEB9821B6DA // Tkw_Form_Child_ID
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DB0614603C8_ME_BBEB9821B6DA GetWordNameForRegister

: ME_4DDFD2EA0116_ME_BBEB9821B6DA
 : Original WL 'ME_4DDFD2EA0116' '4F3E3F5F0160.pas.ms.script' // GetString
 ;
 : Implementor ME_BBEB9821B6DA // Tkw_Form_Child_ID
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DDFD2EA0116_ME_BBEB9821B6DA GetString

: ME_BBEB9821B6DA
 CONST UID 'BBEB9821B6DA'
 CONST Name 'Tkw_Form_Child_ID'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово словаря для идентификатора формы Child'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'''aControl'' форма::Child TryFocus ASSERT'#13#10'{code}' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F6B66F8001B // FormDefinitions
 ;
 : Inherits
   Seq: ( WL 'ME_4DDFD1430390' '4F3E3F5F0160.pas.ms.script' // TtfwString
 )
 ; // Inherits
 : Operations
   Seq: ( ME_584E5BC3E8D4 // Ini_Reg
 )
 ; // Operations
 : Overridden
   Seq: ( ME_4DB0614603C8_ME_BBEB9821B6DA // GetWordNameForRegister
 ME_4DDFD2EA0116_ME_BBEB9821B6DA // GetString
 )
 ; // Overridden
 CONST "NameForScript" 'форма::Child'
 CONST "ifndef" 'NoScripts'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST extprop:rc:SelfName '_Form_Child_ID'
 CONST extprop:rc:isAcceptableForScripts true
 : SpelledFor WL 'ME_4F6B66DB0384' '4F6B66140294.pas.ms.script' // Child
 ;

ref; // ME_BBEB9821B6DA Tkw_Form_Child_ID

FORWARD ME_4D2D1B64FF3F

: ME_6BF361D23EF3
 CONST UID '6BF361D23EF3'
 CONST Name 'Ini_Reg'
 CONST IsSummoned true
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация Tkw_Form_Parent_ID' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4D2D1B64FF3F // Tkw_Form_Parent_ID
 ;

ref; // ME_6BF361D23EF3 Ini_Reg

: ME_4DB0614603C8_ME_4D2D1B64FF3F
 : Original WL 'ME_4DB0614603C8' '4F3E3F5F0160.pas.ms.script' // GetWordNameForRegister
 ;
 : Implementor ME_4D2D1B64FF3F // Tkw_Form_Parent_ID
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DB0614603C8_ME_4D2D1B64FF3F GetWordNameForRegister

: ME_4DDFD2EA0116_ME_4D2D1B64FF3F
 : Original WL 'ME_4DDFD2EA0116' '4F3E3F5F0160.pas.ms.script' // GetString
 ;
 : Implementor ME_4D2D1B64FF3F // Tkw_Form_Parent_ID
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4DDFD2EA0116_ME_4D2D1B64FF3F GetString

: ME_4D2D1B64FF3F
 CONST UID '4D2D1B64FF3F'
 CONST Name 'Tkw_Form_Parent_ID'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово словаря для идентификатора формы Parent'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'''aControl'' форма::Parent TryFocus ASSERT'#13#10'{code}' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F6B66F8001B // FormDefinitions
 ;
 : Inherits
   Seq: ( WL 'ME_4DDFD1430390' '4F3E3F5F0160.pas.ms.script' // TtfwString
 )
 ; // Inherits
 : Operations
   Seq: ( ME_6BF361D23EF3 // Ini_Reg
 )
 ; // Operations
 : Overridden
   Seq: ( ME_4DB0614603C8_ME_4D2D1B64FF3F // GetWordNameForRegister
 ME_4DDFD2EA0116_ME_4D2D1B64FF3F // GetString
 )
 ; // Overridden
 CONST "NameForScript" 'форма::Parent'
 CONST "ifndef" 'NoScripts'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST extprop:rc:SelfName '_Form_Parent_ID'
 CONST extprop:rc:isAcceptableForScripts true
 : SpelledFor WL 'ME_4F6B66CB0200' '4F6B66140294.pas.ms.script' // Parent
 ;

ref; // ME_4D2D1B64FF3F Tkw_Form_Parent_ID

: ME_4F6B66F8001B
 CONST UID '4F6B66F8001B'
 CONST Name 'FormDefinitions'
 CONST Class class_Category
 : Stereotype st_VCMControls ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4F6B660100D5' '4F6B660100D5.pas.ms.script' // View
 ;
 : Children
   Seq: ( ME_4F6B670E017C // Child
 ME_4F6B6714032D // Parent
 ME_BBEB9821B6DA // Tkw_Form_Child_ID
 ME_4D2D1B64FF3F // Tkw_Form_Parent_ID
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4683F37902CF' '4683F37902CF.pas.ms.script' // vcmInterfaces
 WL 'ME_4F3E3F5F0160' '4F3E3F5F0160.pas.ms.script' // PrimitiveWords
 )
 ; // Depends
 CONST "is namespace" true
 CONST "no hands" false
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\View\F1Like_FormDefinitions_Controls.pas'
 CONST extprop:pas:UnitName 'F1Like_FormDefinitions_Controls'

ref; // ME_4F6B66F8001B FormDefinitions
