// VCMAppTester 4F79CD9F015F Impurity Class

INCLUDE '52F21A610247.pas.ms.script'

: ME_4F79CD9F015F
 CONST UID '4F79CD9F015F'
 CONST Name 'VCMAppTester'
 CONST Class 'Class'
 CONST Stereotype 'Impurity'
 %SUMMARY 'Примесь для тестирования приложений, построенных на VCM' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'abstract'
 : Inherits
   [ ME_52F21A610247 // GUIAppTester
 ]
 ; // Inherits
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_4F79CD9F015F VCMAppTester
