// MonitoringsMain 4F7C2E78015C VCMMainForm Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4F7C2E78015C

: ME_C02C69F1F8D8
 CONST UID 'C02C69F1F8D8'
 CONST GUID '302D255D-E242-47AD-ACB5-B3822A5E3F7F'
 CONST Name 'MonitoringsMain'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_VCMFormDefinition ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Идентификатор формы MonitoringsMain' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4F7C2E78015C // MonitoringsMain
 ;
 : Implementors
   Seq: ( HWL ME_4F7C2E78015C // MonitoringsMain
 )
 ; // Implementors
 CONST extprop:pas:TypeName 'MonitoringsMainFormDef'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_C02C69F1F8D8 MonitoringsMain$Def

: ME_2E9AEBC2076A
 CONST UID '2E9AEBC2076A'
 CONST Name 'Ini_FormFactory_MonitoringsMain'
 CONST IsSummoned true
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация фабрики формы MonitoringsMain' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4F7C2E78015C // MonitoringsMain
 ;
 : SpelledFor HWL ME_4F7C2E78015C // MonitoringsMain
 ;

ref; // ME_2E9AEBC2076A Ini_FormFactory_MonitoringsMain$Def

: ME_4F7C2E78015C
 CONST UID '4F7C2E78015C'
 CONST Name 'MonitoringsMain'
 CONST Class class_Class
 : Stereotype st_VCMMainForm ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent WL 'ME_4AA9038C0387' '4AA9038C0387.pas.ms.script' // Monitorings
 ;
 : Inherits
   Seq: ( WL 'ME_4AA919040176' '4AA919040176.pas.ms.script' // PrimMonitoringsMain
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_C02C69F1F8D8 // MonitoringsMain$Def
 )
 ; // Implements
 : Operations
   Seq: ( HWL ME_2E9AEBC2076A // Ini_FormFactory_MonitoringsMain$Def
 )
 ; // Operations
 : Children
   Seq: ( HWL ME_C02C69F1F8D8 // MonitoringsMain$Def
 )
 ; // Children
 CONST "NeedsHackRef" true
 CONST "ZoneType" 'Any'
 CONST "finished dfm" true
 CONST "resizeable" false
 CONST "restrict form def" 'undefined'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\MonitoringsMain_Form.pas'
 CONST extprop:pas:TypeName 'TMonitoringsMainForm'
 CONST extprop:rc:SelfName 'MonitoringsMainForm'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'MonitoringsMain_Form'

ref; // ME_4F7C2E78015C MonitoringsMain
