// Flashing 4F7DD05B035B Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4F7DD05B035B

: ME_4F7DD06802A0
 CONST UID '4F7DD06802A0'
 CONST Name 'nsFlashWindow'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4F7DD05B035B // Flashing
 ;
 CONST "finished" false
 CONST "no hands" false
 CONST dfm:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\NOT_FINISHED_nsFlashWindow.pas'
 CONST intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'
 CONST extprop:rc:SelfName 'FlashWindow'

ref; // ME_4F7DD06802A0 nsFlashWindow

: ME_4F7DD05B035B
 CONST UID '4F7DD05B035B'
 CONST Name 'Flashing'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4986ECDF01F4' '4986ECDF01F4.pas.ms.script' // View
 ;
 : Children
   Seq: ( ME_4F7DD06802A0 // nsFlashWindow
 )
 ; // Children
 CONST dfm:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'
 CONST intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\4F7DD05B035B.pas.ms.script'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\4F7DD05B035B.pas.ms.script.runner'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_4F7DD05B035B Flashing
