// Mouse_RightDown 4F967CAE02C4 ScriptKeyword Class

INCLUDE '4F967BAD0127.pas.ms.script'

INCLUDE '54D229E702B6.pas.ms.script'

FORWARD ME_4F967CAE02C4

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_43E72A4AD379
 CONST UID '43E72A4AD379'
 CONST Name 'Ini_Reg'
 CONST Class 'Operation'
 CONST Stereotype 'ini'
 %SUMMARY 'Регистрация Mouse_RightDown' ;
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_43E72A4AD379 Ini_Reg

: ME_4F967CAE02C4
 CONST UID '4F967CAE02C4'
 CONST Name 'Mouse_RightDown'
 CONST Class 'Class'
 CONST Stereotype 'ScriptKeyword'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Inherits
   [ ME_4F967BAD0127 // TkwMouseUpDownSupport
 ]
 ; // Inherits
 : Operations
   [ ME_43E72A4AD379 // Ini_Reg
 ]
 ; // Operations
 : Implemented
   [ ME_4F967BED0186 // GetMouseEventFlag
 ]
 ; // Implemented
 : Overridden
   [ ME_4DB0614603C8 // GetWordNameForRegister
 ]
 ; // Overridden
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_4F967CAE02C4 Mouse_RightDown
