// StatusBarWords 505C848E02D6 ScriptKeywords Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_505C848E02D6

FORWARD ME_505C855C024A

FORWARD ME_552FC8E1023A

FORWARD ME_6A3FD2C52DF9

: ME_4DAEEDE10285_ME_6A3FD2C52DF9
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_6A3FD2C52DF9 DoDoIt

: ME_6A3FD2C52DF9
 CONST UID '6A3FD2C52DF9'
 CONST Name 'StatusBar_OrderedControl'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта StatusBar:OrderedControl' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_505C855C024A // StatusBarWords
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_6A3FD2C52DF9 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'StatusBar:OrderedControl'
 CONST extprop:pas:TypeName 'TkwStatusBarOrderedControl'
 CONST extprop:rc:SelfName 'StatusBarOrderedControl'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_4E15A08E030D' '49871D5103B9.pas.ms.script' // TnscStatusBar
 ;
 : SpelledFor ME_552FC8E1023A // OrderedControl
 ;

ref; // ME_6A3FD2C52DF9 StatusBar_OrderedControl

FORWARD ME_552FC91301BD

FORWARD ME_C8B065596342

: ME_4DAEEDE10285_ME_C8B065596342
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_C8B065596342 DoDoIt

: ME_C8B065596342
 CONST UID 'C8B065596342'
 CONST Name 'StatusBar_OrderedControlsCount'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта StatusBar:OrderedControlsCount' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_505C855C024A // StatusBarWords
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_C8B065596342 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'StatusBar:OrderedControlsCount'
 CONST extprop:pas:TypeName 'TkwStatusBarOrderedControlsCount'
 CONST extprop:rc:SelfName 'StatusBarOrderedControlsCount'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_4E15A08E030D' '49871D5103B9.pas.ms.script' // TnscStatusBar
 ;
 : SpelledFor ME_552FC91301BD // OrderedControlsCount
 ;

ref; // ME_C8B065596342 StatusBar_OrderedControlsCount

FORWARD ME_552FC94F0188

FORWARD ME_F7D061E9FD6E

: ME_4DAEEDE10285_ME_F7D061E9FD6E
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_F7D061E9FD6E DoDoIt

: ME_F7D061E9FD6E
 CONST UID 'F7D061E9FD6E'
 CONST Name 'StatusBar_OrderIndex'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта StatusBar:OrderIndex' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_505C855C024A // StatusBarWords
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_F7D061E9FD6E // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'StatusBar:OrderIndex'
 CONST extprop:pas:TypeName 'TkwStatusBarOrderIndex'
 CONST extprop:rc:SelfName 'StatusBarOrderIndex'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_4E15A08E030D' '49871D5103B9.pas.ms.script' // TnscStatusBar
 ;
 : SpelledFor ME_552FC94F0188 // OrderIndex
 ;

ref; // ME_F7D061E9FD6E StatusBar_OrderIndex

: ME_552FC9080065
 CONST Name 'anIndex'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_552FC9080065 anIndex

: ME_552FC8E1023A
 CONST UID '552FC8E1023A'
 CONST Name 'OrderedControl'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_505C855C024A // StatusBarWords
 ;
 : Target WL 'ME_47E1201703C3' '4799D29F033F.pas.ms.script' // TControl
 ;
 : Parameters
   Seq: ( ME_552FC9080065 // anIndex
 )
 ; // Parameters
 : Speller ME_6A3FD2C52DF9 // StatusBar_OrderedControl
 ;

ref; // ME_552FC8E1023A OrderedControl

: ME_552FC91301BD
 CONST UID '552FC91301BD'
 CONST Name 'OrderedControlsCount'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_505C855C024A // StatusBarWords
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Speller ME_C8B065596342 // StatusBar_OrderedControlsCount
 ;

ref; // ME_552FC91301BD OrderedControlsCount

: ME_552FC96B007C
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47E1201703C3' '4799D29F033F.pas.ms.script' // TControl
 ;

ref; // ME_552FC96B007C aControl

: ME_552FC94F0188
 CONST UID '552FC94F0188'
 CONST Name 'OrderIndex'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_505C855C024A // StatusBarWords
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Parameters
   Seq: ( ME_552FC96B007C // aControl
 )
 ; // Parameters
 : Speller ME_F7D061E9FD6E // StatusBar_OrderIndex
 ;

ref; // ME_552FC94F0188 OrderIndex

: ME_FD5784AF680E
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_injects::Dependency ;
 : Parent ME_505C855C024A // StatusBarWords
 ;
 : Target WL 'ME_4E15A08E030D' '49871D5103B9.pas.ms.script' // TnscStatusBar
 ;

ref; // ME_FD5784AF680E 

: ME_505C855C024A
 CONST UID '505C855C024A'
 CONST Name 'StatusBarWords'
 CONST Class class_Class
 : Stereotype st_ScriptKeywordsPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_505C848E02D6 // StatusBarWords
 ;
 : Inherits
   Seq: ( WL 'ME_4E15A08E030D' '49871D5103B9.pas.ms.script' // TnscStatusBar
 )
 ; // Inherits
 : Operations
   Seq: ( ME_552FC8E1023A // OrderedControl
 ME_552FC91301BD // OrderedControlsCount
 ME_552FC94F0188 // OrderIndex
 )
 ; // Operations
 : Children
   Seq: ( ME_6A3FD2C52DF9 // StatusBar_OrderedControl
 ME_C8B065596342 // StatusBar_OrderedControlsCount
 ME_F7D061E9FD6E // StatusBar_OrderIndex
 )
 ; // Children
 : Dependencies
   Seq: ( ME_FD5784AF680E // TnscStatusBar
 )
 ; // Dependencies
 CONST "ifndef" 'NoScripts'
 CONST "no class name" false
 CONST "no_pop" true
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\StatusBarWords.pas'

ref; // ME_505C855C024A StatusBarWords

FORWARD ME_54DB6FD1016A

FORWARD ME_552FC9C10154

FORWARD ME_33C559B72437

: ME_4DAEEDE10285_ME_33C559B72437
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_33C559B72437 DoDoIt

: ME_33C559B72437
 CONST UID '33C559B72437'
 CONST Name 'pop_StatusBarButton_IsDown'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_ScriptKeyword ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово скрипта pop:StatusBarButton:IsDown' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_54DB6FD1016A // StatusBarButtonWords
 ;
 : Inherits
   Seq: ( WL 'ME_55CCAE000335' '55CCADD2013D.pas.ms.script' // TtfwClassLike
 )
 ; // Inherits
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_33C559B72437 // DoDoIt
 )
 ; // Implemented
 CONST "NameForScript" 'pop:StatusBarButton:IsDown'
 CONST extprop:pas:TypeName 'TkwPopStatusBarButtonIsDown'
 CONST extprop:rc:SelfName 'PopStatusBarButtonIsDown'
 CONST extprop:rc:isAcceptableForScripts true
 : Speller WL 'ME_503DE6F30027' '49871D5103B9.pas.ms.script' // TnscStatusBarButton
 ;
 : SpelledFor ME_552FC9C10154 // IsDown
 ;

ref; // ME_33C559B72437 pop_StatusBarButton_IsDown

: ME_552FC9C10154
 CONST UID '552FC9C10154'
 CONST Name 'IsDown'
 CONST Class class_Operation
 : Stereotype st_keyword::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_54DB6FD1016A // StatusBarButtonWords
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Speller ME_33C559B72437 // pop_StatusBarButton_IsDown
 ;

ref; // ME_552FC9C10154 IsDown

: ME_95F5D3CF34CC
 CONST IsSummoned true
 CONST Class class_Dependency
 : Stereotype st_injects::Dependency ;
 : Parent ME_54DB6FD1016A // StatusBarButtonWords
 ;
 : Target WL 'ME_503DE6F30027' '49871D5103B9.pas.ms.script' // TnscStatusBarButton
 ;

ref; // ME_95F5D3CF34CC 

: ME_54DB6FD1016A
 CONST UID '54DB6FD1016A'
 CONST Name 'StatusBarButtonWords'
 CONST Class class_Class
 : Stereotype st_ScriptKeywordsPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_505C848E02D6 // StatusBarWords
 ;
 : Inherits
   Seq: ( WL 'ME_503DE6F30027' '49871D5103B9.pas.ms.script' // TnscStatusBarButton
 )
 ; // Inherits
 : Operations
   Seq: ( ME_552FC9C10154 // IsDown
 )
 ; // Operations
 : Children
   Seq: ( ME_33C559B72437 // pop_StatusBarButton_IsDown
 )
 ; // Children
 : Dependencies
   Seq: ( ME_95F5D3CF34CC // TnscStatusBarButton
 )
 ; // Dependencies
 CONST "ifndef" 'NoScripts'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\StatusBarButtonWords.pas'

ref; // ME_54DB6FD1016A StatusBarButtonWords

: ME_505C848E02D6
 CONST UID '505C848E02D6'
 CONST Name 'StatusBarWords'
 CONST Class class_Category
 : Stereotype st_ScriptKeywords ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_54DB83140023' '54DB83140023.pas.ms.script' // ScriptEngine$F1
 ;
 : Children
   Seq: ( ME_505C855C024A // StatusBarWords
 ME_54DB6FD1016A // StatusBarButtonWords
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4799D29F033F' '4799D29F033F.pas.ms.script' // Implementation
 WL 'ME_49871D5103B9' '49871D5103B9.pas.ms.script' // StatusBar
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_4DAF19F600C5' '4DAF19F600C5.pas.ms.script' // tfwScriptingInterfaces
 WL 'ME_4F69DF560034' '4F69DF560034.pas.ms.script' // ControlsProcessing
 WL 'ME_55CCADD2013D' '55CCADD2013D.pas.ms.script' // ClassLikeMapping
 )
 ; // Depends
 CONST "ifdef" 'Nemesis'
 CONST "ifndef" 'NoScripts'

ref; // ME_505C848E02D6 StatusBarWords
