// StatusBarUtils 505DA8FC03CF Views Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_505DA8FC03CF

FORWARD ME_505DA5E7038D

FORWARD ME_50477AAF037C

: ME_50477AC90015
 CONST UID '50477AC90015'
 CONST Name 'cStatusbarItemSize'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_50477AAF037C // StatusBarConsts
 ;
 CONST Value 20
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 20

ref; // ME_50477AC90015 cStatusbarItemSize

: ME_50477AAF037C
 CONST UID '50477AAF037C'
 CONST Name 'StatusBarConsts'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_505DA5E7038D // nscStatusBarItemNotification
 ;
 : Attributes
   Seq: ( ME_50477AC90015 // cStatusbarItemSize
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_50477AAF037C StatusBarConsts

FORWARD ME_505DA91D017B

FORWARD ME_505DA97101BB

FORWARD ME_505DA9AF003E

FORWARD ME_505DA9D50000

FORWARD ME_505DCA6603AA

FORWARD ME_505DD53B0349

FORWARD ME_505DDE8F02A1

FORWARD ME_50603D930238

FORWARD ME_505DA61E00A6

: ME_505DA749005F
 CONST UID '505DA749005F'
 CONST Name 'f_NotificationClients'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_505DA5E7038D // nscStatusBarItemNotification
 ;
 : Target ME_505DA61E00A6 // TnscStatusBarItemsList
 ;

ref; // ME_505DA749005F f_NotificationClients

: ME_506037F90133
 CONST UID '506037F90133'
 CONST Name 'ItemDef'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_505DA5E7038D // nscStatusBarItemNotification
 ;
 : Target WL 'ME_4980350B00FA' '490838E10313.pas.ms.script' // InscStatusBarItemDef
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_506037F90133 ItemDef

: ME_5060229A032B
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_476F78A602B2' '476F78840219.pas.ms.script' // TMessage
 ;

ref; // ME_5060229A032B aMessage

: ME_506022500317
 CONST UID '506022500317'
 CONST Name 'CMVisibleChanged'
 CONST Class class_Operation
 : Stereotype st_message::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_505DA5E7038D // nscStatusBarItemNotification
 ;
 : Parameters
   Seq: ( ME_5060229A032B // aMessage
 )
 ; // Parameters
 CONST "Message ID" 'CM_VISIBLECHANGED'

ref; // ME_506022500317 CMVisibleChanged

FORWARD ME_505DCE690055

: ME_505DCE9103B8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_505DA5E7038D // nscStatusBarItemNotification
 ;
 : Target ME_505DCE690055 // StatusBarUtils
 ;

ref; // ME_505DCE9103B8 

: ME_50601EA802C7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_505DA5E7038D // nscStatusBarItemNotification
 ;
 : Target WL 'ME_4DFF098B00CC' '47913B47006E.pas.ms.script' // l3Free
 ;

ref; // ME_50601EA802C7 

: ME_50601EAB020A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_505DA5E7038D // nscStatusBarItemNotification
 ;
 : Target WL 'ME_47979588035F' '4799D29F033F.pas.ms.script' // CM_Messages
 ;

ref; // ME_50601EAB020A 

: ME_50601EAD02A5
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_505DA5E7038D // nscStatusBarItemNotification
 ;
 : Target WL 'ME_476F78A602B2' '476F78840219.pas.ms.script' // TMessage
 ;

ref; // ME_50601EAD02A5 

: ME_505DA97101BB_ME_505DA5E7038D
 : Original ME_505DA97101BB // Subscribe
 ;
 CONST OpKind opkind_Implemented
ref; // ME_505DA97101BB_ME_505DA5E7038D Subscribe

: ME_505DA9AF003E_ME_505DA5E7038D
 : Original ME_505DA9AF003E // Unsubscribe
 ;
 CONST OpKind opkind_Implemented
ref; // ME_505DA9AF003E_ME_505DA5E7038D Unsubscribe

: ME_505DA9D50000_ME_505DA5E7038D
 : Original ME_505DA9D50000 // SendNotificationToClients
 ;
 CONST OpKind opkind_Implemented
ref; // ME_505DA9D50000_ME_505DA5E7038D SendNotificationToClients

: ME_505DCA6603AA_ME_505DA5E7038D
 : Original ME_505DCA6603AA // Notify
 ;
 CONST OpKind opkind_Implemented
ref; // ME_505DCA6603AA_ME_505DA5E7038D Notify

: ME_505DD53B0349_ME_505DA5E7038D
 : Original ME_505DD53B0349 // Visible
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_505DD53B0349_ME_505DA5E7038D Visible

: ME_505DDE8F02A1_ME_505DA5E7038D
 : Original ME_505DDE8F02A1 // NotificationClients
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_505DDE8F02A1_ME_505DA5E7038D NotificationClients

: ME_50603D930238_ME_505DA5E7038D
 : Original ME_50603D930238 // ItemDef
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_50603D930238_ME_505DA5E7038D ItemDef

: ME_479731C50290_ME_505DA5E7038D
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_505DA5E7038D Cleanup

: ME_505DA5E7038D
 CONST UID '505DA5E7038D'
 CONST Name 'nscStatusBarItemNotification'
 CONST Class class_Class
 : Stereotype st_GUIControlMixIn ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_505DA8FC03CF // StatusBarUtils
 ;
 : Implements
   Seq: ( WL 'ME_4A5CB93700CF' '47913B47006E.pas.ms.script' // Ml3Unknown
 ME_505DA91D017B // InscStatusBarItem
 )
 ; // Implements
 : Attributes
   Seq: ( ME_505DA749005F // f_NotificationClients
 ME_506037F90133 // ItemDef
 )
 ; // Attributes
 : Operations
   Seq: ( ME_506022500317 // CMVisibleChanged
 )
 ; // Operations
 : Implemented
   Seq: ( ME_505DA97101BB_ME_505DA5E7038D // Subscribe
 ME_505DA9AF003E_ME_505DA5E7038D // Unsubscribe
 ME_505DA9D50000_ME_505DA5E7038D // SendNotificationToClients
 ME_505DCA6603AA_ME_505DA5E7038D // Notify
 ME_505DD53B0349_ME_505DA5E7038D // Visible
 ME_505DDE8F02A1_ME_505DA5E7038D // NotificationClients
 ME_50603D930238_ME_505DA5E7038D // ItemDef
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_505DA5E7038D // Cleanup
 )
 ; // Overridden
 : Constants
   Seq: ( ME_50477AAF037C // StatusBarConsts
 )
 ; // Constants
 : Dependencies
   Seq: ( ME_505DCE9103B8 // StatusBarUtils
 ME_50601EA802C7 // l3Free
 ME_50601EAB020A // CM_Messages
 ME_50601EAD02A5 // TMessage
 )
 ; // Dependencies
 CONST "need UC" true
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\gui\Garant\Nemesis\nscStatusBarItemNotification.imp.pas'
 CONST extprop:pas:TypeName '_nscStatusBarItemNotification_'
 CONST extprop:pas:UnitName 'nscStatusBarItemNotification.imp'

ref; // ME_505DA5E7038D nscStatusBarItemNotification

FORWARD ME_505DA86200EB

: ME_505DA8730156
 CONST UID '505DA8730156'
 CONST Name 'sbintVisibleChanged'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_505DA86200EB // TnscStatusBarItemNotificationType
 ;

ref; // ME_505DA8730156 sbintVisibleChanged

: ME_505DA86200EB
 CONST UID '505DA86200EB'
 CONST Name 'TnscStatusBarItemNotificationType'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_505DA91D017B // InscStatusBarItem
 ;
 : Attributes
   Seq: ( ME_505DA8730156 // sbintVisibleChanged
 )
 ; // Attributes
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_505DA86200EB TnscStatusBarItemNotificationType

: ME_505DD53B0349
 CONST UID '505DD53B0349'
 CONST Name 'Visible'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_505DA91D017B // InscStatusBarItem
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" false

ref; // ME_505DD53B0349 Visible

: ME_505DDE8F02A1
 CONST UID '505DDE8F02A1'
 CONST Name 'NotificationClients'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'TnscStatusBarItemsList' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_505DA91D017B // InscStatusBarItem
 ;
 : Target WL 'ME_46A608F00301' '4AB0C3C60310.pas.ms.script' // Pointer
 ;
 CONST "pm" false

ref; // ME_505DDE8F02A1 NotificationClients

: ME_50603D930238
 CONST UID '50603D930238'
 CONST Name 'ItemDef'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_505DA91D017B // InscStatusBarItem
 ;
 : Target WL 'ME_4980350B00FA' '490838E10313.pas.ms.script' // InscStatusBarItemDef
 ;
 CONST "pm" false

ref; // ME_50603D930238 ItemDef

: ME_505DA9C70358
 CONST Name 'aClient'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_505DA91D017B // InscStatusBarItem
 ;

ref; // ME_505DA9C70358 aClient

: ME_505DA9C401C8
 CONST UID '505DA9C401C8'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_505DA9AF003E // Unsubscribe
 ;
 : Parameters
   Seq: ( ME_505DA9C70358 // aClient
 )
 ; // Parameters

ref; // ME_505DA9C401C8 DoIt

: ME_505DA9AF003E
 CONST UID '505DA9AF003E'
 CONST Name 'Unsubscribe'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_505DA91D017B // InscStatusBarItem
 ;
 : Operations
   Seq: ( ME_505DA9C401C8 // DoIt
 )
 ; // Operations

ref; // ME_505DA9AF003E Unsubscribe

: ME_505DD947016D
 CONST Name 'aNotificationType'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_505DA86200EB // TnscStatusBarItemNotificationType
 ;

ref; // ME_505DD947016D aNotificationType

: ME_505DA9E20331
 CONST UID '505DA9E20331'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_505DA9D50000 // SendNotificationToClients
 ;
 : Parameters
   Seq: ( ME_505DD947016D // aNotificationType
 )
 ; // Parameters

ref; // ME_505DA9E20331 DoIt

: ME_505DA9D50000
 CONST UID '505DA9D50000'
 CONST Name 'SendNotificationToClients'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_505DA91D017B // InscStatusBarItem
 ;
 : Operations
   Seq: ( ME_505DA9E20331 // DoIt
 )
 ; // Operations

ref; // ME_505DA9D50000 SendNotificationToClients

: ME_505DA99E0173
 CONST Name 'aClient'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_505DA91D017B // InscStatusBarItem
 ;

ref; // ME_505DA99E0173 aClient

: ME_505DA993034F
 CONST UID '505DA993034F'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_505DA97101BB // Subscribe
 ;
 : Parameters
   Seq: ( ME_505DA99E0173 // aClient
 )
 ; // Parameters

ref; // ME_505DA993034F DoIt

: ME_505DA97101BB
 CONST UID '505DA97101BB'
 CONST Name 'Subscribe'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_505DA91D017B // InscStatusBarItem
 ;
 : Operations
   Seq: ( ME_505DA993034F // DoIt
 )
 ; // Operations

ref; // ME_505DA97101BB Subscribe

: ME_505DD95301FB
 CONST Name 'aSender'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_505DA91D017B // InscStatusBarItem
 ;

ref; // ME_505DD95301FB aSender

: ME_505DD9530222
 CONST Name 'aNotificationType'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target ME_505DA86200EB // TnscStatusBarItemNotificationType
 ;

ref; // ME_505DD9530222 aNotificationType

: ME_505DD9520040
 CONST UID '505DD9520040'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_505DCA6603AA // Notify
 ;
 : Parameters
   Seq: ( ME_505DD95301FB // aSender
 ME_505DD9530222 // aNotificationType
 )
 ; // Parameters

ref; // ME_505DD9520040 DoIt

: ME_505DCA6603AA
 CONST UID '505DCA6603AA'
 CONST Name 'Notify'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_505DA91D017B // InscStatusBarItem
 ;
 : Operations
   Seq: ( ME_505DD9520040 // DoIt
 )
 ; // Operations

ref; // ME_505DCA6603AA Notify

: ME_505DA91D017B
 CONST UID '505DA91D017B'
 CONST GUID 'F1EFAA8A-2134-43CC-AF3F-0B73FB275A89'
 CONST Name 'InscStatusBarItem'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_505DCE690055 // StatusBarUtils
 ;
 : Attributes
   Seq: ( ME_505DD53B0349 // Visible
 ME_505DDE8F02A1 // NotificationClients
 ME_50603D930238 // ItemDef
 )
 ; // Attributes
 : Operations
   Seq: ( ME_505DA9AF003E // Unsubscribe
 ME_505DA9D50000 // SendNotificationToClients
 ME_505DA97101BB // Subscribe
 ME_505DCA6603AA // Notify
 )
 ; // Operations
 : Children
   Seq: ( ME_505DA86200EB // TnscStatusBarItemNotificationType
 )
 ; // Children
 CONST extprop:rc:SelfName 'StatusBarItem'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_505DA91D017B InscStatusBarItem

: ME_505DC5D003BE
 CONST UID '505DC5D003BE'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_505DA61E00A6 // TnscStatusBarItemsList
 ;
 : Target ME_505DA91D017B // InscStatusBarItem
 ;

ref; // ME_505DC5D003BE ItemType

: ME_505DA61E00A6
 CONST UID '505DA61E00A6'
 CONST Name 'TnscStatusBarItemsList'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_505DCE690055 // StatusBarUtils
 ;
 : Inherits
   Seq: ( WL 'ME_47B57D630029' '47913B47006E.pas.ms.script' // l3InterfacePtrList
 WL 'ME_4A54DD4E036F' '47913B47006E.pas.ms.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_505DC5D003BE // ItemType
 )
 ; // Attributes
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST extprop:rc:SelfName 'StatusBarItemsList'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_505DA61E00A6 TnscStatusBarItemsList

: ME_505DCE690055
 CONST UID '505DCE690055'
 CONST Name 'StatusBarUtils'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_505DA8FC03CF // StatusBarUtils
 ;
 : Children
   Seq: ( ME_505DA91D017B // InscStatusBarItem
 ME_505DA61E00A6 // TnscStatusBarItemsList
 )
 ; // Children
 CONST "no hands" false
 CONST intf.pas:Path 'common\components\gui\Garant\Nemesis\StatusBarUtils.pas'

ref; // ME_505DCE690055 StatusBarUtils

: ME_505DA8FC03CF
 CONST UID '505DA8FC03CF'
 CONST Name 'StatusBarUtils'
 CONST Class class_Category
 : Stereotype st_Views ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_490838AA02D0' '490838AA02D0.pas.ms.script' // Nemesis
 ;
 : Children
   Seq: ( ME_505DA5E7038D // nscStatusBarItemNotification
 ME_505DCE690055 // StatusBarUtils
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_476F78840219' '476F78840219.pas.ms.script' // Messages
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_4799D29F033F' '4799D29F033F.pas.ms.script' // Implementation
 WL 'ME_490838E10313' '490838E10313.pas.ms.script' // nscNewInterfaces
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_5028898902A2' '5028898902A2.pas.ms.script' // tb97utils
 )
 ; // Depends
 CONST "UseNewGen" true

ref; // ME_505DA8FC03CF StatusBarUtils
