// Application 50883A2E00B3 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_50883A2E00B3

FORWARD ME_4AB22E140136

FORWARD ME_4AB33E56019A

: ME_4AB33E7A03B0
 CONST Name 'aModule'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4AB33E2C03D7' '47D0E1500033.pas.ms.script' // RvcmModule
 ;

ref; // ME_4AB33E7A03B0 aModule

: ME_4C910A6A011E
 CONST Name 'aCap'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4C910A6A011E aCap

: ME_4AB33E77023E
 CONST UID '4AB33E77023E'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4AB33E56019A // PublishModule
 ;
 : Parameters
   Seq: ( ME_4AB33E7A03B0 // aModule
 ME_4C910A6A011E // aCap
 )
 ; // Parameters

ref; // ME_4AB33E77023E DoIt

: ME_4AB3407002A3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4AB33E56019A // PublishModule
 ;
 : Target WL 'ME_4AB34044026A' '4AB34028023E.pas.ms.script' // TvcmModulesCollection
 ;

ref; // ME_4AB3407002A3 

: ME_4AB33E56019A
 CONST UID '4AB33E56019A'
 CONST Name 'PublishModule'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Operations
   Seq: ( HWL ME_4AB33E77023E // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4AB3407002A3 // TvcmModulesCollection
 )
 ; // Dependencies
 CONST "ifndef" 'DesignTimeLibrary'
 CONST "is static" true

ref; // ME_4AB33E56019A PublishModule

FORWARD ME_4AB33E8201D8

: ME_4AB33EAC01A4
 CONST Name 'aModule'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4AB33E2C03D7' '47D0E1500033.pas.ms.script' // RvcmModule
 ;

ref; // ME_4AB33EAC01A4 aModule

: ME_4AB33EAC01C1
 CONST Name 'aName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4AB33EAC01C1 aName

: ME_4AB33EAC01DE
 CONST Name 'aCap'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4AB33EAC01DE aCap

: ME_4ABC7A9E00C4
 CONST Name 'aNoPrefix'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_4ABC7A9E00C4 aNoPrefix

: ME_4AB33E9900E3
 CONST UID '4AB33E9900E3'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4AB33E8201D8 // PublishModuleOperation
 ;
 : Target WL 'ME_4683CF84010A' '467BAB7F021E.pas.ms.script' // TvcmMOPID
 ;
 : Parameters
   Seq: ( ME_4AB33EAC01A4 // aModule
 ME_4AB33EAC01C1 // aName
 ME_4AB33EAC01DE // aCap
 ME_4ABC7A9E00C4 // aNoPrefix
 )
 ; // Parameters

ref; // ME_4AB33E9900E3 DoIt

: ME_4AB34074033F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4AB33E8201D8 // PublishModuleOperation
 ;
 : Target WL 'ME_4AB34044026A' '4AB34028023E.pas.ms.script' // TvcmModulesCollection
 ;

ref; // ME_4AB34074033F 

: ME_4AB33E8201D8
 CONST UID '4AB33E8201D8'
 CONST Name 'PublishModuleOperation'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Operations
   Seq: ( HWL ME_4AB33E9900E3 // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4AB34074033F // TvcmModulesCollection
 )
 ; // Dependencies
 CONST "ifndef" 'DesignTimeLibrary'
 CONST "is static" true

ref; // ME_4AB33E8201D8 PublishModuleOperation

FORWARD ME_4AB33EF900E2

: ME_4AB33F37036A
 CONST Name 'anEn'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4AB33F37036A anEn

: ME_4AB33F370384
 CONST Name 'anOp'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4AB33F370384 anOp

: ME_4AB33F37039F
 CONST Name 'anEnCap'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4AB33F37039F anEnCap

: ME_4AB33F3703BE
 CONST Name 'anOpCap'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4AB33F3703BE anOpCap

: ME_4AB33F3703DB
 CONST Name 'aNoPrefix'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_4AB33F3703DB aNoPrefix

: ME_4AB33F2301A5
 CONST UID '4AB33F2301A5'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4AB33EF900E2 // PublishOperation
 ;
 : Target WL 'ME_4683CF3401F5' '467BAB7F021E.pas.ms.script' // TvcmOPID
 ;
 : Parameters
   Seq: ( ME_4AB33F37036A // anEn
 ME_4AB33F370384 // anOp
 ME_4AB33F37039F // anEnCap
 ME_4AB33F3703BE // anOpCap
 ME_4AB33F3703DB // aNoPrefix
 )
 ; // Parameters

ref; // ME_4AB33F2301A5 DoIt

: ME_4AB3407C0076
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4AB33EF900E2 // PublishOperation
 ;
 : Target WL 'ME_4AB3405E0326' '4AB34028023E.pas.ms.script' // TvcmRepEntitiesCollection
 ;

ref; // ME_4AB3407C0076 

: ME_4AB33EF900E2
 CONST UID '4AB33EF900E2'
 CONST Name 'PublishOperation'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Operations
   Seq: ( HWL ME_4AB33F2301A5 // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4AB3407C0076 // TvcmRepEntitiesCollection
 )
 ; // Dependencies
 CONST "ifndef" 'DesignTimeLibrary'
 CONST "is static" true

ref; // ME_4AB33EF900E2 PublishOperation

FORWARD ME_4AB33F44024A

: ME_4AB33F6200B8
 CONST Name 'anEn'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4AB33F6200B8 anEn

: ME_4AB33F6200D9
 CONST Name 'anOp'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4AB33F6200D9 anOp

: ME_4AB33F6200F9
 CONST Name 'anEnCap'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4AB33F6200F9 anEnCap

: ME_4AB33F620117
 CONST Name 'anOpCap'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4AB33F620117 anOpCap

: ME_4AB33F620135
 CONST Name 'aNoPrefix'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_4AB33F620135 aNoPrefix

: ME_4AB33F5F020B
 CONST UID '4AB33F5F020B'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4AB33F44024A // PublishInternalOperation
 ;
 : Target WL 'ME_4683CF3401F5' '467BAB7F021E.pas.ms.script' // TvcmOPID
 ;
 : Parameters
   Seq: ( ME_4AB33F6200B8 // anEn
 ME_4AB33F6200D9 // anOp
 ME_4AB33F6200F9 // anEnCap
 ME_4AB33F620117 // anOpCap
 ME_4AB33F620135 // aNoPrefix
 )
 ; // Parameters

ref; // ME_4AB33F5F020B DoIt

: ME_4AB3407F0316
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4AB33F44024A // PublishInternalOperation
 ;
 : Target WL 'ME_4AB3405E0326' '4AB34028023E.pas.ms.script' // TvcmRepEntitiesCollection
 ;

ref; // ME_4AB3407F0316 

: ME_4AB33F44024A
 CONST UID '4AB33F44024A'
 CONST Name 'PublishInternalOperation'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Operations
   Seq: ( HWL ME_4AB33F5F020B // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4AB3407F0316 // TvcmRepEntitiesCollection
 )
 ; // Dependencies
 CONST "ifndef" 'DesignTimeLibrary'
 CONST "is static" true

ref; // ME_4AB33F44024A PublishInternalOperation

FORWARD ME_4C77C9C402B7

: ME_4C77CA3800A5
 CONST Name 'anEn'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4C77CA3800A5 anEn

: ME_4C77CA3800C3
 CONST Name 'anOp'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4C77CA3800C3 anOp

: ME_4C77CA3800E1
 CONST Name 'aState'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4C77CA3800E1 aState

: ME_4C77CA380103
 CONST Name 'aNoPrefix'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_4C77CA380103 aNoPrefix

: ME_4C77C9FC01A9
 CONST UID '4C77C9FC01A9'
 CONST Name 'DoIt'
 CONST Class class_Operation
 %SUMMARY 'Публикует состояние операции' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4C77C9C402B7 // PublishOperationState
 ;
 : Target WL 'ME_4C77C99500F6' '4AB34028023E.pas.ms.script' // TvcmBaseOperationState
 ;
 : Parameters
   Seq: ( ME_4C77CA3800A5 // anEn
 ME_4C77CA3800C3 // anOp
 ME_4C77CA3800E1 // aState
 ME_4C77CA380103 // aNoPrefix
 )
 ; // Parameters

ref; // ME_4C77C9FC01A9 DoIt

: ME_4C77C9C402B7
 CONST UID '4C77C9C402B7'
 CONST Name 'PublishOperationState'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Operations
   Seq: ( HWL ME_4C77C9FC01A9 // DoIt
 )
 ; // Operations
 CONST "ifndef" 'DesignTimeLibrary'
 CONST "is static" true

ref; // ME_4C77C9C402B7 PublishOperationState

FORWARD ME_4EC4C83F01B4

: ME_4EC4C87C01F0
 CONST Name 'anEn'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4EC4C87C01F0 anEn

: ME_4EC4C87C02AE
 CONST Name 'anOp'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4EC4C87C02AE anOp

: ME_4EC4C87C0350
 CONST Name 'anImageIndex'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_4EC4C87C0350 anImageIndex

: ME_4EC4C87D000A
 CONST Name 'aNoPrefix'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_4EC4C87D000A aNoPrefix

: ME_4EC4C8580286
 CONST UID '4EC4C8580286'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4EC4C83F01B4 // SetOperationImageIndex
 ;
 : Parameters
   Seq: ( ME_4EC4C87C01F0 // anEn
 ME_4EC4C87C02AE // anOp
 ME_4EC4C87C0350 // anImageIndex
 ME_4EC4C87D000A // aNoPrefix
 )
 ; // Parameters

ref; // ME_4EC4C8580286 DoIt

: ME_4EC4C83F01B4
 CONST UID '4EC4C83F01B4'
 CONST Name 'SetOperationImageIndex'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Operations
   Seq: ( HWL ME_4EC4C8580286 // DoIt
 )
 ; // Operations
 CONST "ifndef" 'DesignTimeLibrary'
 CONST "is static" true

ref; // ME_4EC4C83F01B4 SetOperationImageIndex

FORWARD ME_4F6AF5F00058

: ME_4F6AF5F801B8
 CONST UID '4F6AF5F801B8'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4F6AF5F00058 // MakeResources
 ;

ref; // ME_4F6AF5F801B8 DoIt

: ME_4F6AF5F00058
 CONST UID '4F6AF5F00058'
 CONST Name 'MakeResources'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Operations
   Seq: ( HWL ME_4F6AF5F801B8 // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_4F6AF5F00058 MakeResources

FORWARD ME_4F79A8E60206

: ME_4F79A8F9000B
 CONST Name 'aTitle'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4B3B3728004C' '4F9BDEEE01BC.pas.ms.script' // Tl3StringIDEx
 ;

ref; // ME_4F79A8F9000B aTitle

: ME_4F79A8F9005C
 CONST Name 'aHelpFile'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4F79A8F9005C aHelpFile

: ME_4F79A8F601F2
 CONST UID '4F79A8F601F2'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4F79A8E60206 // Run
 ;
 : Parameters
   Seq: ( ME_4F79A8F9000B // aTitle
 ME_4F79A8F9005C // aHelpFile
 )
 ; // Parameters

ref; // ME_4F79A8F601F2 DoIt

: ME_4F79AC200294
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4F79A8E60206 // Run
 ;
 : Target WL 'ME_4BA2214002EE' '4F9BDEEE01BC.pas.ms.script' // Tl3ConstStrings
 ;

ref; // ME_4F79AC200294 

: ME_521B8DAC02FB
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4F79A8E60206 // Run
 ;
 : Target WL 'ME_47ECE41C00D2' '4799D29F033F.pas.ms.script' // TApplication
 ;

ref; // ME_521B8DAC02FB 

: ME_521B8F7500DF
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4F79A8E60206 // Run
 ;
 : Target WL 'ME_47752AF90375' '47750CE700D0.pas.ms.script' // afwFacade
 ;

ref; // ME_521B8F7500DF 

: ME_4F79A8E60206
 CONST UID '4F79A8E60206'
 CONST Name 'Run'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Operations
   Seq: ( HWL ME_4F79A8F601F2 // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4F79AC200294 // Tl3ConstStrings
 ME_521B8DAC02FB // TApplication
 ME_521B8F7500DF // afwFacade
 )
 ; // Dependencies
 CONST "is static" true

ref; // ME_4F79A8E60206 Run

FORWARD ME_4F6AF5860291

: ME_4F6AF5AB02A9
 CONST Name 'aTitle'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4B3B3728004C' '4F9BDEEE01BC.pas.ms.script' // Tl3StringIDEx
 ;

ref; // ME_4F6AF5AB02A9 aTitle

: ME_4F6AF5AB02F4
 CONST Name 'aHelpFile'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_4F6AF5AB02F4 aHelpFile

: ME_4F6AF59403C0
 CONST UID '4F6AF59403C0'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_4F6AF5860291 // Runner
 ;
 : Parameters
   Seq: ( ME_4F6AF5AB02A9 // aTitle
 ME_4F6AF5AB02F4 // aHelpFile
 )
 ; // Parameters

ref; // ME_4F6AF59403C0 DoIt

: ME_4F6AF5860291
 CONST UID '4F6AF5860291'
 CONST Name 'Runner'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Operations
   Seq: ( HWL ME_4F6AF59403C0 // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_4F6AF5860291 Runner

FORWARD ME_52F2269B0373

: ME_52F226AA017C
 CONST UID '52F226AA017C'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_52F2269B0373 // BeforeApplicationRun
 ;

ref; // ME_52F226AA017C DoIt

: ME_52F2269B0373
 CONST UID '52F2269B0373'
 CONST Name 'BeforeApplicationRun'
 CONST Class class_Class
 : Stereotype st_virtualmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Operations
   Seq: ( HWL ME_52F226AA017C // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_52F2269B0373 BeforeApplicationRun

: ME_5788BA13039A
 CONST UID '5788BA13039A'
 CONST Name 'RegisterOperations'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 CONST "is static" true

ref; // ME_5788BA13039A RegisterOperations

: ME_4AB24F0D00D3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Target WL 'ME_4AB24EF502BB' '4AADF9450143.pas.ms.script' // vcmBaseMenuManager
 ;

ref; // ME_4AB24F0D00D3 

: ME_57851CF00363
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Target WL 'ME_57851B4B01F9' '57851B200290.pas.ms.script' // TvcmOperationsForRegister
 ;

ref; // ME_57851CF00363 

: ME_5786263C02E7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Target WL 'ME_578614F1007E' '57851B200290.pas.ms.script' // TvcmOperationStateForRegister
 ;

ref; // ME_5786263C02E7 

: ME_5786553701D6
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Target WL 'ME_5786541F0012' '578653AB0077.pas.ms.script' // TvcmModulesForRegister
 ;

ref; // ME_5786553701D6 

: ME_5787733003C2
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_4AB22E140136 // TvcmApplication
 ;
 : Target WL 'ME_5787730D03D7' '578653AB0077.pas.ms.script' // TvcmModuleOperationsForRegister
 ;

ref; // ME_5787733003C2 

: ME_4AB22E140136
 CONST UID '4AB22E140136'
 CONST Name 'TvcmApplication'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_50883A2E00B3 // Application
 ;
 : Operations
   Seq: ( HWL ME_4AB33E56019A // PublishModule
 HWL ME_4AB33E8201D8 // PublishModuleOperation
 HWL ME_4AB33EF900E2 // PublishOperation
 HWL ME_4AB33F44024A // PublishInternalOperation
 HWL ME_4C77C9C402B7 // PublishOperationState
 HWL ME_4EC4C83F01B4 // SetOperationImageIndex
 HWL ME_4F6AF5F00058 // MakeResources
 HWL ME_4F79A8E60206 // Run
 HWL ME_4F6AF5860291 // Runner
 HWL ME_52F2269B0373 // BeforeApplicationRun
 HWL ME_5788BA13039A // RegisterOperations
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_4AB24F0D00D3 // vcmBaseMenuManager
 ME_57851CF00363 // TvcmOperationsForRegister
 ME_5786263C02E7 // TvcmOperationStateForRegister
 ME_5786553701D6 // TvcmModulesForRegister
 ME_5787733003C2 // TvcmModuleOperationsForRegister
 )
 ; // Dependencies
 CONST "author" 'Люлин А.В.'
 CONST "need UC" true
 CONST "no hands" true
 CONST "started" '17.09.2009 16:40'
 CONST intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Visual\vcmApplication.pas'
 CONST extprop:rc:SelfName 'Application'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vcmApplication'

ref; // ME_4AB22E140136 TvcmApplication

: ME_523040FB01AA
 CONST UID '523040FB01AA'
 CONST Name 'MvcmApplication'
 CONST Class class_Class
 : Stereotype st_MixInMirror ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_50883A2E00B3 // Application
 ;
 : Inherits
   Seq: ( HWL ME_4AB22E140136 // TvcmApplication
 )
 ; // Inherits

ref; // ME_523040FB01AA MvcmApplication

: ME_50883A2E00B3
 CONST UID '50883A2E00B3'
 CONST Name 'Application'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4E13416D0227' '4E13416D0227.pas.ms.script' // VCM$Visual
 ;
 : Children
   Seq: ( HWL ME_4AB22E140136 // TvcmApplication
 HWL ME_523040FB01AA // MvcmApplication
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 WL 'ME_467BAB7F021E' '467BAB7F021E.pas.ms.script' // vcmExternalInterfaces
 WL 'ME_47750CE700D0' '47750CE700D0.pas.ms.script' // afwFacade
 WL 'ME_4799D29F033F' '4799D29F033F.pas.ms.script' // Implementation
 WL 'ME_47B9727603BE' '47B9727603BE.pas.ms.script' // FormSets
 WL 'ME_47D0E1500033' '47D0E1500033.pas.ms.script' // Implementation
 WL 'ME_4AADF9450143' '4AADF9450143.pas.ms.script' // Visual
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_4AB34028023E' '4AB34028023E.pas.ms.script' // Components
 WL 'ME_4F9BDEEE01BC' '4F9BDEEE01BC.pas.ms.script' // Поддержка локализованных сообщений
 WL 'ME_57851B200290' '57851B200290.pas.ms.script' // Application
 WL 'ME_578653AB0077' '578653AB0077.pas.ms.script' // Modules
 )
 ; // Depends
 CONST "path prefix" '/implementation/Visual'
 CONST intf.pas:PathOnly '\common\components\gui\Garant\VCM\implementation\Visual'

ref; // ME_50883A2E00B3 Application
