// Shared Delphi Search Tests 511B938D010E Project Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_511B938D010E
%%Inner ME_511B938D010E

ME ME_511B938D010E
 MEPROP UID '511B938D010E'
 MEPROP Name 'Shared Delphi Search Tests'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Project ;
 %SUMMARY 'Тесты поиска F1' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELIST Children
   Seq: ( WL? 'ME_511B4CA100B2' // Search
 WL? 'ME_4114A74FDFBC' // ReleaseSearch
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_4B30CC420206' // Shared Delphi Testing Framework
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "Full MDP" false
 UP "create project" true
 UP "fix version" 0
 UP "force usage" true
 UP "full constraint" true
 UP "ifdef" 'nsTest'
 UP "major version" 1
 UP "minor version" 0
 UP "package prefix" 'ru.garant'
 UP "root path suffix" '/components'
 UP "space key" 'SHD'
 UP "space name" 'Shared (delphi)'
 UP intf.pas:PathOnly '\common\components'

ENDME // ME_511B938D010E Shared Delphi Search Tests
