// EverestLite$Test 512AF4A800AA TestTarget Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_512AF4A800AA
%%Inner ME_512AF4A800AA
%%Inner ME_512AF4A800AA

ME ME_512AF4A800AA
 MEPROP UID '512AF4A800AA'
 MEPROP Name 'EverestLite'
 MEPROP OriginalName 'EverestLite$Test'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_TestTarget ;
 %SUMMARY 'Тесты Эвереста' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_512AF2EE0211' // archi$EverestLite$Test
 ;
 MELIST Children
   Seq: ( WL? 'ME_512AF4F300FC' // TEverestLiteTestRes
 WL? 'ME_512AF81103C7' // toK
 WL? 'ME_53F312A7027C' // toKT
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_4684F91300DD' // Vcl
 WL? 'ME_4790B4F00236' // AFW
 WL? 'ME_4790D09A0378' // L3
 WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_4799D29F033F' // Implementation
 WL? 'ME_4B2A0D4A006F' // DUnit
 WL? 'ME_4B2A0D6A0077' // Source
 WL? 'ME_4B2A10C40309' // DUnitTuning
 WL? 'ME_4B2A112B011A' // Source
 WL? 'ME_4DB14DDC01A9' // ScriptDebugger
 WL? 'ME_4DE3425B01DA' // ArchiScriptSupport
 WL? 'ME_4DE7653F03E5' // Archi Insider Test Support
 WL? 'ME_4DEF302C0007' // ScriptEngine
 WL? 'ME_4E030FC801EB' // BatchServices
 WL? 'ME_4E1F0EB100C4' // ScriptEngine
 WL? 'ME_512B1731031D' // EverestLiteTests
 WL? 'ME_512DAF9001E3' // EverestInsiderTests
 WL? 'ME_512DAFB70392' // EverestLiteInsiderTest
 WL? 'ME_513098F2017C' // Shared Delphi Tests Common
 WL? 'ME_51309A4A02FB' // Tests Res Common
 WL? 'ME_550012C403C4' // L3$AFW
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "defines" 'EverestLite.inc'
 UP "is insider test" true
 UP "need UC in project" true
 UP intf.pas:Path 'archi\source\projects\Everest\Lite\7.0\Express\EverestLiteTest.dpr'
 UP extprop:pas:UnitName 'EverestLiteTest'
 UP Version 0

ENDME // ME_512AF4A800AA EverestLite$Test
