// EverestLiteTests 512B1731031D TestLibrary Category

INCLUDE 'ElementsRTTI.ms.dict'

: ME_512B1731031D
 CONST UID '512B1731031D'
 CONST Name 'EverestLiteTests'
 CONST Class class_Category
 : Stereotype st_TestLibrary ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_512AF2EE0211' '512AF2EE0211.pas.ms.script' // archi$EverestLite$Test
 ;
 : Children
   Seq: ( WL 'ME_512DAE9A0372' '512DAE9A0372.pas.ms.script' // FileFormatTests
 WL 'ME_532164D501C5' '532164D501C5.pas.ms.script' // PreivewTests
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4DE7653F03E5' '4DE7653F03E5.pas.ms.script' // Archi Insider Test Support
 )
 ; // Depends
 CONST "exec mode" 'concluded'
 CONST "gui" 'prj'
 CONST "is namespace" true
 CONST "vendor" '/Tests'
 CONST intf.pas:PathOnly '\archi\source\projects\Everest\Lite\7.0\Express\Tests'

ref; // ME_512B1731031D EverestLiteTests
