// Main 512DBAD202CB Library Category

INCLUDE 'ElementsRTTI.ms.dict'

: ME_512DBAD202CB
 CONST UID '512DBAD202CB'
 CONST Name 'Main'
 CONST Class class_Category
 : Stereotype st_Library ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4E772D3303A7' '4E772D3303A7.pas.ms.script' // archi$EverestLite$NORMAL
 ;
 : Children
   Seq: ( WL 'ME_512DBAE001FA' '512DBAE001FA.pas.ms.script' // MainUnits
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_469F3E37025A' '469F3E37025A.pas.ms.script' // Rtl
 WL 'ME_4DECDBE201FB' '4DECDBE201FB.pas.ms.script' // Dialogs
 )
 ; // Depends
 CONST "exec mode" 'concluded'
 CONST "gui" 'prj'
 CONST "vendor" 'none'
 CONST intf.pas:PathOnly '\archi\source\projects\Everest\Lite\7.0\Express\Main'

ref; // ME_512DBAD202CB Main
