// Tests Res Common 51309A4A02FB Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_51309A4A02FB

FORWARD ME_51349B6001D3

: ME_51349CE90123
 CONST UID '51349CE90123'
 CONST Name 'g_TestsForm'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_51349B6001D3 // TestForm4Scripts
 ;
 : Target WL 'ME_4DA30F0F02C1' '4B2A0D6A0077.pas.ms.script' // TGUITestRunner
 ;

ref; // ME_51349CE90123 g_TestsForm

: ME_51349D2901B5
 CONST UID '51349D2901B5'
 CONST Name 'aForm'
 CONST Class class_Parameter
 : Stereotype st_const ;
 : Target WL 'ME_4DA30F0F02C1' '4B2A0D6A0077.pas.ms.script' // TGUITestRunner
 ;

ref; // ME_51349D2901B5 aForm

: ME_51349D1803A7
 CONST UID '51349D1803A7'
 CONST Name 'LinkTestForm'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_51349B6001D3 // TestForm4Scripts
 ;
 : Parameters
   Seq: ( ME_51349D2901B5 // aForm
 )
 ; // Parameters

ref; // ME_51349D1803A7 LinkTestForm

: ME_51349D2D0187
 CONST UID '51349D2D0187'
 CONST Name 'UnLinkTestForm'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_51349B6001D3 // TestForm4Scripts
 ;

ref; // ME_51349D2D0187 UnLinkTestForm

: ME_51349D4E02CB
 CONST UID '51349D4E02CB'
 CONST Name 'GetTestForm'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_51349B6001D3 // TestForm4Scripts
 ;
 : Target WL 'ME_4DA30F0F02C1' '4B2A0D6A0077.pas.ms.script' // TGUITestRunner
 ;

ref; // ME_51349D4E02CB GetTestForm

: ME_51349B6001D3
 CONST UID '51349B6001D3'
 CONST Name 'TestForm4Scripts'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_51309A4A02FB // Tests Res Common
 ;
 : Attributes
   Seq: ( ME_51349CE90123 // g_TestsForm
 )
 ; // Attributes
 : Operations
   Seq: ( ME_51349D1803A7 // LinkTestForm
 ME_51349D2D0187 // UnLinkTestForm
 ME_51349D4E02CB // GetTestForm
 )
 ; // Operations
 CONST "no hands" false
 CONST intf.pas:Path 'common\components\rtl\Garant\Shared_Delphi_Tests_Common\TestForm4Scripts.pas'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\Shared_Delphi_Tests_Common'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_51349B6001D3 TestForm4Scripts

FORWARD ME_52F21A610247

: ME_4DA478990164
 CONST UID '4DA478990164'
 CONST Name 'g_IsBatchMode'
 CONST Class class_Attribute
 : Stereotype st_static::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_4DA478990164 g_IsBatchMode

: ME_4DA478B5000C
 CONST UID '4DA478B5000C'
 CONST Name 'g_IsBatchModeValid'
 CONST Class class_Attribute
 : Stereotype st_static::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_4DA478B5000C g_IsBatchModeValid

: ME_52F21B18009E
 CONST UID '52F21B18009E'
 CONST Name 'g_Debugger'
 CONST Class class_Attribute
 : Stereotype st_static::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_lnk
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Target WL 'ME_4DB14E0A029D' '4DB14DDC01A9.pas.ms.script' // TtfwScriptDebugger_Form
 ;

ref; // ME_52F21B18009E g_Debugger

: ME_52F21B3201DF
 CONST UID '52F21B3201DF'
 CONST Name 'g_TestsForm'
 CONST Class class_Attribute
 : Stereotype st_static::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_lnk
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Target WL 'ME_4DA30F0F02C1' '4B2A0D6A0077.pas.ms.script' // TGUITestRunner
 ;

ref; // ME_52F21B3201DF g_TestsForm

: ME_52F21B3B012E
 CONST UID '52F21B3B012E'
 CONST Name 'g_InRun'
 CONST Class class_Attribute
 : Stereotype st_static::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_lnk
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_52F21B3B012E g_InRun

FORWARD ME_4F79BCC902C5

: ME_4F79BCDA0351
 CONST UID '4F79BCDA0351'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F79BCC902C5 // CalcBatchMode
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_4F79BCDA0351 DoIt

: ME_4F79BCC902C5
 CONST UID '4F79BCC902C5'
 CONST Name 'CalcBatchMode'
 CONST Class class_Class
 : Stereotype st_abstractmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Operations
   Seq: ( ME_4F79BCDA0351 // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_4F79BCC902C5 CalcBatchMode

FORWARD ME_4DA3361A0305

: ME_4DA3362C0043
 CONST UID '4DA3362C0043'
 CONST Name 'Sender'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4807745602C8' '4AB0C3C60310.pas.ms.script' // TObject
 ;

ref; // ME_4DA3362C0043 Sender

: ME_4DA3362C00B5
 CONST UID '4DA3362C00B5'
 CONST Name 'Done'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_4DA3362C00B5 Done

: ME_4DA33626026D
 CONST UID '4DA33626026D'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4DA3361A0305 // DoIdle
 ;
 : Parameters
   Seq: ( ME_4DA3362C0043 // Sender
 ME_4DA3362C00B5 // Done
 )
 ; // Parameters

ref; // ME_4DA33626026D DoIt

: ME_4DA3361A0305
 CONST UID '4DA3361A0305'
 CONST Name 'DoIdle'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Operations
   Seq: ( ME_4DA33626026D // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_4DA3361A0305 DoIdle

FORWARD ME_4DA476580343

: ME_4DA4766801BC
 CONST UID '4DA4766801BC'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4DA476580343 // IsBatchMode
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_4DA4766801BC DoIt

: ME_4DA476580343
 CONST UID '4DA476580343'
 CONST Name 'IsBatchMode'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Operations
   Seq: ( ME_4DA4766801BC // DoIt
 )
 ; // Operations
 CONST "ifdef" 'InsiderTest'
 CONST "is static" true

ref; // ME_4DA476580343 IsBatchMode

FORWARD ME_4F79B9D500D7

: ME_4F79B9E70001
 CONST UID '4F79B9E70001'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F79B9D500D7 // ReadyToRun
 ;

ref; // ME_4F79B9E70001 DoIt

: ME_4F79B9D500D7
 CONST UID '4F79B9D500D7'
 CONST Name 'ReadyToRun'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 %SUMMARY '¬ызываетс€ непосредственно перед запуском приложени€, например дл€ инициализации/запуска тестов' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Operations
   Seq: ( ME_4F79B9E70001 // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_4F79B9D500D7 ReadyToRun

: ME_52F22702013E
 CONST UID '52F22702013E'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Target WL 'ME_4CDD241C0184' '47913B47006E.pas.ms.script' // l3System
 ;

ref; // ME_52F22702013E 

: ME_52F259E0007D
 CONST UID '52F259E0007D'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Target WL 'ME_4B2A6D4303A9' '4B2A112B011A.pas.ms.script' // KTestRunner
 ;

ref; // ME_52F259E0007D 

: ME_52F25C7E009E
 CONST UID '52F25C7E009E'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Target WL 'ME_4C8A2ADD01B1' '4799D29F033F.pas.ms.script' // Application
 ;

ref; // ME_52F25C7E009E 

: ME_52F25F240290
 CONST UID '52F25F240290'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Target WL 'ME_4E03119F00B2' '4E030FC801EB.pas.ms.script' // afwAnswer
 ;

ref; // ME_52F25F240290 

: ME_52F2615A008E
 CONST UID '52F2615A008E'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Target WL 'ME_4B2A0DCE03A9' '4B2A0D6A0077.pas.ms.script' // TestFrameWork
 ;

ref; // ME_52F2615A008E 

: ME_55099C0B00E4
 CONST UID '55099C0B00E4'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_52F21A610247 // GUIAppTester
 ;
 : Target WL 'ME_5507FDD203E1' '4E030FC801EB.pas.ms.script' // Tl3BatchService
 ;

ref; // ME_55099C0B00E4 

: ME_52F21A610247
 CONST UID '52F21A610247'
 CONST Name 'GUIAppTester'
 CONST Class class_Class
 : Stereotype st_Impurity ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Ѕазовый тестер GUI-приложений' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_51309A4A02FB // Tests Res Common
 ;
 : Attributes
   Seq: ( ME_4DA478990164 // g_IsBatchMode
 ME_4DA478B5000C // g_IsBatchModeValid
 ME_52F21B18009E // g_Debugger
 ME_52F21B3201DF // g_TestsForm
 ME_52F21B3B012E // g_InRun
 )
 ; // Attributes
 : Operations
   Seq: ( ME_4F79BCC902C5 // CalcBatchMode
 ME_4DA3361A0305 // DoIdle
 ME_4DA476580343 // IsBatchMode
 ME_4F79B9D500D7 // ReadyToRun
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_52F22702013E // 
 ME_52F259E0007D // 
 ME_52F25C7E009E // 
 ME_52F25F240290 // 
 ME_52F2615A008E // 
 ME_55099C0B00E4 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\Shared_Delphi_Tests_Common\GUIAppTester.imp.pas'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\Shared_Delphi_Tests_Common'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'
 CONST extprop:pas:TypeName '_GUIAppTester_'
 CONST extprop:pas:UnitName 'GUIAppTester.imp'

ref; // ME_52F21A610247 GUIAppTester

FORWARD ME_52F255E702F0

FORWARD ME_52F264E400E6

: ME_52F264F70116
 CONST UID '52F264F70116'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent ME_52F264E400E6 // TResultsPlaces
 ;
 : Target WL 'ME_4B7AAF1203B4' '4B2A112B011A.pas.ms.script' // RTestResultsPlace
 ;

ref; // ME_52F264F70116 

: ME_52F264E400E6
 CONST UID '52F264E400E6'
 CONST Name 'TResultsPlaces'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_52F255E702F0 // TGUIAppTester
 ;
 : Attributes
   Seq: ( ME_52F264F70116 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\Shared_Delphi_Tests_Common'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_52F264E400E6 TResultsPlaces

FORWARD ME_52F264840382

: ME_52F26508019F
 CONST UID '52F26508019F'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_52F264840382 // GetResultsPlaces
 ;
 : Target ME_52F264E400E6 // TResultsPlaces
 ;

ref; // ME_52F26508019F DoIt

: ME_52F264840382
 CONST UID '52F264840382'
 CONST Name 'GetResultsPlaces'
 CONST Class class_Class
 : Stereotype st_abstractmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent ME_52F255E702F0 // TGUIAppTester
 ;
 : Operations
   Seq: ( ME_52F26508019F // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_52F264840382 GetResultsPlaces

FORWARD ME_52F2651C00F4

: ME_52F2656802BD
 CONST UID '52F2656802BD'
 CONST Name 'aPlaces'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4B7AAF5C0096' '4B2A112B011A.pas.ms.script' // array of RTestResultsPlace
 ;

ref; // ME_52F2656802BD aPlaces

: ME_52F2654F009A
 CONST UID '52F2654F009A'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_52F2651C00F4 // MakeResults
 ;
 : Target ME_52F264E400E6 // TResultsPlaces
 ;
 : Parameters
   Seq: ( ME_52F2656802BD // aPlaces
 )
 ; // Parameters

ref; // ME_52F2654F009A DoIt

: ME_52F2651C00F4
 CONST UID '52F2651C00F4'
 CONST Name 'MakeResults'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent ME_52F255E702F0 // TGUIAppTester
 ;
 : Operations
   Seq: ( ME_52F2654F009A // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_52F2651C00F4 MakeResults

: ME_52F2645E038F
 CONST UID '52F2645E038F'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_52F255E702F0 // TGUIAppTester
 ;
 : Target WL 'ME_4B2A6D4303A9' '4B2A112B011A.pas.ms.script' // KTestRunner
 ;

ref; // ME_52F2645E038F 

: ME_52F268E10370
 CONST UID '52F268E10370'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_52F255E702F0 // TGUIAppTester
 ;
 : Target WL 'ME_4DEF306102FF' '4DEF302C0007.pas.ms.script' // TtfwScriptEngineEX
 ;

ref; // ME_52F268E10370 

: ME_4F79BCC902C5_ME_52F255E702F0
 CONST UID '4F79BCC902C5'
 CONST Name 'CalcBatchMode'
 : Original ME_4F79BCC902C5 // CalcBatchMode
 ;
 : Implementor ME_52F255E702F0 // TGUIAppTester
 ;
 CONST OpKind opkind_Implemented
 CONST "is static" true
ref; // ME_4F79BCC902C5_ME_52F255E702F0 CalcBatchMode

: ME_52F255E702F0
 CONST UID '52F255E702F0'
 CONST Name 'TGUIAppTester'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_51309A4A02FB // Tests Res Common
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 ME_52F21A610247 // GUIAppTester
 )
 ; // Inherits
 : Operations
   Seq: ( ME_52F264840382 // GetResultsPlaces
 ME_52F2651C00F4 // MakeResults
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4F79BCC902C5_ME_52F255E702F0 // CalcBatchMode
 )
 ; // Implemented
 : Children
   Seq: ( ME_52F264E400E6 // TResultsPlaces
 )
 ; // Children
 : Dependencies
   Seq: ( ME_52F2645E038F // 
 ME_52F268E10370 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\Shared_Delphi_Tests_Common\GUIAppTester.pas'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\Shared_Delphi_Tests_Common'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'
 CONST extprop:rc:SelfName 'GUIAppTester'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'GUIAppTester'

ref; // ME_52F255E702F0 TGUIAppTester

: ME_51309A4A02FB
 CONST UID '51309A4A02FB'
 CONST Name 'Tests Res Common'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_513098F2017C' '513098F2017C.pas.ms.script' // Shared Delphi Tests Common
 ;
 : Children
   Seq: ( ME_51349B6001D3 // TestForm4Scripts
 ME_52F21A610247 // GUIAppTester
 ME_52F255E702F0 // TGUIAppTester
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_4799D29F033F' '4799D29F033F.pas.ms.script' // Implementation
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_4B2A0D6A0077' '4B2A0D6A0077.pas.ms.script' // Source
 WL 'ME_4B2A112B011A' '4B2A112B011A.pas.ms.script' // Source
 WL 'ME_4DB14DDC01A9' '4DB14DDC01A9.pas.ms.script' // ScriptDebugger
 WL 'ME_4DEF302C0007' '4DEF302C0007.pas.ms.script' // ScriptEngine
 WL 'ME_4E030FC801EB' '4E030FC801EB.pas.ms.script' // BatchServices
 )
 ; // Depends
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\Shared_Delphi_Tests_Common'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\51309A4A02FB.pas.ms.script'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\51309A4A02FB.pas.ms.script.runner'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_51309A4A02FB Tests Res Common
