// Shared Delphi Tests Common 513098F2017C Library Category

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_513098F2017C
 MEPROP UID '513098F2017C'
 MEPROP Name 'Shared Delphi Tests Common'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Library ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4B30CC420206' '4B30CC420206.ms.model.script' // Shared Delphi Testing Framework
 ;
 MELIST Children
   Seq: ( WL 'ME_51309A4A02FB' '51309A4A02FB.ms.model.script' // Tests Res Common
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_4684F91300DD' '4684F91300DD.ms.model.script' // Vcl
 WL 'ME_469F3E37025A' '469F3E37025A.ms.model.script' // Rtl
 WL 'ME_4790B4F00236' '4790B4F00236.ms.model.script' // AFW
 WL 'ME_4790D09A0378' '4790D09A0378.ms.model.script' // L3
 WL 'ME_4B2A0D4A006F' '4B2A0D4A006F.ms.model.script' // DUnit
 WL 'ME_4B2A10C40309' '4B2A10C40309.ms.model.script' // DUnitTuning
 WL 'ME_4E1F0EB100C4' '4E1F0EB100C4.ms.model.script' // ScriptEngine
 WL 'ME_550012C403C4' '550012C403C4.ms.model.script' // L3$AFW
 )
 ; // Depends
 UP "exec mode" 'concluded'
 UP "gui" 'rtl'
 UP "ifdef" 'nsTest'
 UP "is namespace" true
 UP "vendor" '/Garant'
 UP intf.pas:PathOnly '\common\components\rtl\Garant\Shared_Delphi_Tests_Common'

ENDME // ME_513098F2017C Shared Delphi Tests Common
