// RefCounted 51614065019A Impurity Class

INCLUDE '51612ED700B4.pas.ms.script'

FORWARD ME_51614065019A

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_5161409E01B6
 CONST UID '5161409E01B6'
 CONST Name 'destroy'
 CONST Class 'Operation'
 CONST Stereotype ''
 %SUMMARY 'Это чтобы не было соблазна перекрывать destroy.' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_5161409E01B6 destroy

INCLUDE '4807744200AA.pas.ms.script'

: ME_516D4E5A000A
 CONST UID '516D4E5A000A'
 CONST Name 'NewInstance'
 CONST Class 'Operation'
 CONST Stereotype 'static'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Target ME_4807745602C8 // TObject
 ;

 @SELF
; // ME_516D4E5A000A NewInstance

: ME_516D4E780193
 CONST UID '516D4E780193'
 CONST Name 'FreeInstance'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_516D4E780193 FreeInstance

: ME_516D4E9403A0
 CONST UID '516D4E9403A0'
 CONST Name 'AfterConstruction'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_516D4E9403A0 AfterConstruction

: ME_516D4EAD0095
 CONST UID '516D4EAD0095'
 CONST Name 'BeforeDestruction'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_516D4EAD0095 BeforeDestruction

: ME_51614065019A
 CONST UID '51614065019A'
 CONST Name 'RefCounted'
 CONST Class 'Class'
 CONST Stereotype 'Impurity'
 %SUMMARY 'В этом классе собираем методы, которые запрещено перекрывать и вызывать напрямую' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_51612ED700B4 // RefCountedPrim
 ]
 ; // Inherits
 : Operations
   [ ME_5161409E01B6 // destroy
 ME_516D4E5A000A // NewInstance
 ME_516D4E780193 // FreeInstance
 ME_516D4E9403A0 // AfterConstruction
 ME_516D4EAD0095 // BeforeDestruction
 ]
 ; // Operations
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_51614065019A RefCounted
