// Emba 51643DEB0153 TestUnit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_51643DEB0153

ME ME_51643DEB0153
 MEPROP UID '51643DEB0153'
 MEPROP Name 'Emba'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_TestUnit ;
 %SUMMARY 'Тесты стандартных библиотек' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_5155865B01B6' // SandBoxTest
 ;
 MELIST Children
   Seq: ( WL? 'ME_51643E02018F' // TReallocMemTest
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_4B2A0D6A0077' // Source
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP Version 0

ENDME // ME_51643DEB0153 Emba
