// TvtRadioButton 517941E500BF GuiControl Class

INCLUDE 'ElementsRTTI.ms.dict'

%%InheritedBy ME_4F69BC9C014A ME_517941E500BF
%%InheritedBy ME_5179415C0005 ME_517941E500BF

ME ME_517941E500BF
 MEPROP UID '517941E500BF'
 MEPROP Name 'TvtRadioButton'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_GuiControl ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4C43D64C0168' '4C43D64C0168.ms.model.script' // Buttons
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4F69BC9C014A' '48C78D5402A6.ms.model.script' // TRadioButton
 WL 'ME_5179415C0005' '5179415C0005.ms.model.script' // vtUnicodeButtonControl
 )
 ; // Inherits
 UP "finished" false
 UP intf.pas:Path 'common\components\gui\Garant\VT\NOT_FINISHED_vtRadioButton.pas'
 UP extprop:rc:SelfName 'RadioButton'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'vtRadioButton'

ENDME // ME_517941E500BF TvtRadioButton
