// pop_control_ScrollInfo 51793AE70134 ScriptKeyword Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_51793AE70134

MEREF ME_51793A950073_ME_51793AE70134_impl
 MELINK Original WL 'ME_51793A950073' '517939B9033C.ms.model.script' // DoScrollInfo
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_51793A950073_ME_51793AE70134_impl DoScrollInfo

MEREF ME_517939B9033C_ME_51793AE70134_G
 MELINK Original WL? 'ME_517939B9033C' // TkwScrollInfoWord
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_517939B9033C_ME_51793AE70134_G TkwScrollInfoWord

%%InheritedBy ME_517939B9033C ME_51793AE70134

ME ME_51793AE70134
 MEPROP UID '51793AE70134'
 MEPROP Name 'pop_control_ScrollInfo'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_ScriptKeyword ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL? 'ME_54F5C36C00BE' // ScrollInfoProcessing
 ;
 MELIST Inherits
   Seq: ( ME_517939B9033C_ME_51793AE70134_G // TkwScrollInfoWord
 )
 ; // Inherits
 MELIST Implemented
   Seq: ( ME_51793A950073_ME_51793AE70134_impl // DoScrollInfo
 )
 ; // Implemented
 UP intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\kwPopControlScrollInfo.pas'
 UP extprop:pas:TypeName 'TkwPopControlScrollInfo'
 UP extprop:rc:SelfName 'PopControlScrollInfo'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'kwPopControlScrollInfo'

ENDME // ME_51793AE70134 pop_control_ScrollInfo
