// K453151648 5187509D034E TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4C971C2203DD_ME_5187509D034E_G
 MELINK Original WL? 'ME_4C971C2203DD' // RTFtoEVDWriterTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4C971C2203DD_ME_5187509D034E_G RTFtoEVDWriterTest

%%InheritedBy ME_4C971C2203DD ME_5187509D034E

ME ME_5187509D034E
 MEPROP UID '5187509D034E'
 MEPROP Name 'K453151648'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:453151648}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4F86C70700BD' // 7.8
 ;
 MELIST Inherits
   Seq: ( ME_4C971C2203DD_ME_5187509D034E_G // RTFtoEVDWriterTest
 )
 ; // Inherits
 UP intf.pas:Path 'common\components\rtl\Garant\Daily\K453151648.pas'
 UP extprop:pas:TypeName 'TK453151648'
 UP extprop:rc:SelfName 'K453151648'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_5187509D034E K453151648
