// RTFtypes 518A1E9F0274 UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274
%%Inner ME_518A1E9F0274

FORWARD ME_518A1E9F0274

FORWARD ME_518A5AF901D5

ME ME_518A5B3803D3
 MEPROP UID '518A5B3803D3'
 MEPROP Name 'rtfTwip'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_518A5AF901D5 // TddMainConst
 ;
 MEPROP Value 1440
 UP "AutoInc" false
 UP "forced type" 'none'
 UP "is define" false
 UP extprop:pas:Value 1440

ENDME // ME_518A5B3803D3 rtfTwip

ME ME_518A5AF901D5
 MEPROP UID '518A5AF901D5'
 MEPROP Name 'TddMainConst'
 MEPROP Class class_Class
 MELINK Stereotype st_Constants ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_518A5B3803D3 // rtfTwip
 )
 ; // Attributes
 UP "spell names" false

ENDME // ME_518A5AF901D5 TddMainConst

ME ME_519C847400D0
 MEPROP UID '519C847400D0'
 MEPROP Name 'TddBorderRules'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_519C847400D0 TddBorderRules

FORWARD ME_51D2875E00C0

ME ME_51D287B00347
 MEPROP UID '51D287B00347'
 MEPROP Name 'propNone'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D287B00347 propNone

ME ME_51D287CF01F7
 MEPROP UID '51D287CF01F7'
 MEPROP Name 'propChp'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D287CF01F7 propChp

ME ME_51D287D70098
 MEPROP UID '51D287D70098'
 MEPROP Name 'propPap'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D287D70098 propPap

ME ME_51D287DF00E7
 MEPROP UID '51D287DF00E7'
 MEPROP Name 'propSep'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D287DF00E7 propSep

ME ME_51D287E700FE
 MEPROP UID '51D287E700FE'
 MEPROP Name 'propDop'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D287E700FE propDop

ME ME_51D287F10300
 MEPROP UID '51D287F10300'
 MEPROP Name 'propStyle'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D287F10300 propStyle

ME ME_51D287F90358
 MEPROP UID '51D287F90358'
 MEPROP Name 'propRow'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D287F90358 propRow

ME ME_51D287FD02CF
 MEPROP UID '51D287FD02CF'
 MEPROP Name 'propCell'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D287FD02CF propCell

ME ME_51D2880700C7
 MEPROP UID '51D2880700C7'
 MEPROP Name 'propFrame'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D2880700C7 propFrame

ME ME_51D28810025F
 MEPROP UID '51D28810025F'
 MEPROP Name 'propFont'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D28810025F propFont

ME ME_51D2881B00B7
 MEPROP UID '51D2881B00B7'
 MEPROP Name 'propTAB'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D2881B00B7 propTAB

ME ME_51D288240150
 MEPROP UID '51D288240150'
 MEPROP Name 'propPict'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D288240150 propPict

ME ME_51D2882C0385
 MEPROP UID '51D2882C0385'
 MEPROP Name 'propFormField'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D2882C0385 propFormField

ME ME_51D2883500B8
 MEPROP UID '51D2883500B8'
 MEPROP Name 'propLevel'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D2883500B8 propLevel

ME ME_51D2883E0356
 MEPROP UID '51D2883E0356'
 MEPROP Name 'propList'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D2883E0356 propList

ME ME_51D288480216
 MEPROP UID '51D288480216'
 MEPROP Name 'propColorTable'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D2875E00C0 // TPropType
 ;

ENDME // ME_51D288480216 propColorTable

ME ME_51D2875E00C0
 MEPROP UID '51D2875E00C0'
 MEPROP Name 'TPropType'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_51D287B00347 // propNone
 HWL ME_51D287CF01F7 // propChp
 HWL ME_51D287D70098 // propPap
 HWL ME_51D287DF00E7 // propSep
 HWL ME_51D287E700FE // propDop
 HWL ME_51D287F10300 // propStyle
 HWL ME_51D287F90358 // propRow
 HWL ME_51D287FD02CF // propCell
 HWL ME_51D2880700C7 // propFrame
 HWL ME_51D28810025F // propFont
 HWL ME_51D2881B00B7 // propTAB
 HWL ME_51D288240150 // propPict
 HWL ME_51D2882C0385 // propFormField
 HWL ME_51D2883500B8 // propLevel
 HWL ME_51D2883E0356 // propList
 HWL ME_51D288480216 // propColorTable
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_51D2875E00C0 TPropType

MEREF ME_46A606AC03B2_ME_51D2877C03A1_G
 MELINK Original WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_46A606AC03B2_ME_51D2877C03A1_G Integer

%%InheritedBy ME_46A606AC03B2 ME_51D2877C03A1

ME ME_51D2877C03A1
 MEPROP UID '51D2877C03A1'
 MEPROP Name 'TIProp'
 MEPROP Class class_Class
 MELINK Stereotype st_Typedef ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Inherits
   Seq: ( ME_46A606AC03B2_ME_51D2877C03A1_G // Integer
 )
 ; // Inherits
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_51D2877C03A1 TIProp

FORWARD ME_51DBBE20023F

ME ME_54E1CBC0031A
 MEPROP UID '54E1CBC0031A'
 MEPROP Name 'rdsSkip'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CBC0031A rdsSkip

ME ME_54E1CBCA0099
 MEPROP UID '54E1CBCA0099'
 MEPROP Name 'rdsNorm'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CBCA0099 rdsNorm

ME ME_54E1CBD702C2
 MEPROP UID '54E1CBD702C2'
 MEPROP Name 'rdsFontTable'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CBD702C2 rdsFontTable

ME ME_54E1CBE00328
 MEPROP UID '54E1CBE00328'
 MEPROP Name 'rdsStyleSheet'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CBE00328 rdsStyleSheet

ME ME_54E1CBE90206
 MEPROP UID '54E1CBE90206'
 MEPROP Name 'rdsColorTable'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CBE90206 rdsColorTable

ME ME_54E1CBF301C7
 MEPROP UID '54E1CBF301C7'
 MEPROP Name 'rdsFalt'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CBF301C7 rdsFalt

ME ME_54E1CBFE0227
 MEPROP UID '54E1CBFE0227'
 MEPROP Name 'rdsHeader'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CBFE0227 rdsHeader

ME ME_54E1CC080197
 MEPROP UID '54E1CC080197'
 MEPROP Name 'rdsFooter'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC080197 rdsFooter

ME ME_54E1CC110036
 MEPROP UID '54E1CC110036'
 MEPROP Name 'rdsFName'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC110036 rdsFName

ME ME_54E1CC1B0033
 MEPROP UID '54E1CC1B0033'
 MEPROP Name 'rdsFootnote'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC1B0033 rdsFootnote

ME ME_54E1CC2501A3
 MEPROP UID '54E1CC2501A3'
 MEPROP Name 'rdsPicture'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC2501A3 rdsPicture

ME ME_54E1CC310242
 MEPROP UID '54E1CC310242'
 MEPROP Name 'rdsPanose'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC310242 rdsPanose

ME ME_54E1CC3B0058
 MEPROP UID '54E1CC3B0058'
 MEPROP Name 'rdsPictureProp'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC3B0058 rdsPictureProp

ME ME_54E1CC4A0028
 MEPROP UID '54E1CC4A0028'
 MEPROP Name 'rdsField'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC4A0028 rdsField

ME ME_54E1CC55012F
 MEPROP UID '54E1CC55012F'
 MEPROP Name 'rdsFieldInstruction'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC55012F rdsFieldInstruction

ME ME_54E1CC620117
 MEPROP UID '54E1CC620117'
 MEPROP Name 'rdsFieldResult'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC620117 rdsFieldResult

ME ME_54E1CC6B02D2
 MEPROP UID '54E1CC6B02D2'
 MEPROP Name 'rdsFormField'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC6B02D2 rdsFormField

ME ME_54E1CC74034D
 MEPROP UID '54E1CC74034D'
 MEPROP Name 'rdsFormFieldItem'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC74034D rdsFormFieldItem

ME ME_54E1CC800350
 MEPROP UID '54E1CC800350'
 MEPROP Name 'rdsInfo'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC800350 rdsInfo

ME ME_54E1CC8A01F3
 MEPROP UID '54E1CC8A01F3'
 MEPROP Name 'rdsTitle'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC8A01F3 rdsTitle

ME ME_54E1CC94021C
 MEPROP UID '54E1CC94021C'
 MEPROP Name 'rdsAuthor'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC94021C rdsAuthor

ME ME_54E1CC9D0345
 MEPROP UID '54E1CC9D0345'
 MEPROP Name 'rdsOperator'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CC9D0345 rdsOperator

ME ME_54E1CCA70274
 MEPROP UID '54E1CCA70274'
 MEPROP Name 'rdsCreaTim'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CCA70274 rdsCreaTim

ME ME_54E1CCBC01E2
 MEPROP UID '54E1CCBC01E2'
 MEPROP Name 'rdsRevTim'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CCBC01E2 rdsRevTim

ME ME_54E1CCFA01FE
 MEPROP UID '54E1CCFA01FE'
 MEPROP Name 'rdsCompany'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CCFA01FE rdsCompany

ME ME_54E1CD0A001A
 MEPROP UID '54E1CD0A001A'
 MEPROP Name 'rdsUpr'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD0A001A rdsUpr

ME ME_54E1CD13017D
 MEPROP UID '54E1CD13017D'
 MEPROP Name 'rdsParaNum'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD13017D rdsParaNum

ME ME_54E1CD1D02F0
 MEPROP UID '54E1CD1D02F0'
 MEPROP Name 'rdsAnnotation'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD1D02F0 rdsAnnotation

ME ME_54E1CD2800D8
 MEPROP UID '54E1CD2800D8'
 MEPROP Name 'rdsNone'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD2800D8 rdsNone

ME ME_54E1CD3200B6
 MEPROP UID '54E1CD3200B6'
 MEPROP Name 'rdsListText'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD3200B6 rdsListText

ME ME_54E1CD3D03AD
 MEPROP UID '54E1CD3D03AD'
 MEPROP Name 'rdsBookmarkStart'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD3D03AD rdsBookmarkStart

ME ME_54E1CD47033A
 MEPROP UID '54E1CD47033A'
 MEPROP Name 'rdsBookmarkEnd'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD47033A rdsBookmarkEnd

ME ME_54E1CD510172
 MEPROP UID '54E1CD510172'
 MEPROP Name 'rdsParaNumbered'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD510172 rdsParaNumbered

ME ME_54E1CD5B01AD
 MEPROP UID '54E1CD5B01AD'
 MEPROP Name 'rdsSkipGroup'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD5B01AD rdsSkipGroup

ME ME_54E1CD6501C9
 MEPROP UID '54E1CD6501C9'
 MEPROP Name 'rdsShp'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD6501C9 rdsShp

ME ME_54E1CD730120
 MEPROP UID '54E1CD730120'
 MEPROP Name 'rdsShpInst'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD730120 rdsShpInst

ME ME_54E1CD7D02DE
 MEPROP UID '54E1CD7D02DE'
 MEPROP Name 'rdsShpRslt'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD7D02DE rdsShpRslt

ME ME_54E1CD8700D5
 MEPROP UID '54E1CD8700D5'
 MEPROP Name 'rdsShpTxt'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD8700D5 rdsShpTxt

ME ME_54E1CD9002B4
 MEPROP UID '54E1CD9002B4'
 MEPROP Name 'rdsListTable'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD9002B4 rdsListTable

ME ME_54E1CD9C020F
 MEPROP UID '54E1CD9C020F'
 MEPROP Name 'rdsListLevel'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CD9C020F rdsListLevel

ME ME_54E1CDA601AE
 MEPROP UID '54E1CDA601AE'
 MEPROP Name 'rdsLevelText'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CDA601AE rdsLevelText

ME ME_54E1CDB1010D
 MEPROP UID '54E1CDB1010D'
 MEPROP Name 'rdsList'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CDB1010D rdsList

ME ME_54E1CDBA0221
 MEPROP UID '54E1CDBA0221'
 MEPROP Name 'rdslistoverride'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CDBA0221 rdslistoverride

ME ME_54E1CDC303E4
 MEPROP UID '54E1CDC303E4'
 MEPROP Name 'rdslistoverridetable'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CDC303E4 rdslistoverridetable

ME ME_54E1CDCD025B
 MEPROP UID '54E1CDCD025B'
 MEPROP Name 'rdslistpicture'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CDCD025B rdslistpicture

ME ME_54E1CDD701D8
 MEPROP UID '54E1CDD701D8'
 MEPROP Name 'rdsliststylename'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CDD701D8 rdsliststylename

ME ME_54E1CDE0037B
 MEPROP UID '54E1CDE0037B'
 MEPROP Name 'rdsListName'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CDE0037B rdsListName

ME ME_54E1CDEA03A4
 MEPROP UID '54E1CDEA03A4'
 MEPROP Name 'rdsLevelNumbers'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CDEA03A4 rdsLevelNumbers

ME ME_54E1CDF3028B
 MEPROP UID '54E1CDF3028B'
 MEPROP Name 'rdsOldParaNumbering'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51DBBE20023F // TRDS
 ;

ENDME // ME_54E1CDF3028B rdsOldParaNumbering

ME ME_51DBBE20023F
 MEPROP UID '51DBBE20023F'
 MEPROP Name 'TRDS'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_54E1CBC0031A // rdsSkip
 HWL ME_54E1CBCA0099 // rdsNorm
 HWL ME_54E1CBD702C2 // rdsFontTable
 HWL ME_54E1CBE00328 // rdsStyleSheet
 HWL ME_54E1CBE90206 // rdsColorTable
 HWL ME_54E1CBF301C7 // rdsFalt
 HWL ME_54E1CBFE0227 // rdsHeader
 HWL ME_54E1CC080197 // rdsFooter
 HWL ME_54E1CC110036 // rdsFName
 HWL ME_54E1CC1B0033 // rdsFootnote
 HWL ME_54E1CC2501A3 // rdsPicture
 HWL ME_54E1CC310242 // rdsPanose
 HWL ME_54E1CC3B0058 // rdsPictureProp
 HWL ME_54E1CC4A0028 // rdsField
 HWL ME_54E1CC55012F // rdsFieldInstruction
 HWL ME_54E1CC620117 // rdsFieldResult
 HWL ME_54E1CC6B02D2 // rdsFormField
 HWL ME_54E1CC74034D // rdsFormFieldItem
 HWL ME_54E1CC800350 // rdsInfo
 HWL ME_54E1CC8A01F3 // rdsTitle
 HWL ME_54E1CC94021C // rdsAuthor
 HWL ME_54E1CC9D0345 // rdsOperator
 HWL ME_54E1CCA70274 // rdsCreaTim
 HWL ME_54E1CCBC01E2 // rdsRevTim
 HWL ME_54E1CCFA01FE // rdsCompany
 HWL ME_54E1CD0A001A // rdsUpr
 HWL ME_54E1CD13017D // rdsParaNum
 HWL ME_54E1CD1D02F0 // rdsAnnotation
 HWL ME_54E1CD2800D8 // rdsNone
 HWL ME_54E1CD3200B6 // rdsListText
 HWL ME_54E1CD3D03AD // rdsBookmarkStart
 HWL ME_54E1CD47033A // rdsBookmarkEnd
 HWL ME_54E1CD510172 // rdsParaNumbered
 HWL ME_54E1CD5B01AD // rdsSkipGroup
 HWL ME_54E1CD6501C9 // rdsShp
 HWL ME_54E1CD730120 // rdsShpInst
 HWL ME_54E1CD7D02DE // rdsShpRslt
 HWL ME_54E1CD8700D5 // rdsShpTxt
 HWL ME_54E1CD9002B4 // rdsListTable
 HWL ME_54E1CD9C020F // rdsListLevel
 HWL ME_54E1CDA601AE // rdsLevelText
 HWL ME_54E1CDB1010D // rdsList
 HWL ME_54E1CDBA0221 // rdslistoverride
 HWL ME_54E1CDC303E4 // rdslistoverridetable
 HWL ME_54E1CDCD025B // rdslistpicture
 HWL ME_54E1CDD701D8 // rdsliststylename
 HWL ME_54E1CDE0037B // rdsListName
 HWL ME_54E1CDEA03A4 // rdsLevelNumbers
 HWL ME_54E1CDF3028B // rdsOldParaNumbering
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_51DBBE20023F TRDS

FORWARD ME_51E8F60B00B1

ME ME_51E8F619014A
 MEPROP UID '51E8F619014A'
 MEPROP Name 'breakPage'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51E8F60B00B1 // TddBreakType
 ;

ENDME // ME_51E8F619014A breakPage

ME ME_51E8F6230284
 MEPROP UID '51E8F6230284'
 MEPROP Name 'breakColumn'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51E8F60B00B1 // TddBreakType
 ;

ENDME // ME_51E8F6230284 breakColumn

ME ME_51E8F629029A
 MEPROP UID '51E8F629029A'
 MEPROP Name 'breakSection'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51E8F60B00B1 // TddBreakType
 ;

ENDME // ME_51E8F629029A breakSection

ME ME_51E8F60B00B1
 MEPROP UID '51E8F60B00B1'
 MEPROP Name 'TddBreakType'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_51E8F619014A // breakPage
 HWL ME_51E8F6230284 // breakColumn
 HWL ME_51E8F629029A // breakSection
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_51E8F60B00B1 TddBreakType

ME ME_525E2DF80180
 MEPROP UID '525E2DF80180'
 MEPROP Name 'TddBorderType'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_525E2DF80180 TddBorderType

FORWARD ME_5111FE6903A1

ME ME_5111FF7D01E7
 MEPROP UID '5111FF7D01E7'
 MEPROP Name 'bpTop'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5111FE6903A1 // TddBorderParts
 ;

ENDME // ME_5111FF7D01E7 bpTop

ME ME_5111FF8B01F8
 MEPROP UID '5111FF8B01F8'
 MEPROP Name 'bpLeft'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5111FE6903A1 // TddBorderParts
 ;

ENDME // ME_5111FF8B01F8 bpLeft

ME ME_5111FF9A039D
 MEPROP UID '5111FF9A039D'
 MEPROP Name 'bpBottom'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5111FE6903A1 // TddBorderParts
 ;

ENDME // ME_5111FF9A039D bpBottom

ME ME_5111FFA202B0
 MEPROP UID '5111FFA202B0'
 MEPROP Name 'bpRight'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5111FE6903A1 // TddBorderParts
 ;

ENDME // ME_5111FFA202B0 bpRight

ME ME_5111FFA703A9
 MEPROP UID '5111FFA703A9'
 MEPROP Name 'bpHorizontal'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5111FE6903A1 // TddBorderParts
 ;

ENDME // ME_5111FFA703A9 bpHorizontal

ME ME_5111FFB30365
 MEPROP UID '5111FFB30365'
 MEPROP Name 'bpVertical'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5111FE6903A1 // TddBorderParts
 ;

ENDME // ME_5111FFB30365 bpVertical

ME ME_5111FFBD02CB
 MEPROP UID '5111FFBD02CB'
 MEPROP Name 'bpBox'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5111FE6903A1 // TddBorderParts
 ;

ENDME // ME_5111FFBD02CB bpBox

ME ME_5111FE6903A1
 MEPROP UID '5111FE6903A1'
 MEPROP Name 'TddBorderParts'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_5111FF7D01E7 // bpTop
 HWL ME_5111FF8B01F8 // bpLeft
 HWL ME_5111FF9A039D // bpBottom
 HWL ME_5111FFA202B0 // bpRight
 HWL ME_5111FFA703A9 // bpHorizontal
 HWL ME_5111FFB30365 // bpVertical
 HWL ME_5111FFBD02CB // bpBox
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_5111FE6903A1 TddBorderParts

FORWARD ME_52CFD74F0382

ME ME_52CFD75D0168
 MEPROP UID '52CFD75D0168'
 MEPROP Name 'rtfANSI'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFD74F0382 // TrtfCharacterSet
 ;

ENDME // ME_52CFD75D0168 rtfANSI

ME ME_52CFD7660163
 MEPROP UID '52CFD7660163'
 MEPROP Name 'rtfMac'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFD74F0382 // TrtfCharacterSet
 ;

ENDME // ME_52CFD7660163 rtfMac

ME ME_52CFD770002A
 MEPROP UID '52CFD770002A'
 MEPROP Name 'rtfPC'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFD74F0382 // TrtfCharacterSet
 ;

ENDME // ME_52CFD770002A rtfPC

ME ME_52CFD779036B
 MEPROP UID '52CFD779036B'
 MEPROP Name 'rtfPCA'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFD74F0382 // TrtfCharacterSet
 ;

ENDME // ME_52CFD779036B rtfPCA

ME ME_52CFD74F0382
 MEPROP UID '52CFD74F0382'
 MEPROP Name 'TrtfCharacterSet'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_52CFD75D0168 // rtfANSI
 HWL ME_52CFD7660163 // rtfMac
 HWL ME_52CFD770002A // rtfPC
 HWL ME_52CFD779036B // rtfPCA
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_52CFD74F0382 TrtfCharacterSet

FORWARD ME_52CFDC5B032E

ME ME_52CFDC690091
 MEPROP UID '52CFDC690091'
 MEPROP Name 'pgDec'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFDC5B032E // TPGN
 ;

ENDME // ME_52CFDC690091 pgDec

ME ME_52CFDC710233
 MEPROP UID '52CFDC710233'
 MEPROP Name 'pgURom'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFDC5B032E // TPGN
 ;

ENDME // ME_52CFDC710233 pgURom

ME ME_52CFDC7B019F
 MEPROP UID '52CFDC7B019F'
 MEPROP Name 'pgLRom'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFDC5B032E // TPGN
 ;

ENDME // ME_52CFDC7B019F pgLRom

ME ME_52CFDC920220
 MEPROP UID '52CFDC920220'
 MEPROP Name 'pgULtr'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFDC5B032E // TPGN
 ;

ENDME // ME_52CFDC920220 pgULtr

ME ME_52CFDC9D013B
 MEPROP UID '52CFDC9D013B'
 MEPROP Name 'pgLLtr'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFDC5B032E // TPGN
 ;

ENDME // ME_52CFDC9D013B pgLLtr

ME ME_52CFDCB70012
 MEPROP UID '52CFDCB70012'
 MEPROP Name 'pgNotDefined'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFDC5B032E // TPGN
 ;

ENDME // ME_52CFDCB70012 pgNotDefined

ME ME_52CFDC5B032E
 MEPROP UID '52CFDC5B032E'
 MEPROP Name 'TPGN'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_52CFDC690091 // pgDec
 HWL ME_52CFDC710233 // pgURom
 HWL ME_52CFDC7B019F // pgLRom
 HWL ME_52CFDC920220 // pgULtr
 HWL ME_52CFDC9D013B // pgLLtr
 HWL ME_52CFDCB70012 // pgNotDefined
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_52CFDC5B032E TPGN

FORWARD ME_52CFDD0D0175

ME ME_52CFDD1503A6
 MEPROP UID '52CFDD1503A6'
 MEPROP Name 'sbkNon'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFDD0D0175 // TSBK
 ;

ENDME // ME_52CFDD1503A6 sbkNon

ME ME_52CFDD22033F
 MEPROP UID '52CFDD22033F'
 MEPROP Name 'sbkCol'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFDD0D0175 // TSBK
 ;

ENDME // ME_52CFDD22033F sbkCol

ME ME_52CFDD2C0245
 MEPROP UID '52CFDD2C0245'
 MEPROP Name 'sbkEvn'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFDD0D0175 // TSBK
 ;

ENDME // ME_52CFDD2C0245 sbkEvn

ME ME_52CFDD3701F9
 MEPROP UID '52CFDD3701F9'
 MEPROP Name 'sbkOdd'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFDD0D0175 // TSBK
 ;

ENDME // ME_52CFDD3701F9 sbkOdd

ME ME_52CFDD43001B
 MEPROP UID '52CFDD43001B'
 MEPROP Name 'sbkPg'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFDD0D0175 // TSBK
 ;

ENDME // ME_52CFDD43001B sbkPg

ME ME_52CFDD4E014B
 MEPROP UID '52CFDD4E014B'
 MEPROP Name 'sbkNotDefined'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52CFDD0D0175 // TSBK
 ;

ENDME // ME_52CFDD4E014B sbkNotDefined

ME ME_52CFDD0D0175
 MEPROP UID '52CFDD0D0175'
 MEPROP Name 'TSBK'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_52CFDD1503A6 // sbkNon
 HWL ME_52CFDD22033F // sbkCol
 HWL ME_52CFDD2C0245 // sbkEvn
 HWL ME_52CFDD3701F9 // sbkOdd
 HWL ME_52CFDD43001B // sbkPg
 HWL ME_52CFDD4E014B // sbkNotDefined
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_52CFDD0D0175 TSBK

FORWARD ME_52DCEA5E00C3

ME ME_52DCEA6C00EB
 MEPROP UID '52DCEA6C00EB'
 MEPROP Name 'sdParagraph'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52DCEA5E00C3 // TddStyleDef
 ;

ENDME // ME_52DCEA6C00EB sdParagraph

ME ME_52DCEA740216
 MEPROP UID '52DCEA740216'
 MEPROP Name 'sdCharacter'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52DCEA5E00C3 // TddStyleDef
 ;

ENDME // ME_52DCEA740216 sdCharacter

ME ME_52DCEA84025B
 MEPROP UID '52DCEA84025B'
 MEPROP Name 'sdSection'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_52DCEA5E00C3 // TddStyleDef
 ;

ENDME // ME_52DCEA84025B sdSection

ME ME_52DCEA5E00C3
 MEPROP UID '52DCEA5E00C3'
 MEPROP Name 'TddStyleDef'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_52DCEA6C00EB // sdParagraph
 HWL ME_52DCEA740216 // sdCharacter
 HWL ME_52DCEA84025B // sdSection
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_52DCEA5E00C3 TddStyleDef

FORWARD ME_54DC81490397

ME ME_54DC81630100
 MEPROP UID '54DC81630100'
 MEPROP Name 'cpNone'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC81490397 // TCharPosition
 ;

ENDME // ME_54DC81630100 cpNone

ME ME_54DC816C019E
 MEPROP UID '54DC816C019E'
 MEPROP Name 'cpSuperScript'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC81490397 // TCharPosition
 ;

ENDME // ME_54DC816C019E cpSuperScript

ME ME_54DC81750079
 MEPROP UID '54DC81750079'
 MEPROP Name 'cpSubScript'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC81490397 // TCharPosition
 ;

ENDME // ME_54DC81750079 cpSubScript

ME ME_54DC817E00C8
 MEPROP UID '54DC817E00C8'
 MEPROP Name 'cpNotDefined'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC81490397 // TCharPosition
 ;

ENDME // ME_54DC817E00C8 cpNotDefined

ME ME_54DC81490397
 MEPROP UID '54DC81490397'
 MEPROP Name 'TCharPosition'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_54DC81630100 // cpNone
 HWL ME_54DC816C019E // cpSuperScript
 HWL ME_54DC81750079 // cpSubScript
 HWL ME_54DC817E00C8 // cpNotDefined
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_54DC81490397 TCharPosition

FORWARD ME_54DC825B02C2

ME ME_54DC8265011B
 MEPROP UID '54DC8265011B'
 MEPROP Name 'utNone'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC825B02C2 // TUnderline
 ;

ENDME // ME_54DC8265011B utNone

ME ME_54DC826F0287
 MEPROP UID '54DC826F0287'
 MEPROP Name 'utThick'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC825B02C2 // TUnderline
 ;

ENDME // ME_54DC826F0287 utThick

ME ME_54DC82790056
 MEPROP UID '54DC82790056'
 MEPROP Name 'utDotted'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC825B02C2 // TUnderline
 ;

ENDME // ME_54DC82790056 utDotted

ME ME_54DC82810310
 MEPROP UID '54DC82810310'
 MEPROP Name 'utDash'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC825B02C2 // TUnderline
 ;

ENDME // ME_54DC82810310 utDash

ME ME_54DC828C037F
 MEPROP UID '54DC828C037F'
 MEPROP Name 'utDotDash'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC825B02C2 // TUnderline
 ;

ENDME // ME_54DC828C037F utDotDash

ME ME_54DC82980225
 MEPROP UID '54DC82980225'
 MEPROP Name 'utDotDotDash'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC825B02C2 // TUnderline
 ;

ENDME // ME_54DC82980225 utDotDotDash

ME ME_54DC82A20030
 MEPROP UID '54DC82A20030'
 MEPROP Name 'utDouble'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC825B02C2 // TUnderline
 ;

ENDME // ME_54DC82A20030 utDouble

ME ME_54DC82AB0008
 MEPROP UID '54DC82AB0008'
 MEPROP Name 'utWord'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC825B02C2 // TUnderline
 ;

ENDME // ME_54DC82AB0008 utWord

ME ME_54DC82B30380
 MEPROP UID '54DC82B30380'
 MEPROP Name 'utWave'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC825B02C2 // TUnderline
 ;

ENDME // ME_54DC82B30380 utWave

ME ME_54DC82BF037E
 MEPROP UID '54DC82BF037E'
 MEPROP Name 'utNotDefined'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54DC825B02C2 // TUnderline
 ;

ENDME // ME_54DC82BF037E utNotDefined

ME ME_54DC825B02C2
 MEPROP UID '54DC825B02C2'
 MEPROP Name 'TUnderline'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_54DC8265011B // utNone
 HWL ME_54DC826F0287 // utThick
 HWL ME_54DC82790056 // utDotted
 HWL ME_54DC82810310 // utDash
 HWL ME_54DC828C037F // utDotDash
 HWL ME_54DC82980225 // utDotDotDash
 HWL ME_54DC82A20030 // utDouble
 HWL ME_54DC82AB0008 // utWord
 HWL ME_54DC82B30380 // utWave
 HWL ME_54DC82BF037E // utNotDefined
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_54DC825B02C2 TUnderline

FORWARD ME_54E191970286

ME ME_54E191A70136
 MEPROP UID '54E191A70136'
 MEPROP Name 'ffNil'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E191970286 // TFontFamily
 ;

ENDME // ME_54E191A70136 ffNil

ME ME_54E191B101AE
 MEPROP UID '54E191B101AE'
 MEPROP Name 'ffRoman'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E191970286 // TFontFamily
 ;

ENDME // ME_54E191B101AE ffRoman

ME ME_54E191B90162
 MEPROP UID '54E191B90162'
 MEPROP Name 'ffSwiss'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E191970286 // TFontFamily
 ;

ENDME // ME_54E191B90162 ffSwiss

ME ME_54E191C300EA
 MEPROP UID '54E191C300EA'
 MEPROP Name 'ffModern'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E191970286 // TFontFamily
 ;

ENDME // ME_54E191C300EA ffModern

ME ME_54E191DD02F5
 MEPROP UID '54E191DD02F5'
 MEPROP Name 'ffScript'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E191970286 // TFontFamily
 ;

ENDME // ME_54E191DD02F5 ffScript

ME ME_54E191E70178
 MEPROP UID '54E191E70178'
 MEPROP Name 'ffDecor'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E191970286 // TFontFamily
 ;

ENDME // ME_54E191E70178 ffDecor

ME ME_54E191F20162
 MEPROP UID '54E191F20162'
 MEPROP Name 'ffTech'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E191970286 // TFontFamily
 ;

ENDME // ME_54E191F20162 ffTech

ME ME_54E191FD006A
 MEPROP UID '54E191FD006A'
 MEPROP Name 'ffBidi'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E191970286 // TFontFamily
 ;

ENDME // ME_54E191FD006A ffBidi

ME ME_54E1920D01DD
 MEPROP UID '54E1920D01DD'
 MEPROP Name 'ffNotDefined'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E191970286 // TFontFamily
 ;

ENDME // ME_54E1920D01DD ffNotDefined

ME ME_54E191970286
 MEPROP UID '54E191970286'
 MEPROP Name 'TFontFamily'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_54E191A70136 // ffNil
 HWL ME_54E191B101AE // ffRoman
 HWL ME_54E191B90162 // ffSwiss
 HWL ME_54E191C300EA // ffModern
 HWL ME_54E191DD02F5 // ffScript
 HWL ME_54E191E70178 // ffDecor
 HWL ME_54E191F20162 // ffTech
 HWL ME_54E191FD006A // ffBidi
 HWL ME_54E1920D01DD // ffNotDefined
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_54E191970286 TFontFamily

FORWARD ME_54E1921C028C

ME ME_54E1922502AD
 MEPROP UID '54E1922502AD'
 MEPROP Name 'ftNil'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E1921C028C // TFontType
 ;

ENDME // ME_54E1922502AD ftNil

ME ME_54E1923003CF
 MEPROP UID '54E1923003CF'
 MEPROP Name 'ftTrueType'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E1921C028C // TFontType
 ;

ENDME // ME_54E1923003CF ftTrueType

ME ME_54E19245039C
 MEPROP UID '54E19245039C'
 MEPROP Name 'ftNotDefined'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E1921C028C // TFontType
 ;

ENDME // ME_54E19245039C ftNotDefined

ME ME_54E1921C028C
 MEPROP UID '54E1921C028C'
 MEPROP Name 'TFontType'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_54E1922502AD // ftNil
 HWL ME_54E1923003CF // ftTrueType
 HWL ME_54E19245039C // ftNotDefined
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_54E1921C028C TFontType

FORWARD ME_54E32E0F0359

ME ME_54E32E1A0303
 MEPROP UID '54E32E1A0303'
 MEPROP Name 'rtf_psNo'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E32E0F0359 // TRTFPictureSkip
 ;

ENDME // ME_54E32E1A0303 rtf_psNo

ME ME_54E32E2300F4
 MEPROP UID '54E32E2300F4'
 MEPROP Name 'rtf_psYes'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E32E0F0359 // TRTFPictureSkip
 ;

ENDME // ME_54E32E2300F4 rtf_psYes

ME ME_54E32E2C0167
 MEPROP UID '54E32E2C0167'
 MEPROP Name 'rtf_psWMF'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E32E0F0359 // TRTFPictureSkip
 ;

ENDME // ME_54E32E2C0167 rtf_psWMF

ME ME_54E32E0F0359
 MEPROP UID '54E32E0F0359'
 MEPROP Name 'TRTFPictureSkip'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_54E32E1A0303 // rtf_psNo
 HWL ME_54E32E2300F4 // rtf_psYes
 HWL ME_54E32E2C0167 // rtf_psWMF
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_54E32E0F0359 TRTFPictureSkip

FORWARD ME_51D277A60012

ME ME_51D277AC0049
 MEPROP UID '51D277AC0049'
 MEPROP Name 'dd_fieldUnknown'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D277A60012 // TddFieldType
 ;

ENDME // ME_51D277AC0049 dd_fieldUnknown

ME ME_51D277B7002A
 MEPROP UID '51D277B7002A'
 MEPROP Name 'dd_fieldHyperlink'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D277A60012 // TddFieldType
 ;

ENDME // ME_51D277B7002A dd_fieldHyperlink

ME ME_51D277C100AF
 MEPROP UID '51D277C100AF'
 MEPROP Name 'dd_fieldSymbol'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D277A60012 // TddFieldType
 ;

ENDME // ME_51D277C100AF dd_fieldSymbol

ME ME_51D277CA03A0
 MEPROP UID '51D277CA03A0'
 MEPROP Name 'dd_fieldForm'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D277A60012 // TddFieldType
 ;

ENDME // ME_51D277CA03A0 dd_fieldForm

ME ME_52BC3E690231
 MEPROP UID '52BC3E690231'
 MEPROP Name 'dd_fieldHyperlinkMailTo'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D277A60012 // TddFieldType
 ;

ENDME // ME_52BC3E690231 dd_fieldHyperlinkMailTo

ME ME_546088980390
 MEPROP UID '546088980390'
 MEPROP Name 'dd_fieldPAGE'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_51D277A60012 // TddFieldType
 ;

ENDME // ME_546088980390 dd_fieldPAGE

ME ME_51D277A60012
 MEPROP UID '51D277A60012'
 MEPROP Name 'TddFieldType'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_518A1E9F0274 // RTFtypes
 ;
 MELIST Attributes
   Seq: ( HWL ME_51D277AC0049 // dd_fieldUnknown
 HWL ME_51D277B7002A // dd_fieldHyperlink
 HWL ME_51D277C100AF // dd_fieldSymbol
 HWL ME_51D277CA03A0 // dd_fieldForm
 HWL ME_52BC3E690231 // dd_fieldHyperlinkMailTo
 HWL ME_546088980390 // dd_fieldPAGE
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_51D277A60012 TddFieldType

ME ME_518A1E9F0274
 MEPROP UID '518A1E9F0274'
 MEPROP Name 'RTFtypes'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_UtilityPack ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL? 'ME_4F6843C101D1' // ddCommon
 ;
 MELIST Children
   Seq: ( HWL ME_519C847400D0 // TddBorderRules
 HWL ME_51D2875E00C0 // TPropType
 HWL ME_51D2877C03A1 // TIProp
 HWL ME_51DBBE20023F // TRDS
 HWL ME_51E8F60B00B1 // TddBreakType
 HWL ME_525E2DF80180 // TddBorderType
 HWL ME_5111FE6903A1 // TddBorderParts
 HWL ME_52CFD74F0382 // TrtfCharacterSet
 HWL ME_52CFDC5B032E // TPGN
 HWL ME_52CFDD0D0175 // TSBK
 HWL ME_52DCEA5E00C3 // TddStyleDef
 HWL ME_54DC81490397 // TCharPosition
 HWL ME_54DC825B02C2 // TUnderline
 HWL ME_54E191970286 // TFontFamily
 HWL ME_54E1921C028C // TFontType
 HWL ME_54E32E0F0359 // TRTFPictureSkip
 HWL ME_51D277A60012 // TddFieldType
 )
 ; // Children
 MELIST Constants
   Seq: ( HWL ME_518A5AF901D5 // TddMainConst
 )
 ; // Constants
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "finished" false
 UP intf.pas:Path 'common\components\rtl\Garant\dd\NOT_FINISHED_RTFtypes.pas'

ENDME // ME_518A1E9F0274 RTFtypes
