// ImportExport 51946564017F TestTarget Category

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_51946564017F
 MEPROP UID '51946564017F'
 MEPROP Name 'ImportExport'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_TestTarget ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_51945CDA0027' // archi$ImportExprortTest
 ;
 MELIST Depends
   Seq: ( WL? 'ME_519465D90095' // ImportExportTestLibrary
 WL? 'ME_55ED4FE10372' // SimpleTests
 )
 ; // Depends
 UP "no scripts" true
 UP intf.pas:Path 'archi\source\projects\ImportExportTest\ImportExportTest.dpr'
 UP intf.pas:PathOnly '\archi\source\projects\ImportExportTest'
 UP extprop:pas:UnitName 'ImportExportTest'
 UP Version 0

ENDME // ME_51946564017F ImportExport
