// ZipForge 519C9851011D Library Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_519C9851011D

ME ME_519C9851011D
 MEPROP UID '519C9851011D'
 MEPROP Name 'ZipForge'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Library ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4677DDBD0193' // Shared Delphi
 ;
 MELIST Children
   Seq: ( WL? 'ME_519C98B002F7' // ZipForge
 )
 ; // Children
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "UseNewGen" true
 UP "exec mode" 'concluded'
 UP "gui" 'rtl'
 UP "is namespace" true
 UP "vendor" '/external'
 UP intf.pas:PathOnly '\common\components\rtl\external\ZipForge'

ENDME // ME_519C9851011D ZipForge
