// FormWithPanel 51D533840334 VCMForms Category

INCLUDE 'ElementsRTTI.ms.dict'

: ME_51D533840334
 CONST UID '51D533840334'
 CONST Name 'FormWithPanel'
 CONST Class class_Category
 : Stereotype st_VCMForms ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4B30C6E3023C' '4B30C6E3023C.pas.ms.script' // Forms
 ;
 : Children
   Seq: ( WL 'ME_51D534260378' '51D534260378.pas.ms.script' // FromWithPanel
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 WL 'ME_4799D29F033F' '4799D29F033F.pas.ms.script' // Implementation
 WL 'ME_4A7960CC03A4' '4A7960CC03A4.pas.ms.script' //  Panels
 WL 'ME_4AADF9450143' '4AADF9450143.pas.ms.script' // Visual
 )
 ; // Depends

ref; // ME_51D533840334 FormWithPanel
