// DocumentListTree 51D56E2A023C Views Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_51D56E2A023C

FORWARD ME_51D56E9F004B

FORWARD ME_51DC189502B6

: ME_51DC1957024E
 CONST Name 'anIndex'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_51DC1957024E anIndex

: ME_51DC19280230
 CONST UID '51DC19280230'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_51DC189502B6 // TdltGetNodeTypeEvent
 ;
 : Target WL 'ME_47F213990332' '47EA07FA02CE.pas.ms.script' // TbsListNodeType
 ;
 : Parameters
   Seq: ( ME_51DC1957024E // anIndex
 )
 ; // Parameters

ref; // ME_51DC19280230 DoIt

: ME_51DC189502B6
 CONST UID '51DC189502B6'
 CONST Name 'TdltGetNodeTypeEvent'
 CONST Class class_Class
 : Stereotype st_Function ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Operations
   Seq: ( ME_51DC19280230 // DoIt
 )
 ; // Operations
 CONST "of object" true

ref; // ME_51DC189502B6 TdltGetNodeTypeEvent

: ME_51DC195E0142
 CONST UID '51DC195E0142'
 CONST Name 'OnGetNodeType'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target ME_51DC189502B6 // TdltGetNodeTypeEvent
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_51DC195E0142 OnGetNodeType

FORWARD ME_51E01CC7023D

: ME_51E01CDC0243
 CONST UID '51E01CDC0243'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_51E01CC7023D // GetCurrentText
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_51E01CDC0243 DoIt

: ME_51E01CC7023D
 CONST UID '51E01CC7023D'
 CONST Name 'GetCurrentText'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Operations
   Seq: ( ME_51E01CDC0243 // DoIt
 )
 ; // Operations

ref; // ME_51E01CC7023D GetCurrentText

: ME_51E00DA20133
 CONST Name 'Msg'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_504F1A2302CE' '476F78840219.pas.ms.script' // TWMGetText
 ;

ref; // ME_51E00DA20133 Msg

: ME_51E00D2000A7
 CONST UID '51E00D2000A7'
 CONST Name 'WMGetText'
 CONST Class class_Operation
 : Stereotype st_message::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Parameters
   Seq: ( ME_51E00DA20133 // Msg
 )
 ; // Parameters
 CONST "Message ID" 'WM_GetText'

ref; // ME_51E00D2000A7 WMGetText

: ME_51E00DC1006F
 CONST Name 'Msg'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_504F1A3900B2' '476F78840219.pas.ms.script' // TWMGetTextLength
 ;

ref; // ME_51E00DC1006F Msg

: ME_51E00DAD024C
 CONST UID '51E00DAD024C'
 CONST Name 'WMGetTextLength'
 CONST Class class_Operation
 : Stereotype st_message::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Parameters
   Seq: ( ME_51E00DC1006F // Msg
 )
 ; // Parameters
 CONST "Message ID" 'WM_GETTEXTLENGTH'

ref; // ME_51E00DAD024C WMGetTextLength

: ME_51D6DA1300D6
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target WL 'ME_47D0368C0272' '47D036150077.pas.ms.script' // TvtViewOptions
 ;

ref; // ME_51D6DA1300D6 

: ME_51D6DEF0012E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target WL 'ME_468259900322' '4682595B0268.pas.ms.script' // Il3SimpleNode
 ;

ref; // ME_51D6DEF0012E 

: ME_51D7E49A0117
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target WL 'ME_47ECBD5D03BB' '476F78840219.pas.ms.script' // Msg Codes
 ;

ref; // ME_51D7E49A0117 

: ME_51DACF1201D8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target WL 'ME_48A41FF10094' '4AB0C3F60375.pas.ms.script' // Windows
 ;

ref; // ME_51DACF1201D8 

: ME_51E01C110227
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_51E01C110227 

: ME_51E029F300E5
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target WL 'ME_47878E0E0191' '54B90AC6014B.pas.ms.script' // l3String
 ;

ref; // ME_51E029F300E5 

: ME_51E53E3C035F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target WL 'ME_49F048510365' '47ECB2870309.pas.ms.script' // evStyleTableTools
 ;

ref; // ME_51E53E3C035F 

: ME_51E53FC902B3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target WL 'ME_4727456300E7' '472745450206.pas.ms.script' // Tl3Point
 ;

ref; // ME_51E53FC902B3 

: ME_51E54163036A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target WL 'ME_4799F84900DD' '473C3BEE0334.pas.ms.script' // l3ScreenIC
 ;

ref; // ME_51E54163036A 

: ME_51E5423000C7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target WL 'ME_476BE0660328' '476BE0350329.pas.ms.script' // Standard
 ;

ref; // ME_51E5423000C7 

: ME_51EEBD820221
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target WL 'ME_45EEDB730265' '45700BFD0251.pas.ms.script' // DynList
 ;

ref; // ME_51EEBD820221 

: ME_531DAD1F00A9
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_51D56E9F004B // TnscDocumentListTreeView
 ;
 : Target WL 'ME_45EEB95901C5' '457450470167.pas.ms.script' // NodeBase
 ;

ref; // ME_531DAD1F00A9 

: ME_55E6CC91033A_ME_51D56E9F004B
 : Original WL 'ME_55E6CC91033A' '53D227F702DF.pas.ms.script' // NewDocumentInHistory
 ;
 CONST OpKind opkind_Implemented
ref; // ME_55E6CC91033A_ME_51D56E9F004B NewDocumentInHistory

: ME_479731C50290_ME_51D56E9F004B
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_51D56E9F004B Cleanup

: ME_47A042E100E2_ME_51D56E9F004B
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_51D56E9F004B InitFields

: ME_47D1602000C6_ME_51D56E9F004B
 : Original WL 'ME_47D1602000C6' '4AB0997B00A2.pas.ms.script' // Create
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47D1602000C6_ME_51D56E9F004B Create

: ME_508F825303E4_ME_51D56E9F004B
 : Original WL 'ME_508F825303E4' '4B97E7FD006C.pas.ms.script' // DoOnGetItemStyle
 ;
 CONST OpKind opkind_Overridden
ref; // ME_508F825303E4_ME_51D56E9F004B DoOnGetItemStyle

: ME_5152C7D50201_ME_51D56E9F004B
 : Original WL 'ME_5152C7D50201' '4B97E7FD006C.pas.ms.script' // DoOnGetItemFont
 ;
 CONST OpKind opkind_Overridden
ref; // ME_5152C7D50201_ME_51D56E9F004B DoOnGetItemFont

: ME_51D2DC290320_ME_51D56E9F004B
 : Original WL 'ME_51D2DC290320' '4B97E7FD006C.pas.ms.script' // DoOnGetItemIndentEx
 ;
 CONST OpKind opkind_Overridden
ref; // ME_51D2DC290320_ME_51D56E9F004B DoOnGetItemIndentEx

: ME_51EEB81F017C_ME_51D56E9F004B
 : Original WL 'ME_51EEB81F017C' '4B97E7FD006C.pas.ms.script' // CanAcceptData
 ;
 CONST OpKind opkind_Overridden
ref; // ME_51EEB81F017C_ME_51D56E9F004B CanAcceptData

: ME_543239ED008D_ME_51D56E9F004B
 : Original WL 'ME_543239ED008D' '4B97E7FD006C.pas.ms.script' // GetRealClientWidth
 ;
 CONST OpKind opkind_Overridden
ref; // ME_543239ED008D_ME_51D56E9F004B GetRealClientWidth

: ME_5604EC1403A8_ME_51D56E9F004B
 : Original WL 'ME_5604EC1403A8' '4B97E7FD006C.pas.ms.script' // NeedAssignTreeStructFromHistory
 ;
 CONST OpKind opkind_Overridden
ref; // ME_5604EC1403A8_ME_51D56E9F004B NeedAssignTreeStructFromHistory

: ME_51D56E9F004B
 CONST UID '51D56E9F004B'
 CONST Name 'TnscDocumentListTreeView'
 CONST Class class_Class
 : Stereotype st_GuiControl ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_51D56E2A023C // DocumentListTree
 ;
 : Inherits
   Seq: ( WL 'ME_52DE57DF007B' '52DE57B200A5.pas.ms.script' // TnscTreeViewWithAdapterDragDrop
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_55E6CC7C0362' '53D227F702DF.pas.ms.script' // InscDocumentHistoryListener
 )
 ; // Implements
 : Attributes
   Seq: ( ME_51DC195E0142 // OnGetNodeType
 )
 ; // Attributes
 : Operations
   Seq: ( ME_51E01CC7023D // GetCurrentText
 ME_51E00D2000A7 // WMGetText
 ME_51E00DAD024C // WMGetTextLength
 )
 ; // Operations
 : Implemented
   Seq: ( ME_55E6CC91033A_ME_51D56E9F004B // NewDocumentInHistory
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_51D56E9F004B // Cleanup
 ME_47A042E100E2_ME_51D56E9F004B // InitFields
 ME_47D1602000C6_ME_51D56E9F004B // Create
 ME_508F825303E4_ME_51D56E9F004B // DoOnGetItemStyle
 ME_5152C7D50201_ME_51D56E9F004B // DoOnGetItemFont
 ME_51D2DC290320_ME_51D56E9F004B // DoOnGetItemIndentEx
 ME_51EEB81F017C_ME_51D56E9F004B // CanAcceptData
 ME_543239ED008D_ME_51D56E9F004B // GetRealClientWidth
 ME_5604EC1403A8_ME_51D56E9F004B // NeedAssignTreeStructFromHistory
 )
 ; // Overridden
 : Children
   Seq: ( ME_51DC189502B6 // TdltGetNodeTypeEvent
 )
 ; // Children
 : Dependencies
   Seq: ( ME_51D6DA1300D6 // TvtViewOptions
 ME_51D6DEF0012E // Il3SimpleNode
 ME_51D7E49A0117 // Msg Codes
 ME_51DACF1201D8 // Windows
 ME_51E01C110227 // SysUtils
 ME_51E029F300E5 // l3String
 ME_51E53E3C035F // evStyleTableTools
 ME_51E53FC902B3 // Tl3Point
 ME_51E54163036A // l3ScreenIC
 ME_51E5423000C7 // Standard
 ME_51EEBD820221 // DynList
 ME_531DAD1F00A9 // NodeBase
 )
 ; // Dependencies
 CONST "base wnd class" 'CWnd'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Components\nscDocumentListTreeView.pas'
 CONST extprop:rc:SelfName 'DocumentListTreeView'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'nscDocumentListTreeView'

ref; // ME_51D56E9F004B TnscDocumentListTreeView

: ME_51D56E2A023C
 CONST UID '51D56E2A023C'
 CONST Name 'DocumentListTree'
 CONST Class class_Category
 : Stereotype st_Views ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_51DD5AB6022D' '51DD5AB6022D.pas.ms.script' // Components
 ;
 : Children
   Seq: ( ME_51D56E9F004B // TnscDocumentListTreeView
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_45700BFD0251' '45700BFD0251.pas.ms.script' // DynamicDocList
 WL 'ME_457450470167' '457450470167.pas.ms.script' // DynamicTree
 WL 'ME_4682595B0268' '4682595B0268.pas.ms.script' // l3TreeInterfaces
 WL 'ME_472745450206' '472745450206.pas.ms.script' // l3Units
 WL 'ME_473C3BEE0334' '473C3BEE0334.pas.ms.script' // l3Canvas
 WL 'ME_476BE0350329' '476BE0350329.pas.ms.script' // Styles
 WL 'ME_476F78840219' '476F78840219.pas.ms.script' // Messages
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_47D036150077' '47D036150077.pas.ms.script' // l3ControlsTypes
 WL 'ME_47E246C90144' '47E246C90144.pas.ms.script' // l3Trees
 WL 'ME_47EA07FA02CE' '47EA07FA02CE.pas.ms.script' // bsTypes
 WL 'ME_47ECB2870309' '47ECB2870309.pas.ms.script' // StyleTable
 WL 'ME_48D21909003A' '48D21909003A.pas.ms.script' // OvcConst
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_4AB0C3F60375' '4AB0C3F60375.pas.ms.script' // Win
 WL 'ME_52DE57B200A5' '52DE57B200A5.pas.ms.script' // Tree$WithDnD
 WL 'ME_53D227F702DF' '53D227F702DF.pas.ms.script' // DocumentHistory
 WL 'ME_54B90AC6014B' '54B90AC6014B.pas.ms.script' // StringUtils
 )
 ; // Depends

ref; // ME_51D56E2A023C DocumentListTree
