// EmptyFormTests 51D528280220 TestUnit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_51D528280220

ME ME_51D528280220
 MEPROP UID '51D528280220'
 MEPROP Name 'EmptyFormTests'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_TestUnit ;
 %SUMMARY 'Тесты с пустой формой.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4B30C5FF0172' // TestFormsTest
 ;
 MELIST Children
   Seq: ( WL? 'ME_51D5285300B7' // TEmptyFormTest
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4AADF9450143' // Visual
 WL? 'ME_4B2A112B011A' // Source
 WL? 'ME_4B30C6E3023C' // Forms
 WL? 'ME_4BCE9EA0028A' // MixIns
 WL? 'ME_51D533840334' // FormWithPanel
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP Version 0

ENDME // ME_51D528280220 EmptyFormTests
