// l3StringEx 51E8F24303CC UtilityPack Class

FORWARD ME_51E8F24303CC

: ME_51E8F2620130
 CONST UID '51E8F2620130'
 CONST Name 'Tl3Str'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_51E8F2620130 Tl3Str

: ME_51E8F24303CC
 CONST UID '51E8F24303CC'
 CONST Name 'l3StringEx'
 CONST Class 'Class'
 CONST Stereotype 'UtilityPack'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Children
   [ ME_51E8F2620130 // Tl3Str
 ]
 ; // Children
 CONST "finished" false
 CONST "no hands" false

 @SELF
; // ME_51E8F24303CC l3StringEx
