// DataBaseSave 51F1032E01FB TestUnit Category

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_51F1032E01FB
 MEPROP UID '51F1032E01FB'
 MEPROP Name 'DataBaseSave'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_TestUnit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4DE765AE02EB' // ArchiInsiderTests
 ;
 MELIST Depends
   Seq: ( WL? 'ME_4DE3425B01DA' // ArchiScriptSupport
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP Version 0

ENDME // ME_51F1032E01FB DataBaseSave
