// VCMSandBox 521649450152 VCMGUI Category

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_521649450152
 MEPROP UID '521649450152'
 MEPROP Name 'VCMSandBox'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_VCMGUI ;
 %SUMMARY 'Тестовое приложение VCM' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL 'ME_521648D102D3' '521648D102D3.ms.model.script' // Shared Delphi Sand Box$App
 ;
 MELIST Children
   Seq: ( WL 'ME_521649770277' '521649770277.ms.model.script' // VCMSandBox
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_521633EF023C' '521633EF023C.ms.model.script' // Document
 WL 'ME_521DA5750380' '521DA5750380.ms.model.script' // List
 )
 ; // Depends
 UP "F1Like" false
 UP "needs second icon" false
 UP "vendor" 'none'
 UP intf.pas:Path 'common\components\SandBox\VCM\VCMSandBox.dpr'
 UP Version 0

ENDME // ME_521649450152 VCMSandBox
