// L3$Component Info 528E3D990126 Library Category

INCLUDE 'ElementsRTTI.ms.dict'

: ME_528E3D990126
 CONST UID '528E3D990126'
 CONST Name 'L3'
 CONST Class class_Category
 : Stereotype st_Library ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4ABCC25A0322' '4ABCC25A0322.pas.ms.script' // Shared Delphi Low Level
 ;
 : Children
   Seq: ( WL 'ME_528E3DE20137' '528E3DE20137.pas.ms.script' // Component Info
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4684F91300DD' '4684F91300DD.pas.ms.script' // Vcl
 WL 'ME_469F3E37025A' '469F3E37025A.pas.ms.script' // Rtl
 WL 'ME_4790D09A0378' '4790D09A0378.pas.ms.script' // L3
 WL 'ME_4E2F0E1B03BB' '4E2F0E1B03BB.pas.ms.script' // L3$Domain
 WL 'ME_550012C403C4' '550012C403C4.pas.ms.script' // L3$AFW
 )
 ; // Depends
 CONST "defines" 'l3Define.inc'
 CONST "exec mode" 'concluded'
 CONST "gui" 'rtl'
 CONST "is namespace" true
 CONST "vendor" '/Garant'
 CONST dfm:PathOnly '\common\components\rtl\Garant\L3'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\L3'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\528E3D990126.pas.ms.script'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\528E3D990126.pas.ms.script.runner'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_528E3D990126 L3$Component Info
