// ext 52E7AE9B00CF Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_52E7AE9B00CF

FORWARD ME_52E7AEC802A6

FORWARD ME_52E7AEE4036B

: ME_ED1490592139
 CONST UID 'ED1490592139'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY 'Сигнатура метода l3Calc' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_52E7AEE4036B // l3Calc
 ;

ref; // ME_ED1490592139 DoIt

: ME_52E7AEE4036B
 CONST UID '52E7AEE4036B'
 CONST Name 'l3Calc'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_52E7AEC802A6 // l3SimpleCalc
 ;
 : Operations
   Seq: ( ME_ED1490592139 // DoIt
 )
 ; // Operations
 CONST extprop:rc:SelfName 'Calc'

ref; // ME_52E7AEE4036B l3Calc

: ME_52E7AEC802A6
 CONST UID '52E7AEC802A6'
 CONST Name 'l3SimpleCalc'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_52E7AE9B00CF // ext
 ;
 : Operations
   Seq: ( ME_52E7AEE4036B // l3Calc
 )
 ; // Operations
 CONST "finished" false
 CONST "no hands" false
 CONST intf.pas:Path 'common\components\rtl\Garant\L3\ext\NOT_FINISHED_l3SimpleCalc.pas'
 CONST extprop:rc:SelfName 'SimpleCalc'

ref; // ME_52E7AEC802A6 l3SimpleCalc

: ME_52E7AE9B00CF
 CONST UID '52E7AE9B00CF'
 CONST Name 'ext'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4790D09A0378' '4790D09A0378.pas.ms.script' // L3
 ;
 : Children
   Seq: ( ME_52E7AEC802A6 // l3SimpleCalc
 )
 ; // Children
 CONST "path prefix" '/ext'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\L3\ext'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\52E7AE9B00CF.pas.ms.script'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\52E7AE9B00CF.pas.ms.script.runner'

ref; // ME_52E7AE9B00CF ext
