// tfwParserInterfaces 52EF72190220 Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_52EF72190220

FORWARD ME_52EF723E02D9

FORWARD ME_52EF733F022F

: ME_52EF734C019B
 CONST UID '52EF734C019B'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_52EF733F022F // NextToken
 ;

ref; // ME_52EF734C019B DoIt

: ME_52EF733F022F
 CONST UID '52EF733F022F'
 CONST Name 'NextToken'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_52EF723E02D9 // ItfwParser
 ;
 : Operations
   Seq: ( ME_52EF734C019B // DoIt
 )
 ; // Operations

ref; // ME_52EF733F022F NextToken

FORWARD ME_52EF735A02FF

: ME_52EF736700E1
 CONST UID '52EF736700E1'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_52EF735A02FF // TokenLongString
 ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_52EF736700E1 DoIt

: ME_52EF735A02FF
 CONST UID '52EF735A02FF'
 CONST Name 'TokenLongString'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_52EF723E02D9 // ItfwParser
 ;
 : Operations
   Seq: ( ME_52EF736700E1 // DoIt
 )
 ; // Operations

ref; // ME_52EF735A02FF TokenLongString

FORWARD ME_52EF739503A9

: ME_52EF739C0151
 CONST UID '52EF739C0151'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_52EF739503A9 // TokenInt
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_52EF739C0151 DoIt

: ME_52EF739503A9
 CONST UID '52EF739503A9'
 CONST Name 'TokenInt'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_52EF723E02D9 // ItfwParser
 ;
 : Operations
   Seq: ( ME_52EF739C0151 // DoIt
 )
 ; // Operations

ref; // ME_52EF739503A9 TokenInt

FORWARD ME_52EF73A9014A

: ME_52EF73B100D9
 CONST UID '52EF73B100D9'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_52EF73A9014A // FileName
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_52EF73B100D9 DoIt

: ME_52EF73A9014A
 CONST UID '52EF73A9014A'
 CONST Name 'FileName'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_52EF723E02D9 // ItfwParser
 ;
 : Operations
   Seq: ( ME_52EF73B100D9 // DoIt
 )
 ; // Operations
 CONST extprop:rc:SelfName 'File'

ref; // ME_52EF73A9014A FileName

FORWARD ME_52EF73DE037D

: ME_52EF742B0230
 CONST UID '52EF742B0230'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_52EF73DE037D // TokenType
 ;
 : Target WL 'ME_52EF740F00AE' '4C1B474600AD.pas.ms.script' // Tl3TokenType
 ;

ref; // ME_52EF742B0230 DoIt

: ME_52EF73DE037D
 CONST UID '52EF73DE037D'
 CONST Name 'TokenType'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_52EF723E02D9 // ItfwParser
 ;
 : Operations
   Seq: ( ME_52EF742B0230 // DoIt
 )
 ; // Operations

ref; // ME_52EF73DE037D TokenType

FORWARD ME_52EF7C8E027A

: ME_52EF7C960169
 CONST UID '52EF7C960169'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_52EF7C8E027A // SourceLine
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_52EF7C960169 DoIt

: ME_52EF7C8E027A
 CONST UID '52EF7C8E027A'
 CONST Name 'SourceLine'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_52EF723E02D9 // ItfwParser
 ;
 : Operations
   Seq: ( ME_52EF7C960169 // DoIt
 )
 ; // Operations

ref; // ME_52EF7C8E027A SourceLine

: ME_52EF723E02D9
 CONST UID '52EF723E02D9'
 CONST GUID 'EA8354FC-1EAD-4724-8124-9D8B54CF0780'
 CONST Name 'ItfwParser'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_52EF72190220 // tfwParserInterfaces
 ;
 : Operations
   Seq: ( ME_52EF733F022F // NextToken
 ME_52EF735A02FF // TokenLongString
 ME_52EF739503A9 // TokenInt
 ME_52EF73A9014A // FileName
 ME_52EF73DE037D // TokenType
 ME_52EF7C8E027A // SourceLine
 )
 ; // Operations
 : Injected
   Seq: ( WL 'ME_F70F3EC7E8F2' '4F43A0A401E6.pas.ms.script' // 
 )
 ; // Injected
 CONST extprop:rc:SelfName 'Parser'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_52EF723E02D9 ItfwParser

FORWARD ME_5576DB30036A

FORWARD ME_5576DB400397

: ME_5576DB5403A7
 CONST UID '5576DB5403A7'
 CONST Name 'aString'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_5576DB5403A7 aString

: ME_5576DB4A0182
 CONST UID '5576DB4A0182'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_5576DB400397 // PushString
 ;
 : Parameters
   Seq: ( ME_5576DB5403A7 // aString
 )
 ; // Parameters

ref; // ME_5576DB4A0182 DoIt

: ME_5576DB400397
 CONST UID '5576DB400397'
 CONST Name 'PushString'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_5576DB30036A // ItfwParserEx
 ;
 : Operations
   Seq: ( ME_5576DB4A0182 // DoIt
 )
 ; // Operations

ref; // ME_5576DB400397 PushString

FORWARD ME_5576DB580131

: ME_5576DB6401C6
 CONST UID '5576DB6401C6'
 CONST Name 'aString'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780DA40383' '4677FBA70343.pas.ms.script' // Il3CString
 ;

ref; // ME_5576DB6401C6 aString

: ME_5576DB6200F3
 CONST UID '5576DB6200F3'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_5576DB580131 // PushSymbol
 ;
 : Parameters
   Seq: ( ME_5576DB6401C6 // aString
 )
 ; // Parameters

ref; // ME_5576DB6200F3 DoIt

: ME_5576DB580131
 CONST UID '5576DB580131'
 CONST Name 'PushSymbol'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_5576DB30036A // ItfwParserEx
 ;
 : Operations
   Seq: ( ME_5576DB6200F3 // DoIt
 )
 ; // Operations

ref; // ME_5576DB580131 PushSymbol

FORWARD ME_5576DB6D02FE

: ME_5576DB8101C6
 CONST UID '5576DB8101C6'
 CONST Name 'aValue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_5576DB8101C6 aValue

: ME_5576DB7A0041
 CONST UID '5576DB7A0041'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_5576DB6D02FE // PushInt
 ;
 : Parameters
   Seq: ( ME_5576DB8101C6 // aValue
 )
 ; // Parameters

ref; // ME_5576DB7A0041 DoIt

: ME_5576DB6D02FE
 CONST UID '5576DB6D02FE'
 CONST Name 'PushInt'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_5576DB30036A // ItfwParserEx
 ;
 : Operations
   Seq: ( ME_5576DB7A0041 // DoIt
 )
 ; // Operations

ref; // ME_5576DB6D02FE PushInt

: ME_52EF733F022F_ME_5576DB30036A
 CONST UID '52EF733F022F'
 CONST Name 'NextToken'
 : Original ME_52EF733F022F // NextToken
 ;
 : Implementor ME_5576DB30036A // ItfwParserEx
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52EF733F022F_ME_5576DB30036A NextToken

: ME_52EF735A02FF_ME_5576DB30036A
 CONST UID '52EF735A02FF'
 CONST Name 'TokenLongString'
 : Original ME_52EF735A02FF // TokenLongString
 ;
 : Implementor ME_5576DB30036A // ItfwParserEx
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52EF735A02FF_ME_5576DB30036A TokenLongString

: ME_52EF739503A9_ME_5576DB30036A
 CONST UID '52EF739503A9'
 CONST Name 'TokenInt'
 : Original ME_52EF739503A9 // TokenInt
 ;
 : Implementor ME_5576DB30036A // ItfwParserEx
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52EF739503A9_ME_5576DB30036A TokenInt

: ME_52EF73A9014A_ME_5576DB30036A
 CONST UID '52EF73A9014A'
 CONST Name 'FileName'
 : Original ME_52EF73A9014A // FileName
 ;
 : Implementor ME_5576DB30036A // ItfwParserEx
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52EF73A9014A_ME_5576DB30036A FileName

: ME_52EF73DE037D_ME_5576DB30036A
 CONST UID '52EF73DE037D'
 CONST Name 'TokenType'
 : Original ME_52EF73DE037D // TokenType
 ;
 : Implementor ME_5576DB30036A // ItfwParserEx
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52EF73DE037D_ME_5576DB30036A TokenType

: ME_52EF7C8E027A_ME_5576DB30036A
 CONST UID '52EF7C8E027A'
 CONST Name 'SourceLine'
 : Original ME_52EF7C8E027A // SourceLine
 ;
 : Implementor ME_5576DB30036A // ItfwParserEx
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52EF7C8E027A_ME_5576DB30036A SourceLine

: ME_5576DB30036A
 CONST UID '5576DB30036A'
 CONST GUID '5650435D-EB36-4B67-A8A9-ECCC837FD2E6'
 CONST Name 'ItfwParserEx'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_52EF72190220 // tfwParserInterfaces
 ;
 : Inherits
   Seq: ( ME_52EF723E02D9 // ItfwParser
 )
 ; // Inherits
 : Operations
   Seq: ( ME_5576DB400397 // PushString
 ME_5576DB580131 // PushSymbol
 ME_5576DB6D02FE // PushInt
 )
 ; // Operations
 : Implemented
   Seq: ( ME_52EF733F022F_ME_5576DB30036A // NextToken
 ME_52EF735A02FF_ME_5576DB30036A // TokenLongString
 ME_52EF739503A9_ME_5576DB30036A // TokenInt
 ME_52EF73A9014A_ME_5576DB30036A // FileName
 ME_52EF73DE037D_ME_5576DB30036A // TokenType
 ME_52EF7C8E027A_ME_5576DB30036A // SourceLine
 )
 ; // Implemented
 : Injected
   Seq: ( WL 'ME_1C73FF865D09' '4F43A0A401E6.pas.ms.script' // 
 )
 ; // Injected
 CONST extprop:rc:SelfName 'ParserEx'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5576DB30036A ItfwParserEx

: ME_52EF72190220
 CONST UID '52EF72190220'
 CONST Name 'tfwParserInterfaces'
 CONST Class class_Category
 : Stereotype st_Interfaces ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_55C1EE2F01B7' '55C1EE2F01B7.pas.ms.script' // ScriptEngine$Parsing
 ;
 : Children
   Seq: ( ME_52EF723E02D9 // ItfwParser
 ME_5576DB30036A // ItfwParserEx
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4677FBA70343' '4677FBA70343.pas.ms.script' // l3Interfaces
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_4C1B474600AD' '4C1B474600AD.pas.ms.script' // Parser
 )
 ; // Depends
 CONST "is namespace" true
 CONST "no hands" false
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\tfwParserInterfaces.pas'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\52EF72190220.pas.ms.script'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\52EF72190220.pas.ms.script.runner'

ref; // ME_52EF72190220 tfwParserInterfaces
