// GUIAppTester 52F21A610247 Impurity Class

FORWARD ME_52F21A610247

INCLUDE '4807744200AA.pas.ms.script'

: ME_4DA478990164
 CONST UID '4DA478990164'
 CONST Name 'g_IsBatchMode'
 CONST Class 'Attribute'
 CONST Stereotype 'static'
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_46A603BB0391 // Boolean
 ;
 CONST Value false
 : ValueType ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_4DA478990164 g_IsBatchMode

: ME_4DA478B5000C
 CONST UID '4DA478B5000C'
 CONST Name 'g_IsBatchModeValid'
 CONST Class 'Attribute'
 CONST Stereotype 'static'
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_46A603BB0391 // Boolean
 ;
 CONST Value false
 : ValueType ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_4DA478B5000C g_IsBatchModeValid

INCLUDE '4DB1629901E8.pas.ms.script'

: ME_52F21B18009E
 CONST UID '52F21B18009E'
 CONST Name 'g_Debugger'
 CONST Class 'Attribute'
 CONST Stereotype 'static'
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'lnk'
 : Target ME_4DB14E0A029D // TtfwScriptDebugger_Form
 ;

 @SELF
; // ME_52F21B18009E g_Debugger

INCLUDE '4B2A0D9401CC.pas.ms.script'

: ME_52F21B3201DF
 CONST UID '52F21B3201DF'
 CONST Name 'g_TestsForm'
 CONST Class 'Attribute'
 CONST Stereotype 'static'
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'lnk'
 : Target ME_4DA30F0F02C1 // TGUITestRunner
 ;

 @SELF
; // ME_52F21B3201DF g_TestsForm

: ME_52F21B3B012E
 CONST UID '52F21B3B012E'
 CONST Name 'g_InRun'
 CONST Class 'Attribute'
 CONST Stereotype 'static'
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'lnk'
 : Target ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_52F21B3B012E g_InRun

FORWARD ME_4F79BCC902C5

: ME_4F79BCDA0351
 CONST UID '4F79BCDA0351'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Target ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_4F79BCDA0351 DoIt

: ME_4F79BCC902C5
 CONST UID '4F79BCC902C5'
 CONST Name 'CalcBatchMode'
 CONST Class 'Class'
 CONST Stereotype 'abstractmethod'
 CONST Visibility 'ProtectedAccess'
 CONST Abstraction 'abstract'
 : Operations
   [ ME_4F79BCDA0351 // DoIt
 ]
 ; // Operations
 CONST "is static" true

 @SELF
; // ME_4F79BCC902C5 CalcBatchMode

FORWARD ME_4DA3361A0305

: ME_4DA3362C0043
 CONST UID '4DA3362C0043'
 CONST Name 'Sender'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_4807745602C8 // TObject
 ;

 @SELF
; // ME_4DA3362C0043 Sender

: ME_4DA3362C00B5
 CONST UID '4DA3362C00B5'
 CONST Name 'Done'
 CONST Class 'Parameter'
 CONST Stereotype 'inout'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_4DA3362C00B5 Done

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_4DA33626026D
 CONST UID '4DA33626026D'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Parameters
   [ ME_4DA3362C0043 // Sender
 ME_4DA3362C00B5 // Done
 ]
 ; // Parameters

 @SELF
; // ME_4DA33626026D DoIt

: ME_4DA3361A0305
 CONST UID '4DA3361A0305'
 CONST Name 'DoIdle'
 CONST Class 'Class'
 CONST Stereotype 'method'
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_4DA33626026D // DoIt
 ]
 ; // Operations
 CONST "is static" true

 @SELF
; // ME_4DA3361A0305 DoIdle

FORWARD ME_4DA476580343

: ME_4DA4766801BC
 CONST UID '4DA4766801BC'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Target ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_4DA4766801BC DoIt

: ME_4DA476580343
 CONST UID '4DA476580343'
 CONST Name 'IsBatchMode'
 CONST Class 'Class'
 CONST Stereotype 'method'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_4DA4766801BC // DoIt
 ]
 ; // Operations
 CONST "ifdef" 'InsiderTest'
 CONST "is static" true

 @SELF
; // ME_4DA476580343 IsBatchMode

FORWARD ME_4F79B9D500D7

: ME_4F79B9E70001
 CONST UID '4F79B9E70001'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_4F79B9E70001 DoIt

: ME_4F79B9D500D7
 CONST UID '4F79B9D500D7'
 CONST Name 'ReadyToRun'
 CONST Class 'Class'
 CONST Stereotype 'method'
 %SUMMARY '¬ызываетс€ непосредственно перед запуском приложени€, например дл€ инициализации/запуска тестов' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_4F79B9E70001 // DoIt
 ]
 ; // Operations
 CONST "is static" true

 @SELF
; // ME_4F79B9D500D7 ReadyToRun

: ME_52F21A610247
 CONST UID '52F21A610247'
 CONST Name 'GUIAppTester'
 CONST Class 'Class'
 CONST Stereotype 'Impurity'
 %SUMMARY 'Ѕазовый тестер GUI-приложений' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'abstract'
 : Attributes
   [ ME_4DA478990164 // g_IsBatchMode
 ME_4DA478B5000C // g_IsBatchModeValid
 ME_52F21B18009E // g_Debugger
 ME_52F21B3201DF // g_TestsForm
 ME_52F21B3B012E // g_InRun
 ]
 ; // Attributes
 : Operations
   [ ME_4F79BCC902C5 // CalcBatchMode
 ME_4DA3361A0305 // DoIdle
 ME_4DA476580343 // IsBatchMode
 ME_4F79B9D500D7 // ReadyToRun
 ]
 ; // Operations
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_52F21A610247 GUIAppTester
