// TtfwStreamFactory 52F4E6AA02BB SimpleClass Class

INCLUDE '49E7754802A9.pas.ms.script'

INCLUDE '51612ED700B4.pas.ms.script'

FORWARD ME_52F4E6AA02BB

INCLUDE '48F4745E0023.pas.ms.script'

: ME_52F4E88600DA
 CONST UID '52F4E88600DA'
 CONST Name 'f_Stream'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'ProtectedAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_48F4748E0192 // Tl3Stream
 ;

 @SELF
; // ME_52F4E88600DA f_Stream

INCLUDE '4807744200AA.pas.ms.script'

: ME_52F4E91B0118
 CONST UID '52F4E91B0118'
 CONST Name 'f_FileName'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_476136D3010B // String
 ;

 @SELF
; // ME_52F4E91B0118 f_FileName

FORWARD ME_52F4E6D60067

: ME_52F4E6DE0361
 CONST UID '52F4E6DE0361'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Target ME_476136D3010B // String
 ;

 @SELF
; // ME_52F4E6DE0361 DoIt

: ME_52F4E6D60067
 CONST UID '52F4E6D60067'
 CONST Name 'FileName'
 CONST Class 'Class'
 CONST Stereotype 'method'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_52F4E6DE0361 // DoIt
 ]
 ; // Operations

 @SELF
; // ME_52F4E6D60067 FileName

FORWARD ME_52F4E6E90067

: ME_52F4E70E012F
 CONST UID '52F4E70E012F'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Target ME_48F4748E0192 // Tl3Stream
 ;

 @SELF
; // ME_52F4E70E012F DoIt

: ME_52F4E6E90067
 CONST UID '52F4E6E90067'
 CONST Name 'Stream'
 CONST Class 'Class'
 CONST Stereotype 'abstractmethod'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'abstract'
 : Operations
   [ ME_52F4E70E012F // DoIt
 ]
 ; // Operations

 @SELF
; // ME_52F4E6E90067 Stream

FORWARD ME_52F4E94802D6

: ME_52F4E9590090
 CONST UID '52F4E9590090'
 CONST Name 'aFileName'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_476136D3010B // String
 ;

 @SELF
; // ME_52F4E9590090 aFileName

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_52F4E94F026A
 CONST UID '52F4E94F026A'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Parameters
   [ ME_52F4E9590090 // aFileName
 ]
 ; // Parameters

 @SELF
; // ME_52F4E94F026A DoIt

: ME_52F4E94802D6
 CONST UID '52F4E94802D6'
 CONST Name 'Create'
 CONST Class 'Class'
 CONST Stereotype 'Constructor'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_52F4E94F026A // DoIt
 ]
 ; // Operations

 @SELF
; // ME_52F4E94802D6 Create

FORWARD ME_52F4F68C01E0

: ME_52F4F69C009A
 CONST UID '52F4F69C009A'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_52F4F69C009A DoIt

: ME_52F4F68C01E0
 CONST UID '52F4F68C01E0'
 CONST Name 'CloseStream'
 CONST Class 'Class'
 CONST Stereotype 'method'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_52F4F69C009A // DoIt
 ]
 ; // Operations

 @SELF
; // ME_52F4F68C01E0 CloseStream

FORWARD ME_55A649CC0040

: ME_55A649D90208
 CONST UID '55A649D90208'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Target ME_47272C8B0128 // TDateTime
 ;

 @SELF
; // ME_55A649D90208 DoIt

: ME_55A649CC0040
 CONST UID '55A649CC0040'
 CONST Name 'FileDateTime'
 CONST Class 'Class'
 CONST Stereotype 'abstractmethod'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'abstract'
 : Operations
   [ ME_55A649D90208 // DoIt
 ]
 ; // Operations

 @SELF
; // ME_55A649CC0040 FileDateTime

: ME_52F4E6AA02BB
 CONST UID '52F4E6AA02BB'
 CONST Name 'TtfwStreamFactory'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'abstract'
 : Inherits
   [ ME_49E7754802A9 // Tl3ProtoObject
 ]
 ; // Inherits
 : Attributes
   [ ME_52F4E88600DA // f_Stream
 ME_52F4E91B0118 // f_FileName
 ]
 ; // Attributes
 : Operations
   [ ME_52F4E6D60067 // FileName
 ME_52F4E6E90067 // Stream
 ME_52F4E94802D6 // Create
 ME_52F4F68C01E0 // CloseStream
 ME_55A649CC0040 // FileDateTime
 ]
 ; // Operations
 : Overridden
   [ ME_479731C50290 // Cleanup
 ]
 ; // Overridden
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_52F4E6AA02BB TtfwStreamFactory
