// TaskProcessingTuningForTests 52F8E847028C Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_52F8E847028C

ME ME_52F8E847028C
 MEPROP UID '52F8E847028C'
 MEPROP Name 'TaskProcessingTuningForTests'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_52F275D40238' // Low Level Tests
 ;
 MELIST Children
   Seq: ( WL? 'ME_52F8E8A101EC' // TddServerTaskManagerForTests
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4AB0997B00A2' // Common
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_4E030FC801EB' // BatchServices
 WL? 'ME_52F8C298005C' // Tasks
 WL? 'ME_53D656130130' // Server
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_52F8E847028C TaskProcessingTuningForTests
