// csTaskTypes 532046D302C2 UtilityPack Class

FORWARD ME_532046D302C2

: ME_532047060349
 CONST UID '532047060349'
 CONST Name 'TcsTaskStatus'
 CONST Class 'Class'
 CONST Stereotype 'Enum'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'

 @SELF
; // ME_532047060349 TcsTaskStatus

: ME_532047140237
 CONST UID '532047140237'
 CONST Name 'TcsTaskType'
 CONST Class 'Class'
 CONST Stereotype 'Enum'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'

 @SELF
; // ME_532047140237 TcsTaskType

: ME_532047210179
 CONST UID '532047210179'
 CONST Name 'TcsFileRenameMode'
 CONST Class 'Class'
 CONST Stereotype 'Enum'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'

 @SELF
; // ME_532047210179 TcsFileRenameMode

: ME_532047380399
 CONST UID '532047380399'
 CONST Name 'TcsTaskTypes'
 CONST Class 'Class'
 CONST Stereotype 'SetOf'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_532047140237 // TcsTaskType
 ]
 ; // Inherits

 @SELF
; // ME_532047380399 TcsTaskTypes

FORWARD ME_53C916400254

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_53C9165900CE
 CONST UID '53C9165900CE'
 CONST Name 'cs_arsSuccess'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 CONST Value 0
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false

 @SELF
; // ME_53C9165900CE cs_arsSuccess

: ME_53C91679014A
 CONST UID '53C91679014A'
 CONST Name 'cs_arsAborted'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 CONST Value 1
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false

 @SELF
; // ME_53C91679014A cs_arsAborted

: ME_53C916C10357
 CONST UID '53C916C10357'
 CONST Name 'cs_arsGeneralError'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 CONST Value 2
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false

 @SELF
; // ME_53C916C10357 cs_arsGeneralError

: ME_53C916FC0126
 CONST UID '53C916FC0126'
 CONST Name 'cs_arsUtilityNotFound'
 CONST Class 'Attribute'
 CONST Stereotype ''
 %SUMMARY 'Утилита не найдена' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 CONST Value 3
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false

 @SELF
; // ME_53C916FC0126 cs_arsUtilityNotFound

: ME_53D770A201A1
 CONST UID '53D770A201A1'
 CONST Name 'cs_arsTaskUnregistered'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 CONST Value 4
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false

 @SELF
; // ME_53D770A201A1 cs_arsTaskUnregistered

: ME_53C916400254
 CONST UID '53C916400254'
 CONST Name 'TcsExecutionStatus'
 CONST Class 'Class'
 CONST Stereotype 'Constants'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Attributes
   [ ME_53C9165900CE // cs_arsSuccess
 ME_53C91679014A // cs_arsAborted
 ME_53C916C10357 // cs_arsGeneralError
 ME_53C916FC0126 // cs_arsUtilityNotFound
 ME_53D770A201A1 // cs_arsTaskUnregistered
 ]
 ; // Attributes
 CONST "spell names" false

 @SELF
; // ME_53C916400254 TcsExecutionStatus

: ME_532046D302C2
 CONST UID '532046D302C2'
 CONST Name 'csTaskTypes'
 CONST Class 'Class'
 CONST Stereotype 'UtilityPack'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Children
   [ ME_532047060349 // TcsTaskStatus
 ME_532047140237 // TcsTaskType
 ME_532047210179 // TcsFileRenameMode
 ME_532047380399 // TcsTaskTypes
 ]
 ; // Children
 : Constants
   [ ME_53C916400254 // TcsExecutionStatus
 ]
 ; // Constants
 CONST "finished" false
 CONST "no hands" false

 @SELF
; // ME_532046D302C2 csTaskTypes
