// K517772970_TddBaseStatusRequest 53202365007E TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_53202365007E

ME ME_532035710262
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_53202365007E // K517772970_TddBaseStatusRequest
 ;
 MELINK Target WL? 'ME_531707520169' // csBaseStatusRequest
 ;

ENDME // ME_532035710262 

MEREF ME_5320088202FB_ME_53202365007E_over
 MELINK Original WL 'ME_5320088202FB' '532008240001.ms.model.script' // TaskClass
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_5320088202FB_ME_53202365007E_over TaskClass

MEREF ME_532008D203BA_ME_53202365007E_over
 MELINK Original WL 'ME_532008D203BA' '532008240001.ms.model.script' // InitTask
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_532008D203BA_ME_53202365007E_over InitTask

MEREF ME_53200AD70286_ME_53202365007E_G
 MELINK Original WL? 'ME_53200AD70286' // K517772970_TddRequestTask
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_53200AD70286_ME_53202365007E_G K517772970_TddRequestTask

%%InheritedBy ME_53200AD70286 ME_53202365007E

ME ME_53202365007E
 MEPROP UID '53202365007E'
 MEPROP Name 'K517772970_TddBaseStatusRequest'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{RequestLink:517772970}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_531FF6280311' // TaskSaveLoad
 ;
 MELIST Inherits
   Seq: ( ME_53200AD70286_ME_53202365007E_G // K517772970_TddRequestTask
 )
 ; // Inherits
 MELIST Overridden
   Seq: ( ME_5320088202FB_ME_53202365007E_over // TaskClass
 ME_532008D203BA_ME_53202365007E_over // InitTask
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_532035710262 // csBaseStatusRequest
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP intf.pas:Path 'archi\source\projects\PipeInAuto\Tests\Tasks\SaveLoad\K517772970_TddBaseStatusRequest.pas'
 UP extprop:pas:TypeName 'TK517772970_TddBaseStatusRequest'
 UP extprop:rc:SelfName 'K517772970_TddBaseStatusRequest'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_53202365007E K517772970_TddBaseStatusRequest
