// K517783699 532164F50223 TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4DE4827600CA_ME_532164F50223_G
 MELINK Original WL? 'ME_4DE4827600CA' // TArchiInsiderTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4DE4827600CA_ME_532164F50223_G TArchiInsiderTest

%%InheritedBy ME_4DE4827600CA ME_532164F50223

ME ME_532164F50223
 MEPROP UID '532164F50223'
 MEPROP Name 'K517783699'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:517783699}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_532164D501C5' // PreivewTests
 ;
 MELIST Inherits
   Seq: ( ME_4DE4827600CA_ME_532164F50223_G // TArchiInsiderTest
 )
 ; // Inherits
 UP intf.pas:Path 'archi\source\projects\Everest\Lite\7.0\Express\Tests\K517783699.pas'
 UP extprop:pas:TypeName 'TK517783699'
 UP extprop:rc:SelfName 'K517783699'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_532164F50223 K517783699
