// TaskSaveLoadMixIns 53739AE1025E Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_53739AE1025E

FORWARD ME_53739B29005D

FORWARD ME_537383090350

: ME_5373832C00DD
 CONST Name 'aTask'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_52FA49DF00EF' '52FA49B901D3.pas.ms.script' // TddTaskItem
 ;

ref; // ME_5373832C00DD aTask

: ME_5373832C010F
 CONST Name 'aPipe'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5373832C010F aPipe

: ME_53AC2E6F023B
 CONST Name 'aAsEVD'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_53AC2E6F023B aAsEVD

: ME_537383150366
 CONST UID '537383150366'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_537383090350 // SaveTask
 ;
 : Parameters
   Seq: ( ME_5373832C00DD // aTask
 ME_5373832C010F // aPipe
 ME_53AC2E6F023B // aAsEVD
 )
 ; // Parameters

ref; // ME_537383150366 DoIt

: ME_537383090350
 CONST UID '537383090350'
 CONST Name 'SaveTask'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent ME_53739B29005D // TaskSaver
 ;
 : Operations
   Seq: ( ME_537383150366 // DoIt
 )
 ; // Operations

ref; // ME_537383090350 SaveTask

: ME_53739C0A03E7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_53739B29005D // TaskSaver
 ;
 : Target WL 'ME_4B4F61AD01AA' '47913B47006E.pas.ms.script' // Tl3CustomDosFiler
 ;

ref; // ME_53739C0A03E7 

: ME_53739E2D01BB
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_53739B29005D // TaskSaver
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_53739E2D01BB 

: ME_53739B29005D
 CONST UID '53739B29005D'
 CONST Name 'TaskSaver'
 CONST Class class_Class
 : Stereotype st_Impurity ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_53739AE1025E // TaskSaveLoadMixIns
 ;
 : Operations
   Seq: ( ME_537383090350 // SaveTask
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_53739C0A03E7 // Tl3CustomDosFiler
 ME_53739E2D01BB // FreeAndNil
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'archi\source\projects\PipeInAuto\Tests\TaskSaver.imp.pas'
 CONST extprop:pas:TypeName '_TaskSaver_'
 CONST extprop:pas:UnitName 'TaskSaver.imp'

ref; // ME_53739B29005D TaskSaver

: ME_53739AE1025E
 CONST UID '53739AE1025E'
 CONST Name 'TaskSaveLoadMixIns'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_52F275D40238' '52F275D40238.pas.ms.script' // Low Level Tests
 ;
 : Children
   Seq: ( ME_53739B29005D // TaskSaver
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_52FA49B901D3' '52FA49B901D3.pas.ms.script' // ArchiClientServer
 )
 ; // Depends

ref; // ME_53739AE1025E TaskSaveLoadMixIns
