// OvcKeyDataListeners 53B23EDB01DF Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_53B23EDB01DF

FORWARD ME_53B23EFD0347

: ME_53B23FB902BA
 CONST UID '53B23FB902BA'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent ME_53B23EFD0347 // TOvcKeyDataListenerList
 ;
 : Target WL 'ME_53B11944038A' '467C0CAA02AB.pas.ms.script' // Il3KeyDataListener
 ;

ref; // ME_53B23FB902BA ItemType

: ME_53B23EFD0347
 CONST UID '53B23EFD0347'
 CONST Name 'TOvcKeyDataListenerList'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_53B23EDB01DF // OvcKeyDataListeners
 ;
 : Inherits
   @ ( WL 'ME_47B57D630029' '47913B47006E.pas.ms.script' // l3InterfacePtrList
 WL 'ME_47BC3A07027F' '47913B47006E.pas.ms.script' // Tl3SimpleDataContainer
 ) .SequenceCode.It
 ; // Inherits
 : Attributes
   @ ( ME_53B23FB902BA // ItemType
 ) .SequenceCode.It
 ; // Attributes
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 : Generators
 @ (
 gen_intf.pas
 ) .SequenceCode.It
 ; // Generators
 CONST intf.pas:Path 'common\components\rtl\external\Orpheus\OvcKeyDataListenerList.pas'

ref; // ME_53B23EFD0347 TOvcKeyDataListenerList

: ME_53B23EDB01DF
 CONST UID '53B23EDB01DF'
 CONST Name 'OvcKeyDataListeners'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_47540FF802AC' '47540FF802AC.pas.ms.script' // Orpheus
 ;
 : Children
   @ ( ME_53B23EFD0347 // TOvcKeyDataListenerList
 ) .SequenceCode.It
 ; // Children
 : Depends
   @ ( WL 'ME_467C0CAA02AB' '467C0CAA02AB.pas.ms.script' // l3InternalInterfaces
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 ) .SequenceCode.It
 ; // Depends
 : Generators
 @ (
 gen_pas.script
 gen_pas.script.runner
 ) .SequenceCode.It
 ; // Generators
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\53B23EDB01DF.pas.ms.script'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\53B23EDB01DF.pas.ms.script.runner'

ref; // ME_53B23EDB01DF OvcKeyDataListeners
