// Tm3BaseHeaderStream 53FF134A03BA SimpleClass Class

FORWARD ME_53FF134A03BA

FORWARD ME_53FF29BD01B3

INCLUDE '3DBFDB23006E.pas.ms.script'

INCLUDE '54217680017C.pas.ms.script'

: ME_53FF29CA0197
 CONST UID '53FF29CA0197'
 CONST Name 'cHeaderFullSize'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 CONST Value 'Cm3BasClaDefHeaderSize'
 : ValueType ME_53FF08370075 // BasClaDefaults
 ;
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false

 @SELF
; // ME_53FF29CA0197 cHeaderFullSize

: ME_53FF29BD01B3
 CONST UID '53FF29BD01B3'
 CONST Name 'Defaults'
 CONST Class 'Class'
 CONST Stereotype 'Constants'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Attributes
   [ ME_53FF29CA0197 // cHeaderFullSize
 ]
 ; // Attributes
 CONST "spell names" false

 @SELF
; // ME_53FF29BD01B3 Defaults

INCLUDE '53FF125B01D4.pas.ms.script'

INCLUDE '51612ED700B4.pas.ms.script'

INCLUDE '5481CCCF0319.pas.ms.script'

INCLUDE '4FA276650046.pas.ms.script'

INCLUDE '4807744200AA.pas.ms.script'

: ME_53FF1391017E
 CONST UID '53FF1391017E'
 CONST Name 'FHeaderSize'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'ProtectedAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_46A606AC03B2 // Integer
 ;

 @SELF
; // ME_53FF1391017E FHeaderSize

: ME_53FF13B703B6
 CONST UID '53FF13B703B6'
 CONST Name 'FHeaderLocked'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_46A606AC03B2 // Integer
 ;

 @SELF
; // ME_53FF13B703B6 FHeaderLocked

: ME_53FF1FE30251
 CONST UID '53FF1FE30251'
 CONST Name 'FHeaderLoaded'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'ProtectedAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_46A606AC03B2 // Integer
 ;

 @SELF
; // ME_53FF1FE30251 FHeaderLoaded

FORWARD ME_53FDFE220358

: ME_2658F5BF783E
 CONST UID '2658F5BF783E'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 %SUMMARY 'Сигнатура метода LockHeader' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_2658F5BF783E DoIt

: ME_53FDFE220358
 CONST UID '53FDFE220358'
 CONST Name 'LockHeader'
 CONST Class 'Class'
 CONST Stereotype 'method'
 %SUMMARY 'закрывает заголовок' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_2658F5BF783E // DoIt
 ]
 ; // Operations

 @SELF
; // ME_53FDFE220358 LockHeader

FORWARD ME_53FDFE3802D0

: ME_83D63A1EFE2B
 CONST UID '83D63A1EFE2B'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 %SUMMARY 'Сигнатура метода UnlockHeader' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_83D63A1EFE2B DoIt

: ME_53FDFE3802D0
 CONST UID '53FDFE3802D0'
 CONST Name 'UnlockHeader'
 CONST Class 'Class'
 CONST Stereotype 'method'
 %SUMMARY 'открывает заголовок' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_83D63A1EFE2B // DoIt
 ]
 ; // Operations

 @SELF
; // ME_53FDFE3802D0 UnlockHeader

FORWARD ME_53FDFDF503CE

: ME_53FDFE15039B
 CONST UID '53FDFE15039B'
 CONST Name 'aForceSave'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_53FDFE15039B aForceSave

: ME_53FDFE05015C
 CONST UID '53FDFE05015C'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Parameters
   [ ME_53FDFE15039B // aForceSave
 ]
 ; // Parameters

 @SELF
; // ME_53FDFE05015C DoIt

: ME_53FDFDF503CE
 CONST UID '53FDFDF503CE'
 CONST Name 'DoSaveHeader'
 CONST Class 'Class'
 CONST Stereotype 'abstractmethod'
 %SUMMARY 'сохраняет заголовок' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'abstract'
 : Operations
   [ ME_53FDFE05015C // DoIt
 ]
 ; // Operations

 @SELF
; // ME_53FDFDF503CE DoSaveHeader

FORWARD ME_53FDFDD90071

: ME_C7BF4C4FFD7C
 CONST UID 'C7BF4C4FFD7C'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 %SUMMARY 'Сигнатура метода DoLoadHeader' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_C7BF4C4FFD7C DoIt

: ME_53FDFDD90071
 CONST UID '53FDFDD90071'
 CONST Name 'DoLoadHeader'
 CONST Class 'Class'
 CONST Stereotype 'abstractmethod'
 %SUMMARY 'загружает заголовок в память' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'abstract'
 : Operations
   [ ME_C7BF4C4FFD7C // DoIt
 ]
 ; // Operations

 @SELF
; // ME_53FDFDD90071 DoLoadHeader

FORWARD ME_53FF1F6901C5

: ME_B657CD97F2AA
 CONST UID 'B657CD97F2AA'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 %SUMMARY 'Сигнатура метода LoadHeader' ;
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_B657CD97F2AA DoIt

: ME_53FF1F6901C5
 CONST UID '53FF1F6901C5'
 CONST Name 'LoadHeader'
 CONST Class 'Class'
 CONST Stereotype 'method'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_B657CD97F2AA // DoIt
 ]
 ; // Operations

 @SELF
; // ME_53FF1F6901C5 LoadHeader

FORWARD ME_53FF1F90030A

: ME_53FF1FA50259
 CONST UID '53FF1FA50259'
 CONST Name 'aForceSave'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_46A603BB0391 // Boolean
 ;
 CONST Value false
 : ValueType ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_53FF1FA50259 aForceSave

: ME_53FF1FA20235
 CONST UID '53FF1FA20235'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Parameters
   [ ME_53FF1FA50259 // aForceSave
 ]
 ; // Parameters

 @SELF
; // ME_53FF1FA20235 DoIt

: ME_53FF1F90030A
 CONST UID '53FF1F90030A'
 CONST Name 'SaveHeader'
 CONST Class 'Class'
 CONST Stereotype 'method'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_53FF1FA20235 // DoIt
 ]
 ; // Operations

 @SELF
; // ME_53FF1F90030A SaveHeader

FORWARD ME_53FDFD1D0164

: ME_53FDFD230321
 CONST UID '53FDFD230321'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_53FDFD230321 DoIt

: ME_53FDFD1D0164
 CONST UID '53FDFD1D0164'
 CONST Name 'DefaultInitAction'
 CONST Class 'Class'
 CONST Stereotype 'virtualmethod'
 CONST Visibility 'ProtectedAccess'
 CONST Abstraction 'regular'
 : Operations
   [ ME_53FDFD230321 // DoIt
 ]
 ; // Operations

 @SELF
; // ME_53FDFD1D0164 DefaultInitAction

FORWARD ME_53FDFD34034B

: ME_53FDFD3B02ED
 CONST UID '53FDFD3B02ED'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_53FDFD3B02ED DoIt

: ME_53FDFD34034B
 CONST UID '53FDFD34034B'
 CONST Name 'DefaultDoneAction'
 CONST Class 'Class'
 CONST Stereotype 'virtualmethod'
 CONST Visibility 'ProtectedAccess'
 CONST Abstraction 'regular'
 : Operations
   [ ME_53FDFD3B02ED // DoIt
 ]
 ; // Operations

 @SELF
; // ME_53FDFD34034B DefaultDoneAction

FORWARD ME_540F07260255

: ME_5410259E0201
 CONST UID '5410259E0201'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Target ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_5410259E0201 DoIt

: ME_540F07260255
 CONST UID '540F07260255'
 CONST Name 'DoLockHeader'
 CONST Class 'Class'
 CONST Stereotype 'virtualmethod'
 CONST Visibility 'ProtectedAccess'
 CONST Abstraction 'regular'
 : Operations
   [ ME_5410259E0201 // DoIt
 ]
 ; // Operations

 @SELF
; // ME_540F07260255 DoLockHeader

FORWARD ME_540F072F02B4

: ME_541025A900AA
 CONST UID '541025A900AA'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Target ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_541025A900AA DoIt

: ME_540F072F02B4
 CONST UID '540F072F02B4'
 CONST Name 'DoUnlockHeader'
 CONST Class 'Class'
 CONST Stereotype 'virtualmethod'
 CONST Visibility 'ProtectedAccess'
 CONST Abstraction 'regular'
 : Operations
   [ ME_541025A900AA // DoIt
 ]
 ; // Operations

 @SELF
; // ME_540F072F02B4 DoUnlockHeader

: ME_53FF134A03BA
 CONST UID '53FF134A03BA'
 CONST Name 'Tm3BaseHeaderStream'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_53FF125B01D4 // Tm3LinkedStream
 ]
 ; // Inherits
 : Attributes
   [ ME_53FF1391017E // FHeaderSize
 ME_53FF13B703B6 // FHeaderLocked
 ME_53FF1FE30251 // FHeaderLoaded
 ]
 ; // Attributes
 : Operations
   [ ME_53FDFE220358 // LockHeader
 ME_53FDFE3802D0 // UnlockHeader
 ME_53FDFDF503CE // DoSaveHeader
 ME_53FDFDD90071 // DoLoadHeader
 ME_53FF1F6901C5 // LoadHeader
 ME_53FF1F90030A // SaveHeader
 ME_53FDFD1D0164 // DefaultInitAction
 ME_53FDFD34034B // DefaultDoneAction
 ME_540F07260255 // DoLockHeader
 ME_540F072F02B4 // DoUnlockHeader
 ]
 ; // Operations
 : Overridden
   [ ME_479731C50290 // Cleanup
 ME_4FA27D5302C5 // DoSeek
 ME_4FA27DCD02B4 // DoSetSize
 ME_4FA27E100218 // LockRegion
 ME_4FA27E4C0342 // UnlockRegion
 ME_4FA2802E0231 // DoGetSize
 ]
 ; // Overridden
 : Constants
   [ ME_53FF29BD01B3 // Defaults
 ]
 ; // Constants
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_53FF134A03BA Tm3BaseHeaderStream
