// Tm3LZODeflateStreamNew 542AA47B0241 SimpleClass Class

INCLUDE '542A9FC5028B.pas.ms.script'

INCLUDE '53FDFADD027F.pas.ms.script'

INCLUDE '53FDCEC40006.pas.ms.script'

: ME_542AA47B0241
 CONST UID '542AA47B0241'
 CONST Name 'Tm3LZODeflateStreamNew'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_542AA040007A // Tm3LZODeflateStream
 ]
 ; // Inherits
 : Overridden
   [ ME_53FDFAF900ED // HeaderID
 ME_5408826C0072 // NeedHeaderAlignment
 ]
 ; // Overridden
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_542AA47B0241 Tm3LZODeflateStreamNew
