// Connection 544A09C403BE Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_544A09C403BE

: ME_5451E68E0399
 CONST UID '5451E68E0399'
 CONST Name 'TncsConnection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_544A09C403BE // Connection
 ;
 : Inherits
   @ ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 ) .SequenceCode.It
 ; // Inherits
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 : Generators
 @ (
 gen_intf.pas
 ) .SequenceCode.It
 ; // Generators
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsConnection.pas'

ref; // ME_5451E68E0399 TncsConnection

: ME_5451E6B902C3
 CONST UID '5451E6B902C3'
 CONST Name 'TncsClientConnection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_544A09C403BE // Connection
 ;
 : Inherits
   @ ( ME_5451E68E0399 // TncsConnection
 ) .SequenceCode.It
 ; // Inherits
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 : Generators
 @ (
 gen_intf.pas
 ) .SequenceCode.It
 ; // Generators
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsClientConnection.pas'

ref; // ME_5451E6B902C3 TncsClientConnection

: ME_5451E6E20117
 CONST UID '5451E6E20117'
 CONST Name 'TncsServerConnection'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_544A09C403BE // Connection
 ;
 : Inherits
   @ ( ME_5451E68E0399 // TncsConnection
 ) .SequenceCode.It
 ; // Inherits
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 : Generators
 @ (
 gen_intf.pas
 ) .SequenceCode.It
 ; // Generators
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsServerConnection.pas'

ref; // ME_5451E6E20117 TncsServerConnection

: ME_544A09C403BE
 CONST UID '544A09C403BE'
 CONST Name 'Connection'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_52F8C27F01AB' '52F8C27F01AB.pas.ms.script' // cs
 ;
 : Children
   @ ( ME_5451E68E0399 // TncsConnection
 ME_5451E6B902C3 // TncsClientConnection
 ME_5451E6E20117 // TncsServerConnection
 ) .SequenceCode.It
 ; // Children
 : Depends
   @ ( WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_47D0290B016D' '47D0290B016D.pas.ms.script' // l3Utils
 WL 'ME_544E0148010D' '544E0148010D.pas.ms.script' // Messages
 ) .SequenceCode.It
 ; // Depends
 : Generators
 @ (
 gen_pas.script
 gen_pas.script.runner
 ) .SequenceCode.It
 ; // Generators
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\544A09C403BE.pas.ms.script'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\544A09C403BE.pas.ms.script.runner'

ref; // ME_544A09C403BE Connection
