// TncsLoginMessage 544E07C6034D SimpleClass Class

INCLUDE '5453986402AC.pas.ms.script'

FORWARD ME_544E07C6034D

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_A8CE837D53E8
 CONST UID 'A8CE837D53E8'
 CONST Name 'ServerHost'
 CONST Class 'Attribute'
 CONST Stereotype 'property'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 CONST LinkType 'agr'
 : Target ME_452257A0036F // a-string
 ;
 CONST "pm" true

 @SELF
; // ME_A8CE837D53E8 ServerHost

: ME_F242EF9D067F
 CONST UID 'F242EF9D067F'
 CONST Name 'Login'
 CONST Class 'Attribute'
 CONST Stereotype 'property'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 CONST LinkType 'agr'
 : Target ME_452257A0036F // a-string
 ;
 CONST "pm" true

 @SELF
; // ME_F242EF9D067F Login

: ME_1E446BBD08F0
 CONST UID '1E446BBD08F0'
 CONST Name 'Password'
 CONST Class 'Attribute'
 CONST Stereotype 'property'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 CONST LinkType 'agr'
 : Target ME_452257A0036F // a-string
 ;
 CONST "pm" true

 @SELF
; // ME_1E446BBD08F0 Password

: ME_25BE68E15A6A
 CONST UID '25BE68E15A6A'
 CONST Name 'ServerPort'
 CONST Class 'Attribute'
 CONST Stereotype 'property'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 CONST LinkType 'agr'
 : Target ME_3DBFFD7002C2 // long
 ;
 CONST "pm" true

 @SELF
; // ME_25BE68E15A6A ServerPort

: ME_544E07C6034D
 CONST UID '544E07C6034D'
 CONST Name 'TncsLoginMessage'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_544E079E0253 // TncsMessage
 ]
 ; // Inherits
 : Attributes
   [ ME_A8CE837D53E8 // ServerHost
 ME_F242EF9D067F // Login
 ME_1E446BBD08F0 // Password
 ME_25BE68E15A6A // ServerPort
 ]
 ; // Attributes
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_544E07C6034D TncsLoginMessage
