// Messages 544E0148010D Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_544E0148010D

FORWARD ME_544E079E0253

: ME_544E07C6034D
 CONST UID '544E07C6034D'
 CONST Name 'TncsLoginMessage'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( HWL ME_544E079E0253 // TncsMessage
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_544E02580378' '484A470100DD.pas.ms.script' // csLogin
 )
 ; // Implements
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsLoginMessage.pas'
 CONST extprop:rc:SelfName 'ncsLoginMessage'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsLoginMessage'

ref; // ME_544E07C6034D TncsLoginMessage

FORWARD ME_544F977F036B

: ME_544F98080257
 CONST UID '544F98080257'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_544F977F036B // TncsPriorityMessageList
 ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_544F98080257 ItemType

: ME_5450AE6C031E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544F977F036B // TncsPriorityMessageList
 ;
 : Target WL 'ME_4E8C103D01B1' '4AB0997B00A2.pas.ms.script' // Sign
 ;

ref; // ME_5450AE6C031E 

: ME_47B2C42A0163_ME_544F977F036B
 : Original WL 'ME_47B2C42A0163' '47913B47006E.pas.ms.script' // AssignItem
 ;
 CONST OpKind opkind_Implemented
 CONST "ifdef" 'l3Items_NeedsAssignItem'
 CONST "ifndef" 'l3Items_NoSort'
ref; // ME_47B2C42A0163_ME_544F977F036B AssignItem

: ME_47B99D4503A2_ME_544F977F036B
 : Original WL 'ME_47B99D4503A2' '47BB24D30205.pas.ms.script' // CompareExistingItems
 ;
 CONST OpKind opkind_Implemented
ref; // ME_47B99D4503A2_ME_544F977F036B CompareExistingItems

: ME_544F977F036B
 CONST UID '544F977F036B'
 CONST Name 'TncsPriorityMessageList'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Список сортированый по приоритету и дате сообщения' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.pas.ms.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_47B99E920196' '47913B47006E.pas.ms.script' // l3UncomparabeObjectRefList
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_544F98080257 // ItemType
 )
 ; // Attributes
 : Implemented
   Seq: ( ME_47B2C42A0163_ME_544F977F036B // AssignItem
 ME_47B99D4503A2_ME_544F977F036B // CompareExistingItems
 )
 ; // Implemented
 : Dependencies
   Seq: ( ME_5450AE6C031E // Sign
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsPriorityMessageList.pas'
 CONST extprop:rc:SelfName 'ncsPriorityMessageList'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsPriorityMessageList'

ref; // ME_544F977F036B TncsPriorityMessageList

FORWARD ME_544E3C54031D

: ME_545A157B02C2
 CONST UID '545A157B02C2'
 CONST Name 'Processing'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_545A157B02C2 Processing

: ME_544F981C03B5
 CONST UID '544F981C03B5'
 CONST Name 'f_Data'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 : Target HWL ME_544F977F036B // TncsPriorityMessageList
 ;

ref; // ME_544F981C03B5 f_Data

: ME_544F98B70016
 CONST UID '544F98B70016'
 CONST Name 'f_DataReadyEvent'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 : Target WL 'ME_491D9DB8010F' '4AB0997B00A2.pas.ms.script' // TEvent
 ;

ref; // ME_544F98B70016 f_DataReadyEvent

: ME_5451F97902B8
 CONST UID '5451F97902B8'
 CONST Name 'SignalMessageReady'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;

ref; // ME_5451F97902B8 SignalMessageReady

: ME_544E3E0101A1
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_544E3E0101A1 aMessage

: ME_544E3DE3032D
 CONST UID '544E3DE3032D'
 CONST Name 'Push'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 : Parameters
   Seq: ( ME_544E3E0101A1 // aMessage
 )
 ; // Parameters

ref; // ME_544E3DE3032D Push

: ME_545220540371
 CONST Name 'aTimeOut'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47BC524C0245' '4AB0C3C60310.pas.ms.script' // LongWord
 ;
 CONST Value 'INFINITE'
 : ValueType WL 'ME_483C21B0003E' '4AB0C3F60375.pas.ms.script' // Timeouts
 ;
 CONST extprop:pas:Value 'INFINITE'

ref; // ME_545220540371 aTimeOut

: ME_5452022F026A
 CONST UID '5452022F026A'
 CONST Name 'WaitForMessage'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_545220540371 // aTimeOut
 )
 ; // Parameters

ref; // ME_5452022F026A WaitForMessage

: ME_545202900301
 CONST Name 'theMessage'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_545202900301 theMessage

: ME_545202810200
 CONST UID '545202810200'
 CONST Name 'ExtractMessage'
 CONST Class class_Operation
 %SUMMARY 'Увеличивает счетчик theMessage! Требуется theMessage.Free' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_545202900301 // theMessage
 )
 ; // Parameters

ref; // ME_545202810200 ExtractMessage

: ME_5450B0EF02BD
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_5450B0EF02BD 

: ME_5450D0510367
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 : Target WL 'ME_47614B2901AE' '4678193C009C.pas.ms.script' // Tl3Duplicates
 ;

ref; // ME_5450D0510367 

: ME_5450D7950321
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 : Target WL 'ME_54509FEC02EB' '47D0290B016D.pas.ms.script' // l3CreateStringGUID
 ;

ref; // ME_5450D7950321 

: ME_479731C50290_ME_544E3C54031D
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_544E3C54031D Cleanup

: ME_47A042E100E2_ME_544E3C54031D
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_544E3C54031D InitFields

: ME_544E3C54031D
 CONST UID '544E3C54031D'
 CONST Name 'TncsMessageQueue'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_53A03846011C' '53A038340371.pas.ms.script' // l3CriticalSectionHolder
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_545A157B02C2 // Processing
 HWL ME_544F981C03B5 // f_Data
 HWL ME_544F98B70016 // f_DataReadyEvent
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_5451F97902B8 // SignalMessageReady
 HWL ME_544E3DE3032D // Push
 HWL ME_5452022F026A // WaitForMessage
 HWL ME_545202810200 // ExtractMessage
 )
 ; // Operations
 : Overridden
   Seq: ( ME_479731C50290_ME_544E3C54031D // Cleanup
 ME_47A042E100E2_ME_544E3C54031D // InitFields
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_5450B0EF02BD // FreeAndNil
 ME_5450D0510367 // Tl3Duplicates
 ME_5450D7950321 // l3CreateStringGUID
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsMessageQueue.pas'
 CONST extprop:rc:SelfName 'ncsMessageQueue'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsMessageQueue'

ref; // ME_544E3C54031D TncsMessageQueue

FORWARD ME_5452248C02B8

: ME_5450EA090093
 CONST UID '5450EA090093'
 CONST Name 'Queue'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5452248C02B8 // TncsTransporterThread
 ;
 : Target HWL ME_544E3C54031D // TncsMessageQueue
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5450EA090093 Queue

FORWARD ME_5450EAAA0367

: ME_5450EAE301E1
 CONST Name 'anQueue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E3C54031D // TncsMessageQueue
 ;

ref; // ME_5450EAE301E1 anQueue

: ME_5450EAC70263
 CONST UID '5450EAC70263'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5450EAAA0367 // Create
 ;
 : Parameters
   Seq: ( ME_5450EAE301E1 // anQueue
 )
 ; // Parameters

ref; // ME_5450EAC70263 DoIt

: ME_5450EAAA0367
 CONST UID '5450EAAA0367'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5452248C02B8 // TncsTransporterThread
 ;
 : Operations
   Seq: ( HWL ME_5450EAC70263 // DoIt
 )
 ; // Operations

ref; // ME_5450EAAA0367 Create

FORWARD ME_5459DB98029C

: ME_5459DBA700DB
 CONST UID '5459DBA700DB'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5459DB98029C // TerminatedConnection
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5459DBA700DB DoIt

: ME_5459DB98029C
 CONST UID '5459DB98029C'
 CONST Name 'TerminatedConnection'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5452248C02B8 // TncsTransporterThread
 ;
 : Operations
   Seq: ( HWL ME_5459DBA700DB // DoIt
 )
 ; // Operations

ref; // ME_5459DB98029C TerminatedConnection

: ME_54523C2D01FF
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5452248C02B8 // TncsTransporterThread
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_54523C2D01FF 

: ME_4911B69E037D_ME_5452248C02B8
 : Original WL 'ME_4911B69E037D' '47913B47006E.pas.ms.script' // DoExecute
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4911B69E037D_ME_5452248C02B8 DoExecute

: ME_479731C50290_ME_5452248C02B8
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_5452248C02B8 Cleanup

: ME_5452248C02B8
 CONST UID '5452248C02B8'
 CONST Name 'TncsTransporterThread'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_4911B24C01F6' '47913B47006E.pas.ms.script' // Tl3ThreadContainer
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_5450EA090093 // Queue
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_5450EAAA0367 // Create
 HWL ME_5459DB98029C // TerminatedConnection
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4911B69E037D_ME_5452248C02B8 // DoExecute
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_5452248C02B8 // Cleanup
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_54523C2D01FF // FreeAndNil
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsTransporterThread.pas'
 CONST extprop:rc:SelfName 'ncsTransporterThread'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsTransporterThread'

ref; // ME_5452248C02B8 TncsTransporterThread

FORWARD ME_5460B6230039

: ME_545224C80036
 CONST UID '545224C80036'
 CONST Name 'IOHandler'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5460B6230039 // TncsTransporterIOThread
 ;
 : Target WL 'ME_538DDC890328' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAbstractAdapter
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_545224C80036 IOHandler

: ME_545B3DEA0268
 CONST UID '545B3DEA0268'
 CONST Name 'ReleaseIOHandler'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_5460B6230039 // TncsTransporterIOThread
 ;

ref; // ME_545B3DEA0268 ReleaseIOHandler

: ME_5460BE3D03E2
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5460B6230039 // TncsTransporterIOThread
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_5460BE3D03E2 

: ME_479731C50290_ME_5460B6230039
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_5460B6230039 Cleanup

: ME_5459DB98029C_ME_5460B6230039
 : Original HWL ME_5459DB98029C // TerminatedConnection
 ;
 CONST OpKind opkind_Overridden
ref; // ME_5459DB98029C_ME_5460B6230039 TerminatedConnection

: ME_5460B6230039
 CONST UID '5460B6230039'
 CONST Name 'TncsTransporterIOThread'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( HWL ME_5452248C02B8 // TncsTransporterThread
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_545224C80036 // IOHandler
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_545B3DEA0268 // ReleaseIOHandler
 )
 ; // Operations
 : Overridden
   Seq: ( ME_479731C50290_ME_5460B6230039 // Cleanup
 ME_5459DB98029C_ME_5460B6230039 // TerminatedConnection
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_5460BE3D03E2 // FreeAndNil
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsTransporterIOThread.pas'
 CONST extprop:rc:SelfName 'ncsTransporterIOThread'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsTransporterIOThread'

ref; // ME_5460B6230039 TncsTransporterIOThread

FORWARD ME_54534F1A00BF

FORWARD ME_5453828F0059

: ME_545382B4034A
 CONST UID '545382B4034A'
 CONST Name 'c_ReadTimeout'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5453828F0059 // ThreadTimeouts
 ;
 CONST Value 300
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 300

ref; // ME_545382B4034A c_ReadTimeout

: ME_5453828F0059
 CONST UID '5453828F0059'
 CONST Name 'ThreadTimeouts'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 : Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 : Attributes
   Seq: ( HWL ME_545382B4034A // c_ReadTimeout
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_5453828F0059 ThreadTimeouts

: ME_5453795603AE
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 : Target WL 'ME_47E150FF028A' '4AB0997B00A2.pas.ms.script' // TStream
 ;

ref; // ME_5453795603AE 

: ME_5453795B02A8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 : Target WL 'ME_538DE3F001DC' '47913B47006E.pas.ms.script' // Tl3TempMemoryStream
 ;

ref; // ME_5453795B02A8 

: ME_545388B80110
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_545388B80110 

: ME_54538F000128
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 : Target WL 'ME_4CDD241C0184' '47913B47006E.pas.ms.script' // l3System
 ;

ref; // ME_54538F000128 

: ME_54539217001B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_54539217001B 

FORWARD ME_54539F4702B1

: ME_545B8147003C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 : Target HWL ME_54539F4702B1 // TncsMessageFactory
 ;

ref; // ME_545B8147003C 

: ME_546306C60283
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 : Target WL 'ME_5461CFB8002C' '484A470100DD.pas.ms.script' // TncsMessageKind
 ;

ref; // ME_546306C60283 

FORWARD ME_548AC7FB0046

: ME_548AC9510214
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 : Target HWL ME_548AC7FB0046 // ncsProfile
 ;

ref; // ME_548AC9510214 

: ME_4911B69E037D_ME_54534F1A00BF
 : Original WL 'ME_4911B69E037D' '47913B47006E.pas.ms.script' // DoExecute
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4911B69E037D_ME_54534F1A00BF DoExecute

: ME_54534F1A00BF
 CONST UID '54534F1A00BF'
 CONST Name 'TncsReceiveThread'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( HWL ME_5460B6230039 // TncsTransporterIOThread
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_4911B69E037D_ME_54534F1A00BF // DoExecute
 )
 ; // Overridden
 : Constants
   Seq: ( HWL ME_5453828F0059 // ThreadTimeouts
 )
 ; // Constants
 : Dependencies
   Seq: ( ME_5453795603AE // TStream
 ME_5453795B02A8 // Tl3TempMemoryStream
 ME_545388B80110 // FreeAndNil
 ME_54538F000128 // l3System
 ME_54539217001B // TncsMessage
 ME_545B8147003C // TncsMessageFactory
 ME_546306C60283 // TncsMessageKind
 ME_548AC9510214 // ncsProfile
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsReceiveThread.pas'
 CONST extprop:rc:SelfName 'ncsReceiveThread'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsReceiveThread'

ref; // ME_54534F1A00BF TncsReceiveThread

FORWARD ME_5461D6C30025

: ME_5461D95F00E6
 CONST UID '5461D95F00E6'
 CONST Name 'Message'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5461D95F00E6 Message

: ME_5461D977016B
 CONST UID '5461D977016B'
 CONST Name 'Reply'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5461D977016B Reply

: ME_5463228D00A9
 CONST UID '5463228D00A9'
 CONST Name 'f_Event'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 : Target WL 'ME_491D9DB8010F' '4AB0997B00A2.pas.ms.script' // TEvent
 ;

ref; // ME_5463228D00A9 f_Event

FORWARD ME_5461D8CE0020

: ME_5461D8E50366
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_5461D8E50366 aMessage

: ME_5461D8D70179
 CONST UID '5461D8D70179'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5461D8CE0020 // Create
 ;
 : Parameters
   Seq: ( ME_5461D8E50366 // aMessage
 )
 ; // Parameters

ref; // ME_5461D8D70179 DoIt

: ME_5461D8CE0020
 CONST UID '5461D8CE0020'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 : Operations
   Seq: ( HWL ME_5461D8D70179 // DoIt
 )
 ; // Operations

ref; // ME_5461D8CE0020 Create

FORWARD ME_5463220800C9

: ME_54633E840128
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5463220800C9 // RequestEvent
 ;
 : Target WL 'ME_54509FEC02EB' '47D0290B016D.pas.ms.script' // l3CreateStringGUID
 ;

ref; // ME_54633E840128 

: ME_5463220800C9
 CONST UID '5463220800C9'
 CONST Name 'RequestEvent'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 : Dependencies
   Seq: ( ME_54633E840128 // l3CreateStringGUID
 )
 ; // Dependencies

ref; // ME_5463220800C9 RequestEvent

FORWARD ME_546335030341

: ME_54633B0002A6
 CONST Name 'aTimeOut'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47BC524C0245' '4AB0C3C60310.pas.ms.script' // LongWord
 ;
 CONST Value 'INFINITE'
 : ValueType WL 'ME_483C21B0003E' '4AB0C3F60375.pas.ms.script' // Timeouts
 ;
 CONST extprop:pas:Value 'INFINITE'

ref; // ME_54633B0002A6 aTimeOut

: ME_546335100360
 CONST UID '546335100360'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_546335030341 // WaitForReply
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_54633B0002A6 // aTimeOut
 )
 ; // Parameters

ref; // ME_546335100360 DoIt

: ME_546335030341
 CONST UID '546335030341'
 CONST Name 'WaitForReply'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 : Operations
   Seq: ( HWL ME_546335100360 // DoIt
 )
 ; // Operations

ref; // ME_546335030341 WaitForReply

: ME_5464AAB30031
 CONST UID '5464AAB30031'
 CONST Name 'AbortWait'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;

ref; // ME_5464AAB30031 AbortWait

: ME_5461FCBB01A1
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_5461FCBB01A1 

: ME_5463354D01FF
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 : Target WL 'ME_4CDD241C0184' '47913B47006E.pas.ms.script' // l3System
 ;

ref; // ME_5463354D01FF 

: ME_479731C50290_ME_5461D6C30025
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_5461D6C30025 Cleanup

: ME_5461D6C30025
 CONST UID '5461D6C30025'
 CONST Name 'TncsReplyDescription'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_5461D95F00E6 // Message
 HWL ME_5461D977016B // Reply
 HWL ME_5463228D00A9 // f_Event
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_5461D8CE0020 // Create
 HWL ME_5463220800C9 // RequestEvent
 HWL ME_546335030341 // WaitForReply
 HWL ME_5464AAB30031 // AbortWait
 )
 ; // Operations
 : Overridden
   Seq: ( ME_479731C50290_ME_5461D6C30025 // Cleanup
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_5461FCBB01A1 // FreeAndNil
 ME_5463354D01FF // l3System
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsReplyDescription.pas'
 CONST extprop:rc:SelfName 'ncsReplyDescription'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsReplyDescription'

ref; // ME_5461D6C30025 TncsReplyDescription

FORWARD ME_5460A4DB018A

FORWARD ME_5464B4730055

: ME_5465AB2B00CA
 CONST UID '5465AB2B00CA'
 CONST Name 'Connected'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Есть физический коннект' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent HWL ME_5464B4730055 // IncsTransporter
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" false

ref; // ME_5465AB2B00CA Connected

: ME_546608F101DE
 CONST UID '546608F101DE'
 CONST Name 'ClientID'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent HWL ME_5464B4730055 // IncsTransporter
 ;
 : Target WL 'ME_537F4A04037C' '52FBB2FC0386.pas.ms.script' // TCsClientId
 ;
 CONST "pm" false

ref; // ME_546608F101DE ClientID

: ME_5486B96A0025
 CONST UID '5486B96A0025'
 CONST Name 'Processing'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 %SUMMARY 'Есть полноценная обработка сообщений' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent HWL ME_5464B4730055 // IncsTransporter
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" false

ref; // ME_5486B96A0025 Processing

: ME_548FEF4F002E
 CONST UID '548FEF4F002E'
 CONST Name 'SessionID'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent HWL ME_5464B4730055 // IncsTransporter
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_548FEF4F002E SessionID

: ME_5464B4F800B5
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_5464B4F800B5 aMessage

: ME_5464B4E900DA
 CONST UID '5464B4E900DA'
 CONST Name 'Send'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_5464B4730055 // IncsTransporter
 ;
 : Parameters
   Seq: ( ME_5464B4F800B5 // aMessage
 )
 ; // Parameters

ref; // ME_5464B4E900DA Send

: ME_547C4DC000DF
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_547C4DC000DF aMessage

: ME_547C4DC0010E
 CONST Name 'theReply'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_547C4DC0010E theReply

: ME_547C4DC0014D
 CONST Name 'aTimeOut'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47BC524C0245' '4AB0C3C60310.pas.ms.script' // LongWord
 ;
 CONST Value 'INFINITE'
 : ValueType WL 'ME_483C21B0003E' '4AB0C3F60375.pas.ms.script' // Timeouts
 ;
 CONST extprop:pas:Value 'INFINITE'

ref; // ME_547C4DC0014D aTimeOut

: ME_5464B52F02D5
 CONST UID '5464B52F02D5'
 CONST Name 'WaitForReply'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_5464B4730055 // IncsTransporter
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_547C4DC000DF // aMessage
 ME_547C4DC0010E // theReply
 ME_547C4DC0014D // aTimeOut
 )
 ; // Parameters

ref; // ME_5464B52F02D5 WaitForReply

: ME_5464B4730055
 CONST UID '5464B4730055'
 CONST GUID 'CE5512DA-5FA9-423C-A266-65F24CF2501C'
 CONST Name 'IncsTransporter'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 : Attributes
   Seq: ( HWL ME_5465AB2B00CA // Connected
 HWL ME_546608F101DE // ClientID
 HWL ME_5486B96A0025 // Processing
 HWL ME_548FEF4F002E // SessionID
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_5464B4E900DA // Send
 HWL ME_5464B52F02D5 // WaitForReply
 )
 ; // Operations
 CONST extprop:rc:SelfName 'ncsTransporter'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5464B4730055 IncsTransporter

FORWARD ME_5464B37E01ED

: ME_5464B4A20373
 CONST UID '5464B4A20373'
 CONST Name 'rMessage'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent HWL ME_5464B37E01ED // TncsExecuteContext
 ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_5464B4A20373 rMessage

: ME_5464B4B80072
 CONST UID '5464B4B80072'
 CONST Name 'rTransporter'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_ref
 : Parent HWL ME_5464B37E01ED // TncsExecuteContext
 ;
 : Target HWL ME_5464B4730055 // IncsTransporter
 ;

ref; // ME_5464B4B80072 rTransporter

FORWARD ME_5464B3AA0087

: ME_5464B3D00211
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_5464B3D00211 aMessage

: ME_5464B78E0275
 CONST Name 'aTransporter'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5464B4730055 // IncsTransporter
 ;

ref; // ME_5464B78E0275 aTransporter

: ME_5464B3B5000D
 CONST UID '5464B3B5000D'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5464B3AA0087 // C
 ;
 : Parameters
   Seq: ( ME_5464B3D00211 // aMessage
 ME_5464B78E0275 // aTransporter
 )
 ; // Parameters

ref; // ME_5464B3B5000D DoIt

: ME_5464B3AA0087
 CONST UID '5464B3AA0087'
 CONST Name 'C'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5464B37E01ED // TncsExecuteContext
 ;
 : Operations
   Seq: ( HWL ME_5464B3B5000D // DoIt
 )
 ; // Operations

ref; // ME_5464B3AA0087 C

: ME_5464B37E01ED
 CONST UID '5464B37E01ED'
 CONST Name 'TncsExecuteContext'
 CONST Class class_Class
 : Stereotype st_StaticObject ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 : Attributes
   Seq: ( HWL ME_5464B4A20373 // rMessage
 HWL ME_5464B4B80072 // rTransporter
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_5464B3AA0087 // C
 )
 ; // Operations
 CONST extprop:rc:SelfName 'ncsExecuteContext'

ref; // ME_5464B37E01ED TncsExecuteContext

FORWARD ME_5460731E025E

: ME_5464B3F4039B
 CONST Name 'aContext'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5464B37E01ED // TncsExecuteContext
 ;

ref; // ME_5464B3F4039B aContext

: ME_54607DDC0159
 CONST UID '54607DDC0159'
 CONST Name 'Execute'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_5460731E025E // IncsExecutor
 ;
 : Parameters
   Seq: ( ME_5464B3F4039B // aContext
 )
 ; // Parameters

ref; // ME_54607DDC0159 Execute

: ME_5460731E025E
 CONST UID '5460731E025E'
 CONST GUID 'A6EB1A21-7939-4C8E-B5BC-65A97C27D138'
 CONST Name 'IncsExecutor'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 : Operations
   Seq: ( HWL ME_54607DDC0159 // Execute
 )
 ; // Operations
 CONST extprop:rc:SelfName 'ncsExecutor'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5460731E025E IncsExecutor

FORWARD ME_5460829B0384

: ME_5460A53E01D7
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_5460A53E01D7 aMessage

: ME_546082B801F3
 CONST UID '546082B801F3'
 CONST Name 'MakeExecutor'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_5460829B0384 // IncsMessageExecutorFactory
 ;
 : Target HWL ME_5460731E025E // IncsExecutor
 ;
 : Parameters
   Seq: ( ME_5460A53E01D7 // aMessage
 )
 ; // Parameters

ref; // ME_546082B801F3 MakeExecutor

: ME_5460829B0384
 CONST UID '5460829B0384'
 CONST GUID 'EB847F25-81CC-421B-ADFF-D135A33AC78B'
 CONST Name 'IncsMessageExecutorFactory'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 : Operations
   Seq: ( HWL ME_546082B801F3 // MakeExecutor
 )
 ; // Operations
 CONST extprop:rc:SelfName 'ncsMessageExecutorFactory'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5460829B0384 IncsMessageExecutorFactory

: ME_5460C1A00144
 CONST UID '5460C1A00144'
 CONST Name 'PIncsMessageExecutorFactory'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 : Inherits
   Seq: ( HWL ME_5460829B0384 // IncsMessageExecutorFactory
 )
 ; // Inherits
 CONST "isPointer" true
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5460C1A00144 PIncsMessageExecutorFactory

FORWARD ME_5465A598039E

: ME_5451F5060233
 CONST Name 'aServerHost'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_5451F5060233 aServerHost

: ME_5451F5060262
 CONST Name 'aServerPort'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_5451F5060262 aServerPort

: ME_548FEFC000C2
 CONST Name 'aSessionID'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_548FEFC000C2 aSessionID

: ME_544A1FD802E9
 CONST UID '544A1FD802E9'
 CONST Name 'Connect'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5465A598039E // IncsClientTransporter
 ;
 : Parameters
   Seq: ( ME_5451F5060233 // aServerHost
 ME_5451F5060262 // aServerPort
 ME_548FEFC000C2 // aSessionID
 )
 ; // Parameters

ref; // ME_544A1FD802E9 Connect

: ME_547C1A5702EF
 CONST Name 'Immidiate'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value false
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value false

ref; // ME_547C1A5702EF Immidiate

: ME_544A1FF00062
 CONST UID '544A1FF00062'
 CONST Name 'Disconnect'
 CONST Class class_Operation
 %SUMMARY 'Immidiate = True - отрубить сразу'#13#10'Immidiate = False - дождаться завершения обмена послав ncsDisconnect и дождавшись ответа' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_5465A598039E // IncsClientTransporter
 ;
 : Parameters
   Seq: ( ME_547C1A5702EF // Immidiate
 )
 ; // Parameters

ref; // ME_544A1FF00062 Disconnect

: ME_5464B4E900DA_ME_5465A598039E
 : Original HWL ME_5464B4E900DA // Send
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5464B4E900DA_ME_5465A598039E Send

: ME_5464B52F02D5_ME_5465A598039E
 : Original HWL ME_5464B52F02D5 // WaitForReply
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5464B52F02D5_ME_5465A598039E WaitForReply

: ME_5465AB2B00CA_ME_5465A598039E
 : Original HWL ME_5465AB2B00CA // Connected
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5465AB2B00CA_ME_5465A598039E Connected

: ME_546608F101DE_ME_5465A598039E
 : Original HWL ME_546608F101DE // ClientID
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_546608F101DE_ME_5465A598039E ClientID

: ME_5486B96A0025_ME_5465A598039E
 : Original HWL ME_5486B96A0025 // Processing
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5486B96A0025_ME_5465A598039E Processing

: ME_548FEF4F002E_ME_5465A598039E
 : Original HWL ME_548FEF4F002E // SessionID
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_548FEF4F002E_ME_5465A598039E SessionID

: ME_5465A598039E
 CONST UID '5465A598039E'
 CONST GUID 'CD83C556-C3C5-40FA-91B1-6C1CA7CF87D7'
 CONST Name 'IncsClientTransporter'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 : Inherits
   Seq: ( HWL ME_5464B4730055 // IncsTransporter
 )
 ; // Inherits
 : Operations
   Seq: ( HWL ME_544A1FD802E9 // Connect
 HWL ME_544A1FF00062 // Disconnect
 )
 ; // Operations
 : Implemented
   Seq: ( ME_5464B4E900DA_ME_5465A598039E // Send
 ME_5464B52F02D5_ME_5465A598039E // WaitForReply
 ME_5465AB2B00CA_ME_5465A598039E // Connected
 ME_546608F101DE_ME_5465A598039E // ClientID
 ME_5486B96A0025_ME_5465A598039E // Processing
 ME_548FEF4F002E_ME_5465A598039E // SessionID
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'ncsClientTransporter'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5465A598039E IncsClientTransporter

FORWARD ME_5465A5AB0324

: ME_5459E3150030
 CONST UID '5459E3150030'
 CONST Name 'Terminated'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" false

ref; // ME_5459E3150030 Terminated

: ME_5492AD2202E7
 CONST Name 'IsMainSocket'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5492AD2202E7 IsMainSocket

: ME_545335BF0283
 CONST UID '545335BF0283'
 CONST Name 'ProcessMessages'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 : Parameters
   Seq: ( ME_5492AD2202E7 // IsMainSocket
 )
 ; // Parameters

ref; // ME_545335BF0283 ProcessMessages

: ME_545CC00401A7
 CONST Name 'WaitForTermination'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST Value true
 : ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST extprop:pas:Value true

ref; // ME_545CC00401A7 WaitForTermination

: ME_5459D46D01FE
 CONST UID '5459D46D01FE'
 CONST Name 'Terminate'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 : Parameters
   Seq: ( ME_545CC00401A7 // WaitForTermination
 )
 ; // Parameters

ref; // ME_5459D46D01FE Terminate

: ME_54918100017A
 CONST Name 'aHandler'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_538DDC890328' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAbstractAdapter
 ;

ref; // ME_54918100017A aHandler

: ME_549180E701E0
 CONST UID '549180E701E0'
 CONST Name 'RegisterSendBackHandler'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 : Parameters
   Seq: ( ME_54918100017A // aHandler
 )
 ; // Parameters

ref; // ME_549180E701E0 RegisterSendBackHandler

: ME_5464B4E900DA_ME_5465A5AB0324
 : Original HWL ME_5464B4E900DA // Send
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5464B4E900DA_ME_5465A5AB0324 Send

: ME_5464B52F02D5_ME_5465A5AB0324
 : Original HWL ME_5464B52F02D5 // WaitForReply
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5464B52F02D5_ME_5465A5AB0324 WaitForReply

: ME_5465AB2B00CA_ME_5465A5AB0324
 : Original HWL ME_5465AB2B00CA // Connected
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5465AB2B00CA_ME_5465A5AB0324 Connected

: ME_546608F101DE_ME_5465A5AB0324
 : Original HWL ME_546608F101DE // ClientID
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_546608F101DE_ME_5465A5AB0324 ClientID

: ME_5486B96A0025_ME_5465A5AB0324
 : Original HWL ME_5486B96A0025 // Processing
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5486B96A0025_ME_5465A5AB0324 Processing

: ME_548FEF4F002E_ME_5465A5AB0324
 : Original HWL ME_548FEF4F002E // SessionID
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_548FEF4F002E_ME_5465A5AB0324 SessionID

: ME_5465A5AB0324
 CONST UID '5465A5AB0324'
 CONST GUID '2DF810B8-EB59-4A34-8945-D6D35E58B03C'
 CONST Name 'IncsServerTransporter'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 : Inherits
   Seq: ( HWL ME_5464B4730055 // IncsTransporter
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_5459E3150030 // Terminated
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_545335BF0283 // ProcessMessages
 HWL ME_5459D46D01FE // Terminate
 HWL ME_549180E701E0 // RegisterSendBackHandler
 )
 ; // Operations
 : Implemented
   Seq: ( ME_5464B4E900DA_ME_5465A5AB0324 // Send
 ME_5464B52F02D5_ME_5465A5AB0324 // WaitForReply
 ME_5465AB2B00CA_ME_5465A5AB0324 // Connected
 ME_546608F101DE_ME_5465A5AB0324 // ClientID
 ME_5486B96A0025_ME_5465A5AB0324 // Processing
 ME_548FEF4F002E_ME_5465A5AB0324 // SessionID
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'ncsServerTransporter'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5465A5AB0324 IncsServerTransporter

FORWARD ME_5490036B0204

: ME_5490037B017D
 CONST UID '5490037B017D'
 CONST Name 'ncs_skSend'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5490036B0204 // TncsSocketKind
 ;

ref; // ME_5490037B017D ncs_skSend

: ME_5490038D0132
 CONST UID '5490038D0132'
 CONST Name 'ncs_skReceive'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5490036B0204 // TncsSocketKind
 ;

ref; // ME_5490038D0132 ncs_skReceive

: ME_5490036B0204
 CONST UID '5490036B0204'
 CONST Name 'TncsSocketKind'
 CONST Class class_Class
 : Stereotype st_Enum ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 : Attributes
   Seq: ( HWL ME_5490037B017D // ncs_skSend
 HWL ME_5490038D0132 // ncs_skReceive
 )
 ; // Attributes
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5490036B0204 TncsSocketKind

: ME_5460A4DB018A
 CONST UID '5460A4DB018A'
 CONST Name 'ncsMessageInterfaces'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Children
   Seq: ( HWL ME_5464B4730055 // IncsTransporter
 HWL ME_5464B37E01ED // TncsExecuteContext
 HWL ME_5460731E025E // IncsExecutor
 HWL ME_5460829B0384 // IncsMessageExecutorFactory
 HWL ME_5460C1A00144 // PIncsMessageExecutorFactory
 HWL ME_5465A598039E // IncsClientTransporter
 HWL ME_5465A5AB0324 // IncsServerTransporter
 HWL ME_5490036B0204 // TncsSocketKind
 )
 ; // Children
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsMessageInterfaces.pas'

ref; // ME_5460A4DB018A ncsMessageInterfaces

FORWARD ME_5450E9A0034A

FORWARD ME_545201B70046

: ME_545201E602F7
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_545201E602F7 aMessage

: ME_545201DF0064
 CONST UID '545201DF0064'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_545201B70046 // Send
 ;
 : Parameters
   Seq: ( ME_545201E602F7 // aMessage
 )
 ; // Parameters

ref; // ME_545201DF0064 DoIt

: ME_54523F9A03D0
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_545201B70046 // Send
 ;
 : Target WL 'ME_538DE3F001DC' '47913B47006E.pas.ms.script' // Tl3TempMemoryStream
 ;

ref; // ME_54523F9A03D0 

: ME_54523FC602CF
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_545201B70046 // Send
 ;
 : Target WL 'ME_47E150FF028A' '4AB0997B00A2.pas.ms.script' // TStream
 ;

ref; // ME_54523FC602CF 

: ME_545201B70046
 CONST UID '545201B70046'
 CONST Name 'Send'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5450E9A0034A // TncsSendThread
 ;
 : Operations
   Seq: ( HWL ME_545201DF0064 // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_54523F9A03D0 // Tl3TempMemoryStream
 ME_54523FC602CF // TStream
 )
 ; // Dependencies

ref; // ME_545201B70046 Send

: ME_5450F0BE03BA
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5450E9A0034A // TncsSendThread
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_5450F0BE03BA 

: ME_548AC9640012
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5450E9A0034A // TncsSendThread
 ;
 : Target HWL ME_548AC7FB0046 // ncsProfile
 ;

ref; // ME_548AC9640012 

: ME_4911B69E037D_ME_5450E9A0034A
 : Original WL 'ME_4911B69E037D' '47913B47006E.pas.ms.script' // DoExecute
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4911B69E037D_ME_5450E9A0034A DoExecute

: ME_5450E9A0034A
 CONST UID '5450E9A0034A'
 CONST Name 'TncsSendThread'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( HWL ME_5460B6230039 // TncsTransporterIOThread
 )
 ; // Inherits
 : Operations
   Seq: ( HWL ME_545201B70046 // Send
 )
 ; // Operations
 : Overridden
   Seq: ( ME_4911B69E037D_ME_5450E9A0034A // DoExecute
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_5450F0BE03BA // FreeAndNil
 ME_548AC9640012 // ncsProfile
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsSendThread.pas'
 CONST extprop:rc:SelfName 'ncsSendThread'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsSendThread'

ref; // ME_5450E9A0034A TncsSendThread

FORWARD ME_5453986402AC

: ME_5450A0370225
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544E079E0253 // TncsMessage
 ;
 : Target WL 'ME_54509FEC02EB' '47D0290B016D.pas.ms.script' // l3CreateStringGUID
 ;

ref; // ME_5450A0370225 

: ME_53AC03EE01FD_ME_544E079E0253
 : Original WL 'ME_53AC03EE01FD' '53B24DFD01FF.pas.ms.script' // GetTaggedDataType
 ;
 CONST OpKind opkind_Implemented
 CONST "is static" true
ref; // ME_53AC03EE01FD_ME_544E079E0253 GetTaggedDataType

: ME_47A042E100E2_ME_544E079E0253
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_544E079E0253 InitFields

: ME_549413590379_ME_544E079E0253
 : Original WL 'ME_549413590379' '53B15D5603E3.pas.ms.script' // NeedSendRawDataAsBinary
 ;
 CONST OpKind opkind_Overridden
ref; // ME_549413590379_ME_544E079E0253 NeedSendRawDataAsBinary

: ME_544E079E0253
 CONST UID '544E079E0253'
 CONST Name 'TncsMessage'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5453986402AC // ncsMessage
 ;
 : Inherits
   Seq: ( WL 'ME_534572370056' '47913B47006E.pas.ms.script' // Tl3Tag
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_53AC01CD0335' '53B15D5603E3.pas.ms.script' // evdTagHolder
 WL 'ME_544E01AA03BA' '484A470100DD.pas.ms.script' // csMessage
 )
 ; // Implements
 : Implemented
   Seq: ( ME_53AC03EE01FD_ME_544E079E0253 // GetTaggedDataType
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_47A042E100E2_ME_544E079E0253 // InitFields
 ME_549413590379_ME_544E079E0253 // NeedSendRawDataAsBinary
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_5450A0370225 // l3CreateStringGUID
 )
 ; // Dependencies
 CONST extprop:rc:SelfName 'ncsMessage'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_544E079E0253 TncsMessage

: ME_5453989A0161
 CONST UID '5453989A0161'
 CONST Name 'TncsMessageClass'
 CONST Class class_Class
 : Stereotype st_Typedef ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5453986402AC // ncsMessage
 ;
 : Inherits
   Seq: ( HWL ME_544E079E0253 // TncsMessage
 )
 ; // Inherits
 CONST "isClassRef" true
 CONST extprop:rc:SelfName 'ncsMessageClass'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5453989A0161 TncsMessageClass

: ME_54649C7C00E7
 CONST UID '54649C7C00E7'
 CONST Name 'TncsInvalidMessage'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5453986402AC // ncsMessage
 ;
 : Inherits
   Seq: ( HWL ME_544E079E0253 // TncsMessage
 )
 ; // Inherits
 CONST extprop:rc:SelfName 'ncsInvalidMessage'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_54649C7C00E7 TncsInvalidMessage

FORWARD ME_547831BD02E5

: ME_547831E30313
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_547831E30313 aMessage

: ME_547831D300BE
 CONST UID '547831D300BE'
 CONST Name 'Create'
 CONST Class class_Operation
 : Stereotype st_ctor::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_547831BD02E5 // TncsReply
 ;
 : Parameters
   Seq: ( ME_547831E30313 // aMessage
 )
 ; // Parameters

ref; // ME_547831D300BE Create

: ME_547831BD02E5
 CONST UID '547831BD02E5'
 CONST Name 'TncsReply'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5453986402AC // ncsMessage
 ;
 : Inherits
   Seq: ( HWL ME_544E079E0253 // TncsMessage
 )
 ; // Inherits
 : Operations
   Seq: ( HWL ME_547831D300BE // Create
 )
 ; // Operations
 CONST extprop:rc:SelfName 'ncsReply'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_547831BD02E5 TncsReply

: ME_547C1F31030C
 CONST UID '547C1F31030C'
 CONST Name 'TncsDIsconnect'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5453986402AC // ncsMessage
 ;
 : Inherits
   Seq: ( HWL ME_544E079E0253 // TncsMessage
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_547C1CD001E3' '484A470100DD.pas.ms.script' // csDIsconnect
 )
 ; // Implements
 CONST extprop:rc:SelfName 'ncsDIsconnect'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_547C1F31030C TncsDIsconnect

: ME_547C1F3F025A
 CONST UID '547C1F3F025A'
 CONST Name 'TncsDIsconnectReply'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5453986402AC // ncsMessage
 ;
 : Inherits
   Seq: ( HWL ME_547831BD02E5 // TncsReply
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_547C1CE20205' '484A470100DD.pas.ms.script' // csDIsconnectReply
 )
 ; // Implements
 CONST extprop:rc:SelfName 'ncsDIsconnectReply'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_547C1F3F025A TncsDIsconnectReply

: ME_5453986402AC
 CONST UID '5453986402AC'
 CONST Name 'ncsMessage'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Children
   Seq: ( HWL ME_544E079E0253 // TncsMessage
 HWL ME_5453989A0161 // TncsMessageClass
 HWL ME_54649C7C00E7 // TncsInvalidMessage
 HWL ME_547831BD02E5 // TncsReply
 HWL ME_547C1F31030C // TncsDIsconnect
 HWL ME_547C1F3F025A // TncsDIsconnectReply
 )
 ; // Children
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsMessage.pas'

ref; // ME_5453986402AC ncsMessage

FORWARD ME_54539F0C00AD

: ME_54539F2201C3
 CONST UID '54539F2201C3'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_54539F0C00AD // TncsMessageClassList
 ;
 : Target HWL ME_5453989A0161 // TncsMessageClass
 ;

ref; // ME_54539F2201C3 ItemType

: ME_47B07CF403D0_ME_54539F0C00AD
 : Original WL 'ME_47B07CF403D0' '47913B47006E.pas.ms.script' // IsSameItems
 ;
 CONST OpKind opkind_Implemented
 CONST "ifndef" 'l3Items_IsAtomic'
ref; // ME_47B07CF403D0_ME_54539F0C00AD IsSameItems

: ME_47B2C42A0163_ME_54539F0C00AD
 : Original WL 'ME_47B2C42A0163' '47913B47006E.pas.ms.script' // AssignItem
 ;
 CONST OpKind opkind_Implemented
 CONST "ifdef" 'l3Items_NeedsAssignItem'
 CONST "ifndef" 'l3Items_NoSort'
ref; // ME_47B2C42A0163_ME_54539F0C00AD AssignItem

: ME_47B99D4503A2_ME_54539F0C00AD
 : Original WL 'ME_47B99D4503A2' '47BB24D30205.pas.ms.script' // CompareExistingItems
 ;
 CONST OpKind opkind_Implemented
ref; // ME_47B99D4503A2_ME_54539F0C00AD CompareExistingItems

: ME_54539F0C00AD
 CONST UID '54539F0C00AD'
 CONST Name 'TncsMessageClassList'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.pas.ms.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_47B5782902DA' '47913B47006E.pas.ms.script' // l3PtrList
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_54539F2201C3 // ItemType
 )
 ; // Attributes
 : Implemented
   Seq: ( ME_47B07CF403D0_ME_54539F0C00AD // IsSameItems
 ME_47B2C42A0163_ME_54539F0C00AD // AssignItem
 ME_47B99D4503A2_ME_54539F0C00AD // CompareExistingItems
 )
 ; // Implemented
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsMessageClassList.pas'
 CONST extprop:rc:SelfName 'ncsMessageClassList'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsMessageClassList'

ref; // ME_54539F0C00AD TncsMessageClassList

: ME_54539F5D03D6
 CONST UID '54539F5D03D6'
 CONST Name 'f_List'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 : Target HWL ME_54539F0C00AD // TncsMessageClassList
 ;

ref; // ME_54539F5D03D6 f_List

: ME_545B868002AF
 CONST Name 'aClass'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5453989A0161 // TncsMessageClass
 ;

ref; // ME_545B868002AF aClass

: ME_545A23D30081
 CONST UID '545A23D30081'
 CONST Name 'Register'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 : Parameters
   Seq: ( ME_545B868002AF // aClass
 )
 ; // Parameters

ref; // ME_545A23D30081 Register

: ME_545B86850353
 CONST Name 'aClass'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5453989A0161 // TncsMessageClass
 ;

ref; // ME_545B86850353 aClass

: ME_545A23FB02E0
 CONST UID '545A23FB02E0'
 CONST Name 'UnRegister'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 : Parameters
   Seq: ( ME_545B86850353 // aClass
 )
 ; // Parameters

ref; // ME_545A23FB02E0 UnRegister

: ME_545A242C01AB
 CONST Name 'aMessageTag'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_545A242C01AB aMessageTag

: ME_545A24130098
 CONST UID '545A24130098'
 CONST Name 'Find'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 : Target HWL ME_5453989A0161 // TncsMessageClass
 ;
 : Parameters
   Seq: ( ME_545A242C01AB // aMessageTag
 )
 ; // Parameters

ref; // ME_545A24130098 Find

: ME_545B86710018
 CONST Name 'aStream'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47E150FF028A' '4AB0997B00A2.pas.ms.script' // TStream
 ;

ref; // ME_545B86710018 aStream

: ME_54538B990208
 CONST UID '54538B990208'
 CONST Name 'MakeFromEVD'
 CONST Class class_Operation
 : Stereotype st_static::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;
 : Parameters
   Seq: ( ME_545B86710018 // aStream
 )
 ; // Parameters

ref; // ME_54538B990208 MakeFromEVD

: ME_545B8677028E
 CONST Name 'aData'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_534572370056' '47913B47006E.pas.ms.script' // Tl3Tag
 ;

ref; // ME_545B8677028E aData

: ME_54538F64032E
 CONST UID '54538F64032E'
 CONST Name 'MakeFromTaggedData'
 CONST Class class_Operation
 : Stereotype st_static::Operation ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;
 : Parameters
   Seq: ( ME_545B8677028E // aData
 )
 ; // Parameters

ref; // ME_54538F64032E MakeFromTaggedData

: ME_545A292E0276
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_545A292E0276 

: ME_545A2BAB00FD
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 : Target WL 'ME_47614B2901AE' '4678193C009C.pas.ms.script' // Tl3Duplicates
 ;

ref; // ME_545A2BAB00FD 

: ME_479731C50290_ME_54539F4702B1
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_54539F4702B1 Cleanup

: ME_47A042E100E2_ME_54539F4702B1
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_54539F4702B1 InitFields

: ME_54539F4702B1
 CONST UID '54539F4702B1'
 CONST Name 'TncsMessageFactory'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_54539F5D03D6 // f_List
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_545A23D30081 // Register
 HWL ME_545A23FB02E0 // UnRegister
 HWL ME_545A24130098 // Find
 HWL ME_54538B990208 // MakeFromEVD
 HWL ME_54538F64032E // MakeFromTaggedData
 )
 ; // Operations
 : Overridden
   Seq: ( ME_479731C50290_ME_54539F4702B1 // Cleanup
 ME_47A042E100E2_ME_54539F4702B1 // InitFields
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_545A292E0276 // FreeAndNil
 ME_545A2BAB00FD // Tl3Duplicates
 )
 ; // Dependencies
 CONST "singleton" true
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsMessageFactory.pas'
 CONST extprop:rc:SelfName 'ncsMessageFactory'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsMessageFactory'

ref; // ME_54539F4702B1 TncsMessageFactory

FORWARD ME_545CBE61008B

: ME_545CC4210322
 CONST UID '545CC4210322'
 CONST Name 'l3Items_NoSort'
 CONST Class class_Class
 : Stereotype st_Define ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_545CBE61008B // TncsServerTransporterList
 ;
 CONST extprop:rc:SelfName 'Items_NoSort'

ref; // ME_545CC4210322 l3Items_NoSort

: ME_545CBE9103D8
 CONST UID '545CBE9103D8'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_545CBE61008B // TncsServerTransporterList
 ;
 : Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;

ref; // ME_545CBE9103D8 ItemType

: ME_545CBE61008B
 CONST UID '545CBE61008B'
 CONST Name 'TncsServerTransporterList'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.pas.ms.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_47B57D830369' '47913B47006E.pas.ms.script' // l3InterfaceRefList
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_545CBE9103D8 // ItemType
 )
 ; // Attributes
 : Children
   Seq: ( HWL ME_545CC4210322 // l3Items_NoSort
 )
 ; // Children
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsServerTransporterList.pas'
 CONST extprop:rc:SelfName 'ncsServerTransporterList'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsServerTransporterList'

ref; // ME_545CBE61008B TncsServerTransporterList

FORWARD ME_545CBED90193

: ME_545CBF0E0186
 CONST UID '545CBF0E0186'
 CONST Name 'f_Data'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_545CBED90193 // TncsServerTransporterPool
 ;
 : Target HWL ME_545CBE61008B // TncsServerTransporterList
 ;

ref; // ME_545CBF0E0186 f_Data

: ME_545CBF9100D6
 CONST Name 'aTransporter'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;

ref; // ME_545CBF9100D6 aTransporter

: ME_545CBF760027
 CONST UID '545CBF760027'
 CONST Name 'Register'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_545CBED90193 // TncsServerTransporterPool
 ;
 : Parameters
   Seq: ( ME_545CBF9100D6 // aTransporter
 )
 ; // Parameters

ref; // ME_545CBF760027 Register

: ME_545CBF9B00D6
 CONST Name 'aTransporter'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;

ref; // ME_545CBF9B00D6 aTransporter

: ME_545CBF9602E1
 CONST UID '545CBF9602E1'
 CONST Name 'UnRegister'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_545CBED90193 // TncsServerTransporterPool
 ;
 : Parameters
   Seq: ( ME_545CBF9B00D6 // aTransporter
 )
 ; // Parameters

ref; // ME_545CBF9602E1 UnRegister

: ME_545CBFA2006D
 CONST UID '545CBFA2006D'
 CONST Name 'TerminateAll'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_545CBED90193 // TncsServerTransporterPool
 ;

ref; // ME_545CBFA2006D TerminateAll

: ME_479731C50290_ME_545CBED90193
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_545CBED90193 Cleanup

: ME_47A042E100E2_ME_545CBED90193
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_545CBED90193 InitFields

: ME_545CBED90193
 CONST UID '545CBED90193'
 CONST Name 'TncsServerTransporterPool'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_53A03846011C' '53A038340371.pas.ms.script' // l3CriticalSectionHolder
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_545CBF0E0186 // f_Data
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_545CBF760027 // Register
 HWL ME_545CBF9602E1 // UnRegister
 HWL ME_545CBFA2006D // TerminateAll
 )
 ; // Operations
 : Overridden
   Seq: ( ME_479731C50290_ME_545CBED90193 // Cleanup
 ME_47A042E100E2_ME_545CBED90193 // InitFields
 )
 ; // Overridden
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsServerTransporterPool.pas'
 CONST extprop:rc:SelfName 'ncsServerTransporterPool'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsServerTransporterPool'

ref; // ME_545CBED90193 TncsServerTransporterPool

FORWARD ME_5461D6FC00F7

: ME_5461D7260382
 CONST UID '5461D7260382'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_5461D6FC00F7 // TncsReplyDecsriptionList
 ;
 : Target HWL ME_5461D6C30025 // TncsReplyDescription
 ;

ref; // ME_5461D7260382 ItemType

: ME_47B2C42A0163_ME_5461D6FC00F7
 : Original WL 'ME_47B2C42A0163' '47913B47006E.pas.ms.script' // AssignItem
 ;
 CONST OpKind opkind_Implemented
 CONST "ifdef" 'l3Items_NeedsAssignItem'
 CONST "ifndef" 'l3Items_NoSort'
ref; // ME_47B2C42A0163_ME_5461D6FC00F7 AssignItem

: ME_47B99D4503A2_ME_5461D6FC00F7
 : Original WL 'ME_47B99D4503A2' '47BB24D30205.pas.ms.script' // CompareExistingItems
 ;
 CONST OpKind opkind_Implemented
ref; // ME_47B99D4503A2_ME_5461D6FC00F7 CompareExistingItems

: ME_5461D6FC00F7
 CONST UID '5461D6FC00F7'
 CONST Name 'TncsReplyDecsriptionList'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.pas.ms.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_47B99E920196' '47913B47006E.pas.ms.script' // l3UncomparabeObjectRefList
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_5461D7260382 // ItemType
 )
 ; // Attributes
 : Implemented
   Seq: ( ME_47B2C42A0163_ME_5461D6FC00F7 // AssignItem
 ME_47B99D4503A2_ME_5461D6FC00F7 // CompareExistingItems
 )
 ; // Implemented
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsReplyDecsriptionList.pas'
 CONST extprop:rc:SelfName 'ncsReplyDecsriptionList'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsReplyDecsriptionList'

ref; // ME_5461D6FC00F7 TncsReplyDecsriptionList

FORWARD ME_54609BB100BB

: ME_54609BE1031F
 CONST UID '54609BE1031F'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_54609BB100BB // TncsExecutorFactoryList
 ;
 : Target HWL ME_5460829B0384 // IncsMessageExecutorFactory
 ;

ref; // ME_54609BE1031F ItemType

: ME_54609BB100BB
 CONST UID '54609BB100BB'
 CONST Name 'TncsExecutorFactoryList'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.pas.ms.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_47B57D630029' '47913B47006E.pas.ms.script' // l3InterfacePtrList
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_54609BE1031F // ItemType
 )
 ; // Attributes
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsExecutorFactoryList.pas'
 CONST extprop:rc:SelfName 'ncsExecutorFactoryList'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsExecutorFactoryList'

ref; // ME_54609BB100BB TncsExecutorFactoryList

FORWARD ME_54607384020A

FORWARD ME_5464A0E40234

: ME_5464A4DE0181
 CONST UID '5464A4DE0181'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5464A0E40234 // TncsInvalidExecutor
 ;

ref; // ME_5464A4DE0181 Create

: ME_5464A4E9009C
 CONST UID '5464A4E9009C'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5464A0E40234 // TncsInvalidExecutor
 ;
 : Inherits
   Seq: ( HWL ME_5464A4DE0181 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5460731E025E // IncsExecutor
 )
 ; // Implements

ref; // ME_5464A4E9009C Make

: ME_54607DDC0159_ME_5464A0E40234
 : Original HWL ME_54607DDC0159 // Execute
 ;
 CONST OpKind opkind_Implemented
ref; // ME_54607DDC0159_ME_5464A0E40234 Execute

: ME_5464A0E40234
 CONST UID '5464A0E40234'
 CONST Name 'TncsInvalidExecutor'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5460731E025E // IncsExecutor
 )
 ; // Implements
 : Operations
   Seq: ( HWL ME_5464A4DE0181 // Create
 HWL ME_5464A4E9009C // Make
 )
 ; // Operations
 : Implemented
   Seq: ( ME_54607DDC0159_ME_5464A0E40234 // Execute
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'ncsInvalidExecutor'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5464A0E40234 TncsInvalidExecutor

FORWARD ME_547C1FB30097

: ME_547C1FD9007B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_547C1FB30097 // TncsDisconnectExecutor
 ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_547C1FD9007B 

: ME_547C1FDD03A0
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_547C1FB30097 // TncsDisconnectExecutor
 ;
 : Target HWL ME_547C1F31030C // TncsDIsconnect
 ;

ref; // ME_547C1FDD03A0 

: ME_547C1FE10204
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_547C1FB30097 // TncsDisconnectExecutor
 ;
 : Target HWL ME_547C1F3F025A // TncsDIsconnectReply
 ;

ref; // ME_547C1FE10204 

: ME_54607DDC0159_ME_547C1FB30097
 : Original HWL ME_54607DDC0159 // Execute
 ;
 CONST OpKind opkind_Implemented
ref; // ME_54607DDC0159_ME_547C1FB30097 Execute

: ME_546082B801F3_ME_547C1FB30097
 : Original HWL ME_546082B801F3 // MakeExecutor
 ;
 CONST OpKind opkind_Implemented
ref; // ME_546082B801F3_ME_547C1FB30097 MakeExecutor

: ME_547C1FB30097
 CONST UID '547C1FB30097'
 CONST Name 'TncsDisconnectExecutor'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5460731E025E // IncsExecutor
 HWL ME_5460829B0384 // IncsMessageExecutorFactory
 )
 ; // Implements
 : Implemented
   Seq: ( ME_54607DDC0159_ME_547C1FB30097 // Execute
 ME_546082B801F3_ME_547C1FB30097 // MakeExecutor
 )
 ; // Implemented
 : Dependencies
   Seq: ( ME_547C1FD9007B // TncsMessage
 ME_547C1FDD03A0 // TncsDIsconnect
 ME_547C1FE10204 // TncsDIsconnectReply
 )
 ; // Dependencies
 CONST extprop:rc:SelfName 'ncsDisconnectExecutor'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_547C1FB30097 TncsDisconnectExecutor

: ME_54609BF500ED
 CONST UID '54609BF500ED'
 CONST Name 'f_List'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 : Target HWL ME_54609BB100BB // TncsExecutorFactoryList
 ;

ref; // ME_54609BF500ED f_List

: ME_547C200B02EA
 CONST UID '547C200B02EA'
 CONST Name 'f_DisconnectExecutor'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 : Target HWL ME_547C1FB30097 // TncsDisconnectExecutor
 ;

ref; // ME_547C200B02EA f_DisconnectExecutor

: ME_546083260154
 CONST Name 'aFactory'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5460829B0384 // IncsMessageExecutorFactory
 ;

ref; // ME_546083260154 aFactory

: ME_5460830D0295
 CONST UID '5460830D0295'
 CONST Name 'Register'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 : Parameters
   Seq: ( ME_546083260154 // aFactory
 )
 ; // Parameters

ref; // ME_5460830D0295 Register

: ME_5460832F028E
 CONST Name 'aFactory'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5460829B0384 // IncsMessageExecutorFactory
 ;

ref; // ME_5460832F028E aFactory

: ME_5460832C0080
 CONST UID '5460832C0080'
 CONST Name 'UnRegister'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 : Parameters
   Seq: ( ME_5460832F028E // aFactory
 )
 ; // Parameters

ref; // ME_5460832C0080 UnRegister

: ME_5460B06B03DE
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_5460B06B03DE aMessage

: ME_5460AEC800B8
 CONST UID '5460AEC800B8'
 CONST Name 'MakeExecutor'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 : Target HWL ME_5460731E025E // IncsExecutor
 ;
 : Parameters
   Seq: ( ME_5460B06B03DE // aMessage
 )
 ; // Parameters

ref; // ME_5460AEC800B8 MakeExecutor

: ME_5460A810027B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_5460A810027B 

: ME_5460C4460031
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 : Target WL 'ME_47289B590038' '4678193C009C.pas.ms.script' // PLong
 ;

ref; // ME_5460C4460031 

: ME_5464C855013F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 : Target WL 'ME_5461CFB8002C' '484A470100DD.pas.ms.script' // TncsMessageKind
 ;

ref; // ME_5464C855013F 

: ME_479731C50290_ME_54607384020A
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_54607384020A Cleanup

: ME_47A042E100E2_ME_54607384020A
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_54607384020A InitFields

: ME_54607384020A
 CONST UID '54607384020A'
 CONST Name 'TncsMessageExecutorFactory'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_54609BF500ED // f_List
 HWL ME_547C200B02EA // f_DisconnectExecutor
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_5460830D0295 // Register
 HWL ME_5460832C0080 // UnRegister
 HWL ME_5460AEC800B8 // MakeExecutor
 )
 ; // Operations
 : Overridden
   Seq: ( ME_479731C50290_ME_54607384020A // Cleanup
 ME_47A042E100E2_ME_54607384020A // InitFields
 )
 ; // Overridden
 : Children
   Seq: ( HWL ME_5464A0E40234 // TncsInvalidExecutor
 HWL ME_547C1FB30097 // TncsDisconnectExecutor
 )
 ; // Children
 : Dependencies
   Seq: ( ME_5460A810027B // FreeAndNil
 ME_5460C4460031 // PLong
 ME_5464C855013F // TncsMessageKind
 )
 ; // Dependencies
 CONST "singleton" true
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsMessageExecutorFactory.pas'
 CONST extprop:rc:SelfName 'ncsMessageExecutorFactory'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsMessageExecutorFactory'

ref; // ME_54607384020A TncsMessageExecutorFactory

FORWARD ME_5461D9EE0244

: ME_5461DA210250
 CONST UID '5461DA210250'
 CONST Name 'f_List'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 : Target HWL ME_5461D6FC00F7 // TncsReplyDecsriptionList
 ;

ref; // ME_5461DA210250 f_List

FORWARD ME_54633EAE039A

: ME_54633ECE02CA
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_54633ECE02CA aMessage

: ME_54633EB6031C
 CONST UID '54633EB6031C'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_54633EAE039A // FindDesc
 ;
 : Target HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 : Parameters
   Seq: ( ME_54633ECE02CA // aMessage
 )
 ; // Parameters

ref; // ME_54633EB6031C DoIt

: ME_54633EAE039A
 CONST UID '54633EAE039A'
 CONST Name 'FindDesc'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 : Operations
   Seq: ( HWL ME_54633EB6031C // DoIt
 )
 ; // Operations

ref; // ME_54633EAE039A FindDesc

: ME_54630A360321
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_54630A360321 aMessage

: ME_54630A1F0046
 CONST UID '54630A1F0046'
 CONST Name 'SubmitReply'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 : Parameters
   Seq: ( ME_54630A360321 // aMessage
 )
 ; // Parameters

ref; // ME_54630A1F0046 SubmitReply

: ME_54630A4F0322
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_54630A4F0322 aMessage

: ME_54630A3E001D
 CONST UID '54630A3E001D'
 CONST Name 'SubmitMessage'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 : Parameters
   Seq: ( ME_54630A4F0322 // aMessage
 )
 ; // Parameters

ref; // ME_54630A3E001D SubmitMessage

: ME_54630A7102CD
 CONST UID '54630A7102CD'
 CONST Name 'Clear'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;

ref; // ME_54630A7102CD Clear

: ME_547C4DD20008
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_547C4DD20008 aMessage

: ME_547C4DD20037
 CONST Name 'theReply'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_547C4DD20037 theReply

: ME_547C4DD20056
 CONST Name 'aTimeOut'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47BC524C0245' '4AB0C3C60310.pas.ms.script' // LongWord
 ;
 CONST Value 'INFINITE'
 : ValueType WL 'ME_483C21B0003E' '4AB0C3F60375.pas.ms.script' // Timeouts
 ;
 CONST extprop:pas:Value 'INFINITE'

ref; // ME_547C4DD20056 aTimeOut

: ME_54630A80027D
 CONST UID '54630A80027D'
 CONST Name 'WaitForReply'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   Seq: ( ME_547C4DD20008 // aMessage
 ME_547C4DD20037 // theReply
 ME_547C4DD20056 // aTimeOut
 )
 ; // Parameters

ref; // ME_54630A80027D WaitForReply

: ME_5461FC9C0368
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_5461FC9C0368 

: ME_5463131A0008
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 : Target HWL ME_5461D6C30025 // TncsReplyDescription
 ;

ref; // ME_5463131A0008 

: ME_54634144025A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 : Target WL 'ME_4CDD241C0184' '47913B47006E.pas.ms.script' // l3System
 ;

ref; // ME_54634144025A 

: ME_479731C50290_ME_5461D9EE0244
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_5461D9EE0244 Cleanup

: ME_47A042E100E2_ME_5461D9EE0244
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_5461D9EE0244 InitFields

: ME_5461D9EE0244
 CONST UID '5461D9EE0244'
 CONST Name 'TncsReplyWaiter'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_53A03846011C' '53A038340371.pas.ms.script' // l3CriticalSectionHolder
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_5461DA210250 // f_List
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_54633EAE039A // FindDesc
 HWL ME_54630A1F0046 // SubmitReply
 HWL ME_54630A3E001D // SubmitMessage
 HWL ME_54630A7102CD // Clear
 HWL ME_54630A80027D // WaitForReply
 )
 ; // Operations
 : Overridden
   Seq: ( ME_479731C50290_ME_5461D9EE0244 // Cleanup
 ME_47A042E100E2_ME_5461D9EE0244 // InitFields
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_5461FC9C0368 // FreeAndNil
 ME_5463131A0008 // TncsReplyDescription
 ME_54634144025A // l3System
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsReplyWaiter.pas'
 CONST extprop:rc:SelfName 'ncsReplyWaiter'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsReplyWaiter'

ref; // ME_5461D9EE0244 TncsReplyWaiter

FORWARD ME_546061CE03DA

: ME_5461D7EA00E4
 CONST UID '5461D7EA00E4'
 CONST Name 'ReplyWaiter'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_546061CE03DA // TncsProcessThread
 ;
 : Target HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5461D7EA00E4 ReplyWaiter

: ME_5464BDA603BD
 CONST UID '5464BDA603BD'
 CONST Name 'f_Transporter'
 CONST Class class_Attribute
 %SUMMARY '[weak] IncsTransporter' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_546061CE03DA // TncsProcessThread
 ;
 : Target WL 'ME_46A608F00301' '4AB0C3C60310.pas.ms.script' // Pointer
 ;

ref; // ME_5464BDA603BD f_Transporter

: ME_5464BE030256
 CONST UID '5464BE030256'
 CONST Name 'Transporter'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_546061CE03DA // TncsProcessThread
 ;
 : Target HWL ME_5464B4730055 // IncsTransporter
 ;
 CONST "pm" true

ref; // ME_5464BE030256 Transporter

FORWARD ME_5460680D0277

: ME_5460681F01B0
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_5460681F01B0 aMessage

: ME_5460681B02B0
 CONST UID '5460681B02B0'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 : Parameters
   Seq: ( ME_5460681F01B0 // aMessage
 )
 ; // Parameters

ref; // ME_5460681B02B0 DoIt

: ME_54606E1A0207
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 : Target WL 'ME_4CDD241C0184' '47913B47006E.pas.ms.script' // l3System
 ;

ref; // ME_54606E1A0207 

: ME_5460734B00FE
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_5460734B00FE 

: ME_546073DF01D8
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 : Target HWL ME_54607384020A // TncsMessageExecutorFactory
 ;

ref; // ME_546073DF01D8 

: ME_5460797F01C3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 : Target HWL ME_5460731E025E // IncsExecutor
 ;

ref; // ME_5460797F01C3 

: ME_54784861030C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 : Target HWL ME_54649C7C00E7 // TncsInvalidMessage
 ;

ref; // ME_54784861030C 

: ME_54784865026A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 : Target WL 'ME_5461CFB8002C' '484A470100DD.pas.ms.script' // TncsMessageKind
 ;

ref; // ME_54784865026A 

: ME_547848860360
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 : Target WL 'ME_4787A405013D' '4AB0C3C60310.pas.ms.script' // Exception
 ;

ref; // ME_547848860360 

: ME_5460680D0277
 CONST UID '5460680D0277'
 CONST Name 'ProcessMessage'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_546061CE03DA // TncsProcessThread
 ;
 : Operations
   Seq: ( HWL ME_5460681B02B0 // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_54606E1A0207 // l3System
 ME_5460734B00FE // FreeAndNil
 ME_546073DF01D8 // TncsMessageExecutorFactory
 ME_5460797F01C3 // IncsExecutor
 ME_54784861030C // TncsInvalidMessage
 ME_54784865026A // TncsMessageKind
 ME_547848860360 // Exception
 )
 ; // Dependencies

ref; // ME_5460680D0277 ProcessMessage

FORWARD ME_5464BDC203B1

: ME_5464BDEF00E1
 CONST Name 'anQueue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E3C54031D // TncsMessageQueue
 ;

ref; // ME_5464BDEF00E1 anQueue

: ME_5464BDEF00F1
 CONST Name 'aTransporter'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5464B4730055 // IncsTransporter
 ;

ref; // ME_5464BDEF00F1 aTransporter

: ME_5493FA0C0300
 CONST Name 'aWaiter'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;

ref; // ME_5493FA0C0300 aWaiter

: ME_5464BDCD0296
 CONST UID '5464BDCD0296'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5464BDC203B1 // Create
 ;
 : Parameters
   Seq: ( ME_5464BDEF00E1 // anQueue
 ME_5464BDEF00F1 // aTransporter
 ME_5493FA0C0300 // aWaiter
 )
 ; // Parameters

ref; // ME_5464BDCD0296 DoIt

: ME_5464BDC203B1
 CONST UID '5464BDC203B1'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_546061CE03DA // TncsProcessThread
 ;
 : Operations
   Seq: ( HWL ME_5464BDCD0296 // DoIt
 )
 ; // Operations

ref; // ME_5464BDC203B1 Create

: ME_5462046F018C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_546061CE03DA // TncsProcessThread
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_5462046F018C 

: ME_479731C50290_ME_546061CE03DA
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_546061CE03DA Cleanup

: ME_4911B69E037D_ME_546061CE03DA
 : Original WL 'ME_4911B69E037D' '47913B47006E.pas.ms.script' // DoExecute
 ;
 CONST OpKind opkind_Overridden
ref; // ME_4911B69E037D_ME_546061CE03DA DoExecute

: ME_546061CE03DA
 CONST UID '546061CE03DA'
 CONST Name 'TncsProcessThread'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( HWL ME_5452248C02B8 // TncsTransporterThread
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_5461D7EA00E4 // ReplyWaiter
 HWL ME_5464BDA603BD // f_Transporter
 HWL ME_5464BE030256 // Transporter
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_5460680D0277 // ProcessMessage
 HWL ME_5464BDC203B1 // Create
 )
 ; // Operations
 : Overridden
   Seq: ( ME_479731C50290_ME_546061CE03DA // Cleanup
 ME_4911B69E037D_ME_546061CE03DA // DoExecute
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_5462046F018C // FreeAndNil
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsProcessThread.pas'
 CONST extprop:rc:SelfName 'ncsProcessThread'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsProcessThread'

ref; // ME_546061CE03DA TncsProcessThread

FORWARD ME_544A09EE005F

FORWARD ME_54917076009C

: ME_5491708B03B6
 CONST UID '5491708B03B6'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent HWL ME_54917076009C // TncsIOHandlerArray
 ;
 : Target WL 'ME_538DDC890328' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAbstractAdapter
 ;

ref; // ME_5491708B03B6 

: ME_54917076009C
 CONST UID '54917076009C'
 CONST Name 'TncsIOHandlerArray'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Inherits
   Seq: ( HWL ME_5490036B0204 // TncsSocketKind
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_5491708B03B6 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'

ref; // ME_54917076009C TncsIOHandlerArray

: ME_5450AB4D02E2
 CONST UID '5450AB4D02E2'
 CONST Name 'SendQueue'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target HWL ME_544E3C54031D // TncsMessageQueue
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5450AB4D02E2 SendQueue

: ME_5450AB6A00A2
 CONST UID '5450AB6A00A2'
 CONST Name 'ReceiveQueue'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target HWL ME_544E3C54031D // TncsMessageQueue
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5450AB6A00A2 ReceiveQueue

: ME_5450EA6D02B3
 CONST UID '5450EA6D02B3'
 CONST Name 'SendThread'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target HWL ME_5450E9A0034A // TncsSendThread
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5450EA6D02B3 SendThread

FORWARD ME_545225640060

: ME_5491703C03A8
 CONST UID '5491703C03A8'
 CONST Name 'SocketKind'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_545225640060 // IOHandlers
 ;
 : Target HWL ME_5490036B0204 // TncsSocketKind
 ;

ref; // ME_5491703C03A8 SocketKind

: ME_545225640060
 CONST UID '545225640060'
 CONST Name 'IOHandlers'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target WL 'ME_538DDC890328' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAbstractAdapter
 ;
 : Attributes
   Seq: ( HWL ME_5491703C03A8 // SocketKind
 )
 ; // Attributes
 CONST "pm" true

ref; // ME_545225640060 IOHandlers

: ME_54534F3D0029
 CONST UID '54534F3D0029'
 CONST Name 'ReceiveThread'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_54534F3D0029 ReceiveThread

: ME_546061ED0170
 CONST UID '546061ED0170'
 CONST Name 'ProcessThread'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target HWL ME_546061CE03DA // TncsProcessThread
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_546061ED0170 ProcessThread

: ME_5461D7C4021A
 CONST UID '5461D7C4021A'
 CONST Name 'ReplyWaiter'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_5461D7C4021A ReplyWaiter

: ME_5465AB860254
 CONST UID '5465AB860254'
 CONST Name 'f_Connected'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5465AB860254 f_Connected

: ME_5466092F01BB
 CONST UID '5466092F01BB'
 CONST Name 'f_ClientID'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target WL 'ME_537F4A04037C' '52FBB2FC0386.pas.ms.script' // TCsClientId
 ;

ref; // ME_5466092F01BB f_ClientID

: ME_548FEF8F0026
 CONST UID '548FEF8F0026'
 CONST Name 'IntSessionID'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_548FEF8F0026 IntSessionID

: ME_5491709C03AC
 CONST UID '5491709C03AC'
 CONST Name 'f_IOHandlers'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target HWL ME_54917076009C // TncsIOHandlerArray
 ;

ref; // ME_5491709C03AC f_IOHandlers

FORWARD ME_54533B010030

: ME_54533B2900CE
 CONST Name 'aValue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_54533B2900CE aValue

: ME_54533B1701F2
 CONST UID '54533B1701F2'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_54533B010030 // SetConnected
 ;
 : Parameters
   Seq: ( ME_54533B2900CE // aValue
 )
 ; // Parameters

ref; // ME_54533B1701F2 DoIt

: ME_54533B010030
 CONST UID '54533B010030'
 CONST Name 'SetConnected'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Operations
   Seq: ( HWL ME_54533B1701F2 // DoIt
 )
 ; // Operations

ref; // ME_54533B010030 SetConnected

: ME_5459C7E00125
 CONST UID '5459C7E00125'
 CONST Name 'StartProcessing'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;

ref; // ME_5459C7E00125 StartProcessing

FORWARD ME_5459C803038D

: ME_545B3E250102
 CONST Name 'WaitForThreads'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_545B3E250102 WaitForThreads

: ME_545B3E120323
 CONST UID '545B3E120323'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5459C803038D // StopProcessing
 ;
 : Parameters
   Seq: ( ME_545B3E250102 // WaitForThreads
 )
 ; // Parameters

ref; // ME_545B3E120323 DoIt

: ME_5459C803038D
 CONST UID '5459C803038D'
 CONST Name 'StopProcessing'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Operations
   Seq: ( HWL ME_545B3E120323 // DoIt
 )
 ; // Operations

ref; // ME_5459C803038D StopProcessing

FORWARD ME_5477033C03D0

: ME_A6A7B60F1DF2
 CONST UID 'A6A7B60F1DF2'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY 'Сигнатура метода HandShake' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5477033C03D0 // HandShake
 ;

ref; // ME_A6A7B60F1DF2 DoIt

: ME_5477033C03D0
 CONST UID '5477033C03D0'
 CONST Name 'HandShake'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Operations
   Seq: ( HWL ME_A6A7B60F1DF2 // DoIt
 )
 ; // Operations

ref; // ME_5477033C03D0 HandShake

FORWARD ME_549175C4030A

: ME_549175D702CD
 CONST UID '549175D702CD'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_549175C4030A // HandShakeKind
 ;
 : Target HWL ME_5490036B0204 // TncsSocketKind
 ;

ref; // ME_549175D702CD DoIt

: ME_549175C4030A
 CONST UID '549175C4030A'
 CONST Name 'HandShakeKind'
 CONST Class class_Class
 : Stereotype st_abstractmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Operations
   Seq: ( HWL ME_549175D702CD // DoIt
 )
 ; // Operations

ref; // ME_549175C4030A HandShakeKind

FORWARD ME_5492C5F703AA

: ME_8A8BAA04A4CE
 CONST UID '8A8BAA04A4CE'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY 'Сигнатура метода TransportStarted' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_5492C5F703AA // TransportStarted
 ;

ref; // ME_8A8BAA04A4CE DoIt

: ME_5492C5F703AA
 CONST UID '5492C5F703AA'
 CONST Name 'TransportStarted'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Operations
   Seq: ( HWL ME_8A8BAA04A4CE // DoIt
 )
 ; // Operations

ref; // ME_5492C5F703AA TransportStarted

: ME_5450A0AC017E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target WL 'ME_54509FEC02EB' '47D0290B016D.pas.ms.script' // l3CreateStringGUID
 ;

ref; // ME_5450A0AC017E 

: ME_5450DC780347
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_5450DC780347 

: ME_5463161F0105
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 : Target WL 'ME_5461CFB8002C' '484A470100DD.pas.ms.script' // TncsMessageKind
 ;

ref; // ME_5463161F0105 

: ME_5464B4E900DA_ME_544A09EE005F
 : Original HWL ME_5464B4E900DA // Send
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5464B4E900DA_ME_544A09EE005F Send

: ME_5464B52F02D5_ME_544A09EE005F
 : Original HWL ME_5464B52F02D5 // WaitForReply
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5464B52F02D5_ME_544A09EE005F WaitForReply

: ME_5465AB2B00CA_ME_544A09EE005F
 : Original HWL ME_5465AB2B00CA // Connected
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5465AB2B00CA_ME_544A09EE005F Connected

: ME_546608F101DE_ME_544A09EE005F
 : Original HWL ME_546608F101DE // ClientID
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_546608F101DE_ME_544A09EE005F ClientID

: ME_5486B96A0025_ME_544A09EE005F
 : Original HWL ME_5486B96A0025 // Processing
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5486B96A0025_ME_544A09EE005F Processing

: ME_548FEF4F002E_ME_544A09EE005F
 : Original HWL ME_548FEF4F002E // SessionID
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_548FEF4F002E_ME_544A09EE005F SessionID

: ME_479731C50290_ME_544A09EE005F
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_544A09EE005F Cleanup

: ME_47A042E100E2_ME_544A09EE005F
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_544A09EE005F InitFields

: ME_544A09EE005F
 CONST UID '544A09EE005F'
 CONST Name 'TncsTransporter'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_53A03846011C' '53A038340371.pas.ms.script' // l3CriticalSectionHolder
 HWL ME_5464B4730055 // IncsTransporter
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_5450AB4D02E2 // SendQueue
 HWL ME_5450AB6A00A2 // ReceiveQueue
 HWL ME_5450EA6D02B3 // SendThread
 HWL ME_545225640060 // IOHandlers
 HWL ME_54534F3D0029 // ReceiveThread
 HWL ME_546061ED0170 // ProcessThread
 HWL ME_5461D7C4021A // ReplyWaiter
 HWL ME_5465AB860254 // f_Connected
 HWL ME_5466092F01BB // f_ClientID
 HWL ME_548FEF8F0026 // IntSessionID
 HWL ME_5491709C03AC // f_IOHandlers
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_54533B010030 // SetConnected
 HWL ME_5459C7E00125 // StartProcessing
 HWL ME_5459C803038D // StopProcessing
 HWL ME_5477033C03D0 // HandShake
 HWL ME_549175C4030A // HandShakeKind
 HWL ME_5492C5F703AA // TransportStarted
 )
 ; // Operations
 : Implemented
   Seq: ( ME_5464B4E900DA_ME_544A09EE005F // Send
 ME_5464B52F02D5_ME_544A09EE005F // WaitForReply
 ME_5465AB2B00CA_ME_544A09EE005F // Connected
 ME_546608F101DE_ME_544A09EE005F // ClientID
 ME_5486B96A0025_ME_544A09EE005F // Processing
 ME_548FEF4F002E_ME_544A09EE005F // SessionID
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_544A09EE005F // Cleanup
 ME_47A042E100E2_ME_544A09EE005F // InitFields
 )
 ; // Overridden
 : Children
   Seq: ( HWL ME_54917076009C // TncsIOHandlerArray
 )
 ; // Children
 : Dependencies
   Seq: ( ME_5450A0AC017E // l3CreateStringGUID
 ME_5450DC780347 // FreeAndNil
 ME_5463161F0105 // TncsMessageKind
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsTransporter.pas'
 CONST extprop:rc:SelfName 'ncsTransporter'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsTransporter'

ref; // ME_544A09EE005F TncsTransporter

FORWARD ME_544A0A0D0239

FORWARD ME_544DF67C0075

: ME_544DF69502E9
 CONST UID '544DF69502E9'
 CONST Name 'c_ClientConnectTimeout'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544DF67C0075 // TimeoutConsts
 ;
 CONST Value '10 * 1000'
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '10 * 1000'

ref; // ME_544DF69502E9 c_ClientConnectTimeout

: ME_544DF6C40248
 CONST UID '544DF6C40248'
 CONST Name 'c_ClientReadTimeout'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_544DF67C0075 // TimeoutConsts
 ;
 CONST Value '{$IFDEF CsDebug} 1000 * 1000 {$ELSE} 10 * 1000 {$ENDIF}'
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value '{$IFDEF CsDebug} 1000 * 1000 {$ELSE} 10 * 1000 {$ENDIF}'

ref; // ME_544DF6C40248 c_ClientReadTimeout

: ME_544DF67C0075
 CONST UID '544DF67C0075'
 CONST Name 'TimeoutConsts'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 %SUMMARY 'В миллисек' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Attributes
   Seq: ( HWL ME_544DF69502E9 // c_ClientConnectTimeout
 HWL ME_544DF6C40248 // c_ClientReadTimeout
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_544DF67C0075 TimeoutConsts

FORWARD ME_549163F102D4

: ME_549164000118
 CONST UID '549164000118'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent HWL ME_549163F102D4 // TncsClientArray
 ;
 : Target WL 'ME_54522A0E031D' '52FBB2FC0386.pas.ms.script' // TncsTCPClient
 ;

ref; // ME_549164000118 

: ME_549163F102D4
 CONST UID '549163F102D4'
 CONST Name 'TncsClientArray'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Inherits
   Seq: ( HWL ME_5490036B0204 // TncsSocketKind
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_549164000118 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'

ref; // ME_549163F102D4 TncsClientArray

: ME_544A21B400E4
 CONST UID '544A21B400E4'
 CONST Name 'f_TCPClients'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Target HWL ME_549163F102D4 // TncsClientArray
 ;

ref; // ME_544A21B400E4 f_TCPClients

: ME_54522FCE0023
 CONST UID '54522FCE0023'
 CONST Name 'TransportConnected'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;

ref; // ME_54522FCE0023 TransportConnected

: ME_545B400202AF
 CONST UID '545B400202AF'
 CONST Name 'SendTransportStatus'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Inherits
   Seq: ( WL 'ME_545B3F72015E' '537F464A0198.pas.ms.script' // TIdStatusEvent
 )
 ; // Inherits

ref; // ME_545B400202AF SendTransportStatus

: ME_5465A71E02F2
 CONST UID '5465A71E02F2'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;

ref; // ME_5465A71E02F2 Create

: ME_5465A72C00CA
 CONST UID '5465A72C00CA'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Inherits
   Seq: ( HWL ME_5465A71E02F2 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5465A598039E // IncsClientTransporter
 )
 ; // Implements

ref; // ME_5465A72C00CA Make

: ME_5491684203A6
 CONST UID '5491684203A6'
 CONST Name 'ReceiveTransportStatus'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Inherits
   Seq: ( WL 'ME_545B3F72015E' '537F464A0198.pas.ms.script' // TIdStatusEvent
 )
 ; // Inherits

ref; // ME_5491684203A6 ReceiveTransportStatus

FORWARD ME_549279980264

: ME_2AABD500F271
 CONST UID '2AABD500F271'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY 'Сигнатура метода BeforeSendHandshake' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_549279980264 // BeforeSendHandshake
 ;

ref; // ME_2AABD500F271 DoIt

: ME_549279980264
 CONST UID '549279980264'
 CONST Name 'BeforeSendHandshake'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Operations
   Seq: ( HWL ME_2AABD500F271 // DoIt
 )
 ; // Operations

ref; // ME_549279980264 BeforeSendHandshake

FORWARD ME_549279B300D5

: ME_8B5B641F41AF
 CONST UID '8B5B641F41AF'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY 'Сигнатура метода BeforeReceiveHandshake' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_549279B300D5 // BeforeReceiveHandshake
 ;

ref; // ME_8B5B641F41AF DoIt

: ME_549279B300D5
 CONST UID '549279B300D5'
 CONST Name 'BeforeReceiveHandshake'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Operations
   Seq: ( HWL ME_8B5B641F41AF // DoIt
 )
 ; // Operations

ref; // ME_549279B300D5 BeforeReceiveHandshake

: ME_544DFC0D0116
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_544DFC0D0116 

: ME_544E2CC40195
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Target WL 'ME_4CDD241C0184' '47913B47006E.pas.ms.script' // l3System
 ;

ref; // ME_544E2CC40195 

: ME_544E37D9032B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Target WL 'ME_544E35D90359' '537F464A0198.pas.ms.script' // IdException
 ;

ref; // ME_544E37D9032B 

: ME_54522D8300D7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Target WL 'ME_538DB527006C' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAdapter
 ;

ref; // ME_54522D8300D7 

: ME_54534AD4014F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Target WL 'ME_538DDC890328' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAbstractAdapter
 ;

ref; // ME_54534AD4014F 

: ME_547C1F8E038F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_547C1F8E038F 

: ME_547C1F9501A1
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Target HWL ME_547C1F31030C // TncsDIsconnect
 ;

ref; // ME_547C1F9501A1 

: ME_547C1F9900B0
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 : Target HWL ME_547C1F3F025A // TncsDIsconnectReply
 ;

ref; // ME_547C1F9900B0 

: ME_544A1FD802E9_ME_544A0A0D0239
 : Original HWL ME_544A1FD802E9 // Connect
 ;
 CONST OpKind opkind_Implemented
ref; // ME_544A1FD802E9_ME_544A0A0D0239 Connect

: ME_544A1FF00062_ME_544A0A0D0239
 : Original HWL ME_544A1FF00062 // Disconnect
 ;
 CONST OpKind opkind_Implemented
ref; // ME_544A1FF00062_ME_544A0A0D0239 Disconnect

: ME_5477033C03D0_ME_544A0A0D0239
 : Original HWL ME_5477033C03D0 // HandShake
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5477033C03D0_ME_544A0A0D0239 HandShake

: ME_549175C4030A_ME_544A0A0D0239
 : Original HWL ME_549175C4030A // HandShakeKind
 ;
 CONST OpKind opkind_Implemented
ref; // ME_549175C4030A_ME_544A0A0D0239 HandShakeKind

: ME_479731C50290_ME_544A0A0D0239
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_544A0A0D0239 Cleanup

: ME_47A042E100E2_ME_544A0A0D0239
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_544A0A0D0239 InitFields

: ME_544A0A0D0239
 CONST UID '544A0A0D0239'
 CONST Name 'TncsClientTransporter'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( HWL ME_544A09EE005F // TncsTransporter
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5465A598039E // IncsClientTransporter
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_544A21B400E4 // f_TCPClients
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_54522FCE0023 // TransportConnected
 HWL ME_545B400202AF // SendTransportStatus
 HWL ME_5465A71E02F2 // Create
 HWL ME_5465A72C00CA // Make
 HWL ME_5491684203A6 // ReceiveTransportStatus
 HWL ME_549279980264 // BeforeSendHandshake
 HWL ME_549279B300D5 // BeforeReceiveHandshake
 )
 ; // Operations
 : Implemented
   Seq: ( ME_544A1FD802E9_ME_544A0A0D0239 // Connect
 ME_544A1FF00062_ME_544A0A0D0239 // Disconnect
 ME_5477033C03D0_ME_544A0A0D0239 // HandShake
 ME_549175C4030A_ME_544A0A0D0239 // HandShakeKind
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_544A0A0D0239 // Cleanup
 ME_47A042E100E2_ME_544A0A0D0239 // InitFields
 )
 ; // Overridden
 : Children
   Seq: ( HWL ME_549163F102D4 // TncsClientArray
 )
 ; // Children
 : Constants
   Seq: ( HWL ME_544DF67C0075 // TimeoutConsts
 )
 ; // Constants
 : Dependencies
   Seq: ( ME_544DFC0D0116 // FreeAndNil
 ME_544E2CC40195 // l3System
 ME_544E37D9032B // IdException
 ME_54522D8300D7 // TcsIdIOHandlerAdapter
 ME_54534AD4014F // TcsIdIOHandlerAbstractAdapter
 ME_547C1F8E038F // TncsMessage
 ME_547C1F9501A1 // TncsDIsconnect
 ME_547C1F9900B0 // TncsDIsconnectReply
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsClientTransporter.pas'
 CONST extprop:rc:SelfName 'ncsClientTransporter'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsClientTransporter'

ref; // ME_544A0A0D0239 TncsClientTransporter

FORWARD ME_544A0A21036B

FORWARD ME_5465A67802C1

: ME_5465A68D0008
 CONST Name 'anIOHandler'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_538DDC890328' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAbstractAdapter
 ;

ref; // ME_5465A68D0008 anIOHandler

: ME_549279210267
 CONST Name 'aSessionID'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_549279210267 aSessionID

: ME_5465A6860144
 CONST UID '5465A6860144'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5465A67802C1 // Create
 ;
 : Parameters
   Seq: ( ME_5465A68D0008 // anIOHandler
 ME_549279210267 // aSessionID
 )
 ; // Parameters

ref; // ME_5465A6860144 DoIt

: ME_5465A67802C1
 CONST UID '5465A67802C1'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544A0A21036B // TncsServerTransporter
 ;
 : Operations
   Seq: ( HWL ME_5465A6860144 // DoIt
 )
 ; // Operations

ref; // ME_5465A67802C1 Create

: ME_5465A69A028C
 CONST UID '5465A69A028C'
 CONST Name 'IntMake'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544A0A21036B // TncsServerTransporter
 ;
 : Inherits
   Seq: ( HWL ME_5465A67802C1 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5465A5AB0324 // IncsServerTransporter
 )
 ; // Implements

ref; // ME_5465A69A028C IntMake

FORWARD ME_549195670058

: ME_54919595031C
 CONST Name 'anIOHandler'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_538DDC890328' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAbstractAdapter
 ;

ref; // ME_54919595031C anIOHandler

: ME_5492AB220174
 CONST Name 'IsMainSocket'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_5492AB220174 IsMainSocket

: ME_549195830367
 CONST UID '549195830367'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_549195670058 // Make
 ;
 : Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 : Parameters
   Seq: ( ME_54919595031C // anIOHandler
 ME_5492AB220174 // IsMainSocket
 )
 ; // Parameters

ref; // ME_549195830367 DoIt

: ME_549195670058
 CONST UID '549195670058'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544A0A21036B // TncsServerTransporter
 ;
 : Operations
   Seq: ( HWL ME_549195830367 // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_549195670058 Make

: ME_5453360B0132
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A0A21036B // TncsServerTransporter
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_5453360B0132 

FORWARD ME_54917FF702A4

: ME_5491802100DD
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_544A0A21036B // TncsServerTransporter
 ;
 : Target HWL ME_54917FF702A4 // TncsServerTransporterPtrPool
 ;

ref; // ME_5491802100DD 

: ME_545335BF0283_ME_544A0A21036B
 : Original HWL ME_545335BF0283 // ProcessMessages
 ;
 CONST OpKind opkind_Implemented
ref; // ME_545335BF0283_ME_544A0A21036B ProcessMessages

: ME_5459D46D01FE_ME_544A0A21036B
 : Original HWL ME_5459D46D01FE // Terminate
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5459D46D01FE_ME_544A0A21036B Terminate

: ME_5459E3150030_ME_544A0A21036B
 : Original HWL ME_5459E3150030 // Terminated
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5459E3150030_ME_544A0A21036B Terminated

: ME_5477033C03D0_ME_544A0A21036B
 : Original HWL ME_5477033C03D0 // HandShake
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5477033C03D0_ME_544A0A21036B HandShake

: ME_549175C4030A_ME_544A0A21036B
 : Original HWL ME_549175C4030A // HandShakeKind
 ;
 CONST OpKind opkind_Implemented
ref; // ME_549175C4030A_ME_544A0A21036B HandShakeKind

: ME_549180E701E0_ME_544A0A21036B
 : Original HWL ME_549180E701E0 // RegisterSendBackHandler
 ;
 CONST OpKind opkind_Implemented
ref; // ME_549180E701E0_ME_544A0A21036B RegisterSendBackHandler

: ME_479731C50290_ME_544A0A21036B
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_544A0A21036B Cleanup

: ME_5492C5F703AA_ME_544A0A21036B
 : Original HWL ME_5492C5F703AA // TransportStarted
 ;
 CONST OpKind opkind_Overridden
ref; // ME_5492C5F703AA_ME_544A0A21036B TransportStarted

: ME_544A0A21036B
 CONST UID '544A0A21036B'
 CONST Name 'TncsServerTransporter'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( HWL ME_544A09EE005F // TncsTransporter
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5465A5AB0324 // IncsServerTransporter
 )
 ; // Implements
 : Operations
   Seq: ( HWL ME_5465A67802C1 // Create
 HWL ME_5465A69A028C // IntMake
 HWL ME_549195670058 // Make
 )
 ; // Operations
 : Implemented
   Seq: ( ME_545335BF0283_ME_544A0A21036B // ProcessMessages
 ME_5459D46D01FE_ME_544A0A21036B // Terminate
 ME_5459E3150030_ME_544A0A21036B // Terminated
 ME_5477033C03D0_ME_544A0A21036B // HandShake
 ME_549175C4030A_ME_544A0A21036B // HandShakeKind
 ME_549180E701E0_ME_544A0A21036B // RegisterSendBackHandler
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_544A0A21036B // Cleanup
 ME_5492C5F703AA_ME_544A0A21036B // TransportStarted
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_5453360B0132 // FreeAndNil
 ME_5491802100DD // TncsServerTransporterPtrPool
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsServerTransporter.pas'
 CONST extprop:rc:SelfName 'ncsServerTransporter'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsServerTransporter'

ref; // ME_544A0A21036B TncsServerTransporter

: ME_54634A7902A1
 CONST UID '54634A7902A1'
 CONST Name 'TncsLoginReply'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( HWL ME_547831BD02E5 // TncsReply
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_5461EDFB01EB' '484A470100DD.pas.ms.script' // csLoginReply
 )
 ; // Implements
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsLoginReply.pas'
 CONST extprop:rc:SelfName 'ncsLoginReply'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsLoginReply'

ref; // ME_54634A7902A1 TncsLoginReply

FORWARD ME_547C34C500F7

FORWARD ME_547C34E902C1

: ME_547C34F1018C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_547C34E902C1 // ncsServerRegister
 ;
 : Target HWL ME_54539F4702B1 // TncsMessageFactory
 ;

ref; // ME_547C34F1018C 

: ME_547C34F5033B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_547C34E902C1 // ncsServerRegister
 ;
 : Target HWL ME_547C1F31030C // TncsDIsconnect
 ;

ref; // ME_547C34F5033B 

: ME_547C34E902C1
 CONST UID '547C34E902C1'
 CONST Name 'ncsServerRegister'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_547C34C500F7 // nscMessagesReg
 ;
 : Dependencies
   Seq: ( ME_547C34F1018C // TncsMessageFactory
 ME_547C34F5033B // TncsDIsconnect
 )
 ; // Dependencies

ref; // ME_547C34E902C1 ncsServerRegister

FORWARD ME_547C350000AA

: ME_547C3509029E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_547C350000AA // ncsClientRegister
 ;
 : Target HWL ME_54539F4702B1 // TncsMessageFactory
 ;

ref; // ME_547C3509029E 

: ME_547C350E00F1
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_547C350000AA // ncsClientRegister
 ;
 : Target HWL ME_547C1F3F025A // TncsDIsconnectReply
 ;

ref; // ME_547C350E00F1 

: ME_547C350000AA
 CONST UID '547C350000AA'
 CONST Name 'ncsClientRegister'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_547C34C500F7 // nscMessagesReg
 ;
 : Dependencies
   Seq: ( ME_547C3509029E // TncsMessageFactory
 ME_547C350E00F1 // TncsDIsconnectReply
 )
 ; // Dependencies

ref; // ME_547C350000AA ncsClientRegister

: ME_547C34C500F7
 CONST UID '547C34C500F7'
 CONST Name 'nscMessagesReg'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Operations
   Seq: ( HWL ME_547C34E902C1 // ncsServerRegister
 HWL ME_547C350000AA // ncsClientRegister
 )
 ; // Operations
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\nscMessagesReg.pas'
 CONST extprop:rc:SelfName 'MessagesReg'

ref; // ME_547C34C500F7 nscMessagesReg

: ME_548AC830032D
 CONST UID '548AC830032D'
 CONST Name 'g_SaveMessage'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 : Target WL 'ME_548007530030' '47D0290B016D.pas.ms.script' // Tl3StopWatch
 ;

ref; // ME_548AC830032D g_SaveMessage

: ME_548AC85F004C
 CONST UID '548AC85F004C'
 CONST Name 'g_LoadMessage'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 : Target WL 'ME_548007530030' '47D0290B016D.pas.ms.script' // Tl3StopWatch
 ;

ref; // ME_548AC85F004C g_LoadMessage

: ME_548AC871032C
 CONST UID '548AC871032C'
 CONST Name 'g_SendMessage'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 : Target WL 'ME_548007530030' '47D0290B016D.pas.ms.script' // Tl3StopWatch
 ;

ref; // ME_548AC871032C g_SendMessage

: ME_548AC87E031F
 CONST UID '548AC87E031F'
 CONST Name 'g_ReveiveMessage'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 : Target WL 'ME_548007530030' '47D0290B016D.pas.ms.script' // Tl3StopWatch
 ;

ref; // ME_548AC87E031F g_ReveiveMessage

: ME_548AC89000B2
 CONST UID '548AC89000B2'
 CONST Name 'g_WaitFile'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 : Target WL 'ME_548007530030' '47D0290B016D.pas.ms.script' // Tl3StopWatch
 ;

ref; // ME_548AC89000B2 g_WaitFile

: ME_54C1F62E02A0
 CONST UID '54C1F62E02A0'
 CONST Name 'g_ReceivePartFile'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 : Target WL 'ME_548007530030' '47D0290B016D.pas.ms.script' // Tl3StopWatch
 ;

ref; // ME_54C1F62E02A0 g_ReceivePartFile

: ME_54C216A50244
 CONST UID '54C216A50244'
 CONST Name 'g_SaveControl'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 : Target WL 'ME_548007530030' '47D0290B016D.pas.ms.script' // Tl3StopWatch
 ;

ref; // ME_54C216A50244 g_SaveControl

: ME_54C216BB03A8
 CONST UID '54C216BB03A8'
 CONST Name 'g_WriteFile'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 : Target WL 'ME_548007530030' '47D0290B016D.pas.ms.script' // Tl3StopWatch
 ;

ref; // ME_54C216BB03A8 g_WriteFile

: ME_548AC7FB0046
 CONST UID '548AC7FB0046'
 CONST Name 'ncsProfile'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Attributes
   Seq: ( HWL ME_548AC830032D // g_SaveMessage
 HWL ME_548AC85F004C // g_LoadMessage
 HWL ME_548AC871032C // g_SendMessage
 HWL ME_548AC87E031F // g_ReveiveMessage
 HWL ME_548AC89000B2 // g_WaitFile
 HWL ME_54C1F62E02A0 // g_ReceivePartFile
 HWL ME_54C216A50244 // g_SaveControl
 HWL ME_54C216BB03A8 // g_WriteFile
 )
 ; // Attributes
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsProfile.pas'

ref; // ME_548AC7FB0046 ncsProfile

FORWARD ME_5492D7AC0214

: ME_5492D7DE03B9
 CONST UID '5492D7DE03B9'
 CONST Name 'ItemType'
 CONST Class class_Attribute
 : Stereotype st_impurity_value::Attribute ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_agr
 : Parent HWL ME_5492D7AC0214 // TncsServerTransporterPtrList
 ;
 : Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;

ref; // ME_5492D7DE03B9 ItemType

: ME_5492D7AC0214
 CONST UID '5492D7AC0214'
 CONST Name 'TncsServerTransporterPtrList'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.pas.ms.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_47B57D630029' '47913B47006E.pas.ms.script' // l3InterfacePtrList
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_5492D7DE03B9 // ItemType
 )
 ; // Attributes
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsServerTransporterPtrList.pas'
 CONST extprop:rc:SelfName 'ncsServerTransporterPtrList'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsServerTransporterPtrList'

ref; // ME_5492D7AC0214 TncsServerTransporterPtrList

: ME_5492D81C00D8
 CONST UID '5492D81C00D8'
 CONST Name 'f_Data'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_54917FF702A4 // TncsServerTransporterPtrPool
 ;
 : Target HWL ME_5492D7AC0214 // TncsServerTransporterPtrList
 ;

ref; // ME_5492D81C00D8 f_Data

: ME_5492D83900EF
 CONST Name 'aTransporter'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;

ref; // ME_5492D83900EF aTransporter

: ME_5492D83203D7
 CONST UID '5492D83203D7'
 CONST Name 'Register'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54917FF702A4 // TncsServerTransporterPtrPool
 ;
 : Parameters
   Seq: ( ME_5492D83900EF // aTransporter
 )
 ; // Parameters

ref; // ME_5492D83203D7 Register

: ME_5492D84C01FA
 CONST Name 'aTransporter'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;

ref; // ME_5492D84C01FA aTransporter

: ME_5492D8470118
 CONST UID '5492D8470118'
 CONST Name 'UnRegister'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54917FF702A4 // TncsServerTransporterPtrPool
 ;
 : Parameters
   Seq: ( ME_5492D84C01FA // aTransporter
 )
 ; // Parameters

ref; // ME_5492D8470118 UnRegister

: ME_5492D86002D4
 CONST Name 'aSessionID'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_5492D86002D4 aSessionID

: ME_5492D85A0389
 CONST UID '5492D85A0389'
 CONST Name 'FindTransporter'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54917FF702A4 // TncsServerTransporterPtrPool
 ;
 : Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 : Parameters
   Seq: ( ME_5492D86002D4 // aSessionID
 )
 ; // Parameters

ref; // ME_5492D85A0389 FindTransporter

: ME_479731C50290_ME_54917FF702A4
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_54917FF702A4 Cleanup

: ME_47A042E100E2_ME_54917FF702A4
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_54917FF702A4 InitFields

: ME_54917FF702A4
 CONST UID '54917FF702A4'
 CONST Name 'TncsServerTransporterPtrPool'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_53A03846011C' '53A038340371.pas.ms.script' // l3CriticalSectionHolder
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_5492D81C00D8 // f_Data
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_5492D83203D7 // Register
 HWL ME_5492D8470118 // UnRegister
 HWL ME_5492D85A0389 // FindTransporter
 )
 ; // Operations
 : Overridden
   Seq: ( ME_479731C50290_ME_54917FF702A4 // Cleanup
 ME_47A042E100E2_ME_54917FF702A4 // InitFields
 )
 ; // Overridden
 CONST "singleton" true
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsServerTransporterPtrPool.pas'
 CONST extprop:rc:SelfName 'ncsServerTransporterPtrPool'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsServerTransporterPtrPool'

ref; // ME_54917FF702A4 TncsServerTransporterPtrPool

FORWARD ME_547708500384

: ME_5481A0B20013
 CONST UID '5481A0B20013'
 CONST Name 'f_QueryID'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_547708500384 // TncsCompatibilityClientTransporter
 ;
 : Target WL 'ME_537F63760334' '52FBB2FC0386.pas.ms.script' // TCsQueryId
 ;

ref; // ME_5481A0B20013 f_QueryID

FORWARD ME_5481A0E30063

: ME_5481A10903D0
 CONST Name 'aQueryID'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_537F63760334' '52FBB2FC0386.pas.ms.script' // TCsQueryId
 ;

ref; // ME_5481A10903D0 aQueryID

: ME_5481A0F10108
 CONST UID '5481A0F10108'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_5481A0E30063 // Create
 ;
 : Parameters
   Seq: ( ME_5481A10903D0 // aQueryID
 )
 ; // Parameters

ref; // ME_5481A0F10108 DoIt

: ME_5481A0E30063
 CONST UID '5481A0E30063'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_547708500384 // TncsCompatibilityClientTransporter
 ;
 : Operations
   Seq: ( HWL ME_5481A0F10108 // DoIt
 )
 ; // Operations

ref; // ME_5481A0E30063 Create

: ME_5481A13200D2
 CONST UID '5481A13200D2'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_547708500384 // TncsCompatibilityClientTransporter
 ;
 : Inherits
   Seq: ( HWL ME_5481A0E30063 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5465A598039E // IncsClientTransporter
 )
 ; // Implements

ref; // ME_5481A13200D2 Make

: ME_547708AE00EC
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_547708500384 // TncsCompatibilityClientTransporter
 ;
 : Target WL 'ME_545C9ADE01F3' '52FBB2FC0386.pas.ms.script' // cProtocolVersion
 ;

ref; // ME_547708AE00EC 

: ME_549279980264_ME_547708500384
 : Original HWL ME_549279980264 // BeforeSendHandshake
 ;
 CONST OpKind opkind_Overridden
ref; // ME_549279980264_ME_547708500384 BeforeSendHandshake

: ME_549279B300D5_ME_547708500384
 : Original HWL ME_549279B300D5 // BeforeReceiveHandshake
 ;
 CONST OpKind opkind_Overridden
ref; // ME_549279B300D5_ME_547708500384 BeforeReceiveHandshake

: ME_547708500384
 CONST UID '547708500384'
 CONST Name 'TncsCompatibilityClientTransporter'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( HWL ME_544A0A0D0239 // TncsClientTransporter
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_5481A0B20013 // f_QueryID
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_5481A0E30063 // Create
 HWL ME_5481A13200D2 // Make
 )
 ; // Operations
 : Overridden
   Seq: ( ME_549279980264_ME_547708500384 // BeforeSendHandshake
 ME_549279B300D5_ME_547708500384 // BeforeReceiveHandshake
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_547708AE00EC // cProtocolVersion
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsCompatibilityClientTransporter.pas'
 CONST extprop:rc:SelfName 'ncsCompatibilityClientTransporter'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsCompatibilityClientTransporter'

ref; // ME_547708500384 TncsCompatibilityClientTransporter

FORWARD ME_54E333CD0130

: ME_54E33448033C
 CONST UID '54E33448033C'
 CONST Name 'IntSessionID'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_54E33448033C IntSessionID

: ME_54E3346203DE
 CONST UID '54E3346203DE'
 CONST Name 'f_ClientID'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target WL 'ME_537F4A04037C' '52FBB2FC0386.pas.ms.script' // TCsClientId
 ;

ref; // ME_54E3346203DE f_ClientID

: ME_54E3347301B2
 CONST UID '54E3347301B2'
 CONST Name 'f_Connected'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_54E3347301B2 f_Connected

: ME_54E334830061
 CONST UID '54E334830061'
 CONST Name 'IOHandler'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target WL 'ME_538DDC890328' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAbstractAdapter
 ;
 CONST "pm" true
 CONST "reads field" true

ref; // ME_54E334830061 IOHandler

FORWARD ME_54E334CD02E9

: ME_54E334E6039D
 CONST Name 'aValue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_54E334E6039D aValue

: ME_54E334DA0249
 CONST UID '54E334DA0249'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E334CD02E9 // SetConnected
 ;
 : Parameters
   Seq: ( ME_54E334E6039D // aValue
 )
 ; // Parameters

ref; // ME_54E334DA0249 DoIt

: ME_54E334CD02E9
 CONST UID '54E334CD02E9'
 CONST Name 'SetConnected'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Operations
   Seq: ( HWL ME_54E334DA0249 // DoIt
 )
 ; // Operations

ref; // ME_54E334CD02E9 SetConnected

: ME_54E334F5028C
 CONST UID '54E334F5028C'
 CONST Name 'StartProcessing'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;

ref; // ME_54E334F5028C StartProcessing

: ME_54E3350B01CD
 CONST UID '54E3350B01CD'
 CONST Name 'StopProcessing'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;

ref; // ME_54E3350B01CD StopProcessing

FORWARD ME_54E3353000D8

: ME_3C2D040A2956
 CONST UID '3C2D040A2956'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY 'Сигнатура метода HandShake' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E3353000D8 // HandShake
 ;

ref; // ME_3C2D040A2956 DoIt

: ME_54E3353000D8
 CONST UID '54E3353000D8'
 CONST Name 'HandShake'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Operations
   Seq: ( HWL ME_3C2D040A2956 // DoIt
 )
 ; // Operations

ref; // ME_54E3353000D8 HandShake

FORWARD ME_54E335560020

: ME_6DE12A456230
 CONST UID '6DE12A456230'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY 'Сигнатура метода TransportStarted' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E335560020 // TransportStarted
 ;

ref; // ME_6DE12A456230 DoIt

: ME_54E335560020
 CONST UID '54E335560020'
 CONST Name 'TransportStarted'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Operations
   Seq: ( HWL ME_6DE12A456230 // DoIt
 )
 ; // Operations

ref; // ME_54E335560020 TransportStarted

FORWARD ME_54E45D5E01D9

: ME_54E45D780172
 CONST Name 'aMessage'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_54E45D780172 aMessage

: ME_54E45D6B00CC
 CONST UID '54E45D6B00CC'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E45D5E01D9 // ProcessMessage
 ;
 : Parameters
   Seq: ( ME_54E45D780172 // aMessage
 )
 ; // Parameters

ref; // ME_54E45D6B00CC DoIt

: ME_54E45D5E01D9
 CONST UID '54E45D5E01D9'
 CONST Name 'ProcessMessage'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Operations
   Seq: ( HWL ME_54E45D6B00CC // DoIt
 )
 ; // Operations

ref; // ME_54E45D5E01D9 ProcessMessage

: ME_54E45D4D0010
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target WL 'ME_47E150FF028A' '4AB0997B00A2.pas.ms.script' // TStream
 ;

ref; // ME_54E45D4D0010 

: ME_54E45D500385
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target WL 'ME_538DE3F001DC' '47913B47006E.pas.ms.script' // Tl3TempMemoryStream
 ;

ref; // ME_54E45D500385 

: ME_54E45D9A015E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target HWL ME_548AC7FB0046 // ncsProfile
 ;

ref; // ME_54E45D9A015E 

: ME_54E45DB9021F
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_54E45DB9021F 

: ME_54E45DD30091
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target HWL ME_54539F4702B1 // TncsMessageFactory
 ;

ref; // ME_54E45DD30091 

: ME_54E45DD6032B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target WL 'ME_5461CFB8002C' '484A470100DD.pas.ms.script' // TncsMessageKind
 ;

ref; // ME_54E45DD6032B 

: ME_54E45DEA009C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target WL 'ME_4CDD241C0184' '47913B47006E.pas.ms.script' // l3System
 ;

ref; // ME_54E45DEA009C 

: ME_54E4637B0261
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target HWL ME_54607384020A // TncsMessageExecutorFactory
 ;

ref; // ME_54E4637B0261 

: ME_54EC261601C5
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 : Target WL 'ME_54EC25F3023A' '4AB0997B00A2.pas.ms.script' // MillisecondsBetween
 ;

ref; // ME_54EC261601C5 

: ME_5464B4E900DA_ME_54E333CD0130
 : Original HWL ME_5464B4E900DA // Send
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5464B4E900DA_ME_54E333CD0130 Send

: ME_5464B52F02D5_ME_54E333CD0130
 : Original HWL ME_5464B52F02D5 // WaitForReply
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5464B52F02D5_ME_54E333CD0130 WaitForReply

: ME_5465AB2B00CA_ME_54E333CD0130
 : Original HWL ME_5465AB2B00CA // Connected
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5465AB2B00CA_ME_54E333CD0130 Connected

: ME_546608F101DE_ME_54E333CD0130
 : Original HWL ME_546608F101DE // ClientID
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_546608F101DE_ME_54E333CD0130 ClientID

: ME_5486B96A0025_ME_54E333CD0130
 : Original HWL ME_5486B96A0025 // Processing
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5486B96A0025_ME_54E333CD0130 Processing

: ME_548FEF4F002E_ME_54E333CD0130
 : Original HWL ME_548FEF4F002E // SessionID
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_548FEF4F002E_ME_54E333CD0130 SessionID

: ME_479731C50290_ME_54E333CD0130
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_54E333CD0130 Cleanup

: ME_47A042E100E2_ME_54E333CD0130
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_54E333CD0130 InitFields

: ME_54E333CD0130
 CONST UID '54E333CD0130'
 CONST Name 'TncsSynchroTransporter'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5464B4730055 // IncsTransporter
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_54E33448033C // IntSessionID
 HWL ME_54E3346203DE // f_ClientID
 HWL ME_54E3347301B2 // f_Connected
 HWL ME_54E334830061 // IOHandler
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_54E334CD02E9 // SetConnected
 HWL ME_54E334F5028C // StartProcessing
 HWL ME_54E3350B01CD // StopProcessing
 HWL ME_54E3353000D8 // HandShake
 HWL ME_54E335560020 // TransportStarted
 HWL ME_54E45D5E01D9 // ProcessMessage
 )
 ; // Operations
 : Implemented
   Seq: ( ME_5464B4E900DA_ME_54E333CD0130 // Send
 ME_5464B52F02D5_ME_54E333CD0130 // WaitForReply
 ME_5465AB2B00CA_ME_54E333CD0130 // Connected
 ME_546608F101DE_ME_54E333CD0130 // ClientID
 ME_5486B96A0025_ME_54E333CD0130 // Processing
 ME_548FEF4F002E_ME_54E333CD0130 // SessionID
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_54E333CD0130 // Cleanup
 ME_47A042E100E2_ME_54E333CD0130 // InitFields
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_54E45D4D0010 // TStream
 ME_54E45D500385 // Tl3TempMemoryStream
 ME_54E45D9A015E // ncsProfile
 ME_54E45DB9021F // FreeAndNil
 ME_54E45DD30091 // TncsMessageFactory
 ME_54E45DD6032B // TncsMessageKind
 ME_54E45DEA009C // l3System
 ME_54E4637B0261 // TncsMessageExecutorFactory
 ME_54EC261601C5 // MillisecondsBetween
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsSynchroTransporter.pas'
 CONST extprop:rc:SelfName 'ncsSynchroTransporter'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsSynchroTransporter'

ref; // ME_54E333CD0130 TncsSynchroTransporter

FORWARD ME_54E339B500F7

: ME_54E33B0E00EE
 CONST UID '54E33B0E00EE'
 CONST Name 'f_TCPClient'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Target WL 'ME_54522A0E031D' '52FBB2FC0386.pas.ms.script' // TncsTCPClient
 ;

ref; // ME_54E33B0E00EE f_TCPClient

: ME_54E33A870172
 CONST UID '54E33A870172'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;

ref; // ME_54E33A870172 Create

: ME_54E33A920344
 CONST UID '54E33A920344'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Inherits
   Seq: ( HWL ME_54E33A870172 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5465A598039E // IncsClientTransporter
 )
 ; // Implements

ref; // ME_54E33A920344 Make

: ME_54E33B3A02CB
 CONST UID '54E33B3A02CB'
 CONST Name 'TransportStatus'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Inherits
   Seq: ( WL 'ME_545B3F72015E' '537F464A0198.pas.ms.script' // TIdStatusEvent
 )
 ; // Inherits

ref; // ME_54E33B3A02CB TransportStatus

: ME_54E33B5E0245
 CONST UID '54E33B5E0245'
 CONST Name 'TransportConnected'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;

ref; // ME_54E33B5E0245 TransportConnected

FORWARD ME_54E33EA40163

: ME_9367E3A2B13B
 CONST UID '9367E3A2B13B'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY 'Сигнатура метода BeforeHandshake' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E33EA40163 // BeforeHandshake
 ;

ref; // ME_9367E3A2B13B DoIt

: ME_54E33EA40163
 CONST UID '54E33EA40163'
 CONST Name 'BeforeHandshake'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Operations
   Seq: ( HWL ME_9367E3A2B13B // DoIt
 )
 ; // Operations

ref; // ME_54E33EA40163 BeforeHandshake

: ME_54E33B1D023D
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Target WL 'ME_538DB527006C' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAdapter
 ;

ref; // ME_54E33B1D023D 

: ME_54E33B220023
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Target WL 'ME_538DDC890328' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAbstractAdapter
 ;

ref; // ME_54E33B220023 

: ME_54E34E64034C
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Target WL 'ME_4CDD241C0184' '47913B47006E.pas.ms.script' // l3System
 ;

ref; // ME_54E34E64034C 

: ME_54E34E6900C5
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Target WL 'ME_544E35D90359' '537F464A0198.pas.ms.script' // IdException
 ;

ref; // ME_54E34E6900C5 

: ME_54E34E6E01B7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_54E34E6E01B7 

: ME_54E34E7201A1
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Target WL 'ME_538DDC890328' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAbstractAdapter
 ;

ref; // ME_54E34E7201A1 

: ME_54E34E770042
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_54E34E770042 

: ME_54E34E7B0116
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Target HWL ME_547C1F31030C // TncsDIsconnect
 ;

ref; // ME_54E34E7B0116 

: ME_54E34E7F017D
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Target HWL ME_547C1F3F025A // TncsDIsconnectReply
 ;

ref; // ME_54E34E7F017D 

: ME_54E34E8302CE
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 : Target WL 'ME_538DB527006C' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAdapter
 ;

ref; // ME_54E34E8302CE 

: ME_544A1FD802E9_ME_54E339B500F7
 : Original HWL ME_544A1FD802E9 // Connect
 ;
 CONST OpKind opkind_Implemented
ref; // ME_544A1FD802E9_ME_54E339B500F7 Connect

: ME_544A1FF00062_ME_54E339B500F7
 : Original HWL ME_544A1FF00062 // Disconnect
 ;
 CONST OpKind opkind_Implemented
ref; // ME_544A1FF00062_ME_54E339B500F7 Disconnect

: ME_54E3353000D8_ME_54E339B500F7
 : Original HWL ME_54E3353000D8 // HandShake
 ;
 CONST OpKind opkind_Implemented
ref; // ME_54E3353000D8_ME_54E339B500F7 HandShake

: ME_479731C50290_ME_54E339B500F7
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_54E339B500F7 Cleanup

: ME_47A042E100E2_ME_54E339B500F7
 : Original WL 'ME_47A042E100E2' '47913B47006E.pas.ms.script' // InitFields
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47A042E100E2_ME_54E339B500F7 InitFields

: ME_54E339B500F7
 CONST UID '54E339B500F7'
 CONST Name 'TncsSynchroClientTransporter'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( HWL ME_54E333CD0130 // TncsSynchroTransporter
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5465A598039E // IncsClientTransporter
 )
 ; // Implements
 : Attributes
   Seq: ( HWL ME_54E33B0E00EE // f_TCPClient
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_54E33A870172 // Create
 HWL ME_54E33A920344 // Make
 HWL ME_54E33B3A02CB // TransportStatus
 HWL ME_54E33B5E0245 // TransportConnected
 HWL ME_54E33EA40163 // BeforeHandshake
 )
 ; // Operations
 : Implemented
   Seq: ( ME_544A1FD802E9_ME_54E339B500F7 // Connect
 ME_544A1FF00062_ME_54E339B500F7 // Disconnect
 ME_54E3353000D8_ME_54E339B500F7 // HandShake
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_54E339B500F7 // Cleanup
 ME_47A042E100E2_ME_54E339B500F7 // InitFields
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_54E33B1D023D // TcsIdIOHandlerAdapter
 ME_54E33B220023 // TcsIdIOHandlerAbstractAdapter
 ME_54E34E64034C // l3System
 ME_54E34E6900C5 // IdException
 ME_54E34E6E01B7 // FreeAndNil
 ME_54E34E7201A1 // TcsIdIOHandlerAbstractAdapter
 ME_54E34E770042 // TncsMessage
 ME_54E34E7B0116 // TncsDIsconnect
 ME_54E34E7F017D // TncsDIsconnectReply
 ME_54E34E8302CE // TcsIdIOHandlerAdapter
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsSynchroClientTransporter.pas'
 CONST extprop:rc:SelfName 'ncsSynchroClientTransporter'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsSynchroClientTransporter'

ref; // ME_54E339B500F7 TncsSynchroClientTransporter

FORWARD ME_54E33DBC0063

: ME_54E33E0F03C2
 CONST UID '54E33E0F03C2'
 CONST Name 'f_QueryID'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_54E33DBC0063 // TncsSynchroCompatibilityClientTransporter
 ;
 : Target WL 'ME_537F63760334' '52FBB2FC0386.pas.ms.script' // TCsQueryId
 ;

ref; // ME_54E33E0F03C2 f_QueryID

FORWARD ME_54E33E1A00B4

: ME_54E33E3F01E1
 CONST Name 'aQueryID'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_537F63760334' '52FBB2FC0386.pas.ms.script' // TCsQueryId
 ;

ref; // ME_54E33E3F01E1 aQueryID

: ME_54E33E3D00DB
 CONST UID '54E33E3D00DB'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E33E1A00B4 // Create
 ;
 : Parameters
   Seq: ( ME_54E33E3F01E1 // aQueryID
 )
 ; // Parameters

ref; // ME_54E33E3D00DB DoIt

: ME_54E33E1A00B4
 CONST UID '54E33E1A00B4'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E33DBC0063 // TncsSynchroCompatibilityClientTransporter
 ;
 : Operations
   Seq: ( HWL ME_54E33E3D00DB // DoIt
 )
 ; // Operations

ref; // ME_54E33E1A00B4 Create

: ME_54E33E23020D
 CONST UID '54E33E23020D'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E33DBC0063 // TncsSynchroCompatibilityClientTransporter
 ;
 : Inherits
   Seq: ( HWL ME_54E33E1A00B4 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5465A598039E // IncsClientTransporter
 )
 ; // Implements

ref; // ME_54E33E23020D Make

: ME_54E355790184
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E33DBC0063 // TncsSynchroCompatibilityClientTransporter
 ;
 : Target WL 'ME_545C9ADE01F3' '52FBB2FC0386.pas.ms.script' // cProtocolVersion
 ;

ref; // ME_54E355790184 

: ME_54E33EA40163_ME_54E33DBC0063
 : Original HWL ME_54E33EA40163 // BeforeHandshake
 ;
 CONST OpKind opkind_Overridden
ref; // ME_54E33EA40163_ME_54E33DBC0063 BeforeHandshake

: ME_54E33DBC0063
 CONST UID '54E33DBC0063'
 CONST Name 'TncsSynchroCompatibilityClientTransporter'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_54E33E0F03C2 // f_QueryID
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_54E33E1A00B4 // Create
 HWL ME_54E33E23020D // Make
 )
 ; // Operations
 : Overridden
   Seq: ( ME_54E33EA40163_ME_54E33DBC0063 // BeforeHandshake
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_54E355790184 // cProtocolVersion
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsSynchroCompatibilityClientTransporter.pas'
 CONST extprop:rc:SelfName 'ncsSynchroCompatibilityClientTransporter'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsSynchroCompatibilityClientTransporter'

ref; // ME_54E33DBC0063 TncsSynchroCompatibilityClientTransporter

FORWARD ME_54E47AE90373

FORWARD ME_54E591B50054

: ME_54E591C4003C
 CONST Name 'anIOHandler'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_538DDC890328' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAbstractAdapter
 ;

ref; // ME_54E591C4003C anIOHandler

: ME_54E591C4005B
 CONST Name 'aSessionID'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_54E591C4005B aSessionID

: ME_54E591C00274
 CONST UID '54E591C00274'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E591B50054 // Create
 ;
 : Parameters
   Seq: ( ME_54E591C4003C // anIOHandler
 ME_54E591C4005B // aSessionID
 )
 ; // Parameters

ref; // ME_54E591C00274 DoIt

: ME_54E591B50054
 CONST UID '54E591B50054'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Operations
   Seq: ( HWL ME_54E591C00274 // DoIt
 )
 ; // Operations

ref; // ME_54E591B50054 Create

: ME_54E591D102F6
 CONST UID '54E591D102F6'
 CONST Name 'IntMake'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Inherits
   Seq: ( HWL ME_54E591B50054 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5465A5AB0324 // IncsServerTransporter
 )
 ; // Implements

ref; // ME_54E591D102F6 IntMake

FORWARD ME_54E5920A003C

: ME_54E5922801B3
 CONST Name 'anIOHandler'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_538DDC890328' '52FBB2FC0386.pas.ms.script' // TcsIdIOHandlerAbstractAdapter
 ;

ref; // ME_54E5922801B3 anIOHandler

: ME_54E5921C031D
 CONST UID '54E5921C031D'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E5920A003C // Make
 ;
 : Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 : Parameters
   Seq: ( ME_54E5922801B3 // anIOHandler
 )
 ; // Parameters

ref; // ME_54E5921C031D DoIt

: ME_54E5920A003C
 CONST UID '54E5920A003C'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Operations
   Seq: ( HWL ME_54E5921C031D // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_54E5920A003C Make

: ME_54E47B4D01CC
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_54E47B4D01CC 

: ME_54E48B7302B3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Target HWL ME_548AC7FB0046 // ncsProfile
 ;

ref; // ME_54E48B7302B3 

: ME_54E48B7C017B
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Target WL 'ME_47E150FF028A' '4AB0997B00A2.pas.ms.script' // TStream
 ;

ref; // ME_54E48B7C017B 

: ME_54E48BA50365
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Target WL 'ME_538DE3F001DC' '47913B47006E.pas.ms.script' // Tl3TempMemoryStream
 ;

ref; // ME_54E48BA50365 

: ME_54E48F40014E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Target HWL ME_544E079E0253 // TncsMessage
 ;

ref; // ME_54E48F40014E 

: ME_54E48F4A034D
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Target HWL ME_54649C7C00E7 // TncsInvalidMessage
 ;

ref; // ME_54E48F4A034D 

: ME_54E48F55034E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Target HWL ME_547C1F31030C // TncsDIsconnect
 ;

ref; // ME_54E48F55034E 

: ME_54E48F640365
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Target HWL ME_547C1F3F025A // TncsDIsconnectReply
 ;

ref; // ME_54E48F640365 

: ME_54E494630198
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Target HWL ME_54539F4702B1 // TncsMessageFactory
 ;

ref; // ME_54E494630198 

: ME_54E49C38016A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 : Target WL 'ME_4CDD241C0184' '47913B47006E.pas.ms.script' // l3System
 ;

ref; // ME_54E49C38016A 

: ME_545335BF0283_ME_54E47AE90373
 : Original HWL ME_545335BF0283 // ProcessMessages
 ;
 CONST OpKind opkind_Implemented
ref; // ME_545335BF0283_ME_54E47AE90373 ProcessMessages

: ME_5459D46D01FE_ME_54E47AE90373
 : Original HWL ME_5459D46D01FE // Terminate
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5459D46D01FE_ME_54E47AE90373 Terminate

: ME_5459E3150030_ME_54E47AE90373
 : Original HWL ME_5459E3150030 // Terminated
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5459E3150030_ME_54E47AE90373 Terminated

: ME_549180E701E0_ME_54E47AE90373
 : Original HWL ME_549180E701E0 // RegisterSendBackHandler
 ;
 CONST OpKind opkind_Implemented
ref; // ME_549180E701E0_ME_54E47AE90373 RegisterSendBackHandler

: ME_54E3353000D8_ME_54E47AE90373
 : Original HWL ME_54E3353000D8 // HandShake
 ;
 CONST OpKind opkind_Implemented
ref; // ME_54E3353000D8_ME_54E47AE90373 HandShake

: ME_54E47AE90373
 CONST UID '54E47AE90373'
 CONST Name 'TncsSynchroServerTransporter'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_544E0148010D // Messages
 ;
 : Inherits
   Seq: ( HWL ME_54E333CD0130 // TncsSynchroTransporter
 )
 ; // Inherits
 : Implements
   Seq: ( HWL ME_5465A5AB0324 // IncsServerTransporter
 )
 ; // Implements
 : Operations
   Seq: ( HWL ME_54E591B50054 // Create
 HWL ME_54E591D102F6 // IntMake
 HWL ME_54E5920A003C // Make
 )
 ; // Operations
 : Implemented
   Seq: ( ME_545335BF0283_ME_54E47AE90373 // ProcessMessages
 ME_5459D46D01FE_ME_54E47AE90373 // Terminate
 ME_5459E3150030_ME_54E47AE90373 // Terminated
 ME_549180E701E0_ME_54E47AE90373 // RegisterSendBackHandler
 ME_54E3353000D8_ME_54E47AE90373 // HandShake
 )
 ; // Implemented
 : Dependencies
   Seq: ( ME_54E47B4D01CC // FreeAndNil
 ME_54E48B7302B3 // ncsProfile
 ME_54E48B7C017B // TStream
 ME_54E48BA50365 // Tl3TempMemoryStream
 ME_54E48F40014E // TncsMessage
 ME_54E48F4A034D // TncsInvalidMessage
 ME_54E48F55034E // TncsDIsconnect
 ME_54E48F640365 // TncsDIsconnectReply
 ME_54E494630198 // TncsMessageFactory
 ME_54E49C38016A // l3System
 )
 ; // Dependencies
 CONST intf.pas:Path 'common\components\rtl\Garant\cs\ncsSynchroServerTransporter.pas'
 CONST extprop:rc:SelfName 'ncsSynchroServerTransporter'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'ncsSynchroServerTransporter'

ref; // ME_54E47AE90373 TncsSynchroServerTransporter

: ME_544E0148010D
 CONST UID '544E0148010D'
 CONST Name 'Messages'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_52F8C27F01AB' '52F8C27F01AB.pas.ms.script' // cs
 ;
 : Children
   Seq: ( HWL ME_544E07C6034D // TncsLoginMessage
 HWL ME_544F977F036B // TncsPriorityMessageList
 HWL ME_544E3C54031D // TncsMessageQueue
 HWL ME_5452248C02B8 // TncsTransporterThread
 HWL ME_5460B6230039 // TncsTransporterIOThread
 HWL ME_54534F1A00BF // TncsReceiveThread
 HWL ME_5461D6C30025 // TncsReplyDescription
 HWL ME_5460A4DB018A // ncsMessageInterfaces
 HWL ME_5450E9A0034A // TncsSendThread
 HWL ME_5453986402AC // ncsMessage
 HWL ME_54539F0C00AD // TncsMessageClassList
 HWL ME_54539F4702B1 // TncsMessageFactory
 HWL ME_545CBE61008B // TncsServerTransporterList
 HWL ME_545CBED90193 // TncsServerTransporterPool
 HWL ME_5461D6FC00F7 // TncsReplyDecsriptionList
 HWL ME_54609BB100BB // TncsExecutorFactoryList
 HWL ME_54607384020A // TncsMessageExecutorFactory
 HWL ME_5461D9EE0244 // TncsReplyWaiter
 HWL ME_546061CE03DA // TncsProcessThread
 HWL ME_544A09EE005F // TncsTransporter
 HWL ME_544A0A0D0239 // TncsClientTransporter
 HWL ME_544A0A21036B // TncsServerTransporter
 HWL ME_54634A7902A1 // TncsLoginReply
 HWL ME_547C34C500F7 // nscMessagesReg
 HWL ME_548AC7FB0046 // ncsProfile
 HWL ME_5492D7AC0214 // TncsServerTransporterPtrList
 HWL ME_54917FF702A4 // TncsServerTransporterPtrPool
 HWL ME_547708500384 // TncsCompatibilityClientTransporter
 HWL ME_54E333CD0130 // TncsSynchroTransporter
 HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 HWL ME_54E33DBC0063 // TncsSynchroCompatibilityClientTransporter
 HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 WL 'ME_4678193C009C' '4678193C009C.pas.ms.script' // l3Types
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_47D0290B016D' '47D0290B016D.pas.ms.script' // l3Utils
 WL 'ME_484A470100DD' '484A470100DD.pas.ms.script' // Standard
 WL 'ME_4AB0997B00A2' '4AB0997B00A2.pas.ms.script' // Common
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_4AB0C3F60375' '4AB0C3F60375.pas.ms.script' // Win
 WL 'ME_52FBB2FC0386' '52FBB2FC0386.pas.ms.script' // Core
 WL 'ME_537F464A0198' '537F464A0198.pas.ms.script' // System
 WL 'ME_538DAE950337' '538DAE950337.pas.ms.script' // Core
 WL 'ME_53A038340371' '53A038340371.pas.ms.script' // MultiThread
 WL 'ME_53B15D5603E3' '53B15D5603E3.pas.ms.script' // TagHolder
 )
 ; // Depends

ref; // ME_544E0148010D Messages
