// Mail 5450CFDA02FF Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_5450CFDA02FF

FORWARD ME_5450D0130072

: ME_5450D05B00F7
 CONST UID '5450D05B00F7'
 CONST Name 'TMailServer'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_5450D0130072 // dt_Mail
 ;
 CONST "finished" false
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST extprop:rc:SelfName 'MailServer'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_5450D05B00F7 TMailServer

: ME_5450D0130072
 CONST UID '5450D0130072'
 CONST Name 'dt_Mail'
 CONST Class class_Class
 : Stereotype st_UtilityPack ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_5450CFDA02FF // Mail
 ;
 : Children
   Seq: ( ME_5450D05B00F7 // TMailServer
 )
 ; // Children
 CONST "finished" false
 CONST "no hands" false
 CONST intf.pas:Path 'common\components\rtl\Garant\DT\NOT_FINISHED_dt_Mail.pas'

ref; // ME_5450D0130072 dt_Mail

: ME_5450CFDA02FF
 CONST UID '5450CFDA02FF'
 CONST Name 'Mail'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_47BC4FCB0115' '47BC4FCB0115.pas.ms.script' // DT
 ;
 : Children
   Seq: ( ME_5450D0130072 // dt_Mail
 )
 ; // Children

ref; // ME_5450CFDA02FF Mail
