// Processing 545C744800D9 Library Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_545C744800D9
%%Inner ME_545C744800D9

ME ME_545C744800D9
 MEPROP UID '545C744800D9'
 MEPROP Name 'Processing'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Library ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4DE7F62B000D' '4DE7F62B000D.ms.model.script' // archi
 ;
 MELIST Children
   Seq: ( WL 'ME_545C74760255' '545C74760255.ms.model.script' // ExportDelivery
 WL 'ME_57CFC13E033D' '57CFC13E033D.ms.model.script' // DocTransfer
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_4677E16A022A' '4677E16A022A.ms.model.script' // K2
 WL 'ME_4677E18600C2' '4677E18600C2.ms.model.script' // dd
 WL 'ME_467A8734039C' '467A8734039C.ms.model.script' // EVD
 WL 'ME_469F3E37025A' '469F3E37025A.ms.model.script' // Rtl
 WL 'ME_4790D09A0378' '4790D09A0378.ms.model.script' // L3
 WL 'ME_47BC4FCB0115' '47BC4FCB0115.ms.model.script' // DT
 WL 'ME_4E25512D01C0' '4E25512D01C0.ms.model.script' // Utils
 WL 'ME_4E2F0E1B03BB' '4E2F0E1B03BB.ms.model.script' // L3$Domain
 WL 'ME_52F8C27F01AB' '52F8C27F01AB.ms.model.script' // cs
 WL 'ME_543244050044' '543244050044.ms.model.script' // DA
 WL 'ME_548712F60101' '548712F60101.ms.model.script' // m3$DB
 WL 'ME_57CFC97D017B' '57CFC97D017B.ms.model.script' // $Services
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "exec mode" 'concluded'
 UP "gui" 'prj'
 UP "is namespace" true
 UP "vendor" 'none'
 UP intf.pas:PathOnly '\archi\source\projects\Archi\Processing'

ENDME // ME_545C744800D9 Processing
