// TncsServerTransporterPool 545CBED90193 SimpleClass Class

INCLUDE '49E7754802A9.pas.ms.script'

INCLUDE '53A03846011C.pas.ms.script'

INCLUDE '51612ED700B4.pas.ms.script'

INCLUDE '47913F4E02E0.pas.ms.script'

FORWARD ME_545CBED90193

INCLUDE '545CBE61008B.pas.ms.script'

: ME_545CBF0E0186
 CONST UID '545CBF0E0186'
 CONST Name 'f_Data'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_545CBE61008B // TncsServerTransporterList
 ;

 @SELF
; // ME_545CBF0E0186 f_Data

INCLUDE '5460A4DB018A.pas.ms.script'

: ME_545CBF9100D6
 CONST UID '545CBF9100D6'
 CONST Name 'aTransporter'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_5465A5AB0324 // IncsServerTransporter
 ;

 @SELF
; // ME_545CBF9100D6 aTransporter

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_545CBF760027
 CONST UID '545CBF760027'
 CONST Name 'Register'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Parameters
   [ ME_545CBF9100D6 // aTransporter
 ]
 ; // Parameters

 @SELF
; // ME_545CBF760027 Register

: ME_545CBF9B00D6
 CONST UID '545CBF9B00D6'
 CONST Name 'aTransporter'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_5465A5AB0324 // IncsServerTransporter
 ;

 @SELF
; // ME_545CBF9B00D6 aTransporter

: ME_545CBF9602E1
 CONST UID '545CBF9602E1'
 CONST Name 'UnRegister'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Parameters
   [ ME_545CBF9B00D6 // aTransporter
 ]
 ; // Parameters

 @SELF
; // ME_545CBF9602E1 UnRegister

: ME_545CBFA2006D
 CONST UID '545CBFA2006D'
 CONST Name 'TerminateAll'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'

 @SELF
; // ME_545CBFA2006D TerminateAll

: ME_545CBED90193
 CONST UID '545CBED90193'
 CONST Name 'TncsServerTransporterPool'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_49E7754802A9 // Tl3ProtoObject
 ]
 ; // Inherits
 : Implements
   [ ME_53A03846011C // l3CriticalSectionHolder
 ]
 ; // Implements
 : Attributes
   [ ME_545CBF0E0186 // f_Data
 ]
 ; // Attributes
 : Operations
   [ ME_545CBF760027 // Register
 ME_545CBF9602E1 // UnRegister
 ME_545CBFA2006D // TerminateAll
 ]
 ; // Operations
 : Overridden
   [ ME_479731C50290 // Cleanup
 ME_47A042E100E2 // InitFields
 ]
 ; // Overridden
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_545CBED90193 TncsServerTransporterPool
