// evVisualInterfaces 547C9F6D029C Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_547C9F6D029C

FORWARD ME_547CA05403A0

: ME_547CA0B40252
 CONST UID '547CA0B40252'
 CONST Name 'Visible'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_547CA05403A0 // IevToolWindow
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 CONST "pm" true

ref; // ME_547CA0B40252 Visible

FORWARD ME_547CA089003C

: ME_547CA08F0332
 CONST Name 'iD'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A47F9302DA' '4677FBA70343.pas.ms.script' // Tl3Inch
 ;

ref; // ME_547CA08F0332 iD

: ME_547CA08D01F3
 CONST UID '547CA08D01F3'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_547CA089003C // Scroll
 ;
 : Parameters
   Seq: ( ME_547CA08F0332 // iD
 )
 ; // Parameters

ref; // ME_547CA08D01F3 DoIt

: ME_547CA089003C
 CONST UID '547CA089003C'
 CONST Name 'Scroll'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_547CA05403A0 // IevToolWindow
 ;
 : Operations
   Seq: ( ME_547CA08D01F3 // DoIt
 )
 ; // Operations

ref; // ME_547CA089003C Scroll

FORWARD ME_547CA0940115

: ME_0FE84DAC342F
 CONST UID '0FE84DAC342F'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY '—игнатура метода Invalidate' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_547CA0940115 // Invalidate
 ;

ref; // ME_0FE84DAC342F DoIt

: ME_547CA0940115
 CONST UID '547CA0940115'
 CONST Name 'Invalidate'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_547CA05403A0 // IevToolWindow
 ;
 : Operations
   Seq: ( ME_0FE84DAC342F // DoIt
 )
 ; // Operations

ref; // ME_547CA0940115 Invalidate

: ME_547CA05403A0
 CONST UID '547CA05403A0'
 CONST GUID '24069554-CCF1-4F74-924A-CD604876ED4A'
 CONST Name 'IevToolWindow'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_547C9F6D029C // evVisualInterfaces
 ;
 : Attributes
   Seq: ( ME_547CA0B40252 // Visible
 )
 ; // Attributes
 : Operations
   Seq: ( ME_547CA089003C // Scroll
 ME_547CA0940115 // Invalidate
 )
 ; // Operations
 CONST extprop:rc:SelfName 'ToolWindow'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_547CA05403A0 IevToolWindow

FORWARD ME_547CA0E40341

: ME_547CA11F002F
 CONST UID '547CA11F002F'
 CONST Name 'Control'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 %SUMMARY 'управл€ющий элемент, к которому прив€зана панель.' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_547CA0E40341 // IevLinkedToolWindow
 ;
 : Target WL 'ME_47E124E90272' '4799D29F033F.pas.ms.script' // TWinControl
 ;
 CONST "pm" true

ref; // ME_547CA11F002F Control

: ME_547CA089003C_ME_547CA0E40341
 : Original ME_547CA089003C // Scroll
 ;
 CONST OpKind opkind_Implemented
ref; // ME_547CA089003C_ME_547CA0E40341 Scroll

: ME_547CA0940115_ME_547CA0E40341
 : Original ME_547CA0940115 // Invalidate
 ;
 CONST OpKind opkind_Implemented
ref; // ME_547CA0940115_ME_547CA0E40341 Invalidate

: ME_547CA0B40252_ME_547CA0E40341
 : Original ME_547CA0B40252 // Visible
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_547CA0B40252_ME_547CA0E40341 Visible

: ME_547CA0E40341
 CONST UID '547CA0E40341'
 CONST GUID 'E478C43E-C7CA-4967-BB4C-690E3FB89782'
 CONST Name 'IevLinkedToolWindow'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_547C9F6D029C // evVisualInterfaces
 ;
 : Inherits
   Seq: ( ME_547CA05403A0 // IevToolWindow
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_547CA11F002F // Control
 )
 ; // Attributes
 : Implemented
   Seq: ( ME_547CA089003C_ME_547CA0E40341 // Scroll
 ME_547CA0940115_ME_547CA0E40341 // Invalidate
 ME_547CA0B40252_ME_547CA0E40341 // Visible
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'LinkedToolWindow'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_547CA0E40341 IevLinkedToolWindow

FORWARD ME_547CA15E035E

: ME_547CA1860092
 CONST UID '547CA1860092'
 CONST Name 'Zoom'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_547CA15E035E // IevZoomedLinkedToolWindow
 ;
 : Target WL 'ME_479F11C800E4' '4AB0C3C60310.pas.ms.script' // SmallInt
 ;
 CONST "pm" true

ref; // ME_547CA1860092 Zoom

: ME_547CA089003C_ME_547CA15E035E
 : Original ME_547CA089003C // Scroll
 ;
 CONST OpKind opkind_Implemented
ref; // ME_547CA089003C_ME_547CA15E035E Scroll

: ME_547CA0940115_ME_547CA15E035E
 : Original ME_547CA0940115 // Invalidate
 ;
 CONST OpKind opkind_Implemented
ref; // ME_547CA0940115_ME_547CA15E035E Invalidate

: ME_547CA0B40252_ME_547CA15E035E
 : Original ME_547CA0B40252 // Visible
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_547CA0B40252_ME_547CA15E035E Visible

: ME_547CA11F002F_ME_547CA15E035E
 : Original ME_547CA11F002F // Control
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_547CA11F002F_ME_547CA15E035E Control

: ME_547CA15E035E
 CONST UID '547CA15E035E'
 CONST GUID 'EA309B79-4F35-4C80-879E-D19BC4654F3C'
 CONST Name 'IevZoomedLinkedToolWindow'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_547C9F6D029C // evVisualInterfaces
 ;
 : Inherits
   Seq: ( ME_547CA0E40341 // IevLinkedToolWindow
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_547CA1860092 // Zoom
 )
 ; // Attributes
 : Implemented
   Seq: ( ME_547CA089003C_ME_547CA15E035E // Scroll
 ME_547CA0940115_ME_547CA15E035E // Invalidate
 ME_547CA0B40252_ME_547CA15E035E // Visible
 ME_547CA11F002F_ME_547CA15E035E // Control
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'ZoomedLinkedToolWindow'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_547CA15E035E IevZoomedLinkedToolWindow

FORWARD ME_547CA1B10228

FORWARD ME_547CA1CA0126

: ME_547CA1D401E8
 CONST Name 'aR'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_537B7CC80279' '4677FBA70343.pas.ms.script' // Tl3Rect
 ;

ref; // ME_547CA1D401E8 aR

: ME_547CA1D401FE
 CONST Name 'aSub'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47C6B03200AF' '47C5207602D1.pas.ms.script' // IevSub
 ;

ref; // ME_547CA1D401FE aSub

: ME_547CA1CF0023
 CONST UID '547CA1CF0023'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_547CA1CA0126 // NeedDrawSub
 ;
 : Parameters
   Seq: ( ME_547CA1D401E8 // aR
 ME_547CA1D401FE // aSub
 )
 ; // Parameters

ref; // ME_547CA1CF0023 DoIt

: ME_547CA1CA0126
 CONST UID '547CA1CA0126'
 CONST Name 'NeedDrawSub'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_547CA1B10228 // IevSubPanel
 ;
 : Operations
   Seq: ( ME_547CA1CF0023 // DoIt
 )
 ; // Operations

ref; // ME_547CA1CA0126 NeedDrawSub

: ME_547CA089003C_ME_547CA1B10228
 : Original ME_547CA089003C // Scroll
 ;
 CONST OpKind opkind_Implemented
ref; // ME_547CA089003C_ME_547CA1B10228 Scroll

: ME_547CA0940115_ME_547CA1B10228
 : Original ME_547CA0940115 // Invalidate
 ;
 CONST OpKind opkind_Implemented
ref; // ME_547CA0940115_ME_547CA1B10228 Invalidate

: ME_547CA0B40252_ME_547CA1B10228
 : Original ME_547CA0B40252 // Visible
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_547CA0B40252_ME_547CA1B10228 Visible

: ME_547CA11F002F_ME_547CA1B10228
 : Original ME_547CA11F002F // Control
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_547CA11F002F_ME_547CA1B10228 Control

: ME_547CA1860092_ME_547CA1B10228
 : Original ME_547CA1860092 // Zoom
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_547CA1860092_ME_547CA1B10228 Zoom

: ME_547CA1B10228
 CONST UID '547CA1B10228'
 CONST GUID '14C0338E-1370-4504-AE4E-89C994E9E2AC'
 CONST Name 'IevSubPanel'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_547C9F6D029C // evVisualInterfaces
 ;
 : Inherits
   Seq: ( ME_547CA15E035E // IevZoomedLinkedToolWindow
 )
 ; // Inherits
 : Operations
   Seq: ( ME_547CA1CA0126 // NeedDrawSub
 )
 ; // Operations
 : Implemented
   Seq: ( ME_547CA089003C_ME_547CA1B10228 // Scroll
 ME_547CA0940115_ME_547CA1B10228 // Invalidate
 ME_547CA0B40252_ME_547CA1B10228 // Visible
 ME_547CA11F002F_ME_547CA1B10228 // Control
 ME_547CA1860092_ME_547CA1B10228 // Zoom
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'SubPanel'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_547CA1B10228 IevSubPanel

FORWARD ME_547CA2130299

: ME_547CA23C010C
 CONST Name 'aSender'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4807745602C8' '4AB0C3C60310.pas.ms.script' // TObject
 ;

ref; // ME_547CA23C010C aSender

: ME_547CA23C0126
 CONST Name 'aMarker'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47C6885E01DF' '47C5207602D1.pas.ms.script' // IevMarker
 ;

ref; // ME_547CA23C0126 aMarker

: ME_547CA23C0151
 CONST Name 'aValue'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_547CA23C0151 aValue

: ME_547CA22B0293
 CONST UID '547CA22B0293'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_547CA2130299 // TevOnSetMarker
 ;
 : Parameters
   Seq: ( ME_547CA23C010C // aSender
 ME_547CA23C0126 // aMarker
 ME_547CA23C0151 // aValue
 )
 ; // Parameters

ref; // ME_547CA22B0293 DoIt

: ME_547CA2130299
 CONST UID '547CA2130299'
 CONST Name 'TevOnSetMarker'
 CONST Class class_Class
 : Stereotype st_Function ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_547C9F6D029C // evVisualInterfaces
 ;
 : Operations
   Seq: ( ME_547CA22B0293 // DoIt
 )
 ; // Operations
 CONST "of object" true

ref; // ME_547CA2130299 TevOnSetMarker

FORWARD ME_547CA4880250

: ME_547CA52501AE
 CONST UID '547CA52501AE'
 CONST Name 'Margin'
 CONST Class class_Attribute
 : Stereotype st_writeonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_547CA4880250 // IevRuler
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "pm" true

ref; // ME_547CA52501AE Margin

: ME_547CA5440360
 CONST UID '547CA5440360'
 CONST Name 'Delta'
 CONST Class class_Attribute
 : Stereotype st_writeonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_547CA4880250 // IevRuler
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "pm" true

ref; // ME_547CA5440360 Delta

: ME_547CA55D03B6
 CONST UID '547CA55D03B6'
 CONST Name 'OnSetMarker'
 CONST Class class_Attribute
 : Stereotype st_writeonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent ME_547CA4880250 // IevRuler
 ;
 : Target ME_547CA2130299 // TevOnSetMarker
 ;
 CONST "pm" true

ref; // ME_547CA55D03B6 OnSetMarker

FORWARD ME_547CA4A80023

: ME_547CA4B00012
 CONST Name 'aView'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47C5B97302B2' '47C5207602D1.pas.ms.script' // InevView
 ;

ref; // ME_547CA4B00012 aView

: ME_547CA4B00028
 CONST Name 'aCursor'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47C6899A00AB' '47C5207602D1.pas.ms.script' // IevMarkersSource
 ;

ref; // ME_547CA4B00028 aCursor

: ME_547CA4AD022C
 CONST UID '547CA4AD022C'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_547CA4A80023 // MarkersChanged
 ;
 : Parameters
   Seq: ( ME_547CA4B00012 // aView
 ME_547CA4B00028 // aCursor
 )
 ; // Parameters

ref; // ME_547CA4AD022C DoIt

: ME_547CA4A80023
 CONST UID '547CA4A80023'
 CONST Name 'MarkersChanged'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_547CA4880250 // IevRuler
 ;
 : Operations
   Seq: ( ME_547CA4AD022C // DoIt
 )
 ; // Operations

ref; // ME_547CA4A80023 MarkersChanged

FORWARD ME_547CA4E4039A

: ME_547CA4ED0275
 CONST Name 'aView'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47C5B97302B2' '47C5207602D1.pas.ms.script' // InevView
 ;

ref; // ME_547CA4ED0275 aView

: ME_547CA4E903BC
 CONST UID '547CA4E903BC'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_547CA4E4039A // ViewChanged
 ;
 : Parameters
   Seq: ( ME_547CA4ED0275 // aView
 )
 ; // Parameters

ref; // ME_547CA4E903BC DoIt

: ME_547CA4E4039A
 CONST UID '547CA4E4039A'
 CONST Name 'ViewChanged'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_547CA4880250 // IevRuler
 ;
 : Operations
   Seq: ( ME_547CA4E903BC // DoIt
 )
 ; // Operations

ref; // ME_547CA4E4039A ViewChanged

FORWARD ME_547CA4F10142

: ME_96DDA80DEAD3
 CONST UID '96DDA80DEAD3'
 CONST Name 'DoIt'
 CONST IsSummoned true
 CONST Class class_Operation
 %SUMMARY '—игнатура метода ControlMoved' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_547CA4F10142 // ControlMoved
 ;

ref; // ME_96DDA80DEAD3 DoIt

: ME_547CA4F10142
 CONST UID '547CA4F10142'
 CONST Name 'ControlMoved'
 CONST Class class_Class
 : Stereotype st_facetmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_547CA4880250 // IevRuler
 ;
 : Operations
   Seq: ( ME_96DDA80DEAD3 // DoIt
 )
 ; // Operations

ref; // ME_547CA4F10142 ControlMoved

: ME_547CA089003C_ME_547CA4880250
 : Original ME_547CA089003C // Scroll
 ;
 CONST OpKind opkind_Implemented
ref; // ME_547CA089003C_ME_547CA4880250 Scroll

: ME_547CA0940115_ME_547CA4880250
 : Original ME_547CA0940115 // Invalidate
 ;
 CONST OpKind opkind_Implemented
ref; // ME_547CA0940115_ME_547CA4880250 Invalidate

: ME_547CA0B40252_ME_547CA4880250
 : Original ME_547CA0B40252 // Visible
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_547CA0B40252_ME_547CA4880250 Visible

: ME_547CA11F002F_ME_547CA4880250
 : Original ME_547CA11F002F // Control
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_547CA11F002F_ME_547CA4880250 Control

: ME_547CA1860092_ME_547CA4880250
 : Original ME_547CA1860092 // Zoom
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" true
ref; // ME_547CA1860092_ME_547CA4880250 Zoom

: ME_547CA4880250
 CONST UID '547CA4880250'
 CONST GUID 'F2A24FCB-171C-4DB8-A4FA-202396805059'
 CONST Name 'IevRuler'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_547C9F6D029C // evVisualInterfaces
 ;
 : Inherits
   Seq: ( ME_547CA15E035E // IevZoomedLinkedToolWindow
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_547CA52501AE // Margin
 ME_547CA5440360 // Delta
 ME_547CA55D03B6 // OnSetMarker
 )
 ; // Attributes
 : Operations
   Seq: ( ME_547CA4A80023 // MarkersChanged
 ME_547CA4E4039A // ViewChanged
 ME_547CA4F10142 // ControlMoved
 )
 ; // Operations
 : Implemented
   Seq: ( ME_547CA089003C_ME_547CA4880250 // Scroll
 ME_547CA0940115_ME_547CA4880250 // Invalidate
 ME_547CA0B40252_ME_547CA4880250 // Visible
 ME_547CA11F002F_ME_547CA4880250 // Control
 ME_547CA1860092_ME_547CA4880250 // Zoom
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'Ruler'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_547CA4880250 IevRuler

: ME_547C9F6D029C
 CONST UID '547C9F6D029C'
 CONST Name 'evVisualInterfaces'
 CONST Class class_Category
 : Stereotype st_Interfaces ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4797632D0273' '4797632D0273.pas.ms.script' // Everest
 ;
 : Children
   Seq: ( ME_547CA05403A0 // IevToolWindow
 ME_547CA0E40341 // IevLinkedToolWindow
 ME_547CA15E035E // IevZoomedLinkedToolWindow
 ME_547CA1B10228 // IevSubPanel
 ME_547CA2130299 // TevOnSetMarker
 ME_547CA4880250 // IevRuler
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4677FBA70343' '4677FBA70343.pas.ms.script' // l3Interfaces
 WL 'ME_472745450206' '472745450206.pas.ms.script' // l3Units
 WL 'ME_4799D29F033F' '4799D29F033F.pas.ms.script' // Implementation
 WL 'ME_47C5207602D1' '47C5207602D1.pas.ms.script' // nevTools
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 )
 ; // Depends
 CONST "is namespace" true
 CONST "no hands" false
 CONST intf.pas:Path 'common\components\gui\Garant\Everest\evVisualInterfaces.pas'

ref; // ME_547C9F6D029C evVisualInterfaces
