// VT$Panels 547CC9D40158 Library Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_547CC9D40158

ME ME_547CC9D40158
 MEPROP UID '547CC9D40158'
 MEPROP Name 'VT'
 MEPROP OriginalName 'VT$Panels'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Library ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4677DDBD0193' '4677DDBD0193.ms.model.script' // Shared Delphi
 ;
 MELIST Children
   Seq: ( WL 'ME_4A7960CC03A4' '4A7960CC03A4.ms.model.script' //  Panels
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_4684F91300DD' '4684F91300DD.ms.model.script' // Vcl
 WL 'ME_469F3E37025A' '469F3E37025A.ms.model.script' // Rtl
 WL 'ME_4790B4F00236' '4790B4F00236.ms.model.script' // AFW
 WL 'ME_4790D09A0378' '4790D09A0378.ms.model.script' // L3
 WL 'ME_4D5E61FC01F0' '4D5E61FC01F0.ms.model.script' // AFW$Core
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'uses' )
 ; // DiagramsNames
 UP "UseNewGen" true
 UP "defines" 'vtDefine.inc'
 UP "exec mode" 'concluded'
 UP "gui" 'gui'
 UP "is namespace" true
 UP "vendor" '/Garant'
 UP intf.pas:PathOnly '\common\components\gui\Garant\VT'

ENDME // ME_547CC9D40158 VT$Panels
