// eeSubPanel 54817B05034F Views Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_54817B05034F

FORWARD ME_4C7F94A9028D

FORWARD ME_5481C789009F

: ME_5481C7C30220
 CONST UID '5481C7C30220'
 CONST Name 'aSubType'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_5481C7C30220 aSubType

: ME_5481C7C3023A
 CONST UID '5481C7C3023A'
 CONST Name 'aSubHandle'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_5481C7C3023A aSubHandle

: ME_5481C7BC035A
 CONST UID '5481C7BC035A'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_5481C789009F // GetHotSpot
 ;
 : Target WL 'ME_4F82F62D03BE' '4912DD020283.pas.ms.script' // IeeHotSpot
 ;
 : Parameters
   @ ( ME_5481C7C30220 // aSubType
 ME_5481C7C3023A // aSubHandle
 ) .SequenceCode.It
 ; // Parameters

ref; // ME_5481C7BC035A DoIt

: ME_5481C789009F
 CONST UID '5481C789009F'
 CONST Name 'GetHotSpot'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent ME_4C7F94A9028D // TeeSubPanelExport
 ;
 : Operations
   @ ( ME_5481C7BC035A // DoIt
 ) .SequenceCode.It
 ; // Operations

ref; // ME_5481C789009F GetHotSpot

FORWARD ME_5481D1B20067

: ME_5481D1C20393
 CONST UID '5481D1C20393'
 CONST Name 'aX'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_5481D1C20393 aX

: ME_5481D1C203B5
 CONST UID '5481D1C203B5'
 CONST Name 'aY'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_5481D1C203B5 aY

: ME_5481D1C203DF
 CONST UID '5481D1C203DF'
 CONST Name 'theSub'
 CONST Class class_Parameter
 : Stereotype st_out ;
 : Target WL 'ME_4AE9DFBF0327' '4912DD020283.pas.ms.script' // IeeSub
 ;

ref; // ME_5481D1C203DF theSub

: ME_5481D1B900E0
 CONST UID '5481D1B900E0'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_5481D1B20067 // CheckSubOnPoint
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;
 : Parameters
   @ ( ME_5481D1C20393 // aX
 ME_5481D1C203B5 // aY
 ME_5481D1C203DF // theSub
 ) .SequenceCode.It
 ; // Parameters

ref; // ME_5481D1B900E0 DoIt

: ME_5481D1B20067
 CONST UID '5481D1B20067'
 CONST Name 'CheckSubOnPoint'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_4C7F94A9028D // TeeSubPanelExport
 ;
 : Operations
   @ ( ME_5481D1B900E0 // DoIt
 ) .SequenceCode.It
 ; // Operations

ref; // ME_5481D1B20067 CheckSubOnPoint

: ME_56DC4EE7D6EC
 CONST UID '56DC4EE7D6EC'
 CONST Name 'Ini_Reg_Class'
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация TeeSubPanelExport' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4C7F94A9028D // TeeSubPanelExport
 ;
 CONST "ifndef" 'NoScripts'

ref; // ME_56DC4EE7D6EC Ini_Reg_Class

: ME_5481C7FC03BB
 CONST UID '5481C7FC03BB'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C7F94A9028D // TeeSubPanelExport
 ;
 : Target WL 'ME_47C6B03200AF' '47C5207602D1.pas.ms.script' // IevSub
 ;

ref; // ME_5481C7FC03BB 

: ME_5481C8320140
 CONST UID '5481C8320140'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C7F94A9028D // TeeSubPanelExport
 ;
 : Target WL 'ME_49523C96004A' '49523C640160.pas.ms.script' // IeeDocumentEx
 ;

ref; // ME_5481C8320140 

: ME_5481E45F02A2
 CONST UID '5481E45F02A2'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C7F94A9028D // TeeSubPanelExport
 ;
 : Target WL 'ME_5481DE430189' '46834DB20230.pas.ms.script' // eeSubDescriptorsExport
 ;

ref; // ME_5481E45F02A2 

: ME_5481E47E014C
 CONST UID '5481E47E014C'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C7F94A9028D // TeeSubPanelExport
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_5481E47E014C 

: ME_548707B70059
 CONST UID '548707B70059'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C7F94A9028D // TeeSubPanelExport
 ;
 : Target WL 'ME_54817DA2016E' '4912E16B01B4.pas.ms.script' // TeeSub
 ;

ref; // ME_548707B70059 

: ME_54870CC80160
 CONST UID '54870CC80160'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C7F94A9028D // TeeSubPanelExport
 ;
 : Target WL 'ME_5481DD0C0363' '4912E16B01B4.pas.ms.script' // TeeHotSpot
 ;

ref; // ME_54870CC80160 

: ME_FDFD45908C09
 CONST UID 'FDFD45908C09'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C7F94A9028D // TeeSubPanelExport
 ;
 : Target WL 'ME_561F9F9400BC' '561F9F7D02A7.pas.ms.script' // TtfwClassRef
 ;

ref; // ME_FDFD45908C09 

: ME_5481A0B20112_ME_4C7F94A9028D
 CONST UID '5481A0B20112'
 CONST Name 'SubViewDescriptors'
 : Original WL 'ME_5481A0B20112' '4912DD020283.pas.ms.script' // SubViewDescriptors
 ;
 : Implementor ME_4C7F94A9028D // TeeSubPanelExport
 ;
 CONST "pm" false
ref; // ME_5481A0B20112_ME_4C7F94A9028D SubViewDescriptors

: ME_4C7F94A9028D
 CONST UID '4C7F94A9028D'
 CONST Name 'TeeSubPanelExport'
 CONST Class class_Class
 : Stereotype st_GuiControl ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_54817B05034F // eeSubPanel
 ;
 : Inherits
   @ ( WL 'ME_547DC47400EC' '547CB376012F.pas.ms.script' // TevCustomSubPanel
 ) .SequenceCode.It
 ; // Inherits
 : Implements
   @ ( WL 'ME_5481A06803E5' '4912DD020283.pas.ms.script' // IeeSubPanel
 ) .SequenceCode.It
 ; // Implements
 : Operations
   @ ( ME_5481C789009F // GetHotSpot
 ME_5481D1B20067 // CheckSubOnPoint
 ME_56DC4EE7D6EC // Ini_Reg_Class
 ) .SequenceCode.It
 ; // Operations
 : Implemented
   @ ( ME_5481A0B20112_ME_4C7F94A9028D // SubViewDescriptors
 ) .SequenceCode.It
 ; // Implemented
 : Dependencies
   @ ( ME_5481C7FC03BB // 
 ME_5481C8320140 // 
 ME_5481E45F02A2 // 
 ME_5481E47E014C // 
 ME_548707B70059 // 
 ME_54870CC80160 // 
 ME_FDFD45908C09 // 
 ) .SequenceCode.It
 ; // Dependencies
 CONST "base wnd class" 'CWnd'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 : Generators
 @ (
 gen_intf.pas
 ) .SequenceCode.It
 ; // Generators
 CONST intf.pas:Path 'common\components\gui\Garant\Everest_Engine\eeSubPanelExport.pas'

ref; // ME_4C7F94A9028D TeeSubPanelExport

FORWARD ME_4C7F948C03BD

FORWARD ME_5481CCAE029D

: ME_5481CD0A031C
 CONST UID '5481CD0A031C'
 CONST Name 'SubPanel'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent ME_5481CCAE029D // TeeCustomSubPanel
 ;
 : Target WL 'ME_5481A06803E5' '4912DD020283.pas.ms.script' // IeeSubPanel
 ;
 CONST "pm" true

ref; // ME_5481CD0A031C SubPanel

: ME_97832EB23688
 CONST UID '97832EB23688'
 CONST Name 'Ini_Reg_Class'
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация TeeCustomSubPanel' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_5481CCAE029D // TeeCustomSubPanel
 ;
 CONST "ifndef" 'NoScripts'

ref; // ME_97832EB23688 Ini_Reg_Class

: ME_453767DC7293
 CONST UID '453767DC7293'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_5481CCAE029D // TeeCustomSubPanel
 ;
 : Target WL 'ME_561F9F9400BC' '561F9F7D02A7.pas.ms.script' // TtfwClassRef
 ;

ref; // ME_453767DC7293 

: ME_5481CCAE029D
 CONST UID '5481CCAE029D'
 CONST Name 'TeeCustomSubPanel'
 CONST Class class_Class
 : Stereotype st_GuiControl ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_4C7F948C03BD // TeeSubPanel
 ;
 : Inherits
   @ ( ME_4C7F94A9028D // TeeSubPanelExport
 ) .SequenceCode.It
 ; // Inherits
 : Attributes
   @ ( ME_5481CD0A031C // SubPanel
 ) .SequenceCode.It
 ; // Attributes
 : Operations
   @ ( ME_97832EB23688 // Ini_Reg_Class
 ) .SequenceCode.It
 ; // Operations
 : Dependencies
   @ ( ME_453767DC7293 // 
 ) .SequenceCode.It
 ; // Dependencies
 CONST "base wnd class" 'CWnd'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

ref; // ME_5481CCAE029D TeeCustomSubPanel

: ME_0FF03C69F5AB
 CONST UID '0FF03C69F5AB'
 CONST Name 'Ini_Reg_Class'
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация TeeSubPanel' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4C7F948C03BD // TeeSubPanel
 ;
 CONST "ifndef" 'NoScripts'

ref; // ME_0FF03C69F5AB Ini_Reg_Class

: ME_351FF70040A0
 CONST UID '351FF70040A0'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4C7F948C03BD // TeeSubPanel
 ;
 : Target WL 'ME_561F9F9400BC' '561F9F7D02A7.pas.ms.script' // TtfwClassRef
 ;

ref; // ME_351FF70040A0 

: ME_4C7F948C03BD
 CONST UID '4C7F948C03BD'
 CONST Name 'TeeSubPanel'
 CONST Class class_Class
 : Stereotype st_GuiControl ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_54817B05034F // eeSubPanel
 ;
 : Inherits
   @ ( ME_5481CCAE029D // TeeCustomSubPanel
 ) .SequenceCode.It
 ; // Inherits
 : Operations
   @ ( ME_0FF03C69F5AB // Ini_Reg_Class
 ) .SequenceCode.It
 ; // Operations
 : Children
   @ ( ME_5481CCAE029D // TeeCustomSubPanel
 ) .SequenceCode.It
 ; // Children
 : Dependencies
   @ ( ME_351FF70040A0 // 
 ) .SequenceCode.It
 ; // Dependencies
 CONST "base wnd class" 'CWnd'
 CONST "need UC" true
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 : Generators
 @ (
 gen_intf.pas
 ) .SequenceCode.It
 ; // Generators
 CONST intf.pas:Path 'common\components\gui\Garant\Everest_Engine\eeSubPanel.pas'

ref; // ME_4C7F948C03BD TeeSubPanel

: ME_54817B05034F
 CONST UID '54817B05034F'
 CONST Name 'eeSubPanel'
 CONST Class class_Category
 : Stereotype st_Views ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4680E7D50168' '4680E7D50168.pas.ms.script' // Everest Engine
 ;
 : Children
   @ ( ME_4C7F94A9028D // TeeSubPanelExport
 ME_4C7F948C03BD // TeeSubPanel
 ) .SequenceCode.It
 ; // Children
 : Depends
   @ ( WL 'ME_46834DB20230' '46834DB20230.pas.ms.script' // eeSubExport
 WL 'ME_47C5207602D1' '47C5207602D1.pas.ms.script' // nevTools
 WL 'ME_4912DD020283' '4912DD020283.pas.ms.script' // eeInterfaces
 WL 'ME_4912E16B01B4' '4912E16B01B4.pas.ms.script' // Engine Core
 WL 'ME_49523C640160' '49523C640160.pas.ms.script' // eeInterfacesEx
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_547CB376012F' '547CB376012F.pas.ms.script' // ToolPanel
 WL 'ME_561F9F7D02A7' '561F9F7D02A7.pas.ms.script' // ScriptEngine
 ) .SequenceCode.It
 ; // Depends
 : Generators
 @ (
 gen_pas.script
 gen_pas.script.runner
 ) .SequenceCode.It
 ; // Generators
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\54817B05034F.pas.ms.script'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\54817B05034F.pas.ms.script.runner'

ref; // ME_54817B05034F eeSubPanel
