// StorageHolder 5486E32B0191 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_5486E32B0191
%%Inner ME_5486E32B0191
%%Inner ME_5486E32B0191
%%Inner ME_5486E32B0191

ME ME_5486E32B0191
 MEPROP UID '5486E32B0191'
 MEPROP Name 'StorageHolder'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_472082480337' // m3
 ;
 MELIST Children
   Seq: ( WL? 'ME_542E5D79018F' // Tm3StorageHolder
 WL? 'ME_542E7AB80220' // Tm3StorageHolderListPrim
 WL? 'ME_542E8D2902F1' // Tm3StorageHolderListPrim1
 WL? 'ME_542E7AD00050' // Tm3StorageHolderList
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4678193C009C' // l3Types
 WL? 'ME_46A0E6C5023A' // ActiveX
 WL? 'ME_4720862F0238' // m3StorageInterfaces
 WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_47BB24D30205' // Стандартные примеси
 WL? 'ME_48294AA903A6' // m3CoreObjects
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_4AB0C3F60375' // Win
 WL? 'ME_53A038340371' // MultiThread
 WL? 'ME_54B90AC6014B' // StringUtils
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_5486E32B0191 StorageHolder
