// TeeDocumentCursorPair 54BE50DC0032 SimpleClass Class

: ME_54BE50DC0032
 CONST UID '54BE50DC0032'
 CONST Name 'TeeDocumentCursorPair'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_54BE50DC0032 TeeDocumentCursorPair
