// eeExceptions 54C13B1601FD Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_54C13B1601FD

: ME_54C13B850149
 CONST UID '54C13B850149'
 CONST Name 'EeeUserCommentsHidden'
 CONST Class class_Class
 : Stereotype st_Exception ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_54C13B1601FD // eeExceptions
 ;
 CONST intf.pas:PathOnly '\common\components\gui\Garant\Everest_Engine'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_54C13B850149 EeeUserCommentsHidden

: ME_54C13B1601FD
 CONST UID '54C13B1601FD'
 CONST Name 'eeExceptions'
 CONST Class class_Category
 : Stereotype st_Interfaces ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_4680E7D50168' '4680E7D50168.pas.ms.script' // Everest Engine
 ;
 : Children
   Seq: ( ME_54C13B850149 // EeeUserCommentsHidden
 )
 ; // Children
 CONST "finished" false
 CONST "is namespace" true
 CONST "no hands" false
 CONST intf.pas:Path 'common\components\gui\Garant\Everest_Engine\NOT_FINISHED_eeExceptions.pas'
 CONST intf.pas:PathOnly '\common\components\gui\Garant\Everest_Engine'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\54C13B1601FD.pas.ms.script'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\54C13B1601FD.pas.ms.script.runner'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_54C13B1601FD eeExceptions
