// VCL bindings 54DB92D203C9 ScriptKeywords Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_54DB92D203C9

FORWARD ME_4DB95922039B

: ME_4DB959410236
 CONST UID '4DB959410236'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4DB95922039B // SystemWord
 ;
 : Target WL 'ME_4DDE2C4C01CD' '4AB0C3F60375.pas.ms.script' // GetFocus
 ;

ref; // ME_4DB959410236 

: ME_4DB9594F038D
 CONST UID '4DB9594F038D'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4DB95922039B // SystemWord
 ;
 : Target WL 'ME_4AAF9CFA0263' '4799D29F033F.pas.ms.script' // FindControl
 ;

ref; // ME_4DB9594F038D 

: ME_4DB961430283
 CONST UID '4DB961430283'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4DB95922039B // SystemWord
 ;
 : Target WL 'ME_47E13C6B0341' '4799D29F033F.pas.ms.script' // Forms
 ;

ref; // ME_4DB961430283 

: ME_4DB95922039B
 CONST UID '4DB95922039B'
 CONST Name 'SystemWord'
 CONST Class class_Class
 : Stereotype st_Impurity ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_54DB92D203C9 // VCL bindings
 ;
 : Dependencies
   Seq: ( ME_4DB959410236 // 
 ME_4DB9594F038D // 
 ME_4DB961430283 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\SystemWord.imp.pas'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\ScriptEngine'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'
 CONST extprop:pas:TypeName '_SystemWord_'
 CONST extprop:pas:UnitName 'SystemWord.imp'

ref; // ME_4DB95922039B SystemWord

FORWARD ME_4F2148300318

FORWARD ME_4F21485E0184

: ME_4F2148780352
 CONST UID '4F2148780352'
 CONST Name 'aComponent'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_4F2148780352 aComponent

: ME_4F21487803A9
 CONST UID '4F21487803A9'
 CONST Name 'aCtx'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4DB0091E033E' '4DAF19F600C5.pas.ms.script' // TtfwContext
 ;

ref; // ME_4F21487803A9 aCtx

: ME_4F21486A00E3
 CONST UID '4F21486A00E3'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F21485E0184 // DoComponent
 ;
 : Parameters
   Seq: ( ME_4F2148780352 // aComponent
 ME_4F21487803A9 // aCtx
 )
 ; // Parameters

ref; // ME_4F21486A00E3 DoIt

: ME_4F21485E0184
 CONST UID '4F21485E0184'
 CONST Name 'DoComponent'
 CONST Class class_Class
 : Stereotype st_abstractmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent ME_4F2148300318 // TkwComponentFromStackWord
 ;
 : Operations
   Seq: ( ME_4F21486A00E3 // DoIt
 )
 ; // Operations

ref; // ME_4F21485E0184 DoComponent

: ME_8AA6471D8C63
 CONST UID '8AA6471D8C63'
 CONST Name 'Ini_Reg_Class'
 CONST IsSummoned true
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация TkwComponentFromStackWord' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F2148300318 // TkwComponentFromStackWord
 ;
 CONST "ifndef" 'NoScripts'

ref; // ME_8AA6471D8C63 Ini_Reg_Class

: ME_4F212BD5010E_ME_4F2148300318
 CONST UID '4F212BD5010E'
 CONST Name 'DoObject'
 : Original WL 'ME_4F212BD5010E' '54DC9ACA0156.pas.ms.script' // DoObject
 ;
 : Implementor ME_4F2148300318 // TkwComponentFromStackWord
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F212BD5010E_ME_4F2148300318 DoObject

: ME_4F2148300318
 CONST UID '4F2148300318'
 CONST Name 'TkwComponentFromStackWord'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_54DB92D203C9 // VCL bindings
 ;
 : Inherits
   Seq: ( WL 'ME_4F212BA80137' '54DC9ACA0156.pas.ms.script' // TkwObjectFromStackWord
 )
 ; // Inherits
 : Implements
   Seq: ( ME_4DB95922039B // SystemWord
 )
 ; // Implements
 : Operations
   Seq: ( ME_4F21485E0184 // DoComponent
 ME_8AA6471D8C63 // Ini_Reg_Class
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4F212BD5010E_ME_4F2148300318 // DoObject
 )
 ; // Implemented
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\kwComponentFromStackWord.pas'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\ScriptEngine'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'
 CONST extprop:rc:SelfName 'ComponentFromStackWord'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'kwComponentFromStackWord'

ref; // ME_4F2148300318 TkwComponentFromStackWord

FORWARD ME_4F212C120371

FORWARD ME_4F212C3A015A

: ME_4F212C5E001D
 CONST UID '4F212C5E001D'
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47E1201703C3' '4799D29F033F.pas.ms.script' // TControl
 ;

ref; // ME_4F212C5E001D aControl

: ME_4F212C5E006E
 CONST UID '4F212C5E006E'
 CONST Name 'aCtx'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4DB0091E033E' '4DAF19F600C5.pas.ms.script' // TtfwContext
 ;

ref; // ME_4F212C5E006E aCtx

: ME_4F212C5B0201
 CONST UID '4F212C5B0201'
 CONST Name 'DoControl'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F212C3A015A // DoControl
 ;
 : Parameters
   Seq: ( ME_4F212C5E001D // aControl
 ME_4F212C5E006E // aCtx
 )
 ; // Parameters

ref; // ME_4F212C5B0201 DoControl

: ME_4F212C3A015A
 CONST UID '4F212C3A015A'
 CONST Name 'DoControl'
 CONST Class class_Class
 : Stereotype st_abstractmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent ME_4F212C120371 // kwControlFromStackWord
 ;
 : Operations
   Seq: ( ME_4F212C5B0201 // DoControl
 )
 ; // Operations

ref; // ME_4F212C3A015A DoControl

: ME_4F21485E0184_ME_4F212C120371
 CONST UID '4F21485E0184'
 CONST Name 'DoComponent'
 : Original ME_4F21485E0184 // DoComponent
 ;
 : Implementor ME_4F212C120371 // kwControlFromStackWord
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F21485E0184_ME_4F212C120371 DoComponent

: ME_4F212C120371
 CONST UID '4F212C120371'
 CONST Name 'kwControlFromStackWord'
 CONST Class class_Class
 : Stereotype st_Impurity ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_54DB92D203C9 // VCL bindings
 ;
 : Inherits
   Seq: ( ME_4F2148300318 // TkwComponentFromStackWord
 )
 ; // Inherits
 : Operations
   Seq: ( ME_4F212C3A015A // DoControl
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4F21485E0184_ME_4F212C120371 // DoComponent
 )
 ; // Implemented
 CONST "author" 'Люлин А.В.'
 CONST "ifndef" 'NoVCL'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '26.01.2012 14:34'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\kwControlFromStackWord.imp.pas'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\ScriptEngine'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'
 CONST extprop:pas:TypeName '_kwControlFromStackWord_'
 CONST extprop:pas:UnitName 'kwControlFromStackWord.imp'

ref; // ME_4F212C120371 kwControlFromStackWord

FORWARD ME_508527F30183

FORWARD ME_508528490090

: ME_5085286902DF
 CONST UID '5085286902DF'
 CONST Name 'aName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_5085286902DF aName

: ME_508528690318
 CONST UID '508528690318'
 CONST Name 'aClass'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476775CB036A' '4AB0C3C60310.pas.ms.script' // TClass
 ;

ref; // ME_508528690318 aClass

: ME_50852857013B
 CONST UID '50852857013B'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_508528490090 // Register
 ;
 : Parameters
   Seq: ( ME_5085286902DF // aName
 ME_508528690318 // aClass
 )
 ; // Parameters

ref; // ME_50852857013B DoIt

: ME_508528490090
 CONST UID '508528490090'
 CONST Name 'Register'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_508527F30183 // TtfwControlString
 ;
 : Operations
   Seq: ( ME_50852857013B // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_508528490090 Register

: ME_B4BBFF030F74
 CONST UID 'B4BBFF030F74'
 CONST Name 'Ini_Reg_Class'
 CONST IsSummoned true
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация TtfwControlString' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_508527F30183 // TtfwControlString
 ;
 CONST "ifndef" 'NoScripts'

ref; // ME_B4BBFF030F74 Ini_Reg_Class

: ME_50852885016F
 CONST UID '50852885016F'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_508527F30183 // TtfwControlString
 ;
 : Target WL 'ME_4AA7888B0076' '47913B47006E.pas.ms.script' // l3CStr
 ;

ref; // ME_50852885016F 

: ME_5085288A0398
 CONST UID '5085288A0398'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_508527F30183 // TtfwControlString
 ;
 : Target WL 'ME_4787B1BA031F' '4787B0A8007B.pas.ms.script' // El3DuplicateItem
 ;

ref; // ME_5085288A0398 

: ME_508528DF0096
 CONST UID '508528DF0096'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_508527F30183 // TtfwControlString
 ;
 : Target WL 'ME_508528D10384' '4F3E3F5F0160.pas.ms.script' // TtfwClassRef
 ;

ref; // ME_508528DF0096 

: ME_508529BD0074
 CONST UID '508529BD0074'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_508527F30183 // TtfwControlString
 ;
 : Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.pas.ms.script' // FreeAndNil
 ;

ref; // ME_508529BD0074 

: ME_50853CC6007C
 CONST UID '50853CC6007C'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_508527F30183 // TtfwControlString
 ;
 : Target WL 'ME_4B853D8301E9' '4AB0997B00A2.pas.ms.script' // AnsiStartsStr
 ;

ref; // ME_50853CC6007C 

: ME_54DB70CB02F2
 CONST UID '54DB70CB02F2'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_508527F30183 // TtfwControlString
 ;
 : Target WL 'ME_508528D10384' '4F3E3F5F0160.pas.ms.script' // TtfwClassRef
 ;

ref; // ME_54DB70CB02F2 

: ME_508527F30183
 CONST UID '508527F30183'
 CONST Name 'TtfwControlString'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Слово для регистрации контрола и его класса' ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_54DB92D203C9 // VCL bindings
 ;
 : Inherits
   Seq: ( WL 'ME_4DDFD1430390' '4F3E3F5F0160.pas.ms.script' // TtfwString
 )
 ; // Inherits
 : Operations
   Seq: ( ME_508528490090 // Register
 ME_B4BBFF030F74 // Ini_Reg_Class
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_50852885016F // 
 ME_5085288A0398 // 
 ME_508528DF0096 // 
 ME_508529BD0074 // 
 ME_50853CC6007C // 
 ME_54DB70CB02F2 // 
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\tfwControlString.pas'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\ScriptEngine'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'
 CONST extprop:rc:SelfName 'ControlString'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'tfwControlString'

ref; // ME_508527F30183 TtfwControlString

FORWARD ME_4F212C680161

FORWARD ME_4F212C930149

: ME_4F212CA80231
 CONST UID '4F212CA80231'
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47E124E90272' '4799D29F033F.pas.ms.script' // TWinControl
 ;

ref; // ME_4F212CA80231 aControl

: ME_4F212CA8028B
 CONST UID '4F212CA8028B'
 CONST Name 'aCtx'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4DB0091E033E' '4DAF19F600C5.pas.ms.script' // TtfwContext
 ;

ref; // ME_4F212CA8028B aCtx

: ME_4F212CA2009A
 CONST UID '4F212CA2009A'
 CONST Name 'DoControl'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F212C930149 // DoWinControl
 ;
 : Parameters
   Seq: ( ME_4F212CA80231 // aControl
 ME_4F212CA8028B // aCtx
 )
 ; // Parameters

ref; // ME_4F212CA2009A DoControl

: ME_4F212C930149
 CONST UID '4F212C930149'
 CONST Name 'DoWinControl'
 CONST Class class_Class
 : Stereotype st_abstractmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent ME_4F212C680161 // TkwWinControlFromStackWord
 ;
 : Operations
   Seq: ( ME_4F212CA2009A // DoControl
 )
 ; // Operations

ref; // ME_4F212C930149 DoWinControl

: ME_7929D7B67B97
 CONST UID '7929D7B67B97'
 CONST Name 'Ini_Reg_Class'
 CONST IsSummoned true
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация TkwWinControlFromStackWord' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4F212C680161 // TkwWinControlFromStackWord
 ;
 CONST "ifndef" 'NoScripts'

ref; // ME_7929D7B67B97 Ini_Reg_Class

: ME_4F212C3A015A_ME_4F212C680161
 CONST UID '4F212C3A015A'
 CONST Name 'DoControl'
 : Original ME_4F212C3A015A // DoControl
 ;
 : Implementor ME_4F212C680161 // TkwWinControlFromStackWord
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F212C3A015A_ME_4F212C680161 DoControl

: ME_4F212C680161
 CONST UID '4F212C680161'
 CONST Name 'TkwWinControlFromStackWord'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_54DB92D203C9 // VCL bindings
 ;
 : Inherits
   Seq: ( ME_4F212C120371 // kwControlFromStackWord
 )
 ; // Inherits
 : Operations
   Seq: ( ME_4F212C930149 // DoWinControl
 ME_7929D7B67B97 // Ini_Reg_Class
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4F212C3A015A_ME_4F212C680161 // DoControl
 )
 ; // Implemented
 CONST "author" 'Люлин А.В.'
 CONST "ifndef" 'NoVCL'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '26.01.2012 14:35'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\kwWinControlFromStackWord.pas'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\ScriptEngine'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'
 CONST extprop:rc:SelfName 'WinControlFromStackWord'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'kwWinControlFromStackWord'

ref; // ME_4F212C680161 TkwWinControlFromStackWord

FORWARD ME_4DB98B4B0382

FORWARD ME_4DB98B990054

: ME_4DB98BAE03CB
 CONST UID '4DB98BAE03CB'
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_47E1201703C3' '4799D29F033F.pas.ms.script' // TControl
 ;

ref; // ME_4DB98BAE03CB aControl

: ME_4DB98FBD0045
 CONST UID '4DB98FBD0045'
 CONST Name 'aCtx'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4DB0091E033E' '4DAF19F600C5.pas.ms.script' // TtfwContext
 ;

ref; // ME_4DB98FBD0045 aCtx

: ME_4DB98BA40271
 CONST UID '4DB98BA40271'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4DB98B990054 // DoControl
 ;
 : Parameters
   Seq: ( ME_4DB98BAE03CB // aControl
 ME_4DB98FBD0045 // aCtx
 )
 ; // Parameters

ref; // ME_4DB98BA40271 DoIt

: ME_4DB98B990054
 CONST UID '4DB98B990054'
 CONST Name 'DoControl'
 CONST Class class_Class
 : Stereotype st_abstractmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent ME_4DB98B4B0382 // TkwControlWord
 ;
 : Operations
   Seq: ( ME_4DB98BA40271 // DoIt
 )
 ; // Operations

ref; // ME_4DB98B990054 DoControl

FORWARD ME_5357B6FB0024

: ME_5357B7230025
 CONST UID '5357B7230025'
 CONST Name 'aControl'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_5357B7230025 aControl

: ME_5357B7230040
 CONST UID '5357B7230040'
 CONST Name 'aCtx'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4DB0091E033E' '4DAF19F600C5.pas.ms.script' // TtfwContext
 ;

ref; // ME_5357B7230040 aCtx

: ME_5357B70F010B
 CONST UID '5357B70F010B'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_5357B6FB0024 // DoComponent
 ;
 : Parameters
   Seq: ( ME_5357B7230025 // aControl
 ME_5357B7230040 // aCtx
 )
 ; // Parameters

ref; // ME_5357B70F010B DoIt

: ME_5357B6FB0024
 CONST UID '5357B6FB0024'
 CONST Name 'DoComponent'
 CONST Class class_Class
 : Stereotype st_virtualmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_4DB98B4B0382 // TkwControlWord
 ;
 : Operations
   Seq: ( ME_5357B70F010B // DoIt
 )
 ; // Operations

ref; // ME_5357B6FB0024 DoComponent

: ME_50BA5D0149C5
 CONST UID '50BA5D0149C5'
 CONST Name 'Ini_Reg_Class'
 CONST IsSummoned true
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация TkwControlWord' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4DB98B4B0382 // TkwControlWord
 ;
 CONST "ifndef" 'NoScripts'

ref; // ME_50BA5D0149C5 Ini_Reg_Class

: ME_4DE8978703B3
 CONST UID '4DE8978703B3'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4DB98B4B0382 // TkwControlWord
 ;
 : Target WL 'ME_479878FA0103' '4AB0997B00A2.pas.ms.script' // TComponent
 ;

ref; // ME_4DE8978703B3 

: ME_4EF464BF0208
 CONST UID '4EF464BF0208'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4DB98B4B0382 // TkwControlWord
 ;
 : Target WL 'ME_4DE89E560091' '4AB0C3C60310.pas.ms.script' // Format
 ;

ref; // ME_4EF464BF0208 

: ME_55014F6002C9
 CONST UID '55014F6002C9'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4DB98B4B0382 // TkwControlWord
 ;
 : Target WL 'ME_55014D810077' '55001317029B.pas.ms.script' // Tl3CloseFormHelper
 ;

ref; // ME_55014F6002C9 

: ME_5506D4130133
 CONST UID '5506D4130133'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4DB98B4B0382 // TkwControlWord
 ;
 : Target WL 'ME_5506D3B202FA' '5506D079035B.pas.ms.script' // Tl3MessagesService
 ;

ref; // ME_5506D4130133 

: ME_5506D642024E
 CONST UID '5506D642024E'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4DB98B4B0382 // TkwControlWord
 ;
 : Target WL 'ME_5506D56601D6' '5506D079035B.pas.ms.script' // Tl3FormsService
 ;

ref; // ME_5506D642024E 

: ME_4DAEEDE10285_ME_4DB98B4B0382
 CONST UID '4DAEEDE10285'
 CONST Name 'DoDoIt'
 : Original WL 'ME_4DAEEDE10285' '4DAF19F600C5.pas.ms.script' // DoDoIt
 ;
 : Implementor ME_4DB98B4B0382 // TkwControlWord
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAEEDE10285_ME_4DB98B4B0382 DoDoIt

: ME_4DB98B4B0382
 CONST UID '4DB98B4B0382'
 CONST Name 'TkwControlWord'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_54DB92D203C9 // VCL bindings
 ;
 : Inherits
   Seq: ( WL 'ME_53EDC0E701BC' '4F3E3F5F0160.pas.ms.script' // TtfwRegisterableWord
 )
 ; // Inherits
 : Implements
   Seq: ( ME_4DB95922039B // SystemWord
 )
 ; // Implements
 : Operations
   Seq: ( ME_4DB98B990054 // DoControl
 ME_5357B6FB0024 // DoComponent
 ME_50BA5D0149C5 // Ini_Reg_Class
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4DAEEDE10285_ME_4DB98B4B0382 // DoDoIt
 )
 ; // Implemented
 : Dependencies
   Seq: ( ME_4DE8978703B3 // 
 ME_4EF464BF0208 // 
 ME_55014F6002C9 // 
 ME_5506D4130133 // 
 ME_5506D642024E // 
 )
 ; // Dependencies
 CONST "author" 'Люлин А.В.'
 CONST "ifndef" 'NoVCL'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '28.04.2011 19:44'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\kwControlWord.pas'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\ScriptEngine'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'
 CONST extprop:rc:SelfName 'ControlWord'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'kwControlWord'

ref; // ME_4DB98B4B0382 TkwControlWord

FORWARD ME_4EB25D530395

FORWARD ME_4EB25DE00396

: ME_4EB25E0B0206
 CONST UID '4EB25E0B0206'
 CONST Name 'aForm'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4952591E0263' '4799D29F033F.pas.ms.script' // TForm
 ;

ref; // ME_4EB25E0B0206 aForm

: ME_4EB2681400DA
 CONST UID '4EB2681400DA'
 CONST Name 'aCtx'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4DB0091E033E' '4DAF19F600C5.pas.ms.script' // TtfwContext
 ;

ref; // ME_4EB2681400DA aCtx

: ME_4EB25DFC036C
 CONST UID '4EB25DFC036C'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4EB25DE00396 // DoForm
 ;
 : Parameters
   Seq: ( ME_4EB25E0B0206 // aForm
 ME_4EB2681400DA // aCtx
 )
 ; // Parameters

ref; // ME_4EB25DFC036C DoIt

: ME_4EB25DE00396
 CONST UID '4EB25DE00396'
 CONST Name 'DoForm'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_abstract
 : Parent ME_4EB25D530395 // TkwFormFromControlWord
 ;
 : Operations
   Seq: ( ME_4EB25DFC036C // DoIt
 )
 ; // Operations

ref; // ME_4EB25DE00396 DoForm

: ME_9AD5CF0EFDEA
 CONST UID '9AD5CF0EFDEA'
 CONST Name 'Ini_Reg_Class'
 CONST IsSummoned true
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация TkwFormFromControlWord' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_4EB25D530395 // TkwFormFromControlWord
 ;
 CONST "ifndef" 'NoScripts'

ref; // ME_9AD5CF0EFDEA Ini_Reg_Class

: ME_4EB265890130
 CONST UID '4EB265890130'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4EB25D530395 // TkwFormFromControlWord
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_4EB265890130 

: ME_5506D69E01ED
 CONST UID '5506D69E01ED'
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_4EB25D530395 // TkwFormFromControlWord
 ;
 : Target WL 'ME_5506D56601D6' '5506D079035B.pas.ms.script' // Tl3FormsService
 ;

ref; // ME_5506D69E01ED 

: ME_4DB98B990054_ME_4EB25D530395
 CONST UID '4DB98B990054'
 CONST Name 'DoControl'
 : Original ME_4DB98B990054 // DoControl
 ;
 : Implementor ME_4EB25D530395 // TkwFormFromControlWord
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DB98B990054_ME_4EB25D530395 DoControl

: ME_4EB25D530395
 CONST UID '4EB25D530395'
 CONST Name 'TkwFormFromControlWord'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent ME_54DB92D203C9 // VCL bindings
 ;
 : Inherits
   Seq: ( ME_4DB98B4B0382 // TkwControlWord
 )
 ; // Inherits
 : Operations
   Seq: ( ME_4EB25DE00396 // DoForm
 ME_9AD5CF0EFDEA // Ini_Reg_Class
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4DB98B990054_ME_4EB25D530395 // DoControl
 )
 ; // Implemented
 : Dependencies
   Seq: ( ME_4EB265890130 // 
 ME_5506D69E01ED // 
 )
 ; // Dependencies
 CONST "author" 'Люлин А.В.'
 CONST "ifndef" 'NoVCL'
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" true
 CONST "register in scripts" 'undefined'
 CONST "started" '03.11.2011 13:22'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\kwFormFromControlWord.pas'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\ScriptEngine'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'
 CONST extprop:rc:SelfName 'FormFromControlWord'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'kwFormFromControlWord'

ref; // ME_4EB25D530395 TkwFormFromControlWord

: ME_54DB92D203C9
 CONST UID '54DB92D203C9'
 CONST Name 'VCL bindings'
 CONST Class class_Category
 : Stereotype st_ScriptKeywords ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_54DB92A80279' '54DB92A80279.pas.ms.script' // ScriptEngine$RTLandVCL
 ;
 : Children
   Seq: ( ME_4DB95922039B // SystemWord
 ME_4F2148300318 // TkwComponentFromStackWord
 ME_4F212C120371 // kwControlFromStackWord
 ME_508527F30183 // TtfwControlString
 ME_4F212C680161 // TkwWinControlFromStackWord
 ME_4DB98B4B0382 // TkwControlWord
 ME_4EB25D530395 // TkwFormFromControlWord
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_4DAF19F600C5' '4DAF19F600C5.pas.ms.script' // tfwScriptingInterfaces
 WL 'ME_54DC9ACA0156' '54DC9ACA0156.pas.ms.script' // RTL bindings
 WL 'ME_55001317029B' '55001317029B.pas.ms.script' // VCLHelpers
 WL 'ME_5506D079035B' '5506D079035B.pas.ms.script' // AFWServices
 )
 ; // Depends
 CONST "ifndef" 'NoScripts'
 CONST intf.pas:PathOnly '\common\components\rtl\Garant\ScriptEngine'
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\54DB92D203C9.pas.ms.script'
 CONST pas.script:PathOnly '\shared\models\NewSchool\Scripts'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\54DB92D203C9.pas.ms.script.runner'
 CONST pas.script.runner:PathOnly '\shared\models\NewSchool\Scripts'

ref; // ME_54DB92D203C9 VCL bindings
