// WordsList 54F07F0302C2 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_54F07F0302C2

ME ME_54F07F0302C2
 MEPROP UID '54F07F0302C2'
 MEPROP Name 'WordsList'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_54CF97B10370' // ScriptEngine$Core
 ;
 MELIST Children
   Seq: ( WL? 'ME_4DB6CAC402B4' // TtfwWordRefList
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_4DAF19F600C5' // tfwScriptingInterfaces
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_54F07F0302C2 WordsList
