// htInterfaces 550981B402B9 Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_550981B402B9

FORWARD ME_550981CC01F6

: ME_550981E5026A
 CONST UID '550981E5026A'
 CONST Name 'StationName'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent HWL ME_550981CC01F6 // IhtParamsStorage
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_550981E5026A StationName

: ME_550981FF0138
 CONST UID '550981FF0138'
 CONST Name 'TablePath'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent HWL ME_550981CC01F6 // IhtParamsStorage
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_550981FF0138 TablePath

: ME_550982210098
 CONST UID '550982210098'
 CONST Name 'LockPath'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent HWL ME_550981CC01F6 // IhtParamsStorage
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_550982210098 LockPath

: ME_550982360334
 CONST UID '550982360334'
 CONST Name 'TempPath'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent HWL ME_550981CC01F6 // IhtParamsStorage
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 CONST "pm" false

ref; // ME_550982360334 TempPath

: ME_5512621F0352
 CONST UID '5512621F0352'
 CONST Name 'StationErrorMessage'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_550981CC01F6 // IhtParamsStorage
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_5512621F0352 StationErrorMessage

: ME_551262410001
 CONST UID '551262410001'
 CONST Name 'TablePathErrorMessage'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_550981CC01F6 // IhtParamsStorage
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_551262410001 TablePathErrorMessage

: ME_551262530061
 CONST UID '551262530061'
 CONST Name 'LockPathErrorMessage'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_550981CC01F6 // IhtParamsStorage
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_551262530061 LockPathErrorMessage

: ME_5507D9B100F7_ME_550981CC01F6
 : Original WL 'ME_5507D9B100F7' '5432518A0316.pas.ms.script' // ProviderKey
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5507D9B100F7_ME_550981CC01F6 ProviderKey

: ME_55095596033F_ME_550981CC01F6
 : Original WL 'ME_55095596033F' '5432518A0316.pas.ms.script' // InitStorage
 ;
 CONST OpKind opkind_Implemented
ref; // ME_55095596033F_ME_550981CC01F6 InitStorage

: ME_550963930391_ME_550981CC01F6
 : Original WL 'ME_550963930391' '5432518A0316.pas.ms.script' // Login
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_550963930391_ME_550981CC01F6 Login

: ME_550963A60121_ME_550981CC01F6
 : Original WL 'ME_550963A60121' '5432518A0316.pas.ms.script' // Password
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_550963A60121_ME_550981CC01F6 Password

: ME_550963BC00B0_ME_550981CC01F6
 : Original WL 'ME_550963BC00B0' '5432518A0316.pas.ms.script' // DocStoragePath
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_550963BC00B0_ME_550981CC01F6 DocStoragePath

: ME_550963CF0092_ME_550981CC01F6
 : Original WL 'ME_550963CF0092' '5432518A0316.pas.ms.script' // DocImagePath
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_550963CF0092_ME_550981CC01F6 DocImagePath

: ME_550963EB02F8_ME_550981CC01F6
 : Original WL 'ME_550963EB02F8' '5432518A0316.pas.ms.script' // HomeDirPath
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_550963EB02F8_ME_550981CC01F6 HomeDirPath

: ME_5515121F0358_ME_550981CC01F6
 : Original WL 'ME_5515121F0358' '5432518A0316.pas.ms.script' // OuterConfigEdit
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5515121F0358_ME_550981CC01F6 OuterConfigEdit

: ME_551512370064_ME_550981CC01F6
 : Original WL 'ME_551512370064' '5432518A0316.pas.ms.script' // BuildConfig
 ;
 CONST OpKind opkind_Implemented
 CONST "force overload" true
ref; // ME_551512370064_ME_550981CC01F6 BuildConfig

: ME_5756BD40014A_ME_550981CC01F6
 : Original WL 'ME_5756BD40014A' '5432518A0316.pas.ms.script' // DocImageCachePath
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5756BD40014A_ME_550981CC01F6 DocImageCachePath

: ME_550981CC01F6
 CONST UID '550981CC01F6'
 CONST GUID '68C7AC1A-2794-4F3B-92C2-EF264ED70759'
 CONST Name 'IhtParamsStorage'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_550981B402B9 // htInterfaces
 ;
 : Inherits
   Seq: ( WL 'ME_5507D90F00D2' '5432518A0316.pas.ms.script' // IdaParamsStorage
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_550981E5026A // StationName
 HWL ME_550981FF0138 // TablePath
 HWL ME_550982210098 // LockPath
 HWL ME_550982360334 // TempPath
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_5512621F0352 // StationErrorMessage
 HWL ME_551262410001 // TablePathErrorMessage
 HWL ME_551262530061 // LockPathErrorMessage
 )
 ; // Operations
 : Implemented
   Seq: ( ME_5507D9B100F7_ME_550981CC01F6 // ProviderKey
 ME_55095596033F_ME_550981CC01F6 // InitStorage
 ME_550963930391_ME_550981CC01F6 // Login
 ME_550963A60121_ME_550981CC01F6 // Password
 ME_550963BC00B0_ME_550981CC01F6 // DocStoragePath
 ME_550963CF0092_ME_550981CC01F6 // DocImagePath
 ME_550963EB02F8_ME_550981CC01F6 // HomeDirPath
 ME_5515121F0358_ME_550981CC01F6 // OuterConfigEdit
 ME_551512370064_ME_550981CC01F6 // BuildConfig
 ME_5756BD40014A_ME_550981CC01F6 // DocImageCachePath
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'htParamsStorage'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_550981CC01F6 IhtParamsStorage

FORWARD ME_555EF7B1002F

: ME_555EF81501E3
 CONST Name 'aTable'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_55377C9C0289' '5432448401BC.pas.ms.script' // TdaTables
 ;

ref; // ME_555EF81501E3 aTable

: ME_555EF7F5009F
 CONST UID '555EF7F5009F'
 CONST Name 'TableFullPath'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_555EF7B1002F // IhtDataSchemeHelper
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 : Parameters
   Seq: ( ME_555EF81501E3 // aTable
 )
 ; // Parameters

ref; // ME_555EF7F5009F TableFullPath

: ME_555EF83302FB
 CONST Name 'aTable'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_55377C9C0289' '5432448401BC.pas.ms.script' // TdaTables
 ;

ref; // ME_555EF83302FB aTable

: ME_555EF81A03BF
 CONST UID '555EF81A03BF'
 CONST Name 'TablePassword'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_555EF7B1002F // IhtDataSchemeHelper
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 : Parameters
   Seq: ( ME_555EF83302FB // aTable
 )
 ; // Parameters

ref; // ME_555EF81A03BF TablePassword

: ME_555EF7B1002F
 CONST UID '555EF7B1002F'
 CONST GUID '49B4A6A6-2FE1-4E28-BCD6-101B2639CC07'
 CONST Name 'IhtDataSchemeHelper'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_550981B402B9 // htInterfaces
 ;
 : Operations
   Seq: ( HWL ME_555EF7F5009F // TableFullPath
 HWL ME_555EF81A03BF // TablePassword
 )
 ; // Operations
 CONST extprop:rc:SelfName 'htDataSchemeHelper'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_555EF7B1002F IhtDataSchemeHelper

FORWARD ME_555C848200DA

: ME_555C8490016F
 CONST UID '555C8490016F'
 CONST Name 'Handle'
 CONST Class class_Attribute
 : Stereotype st_readonly::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 CONST LinkType lt_lnk
 : Parent HWL ME_555C848200DA // IhtFromTable
 ;
 : Target WL 'ME_555C84FC0026' '555331D10378.pas.ms.script' // ThtTblHandle
 ;
 CONST "pm" false

ref; // ME_555C8490016F Handle

: ME_555EF86C012C
 CONST Name 'aHelper'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target HWL ME_555EF7B1002F // IhtDataSchemeHelper
 ;

ref; // ME_555EF86C012C aHelper

: ME_555C91D40222
 CONST Name 'RequireNewHandle'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_555C91D40222 RequireNewHandle

: ME_555C91AF003A
 CONST UID '555C91AF003A'
 CONST Name 'Prepare'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_555C848200DA // IhtFromTable
 ;
 : Parameters
   Seq: ( ME_555EF86C012C // aHelper
 ME_555C91D40222 // RequireNewHandle
 )
 ; // Parameters

ref; // ME_555C91AF003A Prepare

: ME_555C91D8022C
 CONST UID '555C91D8022C'
 CONST Name 'Unprepare'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_555C848200DA // IhtFromTable
 ;

ref; // ME_555C91D8022C Unprepare

: ME_5553634C0218_ME_555C848200DA
 : Original WL 'ME_5553634C0218' '5432518A0316.pas.ms.script' // TableAlias
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_5553634C0218_ME_555C848200DA TableAlias

: ME_555363590242_ME_555C848200DA
 : Original WL 'ME_555363590242' '5432518A0316.pas.ms.script' // Table
 ;
 CONST OpKind opkind_Implemented
 CONST "pm" false
ref; // ME_555363590242_ME_555C848200DA Table

: ME_555C848200DA
 CONST UID '555C848200DA'
 CONST GUID '07913015-B7DB-4C2B-8827-93BD8A6F6F24'
 CONST Name 'IhtFromTable'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_550981B402B9 // htInterfaces
 ;
 : Inherits
   Seq: ( WL 'ME_555303840193' '5432518A0316.pas.ms.script' // IdaFromTable
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_555C8490016F // Handle
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_555C91AF003A // Prepare
 HWL ME_555C91D8022C // Unprepare
 )
 ; // Operations
 : Implemented
   Seq: ( ME_5553634C0218_ME_555C848200DA // TableAlias
 ME_555363590242_ME_555C848200DA // Table
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'htFromTable'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_555C848200DA IhtFromTable

FORWARD ME_55C0B2A30315

: ME_55C89BA803C0
 CONST Name 'aData'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A608F00301' '4AB0C3C60310.pas.ms.script' // Pointer
 ;

ref; // ME_55C89BA803C0 aData

: ME_55C89BA90007
 CONST Name 'aDesc'
 CONST Class class_Parameter
 : Stereotype st_const ;
 : Target WL 'ME_559FA10A0133' '555331D10378.pas.ms.script' // OPEL
 ;

ref; // ME_55C89BA90007 aDesc

: ME_55C89B830012
 CONST UID '55C89B830012'
 CONST Name 'ToLargeInt'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_55C0B2A30315 // IhtDataConverter
 ;
 : Target WL 'ME_559390220212' '5432448401BC.pas.ms.script' // LargeInt
 ;
 : Parameters
   Seq: ( ME_55C89BA803C0 // aData
 ME_55C89BA90007 // aDesc
 )
 ; // Parameters

ref; // ME_55C89B830012 ToLargeInt

: ME_55C89BC1031E
 CONST Name 'aData'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A608F00301' '4AB0C3C60310.pas.ms.script' // Pointer
 ;

ref; // ME_55C89BC1031E aData

: ME_55C89BC1033D
 CONST Name 'aDesc'
 CONST Class class_Parameter
 : Stereotype st_const ;
 : Target WL 'ME_559FA10A0133' '555331D10378.pas.ms.script' // OPEL
 ;

ref; // ME_55C89BC1033D aDesc

: ME_55C89BB40093
 CONST UID '55C89BB40093'
 CONST Name 'ToInteger'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_55C0B2A30315 // IhtDataConverter
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Parameters
   Seq: ( ME_55C89BC1031E // aData
 ME_55C89BC1033D // aDesc
 )
 ; // Parameters

ref; // ME_55C89BB40093 ToInteger

: ME_55C89BD601B5
 CONST Name 'aData'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A608F00301' '4AB0C3C60310.pas.ms.script' // Pointer
 ;

ref; // ME_55C89BD601B5 aData

: ME_55C89BD601E4
 CONST Name 'aDesc'
 CONST Class class_Parameter
 : Stereotype st_const ;
 : Target WL 'ME_559FA10A0133' '555331D10378.pas.ms.script' // OPEL
 ;

ref; // ME_55C89BD601E4 aDesc

: ME_55C89BC8017D
 CONST UID '55C89BC8017D'
 CONST Name 'ToStDate'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_55C0B2A30315 // IhtDataConverter
 ;
 : Target WL 'ME_4E8EDFCA01C0' '47D0290B016D.pas.ms.script' // TStDate
 ;
 : Parameters
   Seq: ( ME_55C89BD601B5 // aData
 ME_55C89BD601E4 // aDesc
 )
 ; // Parameters

ref; // ME_55C89BC8017D ToStDate

: ME_55C89BE8010D
 CONST Name 'aData'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A608F00301' '4AB0C3C60310.pas.ms.script' // Pointer
 ;

ref; // ME_55C89BE8010D aData

: ME_55C89BE8013C
 CONST Name 'aDesc'
 CONST Class class_Parameter
 : Stereotype st_const ;
 : Target WL 'ME_559FA10A0133' '555331D10378.pas.ms.script' // OPEL
 ;

ref; // ME_55C89BE8013C aDesc

: ME_55C89BDC012F
 CONST UID '55C89BDC012F'
 CONST Name 'ToStTime'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_55C0B2A30315 // IhtDataConverter
 ;
 : Target WL 'ME_5593952A0301' '47D0290B016D.pas.ms.script' // TStTime
 ;
 : Parameters
   Seq: ( ME_55C89BE8010D // aData
 ME_55C89BE8013C // aDesc
 )
 ; // Parameters

ref; // ME_55C89BDC012F ToStTime

: ME_55FA9B9F0222
 CONST Name 'aData'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A608F00301' '4AB0C3C60310.pas.ms.script' // Pointer
 ;

ref; // ME_55FA9B9F0222 aData

: ME_55FA9B9F0260
 CONST Name 'aDesc'
 CONST Class class_Parameter
 : Stereotype st_const ;
 : Target WL 'ME_559FA10A0133' '555331D10378.pas.ms.script' // OPEL
 ;

ref; // ME_55FA9B9F0260 aDesc

: ME_55FA9B9301D7
 CONST UID '55FA9B9301D7'
 CONST Name 'ToString'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_55C0B2A30315 // IhtDataConverter
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 : Parameters
   Seq: ( ME_55FA9B9F0222 // aData
 ME_55FA9B9F0260 // aDesc
 )
 ; // Parameters

ref; // ME_55FA9B9301D7 ToString

: ME_562E0F990314
 CONST Name 'aData'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A608F00301' '4AB0C3C60310.pas.ms.script' // Pointer
 ;

ref; // ME_562E0F990314 aData

: ME_562E0F990333
 CONST Name 'aDesc'
 CONST Class class_Parameter
 : Stereotype st_const ;
 : Target WL 'ME_559FA10A0133' '555331D10378.pas.ms.script' // OPEL
 ;

ref; // ME_562E0F990333 aDesc

: ME_562E0F8F02F3
 CONST UID '562E0F8F02F3'
 CONST Name 'ToByte'
 CONST Class class_Operation
 CONST Visibility PublicAccess
 CONST Abstraction at_abstract
 : Parent HWL ME_55C0B2A30315 // IhtDataConverter
 ;
 : Target WL 'ME_476130E5023C' '4AB0C3C60310.pas.ms.script' // Byte
 ;
 : Parameters
   Seq: ( ME_562E0F990314 // aData
 ME_562E0F990333 // aDesc
 )
 ; // Parameters

ref; // ME_562E0F8F02F3 ToByte

: ME_555995210007_ME_55C0B2A30315
 : Original WL 'ME_555995210007' '5432518A0316.pas.ms.script' // AllocateParamBuffer
 ;
 CONST OpKind opkind_Implemented
ref; // ME_555995210007_ME_55C0B2A30315 AllocateParamBuffer

: ME_5559955500DF_ME_55C0B2A30315
 : Original WL 'ME_5559955500DF' '5432518A0316.pas.ms.script' // ParamToDataBase
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5559955500DF_ME_55C0B2A30315 ParamToDataBase

: ME_55599596005B_ME_55C0B2A30315
 : Original WL 'ME_55599596005B' '5432518A0316.pas.ms.script' // ParamFromDataBase
 ;
 CONST OpKind opkind_Implemented
ref; // ME_55599596005B_ME_55C0B2A30315 ParamFromDataBase

: ME_5559D14D02D1_ME_55C0B2A30315
 : Original WL 'ME_5559D14D02D1' '5432518A0316.pas.ms.script' // FreeParamBuffer
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5559D14D02D1_ME_55C0B2A30315 FreeParamBuffer

: ME_55C0B2A30315
 CONST UID '55C0B2A30315'
 CONST GUID 'B9607AE1-26FC-417B-810D-A1FE75CC6A45'
 CONST Name 'IhtDataConverter'
 CONST Class class_Class
 : Stereotype st_Facet ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_550981B402B9 // htInterfaces
 ;
 : Inherits
   Seq: ( WL 'ME_5559950F0013' '5432518A0316.pas.ms.script' // IdaDataConverter
 )
 ; // Inherits
 : Operations
   Seq: ( HWL ME_55C89B830012 // ToLargeInt
 HWL ME_55C89BB40093 // ToInteger
 HWL ME_55C89BC8017D // ToStDate
 HWL ME_55C89BDC012F // ToStTime
 HWL ME_55FA9B9301D7 // ToString
 HWL ME_562E0F8F02F3 // ToByte
 )
 ; // Operations
 : Implemented
   Seq: ( ME_555995210007_ME_55C0B2A30315 // AllocateParamBuffer
 ME_5559955500DF_ME_55C0B2A30315 // ParamToDataBase
 ME_55599596005B_ME_55C0B2A30315 // ParamFromDataBase
 ME_5559D14D02D1_ME_55C0B2A30315 // FreeParamBuffer
 )
 ; // Implemented
 CONST extprop:rc:SelfName 'htDataConverter'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_55C0B2A30315 IhtDataConverter

FORWARD ME_55C4911E03DF

: ME_55C49B6B0265
 CONST UID '55C49B6B0265'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_ref
 : Parent HWL ME_55C4911E03DF // ThtSubItemDescriptionArray
 ;
 : Target WL 'ME_559FA10A0133' '555331D10378.pas.ms.script' // OPEL
 ;

ref; // ME_55C49B6B0265 

: ME_55C4911E03DF
 CONST UID '55C4911E03DF'
 CONST Name 'ThtSubItemDescriptionArray'
 CONST Class class_Class
 : Stereotype st_Vector ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_550981B402B9 // htInterfaces
 ;
 : Attributes
   Seq: ( HWL ME_55C49B6B0265 // 
 )
 ; // Attributes
 CONST "array type" 'dynamic'

ref; // ME_55C4911E03DF ThtSubItemDescriptionArray

: ME_550981B402B9
 CONST UID '550981B402B9'
 CONST Name 'htInterfaces'
 CONST Class class_Category
 : Stereotype st_Interfaces ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_543388C10144' '543388C10144.pas.ms.script' // HT
 ;
 : Children
   Seq: ( HWL ME_550981CC01F6 // IhtParamsStorage
 HWL ME_555EF7B1002F // IhtDataSchemeHelper
 HWL ME_555C848200DA // IhtFromTable
 HWL ME_55C0B2A30315 // IhtDataConverter
 HWL ME_55C4911E03DF // ThtSubItemDescriptionArray
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.pas.ms.script' // Primitives
 WL 'ME_47D0290B016D' '47D0290B016D.pas.ms.script' // l3Utils
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.pas.ms.script' // Sys
 WL 'ME_5432448401BC' '5432448401BC.pas.ms.script' // daTypes
 WL 'ME_5432518A0316' '5432518A0316.pas.ms.script' // daInterfaces
 WL 'ME_555331D10378' '555331D10378.pas.ms.script' // Core
 )
 ; // Depends
 CONST "is namespace" true
 CONST intf.pas:Path 'common\components\rtl\Garant\HT\htInterfaces.pas'

ref; // ME_550981B402B9 htInterfaces
