// InpharmMainMenuControllerRealization 550AA7200370 ControllerUnit Category

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_550AA7200370
 MEPROP UID '550AA7200370'
 MEPROP Name 'InpharmMainMenuControllerRealization'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_ControllerUnit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_550AA6E1017D' '550AA6E1017D.ms.model.script' // InpharmControllers
 ;
 MELIST Children
   Seq: ( WL 'ME_550AAEE001B7' '550AAEE001B7.ms.model.script' // TsdsInpharmMainMenu
 WL 'ME_550C0DA5022E' '550C0DA5022E.ms.model.script' // TdsInpharmMainMenu
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_47D0E1500033' '47D0E1500033.ms.model.script' // Implementation
 WL 'ME_48F747EC0073' '48F747EC0073.ms.model.script' // Common
 WL 'ME_4AC241AC01FC' '4AC241AC01FC.ms.model.script' // InpharmInterfaces
 )
 ; // Depends

ENDME // ME_550AA7200370 InpharmMainMenuControllerRealization
