// TabbedInterfaceServices 553213B80041 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_553213B80041

ME ME_553213B80041
 MEPROP UID '553213B80041'
 MEPROP Name 'TabbedInterfaceServices'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_550012C403C4' // L3$AFW
 ;
 MELIST Children
   Seq: ( WL? 'ME_553213D902E0' // Tl3TabbedContainersDispatcher
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4728A7020026' // Types
 WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_4799D29F033F' // Implementation
 WL? 'ME_4AB0C3C60310' // Sys
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames

ENDME // ME_553213B80041 TabbedInterfaceServices
