// ThtDataSchemeHelper 555F0C89007D SimpleClass Class

INCLUDE '49E7754802A9.pas.ms.script'

INCLUDE '550981B402B9.pas.ms.script'

INCLUDE '51612ED700B4.pas.ms.script'

FORWARD ME_555F0C89007D

INCLUDE '54F9AF6B00DD.pas.ms.script'

: ME_555F0D0D013F
 CONST UID '555F0D0D013F'
 CONST Name 'f_Params'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_54F9AF6B00DD // ThtDataProviderParams
 ;

 @SELF
; // ME_555F0D0D013F f_Params

FORWARD ME_555F0CCD008C

: ME_555F0CE60229
 CONST UID '555F0CE60229'
 CONST Name 'aParams'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_54F9AF6B00DD // ThtDataProviderParams
 ;

 @SELF
; // ME_555F0CE60229 aParams

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_555F0CD5012B
 CONST UID '555F0CD5012B'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Parameters
   [ ME_555F0CE60229 // aParams
 ]
 ; // Parameters

 @SELF
; // ME_555F0CD5012B DoIt

: ME_555F0CCD008C
 CONST UID '555F0CCD008C'
 CONST Name 'Create'
 CONST Class 'Class'
 CONST Stereotype 'Constructor'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_555F0CD5012B // DoIt
 ]
 ; // Operations

 @SELF
; // ME_555F0CCD008C Create

FORWARD ME_555F0CEB0175

: ME_0187392FF83F
 CONST UID '0187392FF83F'
 CONST Name 'aParams'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_54F9AF6B00DD // ThtDataProviderParams
 ;

 @SELF
; // ME_0187392FF83F aParams

: ME_2F146717A337
 CONST UID '2F146717A337'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 %SUMMARY 'Сигнатура фабрики ThtDataSchemeHelper.Make' ;
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Target ME_555EF7B1002F // IhtDataSchemeHelper
 ;
 : Parameters
   [ ME_0187392FF83F // aParams
 ]
 ; // Parameters

 @SELF
; // ME_2F146717A337 DoIt

: ME_555F0CEB0175
 CONST UID '555F0CEB0175'
 CONST Name 'Make'
 CONST Class 'Class'
 CONST Stereotype 'Factory'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Inherits
   [ ME_555F0CCD008C // Create
 ]
 ; // Inherits
 : Implements
   [ ME_555EF7B1002F // IhtDataSchemeHelper
 ]
 ; // Implements
 : Operations
   [ ME_2F146717A337 // DoIt
 ]
 ; // Operations
 : Implemented
   [ ME_555EF7F5009F // TableFullPath
 ME_555EF81A03BF // TablePassword
 ME_555EF83803BE // TableFamily
 ]
 ; // Implemented
 CONST "check nil" false
 CONST "need AfterCreate" 'undefined'
 CONST "need Aggregate" 'undefined'
 CONST "need As" false

 @SELF
; // ME_555F0CEB0175 Make

: ME_555F0C89007D
 CONST UID '555F0C89007D'
 CONST Name 'ThtDataSchemeHelper'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_49E7754802A9 // Tl3ProtoObject
 ]
 ; // Inherits
 : Implements
   [ ME_555EF7B1002F // IhtDataSchemeHelper
 ]
 ; // Implements
 : Attributes
   [ ME_555F0D0D013F // f_Params
 ]
 ; // Attributes
 : Operations
   [ ME_555F0CCD008C // Create
 ME_555F0CEB0175 // Make
 ]
 ; // Operations
 : Implemented
   [ ME_555EF7F5009F // TableFullPath
 ME_555EF81A03BF // TablePassword
 ME_555EF83803BE // TableFamily
 ]
 ; // Implemented
 : Overridden
   [ ME_479731C50290 // Cleanup
 ]
 ; // Overridden
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_555F0C89007D ThtDataSchemeHelper
