// TvtCalendarPanel 5562DB5D0259 GuiControl Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_5562DB5D0259

FORWARD ME_556709D10061

: ME_55670CE402C0
 CONST UID '55670CE402C0'
 CONST Name 'f_ForceRedraw'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_55670CE402C0 f_ForceRedraw

: ME_55670CF10085
 CONST UID '55670CF10085'
 CONST Name 'f_MouseDown'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Target WL 'ME_46A603BB0391' '4AB0C3C60310.pas.ms.script' // Boolean
 ;

ref; // ME_55670CF10085 f_MouseDown

: ME_55670D67017B
 CONST UID '55670D67017B'
 CONST Name 'f_MonthIndent'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Target WL 'ME_476130E5023C' '4AB0C3C60310.pas.ms.script' // Byte
 ;

ref; // ME_55670D67017B f_MonthIndent

: ME_55670D7602EE
 CONST UID '55670D7602EE'
 CONST Name 'f_CurYear'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Target WL 'ME_476F71A701AB' '4AB0C3C60310.pas.ms.script' // Word
 ;

ref; // ME_55670D7602EE f_CurYear

: ME_55670D82015C
 CONST UID '55670D82015C'
 CONST Name 'f_CurMonth'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Target WL 'ME_476F71A701AB' '4AB0C3C60310.pas.ms.script' // Word
 ;

ref; // ME_55670D82015C f_CurMonth

: ME_55670D8D02AB
 CONST UID '55670D8D02AB'
 CONST Name 'f_CurDay'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Target WL 'ME_476F71A701AB' '4AB0C3C60310.pas.ms.script' // Word
 ;

ref; // ME_55670D8D02AB f_CurDay

: ME_55670E4C03BD
 CONST UID '55670E4C03BD'
 CONST Name 'StartOfWeek'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Target WL 'ME_554C8DC4028F' '47D0290B016D.pas.ms.script' // TStDayType
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_55670E4C03BD StartOfWeek

: ME_55670E5E022C
 CONST UID '55670E5E022C'
 CONST Name 'Weekends'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Target WL 'ME_554C8E0102AB' '47D0290B016D.pas.ms.script' // TDaysOfWeek
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_55670E5E022C Weekends

: ME_55670E6702F2
 CONST UID '55670E6702F2'
 CONST Name 'WeekendColor'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Target WL 'ME_46A44A2F01C7' '55C4AEC801CA.pas.ms.script' // TColor
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_55670E6702F2 WeekendColor

: ME_55670E87023E
 CONST UID '55670E87023E'
 CONST Name 'OnChange'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Target WL 'ME_47881B22005A' '4AB0997B00A2.pas.ms.script' // TNotifyEvent
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_55670E87023E OnChange

: ME_55670FBF01D7
 CONST UID '55670FBF01D7'
 CONST Name 'OldDay'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 CONST "pm" true
 CONST "reads field" true
 CONST "writes field" true

ref; // ME_55670FBF01D7 OldDay

: ME_55670FF801D4
 CONST UID '55670FF801D4'
 CONST Name 'Date'
 CONST Class class_Attribute
 : Stereotype st_property::Attribute ;
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 CONST LinkType lt_agr
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Target WL 'ME_47272C8B0128' '4AB0C3C60310.pas.ms.script' // TDateTime
 ;
 CONST "pm" true

ref; // ME_55670FF801D4 Date

FORWARD ME_55670EF101FF

: ME_55670EFC0207
 CONST Name 'Pt'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_4739AD110072' '4728A7020026.pas.ms.script' // TPoint
 ;

ref; // ME_55670EFC0207 Pt

: ME_55670EFA01AD
 CONST UID '55670EFA01AD'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55670EF101FF // GetDayFromPoint
 ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;
 : Parameters
   Seq: ( ME_55670EFC0207 // Pt
 )
 ; // Parameters

ref; // ME_55670EFA01AD DoIt

: ME_55670EF101FF
 CONST UID '55670EF101FF'
 CONST Name 'GetDayFromPoint'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Operations
   Seq: ( HWL ME_55670EFA01AD // DoIt
 )
 ; // Operations

ref; // ME_55670EF101FF GetDayFromPoint

FORWARD ME_55670F3A02E0

: ME_55670F420033
 CONST Name 'aDay'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476F71A701AB' '4AB0C3C60310.pas.ms.script' // Word
 ;

ref; // ME_55670F420033 aDay

: ME_55670F400015
 CONST UID '55670F400015'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55670F3A02E0 // GetDayRect
 ;
 : Target WL 'ME_4728A7190065' '4728A7020026.pas.ms.script' // TRect
 ;
 : Parameters
   Seq: ( ME_55670F420033 // aDay
 )
 ; // Parameters

ref; // ME_55670F400015 DoIt

: ME_55670F3A02E0
 CONST UID '55670F3A02E0'
 CONST Name 'GetDayRect'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Operations
   Seq: ( HWL ME_55670F400015 // DoIt
 )
 ; // Operations

ref; // ME_55670F3A02E0 GetDayRect

FORWARD ME_55670F7202CB

: ME_55670F7B038D
 CONST Name 'aPredDay'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476F71A701AB' '4AB0C3C60310.pas.ms.script' // Word
 ;

ref; // ME_55670F7B038D aPredDay

: ME_55670F78005E
 CONST UID '55670F78005E'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_55670F7202CB // DrawFocusFrame
 ;
 : Parameters
   Seq: ( ME_55670F7B038D // aPredDay
 )
 ; // Parameters

ref; // ME_55670F78005E DoIt

: ME_55670F7202CB
 CONST UID '55670F7202CB'
 CONST Name 'DrawFocusFrame'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Operations
   Seq: ( HWL ME_55670F78005E // DoIt
 )
 ; // Operations

ref; // ME_55670F7202CB DrawFocusFrame

: ME_55670F9602CB
 CONST UID '55670F9602CB'
 CONST Name 'InvalidateDayArray'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;

ref; // ME_55670F9602CB InvalidateDayArray

: ME_55670FA502B8
 CONST UID '55670FA502B8'
 CONST Name 'Change'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;

ref; // ME_55670FA502B8 Change

: ME_55671071035C
 CONST UID '55671071035C'
 CONST Name 'NextDay'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;

ref; // ME_55671071035C NextDay

: ME_5567107A01EF
 CONST UID '5567107A01EF'
 CONST Name 'PrevDay'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;

ref; // ME_5567107A01EF PrevDay

: ME_55671084000E
 CONST UID '55671084000E'
 CONST Name 'NextWeek'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;

ref; // ME_55671084000E NextWeek

: ME_5567108F020C
 CONST UID '5567108F020C'
 CONST Name 'PrevWeek'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;

ref; // ME_5567108F020C PrevWeek

: ME_5567109A01A1
 CONST UID '5567109A01A1'
 CONST Name 'NextMonth'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;

ref; // ME_5567109A01A1 NextMonth

: ME_556710A500BA
 CONST UID '556710A500BA'
 CONST Name 'PrevMonth'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;

ref; // ME_556710A500BA PrevMonth

: ME_556710AF02F4
 CONST UID '556710AF02F4'
 CONST Name 'NextYear'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;

ref; // ME_556710AF02F4 NextYear

: ME_556710BA0108
 CONST UID '556710BA0108'
 CONST Name 'PrevYear'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;

ref; // ME_556710BA0108 PrevYear

FORWARD ME_556710D300D7

: ME_556710DD0113
 CONST Name 'nDays'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46A606AC03B2' '4AB0C3C60310.pas.ms.script' // Integer
 ;

ref; // ME_556710DD0113 nDays

: ME_556710DA016D
 CONST UID '556710DA016D'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_556710D300D7 // RelMoveDate
 ;
 : Parameters
   Seq: ( ME_556710DD0113 // nDays
 )
 ; // Parameters

ref; // ME_556710DA016D DoIt

: ME_556710D300D7
 CONST UID '556710D300D7'
 CONST Name 'RelMoveDate'
 CONST Class class_Class
 : Stereotype st_method ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Operations
   Seq: ( HWL ME_556710DA016D // DoIt
 )
 ; // Operations

ref; // ME_556710D300D7 RelMoveDate

: ME_5567116700F3
 CONST Name 'Msg'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_482C43D50367' '476F78840219.pas.ms.script' // TWMGetDlgCode
 ;

ref; // ME_5567116700F3 Msg

: ME_5567115E02E0
 CONST UID '5567115E02E0'
 CONST Name 'WMGetDlgCode'
 CONST Class class_Operation
 : Stereotype st_message::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Parameters
   Seq: ( ME_5567116700F3 // Msg
 )
 ; // Parameters
 CONST "Message ID" 'WM_GETDLGCODE'

ref; // ME_5567115E02E0 WMGetDlgCode

: ME_5567117900F2
 CONST Name 'Message'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_51540F730239' '476F78840219.pas.ms.script' // TWMLButtonDown
 ;

ref; // ME_5567117900F2 Message

: ME_5567117301B0
 CONST UID '5567117301B0'
 CONST Name 'WMLButtonDown'
 CONST Class class_Operation
 : Stereotype st_message::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Parameters
   Seq: ( ME_5567117900F2 // Message
 )
 ; // Parameters
 CONST "Message ID" 'WM_LBUTTONDOWN'

ref; // ME_5567117301B0 WMLButtonDown

: ME_556711870062
 CONST Name 'Message'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_51540F7B0230' '476F78840219.pas.ms.script' // TWMLButtonUp
 ;

ref; // ME_556711870062 Message

: ME_55671181020A
 CONST UID '55671181020A'
 CONST Name 'WMLButtonUp'
 CONST Class class_Operation
 : Stereotype st_message::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Parameters
   Seq: ( ME_556711870062 // Message
 )
 ; // Parameters
 CONST "Message ID" 'WM_LBUTTONUP'

ref; // ME_55671181020A WMLButtonUp

: ME_5567119402F4
 CONST Name 'Message'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_508FAB07030A' '476F78840219.pas.ms.script' // TWMMouseMove
 ;

ref; // ME_5567119402F4 Message

: ME_5567118E02EF
 CONST UID '5567118E02EF'
 CONST Name 'WMMouseMove'
 CONST Class class_Operation
 : Stereotype st_message::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Parameters
   Seq: ( ME_5567119402F4 // Message
 )
 ; // Parameters
 CONST "Message ID" 'WM_MOUSEMOVE'

ref; // ME_5567118E02EF WMMouseMove

: ME_556711A3024F
 CONST Name 'Message'
 CONST Class class_Parameter
 : Stereotype st_inout ;
 : Target WL 'ME_556711FF008B' '476F78840219.pas.ms.script' // TWMShowWindow
 ;

ref; // ME_556711A3024F Message

: ME_5567119C03D0
 CONST UID '5567119C03D0'
 CONST Name 'WMShowWindow'
 CONST Class class_Operation
 : Stereotype st_message::Operation ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent HWL ME_556709D10061 // TvtCustomCalendarPanel
 ;
 : Parameters
   Seq: ( ME_556711A3024F // Message
 )
 ; // Parameters
 CONST "Message ID" 'WM_SHOWWINDOW'

ref; // ME_5567119C03D0 WMShowWindow

: ME_47D1602000C6_ME_556709D10061
 : Original WL 'ME_47D1602000C6' '4AB0997B00A2.pas.ms.script' // Create
 ;
 CONST OpKind opkind_Overridden
ref; // ME_47D1602000C6_ME_556709D10061 Create

: ME_48C6C044025E_ME_556709D10061
 : Original WL 'ME_48C6C044025E' '48BD1975029B.pas.ms.script' // Paint
 ;
 CONST OpKind opkind_Overridden
ref; // ME_48C6C044025E_ME_556709D10061 Paint

: ME_554CABC100AC_ME_556709D10061
 : Original WL 'ME_554CABC100AC' '4799D29F033F.pas.ms.script' // KeyDown
 ;
 CONST OpKind opkind_Overridden
ref; // ME_554CABC100AC_ME_556709D10061 KeyDown

: ME_556709D10061
 CONST UID '556709D10061'
 CONST Name 'TvtCustomCalendarPanel'
 CONST Class class_Class
 : Stereotype st_GuiControl ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5562DB5D0259 // TvtCalendarPanel
 ;
 : Inherits
   Seq: ( WL 'ME_50FD1AE5027A' '4A7961A701CF.pas.ms.script' // TvtCustomPanel
 )
 ; // Inherits
 : Attributes
   Seq: ( HWL ME_55670CE402C0 // f_ForceRedraw
 HWL ME_55670CF10085 // f_MouseDown
 HWL ME_55670D67017B // f_MonthIndent
 HWL ME_55670D7602EE // f_CurYear
 HWL ME_55670D82015C // f_CurMonth
 HWL ME_55670D8D02AB // f_CurDay
 HWL ME_55670E4C03BD // StartOfWeek
 HWL ME_55670E5E022C // Weekends
 HWL ME_55670E6702F2 // WeekendColor
 HWL ME_55670E87023E // OnChange
 HWL ME_55670FBF01D7 // OldDay
 HWL ME_55670FF801D4 // Date
 )
 ; // Attributes
 : Operations
   Seq: ( HWL ME_55670EF101FF // GetDayFromPoint
 HWL ME_55670F3A02E0 // GetDayRect
 HWL ME_55670F7202CB // DrawFocusFrame
 HWL ME_55670F9602CB // InvalidateDayArray
 HWL ME_55670FA502B8 // Change
 HWL ME_55671071035C // NextDay
 HWL ME_5567107A01EF // PrevDay
 HWL ME_55671084000E // NextWeek
 HWL ME_5567108F020C // PrevWeek
 HWL ME_5567109A01A1 // NextMonth
 HWL ME_556710A500BA // PrevMonth
 HWL ME_556710AF02F4 // NextYear
 HWL ME_556710BA0108 // PrevYear
 HWL ME_556710D300D7 // RelMoveDate
 HWL ME_5567115E02E0 // WMGetDlgCode
 HWL ME_5567117301B0 // WMLButtonDown
 HWL ME_55671181020A // WMLButtonUp
 HWL ME_5567118E02EF // WMMouseMove
 HWL ME_5567119C03D0 // WMShowWindow
 )
 ; // Operations
 : Overridden
   Seq: ( ME_47D1602000C6_ME_556709D10061 // Create
 ME_48C6C044025E_ME_556709D10061 // Paint
 ME_554CABC100AC_ME_556709D10061 // KeyDown
 )
 ; // Overridden
 CONST extprop:rc:SelfName 'CalendarPanel'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_556709D10061 TvtCustomCalendarPanel

FORWARD ME_5567126103D0

: ME_55671287013E
 CONST UID '55671287013E'
 CONST Name 'BorderIndent'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5567126103D0 // Calendar Panel const
 ;
 CONST Value 4
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 4

ref; // ME_55671287013E BorderIndent

: ME_556712910077
 CONST UID '556712910077'
 CONST Name 'SplitLineHeight'
 CONST Class class_Attribute
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent HWL ME_5567126103D0 // Calendar Panel const
 ;
 CONST Value 8
 CONST "AutoInc" false
 CONST "forced type" 'none'
 CONST "is define" false
 CONST extprop:pas:Value 8

ref; // ME_556712910077 SplitLineHeight

: ME_5567126103D0
 CONST UID '5567126103D0'
 CONST Name 'Calendar Panel const'
 CONST Class class_Class
 : Stereotype st_Constants ;
 CONST Kind kind_NormalClass
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 : Parent HWL ME_5562DB5D0259 // TvtCalendarPanel
 ;
 : Attributes
   Seq: ( HWL ME_55671287013E // BorderIndent
 HWL ME_556712910077 // SplitLineHeight
 )
 ; // Attributes
 CONST "spell names" false

ref; // ME_5567126103D0 Calendar Panel const

: ME_5567131F031A
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5562DB5D0259 // TvtCalendarPanel
 ;
 : Target WL 'ME_4B8E4B58034D' '4AC5DADB00C9.pas.ms.script' // vtDateEditRes
 ;

ref; // ME_5567131F031A 

: ME_5568449A02F5
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5562DB5D0259 // TvtCalendarPanel
 ;
 : Target WL 'ME_47289677028A' '472745450206.pas.ms.script' // Tl3SPoint
 ;

ref; // ME_5568449A02F5 

: ME_5568449D0199
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5562DB5D0259 // TvtCalendarPanel
 ;
 : Target WL 'ME_47878E0E0191' '54B90AC6014B.pas.ms.script' // l3String
 ;

ref; // ME_5568449D0199 

: ME_5568449F0208
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5562DB5D0259 // TvtCalendarPanel
 ;
 : Target WL 'ME_47E11FC3021E' '4799D29F033F.pas.ms.script' // Controls
 ;

ref; // ME_5568449F0208 

: ME_556844A10231
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent HWL ME_5562DB5D0259 // TvtCalendarPanel
 ;
 : Target WL 'ME_48A41FF10094' '4AB0C3F60375.pas.ms.script' // Windows
 ;

ref; // ME_556844A10231 

: ME_5562DB5D0259
 CONST UID '5562DB5D0259'
 CONST Name 'TvtCalendarPanel'
 CONST Class class_Class
 : Stereotype st_GuiControl ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent WL 'ME_4AC5DADB00C9' '4AC5DADB00C9.pas.ms.script' // DateEdit
 ;
 : Inherits
   Seq: ( HWL ME_556709D10061 // TvtCustomCalendarPanel
 )
 ; // Inherits
 : Children
   Seq: ( HWL ME_556709D10061 // TvtCustomCalendarPanel
 )
 ; // Children
 : Constants
   Seq: ( HWL ME_5567126103D0 // Calendar Panel const
 )
 ; // Constants
 : Dependencies
   Seq: ( ME_5567131F031A // vtDateEditRes
 ME_5568449A02F5 // Tl3SPoint
 ME_5568449D0199 // l3String
 ME_5568449F0208 // Controls
 ME_556844A10231 // Windows
 )
 ; // Dependencies
 CONST "need UC" true
 CONST intf.pas:Path 'common\components\gui\Garant\VT\vtCalendarPanel.pas'
 CONST extprop:rc:SelfName 'CalendarPanel'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'vtCalendarPanel'

ref; // ME_5562DB5D0259 TvtCalendarPanel
