// ScriptCallers 55C481E00003 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_55C481E00003

FORWARD ME_55C482690029

: ME_570FC6DE0328
 CONST UID '570FC6DE0328'
 CONST Name 'f_Starts'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_55C482690029 // TtfwDefaultScriptCaller
 ;
 : Target WL 'ME_4B2F4382001F' '47913B47006E.pas.ms.script' // Tl3CardinalList
 ;

ref; // ME_570FC6DE0328 f_Starts

FORWARD ME_55C491FC025C

: ME_55C4927600E2
 CONST Name 'aStr'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_46780D0003AF' '4677FBA70343.pas.ms.script' // Tl3WString
 ;

ref; // ME_55C4927600E2 aStr

: ME_55C4926D01BE
 CONST UID '55C4926D01BE'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55C491FC025C // DoPrint
 ;
 : Parameters
   Seq: ( ME_55C4927600E2 // aStr
 )
 ; // Parameters

ref; // ME_55C4926D01BE DoIt

: ME_55C4A5640321
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55C491FC025C // DoPrint
 ;
 : Target WL 'ME_47878E0E0191' '54B90AC6014B.pas.ms.script' // l3String
 ;

ref; // ME_55C4A5640321 

: ME_55C491FC025C
 CONST UID '55C491FC025C'
 CONST Name 'DoPrint'
 CONST Class class_Class
 : Stereotype st_virtualmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_55C482690029 // TtfwDefaultScriptCaller
 ;
 : Operations
   Seq: ( ME_55C4926D01BE // DoIt
 )
 ; // Operations
 : Dependencies
   Seq: ( ME_55C4A5640321 // l3String
 )
 ; // Dependencies

ref; // ME_55C491FC025C DoPrint

FORWARD ME_55C4A52C01A0

: ME_55C4A53202D3
 CONST UID '55C4A53202D3'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55C4A52C01A0 // Create
 ;

ref; // ME_55C4A53202D3 DoIt

: ME_55C4A52C01A0
 CONST UID '55C4A52C01A0'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_55C482690029 // TtfwDefaultScriptCaller
 ;
 : Operations
   Seq: ( ME_55C4A53202D3 // DoIt
 )
 ; // Operations

ref; // ME_55C4A52C01A0 Create

: ME_55C4A53D0305
 CONST UID '55C4A53D0305'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_55C482690029 // TtfwDefaultScriptCaller
 ;
 : Inherits
   Seq: ( ME_55C4A52C01A0 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4DAF1A1700F7' '4DAF19F600C5.pas.ms.script' // ItfwScriptCaller
 )
 ; // Implements
 CONST "check nil" false
 CONST "need AfterCreate" 'undefined'
 CONST "need Aggregate" 'undefined'
 CONST "need As" false

ref; // ME_55C4A53D0305 Make

FORWARD ME_55CC867301F7

: ME_55CC868302A8
 CONST UID '55CC868302A8'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55CC867301F7 // DictPath
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55CC868302A8 DoIt

: ME_55CC867301F7
 CONST UID '55CC867301F7'
 CONST Name 'DictPath'
 CONST Class class_Class
 : Stereotype st_virtualmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility ProtectedAccess
 CONST Abstraction at_regular
 : Parent ME_55C482690029 // TtfwDefaultScriptCaller
 ;
 : Operations
   Seq: ( ME_55CC868302A8 // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_55CC867301F7 DictPath

FORWARD ME_55D34AD90105

: ME_55D34AFC0293
 CONST Name 'aFile'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_55D34AFC0293 aFile

: ME_55D34AEA00A4
 CONST UID '55D34AEA00A4'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55D34AD90105 // DoResolveIncludedFilePath
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;
 : Parameters
   Seq: ( ME_55D34AFC0293 // aFile
 )
 ; // Parameters

ref; // ME_55D34AEA00A4 DoIt

: ME_55D34AD90105
 CONST UID '55D34AD90105'
 CONST Name 'DoResolveIncludedFilePath'
 CONST Class class_Class
 : Stereotype st_virtualmethod ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_55C482690029 // TtfwDefaultScriptCaller
 ;
 : Operations
   Seq: ( ME_55D34AEA00A4 // DoIt
 )
 ; // Operations
 CONST "is static" true

ref; // ME_55D34AD90105 DoResolveIncludedFilePath

: ME_55C4A5B701B3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55C482690029 // TtfwDefaultScriptCaller
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_55C4A5B701B3 

: ME_55CC865B0317
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55C482690029 // TtfwDefaultScriptCaller
 ;
 : Target WL 'ME_4F191FDD0358' '47D0290B016D.pas.ms.script' // ConcatDirName
 ;

ref; // ME_55CC865B0317 

: ME_570FCEEE020E
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55C482690029 // TtfwDefaultScriptCaller
 ;
 : Target WL 'ME_46780CCE037B' '47913B47006E.pas.ms.script' // Tl3Base
 ;

ref; // ME_570FCEEE020E 

: ME_570FCF030376
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55C482690029 // TtfwDefaultScriptCaller
 ;
 : Target WL 'ME_48A41FF10094' '4AB0C3F60375.pas.ms.script' // Windows
 ;

ref; // ME_570FCF030376 

: ME_4CAEDCF9006A_ME_55C482690029
 : Original WL 'ME_4CAEDCF9006A' '515AC8CC02BD.pas.ms.script' // CheckOutputWithInput$1
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4CAEDCF9006A_ME_55C482690029 CheckOutputWithInput$1

: ME_4DAF1A280116_ME_55C482690029
 : Original WL 'ME_4DAF1A280116' '4DAF19F600C5.pas.ms.script' // Check
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DAF1A280116_ME_55C482690029 Check

: ME_4DB173AA005A_ME_55C482690029
 : Original WL 'ME_4DB173AA005A' '4DAF19F600C5.pas.ms.script' // Print
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DB173AA005A_ME_55C482690029 Print

: ME_4DB1785F011A_ME_55C482690029
 : Original WL 'ME_4DB1785F011A' '4DAF19F600C5.pas.ms.script' // Print
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DB1785F011A_ME_55C482690029 Print

: ME_4DC2E1470046_ME_55C482690029
 : Original WL 'ME_4DC2E1470046' '4DAF19F600C5.pas.ms.script' // ResolveIncludedFilePath
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DC2E1470046_ME_55C482690029 ResolveIncludedFilePath

: ME_4DCA915C0120_ME_55C482690029
 : Original WL 'ME_4DCA915C0120' '4DAF19F600C5.pas.ms.script' // ResolveOutputFilePath
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DCA915C0120_ME_55C482690029 ResolveOutputFilePath

: ME_4DD533BF023D_ME_55C482690029
 : Original WL 'ME_4DD533BF023D' '515AC8CC02BD.pas.ms.script' // CheckWithEtalon
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DD533BF023D_ME_55C482690029 CheckWithEtalon

: ME_4DECF57B02D2_ME_55C482690029
 : Original WL 'ME_4DECF57B02D2' '4DAF19F600C5.pas.ms.script' // ResolveInputFilePath
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4DECF57B02D2_ME_55C482690029 ResolveInputFilePath

: ME_4F0D7AC900FA_ME_55C482690029
 : Original WL 'ME_4F0D7AC900FA' '4DAF19F600C5.pas.ms.script' // CheckPrintEtalon
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F0D7AC900FA_ME_55C482690029 CheckPrintEtalon

: ME_4F0D8B740186_ME_55C482690029
 : Original WL 'ME_4F0D8B740186' '4DAF19F600C5.pas.ms.script' // ShouldStop
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F0D8B740186_ME_55C482690029 ShouldStop

: ME_4F0D8C360085_ME_55C482690029
 : Original WL 'ME_4F0D8C360085' '4DAF19F600C5.pas.ms.script' // CheckTimeout
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F0D8C360085_ME_55C482690029 CheckTimeout

: ME_4F0D8C5A01A2_ME_55C482690029
 : Original WL 'ME_4F0D8C5A01A2' '4DAF19F600C5.pas.ms.script' // StartTimer
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F0D8C5A01A2_ME_55C482690029 StartTimer

: ME_4F0D8CB0015D_ME_55C482690029
 : Original WL 'ME_4F0D8CB0015D' '4DAF19F600C5.pas.ms.script' // StopTimer
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F0D8CB0015D_ME_55C482690029 StopTimer

: ME_4F0D91AA0080_ME_55C482690029
 : Original WL 'ME_4F0D91AA0080' '4DAF19F600C5.pas.ms.script' // KPage
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F0D91AA0080_ME_55C482690029 KPage

: ME_4F0DA2A7024A_ME_55C482690029
 : Original WL 'ME_4F0DA2A7024A' '4DAF19F600C5.pas.ms.script' // ToLog
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F0DA2A7024A_ME_55C482690029 ToLog

: ME_4F5F3C61023E_ME_55C482690029
 : Original WL 'ME_4F5F3C61023E' '515AC8CC02BD.pas.ms.script' // CheckOutputWithInput
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F5F3C61023E_ME_55C482690029 CheckOutputWithInput

: ME_4F72CEFE016D_ME_55C482690029
 : Original WL 'ME_4F72CEFE016D' '4DAF19F600C5.pas.ms.script' // GetIsWritingToK
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F72CEFE016D_ME_55C482690029 GetIsWritingToK

: ME_4F72CF27029A_ME_55C482690029
 : Original WL 'ME_4F72CF27029A' '4DAF19F600C5.pas.ms.script' // GetIsFakeCVS
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F72CF27029A_ME_55C482690029 GetIsFakeCVS

: ME_4F72CF78027D_ME_55C482690029
 : Original WL 'ME_4F72CF78027D' '4DAF19F600C5.pas.ms.script' // GetCVSPath
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F72CF78027D_ME_55C482690029 GetCVSPath

: ME_4F851D7B0399_ME_55C482690029
 : Original WL 'ME_4F851D7B0399' '4DAF19F600C5.pas.ms.script' // DontRaiseIfEtalonCreated
 ;
 CONST OpKind opkind_Implemented
ref; // ME_4F851D7B0399_ME_55C482690029 DontRaiseIfEtalonCreated

: ME_511BC7C60063_ME_55C482690029
 : Original WL 'ME_511BC7C60063' '4DAF19F600C5.pas.ms.script' // TimeToLog
 ;
 CONST OpKind opkind_Implemented
ref; // ME_511BC7C60063_ME_55C482690029 TimeToLog

: ME_513866B10237_ME_55C482690029
 : Original WL 'ME_513866B10237' '4DAF19F600C5.pas.ms.script' // GetTestSetFolderName
 ;
 CONST OpKind opkind_Implemented
ref; // ME_513866B10237_ME_55C482690029 GetTestSetFolderName

: ME_5138790002FF_ME_55C482690029
 : Original WL 'ME_5138790002FF' '4DAF19F600C5.pas.ms.script' // GetEtalonSuffix
 ;
 CONST OpKind opkind_Implemented
ref; // ME_5138790002FF_ME_55C482690029 GetEtalonSuffix

: ME_52EBC5BB0300_ME_55C482690029
 : Original WL 'ME_52EBC5BB0300' '4DAF19F600C5.pas.ms.script' // CompileOnly
 ;
 CONST OpKind opkind_Implemented
ref; // ME_52EBC5BB0300_ME_55C482690029 CompileOnly

: ME_536A15F901DA_ME_55C482690029
 : Original WL 'ME_536A15F901DA' '515AC8CC02BD.pas.ms.script' // CheckPictureOnly
 ;
 CONST OpKind opkind_Implemented
ref; // ME_536A15F901DA_ME_55C482690029 CheckPictureOnly

: ME_479731C50290_ME_55C482690029
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_55C482690029 Cleanup

: ME_55C482690029
 CONST UID '55C482690029'
 CONST Name 'TtfwDefaultScriptCaller'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_55C481E00003 // ScriptCallers
 ;
 : Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.pas.ms.script' // Tl3ProtoObject
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4DAF1A1700F7' '4DAF19F600C5.pas.ms.script' // ItfwScriptCaller
 )
 ; // Implements
 : Attributes
   Seq: ( ME_570FC6DE0328 // f_Starts
 )
 ; // Attributes
 : Operations
   Seq: ( ME_55C491FC025C // DoPrint
 ME_55C4A52C01A0 // Create
 ME_55C4A53D0305 // Make
 ME_55CC867301F7 // DictPath
 ME_55D34AD90105 // DoResolveIncludedFilePath
 )
 ; // Operations
 : Implemented
   Seq: ( ME_4CAEDCF9006A_ME_55C482690029 // CheckOutputWithInput$1
 ME_4DAF1A280116_ME_55C482690029 // Check
 ME_4DB173AA005A_ME_55C482690029 // Print
 ME_4DB1785F011A_ME_55C482690029 // Print
 ME_4DC2E1470046_ME_55C482690029 // ResolveIncludedFilePath
 ME_4DCA915C0120_ME_55C482690029 // ResolveOutputFilePath
 ME_4DD533BF023D_ME_55C482690029 // CheckWithEtalon
 ME_4DECF57B02D2_ME_55C482690029 // ResolveInputFilePath
 ME_4F0D7AC900FA_ME_55C482690029 // CheckPrintEtalon
 ME_4F0D8B740186_ME_55C482690029 // ShouldStop
 ME_4F0D8C360085_ME_55C482690029 // CheckTimeout
 ME_4F0D8C5A01A2_ME_55C482690029 // StartTimer
 ME_4F0D8CB0015D_ME_55C482690029 // StopTimer
 ME_4F0D91AA0080_ME_55C482690029 // KPage
 ME_4F0DA2A7024A_ME_55C482690029 // ToLog
 ME_4F5F3C61023E_ME_55C482690029 // CheckOutputWithInput
 ME_4F72CEFE016D_ME_55C482690029 // GetIsWritingToK
 ME_4F72CF27029A_ME_55C482690029 // GetIsFakeCVS
 ME_4F72CF78027D_ME_55C482690029 // GetCVSPath
 ME_4F851D7B0399_ME_55C482690029 // DontRaiseIfEtalonCreated
 ME_511BC7C60063_ME_55C482690029 // TimeToLog
 ME_513866B10237_ME_55C482690029 // GetTestSetFolderName
 ME_5138790002FF_ME_55C482690029 // GetEtalonSuffix
 ME_52EBC5BB0300_ME_55C482690029 // CompileOnly
 ME_536A15F901DA_ME_55C482690029 // CheckPictureOnly
 )
 ; // Implemented
 : Overridden
   Seq: ( ME_479731C50290_ME_55C482690029 // Cleanup
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_55C4A5B701B3 // SysUtils
 ME_55CC865B0317 // ConcatDirName
 ME_570FCEEE020E // Tl3Base
 ME_570FCF030376 // Windows
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\tfwDefaultScriptCaller.pas'
 CONST extprop:rc:SelfName 'DefaultScriptCaller'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'tfwDefaultScriptCaller'

ref; // ME_55C482690029 TtfwDefaultScriptCaller

FORWARD ME_55C48FCE03AB

: ME_55C4A57800C7
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55C48FCE03AB // TtfwConsoleScriptCaller
 ;
 : Target WL 'ME_47878E0E0191' '54B90AC6014B.pas.ms.script' // l3String
 ;

ref; // ME_55C4A57800C7 

: ME_55CC96DE0296
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_55C48FCE03AB // TtfwConsoleScriptCaller
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_55CC96DE0296 

: ME_55C491FC025C_ME_55C48FCE03AB
 : Original ME_55C491FC025C // DoPrint
 ;
 CONST OpKind opkind_Overridden
ref; // ME_55C491FC025C_ME_55C48FCE03AB DoPrint

: ME_55CC867301F7_ME_55C48FCE03AB
 : Original ME_55CC867301F7 // DictPath
 ;
 CONST OpKind opkind_Overridden
 CONST "is static" true
ref; // ME_55CC867301F7_ME_55C48FCE03AB DictPath

: ME_55C48FCE03AB
 CONST UID '55C48FCE03AB'
 CONST Name 'TtfwConsoleScriptCaller'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_55C481E00003 // ScriptCallers
 ;
 : Inherits
   Seq: ( ME_55C482690029 // TtfwDefaultScriptCaller
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_55C491FC025C_ME_55C48FCE03AB // DoPrint
 ME_55CC867301F7_ME_55C48FCE03AB // DictPath
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_55C4A57800C7 // l3String
 ME_55CC96DE0296 // SysUtils
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\tfwConsoleScriptCaller.pas'
 CONST extprop:rc:SelfName 'ConsoleScriptCaller'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'tfwConsoleScriptCaller'

ref; // ME_55C48FCE03AB TtfwConsoleScriptCaller

: ME_55D345A40226
 CONST UID '55D345A40226'
 CONST Name 'TtfwHyperlinkScriptCaller'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_55C481E00003 // ScriptCallers
 ;
 : Inherits
   Seq: ( ME_55C482690029 // TtfwDefaultScriptCaller
 )
 ; // Inherits
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\tfwHyperlinkScriptCaller.pas'
 CONST extprop:rc:SelfName 'HyperlinkScriptCaller'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'tfwHyperlinkScriptCaller'

ref; // ME_55D345A40226 TtfwHyperlinkScriptCaller

FORWARD ME_55D34A7E0127

FORWARD ME_2601B8C0800A

: ME_D0D5A4EAD080
 CONST UID 'D0D5A4EAD080'
 CONST Name 'RegAxiom'
 CONST IsSummoned true
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация скриптованой аксиоматики' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_2601B8C0800A // TtfwArchiHyperlinkScriptCallerResNameGetter
 ;

ref; // ME_D0D5A4EAD080 RegAxiom

: ME_55B7A3AF0359_ME_2601B8C0800A
 : Original WL 'ME_55B7A3AF0359' '55B7A3160128.pas.ms.script' // ResName
 ;
 CONST OpKind opkind_Implemented
 CONST "is static" true
ref; // ME_55B7A3AF0359_ME_2601B8C0800A ResName

: ME_2601B8C0800A
 CONST UID '2601B8C0800A'
 CONST Name 'TtfwArchiHyperlinkScriptCallerResNameGetter'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Регистрация скриптованой аксиоматики' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55D34A7E0127 // TtfwArchiHyperlinkScriptCaller
 ;
 : Inherits
   Seq: ( WL 'ME_55B7A33101AF' '55B7A3160128.pas.ms.script' // TtfwAxiomaticsResNameGetter
 )
 ; // Inherits
 : Operations
   Seq: ( ME_D0D5A4EAD080 // RegAxiom
 )
 ; // Operations
 : Implemented
   Seq: ( ME_55B7A3AF0359_ME_2601B8C0800A // ResName
 )
 ; // Implemented
 CONST "need UC" true
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST extprop:rc:SelfName 'ArchiHyperlinkScriptCallerResNameGetter'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_2601B8C0800A TtfwArchiHyperlinkScriptCallerResNameGetter

: ME_55D34AD90105_ME_55D34A7E0127
 : Original ME_55D34AD90105 // DoResolveIncludedFilePath
 ;
 CONST OpKind opkind_Overridden
 CONST "is static" true
ref; // ME_55D34AD90105_ME_55D34A7E0127 DoResolveIncludedFilePath

: ME_55D34A7E0127
 CONST UID '55D34A7E0127'
 CONST Name 'TtfwArchiHyperlinkScriptCaller'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_55C481E00003 // ScriptCallers
 ;
 : Inherits
   Seq: ( ME_55D345A40226 // TtfwHyperlinkScriptCaller
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_55D34AD90105_ME_55D34A7E0127 // DoResolveIncludedFilePath
 )
 ; // Overridden
 : Children
   Seq: ( ME_2601B8C0800A // TtfwArchiHyperlinkScriptCallerResNameGetter
 )
 ; // Children
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" true
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\tfwArchiHyperlinkScriptCaller.pas'
 CONST extprop:rc:SelfName 'ArchiHyperlinkScriptCaller'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'tfwArchiHyperlinkScriptCaller'

ref; // ME_55D34A7E0127 TtfwArchiHyperlinkScriptCaller

FORWARD ME_55D34A9B0067

FORWARD ME_77DB2124A8AE

: ME_4100BCBA3C15
 CONST UID '4100BCBA3C15'
 CONST Name 'RegAxiom'
 CONST IsSummoned true
 CONST Class class_Operation
 : Stereotype st_ini::Operation ;
 %SUMMARY 'Регистрация скриптованой аксиоматики' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_77DB2124A8AE // TtfwF1HyperlinkScriptCallerResNameGetter
 ;

ref; // ME_4100BCBA3C15 RegAxiom

: ME_55B7A3AF0359_ME_77DB2124A8AE
 : Original WL 'ME_55B7A3AF0359' '55B7A3160128.pas.ms.script' // ResName
 ;
 CONST OpKind opkind_Implemented
 CONST "is static" true
ref; // ME_55B7A3AF0359_ME_77DB2124A8AE ResName

: ME_77DB2124A8AE
 CONST UID '77DB2124A8AE'
 CONST Name 'TtfwF1HyperlinkScriptCallerResNameGetter'
 CONST IsSummoned true
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 %SUMMARY 'Регистрация скриптованой аксиоматики' ;
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_55D34A9B0067 // TtfwF1HyperlinkScriptCaller
 ;
 : Inherits
   Seq: ( WL 'ME_55B7A33101AF' '55B7A3160128.pas.ms.script' // TtfwAxiomaticsResNameGetter
 )
 ; // Inherits
 : Operations
   Seq: ( ME_4100BCBA3C15 // RegAxiom
 )
 ; // Operations
 : Implemented
   Seq: ( ME_55B7A3AF0359_ME_77DB2124A8AE // ResName
 )
 ; // Implemented
 CONST "need UC" true
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST extprop:rc:SelfName 'F1HyperlinkScriptCallerResNameGetter'
 CONST extprop:rc:isAcceptableForScripts true

ref; // ME_77DB2124A8AE TtfwF1HyperlinkScriptCallerResNameGetter

: ME_55D34AD90105_ME_55D34A9B0067
 : Original ME_55D34AD90105 // DoResolveIncludedFilePath
 ;
 CONST OpKind opkind_Overridden
 CONST "is static" true
ref; // ME_55D34AD90105_ME_55D34A9B0067 DoResolveIncludedFilePath

: ME_55D34A9B0067
 CONST UID '55D34A9B0067'
 CONST Name 'TtfwF1HyperlinkScriptCaller'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_55C481E00003 // ScriptCallers
 ;
 : Inherits
   Seq: ( ME_55D345A40226 // TtfwHyperlinkScriptCaller
 )
 ; // Inherits
 : Overridden
   Seq: ( ME_55D34AD90105_ME_55D34A9B0067 // DoResolveIncludedFilePath
 )
 ; // Overridden
 : Children
   Seq: ( ME_77DB2124A8AE // TtfwF1HyperlinkScriptCallerResNameGetter
 )
 ; // Children
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" true
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\tfwF1HyperlinkScriptCaller.pas'
 CONST extprop:rc:SelfName 'F1HyperlinkScriptCaller'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'tfwF1HyperlinkScriptCaller'

ref; // ME_55D34A9B0067 TtfwF1HyperlinkScriptCaller

FORWARD ME_56456E3E01E4

: ME_56456E910302
 CONST UID '56456E910302'
 CONST Name 'f_OutFiler'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_56456E3E01E4 // TtfwOutToFileScriptCaller
 ;
 : Target WL 'ME_53A05AFD02CC' '47913B47006E.pas.ms.script' // Tl3DOSFiler
 ;

ref; // ME_56456E910302 f_OutFiler

: ME_564571210221
 CONST UID '564571210221'
 CONST Name 'f_FileName'
 CONST Class class_Attribute
 CONST Visibility PrivateAccess
 CONST Abstraction at_regular
 CONST LinkType lt_agr
 : Parent ME_56456E3E01E4 // TtfwOutToFileScriptCaller
 ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_564571210221 f_FileName

FORWARD ME_5645710E0083

: ME_564571370276
 CONST Name 'aFileName'
 CONST Class class_Parameter
 : Stereotype st_in ;
 : Target WL 'ME_476136D3010B' '4AB0C3C60310.pas.ms.script' // String
 ;

ref; // ME_564571370276 aFileName

: ME_5645712D01A1
 CONST UID '5645712D01A1'
 CONST Name 'DoIt'
 CONST Class class_Operation
 CONST Visibility PrivateAccess
 CONST Abstraction at_final
 : Parent ME_5645710E0083 // Create
 ;
 : Parameters
   Seq: ( ME_564571370276 // aFileName
 )
 ; // Parameters

ref; // ME_5645712D01A1 DoIt

: ME_5645710E0083
 CONST UID '5645710E0083'
 CONST Name 'Create'
 CONST Class class_Class
 : Stereotype st_Constructor ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_56456E3E01E4 // TtfwOutToFileScriptCaller
 ;
 : Operations
   Seq: ( ME_5645712D01A1 // DoIt
 )
 ; // Operations

ref; // ME_5645710E0083 Create

: ME_5645713B035C
 CONST UID '5645713B035C'
 CONST Name 'Make'
 CONST Class class_Class
 : Stereotype st_Factory ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_final
 : Parent ME_56456E3E01E4 // TtfwOutToFileScriptCaller
 ;
 : Inherits
   Seq: ( ME_5645710E0083 // Create
 )
 ; // Inherits
 : Implements
   Seq: ( WL 'ME_4DAF1A1700F7' '4DAF19F600C5.pas.ms.script' // ItfwScriptCaller
 )
 ; // Implements
 CONST "check nil" false
 CONST "need AfterCreate" 'undefined'
 CONST "need Aggregate" 'undefined'
 CONST "need As" false

ref; // ME_5645713B035C Make

: ME_56456E760304
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_56456E3E01E4 // TtfwOutToFileScriptCaller
 ;
 : Target WL 'ME_47877EB202FB' '4AB0C3C60310.pas.ms.script' // SysUtils
 ;

ref; // ME_56456E760304 

: ME_56456EBF01AD
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_56456E3E01E4 // TtfwOutToFileScriptCaller
 ;
 : Target WL 'ME_48F4BE400154' '4678193C009C.pas.ms.script' // Tl3FileMode
 ;

ref; // ME_56456EBF01AD 

: ME_56456ECF02B3
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_56456E3E01E4 // TtfwOutToFileScriptCaller
 ;
 : Target WL 'ME_47878E0E0191' '54B90AC6014B.pas.ms.script' // l3String
 ;

ref; // ME_56456ECF02B3 

: ME_5645886600F0
 CONST Class class_Dependency
 : Stereotype st_uses::Dependency ;
 : Parent ME_56456E3E01E4 // TtfwOutToFileScriptCaller
 ;
 : Target WL 'ME_49082AE80393' '476BE98C01B8.pas.ms.script' // Code Pages
 ;

ref; // ME_5645886600F0 

: ME_479731C50290_ME_56456E3E01E4
 : Original WL 'ME_479731C50290' '51612EBB02F5.pas.ms.script' // Cleanup
 ;
 CONST OpKind opkind_Overridden
ref; // ME_479731C50290_ME_56456E3E01E4 Cleanup

: ME_55C491FC025C_ME_56456E3E01E4
 : Original ME_55C491FC025C // DoPrint
 ;
 CONST OpKind opkind_Overridden
ref; // ME_55C491FC025C_ME_56456E3E01E4 DoPrint

: ME_56456E3E01E4
 CONST UID '56456E3E01E4'
 CONST Name 'TtfwOutToFileScriptCaller'
 CONST Class class_Class
 : Stereotype st_SimpleClass ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_55C481E00003 // ScriptCallers
 ;
 : Inherits
   Seq: ( ME_55C48FCE03AB // TtfwConsoleScriptCaller
 )
 ; // Inherits
 : Attributes
   Seq: ( ME_56456E910302 // f_OutFiler
 ME_564571210221 // f_FileName
 )
 ; // Attributes
 : Operations
   Seq: ( ME_5645710E0083 // Create
 ME_5645713B035C // Make
 )
 ; // Operations
 : Overridden
   Seq: ( ME_479731C50290_ME_56456E3E01E4 // Cleanup
 ME_55C491FC025C_ME_56456E3E01E4 // DoPrint
 )
 ; // Overridden
 : Dependencies
   Seq: ( ME_56456E760304 // SysUtils
 ME_56456EBF01AD // Tl3FileMode
 ME_56456ECF02B3 // l3String
 ME_5645886600F0 // Code Pages
 )
 ; // Dependencies
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'
 CONST intf.pas:Path 'common\components\rtl\Garant\ScriptEngine\tfwOutToFileScriptCaller.pas'
 CONST extprop:rc:SelfName 'OutToFileScriptCaller'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'tfwOutToFileScriptCaller'

ref; // ME_56456E3E01E4 TtfwOutToFileScriptCaller

: ME_55C481E00003
 CONST UID '55C481E00003'
 CONST Name 'ScriptCallers'
 CONST Class class_Category
 : Stereotype st_Unit ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_54CF97B10370' '54CF97B10370.pas.ms.script' // ScriptEngine$Core
 ;
 : Children
   Seq: ( ME_55C482690029 // TtfwDefaultScriptCaller
 ME_55C48FCE03AB // TtfwConsoleScriptCaller
 ME_55D345A40226 // TtfwHyperlinkScriptCaller
 ME_55D34A7E0127 // TtfwArchiHyperlinkScriptCaller
 ME_55D34A9B0067 // TtfwF1HyperlinkScriptCaller
 ME_56456E3E01E4 // TtfwOutToFileScriptCaller
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4677FBA70343' '4677FBA70343.pas.ms.script' // l3Interfaces
 WL 'ME_4678193C009C' '4678193C009C.pas.ms.script' // l3Types
 WL 'ME_476BE98C01B8' '476BE98C01B8.pas.ms.script' // l3Chars
 WL 'ME_47913B47006E' '47913B47006E.pas.ms.script' // l3CoreObjects
 WL 'ME_47D0290B016D' '47D0290B016D.pas.ms.script' // l3Utils
 WL 'ME_4DAF19F600C5' '4DAF19F600C5.pas.ms.script' // tfwScriptingInterfaces
 )
 ; // Depends
 CONST "UseNewGen" true

ref; // ME_55C481E00003 ScriptCallers
