// TExprEditorWordsPack 55C8CDFC039B ScriptKeywordsPack Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_55C8CDFC039B

ME ME_55C8CE280375
 MEPROP UID '55C8CE280375'
 MEPROP Name 'Fake'
 MEPROP Class class_Operation
 MELINK Stereotype st_keyword::Operation ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_55C8CDFC039B // TExprEditorWordsPack
 ;

ENDME // ME_55C8CE280375 Fake

%%InheritedBy ME_4F57640C0241 ME_55C8CDFC039B

ME ME_55C8CDFC039B
 MEPROP UID '55C8CDFC039B'
 MEPROP Name 'TExprEditorWordsPack'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_ScriptKeywordsPack ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL 'ME_55C8CD14003A' '55C8CD14003A.ms.model.script' // Dialogs
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4F57640C0241' '4F5763F4012E.ms.model.script' // TExprEditor
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_55C8CE280375 // Fake
 )
 ; // Operations
 UP "ifndef" 'NoScripts'
 UP intf.pas:Path 'archi\source\projects\Common\Dialogs\TExprEditorWordsPack.pas'

ENDME // ME_55C8CDFC039B TExprEditorWordsPack
