// K605147298 55CC6F620202 TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4C971C2203DD_ME_55CC6F620202_G
 MELINK Original WL? 'ME_4C971C2203DD' // RTFtoEVDWriterTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4C971C2203DD_ME_55CC6F620202_G RTFtoEVDWriterTest

%%InheritedBy ME_4C971C2203DD ME_55CC6F620202

ME ME_55CC6F620202
 MEPROP UID '55CC6F620202'
 MEPROP Name 'K605147298'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:605147298}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_549199FF02ED' // 7.11
 ;
 MELIST Inherits
   Seq: ( ME_4C971C2203DD_ME_55CC6F620202_G // RTFtoEVDWriterTest
 )
 ; // Inherits
 UP intf.pas:Path 'common\components\rtl\Garant\Daily\K605147298.pas'
 UP extprop:pas:TypeName 'TK605147298'
 UP extprop:rc:SelfName 'K605147298'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_55CC6F620202 K605147298
