// TtfwWordsIterator 55ED4D040017 SimpleClass Class

INCLUDE '52E29ED5016B.pas.ms.script'

INCLUDE '4DAF19F600C5.pas.ms.script'

INCLUDE '51612ED700B4.pas.ms.script'

FORWARD ME_55ED4D040017

INCLUDE '4DB6CAC402B4.pas.ms.script'

: ME_55ED4D4B0071
 CONST UID '55ED4D4B0071'
 CONST Name 'f_Words'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_4DB6CAC402B4 // TtfwWordRefList
 ;

 @SELF
; // ME_55ED4D4B0071 f_Words

FORWARD ME_55ED4DC20358

: ME_55ED4DD40105
 CONST UID '55ED4DD40105'
 CONST Name 'aWords'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_4DB6CAC402B4 // TtfwWordRefList
 ;

 @SELF
; // ME_55ED4DD40105 aWords

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_55ED4DCA01B6
 CONST UID '55ED4DCA01B6'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Parameters
   [ ME_55ED4DD40105 // aWords
 ]
 ; // Parameters

 @SELF
; // ME_55ED4DCA01B6 DoIt

: ME_55ED4DC20358
 CONST UID '55ED4DC20358'
 CONST Name 'Create'
 CONST Class 'Class'
 CONST Stereotype 'Constructor'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_55ED4DCA01B6 // DoIt
 ]
 ; // Operations

 @SELF
; // ME_55ED4DC20358 Create

FORWARD ME_55ED4DDB03D8

: ME_37A47E7BC864
 CONST UID '37A47E7BC864'
 CONST Name 'aWords'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_4DB6CAC402B4 // TtfwWordRefList
 ;

 @SELF
; // ME_37A47E7BC864 aWords

: ME_45843FCC7984
 CONST UID '45843FCC7984'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 %SUMMARY 'Сигнатура фабрики TtfwWordsIterator.Make' ;
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Target ME_4DCC12FC0125 // ItfwValueList
 ;
 : Parameters
   [ ME_37A47E7BC864 // aWords
 ]
 ; // Parameters

 @SELF
; // ME_45843FCC7984 DoIt

: ME_55ED4DDB03D8
 CONST UID '55ED4DDB03D8'
 CONST Name 'Make'
 CONST Class 'Class'
 CONST Stereotype 'Factory'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Inherits
   [ ME_55ED4DC20358 // Create
 ]
 ; // Inherits
 : Implements
   [ ME_4DCC12FC0125 // ItfwValueList
 ]
 ; // Implements
 : Operations
   [ ME_45843FCC7984 // DoIt
 ]
 ; // Operations
 CONST "check nil" false
 CONST "need AfterCreate" 'undefined'
 CONST "need Aggregate" 'undefined'
 CONST "need As" false

 @SELF
; // ME_55ED4DDB03D8 Make

: ME_55ED4D040017
 CONST UID '55ED4D040017'
 CONST Name 'TtfwWordsIterator'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_52E29ED5016B // TtfwIteratableParent
 ]
 ; // Inherits
 : Implements
   [ ME_4DCC12FC0125 // ItfwValueList
 ]
 ; // Implements
 : Attributes
   [ ME_55ED4D4B0071 // f_Words
 ]
 ; // Attributes
 : Operations
   [ ME_55ED4DC20358 // Create
 ME_55ED4DDB03D8 // Make
 ]
 ; // Operations
 : Implemented
   [ ME_52E23B7A00EC // ForEach
 ME_52E23BB102FA // ForEachBack
 ME_55CDF40C03D4 // SetItem
 ME_55E849210175 // ItemsCountInSlice
 ]
 ; // Implemented
 : Overridden
   [ ME_479731C50290 // Cleanup
 ]
 ; // Overridden
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_55ED4D040017 TtfwWordsIterator
