// TkwCompiledWordPrimPrim 55EEDAFE018F SimpleClass Class

INCLUDE '556427250160.pas.ms.script'

INCLUDE '51612ED700B4.pas.ms.script'

INCLUDE '47913F4E02E0.pas.ms.script'

INCLUDE '4DAF19F600C5.pas.ms.script'

FORWARD ME_55EEDAFE018F

: ME_55EEDB270091
 CONST UID '55EEDB270091'
 CONST Name 'f_WordProducer'
 CONST Class 'Attribute'
 CONST Stereotype ''
 %SUMMARY 'Слово, которое породило данное при компиляции' ;
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'lnk'
 : Target ME_4DAEED140007 // TtfwWord
 ;

 @SELF
; // ME_55EEDB270091 f_WordProducer

FORWARD ME_55EEDB4E00B3

: ME_55EEDB66023C
 CONST UID '55EEDB66023C'
 CONST Name 'aWordProducer'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_4DAEED140007 // TtfwWord
 ;

 @SELF
; // ME_55EEDB66023C aWordProducer

: ME_55EEDB660264
 CONST UID '55EEDB660264'
 CONST Name 'aCtx'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_4DB0091E033E // TtfwContext
 ;

 @SELF
; // ME_55EEDB660264 aCtx

INCLUDE '4FFEEC080367.pas.ms.script'

: ME_55EEDB66028C
 CONST UID '55EEDB66028C'
 CONST Name 'aKey'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_4FFEEC080367 // TtfwKeyWordPrim
 ;

 @SELF
; // ME_55EEDB66028C aKey

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_55EEDB540277
 CONST UID '55EEDB540277'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Parameters
   [ ME_55EEDB66023C // aWordProducer
 ME_55EEDB660264 // aCtx
 ME_55EEDB66028C // aKey
 ]
 ; // Parameters

 @SELF
; // ME_55EEDB540277 DoIt

: ME_55EEDB4E00B3
 CONST UID '55EEDB4E00B3'
 CONST Name 'Create'
 CONST Class 'Class'
 CONST Stereotype 'Constructor'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_55EEDB540277 // DoIt
 ]
 ; // Operations

 @SELF
; // ME_55EEDB4E00B3 Create

: ME_0E888E20A724
 CONST UID '0E888E20A724'
 CONST Name 'Ini_Reg_Class'
 CONST Class 'Operation'
 CONST Stereotype 'ini'
 %SUMMARY 'Регистрация TkwCompiledWordPrimPrim' ;
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 CONST "ifndef" 'NoScripts'

 @SELF
; // ME_0E888E20A724 Ini_Reg_Class

: ME_55EEDAFE018F
 CONST UID '55EEDAFE018F'
 CONST Name 'TkwCompiledWordPrimPrim'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_556427250160 // TkwSourcePointWord
 ]
 ; // Inherits
 : Attributes
   [ ME_55EEDB270091 // f_WordProducer
 ]
 ; // Attributes
 : Operations
   [ ME_55EEDB4E00B3 // Create
 ME_0E888E20A724 // Ini_Reg_Class
 ]
 ; // Operations
 : Overridden
   [ ME_479731C50290 // Cleanup
 ME_47A6FEE600FC // IsCacheable
 ME_4F43C9A10139 // WordProducer
 ME_52D6B62E001B // GetEndBracket
 ME_52D7DC84019E // AcceptMedianBracket
 ]
 ; // Overridden
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_55EEDAFE018F TkwCompiledWordPrimPrim
