// TvcmControlList 55F5814303D8 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_55F5814303D8

ME ME_55F58175015E
 MEPROP UID '55F58175015E'
 MEPROP Name 'ItemType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_55F5814303D8 // TvcmControlList
 ;
 MELINK Target WL 'ME_47E1201703C3' '47E11FC3021E.ms.model.script' // TControl
 ;

ENDME // ME_55F58175015E ItemType

MEREF ME_4A54DD4E036F_ME_55F5814303D8_G
 MELINK Original WL? 'ME_4A54DD4E036F' // Tl3ProtoDataContainer
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4A54DD4E036F_ME_55F5814303D8_G Tl3ProtoDataContainer

MEREF ME_47B57B7800A7_ME_55F5814303D8_R
 MELINK Original WL? 'ME_47B57B7800A7' // l3ObjectPtrList
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_47B57B7800A7_ME_55F5814303D8_R l3ObjectPtrList

%%ImplementedBy ME_47B57B7800A7 ME_55F5814303D8

%%InheritedBy ME_4A54DD4E036F ME_55F5814303D8

ME ME_55F5814303D8
 MEPROP UID '55F5814303D8'
 MEPROP Name 'TvcmControlList'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_47DF70170311' // vcmCore
 ;
 MELIST Inherits
   Seq: ( ME_4A54DD4E036F_ME_55F5814303D8_G // Tl3ProtoDataContainer
 )
 ; // Inherits
 MELIST Implements
   Seq: ( ME_47B57B7800A7_ME_55F5814303D8_R // l3ObjectPtrList
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_55F58175015E // ItemType
 )
 ; // Attributes
 UP intf.pas:Path 'common\components\gui\Garant\VCM\implementation\vcmControlList.pas'
 UP extprop:rc:SelfName 'ControlList'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'vcmControlList'

ENDME // ME_55F5814303D8 TvcmControlList
