// TvcmEntities 560AC98C026A SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_560AC98C026A
 MEPROP UID '560AC98C026A'
 MEPROP Name 'TvcmEntities'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4AB34028023E' // Components
 ;
 UP "finished" false
 UP intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Components\NOT_FINISHED_vcmEntities.pas'
 UP extprop:rc:SelfName 'Entities'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'vcmEntities'

ENDME // ME_560AC98C026A TvcmEntities
