// TpgResultSet 560B961401E4 SimpleClass Class

INCLUDE '49E7754802A9.pas.ms.script'

INCLUDE '5432518A0316.pas.ms.script'

INCLUDE '51612ED700B4.pas.ms.script'

FORWARD ME_560B961401E4

INCLUDE '556C43B0014B.pas.ms.script'

: ME_560BA50701CE
 CONST UID '560BA50701CE'
 CONST Name 'f_Result'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_556DA51E037C // PPGresult
 ;

 @SELF
; // ME_560BA50701CE f_Result

INCLUDE '4807744200AA.pas.ms.script'

: ME_560E33120071
 CONST UID '560E33120071'
 CONST Name 'f_CurrentPos'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_4DE60F5E00A6 // LongInt
 ;

 @SELF
; // ME_560E33120071 f_CurrentPos

: ME_560E331E03D8
 CONST UID '560E331E03D8'
 CONST Name 'f_EOF'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_560E331E03D8 f_EOF

INCLUDE '55C84D190010.pas.ms.script'

: ME_560E70FD000D
 CONST UID '560E70FD000D'
 CONST Name 'f_FieldsDescription'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_55C84D190010 // TdaSelectFieldList
 ;

 @SELF
; // ME_560E70FD000D f_FieldsDescription

INCLUDE '5637497102C9.pas.ms.script'

: ME_560E77A20333
 CONST UID '560E77A20333'
 CONST Name 'f_Fields'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_5637497102C9 // TdaFieldList
 ;

 @SELF
; // ME_560E77A20333 f_Fields

INCLUDE '55DAD4150001.pas.ms.script'

: ME_5627729E012B
 CONST UID '5627729E012B'
 CONST Name 'f_DataConverter'
 CONST Class 'Attribute'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'regular'
 CONST LinkType 'agr'
 : Target ME_55E41C6E00E2 // IpgDataConverter
 ;

 @SELF
; // ME_5627729E012B f_DataConverter

FORWARD ME_560B99890062

INCLUDE '55F6875803A8.pas.ms.script'

: ME_560B99D4021C
 CONST UID '560B99D4021C'
 CONST Name 'aConnection'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_55F6875803A8 // TpgConnection
 ;

 @SELF
; // ME_560B99D4021C aConnection

: ME_560B99D4022C
 CONST UID '560B99D4022C'
 CONST Name 'aDataConverter'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_55E41C6E00E2 // IpgDataConverter
 ;

 @SELF
; // ME_560B99D4022C aDataConverter

: ME_560B99D4024B
 CONST UID '560B99D4024B'
 CONST Name 'aQueryName'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_476136D3010B // String
 ;

 @SELF
; // ME_560B99D4024B aQueryName

INCLUDE '5555C169038C.pas.ms.script'

: ME_560B99D4026A
 CONST UID '560B99D4026A'
 CONST Name 'aParams'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_5555C169038C // TdaParamList
 ;

 @SELF
; // ME_560B99D4026A aParams

: ME_560B99D402A8
 CONST UID '560B99D402A8'
 CONST Name 'aSelectFields'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_55C84D190010 // TdaSelectFieldList
 ;

 @SELF
; // ME_560B99D402A8 aSelectFields

: ME_560B99D402F6
 CONST UID '560B99D402F6'
 CONST Name 'Unidirectional'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_560B99D402F6 Unidirectional

INCLUDE '3DBFDB23006E.pas.ms.script'

: ME_560B999B03DE
 CONST UID '560B999B03DE'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Parameters
   [ ME_560B99D4021C // aConnection
 ME_560B99D4022C // aDataConverter
 ME_560B99D4024B // aQueryName
 ME_560B99D4026A // aParams
 ME_560B99D402A8 // aSelectFields
 ME_560B99D402F6 // Unidirectional
 ]
 ; // Parameters

 @SELF
; // ME_560B999B03DE DoIt

: ME_560B99890062
 CONST UID '560B99890062'
 CONST Name 'Create'
 CONST Class 'Class'
 CONST Stereotype 'Constructor'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Operations
   [ ME_560B999B03DE // DoIt
 ]
 ; // Operations

 @SELF
; // ME_560B99890062 Create

FORWARD ME_560B99FB0299

: ME_61216A45398B
 CONST UID '61216A45398B'
 CONST Name 'aConnection'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_55F6875803A8 // TpgConnection
 ;

 @SELF
; // ME_61216A45398B aConnection

: ME_C6B937AFB310
 CONST UID 'C6B937AFB310'
 CONST Name 'aDataConverter'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_55E41C6E00E2 // IpgDataConverter
 ;

 @SELF
; // ME_C6B937AFB310 aDataConverter

: ME_A654A9051224
 CONST UID 'A654A9051224'
 CONST Name 'aQueryName'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_476136D3010B // String
 ;

 @SELF
; // ME_A654A9051224 aQueryName

: ME_76A9FBED43A6
 CONST UID '76A9FBED43A6'
 CONST Name 'aParams'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_5555C169038C // TdaParamList
 ;

 @SELF
; // ME_76A9FBED43A6 aParams

: ME_4128F08A4CE4
 CONST UID '4128F08A4CE4'
 CONST Name 'aSelectFields'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_55C84D190010 // TdaSelectFieldList
 ;

 @SELF
; // ME_4128F08A4CE4 aSelectFields

: ME_F4C06B2D387C
 CONST UID 'F4C06B2D387C'
 CONST Name 'Unidirectional'
 CONST Class 'Parameter'
 CONST Stereotype 'in'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Target ME_46A603BB0391 // Boolean
 ;

 @SELF
; // ME_F4C06B2D387C Unidirectional

: ME_428A68182B5D
 CONST UID '428A68182B5D'
 CONST Name 'DoIt'
 CONST Class 'Operation'
 CONST Stereotype ''
 %SUMMARY 'Сигнатура фабрики TpgResultSet.Make' ;
 CONST Visibility 'PrivateAccess'
 CONST Abstraction 'final'
 : Target ME_558BDCD00086 // IdaResultSet
 ;
 : Parameters
   [ ME_61216A45398B // aConnection
 ME_C6B937AFB310 // aDataConverter
 ME_A654A9051224 // aQueryName
 ME_76A9FBED43A6 // aParams
 ME_4128F08A4CE4 // aSelectFields
 ME_F4C06B2D387C // Unidirectional
 ]
 ; // Parameters

 @SELF
; // ME_428A68182B5D DoIt

: ME_560B99FB0299
 CONST UID '560B99FB0299'
 CONST Name 'Make'
 CONST Class 'Class'
 CONST Stereotype 'Factory'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'final'
 : Inherits
   [ ME_560B99890062 // Create
 ]
 ; // Inherits
 : Implements
   [ ME_558BDCD00086 // IdaResultSet
 ]
 ; // Implements
 : Operations
   [ ME_428A68182B5D // DoIt
 ]
 ; // Operations
 : Implemented
   [ ME_5549C44C037A // Next
 ME_5549C45A025C // EOF
 ME_558BF63203D7 // IsEmpty
 ME_5590FD57027D // Field
 ]
 ; // Implemented
 CONST "check nil" false
 CONST "need AfterCreate" 'undefined'
 CONST "need Aggregate" 'undefined'
 CONST "need As" false

 @SELF
; // ME_560B99FB0299 Make

: ME_560B961401E4
 CONST UID '560B961401E4'
 CONST Name 'TpgResultSet'
 CONST Class 'Class'
 CONST Stereotype 'SimpleClass'
 CONST Visibility 'PublicAccess'
 CONST Abstraction 'regular'
 : Inherits
   [ ME_49E7754802A9 // Tl3ProtoObject
 ]
 ; // Inherits
 : Implements
   [ ME_558BDCD00086 // IdaResultSet
 ME_55A63E0A00E7 // IdaResultBuffer
 ]
 ; // Implements
 : Attributes
   [ ME_560BA50701CE // f_Result
 ME_560E33120071 // f_CurrentPos
 ME_560E331E03D8 // f_EOF
 ME_560E70FD000D // f_FieldsDescription
 ME_560E77A20333 // f_Fields
 ME_5627729E012B // f_DataConverter
 ]
 ; // Attributes
 : Operations
   [ ME_560B99890062 // Create
 ME_560B99FB0299 // Make
 ]
 ; // Operations
 : Implemented
   [ ME_5549C44C037A // Next
 ME_5549C45A025C // EOF
 ME_558BF63203D7 // IsEmpty
 ME_5590FD57027D // Field
 ME_55A63E22019B // RegisterField
 ME_55A63E3D0122 // UnregisterField
 ME_55C8996702B1 // FieldBufferPtr
 ]
 ; // Implemented
 : Overridden
   [ ME_479731C50290 // Cleanup
 ]
 ; // Overridden
 CONST "needs InstanceR" 'undefined'
 CONST "needs script" 'undefined'
 CONST "no hands" false
 CONST "register in scripts" 'undefined'

 @SELF
; // ME_560B961401E4 TpgResultSet
