// Containers 561D3DA401FE Layer Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_561D3DA401FE

: ME_561D40470085
 CONST UID '561D40470085'
 CONST Name 'Tl3LongintList'
 CONST Class class_Class
 : Stereotype st_ClassProxy ;
 CONST Kind kind_NormalClass
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent ME_561D3DA401FE // Containers
 ;
 CONST extprop:rc:SelfName 'LongintList'
 CONST extprop:rc:isAcceptableForScripts true
 CONST extprop:pas:UnitName 'Tl3LongintList_Proxy'

ref; // ME_561D40470085 Tl3LongintList

: ME_561D3DA401FE
 CONST UID '561D3DA401FE'
 CONST Name 'Containers'
 CONST Class class_Category
 : Stereotype st_Layer ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Parent WL 'ME_561D37540316' '561D37540316.pas.ms.script' // L3$Interface
 ;
 : Children
   Seq: ( ME_561D40470085 // Tl3LongintList
 )
 ; // Children
 CONST pas.script:Path 'shared\models\NewSchool\Scripts\561D3DA401FE.pas.ms.script'
 CONST pas.script.runner:Path 'shared\models\NewSchool\Scripts\561D3DA401FE.pas.ms.script.runner'

ref; // ME_561D3DA401FE Containers
