// New Generator 5626580A00B5 ProjectGroup Category

INCLUDE 'ElementsRTTI.ms.dict'

: ME_5626580A00B5
 CONST UID '5626580A00B5'
 CONST Name 'New Generator'
 CONST Class class_Category
 : Stereotype st_ProjectGroup ;
 CONST Visibility PublicAccess
 CONST Abstraction at_regular
 : Children
   Seq: ( WL 'ME_4F6AE3CE036B' '4F6AE3CE036B.pas.ms.script' // MDProcess$NewGen$Interface
 WL 'ME_4F5F65870086' '4F5F65870086.pas.ms.script' // MDProcess$NewGen
 )
 ; // Children
 : Depends
   Seq: ( WL 'ME_4F6CCC8800A0' '4F6CCC8800A0.pas.ms.script' // Shared Delphi F1 Like Application
 WL 'ME_561FCFDC007C' '561FCFDC007C.pas.ms.script' // Templates
 WL 'ME_5623B27D02CF' '5623B27D02CF.pas.ms.script' // Shared Delphi Core And Low Level
 WL 'ME_56263D2100DB' '56263D2100DB.pas.ms.script' // Shared Delphi Libraries
 )
 ; // Depends

ref; // ME_5626580A00B5 New Generator
