// K615679638 5694C6F30101 TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_5694C6F30101

MEREF ME_4C937013031D_ME_5694C6F30101_over
 MELINK Original WL 'ME_4C937013031D' '4B2A0DCE03A9.ms.model.script' // GetFolder
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_4C937013031D_ME_5694C6F30101_over GetFolder

MEREF ME_4DAED6F60146_ME_5694C6F30101_over
 MELINK Original WL 'ME_4DAED6F60146' '4B2A0DCE03A9.ms.model.script' // GetModelElementGUID
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_4DAED6F60146_ME_5694C6F30101_over GetModelElementGUID

MEREF ME_51406117007F_ME_5694C6F30101_over
 MELINK Original WL 'ME_51406117007F' '4BACDDB500CE.ms.model.script' // TreatExceptionAsSuccess
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_51406117007F_ME_5694C6F30101_over TreatExceptionAsSuccess

MEREF ME_4C971C2203DD_ME_5694C6F30101_G
 MELINK Original WL? 'ME_4C971C2203DD' // RTFtoEVDWriterTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4C971C2203DD_ME_5694C6F30101_G RTFtoEVDWriterTest

%%InheritedBy ME_4C971C2203DD ME_5694C6F30101

ME ME_5694C6F30101
 MEPROP UID '5694C6F30101'
 MEPROP Name 'K615679638'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:615679638}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_56124E2F02D2' // 7.12
 ;
 MELIST Inherits
   Seq: ( ME_4C971C2203DD_ME_5694C6F30101_G // RTFtoEVDWriterTest
 )
 ; // Inherits
 MELIST Overridden
   Seq: ( ME_4C937013031D_ME_5694C6F30101_over // GetFolder
 ME_4DAED6F60146_ME_5694C6F30101_over // GetModelElementGUID
 ME_51406117007F_ME_5694C6F30101_over // TreatExceptionAsSuccess
 )
 ; // Overridden
 UP intf.pas:Path 'common\components\rtl\Garant\Daily\K615679638.pas'
 UP extprop:pas:TypeName 'TK615679638'
 UP extprop:rc:SelfName 'K615679638'
 UP extprop:rc:isAcceptableForScripts true

ENDME // ME_5694C6F30101 K615679638
