// TcsSchedulerProxyTask 57065CCE0306 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_52F8C2BF0110_ME_57065CCE0306_G
 MELINK Original WL 'ME_52F8C2BF0110' '52F8C2AE0042.ms.model.script' // TddProcessTask
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_52F8C2BF0110_ME_57065CCE0306_G TddProcessTask

MEREF ME_5706552C0169_ME_57065CCE0306_R
 MELINK Original WL 'ME_5706552C0169' '484A470100DD.ms.model.script' // SchedulerProxyTask
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_5706552C0169_ME_57065CCE0306_R SchedulerProxyTask

%%ImplementedBy ME_5706552C0169 ME_57065CCE0306

%%InheritedBy ME_52F8C2BF0110 ME_57065CCE0306

ME ME_57065CCE0306
 MEPROP UID '57065CCE0306'
 MEPROP Name 'TcsSchedulerProxyTask'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_52F8C298005C' // Tasks
 ;
 MELIST Inherits
   Seq: ( ME_52F8C2BF0110_ME_57065CCE0306_G // TddProcessTask
 )
 ; // Inherits
 MELIST Implements
   Seq: ( ME_5706552C0169_ME_57065CCE0306_R // SchedulerProxyTask
 )
 ; // Implements
 UP intf.pas:Path 'common\components\rtl\Garant\cs\csSchedulerProxyTask.pas'
 UP extprop:rc:SelfName 'csSchedulerProxyTask'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'csSchedulerProxyTask'

ENDME // ME_57065CCE0306 TcsSchedulerProxyTask
