// Tl3ClipSpyService 57762BA20039 Service Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_57762BA20039

ME ME_57762C5F03A0
 MEPROP Name 'aListner'
 MEPROP Class class_Parameter
 MELINK Stereotype st_const ;
 MELINK Target WL 'ME_57762C030193' '57762BD601E1.ms.model.script' // Il3ClipListner
 ;

ENDME // ME_57762C5F03A0 aListner

ME ME_57762C370191
 MEPROP UID '57762C370191'
 MEPROP Name 'Subscribe'
 MEPROP Class class_Operation
 MELINK Stereotype st_responsibility::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_57762BA20039 // Tl3ClipSpyService
 ;
 MELIST Parameters
   Seq: ( ME_57762C5F03A0 // aListner
 )
 ; // Parameters

ENDME // ME_57762C370191 Subscribe

ME ME_57762C6C0368
 MEPROP Name 'aListner'
 MEPROP Class class_Parameter
 MELINK Stereotype st_const ;
 MELINK Target WL 'ME_57762C030193' '57762BD601E1.ms.model.script' // Il3ClipListner
 ;

ENDME // ME_57762C6C0368 aListner

ME ME_57762C6503A9
 MEPROP UID '57762C6503A9'
 MEPROP Name 'Unsubscribe'
 MEPROP Class class_Operation
 MELINK Stereotype st_responsibility::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_57762BA20039 // Tl3ClipSpyService
 ;
 MELIST Parameters
   Seq: ( ME_57762C6C0368 // aListner
 )
 ; // Parameters

ENDME // ME_57762C6503A9 Unsubscribe

MEREF ME_49E7754802A9_ME_57762BA20039_G
 MELINK Original WL? 'ME_49E7754802A9' // Tl3ProtoObject
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_49E7754802A9_ME_57762BA20039_G Tl3ProtoObject

%%InheritedBy ME_49E7754802A9 ME_57762BA20039

ME ME_57762BA20039
 MEPROP UID '57762BA20039'
 MEPROP Name 'Tl3ClipSpyService'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_Service ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL? 'ME_57762B5A0168' // vtServices
 ;
 MELIST Inherits
   Seq: ( ME_49E7754802A9_ME_57762BA20039_G // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_57762C370191 // Subscribe
 HWL ME_57762C6503A9 // Unsubscribe
 )
 ; // Operations
 UP "auto translate to alien" 'undefined'
 UP intf.pas:Path 'common\components\rtl\Garant\L3\l3ClipSpyService.pas'
 UP extprop:rc:SelfName 'ClipSpyService'
 UP extprop:rc:isAcceptableForScripts true
 UP extprop:pas:UnitName 'l3ClipSpyService'

ENDME // ME_57762BA20039 Tl3ClipSpyService
