#define yy_create_buffer gcla__create_buffer
#define yy_delete_buffer gcla__delete_buffer
#define yy_scan_buffer gcla__scan_buffer
#define yy_scan_string gcla__scan_string
#define yy_scan_bytes gcla__scan_bytes
#define yy_flex_debug gcla__flex_debug
#define yy_init_buffer gcla__init_buffer
#define yy_flush_buffer gcla__flush_buffer
#define yy_load_buffer_state gcla__load_buffer_state
#define yy_switch_to_buffer gcla__switch_to_buffer
#define yyin gcla_in
#define yyleng gcla_leng
#define yylex gcla_lex
#define yyout gcla_out
#define yyrestart gcla_restart
#define yytext gcla_text

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /export/home/cvs/garantPIL/implementation/component/cpp/tools/gctools/src/classes.cpp,v 2.58 2011/10/24 12:42:46 vlad Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <vector>
#include <deque>
#include <string>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern std::deque<std::string> errors;
extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 36
#define YY_END_OF_BUFFER 37
static yyconst short int yy_accept[184] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   37,   32,
       11,   35,    1,   32,    2,    3,    4,    1,    5,    8,
        1,   32,    7,   32,   34,    1,   10,    1,    9,   36,
       28,   29,   31,    1,   30,   26,   27,    1,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    3,
        0,   33,    9,   28,   29,   30,   26,   27,    0,    0,
        0,    0,    0,   24,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   24,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    6,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    6,
        0,    0,   22,    0,    0,    0,    0,    0,   23,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   23,
        0,    0,    0,   12,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   12,   13,    0,    0,    0,    0,
        0,    0,   25,    0,    0,   13,   21,   15,   14,   16,
       20,   17,   18,   19,   21,   15,   14,   16,   20,   17,
       18,   19,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    1,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    7,    1,    1,    1,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    6,    1,
        9,    1,    1,    1,   10,   11,   12,   13,   14,   15,
        1,    1,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,    1,   30,    1,    1,
        1,   31,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[32] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5
    } ;

static yyconst short int yy_base[194] =
    {   0,
        0,    3,    7,    9,   12,   42,   14,   18,   20,   22,
       28,   30,   72,   79,   36,   38,   53,   57,  257,  258,
      258,  258,  258,   79,    0,    0,  258,    0,  258,  258,
      258,  248,  258,    0,  258,    0,  258,  258,  247,  258,
      246,   45,  258,   60,  245,    0,   50,   62,  233,  226,
       29,  228,  225,  226,  226,  221,  217,  230,    0,    0,
      235,    0,  234,  233,   94,  232,    0,   65,  220,  224,
      227,  216,  223,  232,  208,  205,   90,  217,  205,  220,
      205,  212,  200,  205,  198,  221,  202,  207,  202,  204,
      201,  191,  190,    0,  190,  191,  187,  189,  188,  187,

      186,  185,  191,  183,  182,  188,    0,  189,  177,  199,
      175,  174,  173,  172,  171,  165,  169,  168,  170,    0,
      176,  176,  187,  174,  173,  172,  171,  170,   56,  169,
      168,  160,  164,  164,  163,  162,  161,  160,  159,  171,
      142,  156,  155,  167,  138,  151,  150,  149,  148,  147,
      146,  159,  144,  143,  156,  155,  126,  125,  121,  120,
      115,  110,  133,   81,   80,  107,  105,  104,  103,   97,
       95,   83,   76,   75,   70,   69,   61,   35,   33,   27,
       25,   17,  258,  112,  117,  122,  127,  132,  137,  142,
      147,    0,  152

    } ;

static yyconst short int yy_def[194] =
    {   0,
      184,  184,  185,  185,  184,  184,  186,  186,  184,  184,
      184,  184,  184,  184,  184,  184,  187,  187,  183,  183,
      183,  183,  183,  183,  188,  189,  183,  189,  183,  183,
      183,  183,  183,  190,  183,  190,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  191,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  188,  189,
      183,  190,  183,  183,  183,  183,  191,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  192,  183,  183,  183,  183,  183,  183,

      183,  183,  183,  183,  183,  183,  193,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  193,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,    0,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183

    } ;

static yyconst short int yy_nxt[290] =
    {   0,
      107,   21,   22,   23,   21,   22,   23,   24,   25,   27,
       28,   27,   28,   29,   30,   31,   35,   36,  182,   32,
       35,   36,   37,   38,   37,   38,  181,   39,  180,   39,
       40,   38,   40,   38,  179,   41,  178,   41,   40,   38,
       40,   38,   33,   29,   30,   31,   65,   71,   65,   32,
       72,   65,   68,   68,   20,   47,   48,  140,   20,   47,
       48,   65,  177,   65,   68,   68,   65,   68,   68,  141,
      176,  175,   33,   42,   43,   44,  182,  181,   42,   45,
       42,   43,   44,   20,  180,   42,   45,   20,   49,   50,
       51,   52,   53,   54,   55,   65,  179,   65,  178,   89,

       65,   56,   57,   90,  177,  176,  175,   58,  166,  174,
      173,   91,   20,   20,   20,   20,   20,   26,   26,   26,
       26,   26,   34,   34,   34,   34,   34,   46,   46,   46,
       46,   46,   59,   59,  163,   59,   59,   60,   60,  172,
       60,   60,   62,   62,  171,   62,   62,   67,   67,  170,
      169,   67,  120,  120,  168,  167,  166,  155,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  140,  151,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  139,  138,  137,  136,  135,  123,  134,
      133,  132,  131,  130,  129,  128,  127,  126,  125,  124,

      123,  122,  121,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  110,  109,  108,  106,  105,  104,  103,  102,
      101,  100,   86,   99,   98,   97,   96,   95,   94,   93,
       92,   88,   87,   86,   85,   84,   83,   82,   81,   66,
       64,   63,   80,   79,   78,   77,   76,   75,   74,   73,
       70,   69,   66,   64,   63,   61,  183,   19,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183
    } ;

static yyconst short int yy_chk[290] =
    {   0,
      192,    1,    1,    1,    2,    2,    2,    2,    2,    3,
        3,    4,    4,    5,    5,    5,    7,    7,  182,    5,
        8,    8,    9,    9,   10,   10,  181,    9,  180,   10,
       11,   11,   12,   12,  179,   11,  178,   12,   15,   15,
       16,   16,    5,    6,    6,    6,   42,   51,   42,    6,
       51,   42,   47,   47,   17,   17,   17,  129,   18,   18,
       18,   44,  177,   44,   48,   48,   44,   68,   68,  129,
      176,  175,    6,   13,   13,   13,  174,  173,   13,   13,
       14,   14,   14,   17,  172,   14,   14,   18,   24,   24,
       24,   24,   24,   24,   24,   65,  171,   65,  170,   77,

       65,   24,   24,   77,  169,  168,  167,   24,  166,  165,
      164,   77,  184,  184,  184,  184,  184,  185,  185,  185,
      185,  185,  186,  186,  186,  186,  186,  187,  187,  187,
      187,  187,  188,  188,  163,  188,  188,  189,  189,  162,
      189,  189,  190,  190,  161,  190,  190,  191,  191,  160,
      159,  191,  193,  193,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  128,  127,  126,  125,  124,  123,  122,
      121,  119,  118,  117,  116,  115,  114,  113,  112,  111,

      110,  109,  108,  106,  105,  104,  103,  102,  101,  100,
       99,   98,   97,   96,   95,   93,   92,   91,   90,   89,
       88,   87,   86,   85,   84,   83,   82,   81,   80,   79,
       78,   76,   75,   74,   73,   72,   71,   70,   69,   66,
       64,   63,   61,   58,   57,   56,   55,   54,   53,   52,
       50,   49,   45,   41,   39,   32,   19,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "classes.flex"
#define INITIAL 0
#define YY_NO_UNPUT 1
#define COMMENT 1

#define GETREST 2

#define FERROR 3

#define GETVERSION 4

#define GETEQID 5

#define GETEQSET 6

#define GETNOSUF 7

#define GETPREFIXEX 8

#line 15 "classes.flex"
#include <osdep.h>
#include <stdio.h>
#include <unistd.h>
//#include "FString.long.SplayMap.h"
//#include "FString.SplaySet.h"
//#include "FString.caddr_t.SplayMap.h"
//#include "FString.SplaySet.h"
#include "CaseString.defs.h"
#include "classes.h"
#include "hnode.h"
#include "gardefs.h"
#include "garcomp.h"
#include "gclog.h"
	static int cln;
	static char *fullsrc, *stripsrc;
	static char *ft, *ts;
	static int print_prefix;
	static void doGetRest();
	static void doNoSuffix();
	static int prepend;
	static int enableClasses;
	static int enablePrefixes;
	static ClassesInfo *pCI;
	static void (*end_of_rest)();
	static void *end_of_rest_param;
	static void (*rest_slash)();
	static void claEndOfRest(), claSlash(), endOfClasses();
	static void setPrefixSlash(), setPrefixEndOfRest();
	static void prefixSlash(), prefixEndOfRest();
	static void setupEQ(), doEQ(), finishEQ();
	static struct ClassesInfo::ClassInfo *classInfo = 0;
	static struct ClassesInfo::PrefixInfo *prefixInfo = 0;
	static int nInClasses = 0;
	static int maxInClasses = 0;
	static int nInPrefixes = 0;
	static int maxInPrefixes = 0;
	static unsigned char isClassFlushed = 0;
	static unsigned char isEQFlushed = 0;
	static int *cEqs = 0, nEq=0, cEq=0, mEq=0;
	static int endOfClassesDone = 0;
	static int endOfPrefixesDone = 0;
	static void setPrefixTypes();
	static void endOfPrefixes();
	static void parsePrefixEx();
	static HNode * clsTree;
	static HNode * pfxTree;

	static unsigned char bWasFatal = 0;

unsigned char isPrefixType(CaseStringSplaySet& prefixGroup, FString& prefix)
{
	for (Pix pix = prefixGroup.first(); pix; prefixGroup.next(pix))
	{
		if ((prefix.length() == prefixGroup(pix).length()) && (strcasecmp(prefix.chars(),prefixGroup(pix).chars()) == 0)) return 1;
		if ((prefix.length() < prefixGroup(pix).length()) || (prefix.chars()[prefixGroup(pix).length()] != '\\')) continue;

		char * subprefix = new char[prefixGroup(pix).length()+1];
		memcpy(subprefix,prefix.chars(),prefixGroup(pix).length());
		subprefix[prefixGroup(pix).length()] = 0;
		unsigned char res = (strcasecmp(subprefix,prefixGroup(pix).chars()) == 0);
		delete subprefix;
		if (res) return 1;
	}
	return 0;
}

void setPrefixTypes()
{
	for( int i=0; i<nInPrefixes; i++)
	{
		FString s( prefixInfo[i].prefixName );
		prefixInfo[i].prefixType = 0;

		//if (isPrefixType(*pCI->docPrefixes,s))  prefixInfo[i].prefixType |= DS_ISDOC;
		/*
		if (isPrefixType(*pCI->commPrefixes,s)) prefixInfo[i].prefixType |= DS_ISCOMMENT;
		if (isPrefixType(*pCI->formPrefixes,s)) prefixInfo[i].prefixType |= DS_ISFORM;
		if (isPrefixType(*pCI->projPrefixes,s)) prefixInfo[i].prefixType |= DS_ISPROJECT;
		if (isPrefixType(*pCI->prakPrefixes,s)) prefixInfo[i].prefixType |= DS_ISPRAKTIC;
		if (isPrefixType(*pCI->intePrefixes,s)) prefixInfo[i].prefixType |= DS_ISINTER;
		if (isPrefixType(*pCI->quesPrefixes,s)) prefixInfo[i].prefixType |= DS_ISQUESTION;
		if (isPrefixType(*pCI->brefPrefixes,s)) prefixInfo[i].prefixType |= DS_ISBREFER;
		*/
	}
}


#define SETUPPREFIX(target) \
							prepend =0;\
							ft=fullsrc; \
							ts=stripsrc;\
							end_of_rest = setPrefixEndOfRest; \
							end_of_rest_param= pCI->target; \
							rest_slash = setPrefixSlash; \
							BEGIN(GETREST);







#line 630 "lex.gcla_.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 137 "classes.flex"

#line 786 "lex.gcla_.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 184 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 258 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 138 "classes.flex"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 139 "classes.flex"
BEGIN(COMMENT);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 140 "classes.flex"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 141 "classes.flex"
cln++; BEGIN(INITIAL);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 142 "classes.flex"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 143 "classes.flex"
doGetRest();
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 144 "classes.flex"
{ if(rest_slash) (*rest_slash)(); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 145 "classes.flex"
{ if(end_of_rest) (*end_of_rest)(); isClassFlushed = 1; BEGIN(INITIAL); cln++;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 146 "classes.flex"
{
						if( ! pCI-> v )
							pCI->v = atoi(yytext);
						else{
							gclog.setLN(cln);
							gclog.printfC(AdvLogger::LOG_ERROR, 
								AdvLogger::CD_KOI, "˜≈“”…— ’÷≈ –œÕ≈ﬁ≈Œ¡.\n");
						}
					}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 155 "classes.flex"
{ BEGIN(INITIAL); cln++; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 156 "classes.flex"

	YY_BREAK
case 12:
YY_RULE_SETUP
#line 157 "classes.flex"
BEGIN(GETVERSION);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 159 "classes.flex"
{ SETUPPREFIX(allPrefixes) }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 160 "classes.flex"
{ SETUPPREFIX(docPrefixes) }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 161 "classes.flex"
{ SETUPPREFIX(commPrefixes); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 162 "classes.flex"
{ SETUPPREFIX(formPrefixes); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 163 "classes.flex"
{ SETUPPREFIX(prakPrefixes); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 164 "classes.flex"
{ SETUPPREFIX(projPrefixes); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 165 "classes.flex"
{ SETUPPREFIX(quesPrefixes); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 166 "classes.flex"
{ SETUPPREFIX(intePrefixes); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 167 "classes.flex"
{ SETUPPREFIX(brefPrefixes); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 168 "classes.flex"
{
						if( enableClasses ){
							prepend = 0;
							ft=fullsrc;
							ts=stripsrc;
							end_of_rest = claEndOfRest;
							rest_slash = claSlash;
							isClassFlushed = 0;
							BEGIN(GETREST);
						}else{
							gclog.printfC(AdvLogger::LOG_ERROR, 
								AdvLogger::CD_KOI,
					"Ó≈Ãÿ⁄— …”–œÃÿ⁄œ◊¡‘ÿ CLASS –œ”Ã≈ EQ …Ã… PREFIXEX\n");
						}
					}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 183 "classes.flex"
{
						if( enablePrefixes ){
							prepend = 0;
							ft=fullsrc;
							ts=stripsrc;
							end_of_rest = prefixEndOfRest;
							rest_slash = prefixSlash;
							BEGIN(GETREST);
						}else{
							gclog.printfC(AdvLogger::LOG_ERROR, 
								AdvLogger::CD_KOI,
							"Ó≈Ãÿ⁄— …”–œÃÿ⁄œ◊¡‘ÿ PREFIX –œ”Ã≈ PREFIXEX\n");
						}
					}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 197 "classes.flex"
if( !endOfClassesDone ) isEQFlushed = 0; endOfClasses(); BEGIN(GETEQID);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 198 "classes.flex"
{
						if( !endOfPrefixesDone ) 
								endOfPrefixes();
						if( !endOfClassesDone ) 
								endOfClasses();
						BEGIN(GETPREFIXEX);
					}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 205 "classes.flex"
parsePrefixEx();
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 206 "classes.flex"
gclog.setLN(++cln); BEGIN(INITIAL);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 207 "classes.flex"
setupEQ();
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 208 "classes.flex"

	YY_BREAK
case 30:
YY_RULE_SETUP
#line 209 "classes.flex"
doEQ();
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 210 "classes.flex"
finishEQ(); isEQFlushed = 1; BEGIN(INITIAL); gclog.setLN(++cln);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 211 "classes.flex"
yymore(); BEGIN(FERROR); 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 212 "classes.flex"
{
				gclog.setLN(cln);
				gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,
					"Ô€…¬À¡ ∆œ“Õ¡‘¡ œÀœÃœ '%s'\n", yytext ); 
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 217 "classes.flex"
gclog.setLN(++cln); BEGIN(INITIAL);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 218 "classes.flex"
gclog.setLN(++cln);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 219 "classes.flex"
ECHO;
	YY_BREAK
#line 1101 "lex.gcla_.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(GETREST):
case YY_STATE_EOF(FERROR):
case YY_STATE_EOF(GETVERSION):
case YY_STATE_EOF(GETEQID):
case YY_STATE_EOF(GETEQSET):
case YY_STATE_EOF(GETNOSUF):
case YY_STATE_EOF(GETPREFIXEX):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 184 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 184 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 183);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 219 "classes.flex"


void parsePrefixEx()
{
	char *bf = strdup(yytext);
	gclog.setLN(cln);
	int jumpType = 0;
	char *pfx, *unname, *cls;
	char *p, *q;
	
	pfx = bf;
	char *cmd = strchr( bf, ':' );
	if (!cmd) return;
	*cmd = 0;
	
	FString pf(pfx); pf.bDoFree=1;
	
	FString *pt = pCI->pTranslate( pf, ClassesInfo::TRANSPREFIX );
	if( !pt ) {
		gclog.setLN(cln);
		gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,
			"Ó≈ Õœ«’ “¡”–œ⁄Œ¡‘ÿ –“≈∆…À” ");
		gclog.printfCP(AdvLogger::CD_ALT, "'%s'\n", pfx);
		return;
	}

	for (p = cmd+1, q = strchr(p,';'); *p; p = q+1, q = strchr(p,';'))
	{
		if (!q)
		{
			gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,"Command is not finished with ';'");
			return;
		}
		*q = 0;
		
		char * tmp = strchr(p,':');
		if (!tmp)
		{
			jumpType = 0;
			unname = p;
			cls = q;
		}
		else
		{
			*tmp = 0;
			unname = p;
			cls = tmp+1;
			char * jump = q-1;
			while ((jump > cls) && (*jump == '\\'))
			{
				*jump = 0;
				jumpType++;
				jump--;
			}
		}
		
		FString c(cls); c.bDoFree=1;
		FString *ct = 0;
		if (*cls)
		{
			ct = pCI->pTranslate( c, ClassesInfo::TRANSCLASS );
			if( !ct ) {
				gclog.setLN(cln);
				gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,"Ó≈ Õœ«’ “¡”–œ⁄Œ¡‘ÿ ÀÃ¡”” ");
				gclog.printfCP(AdvLogger::CD_ALT, "'%s'\n", cls);
				continue;
			}
		}
		else
		{
			ct = new FString("");
		}

		if (jumpType == 2 && *unname == 0)
		{

#undef CHECKEX
#define CHECKEX(a) if (pCI->a->contains(*pt))	\
			{	\
				gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_WIN,"ÕÂ ÏÓ„Û ‰Ó·‡‚ËÚ¸ ÒÔËÒÓÍ ‰ÓÍÛÏÂÌÚÓ‚-ÔÓÚÓÏÍÓ‚ ÍÌÓÔÍË ÓÒÌÓ‚ÌÓ„Ó ÏÂÌ˛.  ÓÏ‡Ì‰‡ Ë„ÌÓËÛÂÚÒˇ.\n");	\
				continue;	\
			}


			CHECKEX(allPrefixes);
			CHECKEX(docPrefixes);
			CHECKEX(commPrefixes);
			CHECKEX(formPrefixes);
			CHECKEX(projPrefixes);
			CHECKEX(prakPrefixes);
			CHECKEX(intePrefixes);
			CHECKEX(quesPrefixes);
			CHECKEX(brefPrefixes);

#undef CHECKEX
		}
		
		ClassesInfo::UnodeInfo *ninfo = (ClassesInfo::UnodeInfo *)(*(pCI->unodes))[*pt];
		if( !ninfo )
		{
			ninfo = (ClassesInfo::UnodeInfo *)calloc( 1, sizeof( ClassesInfo::UnodeInfo ));
			(*(pCI->unodes))[*pt] = (caddr_t)ninfo;
		}
		if( ninfo->nIn >= ninfo->maxIn )
		{
			ninfo->maxIn += 10;
			ninfo->node = (ClassesInfo::UnodeInfo::NI*)realloc( ninfo->node,sizeof(ClassesInfo::UnodeInfo::NI)*ninfo->maxIn );
		}
		ninfo->node[ninfo->nIn].jtype = jumpType;
		ninfo->node[ninfo->nIn].uname = strdup(unname);
		ninfo->node[ninfo->nIn].cls = strdup(ct->chars());

		delete ct;

		if (print_prefix)
		{
			gclog.printfC(AdvLogger::LOG_INFO_MPCXC, AdvLogger::CD_ALT,
				"PREFIXEX (%d)>>%s:%s:%s<<\n",
				ninfo->node[ninfo->nIn].jtype,
				pt->chars(),
				ninfo->node[ninfo->nIn].uname,
				ninfo->node[ninfo->nIn].cls );
		}
		ninfo->nIn ++;
	}

	delete pt;

	if( bf ) free(bf);
	yymore(); BEGIN(FERROR);
}

void setupEQ()
{
	cEq = atoi(yytext) - 1;
	if( cEq < 0 || cEq >= nInClasses ){
		gclog.setLN(cln);
		gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,
			"Ó≈◊≈“ŒŸ  ŒœÕ≈“ EQ: %d\n", cEq);
		BEGIN(COMMENT);
	}else{
		BEGIN(GETEQSET);
	}
	nEq = 0;
}

void doEQ()
{
	if (yytext[0] < '0' || yytext[0] > '9') 
	{
		gclog.setLN(cln);
		gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,
			"Ó≈◊≈“ŒŸ  …ƒ≈Œ‘…∆…À¡‘œ“ ÀÃ¡””¡ %s.\n", yytext ); 
	}
	int t = atoi(yytext) -1;
	if( t < nInClasses )
	{
		if( nEq >= mEq )
		{
			mEq += 10;
			cEqs = (int*)realloc(cEqs,mEq*sizeof(int));
		}
		cEqs[nEq++] = t;
	}else{
		gclog.setLN(cln);
		gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,
			"Ó≈◊≈“ŒŸ  …ƒ≈Œ‘…∆…À¡‘œ“ ÀÃ¡””¡ %d.\n", t ); 
	}
}
void finishEQ()
{
	if( nEq )
	{
		classInfo[cEq].equals = (int*) realloc(classInfo[cEq].equals,
						(classInfo[cEq].nEquals+nEq)*sizeof(int));
		for( ;nEq; nEq--)
			classInfo[cEq].equals[classInfo[cEq].nEquals++]=cEqs[nEq-1];
	}
}

void endOfClasses()
{
	enableClasses = 0;
	endOfClassesDone = 1;
	classInfo = (ClassesInfo::ClassInfo *)realloc(classInfo,
			sizeof(ClassesInfo::ClassInfo)*nInClasses);
	pCI->classCount = nInClasses;
	pCI->clInfo = classInfo;
}
void endOfPrefixes()
{
	enablePrefixes = 0;
	endOfPrefixesDone = 1;
	prefixInfo = (ClassesInfo::PrefixInfo *)realloc(prefixInfo,
			sizeof(ClassesInfo::PrefixInfo)*nInPrefixes);
	pCI->prefixCount = nInPrefixes;
	pCI->pfxInfo = prefixInfo;
}
void claEndOfRest()
{
	FString s(stripsrc, ts - stripsrc);
	
	HNode * nnew = 0;
	HN_STATUS st = clsTree->addNode(s.chars(),nnew);

	if( (*(pCI->cm)).contains(s) || (st & INS_BRK))
	{
		gclog.setLN(cln);
		gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,"œ◊‘œ“—¿›… ”— …Ã… Œ≈–œÃŒŸ  ÀÃ¿ﬁ ");
		gclog.printfCP(AdvLogger::CD_ALT,"'%s'\n",s.chars());
		return;
	}

	if (st & INS_CONT)
	{
		HNode * p = 0;
		for (p = nnew->parent; !p->bIsFinal; p = p->parent);
		FString bad(p->path());
		(*(pCI->cm)).del(bad);
		gclog.setLN((int)(p->p));
		p->bIsFinal = 0;
		gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,"œ◊‘œ“—¿›… ”— …Ã… Œ≈–œÃŒŸ  ÀÃ¿ﬁ ");
		gclog.printfCP(AdvLogger::CD_ALT,"'%s'\n",bad.chars());
	}

	if (st & INS_CASE)
	{
		gclog.setLN(cln);
		gclog.printfC(AdvLogger::LOG_FATAL, AdvLogger::CD_WIN,"ÕÂ‚ÂÌ˚È Â„ËÒÚ. Œ‰ËÌ ËÁ ÛÁÎÓ‚ ÒÚÓÍË ÓÔÂ‰ÂÎÂÌ ‚ ‰Û„ÓÏ Â„ËÒÚÂ: ");
		gclog.printfCP(AdvLogger::CD_ALT,"'%s'\n",s.chars());
		bWasFatal = 1;
		return;
	}

	s.bDoFree = 0;
	(*(pCI->cm))[s] = nInClasses;
	nnew->p = (void*)cln;
	int t=classInfo[nInClasses].nameLength = ft-fullsrc+1;
	char *p = (char*)malloc(t);
	if (!p) {
		gclog.printfC(AdvLogger::LOG_FATAL, AdvLogger::CD_KOI,
			"≈“≈–œÃŒ≈Œ…≈ –¡Õ—‘….\n");
		bWasFatal = 1;
		return;
	}
	memcpy(p, fullsrc, t);
	classInfo[nInClasses].className = p;
	classInfo[nInClasses].nEquals = 0;
	classInfo[nInClasses].equals = 0;
	nInClasses++;
}

void prefixEndOfRest()
{
	FString s(stripsrc, ts - stripsrc);
	HNode * nnew = 0;
	HN_STATUS st = pfxTree->addNode(s.chars(),nnew);

	if( (*(pCI->pm)).contains(s) && (st & INS_BRK))
	{
		gclog.setLN(cln);
		gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,"œ◊‘œ“—¿›… ”— …Ã… Œ≈–œÃŒŸ  ÀÃ¿ﬁ ");
		gclog.printfCP(AdvLogger::CD_ALT,"'%s'\n",s.chars());
		return;
	}

	if (st & INS_CONT)
	{
		HNode * p = 0;
		for (p = nnew->parent; !p->bIsFinal; p = p->parent);
		FString bad(p->name);
		FString pn(p->name);
		(*(pCI->cm)).del(pn);
		gclog.setLN((int)(p->p));
		p->bIsFinal = 0;
		gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,"œ◊‘œ“—¿›… ”— …Ã… Œ≈–œÃŒŸ  ÀÃ¿ﬁ ");
		gclog.printfCP(AdvLogger::CD_ALT,"'%s'\n",p->name);
	}

	if (st & INS_CASE)
	{
		gclog.setLN(cln);
		gclog.printfC(AdvLogger::LOG_FATAL, AdvLogger::CD_WIN,"ÕÂ‚ÂÌ˚È Â„ËÒÚ. Œ‰ËÌ ËÁ ÛÁÎÓ‚ ÒÚÓÍË ÓÔÂ‰ÂÎÂÌ ‚ ‰Û„ÓÏ Â„ËÒÚÂ: ");
		gclog.printfCP(AdvLogger::CD_ALT,"'%s'\n",s.chars());
		bWasFatal = 1;
		return;
	}

	if( nInPrefixes >= maxInPrefixes ){
		maxInPrefixes += 100;
		prefixInfo = (ClassesInfo::PrefixInfo *)realloc(prefixInfo,
					sizeof(ClassesInfo::PrefixInfo)*maxInPrefixes);
	}

	s.bDoFree = 0;
	(*(pCI->pm))[s] = nInPrefixes;
	nnew->p = (void*)cln;
	int t=prefixInfo[nInPrefixes].nameLength = ft-fullsrc+1;
	char *p = (char*)malloc(t);
	if (!p) {
		gclog.printfC(AdvLogger::LOG_FATAL, AdvLogger::CD_KOI,
			"≈“≈–œÃŒ≈Œ…≈ –¡Õ—‘….\n");
		bWasFatal = 1;
		return;
	}
	memcpy(p, fullsrc, t);
	prefixInfo[nInPrefixes].prefixName = p;
	prefixInfo[nInPrefixes].prefixType = 0;
	nInPrefixes++;
}

void setPrefixEndOfRest()
{
	FString s(fullsrc, ft - fullsrc);
	FStringSplaySet *a = (FStringSplaySet*)end_of_rest_param;
	if( (*a).contains(s) ){
		gclog.setLN(cln);
		gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,
			"Prefix ");
		gclog.printfCP(AdvLogger::CD_ALT, "'%s'", s.chars());
		gclog.printfCP(AdvLogger::CD_KOI, " ’÷≈ ”’›≈”‘◊’≈‘.\n");
	}else{
		s.bDoFree = 0;
		(*a).add(s);
	}
}

void claSlash()
{
	if( !prepend ){
		// check whether the space available
		if( nInClasses >= maxInClasses ){
			maxInClasses += 10000;
			classInfo = (ClassesInfo::ClassInfo *)realloc(classInfo,
						sizeof(ClassesInfo::ClassInfo)*maxInClasses);
		}
		prepend = '\\';
	}
}
void setPrefixSlash()
{
	if( !prepend ){
		prepend = '\\';
	}
}
void prefixSlash()
{
	if( !prepend ){
		// check whether the space available
		if( nInPrefixes >= maxInPrefixes ){
			maxInPrefixes += 100;
			prefixInfo = (ClassesInfo::PrefixInfo *)realloc(prefixInfo,
						sizeof(ClassesInfo::PrefixInfo)*maxInPrefixes);
		}
		prepend = '\\';
	}
}
void doGetRest()
{
	if( yyleng >= CLASS_KEY_SIZE ){
		gclog.setLN(cln);
		gclog.printfC(errors, AdvLogger::LOG_ERROR, AdvLogger::CD_KOI, "Ú¡⁄ƒ≈Ã ƒÃ…ŒŒ≈≈ %d ”…Õ◊œÃœ◊.\n", CLASS_KEY_SIZE - 1);
		BEGIN(COMMENT);
		return;
	}
	if( ft ){
		if( prepend ){
			*ft++ = prepend;
		}
		strcpy(ft,yytext);
		ft += yyleng;
	}
	if( ts ){
		if( prepend ){
			*ts++=prepend;
		}
		strcpy(ts, yytext+4);
		ts += yyleng-4;
	}
}
FString * ClassesInfo:: pTranslate(FString &key,
	ClassesInfo::TranslateWhat w, int bTheLast)
{
	CaseStringlongSplayMap *m = cm;
	if( w == TRANSPREFIX ) m = pm;

	Pix i = m->nearest(key);
	if( i ){
		long n = m->contents(i);
		char *tptr = 0;
		if( w == TRANSPREFIX ) tptr = pfxInfo[n].prefixName;		
		else tptr = clInfo[n].className;

		char *cptr = (char *) key.chars();
		char *cpPtr, *tpPtr;
		/* FIXIT  - just a trick */
		if( bTheLast && cptr[key.length()-1] == '\\' )
			cptr[key.length()-1]= 0;
		for(;;){
			cpPtr = strchr(cptr,'\\');
			tpPtr = strchr(tptr,'\\');
			if( cpPtr ){
				if( tpPtr ){
					if( ((tpPtr-tptr)-4) == (cpPtr - cptr) ){
						if( str_n_case_cmp(cptr, tptr+4, cpPtr - cptr ) == 0 ){
							cptr = cpPtr+1;
							tptr = tpPtr+1;
						}else{
							goto last_try;
						}
					}else{
						goto last_try;
					}
				}else{
					goto last_try;
				}
			}else{
				// looks like last part
				cpPtr = strchr(cptr,0);
				if( !tpPtr ) tpPtr = strchr(tptr,0);
				if( ((tpPtr-tptr)-4) == (cpPtr - cptr) ){
					if( str_n_case_cmp(cptr, tptr+4, cpPtr - cptr ) == 0 ){
						// got it!
						char *tptr = 0;
						if( w == TRANSPREFIX ) tptr = pfxInfo[n].prefixName;
						else tptr = clInfo[n].className;

						FString *t = new FString(tptr,tpPtr-tptr);
						return t;
					}else{
						goto last_try;
					}
				}else{
					goto last_try;
				}
			}
		}
	}else{
		gclog.printf(AdvLogger::LOG_ERROR,
			"Can't find nearest to '%s'\n", key.chars());
	}
last_try:
	if( bTheLast )
		return 0;
	
	char *buf = (char*)malloc(key.length()+1);
	memcpy(buf,key.chars(),key.length());
	buf[key.length()]='\\';
	FString tkey(buf, key.length()+1 ); tkey.bDoFree =1;
	FString *t = pTranslate(tkey, w, 1);
	free(buf);
	return t;
}

int readClassInfo(ClassesInfo & ci, const char *fn, int print_pfx_ex)
{
#if defined(__CYGWIN32__) || defined(__GO32__) || defined(__MSVC__)
	yyin = mpcxc_fopen( fn, "rb" );
#else
	yyin = mpcxc_fopen( fn, "r" );
#endif
	if( !yyin ){
		gclog.noHdr();
		gclog.printfC(AdvLogger::LOG_ERROR, AdvLogger::CD_KOI,
			"Ó≈ Õœ«’ œ‘À“Ÿ‘ÿ ∆¡ Ã ÀÃ¡””œ◊\n");
		return 1;
	}
	gclog.setFileName( fn );
	print_prefix = print_pfx_ex;
	clsTree = new HNode;
	pfxTree = new HNode;

	fullsrc = (char*)malloc(8192);
	stripsrc = (char*)malloc(8192);
	pCI = &ci;
	ci.cm = new CaseStringlongSplayMap(-1);
	classInfo = 0;
	maxInClasses = nInClasses = 0;

	ci.pm = new CaseStringlongSplayMap(-1);
	prefixInfo = 0;
	maxInPrefixes = nInPrefixes = 0;

	ci.allPrefixes = new CaseStringSplaySet();
	ci.docPrefixes = new CaseStringSplaySet();
	ci.commPrefixes = new CaseStringSplaySet();
	ci.formPrefixes = new CaseStringSplaySet();
	ci.projPrefixes = new CaseStringSplaySet();
	ci.prakPrefixes = new CaseStringSplaySet();
	ci.intePrefixes = new CaseStringSplaySet();
	ci.quesPrefixes = new CaseStringSplaySet();
	ci.brefPrefixes = new CaseStringSplaySet();
	ci.unodes = new CaseStringcaddr_tSplayMap(0);

	cln = 1;
	gclog.setLN(1);
	enableClasses = 1;
	endOfClassesDone = 0;
	enablePrefixes = 1;
	endOfPrefixesDone = 0;
	yylex();
	if (!isClassFlushed) if(end_of_rest) (*end_of_rest)();
	if (!isEQFlushed) finishEQ();

	fclose(yyin);
	free( fullsrc );
	free( stripsrc );
	if( !endOfClassesDone) endOfClasses();
	if( !endOfPrefixesDone) endOfPrefixes();
	setPrefixTypes();

	delete clsTree;
	delete pfxTree;
	if (bWasFatal) exit(1);
	return 0;
}
int checkPartialTranslate(ClassesInfo & ci)
{
	CaseStringlongSplayMap *cm = ci.cm;
	for( Pix i= cm->first(); i; cm->next(i) ){
		FString t = cm->key(i);
		char *tb = strdup(t.chars());
		char *lptr = tb+t.length();
		while( tb < lptr ){
			while( tb < lptr && *lptr != '\\' ) lptr--;
			if( lptr > tb ){
				*lptr = 0;
				FString tp(tb); tp.bDoFree=1;
				FString *ttr = ci.pTranslate(tp,ClassesInfo::TRANSCLASS);
				if( !ttr ){
					gclog.noHdr();
					gclog.printf(AdvLogger::LOG_ERROR,
							"pTranslate: Failed on %s\n", tp.chars());
					return 1;
				}
				ttr->bDoFree = 1;
				delete ttr;
			}
		}
		free(tb);
	}
	return 0;
}
