main.o: main.c ../../../libs/mrglib/src/log.h \
 ../../../libs/mrglib/src/gdbapi.h ../../../libs/mrglib/src/base.h \
 ../../../libs/mrglib/src/mrgdefs.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/mrglib/src/stdindex.h ready.h \
 ../../../include/garver.h
hisync.o: hisync.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ready.h \
 ../../../libs/mrglib/src/log.h
synchind.o: synchind.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 ../../../libs/mrglib/src/log.h
cmdline.o: cmdline.c ../../../libs/mrglib/src/log.h
ready.o: ready.cc ../../../libs/gkdb/src/basemask.h \
 ../../../include/osdep.h
