dbproc.o: dbproc.h topic_t.h ../../../include/osdep.h \
 ../../gkdb/src/gardefs.h
dbproc.mf.o: ../../gkdb/src/deflate.h \
 ../../gkdb/src/zutil.h ../../gkdb/src/zlib.h ../../gkdb/src/zconf.h \
 dbproc.mf.h dbproc.mh.h ../../gkdb/src/gardefs.h \
 ../../../include/osdep.h topic_t.h
gclog.o: gclog.h ../../cchlp/src/advlog.h \
 ../../gkdb/src/gardefs.h ../../../include/osdep.h
unixdummies.o: ../../gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../gkdb/src/garutils.h \
 ../../gkdb/src/collect.h ../../gkdb/src/store.h
