ctxwords.o: ctxwords.cpp ctxwords.h ../../gkdb/src/gardefs.h \
 ../../../include/osdep.h
u_int64_t.CtxLongSet.Map.o: u_int64_t.CtxLongSet.Map.cpp \
 ../../cchlp/src/errhandler.h u_int64_t.CtxLongSet.Map.h \
 ../../cchlp/src/u_int64_t.defs.h ../../../include/osdep.h \
 ctxLongSet.h
u_int64_t.CtxLongSet.SplayMap.o: u_int64_t.CtxLongSet.SplayMap.cpp \
 u_int64_t.CtxLongSet.SplayMap.h u_int64_t.CtxLongSet.Map.h \
 ../../cchlp/src/u_int64_t.defs.h ../../../include/osdep.h \
 ctxLongSet.h
unixdummies.o: unixdummies.cpp ../../gkdb/src/gardefs.h \
 ../../../include/osdep.h
