set PATH_TO_WSCRIPT=%WINDIR%

if "%PROCESSOR_ARCHITECTURE%" == "AMD64" (
	set PATH_TO_WSCRIPT=%PATH_TO_WSCRIPT%\SysWOW64
) else (
	set PATH_TO_WSCRIPT=%PATH_TO_WSCRIPT%\System32
)

set PATH_TO_WSCRIPT=%PATH_TO_WSCRIPT%\wscript.exe