<<VCMViews>> View
 %UID '4ABCFB180302'
 %SUMMARY 'Представление' ;
 %DEPENDS
  U$ '456EA3D2031C' /* GblAdapterLib */
  U$ '4677FF4B0036' /* Data */
  U$ '4680E7D50168' /* "Everest Engine" */
  U$ '4682595B0268' /* l3TreeInterfaces */
  U$ '469F3E37025A' /* Rtl */
  U$ '4790C3B8021E' /* VCM */
  U$ '4790D09A0378' /* L3 */
  U$ '4799D29F033F' /* Implementation */
  U$ '47B9727603BE' /* FormSets */
  U$ '47E9EEC60260' /* Model */
  U$ '493FCF1E03DC' /* Consultation */
  U$ '4954C0500033' /* UserInteraction */
  U$ '499EAAE502A8' /* vcmUserControls */
  U$ '4A78013D01CD' /* "View$For F1 and Monitorings" */
  U$ '4A7960CC03A4' /* " Panels" */
  U$ '4A7C099B004F' /* View */
  U$ '4A92C59801C7' /* View */
  U$ '4A9B9BAA0207' /* Labels */
  U$ '4ABCF16F01CD' /* Consultation$Lib */
  U$ '4AC5DA5A01AD' /* Radio */
  U$ '4C43D64C0168' /* Buttons */
  U$ '4DAF19F600C5' /* tfwScriptingInterfaces */
  U$ '4E13416D0227' /* VCM$Visual */
  U$ '4E2F0E1B03BB' /* L3$Domain */
  U$ '4F3E3F5F0160' /* PrimitiveWords */
  U$ '4F69DF560034' /* ControlsProcessing */
  U$ '54DB92D203C9' /* "VCL bindings" */
  U$ '5527F81C020E' /* TypesRegistration */
  U$ '55BA28CE0290' /* tfwScriptingTypes */
  U$ '55CCADD2013D' /* ClassLikeMapping */
  U$ '561F9F7D02A7' /* ScriptEngine */
 ; // %DEPENDS
 %META
  %upv "exec mode" 'concluded'
  %upv "gui" 'prj'
  %upv "is namespace" true
  %upv "vendor" 'none'
 ; // %META
 %TOBEINCLUDED
  U$ '456EA3D2031C' /* GblAdapterLib */
  U$ '4677FF4B0036' /* Data */
  U$ '467A75D90346' /* VT */
  U$ '4680E7D50168' /* "Everest Engine" */
  U$ '4684F91300DD' /* Vcl */
  U$ '469F3E37025A' /* Rtl */
  U$ '4790C3B8021E' /* VCM */
  U$ '4790D09A0378' /* L3 */
  U$ '47E9EEC60260' /* Model */
  U$ '493FCF1E03DC' /* Consultation */
  U$ '4954C0500033' /* UserInteraction */
  U$ '4A78013D01CD' /* "View$For F1 and Monitorings" */
  U$ '4A7C099B004F' /* View */
  U$ '4A92C59801C7' /* View */
  U$ '4ABCF16F01CD' /* Consultation$Lib */
  U$ '4B63155B0328' /* MDProcess$ForDelphi */
  U$ '4E13416D0227' /* VCM$Visual */
  U$ '4E2F0E1B03BB' /* L3$Domain */
  U$ '547CC9D40158' /* VT$Panels */
  U$ '54CF97B10370' /* ScriptEngine$Core */
  U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
 ; // %TOBEINCLUDED
 %CHILDREN
  
  <<VCMModule>> Consultation
   %UID '4ABCFB650008'
   %SUMMARY 'Консультации' ;
   %DEPENDS
    U$ '457007DB002E' /* Consulting */
    U$ '45EEAA8E034E' /* Search */
    U$ '4682595B0268' /* l3TreeInterfaces */
    U$ '4683F37902CF' /* vcmInterfaces */
    U$ '4728A7020026' /* Types */
    U$ '4767743E00E5' /* TypInfo */
    U$ '4799D29F033F' /* Implementation */
    U$ '47B9727603BE' /* FormSets */
    U$ '47D0E1500033' /* Implementation */
    U$ '47EA07FA02CE' /* bsTypes */
    U$ '48F747EC0073' /* Common */
    U$ '491C3E40007B' /* Consultation */
    U$ '491C3E540050' /* ConsultationInterfaces */
    U$ '4952683C007B' /* Editor */
    U$ '4958E382019E' /* "Search$Presentation for F1 and Monitorings" */
    U$ '499EAAE502A8' /* vcmUserControls */
    U$ '4A7960CC03A4' /* " Panels" */
    U$ '4A7C0BB70162' /* "Base Forms" */
    U$ '4A8AD3C70195' /* Result */
    U$ '4A9B9BAA0207' /* Labels */
    U$ '4AADF9450143' /* Visual */
    U$ '4AB0997B00A2' /* Common */
    U$ '4AB0C3C60310' /* Sys */
    U$ '4ABCF04F00DF' /* ConsultationDomainInterfaces */
    U$ '4ABCF1450282' /* ConsultationDomain */
    U$ '4AC5DA5A01AD' /* Radio */
    U$ '4BD856E802F9' /* FormDefinitions */
    U$ '4BD97FDB031A' /* FormDefinitions */
    U$ '4C43D64C0168' /* Buttons */
    U$ '4DAF19F600C5' /* tfwScriptingInterfaces */
    U$ '4F3E3F5F0160' /* PrimitiveWords */
    U$ '4F69DF560034' /* ControlsProcessing */
    U$ '54DB92D203C9' /* "VCL bindings" */
    U$ '5527F81C020E' /* TypesRegistration */
    U$ '55BA28CE0290' /* tfwScriptingTypes */
    U$ '55CCADD2013D' /* ClassLikeMapping */
    U$ '561F9F7D02A7' /* ScriptEngine */
   ; // %DEPENDS
   %TOBEINCLUDED
    U$ '456EA3D2031C' /* GblAdapterLib */
    U$ '4677FF4B0036' /* Data */
    U$ '467A75D90346' /* VT */
    U$ '4680E7D50168' /* "Everest Engine" */
    U$ '4684F91300DD' /* Vcl */
    U$ '469F3E37025A' /* Rtl */
    U$ '4790C3B8021E' /* VCM */
    U$ '4790D09A0378' /* L3 */
    U$ '47E9EEC60260' /* Model */
    U$ '493FCF1E03DC' /* Consultation */
    U$ '4954C0500033' /* UserInteraction */
    U$ '4A78013D01CD' /* "View$For F1 and Monitorings" */
    U$ '4A7C099B004F' /* View */
    U$ '4A92C59801C7' /* View */
    U$ '4ABCF16F01CD' /* Consultation$Lib */
    U$ '4ABCFB180302' /* View */
    U$ '4B63155B0328' /* MDProcess$ForDelphi */
    U$ '4E13416D0227' /* VCM$Visual */
    U$ '4E2F0E1B03BB' /* L3$Domain */
    U$ '547CC9D40158' /* VT$Panels */
    U$ '54CF97B10370' /* ScriptEngine$Core */
    U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
   ; // %TOBEINCLUDED
   %CHILDREN
    
     <<VCMForm>> PrimConsultationMark
      %UID '497EDC5003D1'
      %SUMMARY 'Оценка консультации' ;
      %META
       %upv "NeedsHackRef" false
       %upv "ZoneType" 'Any'
       %upv "author" 'Люлин А.В.'
       %upv "base wnd class" 'CWnd'
       %upv "finished dfm" true
       %upv "needs InstanceR" 'undefined'
       %upv "needs script" 'undefined'
       %upv "no hands" true
       %upv "register in scripts" 'undefined'
       %upv "resizeable" false
       %upv "restrict form def" 'undefined'
       %upv "started" '27.01.2009 13:06'
      ; // %META
      %TOBEINCLUDED
       U$ '467A75D90346' /* VT */
       U$ '4680E7D50168' /* "Everest Engine" */
       U$ '469F3E37025A' /* Rtl */
       U$ '4790C3B8021E' /* VCM */
       U$ '4790D09A0378' /* L3 */
       U$ '47E9EEC60260' /* Model */
       U$ '4ABCF16F01CD' /* Consultation$Lib */
       U$ '4E13416D0227' /* VCM$Visual */
       U$ '547CC9D40158' /* VT$Panels */
       U$ '54CF97B10370' /* ScriptEngine$Core */
      ; // %TOBEINCLUDED
      %INHERITS
       U$ '49525B34022A' /* TvcmEntityForm */
      ; // %INHERITS
      %OVERRIDES
       U$ '4A8E8F2E0195' /* InitControls */
      ; // %OVERRIDES
      %LINKS
        <<uses>> "5176B853011C"
         %UID '5176B853011C'
         %TARGET U$ '4921639C00DB' /* TbsConsultationMark */
        ; // 5176B853011C
        <<uses>> "5176C0960324"
         %UID '5176C0960324'
         %TARGET U$ '47E13C6B0341' /* Forms */
        ; // 5176C0960324
        <<uses>> "5176C09B0245"
         %UID '5176C09B0245'
         %TARGET U$ '47E11FC3021E' /* Controls */
        ; // 5176C09B0245
        <<uses>> "5177CF2C02F3"
         %UID '5177CF2C02F3'
         %TARGET U$ '4728A7190065' /* TRect */
        ; // 5177CF2C02F3
        SUMMONED <<uses>> "56263E97FB0A"
         %UID '56263E97FB0A'
         %TARGET U$ '4B3B3728004C' /* Tl3StringIDEx */
        ; // 56263E97FB0A
        SUMMONED <<uses>> "DD790BF65603"
         %UID 'DD790BF65603'
         %TARGET U$ '4E01D1E002AE' /* Tl3MessageID */
        ; // DD790BF65603
        SUMMONED <<uses>> "A40622A91F66"
         %UID 'A40622A91F66'
         %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
        ; // A40622A91F66
      ; // %LINKS
      %ATTRIBUTES
        PROTECTED FINAL LINK <<ViewArea>> DSMark
         %UID '497EDCDC0187'
         %SUMMARY 'Оценка консультации' ;
         %TARGET U$ '492164C302A6' /* IdsConsultationMark */
         %TOBEINCLUDED
          U$ '4ABCF16F01CD' /* Consultation$Lib */
         ; // %TOBEINCLUDED
        ; // DSMark
        SUMMONED PRIVATE <<Attribute>> f_gbMark
         %UID '9B584B7A9770'
         %SUMMARY 'Поле для свойства gbMark' ;
         %TARGET U$ '4AC608E40294' /* TvtGroupBox */
         %TOBEINCLUDED
          U$ '467A75D90346' /* VT */
         ; // %TOBEINCLUDED
        ; // f_gbMark
        SUMMONED PRIVATE <<Attribute>> f_rbNotSure
         %UID '8CA27A49624D'
         %SUMMARY 'Поле для свойства rbNotSure' ;
         %TARGET U$ '517941E500BF' /* TvtRadioButton */
         %TOBEINCLUDED
          U$ '467A75D90346' /* VT */
         ; // %TOBEINCLUDED
        ; // f_rbNotSure
        SUMMONED PRIVATE <<Attribute>> f_rbTwo
         %UID '5F208E3FE79C'
         %SUMMARY 'Поле для свойства rbTwo' ;
         %TARGET U$ '517941E500BF' /* TvtRadioButton */
         %TOBEINCLUDED
          U$ '467A75D90346' /* VT */
         ; // %TOBEINCLUDED
        ; // f_rbTwo
        SUMMONED PRIVATE <<Attribute>> f_rbThree
         %UID 'A4988A11DA2C'
         %SUMMARY 'Поле для свойства rbThree' ;
         %TARGET U$ '517941E500BF' /* TvtRadioButton */
         %TOBEINCLUDED
          U$ '467A75D90346' /* VT */
         ; // %TOBEINCLUDED
        ; // f_rbThree
        SUMMONED PRIVATE <<Attribute>> f_rbFour
         %UID '3174483A6668'
         %SUMMARY 'Поле для свойства rbFour' ;
         %TARGET U$ '517941E500BF' /* TvtRadioButton */
         %TOBEINCLUDED
          U$ '467A75D90346' /* VT */
         ; // %TOBEINCLUDED
        ; // f_rbFour
        SUMMONED PRIVATE <<Attribute>> f_rbFive
         %UID 'BECDC8D06AFC'
         %SUMMARY 'Поле для свойства rbFive' ;
         %TARGET U$ '517941E500BF' /* TvtRadioButton */
         %TOBEINCLUDED
          U$ '467A75D90346' /* VT */
         ; // %TOBEINCLUDED
        ; // f_rbFive
        SUMMONED PRIVATE <<Attribute>> f_pnlHelp
         %UID 'EB2ECCDA10B7'
         %SUMMARY 'Поле для свойства pnlHelp' ;
         %TARGET U$ '4A7961A701CF' /* TvtPanel */
         %TOBEINCLUDED
          U$ '547CC9D40158' /* VT$Panels */
         ; // %TOBEINCLUDED
        ; // f_pnlHelp
        SUMMONED PRIVATE <<Attribute>> f_lblHelp
         %UID '451B9CDEAA66'
         %SUMMARY 'Поле для свойства lblHelp' ;
         %TARGET U$ '4AE8541A01AE' /* TvtLabel */
         %TOBEINCLUDED
          U$ '467A75D90346' /* VT */
         ; // %TOBEINCLUDED
        ; // f_lblHelp
        SUMMONED PRIVATE <<Attribute>> f_gbComment
         %UID '6ECDBF6EE1DB'
         %SUMMARY 'Поле для свойства gbComment' ;
         %TARGET U$ '4AC608E40294' /* TvtGroupBox */
         %TOBEINCLUDED
          U$ '467A75D90346' /* VT */
         ; // %TOBEINCLUDED
        ; // f_gbComment
        SUMMONED PRIVATE <<Attribute>> f_mComment
         %UID '769ADAF00F70'
         %SUMMARY 'Поле для свойства mComment' ;
         %TARGET U$ '4AC5D3380185' /* TeeMemoWithEditOperations */
         %TOBEINCLUDED
          U$ '4680E7D50168' /* "Everest Engine" */
         ; // %TOBEINCLUDED
        ; // f_mComment
      ; // %ATTRIBUTES
      %OPERATIONS
        PRIVATE FINAL <<method>> rbNotSureClick
         %UID '5176B3D003B4'
         %TOBEINCLUDED
          U$ '469F3E37025A' /* Rtl */
         ; // %TOBEINCLUDED
         %INHERITS
          U$ '47881B22005A' /* TNotifyEvent */
         ; // %INHERITS
         %OPERATIONS
           SUMMONED PRIVATE FINAL <<Operation>> DoIt
            %UID '822D0984209A'
            %SUMMARY 'TNotifyEvent is used for events that do not require parameters.' ;
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
            ; // %TOBEINCLUDED
            %PARAMETERS
              SUMMONED <<in>> Sender
               %UID '5A6E229C5EFE'
               %TARGET U$ '4807745602C8' /* TObject */
               %TOBEINCLUDED
                U$ '469F3E37025A' /* Rtl */
               ; // %TOBEINCLUDED
              ; // Sender
            ; // %PARAMETERS
           ; // DoIt
         ; // %OPERATIONS
        ; // rbNotSureClick
        PRIVATE FINAL <<method>> rbFiveClick
         %UID '5176B3E200C1'
         %TOBEINCLUDED
          U$ '469F3E37025A' /* Rtl */
         ; // %TOBEINCLUDED
         %INHERITS
          U$ '47881B22005A' /* TNotifyEvent */
         ; // %INHERITS
         %OPERATIONS
           SUMMONED PRIVATE FINAL <<Operation>> DoIt
            %UID '39975A0D08DA'
            %SUMMARY 'TNotifyEvent is used for events that do not require parameters.' ;
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
            ; // %TOBEINCLUDED
            %PARAMETERS
              SUMMONED <<in>> Sender
               %UID '64C49C848A34'
               %TARGET U$ '4807745602C8' /* TObject */
               %TOBEINCLUDED
                U$ '469F3E37025A' /* Rtl */
               ; // %TOBEINCLUDED
              ; // Sender
            ; // %PARAMETERS
           ; // DoIt
         ; // %OPERATIONS
        ; // rbFiveClick
        PRIVATE FINAL <<method>> rbFourClick
         %UID '5176B3F200F4'
         %TOBEINCLUDED
          U$ '469F3E37025A' /* Rtl */
         ; // %TOBEINCLUDED
         %INHERITS
          U$ '47881B22005A' /* TNotifyEvent */
         ; // %INHERITS
         %OPERATIONS
           SUMMONED PRIVATE FINAL <<Operation>> DoIt
            %UID '958B0E1E071E'
            %SUMMARY 'TNotifyEvent is used for events that do not require parameters.' ;
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
            ; // %TOBEINCLUDED
            %PARAMETERS
              SUMMONED <<in>> Sender
               %UID '0943906FF61A'
               %TARGET U$ '4807745602C8' /* TObject */
               %TOBEINCLUDED
                U$ '469F3E37025A' /* Rtl */
               ; // %TOBEINCLUDED
              ; // Sender
            ; // %PARAMETERS
           ; // DoIt
         ; // %OPERATIONS
        ; // rbFourClick
        PRIVATE FINAL <<method>> rbThreeClick
         %UID '5176B3FD0292'
         %TOBEINCLUDED
          U$ '469F3E37025A' /* Rtl */
         ; // %TOBEINCLUDED
         %INHERITS
          U$ '47881B22005A' /* TNotifyEvent */
         ; // %INHERITS
         %OPERATIONS
           SUMMONED PRIVATE FINAL <<Operation>> DoIt
            %UID '0A7E07833558'
            %SUMMARY 'TNotifyEvent is used for events that do not require parameters.' ;
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
            ; // %TOBEINCLUDED
            %PARAMETERS
              SUMMONED <<in>> Sender
               %UID '1378654FEC7A'
               %TARGET U$ '4807745602C8' /* TObject */
               %TOBEINCLUDED
                U$ '469F3E37025A' /* Rtl */
               ; // %TOBEINCLUDED
              ; // Sender
            ; // %PARAMETERS
           ; // DoIt
         ; // %OPERATIONS
        ; // rbThreeClick
        PRIVATE FINAL <<method>> rbTwoClick
         %UID '5176B4060002'
         %TOBEINCLUDED
          U$ '469F3E37025A' /* Rtl */
         ; // %TOBEINCLUDED
         %INHERITS
          U$ '47881B22005A' /* TNotifyEvent */
         ; // %INHERITS
         %OPERATIONS
           SUMMONED PRIVATE FINAL <<Operation>> DoIt
            %UID '2C352849352E'
            %SUMMARY 'TNotifyEvent is used for events that do not require parameters.' ;
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
            ; // %TOBEINCLUDED
            %PARAMETERS
              SUMMONED <<in>> Sender
               %UID '1210BC5189CF'
               %TARGET U$ '4807745602C8' /* TObject */
               %TOBEINCLUDED
                U$ '469F3E37025A' /* Rtl */
               ; // %TOBEINCLUDED
              ; // Sender
            ; // %PARAMETERS
           ; // DoIt
         ; // %OPERATIONS
        ; // rbTwoClick
        PRIVATE FINAL <<method>> PlaceComponents
         %UID '5176B4200040'
         %OPERATIONS
           SUMMONED FINAL <<Operation>> DoIt
            %UID 'B2E74E0A154C'
            %SUMMARY 'Сигнатура метода PlaceComponents' ;
           ; // DoIt
         ; // %OPERATIONS
        ; // PlaceComponents
        PRIVATE FINAL <<method>> ChangeMark
         %UID '5176B42C0279'
         %TOBEINCLUDED
          U$ '47E9EEC60260' /* Model */
         ; // %TOBEINCLUDED
         %OPERATIONS
           PRIVATE FINAL <<Operation>> DoIt
            %UID '5176B43D033E'
            %TOBEINCLUDED
             U$ '47E9EEC60260' /* Model */
            ; // %TOBEINCLUDED
            %PARAMETERS
              <<in>> aMark
               %UID '5176B44200DF'
               %TARGET U$ '4921639C00DB' /* TbsConsultationMark */
               %TOBEINCLUDED
                U$ '47E9EEC60260' /* Model */
               ; // %TOBEINCLUDED
              ; // aMark
            ; // %PARAMETERS
           ; // DoIt
         ; // %OPERATIONS
        ; // ChangeMark
        SUMMONED PRIVATE FINAL <<ini>> Init_utcmMainCaption
         %UID '96D2C8FD3FC0'
         %SUMMARY 'Инициализация str_utcmMainCaption' ;
        ; // Init_utcmMainCaption
        SUMMONED PRIVATE FINAL <<ini>> Ini_Reg_Class
         %UID '8CD38BF7966D'
         %SUMMARY 'Регистрация PrimConsultationMark' ;
         %META
          %upv "ifndef" 'NoScripts'
         ; // %META
        ; // Ini_Reg_Class
      ; // %OPERATIONS
      %CHILDREN
       
        <<Constants>> Constants
         %UID '4C84E4AC0171'
         %META
          %upv "spell names" false
         ; // %META
         %ATTRIBUTES
           <<Attribute>> c_TextCommentLen
            %UID '4C84E4B70371'
            %VALUE 6000
            %META
             %upv "AutoInc" false
             %upv "forced type" 'none'
             %upv "is define" false
            ; // %META
           ; // c_TextCommentLen
         ; // %ATTRIBUTES
        ; // Constants
        FINAL <<UserType>> utcmMain
         %UID '4CD142B70232'
         %SUMMARY 'Оценка ответа' ;
         %META
          %upv "CanClose" 'undefined'
          %upv "CanHaveToolbars" 'undefined'
          %upv "ImageIndex" '-1'
          %upv "NeedOnQueryClose" false
          %upv "NeedOnQueryMaximized" false
          %upv "NeedOnQueryOpen" false
          %upv "VisibleToUser" false
          %upv "Weight" '-1'
         ; // %META
         %TOBEINCLUDED
          U$ '4790C3B8021E' /* VCM */
          U$ '54CF97B10370' /* ScriptEngine$Core */
         ; // %TOBEINCLUDED
         %CHILDREN
          
           SUMMONED <<Constants>> utcmMainConstants
            %UID '6AF16D1D6654'
            %SUMMARY 'Константы для типа формы utcmMain' ;
            %META
             %upv "spell names" false
            ; // %META
            %TOBEINCLUDED
             U$ '4790C3B8021E' /* VCM */
            ; // %TOBEINCLUDED
            %ATTRIBUTES
              SUMMONED <<Attribute>> utcmMainName
               %UID '3166DCF164E4'
               %SUMMARY 'Строковый идентификатор пользовательского типа "Оценка ответа"' ;
               %VALUE '''utcmMain'''
               %META
                %upv "AutoInc" false
                %upv "forced type" 'none'
                %upv "is define" false
               ; // %META
              ; // utcmMainName
              SUMMONED <<Attribute>> utcmMain
               %UID 'A25DB5826EC4'
               %SUMMARY 'Оценка ответа' ;
               %TARGET U$ '47F2534B010F' /* TvcmUserType */
               %VALUE 0
               %META
                %upv "AutoInc" false
                %upv "forced type" 'none'
                %upv "is define" true
               ; // %META
               %TOBEINCLUDED
                U$ '4790C3B8021E' /* VCM */
               ; // %TOBEINCLUDED
              ; // utcmMain
            ; // %ATTRIBUTES
           ; // utcmMainConstants
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_FormUserType_utcmMain"
            %UID 'A4A4295DF23B'
            %SUMMARY 'Слово словаря для типа формы utcmMain' ;
            %META
             %upv "NameForScript" 'тип_формы::utcmMain'
             %upv "ifndef" 'NoScripts'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54CF97B10370' /* ScriptEngine$Core */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4EE1DBBB013C' /* TtfwInteger */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '4EE1DC8903BB' /* GetInteger */
            ; // %OVERRIDES
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '6AEB6C22A37D'
               %SUMMARY 'Регистрация Tkw_FormUserType_utcmMain' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_FormUserType_utcmMain"
         ; // %CHILDREN
        ; // utcmMain
        FINAL <<Control>> gbMark
         %UID '517692CD0370'
         %SUMMARY 'Оценка:' ;
         %META
          %upv "ControlClass" 'TvtGroupBox'
          %upv "need Caption" 'undefined'
          %upv "pm" true
          %upv "put to dfm" false
         ; // %META
         %TOBEINCLUDED
          U$ '467A75D90346' /* VT */
         ; // %TOBEINCLUDED
         %INHERITS
          U$ '4AC608E40294' /* TvtGroupBox */
         ; // %INHERITS
         %CHILDREN
          
           FINAL <<Control>> rbNotSure
            %UID '517696060243'
            %SUMMARY 'Затрудняюсь ответить (оценка 0)' ;
            %META
             %upv "ControlClass" 'TvtRadioButton'
             %upv "need Caption" 'undefined'
             %upv "pm" true
             %upv "put to dfm" false
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '517941E500BF' /* TvtRadioButton */
            ; // %INHERITS
           ; // rbNotSure
           FINAL <<Control>> rbTwo
            %UID '5176964E0305'
            %SUMMARY 'Плохо (оценка 2)' ;
            %META
             %upv "ControlClass" 'TvtRadioButton'
             %upv "need Caption" 'undefined'
             %upv "pm" true
             %upv "put to dfm" false
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '517941E500BF' /* TvtRadioButton */
            ; // %INHERITS
           ; // rbTwo
           FINAL <<Control>> rbThree
            %UID '517696700205'
            %SUMMARY 'Удовлетворительно (оценка 3)' ;
            %META
             %upv "ControlClass" 'TvtRadioButton'
             %upv "need Caption" 'undefined'
             %upv "pm" true
             %upv "put to dfm" false
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '517941E500BF' /* TvtRadioButton */
            ; // %INHERITS
           ; // rbThree
           FINAL <<Control>> rbFour
            %UID '517696B3017A'
            %SUMMARY 'Хорошо (оценка 4)' ;
            %META
             %upv "ControlClass" 'TvtRadioButton'
             %upv "need Caption" 'undefined'
             %upv "pm" true
             %upv "put to dfm" false
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '517941E500BF' /* TvtRadioButton */
            ; // %INHERITS
           ; // rbFour
           FINAL <<Control>> rbFive
            %UID '517696E600B2'
            %SUMMARY 'Отлично (оценка 5)' ;
            %META
             %upv "ControlClass" 'TvtRadioButton'
             %upv "need Caption" 'undefined'
             %upv "pm" true
             %upv "put to dfm" false
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '517941E500BF' /* TvtRadioButton */
            ; // %INHERITS
           ; // rbFive
         ; // %CHILDREN
        ; // gbMark
        FINAL <<Control>> pnlHelp
         %UID '51769718021E'
         %META
          %upv "ControlClass" 'TvtPanel'
          %upv "need Caption" 'undefined'
          %upv "pm" true
          %upv "put to dfm" false
         ; // %META
         %TOBEINCLUDED
          U$ '467A75D90346' /* VT */
          U$ '547CC9D40158' /* VT$Panels */
         ; // %TOBEINCLUDED
         %INHERITS
          U$ '4A7961A701CF' /* TvtPanel */
         ; // %INHERITS
         %CHILDREN
          
           FINAL <<Control>> lblHelp
            %UID '51769756011F'
            %SUMMARY 'Данное окно предназначено для внесения комментария к оценке представленной консультации. Если Вам необходимы дополнительные  разъяснения по сути предоставленного ответа, просьба внести отдельный запрос в карточку запроса «Правовая поддержка онлайн».' ;
            %META
             %upv "ControlClass" 'TvtLabel'
             %upv "need Caption" 'undefined'
             %upv "pm" true
             %upv "put to dfm" false
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4AE8541A01AE' /* TvtLabel */
            ; // %INHERITS
           ; // lblHelp
         ; // %CHILDREN
        ; // pnlHelp
        FINAL <<Control>> gbComment
         %UID '5176979B0055'
         %SUMMARY 'Комментарий к Вашей оценке:' ;
         %META
          %upv "ControlClass" 'TvtGroupBox'
          %upv "need Caption" 'undefined'
          %upv "pm" true
          %upv "put to dfm" false
         ; // %META
         %TOBEINCLUDED
          U$ '467A75D90346' /* VT */
          U$ '4680E7D50168' /* "Everest Engine" */
         ; // %TOBEINCLUDED
         %INHERITS
          U$ '4AC608E40294' /* TvtGroupBox */
         ; // %INHERITS
         %CHILDREN
          
           FINAL <<Control>> mComment
            %UID '4C84E44B0065'
            %META
             %upv "ControlClass" 'TeeMemoWithEditOperations'
             %upv "need Caption" 'undefined'
             %upv "pm" true
             %upv "put to dfm" false
            ; // %META
            %TOBEINCLUDED
             U$ '4680E7D50168' /* "Everest Engine" */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4AC5D3380185' /* TeeMemoWithEditOperations */
            ; // %INHERITS
           ; // mComment
         ; // %CHILDREN
        ; // gbComment
        SUMMONED PRIVATE FINAL <<LocalConst>> utcmMainLocalConstants
         %UID 'DB277B3A75DD'
         %SUMMARY 'Локализуемые константы для типа формы utcmMain' ;
         %META
          %upv "Need map interface" false
          %upv "Need mapping support" false
          %upv "spell names" false
         ; // %META
         %ATTRIBUTES
           SUMMONED <<Attribute>> utcmMainCaption
            %UID '58313837B609'
            %SUMMARY 'Заголовок пользовательского типа "Оценка ответа"' ;
            %VALUE '''Оценка ответа'''
            %META
             %upv "AutoInc" false
             %upv "forced type" 'none'
             %upv "is define" false
            ; // %META
           ; // utcmMainCaption
         ; // %ATTRIBUTES
        ; // utcmMainLocalConstants
        SUMMONED PRIVATE <<Constants>> LCImplutcmMainLocalConstants
         %UID 'CB03B1AA38F6'
         %SUMMARY 'Локализуемые строки utcmMainLocalConstants' ;
         %META
          %upv "elements prefix" 'str'
          %upv "spell names" false
         ; // %META
         %TOBEINCLUDED
          U$ '4790D09A0378' /* L3 */
         ; // %TOBEINCLUDED
         %ATTRIBUTES
           SUMMONED <<Attribute>> utcmMainCaption
            %UID '846E56D67F4B'
            %SUMMARY 'Заголовок пользовательского типа "Оценка ответа"' ;
            %TARGET U$ '4B3B3728004C' /* Tl3StringIDEx */
            %VALUE '(rS : -1; rLocalized : false; rKey : ''utcmMainCaption''; rValue : ''Оценка ответа'')'
            %META
             %upv "AutoInc" false
             %upv "forced type" 'none'
             %upv "is define" false
            ; // %META
            %TOBEINCLUDED
             U$ '4790D09A0378' /* L3 */
            ; // %TOBEINCLUDED
           ; // utcmMainCaption
         ; // %ATTRIBUTES
        ; // LCImplutcmMainLocalConstants
      ; // %CHILDREN
     ; // PrimConsultationMark
     <<VCMForm>> PrimConsultationMarkOptions
      %UID '4C84E097023A'
      %SUMMARY 'Оценка ответа' ;
      %META
       %upv "NeedsHackRef" true
       %upv "ZoneType" 'Any'
       %upv "author" 'Люлин А.В.'
       %upv "base wnd class" 'CWnd'
       %upv "finished dfm" true
       %upv "needs InstanceR" 'undefined'
       %upv "needs script" 'undefined'
       %upv "no hands" true
       %upv "register in scripts" 'undefined'
       %upv "resizeable" false
       %upv "restrict form def" 'undefined'
       %upv "started" '06.09.2010 16:38'
      ; // %META
      %TOBEINCLUDED
       U$ '4954C0500033' /* UserInteraction */
       U$ '4ABCFB180302' /* View */
      ; // %TOBEINCLUDED
      %IMPLEMENTS
       U$ '4A8AD409003A' /* Result$Cancel */
       U$ '4A97EBC80201' /* Result$Ok */
      ; // %IMPLEMENTS
      %INHERITS
       U$ '497EDC5003D1' /* PrimConsultationMark */
      ; // %INHERITS
      %REALIZES
       U$ '4C762A1501FC' /* Ok */
       U$ '4C762AB601E1' /* Cancel */
      ; // %REALIZES
      %LINKS
        <<uses>> "4C84E22801A2"
         %UID '4C84E22801A2'
         %TARGET U$ '4A980B37006B' /* ModalResults */
        ; // 4C84E22801A2
        <<uses>> "4C84E4E803BF"
         %UID '4C84E4E803BF'
         %TARGET U$ '4570098B0159' /* NoConnection */
        ; // 4C84E4E803BF
        <<uses>> "4C84E4FF039A"
         %UID '4C84E4FF039A'
         %TARGET U$ '4570098B015B' /* NoSubscription */
        ; // 4C84E4FF039A
        <<uses>> "4C84E52002B7"
         %UID '4C84E52002B7'
         %TARGET U$ '4B1E8FAE0380' /* DefDataAdapter$4B1E8FAE0380 */
        ; // 4C84E52002B7
        <<ToolbarAtBottom>> "5177CFB00365"
         %UID '5177CFB00365'
         %TARGET U$ '4A97EBC80201' /* Result$Ok */
        ; // 5177CFB00365
        SUMMONED <<uses>> "ED473FD07F05"
         %UID 'ED473FD07F05'
         %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
        ; // ED473FD07F05
      ; // %LINKS
      %OPERATIONS
        SUMMONED PRIVATE FINAL <<ini>> Ini_Reg_Class
         %UID '5F076A1BF650'
         %SUMMARY 'Регистрация PrimConsultationMarkOptions' ;
         %META
          %upv "ifndef" 'NoScripts'
         ; // %META
        ; // Ini_Reg_Class
      ; // %OPERATIONS
     ; // PrimConsultationMarkOptions
     <<VCMFormsPack>> Consultation$FP
      %UID '4ABCFB7F017B'
      %SUMMARY 'Консультации' ;
      %META
       %upv "author" 'Люлин А.В.'
       %upv "needs InstanceR" 'undefined'
       %upv "needs script" 'undefined'
       %upv "no hands" true
       %upv "register in scripts" 'undefined'
       %upv "started" '25.09.2009 21:19'
      ; // %META
      %TOBEINCLUDED
       U$ '456EA3D2031C' /* GblAdapterLib */
       U$ '467A75D90346' /* VT */
       U$ '4680E7D50168' /* "Everest Engine" */
       U$ '469F3E37025A' /* Rtl */
       U$ '4790C3B8021E' /* VCM */
       U$ '4790D09A0378' /* L3 */
       U$ '493FCF1E03DC' /* Consultation */
       U$ '4A78013D01CD' /* "View$For F1 and Monitorings" */
       U$ '4A7C099B004F' /* View */
       U$ '4A92C59801C7' /* View */
       U$ '4ABCF16F01CD' /* Consultation$Lib */
       U$ '4ABCFB180302' /* View */
       U$ '4E13416D0227' /* VCM$Visual */
       U$ '4E2F0E1B03BB' /* L3$Domain */
       U$ '547CC9D40158' /* VT$Panels */
       U$ '54CF97B10370' /* ScriptEngine$Core */
       U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
      ; // %TOBEINCLUDED
      %LINKS
        <<uses>> "4BD1F02E0221"
         %UID '4BD1F02E0221'
         %TARGET U$ '4B040F540027' /* dftConsultation */
        ; // 4BD1F02E0221
        <<uses>> "4BD97948027F"
         %UID '4BD97948027F'
         %TARGET U$ '4BD8574A03A5' /* Text */
        ; // 4BD97948027F
        SUMMONED <<uses>> "5997B82EED64"
         %UID '5997B82EED64'
         %TARGET U$ '47F25BC801DB' /* vcmBase */
        ; // 5997B82EED64
      ; // %LINKS
      %OPERATIONS
        FINAL <<FactoryMethod>> GiveMarkOnConsultation
         %UID '4ABBA1BF0053'
         %TOBEINCLUDED
          U$ '4790C3B8021E' /* VCM */
          U$ '4ABCF16F01CD' /* Consultation$Lib */
          U$ '4E2F0E1B03BB' /* L3$Domain */
         ; // %TOBEINCLUDED
         %LINKS
           <<uses>> "4ABBA356006F"
            %UID '4ABBA356006F'
            %TARGET U$ '47877EB202FB' /* SysUtils */
           ; // 4ABBA356006F
           <<uses>> "4ABBA36A0055"
            %UID '4ABBA36A0055'
            %TARGET U$ '4A93BA1802CE' /* vcmParams */
           ; // 4ABBA36A0055
           <<uses>> "4ABCED270359"
            %UID '4ABCED270359'
            %TARGET U$ '49228CA903BA' /* TsdsConsultation */
           ; // 4ABCED270359
           <<uses>> "4ABCED4C028E"
            %UID '4ABCED4C028E'
            %TARGET U$ '49228BA50210' /* TbsConsultation */
           ; // 4ABCED4C028E
           <<uses>> "4ABCED81008D"
            %UID '4ABCED81008D'
            %TARGET U$ '4ABCED74003A' /* bsGetConsultation */
           ; // 4ABCED81008D
         ; // %LINKS
         %ATTRIBUTES
           PRIVATE FINAL <<var>> OpenConsultation
            %UID '4ABBA3250040'
            %TARGET U$ '4921732002D9' /* IsdsConsultation */
            %META
             %upv "IsResult" false
            ; // %META
            %TOBEINCLUDED
             U$ '4ABCF16F01CD' /* Consultation$Lib */
            ; // %TOBEINCLUDED
           ; // OpenConsultation
           PRIVATE FINAL <<var>> Form
            %UID '4ABBA33A0070'
            %TARGET U$ '4914746C019E' /* IvcmEntityForm */
            %META
             %upv "IsResult" false
            ; // %META
            %TOBEINCLUDED
             U$ '4790C3B8021E' /* VCM */
            ; // %TOBEINCLUDED
           ; // Form
           PRIVATE FINAL <<var>> Cons
            %UID '4ABCECF30196'
            %TARGET U$ '4921732002D9' /* IsdsConsultation */
            %META
             %upv "IsResult" false
            ; // %META
            %TOBEINCLUDED
             U$ '4ABCF16F01CD' /* Consultation$Lib */
            ; // %TOBEINCLUDED
           ; // Cons
         ; // %ATTRIBUTES
         %OPERATIONS
           PRIVATE FINAL <<Operation>> DoIt
            %UID '4ABBA1D6029B'
            %TOBEINCLUDED
             U$ '4E2F0E1B03BB' /* L3$Domain */
            ; // %TOBEINCLUDED
            %PARAMETERS
              <<in>> aNode
               %UID '4ABCECDA01B6'
               %TARGET U$ '468259900322' /* Il3SimpleNode */
               %TOBEINCLUDED
                U$ '4E2F0E1B03BB' /* L3$Domain */
               ; // %TOBEINCLUDED
              ; // aNode
            ; // %PARAMETERS
           ; // DoIt
         ; // %OPERATIONS
        ; // GiveMarkOnConsultation
        FINAL <<FormSetFactory>> OpenSendConsultation
         %UID '4AA53DF902C5'
         %TOBEINCLUDED
          U$ '456EA3D2031C' /* GblAdapterLib */
         ; // %TOBEINCLUDED
         %LINKS
           <<uses>> "4AA5403A0125"
            %UID '4AA5403A0125'
            %TARGET U$ '492FF1C500B5' /* TsdsSendConsultation */
           ; // 4AA5403A0125
           <<uses>> "4AA5418301FF"
            %UID '4AA5418301FF'
            %TARGET U$ '4A9D129E00FA' /* Say$4A9D129E00FA */
           ; // 4AA5418301FF
           <<uses>> "4AA5437F038E"
            %UID '4AA5437F038E'
            %TARGET U$ '48FF556602BA' /* DataAdapter */
           ; // 4AA5437F038E
         ; // %LINKS
         %OPERATIONS
           PRIVATE FINAL <<Operation>> DoIt
            %UID '4AA53E2E01B1'
            %TOBEINCLUDED
             U$ '456EA3D2031C' /* GblAdapterLib */
            ; // %TOBEINCLUDED
            %PARAMETERS
              <<in>> aQuery
               %UID '4AA53E3201B3'
               %TARGET U$ '45EEE145027B' /* Query */
               %TOBEINCLUDED
                U$ '456EA3D2031C' /* GblAdapterLib */
               ; // %TOBEINCLUDED
              ; // aQuery
            ; // %PARAMETERS
           ; // DoIt
         ; // %OPERATIONS
        ; // OpenSendConsultation
        FINAL <<FormSetFactory>> OpenEntityAsConsultation
         %UID '4AA5385C03DD'
         %TOBEINCLUDED
          U$ '456EA3D2031C' /* GblAdapterLib */
          U$ '469F3E37025A' /* Rtl */
          U$ '4790C3B8021E' /* VCM */
         ; // %TOBEINCLUDED
         %LINKS
           <<uses>> "4AA53AF5028D"
            %UID '4AA53AF5028D'
            %TARGET U$ '46286C980119' /* OldFormatConsultation */
           ; // 4AA53AF5028D
           <<uses>> "4AA53B18024C"
            %UID '4AA53B18024C'
            %TARGET U$ '49228BA50210' /* TbsConsultation */
           ; // 4AA53B18024C
           <<uses>> "4AA53B3C02A0"
            %UID '4AA53B3C02A0'
            %TARGET U$ '4A9D129E00FA' /* Say$4A9D129E00FA */
           ; // 4AA53B3C02A0
         ; // %LINKS
         %ATTRIBUTES
           PRIVATE FINAL <<var>> Cons
            %UID '4AA539F30206'
            %TARGET U$ '457008050157' /* Consultation */
            %META
             %upv "IsResult" false
            ; // %META
            %TOBEINCLUDED
             U$ '456EA3D2031C' /* GblAdapterLib */
            ; // %TOBEINCLUDED
           ; // Cons
         ; // %ATTRIBUTES
         %OPERATIONS
           PRIVATE FINAL <<Operation>> DoIt
            %UID '4AA5389200C7'
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
             U$ '4790C3B8021E' /* VCM */
            ; // %TOBEINCLUDED
            %PARAMETERS
              <<in>> aCons
               %UID '4AA5389C00C5'
               %TARGET U$ '46A451250363' /* IUnknown */
               %TOBEINCLUDED
                U$ '469F3E37025A' /* Rtl */
               ; // %TOBEINCLUDED
              ; // aCons
              <<in>> aContainer
               %UID '4AA538FD0167'
               %TARGET U$ '49525C400141' /* IvcmContainer */
               %TOBEINCLUDED
                U$ '4790C3B8021E' /* VCM */
               ; // %TOBEINCLUDED
              ; // aContainer
            ; // %PARAMETERS
           ; // DoIt
         ; // %OPERATIONS
        ; // OpenEntityAsConsultation
        FINAL <<FormSetFactory>> OpenConsultation
         %UID '4AA5363D02D0'
         %TOBEINCLUDED
          U$ '4790C3B8021E' /* VCM */
          U$ '4ABCF16F01CD' /* Consultation$Lib */
         ; // %TOBEINCLUDED
         %LINKS
           <<uses>> "4AA5367D001F"
            %UID '4AA5367D001F'
            %TARGET U$ '49228CA903BA' /* TsdsConsultation */
           ; // 4AA5367D001F
         ; // %LINKS
         %OPERATIONS
           PRIVATE FINAL <<Operation>> DoIt
            %UID '4AA5366502A4'
            %TOBEINCLUDED
             U$ '4790C3B8021E' /* VCM */
             U$ '4ABCF16F01CD' /* Consultation$Lib */
            ; // %TOBEINCLUDED
            %PARAMETERS
              <<in>> aCons
               %UID '4AA5366A0061'
               %TARGET U$ '491C422A0003' /* IbsConsultation */
               %TOBEINCLUDED
                U$ '4ABCF16F01CD' /* Consultation$Lib */
               ; // %TOBEINCLUDED
              ; // aCons
              <<in>> aContainer
               %UID '4AA5366A0085'
               %TARGET U$ '49525C400141' /* IvcmContainer */
               %TOBEINCLUDED
                U$ '4790C3B8021E' /* VCM */
               ; // %TOBEINCLUDED
              ; // aContainer
            ; // %PARAMETERS
           ; // DoIt
         ; // %OPERATIONS
        ; // OpenConsultation
      ; // %OPERATIONS
      %CHILDREN
       
        FINAL <<VCMFormSetFactory>> SendConsultation
         %UID '4AA53D3A002B'
         %META
          %upv "Caption" 'Правовая поддержка'
          %upv "DefaultStatusForm" '-1'
          %upv "Need GetMainCaption" false
          %upv "Need GetMainImageIndex" false
          %upv "finished dfm" true
          %upv "needs InstanceR" 'undefined'
          %upv "needs script" 'undefined'
          %upv "no hands" false
          %upv "register in scripts" 'undefined'
          %upv "singleton" true
         ; // %META
         %TOBEINCLUDED
          U$ '469F3E37025A' /* Rtl */
          U$ '4790C3B8021E' /* VCM */
          U$ '4790D09A0378' /* L3 */
          U$ '493FCF1E03DC' /* Consultation */
          U$ '4A78013D01CD' /* "View$For F1 and Monitorings" */
          U$ '4E13416D0227' /* VCM$Visual */
         ; // %TOBEINCLUDED
         %INHERITS
          U$ '47B97312006D' /* TvcmFormSetFactory */
         ; // %INHERITS
         %OVERRIDES
          U$ '47A042E100E2' /* InitFields */
          U$ '4FFE854A009B' /* GetInstance */
         ; // %OVERRIDES
         %LINKS
           <<OwnerForm>> "4FFAE6370055"
            %UID '4FFAE6370055'
            %TARGET U$ '4FFAE62E0209' /* SaveLoad */
           ; // 4FFAE6370055
           SUMMONED <<uses>> "2725B13CF967"
            %UID '2725B13CF967'
            %TARGET U$ '4B3B3728004C' /* Tl3StringIDEx */
           ; // 2725B13CF967
           SUMMONED <<uses>> "F15271395BF8"
            %UID 'F15271395BF8'
            %TARGET U$ '4E01D1E002AE' /* Tl3MessageID */
           ; // F15271395BF8
         ; // %LINKS
         %OPERATIONS
           SUMMONED FINAL <<method>> SaveLoad_Parent_slqtConsult_NeedMakeForm
            %UID 'CAD3716E6F7B'
            %SUMMARY 'Обработчик OnNeedMakeForm для SaveLoad' ;
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
             U$ '4790C3B8021E' /* VCM */
             U$ '4E13416D0227' /* VCM$Visual */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '50096E800075' /* TvcmNeedMakeFormEvent */
            ; // %INHERITS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> DoIt
               %UID '002B70C0D436'
               %SUMMARY 'данные необходимые для создания формы' ;
               %TARGET U$ '46A603BB0391' /* Boolean */
               %TOBEINCLUDED
                U$ '469F3E37025A' /* Rtl */
                U$ '4790C3B8021E' /* VCM */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aDataSource
                  %UID 'E0FB7CD1C303'
                  %TARGET U$ '47F252870299' /* IvcmFormSetDataSource */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aDataSource
                 SUMMONED <<out>> aNew
                  %UID '7BE7668E4AF0'
                  %TARGET U$ '47EB900B0216' /* IvcmFormDataSource */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aNew
                 SUMMONED <<in>> aSubUserType
                  %UID '03A7DB11A26F'
                  %TARGET U$ '47F2534B010F' /* TvcmUserType */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aSubUserType
               ; // %PARAMETERS
              ; // DoIt
            ; // %OPERATIONS
           ; // SaveLoad_Parent_slqtConsult_NeedMakeForm
           SUMMONED FINAL <<method>> QueryCard_Parent_utqcSendConsultation_NeedMakeForm
            %UID '0BD7FE614FE1'
            %SUMMARY 'Обработчик OnNeedMakeForm для QueryCard' ;
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
             U$ '4790C3B8021E' /* VCM */
             U$ '4E13416D0227' /* VCM$Visual */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '50096E800075' /* TvcmNeedMakeFormEvent */
            ; // %INHERITS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> DoIt
               %UID 'FB0FBD212D07'
               %SUMMARY 'данные необходимые для создания формы' ;
               %TARGET U$ '46A603BB0391' /* Boolean */
               %TOBEINCLUDED
                U$ '469F3E37025A' /* Rtl */
                U$ '4790C3B8021E' /* VCM */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aDataSource
                  %UID '2C1DFCE2164C'
                  %TARGET U$ '47F252870299' /* IvcmFormSetDataSource */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aDataSource
                 SUMMONED <<out>> aNew
                  %UID '581B8480BE36'
                  %TARGET U$ '47EB900B0216' /* IvcmFormDataSource */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aNew
                 SUMMONED <<in>> aSubUserType
                  %UID '47F68F8EF4E0'
                  %TARGET U$ '47F2534B010F' /* TvcmUserType */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aSubUserType
               ; // %PARAMETERS
              ; // DoIt
            ; // %OPERATIONS
           ; // QueryCard_Parent_utqcSendConsultation_NeedMakeForm
           SUMMONED PRIVATE FINAL <<ini>> Init_fszQueryCard_Parent_utqcSendConsultationCaption
            %UID 'E34687D56B23'
            %SUMMARY 'Инициализация str_fszQueryCard_Parent_utqcSendConsultationCaption' ;
           ; // Init_fszQueryCard_Parent_utqcSendConsultationCaption
           SUMMONED FINAL <<static>> Exists
            %UID 'C14ED2BE6206'
            %SUMMARY 'Проверяет создан экземпляр синглетона или нет' ;
            %TARGET U$ '46A603BB0391' /* Boolean */
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
            ; // %TOBEINCLUDED
           ; // Exists
           SUMMONED PRIVATE FINAL <<ini>> Init_fsSendConsultationCaption
            %UID 'E0F352363C52'
            %SUMMARY 'Инициализация str_fsSendConsultationCaption' ;
           ; // Init_fsSendConsultationCaption
         ; // %OPERATIONS
         %CHILDREN
          
           <<VCMZone>> SaveLoad
            %UID '4FFAE62E0209'
            %META
             %upv "ActivateIfUpdate" 'None'
             %upv "Need GetFormCount" false
             %upv "Need OnFormWeight" 'undefined'
             %upv "Need UC" 'undefined'
             %upv "ZoneType" 'Parent'
            ; // %META
            %TOBEINCLUDED
             U$ '493FCF1E03DC' /* Consultation */
             U$ '4A78013D01CD' /* "View$For F1 and Monitorings" */
            ; // %TOBEINCLUDED
            %IMPLEMENTS
             U$ '492F005A02C7' /* IsdsQuery */
            ; // %IMPLEMENTS
            %INHERITS
             U$ '4BD5BC700046' /* slqtConsult */
             U$ '4D77A59D03E6' /* SaveLoad */
            ; // %INHERITS
            %REALIZES
             U$ '492F006F00BE' /* dsQuery */
             U$ '492F00890059' /* dsSaveLoad */
            ; // %REALIZES
            %CHILDREN
             
              <<VCMZone>> QueryCard
               %UID '4FFAE7500345'
               %META
                %upv "ActivateIfUpdate" 'None'
                %upv "Caption" '''Поиск с правовой поддержкой'''
                %upv "Need GetFormCount" false
                %upv "Need OnFormWeight" 'undefined'
                %upv "Need UC" 'undefined'
                %upv "ZoneType" 'Parent'
               ; // %META
               %TOBEINCLUDED
                U$ '493FCF1E03DC' /* Consultation */
                U$ '4A78013D01CD' /* "View$For F1 and Monitorings" */
               ; // %TOBEINCLUDED
               %IMPLEMENTS
                U$ '492F005A02C7' /* IsdsQuery */
               ; // %IMPLEMENTS
               %INHERITS
                U$ '4BD5C37D030C' /* utqcSendConsultation */
                U$ '4BD97FFF0005' /* QueryCard */
               ; // %INHERITS
               %REALIZES
                U$ '492F006F00BE' /* dsQuery */
                U$ '492F00890059' /* dsSaveLoad */
               ; // %REALIZES
              ; // QueryCard
            ; // %CHILDREN
           ; // SaveLoad
           SUMMONED PRIVATE FINAL <<LocalConst>> QueryCardCaptionLocalConstants
            %UID 'C649B12203E0'
            %SUMMARY 'Локализуемые константы для зоны QueryCard сборки форм SendConsultation' ;
            %META
             %upv "Need map interface" false
             %upv "Need mapping support" false
             %upv "spell names" false
            ; // %META
            %ATTRIBUTES
              SUMMONED <<Attribute>> fszQueryCard_Parent_utqcSendConsultationCaption
               %UID '4A185158B971'
               %SUMMARY 'Заголовок зоны "QueryCard" фабрики сборки форм "SendConsultation"' ;
               %VALUE '''Поиск с правовой поддержкой'''
               %META
                %upv "AutoInc" false
                %upv "forced type" 'none'
                %upv "is define" false
               ; // %META
              ; // fszQueryCard_Parent_utqcSendConsultationCaption
            ; // %ATTRIBUTES
           ; // QueryCardCaptionLocalConstants
           SUMMONED PRIVATE <<Constants>> LCImplQueryCardCaptionLocalConstants
            %UID 'BA6EDD17847F'
            %SUMMARY 'Локализуемые строки QueryCardCaptionLocalConstants' ;
            %META
             %upv "elements prefix" 'str'
             %upv "spell names" false
            ; // %META
            %TOBEINCLUDED
             U$ '4790D09A0378' /* L3 */
            ; // %TOBEINCLUDED
            %ATTRIBUTES
              SUMMONED <<Attribute>> fszQueryCard_Parent_utqcSendConsultationCaption
               %UID '99DD09910A2C'
               %SUMMARY 'Заголовок зоны "QueryCard" фабрики сборки форм "SendConsultation"' ;
               %TARGET U$ '4B3B3728004C' /* Tl3StringIDEx */
               %VALUE '(rS : -1; rLocalized : false; rKey : ''fszQueryCard_Parent_utqcSendConsultationCaption''; rValue : ''Поиск с правовой поддержкой'')'
               %META
                %upv "AutoInc" false
                %upv "forced type" 'none'
                %upv "is define" false
               ; // %META
               %TOBEINCLUDED
                U$ '4790D09A0378' /* L3 */
               ; // %TOBEINCLUDED
              ; // fszQueryCard_Parent_utqcSendConsultationCaption
            ; // %ATTRIBUTES
           ; // LCImplQueryCardCaptionLocalConstants
           SUMMONED PRIVATE FINAL <<LocalConst>> SendConsultationCaptionLocalConstants
            %UID '83A95AFD27A0'
            %SUMMARY 'Локализуемые константы для фабрики сборки форм SendConsultation' ;
            %META
             %upv "Need map interface" false
             %upv "Need mapping support" false
             %upv "spell names" false
            ; // %META
            %ATTRIBUTES
              SUMMONED <<Attribute>> fsSendConsultationCaption
               %UID '99948C597286'
               %SUMMARY 'Заголовок фабрики сборки форм "SendConsultation"' ;
               %VALUE '''Правовая поддержка'''
               %META
                %upv "AutoInc" false
                %upv "forced type" 'none'
                %upv "is define" false
               ; // %META
              ; // fsSendConsultationCaption
            ; // %ATTRIBUTES
           ; // SendConsultationCaptionLocalConstants
           SUMMONED PRIVATE <<Constants>> LCImplSendConsultationCaptionLocalConstants
            %UID '506B6BFACBA7'
            %SUMMARY 'Локализуемые строки SendConsultationCaptionLocalConstants' ;
            %META
             %upv "elements prefix" 'str'
             %upv "spell names" false
            ; // %META
            %TOBEINCLUDED
             U$ '4790D09A0378' /* L3 */
            ; // %TOBEINCLUDED
            %ATTRIBUTES
              SUMMONED <<Attribute>> fsSendConsultationCaption
               %UID '0B01338F3AD8'
               %SUMMARY 'Заголовок фабрики сборки форм "SendConsultation"' ;
               %TARGET U$ '4B3B3728004C' /* Tl3StringIDEx */
               %VALUE '(rS : -1; rLocalized : false; rKey : ''fsSendConsultationCaption''; rValue : ''Правовая поддержка'')'
               %META
                %upv "AutoInc" false
                %upv "forced type" 'none'
                %upv "is define" false
               ; // %META
               %TOBEINCLUDED
                U$ '4790D09A0378' /* L3 */
               ; // %TOBEINCLUDED
              ; // fsSendConsultationCaption
            ; // %ATTRIBUTES
           ; // LCImplSendConsultationCaptionLocalConstants
         ; // %CHILDREN
        ; // SendConsultation
        FINAL <<VCMFormSetFactory>> Consultation
         %UID '4AA5360E0197'
         %SUMMARY 'Сборка для показа консультации' ;
         %META
          %upv "Caption" 'Консультация'
          %upv "DefaultStatusForm" '-1'
          %upv "Need GetMainCaption" false
          %upv "Need GetMainImageIndex" false
          %upv "finished dfm" true
          %upv "needs InstanceR" 'undefined'
          %upv "needs script" 'undefined'
          %upv "no hands" false
          %upv "register in scripts" 'undefined'
          %upv "singleton" true
         ; // %META
         %TOBEINCLUDED
          U$ '469F3E37025A' /* Rtl */
          U$ '4790C3B8021E' /* VCM */
          U$ '4790D09A0378' /* L3 */
          U$ '4A7C099B004F' /* View */
          U$ '4A92C59801C7' /* View */
          U$ '4ABCF16F01CD' /* Consultation$Lib */
          U$ '4ABCFB180302' /* View */
          U$ '4E13416D0227' /* VCM$Visual */
         ; // %TOBEINCLUDED
         %INHERITS
          U$ '47B97312006D' /* TvcmFormSetFactory */
         ; // %INHERITS
         %OVERRIDES
          U$ '47A042E100E2' /* InitFields */
          U$ '4FFE854A009B' /* GetInstance */
         ; // %OVERRIDES
         %LINKS
           <<OwnerForm>> "4FFADB0701F1"
            %UID '4FFADB0701F1'
            %TARGET U$ '4FFADAFD02F1' /* Text */
           ; // 4FFADB0701F1
           SUMMONED <<uses>> "BBCCE7334A76"
            %UID 'BBCCE7334A76'
            %TARGET U$ '4B3B3728004C' /* Tl3StringIDEx */
           ; // BBCCE7334A76
           SUMMONED <<uses>> "38C06A096105"
            %UID '38C06A096105'
            %TARGET U$ '4E01D1E002AE' /* Tl3MessageID */
           ; // 38C06A096105
         ; // %LINKS
         %OPERATIONS
           SUMMONED FINAL <<method>> Text_Parent_dftConsultation_NeedMakeForm
            %UID 'C368BAC18740'
            %SUMMARY 'Обработчик OnNeedMakeForm для Text' ;
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
             U$ '4790C3B8021E' /* VCM */
             U$ '4E13416D0227' /* VCM$Visual */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '50096E800075' /* TvcmNeedMakeFormEvent */
            ; // %INHERITS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> DoIt
               %UID 'FA87DCF593FA'
               %SUMMARY 'данные необходимые для создания формы' ;
               %TARGET U$ '46A603BB0391' /* Boolean */
               %TOBEINCLUDED
                U$ '469F3E37025A' /* Rtl */
                U$ '4790C3B8021E' /* VCM */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aDataSource
                  %UID 'D9D9DD6563DA'
                  %TARGET U$ '47F252870299' /* IvcmFormSetDataSource */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aDataSource
                 SUMMONED <<out>> aNew
                  %UID 'DDC323CCF1B2'
                  %TARGET U$ '47EB900B0216' /* IvcmFormDataSource */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aNew
                 SUMMONED <<in>> aSubUserType
                  %UID 'C9955557D459'
                  %TARGET U$ '47F2534B010F' /* TvcmUserType */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aSubUserType
               ; // %PARAMETERS
              ; // DoIt
            ; // %OPERATIONS
           ; // Text_Parent_dftConsultation_NeedMakeForm
           SUMMONED FINAL <<method>> List_Child_lftConsultation_NeedMakeForm
            %UID 'E34153DD0D14'
            %SUMMARY 'Обработчик OnNeedMakeForm для List' ;
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
             U$ '4790C3B8021E' /* VCM */
             U$ '4E13416D0227' /* VCM$Visual */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '50096E800075' /* TvcmNeedMakeFormEvent */
            ; // %INHERITS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> DoIt
               %UID '4F735122A4D7'
               %SUMMARY 'данные необходимые для создания формы' ;
               %TARGET U$ '46A603BB0391' /* Boolean */
               %TOBEINCLUDED
                U$ '469F3E37025A' /* Rtl */
                U$ '4790C3B8021E' /* VCM */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aDataSource
                  %UID '4E62F28F7D97'
                  %TARGET U$ '47F252870299' /* IvcmFormSetDataSource */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aDataSource
                 SUMMONED <<out>> aNew
                  %UID '183F592329ED'
                  %TARGET U$ '47EB900B0216' /* IvcmFormDataSource */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aNew
                 SUMMONED <<in>> aSubUserType
                  %UID '982ABCF3F6C0'
                  %TARGET U$ '47F2534B010F' /* TvcmUserType */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aSubUserType
               ; // %PARAMETERS
              ; // DoIt
            ; // %OPERATIONS
           ; // List_Child_lftConsultation_NeedMakeForm
           SUMMONED FINAL <<method>> Mark_Modal_utcmMain_NeedMakeForm
            %UID '3B88C8040506'
            %SUMMARY 'Обработчик OnNeedMakeForm для Mark' ;
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
             U$ '4790C3B8021E' /* VCM */
             U$ '4E13416D0227' /* VCM$Visual */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '50096E800075' /* TvcmNeedMakeFormEvent */
            ; // %INHERITS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> DoIt
               %UID 'EE253E591973'
               %SUMMARY 'данные необходимые для создания формы' ;
               %TARGET U$ '46A603BB0391' /* Boolean */
               %TOBEINCLUDED
                U$ '469F3E37025A' /* Rtl */
                U$ '4790C3B8021E' /* VCM */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aDataSource
                  %UID '4857E59D3185'
                  %TARGET U$ '47F252870299' /* IvcmFormSetDataSource */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aDataSource
                 SUMMONED <<out>> aNew
                  %UID 'E4548291926B'
                  %TARGET U$ '47EB900B0216' /* IvcmFormDataSource */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aNew
                 SUMMONED <<in>> aSubUserType
                  %UID '5F001DF0C57D'
                  %TARGET U$ '47F2534B010F' /* TvcmUserType */
                  %TOBEINCLUDED
                   U$ '4790C3B8021E' /* VCM */
                  ; // %TOBEINCLUDED
                 ; // aSubUserType
               ; // %PARAMETERS
              ; // DoIt
            ; // %OPERATIONS
           ; // Mark_Modal_utcmMain_NeedMakeForm
           SUMMONED FINAL <<static>> Exists
            %UID 'D6A1631002BE'
            %SUMMARY 'Проверяет создан экземпляр синглетона или нет' ;
            %TARGET U$ '46A603BB0391' /* Boolean */
            %TOBEINCLUDED
             U$ '469F3E37025A' /* Rtl */
            ; // %TOBEINCLUDED
           ; // Exists
           SUMMONED PRIVATE FINAL <<ini>> Init_fsConsultationCaption
            %UID '3F6523B4C163'
            %SUMMARY 'Инициализация str_fsConsultationCaption' ;
           ; // Init_fsConsultationCaption
         ; // %OPERATIONS
         %CHILDREN
          
           <<VCMZone>> Text
            %UID '4FFADAFD02F1'
            %META
             %upv "ActivateIfUpdate" 'None'
             %upv "Need GetFormCount" false
             %upv "Need OnFormWeight" 'undefined'
             %upv "Need UC" 'undefined'
             %upv "ZoneType" 'Parent'
            ; // %META
            %TOBEINCLUDED
             U$ '4A7C099B004F' /* View */
             U$ '4A92C59801C7' /* View */
             U$ '4ABCF16F01CD' /* Consultation$Lib */
            ; // %TOBEINCLUDED
            %IMPLEMENTS
             U$ '4921732002D9' /* IsdsConsultation */
            ; // %IMPLEMENTS
            %INHERITS
             U$ '4B040F540027' /* dftConsultation */
             U$ '4BD8574A03A5' /* Text */
            ; // %INHERITS
            %REALIZES
             U$ '492597A602F6' /* MakeGotoPointData */
             U$ '492EB71000D6' /* dsConsultation */
             U$ '492EB77C0125' /* dsList */
             U$ '492EB793009E' /* DSConsultationMark */
             U$ '492EB7BA035E' /* GiveMark */
             U$ '492EB82F0391' /* NeedGiveMark */
             U$ '492EB8620306' /* ConfirmPayment */
             U$ '492EB8820218' /* UpdateAnswer */
             U$ '492EB91F0391' /* ListChanged */
             U$ '492EB93700FF' /* ConsultationWasMarked */
             U$ '492EBCE002E0' /* MarkSended */
             U$ '4F4E1E06038E' /* bsConsultation */
            ; // %REALIZES
           ; // Text
           <<VCMZone>> List
            %UID '4FFADCDA016F'
            %META
             %upv "ActivateIfUpdate" 'None'
             %upv "Need GetFormCount" false
             %upv "Need OnFormWeight" 'undefined'
             %upv "Need UC" 'undefined'
             %upv "ZoneType" 'Child'
            ; // %META
            %TOBEINCLUDED
             U$ '4A7C099B004F' /* View */
             U$ '4A92C59801C7' /* View */
             U$ '4ABCF16F01CD' /* Consultation$Lib */
            ; // %TOBEINCLUDED
            %IMPLEMENTS
             U$ '4921732002D9' /* IsdsConsultation */
            ; // %IMPLEMENTS
            %INHERITS
             U$ '4BD589B50312' /* lftConsultation */
             U$ '4BD96F4C0025' /* List */
            ; // %INHERITS
            %REALIZES
             U$ '492597A602F6' /* MakeGotoPointData */
             U$ '492EB71000D6' /* dsConsultation */
             U$ '492EB77C0125' /* dsList */
             U$ '492EB793009E' /* DSConsultationMark */
             U$ '492EB7BA035E' /* GiveMark */
             U$ '492EB82F0391' /* NeedGiveMark */
             U$ '492EB8620306' /* ConfirmPayment */
             U$ '492EB8820218' /* UpdateAnswer */
             U$ '492EB91F0391' /* ListChanged */
             U$ '492EB93700FF' /* ConsultationWasMarked */
             U$ '492EBCE002E0' /* MarkSended */
             U$ '4F4E1E06038E' /* bsConsultation */
            ; // %REALIZES
           ; // List
           <<VCMZone>> Mark
            %UID '4FFADD000158'
            %META
             %upv "ActivateIfUpdate" 'None'
             %upv "Need GetFormCount" false
             %upv "Need OnFormWeight" 'undefined'
             %upv "Need UC" 'undefined'
             %upv "ZoneType" 'Modal'
            ; // %META
            %TOBEINCLUDED
             U$ '4A92C59801C7' /* View */
             U$ '4ABCF16F01CD' /* Consultation$Lib */
             U$ '4ABCFB180302' /* View */
            ; // %TOBEINCLUDED
            %IMPLEMENTS
             U$ '4921732002D9' /* IsdsConsultation */
            ; // %IMPLEMENTS
            %INHERITS
             U$ '4CD142B70232' /* utcmMain */
             U$ '4FFADD3502A1' /* ConsultationMark */
            ; // %INHERITS
            %REALIZES
             U$ '492597A602F6' /* MakeGotoPointData */
             U$ '492EB71000D6' /* dsConsultation */
             U$ '492EB77C0125' /* dsList */
             U$ '492EB793009E' /* DSConsultationMark */
             U$ '492EB7BA035E' /* GiveMark */
             U$ '492EB82F0391' /* NeedGiveMark */
             U$ '492EB8620306' /* ConfirmPayment */
             U$ '492EB8820218' /* UpdateAnswer */
             U$ '492EB91F0391' /* ListChanged */
             U$ '492EB93700FF' /* ConsultationWasMarked */
             U$ '492EBCE002E0' /* MarkSended */
             U$ '4F4E1E06038E' /* bsConsultation */
            ; // %REALIZES
           ; // Mark
           SUMMONED PRIVATE FINAL <<LocalConst>> ConsultationCaptionLocalConstants
            %UID 'CBB3895E2FDF'
            %SUMMARY 'Локализуемые константы для фабрики сборки форм Consultation' ;
            %META
             %upv "Need map interface" false
             %upv "Need mapping support" false
             %upv "spell names" false
            ; // %META
            %ATTRIBUTES
              SUMMONED <<Attribute>> fsConsultationCaption
               %UID 'B3ED49D1BFAC'
               %SUMMARY 'Заголовок фабрики сборки форм "Consultation"' ;
               %VALUE '''Консультация'''
               %META
                %upv "AutoInc" false
                %upv "forced type" 'none'
                %upv "is define" false
               ; // %META
              ; // fsConsultationCaption
            ; // %ATTRIBUTES
           ; // ConsultationCaptionLocalConstants
           SUMMONED PRIVATE <<Constants>> LCImplConsultationCaptionLocalConstants
            %UID '471A200AED99'
            %SUMMARY 'Локализуемые строки ConsultationCaptionLocalConstants' ;
            %META
             %upv "elements prefix" 'str'
             %upv "spell names" false
            ; // %META
            %TOBEINCLUDED
             U$ '4790D09A0378' /* L3 */
            ; // %TOBEINCLUDED
            %ATTRIBUTES
              SUMMONED <<Attribute>> fsConsultationCaption
               %UID '393D3BBD8AF0'
               %SUMMARY 'Заголовок фабрики сборки форм "Consultation"' ;
               %TARGET U$ '4B3B3728004C' /* Tl3StringIDEx */
               %VALUE '(rS : -1; rLocalized : false; rKey : ''fsConsultationCaption''; rValue : ''Консультация'')'
               %META
                %upv "AutoInc" false
                %upv "forced type" 'none'
                %upv "is define" false
               ; // %META
               %TOBEINCLUDED
                U$ '4790D09A0378' /* L3 */
               ; // %TOBEINCLUDED
              ; // fsConsultationCaption
            ; // %ATTRIBUTES
           ; // LCImplConsultationCaptionLocalConstants
         ; // %CHILDREN
        ; // Consultation
        FINAL <<VCMFinalForm>> ConsultationMark
         %UID '4AB8D1DB01FD'
         %SUMMARY 'Оценка ответа' ;
         %META
          %upv "NeedsHackRef" true
          %upv "ZoneType" 'Any'
          %upv "author" 'Люлин А.В.'
          %upv "base wnd class" 'CWnd'
          %upv "finished dfm" true
          %upv "form name prefix" 'en_'
          %upv "needs InstanceR" 'undefined'
          %upv "needs script" 'undefined'
          %upv "no hands" false
          %upv "register in scripts" 'undefined'
          %upv "resizeable" false
          %upv "restrict form def" 'undefined'
          %upv "started" '22.09.2009 16:49'
         ; // %META
         %TOBEINCLUDED
          U$ '4A92C59801C7' /* View */
          U$ '4ABCFB180302' /* View */
         ; // %TOBEINCLUDED
         %IMPLEMENTS
          U$ '4FFADD3502A1' /* ConsultationMark */
         ; // %IMPLEMENTS
         %INHERITS
          U$ '4C84E097023A' /* PrimConsultationMarkOptions */
         ; // %INHERITS
         %LINKS
           SUMMONED <<uses>> "C2CD070753FC"
            %UID 'C2CD070753FC'
            %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
           ; // C2CD070753FC
         ; // %LINKS
         %OPERATIONS
           SUMMONED PRIVATE FINAL <<ini>> Ini_Reg_Class
            %UID '015478C542D8'
            %SUMMARY 'Регистрация ConsultationMark' ;
            %META
             %upv "ifndef" 'NoScripts'
            ; // %META
           ; // Ini_Reg_Class
           SUMMONED PRIVATE FINAL <<ini>> Ini_FormFactory_ConsultationMark
            %UID '1DADCA21A4C1'
            %SUMMARY 'Регистрация фабрики формы ConsultationMark' ;
           ; // Ini_FormFactory_ConsultationMark
         ; // %OPERATIONS
        ; // ConsultationMark
        SUMMONED FINAL <<ScriptKeywordsPack>> ConsultationMarkKeywordsPack
         %UID '18755A78D1B1'
         %SUMMARY 'Набор слов словаря для доступа к экземплярам контролов формы ConsultationMark' ;
         %META
          %upv "ifndef" 'NoScripts'
          %upv "needs script" 'undefined'
          %upv "no class name" 'undefined'
          %upv "no hands" false
          %upv "no_pop" true
         ; // %META
         %TOBEINCLUDED
          U$ '467A75D90346' /* VT */
          U$ '4680E7D50168' /* "Everest Engine" */
          U$ '4ABCFB180302' /* View */
          U$ '547CC9D40158' /* VT$Panels */
          U$ '54CF97B10370' /* ScriptEngine$Core */
          U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
         ; // %TOBEINCLUDED
         %INHERITS
          U$ '4AB8D1DB01FD' /* ConsultationMark */
         ; // %INHERITS
         %REALIZES
          U$ '4A8AD46D0226' /* Cancel$4A8AD46D0226 */
          U$ '4A97EBE702F8' /* Ok$4A97EBE702F8 */
         ; // %REALIZES
         %LINKS
           SUMMONED <<uses>> "F72306081C35"
            %UID 'F72306081C35'
            %TARGET U$ '55153C2C036F' /* TypeInfoExt */
           ; // F72306081C35
           SUMMONED <<injects>> "57B07CC577B3"
            %UID '57B07CC577B3'
            %TARGET U$ '4AB8D1DB01FD' /* ConsultationMark */
           ; // 57B07CC577B3
           SUMMONED <<uses>> "12E5ABA91BDC"
            %UID '12E5ABA91BDC'
            %TARGET U$ '5527F8330362' /* TtfwTypeRegistrator */
           ; // 12E5ABA91BDC
         ; // %LINKS
         %ATTRIBUTES
           SUMMONED FINAL <<readonly>> gbMark
            %UID 'B1C1A7E28A49'
            %SUMMARY 'Контрол gbMark формы Ten_ConsultationMark' ;
            %TARGET U$ '4AC608E40294' /* TvtGroupBox */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.gbMark'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // gbMark
           SUMMONED FINAL <<readonly>> rbNotSure
            %UID 'C911D04469D9'
            %SUMMARY 'Контрол rbNotSure формы Ten_ConsultationMark' ;
            %TARGET U$ '517941E500BF' /* TvtRadioButton */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbNotSure'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // rbNotSure
           SUMMONED FINAL <<readonly>> rbTwo
            %UID '550F86E0A064'
            %SUMMARY 'Контрол rbTwo формы Ten_ConsultationMark' ;
            %TARGET U$ '517941E500BF' /* TvtRadioButton */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbTwo'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // rbTwo
           SUMMONED FINAL <<readonly>> rbThree
            %UID 'AB5EACDDC4EB'
            %SUMMARY 'Контрол rbThree формы Ten_ConsultationMark' ;
            %TARGET U$ '517941E500BF' /* TvtRadioButton */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbThree'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // rbThree
           SUMMONED FINAL <<readonly>> rbFour
            %UID '1840085A763E'
            %SUMMARY 'Контрол rbFour формы Ten_ConsultationMark' ;
            %TARGET U$ '517941E500BF' /* TvtRadioButton */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbFour'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // rbFour
           SUMMONED FINAL <<readonly>> rbFive
            %UID '9931D6FEA634'
            %SUMMARY 'Контрол rbFive формы Ten_ConsultationMark' ;
            %TARGET U$ '517941E500BF' /* TvtRadioButton */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbFive'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // rbFive
           SUMMONED FINAL <<readonly>> pnlHelp
            %UID '458A10E71914'
            %SUMMARY 'Контрол pnlHelp формы Ten_ConsultationMark' ;
            %TARGET U$ '4A7961A701CF' /* TvtPanel */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.pnlHelp'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '547CC9D40158' /* VT$Panels */
            ; // %TOBEINCLUDED
           ; // pnlHelp
           SUMMONED FINAL <<readonly>> lblHelp
            %UID '2D88BA4B9AE8'
            %SUMMARY 'Контрол lblHelp формы Ten_ConsultationMark' ;
            %TARGET U$ '4AE8541A01AE' /* TvtLabel */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.lblHelp'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // lblHelp
           SUMMONED FINAL <<readonly>> gbComment
            %UID 'E748C3F198F4'
            %SUMMARY 'Контрол gbComment формы Ten_ConsultationMark' ;
            %TARGET U$ '4AC608E40294' /* TvtGroupBox */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.gbComment'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // gbComment
           SUMMONED FINAL <<readonly>> mComment
            %UID 'F1F50094D78C'
            %SUMMARY 'Контрол mComment формы Ten_ConsultationMark' ;
            %TARGET U$ '4AC5D3380185' /* TeeMemoWithEditOperations */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.mComment'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '4680E7D50168' /* "Everest Engine" */
            ; // %TOBEINCLUDED
           ; // mComment
         ; // %ATTRIBUTES
         %OPERATIONS
           SUMMONED FINAL <<keyword>> gbMark$0B29209C7DDD
            %UID '0B29209C7DDD'
            %SUMMARY 'Контрол gbMark формы Ten_ConsultationMark' ;
            %TARGET U$ '4AC608E40294' /* TvtGroupBox */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.gbMark'
             %upv "bind params" 'undefined'
             %upv "lvalue" 'undefined'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // gbMark$0B29209C7DDD
           SUMMONED FINAL <<keyword>> rbNotSure$8142F1219EC7
            %UID '8142F1219EC7'
            %SUMMARY 'Контрол rbNotSure формы Ten_ConsultationMark' ;
            %TARGET U$ '517941E500BF' /* TvtRadioButton */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbNotSure'
             %upv "bind params" 'undefined'
             %upv "lvalue" 'undefined'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // rbNotSure$8142F1219EC7
           SUMMONED FINAL <<keyword>> rbTwo$AAA377FDCD7C
            %UID 'AAA377FDCD7C'
            %SUMMARY 'Контрол rbTwo формы Ten_ConsultationMark' ;
            %TARGET U$ '517941E500BF' /* TvtRadioButton */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbTwo'
             %upv "bind params" 'undefined'
             %upv "lvalue" 'undefined'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // rbTwo$AAA377FDCD7C
           SUMMONED FINAL <<keyword>> rbThree$AD8142FC2183
            %UID 'AD8142FC2183'
            %SUMMARY 'Контрол rbThree формы Ten_ConsultationMark' ;
            %TARGET U$ '517941E500BF' /* TvtRadioButton */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbThree'
             %upv "bind params" 'undefined'
             %upv "lvalue" 'undefined'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // rbThree$AD8142FC2183
           SUMMONED FINAL <<keyword>> rbFour$C2CD78D2D6D1
            %UID 'C2CD78D2D6D1'
            %SUMMARY 'Контрол rbFour формы Ten_ConsultationMark' ;
            %TARGET U$ '517941E500BF' /* TvtRadioButton */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbFour'
             %upv "bind params" 'undefined'
             %upv "lvalue" 'undefined'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // rbFour$C2CD78D2D6D1
           SUMMONED FINAL <<keyword>> rbFive$D06DCA754D5E
            %UID 'D06DCA754D5E'
            %SUMMARY 'Контрол rbFive формы Ten_ConsultationMark' ;
            %TARGET U$ '517941E500BF' /* TvtRadioButton */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbFive'
             %upv "bind params" 'undefined'
             %upv "lvalue" 'undefined'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // rbFive$D06DCA754D5E
           SUMMONED FINAL <<keyword>> pnlHelp$17F5D1F5B7A8
            %UID '17F5D1F5B7A8'
            %SUMMARY 'Контрол pnlHelp формы Ten_ConsultationMark' ;
            %TARGET U$ '4A7961A701CF' /* TvtPanel */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.pnlHelp'
             %upv "bind params" 'undefined'
             %upv "lvalue" 'undefined'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '547CC9D40158' /* VT$Panels */
            ; // %TOBEINCLUDED
           ; // pnlHelp$17F5D1F5B7A8
           SUMMONED FINAL <<keyword>> lblHelp$60BA472CA121
            %UID '60BA472CA121'
            %SUMMARY 'Контрол lblHelp формы Ten_ConsultationMark' ;
            %TARGET U$ '4AE8541A01AE' /* TvtLabel */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.lblHelp'
             %upv "bind params" 'undefined'
             %upv "lvalue" 'undefined'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // lblHelp$60BA472CA121
           SUMMONED FINAL <<keyword>> gbComment$162607EEE2FB
            %UID '162607EEE2FB'
            %SUMMARY 'Контрол gbComment формы Ten_ConsultationMark' ;
            %TARGET U$ '4AC608E40294' /* TvtGroupBox */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.gbComment'
             %upv "bind params" 'undefined'
             %upv "lvalue" 'undefined'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
            ; // %TOBEINCLUDED
           ; // gbComment$162607EEE2FB
           SUMMONED FINAL <<keyword>> mComment$233253748806
            %UID '233253748806'
            %SUMMARY 'Контрол mComment формы Ten_ConsultationMark' ;
            %TARGET U$ '4AC5D3380185' /* TeeMemoWithEditOperations */
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.mComment'
             %upv "bind params" 'undefined'
             %upv "lvalue" 'undefined'
             %upv "mapped" true
            ; // %META
            %TOBEINCLUDED
             U$ '4680E7D50168' /* "Everest Engine" */
            ; // %TOBEINCLUDED
           ; // mComment$233253748806
           SUMMONED PRIVATE FINAL <<ini>> Reg_TtfwContext
            %UID 'CE122B902088'
            %SUMMARY 'Регистрация типа TtfwContext' ;
           ; // Reg_TtfwContext
           SUMMONED PRIVATE FINAL <<ini>> Reg_ConsultationMark
            %UID 'B3501A4B9E67'
            %SUMMARY 'Регистрация типа ConsultationMark' ;
           ; // Reg_ConsultationMark
           SUMMONED PRIVATE FINAL <<ini>> Reg_TvtGroupBox
            %UID 'D77CCFC4D916'
            %SUMMARY 'Регистрация типа TvtGroupBox' ;
           ; // Reg_TvtGroupBox
           SUMMONED PRIVATE FINAL <<ini>> Reg_TvtRadioButton
            %UID '3A60AEA5D3BA'
            %SUMMARY 'Регистрация типа TvtRadioButton' ;
           ; // Reg_TvtRadioButton
           SUMMONED PRIVATE FINAL <<ini>> Reg_TvtPanel
            %UID '7B6FDC3F37CC'
            %SUMMARY 'Регистрация типа TvtPanel' ;
           ; // Reg_TvtPanel
           SUMMONED PRIVATE FINAL <<ini>> Reg_TvtLabel
            %UID 'F8DEF7E5A1C2'
            %SUMMARY 'Регистрация типа TvtLabel' ;
           ; // Reg_TvtLabel
           SUMMONED PRIVATE FINAL <<ini>> Reg_TeeMemoWithEditOperations
            %UID 'AE6A13085975'
            %SUMMARY 'Регистрация типа TeeMemoWithEditOperations' ;
           ; // Reg_TeeMemoWithEditOperations
         ; // %OPERATIONS
         %CHILDREN
          
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_Form_ConsultationMark"
            %UID '0086675B6B83'
            %SUMMARY 'Слово словаря для идентификатора формы ConsultationMark'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'''aControl'' форма::ConsultationMark TryFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'форма::ConsultationMark'
             %upv "ifndef" 'NoScripts'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '508527F30183' /* TtfwControlString */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '4DDFD2EA0116' /* GetString */
            ; // %OVERRIDES
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '219A3B1793B1'
               %SUMMARY 'Регистрация Tkw_Form_ConsultationMark' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_Form_ConsultationMark"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_gbMark"
            %UID '118FE6A612B7'
            %SUMMARY 'Слово словаря для идентификатора контрола gbMark'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::gbMark TryFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::gbMark'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '508527F30183' /* TtfwControlString */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '4DDFD2EA0116' /* GetString */
             U$ '52A086150180' /* RegisterInEngine */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "4CDABBB67C3B"
               %UID '4CDABBB67C3B'
               %TARGET U$ '4AC608E40294' /* TvtGroupBox */
              ; // 4CDABBB67C3B
              SUMMONED <<uses>> "9F0A9837BCD1"
               %UID '9F0A9837BCD1'
               %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
              ; // 9F0A9837BCD1
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'E86B44C83E79'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_gbMark' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_gbMark"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_gbMark_Push"
            %UID '8B30EAB1C18A'
            %SUMMARY 'Слово словаря для контрола gbMark'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::gbMark:push pop:control:SetFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::gbMark:push'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4F2141AD0203' /* "byname_control_push" */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DAEEDE10285' /* DoDoIt */
             U$ '4DB0614603C8' /* GetWordNameForRegister */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "BC507A3A1737"
               %UID 'BC507A3A1737'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // BC507A3A1737
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'EFA624096E6D'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_gbMark_Push' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_gbMark_Push"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_rbNotSure"
            %UID '7B79325E0A7A'
            %SUMMARY 'Слово словаря для идентификатора контрола rbNotSure'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::rbNotSure TryFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::rbNotSure'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '508527F30183' /* TtfwControlString */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '4DDFD2EA0116' /* GetString */
             U$ '52A086150180' /* RegisterInEngine */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "355911C56F4D"
               %UID '355911C56F4D'
               %TARGET U$ '517941E500BF' /* TvtRadioButton */
              ; // 355911C56F4D
              SUMMONED <<uses>> "ABC11D79F8D4"
               %UID 'ABC11D79F8D4'
               %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
              ; // ABC11D79F8D4
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '7155CA1C23B2'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_rbNotSure' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_rbNotSure"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_rbNotSure_Push"
            %UID 'DD80E9E3BC24'
            %SUMMARY 'Слово словаря для контрола rbNotSure'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::rbNotSure:push pop:control:SetFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::rbNotSure:push'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4F2141AD0203' /* "byname_control_push" */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DAEEDE10285' /* DoDoIt */
             U$ '4DB0614603C8' /* GetWordNameForRegister */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "34E0BC4BA61E"
               %UID '34E0BC4BA61E'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 34E0BC4BA61E
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '8828B56CD77A'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_rbNotSure_Push' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_rbNotSure_Push"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_rbTwo"
            %UID 'EA306136E4F7'
            %SUMMARY 'Слово словаря для идентификатора контрола rbTwo'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::rbTwo TryFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::rbTwo'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '508527F30183' /* TtfwControlString */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '4DDFD2EA0116' /* GetString */
             U$ '52A086150180' /* RegisterInEngine */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "028629224FF9"
               %UID '028629224FF9'
               %TARGET U$ '517941E500BF' /* TvtRadioButton */
              ; // 028629224FF9
              SUMMONED <<uses>> "8256CDCB8D57"
               %UID '8256CDCB8D57'
               %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
              ; // 8256CDCB8D57
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '8937E0B7A338'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_rbTwo' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_rbTwo"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_rbTwo_Push"
            %UID 'F4BF94F0783C'
            %SUMMARY 'Слово словаря для контрола rbTwo'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::rbTwo:push pop:control:SetFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::rbTwo:push'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4F2141AD0203' /* "byname_control_push" */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DAEEDE10285' /* DoDoIt */
             U$ '4DB0614603C8' /* GetWordNameForRegister */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "255F8729F7BA"
               %UID '255F8729F7BA'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 255F8729F7BA
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'AF877DB69EB3'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_rbTwo_Push' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_rbTwo_Push"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_rbThree"
            %UID '391E219F54C0'
            %SUMMARY 'Слово словаря для идентификатора контрола rbThree'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::rbThree TryFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::rbThree'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '508527F30183' /* TtfwControlString */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '4DDFD2EA0116' /* GetString */
             U$ '52A086150180' /* RegisterInEngine */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "68F75C6080AB"
               %UID '68F75C6080AB'
               %TARGET U$ '517941E500BF' /* TvtRadioButton */
              ; // 68F75C6080AB
              SUMMONED <<uses>> "34A97D73530E"
               %UID '34A97D73530E'
               %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
              ; // 34A97D73530E
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '5159EAF08104'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_rbThree' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_rbThree"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_rbThree_Push"
            %UID '227391332298'
            %SUMMARY 'Слово словаря для контрола rbThree'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::rbThree:push pop:control:SetFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::rbThree:push'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4F2141AD0203' /* "byname_control_push" */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DAEEDE10285' /* DoDoIt */
             U$ '4DB0614603C8' /* GetWordNameForRegister */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "66981FCE768C"
               %UID '66981FCE768C'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 66981FCE768C
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '1CAE1B6BE9EC'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_rbThree_Push' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_rbThree_Push"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_rbFour"
            %UID 'E0D3D888E0D9'
            %SUMMARY 'Слово словаря для идентификатора контрола rbFour'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::rbFour TryFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::rbFour'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '508527F30183' /* TtfwControlString */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '4DDFD2EA0116' /* GetString */
             U$ '52A086150180' /* RegisterInEngine */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "F42CA4D0AEF4"
               %UID 'F42CA4D0AEF4'
               %TARGET U$ '517941E500BF' /* TvtRadioButton */
              ; // F42CA4D0AEF4
              SUMMONED <<uses>> "C0FD1C4074C8"
               %UID 'C0FD1C4074C8'
               %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
              ; // C0FD1C4074C8
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '4951BB45D0D2'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_rbFour' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_rbFour"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_rbFour_Push"
            %UID '661E127E17A8'
            %SUMMARY 'Слово словаря для контрола rbFour'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::rbFour:push pop:control:SetFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::rbFour:push'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4F2141AD0203' /* "byname_control_push" */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DAEEDE10285' /* DoDoIt */
             U$ '4DB0614603C8' /* GetWordNameForRegister */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "4B16FB4CF826"
               %UID '4B16FB4CF826'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 4B16FB4CF826
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'C0FBAD95E7C5'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_rbFour_Push' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_rbFour_Push"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_rbFive"
            %UID '313D31B5C832'
            %SUMMARY 'Слово словаря для идентификатора контрола rbFive'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::rbFive TryFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::rbFive'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '508527F30183' /* TtfwControlString */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '4DDFD2EA0116' /* GetString */
             U$ '52A086150180' /* RegisterInEngine */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "94C500856965"
               %UID '94C500856965'
               %TARGET U$ '517941E500BF' /* TvtRadioButton */
              ; // 94C500856965
              SUMMONED <<uses>> "65EEB17583E0"
               %UID '65EEB17583E0'
               %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
              ; // 65EEB17583E0
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'E3DB75476C81'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_rbFive' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_rbFive"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_rbFive_Push"
            %UID '66CFD6054E2B'
            %SUMMARY 'Слово словаря для контрола rbFive'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::rbFive:push pop:control:SetFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::rbFive:push'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4F2141AD0203' /* "byname_control_push" */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DAEEDE10285' /* DoDoIt */
             U$ '4DB0614603C8' /* GetWordNameForRegister */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "5EF251FE4C20"
               %UID '5EF251FE4C20'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 5EF251FE4C20
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'C9C6DF41E5F7'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_rbFive_Push' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_rbFive_Push"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_pnlHelp"
            %UID 'D5885EA40FCB'
            %SUMMARY 'Слово словаря для идентификатора контрола pnlHelp'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::pnlHelp TryFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::pnlHelp'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '508527F30183' /* TtfwControlString */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '4DDFD2EA0116' /* GetString */
             U$ '52A086150180' /* RegisterInEngine */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "8AB6E1B547FA"
               %UID '8AB6E1B547FA'
               %TARGET U$ '4A7961A701CF' /* TvtPanel */
              ; // 8AB6E1B547FA
              SUMMONED <<uses>> "A878775011FE"
               %UID 'A878775011FE'
               %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
              ; // A878775011FE
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '955D914A589D'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_pnlHelp' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_pnlHelp"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_pnlHelp_Push"
            %UID 'FC2521E59BA7'
            %SUMMARY 'Слово словаря для контрола pnlHelp'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::pnlHelp:push pop:control:SetFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::pnlHelp:push'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4F2141AD0203' /* "byname_control_push" */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DAEEDE10285' /* DoDoIt */
             U$ '4DB0614603C8' /* GetWordNameForRegister */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "AD14A1A35FF4"
               %UID 'AD14A1A35FF4'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // AD14A1A35FF4
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'B9064AB2D227'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_pnlHelp_Push' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_pnlHelp_Push"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_lblHelp"
            %UID '83E8C1A835A2'
            %SUMMARY 'Слово словаря для идентификатора контрола lblHelp'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::lblHelp TryFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::lblHelp'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '508527F30183' /* TtfwControlString */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '4DDFD2EA0116' /* GetString */
             U$ '52A086150180' /* RegisterInEngine */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "71A503DFE8AD"
               %UID '71A503DFE8AD'
               %TARGET U$ '4AE8541A01AE' /* TvtLabel */
              ; // 71A503DFE8AD
              SUMMONED <<uses>> "EF49AD6CBFD9"
               %UID 'EF49AD6CBFD9'
               %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
              ; // EF49AD6CBFD9
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '9ECA6690093C'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_lblHelp' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_lblHelp"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_lblHelp_Push"
            %UID 'ACA53177E8C9'
            %SUMMARY 'Слово словаря для контрола lblHelp'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::lblHelp:push pop:control:SetFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::lblHelp:push'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4F2141AD0203' /* "byname_control_push" */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DAEEDE10285' /* DoDoIt */
             U$ '4DB0614603C8' /* GetWordNameForRegister */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "8E42A3B98698"
               %UID '8E42A3B98698'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 8E42A3B98698
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'FD8EA83B45C9'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_lblHelp_Push' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_lblHelp_Push"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_gbComment"
            %UID '9657597A81C9'
            %SUMMARY 'Слово словаря для идентификатора контрола gbComment'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::gbComment TryFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::gbComment'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '508527F30183' /* TtfwControlString */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '4DDFD2EA0116' /* GetString */
             U$ '52A086150180' /* RegisterInEngine */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "BCAF9CDC793D"
               %UID 'BCAF9CDC793D'
               %TARGET U$ '4AC608E40294' /* TvtGroupBox */
              ; // BCAF9CDC793D
              SUMMONED <<uses>> "DFB6F8B580C3"
               %UID 'DFB6F8B580C3'
               %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
              ; // DFB6F8B580C3
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'AFF20C7D7E21'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_gbComment' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_gbComment"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_gbComment_Push"
            %UID 'B9AAAEC2E11B'
            %SUMMARY 'Слово словаря для контрола gbComment'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::gbComment:push pop:control:SetFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::gbComment:push'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4F2141AD0203' /* "byname_control_push" */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DAEEDE10285' /* DoDoIt */
             U$ '4DB0614603C8' /* GetWordNameForRegister */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "DE1E744B9F73"
               %UID 'DE1E744B9F73'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // DE1E744B9F73
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '5A22AC54040D'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_gbComment_Push' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_gbComment_Push"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_mComment"
            %UID 'E2078C247487'
            %SUMMARY 'Слово словаря для идентификатора контрола mComment'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::mComment TryFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::mComment'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '508527F30183' /* TtfwControlString */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '4DDFD2EA0116' /* GetString */
             U$ '52A086150180' /* RegisterInEngine */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "E66C08903C99"
               %UID 'E66C08903C99'
               %TARGET U$ '4AC5D3380185' /* TeeMemoWithEditOperations */
              ; // E66C08903C99
              SUMMONED <<uses>> "A64E620ADCD2"
               %UID 'A64E620ADCD2'
               %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
              ; // A64E620ADCD2
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'B3893BF2E7F7'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_mComment' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_mComment"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "Tkw_ConsultationMark_Control_mComment_Push"
            %UID 'DBA48F967BE6'
            %SUMMARY 'Слово словаря для контрола mComment'#13#10'----'#13#10'*Пример использования*:'#13#10'{code}'#13#10'контрол::mComment:push pop:control:SetFocus ASSERT'#13#10'{code}' ;
            %META
             %upv "NameForScript" 'контрол::mComment:push'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '54DB92A80279' /* ScriptEngine$RTLandVCL */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '4F2141AD0203' /* "byname_control_push" */
            ; // %INHERITS
            %OVERRIDES
             U$ '4DAEEDE10285' /* DoDoIt */
             U$ '4DB0614603C8' /* GetWordNameForRegister */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "5D8D21149469"
               %UID '5D8D21149469'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 5D8D21149469
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'DAAACC279846'
               %SUMMARY 'Регистрация Tkw_ConsultationMark_Control_mComment_Push' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "Tkw_ConsultationMark_Control_mComment_Push"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "en_ConsultationMark_gbMark"
            %UID '08E015178ADF'
            %SUMMARY 'Слово скрипта .Ten_ConsultationMark.gbMark'#13#10'{panel}Контрол gbMark формы Ten_ConsultationMark{panel}'#13#10'*Тип результата:* TvtGroupBox'#13#10'*Пример:*'#13#10'{code}'#13#10'OBJECT VAR l_TvtGroupBox'#13#10' aen_ConsultationMark .Ten_ConsultationMark.gbMark >>> l_TvtGroupBox'#13#10'{code} ' ;
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.gbMark'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
             U$ '4ABCFB180302' /* View */
             U$ '54CF97B10370' /* ScriptEngine$Core */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '5619169603BE' /* TtfwPropertyLike */
            ; // %INHERITS
            %REALIZES
             U$ '4DAEEDE10285' /* DoDoIt */
            ; // %REALIZES
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '52D00B00031A' /* SetValuePrim */
             U$ '551544E2001A' /* GetResultTypeInfo */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "3F168E3759BA"
               %UID '3F168E3759BA'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 3F168E3759BA
              SUMMONED <<uses>> "4A911AA1A93C"
               %UID '4A911AA1A93C'
               %TARGET U$ '4767748503B5' /* TTypeInfo */
              ; // 4A911AA1A93C
              SUMMONED <<uses>> "308F6842CE90"
               %UID '308F6842CE90'
               %TARGET U$ '47877EB202FB' /* SysUtils */
              ; // 308F6842CE90
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> gbMark
               %UID 'A23E58F755E1'
               %SUMMARY 'Реализация слова скрипта .Ten_ConsultationMark.gbMark' ;
               %TARGET U$ '4AC608E40294' /* TvtGroupBox */
               %TOBEINCLUDED
                U$ '467A75D90346' /* VT */
                U$ '4ABCFB180302' /* View */
                U$ '54CF97B10370' /* ScriptEngine$Core */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aCtx
                  %UID 'CE54C3302129'
                  %TARGET U$ '4DB0091E033E' /* TtfwContext */
                  %TOBEINCLUDED
                   U$ '54CF97B10370' /* ScriptEngine$Core */
                  ; // %TOBEINCLUDED
                 ; // aCtx
                 SUMMONED <<in>> aen_ConsultationMark
                  %UID 'CE54C330212A'
                  %TARGET U$ '4AB8D1DB01FD' /* ConsultationMark */
                  %TOBEINCLUDED
                   U$ '4ABCFB180302' /* View */
                  ; // %TOBEINCLUDED
                 ; // aen_ConsultationMark
               ; // %PARAMETERS
              ; // gbMark
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'BEEB5C3F6906'
               %SUMMARY 'Регистрация en_ConsultationMark_gbMark' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "en_ConsultationMark_gbMark"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "en_ConsultationMark_rbNotSure"
            %UID '102A22C548B7'
            %SUMMARY 'Слово скрипта .Ten_ConsultationMark.rbNotSure'#13#10'{panel}Контрол rbNotSure формы Ten_ConsultationMark{panel}'#13#10'*Тип результата:* TvtRadioButton'#13#10'*Пример:*'#13#10'{code}'#13#10'OBJECT VAR l_TvtRadioButton'#13#10' aen_ConsultationMark .Ten_ConsultationMark.rbNotSure >>> l_TvtRadioButton'#13#10'{code} ' ;
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbNotSure'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
             U$ '4ABCFB180302' /* View */
             U$ '54CF97B10370' /* ScriptEngine$Core */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '5619169603BE' /* TtfwPropertyLike */
            ; // %INHERITS
            %REALIZES
             U$ '4DAEEDE10285' /* DoDoIt */
            ; // %REALIZES
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '52D00B00031A' /* SetValuePrim */
             U$ '551544E2001A' /* GetResultTypeInfo */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "56BE1A10B386"
               %UID '56BE1A10B386'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 56BE1A10B386
              SUMMONED <<uses>> "0ECCDFA27582"
               %UID '0ECCDFA27582'
               %TARGET U$ '4767748503B5' /* TTypeInfo */
              ; // 0ECCDFA27582
              SUMMONED <<uses>> "AECCB453BC0B"
               %UID 'AECCB453BC0B'
               %TARGET U$ '47877EB202FB' /* SysUtils */
              ; // AECCB453BC0B
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> rbNotSure
               %UID '2CE3B78803F7'
               %SUMMARY 'Реализация слова скрипта .Ten_ConsultationMark.rbNotSure' ;
               %TARGET U$ '517941E500BF' /* TvtRadioButton */
               %TOBEINCLUDED
                U$ '467A75D90346' /* VT */
                U$ '4ABCFB180302' /* View */
                U$ '54CF97B10370' /* ScriptEngine$Core */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aCtx
                  %UID '853218703871'
                  %TARGET U$ '4DB0091E033E' /* TtfwContext */
                  %TOBEINCLUDED
                   U$ '54CF97B10370' /* ScriptEngine$Core */
                  ; // %TOBEINCLUDED
                 ; // aCtx
                 SUMMONED <<in>> aen_ConsultationMark
                  %UID '853218703872'
                  %TARGET U$ '4AB8D1DB01FD' /* ConsultationMark */
                  %TOBEINCLUDED
                   U$ '4ABCFB180302' /* View */
                  ; // %TOBEINCLUDED
                 ; // aen_ConsultationMark
               ; // %PARAMETERS
              ; // rbNotSure
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '1CEB6C8E222D'
               %SUMMARY 'Регистрация en_ConsultationMark_rbNotSure' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "en_ConsultationMark_rbNotSure"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "en_ConsultationMark_rbTwo"
            %UID '1361F312A549'
            %SUMMARY 'Слово скрипта .Ten_ConsultationMark.rbTwo'#13#10'{panel}Контрол rbTwo формы Ten_ConsultationMark{panel}'#13#10'*Тип результата:* TvtRadioButton'#13#10'*Пример:*'#13#10'{code}'#13#10'OBJECT VAR l_TvtRadioButton'#13#10' aen_ConsultationMark .Ten_ConsultationMark.rbTwo >>> l_TvtRadioButton'#13#10'{code} ' ;
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbTwo'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
             U$ '4ABCFB180302' /* View */
             U$ '54CF97B10370' /* ScriptEngine$Core */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '5619169603BE' /* TtfwPropertyLike */
            ; // %INHERITS
            %REALIZES
             U$ '4DAEEDE10285' /* DoDoIt */
            ; // %REALIZES
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '52D00B00031A' /* SetValuePrim */
             U$ '551544E2001A' /* GetResultTypeInfo */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "F7C270A13720"
               %UID 'F7C270A13720'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // F7C270A13720
              SUMMONED <<uses>> "33E3830B72E6"
               %UID '33E3830B72E6'
               %TARGET U$ '4767748503B5' /* TTypeInfo */
              ; // 33E3830B72E6
              SUMMONED <<uses>> "15270E34C5EC"
               %UID '15270E34C5EC'
               %TARGET U$ '47877EB202FB' /* SysUtils */
              ; // 15270E34C5EC
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> rbTwo
               %UID '654BA6F682D0'
               %SUMMARY 'Реализация слова скрипта .Ten_ConsultationMark.rbTwo' ;
               %TARGET U$ '517941E500BF' /* TvtRadioButton */
               %TOBEINCLUDED
                U$ '467A75D90346' /* VT */
                U$ '4ABCFB180302' /* View */
                U$ '54CF97B10370' /* ScriptEngine$Core */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aCtx
                  %UID '6562A1D77BB8'
                  %TARGET U$ '4DB0091E033E' /* TtfwContext */
                  %TOBEINCLUDED
                   U$ '54CF97B10370' /* ScriptEngine$Core */
                  ; // %TOBEINCLUDED
                 ; // aCtx
                 SUMMONED <<in>> aen_ConsultationMark
                  %UID '6562A1D77BB9'
                  %TARGET U$ '4AB8D1DB01FD' /* ConsultationMark */
                  %TOBEINCLUDED
                   U$ '4ABCFB180302' /* View */
                  ; // %TOBEINCLUDED
                 ; // aen_ConsultationMark
               ; // %PARAMETERS
              ; // rbTwo
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'FF9FE0A064D0'
               %SUMMARY 'Регистрация en_ConsultationMark_rbTwo' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "en_ConsultationMark_rbTwo"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "en_ConsultationMark_rbThree"
            %UID 'DCFA687F0AB6'
            %SUMMARY 'Слово скрипта .Ten_ConsultationMark.rbThree'#13#10'{panel}Контрол rbThree формы Ten_ConsultationMark{panel}'#13#10'*Тип результата:* TvtRadioButton'#13#10'*Пример:*'#13#10'{code}'#13#10'OBJECT VAR l_TvtRadioButton'#13#10' aen_ConsultationMark .Ten_ConsultationMark.rbThree >>> l_TvtRadioButton'#13#10'{code} ' ;
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbThree'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
             U$ '4ABCFB180302' /* View */
             U$ '54CF97B10370' /* ScriptEngine$Core */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '5619169603BE' /* TtfwPropertyLike */
            ; // %INHERITS
            %REALIZES
             U$ '4DAEEDE10285' /* DoDoIt */
            ; // %REALIZES
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '52D00B00031A' /* SetValuePrim */
             U$ '551544E2001A' /* GetResultTypeInfo */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "47840FBD756A"
               %UID '47840FBD756A'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 47840FBD756A
              SUMMONED <<uses>> "9A8108367562"
               %UID '9A8108367562'
               %TARGET U$ '4767748503B5' /* TTypeInfo */
              ; // 9A8108367562
              SUMMONED <<uses>> "F6FCB61EDA85"
               %UID 'F6FCB61EDA85'
               %TARGET U$ '47877EB202FB' /* SysUtils */
              ; // F6FCB61EDA85
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> rbThree
               %UID '84B5FE5A6382'
               %SUMMARY 'Реализация слова скрипта .Ten_ConsultationMark.rbThree' ;
               %TARGET U$ '517941E500BF' /* TvtRadioButton */
               %TOBEINCLUDED
                U$ '467A75D90346' /* VT */
                U$ '4ABCFB180302' /* View */
                U$ '54CF97B10370' /* ScriptEngine$Core */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aCtx
                  %UID '8D26A86AF1D7'
                  %TARGET U$ '4DB0091E033E' /* TtfwContext */
                  %TOBEINCLUDED
                   U$ '54CF97B10370' /* ScriptEngine$Core */
                  ; // %TOBEINCLUDED
                 ; // aCtx
                 SUMMONED <<in>> aen_ConsultationMark
                  %UID '8D26A86AF1D8'
                  %TARGET U$ '4AB8D1DB01FD' /* ConsultationMark */
                  %TOBEINCLUDED
                   U$ '4ABCFB180302' /* View */
                  ; // %TOBEINCLUDED
                 ; // aen_ConsultationMark
               ; // %PARAMETERS
              ; // rbThree
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '36EE2ABE58E3'
               %SUMMARY 'Регистрация en_ConsultationMark_rbThree' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "en_ConsultationMark_rbThree"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "en_ConsultationMark_rbFour"
            %UID '017B75B3B73E'
            %SUMMARY 'Слово скрипта .Ten_ConsultationMark.rbFour'#13#10'{panel}Контрол rbFour формы Ten_ConsultationMark{panel}'#13#10'*Тип результата:* TvtRadioButton'#13#10'*Пример:*'#13#10'{code}'#13#10'OBJECT VAR l_TvtRadioButton'#13#10' aen_ConsultationMark .Ten_ConsultationMark.rbFour >>> l_TvtRadioButton'#13#10'{code} ' ;
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbFour'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
             U$ '4ABCFB180302' /* View */
             U$ '54CF97B10370' /* ScriptEngine$Core */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '5619169603BE' /* TtfwPropertyLike */
            ; // %INHERITS
            %REALIZES
             U$ '4DAEEDE10285' /* DoDoIt */
            ; // %REALIZES
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '52D00B00031A' /* SetValuePrim */
             U$ '551544E2001A' /* GetResultTypeInfo */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "7D90E29F61A5"
               %UID '7D90E29F61A5'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 7D90E29F61A5
              SUMMONED <<uses>> "A9F1CD25F110"
               %UID 'A9F1CD25F110'
               %TARGET U$ '4767748503B5' /* TTypeInfo */
              ; // A9F1CD25F110
              SUMMONED <<uses>> "BDA945BE175B"
               %UID 'BDA945BE175B'
               %TARGET U$ '47877EB202FB' /* SysUtils */
              ; // BDA945BE175B
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> rbFour
               %UID 'C5051E3C904E'
               %SUMMARY 'Реализация слова скрипта .Ten_ConsultationMark.rbFour' ;
               %TARGET U$ '517941E500BF' /* TvtRadioButton */
               %TOBEINCLUDED
                U$ '467A75D90346' /* VT */
                U$ '4ABCFB180302' /* View */
                U$ '54CF97B10370' /* ScriptEngine$Core */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aCtx
                  %UID 'B57D55A9D8AC'
                  %TARGET U$ '4DB0091E033E' /* TtfwContext */
                  %TOBEINCLUDED
                   U$ '54CF97B10370' /* ScriptEngine$Core */
                  ; // %TOBEINCLUDED
                 ; // aCtx
                 SUMMONED <<in>> aen_ConsultationMark
                  %UID 'B57D55A9D8AD'
                  %TARGET U$ '4AB8D1DB01FD' /* ConsultationMark */
                  %TOBEINCLUDED
                   U$ '4ABCFB180302' /* View */
                  ; // %TOBEINCLUDED
                 ; // aen_ConsultationMark
               ; // %PARAMETERS
              ; // rbFour
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '688DB8AC2B7C'
               %SUMMARY 'Регистрация en_ConsultationMark_rbFour' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "en_ConsultationMark_rbFour"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "en_ConsultationMark_rbFive"
            %UID 'B408A9A1DAB5'
            %SUMMARY 'Слово скрипта .Ten_ConsultationMark.rbFive'#13#10'{panel}Контрол rbFive формы Ten_ConsultationMark{panel}'#13#10'*Тип результата:* TvtRadioButton'#13#10'*Пример:*'#13#10'{code}'#13#10'OBJECT VAR l_TvtRadioButton'#13#10' aen_ConsultationMark .Ten_ConsultationMark.rbFive >>> l_TvtRadioButton'#13#10'{code} ' ;
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.rbFive'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
             U$ '4ABCFB180302' /* View */
             U$ '54CF97B10370' /* ScriptEngine$Core */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '5619169603BE' /* TtfwPropertyLike */
            ; // %INHERITS
            %REALIZES
             U$ '4DAEEDE10285' /* DoDoIt */
            ; // %REALIZES
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '52D00B00031A' /* SetValuePrim */
             U$ '551544E2001A' /* GetResultTypeInfo */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "54742959948D"
               %UID '54742959948D'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 54742959948D
              SUMMONED <<uses>> "278FDAF8C2E3"
               %UID '278FDAF8C2E3'
               %TARGET U$ '4767748503B5' /* TTypeInfo */
              ; // 278FDAF8C2E3
              SUMMONED <<uses>> "E88E4C8E6482"
               %UID 'E88E4C8E6482'
               %TARGET U$ '47877EB202FB' /* SysUtils */
              ; // E88E4C8E6482
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> rbFive
               %UID 'C87CB7ECD919'
               %SUMMARY 'Реализация слова скрипта .Ten_ConsultationMark.rbFive' ;
               %TARGET U$ '517941E500BF' /* TvtRadioButton */
               %TOBEINCLUDED
                U$ '467A75D90346' /* VT */
                U$ '4ABCFB180302' /* View */
                U$ '54CF97B10370' /* ScriptEngine$Core */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aCtx
                  %UID 'D4C1BD200DAB'
                  %TARGET U$ '4DB0091E033E' /* TtfwContext */
                  %TOBEINCLUDED
                   U$ '54CF97B10370' /* ScriptEngine$Core */
                  ; // %TOBEINCLUDED
                 ; // aCtx
                 SUMMONED <<in>> aen_ConsultationMark
                  %UID 'D4C1BD200DAC'
                  %TARGET U$ '4AB8D1DB01FD' /* ConsultationMark */
                  %TOBEINCLUDED
                   U$ '4ABCFB180302' /* View */
                  ; // %TOBEINCLUDED
                 ; // aen_ConsultationMark
               ; // %PARAMETERS
              ; // rbFive
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '8D0B84D34458'
               %SUMMARY 'Регистрация en_ConsultationMark_rbFive' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "en_ConsultationMark_rbFive"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "en_ConsultationMark_pnlHelp"
            %UID '85E1FBE51015'
            %SUMMARY 'Слово скрипта .Ten_ConsultationMark.pnlHelp'#13#10'{panel}Контрол pnlHelp формы Ten_ConsultationMark{panel}'#13#10'*Тип результата:* TvtPanel'#13#10'*Пример:*'#13#10'{code}'#13#10'OBJECT VAR l_TvtPanel'#13#10' aen_ConsultationMark .Ten_ConsultationMark.pnlHelp >>> l_TvtPanel'#13#10'{code} ' ;
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.pnlHelp'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '4ABCFB180302' /* View */
             U$ '547CC9D40158' /* VT$Panels */
             U$ '54CF97B10370' /* ScriptEngine$Core */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '5619169603BE' /* TtfwPropertyLike */
            ; // %INHERITS
            %REALIZES
             U$ '4DAEEDE10285' /* DoDoIt */
            ; // %REALIZES
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '52D00B00031A' /* SetValuePrim */
             U$ '551544E2001A' /* GetResultTypeInfo */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "5DCA22623C9D"
               %UID '5DCA22623C9D'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 5DCA22623C9D
              SUMMONED <<uses>> "455F380498CD"
               %UID '455F380498CD'
               %TARGET U$ '4767748503B5' /* TTypeInfo */
              ; // 455F380498CD
              SUMMONED <<uses>> "F22EB8C020E4"
               %UID 'F22EB8C020E4'
               %TARGET U$ '47877EB202FB' /* SysUtils */
              ; // F22EB8C020E4
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> pnlHelp
               %UID '6D3336D8B01D'
               %SUMMARY 'Реализация слова скрипта .Ten_ConsultationMark.pnlHelp' ;
               %TARGET U$ '4A7961A701CF' /* TvtPanel */
               %TOBEINCLUDED
                U$ '4ABCFB180302' /* View */
                U$ '547CC9D40158' /* VT$Panels */
                U$ '54CF97B10370' /* ScriptEngine$Core */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aCtx
                  %UID 'AA63B76EDCAF'
                  %TARGET U$ '4DB0091E033E' /* TtfwContext */
                  %TOBEINCLUDED
                   U$ '54CF97B10370' /* ScriptEngine$Core */
                  ; // %TOBEINCLUDED
                 ; // aCtx
                 SUMMONED <<in>> aen_ConsultationMark
                  %UID 'AA63B76EDCB0'
                  %TARGET U$ '4AB8D1DB01FD' /* ConsultationMark */
                  %TOBEINCLUDED
                   U$ '4ABCFB180302' /* View */
                  ; // %TOBEINCLUDED
                 ; // aen_ConsultationMark
               ; // %PARAMETERS
              ; // pnlHelp
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '3EAF73FDF849'
               %SUMMARY 'Регистрация en_ConsultationMark_pnlHelp' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "en_ConsultationMark_pnlHelp"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "en_ConsultationMark_lblHelp"
            %UID 'BD995E557E53'
            %SUMMARY 'Слово скрипта .Ten_ConsultationMark.lblHelp'#13#10'{panel}Контрол lblHelp формы Ten_ConsultationMark{panel}'#13#10'*Тип результата:* TvtLabel'#13#10'*Пример:*'#13#10'{code}'#13#10'OBJECT VAR l_TvtLabel'#13#10' aen_ConsultationMark .Ten_ConsultationMark.lblHelp >>> l_TvtLabel'#13#10'{code} ' ;
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.lblHelp'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
             U$ '4ABCFB180302' /* View */
             U$ '54CF97B10370' /* ScriptEngine$Core */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '5619169603BE' /* TtfwPropertyLike */
            ; // %INHERITS
            %REALIZES
             U$ '4DAEEDE10285' /* DoDoIt */
            ; // %REALIZES
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '52D00B00031A' /* SetValuePrim */
             U$ '551544E2001A' /* GetResultTypeInfo */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "4D66DB790DFA"
               %UID '4D66DB790DFA'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 4D66DB790DFA
              SUMMONED <<uses>> "4D69A00AEC92"
               %UID '4D69A00AEC92'
               %TARGET U$ '4767748503B5' /* TTypeInfo */
              ; // 4D69A00AEC92
              SUMMONED <<uses>> "0A94AE9368E5"
               %UID '0A94AE9368E5'
               %TARGET U$ '47877EB202FB' /* SysUtils */
              ; // 0A94AE9368E5
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> lblHelp
               %UID 'C16FF77D9FFB'
               %SUMMARY 'Реализация слова скрипта .Ten_ConsultationMark.lblHelp' ;
               %TARGET U$ '4AE8541A01AE' /* TvtLabel */
               %TOBEINCLUDED
                U$ '467A75D90346' /* VT */
                U$ '4ABCFB180302' /* View */
                U$ '54CF97B10370' /* ScriptEngine$Core */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aCtx
                  %UID 'E798B5E77DCD'
                  %TARGET U$ '4DB0091E033E' /* TtfwContext */
                  %TOBEINCLUDED
                   U$ '54CF97B10370' /* ScriptEngine$Core */
                  ; // %TOBEINCLUDED
                 ; // aCtx
                 SUMMONED <<in>> aen_ConsultationMark
                  %UID 'E798B5E77DCE'
                  %TARGET U$ '4AB8D1DB01FD' /* ConsultationMark */
                  %TOBEINCLUDED
                   U$ '4ABCFB180302' /* View */
                  ; // %TOBEINCLUDED
                 ; // aen_ConsultationMark
               ; // %PARAMETERS
              ; // lblHelp
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '065E376A7D01'
               %SUMMARY 'Регистрация en_ConsultationMark_lblHelp' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "en_ConsultationMark_lblHelp"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "en_ConsultationMark_gbComment"
            %UID '5E131FAEC04F'
            %SUMMARY 'Слово скрипта .Ten_ConsultationMark.gbComment'#13#10'{panel}Контрол gbComment формы Ten_ConsultationMark{panel}'#13#10'*Тип результата:* TvtGroupBox'#13#10'*Пример:*'#13#10'{code}'#13#10'OBJECT VAR l_TvtGroupBox'#13#10' aen_ConsultationMark .Ten_ConsultationMark.gbComment >>> l_TvtGroupBox'#13#10'{code} ' ;
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.gbComment'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '467A75D90346' /* VT */
             U$ '4ABCFB180302' /* View */
             U$ '54CF97B10370' /* ScriptEngine$Core */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '5619169603BE' /* TtfwPropertyLike */
            ; // %INHERITS
            %REALIZES
             U$ '4DAEEDE10285' /* DoDoIt */
            ; // %REALIZES
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '52D00B00031A' /* SetValuePrim */
             U$ '551544E2001A' /* GetResultTypeInfo */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "CAA333A76FA6"
               %UID 'CAA333A76FA6'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // CAA333A76FA6
              SUMMONED <<uses>> "F8DF237D5B0E"
               %UID 'F8DF237D5B0E'
               %TARGET U$ '4767748503B5' /* TTypeInfo */
              ; // F8DF237D5B0E
              SUMMONED <<uses>> "EA8C93D04C04"
               %UID 'EA8C93D04C04'
               %TARGET U$ '47877EB202FB' /* SysUtils */
              ; // EA8C93D04C04
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> gbComment
               %UID '1661EACD5277'
               %SUMMARY 'Реализация слова скрипта .Ten_ConsultationMark.gbComment' ;
               %TARGET U$ '4AC608E40294' /* TvtGroupBox */
               %TOBEINCLUDED
                U$ '467A75D90346' /* VT */
                U$ '4ABCFB180302' /* View */
                U$ '54CF97B10370' /* ScriptEngine$Core */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aCtx
                  %UID '7377C3F5A74C'
                  %TARGET U$ '4DB0091E033E' /* TtfwContext */
                  %TOBEINCLUDED
                   U$ '54CF97B10370' /* ScriptEngine$Core */
                  ; // %TOBEINCLUDED
                 ; // aCtx
                 SUMMONED <<in>> aen_ConsultationMark
                  %UID '7377C3F5A74D'
                  %TARGET U$ '4AB8D1DB01FD' /* ConsultationMark */
                  %TOBEINCLUDED
                   U$ '4ABCFB180302' /* View */
                  ; // %TOBEINCLUDED
                 ; // aen_ConsultationMark
               ; // %PARAMETERS
              ; // gbComment
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID '724228732A0C'
               %SUMMARY 'Регистрация en_ConsultationMark_gbComment' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "en_ConsultationMark_gbComment"
           SUMMONED PRIVATE FINAL <<ScriptKeyword>> "en_ConsultationMark_mComment"
            %UID '780807DC0F9A'
            %SUMMARY 'Слово скрипта .Ten_ConsultationMark.mComment'#13#10'{panel}Контрол mComment формы Ten_ConsultationMark{panel}'#13#10'*Тип результата:* TeeMemoWithEditOperations'#13#10'*Пример:*'#13#10'{code}'#13#10'OBJECT VAR l_TeeMemoWithEditOperations'#13#10' aen_ConsultationMark .Ten_ConsultationMark.mComment >>> l_TeeMemoWithEditOperations'#13#10'{code} ' ;
            %META
             %upv "NameForScript" '.Ten_ConsultationMark.mComment'
             %upv "needs InstanceR" 'undefined'
             %upv "needs script" 'undefined'
             %upv "no hands" false
             %upv "register in scripts" 'undefined'
            ; // %META
            %TOBEINCLUDED
             U$ '4680E7D50168' /* "Everest Engine" */
             U$ '4ABCFB180302' /* View */
             U$ '54CF97B10370' /* ScriptEngine$Core */
            ; // %TOBEINCLUDED
            %INHERITS
             U$ '5619169603BE' /* TtfwPropertyLike */
            ; // %INHERITS
            %REALIZES
             U$ '4DAEEDE10285' /* DoDoIt */
            ; // %REALIZES
            %OVERRIDES
             U$ '4DB0614603C8' /* GetWordNameForRegister */
             U$ '52D00B00031A' /* SetValuePrim */
             U$ '551544E2001A' /* GetResultTypeInfo */
            ; // %OVERRIDES
            %LINKS
              SUMMONED <<uses>> "09AFE6662CDE"
               %UID '09AFE6662CDE'
               %TARGET U$ '4DB0091E033E' /* TtfwContext */
              ; // 09AFE6662CDE
              SUMMONED <<uses>> "EC756C3519F6"
               %UID 'EC756C3519F6'
               %TARGET U$ '4767748503B5' /* TTypeInfo */
              ; // EC756C3519F6
              SUMMONED <<uses>> "AF903648ED13"
               %UID 'AF903648ED13'
               %TARGET U$ '47877EB202FB' /* SysUtils */
              ; // AF903648ED13
            ; // %LINKS
            %OPERATIONS
              SUMMONED PRIVATE FINAL <<Operation>> mComment
               %UID 'B825D48A3113'
               %SUMMARY 'Реализация слова скрипта .Ten_ConsultationMark.mComment' ;
               %TARGET U$ '4AC5D3380185' /* TeeMemoWithEditOperations */
               %TOBEINCLUDED
                U$ '4680E7D50168' /* "Everest Engine" */
                U$ '4ABCFB180302' /* View */
                U$ '54CF97B10370' /* ScriptEngine$Core */
               ; // %TOBEINCLUDED
               %PARAMETERS
                 SUMMONED <<in>> aCtx
                  %UID 'BEA0BFA0D2D5'
                  %TARGET U$ '4DB0091E033E' /* TtfwContext */
                  %TOBEINCLUDED
                   U$ '54CF97B10370' /* ScriptEngine$Core */
                  ; // %TOBEINCLUDED
                 ; // aCtx
                 SUMMONED <<in>> aen_ConsultationMark
                  %UID 'BEA0BFA0D2D6'
                  %TARGET U$ '4AB8D1DB01FD' /* ConsultationMark */
                  %TOBEINCLUDED
                   U$ '4ABCFB180302' /* View */
                  ; // %TOBEINCLUDED
                 ; // aen_ConsultationMark
               ; // %PARAMETERS
              ; // mComment
              SUMMONED PRIVATE FINAL <<ini>> Ini_Reg
               %UID 'C839E57FB28F'
               %SUMMARY 'Регистрация en_ConsultationMark_mComment' ;
              ; // Ini_Reg
            ; // %OPERATIONS
           ; // "en_ConsultationMark_mComment"
         ; // %CHILDREN
        ; // ConsultationMarkKeywordsPack
      ; // %CHILDREN
     ; // Consultation$FP
   ; // %CHILDREN
  ; // Consultation
 ; // %CHILDREN
; // View