*****************************************************************
**************** DO NOT EDIT THIS FILE ********************
*****************************************************************
RTAuthentication.csv
10
V
2C
L
*** BEGIN FIELD SPECIFICATIONS ***
1,State,INTER,INTER,15,S,0,0,1,0,1,7
2,Class,INTER,INTER,15,S,0,0,1,0,1,7
3,Subclass,INTER,INTER,15,S,0,0,1,0,1,7
4,Service,INTER,INTER,15,S,0,0,1,0,1,7
5,Login,INTER,INTER,15,S,0,0,1,0,1,7
6,Password,INTER,INTER,15,S,0,0,1,0,1,7
*** END FIELD SPECIFICATIONS ***