<<VCMViews>> Consultation$View
 %UID '4CF380E402F8'
 %DEPENDS
  U$ '469F3E37025A' /* Rtl */
  U$ '4A9FFD3F01AD' /* Search */
  U$ '561F9F7D02A7' /* ScriptEngine */
 ; // %DEPENDS
 %META
  %upv "exec mode" 'concluded'
  %upv "gui" 'prj'
  %upv "is namespace" true
  %upv "vendor" 'none'
 ; // %META
 %TOBEINCLUDED
  U$ '469F3E37025A' /* Rtl */
  U$ '4A9FFD3F01AD' /* Search */
  U$ '4B63155B0328' /* MDProcess$ForDelphi */
 ; // %TOBEINCLUDED
 %CHILDREN
  
  <<VCMForms>> HAFPainters
   %UID '4CF3810D0038'
   %DEPENDS
    U$ '491DCA2C00A9' /* Search */
    U$ '4AB0997B00A2' /* Common */
    U$ '561F9F7D02A7' /* ScriptEngine */
   ; // %DEPENDS
   %TOBEINCLUDED
    U$ '469F3E37025A' /* Rtl */
    U$ '4A9FFD3F01AD' /* Search */
    U$ '4B63155B0328' /* MDProcess$ForDelphi */
   ; // %TOBEINCLUDED
   %CHILDREN
    
     <<VCMDataModule>> nsConsultationHAFPainterImages
      %UID '4CF37C170269'
      %META
       %upv "NeedsHackRef" true
       %upv "author" 'Люлин А.В.'
       %upv "base wnd class" 'CWnd'
       %upv "finished" false
       %upv "finished dfm" true
       %upv "needs InstanceR" 'undefined'
       %upv "needs script" 'undefined'
       %upv "no hands" false
       %upv "register in scripts" 'undefined'
       %upv "resizeable" false
      ; // %META
      %TOBEINCLUDED
       U$ '469F3E37025A' /* Rtl */
       U$ '4A9FFD3F01AD' /* Search */
      ; // %TOBEINCLUDED
      %INHERITS
       U$ '4AAA214A0250' /* TDataModule */
      ; // %INHERITS
      %LINKS
        SUMMONED <<uses>> "0DB87C32D2CD"
         %UID '0DB87C32D2CD'
         %TARGET U$ '561F9F9400BC' /* TtfwClassRef */
        ; // 0DB87C32D2CD
      ; // %LINKS
      %OPERATIONS
        SUMMONED PRIVATE FINAL <<ini>> Ini_Reg_Class
         %UID 'A9BB14C0B36A'
         %SUMMARY 'Регистрация nsConsultationHAFPainterImages' ;
         %META
          %upv "ifndef" 'NoScripts'
         ; // %META
        ; // Ini_Reg_Class
      ; // %OPERATIONS
      %CHILDREN
       
        <<SimpleClass>> TnsConsultationHAFPainter
         %UID '4CF37B3401D9'
         %META
          %upv "author" 'Люлин А.В.'
          %upv "finished" false
          %upv "needs InstanceR" 'undefined'
          %upv "needs script" 'undefined'
          %upv "no hands" false
          %upv "register in scripts" 'undefined'
          %upv "started" '2010/10/26 13:02:52'
         ; // %META
         %TOBEINCLUDED
          U$ '4A9FFD3F01AD' /* Search */
         ; // %TOBEINCLUDED
         %INHERITS
          U$ '47F2317F015E' /* TnsHAFPainter */
         ; // %INHERITS
        ; // TnsConsultationHAFPainter
      ; // %CHILDREN
     ; // nsConsultationHAFPainterImages
   ; // %CHILDREN
  ; // HAFPainters
 ; // %CHILDREN
; // Consultation$View