gpack.o: gpack.cpp ../../../include/osdep.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/pack.h ../../../libs/gsscreen/src/toys.h
