%DISABLE_CASCADE_DICT

USES
 'W:\shared\models\NewSchool\Templates\TemplatesCore.tpl.script'
;

USES
 'w:\shared\models\NewSchool\MDProcess$CoreTemplates\MDProcess$CoreTemplates.model.script'
 'w:\shared\models\NewSchool\MDProcess$Templates\MDProcess$Templates.model.script'
 'w:\shared\models\NewSchool\MDProcess$ForDelphi\MDProcess$ForDelphi.model.script'
 'w:\shared\models\NewSchool\MDProcess$ForF1\MDProcess$ForF1.model.script'
 'w:\shared\models\NewSchool\Shared Delphi Rtl\Shared Delphi Rtl.model.script'
;

<<ProjectGroup>> Templates
 %UID '561FCFDC007C'
 %TOBEINCLUDED
  U$ '469F3E37025A' /* Rtl */
  U$ '46E138D901C5' /* CommonTemplates */
  U$ '46E13A3C030D' /* Meta */
  U$ '46E13A8E00AB' /* Integrated */
  U$ '46E801C00348' /* Core */
  U$ '47022A100167' /* CommonLang */
  U$ '47287F7D02CE' /* RequirementsLib */
  U$ '4729C18B01F4' /* DelphiSpecific */
  U$ '4729C41D032C' /* DelphiLang */
  U$ '4734A001000F' /* MetaTemplate */
  U$ '4734A46F005D' /* CoreTemplates */
  U$ '4742CFA001FA' /* CommonWithMeta */
  U$ '4742D02F0390' /* Integrated */
  U$ '47739263024C' /* WebLang */
  U$ '4773963E021D' /* AllGenerators */
  U$ '478DEEBE011B' /* ServerLib */
  U$ '484914FC025E' /* EVDTemplates */
  U$ '484918A30320' /* "Data Definition" */
  U$ '48C8B810028D' /* SettingsLib */
  U$ '492E8F8603C3' /* VCMTemplates */
  U$ '492E952D02A0' /* VCMSubsystemLayer */
  U$ '499970DC01D0' /* Testing */
  U$ '49F99E660011' /* Integrated */
  U$ '4B5F469E0305' /* VCMProjectLayer */
  U$ '4B5F4952010E' /* VCMModelLayer */
  U$ '4B62DE6100ED' /* VCMCore */
  U$ '4B62E29801AA' /* VCMControllersLayer */
  U$ '4B62EC84020F' /* VCMViewInterfacesLayer */
  U$ '4B62F01802BC' /* VCMViewImplementationLayer */
  U$ '4B63155B0328' /* MDProcess$ForDelphi */
  U$ '4F5E505102A8' /* MDProcess$Templates */
  U$ '52138AEC0388' /* MDProcess$CoreTemplates */
  U$ '561D2FE00378' /* SimpleTemplates */
  U$ '561D2FFF03CF' /* SimpleTemplatesLibrary */
 ; // %TOBEINCLUDED
; // Templates