!include "..\..\..\mk\msvc32.inc"

project:	gkdbcmp doc2htm gkdbcmp gkdumpi gkdumpkw gkgetdoc gready gregtst gsetname gsetrev gsstatus

basestat:	basestat.mak
		$(MAKE) basestat.mak CFG="basestat - Win32 $(MODE)" all
doc2htm:	doc2htm.mak
		$(MAKE) doc2htm.mak CFG="doc2htm - Win32 $(MODE)" all
gattrfix:	gattrfix.mak
		$(MAKE) gattrfix.mak CFG="gattrfix - Win32 $(MODE)" all
gchange:	gchange.mak
		$(MAKE) gchange.mak CFG="gchange - Win32 $(MODE)" all
gkdbcmp:	gkdbcmp.mak
		$(MAKE) gkdbcmp.mak CFG="gkdbcmp - Win32 $(MODE)" all
gkdumpi:	gkdumpi.mak
		$(MAKE) gkdumpi.mak CFG="gkdumpi - Win32 $(MODE)" all
gkdumpkw:	gkdumpkw.mak
		$(MAKE) gkdumpkw.mak CFG="gkdumpkw - Win32 $(MODE)" all
gkdumps:	gkdumps.mak
		$(MAKE) gkdumps.mak CFG="gkdumps - Win32 $(MODE)" all
gkgetdoc:	gkgetdoc.mak
		$(MAKE) gkgetdoc.mak CFG="gkgetdoc - Win32 $(MODE)" all
gready:		gready.mak
		$(MAKE) gready.mak CFG="gready - Win32 $(MODE)" all
gregtst:	gregtst.mak
		$(MAKE) gregtst.mak CFG="gregtst - Win32 $(MODE)" all
gsetname:	gsetname.mak
		$(MAKE) gsetname.mak CFG="gsetname - Win32 $(MODE)" all
gsetrev:	gsetrev.mak
		$(MAKE) gsetrev.mak CFG="gsetrev - Win32 $(MODE)" all
gsstat:		gsstat.mak
		$(MAKE) gsstat.mak CFG="gsstat - Win32 $(MODE)" all
gsstatus:	gsstatus.mak
		$(MAKE) gsstatus.mak CFG="gsstatus - Win32 $(MODE)" all
