// ***************************************************************************
//                                                                            
// Generated by the MTDORB IDL-to-Pascal Translator (1.0.1b1), 21.09.2010 14:21
//                                                                            
// Copyright (c) 2002 - 2004                                                  
// Millennium Group.                                                          
// Samara, Russia                                                             
//                                                                            
// All Rights Reserved                                                        
//                                                                            
// ***************************************************************************
// Compiled with parameters: " -iw:\ W:\MDProcess\ServerGate\Contents\Contents.idl" 
//                                                                            
unit Contents_int;

{$MINENUMSIZE 4}

interface

uses
  orbtypes, code_int, orb_int, RootSrv_int, except_int;

type

// module ServerGate types

// module Contents types

  IServerGate_Contents_PageNotFound = interface(IUserException)
  ['{09459816-05A0-4456-BEAF-EBE45EFBC006}']
  end;

  IServerGate_Contents_CantCreatePage = interface(IUserException)
  ['{A5818814-76E6-4EB8-A3E3-B70301DEDEFE}']
  end;

  IServerGate_Contents_PermissionException = interface(IUserException)
  ['{C408201A-7605-4BFD-B9E6-07E079B1317B}']
  end;

  TServerGate_Contents_PageId = longlong;

  TServerGate_Contents_MetadataEntity = record
    key : AnsiString;
    value : AnsiString;
  end;

  TServerGate_Contents_MetadataEntityList = Array of TServerGate_Contents_MetadataEntity;

  TServerGate_Contents_ByteBuffer = Array of octet;

  IServerGate_Contents_KPage = interface
  ['{7B020115-9D0B-46EA-AEFF-0225ACA56475}']
    function get_name: AnsiString;
    function get_id: TServerGate_Contents_PageId;
    function create_child(const name: AnsiString): IServerGate_Contents_KPage;
    procedure _free;
    function get_metadata(const name: AnsiString): AnsiString;
    procedure set_metadata(const name: AnsiString; const value: AnsiString);
    procedure append_wiki_text(const text: AnsiString);
    function get_wiki_text: AnsiString;
    function get_labels: AnsiString;
    procedure set_labels(const labels: AnsiString);
    procedure set_wiki_text(const wiki: AnsiString);
    procedure set_name(const name: AnsiString);
    procedure add_metadata(const metas: TServerGate_Contents_MetadataEntityList);
    procedure add_attachment(const name: AnsiString; const byte_stream: TServerGate_Contents_ByteBuffer; const content_type: AnsiString);
    procedure simulate_viewpage_action(const current_user_password: AnsiString);
  end;

  IServerGate_Contents_KPageFactoryManagerSrv = interface
  ['{7551A0D8-14F2-47A5-8767-5E99B262DAB5}']
    function get(const page_id: TServerGate_Contents_PageId): IServerGate_Contents_KPage;
  end;

implementation

end.
