// ***************************************************************************
//                                                                            
// Generated by the MTDORB IDL-to-Pascal Translator (1.0.1b1), 21.09.2010 14:20
//                                                                            
// Copyright (c) 2002 - 2004                                                  
// Millennium Group.                                                          
// Samara, Russia                                                             
//                                                                            
// All Rights Reserved                                                        
//                                                                            
// ***************************************************************************
// Compiled with parameters: " -iw:\ W:\shared\CoreSrv\RootSrv\RootSrv.idl" 
//                                                                            
unit RootSrv_int;

{$MINENUMSIZE 4}

interface

uses
  orbtypes, code_int, orb_int, except_int;

type

// module CoreSrv types

  ICoreSrv_NoActiveFactory = interface(IUserException)
  ['{3F105CE1-F369-4AA3-9B9A-D367334FC003}']
  end;

  ICoreSrv_ForeignObject = interface(IUserException)
  ['{DC7BF7C1-41DE-435E-886A-FE92E68C07F9}']
  end;

  ICoreSrv_UnknownFactoryKey = interface(IUserException)
  ['{272A4DCB-2CF5-4E82-8F50-F65BBAE2A94E}']
  end;

implementation

end.
