// ***************************************************************************
//                                                                            
// Generated by the MTDORB IDL-to-Pascal Translator (1.0.1b1), 21.09.2010 17:16
//                                                                            
// Copyright (c) 2002 - 2004                                                  
// Millennium Group.                                                          
// Samara, Russia                                                             
//                                                                            
// All Rights Reserved                                                        
//                                                                            
// ***************************************************************************
// Compiled with parameters: " -iw:\ W:\shared\CoreSrv\SecuritySrv\SecuritySrv.idl" 
//                                                                            
unit SecuritySrv_int;

{$MINENUMSIZE 4}

interface

uses
  orbtypes, code_int, orb_int, SecuritySrvComm_int, RootSrv_int, except_int;

type

// module SecuritySrv types

  TCoreSrv_SecuritySrv_Token = record
    sid : TCoreSrv_SessionID;
    uid : TCoreSrv_UserID;
  end;

  ICoreSrv_SecuritySrv_SessionManager = interface
  ['{9CC217DA-BCDF-4204-B55C-CB473002849F}']
    function login(const login: AnsiString; const pswd: AnsiString): TCoreSrv_SecuritySrv_Token;
    procedure logout;
    procedure keep_alive;
    procedure add_session_interceptor(const sint: ICoreSrv_SessionInterceptor);
  end;

  ICoreSrv_SecuritySrv_SessionManagerFactoryManagerSrv = interface
  ['{0411A821-7516-4DC4-B5EF-9818B40DDDBB}']
    function get: ICoreSrv_SecuritySrv_SessionManager;
  end;

implementation

end.
