// This file is generated by omniidl (C++ backend)- omniORB_3_0. Do not edit.

#include "strings_struct.h"
#include <omniORB3/callDescriptor.h>

static const char* _0RL_library_version = omniORB_3_0;

size_t
StrRevision::_NP_alignedSize(size_t _initialoffset) const
{
  CORBA::ULong _msgsize = _initialoffset;
  _msgsize = date._NP_alignedSize(_msgsize);

  _msgsize = time._NP_alignedSize(_msgsize);

  return _msgsize;
}

void
StrRevision::operator>>= (NetBufferedStream &_n) const
{
  date >>= _n;
  time >>= _n;
  
}

void
StrRevision::operator<<= (NetBufferedStream &_n)
{
  date <<= _n;
  time <<= _n;
  
}

void
StrRevision::operator>>= (MemBufferedStream &_n) const
{
  date >>= _n;
  time >>= _n;
  
}

void
StrRevision::operator<<= (MemBufferedStream &_n)
{
  date <<= _n;
  time <<= _n;
  
}

size_t
StrPeriod::_NP_alignedSize(size_t _initialoffset) const
{
  CORBA::ULong _msgsize = _initialoffset;
  _msgsize = old_date._NP_alignedSize(_msgsize);

  _msgsize = new_date._NP_alignedSize(_msgsize);

  return _msgsize;
}

void
StrPeriod::operator>>= (NetBufferedStream &_n) const
{
  old_date >>= _n;
  new_date >>= _n;
  
}

void
StrPeriod::operator<<= (NetBufferedStream &_n)
{
  old_date <<= _n;
  new_date <<= _n;
  
}

void
StrPeriod::operator>>= (MemBufferedStream &_n) const
{
  old_date >>= _n;
  new_date >>= _n;
  
}

void
StrPeriod::operator<<= (MemBufferedStream &_n)
{
  old_date <<= _n;
  new_date <<= _n;
  
}

size_t
StrSettings::_NP_alignedSize(size_t _initialoffset) const
{
  CORBA::ULong _msgsize = _initialoffset;
  _msgsize = out_name._NP_alignedSize(_msgsize);

  _msgsize = omni::align_to(_msgsize, omni::ALIGN_2) + 2;

  _msgsize = omni::align_to(_msgsize, omni::ALIGN_2) + 2;

  _msgsize = mrg_segs._NP_alignedSize(_msgsize);

  _msgsize = period._NP_alignedSize(_msgsize);

  return _msgsize;
}

void
StrSettings::operator>>= (NetBufferedStream &_n) const
{
  out_name >>= _n;
  pic_enable >>= _n;
  rtf_enable >>= _n;
  mrg_segs >>= _n;
  period >>= _n;
  
}

void
StrSettings::operator<<= (NetBufferedStream &_n)
{
  out_name <<= _n;
  pic_enable <<= _n;
  rtf_enable <<= _n;
  mrg_segs <<= _n;
  period <<= _n;
  
}

void
StrSettings::operator>>= (MemBufferedStream &_n) const
{
  out_name >>= _n;
  pic_enable >>= _n;
  rtf_enable >>= _n;
  mrg_segs >>= _n;
  period >>= _n;
  
}

void
StrSettings::operator<<= (MemBufferedStream &_n)
{
  out_name <<= _n;
  pic_enable <<= _n;
  rtf_enable <<= _n;
  mrg_segs <<= _n;
  period <<= _n;
  
}

