clcache.o: clcache.cpp clcache.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h \
 ../../../libs/cchlp/src/Pix.h ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h ../../../include/osdep.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/gkdb_ver.h ../../../libs/gkdb/src/bmsk_ver.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/doccol.h ../../../libs/gkdb/src/refcol.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h ../../../libs/delta/src/adds.h \
 ../../../libs/cchlp/src/stringz.h ../../../libs/cchlp/src/Logger.h \
 ../../../libs/cchlp/src/SplayMap.h ../../../libs/cchlp/src/Map.h \
 ../../../libs/cchlp/src/SplaySet.h ../../../libs/cchlp/src/Set.h \
 ../../../libs/cchlp/src/typecmp.h ../../../libs/cchlp/src/recode.h \
 ../../../libs/gkdb/src/btiter.h \
 ../../../libs/cchlp/src/StorableSplaySet.h \
 ../../../libs/delta/src/dltcomon.h ../../../libs/gkdb/src/garutils.h \
 ../../../libs/delta/src/dhr_ver.h ../../../libs/gkdb/src/rev.h \
 /usr/include/malloc.h ../../../libs/gsscreen/src/toys.h
cntxtcol.o: cntxtcol.cpp ../../../libs/gkdb/src/collect.h \
 ../../../libs/gkdb/src/store.h ../../../include/osdep.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/gkdb/src/doccol.h ../../../libs/gkdb/src/refcol.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/gkdb_ver.h ../../../libs/gkdb/src/bmsk_ver.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/hindex.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h ../../../libs/gkdb/src/garutils.h \
 cntxtcol.h ../../../libs/delta/src/deltadef.h \
 ../../../libs/cchlp/src/u_int64_t.u_int16_t.SplayMap.h \
 ../../../libs/cchlp/src/u_int64_t.u_int16_t.Map.h \
 ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/u_int64_t.defs.h \
 ../../../libs/cchlp/src/Logger.h ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/SplayMap.h ../../../libs/cchlp/src/Map.h \
 ../../../libs/cchlp/src/SplaySet.h ../../../libs/cchlp/src/Set.h \
 ../../../libs/cchlp/src/typecmp.h ../../../libs/cchlp/src/recode.h
delta.o: delta.cpp gdlt_ver.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/delta/src/dhr_ver.h \
 ../../../libs/delta/src/delt_ver.h ../../../libs/gctx/src/gctxl_ver.h \
 ../../../libs/cchlp/src/cchlp_ver.h ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 fulldiff.h ../../../libs/delta/src/hendlers.h \
 ../../../libs/delta/src/elems.h ../../../libs/delta/src/deltadef.h \
 ../../../libs/gkdb/src/dociter.h ../../../libs/gkdb/src/btiter.h \
 diffhldr.h ../../../libs/gsscreen/src/toys.h \
 ../../../libs/cchlp/src/StorableSplaySet.h \
 ../../../libs/cchlp/src/SplaySet.h ../../../libs/cchlp/src/Set.h \
 ../../../libs/cchlp/src/typecmp.h ../../../libs/gkdb/src/garutils.h \
 ../../../libs/gkdb/src/basemask.h ../../../include/garver.h \
 ../../../libs/cchlp/src/Logger.h ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/SplayMap.h ../../../libs/cchlp/src/Map.h \
 ../../../libs/cchlp/src/recode.h ../../../libs/delta/src/adds.h \
 ../../../libs/cchlp/src/stringz.h ../../../libs/delta/src/dltcomon.h \
 ../../../libs/gkdb/src/rev.h /usr/include/malloc.h
diffhldr.o: diffhldr.cpp ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/gkdb_ver.h ../../../libs/gkdb/src/bmsk_ver.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/ncpf.h \
 diffhldr.h
fulldiff.o: fulldiff.cpp gdlt_ver.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/delta/src/dhr_ver.h \
 ../../../libs/delta/src/delt_ver.h ../../../libs/gctx/src/gctxl_ver.h \
 ../../../libs/cchlp/src/cchlp_ver.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/gkdb/src/doccol.h ../../../libs/gkdb/src/collect.h \
 ../../../libs/gkdb/src/store.h ../../../libs/gkdb/src/refcol.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/hindex.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h ../../../libs/gkdb/src/dociter.h \
 ../../../libs/gkdb/src/btiter.h ../../../libs/delta/src/elems.h \
 ../../../libs/delta/src/hendlers.h ../../../libs/delta/src/deltadef.h \
 ../../../libs/delta/src/wordcol.h ../../../libs/gkdb/src/garutils.h \
 ../../../libs/cchlp/src/stringz.h ../../../libs/cchlp/src/Logger.h \
 ../../../libs/cchlp/src/fstring.h ../../../libs/cchlp/src/SplayMap.h \
 ../../../libs/cchlp/src/Map.h ../../../libs/cchlp/src/SplaySet.h \
 ../../../libs/cchlp/src/Set.h ../../../libs/cchlp/src/typecmp.h \
 ../../../libs/cchlp/src/recode.h fulldiff.h diffhldr.h \
 ../../../libs/gsscreen/src/toys.h \
 ../../../libs/cchlp/src/StorableSplaySet.h \
 ../../../libs/delta/src/dltcomon.h ../../../libs/gkdb/src/rev.h \
 /usr/include/malloc.h ../../../libs/delta/src/adds.h \
 ../../../libs/cchlp/src/hnode.h ../../../libs/delta/src/tempdoc.h 
reviser.o: reviser.cpp ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/gkdb/src/doccol.h ../../../libs/gkdb/src/collect.h \
 ../../../libs/gkdb/src/store.h ../../../libs/gkdb/src/refcol.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/gkdb_ver.h ../../../libs/gkdb/src/bmsk_ver.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/hindex.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h ../../../libs/cchlp/src/stringz.h \
 ../../../libs/cchlp/src/Logger.h ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/SplayMap.h ../../../libs/cchlp/src/Map.h \
 ../../../libs/cchlp/src/SplaySet.h ../../../libs/cchlp/src/Set.h \
 ../../../libs/cchlp/src/typecmp.h ../../../libs/cchlp/src/recode.h \
 reviser.h ../../../libs/gkdb/src/dociter.h \
 ../../../libs/gkdb/src/btiter.h \
 ../../../libs/cchlp/src/StorableSplaySet.h \
 ../../../libs/delta/src/deltadef.h ../../../libs/gkdb/src/garutils.h \
 ../../../libs/delta/src/adds.h ../../../libs/delta/src/dltcomon.h \
 ../../../libs/delta/src/dhr_ver.h ../../../libs/gkdb/src/rev.h \
 /usr/include/malloc.h ../../../libs/gsscreen/src/toys.h
setrev.o: setrev.cpp grev_ver.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/delta/src/delt_ver.h \
 ../../../libs/gctx/src/gctxl_ver.h \
 ../../../libs/cchlp/src/cchlp_ver.h ../../../include/garver.h \
 ../../../libs/gkdb/src/stdbase.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/gkdb/src/doccol.h ../../../libs/gkdb/src/collect.h \
 ../../../libs/gkdb/src/store.h ../../../libs/gkdb/src/refcol.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/hindex.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h ../../../libs/gkdb/src/garutils.h \
 ../../../libs/gkdb/src/basemask.h reviser.h \
 ../../../libs/gkdb/src/dociter.h ../../../libs/gkdb/src/btiter.h \
 ../../../libs/cchlp/src/StorableSplaySet.h \
 ../../../libs/cchlp/src/SplaySet.h ../../../libs/cchlp/src/Set.h \
 ../../../libs/cchlp/src/typecmp.h ../../../libs/cchlp/src/Logger.h \
 ../../../libs/cchlp/src/fstring.h ../../../libs/cchlp/src/SplayMap.h \
 ../../../libs/cchlp/src/Map.h ../../../libs/cchlp/src/recode.h \
 ../../../libs/delta/src/adds.h ../../../libs/cchlp/src/stringz.h \
 ../../../libs/delta/src/dltcomon.h ../../../libs/delta/src/dhr_ver.h \
 ../../../libs/gkdb/src/rev.h /usr/include/malloc.h \
 ../../../libs/gsscreen/src/toys.h
unfull.o: unfull.cpp gu_ver.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/cchlp/src/cchlp_ver.h \
 ../../../libs/delta/src/dhr_ver.h ../../../libs/delta/src/delt_ver.h \
 ../../../libs/gctx/src/gctxl_ver.h \
 ../../../libs/inifile/src/ini_ver.h \
 ../../../libs/gsscreen/src/gsscreen_ver.h ../../../include/osdep.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/gkdb/src/doccol.h ../../../libs/gkdb/src/collect.h \
 ../../../libs/gkdb/src/store.h ../../../libs/gkdb/src/refcol.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/hindex.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h ../../../libs/gkdb/src/newdoc.h \
 ../../../libs/gkdb/src/garutils.h ../../../libs/cchlp/src/stringz.h \
 ../../../libs/cchlp/src/Logger.h ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/SplayMap.h ../../../libs/cchlp/src/Map.h \
 ../../../libs/cchlp/src/SplaySet.h ../../../libs/cchlp/src/Set.h \
 ../../../libs/cchlp/src/typecmp.h ../../../libs/cchlp/src/recode.h \
 unfull.h ../../../libs/delta/src/elems.h \
 ../../../libs/delta/src/hendlers.h ../../../libs/delta/src/deltadef.h \
 cntxtcol.h ../../../libs/cchlp/src/u_int64_t.u_int16_t.SplayMap.h \
 ../../../libs/cchlp/src/u_int64_t.u_int16_t.Map.h \
 ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/u_int64_t.defs.h clcache.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/delta/src/dhreader.h \
 ../../../libs/cchlp/src/StorableSplaySet.h \
 ../../../libs/delta/src/adds.h ../../../libs/gkdb/src/btiter.h \
 ../../../libs/delta/src/dltcomon.h ../../../libs/gkdb/src/rev.h \
 /usr/include/malloc.h ../../../libs/gsscreen/src/toys.h \
 ../../../libs/gctx/src/ctxwords.h ../../../libs/delta/src/wordcol.h \
 ../../../libs/cchlp/src/long.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/long.caddr_t.Map.h \
 ../../../libs/cchlp/src/long.defs.h ../../../libs/delta/src/tempdoc.h 
update.o: update.cpp gu_ver.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/cchlp/src/cchlp_ver.h \
 ../../../libs/delta/src/dhr_ver.h ../../../libs/delta/src/delt_ver.h \
 ../../../libs/gctx/src/gctxl_ver.h \
 ../../../libs/inifile/src/ini_ver.h \
 ../../../libs/gsscreen/src/gsscreen_ver.h \
 ../../../libs/gkdb/src/stdbase.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/gkdb/src/doccol.h ../../../libs/gkdb/src/collect.h \
 ../../../libs/gkdb/src/store.h ../../../libs/gkdb/src/refcol.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/hindex.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h ../../../libs/gkdb/src/ncpf.h \
 ../../../libs/gkdb/src/garutils.h ../../../libs/delta/src/deltadef.h \
 ../../../libs/delta/src/dltcomon.h ../../../libs/gkdb/src/rev.h \
 ../../../libs/cchlp/src/SplaySet.h ../../../libs/cchlp/src/Set.h \
 ../../../libs/cchlp/src/typecmp.h ../../../libs/cchlp/src/Logger.h \
 ../../../libs/cchlp/src/fstring.h ../../../libs/cchlp/src/SplayMap.h \
 ../../../libs/cchlp/src/Map.h ../../../libs/cchlp/src/recode.h \
 /usr/include/malloc.h unfull.h ../../../libs/delta/src/elems.h \
 ../../../libs/delta/src/hendlers.h cntxtcol.h \
 ../../../libs/cchlp/src/u_int64_t.u_int16_t.SplayMap.h \
 ../../../libs/cchlp/src/u_int64_t.u_int16_t.Map.h \
 ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/u_int64_t.defs.h clcache.h \
 ../../../libs/cchlp/src/FString.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/FString.caddr_t.Map.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/stringz.h ../../../libs/delta/src/dhreader.h \
 ../../../libs/cchlp/src/StorableSplaySet.h \
 ../../../libs/delta/src/adds.h ../../../libs/gkdb/src/btiter.h \
 ../../../libs/gsscreen/src/toys.h ../../../libs/inifile/src/inifile.h \
 ../../../libs/inifile/src/wdefs.h ../../../libs/gkdb/src/basemask.h \
 ../../../include/garver.h
