/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_garant_SolrExtensions_MorphoAdapter */

#ifndef _Included_ru_garant_SolrExtensions_MorphoAdapter
#define _Included_ru_garant_SolrExtensions_MorphoAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_garant_SolrExtensions_MorphoAdapter
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_garant_SolrExtensions_MorphoAdapter_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_garant_SolrExtensions_MorphoAdapter
 * Method:    initEx
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_garant_SolrExtensions_MorphoAdapter_initEx
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_garant_SolrExtensions_MorphoAdapter
 * Method:    normalize
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ru_garant_SolrExtensions_MorphoAdapter_normalize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_garant_SolrExtensions_MorphoAdapter
 * Method:    getSSyns
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ru_garant_SolrExtensions_MorphoAdapter_getSSyns
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
