// Модуль: "w:\common\components\rtl\Garant\ScriptEngine\InterfacedNodeWords.rc.script"
// Стереотип: "ScriptKeywordsPack"


//#UC START# *53B532DE0203man_uses*
//#UC END# *53B532DE0203man_uses*

USES
 axiom:Node
;

// Класс Il3Node - Node
//  Операция Caption
//  Класс реализующий операцию Node_Caption - Node:Caption
WordAlias pop:Node:Caption Node:Caption
//  Операция Index
//  Класс реализующий операцию Node_Index - Node:Index
WordAlias pop:Node:Index Node:Index
//  Операция IndexInTree
//  Класс реализующий операцию Node_IndexInTree - Node:IndexInTree
WordAlias pop:Node:IndexInTree Node:IndexInTree

//#UC START# *53B532DE0203impl*
//#UC END# *53B532DE0203impl*

EXPORTS
//#UC START# *53B532DE0203exports*
 *
//#UC END# *53B532DE0203exports*
