#ifndef _TAO_IDL_______________GARANTPIL_IMPLEMENTATION_COMPONENT_CPP_GARANT_GLOBAL_CORE_ORBS_H_
#define _TAO_IDL_______________GARANTPIL_IMPLEMENTATION_COMPONENT_CPP_GARANT_GLOBAL_CORE_ORBS_H_

#include "ORBC.h"

#endif /* ifndef */

