#ifndef ___COMMON_FIXES_CORBA_POA_IDL__
#define ___COMMON_FIXES_CORBA_POA_IDL__
#define CORBA3

#ifdef _OMNI_IDL
	#include "omniPortableInterceptor.idl"
	#include "omniPortableServer.idl"
#else
	#include "PortableInterceptor.pidl"
#endif
#endif
