#ifndef ___COMMON_FIXES_CORBA_TIMEBASE_IDL__
#define ___COMMON_FIXES_CORBA_TIMEBASE_IDL__
#define CORBA3

#ifdef _OMNI_IDL
	#include "COS/TimeBase.idl"
#else
	#include "orbsvcs/orbsvcs/TimeBase.idl"
#endif

#endif