@echo off
rem Начало сборки
echo Сборка документации началась %DATE% %TIME% > \\archi2-2008\archi\!DAILY_MANUALS\ManualBuild.txt
echo. >> \\archi2-2008\archi\!DAILY_MANUALS\ManualBuild.txt
 
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\AddImg.AdminGuide.hmxz "/tsk=Recent Publishes:AddImg.AdminGuide " "/tsk=Recent Publishes:AddImg_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\AdjustToPage.AdminGuide.hmxz "/tsk=Recent Publishes:AdjustToPage.AdminGuide" "/tsk=Recent Publishes:AdjustToPage_!DAYLY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Administrator.AdminGuide.hmxz "/tsk=Recent Publishes:Administrator.AdminGuide" "/tsk=Recent Publishes:Administrator_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" "D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Archivarius.AppositionBD.hmxz" "/tsk=Recent Publishes:Archivarius.AppositionBD.AdminGuide" "/tsk=Recent Publishes:AppositionBD_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Archivarius.IntroductionOperation.hmxz "/tsk=Recent Publishes:Archivarius.IntroductionOperation" "/tsk=Recent Publishes:Archivarius.Inroduction_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Archivarius.Setting.AdminGuide.hmxz "/tsk=Recent Publishes:Archivarius.Setting.AdminGuide" "/tsk=Recent Publishes:Archivarius.Setting.AdminGuide_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Archivarius.UserGuide.hmxz /tsk=FullBuild:Archivarius.UserGuide(federal) /tsk=FullBuild:Archivarius.UserGuide(regions) /tsk=FullBuild:Archivarius.UserGuide(r)_!DAILY
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Autopipeserver.AdminGuide.hmxz "/tsk=ManualGuide (*pdf):AutoPipeServer.AdminGuide(f)" "/tsk=ManualGuide (*pdf):AutoPipeServer.AdminGuide(r)" "/tsk=ManualGuide (*pdf):AutoPipeServer.AdminGuide(rCHM)" "/tsk=ManualGuide (*pdf):AutoPipeServer.AdminGuide(fCHM)" "/tsk=ManualGuide (*pdf):AutoPipeServer.AdminGuide(rCHM)_!DAILY" "/tsk=ManualGuide (*pdf):AutoPipeServer.AdminGuide(rPDF)_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\DbUtil.AdminGuide.hmxz /tsk=FullBuild:DbUtil.AdminGuide(federal) /tsk=FullBuild:DbUtil.AdminGuide(regional) /tsk=FullBuild:DbUtil.AdminGuide(r)_!DAILY
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Delprefix.AdminGuide.hmxz /tsk=DelPrefixBuild:Delprefix.AdminGuide /tsk=DelPrefixBuild:Delprefix.AdminGuide_!DAILY
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Descript.hmxz "/tsk=Recent Publishes:Publish as CHM" "/tsk=Recent Publishes:!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Dictsync.AdmingGuide.hmxz "/tsk=Recent Publishes:Dictsync.AdmingGuide" "/tsk=Recent Publishes:Dictsync.AdmingGuide_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\FAQ.hmxz /tsk=FAQ_Task:FAQ-Manual /tsk=FAQ_Task:FAQ_!DAILY
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\HyTech.CorrectionTable.AdminGuide.hmxz "/tsk=Recent Publishes:HyTech.CorrectionTable.AdminGuide" "/tsk=Recent Publishes:HyTech.CorrectionTable.AdminGuide_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\KILLTR.UserGuide.hmxz "/tsk=Recent Publishes:KILLTR.UserGuide" "/tsk=Recent Publishes:KILLTR.UserGuide_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\ListImport.AdminGuide.hmxz "/tsk=Recent Publishes:ListImport.AdminGuide" "/tsk=Recent Publishes:ListImport.AdminGuide_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Nsrcspy.AdminGuide.hmxz /tsk=FullManual:NSRCSpy.AdminGuide(rCHM) /tsk=FullManual:NSRCSpy.AdminGuide(rPDF) /tsk=FullManual:NSRCSpy.AdminGuide(rCHM)_!DAILY /tsk=FullManual:NSRCSpy.AdminGuide(rPDF)_!DAILY /tsk=FullManual:NSRCSpy.AdminGuide(enPDF) /tsk=FullManual:NSRCSpy.AdminGuide(enPDF)_!DAILY
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Nsrplus2nsr.AdminGuide.hmxz "/tsk=Recent Publishes:Nsrplus2nsr.AdminGuide" "/tsk=Recent Publishes:Nsrplus2nsr.AdminGuide_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\PipeOut2.AdminGuide.hmxz "/tsk=Recent Publishes:PipeOut2.AdminGuide" "/tsk=Recent Publishes:PipeOut2.AdminGuide_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\RegionTool.AdminGuide.hmxz /tsk=RegionTool:RegionTool.AdminGuide /tsk=RegionTool:RegionTool.AdminGuide_!DAILY
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\HyTechAPI.CodeList.hmxz "/tsk=Recent Publishes:HyTech API.CodeList.AdminGuide" "/tsk=Recent Publishes:HyTech API.CodeList.AdminGuide_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Archivarius.ReleaseNotes.hmxz "/tsk=Recent Publishes:Archivarius.ReleaseNotes" "/tsk=Recent Publishes:Archivarius.ReleaseNotes_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Archivarius.ReleaseNotes.hmxz /tsk=CustomBuild:ReleaseNotes.AddImg /tsk=CustomBuild:ReleaseNotes.Adjust2page /tsk=CustomBuild:ReleaseNotes.Dbupdate /tsk=CustomBuild:ReleaseNotes.DBUtil /tsk=CustomBuild:ReleaseNotes.Dictsync /tsk=CustomBuild:ReleaseNotes.Listimport /tsk=CustomBuild:ReleaseNotes.Nsrplus2nsr /tsk=CustomBuild:ReleaseNotes.Pipeout2 /tsk=CustomBuild:ReleaseNotes.Regiontool /tsk=CustomBuild:ReleaseNotes.Admin2 /tsk=CustomBuild:ReleaseNotes.Archivarius /tsk=CustomBuild:ReleaseNotes.BaseVersion /tsk=CustomBuild:ReleaseNotes.Autopipeserver /tsk=CustomBuild:ReleaseNotes.Nsrcspy /tsk=CustomBuild:ReleaseNotes.AddImg_!DAILY /tsk=CustomBuild:ReleaseNotes.Adjust2page_!DAILY /tsk=CustomBuild:ReleaseNotes.Dbupdate_!DAILY /tsk=CustomBuild:ReleaseNotes.DBUtil_!DAILY /tsk=CustomBuild:ReleaseNotes.Dictsync_!DAILY /tsk=CustomBuild:ReleaseNotes.Listimport_!DAILY /tsk=CustomBuild:ReleaseNotes.Nsrplus2nsr_!DAILY /tsk=CustomBuild:ReleaseNotes.Pipeout2_!DAILY /tsk=CustomBuild:ReleaseNotes.Regiontool_!DAILY /tsk=CustomBuild:ReleaseNotes.Admin2_!DAILY /tsk=CustomBuild:ReleaseNotes.Archivarius_!DAILY /tsk=CustomBuild:ReleaseNotes.BaseVersion_!DAILY /tsk=CustomBuild:ReleaseNotes.Autopipeserver_!DAILY /tsk=CustomBuild:ReleaseNotes.Nsrcspy_!DAILY
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" "D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Description of the process of the technical processing the document.hmxz" "/tsk=Recent Publishes:TechDocument" "/tsk=Recent Publishes:TechDocument_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" "D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Procedure for making proofreading.hmxz" "/tsk=Recent Publishes:ProcedureMakingProofreading" "/tsk=Recent Publishes:ProcedureMakingProofreading_!DAILY
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" "D:\MANUAL(CVS)\archi\source\DOCUMENTATION\The sequence of actions when entering new documents.hmxz" "/tsk=Recent Publishes:SequenceActionsEnteringNewDocuments" "/tsk=Recent Publishes:SequenceActionsEnteringNewDocuments_!DAILY"
"C:\Program Files\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\DOCUMENTATION\Arhivarius.Kompleks.hmxz /tsk=Common:Arhivarius.Kompleks /tsk=Common:Kompleks.Arhivarius /tsk=Common:Arhivarius.Kompleks_!DAILY
echo. >> \\archi2-2008\archi\!DAILY_MANUALS\ManualBuild.txt
echo Сборка документации завершена %DATE% %TIME% >> \\archi2-2008\archi\!DAILY_MANUALS\ManualBuild.txt
