balancer.o: balancer.cpp ../../../include/osdep.h
basestat.o: basestat.cpp ../../../include/osdep.h \
 ../../../libs/gkdb/src/stdbase.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h
doc2html.o: doc2html.cpp ../../../include/osdep.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/btiter.h ../../../libs/cchlp/src/hnode.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/long.long.SplayMap.h \
 ../../../libs/cchlp/src/long.long.Map.h \
 ../../../libs/cchlp/src/fstring.h
newcorrs.o: newcorrs.cpp ../../../include/osdep.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/btiter.h ../../../libs/cchlp/src/hnode.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/long.long.SplayMap.h \
 ../../../libs/cchlp/src/long.long.Map.h \
 ../../../libs/cchlp/src/fstring.h
flimit.o: flimit.cc
gardbclean.o: gardbclean.cpp ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/btiter.h
gardbcmp.o: gardbcmp.cpp gardbcmp.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/store.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/doccol.h ../../../libs/gkdb/src/collect.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/hindex.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/long.SplayNode.h ../../../include/garver.h \
 ../../../libs/gkdb/src/btiter.h ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/u_int64_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int64_t.Set.h \
 ../../../libs/cchlp/src/u_int64_t.defs.h \
 ../../../libs/cchlp/src/u_int64_t.SplayNode.h \
 ../../../libs/cchlp/src/FString.long.SplayMap.h \
 ../../../libs/cchlp/src/FString.long.Map.h \
 ../../../libs/cchlp/src/long.long.SplayMap.h \
 ../../../libs/cchlp/src/long.long.Map.h \
 ../../../libs/cchlp/src/u_int32_t.FString.SplayMap.h \
 ../../../libs/cchlp/src/u_int32_t.FString.Map.h
gattrfix.o: gattrfix.cpp ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/gkdb/src/doccol.h ../../../libs/gkdb/src/collect.h \
 ../../../libs/gkdb/src/store.h ../../../libs/gkdb/src/refcol.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/gkdb_ver.h ../../../libs/gkdb/src/bmsk_ver.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/hindex.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/garutils.h ../../../libs/gkdb/src/dociter.h \
 ../../../libs/gkdb/src/btiter.h ../../../libs/cchlp/src/stringz.h \
 ../../../libs/cchlp/src/Logger.h ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/SplayMap.h ../../../libs/cchlp/src/Map.h \
 ../../../libs/cchlp/src/SplaySet.h ../../../libs/cchlp/src/Set.h \
 ../../../libs/cchlp/src/typecmp.h ../../../libs/cchlp/src/recode.h \
 ../../../include/garver.h ../../../libs/gkdb/src/basemask.h \
 ../../../libs/cchlp/src/StorableSplaySet.h
gdinfo.o: gdinfo.cpp ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/basemask.h ../../../include/garver.h
gfintst.o: gfintst.cpp ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/gkdb/src/doccol.h ../../../libs/gkdb/src/collect.h \
 ../../../libs/gkdb/src/store.h ../../../libs/gkdb/src/refcol.h \
 ../../../libs/gkdb/src/index.h ../../../libs/gkdb/src/btree.h \
 ../../../libs/gkdb/src/pagefile.h ../../../libs/gkdb/src/check.h \
 ../../../libs/gkdb/src/gkdb_ver.h ../../../libs/gkdb/src/bmsk_ver.h \
 ../../../libs/gkdb/src/streams.h ../../../libs/gkdb/src/hindex.h \
 ../../../libs/gkdb/src/indices.h ../../../libs/gkdb/src/document.h \
 ../../../libs/gkdb/src/basemsgs.h ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/garutils.h ../../../libs/gkdb/src/dociter.h \
 ../../../libs/gkdb/src/btiter.h ../../../libs/gkdb/src/basemask.h \
 ../../../include/garver.h
gkdbchkstr.o: gkdbchkstr.cpp ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h
gkdbcmp.o: gkdbcmp.cpp ../../../include/osdep.h \
 ../../../libs/gkdb/src/stdbase.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/garutils.h ../../../libs/gkdb/src/btiter.h \
 ../../../libs/cchlp/src/StorableSplaySet.h \
 ../../../libs/cchlp/src/SplaySet.h ../../../libs/cchlp/src/Set.h \
 ../../../libs/cchlp/src/typecmp.h ../../../libs/cchlp/src/stringz.h \
 ../../../libs/cchlp/src/Logger.h ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/SplayMap.h ../../../libs/cchlp/src/Map.h \
 ../../../libs/cchlp/src/recode.h
gkdbscr.o: gkdbscr.cpp ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../include/osdep.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h
gkdumpi.o: gkdumpi.cpp ../../../include/osdep.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/btiter.h
gkdumpkw.o: gkdumpkw.cpp ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/newdoc.h ../../../libs/gkdb/src/btiter.h \
 ../../../libs/cchlp/src/long.caddr_t.SplayMap.h \
 ../../../libs/cchlp/src/long.caddr_t.Map.h \
 ../../../libs/cchlp/src/Pix.h ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/clTreeNode.SplaySet.h \
 ../../../libs/cchlp/src/clTreeNode.Set.h \
 ../../../libs/cchlp/src/clTreeNode.defs.h \
 ../../../libs/cchlp/src/clTreeNode.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/clTreeNode.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/long.long.SplayMap.h \
 ../../../libs/cchlp/src/long.long.Map.h cdflts.h \
 ../../../include/garver.h
gkdumps.o: gkdumps.cpp ../../../include/osdep.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/btiter.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/long.SplayNode.h
gkforce.o: gkforce.cpp ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/btiter.h
gkgetdoc.o: gkgetdoc.cpp ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../include/garver.h
gktouch.o: gktouch.cpp ../../../include/osdep.h \
 ../../../libs/gkdb/src/stdbase.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h
gmonth.o: gmonth.cpp ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/btiter.h
gpds.o: gpds.cpp ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/btiter.h ../../../include/garver.h
gready.o: gready.cpp ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/basemask.h ../../../include/garver.h
gregtst.o: gregtst.cpp ../../../include/osdep.h \
 ../../../libs/gkdb/src/stdbase.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/btiter.h ../../../libs/cchlp/src/hnode.h \
 ../../../libs/cchlp/src/long.long.SplayMap.h \
 ../../../libs/cchlp/src/long.long.Map.h ../../../libs/cchlp/src/Pix.h \
 ../../../libs/cchlp/src/long.defs.h \
 ../../../libs/cchlp/src/long.SplaySet.h \
 ../../../libs/cchlp/src/long.Set.h \
 ../../../libs/cchlp/src/long.SplayNode.h \
 ../../../libs/cchlp/src/long.longSplaySet.SplayMap.h \
 ../../../libs/cchlp/src/long.longSplaySet.Map.h \
 ../../../libs/cchlp/src/FString.SplaySet.h \
 ../../../libs/cchlp/src/FString.Set.h \
 ../../../libs/cchlp/src/FString.defs.h \
 ../../../libs/cchlp/src/fstring.h \
 ../../../libs/cchlp/src/FString.SplayNode.h \
 ../../../libs/cchlp/src/u_int32_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int32_t.Set.h \
 ../../../libs/cchlp/src/u_int32_t.defs.h \
 ../../../libs/cchlp/src/u_int32_t.SplayNode.h \
 ../../../libs/cchlp/src/u_int64_t.SplaySet.h \
 ../../../libs/cchlp/src/u_int64_t.Set.h \
 ../../../libs/cchlp/src/u_int64_t.defs.h \
 ../../../libs/cchlp/src/u_int64_t.SplayNode.h
gsec.o: gsec.cpp ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../include/osdep.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h
gsetname.o: gsetname.cpp ../../../libs/inifile/src/inifile.h \
 ../../../include/osdep.h ../../../libs/inifile/src/wdefs.h \
 ../../../libs/gkdb/src/stdbase.h ../../../libs/gkdb/src/base.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../include/garver.h
gsetrev.o: gsetrev.cpp ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/basemask.h ../../../include/garver.h
gstat.o: gstat.cpp ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/btiter.h ../../../include/garver.h
gstatus.o: gstatus.cpp ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h \
 ../../../libs/gkdb/src/basemask.h ../../../include/garver.h
write-here.o: write-here.cpp ../../../libs/gkdb/src/stdbase.h \
 ../../../libs/gkdb/src/base.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/gkdb/src/doccol.h \
 ../../../libs/gkdb/src/collect.h ../../../libs/gkdb/src/store.h \
 ../../../libs/gkdb/src/refcol.h ../../../libs/gkdb/src/index.h \
 ../../../libs/gkdb/src/btree.h ../../../libs/gkdb/src/pagefile.h \
 ../../../libs/gkdb/src/check.h ../../../libs/gkdb/src/gkdb_ver.h \
 ../../../libs/gkdb/src/bmsk_ver.h ../../../libs/gkdb/src/streams.h \
 ../../../libs/gkdb/src/hindex.h ../../../libs/gkdb/src/indices.h \
 ../../../libs/gkdb/src/document.h ../../../libs/gkdb/src/basemsgs.h
