# DO NOT DELETE

garutils.o: check.h gardefs.h garutils.h collect.h store.h
collect.o: check.h collect.h store.h gardefs.h
newdoc.o: newdoc.h base.h gardefs.h doccol.h collect.h store.h refcol.h
newdoc.o: index.h btree.h pagefile.h check.h gkdb_ver.h bmsk_ver.h streams.h
newdoc.o: hindex.h indices.h document.h basemsgs.h garutils.h pack.h
base.o: btiter.h btree.h gardefs.h pagefile.h check.h gkdb_ver.h bmsk_ver.h
base.o: base.h doccol.h collect.h store.h refcol.h index.h streams.h hindex.h
base.o: indices.h document.h basemsgs.h garutils.h basemask.h
document.o: check.h base.h gardefs.h doccol.h collect.h store.h refcol.h
document.o: index.h btree.h pagefile.h gkdb_ver.h bmsk_ver.h streams.h
document.o: hindex.h indices.h document.h basemsgs.h garutils.h pack.h
doccol.o: check.h doccol.h collect.h store.h refcol.h gardefs.h
dociter.o: check.h dociter.h btiter.h btree.h gardefs.h pagefile.h gkdb_ver.h
dociter.o: bmsk_ver.h base.h doccol.h collect.h store.h refcol.h index.h
dociter.o: streams.h hindex.h indices.h document.h basemsgs.h
pagefile.o: gardefs.h check.h pagefile.h gkdb_ver.h bmsk_ver.h pack.h
index.o: check.h index.h btree.h gardefs.h pagefile.h gkdb_ver.h bmsk_ver.h
index.o: streams.h store.h
hindex.o: hindex.h index.h btree.h gardefs.h pagefile.h check.h gkdb_ver.h
hindex.o: bmsk_ver.h streams.h store.h btiter.h
indices.o: check.h gardefs.h indices.h index.h btree.h pagefile.h gkdb_ver.h
indices.o: bmsk_ver.h streams.h store.h hindex.h garutils.h collect.h
refcol.o: check.h refcol.h store.h collect.h gardefs.h doccol.h indices.h
refcol.o: index.h btree.h pagefile.h gkdb_ver.h bmsk_ver.h streams.h hindex.h
refcol.o: base.h document.h basemsgs.h
privbase.o: privbase.h hindex.h index.h btree.h gardefs.h pagefile.h check.h
privbase.o: gkdb_ver.h bmsk_ver.h streams.h store.h garutils.h collect.h
streams.o: streams.h store.h pagefile.h check.h gardefs.h gkdb_ver.h
streams.o: bmsk_ver.h
btree.o: check.h btree.h gardefs.h pagefile.h gkdb_ver.h bmsk_ver.h
btiter.o: btiter.h btree.h gardefs.h pagefile.h check.h gkdb_ver.h bmsk_ver.h
basemask.o: basemask.h bmsk_ver.h
ncpf.o: ncpf.h pagefile.h check.h gardefs.h gkdb_ver.h bmsk_ver.h
stdbase.o: stdbase.h base.h gardefs.h doccol.h collect.h store.h refcol.h
stdbase.o: index.h btree.h pagefile.h check.h gkdb_ver.h bmsk_ver.h streams.h
stdbase.o: hindex.h indices.h document.h basemsgs.h garutils.h ncpf.h
store.o: check.h store.h
rev.o: gardefs.h rev.h
fltiter.o: index.h btree.h gardefs.h pagefile.h check.h gkdb_ver.h bmsk_ver.h
fltiter.o: streams.h store.h btiter.h fltiter.h
unzip.o: zlib.h zconf.h
inflate.o: zutil.h zlib.h zconf.h infblock.h
deflate.o: deflate.h zutil.h zlib.h zconf.h
infblock.o: zutil.h zlib.h zconf.h infblock.h inftrees.h infcodes.h infutil.h
zutil.o: zutil.h zlib.h zconf.h
infutil.o: zutil.h zlib.h zconf.h infblock.h inftrees.h infcodes.h infutil.h
infcodes.o: zutil.h zlib.h zconf.h inftrees.h infblock.h infcodes.h infutil.h
infcodes.o: inffast.h
inftrees.o: zutil.h zlib.h zconf.h inftrees.h
inffast.o: zutil.h zlib.h zconf.h inftrees.h infblock.h infcodes.h infutil.h
inffast.o: inffast.h
adler32.o: zlib.h zconf.h
trees.o: deflate.h zutil.h zlib.h zconf.h
pack.o: pack.h zlib.h zconf.h
crc32.o: gardefs.h
pl_crypt.o: ../../GPersn/src/PL_Defs.h ../../GPersn/src/PL_Types.h ../../GPersn/src/PL_Proto.h
rev.o: rev.cpp rev.h
