// CatalogBase 45EEBA2C02BF Interface Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_45EEBA2C02BF_diagrams

 MEDIAGRAM ME_45EEBA2C02BF_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_45EEBA2C02BF' '457450470167.ms.model.script' ; // CatalogBase

  MEVIEW ME_45EEBA2C02C0_view
   MELINK Original WL 'ME_45EEBA2C02C0' '457450470167.ms.model.script' ; // clone
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_45EEBA2C02C0_view

  MEVIEW ME_45EEBA2C02C1_view
   MELINK Original WL 'ME_45EEBA2C02C1' '457450470167.ms.model.script' ; // get_node_by_path
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_45EEBA2C02C1_view

  MEVIEW ME_45EEBA2C02C5_view
   MELINK Original WL 'ME_45EEBA2C02C5' '457450470167.ms.model.script' ; // intersect_tree
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_45EEBA2C02C5_view

  MEVIEW ME_45EEBA2C02C7_view
   MELINK Original WL 'ME_45EEBA2C02C7' '457450470167.ms.model.script' ; // merge_tree
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_45EEBA2C02C7_view

  MEVIEW ME_45EEBA2C02C9_view
   MELINK Original WL 'ME_45EEBA2C02C9' '457450470167.ms.model.script' ; // minus_tree
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_45EEBA2C02C9_view

  MEVIEW ME_45EEBA2C02CB_view
   MELINK Original WL 'ME_45EEBA2C02CB' '457450470167.ms.model.script' ; // create
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_45EEBA2C02CB_view

  MEVIEW ME_45EEBA2C02CD_view
   MELINK Original WL 'ME_45EEBA2C02CD' '457450470167.ms.model.script' ; // name
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_45EEBA2C02CD_view

  MEVIEW ME_45F6906C03C8_view
   MELINK Original WL 'ME_45F6906C03C8' '457450470167.ms.model.script' ; // root
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_45F6906C03C8_view

  MELIST Views
   Seq: ( ME_45EEBA2C02C0_view // clone
   ME_45EEBA2C02C1_view // get_node_by_path
   ME_45EEBA2C02C5_view // intersect_tree
   ME_45EEBA2C02C7_view // merge_tree
   ME_45EEBA2C02C9_view // minus_tree
   ME_45EEBA2C02CB_view // create
   ME_45EEBA2C02CD_view // name
   ME_45F6906C03C8_view // root
   )
  ; // Views
 ENDMEDIAGRAM // ME_45EEBA2C02BF_main

 MELIST Diagrams
  Seq: ( ME_45EEBA2C02BF_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_45EEBA2C02BF_diagrams
