// Configuration 45EEDBE3014C Interface Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_45EEDBE3014C_diagrams

 MEDIAGRAM ME_45EEDBE3014C_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_45EEDBE3014C' '45EEAA69036E.ms.model.script' ; // Configuration

  MEVIEW ME_45EEDBE3014D_view
   MELINK Original WL 'ME_45EEDBE3014D' '45EEAA69036E.ms.model.script' ; // restore_default_values
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_45EEDBE3014D_view

  MEVIEW ME_45EEDBE3014E_view
   MELINK Original WL 'ME_45EEDBE3014E' '45EEAA69036E.ms.model.script' ; // save_values_as_default
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_45EEDBE3014E_view

  MEVIEW ME_45EEDBE3014F_view
   MELINK Original WL 'ME_45EEDBE3014F' '45EEAA69036E.ms.model.script' ; // copy
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_45EEDBE3014F_view

  MEVIEW ME_45EEDBE30150_view
   MELINK Original WL 'ME_45EEDBE30150' '45EEAA69036E.ms.model.script' ; // get_settings
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_45EEDBE30150_view

  MEVIEW ME_45F11C98009C_view
   MELINK Original WL 'ME_45F11C98009C' '45EEAA69036E.ms.model.script' ; // make
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_45F11C98009C_view

  MEVIEW ME_45EEDBE30151_view
   MELINK Original WL 'ME_45EEDBE30151' '45EEAA69036E.ms.model.script' ; // name
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_45EEDBE30151_view

  MEVIEW ME_45EEDBE30152_view
   MELINK Original WL 'ME_45EEDBE30152' '45EEAA69036E.ms.model.script' ; // hint
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_45EEDBE30152_view

  MEVIEW ME_45EEDBE30153_view
   MELINK Original WL 'ME_45EEDBE30153' '45EEAA69036E.ms.model.script' ; // type
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_45EEDBE30153_view

  MEVIEW ME_45EEDBE30154_view
   MELINK Original WL 'ME_45EEDBE30154' '45EEAA69036E.ms.model.script' ; // is_readonly
   MEPROP X 200
   MEPROP Y 180
  ENDMEVIEW // ME_45EEDBE30154_view

  MEVIEW ME_45EEDBE30155_view
   MELINK Original WL 'ME_45EEDBE30155' '45EEAA69036E.ms.model.script' ; // id
   MEPROP X 360
   MEPROP Y 180
  ENDMEVIEW // ME_45EEDBE30155_view

  MELIST Views
   Seq: ( ME_45EEDBE3014D_view // restore_default_values
   ME_45EEDBE3014E_view // save_values_as_default
   ME_45EEDBE3014F_view // copy
   ME_45EEDBE30150_view // get_settings
   ME_45F11C98009C_view // make
   ME_45EEDBE30151_view // name
   ME_45EEDBE30152_view // hint
   ME_45EEDBE30153_view // type
   ME_45EEDBE30154_view // is_readonly
   ME_45EEDBE30155_view // id
   )
  ; // Views
 ENDMEDIAGRAM // ME_45EEDBE3014C_main

 MELIST Diagrams
  Seq: ( ME_45EEDBE3014C_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_45EEDBE3014C_diagrams
