// NewNodeBackMap 46025892038A Map Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_46025892038A_diagrams

 MEDIAGRAM ME_46025892038A_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_46025892038A' '45F585F802AF.ms.model.script' ; // NewNodeBackMap

  MEVIEW ME_460258D7004E_view
   MELINK Original WL 'ME_460258D7004E' '45F585F802AF.ms.model.script' ; // 
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_460258D7004E_view

  MELIST Views
   Seq: ( ME_460258D7004E_view )
  ; // Views
 ENDMEDIAGRAM // ME_46025892038A_main

 MELIST Diagrams
  Seq: ( ME_46025892038A_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_46025892038A_diagrams
