// Tk2StorePropertyFlag 469F6CD10123 Enum Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_469F6CD10123_diagrams

 MEDIAGRAM ME_469F6CD10123_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_469F6CD10123' '49A6646B0044.ms.model.script' ; // Tk2StorePropertyFlag

  MEVIEW ME_469F6CE801D0_view
   MELINK Original WL 'ME_469F6CE801D0' '49A6646B0044.ms.model.script' ; // l3_spfScalars
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_469F6CE801D0_view

  MEVIEW ME_469F6CF1025F_view
   MELINK Original WL 'ME_469F6CF1025F' '49A6646B0044.ms.model.script' ; // l3_spfObjects
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_469F6CF1025F_view

  MEVIEW ME_469F6CFB01A5_view
   MELINK Original WL 'ME_469F6CFB01A5' '49A6646B0044.ms.model.script' ; // l3_spfChildren
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_469F6CFB01A5_view

  MEVIEW ME_469F6D050109_view
   MELINK Original WL 'ME_469F6D050109' '49A6646B0044.ms.model.script' ; // l3_spfRawData
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_469F6D050109_view

  MELIST Views
   Seq: ( ME_469F6CE801D0_view // l3_spfScalars
   ME_469F6CF1025F_view // l3_spfObjects
   ME_469F6CFB01A5_view // l3_spfChildren
   ME_469F6D050109_view // l3_spfRawData
   )
  ; // Views
 ENDMEDIAGRAM // ME_469F6CD10123_main

 MELIST Diagrams
  Seq: ( ME_469F6CD10123_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_469F6CD10123_diagrams
