// BitMask 470F39A900EA MDAClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_470F39A900EA_diagrams

 MEDIAGRAM ME_470F39A900EA_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_470F39A900EA' '470EF9BF0138.ms.model.script' ; // BitMask

  MEVIEW ME_470F3A1C038A_view
   MELINK Original WL 'ME_470F3A1C038A' '470EF9BF0138.ms.model.script' ; // attr
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_470F3A1C038A_view

  MELIST Views
   Seq: ( ME_470F3A1C038A_view // attr
   )
  ; // Views
 ENDMEDIAGRAM // ME_470F39A900EA_main

 MELIST Diagrams
  Seq: ( ME_470F39A900EA_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_470F39A900EA_diagrams
