// Tl3TextFormatFlag 4728B9A60134 Enum Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4728B9A60134_diagrams

 MEDIAGRAM ME_4728B9A60134_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4728B9A60134' '467C0CAA02AB.ms.model.script' ; // Tl3TextFormatFlag

  MEVIEW ME_4728B9C00100_view
   MELINK Original WL 'ME_4728B9C00100' '467C0CAA02AB.ms.model.script' ; // l3_tffLeft
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4728B9C00100_view

  MEVIEW ME_4728B9C702F4_view
   MELINK Original WL 'ME_4728B9C702F4' '467C0CAA02AB.ms.model.script' ; // l3_tffCenter
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4728B9C702F4_view

  MEVIEW ME_4728B9CE01E6_view
   MELINK Original WL 'ME_4728B9CE01E6' '467C0CAA02AB.ms.model.script' ; // l3_tffRight
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4728B9CE01E6_view

  MELIST Views
   Seq: ( ME_4728B9C00100_view // l3_tffLeft
   ME_4728B9C702F4_view // l3_tffCenter
   ME_4728B9CE01E6_view // l3_tffRight
   )
  ; // Views
 ENDMEDIAGRAM // ME_4728B9A60134_main

 MELIST Diagrams
  Seq: ( ME_4728B9A60134_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4728B9A60134_diagrams
