// Tl3BufferState 47A0818C0025 Enum Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_47A0818C0025_diagrams

 MEDIAGRAM ME_47A0818C0025_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_47A0818C0025' '47A080670100.ms.model.script' ; // Tl3BufferState

  MEVIEW ME_47A08195015E_view
   MELINK Original WL 'ME_47A08195015E' '47A080670100.ms.model.script' ; // bsUnknown
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_47A08195015E_view

  MEVIEW ME_47A0819A0127_view
   MELINK Original WL 'ME_47A0819A0127' '47A080670100.ms.model.script' ; // bsRead
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_47A0819A0127_view

  MEVIEW ME_47A0819E03BF_view
   MELINK Original WL 'ME_47A0819E03BF' '47A080670100.ms.model.script' ; // bsWrite
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_47A0819E03BF_view

  MELIST Views
   Seq: ( ME_47A08195015E_view // bsUnknown
   ME_47A0819A0127_view // bsRead
   ME_47A0819E03BF_view // bsWrite
   )
  ; // Views
 ENDMEDIAGRAM // ME_47A0818C0025_main

 MELIST Diagrams
  Seq: ( ME_47A0818C0025_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_47A0818C0025_diagrams
