// impurity value 47A1B60702B1 MDAAttribute Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_47A1B60702B1_diagrams

 MEDIAGRAM ME_47A1B60702B1_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_47A1B60702B1' '470EF980003E.ms.model.script' ; // impurity value

  MEVIEW ME_47A1B79E0139_view
   MELINK Original WL 'ME_47A1B79E0139' '470EF980003E.ms.model.script' ; // IsProp
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_47A1B79E0139_view

  MELIST Views
   Seq: ( ME_47A1B79E0139_view // IsProp
   )
  ; // Views
 ENDMEDIAGRAM // ME_47A1B60702B1_main

 MELIST Diagrams
  Seq: ( ME_47A1B60702B1_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_47A1B60702B1_diagrams
