// chg 47BABD2E01C1 MDAOperation Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_47BABD2E01C1_diagrams

 MEDIAGRAM ME_47BABD2E01C1_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_47BABD2E01C1' '478DEF830021.ms.model.script' ; // chg

  MEVIEW ME_47BABD6D0273_view
   MELINK Original WL 'ME_47BABD6D0273' '478DEF830021.ms.model.script' ; // param
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_47BABD6D0273_view

  MELIST Views
   Seq: ( ME_47BABD6D0273_view // param
   )
  ; // Views
 ENDMEDIAGRAM // ME_47BABD2E01C1_main

 MELIST Diagrams
  Seq: ( ME_47BABD2E01C1_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_47BABD2E01C1_diagrams
