// AccessorsSupport 47C66648034C MDAUtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_47C66648034C_diagrams

 MEDIAGRAM ME_47C66648034C_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_47C66648034C' '470384F502CE.ms.model.script' ; // AccessorsSupport

  MEVIEW ME_47C666640090_view
   MELINK Original WL 'ME_47C666640090' '470384F502CE.ms.model.script' ; // read_accessor_h
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_47C666640090_view

  MEVIEW ME_47C666750027_view
   MELINK Original WL 'ME_47C666750027' '470384F502CE.ms.model.script' ; // read_accessor_cpp
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_47C666750027_view

  MEVIEW ME_47C6667C0395_view
   MELINK Original WL 'ME_47C6667C0395' '470384F502CE.ms.model.script' ; // read_accessor_java
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_47C6667C0395_view

  MEVIEW ME_47C666AD01D0_view
   MELINK Original WL 'ME_47C666AD01D0' '470384F502CE.ms.model.script' ; // write_accessor_h
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_47C666AD01D0_view

  MEVIEW ME_47C6670B0197_view
   MELINK Original WL 'ME_47C6670B0197' '470384F502CE.ms.model.script' ; // write_accessor_cpp
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_47C6670B0197_view

  MEVIEW ME_47C6671500DC_view
   MELINK Original WL 'ME_47C6671500DC' '470384F502CE.ms.model.script' ; // write_accessor_java
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_47C6671500DC_view

  MEVIEW ME_47C668A10247_view
   MELINK Original WL 'ME_47C668A10247' '470384F502CE.ms.model.script' ; // is_static_accessor
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_47C668A10247_view

  MEVIEW ME_47CE9E06011B_view
   MELINK Original WL 'ME_47CE9E06011B' '470384F502CE.ms.model.script' ; // need_ro
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_47CE9E06011B_view

  MEVIEW ME_47CE9E3A00FB_view
   MELINK Original WL 'ME_47CE9E3A00FB' '470384F502CE.ms.model.script' ; // need_rw
   MEPROP X 200
   MEPROP Y 180
  ENDMEVIEW // ME_47CE9E3A00FB_view

  MELIST Views
   Seq: ( ME_47C666640090_view // read_accessor_h
   ME_47C666750027_view // read_accessor_cpp
   ME_47C6667C0395_view // read_accessor_java
   ME_47C666AD01D0_view // write_accessor_h
   ME_47C6670B0197_view // write_accessor_cpp
   ME_47C6671500DC_view // write_accessor_java
   ME_47C668A10247_view // is_static_accessor
   ME_47CE9E06011B_view // need_ro
   ME_47CE9E3A00FB_view // need_rw
   )
  ; // Views
 ENDMEDIAGRAM // ME_47C66648034C_main

 MELIST Diagrams
  Seq: ( ME_47C66648034C_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_47C66648034C_diagrams
