// IevCustomEditorControl 47CD5E5300D5 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_47CD5E5300D5_diagrams

 MEDIAGRAM ME_47CD5E5300D5_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_47CD5E5300D5' '47CD5C7602CD.ms.model.script' ; // IevCustomEditorControl

  MEVIEW ME_47CD5E7A027B_view
   MELINK Original WL 'ME_47CD5E7A027B' '47CD5C7602CD.ms.model.script' ; // IsMultiline
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_47CD5E7A027B_view

  MEVIEW ME_47CD5E9B031F_view
   MELINK Original WL 'ME_47CD5E9B031F' '47CD5C7602CD.ms.model.script' ; // GetControlIterator
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_47CD5E9B031F_view

  MEVIEW ME_47CD5EB4005D_view
   MELINK Original WL 'ME_47CD5EB4005D' '47CD5C7602CD.ms.model.script' ; // InitBoolProperty
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_47CD5EB4005D_view

  MEVIEW ME_47CD5EC10294_view
   MELINK Original WL 'ME_47CD5EC10294' '47CD5C7602CD.ms.model.script' ; // UpperChange
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_47CD5EC10294_view

  MEVIEW ME_47CD5EE900F7_view
   MELINK Original WL 'ME_47CD5EE900F7' '47CD5C7602CD.ms.model.script' ; // ControlName
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_47CD5EE900F7_view

  MEVIEW ME_47CD5F19011F_view
   MELINK Original WL 'ME_47CD5F19011F' '47CD5C7602CD.ms.model.script' ; // ControlType
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_47CD5F19011F_view

  MEVIEW ME_47CD5F3B03CA_view
   MELINK Original WL 'ME_47CD5F3B03CA' '47CD5C7602CD.ms.model.script' ; // Visible
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_47CD5F3B03CA_view

  MEVIEW ME_47CD5F4F015B_view
   MELINK Original WL 'ME_47CD5F4F015B' '47CD5C7602CD.ms.model.script' ; // Upper
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_47CD5F4F015B_view

  MELIST Views
   Seq: ( ME_47CD5E7A027B_view // IsMultiline
   ME_47CD5E9B031F_view // GetControlIterator
   ME_47CD5EB4005D_view // InitBoolProperty
   ME_47CD5EC10294_view // UpperChange
   ME_47CD5EE900F7_view // ControlName
   ME_47CD5F19011F_view // ControlType
   ME_47CD5F3B03CA_view // Visible
   ME_47CD5F4F015B_view // Upper
   )
  ; // Views
 ENDMEDIAGRAM // ME_47CD5E5300D5_main

 MELIST Diagrams
  Seq: ( ME_47CD5E5300D5_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_47CD5E5300D5_diagrams
