// TvlViewOption 47D63BD2033F Range Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_47D63BD2033F_diagrams

 MEDIAGRAM ME_47D63BD2033F_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_47D63BD2033F' '47D036150077.ms.model.script' ; // TvlViewOption

  MEVIEW ME_47D63BE00042_view
   MELINK Original WL 'ME_47D63BE00042' '47D036150077.ms.model.script' ; // voShowInterRowSpace
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_47D63BE00042_view

  MELIST Views
   Seq: ( ME_47D63BE00042_view // voShowInterRowSpace
   )
  ; // Views
 ENDMEDIAGRAM // ME_47D63BD2033F_main

 MELIST Diagrams
  Seq: ( ME_47D63BD2033F_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_47D63BD2033F_diagrams
