// Печать, Экспорт 48200CF8039E UseCases Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_48200CF8039E_diagrams

 MEDIAGRAM ME_48200CF8039E_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_48200CF8039E' ; // Печать, Экспорт

  MEVIEW ME_48200F89020E_view
   MELINK Original WL 'ME_48200F89020E' '48200CF8039E.ms.model.script' ; // Печать
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_48200F89020E_view

  MEVIEW ME_4820112E00B7_view
   MELINK Original WL 'ME_4820112E00B7' '48200CF8039E.ms.model.script' ; // Предварительный просмотр  печати
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4820112E00B7_view

  MEVIEW ME_48201D2E0282_view
   MELINK Original WL 'ME_48201D2E0282' '48200CF8039E.ms.model.script' ; // Диалог настройки страницы
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_48201D2E0282_view

  MEVIEW ME_484E539101BE_view
   MELINK Original WL 'ME_484E539101BE' '48200CF8039E.ms.model.script' ; // Экспорт в файл
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_484E539101BE_view

  MEVIEW ME_484E5531000E_view
   MELINK Original WL 'ME_484E5531000E' '48200CF8039E.ms.model.script' ; // Вызов внешнего приложения
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_484E5531000E_view

  MEVIEW ME_4E7879AC00F6_view
   MELINK Original WL 'ME_4E7879AC00F6' '48200CF8039E.ms.model.script' ; // При печати или экспорте фрагмента надо печатать и экспортировать заголовок
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_4E7879AC00F6_view

  MEVIEW ME_4F633BD400BA_view
   MELINK Original WL 'ME_4F633BD400BA' '48200CF8039E.ms.model.script' ; // Печать ОИД
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_4F633BD400BA_view

  MEVIEWLINK ME_4F633BD400BA_ME_48200F89020E_Inherits
   MELINK From ME_4F633BD400BA_view ;
   MELINK To ME_48200F89020E_view ;
   MEPROP Class class_Inherits
  ENDMEVIEWLINK // ME_4F633BD400BA_ME_48200F89020E_Inherits

  MELIST Views
   Seq: ( ME_48200F89020E_view // Печать
   ME_4820112E00B7_view // Предварительный просмотр  печати
   ME_48201D2E0282_view // Диалог настройки страницы
   ME_484E539101BE_view // Экспорт в файл
   ME_484E5531000E_view // Вызов внешнего приложения
   ME_4E7879AC00F6_view // При печати или экспорте фрагмента надо печатать и экспортировать заголовок
   ME_4F633BD400BA_view // Печать ОИД
   ME_4F633BD400BA_ME_48200F89020E_Inherits // Печать ОИД ==> Печать
   )
  ; // Views
 ENDMEDIAGRAM // ME_48200CF8039E_main

 MELIST Diagrams
  Seq: ( ME_48200CF8039E_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_48200CF8039E_diagrams
