// TnevRubberCellsRenderInfo 482098D2015E SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_482098D2015E_diagrams

 MEDIAGRAM ME_482098D2015E_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_482098D2015E' ; // TnevRubberCellsRenderInfo

  MEVIEW ME_4ED719EE01C1_view
   MELINK Original WL 'ME_4ED719EE01C1' '482098D2015E.ms.model.script' ; // WasChanged
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4ED719EE01C1_view

  MEVIEW ME_4ED71A110169_view
   MELINK Original WL 'ME_4ED71A110169' '482098D2015E.ms.model.script' ; // ClearChangedFlag
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4ED71A110169_view

  MEVIEW ME_4BFD6763012A_view
   MELINK Original WL 'ME_4BFD6763012A' '482098D2015E.ms.model.script' ; // ValidateNewChildWidth
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4BFD6763012A_view

  MEVIEW ME_4821596F01CB_view
   MELINK Original WL 'ME_4821596F01CB' '482098D2015E.ms.model.script' ; // Widthes
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4821596F01CB_view

  MEVIEW ME_4ED721DF02D2_view
   MELINK Original WL 'ME_4ED721DF02D2' '482098D2015E.ms.model.script' ; // f_LimitWidth
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4ED721DF02D2_view

  MELIST Views
   Seq: ( ME_4ED719EE01C1_view // WasChanged
   ME_4ED71A110169_view // ClearChangedFlag
   ME_4BFD6763012A_view // ValidateNewChildWidth
   ME_4821596F01CB_view // Widthes
   ME_4ED721DF02D2_view // f_LimitWidth
   )
  ; // Views
 ENDMEDIAGRAM // ME_482098D2015E_main

 MELIST Diagrams
  Seq: ( ME_482098D2015E_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_482098D2015E_diagrams
