// IdsQuery 491DC972029C ViewAreaController Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_491DC972029C_diagrams

 MEDIAGRAM ME_491DC972029C_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_491DC972029C' '4AA5503000D7.ms.model.script' ; // IdsQuery

  MEVIEW ME_491DC9970093_view
   MELINK Original WL 'ME_491DC9970093' '4AA5503000D7.ms.model.script' ; // Query
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_491DC9970093_view

  MEVIEW ME_491DC9AE0355_view
   MELINK Original WL 'ME_491DC9AE0355' '4AA5503000D7.ms.model.script' ; // IsQuerySaved
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_491DC9AE0355_view

  MELIST Views
   Seq: ( ME_491DC9970093_view // Query
   ME_491DC9AE0355_view // IsQuerySaved
   )
  ; // Views
 ENDMEDIAGRAM // ME_491DC972029C_main

 MELIST Diagrams
  Seq: ( ME_491DC972029C_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_491DC972029C_diagrams
