// IsdsDocInfo 4926B4100016 UseCaseController Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4926B4100016_diagrams

 MEDIAGRAM ME_4926B4100016_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4926B4100016' '4D1B7B830045.ms.model.script' ; // IsdsDocInfo

  MEVIEW ME_4937C4D90220_view
   MELINK Original WL 'ME_4937C4D90220' '4D1B7B830045.ms.model.script' ; // OpenCorrespondents
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4937C4D90220_view

  MEVIEW ME_4937C4E701F3_view
   MELINK Original WL 'ME_4937C4E701F3' '4D1B7B830045.ms.model.script' ; // OpenRespondents
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4937C4E701F3_view

  MEVIEW ME_4937C4F5038B_view
   MELINK Original WL 'ME_4937C4F5038B' '4D1B7B830045.ms.model.script' ; // ChangeCRType
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4937C4F5038B_view

  MEVIEW ME_4937C5250138_view
   MELINK Original WL 'ME_4937C5250138' '4D1B7B830045.ms.model.script' ; // AddToControl
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4937C5250138_view

  MEVIEW ME_4937C55101B2_view
   MELINK Original WL 'ME_4937C55101B2' '4D1B7B830045.ms.model.script' ; // DelFromControl
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4937C55101B2_view

  MEVIEW ME_4937C56002B6_view
   MELINK Original WL 'ME_4937C56002B6' '4D1B7B830045.ms.model.script' ; // ResetCacheAfterUpdate
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_4937C56002B6_view

  MEVIEW ME_4937C58D008D_view
   MELINK Original WL 'ME_4937C58D008D' '4D1B7B830045.ms.model.script' ; // IsTypedCRSelected
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_4937C58D008D_view

  MEVIEW ME_4937C5A5024F_view
   MELINK Original WL 'ME_4937C5A5024F' '4D1B7B830045.ms.model.script' ; // HasTypedCRinBigBase
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_4937C5A5024F_view

  MEVIEW ME_558928CF0335_view
   MELINK Original WL 'ME_558928CF0335' '4D1B7B830045.ms.model.script' ; // HasSimilarToFragment
   MEPROP X 200
   MEPROP Y 180
  ENDMEVIEW // ME_558928CF0335_view

  MEVIEW ME_5009A673037A_view
   MELINK Original WL 'ME_5009A673037A' '4D1B7B830045.ms.model.script' ; // dsRelatedDoc
   MEPROP X 360
   MEPROP Y 180
  ENDMEVIEW // ME_5009A673037A_view

  MEVIEW ME_5009A699023D_view
   MELINK Original WL 'ME_5009A699023D' '4D1B7B830045.ms.model.script' ; // dsRespondents
   MEPROP X 520
   MEPROP Y 180
  ENDMEVIEW // ME_5009A699023D_view

  MEVIEW ME_5009A6BE01DD_view
   MELINK Original WL 'ME_5009A6BE01DD' '4D1B7B830045.ms.model.script' ; // dsCorrespondents
   MEPROP X 680
   MEPROP Y 180
  ENDMEVIEW // ME_5009A6BE01DD_view

  MEVIEW ME_5009A6EF0016_view
   MELINK Original WL 'ME_5009A6EF0016' '4D1B7B830045.ms.model.script' ; // dsUserCR1
   MEPROP X 840
   MEPROP Y 180
  ENDMEVIEW // ME_5009A6EF0016_view

  MEVIEW ME_5009A72B01A5_view
   MELINK Original WL 'ME_5009A72B01A5' '4D1B7B830045.ms.model.script' ; // dsUserCR2
   MEPROP X 1000
   MEPROP Y 180
  ENDMEVIEW // ME_5009A72B01A5_view

  MEVIEW ME_5009ADAC0080_view
   MELINK Original WL 'ME_5009ADAC0080' '4D1B7B830045.ms.model.script' ; // dsDocumentWithFlash
   MEPROP X 40
   MEPROP Y 320
  ENDMEVIEW // ME_5009ADAC0080_view

  MEVIEW ME_500CEDF00141_view
   MELINK Original WL 'ME_500CEDF00141' '4D1B7B830045.ms.model.script' ; // dsAnnotation
   MEPROP X 200
   MEPROP Y 320
  ENDMEVIEW // ME_500CEDF00141_view

  MEVIEW ME_500CEE0F0071_view
   MELINK Original WL 'ME_500CEE0F0071' '4D1B7B830045.ms.model.script' ; // dsTranslation
   MEPROP X 360
   MEPROP Y 320
  ENDMEVIEW // ME_500CEE0F0071_view

  MEVIEW ME_500CEE5200DF_view
   MELINK Original WL 'ME_500CEE5200DF' '4D1B7B830045.ms.model.script' ; // dsSimilarDocuments
   MEPROP X 520
   MEPROP Y 320
  ENDMEVIEW // ME_500CEE5200DF_view

  MEVIEW ME_53BFD3A70050_view
   MELINK Original WL 'ME_53BFD3A70050' '4D1B7B830045.ms.model.script' ; // dsChronology
   MEPROP X 680
   MEPROP Y 320
  ENDMEVIEW // ME_53BFD3A70050_view

  MEVIEW ME_5594F2C102D7_view
   MELINK Original WL 'ME_5594F2C102D7' '4D1B7B830045.ms.model.script' ; // dsSimilarDocumentsToFragment
   MEPROP X 840
   MEPROP Y 320
  ENDMEVIEW // ME_5594F2C102D7_view

  MEVIEW ME_4937C61C0270_view
   MELINK Original WL 'ME_4937C61C0270' '4D1B7B830045.ms.model.script' ; // IsUnderControl
   MEPROP X 1000
   MEPROP Y 320
  ENDMEVIEW // ME_4937C61C0270_view

  MEVIEW ME_4937D0FF0303_view
   MELINK Original WL 'ME_4937D0FF0303' '4D1B7B830045.ms.model.script' ; // UserCRListInfo
   MEPROP X 40
   MEPROP Y 460
  ENDMEVIEW // ME_4937D0FF0303_view

  MEVIEW ME_3690DB82E835_view
   MELINK Original WL 'ME_3690DB82E835' '4D1B7B830045.ms.model.script' ; // HasRelatedDoc
   MEPROP X 200
   MEPROP Y 460
  ENDMEVIEW // ME_3690DB82E835_view

  MEVIEW ME_E562F23618B1_view
   MELINK Original WL 'ME_E562F23618B1' '4D1B7B830045.ms.model.script' ; // HasRespondents
   MEPROP X 360
   MEPROP Y 460
  ENDMEVIEW // ME_E562F23618B1_view

  MEVIEW ME_A0814C441725_view
   MELINK Original WL 'ME_A0814C441725' '4D1B7B830045.ms.model.script' ; // HasCorrespondents
   MEPROP X 520
   MEPROP Y 460
  ENDMEVIEW // ME_A0814C441725_view

  MEVIEW ME_8A0096569944_view
   MELINK Original WL 'ME_8A0096569944' '4D1B7B830045.ms.model.script' ; // HasAnnotation
   MEPROP X 680
   MEPROP Y 460
  ENDMEVIEW // ME_8A0096569944_view

  MEVIEW ME_01DBA41F4474_view
   MELINK Original WL 'ME_01DBA41F4474' '4D1B7B830045.ms.model.script' ; // HasTranslation
   MEPROP X 840
   MEPROP Y 460
  ENDMEVIEW // ME_01DBA41F4474_view

  MEVIEW ME_10E3D328A415_view
   MELINK Original WL 'ME_10E3D328A415' '4D1B7B830045.ms.model.script' ; // HasSimilarDocuments
   MEPROP X 1000
   MEPROP Y 460
  ENDMEVIEW // ME_10E3D328A415_view

  MEVIEW ME_5BAF4D39E661_view
   MELINK Original WL 'ME_5BAF4D39E661' '4D1B7B830045.ms.model.script' ; // HasChronology
   MEPROP X 40
   MEPROP Y 600
  ENDMEVIEW // ME_5BAF4D39E661_view

  MELIST Views
   Seq: ( ME_4937C4D90220_view // OpenCorrespondents
   ME_4937C4E701F3_view // OpenRespondents
   ME_4937C4F5038B_view // ChangeCRType
   ME_4937C5250138_view // AddToControl
   ME_4937C55101B2_view // DelFromControl
   ME_4937C56002B6_view // ResetCacheAfterUpdate
   ME_4937C58D008D_view // IsTypedCRSelected
   ME_4937C5A5024F_view // HasTypedCRinBigBase
   ME_558928CF0335_view // HasSimilarToFragment
   ME_5009A673037A_view // dsRelatedDoc
   ME_5009A699023D_view // dsRespondents
   ME_5009A6BE01DD_view // dsCorrespondents
   ME_5009A6EF0016_view // dsUserCR1
   ME_5009A72B01A5_view // dsUserCR2
   ME_5009ADAC0080_view // dsDocumentWithFlash
   ME_500CEDF00141_view // dsAnnotation
   ME_500CEE0F0071_view // dsTranslation
   ME_500CEE5200DF_view // dsSimilarDocuments
   ME_53BFD3A70050_view // dsChronology
   ME_5594F2C102D7_view // dsSimilarDocumentsToFragment
   ME_4937C61C0270_view // IsUnderControl
   ME_4937D0FF0303_view // UserCRListInfo
   ME_3690DB82E835_view // HasRelatedDoc
   ME_E562F23618B1_view // HasRespondents
   ME_A0814C441725_view // HasCorrespondents
   ME_8A0096569944_view // HasAnnotation
   ME_01DBA41F4474_view // HasTranslation
   ME_10E3D328A415_view // HasSimilarDocuments
   ME_5BAF4D39E661_view // HasChronology
   )
  ; // Views
 ENDMEDIAGRAM // ME_4926B4100016_main

 MELIST Diagrams
  Seq: ( ME_4926B4100016_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4926B4100016_diagrams
