// TdsDocumentListCR 492D687F0214 ViewAreaControllerImp Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_492D687F0214_diagrams

 MEDIAGRAM ME_492D687F0214_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_492D687F0214' ; // TdsDocumentListCR

  MEVIEW ME_492D74ED009A_view
   MELINK Original WL 'ME_492D74ED009A' '492D687F0214.ms.model.script' ; // InitDataType
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_492D74ED009A_view

  MELIST Views
   Seq: ( ME_492D74ED009A_view // InitDataType
   )
  ; // Views
 ENDMEDIAGRAM // ME_492D687F0214_main

 MELIST Diagrams
  Seq: ( ME_492D687F0214_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_492D687F0214_diagrams
