// TevTunedEditor 4999A57C01BA TestClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4999A57C01BA_diagrams

 MEDIAGRAM ME_4999A57C01BA_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4999A57C01BA' '49997B6803BC.ms.model.script' ; // TevTunedEditor

  MEVIEW ME_499A7B700283_view
   MELINK Original WL 'ME_499A7B700283' '49997B6803BC.ms.model.script' ; // IsDocumentTailVisible
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_499A7B700283_view

  MEVIEW ME_4999A61D00BC_view
   MELINK Original WL 'ME_4999A61D00BC' '49997B6803BC.ms.model.script' ; // Selection
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4999A61D00BC_view

  MELIST Views
   Seq: ( ME_499A7B700283_view // IsDocumentTailVisible
   ME_4999A61D00BC_view // Selection
   )
  ; // Views
 ENDMEDIAGRAM // ME_4999A57C01BA_main

 MELIST Diagrams
  Seq: ( ME_4999A57C01BA_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4999A57C01BA_diagrams
