// InsJournalBookmarkNode 4A8BAA7401EB Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4A8BAA7401EB_diagrams

 MEDIAGRAM ME_4A8BAA7401EB_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4A8BAA7401EB' '49904AF102FD.ms.model.script' ; // InsJournalBookmarkNode

  MEVIEW ME_4A8BAAA50229_view
   MELINK Original WL 'ME_4A8BAAA50229' '49904AF102FD.ms.model.script' ; // DocName
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4A8BAAA50229_view

  MEVIEW ME_4A8BAACC02D5_view
   MELINK Original WL 'ME_4A8BAACC02D5' '49904AF102FD.ms.model.script' ; // Bookmark
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4A8BAACC02D5_view

  MELIST Views
   Seq: ( ME_4A8BAAA50229_view // DocName
   ME_4A8BAACC02D5_view // Bookmark
   )
  ; // Views
 ENDMEDIAGRAM // ME_4A8BAA7401EB_main

 MELIST Diagrams
  Seq: ( ME_4A8BAA7401EB_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4A8BAA7401EB_diagrams
