// Folders$FSF 4AA4B2ED00FE VCMFormSetFactory Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4AA4B2ED00FE_diagrams

 MEDIAGRAM ME_4AA4B2ED00FE_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4AA4B2ED00FE' ; // Folders$FSF

  MEVIEW ME_4FFAA4A801DD_view
   MELINK Original WL 'ME_4FFAA4A801DD' '4AA4B2ED00FE.ms.model.script' ; // cfFolders
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4FFAA4A801DD_view

  MEVIEW ME_010F44F16CA4_view
   MELINK Original WL 'ME_010F44F16CA4' '4AA4B2ED00FE.ms.model.script' ; // Folders$FSFCaptionLocalConstants
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_010F44F16CA4_view

  MEVIEW ME_C0B08AD85726_view
   MELINK Original WL 'ME_C0B08AD85726' '4AA4B2ED00FE.ms.model.script' ; // cfFolders_Navigator_utFolders_NeedMakeForm
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_C0B08AD85726_view

  MEVIEW ME_49E15BACC408_view
   MELINK Original WL 'ME_49E15BACC408' '4AA4B2ED00FE.ms.model.script' ; // enFoldersTree_utFoldersTree_Parent_utFoldersTree_NeedMakeForm
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_49E15BACC408_view

  MEVIEW ME_60EE3E3C50F2_view
   MELINK Original WL 'ME_60EE3E3C50F2' '4AA4B2ED00FE.ms.model.script' ; // enFoldersElementInfo_utFoldersProperty_Child_utFoldersProperty_NeedMakeForm
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_60EE3E3C50F2_view

  MELIST Views
   Seq: ( ME_4FFAA4A801DD_view // cfFolders
   ME_010F44F16CA4_view // Folders$FSFCaptionLocalConstants
   ME_C0B08AD85726_view // cfFolders_Navigator_utFolders_NeedMakeForm
   ME_49E15BACC408_view // enFoldersTree_utFoldersTree_Parent_utFoldersTree_NeedMakeForm
   ME_60EE3E3C50F2_view // enFoldersElementInfo_utFoldersProperty_Child_utFoldersProperty_NeedMakeForm
   )
  ; // Views
 ENDMEDIAGRAM // ME_4AA4B2ED00FE_main

 MELIST Diagrams
  Seq: ( ME_4AA4B2ED00FE_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4AA4B2ED00FE_diagrams
