// Consultation$Lib 4ABCF16F01CD VCMControllers Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4ABCF16F01CD_diagrams

 MEDIAGRAM ME_4ABCF16F01CD_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4ABCF16F01CD' ; // Consultation$Lib

  MEVIEW ME_4ABCF04F00DF_view
   MELINK Original WL? 'ME_4ABCF04F00DF' ; // ConsultationDomainInterfaces
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4ABCF04F00DF_view

  MEVIEW ME_4ABCF1450282_view
   MELINK Original WL? 'ME_4ABCF1450282' ; // ConsultationDomain
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4ABCF1450282_view

  MELIST Views
   Seq: ( ME_4ABCF04F00DF_view // ConsultationDomainInterfaces
   ME_4ABCF1450282_view // ConsultationDomain
   )
  ; // Views
 ENDMEDIAGRAM // ME_4ABCF16F01CD_main

 MELIST Diagrams
  Seq: ( ME_4ABCF16F01CD_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4ABCF16F01CD_diagrams
