// Radio 4AC5DA5A01AD Views Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4AC5DA5A01AD_diagrams

 MEDIAGRAM ME_4AC5DA5A01AD_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4AC5DA5A01AD' ; // Radio

  MEVIEW ME_4AC608E40294_view
   MELINK Original WL? 'ME_4AC608E40294' ; // TvtGroupBox
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4AC608E40294_view

  MELIST Views
   Seq: ( ME_4AC608E40294_view // TvtGroupBox
   )
  ; // Views
 ENDMEDIAGRAM // ME_4AC5DA5A01AD_main

 MELIST Diagrams
  Seq: ( ME_4AC5DA5A01AD_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4AC5DA5A01AD_diagrams
