// UsesContainer 4B2A2ADB0305 MDAClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4B2A2ADB0305_diagrams

 MEDIAGRAM ME_4B2A2ADB0305_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4B2A2ADB0305' '470384F502CE.ms.model.script' ; // UsesContainer

  MEVIEW ME_47049B5902FD_view
   MELINK Original WL 'ME_47049B5902FD' '470384F502CE.ms.model.script' ; // uses
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_47049B5902FD_view

  MELIST Views
   Seq: ( ME_47049B5902FD_view // uses
   )
  ; // Views
 ENDMEDIAGRAM // ME_4B2A2ADB0305_main

 MELIST Diagrams
  Seq: ( ME_4B2A2ADB0305_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4B2A2ADB0305_diagrams
