// Tl3CardinalList 4B2F4382001F SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4B2F4382001F_diagrams

 MEDIAGRAM ME_4B2F4382001F_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4B2F4382001F' ; // Tl3CardinalList

  MEVIEW ME_4B2F43EC01E5_view
   MELINK Original WL 'ME_4B2F43EC01E5' '4B2F4382001F.ms.model.script' ; // ItemType
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4B2F43EC01E5_view

  MELIST Views
   Seq: ( ME_4B2F43EC01E5_view // ItemType
   )
  ; // Views
 ENDMEDIAGRAM // ME_4B2F4382001F_main

 MELIST Diagrams
  Seq: ( ME_4B2F4382001F_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4B2F4382001F_diagrams
