// AttributesHelper 4CEA4CD7006D Interface Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4CEA4CD7006D_diagrams

 MEDIAGRAM ME_4CEA4CD7006D_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4CEA4CD7006D' '45EEAA8E034E.ms.model.script' ; // AttributesHelper

  MEVIEW ME_4CEA4D0702FD_view
   MELINK Original WL 'ME_4CEA4D0702FD' '45EEAA8E034E.ms.model.script' ; // attribute_KW_exists
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4CEA4D0702FD_view

  MEVIEW ME_4CEA4D5D002C_view
   MELINK Original WL 'ME_4CEA4D5D002C' '45EEAA8E034E.ms.model.script' ; // attribute_publish_source_exists
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4CEA4D5D002C_view

  MEVIEW ME_4CEA4EEF01E8_view
   MELINK Original WL 'ME_4CEA4EEF01E8' '45EEAA8E034E.ms.model.script' ; // make
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4CEA4EEF01E8_view

  MELIST Views
   Seq: ( ME_4CEA4D0702FD_view // attribute_KW_exists
   ME_4CEA4D5D002C_view // attribute_publish_source_exists
   ME_4CEA4EEF01E8_view // make
   )
  ; // Views
 ENDMEDIAGRAM // ME_4CEA4CD7006D_main

 MELIST Diagrams
  Seq: ( ME_4CEA4CD7006D_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4CEA4CD7006D_diagrams
