// If1ChildMaker 4CEBB7550046 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4CEBB7550046_diagrams

 MEDIAGRAM ME_4CEBB7550046_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4CEBB7550046' '4C6E92E9016E.ms.model.script' ; // If1ChildMaker

  MEVIEW ME_4CEBB765029D_view
   MELINK Original WL 'ME_4CEBB765029D' '4C6E92E9016E.ms.model.script' ; // MakeChildTag
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4CEBB765029D_view

  MELIST Views
   Seq: ( ME_4CEBB765029D_view // MakeChildTag
   )
  ; // Views
 ENDMEDIAGRAM // ME_4CEBB7550046_main

 MELIST Diagrams
  Seq: ( ME_4CEBB7550046_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4CEBB7550046_diagrams
