// PrimDictionContainer 4D7A69F9028C VCMContainer Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4D7A69F9028C_diagrams

 MEDIAGRAM ME_4D7A69F9028C_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4D7A69F9028C' ; // PrimDictionContainer

  MEVIEW ME_4D7A6D6A0341_view
   MELINK Original WL 'ME_4D7A6D6A0341' '4D7A69F9028C.ms.model.script' ; // Navigator
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4D7A6D6A0341_view

  MEVIEW ME_4D7A7B9601CD_view
   MELINK Original WL 'ME_4D7A7B9601CD' '4D7A69F9028C.ms.model.script' ; // Child
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4D7A7B9601CD_view

  MEVIEW ME_4F5DB0BA0034_view
   MELINK Original WL 'ME_4F5DB0BA0034' '4D7A69F9028C.ms.model.script' ; // ExcludeAll
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4F5DB0BA0034_view

  MEVIEW ME_4D7F8B4A0214_view
   MELINK Original WL 'ME_4D7F8B4A0214' '4D7A69F9028C.ms.model.script' ; // ChildZoneQueryResize
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4D7F8B4A0214_view

  MEVIEW ME_4D7A6C630193_view
   MELINK Original WL 'ME_4D7A6C630193' '4D7A69F9028C.ms.model.script' ; // pnBackground
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4D7A6C630193_view

  MELIST Views
   Seq: ( ME_4D7A6D6A0341_view // Navigator
   ME_4D7A7B9601CD_view // Child
   ME_4F5DB0BA0034_view // ExcludeAll
   ME_4D7F8B4A0214_view // ChildZoneQueryResize
   ME_4D7A6C630193_view // pnBackground
   )
  ; // Views
 ENDMEDIAGRAM // ME_4D7A69F9028C_main

 MELIST Diagrams
  Seq: ( ME_4D7A69F9028C_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4D7A69F9028C_diagrams
