// TtfwCompilingWord 4DB6C8F30161 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4DB6C8F30161_diagrams

 MEDIAGRAM ME_4DB6C8F30161_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4DB6C8F30161' ; // TtfwCompilingWord

  MEVIEW ME_4DB6C99F026E_view
   MELINK Original WL 'ME_4DB6C99F026E' '4DB6C8F30161.ms.model.script' ; // EndBracket
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4DB6C99F026E_view

  MEVIEW ME_4DB6CDDA038B_view
   MELINK Original WL 'ME_4DB6CDDA038B' '4DB6C8F30161.ms.model.script' ; // BeforeCompile
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4DB6CDDA038B_view

  MEVIEW ME_4DB6CE2302C9_view
   MELINK Original WL 'ME_4DB6CE2302C9' '4DB6C8F30161.ms.model.script' ; // AfterCompile
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4DB6CE2302C9_view

  MEVIEW ME_4DB6F2760023_view
   MELINK Original WL 'ME_4DB6F2760023' '4DB6C8F30161.ms.model.script' ; // UnknownWord
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4DB6F2760023_view

  MEVIEW ME_4DB9B446039A_view
   MELINK Original WL 'ME_4DB9B446039A' '4DB6C8F30161.ms.model.script' ; // AfterWordMaxCount
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4DB9B446039A_view

  MEVIEW ME_4DB9B502013D_view
   MELINK Original WL 'ME_4DB9B502013D' '4DB6C8F30161.ms.model.script' ; // AcceptsKeyWordAfter
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_4DB9B502013D_view

  MEVIEW ME_4DBAEE0D028D_view
   MELINK Original WL 'ME_4DBAEE0D028D' '4DB6C8F30161.ms.model.script' ; // CompiledWordClass
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_4DBAEE0D028D_view

  MEVIEW ME_4DC19432023E_view
   MELINK Original WL 'ME_4DC19432023E' '4DB6C8F30161.ms.model.script' ; // DoStringToken
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_4DC19432023E_view

  MEVIEW ME_4DC2DEE70178_view
   MELINK Original WL 'ME_4DC2DEE70178' '4DB6C8F30161.ms.model.script' ; // AcceptsEOF
   MEPROP X 200
   MEPROP Y 180
  ENDMEVIEW // ME_4DC2DEE70178_view

  MEVIEW ME_4EF4A9500352_view
   MELINK Original WL 'ME_4EF4A9500352' '4DB6C8F30161.ms.model.script' ; // DisabledEndBracket
   MEPROP X 360
   MEPROP Y 180
  ENDMEVIEW // ME_4EF4A9500352_view

  MEVIEW ME_4F21A4F60049_view
   MELINK Original WL 'ME_4F21A4F60049' '4DB6C8F30161.ms.model.script' ; // FillCompiledWord
   MEPROP X 520
   MEPROP Y 180
  ENDMEVIEW // ME_4F21A4F60049_view

  MEVIEW ME_4F395A6902D2_view
   MELINK Original WL 'ME_4F395A6902D2' '4DB6C8F30161.ms.model.script' ; // GetWordProducerForCompiledClass
   MEPROP X 680
   MEPROP Y 180
  ENDMEVIEW // ME_4F395A6902D2_view

  MEVIEW ME_4F3AB3B101FC_view
   MELINK Original WL 'ME_4F3AB3B101FC' '4DB6C8F30161.ms.model.script' ; // SuppressNextImmediate
   MEPROP X 840
   MEPROP Y 180
  ENDMEVIEW // ME_4F3AB3B101FC_view

  MEVIEW ME_4F3BCE1501F0_view
   MELINK Original WL 'ME_4F3BCE1501F0' '4DB6C8F30161.ms.model.script' ; // AfterCodePartAdded
   MEPROP X 1000
   MEPROP Y 180
  ENDMEVIEW // ME_4F3BCE1501F0_view

  MEVIEW ME_53E21481021D_view
   MELINK Original WL 'ME_53E21481021D' '4DB6C8F30161.ms.model.script' ; // DoKeyword
   MEPROP X 40
   MEPROP Y 320
  ENDMEVIEW // ME_53E21481021D_view

  MEVIEW ME_560941240035_view
   MELINK Original WL 'ME_560941240035' '4DB6C8F30161.ms.model.script' ; // CheckWordInfoOnCompile
   MEPROP X 200
   MEPROP Y 320
  ENDMEVIEW // ME_560941240035_view

  MELIST Views
   Seq: ( ME_4DB6C99F026E_view // EndBracket
   ME_4DB6CDDA038B_view // BeforeCompile
   ME_4DB6CE2302C9_view // AfterCompile
   ME_4DB6F2760023_view // UnknownWord
   ME_4DB9B446039A_view // AfterWordMaxCount
   ME_4DB9B502013D_view // AcceptsKeyWordAfter
   ME_4DBAEE0D028D_view // CompiledWordClass
   ME_4DC19432023E_view // DoStringToken
   ME_4DC2DEE70178_view // AcceptsEOF
   ME_4EF4A9500352_view // DisabledEndBracket
   ME_4F21A4F60049_view // FillCompiledWord
   ME_4F395A6902D2_view // GetWordProducerForCompiledClass
   ME_4F3AB3B101FC_view // SuppressNextImmediate
   ME_4F3BCE1501F0_view // AfterCodePartAdded
   ME_53E21481021D_view // DoKeyword
   ME_560941240035_view // CheckWordInfoOnCompile
   )
  ; // Views
 ENDMEDIAGRAM // ME_4DB6C8F30161_main

 MELIST Diagrams
  Seq: ( ME_4DB6C8F30161_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4DB6C8F30161_diagrams
