// ChangesBetweenEditionsImplementation 4DDCD7B600D5 ControllerUnit Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4DDCD7B600D5_diagrams

 MEDIAGRAM ME_4DDCD7B600D5_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4DDCD7B600D5' ; // ChangesBetweenEditionsImplementation

  MEVIEW ME_4DDCD7D0002E_view
   MELINK Original WL? 'ME_4DDCD7D0002E' ; // TsdsChangesBetweenEditions
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4DDCD7D0002E_view

  MEVIEW ME_4DDCD9670300_view
   MELINK Original WL? 'ME_4DDCD9670300' ; // TnsChangesBetweenEditionsInfo
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4DDCD9670300_view

  MEVIEW ME_4DDCDD68019E_view
   MELINK Original WL? 'ME_4DDCDD68019E' ; // TdsChangesBetweenEditions
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4DDCDD68019E_view

  MEVIEW ME_4DDCF660018A_view
   MELINK Original WL? 'ME_4DDCF660018A' ; // TsdsChangesBetweenEditionsData
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4DDCF660018A_view

  MEVIEW ME_4DDD0D92039C_view
   MELINK Original WL? 'ME_4DDD0D92039C' ; // TnsChangesBetweenEditionsDocumentContainer
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4DDD0D92039C_view

  MEVIEWLINK ME_4DDD0DAA01D8_viewlink
   MELINK Original WL 'ME_4DDD0DAA01D8' '4DDCDD68019E.ms.model.script' ;
   MELINK From ME_4DDCDD68019E_view ;
   MELINK To ME_4DDD0D92039C_view ;
  ENDMEVIEWLINK // ME_4DDD0DAA01D8_viewlink

  MELIST Views
   Seq: ( ME_4DDCD7D0002E_view // TsdsChangesBetweenEditions
   ME_4DDCD9670300_view // TnsChangesBetweenEditionsInfo
   ME_4DDCDD68019E_view // TdsChangesBetweenEditions
   ME_4DDCF660018A_view // TsdsChangesBetweenEditionsData
   ME_4DDD0D92039C_view // TnsChangesBetweenEditionsDocumentContainer
   ME_4DDD0DAA01D8_viewlink // TdsChangesBetweenEditions ==> TnsChangesBetweenEditionsDocumentContainer
   )
  ; // Views
 ENDMEDIAGRAM // ME_4DDCD7B600D5_main

 MELIST Diagrams
  Seq: ( ME_4DDCD7B600D5_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4DDCD7B600D5_diagrams
