// Common$MemUsage 4F882119031B VCMOperations Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4F882119031B_diagrams

 MEDIAGRAM ME_4F882119031B_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4F882119031B' '4A8E792A0108.ms.model.script' ; // Common$MemUsage

  MEVIEW ME_4F88213001DE_view
   MELINK Original WL 'ME_4F88213001DE' '4A8E792A0108.ms.model.script' ; // MemUsage
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4F88213001DE_view

  MELIST Views
   Seq: ( ME_4F88213001DE_view // MemUsage
   )
  ; // Views
 ENDMEDIAGRAM // ME_4F882119031B_main

 MELIST Diagrams
  Seq: ( ME_4F882119031B_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4F882119031B_diagrams
