// TvcmTBPosStringArray 52AAFF960114 Vector Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_52AAFF960114_diagrams

 MEDIAGRAM ME_52AAFF960114_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_52AAFF960114' '4B30EC67025A.ms.model.script' ; // TvcmTBPosStringArray

  MEVIEW ME_52AAFFCB028F_view
   MELINK Original WL 'ME_52AAFFCB028F' '4B30EC67025A.ms.model.script' ; // 
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_52AAFFCB028F_view

  MELIST Views
   Seq: ( ME_52AAFFCB028F_view )
  ; // Views
 ENDMEDIAGRAM // ME_52AAFF960114_main

 MELIST Diagrams
  Seq: ( ME_52AAFF960114_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_52AAFF960114_diagrams
