// File 53BFCC8503AA Tag Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_53BFCC8503AA_diagrams

 MEDIAGRAM ME_53BFCC8503AA_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_53BFCC8503AA' '484A470100DD.ms.model.script' ; // File

  MEVIEW ME_54B3773402D2_view
   MELINK Original WL 'ME_54B3773402D2' '484A470100DD.ms.model.script' ; // AdditionalFiles
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_54B3773402D2_view

  MELIST Views
   Seq: ( ME_54B3773402D2_view // AdditionalFiles
   )
  ; // Views
 ENDMEDIAGRAM // ME_53BFCC8503AA_main

 MELIST Diagrams
  Seq: ( ME_53BFCC8503AA_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_53BFCC8503AA_diagrams
