// csGetReadyToDeliveryTasks 546458310155 Tag Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_546458310155_diagrams

 MEDIAGRAM ME_546458310155_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_546458310155' '484A470100DD.ms.model.script' ; // csGetReadyToDeliveryTasks

  MEVIEW ME_546459BB01D1_view
   MELINK Original WL 'ME_546459BB01D1' '484A470100DD.ms.model.script' ; // UserID
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_546459BB01D1_view

  MELIST Views
   Seq: ( ME_546459BB01D1_view // UserID
   )
  ; // Views
 ENDMEDIAGRAM // ME_546458310155_main

 MELIST Diagrams
  Seq: ( ME_546458310155_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_546458310155_diagrams
