// ScriptEngine$F1 54DB83140023 Library Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_54DB83140023_diagrams

 MEDIAGRAM ME_54DB83140023_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_54DB83140023' ; // ScriptEngine$F1

  MEVIEW ME_505C848E02D6_view
   MELINK Original WL? 'ME_505C848E02D6' ; // StatusBarWords
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_505C848E02D6_view

  MEVIEW ME_510134290310_view
   MELINK Original WL? 'ME_510134290310' ; // TaskPanelWords
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_510134290310_view

  MELIST Views
   Seq: ( ME_505C848E02D6_view // StatusBarWords
   ME_510134290310_view // TaskPanelWords
   )
  ; // Views
 ENDMEDIAGRAM // ME_54DB83140023_main

 MELIST Diagrams
  Seq: ( ME_54DB83140023_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_54DB83140023_diagrams
