// Tl3FormatActionInfoHelper 551442110069 Service Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_551442110069_diagrams

 MEDIAGRAM ME_551442110069_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_551442110069' ; // Tl3FormatActionInfoHelper

  MEVIEW ME_5514424D01A2_view
   MELINK Original WL 'ME_5514424D01A2' '551442110069.ms.model.script' ; // Format
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5514424D01A2_view

  MELIST Views
   Seq: ( ME_5514424D01A2_view // Format
   )
  ; // Views
 ENDMEDIAGRAM // ME_551442110069_main

 MELIST Diagrams
  Seq: ( ME_551442110069_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_551442110069_diagrams
