// Dialogs 55C8CD14003A ScriptKeywords Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_55C8CD14003A_diagrams

 MEDIAGRAM ME_55C8CD14003A_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_55C8CD14003A' ; // Dialogs

  MEVIEW ME_55C8CD3401D2_view
   MELINK Original WL? 'ME_55C8CD3401D2' ; // TTextSearchDlgWordsPack
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_55C8CD3401D2_view

  MEVIEW ME_55C8CD820269_view
   MELINK Original WL? 'ME_55C8CD820269' ; // TTableConvParamDialogWordsPack
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_55C8CD820269_view

  MEVIEW ME_55C8CD9D0010_view
   MELINK Original WL? 'ME_55C8CD9D0010' ; // TNewSubDlgWordsPack
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_55C8CD9D0010_view

  MEVIEW ME_55C8CDB30208_view
   MELINK Original WL? 'ME_55C8CDB30208' ; // TSpellCheckDlgWordsPack
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_55C8CDB30208_view

  MEVIEW ME_55C8CDD703B3_view
   MELINK Original WL? 'ME_55C8CDD703B3' ; // TPicSizeEditDlgWordsPack
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_55C8CDD703B3_view

  MEVIEW ME_55C8CDFC039B_view
   MELINK Original WL? 'ME_55C8CDFC039B' ; // TExprEditorWordsPack
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_55C8CDFC039B_view

  MELIST Views
   Seq: ( ME_55C8CD3401D2_view // TTextSearchDlgWordsPack
   ME_55C8CD820269_view // TTableConvParamDialogWordsPack
   ME_55C8CD9D0010_view // TNewSubDlgWordsPack
   ME_55C8CDB30208_view // TSpellCheckDlgWordsPack
   ME_55C8CDD703B3_view // TPicSizeEditDlgWordsPack
   ME_55C8CDFC039B_view // TExprEditorWordsPack
   )
  ; // Views
 ENDMEDIAGRAM // ME_55C8CD14003A_main

 MELIST Diagrams
  Seq: ( ME_55C8CD14003A_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_55C8CD14003A_diagrams
