// array of PTypeInfo 5617F48201F6 Vector Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_5617F48201F6_diagrams

 MEDIAGRAM ME_5617F48201F6_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_5617F48201F6' '4DAF19F600C5.ms.model.script' ; // array of PTypeInfo

  MEVIEW ME_5617F4990100_view
   MELINK Original WL 'ME_5617F4990100' '4DAF19F600C5.ms.model.script' ; // 
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5617F4990100_view

  MELIST Views
   Seq: ( ME_5617F4990100_view )
  ; // Views
 ENDMEDIAGRAM // ME_5617F48201F6_main

 MELIST Diagrams
  Seq: ( ME_5617F48201F6_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_5617F48201F6_diagrams
