// ElementProxy 561D3E94025C MDAClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_561D3E94025C_diagrams

 MEDIAGRAM ME_561D3E94025C_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_561D3E94025C' '561D307100B4.ms.model.script' ; // ElementProxy

  MEVIEW ME_561FA29C0136_view
   MELINK Original WL 'ME_561FA29C0136' '561D307100B4.ms.model.script' ; // IsElementProxy
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_561FA29C0136_view

  MELIST Views
   Seq: ( ME_561FA29C0136_view // IsElementProxy
   )
  ; // Views
 ENDMEDIAGRAM // ME_561D3E94025C_main

 MELIST Diagrams
  Seq: ( ME_561D3E94025C_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_561D3E94025C_diagrams
