// Работа с аннотацией 579B136C000F UseCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_579B136C000F_diagrams

 MEDIAGRAM ME_579B136C000F_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_579B136C000F' '53F327E402A1.ms.model.script' ; // Работа с аннотацией

  MEVIEW ME_579B15F30144_view
   MELINK Original WL 'ME_579B15F30144' '53F327E402A1.ms.model.script' ; // Установка заголовка аннотации
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_579B15F30144_view

  MEVIEW ME_579B161300DA_view
   MELINK Original WL 'ME_579B161300DA' '53F327E402A1.ms.model.script' ; // Установка класса аннотации
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_579B161300DA_view

  MEVIEW ME_579B163A0090_view
   MELINK Original WL 'ME_579B163A0090' '53F327E402A1.ms.model.script' ; // Удаление аннотации
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_579B163A0090_view

  MEVIEW ME_579B165501A0_view
   MELINK Original WL 'ME_579B165501A0' '53F327E402A1.ms.model.script' ; // Анонсирование аннотации
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_579B165501A0_view

  MELIST Views
   Seq: ( ME_579B15F30144_view // Установка заголовка аннотации
   ME_579B161300DA_view // Установка класса аннотации
   ME_579B163A0090_view // Удаление аннотации
   ME_579B165501A0_view // Анонсирование аннотации
   )
  ; // Views
 ENDMEDIAGRAM // ME_579B136C000F_main

 MELIST Diagrams
  Seq: ( ME_579B136C000F_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_579B136C000F_diagrams
