// TDocumentSettingsService 57A4A44F02FA Service Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_57A4A44F02FA_diagrams

 MEDIAGRAM ME_57A4A44F02FA_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_57A4A44F02FA' '4DDD3D520070.ms.model.script' ; // TDocumentSettingsService

  MEVIEW ME_57A4A4740274_view
   MELINK Original WL 'ME_57A4A4740274' '4DDD3D520070.ms.model.script' ; // ShowChangesInfoSetting
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_57A4A4740274_view

  MELIST Views
   Seq: ( ME_57A4A4740274_view // ShowChangesInfoSetting
   )
  ; // Views
 ENDMEDIAGRAM // ME_57A4A44F02FA_main

 MELIST Diagrams
  Seq: ( ME_57A4A44F02FA_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_57A4A44F02FA_diagrams
