// msmWordsIndexPack 57E511340388 ScriptKeywordsPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_57E511340388_diagrams

 MEDIAGRAM ME_57E511340388_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_57E511340388' ; // msmWordsIndexPack

  MEVIEW ME_57E511610278_view
   MELINK Original WL 'ME_57E511610278' '57E511340388.ms.model.script' ; // msm_AddWordToIndex
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_57E511610278_view

  MELIST Views
   Seq: ( ME_57E511610278_view // msm_AddWordToIndex
   )
  ; // Views
 ENDMEDIAGRAM // ME_57E511340388_main

 MELIST Diagrams
  Seq: ( ME_57E511340388_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_57E511340388_diagrams
