// csMultiOperation 57EE4F6402C7 Tag Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_57EE4F6402C7_diagrams

 MEDIAGRAM ME_57EE4F6402C7_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_57EE4F6402C7' '484A470100DD.ms.model.script' ; // csMultiOperation

  MEVIEW ME_57EE4F930134_view
   MELINK Original WL 'ME_57EE4F930134' '484A470100DD.ms.model.script' ; // FamilyID
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_57EE4F930134_view

  MEVIEW ME_57EE4FC10280_view
   MELINK Original WL 'ME_57EE4FC10280' '484A470100DD.ms.model.script' ; // Operation
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_57EE4FC10280_view

  MEVIEW ME_57FF729C027F_view
   MELINK Original WL 'ME_57FF729C027F' '484A470100DD.ms.model.script' ; // DocumentIDList
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_57FF729C027F_view

  MELIST Views
   Seq: ( ME_57EE4F930134_view // FamilyID
   ME_57EE4FC10280_view // Operation
   ME_57FF729C027F_view // DocumentIDList
   )
  ; // Views
 ENDMEDIAGRAM // ME_57EE4F6402C7_main

 MELIST Diagrams
  Seq: ( ME_57EE4F6402C7_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_57EE4F6402C7_diagrams
