// ImsmModelElementListWordsPack 58095A5103B5 ScriptKeywordsPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_58095A5103B5_diagrams

 MEDIAGRAM ME_58095A5103B5_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_58095A5103B5' ; // ImsmModelElementListWordsPack

  MEVIEW ME_58095A9B0031_view
   MELINK Original WL 'ME_58095A9B0031' '58095A5103B5.ms.model.script' ; // Add
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_58095A9B0031_view

  MEVIEW ME_580962690025_view
   MELINK Original WL 'ME_580962690025' '58095A5103B5.ms.model.script' ; // Make
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_580962690025_view

  MELIST Views
   Seq: ( ME_58095A9B0031_view // Add
   ME_580962690025_view // Make
   )
  ; // Views
 ENDMEDIAGRAM // ME_58095A5103B5_main

 MELIST Diagrams
  Seq: ( ME_58095A5103B5_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_58095A5103B5_diagrams
