// TmsmSomeWordsListPrim 58114D530021 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_58114D530021_diagrams

 MEDIAGRAM ME_58114D530021_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_58114D530021' ; // TmsmSomeWordsListPrim

  MEVIEW ME_58115104021E_view
   MELINK Original WL 'ME_58115104021E' '58114D530021.ms.model.script' ; // Create
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_58115104021E_view

  MEVIEW ME_5811547001A8_view
   MELINK Original WL 'ME_5811547001A8' '58114D530021.ms.model.script' ; // DoGetCount
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_5811547001A8_view

  MEVIEW ME_581154A203C2_view
   MELINK Original WL 'ME_581154A203C2' '58114D530021.ms.model.script' ; // DoGetItem
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_581154A203C2_view

  MELIST Views
   Seq: ( ME_58115104021E_view // Create
   ME_5811547001A8_view // DoGetCount
   ME_581154A203C2_view // DoGetItem
   )
  ; // Views
 ENDMEDIAGRAM // ME_58114D530021_main

 MELIST Diagrams
  Seq: ( ME_58114D530021_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_58114D530021_diagrams
