//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Downloader.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DOWNLOADER_DIALOG           102
#define IDS_ERROR_CONNECTION_FAILED     102
#define IDS_CONNECTION_FAILED           102
#define IDS_ERROR_INCORRECT_LOGIN       103
#define IDS_ERROR_HTTP_ERROR            104
#define IDS_DOWNLOAD_CANCEL             105
#define IDS_QUEST_FILE_ALREADY_EXIST    106
#define IDS_STATIC_DOWNLOAD_NORMAL      107
#define IDS_STATIC_DOWNLOAD_CANCELED    108
#define IDS_STATIC_DOWNLOAD_ABORTED     109
#define IDS_ERROR_CLOSED_FILE           110
#define IDS_QUEST_EXIT_FROM_PROGAM      111
#define IDS_MSG_CLOSED_PROGRAM          112
#define IDS_APPLICATION_ALREADY_RUNNING 113
#define IDS_DONT_RUN_PROGRAM            114
#define IDS_FILE_NOTFOUND               115
#define IDS_ERROR_DOWNLOAD              116
#define IDS_UNEXPECTED_ERROR            117
#define IDS_QUERY_TO_SERVER             118
#define IDS_DOWNLOAD_FILE               119
#define IDS_ERROR_NO_UPDATE             120
#define IDS_ERROR_INCORRECT_UPDATE_PERIOD 122
#define IDS_ERROR_FILE_NOT_OPEN         123
#define IDS_MSG_CHECK_REGISTRATION      124
#define IDS_MSG_RUNNING_PROGRAM         125
#define IDS_ERROR_LOAD_SECOND_APPLICATION 126
#define IDS_ERROR_NOT_INIT_LOGIN_OR_PASSWORD 127
#define IDR_MAINFRAME                   128
#define IDS_ERROR_NOT_CREATE_THREAD     128
#define IDD_LOGIN                       129
#define IDS_ERROR_PROGRAM_CANT_RUNNING  129
#define IDS_ERROR_CANT_RECEIVE_DIRECTORY_PATH 130
#define IDD_STATUS_PROCESS_DIALOG       131
#define IDS_BASESORG_NOTFOUND           131
#define IDS_BASESORGPRIMARY             132
#define IDS_BASESORGBADCOMPLECT         133
#define IDS_ERROROPENINGBASE            134
#define IDS_ERRORREADINGHERE            135
#define IDS_BASEPACKED                  136
#define IDB_DESIGNED                    137
#define IDS_BASENOTGL                   137
#define IDB_GARANT                      138
#define IDS_CANTFINDBASEINFO            138
#define IDD_INTERNET_CONNECT            139
#define IDS_BASEBADREVS                 139
#define IDD_END_PROCESS                 140
#define IDS_MSG_RUNNING_PROGRAM_IN_AUTO_MODE 140
#define IDS_ERROR_DOWNLOAD_DATA         141
#define IDS_ERROR_HTTP_GETINFO          142
#define IDS_MSG_STOP_DOWNLOAD           143
#define IDS_ERROR_NOT_LOAD_DLL          144
#define IDS_ERROR_LOAD_DLL              145
#define IDS_ERROR_WSA_STARTUP           146
#define IDB_PROGRESS                    147
#define IDD_DOWNLOAD_PROCESS            147
#define IDS_ERROR_WINSOCK_NOT_SUPPORT   147
#define IDS_ERROR_PROXY_ADDR_EMPTY      148
#define IDS_ERROR_PROXY_PORT_EMPTY      149
#define IDS_ERROR_EMPTY_FILE_NAME       150
#define IDS_ERROR_USERS_AUTHORIZATION   151
#define IDS_QUEST_ABORTED_FILE_EXIST    152
#define IDS_QUEST_ABORTED_FILE_ALREADY_EXIST 152
#define IDS_DOWNLOAD_FILE_PLUS          153
#define IDS_PROXY_PING                  154
#define IDB_PROGRESS_                   155
#define IDS_USE_PROXY_SERVER            155
#define IDS_INCORRECT_PROXY_SETTINGS    156
#define IDD_MODAL_MESSAGE_BOX           157
#define IDS_USE_SERVER_FROM_COMMAND_LINE 157
#define IDD_INTERNET_ACCESS_SETTINGS    158
#define IDS_REG_PROXY_NOT_FOUND         158
#define IDD_DIALOG_REWRITE_EXIST_FILE   159
#define IDS_USE_SERVER                  159
#define IDS_INTERNET_NOT_FOUND          160
#define IDS_GARANT_SERVERS_NOT_FOUND    161
#define IDS_CONNECT_SYSTEM_EXCEPTION    162
#define IDD_PILOT_LOGIN                 162
#define IDS_USE_PRECONFIG_TYPE          163
#define IDS_PING_HOST                   164
#define IDB_NTCOMPATIBLE                164
#define IDS_RECONNECT_MESSAGE           165
#define IDS_SESSION_LOG_DELIMITER       166
#define IDS_DOWNLOAD_QUERY              167
#define IDS_DOWNLOAD_INFO               168
#define IDS_ADD_DOWNLOAD_INFO           169
#define IDS_USER_AGENT                  170
#define IDS_IP_CONFIG                   171
#define IDS_INET_ACCESS_SETTING_CHANGE  172
#define IDS_SYSTEM_EXCEPTION            173
#define IDS_RUN_UPDATE_UTIL             174
#define IDS_STATIC_NOT_DOWLOAD_DATA     175
#define IDS_CANT_RUN_PROCESS            176
#define IDS_ATTEMPT_USER_AUTHORIZATION  177
#define IDS_QUERY_RECEIVE_FILE_LENGTH_RESULT_MSG 178
#define IDS_UNKNOWN_EXCEPTION           179
#define IDS_ATTEMPT_RENEW_CONNECTION    180
#define IDS_DOWNLOAD_DATA_PROCESS       181
#define IDS_INCORRECT_TIMEOUT_PARAM     182
#define IDS_FATAL_ERROR_CLOSE           183
#define IDS_FATAL_ERROR_DOWNLOAD_DATA   184
#define IDS_TRANSIENT                   185
#define IDS_SERVER_NOT_FOUND            186
#define IDS_BAD_NETWORK_CONFIG          187
#define IDS_IP_ADDRESS_NOT_FOUND        188
#define IDS_DATANOTFOUND                189
#define IDS_USER_ALREADY_EXIST_IN_ONLINE 190
#define IDS_USER_IS_LOCKED              191
#define IDS_PILOT_DATE_NOT_INITIALIZE   192
#define IDS_EXCEPTION_USER_AUTHORIZATION 193
#define IDS_PILOT_NAME                  194
#define IDS_NEMESIS_NAME                195
#define IDS_INPUT_USERNAME              196
#define IDD_NEMESIS_LOGIN               197
#define IDS_ERROR_PROXY_LOGIN_EMPTY     198
#define IDS_ERROR_PROXY_PASSWORD_EMPTY  199
#define IDS_ATTEMPT_USER_AUTHORIZATION_ON_PROXY 200
#define IDS_NEMESIS_BASE_NOT_EXIST      201
#define IDS_BAD_PARAMS                  202
#define IDS_BAD_PROXYPORT               203
#define IDS_BADPING_MESSAGE             204
#define IDS_ATTENTION                   205
#define IDS_CHOOSE_DIR                  206
#define IDS_FATAL_ERROR                 207
#define IDS_COMPLECT_NOT_REGISTRED      208
#define IDS_CHECK_INFO                  209
#define IDS_NOT_ENOUGH_SPACE            210
#define IDS_SERVER_IS_STARTING          211
#define	IDS_ATTENTION_COLON		212
#define IDC_START_DOWNLOAD              1000
#define IDC_BEGIN_DATE                  1003
#define IDC_END_DATE                    1004
#define IDC_COMBO_COMPLECT              1006
#define IDC_PATH                        1008
#define IDC_BROWSE                      1009
#define IDC_LOGIN                       1010
#define IDC_PASSWORD                    1011
#define IDC_APPLY                       1016
#define IDC_STATUS_STATIC               1019
#define IDC_PROGRESS_STATUS             1032
#define IDBACK                          1034
#define IDC_IMAGE_PROGRESS              1039
#define IDC_FINAL_MESSAGE_TEXT          1040
#define IDC_STATIC____                  1042
#define IDC_STATIC_CHECK_REGISTRATION   1043
#define ID_EVENT                        1044
#define IDC_STATIC_COMMENT              1045
#define IDC_RADIO_OPEN_TYPE_DIRECT      1050
#define IDC_RADIO_OPEN_TYPE_PROXY       1051
#define IDC_RADIO_OPEN_TYPE_PRECONFIG   1052
#define IDC_INET_SETTINGS               1053
#define IDC_EDIT_PROXY_NAME             1054
#define IDC_EDIT_PROXY_PORT             1055
#define IDC_BTN_ADD                     1056
#define IDC_CHECK_RELOAD_CACHE          1062
#define IDC_CHECK_NO_CACHE_WRITE        1063
#define IDC_INPUT_NAME_STATIC           1064
#define IDC_EDIT1                       1065
#define IDC_EDIT_PROXY_LOGIN            1065
#define IDC_CHECK_PROXY_AUTHENTICATION  1066
#define IDC_EDIT_PROXY_PASSWORD         1067

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
