<<Library>> "F1 AutoTests"
 %UID '4E2596720102'
 %DEPENDS
  U$ '4B2A0D4A006F' /* DUnit */
  U$ '4DC3D1BC0060' /* ScriptTestLibrary */
  U$ '4E20331F01E4' /* "F1 Shell Tests Core" */
  U$ '5130499D0080' /* "DUnit Script Support" */
 ; // %DEPENDS
 %META
  %upv "exec mode" 'concluded'
  %upv "gui" 'prj'
  %upv "ifdef" 'nsTest'
  %upv "is namespace" true
  %upv "vendor" 'none'
 ; // %META
 %TOBEINCLUDED
  U$ '4B2A0D4A006F' /* DUnit */
  U$ '4DC3D1BC0060' /* ScriptTestLibrary */
  U$ '4E20331F01E4' /* "F1 Shell Tests Core" */
  U$ '5130499D0080' /* "DUnit Script Support" */
 ; // %TOBEINCLUDED
 %CHILDREN
  
  <<Unit>> AutoTests
   %UID '4E25969000FF'
   %DEPENDS
    U$ '4B2A0D6A0077' /* Source */
    U$ '4DB01C7F03C7' /* Core */
    U$ '5130776E01BE' /* DUnitKeyWordsSupport */
   ; // %DEPENDS
   %TOBEINCLUDED
    U$ '4B2A0D4A006F' /* DUnit */
    U$ '4E20331F01E4' /* "F1 Shell Tests Core" */
    U$ '5130499D0080' /* "DUnit Script Support" */
   ; // %TOBEINCLUDED
   %CHILDREN
    
     <<SimpleClass>> TF1AutoTestSuite
      %UID '4DC3FE5D03B4'
      %META
       %upv "ifdef" 'nsTest'
       %upv "needs InstanceR" 'undefined'
       %upv "needs script" 'undefined'
       %upv "no hands" false
       %upv "register in scripts" 'undefined'
      ; // %META
      %TOBEINCLUDED
       U$ '5130499D0080' /* "DUnit Script Support" */
      ; // %TOBEINCLUDED
      %INHERITS
       U$ '51307830007E' /* TAutoTestSuiteWithDUnitSupport */
      ; // %INHERITS
      %OVERRIDES
       U$ '5040A3CE0118' /* DoReReadAbstractTests */
      ; // %OVERRIDES
      %LINKS
        <<uses>> "4DC3FF18023D"
         %UID '4DC3FF18023D'
         %TARGET U$ '4DC3F6DD00F1' /* TF1AutoScripter */
        ; // 4DC3FF18023D
        <<uses>> "4EA807C40295"
         %UID '4EA807C40295'
         %TARGET U$ '4B2A0DCE03A9' /* TestFrameWork */
        ; // 4EA807C40295
      ; // %LINKS
      %OPERATIONS
        FINAL <<static>> Register
         %UID '4DC40E2F00E3'
        ; // Register
      ; // %OPERATIONS
     ; // TF1AutoTestSuite
   ; // %CHILDREN
  ; // AutoTests
 ; // %CHILDREN
; // "F1 AutoTests"