attrs_index.o: attrs_index.c ../../../include/osdep.h \
 ../../../libs/mrglib/src/gdbapi.h ../../../libs/mrglib/src/base.h \
 ../../../libs/mrglib/src/mrgdefs.h ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/mrglib/src/stdindex.h gm.h \
 ../../../libs/mrglib/src/sets.h ../../../libs/mrglib/src/log.h
cmdline.o: cmdline.c ../../../libs/mrglib/src/log.h \
 ../../../include/garver.h
doc_index.o: doc_index.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 gm.h ../../../libs/mrglib/src/log.h
gmmain.o: gmmain.c ../../../include/osdep.h \
 ../../../libs/mrglib/src/gdbapi.h ../../../libs/mrglib/src/base.h \
 ../../../libs/mrglib/src/mrgdefs.h ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/mrglib/src/stdindex.h gm.h \
 ../../../libs/mrglib/src/sets.h ../../../libs/gsscreen/src/toys.h \
 ../../../libs/mrglib/src/log.h ready.h ../../../include/garver.h
hier_index.o: hier_index.c ../../../include/osdep.h \
 ../../../libs/mrglib/src/gdbapi.h ../../../libs/mrglib/src/base.h \
 ../../../libs/mrglib/src/mrgdefs.h ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 gm.h
ind_merge.o: ind_merge.c ../../../include/osdep.h \
 ../../../libs/mrglib/src/gdbapi.h ../../../libs/mrglib/src/base.h \
 ../../../libs/mrglib/src/mrgdefs.h ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/mrglib/src/stdindex.h
main.o: main.cpp ../../../libs/gsscreen/src/gsscreen.h
settings.o: settings.c ../../../libs/mrglib/src/profile.h
idxmhlp.o: idxmhlp.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h
profile.o: profile.c ../../../include/osdep.h \
 ../../../libs/mrglib/src/profile.h
aux_index.o: aux_index.c ../../../include/osdep.h \
 ../../../libs/mrglib/src/gdbapi.h ../../../libs/mrglib/src/base.h \
 ../../../libs/mrglib/src/mrgdefs.h ../../../libs/gkdb/src/gardefs.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 gm.h ../../../libs/mrglib/src/log.h
progress.o: progress.cpp ../../../libs/gsscreen/src/pscreen.h
subname_index.o: subname_index.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h gm.h \
 ../../../libs/mrglib/src/sets.h
blob_index.o: blob_index.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h gm.h \
 ../../../libs/mrglib/src/sets.h
ready.o: ready.cpp ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/gkdb/src/basemask.h
