//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestBreeder32.rc
//
#define ID_BACK                         3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_SELECT_FOLDER               102
#define IDS_NEXT_SPF                    103
#define IDS_EXIT_TITLE                  104
#define IDS_EXIT_MSG                    105
#define IDS_FLOPPY_ERR                  106
#define IDS_QTITLE                      107
#define IDS_MSG_0                       108
#define IDS_MSG_1                       109
#define IDS_MSG_2                       110
#define IDS_MSG_3                       111
#define IDS_MSG_20                      112
#define IDS_MSG_21                      113
#define IDS_MSG_50                      114
#define IDS_MSG_51                      115
#define IDS_MSG_60                      116
#define IDS_MSG_61                      117
#define IDS_MSG_62                      118
#define IDS_MSG_63                      119
#define IDS_MSG_64                      120
#define IDS_MSG_65                      121
#define IDS_MSG_66                      122
#define IDS_MSG_67                      123
#define IDS_MSG_68                      124
#define IDS_MSG_60A                     125
#define IDS_BAD_INST_SRC                126
#define IDS_NOT_FIND_INST_SRC           127
#define IDR_MAINFRAME                   128
#define IDS_FRMT0                       128
#define IDD_DIALOG1                     129
#define IDS_FRMT1                       129
#define IDI_CMPLCT_UN                   130
#define IDD_TESTBREEDER32               130
#define IDS_FRMT2                       130
#define IDI_CMPLCT_SL                   131
#define IDB_DESIGNED                    131
#define IDS_FRMT3                       131
#define IDI_SGMNT_SL                    132
#define IDB_GARANT                      132
#define IDS_FRMT20                      132
#define IDI_SGMNT_UN                    133
#define IDS_FRMT21                      133
#define IDS_FRMT30                      134
#define IDS_FRMT31                      135
#define IDS_FRMT31A                     136
#define IDS_FRMT41                      137
#define IDS_FRMT01                      138
#define IDB_BITMAP_ICONS                139
#define IDS_FRMT50                      139
#define IDS_FRMT51                      140
#define IDD_TRIAL_DLG                   140
#define IDS_FRMT52                      141
#define IDD_TRIAL_DLG1                  141
#define IDS_MSG_69                      142
#define IDD_BROWSEDLG                   142
#define IDS_MSG_70                      143
#define IDD_LOGIN_DLG                   143
#define IDS_MSG_71                      144
#define IDC_CURSOR1                     144
#define IDS_MSG_72                      145
#define IDD_NEWNAME                     145
#define IDS_MSG_73                      146
#define IDD_SYNCUPDATE                  146
#define IDS_MSG_74                      147
#define IDD_SELECTBASEFOLDER            147
#define IDS_MSG_75                      148
#define IDD_WAITSERVER                  148
#define IDS_FRMT4                       149
#define IDD_UPDATECOMPLETE              149
#define IDS_MSG_76                      150
#define IDS_MSG_77                      151
#define IDS_FRMT1A                      152
#define IDS_MSG_78                      153
#define IDS_MSG_79                      154
#define IDS_MSG_80                      155
#define IDS_NEXT_DISK                   156
#define IDS_MSG_81                      157
#define IDS_MSG_82                      158
#define IDS_MSG_83                      159
#define IDS_MSG_84                      160
#define IDS_MSG_85                      161
#define IDS_MSG_86                      162
#define IDS_MSG_87                      163
#define IDS_MSG_88                      164
#define IDS_MSG_89                      165
#define IDS_MSG_90                      166
#define IDS_MSG_91                      167
#define IDS_MSG_92                      168
#define IDS_MSG_93                      169
#define IDS_MSG_94                      170
#define IDS_TRANSIENT                   171
#define IDS_SERVER_NOT_FOUND            172
#define IDS_BAD_NETWORK_CONFIG          173
#define IDS_IP_ADDRESS_NOT_FOUND        174
#define IDS_DATANOTFOUND                175
#define IDS_FORBIDDEN                   176
#define IDS_NOMORE_CONNECTIONS          177
#define IDS_MSG_95                      178
#define IDS_MSG_96                      179
#define IDS_MSG_97                      180
#define IDS_MSG_98                      181
#define IDS_MSG_99                      182
#define IDS_MSG_100                     183
#define IDS_MSG_101                     184
#define IDS_MSG_102                     185
#define IDS_MSG_103                     186
#define IDS_MSG_104                     187
#define IDS_MSG_VERSION_EXIT            188
#define IDB_PROGRESS                    188
#define IDS_MSG_VERSION_NEW             189
#define IDS_MSG_VERSION_OLDER           190
#define IDC_FILE                        190
#define IDS_MSG_VERSION_BUGFIX          191
#define IDS_XMLIMPORT                   192
#define IDS_AUTHORIZATION               193
#define IDS_FATAL_END                   194
#define IDS_ERROR_LOAD_SECOND_APPLICATION 195
#define IDS_AUTHORIZATION_EXEPTION      196
#define IDS_COPYING_FILE                197
#define IDS_INSTALL_BASE_EXEPTION       198
#define IDS_BASE_COPY_ERROR             199
#define IDD_WAITUSERS                   200
#define IDS_COPY_DATA_ERROR             200
#define IDS_ENOUGH_ROOM                 201
#define IDS_SETUP_DATA                  202
#define IDS_CANT_UPDATE_BASE            203
#define IDS_ATTENTION                   204
#define IDS_NEED_BYTES                  205
#define IDS_NEED_BYTES_SPLIT            206
#define IDS_FREE_SPACE                  207
#define IDS_CANT_WRITE_TO_DIR           208
#define IDD_WAITXML                     209
#define IDS_SERVER_IS_STARTING          210
#define IDD_DIALOG_BRC                  210
#define IDD_WAITSERVERSTART             211
#define IDC_PROGRESS1                   1000
#define IDC_PROCESS_MSG                 1001
#define IDC_TREE1                       1002
#define ID_NEXT                         1004
#define	ID_COPYPASSWORD			1005
#define IDC_STATIC_1                    1010
#define IDC_STATIC_2                    1011
#define IDC_STATIC_3                    1012
#define IDC_LOGIN                       1013
#define IDC_PASS                        1014
#define IDC_MSG_0                       1015
#define IDC_MSG_1                       1016
#define IDC_MSG_2                       1017
#define IDC_RADIO3                      1018
#define IDC_RADIO4                      1019
#define IDC_EDIT_ANSWER                 1020
#define IDC_RADIO1                      1021
#define IDC_RADIO2                      1022
#define IDC_RADIO5                      1023
#define IDC_RADIO6                      1024
#define IDC_STATIC_AD0                  1026
#define IDC_STATIC_AD1                  1027
#define IDC_EDIT1                       1028
#define IDC_EDIT2                       1029
#define IDC_MSG_DEALER                  1030
#define IDC_LIST2                       1031
#define IDC_STATIC_01                   1032
#define IDC_STATIC_02                   1033
#define IDC_STATIC_03                   1034
#define IDC_RADIONO                     1035
#define IDC_RADIOYES                    1036
#define IDC_BROWSE                      1037
#define IDC_PATH                        1038
#define IDC_NEED                        1039
#define IDC_FREE                        1040
#define IDC_IMAGE_PROGRESS              1042
#define IDC_INET_SETTINGS				1043
#define IDD_INTERNET_ACCESS_SETTINGS    1100

#define IDC_RADIO_OPEN_TYPE_PRECONFIG   1152
#define IDC_RADIO_OPEN_TYPE_PROXY       1151
#define IDC_EDIT_PROXY_NAME             1154
#define IDC_EDIT_PROXY_PORT             1155
#define IDC_RADIO_OPEN_TYPE_DIRECT      1150
#define IDC_CHECK_PROXY_AUTHENTICATION  1166
#define IDC_EDIT_PROXY_LOGIN            1165
#define IDC_EDIT_PROXY_PASSWORD         1167

#define	IDS_ERROR_PROXY_ADDR_EMPTY	1170
#define	IDS_ERROR_PROXY_PORT_EMPTY	1171
#define	IDS_BAD_PROXYPORT       	1172
#define	IDS_ERROR_PROXY_LOGIN_EMPTY	1173
#define	IDS_ERROR_PROXY_PASSWORD_EMPTY	1174
#define	IDS_FZ_NET_ERROR		1175

#define IDD_WAITGARANTRU		2000
#define IDD_WAITSERVERSTART2		2001

#define IDI_COPYPASSWORD		3000
#define	IDS_COPYPASSWORD		3001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        211
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
