attr_index.o: attr_index.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 ../../../libs/mrglib/src/log.h ../../../libs/gsscreen/src/toys.h \
 progress.h message.h
aux_index.o: aux_index.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 ../../../libs/mrglib/src/log.h ../../../libs/gsscreen/src/toys.h \
 progress.h
cmdline.o: cmdline.c ../../../include/osdep.h message.h
doc_index.o: doc_index.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 ../../../libs/mrglib/src/log.h indhlp.h \
 ../../../libs/gsscreen/src/toys.h progress.h
doclist.o: doclist.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 ../../../libs/mrglib/src/log.h ../../../libs/gsscreen/src/toys.h \
 progress.h message.h
main.o: main.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 ../../../libs/mrglib/src/log.h ../../../libs/gsscreen/src/toys.h \
 ready.h message.h ../../../include/garver.h
split_index.o: split_index.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 ../../../libs/gsscreen/src/toys.h message.h
segfile.o: segfile.c ../../../libs/mrglib/src/sets.h \
 ../../../libs/mrglib/src/stdindex.h \
 ../../../libs/mrglib/src/mrgdefs.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/mrglib/src/base.h \
 ../../../libs/mrglib/src/log.h ../../../libs/mrglib/src/gdbapi.h
subname.o: subname.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 ../../../libs/mrglib/src/log.h ../../../libs/gsscreen/src/toys.h \
 progress.h
usage.o: usage.c ../../../include/garver.h
indhlp.o: indhlp.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 ../../../libs/mrglib/src/log.h indhlp.h
hier_index.o: hier_index.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 ../../../libs/mrglib/src/log.h indhlp.h \
 ../../../libs/gsscreen/src/toys.h progress.h
progress.o: progress.c ../../../libs/gsscreen/src/toys.h
msg_tbl.o: msg_tbl.c
hc_index.o: hc_index.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 hc_index.h ../../../libs/mrglib/src/log.h indhlp.h \
 ../../../libs/gsscreen/src/toys.h progress.h
hind_collect.o: hind_collect.c hc_index.h \
 ../../../libs/mrglib/src/gdbapi.h ../../../libs/mrglib/src/base.h \
 ../../../libs/mrglib/src/mrgdefs.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/mrglib/src/stdindex.h \
 ../../../libs/mrglib/src/sets.h
blob_index.o: blob_index.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h \
 ../../../libs/mrglib/src/log.h ../../../libs/gsscreen/src/toys.h \
 progress.h
cr_index.o: cr_index.c ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/mrglib/src/sets.h
ready.o: ready.cc ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/gkdb/src/basemask.h
