optmain.o: optmain.c ../../../libs/mrglib/src/log.h \
 ../../../include/osdep.h gopt.h ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/mrglib/src/stdindex.h \
 ready.h
optndt.o: optndt.c ../../../libs/mrglib/src/log.h gopt.h \
 ../../../libs/mrglib/src/gdbapi.h ../../../libs/mrglib/src/base.h \
 ../../../libs/mrglib/src/mrgdefs.h ../../../libs/gkdb/src/gardefs.h \
 ../../../include/osdep.h ../../../libs/mrglib/src/stdindex.h
opttree.o: opttree.c ../../../libs/mrglib/src/log.h \
 ../../../include/osdep.h gopt.h ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../libs/mrglib/src/stdindex.h
main.o: main.c gopt.h ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../include/garver.h
ready.o: ready.cpp ../../../libs/mrglib/src/gdbapi.h \
 ../../../libs/mrglib/src/base.h ../../../libs/mrglib/src/mrgdefs.h \
 ../../../libs/gkdb/src/gardefs.h ../../../include/osdep.h \
 ../../../libs/mrglib/src/stdindex.h ../../../libs/gkdb/src/basemask.h
