//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MDAGenerator.rc
//
#define IDOK2                           3
#define IDD_UNUSED_USER_CODE            9
#define IDS_PROJNAME                    100
#define IDR_GENERATION                  102
#define IDD_HDLG_DIALOG                 103
#define IDD_CHOICE_TYPE                 103
#define IDS_PROPSHT_CAPTION             104
#define IDD_PROPPAGE_UP                 105
#define IDD_IPP_USER_PROP               105
#define IDD_PROPPAGE_EXCEPTION          106
#define IDD_IPP_EXCEPTION               106
#define IDD_PROPPAGE_USES               107
#define IDD_IPP_USES                    107
#define IDR_HTML_GENTREE                108
#define IDR_HTML_M_SHOW_ALL             109
#define ID_MDAPROP_COMMAND              110
#define ID_MDAGEN_COMMAND               111
#define ID_MDAREP_COMMAND               112
#define ID_MDASRCH_COMMAND              113
#define ID_MDA_VIEW_LOCKED_COMMAND      114
#define ID_MDA_SHOW_HIDE_STEREOTYPES    115
#define ID_MDA_VIEW_ERRORS              116
#define IDD_GENERATE                    201
#define IDC_FILENAME                    201
#define IDC_EDIT1                       201
#define IDC_BROWSE                      202
#define IDC_SET_TITLE1                  202
#define IDC_EDIT2                       202
#define IDC_ROOTMODULE                  203
#define IDD_EX_DIALOG                   203
#define IDC_SET_TITLE2                  203
#define IDC_ROOTMODULENAME              204
#define IDD_DIALOG1                     204
#define IDC_EXC                         204
#define IDD_CONTENTS                    204
#define IDC_NAME                        205
#define IDD_EXCEPTIONS                  205
#define IDC_OP_AND_ATTRS                205
#define IDC_IMPLTYPE                    206
#define IDD_DIALOG2                     206
#define IDC_BUTTON1                     206
#define IDC_MODEL_ST                    206
#define IDC_MODEL_ST_COMBO              206
#define IDD_GENERATOR_SELECT            206
#define IDC_LIST1                       207
#define IDC_GEN_ST                      207
#define IDC_R2                          207
#define IDC_BUTTON2                     208
#define IDC_TEMPLATE                    208
#define IDC_EX_LIST                     209
#define IDC_CHECK1                      209
#define IDD_PROPPAGE_STD                209
#define IDC_UC_PRELOAD                  209
#define IDC_STD_PROP_ABSTRACT           209
#define IDC_R4                          209
#define IDC_BUTTON6                     209
#define IDC_CONTENT_BTN                 209
#define IDD_IPP_STD                     209
#define IDC_ADD                         210
#define IDD_UNUSED_UC                   210
#define IDC_REMOVE_TPL                  210
#define IDC_R5                          210
#define IDC_BUT_EDIT                    210
#define IDC_REMOVE                      211
#define IDC_NAME_1                      211
#define IDC_BUT_BROWSE_CLOSE            211
#define IDC_SEL_LIST                    212
#define IDC_VALUE_1                     212
#define IDD_STATISTICS                  212
#define IDC_BUT_BROWSE_CLOSE2           212
#define IDD_GEN_STATISTICS              212
#define IDC_ALL_SET_EX                  213
#define IDD_PROPPAGE_DERIVEDIMPL        213
#define IDC_R6                          213
#define IDC_BUT_BROWSE_CLOSE3           213
#define IDD_IPP_DERIVED_IMPL            213
#define IDC_SET_EX                      214
#define IDD_PROPPAGE_APPLGEN            214
#define IDD_IPP_APPL_GEN                214
#define IDC_ADD_SET                     215
#define IDC_R7                          215
#define IDD_ST_COLL                     215
#define IDD_ST_COLLECTION               215
#define IDC_REMOVE_SET                  216
#define IDC_R8                          216
#define IDC_ALL_GET_EX                  217
#define IDC_R9                          217
#define IDB_BITMAP1                     217
#define IDC_GET_EX                      218
#define IDC_R10                         218
#define IDD_TEMPL_ARG                   218
#define IDD_TEMPL_ARGS                  218
#define IDC_ADD_GET                     219
#define IDC_R11                         219
#define IDD_START_DLG                   219
#define IDD_MDA_START                   219
#define IDC_REMOVE_GET                  220
#define IDD_MDA_PROJ_PROP               220
#define IDD_START_PROPERTIES            220
#define IDD_CONTENTS_DLG                221
#define IDC_ON_SELECT_TEMPLATE          222
#define IDD_PROPPAGE_SYSTEM             222
#define IDD_IPP_SYSTEM                  222
#define IDC_ON_SELECT_PACKAGE           223
#define IDD_PROPPAGE_NATIVE             223
#define IDD_IPP_NATIVE                  223
#define IDC_PACKAGE_NAME                224
#define IDD_REPORT_VIEW                 224
#define IDC_NAME_2                      225
#define IDC_TEMPLATE_NAME               225
#define IDD_ADV_SEARCH                  225
#define IDD_ADVANCED_SEARCH             225
#define IDC_VALUE_2                     226
#define IDC_DOC                         226
#define IDI_ICON1                       226
#define IDC_NAME_3                      227
#define IDC_STD_SPEC                    227
#define IDD_ABOUT                       227
#define IDD_MDA_ABOUT                   227
#define IDC_VALUE_3                     228
#define IDC_CHANGE_TEMPL                228
#define IDC_NAME_4                      229
#define IDC_REMOVE_TEMPL                229
#define IDC_VALUE_4                     230
#define IDD_MD_SUPPORT_SERVER_AUTHORIZATION 230
#define IDC_NAME_5                      231
#define IDC_FOR_ITEM_NAME               231
#define IDC_VALUE_5                     232
#define IDC_UC_LIST                     232
#define IDD_LOCKED_PACKAGE_LIST         232
#define IDC_NAME_6                      233
#define IDD_TO_C                        233
#define IDD_TO_CLEAR_LOCKED_PACKS       233
#define IDC_VALUE_6                     234
#define IDC_NAME_7                      235
#define IDC_UC_TEXT                     235
#define IDD_QUESTION_BOX                235
#define IDC_VALUE_7                     236
#define IDC_SAVE_ALL                    236
#define IDC_NAME_8                      237
#define IDC_SUPPRES_UC                  237
#define IDC_VALUE_8                     238
#define IDC_GET_TITLE1                  238
#define IDB_BITMAP_FOR_EXPLORER         238
#define IDC_NAME_9                      239
#define IDC_GET_TITLE2                  239
#define IDC_VALUE_9                     240
#define IDC_TOTAL                       240
#define IDC_NAME_10                     241
#define IDC_NEW                         241
#define IDC_VALUE_10                    242
#define IDC_CHG                         242
#define IDC_NAME_11                     243
#define IDC_EQU                         243
#define IDC_VALUE_11                    244
#define IDC_DETAILS                     244
#define IDC_SHOW_STAT                   245
#define IDC_DEL                         245
#define IDC_REWRITE_UC                  246
#define IDC_DIFF                        247
#define IDC_RESTORE                     248
#define IDR_DIAGRAM                     248
#define IDC_RESTORE_ALL                 249
#define IDR_TREE                        249
#define IDD_ENTER_STRING_DIALOG         249
#define IDC_DIS_AUTO_COUNTER            250
#define IDD_CREATE_REPORT               253
#define IDD_CHOICE_DIALOG               254
#define IDC_STD_PROP_LINK_TYPE          255
#define IDD_CHANGED_PACKAGE_INFO        255
#define IDC_DIS_POST_PROCESSING         256
#define IDD_CONTENT_VIEW                256
#define IDC_STD_NATIVE                  257
#define IDD_DELETE_QUESTION             257
#define IDD_DIALOG3                     258
#define IDD_MDA_GENERATOR_PROPERTIES    258
#define IDC_IMPL_ALL                    259
#define IDD_GENERATION_ERROR_DIALOG     259
#define IDC_IMPL_INCL                   260
#define IDC_IMPL_EXCL                   261
#define IDC_DERIVED_ABSTRACT            263
#define IDC_DERIVED_IMPL                264
#define IDC_OVER_ALL                    265
#define IDC_OVER_INCL                   266
#define IDC_OVER_EXCL                   267
#define IDC_IMPLEMENT                   268
#define IDC_OVERLOAD                    269
#define IDC_ADD_IMPL                    270
#define IDC_REMOVE_IMPL                 271
#define IDC_ADD_OVER                    272
#define IDC_REMOVE_OVER                 273
#define IDC_CHECK2                      275
#define IDC_TARGET_ST                   276
#define IDC_R1                          277
#define IDC_R3                          278
#define IDC_BUTTON3                     279
#define IDC_BUTTON4                     280
#define IDC_COMBO1                      281
#define IDC_CONTENT                     281
#define IDC_COMBO2                      283
#define IDC_COMBO3                      284
#define IDC_COMBO4                      285
#define IDC_COMBO5                      286
#define IDC_COMBO6                      287
#define IDC_COMBO7                      288
#define IDC_COMBO8                      289
#define IDC_COMBO9                      290
#define IDC_COMBO10                     291
#define IDC_COMBO11                     292
#define IDC_CHECK_1                     293
#define IDC_CHECK_2                     294
#define IDC_TREE1                       294
#define IDC_CHECK_3                     295
#define IDC_CHECK_4                     296
#define IDC_CHECK_5                     297
#define IDC_CHECK_6                     298
#define IDC_LIST2                       298
#define IDC_MDA                         298
#define IDC_CHILDS_LIST                 298
#define IDC_CHECK_7                     299
#define IDC_BUTTON5                     299
#define IDC_CHECK_8                     300
#define IDC_RML                         300
#define IDC_CHECK_9                     301
#define IDC_EDIT3                       301
#define IDC_CHECK_10                    302
#define IDC_CHECK3                      302
#define IDC_CHECK_11                    303
#define IDC_GLOBAL_RB                   303
#define IDC_EDIT4                       303
#define IDC_PROJECT_RB                  304
#define IDC_EDIT5                       304
#define IDC_CHECK4                      305
#define IDC_RB_PUBLIC                   306
#define IDC_EDIT6                       306
#define IDC_RB_PROTECTED                307
#define IDC_RB_PRIVATE                  308
#define IDC_RB_IMPL                     309
#define IDC_RB_ABSTRACT                 310
#define IDC_RB_REGULAR                  311
#define IDC_RB_FINAL                    312
#define IDC_RB_OPTIONAL                 313
#define IDC_CONTENTS_CHK                314
#define IDC_TEMPL                       315
#define IDC_ROOT_DIR                    316
#define IDC_TEMPL2                      316
#define IDC_TEMPL_SELECT                317
#define IDC_ROOT_DIR_SELECT             318
#define IDC_ROOT_DIRSELECT              318
#define IDC_ALL_RB                      319
#define IDC_TEMPL3                      319
#define IDC_CLASS_RB                    320
#define IDC_TEMPL4                      320
#define IDC_OP_RB                       321
#define IDC_ATTR_RB                     322
#define IDC_CAT_RB                      323
#define IDC_STATIC1                     324
#define IDC_TEMPL5                      325
#define IDC_TEMPL6                      326
#define IDC_TEMPL7                      327
#define IDC_TEMPL8                      328
#define IDC_TEMPL9                      329
#define IDC_TEMPL10                     330
#define IDC_TEMPL11                     331
#define IDC_TEMPL12                     332
#define IDC_STATIC2                     333
#define IDC_STATIC3                     334
#define IDC_STATIC4                     335
#define IDC_STATIC5                     336
#define IDC_STATIC6                     337
#define IDC_STATIC7                     338
#define IDC_STATIC8                     339
#define IDC_STATIC9                     340
#define IDC_STATIC10                    341
#define IDC_STATIC11                    342
#define IDC_STATIC12                    343
#define IDC_STATIC_NAME                 344
#define IDC_STATIC_NAME2                345
#define IDC_RESULT                      345
#define IDC_OP                          346
#define IDC_ATTR                        347
#define IDC_TEXT_FIELD                  366
#define IDC_ADVANCED_SEARCH             367
#define IDC_DEP                         370
#define IDC_CHECK8                      371
#define IDC_CHECK9                      372
#define IDC_CHECK10                     373
#define IDC_CHECK11                     374
#define IDC_CAT                         375
#define IDC_CLASS                       376
#define IDC_CHECK12                     377
#define IDC_CHECK13                     378
#define IDC_CHECK14                     379
#define IDC_CHECK15                     380
#define IDC_CHECK16                     381
#define IDC_CHECK17                     382
#define IDC_CHECK18                     383
#define IDC_CHECK19                     384
#define IDC_CHECK20                     385
#define IDC_CHECK21                     386
#define IDC_CLEAR                       387
#define IDC_BUT_BROWSE                  388
#define IDC_VERSION                     391
#define IDC_BUILD                       392
#define IDC_TARGET                      393
#define IDC_ANIMATE1                    394
#define IDC_TARGET2                     394
#define IDC_SERVER                      394
#define IDC_EDIT_LOGIN                  395
#define IDC_EDIT_PASS                   396
#define IDC_LIST_OF_LOCKED              397
#define IDC_SELECT_IN_BROWSER           398
#define IDC_BUTTON_DESELECT             399
#define IDC_BUTTON_DESELECT_CURRENT     399
#define IDC_BUTTON_DESELECT_CURRENT2    400
#define IDC_BUTTON_DESELECT_OTHER       400
#define IDC_SAVE                        402
#define IDC_REMEMBER_ME                 403
#define IDC_EDIT_STRING                 404
#define IDC_APPLY                       405
#define IDC_MINOR_CHANGES               406
#define IDC_TEXT_SRCH_GRP               407
#define IDC_ATTR_SRCH_GRP               408
#define IDC_ST_SRCH_GRP                 409
#define IDC_META_SRCH_GRP               410
#define IDC_UP_SRCH_GRP                 411
#define IDC_EDIT_REPORT_NAME            412
#define IDC_EDIT_REPORT_NAME2           413
#define IDC_EDIT_REPORT_QUERY           413
#define IDC_SELECTION_LIST              413
#define IDC_LOCKED_INFO_LIST            414
#define IDC_STATIC_UNLOCKED             415
#define IDC_STATIC_LOCKED               416
#define IDC_UNLOCKED_INFO_LIST          417
#define IDC_IS_INCOMPLETE               417
#define IDC_LOCK_ALLWAYS                418
#define IDC_ASK                         419
#define IDC_NO_LOCK                     420
#define IDC_STRATEGY_GROUP              421
#define IDC_OTHER_MODEL_TREE            422
#define IDC_CURRENT_MODEL_TREE          423
#define IDC_MESSAGE                     423
#define IDC_ADDITIONAL_LIST             424
#define IDC_ADDITIONAL_MESS             425
#define IDC_                            427
#define IDC_ABSTRACT_LABEL              427
#define IDC_OVERLOAD_LABEL              428
#define IDC_GUID                        429
#define IDC_GUID_STATIC                 430
#define IDC_VISIBILITY_LEVEL_SPIN       431
#define IDC_VISIBILITY_LEVEL_EDIT       432
#define IDC_VISIBILITY_LEVEL_STATIC     433
#define IDC_ST_LABEL                    434
#define IDC_DESC_LABEL                  435
#define IDC_SEARCH_IN_GUID              436
#define IDC_USE_GEN_TREE                437
#define IDC_SEARCH_IN_GUID2             437
#define IDC_RUN_SPELL                   437
#define IDC_GLOBAL_LOCALLY              438
#define IDC_ERRORS_LIST                 439
#define ID_OPEN_EXTRERNAL_APP_DIAG      3198
#define ID_OPEN_EXTRERNAL_APP_TREE      3199
#define ID_CATEGORY_UNITS               3200
#define ID_CONTROL_DIAG                 3201
#define ID_CONTROL_ALL_DIAG             3202
#define ID_CONTROL_FILE_DIAG            3203
#define ID_UNCONTROL_ALL_DIAG           3204
#define ID_CONTROL_ALL_TREE             3205
#define ID_CONTROL_FILE_TREE            3206
#define ID_UNCONTROL_ALL_TREE           3207
#define ID_UNCONTROL_DIAG               3208
#define ID_UNCONTROL_TREE               3209
#define ID_CLASS_CREATESTATEDIAGRAM     3210
#define ID_NEW_STATEDIAGRAM_DIAG        3211
#define ID_NEW_STATEDIAGRAM_TREE        3212
#define ID_OPEN_DIAGRAM_DIAG            3213
#define ID_GENERATE_NO_REP_TREE         3214
#define ID_GENERATE_NO_REP_DIAG         3215
#define ID_LOCKALL_DIAG                 3216
#define ID_LOCK_ALL_DIAG                3217
#define ID_UNLOCK_ALL_DIAG              3218
#define ID_Menu                         3219
#define ID_CATEGORY_S                   3220
#define ID_LOCK_ALL_TREE                3221
#define ID_UNLOCK_ALL_TREE              3222
#define ID_CLASSDIAGRAM_ASD             3223
#define ID_GENERATION_WITH_CONSUMERS_DIAG 3224
#define ID_GENERATION_WITH_CONSUMERS_TREE 3225
#define ID_GENERATION_WITH_CONSUMERS_NOREP_DIAG 3226
#define ID_GENERATION_WITH_CONSUMERS_NOREP_TREE 3227
#define ID_TREE_EDIT                    32772
#define ID_EDIT_COPY32773               32773
#define ID_EDIT_CUT32774                32774
#define ID_EDIT_PAST                    32775
#define ID_TREE_NEW                     32776
#define ID_NEW_NEWELEMENT               32777
#define ID_NEW_NEWDIAGRAM               32778
#define ID_NEW_DELETE                   32784
#define ID_TREE_NEW_DELETE              32785
#define ID_EDIT_DELETE                  32786
#define ID_TREE_VIEW                    32788
#define ID_VIEW_EXPANDALL               32789
#define ID_VIEW_EXPAND                  32790
#define ID_VIEW_COLLAPSEALL             32791
#define ID_VIEW_COLLAPSE                32792
#define ID_MODEL_SEARCH                 32797
#define ID_RELOAD_TREE                  32798
#define ID_COPY_ELEMENTS_DIAG           32816
#define ID_RELOCATE_DIAG                32817
#define ID_ROLLBACK_DIAG                32818
#define ID_PROPERTIES_DIAG              32819
#define ID_LOCK_DIAG                    32820
#define ID_GENERATE_DIAG                32821
#define ID_REPORT_DIAG                  32822
#define ID_SEARCH_DIAG                  32823
#define ID_DELETE_DIAG                  32824
#define ID_NEW_CLASS_DIAG               32825
#define ID_NEW_ATTR_DIAG                32826
#define ID_SHOW_IN_BROWSER              32827
#define ID_NEW_OPERATION_DIAG           32828
#define ID_NEW_SEQUENCEDIAG_DIAG        32829
#define ID_NEW_ATTRKEY_DIAG             32830
#define ID_BROWSE_IN_DIAG_DIAG          32831
#define ID_NEW_CATEGORY_DIAG            32832
#define ID_NEW_ELEMENT_DIAG             32833
#define ID_NEW_CLASSDIAG_DIAG           32834
#define ID_COLORIZE_DIAG                32835
#define ID_PROPERTIES_TREE              32836
#define ID_LOCK_TREE                    32837
#define ID_GENERATE_TREE                32838
#define ID_REPORT_TREE                  32839
#define ID_SEARCH_TREE                  32840
#define ID_DELETE_TREE                  32841
#define ID_NEW_ELEMENT_TREE             32842
#define ID_NEW_CATEGORY_TREE            32843
#define ID_NEW_CLASS_TREE               32844
#define ID_NEW_CLASSDIAG_TREE           32845
#define ID_CATEGORY_VIEW                32846
#define ID_EXPAND_COLLAPSE_TREE         32848
#define ID_EXPAND_COLLAPSE_ALL_TREE     32849
#define ID_NEW_ATTRIBUTE_TREE           32850
#define ID_NEW_OPERATION_TREE           32851
#define ID_NEW_SEQUENCEDIAG_TREE        32852
#define ID_NEW_ATTRKEY_TREE             32853
#define ID_CLASSDIAGRAM                 32854
#define ID_BROWSE_IN_DIAG_TREE          32855
#define ID_CATEGORY_ROLLBACK            32856
#define ID_ROLLBACK_TREE                32857
#define ID_COLORIZE_TREE                32858
#define ID_VIEW_ELEM_IN_CONFLUENCE_TREE 32860
#define ID_VIEW_ELEM_IN_CONFLUENCE_DIAG 32861

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        260
#define _APS_NEXT_COMMAND_VALUE         3228
#define _APS_NEXT_CONTROL_VALUE         440
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
