# DO NOT DELETE

btree_.o: gdbapi.h base.h mrgdefs.h stdindex.h iapi.h platform.h
cmpfunc.o: base.h mrgdefs.h
flog.o: gdbapi.h base.h mrgdefs.h stdindex.h
gbase.o: gdbapi.h base.h mrgdefs.h stdindex.h iapi.h platform.h
gberr.o: gdbapi.h base.h mrgdefs.h stdindex.h log.h platform.h
globals.o: base.h mrgdefs.h iapi.h stdindex.h
index_.o: gdbapi.h base.h mrgdefs.h stdindex.h iapi.h platform.h
iter.o: gdbapi.h base.h mrgdefs.h stdindex.h
keyfile.o: base.h mrgdefs.h platform.h gdbapi.h stdindex.h
pgfile.o: gdbapi.h base.h mrgdefs.h stdindex.h iapi.h platform.h
sets.o: gdbapi.h base.h mrgdefs.h stdindex.h sets.h
ssets.o: gdbapi.h base.h mrgdefs.h stdindex.h sets.h
streams_.o: gdbapi.h base.h mrgdefs.h stdindex.h platform.h log.h
strcache.o: gdbapi.h base.h mrgdefs.h stdindex.h
mlhooks.o: gdbapi.h base.h mrgdefs.h stdindex.h
flog.o: gdbapi.h base.h mrgdefs.h stdindex.h
unifname.o: gdbapi.h base.h mrgdefs.h stdindex.h
profile.o: gdbapi.h base.h mrgdefs.h stdindex.h profile.h
