// MnsSaveDialogExecutor 1F9B40407B77 PureMixIn Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_1F9B40407B77_diagrams

 MEDIAGRAM ME_1F9B40407B77_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_1F9B40407B77' '4DDA34AA023B.ms.model.script' ; // MnsSaveDialogExecutor

  MEVIEW ME_52B375B038DC_view
   MELINK Original WL 'ME_52B375B038DC' '4DDA34AA023B.ms.model.script' ; // Call
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_52B375B038DC_view

  MEVIEW ME_D50DF667C759_view
   MELINK Original WL 'ME_D50DF667C759' '4DDA34AA023B.ms.model.script' ; // GetFileName
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_D50DF667C759_view

  MEVIEW ME_593F1F6D46A5_view
   MELINK Original WL 'ME_593F1F6D46A5' '4DDA34AA023B.ms.model.script' ; // SetFileFormat
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_593F1F6D46A5_view

  MEVIEW ME_4020F60E166B_view
   MELINK Original WL 'ME_4020F60E166B' '4DDA34AA023B.ms.model.script' ; // SetSaveObjects
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4020F60E166B_view

  MEVIEW ME_8E9943B92E87_view
   MELINK Original WL 'ME_8E9943B92E87' '4DDA34AA023B.ms.model.script' ; // SetMergeFiles
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_8E9943B92E87_view

  MEVIEW ME_242B3CA0CFEF_view
   MELINK Original WL 'ME_242B3CA0CFEF' '4DDA34AA023B.ms.model.script' ; // SetSelectedOnly
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_242B3CA0CFEF_view

  MELIST Views
   Seq: ( ME_52B375B038DC_view // Call
   ME_D50DF667C759_view // GetFileName
   ME_593F1F6D46A5_view // SetFileFormat
   ME_4020F60E166B_view // SetSaveObjects
   ME_8E9943B92E87_view // SetMergeFiles
   ME_242B3CA0CFEF_view // SetSelectedOnly
   )
  ; // Views
 ENDMEDIAGRAM // ME_1F9B40407B77_main

 MELIST Diagrams
  Seq: ( ME_1F9B40407B77_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_1F9B40407B77_diagrams
