// NewsLine_i 45EEA851039F Impl Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_45EEA851039F_diagrams

 MEDIAGRAM ME_45EEA851039F_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_45EEA851039F' ; // NewsLine_i

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_45EEA851039F_main

 MELIST Diagrams
  Seq: ( ME_45EEA851039F_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_45EEA851039F_diagrams
