// ExternalOperation 45EEA4890342 Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_45EEA4890342_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_45EEA4890342' '45EEA4890342.ms.model.script' ; // ExternalOperation

 MEVIEW ME_45EEAEA10295_view
  MELINK Original WL 'ME_45EEAEA10295' '45EEA4890342.ms.model.script' ; // ExternalOperation
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_45EEAEA10295_view

 MEVIEW ME_45EEAEC40311_view
  MELINK Original WL 'ME_45EEAEC40311' '45EEA4890342.ms.model.script' ; // ExternalOperationId
  MEPROP X 120
  MEPROP Y 10
 ENDMEVIEW // ME_45EEAEC40311_view

ENDMEDIAGRAM // ME_45EEA4890342_main
