// FlagMaskStubPostProcess 46013DB90157 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_46013DB90157_diagrams

 MEDIAGRAM ME_46013DB90157_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_46013DB90157' '45EEA4490239.ms.model.script' ; // FlagMaskStubPostProcess

  MEVIEW ME_46013DEC02CE_view
   MELINK Original WL 'ME_46013DEC02CE' '45EEA4490239.ms.model.script' ; // make
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_46013DEC02CE_view

  MELIST Views
   Seq: ( ME_46013DEC02CE_view // make
   )
  ; // Views
 ENDMEDIAGRAM // ME_46013DB90157_main

 MELIST Diagrams
  Seq: ( ME_46013DB90157_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_46013DB90157_diagrams
