// DocumentHelper 4628939B0216 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4628939B0216

FORWARD ME_462895DD0240

FORWARD ME_462896090184

ME ME_462896540184
 MEPROP Name 'redaction_info_list'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EED8DE0121' '4570511E038A.ms.model.script' // RedactionInfoList
 ;

ENDME // ME_462896540184 redaction_info_list

ME ME_4628965401C2
 MEPROP Name 'to_find'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EED84C01FD' '4570511E038A.ms.model.script' // RedactionID
 ;

ENDME // ME_4628965401C2 to_find

ME ME_462896090184
 MEPROP UID '462896090184'
 MEPROP Name 'find_redaction'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_462895DD0240 // RedactionInfoListHelper
 ;
 MELINK Target WL 'ME_450A61050251' '3DBFDB23006E.ms.model.script' // integer
 ;
 MELIST Parameters
   Seq: ( ME_462896540184 // redaction_info_list
 ME_4628965401C2 // to_find
 )
 ; // Parameters

ENDME // ME_462896090184 find_redaction

FORWARD ME_46289660023F

ME ME_4628969300E7
 MEPROP Name 'redaction_info_list'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EED8DE0121' '4570511E038A.ms.model.script' // RedactionInfoList
 ;

ENDME // ME_4628969300E7 redaction_info_list

ME ME_462896930135
 MEPROP Name 'to_find'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EED83A00C4' '4570511E038A.ms.model.script' // RedactionInfo
 ;

ENDME // ME_462896930135 to_find

ME ME_46289660023F
 MEPROP UID '46289660023F'
 MEPROP Name 'find_redaction'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_462895DD0240 // RedactionInfoListHelper
 ;
 MELINK Target WL 'ME_450A61050251' '3DBFDB23006E.ms.model.script' // integer
 ;
 MELIST Parameters
   Seq: ( ME_4628969300E7 // redaction_info_list
 ME_462896930135 // to_find
 )
 ; // Parameters

ENDME // ME_46289660023F find_redaction

FORWARD ME_4628969F03E4

ME ME_462896CB0377
 MEPROP Name 'redaction_info_list'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EED8DE0121' '4570511E038A.ms.model.script' // RedactionInfoList
 ;

ENDME // ME_462896CB0377 redaction_info_list

ME ME_4628969F03E4
 MEPROP UID '4628969F03E4'
 MEPROP Name 'find_actual_redaction'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_462895DD0240 // RedactionInfoListHelper
 ;
 MELINK Target WL 'ME_450A61050251' '3DBFDB23006E.ms.model.script' // integer
 ;
 MELIST Parameters
   Seq: ( ME_462896CB0377 // redaction_info_list
 )
 ; // Parameters

ENDME // ME_4628969F03E4 find_actual_redaction

FORWARD ME_4A8145520247

ME ME_4A8145B9001D
 MEPROP Name 'redaction_info_list'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EED8DE0121' '4570511E038A.ms.model.script' // RedactionInfoList
 ;

ENDME // ME_4A8145B9001D redaction_info_list

ME ME_4A8145B9003F
 MEPROP Name 'id'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EED84C01FD' '4570511E038A.ms.model.script' // RedactionID
 ;

ENDME // ME_4A8145B9003F id

ME ME_4A8145B90062
 MEPROP Name 'prev_list'
 MEPROP Class class_Parameter
 MELINK Stereotype st_inout ;
 MELINK Target WL 'ME_45EED8DE0121' '4570511E038A.ms.model.script' // RedactionInfoList
 ;

ENDME // ME_4A8145B90062 prev_list

ME ME_4A8145520247
 MEPROP UID '4A8145520247'
 MEPROP Name 'prev_redactions'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_462895DD0240 // RedactionInfoListHelper
 ;
 MELIST Parameters
   Seq: ( ME_4A8145B9001D // redaction_info_list
 ME_4A8145B9003F // id
 ME_4A8145B90062 // prev_list
 )
 ; // Parameters

ENDME // ME_4A8145520247 prev_redactions

FORWARD ME_4B556E69014E

ME ME_4B556E6F025C
 MEPROP Name 'redaction_info_list'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EED8DE0121' '4570511E038A.ms.model.script' // RedactionInfoList
 ;

ENDME // ME_4B556E6F025C redaction_info_list

ME ME_4B556E6F0285
 MEPROP Name 'id'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EED84C01FD' '4570511E038A.ms.model.script' // RedactionID
 ;

ENDME // ME_4B556E6F0285 id

ME ME_4B55733E030F
 MEPROP Name 'next_list'
 MEPROP Class class_Parameter
 MELINK Stereotype st_inout ;
 MELINK Target WL 'ME_45EED8DE0121' '4570511E038A.ms.model.script' // RedactionInfoList
 ;

ENDME // ME_4B55733E030F next_list

ME ME_4B556E69014E
 MEPROP UID '4B556E69014E'
 MEPROP Name 'cur_and_next_redactions'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_462895DD0240 // RedactionInfoListHelper
 ;
 MELIST Parameters
   Seq: ( ME_4B556E6F025C // redaction_info_list
 ME_4B556E6F0285 // id
 ME_4B55733E030F // next_list
 )
 ; // Parameters

ENDME // ME_4B556E69014E cur_and_next_redactions

ME ME_462895DD0240
 MEPROP UID '462895DD0240'
 MEPROP Name 'RedactionInfoListHelper'
 MEPROP Class class_Class
 MELINK Stereotype st_UtilityPack ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4628939B0216 // DocumentHelper
 ;
 MELIST Operations
   Seq: ( HWL ME_462896090184 // find_redaction
 HWL ME_46289660023F // find_redaction
 HWL ME_4628969F03E4 // find_actual_redaction
 HWL ME_4A8145520247 // prev_redactions
 HWL ME_4B556E69014E // cur_and_next_redactions
 )
 ; // Operations
 UP "is namespace" True
 UP cpp:Path 'garant6x\implementation\Garant\GblAdapterLib\DocumentHelper\RedactionInfoListHelper.cpp'
 UP h:Path 'garant6x\implementation\Garant\GblAdapterLib\DocumentHelper\RedactionInfoListHelper.h'
 UP intf.pas:Path 'garant6x\implementation\Garant\tie\Garant\GblAdapterLib\RedactionInfoListHelper.pas'

ENDME // ME_462895DD0240 RedactionInfoListHelper

FORWARD ME_47ED11E002A7

FORWARD ME_47ED12200202

ME ME_47ED125A02CE
 MEPROP Name 'document'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;

ENDME // ME_47ED125A02CE document

ME ME_47ED12200202
 MEPROP UID '47ED12200202'
 MEPROP Name 'server_document_to_key'
 MEPROP Class class_Operation
 %SUMMARY 'По серверному документу' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47ED11E002A7 // DocumentFactoryKeyHelper
 ;
 MELINK Target WL 'ME_47ED1AC7036F' '4570511E038A.ms.model.script' // FactoryKey
 ;
 MELIST Parameters
   Seq: ( ME_47ED125A02CE // document
 )
 ; // Parameters

ENDME // ME_47ED12200202 server_document_to_key

FORWARD ME_47ED1269019D

ME ME_47ED128801B9
 MEPROP Name 'pid'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;

ENDME // ME_47ED128801B9 pid

ME ME_47ED1269019D
 MEPROP UID '47ED1269019D'
 MEPROP Name 'PID_to_key'
 MEPROP Class class_Operation
 %SUMMARY 'По PID''у' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_47ED11E002A7 // DocumentFactoryKeyHelper
 ;
 MELINK Target WL 'ME_47ED1AC7036F' '4570511E038A.ms.model.script' // FactoryKey
 ;
 MELIST Parameters
   Seq: ( ME_47ED128801B9 // pid
 )
 ; // Parameters

ENDME // ME_47ED1269019D PID_to_key

ME ME_47ED1D0E00EB
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47ED11E002A7 // DocumentFactoryKeyHelper
 ;
 MELINK Target WL 'ME_47ED1AC7036F' '4570511E038A.ms.model.script' // FactoryKey
 ;

ENDME // ME_47ED1D0E00EB 

ME ME_4859191D0249
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47ED11E002A7 // DocumentFactoryKeyHelper
 ;
 MELINK Target WL 'ME_460A6EF8024B' '460BAAA30119.ms.model.script' // ApplicationHelper
 ;

ENDME // ME_4859191D0249 

FORWARD ME_4FE870160102

ME ME_4FE874B803C9
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47ED11E002A7 // DocumentFactoryKeyHelper
 ;
 MELINK Target HWL ME_4FE870160102 // DocumentTypeToFactoryKey
 ;

ENDME // ME_4FE874B803C9 

ME ME_47ED11E002A7
 MEPROP UID '47ED11E002A7'
 MEPROP Name 'DocumentFactoryKeyHelper'
 MEPROP Class class_Class
 MELINK Stereotype st_UtilityPack ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Получение ключа мультифабрики по серверному документу или PID' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4628939B0216 // DocumentHelper
 ;
 MELIST Operations
   Seq: ( HWL ME_47ED12200202 // server_document_to_key
 HWL ME_47ED1269019D // PID_to_key
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_47ED1D0E00EB // FactoryKey
 ME_4859191D0249 // ApplicationHelper
 ME_4FE874B803C9 // DocumentTypeToFactoryKey
 )
 ; // Dependencies
 UP "is namespace" True
 UP cpp:Path 'garant6x\implementation\Garant\GblAdapterLib\DocumentHelper\DocumentFactoryKeyHelper.cpp'
 UP h:Path 'garant6x\implementation\Garant\GblAdapterLib\DocumentHelper\DocumentFactoryKeyHelper.h'
 UP intf.pas:Path 'garant6x\implementation\Garant\tie\Garant\GblAdapterLib\DocumentFactoryKeyHelper.pas'

ENDME // ME_47ED11E002A7 DocumentFactoryKeyHelper

ME ME_4FE870160102
 MEPROP UID '4FE870160102'
 MEPROP Name 'DocumentTypeToFactoryKey'
 MEPROP Class class_Class
 MELINK Stereotype st_TypeConvertor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_4628939B0216 // DocumentHelper
 ;
 UP "is sorted" False
 UP h:Path 'garant6x\implementation\Garant\GblAdapterLib\DocumentHelper\DocumentTypeToFactoryKey.h'

ENDME // ME_4FE870160102 DocumentTypeToFactoryKey

ME ME_4628939B0216
 MEPROP UID '4628939B0216'
 MEPROP Name 'DocumentHelper'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_456EA3D2031C' '456EA3D2031C.ms.model.script' // GblAdapterLib
 ;
 MELIST Children
   Seq: ( HWL ME_462895DD0240 // RedactionInfoListHelper
 HWL ME_47ED11E002A7 // DocumentFactoryKeyHelper
 HWL ME_4FE870160102 // DocumentTypeToFactoryKey
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_4570511E038A' '4570511E038A.ms.model.script' // Document
 WL 'ME_460BAAA30119' '460BAAA30119.ms.model.script' // ApplicationHelper
 )
 ; // Depends
 UP cpp:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\DocumentHelper'
 UP h:PathOnly '\garant6x\implementation\Garant\GblAdapterLib\DocumentHelper'

ENDME // ME_4628939B0216 DocumentHelper
