// TnsTextParaNode 467FCDBF0372 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_467FCDA10044_ME_467FCDBF0372_G
 MELINK Original WL? 'ME_467FCDA10044' // TnsLeafParaNode
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_467FCDA10044_ME_467FCDBF0372_G TnsLeafParaNode

%%InheritedBy ME_467FCDA10044 ME_467FCDBF0372

ME ME_467FCDBF0372
 MEPROP UID '467FCDBF0372'
 MEPROP Name 'TnsTextParaNode'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Текстовый параграф.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_467FC9F80281' // DocumentTagNodes
 ;
 MELIST Inherits
   Seq: ( HWL ME_467FCDA10044_ME_467FCDBF0372_G // TnsLeafParaNode
 )
 ; // Inherits
 UP "author" 'Люлин А.В.'
 UP "no hands" True
 UP "started" '2005/06/23 16:38:20'
 UP extprop:pas:UnitName 'nsTextParaNode'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'TextParaNode'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\f1DocumentTagsImplementation\nsTextParaNode.pas'

ENDME // ME_467FCDBF0372 TnsTextParaNode
