// Il3Lines 46A60664008D Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_46A60664008D_diagrams

 MEDIAGRAM ME_46A60664008D_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_46A60664008D' '4677FBA70343.ms.model.script' ; // Il3Lines

  MEVIEW ME_46A60683020E_view
   MELINK Original WL 'ME_46A60683020E' '4677FBA70343.ms.model.script' ; // AsObject
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_46A60683020E_view

  MELIST Views
   Seq: ( ME_46A60683020E_view // AsObject
   )
  ; // Views
 ENDMEDIAGRAM // ME_46A60664008D_main

 MELIST Diagrams
  Seq: ( ME_46A60664008D_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_46A60664008D_diagrams
