// RequirementsLib 47287F7D02CE MDALibrary Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_47287F7D02CE_diagrams

 MEDIAGRAM ME_47287F7D02CE_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_47287F7D02CE' '47287F7D02CE.ms.model.script' ; // RequirementsLib

  MEVIEW ME_470335E60290_view
   MELINK Original WL 'ME_470335E60290' '470335E60290.ms.model.script' ; // Requirements
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_470335E60290_view

  MELIST Views
   Seq: ( ME_470335E60290_view // Requirements
   )
  ; // Views
 ENDMEDIAGRAM // ME_47287F7D02CE_main

 MELIST Diagrams
  Seq: ( ME_47287F7D02CE_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_47287F7D02CE_diagrams
