// IafwSettingsSource 473DA12B02A0 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_473DA12B02A0_diagrams

 MEDIAGRAM ME_473DA12B02A0_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_473DA12B02A0' '467823B7002C.ms.model.script' ; // IafwSettingsSource

  MEVIEW ME_473DA149020D_view
   MELINK Original WL 'ME_473DA149020D' '467823B7002C.ms.model.script' ; // Settings
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_473DA149020D_view

  MEVIEW ME_473DA15800E2_view
   MELINK Original WL 'ME_473DA15800E2' '467823B7002C.ms.model.script' ; // BaseId
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_473DA15800E2_view

  MELIST Views
   Seq: ( ME_473DA149020D_view // Settings
   ME_473DA15800E2_view // BaseId
   )
  ; // Views
 ENDMEDIAGRAM // ME_473DA12B02A0_main

 MELIST Diagrams
  Seq: ( ME_473DA12B02A0_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_473DA12B02A0_diagrams
