// Tl3ClassCacheEntry 47A9A53001F6 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_47A9A53001F6_diagrams

 MEDIAGRAM ME_47A9A53001F6_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_47A9A53001F6' '47913B47006E.ms.model.script' ; // Tl3ClassCacheEntry

  MEVIEW ME_4BE3D27401ED_view
   MELINK Original WL 'ME_4BE3D27401ED' '47913B47006E.ms.model.script' ; // l3Items_NoSort
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4BE3D27401ED_view

  MEVIEW ME_47B5A114039E_view
   MELINK Original WL 'ME_47B5A114039E' '47913B47006E.ms.model.script' ; // Create
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_47B5A114039E_view

  MEVIEW ME_47B5A13B0025_view
   MELINK Original WL 'ME_47B5A13B0025' '47913B47006E.ms.model.script' ; // Add
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_47B5A13B0025_view

  MEVIEW ME_47B5A15003B3_view
   MELINK Original WL 'ME_47B5A15003B3' '47913B47006E.ms.model.script' ; // DeleteTailWithoutFree
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_47B5A15003B3_view

  MELIST Views
   Seq: ( ME_4BE3D27401ED_view // l3Items_NoSort
   ME_47B5A114039E_view // Create
   ME_47B5A13B0025_view // Add
   ME_47B5A15003B3_view // DeleteTailWithoutFree
   )
  ; // Views
 ENDMEDIAGRAM // ME_47A9A53001F6_main

 MELIST Diagrams
  Seq: ( ME_47A9A53001F6_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_47A9A53001F6_diagrams
