// Tips 47B30C7D02F3 Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_47B30C7D02F3_diagrams

 MEDIAGRAM ME_47B30C7D02F3_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_47B30C7D02F3' ; // Tips

  MEVIEW ME_47B30CD40027_view
   MELINK Original WL 'ME_47B30CD40027' '47B30C7D02F3.ms.model.script' ; // TipsManager
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_47B30CD40027_view

  MELIST Views
   Seq: ( ME_47B30CD40027_view // TipsManager
   )
  ; // Views
 ENDMEDIAGRAM // ME_47B30C7D02F3_main

 MELIST Diagrams
  Seq: ( ME_47B30C7D02F3_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_47B30C7D02F3_diagrams
