// Tk2OperationContainerRefList 47E3D0820267 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_47E3D0820267

ME ME_47E3D0CA029B
 MEPROP UID '47E3D0CA029B'
 MEPROP Name 'ItemType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_47E3D0820267 // Tk2OperationContainerRefList
 ;
 MELINK Target WL? 'ME_47E3C78502FB' // Tk2OperationContainer
 ;

ENDME // ME_47E3D0CA029B ItemType

MEREF ME_47B2C42A0163_ME_47E3D0820267_impl
 MELINK Original WL 'ME_47B2C42A0163' '47A74A5F0123.ms.model.script' // AssignItem
 ;
 MEPROP OpKind opkind_Implemented
 UP "ifdef" 'l3Items_NeedsAssignItem'
 UP "ifndef" 'l3Items_NoSort'
ENDMEREF // ME_47B2C42A0163_ME_47E3D0820267_impl AssignItem

MEREF ME_47B99D4503A2_ME_47E3D0820267_impl
 MELINK Original WL 'ME_47B99D4503A2' '47B45152003F.ms.model.script' // CompareExistingItems
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_47B99D4503A2_ME_47E3D0820267_impl CompareExistingItems

MEREF ME_47B99E920196_ME_47E3D0820267_G
 MELINK Original WL? 'ME_47B99E920196' // l3UncomparabeObjectRefList
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_47B99E920196_ME_47E3D0820267_G l3UncomparabeObjectRefList

MEREF ME_47BC3A07027F_ME_47E3D0820267_G
 MELINK Original WL? 'ME_47BC3A07027F' // Tl3SimpleDataContainer
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_47BC3A07027F_ME_47E3D0820267_G Tl3SimpleDataContainer

%%InheritedBy ME_47B99E920196 ME_47E3D0820267
%%InheritedBy ME_47BC3A07027F ME_47E3D0820267

ME ME_47E3D0820267
 MEPROP UID '47E3D0820267'
 MEPROP Name 'Tk2OperationContainerRefList'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_47E3C64F037E' // Operations
 ;
 MELIST Inherits
   Seq: ( HWL ME_47B99E920196_ME_47E3D0820267_G // l3UncomparabeObjectRefList
 HWL ME_47BC3A07027F_ME_47E3D0820267_G // Tl3SimpleDataContainer
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_47E3D0CA029B // ItemType
 )
 ; // Attributes
 MELIST Implemented
   Seq: ( ME_47B2C42A0163_ME_47E3D0820267_impl // AssignItem
 ME_47B99D4503A2_ME_47E3D0820267_impl // CompareExistingItems
 )
 ; // Implemented
 UP "author" 'Ëþëèí À.Â.'
 UP "no hands" True
 UP "started" '21.03.2008 18:13'
 UP extprop:pas:UnitName 'k2OperationContainerRefList'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'OperationContainerRefList'
 UP intf.pas:Path 'common\components\rtl\Garant\K2\k2OperationContainerRefList.pas'

ENDME // ME_47E3D0820267 Tk2OperationContainerRefList
