// TdDrugList 47EB3E410033 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_47EB3E410033_diagrams

 MEDIAGRAM ME_47EB3E410033_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_47EB3E410033' '4A9FCCDB035B.ms.model.script' ; // TdDrugList

  MEVIEW ME_494176F40163_view
   MELINK Original WL 'ME_494176F40163' '4A9FCCDB035B.ms.model.script' ; // Make
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_494176F40163_view

  MELIST Views
   Seq: ( ME_494176F40163_view // Make
   )
  ; // Views
 ENDMEDIAGRAM // ME_47EB3E410033_main

 MELIST Diagrams
  Seq: ( ME_47EB3E410033_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_47EB3E410033_diagrams
