// TnevTextSourcePool 47F1FBC30128 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_47F1FBC30128
 MEPROP UID '47F1FBC30128'
 MEPROP Name 'TnevTextSourcePool'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_47F086170200' // DocumentContainers
 ;
 UP "author" 'Ëþëèí À.Â.'
 UP "finished" False
 UP "started" '14.07.2005 15:26'
 UP extprop:pas:UnitName 'nevTextSourcePool'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'TextSourcePool'
 UP intf.pas:Path 'common\components\gui\Garant\Everest\new\NOT_FINISHED_nevTextSourcePool.pas'

ENDME // ME_47F1FBC30128 TnevTextSourcePool
