// TnsHAFPainter 47F2317F015E SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_47F2317F015E

ME ME_5243FD120266
 MEPROP UID '5243FD120266'
 MEPROP Name 'Settings'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_47F2317F015E // TnsHAFPainter
 ;
 MELINK Target WL 'ME_476963BB00EF' '467BAB7F021E.ms.model.script' // IvcmSettings
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_5243FD120266 Settings

ME ME_52440E91014A
 MEPROP UID '52440E91014A'
 MEPROP Name 'f_BaseId'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_47F2317F015E // TnsHAFPainter
 ;
 MELINK Target WL 'ME_476136D3010B' '4807744200AA.ms.model.script' // String
 ;

ENDME // ME_52440E91014A f_BaseId

ME ME_5244002901F5
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47F2317F015E // TnsHAFPainter
 ;
 MELINK Target WL? 'ME_47877EB202FB' // SysUtils
 ;

ENDME // ME_5244002901F5 

ME ME_5244002C00D6
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47F2317F015E // TnsHAFPainter
 ;
 MELINK Target WL? 'ME_47752AF90375' // afwFacade
 ;

ENDME // ME_5244002C00D6 

ME ME_5244002E0025
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47F2317F015E // TnsHAFPainter
 ;
 MELINK Target WL 'ME_5110DBDD0004' '47C695A10172.ms.model.script' // TevStyleId
 ;

ENDME // ME_5244002E0025 

ME ME_5244002F0306
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47F2317F015E // TnsHAFPainter
 ;
 MELINK Target WL? 'ME_47FB50E4008E' // nsConst
 ;

ENDME // ME_5244002F0306 

ME ME_52440031026C
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47F2317F015E // TnsHAFPainter
 ;
 MELINK Target WL? 'ME_4AD6FDC802F3' // TnsSettings
 ;

ENDME // ME_52440031026C 

ME ME_53EDCCD40372
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47F2317F015E // TnsHAFPainter
 ;
 MELINK Target WL? 'ME_47F25BC801DB' // vcmBase
 ;

ENDME // ME_53EDCCD40372 

ME ME_540E9F2E0107
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_47F2317F015E // TnsHAFPainter
 ;
 MELINK Target WL? 'ME_540E9DE4024C' // TnsHAFPainterPrim
 ;

ENDME // ME_540E9F2E0107 

MEREF ME_473DA149020D_ME_47F2317F015E_impl
 MELINK Original WL 'ME_473DA149020D' '467823B7002C.ms.model.script' // Settings
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" True
ENDMEREF // ME_473DA149020D_ME_47F2317F015E_impl Settings

MEREF ME_473DA15800E2_ME_47F2317F015E_impl
 MELINK Original WL 'ME_473DA15800E2' '467823B7002C.ms.model.script' // BaseId
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" True
ENDMEREF // ME_473DA15800E2_ME_47F2317F015E_impl BaseId

MEREF ME_479731C50290_ME_47F2317F015E_over
 MELINK Original WL 'ME_479731C50290' '51612ED700B4.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_479731C50290_ME_47F2317F015E_over Cleanup

MEREF ME_5243CCEE0271_ME_47F2317F015E_over
 MELINK Original WL 'ME_5243CCEE0271' '4C22178C0102.ms.model.script' // Create
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_5243CCEE0271_ME_47F2317F015E_over Create

MEREF ME_5243E95503E4_ME_47F2317F015E_over
 MELINK Original WL 'ME_5243E95503E4' '4C22137E025C.ms.model.script' // IsSettingAffectsUs
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_5243E95503E4_ME_47F2317F015E_over IsSettingAffectsUs

MEREF ME_5243E9AE0230_ME_47F2317F015E_over
 MELINK Original WL 'ME_5243E9AE0230' '4C22137E025C.ms.model.script' // ReadColontitulSettings
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_5243E9AE0230_ME_47F2317F015E_over ReadColontitulSettings

MEREF ME_540E9DE4024C_ME_47F2317F015E_G
 MELINK Original WL? 'ME_540E9DE4024C' // TnsHAFPainterPrim
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_540E9DE4024C_ME_47F2317F015E_G TnsHAFPainterPrim

MEREF ME_476A5EFF00B5_ME_47F2317F015E_R
 MELINK Original WL 'ME_476A5EFF00B5' '467BAB7F021E.ms.model.script' // IvcmSettingsSource
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_476A5EFF00B5_ME_47F2317F015E_R IvcmSettingsSource

%%ImplementedBy ME_476A5EFF00B5 ME_47F2317F015E

%%InheritedBy ME_540E9DE4024C ME_47F2317F015E

ME ME_47F2317F015E
 MEPROP UID '47F2317F015E'
 MEPROP Name 'TnsHAFPainter'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '-' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_491DCA2C00A9' // Search
 ;
 MELIST Inherits
   Seq: ( HWL ME_540E9DE4024C_ME_47F2317F015E_G // TnsHAFPainterPrim
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_476A5EFF00B5_ME_47F2317F015E_R // IvcmSettingsSource
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_5243FD120266 // Settings
 HWL ME_52440E91014A // f_BaseId
 )
 ; // Attributes
 MELIST Implemented
   Seq: ( ME_473DA149020D_ME_47F2317F015E_impl // Settings
 ME_473DA15800E2_ME_47F2317F015E_impl // BaseId
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_47F2317F015E_over // Cleanup
 ME_5243CCEE0271_ME_47F2317F015E_over // Create
 ME_5243E95503E4_ME_47F2317F015E_over // IsSettingAffectsUs
 ME_5243E9AE0230_ME_47F2317F015E_over // ReadColontitulSettings
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_5244002901F5 // SysUtils
 ME_5244002C00D6 // afwFacade
 ME_5244002E0025 // TevStyleId
 ME_5244002F0306 // nsConst
 ME_52440031026C // TnsSettings
 ME_53EDCCD40372 // vcmBase
 ME_540E9F2E0107 // TnsHAFPainterPrim
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP extprop:pas:UnitName 'nsHAFPainter'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'HAFPainter'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Search\nsHAFPainter.pas'

ENDME // ME_47F2317F015E TnsHAFPainter
