// TevFontArray 480DBEB7009D Vector Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_480DBEB7009D_diagrams

 MEDIAGRAM ME_480DBEB7009D_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_480DBEB7009D' '480DBE6E01D0.ms.model.script' ; // TevFontArray

  MEVIEW ME_480DBEDB0202_view
   MELINK Original WL 'ME_480DBEDB0202' '480DBE6E01D0.ms.model.script' ; // 
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_480DBEDB0202_view

  MELIST Views
   Seq: ( ME_480DBEDB0202_view )
  ; // Views
 ENDMEDIAGRAM // ME_480DBEB7009D_main

 MELIST Diagrams
  Seq: ( ME_480DBEB7009D_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_480DBEB7009D_diagrams
