// Утилиты 481F03780379 UseCases Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_481F03780379_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_481F03780379' '481F03780379.ms.model.script' ; // Утилиты

 MEVIEW ME_481F041C02D9_view
  MELINK Original WL 'ME_481F041C02D9' '481F03780379.ms.model.script' ; // Утилита импорта списка пользователей
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_481F041C02D9_view

ENDMEDIAGRAM // ME_481F03780379_main
