// TctButtonEdit 482AE8CA0176 GuiControl Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_482AE8CA0176_diagrams

 MEDIAGRAM ME_482AE8CA0176_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_482AE8CA0176' '482AE8CA0176.ms.model.script' ; // TctButtonEdit

  MEVIEW ME_482AE97A02F7_view
   MELINK Original WL 'ME_482AE97A02F7' '482AE8CA0176.ms.model.script' ; // Text
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_482AE97A02F7_view

  MELIST Views
   Seq: ( ME_482AE97A02F7_view // Text
   )
  ; // Views
 ENDMEDIAGRAM // ME_482AE8CA0176_main

 MELIST Diagrams
  Seq: ( ME_482AE8CA0176_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_482AE8CA0176_diagrams
