// TevCustomMemoContainer 482D888D039E SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_482D888D039E

ME ME_483FA3BF01F2
 MEPROP UID '483FA3BF01F2'
 MEPROP Name 'Memo'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL 'ME_479878FA0103' '478CF30500C1.ms.model.script' // TComponent
 ;
 UP "needs field" False
 UP "pm" True

ENDME // ME_483FA3BF01F2 Memo

FORWARD ME_483FA33B0045

ME ME_483FAD050164
 MEPROP Name 'Atom'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_47F2272B0394' '47F226C7001F.ms.model.script' // Tk2StackAtom
 ;

ENDME // ME_483FAD050164 Atom

ME ME_483FA33B0045
 MEPROP UID '483FA33B0045'
 MEPROP Name 'UpdateParaParam'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELIST Parameters
   Seq: ( ME_483FAD050164 // Atom
 )
 ; // Parameters

ENDME // ME_483FA33B0045 UpdateParaParam

ME ME_483FA3A301E0
 MEPROP UID '483FA3A301E0'
 MEPROP Name 'Create'
 MEPROP Class class_Operation
 MELINK Stereotype st_ctor::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;

ENDME // ME_483FA3A301E0 Create

ME ME_483FA3B101FA
 MEPROP UID '483FA3B101FA'
 MEPROP Name 'Make'
 MEPROP Class class_Operation
 MELINK Stereotype st_factory::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL 'ME_47C6A603009D' '47C5207602D1.ms.model.script' // InevDocumentContainer
 ;

ENDME // ME_483FA3B101FA Make

ME ME_483FA8210327
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL 'ME_47C69EBC00A8' '47AC75550330.ms.model.script' // Tk2TagID
 ;

ENDME // ME_483FA8210327 

ME ME_483FA9230317
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL? 'ME_483FA8E5036B' // TevTagsListFilter
 ;

ENDME // ME_483FA9230317 

ME ME_483FABF90341
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL? 'ME_4829D81D02E5' // TevCustomMemo
 ;

ENDME // ME_483FABF90341 

ME ME_483FAC1601B7
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL? 'ME_480DBA760390' // k2Facade
 ;

ENDME // ME_483FAC1601B7 

ME ME_483FAC4902AB
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL 'ME_4688D85301B2' '469D0AC7005E.ms.model.script' // IndentType
 ;

ENDME // ME_483FAC4902AB 

ME ME_4864C0A402C7
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL? 'ME_4864C01000A7' // TevMemoProcessor
 ;

ENDME // ME_4864C0A402C7 

ME ME_49AE392203B5
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL 'ME_485683750360' '48492FC0029D.ms.model.script' // TextPara
 ;

ENDME // ME_49AE392203B5 

ME ME_49AE392D0283
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL 'ME_4857C5D803A1' '48492FC0029D.ms.model.script' // SimpleDocument
 ;

ENDME // ME_49AE392D0283 

ME ME_4A8A82470116
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL 'ME_4727223D039C' '4678193C009C.ms.model.script' // TLongArray
 ;

ENDME // ME_4A8A82470116 

ME ME_4A8A82600385
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL? 'ME_4773D64E036C' // l3Base
 ;

ENDME // ME_4A8A82600385 

ME ME_4C4EA1BF012E
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL 'ME_47F245BD01E1' '47F2458300E4.ms.model.script' // Defaults
 ;

ENDME // ME_4C4EA1BF012E 

ME ME_5307781702C3
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_482D888D039E // TevCustomMemoContainer
 ;
 MELINK Target WL 'ME_484CEE9A0170' '484A470100DD.ms.model.script' // Font
 ;

ENDME // ME_5307781702C3 

MEREF ME_47F226170180_ME_482D888D039E_over
 MELINK Original WL 'ME_47F226170180' '47F0870E0034.ms.model.script' // DoBeforeFinishAtom1
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_47F226170180_ME_482D888D039E_over DoBeforeFinishAtom1

MEREF ME_47F2262B0094_ME_482D888D039E_over
 MELINK Original WL 'ME_47F2262B0094' '47F0870E0034.ms.model.script' // DoBeforeFinishAtom
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_47F2262B0094_ME_482D888D039E_over DoBeforeFinishAtom

MEREF ME_47F35245009A_ME_482D888D039E_over
 MELINK Original WL 'ME_47F35245009A' '47F3513A017F.ms.model.script' // MakeProcessor
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_47F35245009A_ME_482D888D039E_over MakeProcessor

MEREF ME_483E6C150277_ME_482D888D039E_over
 MELINK Original WL 'ME_483E6C150277' '483E6CFE02DC.ms.model.script' // DoGetWriter
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_483E6C150277_ME_482D888D039E_over DoGetWriter

MEREF ME_483FA1320271_ME_482D888D039E_over
 MELINK Original WL 'ME_483FA1320271' '47F0870E0034.ms.model.script' // NeedsProgressOnSave
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_483FA1320271_ME_482D888D039E_over NeedsProgressOnSave

MEREF ME_4A8D226F0164_ME_482D888D039E_over
 MELINK Original WL 'ME_4A8D226F0164' '47F0870E0034.ms.model.script' // GetDocumentType
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_4A8D226F0164_ME_482D888D039E_over GetDocumentType

MEREF ME_47F34F00021C_ME_482D888D039E_G
 MELINK Original WL? 'ME_47F34F00021C' // TnevPrintableDocumentContainer
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_47F34F00021C_ME_482D888D039E_G TnevPrintableDocumentContainer

%%InheritedBy ME_47F34F00021C ME_482D888D039E

ME ME_482D888D039E
 MEPROP UID '482D888D039E'
 MEPROP Name 'TevCustomMemoContainer'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4829D7D50156' // Editors
 ;
 MELIST Inherits
   Seq: ( HWL ME_47F34F00021C_ME_482D888D039E_G // TnevPrintableDocumentContainer
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_483FA3BF01F2 // Memo
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_483FA33B0045 // UpdateParaParam
 HWL ME_483FA3A301E0 // Create
 HWL ME_483FA3B101FA // Make
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_47F226170180_ME_482D888D039E_over // DoBeforeFinishAtom1
 ME_47F2262B0094_ME_482D888D039E_over // DoBeforeFinishAtom
 ME_47F35245009A_ME_482D888D039E_over // MakeProcessor
 ME_483E6C150277_ME_482D888D039E_over // DoGetWriter
 ME_483FA1320271_ME_482D888D039E_over // NeedsProgressOnSave
 ME_4A8D226F0164_ME_482D888D039E_over // GetDocumentType
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_483FA8210327 // Tk2TagID
 ME_483FA9230317 // TevTagsListFilter
 ME_483FABF90341 // TevCustomMemo
 ME_483FAC1601B7 // k2Facade
 ME_483FAC4902AB // IndentType
 ME_4864C0A402C7 // TevMemoProcessor
 ME_49AE392203B5 // TextPara
 ME_49AE392D0283 // SimpleDocument
 ME_4A8A82470116 // TLongArray
 ME_4A8A82600385 // l3Base
 ME_4C4EA1BF012E // Defaults
 ME_5307781702C3 // Font
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "author" 'Ëþëèí À.Â.'
 UP "no hands" True
 UP "started" '23.05.1997 09:10'
 UP extprop:pas:UnitName 'evCustomMemoContainer'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'MemoContainer'
 UP intf.pas:Path 'common\components\gui\Garant\Everest\evCustomMemoContainer.pas'

ENDME // ME_482D888D039E TevCustomMemoContainer
