// Tk2BaseStackGenerator 4836B2EC01DE SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4836B2EC01DE

ME ME_53A967A10314
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4836B2EC01DE // Tk2BaseStackGenerator
 ;
 MELINK Target WL? 'ME_53A963F700CD' // Tk2Attributes
 ;

ENDME // ME_53A967A10314 

MEREF ME_47ECAA5B0394_ME_4836B2EC01DE_G
 MELINK Original WL 'ME_47ECAA5B0394' '47ECAA270135.ms.model.script' // Tk2TagGenerator
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_47ECAA5B0394_ME_4836B2EC01DE_G Tk2TagGenerator

%%InheritedBy ME_47ECAA5B0394 ME_4836B2EC01DE

ME ME_4836B2EC01DE
 MEPROP UID '4836B2EC01DE'
 MEPROP Name 'Tk2BaseStackGenerator'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Генераторы тегов со стеком текущего состояния.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_47ECA80B000D' // Generators
 ;
 MELIST Inherits
   Seq: ( HWL ME_47ECAA5B0394_ME_4836B2EC01DE_G // Tk2TagGenerator
 )
 ; // Inherits
 MELIST Dependencies
   Seq: ( ME_53A967A10314 // Tk2Attributes
 )
 ; // Dependencies
 UP "author" 'Люлин А.В.'
 UP "finished" False
 UP "started" '18.09.2002 10:17'
 UP extprop:pas:UnitName 'k2BaseStackGenerator'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'BaseStackGenerator'
 UP intf.pas:Path 'common\components\rtl\Garant\K2\NOT_FINISHED_k2BaseStackGenerator.pas'

ENDME // ME_4836B2EC01DE Tk2BaseStackGenerator
