// Font 4868BA950304 InnerTag Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4868BA950304_diagrams

 MEDIAGRAM ME_4868BA950304_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4868BA950304' '48492FC0029D.ms.model.script' ; // Font

  MEVIEW ME_4868BAA200FA_view
   MELINK Original WL 'ME_4868BAA200FA' '48492FC0029D.ms.model.script' ; // Italic
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4868BAA200FA_view

  MELIST Views
   Seq: ( ME_4868BAA200FA_view // Italic
   )
  ; // Views
 ENDMEDIAGRAM // ME_4868BA950304_main

 MELIST Diagrams
  Seq: ( ME_4868BA950304_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4868BA950304_diagrams
