// TafwCustomCommonTextControl 48BBD6550261 GuiControl Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_48BBD6550261_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_48BBD6550261' '48BBD6550261.ms.model.script' ; // TafwCustomCommonTextControl

 MEVIEW ME_48BBD6AB0328_view
  MELINK Original WL 'ME_48BBD6AB0328' '48BBD6550261.ms.model.script' ; // Paint
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_48BBD6AB0328_view

ENDMEDIAGRAM // ME_48BBD6550261_main
