// TevSimpleEdit 48D253650260 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_48D2409102B7_ME_48D253650260_G
 MELINK Original WL? 'ME_48D2409102B7' // TevEditControl
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_48D2409102B7_ME_48D253650260_G TevEditControl

%%InheritedBy ME_48D2409102B7 ME_48D253650260

ME ME_48D253650260
 MEPROP UID '48D253650260'
 MEPROP Name 'TevSimpleEdit'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Поле редактора для конечного исользования' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_47CEBC900123' // qf
 ;
 MELIST Inherits
   Seq: ( HWL ME_48D2409102B7_ME_48D253650260_G // TevEditControl
 )
 ; // Inherits
 UP "author" 'Инишев Д.А.'
 UP "no hands" True
 UP extprop:pas:UnitName 'evSimpleEdit'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'SimpleEdit'
 UP intf.pas:Path 'common\components\gui\Garant\Everest\qf\evSimpleEdit.pas'

ENDME // ME_48D253650260 TevSimpleEdit
