// evRangeTools 48E3BA3300DE UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_48E3BA3300DE_diagrams

 MEDIAGRAM ME_48E3BA3300DE_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_48E3BA3300DE' '4829D7D50156.ms.model.script' ; // evRangeTools

  MEVIEW ME_48E3BA60014C_view
   MELINK Original WL 'ME_48E3BA60014C' '4829D7D50156.ms.model.script' ; // TevBlockCompareResult
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_48E3BA60014C_view

  MELIST Views
   Seq: ( ME_48E3BA60014C_view // TevBlockCompareResult
   )
  ; // Views
 ENDMEDIAGRAM // ME_48E3BA3300DE_main

 MELIST Diagrams
  Seq: ( ME_48E3BA3300DE_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_48E3BA3300DE_diagrams
