// DocumentDataObjects 48F5EE2702FF Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4682704E0347
%%Inner ME_4682706F038A
%%Inner ME_48F72B630069
%%Inner ME_48F8B61F0032

ME ME_48F5EE2702FF
 MEPROP UID '48F5EE2702FF'
 MEPROP Name 'DocumentDataObjects'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4ABB680E0218' // Common$Lib
 ;
 MELIST Children
   Seq: ( WL? 'ME_4682704E0347' // TnsSingleAttributeStorable
 WL? 'ME_4682706F038A' // TnsSingleAttributeDataObject
 WL? 'ME_48F72B630069' // TnsSingleAttributeData
 WL? 'ME_48F8B61F0032' // TnsContentsTreeStorable
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4423F94903C8' // IO
 WL? 'ME_4570511E038A' // Document
 WL? 'ME_4678209200A6' // nevBase
 WL? 'ME_4682595B0268' // l3TreeInterfaces
 WL? 'ME_469C688102A3' // DataObjects
 WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_47AC75550330' // k2Tags
 WL? 'ME_47C5207602D1' // nevTools
 WL? 'ME_47F2170002B2' // nsTypes
 WL? 'ME_4802FF41005C' // DataObjects
 WL? 'ME_48492FC0029D' // Standard
 WL? 'ME_4AB0C3C60310' // Sys
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_48F5EE2702FF DocumentDataObjects
