// InsCutToLeafFilter 4901F73E01D0 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4901F73E01D0_diagrams

 MEDIAGRAM ME_4901F73E01D0_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4901F73E01D0' '4A9F98B901A5.ms.model.script' ; // InsCutToLeafFilter

  MEVIEW ME_4901F74E0224_view
   MELINK Original WL 'ME_4901F74E0224' '4A9F98B901A5.ms.model.script' ; // LeafCount
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4901F74E0224_view

  MELIST Views
   Seq: ( ME_4901F74E0224_view // LeafCount
   )
  ; // Views
 ENDMEDIAGRAM // ME_4901F73E01D0_main

 MELIST Diagrams
  Seq: ( ME_4901F73E01D0_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4901F73E01D0_diagrams
