// InsBaseSearchPromptFilters 4901F75A0378 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4901F75A0378_diagrams

 MEDIAGRAM ME_4901F75A0378_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4901F75A0378' '4A9F98B901A5.ms.model.script' ; // InsBaseSearchPromptFilters

  MEVIEW ME_4901F789034B_view
   MELINK Original WL 'ME_4901F789034B' '4A9F98B901A5.ms.model.script' ; // SetLeaf
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4901F789034B_view

  MEVIEW ME_4AA4D7930085_view
   MELINK Original WL 'ME_4AA4D7930085' '4A9F98B901A5.ms.model.script' ; // SetPromptForDoc
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4AA4D7930085_view

  MELIST Views
   Seq: ( ME_4901F789034B_view // SetLeaf
   ME_4AA4D7930085_view // SetPromptForDoc
   )
  ; // Views
 ENDMEDIAGRAM // ME_4901F75A0378_main

 MELIST Diagrams
  Seq: ( ME_4901F75A0378_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4901F75A0378_diagrams
