// InscContextFilterState 4908393001C5 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4908393001C5_diagrams

 MEDIAGRAM ME_4908393001C5_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4908393001C5' '490838E10313.ms.model.script' ; // InscContextFilterState

  MEVIEW ME_490839F50038_view
   MELINK Original WL 'ME_490839F50038' '490838E10313.ms.model.script' ; // NeedRefilterTree
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_490839F50038_view

  MELIST Views
   Seq: ( ME_490839F50038_view // NeedRefilterTree
   )
  ; // Views
 ENDMEDIAGRAM // ME_4908393001C5_main

 MELIST Diagrams
  Seq: ( ME_4908393001C5_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4908393001C5_diagrams
