// TdsAutoreferat 491C3B8D00D8 ViewAreaControllerImp Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_491C3B8D00D8_diagrams

 MEDIAGRAM ME_491C3B8D00D8_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_491C3B8D00D8' '491C3B8D00D8.ms.model.script' ; // TdsAutoreferat

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_491C3B8D00D8_main

 MELIST Diagrams
  Seq: ( ME_491C3B8D00D8_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_491C3B8D00D8_diagrams
