// TdsFolders 492198EA0072 ViewAreaControllerImp Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_492198EA0072

ME ME_49340B11030B
 MEPROP UID '49340B11030B'
 MEPROP Name 'FormDataSourceType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_492198EA0072 // TdsFolders
 ;
 MELINK Target WL 'ME_49340A8D0243' '492192300095.ms.model.script' // IdsFolders
 ;

ENDME // ME_49340B11030B FormDataSourceType

ME ME_492198EA0072
 MEPROP UID '492198EA0072'
 MEPROP Name 'TdsFolders'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_ViewAreaControllerImp ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4921954E019B' '4921954E019B.ms.model.script' // Folders
 ;
 MELIST Inherits
   Seq: ( WL 'ME_47ECE94D03D4' '47D0E1500033.ms.model.script' // vcmFormDataSourcePrim
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_49340A8D0243' '492192300095.ms.model.script' // IdsFolders
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_49340B11030B // FormDataSourceType
 )
 ; // Attributes
 UP "author" 'Морозов М.А.'
 UP "no hands" True
 UP "started" '03.05.2006 14:59'
 UP extprop:pas:UnitName 'dsFolders'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'dsFolders'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Folders\dsFolders.pas'

ENDME // ME_492198EA0072 TdsFolders
