// TbsConsultation 49228BA50210 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_49228BA50210_diagrams

 MEDIAGRAM ME_49228BA50210_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_49228BA50210' '4ABCF1450282.ms.model.script' ; // TbsConsultation

  MEVIEW ME_498FFACA0046_view
   MELINK Original WL 'ME_498FFACA0046' '4ABCF1450282.ms.model.script' ; // Create
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_498FFACA0046_view

  MEVIEW ME_498FFAE200B0_view
   MELINK Original WL 'ME_498FFAE200B0' '4ABCF1450282.ms.model.script' ; // Make
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_498FFAE200B0_view

  MEVIEW ME_498FFBFE016A_view
   MELINK Original WL 'ME_498FFBFE016A' '4ABCF1450282.ms.model.script' ; // f_IsRefusedOldFormat
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_498FFBFE016A_view

  MEVIEW ME_498FFC2C008B_view
   MELINK Original WL 'ME_498FFC2C008B' '4ABCF1450282.ms.model.script' ; // f_IsStatusChached
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_498FFC2C008B_view

  MEVIEW ME_498FFC560125_view
   MELINK Original WL 'ME_498FFC560125' '4ABCF1450282.ms.model.script' ; // CachedStatuses
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_498FFC560125_view

  MEVIEW ME_498FFC850180_view
   MELINK Original WL 'ME_498FFC850180' '4ABCF1450282.ms.model.script' ; // Consultation
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_498FFC850180_view

  MEVIEW ME_498FFCAA03B9_view
   MELINK Original WL 'ME_498FFCAA03B9' '4ABCF1450282.ms.model.script' ; // f_Text
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_498FFCAA03B9_view

  MELIST Views
   Seq: ( ME_498FFACA0046_view // Create
   ME_498FFAE200B0_view // Make
   ME_498FFBFE016A_view // f_IsRefusedOldFormat
   ME_498FFC2C008B_view // f_IsStatusChached
   ME_498FFC560125_view // CachedStatuses
   ME_498FFC850180_view // Consultation
   ME_498FFCAA03B9_view // f_Text
   )
  ; // Views
 ENDMEDIAGRAM // ME_49228BA50210_main

 MELIST Diagrams
  Seq: ( ME_49228BA50210_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_49228BA50210_diagrams
