// TdsUserList 49246742002B ViewAreaControllerImp Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_49246742002B_diagrams

 MEDIAGRAM ME_49246742002B_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_49246742002B' '49246742002B.ms.model.script' ; // TdsUserList

  MEVIEW ME_49246C70028F_view
   MELINK Original WL 'ME_49246C70028F' '49246742002B.ms.model.script' ; // MakeSelectedList
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_49246C70028F_view

  MELIST Views
   Seq: ( ME_49246C70028F_view // MakeSelectedList
   )
  ; // Views
 ENDMEDIAGRAM // ME_49246742002B_main

 MELIST Diagrams
  Seq: ( ME_49246742002B_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_49246742002B_diagrams
