// InsCRSimpleListTypeRootNodeListener 4926A3780038 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4926A3780038_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4926A3780038' '47ECAAF901F8.ms.model.script' ; // InsCRSimpleListTypeRootNodeListener

 MEVIEW ME_4926A3930339_view
  MELINK Original WL 'ME_4926A3930339' '47ECAAF901F8.ms.model.script' ; // Updated
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4926A3930339_view

ENDMEDIAGRAM // ME_4926A3780038_main
