// TdsAnnotation 493D4783035C ViewAreaControllerImp Class

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_49589999029F_ME_493D4783035C
 MELINK Original WL 'ME_49589999029F' '47EA20430108.ms.model.script' // DoGet_PreviewCaleeArea
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_49589999029F_ME_493D4783035C DoGet_PreviewCaleeArea

ME ME_493D4783035C
 MEPROP UID '493D4783035C'
 MEPROP Name 'TdsAnnotation'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_ViewAreaControllerImp ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Аннотация к документу' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_493D465902FA' '493D465902FA.ms.model.script' // DocumentAndList
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4958980300D5' '4958980300D5.ms.model.script' // TdsChildDocument
 )
 ; // Inherits
 MELIST Overridden
   Seq: ( ME_49589999029F_ME_493D4783035C // DoGet_PreviewCaleeArea
 )
 ; // Overridden
 UP "author" 'Морозов М.А.'
 UP "no hands" True
 UP "started" '2005/11/25 09:45:47'
 UP extprop:pas:UnitName 'dsAnnotation'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'dsAnnotation'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\Business\Document\dsAnnotation.pas'

ENDME // ME_493D4783035C TdsAnnotation
