// Consultation 493FCF1E03DC VCMControllers Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_491C3E540050
%%Inner ME_491C3E40007B

ME ME_493FCF1E03DC
 MEPROP UID '493FCF1E03DC'
 MEPROP Name 'Consultation'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_VCMControllers ;
 %SUMMARY 'Работа с консультациями' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4ABCFA76015C' // Consultation
 ;
 MELIST Children
   Seq: ( WL? 'ME_491C3E540050' // ConsultationInterfaces
 WL? 'ME_491C3E40007B' // Consultation
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_447878770121' // GCI
 WL? 'ME_456EA3D2031C' // GblAdapterLib
 WL? 'ME_4677E16A022A' // K2
 WL? 'ME_4677FBA70343' // l3Interfaces
 WL? 'ME_4677FF4B0036' // Data
 WL? 'ME_467A8734039C' // EVD
 WL? 'ME_4680C57D01E9' // Business
 WL? 'ME_4680E7D50168' // Everest Engine
 WL? 'ME_4790C3B8021E' // VCM
 WL? 'ME_4790D09A0378' // L3
 WL? 'ME_4797632D0273' // Everest
 WL? 'ME_47E9EEC60260' // Model
 WL? 'ME_481EF5C4020D' // Оболочка
 WL? 'ME_4954FAA00232' // Search
 WL? 'ME_4A85683403A8' // View
 WL? 'ME_4A9FFD3F01AD' // Search
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_4ABB680E0218' // Common$Lib
 WL? 'ME_4ABCF16F01CD' // Consultation$Lib
 WL? 'ME_4C6A65ED0374' // F1DocumentProcessing
 WL? 'ME_4CF380E402F8' // Consultation$View
 WL? 'ME_4D1B64E70031' // BusinessInterfaces
 WL? 'ME_4D1B6BAB022D' // F1DocumentProcessingInterfaces
 WL? 'ME_4E2F0E1B03BB' // L3$Domain
 WL? 'ME_54B90AC6014B' // StringUtils
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "ifndef" 'Admin'
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\Consultation'

ENDME // ME_493FCF1E03DC Consultation
