// Autoreferat 49411E4001AB VCMControllers Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_492F0586030C
%%Inner ME_491C3ADB03A5

ME ME_49411E4001AB
 MEPROP UID '49411E4001AB'
 MEPROP Name 'Autoreferat'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_VCMControllers ;
 %SUMMARY 'Работа с новостной лентой' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4A92CF230269' // Autoreferat
 ;
 MELIST Children
   Seq: ( WL? 'ME_492F0586030C' // AutoreferatInterfaces
 WL? 'ME_491C3ADB03A5' // Autoreferat
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_456EA3D2031C' // GblAdapterLib
 WL? 'ME_4677E16A022A' // K2
 WL? 'ME_4677FF4B0036' // Data
 WL? 'ME_467A8734039C' // EVD
 WL? 'ME_4680C57D01E9' // Business
 WL? 'ME_4680E7D50168' // Everest Engine
 WL? 'ME_469F3E37025A' // Rtl
 WL? 'ME_46A0E6C5023A' // ActiveX
 WL? 'ME_4790C3B8021E' // VCM
 WL? 'ME_4790D09A0378' // L3
 WL? 'ME_4797632D0273' // Everest
 WL? 'ME_47E9EEC60260' // Model
 WL? 'ME_4954FAA00232' // Search
 WL? 'ME_4AB0997B00A2' // Common
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_4ABB680E0218' // Common$Lib
 WL? 'ME_4C6A65ED0374' // F1DocumentProcessing
 WL? 'ME_4CEBA36A00AA' // f1DocumentTagsImplementation
 WL? 'ME_4D1B64E70031' // BusinessInterfaces
 WL? 'ME_4D1B6BAB022D' // F1DocumentProcessingInterfaces
 WL? 'ME_53BA5A5D03A0' // TabInterface
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "exec mode" 'concluded'
 UP "gui" 'prj'
 UP "is namespace" True
 UP "vendor" 'none'
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\Autoreferat'

ENDME // ME_49411E4001AB Autoreferat
