// Editor 4952683C007B Views Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4952683C007B_diagrams

 MEDIAGRAM ME_4952683C007B_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4952683C007B' '4952683C007B.ms.model.script' ; // Editor

  MEVIEW ME_4B877FE00340_view
   MELINK Original WL 'ME_4B877FE00340' '4B877FE00340.ms.model.script' ; // TeeEditorExportModelPart
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4B877FE00340_view

  MEVIEW ME_4952693000EA_view
   MELINK Original WL 'ME_4952693000EA' '4952693000EA.ms.model.script' ; // TeeEditorExport
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4952693000EA_view

  MEVIEW ME_4AC5D3DB0371_view
   MELINK Original WL 'ME_4AC5D3DB0371' '4AC5D3DB0371.ms.model.script' ; // TeeMemo
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4AC5D3DB0371_view

  MEVIEW ME_4AC5D35601BB_view
   MELINK Original WL 'ME_4AC5D35601BB' '4952683C007B.ms.model.script' ; // eeCustomMemo
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4AC5D35601BB_view

  MEVIEW ME_4AC5D3380185_view
   MELINK Original WL 'ME_4AC5D3380185' '4AC5D3380185.ms.model.script' ; // TeeMemoWithEditOperations
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4AC5D3380185_view

  MEVIEW ME_495268900201_view
   MELINK Original WL 'ME_495268900201' '495268900201.ms.model.script' ; // TeeEditor
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_495268900201_view

  MEVIEW ME_4CFFD97801C0_view
   MELINK Original WL 'ME_4CFFD97801C0' '4CFFD97801C0.ms.model.script' ; // TeePreviewPanel
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_4CFFD97801C0_view

  MEVIEW ME_54C24DE1010C_view
   MELINK Original WL 'ME_54C24DE1010C' '4952683C007B.ms.model.script' ; // eeCustomEditor
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_54C24DE1010C_view

  MEVIEW ME_4CFFD8F603A0_view
   MELINK Original WL 'ME_4CFFD8F603A0' '4CFFD8F603A0.ms.model.script' ; // TeeEditorWithoutOperations
   MEPROP X 200
   MEPROP Y 180
  ENDMEVIEW // ME_4CFFD8F603A0_view

  MELIST Views
   Seq: ( ME_4B877FE00340_view // TeeEditorExportModelPart
   ME_4952693000EA_view // TeeEditorExport
   ME_4AC5D3DB0371_view // TeeMemo
   ME_4AC5D35601BB_view // eeCustomMemo
   ME_4AC5D3380185_view // TeeMemoWithEditOperations
   ME_495268900201_view // TeeEditor
   ME_4CFFD97801C0_view // TeePreviewPanel
   ME_54C24DE1010C_view // eeCustomEditor
   ME_4CFFD8F603A0_view // TeeEditorWithoutOperations
   )
  ; // Views
 ENDMEDIAGRAM // ME_4952683C007B_main

 MELIST Diagrams
  Seq: ( ME_4952683C007B_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4952683C007B_diagrams
