// Search 4954FAA00232 VCMControllers Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4954FAA00232_diagrams

 MEDIAGRAM ME_4954FAA00232_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4954FAA00232' ; // Search

  MEVIEW ME_491DAF4202EE_view
   MELINK Original WL? 'ME_491DAF4202EE' ; // SearchInterfaces
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_491DAF4202EE_view

  MEVIEW ME_46837A08002C_view
   MELINK Original WL? 'ME_46837A08002C' ; // nsQueryInterfaces
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_46837A08002C_view

  MELIST Views
   Seq: ( ME_491DAF4202EE_view // SearchInterfaces
   ME_46837A08002C_view // nsQueryInterfaces
   )
  ; // Views
 ENDMEDIAGRAM // ME_4954FAA00232_main

 MELIST Diagrams
  Seq: ( ME_4954FAA00232_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4954FAA00232_diagrams
