// SearcheableText 496B68FC000B VCMForm Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_496B68FC000B_diagrams

 MEDIAGRAM ME_496B68FC000B_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_496B68FC000B' '496B68FC000B.ms.model.script' ; // SearcheableText

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_496B68FC000B_main

 MELIST Diagrams
  Seq: ( ME_496B68FC000B_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_496B68FC000B_diagrams
