// PrimTreeAttributeSelect 497ECC0E0325 VCMForm Class

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4BD6F94500AC
%%Inner ME_4BD6F9540396
%%Inner ME_4BD6F97301F4
%%Inner ME_4BD6F992021A
%%Inner ME_4C2B075E0155
%%Inner ME_4C2B1BE20259
%%Inner ME_53A950A801A6

FORWARD ME_497ECC0E0325

ME ME_4BD6F94500AC
 MEPROP UID '4BD6F94500AC'
 MEPROP Name 'astNone'
 MEPROP Class class_Class
 MELINK Stereotype st_UserType ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Поиск: Выбор реквизита' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 UP "ImageIndex" '-1'
 UP "Weight" '-1'
 UP extprop:pas:UnitName 'PrimTreeAttributeSelect_astNone_UserType'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms\PrimTreeAttributeSelect_astNone_UserType.pas'

ENDME // ME_4BD6F94500AC astNone

%%InheritedBy ME_4BD6F94500AC ME_4BD6F9540396

ME ME_4BD6F9540396
 MEPROP UID '4BD6F9540396'
 MEPROP Name 'astOneLevel'
 MEPROP Class class_Class
 MELINK Stereotype st_UserType ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Ситуации второго уровня' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( HWL ME_4BD6F94500AC // astNone
 )
 ; // Inherits
 UP "ImageIndex" '-1'
 UP "VisibleToUser" False
 UP "Weight" '-1'
 UP extprop:pas:UnitName 'PrimTreeAttributeSelect_astOneLevel_UserType'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms\PrimTreeAttributeSelect_astOneLevel_UserType.pas'

ENDME // ME_4BD6F9540396 astOneLevel

%%InheritedBy ME_4BD6F9540396 ME_4BD6F97301F4

ME ME_4BD6F97301F4
 MEPROP UID '4BD6F97301F4'
 MEPROP Name 'astFirstLevel'
 MEPROP Class class_Class
 MELINK Stereotype st_UserType ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Ситуации первого уровня' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( HWL ME_4BD6F9540396 // astOneLevel
 )
 ; // Inherits
 UP "ImageIndex" '-1'
 UP "VisibleToUser" False
 UP "Weight" '-1'
 UP extprop:pas:UnitName 'PrimTreeAttributeSelect_astFirstLevel_UserType'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms\PrimTreeAttributeSelect_astFirstLevel_UserType.pas'

ENDME // ME_4BD6F97301F4 astFirstLevel

FORWARD ME_4BD6F992021A

ME ME_4BD6F9A8011C
 MEPROP UID '4BD6F9A8011C'
 MEPROP Name 'UseToolbarOfUserTypeName'
 MEPROP Class class_Attribute
 MELINK Stereotype st_link::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_lnk
 MELINK Parent HWL ME_4BD6F992021A // astTaxesPublishSearch
 ;
 MELINK Target HWL ME_4BD6F94500AC // astNone
 ;

ENDME // ME_4BD6F9A8011C UseToolbarOfUserTypeName

%%InheritedBy ME_4BD6F97301F4 ME_4BD6F992021A

ME ME_4BD6F992021A
 MEPROP UID '4BD6F992021A'
 MEPROP Name 'astTaxesPublishSearch'
 MEPROP Class class_Class
 MELINK Stereotype st_UserType ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'СМИ по налогам и бухучету' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( HWL ME_4BD6F97301F4 // astFirstLevel
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_4BD6F9A8011C // UseToolbarOfUserTypeName
 )
 ; // Attributes
 UP "ImageIndex" '-1'
 UP "VisibleToUser" False
 UP "Weight" '-1'
 UP extprop:pas:UnitName 'PrimTreeAttributeSelect_astTaxesPublishSearch_UserType'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms\PrimTreeAttributeSelect_astTaxesPublishSearch_UserType.pas'

ENDME // ME_4BD6F992021A astTaxesPublishSearch

ME ME_4AE831FA00F9_ME_4C2B075E0155
 MELINK Original WL 'ME_4AE831FA00F9' '4AE831B30019.ms.model.script' // ExternalCharPressed
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AE831FA00F9_ME_4C2B075E0155 ExternalCharPressed

%%ImplementedBy ME_4AE831E70016 ME_4C2B075E0155

%%InheritedBy ME_4BD6F9540396 ME_4C2B075E0155

ME ME_4C2B075E0155
 MEPROP UID '4C2B075E0155'
 MEPROP Name 'ExcludeExternalCharPressedForOneLevel'
 MEPROP Class class_Class
 MELINK Stereotype st_ExcludeUserTypes ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( HWL ME_4BD6F9540396 // astOneLevel
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_4AE831E70016' '4AE831B30019.ms.model.script' // AttributeTree$Select
 )
 ; // Implements
 MELIST Implemented
   Seq: ( ME_4AE831FA00F9_ME_4C2B075E0155 // ExternalCharPressed
 )
 ; // Implemented

ENDME // ME_4C2B075E0155 ExcludeExternalCharPressedForOneLevel

ME ME_4C2B1B9100B5_ME_4C2B1BE20259
 MELINK Original WL 'ME_4C2B1B9100B5' '4AE831B30019.ms.model.script' // FindFirstSelected
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" False
 UP "LongProcess" False
 UP "no prefix" False
 UP "ShowInContextMenu" True
 UP "ShowInToolbar" False
ENDME // ME_4C2B1B9100B5_ME_4C2B1BE20259 FindFirstSelected

%%ImplementedBy ME_4C2B1B8003E4 ME_4C2B1BE20259

%%InheritedBy ME_4BD6F9540396 ME_4C2B1BE20259

ME ME_4C2B1BE20259
 MEPROP UID '4C2B1BE20259'
 MEPROP Name 'ExludeFindFirstSelectedForOneLevel'
 MEPROP Class class_Class
 MELINK Stereotype st_ExcludeUserTypes ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( HWL ME_4BD6F9540396 // astOneLevel
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_4C2B1B8003E4' '4AE831B30019.ms.model.script' // Folder
 )
 ; // Implements
 MELIST Implemented
   Seq: ( ME_4C2B1B9100B5_ME_4C2B1BE20259 // FindFirstSelected
 )
 ; // Implemented

ENDME // ME_4C2B1BE20259 ExludeFindFirstSelectedForOneLevel

FORWARD ME_53A950A801A6

ME ME_53A9515E0061
 MEPROP UID '53A9515E0061'
 MEPROP Name 'UseToolbarOfUserTypeName'
 MEPROP Class class_Attribute
 MELINK Stereotype st_link::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_lnk
 MELINK Parent HWL ME_53A950A801A6 // astPharmPublishSearch
 ;
 MELINK Target HWL ME_4BD6F94500AC // astNone
 ;

ENDME // ME_53A9515E0061 UseToolbarOfUserTypeName

%%InheritedBy ME_4BD6F992021A ME_53A950A801A6

ME ME_53A950A801A6
 MEPROP UID '53A950A801A6'
 MEPROP Name 'astPharmPublishSearch'
 MEPROP Class class_Class
 MELINK Stereotype st_UserType ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'СМИ по медицине и здравоохранению' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( HWL ME_4BD6F992021A // astTaxesPublishSearch
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_53A9515E0061 // UseToolbarOfUserTypeName
 )
 ; // Attributes
 UP "ImageIndex" '-1'
 UP "VisibleToUser" False
 UP "Weight" '-1'
 UP extprop:pas:UnitName 'PrimTreeAttributeSelect_astPharmPublishSearch_UserType'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms\PrimTreeAttributeSelect_astPharmPublishSearch_UserType.pas'

ENDME // ME_53A950A801A6 astPharmPublishSearch

FORWARD ME_527746CF030B

ME ME_4ACDE6290267
 MEPROP UID '4ACDE6290267'
 MEPROP Name 'ContextFilter'
 MEPROP Class class_Class
 MELINK Stereotype st_Control ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_527746CF030B // BackgroundPanel
 ;
 UP "ControlClass" 'TnscContextFilter'
 UP "pm" True
 UP "put to dfm" False

ENDME // ME_4ACDE6290267 ContextFilter

ME ME_4AEAEABF034E_ME_4ACDE63F00C5
 MELINK Original WL 'ME_4AEAEABF034E' '4AE831B30019.ms.model.script' // DefaultAction
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AEAEABF034E_ME_4ACDE63F00C5 DefaultAction

ME ME_4AFAFB4602D9_ME_4ACDE63F00C5
 MELINK Original WL 'ME_4AFAFB4602D9' '4AE831B30019.ms.model.script' // LogicOr
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" False
 UP "LongProcess" False
 UP "no prefix" False
 UP "ShowInContextMenu" 'undefined'
 UP "ShowInToolbar" 'undefined'
ENDME // ME_4AFAFB4602D9_ME_4ACDE63F00C5 LogicOr

ME ME_4AFAFB5800B9_ME_4ACDE63F00C5
 MELINK Original WL 'ME_4AFAFB5800B9' '4AE831B30019.ms.model.script' // LogicAnd
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" False
 UP "LongProcess" False
 UP "no prefix" False
 UP "ShowInContextMenu" 'undefined'
 UP "ShowInToolbar" 'undefined'
ENDME // ME_4AFAFB5800B9_ME_4ACDE63F00C5 LogicAnd

ME ME_4AFAFB7002B5_ME_4ACDE63F00C5
 MELINK Original WL 'ME_4AFAFB7002B5' '4AE831B30019.ms.model.script' // LogicNot
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" False
 UP "LongProcess" False
 UP "no prefix" False
 UP "ShowInContextMenu" 'undefined'
 UP "ShowInToolbar" 'undefined'
ENDME // ME_4AFAFB7002B5_ME_4ACDE63F00C5 LogicNot

ME ME_4BDAF7880236_ME_4ACDE63F00C5
 MELINK Original WL 'ME_4BDAF7880236' '4BDAF7510113.ms.model.script' // ExpandAll
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" False
 UP "LongProcess" False
 UP "no prefix" False
 UP "ShowInContextMenu" 'undefined'
 UP "ShowInToolbar" 'undefined'
ENDME // ME_4BDAF7880236_ME_4ACDE63F00C5 ExpandAll

ME ME_4BDAF7A2005C_ME_4ACDE63F00C5
 MELINK Original WL 'ME_4BDAF7A2005C' '4BDAF7510113.ms.model.script' // CollapseAll
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" False
 UP "LongProcess" False
 UP "no prefix" False
 UP "ShowInContextMenu" 'undefined'
 UP "ShowInToolbar" 'undefined'
ENDME // ME_4BDAF7A2005C_ME_4ACDE63F00C5 CollapseAll

ME ME_4BDAF7B803CF_ME_4ACDE63F00C5
 MELINK Original WL 'ME_4BDAF7B803CF' '4BDAF7510113.ms.model.script' // Wrap
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" False
 UP "LongProcess" False
 UP "no prefix" False
 UP "ShowInContextMenu" 'undefined'
 UP "ShowInToolbar" 'undefined'
ENDME // ME_4BDAF7B803CF_ME_4ACDE63F00C5 Wrap

ME ME_4C44444E0066_ME_4ACDE63F00C5
 MELINK Original WL 'ME_4C44444E0066' '4AE831B30019.ms.model.script' // LogicOrShortcut
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" False
 UP "LongProcess" False
 UP "no prefix" False
 UP "ShowInContextMenu" 'undefined'
 UP "ShowInToolbar" 'undefined'
ENDME // ME_4C44444E0066_ME_4ACDE63F00C5 LogicOrShortcut

ME ME_4C4445300216_ME_4ACDE63F00C5
 MELINK Original WL 'ME_4C4445300216' '4AE831B30019.ms.model.script' // DropSelection
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" False
 UP "LongProcess" False
 UP "no prefix" False
 UP "ShowInContextMenu" 'undefined'
 UP "ShowInToolbar" 'undefined'
ENDME // ME_4C4445300216_ME_4ACDE63F00C5 DropSelection

%%ImplementedBy ME_4AEAEAB60182 ME_4ACDE63F00C5
%%ImplementedBy ME_4BDAF7790158 ME_4ACDE63F00C5
%%ImplementedBy ME_4C44452402C9 ME_4ACDE63F00C5

ME ME_4ACDE63F00C5
 MEPROP UID '4ACDE63F00C5'
 MEPROP Name 'AttributeTree'
 MEPROP Class class_Class
 MELINK Stereotype st_Control ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_527746CF030B // BackgroundPanel
 ;
 MELIST Implements
   Seq: ( WL 'ME_4AEAEAB60182' '4AE831B30019.ms.model.script' // Attribute
 WL 'ME_4BDAF7790158' '4BDAF7510113.ms.model.script' // Tree
 WL 'ME_4C44452402C9' '4AE831B30019.ms.model.script' // Selection
 )
 ; // Implements
 MELIST Implemented
   Seq: ( ME_4AEAEABF034E_ME_4ACDE63F00C5 // DefaultAction
 ME_4AFAFB4602D9_ME_4ACDE63F00C5 // LogicOr
 ME_4AFAFB5800B9_ME_4ACDE63F00C5 // LogicAnd
 ME_4AFAFB7002B5_ME_4ACDE63F00C5 // LogicNot
 ME_4BDAF7880236_ME_4ACDE63F00C5 // ExpandAll
 ME_4BDAF7A2005C_ME_4ACDE63F00C5 // CollapseAll
 ME_4BDAF7B803CF_ME_4ACDE63F00C5 // Wrap
 ME_4C44444E0066_ME_4ACDE63F00C5 // LogicOrShortcut
 ME_4C4445300216_ME_4ACDE63F00C5 // DropSelection
 )
 ; // Implemented
 UP "ControlClass" 'TnscTreeViewHotTruck'
 UP "pm" True
 UP "put to dfm" False

ENDME // ME_4ACDE63F00C5 AttributeTree

ME ME_527746CF030B
 MEPROP UID '527746CF030B'
 MEPROP Name 'BackgroundPanel'
 MEPROP Class class_Class
 MELINK Stereotype st_Control ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Attributes
   Seq: ( HWL ME_4ACDE6290267 // ContextFilter
 HWL ME_4ACDE63F00C5 // AttributeTree
 )
 ; // Attributes
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "ControlClass" 'TvtPanel'
 UP "pm" True
 UP "put to dfm" False

ENDME // ME_527746CF030B BackgroundPanel

ME ME_497ECC8E0036
 MEPROP UID '497ECC8E0036'
 MEPROP Name 'dsTreeAttributeSelect'
 MEPROP Class class_Attribute
 MELINK Stereotype st_ViewArea::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_lnk
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4924352E01C3' '491DAF4202EE.ms.model.script' // IdsTreeAttributeSelect
 ;

ENDME // ME_497ECC8E0036 dsTreeAttributeSelect

ME ME_4AEF38D40105
 MEPROP UID '4AEF38D40105'
 MEPROP Name 'f_NeedRefilterTree'
 MEPROP Class class_Attribute
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_lnk
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4AEF38D40105 f_NeedRefilterTree

ME ME_52774DA600FD
 MEPROP UID '52774DA600FD'
 MEPROP Name 'DS'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4924352E01C3' '491DAF4202EE.ms.model.script' // IdsTreeAttributeSelect
 ;
 UP "pm" True

ENDME // ME_52774DA600FD DS

ME ME_52774DDF02AF
 MEPROP UID '52774DDF02AF'
 MEPROP Name 'TaggedTreeInfo'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_49006C6F02C8' '4990510C0026.ms.model.script' // InsTaggedTreeInfo
 ;
 UP "pm" True

ENDME // ME_52774DDF02AF TaggedTreeInfo

ME ME_52774E0A018E
 MEPROP UID '52774E0A018E'
 MEPROP Name 'RootInfo'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4909E0980010' '47ECAAF901F8.ms.model.script' // InsRootInfo
 ;
 UP "pm" True

ENDME // ME_52774E0A018E RootInfo

ME ME_5277509B008E
 MEPROP UID '5277509B008E'
 MEPROP Name 'f_OrState'
 MEPROP Class class_Attribute
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_5277509B008E f_OrState

ME ME_527750A60194
 MEPROP UID '527750A60194'
 MEPROP Name 'f_AndState'
 MEPROP Class class_Attribute
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_527750A60194 f_AndState

ME ME_527750AE0202
 MEPROP UID '527750AE0202'
 MEPROP Name 'f_NotState'
 MEPROP Class class_Attribute
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_527750AE0202 f_NotState

ME ME_5277512702E8
 MEPROP UID '5277512702E8'
 MEPROP Name 'f_CaptionMap'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_492438C90376' '499192F203B4.ms.model.script' // InsStringValueMap
 ;

ENDME // ME_5277512702E8 f_CaptionMap

ME ME_527751400121
 MEPROP UID '527751400121'
 MEPROP Name 'f_Painted'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_527751400121 f_Painted

ME ME_52777F37036D
 MEPROP UID '52777F37036D'
 MEPROP Name 'f_LockCurrentChange'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_52777F37036D f_LockCurrentChange

FORWARD ME_4ACDE6BF0255

ME ME_4ACDE95E00EE
 MEPROP UID '4ACDE95E00EE'
 MEPROP Name 'Filters'
 MEPROP Class class_Attribute
 MELINK Stereotype st_var::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 MELINK Target WL 'ME_4902013F03CC' '47ECAAF901F8.ms.model.script' // InsAttributeTreeFilters
 ;
 UP "IsResult" False

ENDME // ME_4ACDE95E00EE Filters

ME ME_4ACDE97D0289
 MEPROP UID '4ACDE97D0289'
 MEPROP Name 'Tree'
 MEPROP Class class_Attribute
 MELINK Stereotype st_var::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 MELINK Target WL 'ME_46835C050374' '4682595B0268.ms.model.script' // Il3FilterableTree
 ;
 UP "IsResult" False

ENDME // ME_4ACDE97D0289 Tree

ME ME_4ACDE98E02DA
 MEPROP UID '4ACDE98E02DA'
 MEPROP Name 'Index'
 MEPROP Class class_Attribute
 MELINK Stereotype st_var::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;
 UP "IsResult" False

ENDME // ME_4ACDE98E02DA Index

FORWARD ME_4ACDE6E9028A

ME ME_4ACDE6ED0177
 MEPROP Name 'aFilterType'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_490200F300DD' '4A6854C70390.ms.model.script' // TnsFilterType
 ;

ENDME // ME_4ACDE6ED0177 aFilterType

ME ME_4ACDE6E9028A
 MEPROP UID '4ACDE6E9028A'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 MELIST Parameters
   Seq: ( ME_4ACDE6ED0177 // aFilterType
 )
 ; // Parameters

ENDME // ME_4ACDE6E9028A DoIt

ME ME_4ACDED460185
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 MELINK Target WL? 'ME_47877EB202FB' // SysUtils
 ;

ENDME // ME_4ACDED460185 

ME ME_4ACDED720066
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 MELINK Target WL? 'ME_47F260EC02C7' // StdRes
 ;

ENDME // ME_4ACDED720066 

ME ME_4ACDEFD90017
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 MELINK Target WL 'ME_4908462903E0' '49083E150027.ms.model.script' // TnscContextFilterState
 ;

ENDME // ME_4ACDEFD90017 

ME ME_4ACDF01C011C
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4ACDE6BF0255 // SetFilter
 ;
 MELINK Target WL? 'ME_47878E0E0191' // l3String
 ;

ENDME // ME_4ACDF01C011C 

ME ME_4ACDE6BF0255
 MEPROP UID '4ACDE6BF0255'
 MEPROP Name 'SetFilter'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Накладывает фильтр на дерево' ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Attributes
   Seq: ( HWL ME_4ACDE95E00EE // Filters
 HWL ME_4ACDE97D0289 // Tree
 HWL ME_4ACDE98E02DA // Index
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_4ACDE6E9028A // DoIt
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_4ACDED460185 // SysUtils
 ME_4ACDED720066 // StdRes
 ME_4ACDEFD90017 // TnscContextFilterState
 ME_4ACDF01C011C // l3String
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames

ENDME // ME_4ACDE6BF0255 SetFilter

FORWARD ME_4ACDF3B90238

ME ME_4ACDF3CD0189
 MEPROP UID '4ACDF3CD0189'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 %SUMMARY 'Аналог проверки TefTreeAttributeSelectUT(UserType) <> astNone, только с учётом astTaxesPublishSearch' ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4ACDF3B90238 // IsOldSchoolNone
 ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4ACDF3CD0189 DoIt

ME ME_4ACDF3B90238
 MEPROP UID '4ACDF3B90238'
 MEPROP Name 'IsOldSchoolNone'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Аналог проверки TefTreeAttributeSelectUT(UserType) <> astNone, только с учётом astTaxesPublishSearch' ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_4ACDF3CD0189 // DoIt
 )
 ; // Operations

ENDME // ME_4ACDF3B90238 IsOldSchoolNone

FORWARD ME_4F88602F0276

FORWARD ME_4F8860400108

ME ME_4F88605A039E
 MEPROP Name 'aControl'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_479878FA0103' '478CF30500C1.ms.model.script' // TComponent
 ;

ENDME // ME_4F88605A039E aControl

ME ME_4F88605B0006
 MEPROP Name 'aX'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_4F88605B0006 aX

ME ME_4F88605B0053
 MEPROP Name 'aY'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_4F88605B0053 aY

ME ME_4F88605B0093
 MEPROP Name 'theTarget'
 MEPROP Class class_Parameter
 MELINK Stereotype st_out ;
 MELINK Target WL 'ME_46A451250363' '4807744200AA.ms.model.script' // IUnknown
 ;

ENDME // ME_4F88605B0093 theTarget

ME ME_4F8860400108
 MEPROP UID '4F8860400108'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_4F88602F0276 // EntitiesenAttributeGetTarget
 ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 MELIST Parameters
   Seq: ( ME_4F88605A039E // aControl
 ME_4F88605B0006 // aX
 ME_4F88605B0053 // aY
 ME_4F88605B0093 // theTarget
 )
 ; // Parameters

ENDME // ME_4F8860400108 DoIt

%%ImplementedBy ME_4AEAEAB60182 ME_4F88602F0276

ME ME_4F88602F0276
 MEPROP UID '4F88602F0276'
 MEPROP Name 'EntitiesenAttributeGetTarget'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Implements
   Seq: ( WL 'ME_4AEAEAB60182' '4AE831B30019.ms.model.script' // Attribute
 )
 ; // Implements
 MELIST Operations
   Seq: ( HWL ME_4F8860400108 // DoIt
 )
 ; // Operations

ENDME // ME_4F88602F0276 EntitiesenAttributeGetTarget

%%InheritedBy ME_47881B22005A ME_52774A9A001E

ME ME_52774A9A001E
 MEPROP UID '52774A9A001E'
 MEPROP Name 'ContextFilterChange'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( WL 'ME_47881B22005A' '478CF30500C1.ms.model.script' // TNotifyEvent
 )
 ; // Inherits

ENDME // ME_52774A9A001E ContextFilterChange

%%InheritedBy ME_47881B22005A ME_52774AA6031C

ME ME_52774AA6031C
 MEPROP UID '52774AA6031C'
 MEPROP Name 'ContextFilterWrongContext'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( WL 'ME_47881B22005A' '478CF30500C1.ms.model.script' // TNotifyEvent
 )
 ; // Inherits

ENDME // ME_52774AA6031C ContextFilterWrongContext

%%InheritedBy ME_514B3AD903AA ME_52774AB301C7

ME ME_52774AB301C7
 MEPROP UID '52774AB301C7'
 MEPROP Name 'AttributeTreeIsCommandProcessed'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( WL 'ME_514B3AD903AA' '4CFFE3470249.ms.model.script' // TCommandProcessedEvent
 )
 ; // Inherits

ENDME // ME_52774AB301C7 AttributeTreeIsCommandProcessed

%%InheritedBy ME_47881B22005A ME_52774ABF000B

ME ME_52774ABF000B
 MEPROP UID '52774ABF000B'
 MEPROP Name 'AttributeTreeAfterFirstPaint'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( WL 'ME_47881B22005A' '478CF30500C1.ms.model.script' // TNotifyEvent
 )
 ; // Inherits

ENDME // ME_52774ABF000B AttributeTreeAfterFirstPaint

%%InheritedBy ME_515183DD03C3 ME_52774ACB00D3

ME ME_52774ACB00D3
 MEPROP UID '52774ACB00D3'
 MEPROP Name 'AttributeTreeLMouseDown'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( WL 'ME_515183DD03C3' '47E11FC3021E.ms.model.script' // TMouseEvent
 )
 ; // Inherits

ENDME // ME_52774ACB00D3 AttributeTreeLMouseDown

%%InheritedBy ME_47D63B6D0157 ME_52774AD4024A

ME ME_52774AD4024A
 MEPROP UID '52774AD4024A'
 MEPROP Name 'AttributeTreeGetItemImage'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( WL 'ME_47D63B6D0157' '47D036150077.ms.model.script' // Tl3GetItemImage
 )
 ; // Inherits

ENDME // ME_52774AD4024A AttributeTreeGetItemImage

%%InheritedBy ME_51432026033F ME_52774AF002C7

ME ME_52774AF002C7
 MEPROP UID '52774AF002C7'
 MEPROP Name 'AttributeTreeActionElement'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( WL 'ME_51432026033F' '4CFFE3470249.ms.model.script' // TActionElement
 )
 ; // Inherits

ENDME // ME_52774AF002C7 AttributeTreeActionElement

%%InheritedBy ME_4A9D4FB0034A ME_52774AF800AF

ME ME_52774AF800AF
 MEPROP UID '52774AF800AF'
 MEPROP Name 'AttributeTreeCurrentChanged'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4A9D4FB0034A' '494B949E022B.ms.model.script' // TeeCurrentChanged
 )
 ; // Inherits

ENDME // ME_52774AF800AF AttributeTreeCurrentChanged

%%InheritedBy ME_5146EBE00019 ME_52774B01032D

ME ME_52774B01032D
 MEPROP UID '52774B01032D'
 MEPROP Name 'AttributeTreeTreeChanged'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( WL 'ME_5146EBE00019' '515DA5860015.ms.model.script' // TvtTreeChangedEvent
 )
 ; // Inherits

ENDME // ME_52774B01032D AttributeTreeTreeChanged

%%InheritedBy ME_5143230F01E4 ME_52774B080270

ME ME_52774B080270
 MEPROP UID '52774B080270'
 MEPROP Name 'AttributeTreeNewCharPressed'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Inherits
   Seq: ( WL 'ME_5143230F01E4' '494B949E022B.ms.model.script' // TeeNewCharPressed
 )
 ; // Inherits

ENDME // ME_52774B080270 AttributeTreeNewCharPressed

ME ME_52775595015F
 MEPROP UID '52775595015F'
 MEPROP Name 'SendContextChangeMessage'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;

ENDME // ME_52775595015F SendContextChangeMessage

FORWARD ME_527756DF00E1

FORWARD ME_527756E30339

ME ME_527756E701B6
 MEPROP Name 'aTree'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46825CC00249' '4682595B0268.ms.model.script' // Il3SimpleTree
 ;

ENDME // ME_527756E701B6 aTree

ME ME_527756E30339
 MEPROP UID '527756E30339'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_527756DF00E1 // SetupNewTreeStruct
 ;
 MELIST Parameters
   Seq: ( ME_527756E701B6 // aTree
 )
 ; // Parameters

ENDME // ME_527756E30339 DoIt

ME ME_527756DF00E1
 MEPROP UID '527756DF00E1'
 MEPROP Name 'SetupNewTreeStruct'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_527756E30339 // DoIt
 )
 ; // Operations

ENDME // ME_527756DF00E1 SetupNewTreeStruct

FORWARD ME_52775711033A

FORWARD ME_527757160296

ME ME_5277571D019F
 MEPROP Name 'aNode'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_468259900322' '4682595B0268.ms.model.script' // Il3SimpleNode
 ;

ENDME // ME_5277571D019F aNode

ME ME_5277571D01BC
 MEPROP Name 'aExpand'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 MEPROP Value False
 MELINK ValueType WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 UP extprop:pas:Value False

ENDME // ME_5277571D01BC aExpand

ME ME_527757160296
 MEPROP UID '527757160296'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_52775711033A // SetCurrentNode
 ;
 MELIST Parameters
   Seq: ( ME_5277571D019F // aNode
 ME_5277571D01BC // aExpand
 )
 ; // Parameters

ENDME // ME_527757160296 DoIt

ME ME_52775711033A
 MEPROP UID '52775711033A'
 MEPROP Name 'SetCurrentNode'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_527757160296 // DoIt
 )
 ; // Operations

ENDME // ME_52775711033A SetCurrentNode

FORWARD ME_52775732027C

FORWARD ME_527757370293

ME ME_5277573B030C
 MEPROP Name 'aDropSelection'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 MEPROP Value False
 MELINK ValueType WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 UP extprop:pas:Value False

ENDME // ME_5277573B030C aDropSelection

ME ME_527757370293
 MEPROP UID '527757370293'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_52775732027C // DropAllLogicSelection
 ;
 MELIST Parameters
   Seq: ( ME_5277573B030C // aDropSelection
 )
 ; // Parameters

ENDME // ME_527757370293 DoIt

ME ME_52775732027C
 MEPROP UID '52775732027C'
 MEPROP Name 'DropAllLogicSelection'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_527757370293 // DoIt
 )
 ; // Operations

ENDME // ME_52775732027C DropAllLogicSelection

ME ME_52775768034C
 MEPROP UID '52775768034C'
 MEPROP Name 'NotifyMultipleChanges'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;

ENDME // ME_52775768034C NotifyMultipleChanges

FORWARD ME_52775777039C

FORWARD ME_5277577C0291

ME ME_52775780037A
 MEPROP Name 'aQuery'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEE145027B' '45EEAA8E034E.ms.model.script' // Query
 ;

ENDME // ME_52775780037A aQuery

ME ME_5277577C0291
 MEPROP UID '5277577C0291'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_52775777039C // SaveToQuery
 ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 MELIST Parameters
   Seq: ( ME_52775780037A // aQuery
 )
 ; // Parameters

ENDME // ME_5277577C0291 DoIt

ME ME_52775777039C
 MEPROP UID '52775777039C'
 MEPROP Name 'SaveToQuery'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_5277577C0291 // DoIt
 )
 ; // Operations

ENDME // ME_52775777039C SaveToQuery

FORWARD ME_5277579C0100

FORWARD ME_527757A502A9

ME ME_527757AA03B9
 MEPROP Name 'anIndex'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_527757AA03B9 anIndex

ME ME_527757AA03D6
 MEPROP Name 'LogicOperationOnly'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 MEPROP Value False
 MELINK ValueType WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 UP extprop:pas:Value False

ENDME // ME_527757AA03D6 LogicOperationOnly

ME ME_527757A502A9
 MEPROP UID '527757A502A9'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5277579C0100 // ActivateElement
 ;
 MELIST Parameters
   Seq: ( ME_527757AA03B9 // anIndex
 ME_527757AA03D6 // LogicOperationOnly
 )
 ; // Parameters

ENDME // ME_527757A502A9 DoIt

ME ME_5277579C0100
 MEPROP UID '5277579C0100'
 MEPROP Name 'ActivateElement'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_527757A502A9 // DoIt
 )
 ; // Operations

ENDME // ME_5277579C0100 ActivateElement

FORWARD ME_527757CF036E

FORWARD ME_527757D40147

ME ME_527757DA02EE
 MEPROP Name 'aQuery'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEE145027B' '45EEAA8E034E.ms.model.script' // Query
 ;

ENDME // ME_527757DA02EE aQuery

ME ME_527757D40147
 MEPROP UID '527757D40147'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_527757CF036E // LoadFromQuery
 ;
 MELIST Parameters
   Seq: ( ME_527757DA02EE // aQuery
 )
 ; // Parameters

ENDME // ME_527757D40147 DoIt

ME ME_527757CF036E
 MEPROP UID '527757CF036E'
 MEPROP Name 'LoadFromQuery'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_527757D40147 // DoIt
 )
 ; // Operations

ENDME // ME_527757CF036E LoadFromQuery

FORWARD ME_527757EA030A

FORWARD ME_527757EF0123

ME ME_527757F10295
 MEPROP Name 'aSender'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4807745602C8' '4807744200AA.ms.model.script' // TObject
 ;

ENDME // ME_527757F10295 aSender

ME ME_527757EF0123
 MEPROP UID '527757EF0123'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_527757EA030A // DoContextFilterChange
 ;
 MELIST Parameters
   Seq: ( ME_527757F10295 // aSender
 )
 ; // Parameters

ENDME // ME_527757EF0123 DoIt

ME ME_527757EA030A
 MEPROP UID '527757EA030A'
 MEPROP Name 'DoContextFilterChange'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_527757EF0123 // DoIt
 )
 ; // Operations

ENDME // ME_527757EA030A DoContextFilterChange

ME ME_527757FE02EE
 MEPROP UID '527757FE02EE'
 MEPROP Name 'InvalidateOtherTree'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;

ENDME // ME_527757FE02EE InvalidateOtherTree

FORWARD ME_52775827028F

FORWARD ME_5277582B03E4

ME ME_5277582F02D2
 MEPROP Name 'aTag'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_5277582F02D2 aTag

ME ME_5277582B03E4
 MEPROP UID '5277582B03E4'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_52775827028F // SetRootForFullForm
 ;
 MELIST Parameters
   Seq: ( ME_5277582F02D2 // aTag
 )
 ; // Parameters

ENDME // ME_5277582B03E4 DoIt

ME ME_52775827028F
 MEPROP UID '52775827028F'
 MEPROP Name 'SetRootForFullForm'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_5277582B03E4 // DoIt
 )
 ; // Operations

ENDME // ME_52775827028F SetRootForFullForm

FORWARD ME_5277584002E5

FORWARD ME_5277584403BF

ME ME_527758480202
 MEPROP Name 'aTag'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_527758480202 aTag

ME ME_5277584403BF
 MEPROP UID '5277584403BF'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5277584002E5 // SetRootForFirstLevelForm
 ;
 MELIST Parameters
   Seq: ( ME_527758480202 // aTag
 )
 ; // Parameters

ENDME // ME_5277584403BF DoIt

ME ME_5277584002E5
 MEPROP UID '5277584002E5'
 MEPROP Name 'SetRootForFirstLevelForm'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_5277584403BF // DoIt
 )
 ; // Operations

ENDME // ME_5277584002E5 SetRootForFirstLevelForm

FORWARD ME_5277585E00BE

ME ME_5277586202AE
 MEPROP UID '5277586202AE'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5277585E00BE // GetRootInfo
 ;
 MELINK Target WL 'ME_4909E0980010' '47ECAAF901F8.ms.model.script' // InsRootInfo
 ;

ENDME // ME_5277586202AE DoIt

ME ME_5277585E00BE
 MEPROP UID '5277585E00BE'
 MEPROP Name 'GetRootInfo'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_5277586202AE // DoIt
 )
 ; // Operations

ENDME // ME_5277585E00BE GetRootInfo

FORWARD ME_527758940054

FORWARD ME_527758A20048

ME ME_527758A90134
 MEPROP Name 'aNode'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB95901C5' '457450470167.ms.model.script' // NodeBase
 ;

ENDME // ME_527758A90134 aNode

ME ME_527758A90151
 MEPROP Name 'aOldOp'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_49006BB201CB' '4990510C0026.ms.model.script' // TLogicOperation
 ;

ENDME // ME_527758A90151 aOldOp

ME ME_527758A9016F
 MEPROP Name 'aNewOp'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_49006BB201CB' '4990510C0026.ms.model.script' // TLogicOperation
 ;

ENDME // ME_527758A9016F aNewOp

ME ME_527758A20048
 MEPROP UID '527758A20048'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_527758940054 // NotifyOperationChange
 ;
 MELIST Parameters
   Seq: ( ME_527758A90134 // aNode
 ME_527758A90151 // aOldOp
 ME_527758A9016F // aNewOp
 )
 ; // Parameters

ENDME // ME_527758A20048 DoIt

ME ME_527758940054
 MEPROP UID '527758940054'
 MEPROP Name 'NotifyOperationChange'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_527758A20048 // DoIt
 )
 ; // Operations

ENDME // ME_527758940054 NotifyOperationChange

FORWARD ME_527758E80127

FORWARD ME_527758EC0393

ME ME_527758F50053
 MEPROP Name 'aNode'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB95901C5' '457450470167.ms.model.script' // NodeBase
 ;

ENDME // ME_527758F50053 aNode

ME ME_527758F50071
 MEPROP Name 'aOp'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_49006BB201CB' '4990510C0026.ms.model.script' // TLogicOperation
 ;

ENDME // ME_527758F50071 aOp

ME ME_527758F5008F
 MEPROP Name 'aWithNotify'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 MEPROP Value True
 MELINK ValueType WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 UP extprop:pas:Value True

ENDME // ME_527758F5008F aWithNotify

ME ME_527758EC0393
 MEPROP UID '527758EC0393'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_527758E80127 // FormLogicOperation
 ;
 MELIST Parameters
   Seq: ( ME_527758F50053 // aNode
 ME_527758F50071 // aOp
 ME_527758F5008F // aWithNotify
 )
 ; // Parameters

ENDME // ME_527758EC0393 DoIt

ME ME_527758E80127
 MEPROP UID '527758E80127'
 MEPROP Name 'FormLogicOperation'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_527758EC0393 // DoIt
 )
 ; // Operations

ENDME // ME_527758E80127 FormLogicOperation

ME ME_5277590003E1
 MEPROP UID '5277590003E1'
 MEPROP Name 'DropSelectedOperation'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;

ENDME // ME_5277590003E1 DropSelectedOperation

FORWARD ME_527759200129

FORWARD ME_52775924023E

ME ME_52775926033A
 MEPROP Name 'aNewOp'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_49006BB201CB' '4990510C0026.ms.model.script' // TLogicOperation
 ;

ENDME // ME_52775926033A aNewOp

ME ME_52775924023E
 MEPROP UID '52775924023E'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_527759200129 // ChangeOperationOnSelected
 ;
 MELIST Parameters
   Seq: ( ME_52775926033A // aNewOp
 )
 ; // Parameters

ENDME // ME_52775924023E DoIt

ME ME_527759200129
 MEPROP UID '527759200129'
 MEPROP Name 'ChangeOperationOnSelected'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_52775924023E // DoIt
 )
 ; // Operations

ENDME // ME_527759200129 ChangeOperationOnSelected

FORWARD ME_527759B902F8

FORWARD ME_527759BF0124

ME ME_527759C8006B
 MEPROP Name 'aNewIndex'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_527759C8006B aNewIndex

ME ME_527759C80088
 MEPROP Name 'aOldIndex'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_527759C80088 aOldIndex

ME ME_527759C800A5
 MEPROP Name 'aForceUpdateParent'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 MEPROP Value False
 MELINK ValueType WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;
 UP extprop:pas:Value False

ENDME // ME_527759C800A5 aForceUpdateParent

ME ME_527759BF0124
 MEPROP UID '527759BF0124'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_527759B902F8 // CurrentChangedPrim
 ;
 MELIST Parameters
   Seq: ( ME_527759C8006B // aNewIndex
 ME_527759C80088 // aOldIndex
 ME_527759C800A5 // aForceUpdateParent
 )
 ; // Parameters

ENDME // ME_527759BF0124 DoIt

ME ME_527759B902F8
 MEPROP UID '527759B902F8'
 MEPROP Name 'CurrentChangedPrim'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_527759BF0124 // DoIt
 )
 ; // Operations

ENDME // ME_527759B902F8 CurrentChangedPrim

FORWARD ME_527759E3016D

FORWARD ME_527759E8036C

ME ME_527759EC0385
 MEPROP Name 'aNode'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB95901C5' '457450470167.ms.model.script' // NodeBase
 ;

ENDME // ME_527759EC0385 aNode

ME ME_527759E8036C
 MEPROP UID '527759E8036C'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_527759E3016D // SetLogicOperationOnNode
 ;
 MELIST Parameters
   Seq: ( ME_527759EC0385 // aNode
 )
 ; // Parameters

ENDME // ME_527759E8036C DoIt

ME ME_527759E3016D
 MEPROP UID '527759E3016D'
 MEPROP Name 'SetLogicOperationOnNode'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_527759E8036C // DoIt
 )
 ; // Operations

ENDME // ME_527759E3016D SetLogicOperationOnNode

FORWARD ME_52775A88036E

FORWARD ME_52775A8D0147

ME ME_52775A930138
 MEPROP Name 'aParams'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4683E07E004B' '467BAB7F021E.ms.model.script' // IvcmTestParamsPrim
 ;

ENDME // ME_52775A930138 aParams

ME ME_52775A930156
 MEPROP Name 'aOp'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_49006BB201CB' '4990510C0026.ms.model.script' // TLogicOperation
 ;

ENDME // ME_52775A930156 aOp

ME ME_52775A8D0147
 MEPROP UID '52775A8D0147'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_52775A88036E // LogicOperationTest
 ;
 MELIST Parameters
   Seq: ( ME_52775A930138 // aParams
 ME_52775A930156 // aOp
 )
 ; // Parameters

ENDME // ME_52775A8D0147 DoIt

ME ME_52775A88036E
 MEPROP UID '52775A88036E'
 MEPROP Name 'LogicOperationTest'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_52775A8D0147 // DoIt
 )
 ; // Operations

ENDME // ME_52775A88036E LogicOperationTest

FORWARD ME_52775B27001A

FORWARD ME_52775B50023F

ME ME_52775B5500FB
 MEPROP Name 'aNode'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_468259900322' '4682595B0268.ms.model.script' // Il3SimpleNode
 ;

ENDME // ME_52775B5500FB aNode

ME ME_52775B50023F
 MEPROP UID '52775B50023F'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_52775B27001A // GetFirstLevelParent$1
 ;
 MELINK Target WL 'ME_468259900322' '4682595B0268.ms.model.script' // Il3SimpleNode
 ;
 MELIST Parameters
   Seq: ( ME_52775B5500FB // aNode
 )
 ; // Parameters

ENDME // ME_52775B50023F DoIt

ME ME_52775B27001A
 MEPROP UID '52775B27001A'
 MEPROP Name 'GetFirstLevelParent'
 MEPROP OriginalName 'GetFirstLevelParent$1'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_52775B50023F // DoIt
 )
 ; // Operations

ENDME // ME_52775B27001A GetFirstLevelParent$1

FORWARD ME_52775B3700D4

FORWARD ME_52775B6101AE

ME ME_52775B66007B
 MEPROP Name 'aNode'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB95901C5' '457450470167.ms.model.script' // NodeBase
 ;

ENDME // ME_52775B66007B aNode

ME ME_52775B6101AE
 MEPROP UID '52775B6101AE'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_52775B3700D4 // GetFirstLevelParent$2
 ;
 MELINK Target WL 'ME_45EEB95901C5' '457450470167.ms.model.script' // NodeBase
 ;
 MELIST Parameters
   Seq: ( ME_52775B66007B // aNode
 )
 ; // Parameters

ENDME // ME_52775B6101AE DoIt

ME ME_52775B3700D4
 MEPROP UID '52775B3700D4'
 MEPROP Name 'GetFirstLevelParent'
 MEPROP OriginalName 'GetFirstLevelParent$2'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_52775B6101AE // DoIt
 )
 ; // Operations

ENDME // ME_52775B3700D4 GetFirstLevelParent$2

FORWARD ME_52775B3F025E

FORWARD ME_52775B740230

ME ME_52775B7703CC
 MEPROP Name 'aIndex'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_52775B7703CC aIndex

ME ME_52775B740230
 MEPROP UID '52775B740230'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_52775B3F025E // GetFirstLevelParent$3
 ;
 MELINK Target WL 'ME_468259900322' '4682595B0268.ms.model.script' // Il3SimpleNode
 ;
 MELIST Parameters
   Seq: ( ME_52775B7703CC // aIndex
 )
 ; // Parameters

ENDME // ME_52775B740230 DoIt

ME ME_52775B3F025E
 MEPROP UID '52775B3F025E'
 MEPROP Name 'GetFirstLevelParent'
 MEPROP OriginalName 'GetFirstLevelParent$3'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_52775B740230 // DoIt
 )
 ; // Operations

ENDME // ME_52775B3F025E GetFirstLevelParent$3

FORWARD ME_52775B9402B2

FORWARD ME_52775BBA0271

ME ME_52775BBD013D
 MEPROP Name 'aParams'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4683E07E004B' '467BAB7F021E.ms.model.script' // IvcmTestParamsPrim
 ;

ENDME // ME_52775BBD013D aParams

ME ME_52775BBD015A
 MEPROP Name 'aLO'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_49006BB201CB' '4990510C0026.ms.model.script' // TLogicOperation
 ;

ENDME // ME_52775BBD015A aLO

ME ME_52775BBA0271
 MEPROP UID '52775BBA0271'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_52775B9402B2 // LOToolbarTest
 ;
 MELIST Parameters
   Seq: ( ME_52775BBD013D // aParams
 ME_52775BBD015A // aLO
 )
 ; // Parameters

ENDME // ME_52775BBA0271 DoIt

ME ME_52775B9402B2
 MEPROP UID '52775B9402B2'
 MEPROP Name 'LOToolbarTest'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'метод установки параметров в _OnTest для операций публикуемых в toolbar-е. Отличие в том, что они не показываются для ситуаций первого второго уровня.'#13#10''#13#10'Отключено при переносе на модель.'#13#10'Решили, что нет нужды делать разную логику для тулбаров и контекстного меню.' ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_52775BBA0271 // DoIt
 )
 ; // Operations
 UP "ifdef" 'disabled_function'

ENDME // ME_52775B9402B2 LOToolbarTest

FORWARD ME_52777B680276

FORWARD ME_52777B6F0231

ME ME_52777B7A01B8
 MEPROP Name 'aNode'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_45EEB95901C5' '457450470167.ms.model.script' // NodeBase
 ;

ENDME // ME_52777B7A01B8 aNode

ME ME_52777B6F0231
 MEPROP UID '52777B6F0231'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_52777B680276 // CountItemImage
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;
 MELIST Parameters
   Seq: ( ME_52777B7A01B8 // aNode
 )
 ; // Parameters

ENDME // ME_52777B6F0231 DoIt

ME ME_52777B680276
 MEPROP UID '52777B680276'
 MEPROP Name 'CountItemImage'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_52777B6F0231 // DoIt
 )
 ; // Operations

ENDME // ME_52777B680276 CountItemImage

FORWARD ME_5279F70F0146

FORWARD ME_5279F71E022A

ME ME_5279F7240380
 MEPROP Name 'aState'
 MEPROP Class class_Parameter
 MELINK Stereotype st_out ;
 MELINK Target WL 'ME_4992FC0C02CA' '4683F37902CF.ms.model.script' // IvcmBase
 ;

ENDME // ME_5279F7240380 aState

ME ME_5279F724039D
 MEPROP Name 'aStateType'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4683CBFD032D' '467BAB7F021E.ms.model.script' // TvcmStateType
 ;

ENDME // ME_5279F724039D aStateType

ME ME_5279F72403BA
 MEPROP Name 'Saved'
 MEPROP Class class_Parameter
 MELINK Stereotype st_inout ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_5279F72403BA Saved

ME ME_5279F71E022A
 MEPROP UID '5279F71E022A'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5279F70F0146 // vcmEntityFormSaveState
 ;
 MELIST Parameters
   Seq: ( ME_5279F7240380 // aState
 ME_5279F724039D // aStateType
 ME_5279F72403BA // Saved
 )
 ; // Parameters

ENDME // ME_5279F71E022A DoIt

ME ME_5279F70F0146
 MEPROP UID '5279F70F0146'
 MEPROP Name 'vcmEntityFormSaveState'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELIST Operations
   Seq: ( HWL ME_5279F71E022A // DoIt
 )
 ; // Operations
 UP extprop:rc:SelfName 'EntityFormSaveState'

ENDME // ME_5279F70F0146 vcmEntityFormSaveState

ME ME_4AE8329D00E8
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_47878E0E0191' // l3String
 ;

ENDME // ME_4AE8329D00E8 

ME ME_4AE87B5E0017
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_45EEB95901C5' '457450470167.ms.model.script' // NodeBase
 ;

ENDME // ME_4AE87B5E0017 

ME ME_4AE87B6F0149
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_47877EB202FB' // SysUtils
 ;

ENDME // ME_4AE87B6F0149 

ME ME_4AE87BE100E5
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_49243E5C035C' // nsLogicOperationToFlags
 ;

ENDME // ME_4AE87BE100E5 

ME ME_4AEF3C110257
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_49006BB201CB' '4990510C0026.ms.model.script' // TLogicOperation
 ;

ENDME // ME_4AEF3C110257 

ME ME_4AF2CFA20339
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4AEF128901C3' '4AE831B30019.ms.model.script' // AttributeTree
 ;

ENDME // ME_4AF2CFA20339 

ME ME_4AF3FF040124
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4804BDA10127' '47E246C90144.ms.model.script' // Tl3Tree
 ;

ENDME // ME_4AF3FF040124 

ME ME_4AF4001A010E
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4909E1DD038F' '49006FAB024A.ms.model.script' // TnsAttrBranchStruct
 ;

ENDME // ME_4AF4001A010E 

ME ME_4AF4004001EF
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4AA7888B0076' '4773D64E036C.ms.model.script' // l3CStr
 ;

ENDME // ME_4AF4004001EF 

ME ME_4AF41A860358
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4AF4007401DC' '4AE831B30019.ms.model.script' // ContextParams
 ;

ENDME // ME_4AF41A860358 

ME ME_4C2B1C5C028F
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_468259900322' '4682595B0268.ms.model.script' // Il3SimpleNode
 ;

ENDME // ME_4C2B1C5C028F 

ME ME_4C2B20EA0000
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4C2B202402C3' '490C47C70210.ms.model.script' // nsSetCurrentFirstSelected
 ;

ENDME // ME_4C2B20EA0000 

ME ME_52774B6402A8
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_47E11FC3021E' // Controls
 ;

ENDME // ME_52774B6402A8 

ME ME_52774B670274
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_47E13C6B0341' // Forms
 ;

ENDME // ME_52774B670274 

ME ME_52777BBA01CC
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_48D2191902CB' '48D21909003A.ms.model.script' // ActionCodes
 ;

ENDME // ME_52777BBA01CC 

ME ME_52777BE10316
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_484D2CBA0213' '484A470100DD.ms.model.script' // TextStyle
 ;

ENDME // ME_52777BE10316 

ME ME_52778101030A
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4AE58E7C00A4' '4AA005310028.ms.model.script' // TnsSelectedAttributesIterators
 ;

ENDME // ME_52778101030A 

ME ME_5277812100F8
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_4AF4111F0184' // nsTreeAttributeNodesNew
 ;

ENDME // ME_5277812100F8 

ME ME_527781D40228
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_468364C70131' '49006FAB024A.ms.model.script' // TnsAttributeTreeStruct
 ;

ENDME // ME_527781D40228 

ME ME_527789210166
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_492440D20009' // nsValueMaps
 ;

ENDME // ME_527789210166 

ME ME_52778924011E
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_4924422E0249' // nsValueMapsIDs
 ;

ENDME // ME_52778924011E 

ME ME_5277895B03CE
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4909DC950238' '49006FAB024A.ms.model.script' // TnsFirstLevelStruct
 ;

ENDME // ME_5277895B03CE 

ME ME_527789720154
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_47F25BC801DB' // vcmBase
 ;

ENDME // ME_527789720154 

ME ME_5277898A003A
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_4EC391C00307' // SearchRes
 ;

ENDME // ME_5277898A003A 

ME ME_527789A502ED
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_492437620004' // TdsTreeAttributeSelect
 ;

ENDME // ME_527789A502ED 

ME ME_527789BB034F
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4AE593970016' '4AA005310028.ms.model.script' // TdeSearch
 ;

ENDME // ME_527789BB034F 

ME ME_527789E50119
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_4AE8A02C03E7' // nsQuery
 ;

ENDME // ME_527789E50119 

ME ME_527789FA02D4
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_48FF556602BA' // DataAdapter
 ;

ENDME // ME_527789FA02D4 

ME ME_52778A98036F
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_523309E20374' '46837A08002C.ms.model.script' // InsQueryContainer
 ;

ENDME // ME_52778A98036F 

ME ME_54B7B47F03D9
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL 'ME_4D80CDFB03A2' '4D80CDE4033D.ms.model.script' // TreeAttributeSelect
 ;

ENDME // ME_54B7B47F03D9 

ME ME_54F835FA0062
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_497ECC0E0325 // PrimTreeAttributeSelect
 ;
 MELINK Target WL? 'ME_54F835DA0012' // tasSaveLoadProxy
 ;

ENDME // ME_54F835FA0062 

ME ME_48FF6D200201_ME_497ECC0E0325
 MELINK Original WL 'ME_48FF6D200201' '47ECAAF901F8.ms.model.script' // Updated
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_48FF6D200201_ME_497ECC0E0325 Updated

ME ME_497465F501B7_ME_497ECC0E0325
 MELINK Original WL 'ME_497465F501B7' '4974652502DA.ms.model.script' // CurrentChangedNotification
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_497465F501B7_ME_497ECC0E0325 CurrentChangedNotification

ME ME_4AE831FA00F9_ME_497ECC0E0325
 MELINK Original WL 'ME_4AE831FA00F9' '4AE831B30019.ms.model.script' // ExternalCharPressed
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AE831FA00F9_ME_497ECC0E0325 ExternalCharPressed

ME ME_4AE8703B02A2_ME_497ECC0E0325
 MELINK Original WL 'ME_4AE8703B02A2' '4AE831B30019.ms.model.script' // SetCurrent
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AE8703B02A2_ME_497ECC0E0325 SetCurrent

ME ME_4AE870DD01D0_ME_497ECC0E0325
 MELINK Original WL 'ME_4AE870DD01D0' '4AE831B30019.ms.model.script' // DropAllLogicSelection
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AE870DD01D0_ME_497ECC0E0325 DropAllLogicSelection

ME ME_4AE879D00143_ME_497ECC0E0325
 MELINK Original WL 'ME_4AE879D00143' '4AE831B30019.ms.model.script' // IsQueryEmpty
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AE879D00143_ME_497ECC0E0325 IsQueryEmpty

ME ME_4AE8913D00A7_ME_497ECC0E0325
 MELINK Original WL 'ME_4AE8913D00A7' '4AE831B30019.ms.model.script' // SaveToQuery
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AE8913D00A7_ME_497ECC0E0325 SaveToQuery

ME ME_4AEAE67802ED_ME_497ECC0E0325
 MELINK Original WL 'ME_4AEAE67802ED' '4AE831B30019.ms.model.script' // Invalidate
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AEAE67802ED_ME_497ECC0E0325 Invalidate

ME ME_4AEAEABF034E_ME_497ECC0E0325
 MELINK Original WL 'ME_4AEAEABF034E' '4AE831B30019.ms.model.script' // DefaultAction
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AEAEABF034E_ME_497ECC0E0325 DefaultAction

ME ME_4AEF213001F0_ME_497ECC0E0325
 MELINK Original WL 'ME_4AEF213001F0' '4AE831B30019.ms.model.script' // SetQuery
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AEF213001F0_ME_497ECC0E0325 SetQuery

ME ME_4AEF38310030_ME_497ECC0E0325
 MELINK Original WL 'ME_4AEF38310030' '4AE831B30019.ms.model.script' // DropLogicSelection
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AEF38310030_ME_497ECC0E0325 DropLogicSelection

ME ME_4AEF3857010A_ME_497ECC0E0325
 MELINK Original WL 'ME_4AEF3857010A' '4AE831B30019.ms.model.script' // LoadQuery
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AEF3857010A_ME_497ECC0E0325 LoadQuery

ME ME_4AEF3871010E_ME_497ECC0E0325
 MELINK Original WL 'ME_4AEF3871010E' '4AE831B30019.ms.model.script' // SetOneLevelCurrent
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AEF3871010E_ME_497ECC0E0325 SetOneLevelCurrent

ME ME_4AEF38920247_ME_497ECC0E0325
 MELINK Original WL 'ME_4AEF38920247' '4AE831B30019.ms.model.script' // SetContext
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AEF38920247_ME_497ECC0E0325 SetContext

ME ME_4AF3EBC001C4_ME_497ECC0E0325
 MELINK Original WL 'ME_4AF3EBC001C4' '4AE831B30019.ms.model.script' // SetRoot
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AF3EBC001C4_ME_497ECC0E0325 SetRoot

ME ME_4AF3FE7D0138_ME_497ECC0E0325
 MELINK Original WL 'ME_4AF3FE7D0138' '4AE831B30019.ms.model.script' // ChangeRoot
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AF3FE7D0138_ME_497ECC0E0325 ChangeRoot

ME ME_4AF40A0E01D3_ME_497ECC0E0325
 MELINK Original WL 'ME_4AF40A0E01D3' '4AE831B30019.ms.model.script' // SyncContextParams
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AF40A0E01D3_ME_497ECC0E0325 SyncContextParams

ME ME_4AF8604B021E_ME_497ECC0E0325
 MELINK Original WL 'ME_4AF8604B021E' '4AE831B30019.ms.model.script' // AddNodeIfEmpty
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AF8604B021E_ME_497ECC0E0325 AddNodeIfEmpty

ME ME_4AF92B09017F_ME_497ECC0E0325
 MELINK Original WL 'ME_4AF92B09017F' '4AE831B30019.ms.model.script' // ClearQuery
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" True
 UP "LongProcess" False
 UP "Needs Broadcast" False
 UP "no prefix" False
ENDME // ME_4AF92B09017F_ME_497ECC0E0325 ClearQuery

ME ME_4C2B1B9100B5_ME_497ECC0E0325
 MELINK Original WL 'ME_4C2B1B9100B5' '4AE831B30019.ms.model.script' // FindFirstSelected
 ;
 MEPROP OpKind opkind_Implemented
 UP "AutoFocus" False
 UP "AutoLock" False
 UP "has states" False
 UP "is FormActivate" False
 UP "is query" False
 UP "LongProcess" False
 UP "no prefix" False
 UP "ShowInContextMenu" True
 UP "ShowInToolbar" False
ENDME // ME_4C2B1B9100B5_ME_497ECC0E0325 FindFirstSelected

ME ME_479731C50290_ME_497ECC0E0325
 MELINK Original WL 'ME_479731C50290' '51612ED700B4.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_497ECC0E0325 Cleanup

ME ME_47A042E100E2_ME_497ECC0E0325
 MELINK Original WL 'ME_47A042E100E2' '47913F4E02E0.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_497ECC0E0325 InitFields

ME ME_497469C90140_ME_497ECC0E0325
 MELINK Original WL 'ME_497469C90140' '500004240202.ms.model.script' // NotifyDataSourceChanged
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_497469C90140_ME_497ECC0E0325 NotifyDataSourceChanged

ME ME_49807428008C_ME_497ECC0E0325
 MELINK Original WL 'ME_49807428008C' '4AADF9450143.ms.model.script' // DoLoadState
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_49807428008C_ME_497ECC0E0325 DoLoadState

ME ME_4A8E8F2E0195_ME_497ECC0E0325
 MELINK Original WL 'ME_4A8E8F2E0195' '500004240202.ms.model.script' // InitControls
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_4A8E8F2E0195_ME_497ECC0E0325 InitControls

ME ME_4D78E2BB0211_ME_497ECC0E0325
 MELINK Original WL 'ME_4D78E2BB0211' '4AADF9450143.ms.model.script' // NotifyUserTypeSet
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_4D78E2BB0211_ME_497ECC0E0325 NotifyUserTypeSet

%%ImplementedBy ME_48FF6D050234 ME_497ECC0E0325
%%ImplementedBy ME_4AE831E70016 ME_497ECC0E0325
%%ImplementedBy ME_4AE879C5022F ME_497ECC0E0325
%%ImplementedBy ME_4AE8912B03B3 ME_497ECC0E0325
%%ImplementedBy ME_4AEAEAB60182 ME_497ECC0E0325
%%ImplementedBy ME_4AEF388A0016 ME_497ECC0E0325
%%ImplementedBy ME_4AF3EB1C03A9 ME_497ECC0E0325
%%ImplementedBy ME_4AF3FE6B0386 ME_497ECC0E0325
%%ImplementedBy ME_4C2B1B8003E4 ME_497ECC0E0325

%%InheritedBy ME_4974652502DA ME_497ECC0E0325

ME ME_497ECC0E0325
 MEPROP UID '497ECC0E0325'
 MEPROP Name 'PrimTreeAttributeSelect'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_VCMForm ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent WL? 'ME_4A85282C0252' // LiteSearch
 ;
 MELIST Inherits
   Seq: ( WL? 'ME_4974652502DA' // TreeAttribute
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_48FF6D050234' '47ECAAF901F8.ms.model.script' // InsTreeDataListener
 WL 'ME_4AE831E70016' '4AE831B30019.ms.model.script' // AttributeTree$Select
 WL 'ME_4AE879C5022F' '4AE831B30019.ms.model.script' // SearchParameters
 WL 'ME_4AE8912B03B3' '4AE831B30019.ms.model.script' // AttributeTree$SaveToQuery
 WL 'ME_4AEAEAB60182' '4AE831B30019.ms.model.script' // Attribute
 WL 'ME_4AEF388A0016' '4AE831B30019.ms.model.script' // Context
 WL 'ME_4AF3EB1C03A9' '4AE831B30019.ms.model.script' // AttributeTree$SetRoot
 WL 'ME_4AF3FE6B0386' '4AE831B30019.ms.model.script' // AttributeTree$ChangeRoot
 WL 'ME_4C2B1B8003E4' '4AE831B30019.ms.model.script' // Folder
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_527746CF030B // BackgroundPanel
 HWL ME_497ECC8E0036 // dsTreeAttributeSelect
 HWL ME_4AEF38D40105 // f_NeedRefilterTree
 HWL ME_52774DA600FD // DS
 HWL ME_52774DDF02AF // TaggedTreeInfo
 HWL ME_52774E0A018E // RootInfo
 HWL ME_5277509B008E // f_OrState
 HWL ME_527750A60194 // f_AndState
 HWL ME_527750AE0202 // f_NotState
 HWL ME_5277512702E8 // f_CaptionMap
 HWL ME_527751400121 // f_Painted
 HWL ME_52777F37036D // f_LockCurrentChange
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_4ACDE6BF0255 // SetFilter
 HWL ME_4ACDF3B90238 // IsOldSchoolNone
 HWL ME_4F88602F0276 // EntitiesenAttributeGetTarget
 HWL ME_52774A9A001E // ContextFilterChange
 HWL ME_52774AA6031C // ContextFilterWrongContext
 HWL ME_52774AB301C7 // AttributeTreeIsCommandProcessed
 HWL ME_52774ABF000B // AttributeTreeAfterFirstPaint
 HWL ME_52774ACB00D3 // AttributeTreeLMouseDown
 HWL ME_52774AD4024A // AttributeTreeGetItemImage
 HWL ME_52774AF002C7 // AttributeTreeActionElement
 HWL ME_52774AF800AF // AttributeTreeCurrentChanged
 HWL ME_52774B01032D // AttributeTreeTreeChanged
 HWL ME_52774B080270 // AttributeTreeNewCharPressed
 HWL ME_52775595015F // SendContextChangeMessage
 HWL ME_527756DF00E1 // SetupNewTreeStruct
 HWL ME_52775711033A // SetCurrentNode
 HWL ME_52775732027C // DropAllLogicSelection
 HWL ME_52775768034C // NotifyMultipleChanges
 HWL ME_52775777039C // SaveToQuery
 HWL ME_5277579C0100 // ActivateElement
 HWL ME_527757CF036E // LoadFromQuery
 HWL ME_527757EA030A // DoContextFilterChange
 HWL ME_527757FE02EE // InvalidateOtherTree
 HWL ME_52775827028F // SetRootForFullForm
 HWL ME_5277584002E5 // SetRootForFirstLevelForm
 HWL ME_5277585E00BE // GetRootInfo
 HWL ME_527758940054 // NotifyOperationChange
 HWL ME_527758E80127 // FormLogicOperation
 HWL ME_5277590003E1 // DropSelectedOperation
 HWL ME_527759200129 // ChangeOperationOnSelected
 HWL ME_527759B902F8 // CurrentChangedPrim
 HWL ME_527759E3016D // SetLogicOperationOnNode
 HWL ME_52775A88036E // LogicOperationTest
 HWL ME_52775B27001A // GetFirstLevelParent$1
 HWL ME_52775B3700D4 // GetFirstLevelParent$2
 HWL ME_52775B3F025E // GetFirstLevelParent$3
 HWL ME_52775B9402B2 // LOToolbarTest
 HWL ME_52777B680276 // CountItemImage
 HWL ME_5279F70F0146 // vcmEntityFormSaveState
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_48FF6D200201_ME_497ECC0E0325 // Updated
 ME_497465F501B7_ME_497ECC0E0325 // CurrentChangedNotification
 ME_4AE831FA00F9_ME_497ECC0E0325 // ExternalCharPressed
 ME_4AE8703B02A2_ME_497ECC0E0325 // SetCurrent
 ME_4AE870DD01D0_ME_497ECC0E0325 // DropAllLogicSelection
 ME_4AE879D00143_ME_497ECC0E0325 // IsQueryEmpty
 ME_4AE8913D00A7_ME_497ECC0E0325 // SaveToQuery
 ME_4AEAE67802ED_ME_497ECC0E0325 // Invalidate
 ME_4AEAEABF034E_ME_497ECC0E0325 // DefaultAction
 ME_4AEF213001F0_ME_497ECC0E0325 // SetQuery
 ME_4AEF38310030_ME_497ECC0E0325 // DropLogicSelection
 ME_4AEF3857010A_ME_497ECC0E0325 // LoadQuery
 ME_4AEF3871010E_ME_497ECC0E0325 // SetOneLevelCurrent
 ME_4AEF38920247_ME_497ECC0E0325 // SetContext
 ME_4AF3EBC001C4_ME_497ECC0E0325 // SetRoot
 ME_4AF3FE7D0138_ME_497ECC0E0325 // ChangeRoot
 ME_4AF40A0E01D3_ME_497ECC0E0325 // SyncContextParams
 ME_4AF8604B021E_ME_497ECC0E0325 // AddNodeIfEmpty
 ME_4AF92B09017F_ME_497ECC0E0325 // ClearQuery
 ME_4C2B1B9100B5_ME_497ECC0E0325 // FindFirstSelected
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_497ECC0E0325 // Cleanup
 ME_47A042E100E2_ME_497ECC0E0325 // InitFields
 ME_497469C90140_ME_497ECC0E0325 // NotifyDataSourceChanged
 ME_49807428008C_ME_497ECC0E0325 // DoLoadState
 ME_4A8E8F2E0195_ME_497ECC0E0325 // InitControls
 ME_4D78E2BB0211_ME_497ECC0E0325 // NotifyUserTypeSet
 )
 ; // Overridden
 MELIST Children
   Seq: ( HWL ME_4BD6F94500AC // astNone
 HWL ME_4BD6F9540396 // astOneLevel
 HWL ME_4BD6F97301F4 // astFirstLevel
 HWL ME_4BD6F992021A // astTaxesPublishSearch
 HWL ME_4C2B075E0155 // ExcludeExternalCharPressedForOneLevel
 HWL ME_4C2B1BE20259 // ExludeFindFirstSelectedForOneLevel
 HWL ME_53A950A801A6 // astPharmPublishSearch
 )
 ; // Children
 MELIST Dependencies
   Seq: ( ME_4AE8329D00E8 // l3String
 ME_4AE87B5E0017 // NodeBase
 ME_4AE87B6F0149 // SysUtils
 ME_4AE87BE100E5 // nsLogicOperationToFlags
 ME_4AEF3C110257 // TLogicOperation
 ME_4AF2CFA20339 // AttributeTree
 ME_4AF3FF040124 // Tl3Tree
 ME_4AF4001A010E // TnsAttrBranchStruct
 ME_4AF4004001EF // l3CStr
 ME_4AF41A860358 // ContextParams
 ME_4C2B1C5C028F // Il3SimpleNode
 ME_4C2B20EA0000 // nsSetCurrentFirstSelected
 ME_52774B6402A8 // Controls
 ME_52774B670274 // Forms
 ME_52777BBA01CC // ActionCodes
 ME_52777BE10316 // TextStyle
 ME_52778101030A // TnsSelectedAttributesIterators
 ME_5277812100F8 // nsTreeAttributeNodesNew
 ME_527781D40228 // TnsAttributeTreeStruct
 ME_527789210166 // nsValueMaps
 ME_52778924011E // nsValueMapsIDs
 ME_5277895B03CE // TnsFirstLevelStruct
 ME_527789720154 // vcmBase
 ME_5277898A003A // SearchRes
 ME_527789A502ED // TdsTreeAttributeSelect
 ME_527789BB034F // TdeSearch
 ME_527789E50119 // nsQuery
 ME_527789FA02D4 // DataAdapter
 ME_52778A98036F // InsQueryContainer
 ME_54B7B47F03D9 // TreeAttributeSelect
 ME_54F835FA0062 // tasSaveLoadProxy
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "author" 'Люлин А.В.'
 UP "finished dfm" True
 UP "NeedsHackRef" False
 UP "no hands" True
 UP "resizeable" False
 UP "restrict form def" 'undefined'
 UP "started" '27.01.2009 11:56'
 UP "ZoneType" 'Any'
 UP extprop:NeedsInitEntities True
 UP extprop:pas:TypeName 'TPrimTreeAttributeSelectForm'
 UP extprop:pas:UnitName 'PrimTreeAttributeSelect_Form'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'PrimTreeAttributeSelectForm'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms\PrimTreeAttributeSelect_Form.pas'
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View\LiteSearch\Forms'

ENDME // ME_497ECC0E0325 PrimTreeAttributeSelect
