// TurnOnTimeMachine 49805ACC01CF Impurity Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_49805ACC01CF_diagrams

 MEDIAGRAM ME_49805ACC01CF_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_49805ACC01CF' ; // TurnOnTimeMachine

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_49805ACC01CF_main

 MELIST Diagrams
  Seq: ( ME_49805ACC01CF_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_49805ACC01CF_diagrams
