// BaseDocument 49870A7E033E VCMForm Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_49870A7E033E_diagrams

 MEDIAGRAM ME_49870A7E033E_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_49870A7E033E' '49870A7E033E.ms.model.script' ; // BaseDocument

  MEVIEW ME_49870AB400FA_view
   MELINK Original WL 'ME_49870AB400FA' '49870A7E033E.ms.model.script' ; // sdsBaseDocument
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_49870AB400FA_view

  MELIST Views
   Seq: ( ME_49870AB400FA_view // sdsBaseDocument
   )
  ; // Views
 ENDMEDIAGRAM // ME_49870A7E033E_main

 MELIST Diagrams
  Seq: ( ME_49870A7E033E_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_49870A7E033E_diagrams
