// TFoldersNodeDeleteEvent 49901D810061 Enum Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_49901D810061_diagrams

 MEDIAGRAM ME_49901D810061_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_49901D810061' '4990135D02F1.ms.model.script' ; // TFoldersNodeDeleteEvent

  MEVIEW ME_49901D890243_view
   MELINK Original WL 'ME_49901D890243' '4990135D02F1.ms.model.script' ; // fndeNone
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_49901D890243_view

  MEVIEW ME_49901D8F02CE_view
   MELINK Original WL 'ME_49901D8F02CE' '4990135D02F1.ms.model.script' ; // fndeQuery
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_49901D8F02CE_view

  MEVIEW ME_49901D9400DC_view
   MELINK Original WL 'ME_49901D9400DC' '4990135D02F1.ms.model.script' ; // fndeControlled
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_49901D9400DC_view

  MELIST Views
   Seq: ( ME_49901D890243_view // fndeNone
   ME_49901D8F02CE_view // fndeQuery
   ME_49901D9400DC_view // fndeControlled
   )
  ; // Views
 ENDMEDIAGRAM // ME_49901D810061_main

 MELIST Diagrams
  Seq: ( ME_49901D810061_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_49901D810061_diagrams
