// IvcmEntityDef 49956D4A00C6 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_49956D4A00C6_diagrams

 MEDIAGRAM ME_49956D4A00C6_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_49956D4A00C6' '4683F37902CF.ms.model.script' ; // IvcmEntityDef

  MEVIEW ME_4992FA1A022C_view
   MELINK Original WL 'ME_4992FA1A022C' '4683F37902CF.ms.model.script' ; // TvcmEntityOperationsOption
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4992FA1A022C_view

  MEVIEW ME_4992FA3601A9_view
   MELINK Original WL 'ME_4992FA3601A9' '4683F37902CF.ms.model.script' ; // TvcmEntityOperationsOptions
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4992FA3601A9_view

  MEVIEW ME_49956D95016A_view
   MELINK Original WL 'ME_49956D95016A' '4683F37902CF.ms.model.script' ; // Options
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_49956D95016A_view

  MEVIEW ME_51D12DBB014B_view
   MELINK Original WL 'ME_51D12DBB014B' '4683F37902CF.ms.model.script' ; // ContextMenuWeight
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_51D12DBB014B_view

  MEVIEWLINK ME_4992FA3601A9_ME_4992FA1A022C_Inherits
   MELINK From ME_4992FA3601A9_view ;
   MELINK To ME_4992FA1A022C_view ;
   MEPROP Class class_Inherits
  ENDMEVIEWLINK // ME_4992FA3601A9_ME_4992FA1A022C_Inherits

  MELIST Views
   Seq: ( ME_4992FA1A022C_view // TvcmEntityOperationsOption
   ME_4992FA3601A9_view // TvcmEntityOperationsOptions
   ME_49956D95016A_view // Options
   ME_51D12DBB014B_view // ContextMenuWeight
   ME_4992FA3601A9_ME_4992FA1A022C_Inherits // TvcmEntityOperationsOptions -> TvcmEntityOperationsOption
   )
  ; // Views
 ENDMEDIAGRAM // ME_49956D4A00C6_main

 MELIST Diagrams
  Seq: ( ME_49956D4A00C6_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_49956D4A00C6_diagrams
