// m3DBActions 49C77D5E0246 UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_49C77D5E0246_diagrams

 MEDIAGRAM ME_49C77D5E0246_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_49C77D5E0246' '49C77D5E0246.ms.model.script' ; // m3DBActions

  MEVIEW ME_49C77D8B0081_view
   MELINK Original WL 'ME_49C77D8B0081' '49C77D5E0246.ms.model.script' ; // m3FreeDBStreamAction
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_49C77D8B0081_view

  MELIST Views
   Seq: ( ME_49C77D8B0081_view // m3FreeDBStreamAction
   )
  ; // Views
 ENDMEDIAGRAM // ME_49C77D5E0246_main

 MELIST Diagrams
  Seq: ( ME_49C77D5E0246_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_49C77D5E0246_diagrams
