// MafwVisualizater 49E85D2102CD PureMixIn Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_49E85D2102CD_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_49E85D2102CD' '467823B7002C.ms.model.script' ; // MafwVisualizater

 MEVIEW ME_49E85D4A0016_view
  MELINK Original WL 'ME_49E85D4A0016' '467823B7002C.ms.model.script' ; // MakeLongProcessVisualizer
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_49E85D4A0016_view

ENDMEDIAGRAM // ME_49E85D2102CD_main
