// MafwVisualizater 49E85D2102CD PureMixIn Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_49E85D2102CD_diagrams

 MEDIAGRAM ME_49E85D2102CD_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_49E85D2102CD' '467823B7002C.ms.model.script' ; // MafwVisualizater

  MEVIEW ME_49E85D4A0016_view
   MELINK Original WL 'ME_49E85D4A0016' '467823B7002C.ms.model.script' ; // MakeLongProcessVisualizer
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_49E85D4A0016_view

  MELIST Views
   Seq: ( ME_49E85D4A0016_view // MakeLongProcessVisualizer
   )
  ; // Views
 ENDMEDIAGRAM // ME_49E85D2102CD_main

 MELIST Diagrams
  Seq: ( ME_49E85D2102CD_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_49E85D2102CD_diagrams
