// IsdsInternetAgent 49EC6E2B0118 UseCaseController Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_49EC6E2B0118_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_49EC6E2B0118' '49EC6D9000EE.ms.model.script' ; // IsdsInternetAgent

 MEVIEW ME_49EC6E080148_view
  MELINK Original WL 'ME_49EC6E080148' '49EC6D9000EE.ms.model.script' ; // IdsInternetAgent
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_49EC6E080148_view

ENDMEDIAGRAM // ME_49EC6E2B0118_main
