// ControlsMixIns 49EF33F700C2 Views Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_49EF33F700C2_diagrams

 MEDIAGRAM ME_49EF33F700C2_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_49EF33F700C2' '49EF33F700C2.ms.model.script' ; // ControlsMixIns

  MEVIEW ME_49EF346400A4_view
   MELINK Original WL 'ME_49EF346400A4' '49EF346400A4.ms.model.script' ; // afwShortcutsHandler
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_49EF346400A4_view

  MELIST Views
   Seq: ( ME_49EF346400A4_view // afwShortcutsHandler
   )
  ; // Views
 ENDMEDIAGRAM // ME_49EF33F700C2_main

 MELIST Diagrams
  Seq: ( ME_49EF33F700C2_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_49EF33F700C2_diagrams
