// InevActiveHyperlink 4A27C5A7004E Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4A27C5A7004E_diagrams

 MEDIAGRAM ME_4A27C5A7004E_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4A27C5A7004E' '4A27C4D20100.ms.model.script' ; // InevActiveHyperlink

  MEVIEW ME_4A27C5C600AC_view
   MELINK Original WL 'ME_4A27C5C600AC' '4A27C4D20100.ms.model.script' ; // Hyperlink
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4A27C5C600AC_view

  MELIST Views
   Seq: ( ME_4A27C5C600AC_view // Hyperlink
   )
  ; // Views
 ENDMEDIAGRAM // ME_4A27C5A7004E_main

 MELIST Diagrams
  Seq: ( ME_4A27C5A7004E_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4A27C5A7004E_diagrams
