// ChatInterfaces 4A40991F003F Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4A40991F003F_diagrams

 MEDIAGRAM ME_4A40991F003F_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4A40991F003F' '4A40991F003F.ms.model.script' ; // ChatInterfaces

  MEVIEW ME_4A409BC300FB_view
   MELINK Original WL 'ME_4A409BC300FB' '4A40991F003F.ms.model.script' ; // UserInfo
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4A409BC300FB_view

  MEVIEW ME_4A409D1F00AA_view
   MELINK Original WL 'ME_4A409D1F00AA' '4A40991F003F.ms.model.script' ; // UnknownUser
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4A409D1F00AA_view

  MEVIEW ME_4A4099A302A3_view
   MELINK Original WL 'ME_4A4099A302A3' '4A40991F003F.ms.model.script' ; // ChatManager
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4A4099A302A3_view

  MEVIEW ME_4A409DE402DE_view
   MELINK Original WL 'ME_4A409DE402DE' '4A40991F003F.ms.model.script' ; // Message
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4A409DE402DE_view

  MEVIEW ME_4A40A5670265_view
   MELINK Original WL 'ME_4A40A5670265' '4A40991F003F.ms.model.script' ; // Messages
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4A40A5670265_view

  MEVIEW ME_4A409DC300BF_view
   MELINK Original WL 'ME_4A409DC300BF' '4A40991F003F.ms.model.script' ; // MessagesManager
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_4A409DC300BF_view

  MELIST Views
   Seq: ( ME_4A409BC300FB_view // UserInfo
   ME_4A409D1F00AA_view // UnknownUser
   ME_4A4099A302A3_view // ChatManager
   ME_4A409DE402DE_view // Message
   ME_4A40A5670265_view // Messages
   ME_4A409DC300BF_view // MessagesManager
   )
  ; // Views
 ENDMEDIAGRAM // ME_4A40991F003F_main

 MELIST Diagrams
  Seq: ( ME_4A40991F003F_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4A40991F003F_diagrams
