// MessagesManager 4A409DC300BF Interface Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4A409DC300BF_diagrams

 MEDIAGRAM ME_4A409DC300BF_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4A409DC300BF' '4A40991F003F.ms.model.script' ; // MessagesManager

  MEVIEW ME_4A40A59901F4_view
   MELINK Original WL 'ME_4A40A59901F4' '4A40991F003F.ms.model.script' ; // make
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4A40A59901F4_view

  MEVIEW ME_4A40A5D7025F_view
   MELINK Original WL 'ME_4A40A5D7025F' '4A40991F003F.ms.model.script' ; // get_unreaded_messages
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4A40A5D7025F_view

  MEVIEW ME_4A40A73102AC_view
   MELINK Original WL 'ME_4A40A73102AC' '4A40991F003F.ms.model.script' ; // send_message
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4A40A73102AC_view

  MEVIEW ME_4A40A84A02FE_view
   MELINK Original WL 'ME_4A40A84A02FE' '4A40991F003F.ms.model.script' ; // get_history_for_user
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4A40A84A02FE_view

  MEVIEW ME_4A40A93400D7_view
   MELINK Original WL 'ME_4A40A93400D7' '4A40991F003F.ms.model.script' ; // clean_history
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4A40A93400D7_view

  MEVIEW ME_4A4B0CCC007A_view
   MELINK Original WL 'ME_4A4B0CCC007A' '4A40991F003F.ms.model.script' ; // get_unreaded_messages
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_4A4B0CCC007A_view

  MELIST Views
   Seq: ( ME_4A40A59901F4_view // make
   ME_4A40A5D7025F_view // get_unreaded_messages
   ME_4A40A73102AC_view // send_message
   ME_4A40A84A02FE_view // get_history_for_user
   ME_4A40A93400D7_view // clean_history
   ME_4A4B0CCC007A_view // get_unreaded_messages
   )
  ; // Views
 ENDMEDIAGRAM // ME_4A409DC300BF_main

 MELIST Diagrams
  Seq: ( ME_4A409DC300BF_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4A409DC300BF_diagrams
