// TatGetCRListFromDocumentOperation 4A4CA0DD02F9 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4A4CA0DD02F9_diagrams

 MEDIAGRAM ME_4A4CA0DD02F9_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4A4CA0DD02F9' ; // TatGetCRListFromDocumentOperation

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_4A4CA0DD02F9_main

 MELIST Diagrams
  Seq: ( ME_4A4CA0DD02F9_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4A4CA0DD02F9_diagrams
