// k2TagHolder 4A573C5F01FF Impurity Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4A573C5F01FF_diagrams

 MEDIAGRAM ME_4A573C5F01FF_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4A573C5F01FF' '49A58A1A03C4.ms.model.script' ; // k2TagHolder

  MEVIEW ME_533ED10E0160_view
   MELINK Original WL 'ME_533ED10E0160' '49A58A1A03C4.ms.model.script' ; // Redirect
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_533ED10E0160_view

  MELIST Views
   Seq: ( ME_533ED10E0160_view // Redirect
   )
  ; // Views
 ENDMEDIAGRAM // ME_4A573C5F01FF_main

 MELIST Diagrams
  Seq: ( ME_4A573C5F01FF_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4A573C5F01FF_diagrams
