// EditionsContainer 4A6EC095039C VCMFinalForm Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4A6EC095039C_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4A6EC095039C' '4A6EC095039C.ms.model.script' ; // EditionsContainer

 MEVIEW ME_4CDF29F3816A_view
  MELINK Original WL 'ME_4CDF29F3816A' '4A6EC095039C.ms.model.script' ; // Ini_FormFactory_EditionsContainer
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4CDF29F3816A_view

ENDMEDIAGRAM // ME_4A6EC095039C_main
