// AbstactChatWindowList 4A6EAB540196 Impurity Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4A6EAB540196_diagrams

 MEDIAGRAM ME_4A6EAB540196_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4A6EAB540196' '4A66EB280367.ms.model.script' ; // AbstactChatWindowList

  MEVIEW ME_4A6EAC0F00A9_view
   MELINK Original WL 'ME_4A6EAC0F00A9' '4A66EB280367.ms.model.script' ; // FindChatWindow
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4A6EAC0F00A9_view

  MELIST Views
   Seq: ( ME_4A6EAC0F00A9_view // FindChatWindow
   )
  ; // Views
 ENDMEDIAGRAM // ME_4A6EAB540196_main

 MELIST Diagrams
  Seq: ( ME_4A6EAB540196_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4A6EAB540196_diagrams
