// PrimEditionsContainer 4A6EC0D0020C VCMContainer Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4A6EC0D0020C_diagrams

 MEDIAGRAM ME_4A6EC0D0020C_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4A6EC0D0020C' '4A6EC0D0020C.ms.model.script' ; // PrimEditionsContainer

  MEVIEW ME_4A7985290240_view
   MELINK Original WL 'ME_4A7985290240' '4A6EC0D0020C.ms.model.script' ; // Left
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4A7985290240_view

  MEVIEW ME_4A798550031D_view
   MELINK Original WL 'ME_4A798550031D' '4A6EC0D0020C.ms.model.script' ; // Right
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4A798550031D_view

  MEVIEW ME_4BD705C900FF_view
   MELINK Original WL 'ME_4BD705C900FF' '4A6EC0D0020C.ms.model.script' ; // utEditionsContainer
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4BD705C900FF_view

  MEVIEW ME_54630BDE0364_view
   MELINK Original WL 'ME_54630BDE0364' '4A6EC0D0020C.ms.model.script' ; // CaptionConst
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_54630BDE0364_view

  MEVIEW ME_4A80256B02A5_view
   MELINK Original WL 'ME_4A80256B02A5' '4A6EC0D0020C.ms.model.script' ; // UpdateCaptionFromDS
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4A80256B02A5_view

  MEVIEW ME_4ADC8D5C0182_view
   MELINK Original WL 'ME_4ADC8D5C0182' '4A6EC0D0020C.ms.model.script' ; // FindChangedText
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_4ADC8D5C0182_view

  MEVIEW ME_4AE046D4038D_view
   MELINK Original WL 'ME_4AE046D4038D' '4A6EC0D0020C.ms.model.script' ; // CanFindChangedText
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_4AE046D4038D_view

  MEVIEW ME_54630D2702E1_view
   MELINK Original WL 'ME_54630D2702E1' '4A6EC0D0020C.ms.model.script' ; // MakePrefixedCaption
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_54630D2702E1_view

  MELIST Views
   Seq: ( ME_4A7985290240_view // Left
   ME_4A798550031D_view // Right
   ME_4BD705C900FF_view // utEditionsContainer
   ME_54630BDE0364_view // CaptionConst
   ME_4A80256B02A5_view // UpdateCaptionFromDS
   ME_4ADC8D5C0182_view // FindChangedText
   ME_4AE046D4038D_view // CanFindChangedText
   ME_54630D2702E1_view // MakePrefixedCaption
   )
  ; // Views
 ENDMEDIAGRAM // ME_4A6EC0D0020C_main

 MELIST Diagrams
  Seq: ( ME_4A6EC0D0020C_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4A6EC0D0020C_diagrams
