// l3InterfacePtrListPrim 4A6FFCC00354 Impurity Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4A6FFCC00354_diagrams

 MEDIAGRAM ME_4A6FFCC00354_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4A6FFCC00354' ; // l3InterfacePtrListPrim

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_4A6FFCC00354_main

 MELIST Diagrams
  Seq: ( ME_4A6FFCC00354_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4A6FFCC00354_diagrams
