// View 4A811B89032D VCMViews Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4C3F34640373
%%Inner ME_4A811BCC031F

ME ME_4A811B89032D
 MEPROP UID '4A811B89032D'
 MEPROP Name 'View'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_VCMViews ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4A811B590020' // WorkJournal
 ;
 MELIST Children
   Seq: ( WL? 'ME_4C3F34640373' // Strange
 WL? 'ME_4A811BCC031F' // WorkJournal
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_456EA3D2031C' // GblAdapterLib
 WL? 'ME_4677FBA70343' // l3Interfaces
 WL? 'ME_4677FF4B0036' // Data
 WL? 'ME_467A75D90346' // VT
 WL? 'ME_467A8734039C' // EVD
 WL? 'ME_4680E7D50168' // Everest Engine
 WL? 'ME_4790B4F00236' // AFW
 WL? 'ME_4790C3B8021E' // VCM
 WL? 'ME_4790D09A0378' // L3
 WL? 'ME_4799D29F033F' // Implementation
 WL? 'ME_490838AA02D0' // Nemesis
 WL? 'ME_4954C0500033' // UserInteraction
 WL? 'ME_4954FAA00232' // Search
 WL? 'ME_4A7C099B004F' // View
 WL? 'ME_4A825D4902F1' // WorkJournal
 WL? 'ME_4A9FFD3F01AD' // Search
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_4AB0C3F60375' // Win
 WL? 'ME_4E13416D0227' // VCM$Visual
 WL? 'ME_4E2F0E1B03BB' // L3$Domain
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "exec mode" 'concluded'
 UP "gui" 'prj'
 UP "is namespace" True
 UP "vendor" 'none'
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'

ENDME // ME_4A811B89032D View
