// InsWorkJournalListener 4A83AA5202C1 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4A83AA5202C1_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4A83AA5202C1' '4D7A05A000C1.ms.model.script' ; // InsWorkJournalListener

 MEVIEW ME_4A83AA610299_view
  MELINK Original WL 'ME_4A83AA610299' '4D7A05A000C1.ms.model.script' ; // JournalShrinked
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4A83AA610299_view

ENDMEDIAGRAM // ME_4A83AA5202C1_main
