// ProgressIndicator 4A93F1CC01A8 VCMFinalForm Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4A93F1CC01A8_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4A93F1CC01A8' '4A93F1CC01A8.ms.model.script' ; // ProgressIndicator

 MEVIEW ME_60BD30ED24A4_view
  MELINK Original WL 'ME_60BD30ED24A4' '4A93F1CC01A8.ms.model.script' ; // ProgressIndicator$Def
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_60BD30ED24A4_view

ENDMEDIAGRAM // ME_4A93F1CC01A8_main
