// Result 4A97FFC40154 VCMControls Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4A97FFC40154_diagrams

 MEDIAGRAM ME_4A97FFC40154_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4A97FFC40154' ; // Result

  MEVIEW ME_4A97FFE30274_view
   MELINK Original WL 'ME_4A97FFE30274' '4A97FFC40154.ms.model.script' ; // Result
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4A97FFE30274_view

  MEVIEW ME_4AFAEBDF039C_view
   MELINK Original WL 'ME_4AFAEBDF039C' '4A97FFC40154.ms.model.script' ; // ResultExt
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4AFAEBDF039C_view

  MELIST Views
   Seq: ( ME_4A97FFE30274_view // Result
   ME_4AFAEBDF039C_view // ResultExt
   )
  ; // Views
 ENDMEDIAGRAM // ME_4A97FFC40154_main

 MELIST Diagrams
  Seq: ( ME_4A97FFC40154_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4A97FFC40154_diagrams
