// View 4A9BEFA00301 VCMViews Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4B20DE9B0154
%%Inner ME_4C371629008F
%%Inner ME_497DDB0A0168

ME ME_4A9BEFA00301
 MEPROP UID '4A9BEFA00301'
 MEPROP Name 'View'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_VCMViews ;
 %SUMMARY 'Представление' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4A9BEF6C0297' // WorkWithList
 ;
 MELIST Children
   Seq: ( WL? 'ME_4B20DE9B0154' // StatusBar
 WL? 'ME_4C371629008F' // ListOperations
 WL? 'ME_497DDB0A0168' // List
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4423F94903C8' // IO
 WL? 'ME_456EA3D2031C' // GblAdapterLib
 WL? 'ME_4677E16A022A' // K2
 WL? 'ME_4677FBA70343' // l3Interfaces
 WL? 'ME_4677FF4B0036' // Data
 WL? 'ME_467A75D90346' // VT
 WL? 'ME_467A8734039C' // EVD
 WL? 'ME_4680C57D01E9' // Business
 WL? 'ME_4680E7D50168' // Everest Engine
 WL? 'ME_4682595B0268' // l3TreeInterfaces
 WL? 'ME_46A0E6C5023A' // ActiveX
 WL? 'ME_476F78840219' // Messages
 WL? 'ME_4790B4F00236' // AFW
 WL? 'ME_4790C3B8021E' // VCM
 WL? 'ME_4790D09A0378' // L3
 WL? 'ME_4797632D0273' // Everest
 WL? 'ME_4799D29F033F' // Implementation
 WL? 'ME_47B9727603BE' // FormSets
 WL? 'ME_47E9EEC60260' // Model
 WL? 'ME_481EF5C4020D' // Оболочка
 WL? 'ME_490838AA02D0' // Nemesis
 WL? 'ME_493FAECB025F' // Tree
 WL? 'ME_4954C0500033' // UserInteraction
 WL? 'ME_4954F58900E8' // List
 WL? 'ME_4986ECDF01F4' // View
 WL? 'ME_4A78013D01CD' // View$For F1 and Monitorings
 WL? 'ME_4A7C099B004F' // View
 WL? 'ME_4A92C59801C7' // View
 WL? 'ME_4A9F8D450169' // List
 WL? 'ME_4A9FFD3F01AD' // Search
 WL? 'ME_4AB0997B00A2' // Common
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_4AB0C3F60375' // Win
 WL? 'ME_4ABB680E0218' // Common$Lib
 WL? 'ME_4C6A65ED0374' // F1DocumentProcessing
 WL? 'ME_4CAC58CB03A2' // Filters
 WL? 'ME_4CDD182B02B9' // LinksToGarant
 WL? 'ME_4D1B64E70031' // BusinessInterfaces
 WL? 'ME_4D1B6BAB022D' // F1DocumentProcessingInterfaces
 WL? 'ME_4D4927B5008B' // VT$Core
 WL? 'ME_4DAF19F600C5' // tfwScriptingInterfaces
 WL? 'ME_4E13416D0227' // VCM$Visual
 WL? 'ME_4E2F0E1B03BB' // L3$Domain
 WL? 'ME_4EEA091C01B4' // View$Prim
 WL? 'ME_4F4B8F830023' // ExternalObjects
 WL? 'ME_4F6B660100D5' // View
 WL? 'ME_4F91817500AC' // VT$Rem
 WL? 'ME_51DD5AB6022D' // Components
 WL? 'ME_5257E836001C' // View$Strange
 WL? 'ME_53BA5A5D03A0' // TabInterface
 WL? 'ME_547CC9D40158' // VT$Panels
 WL? 'ME_54B90AC6014B' // StringUtils
 WL? 'ME_54DB92D203C9' // VCL bindings
 WL? 'ME_550012C403C4' // L3$AFW
 WL? 'ME_55B62380030A' // Logging
 WL? 'ME_55C4AEB903E1' // Printing
 WL? 'ME_55C4AEC801CA' // Graphics
 WL? 'ME_57A06C1C0138' // View$Hack
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "exec mode" 'concluded'
 UP "gui" 'prj'
 UP "is namespace" True
 UP "vendor" 'none'
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'

ENDME // ME_4A9BEFA00301 View
