// ModuleOperationPrim 4A9D2DEA0027 MDAClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4A9D2DEA0027_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4A9D2DEA0027' '4B62F51F0182.ms.model.script' ; // ModuleOperationPrim

 MEVIEW ME_4A9D35E401D5_view
  MELINK Original WL 'ME_4A9D35E401D5' '4B62F51F0182.ms.model.script' ; // IsModuleOperation
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4A9D35E401D5_view

ENDMEDIAGRAM // ME_4A9D2DEA0027_main
