// AutoreferatAfterSearch 4AA4B28D02A1 VCMFormSetFactory Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4AA4B28D02A1_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4AA4B28D02A1' '4AA4B28D02A1.ms.model.script' ; // AutoreferatAfterSearch

 MEVIEW ME_4FFA92850358_view
  MELINK Original WL 'ME_4FFA92850358' '4AA4B28D02A1.ms.model.script' ; // TextForm
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4FFA92850358_view

 MEVIEW ME_165DAAD62350_view
  MELINK Original WL 'ME_165DAAD62350' '4AA4B28D02A1.ms.model.script' ; // AutoreferatAfterSearchCaptionLocalConstants
  MEPROP X 120
  MEPROP Y 10
 ENDMEVIEW // ME_165DAAD62350_view

 MEVIEW ME_CAF00B32945C_view
  MELINK Original WL 'ME_CAF00B32945C' '4AA4B28D02A1.ms.model.script' ; // TextForm_Parent_dftAutoreferatAfterSearch_NeedMakeForm
  MEPROP X 230
  MEPROP Y 10
 ENDMEVIEW // ME_CAF00B32945C_view

ENDMEDIAGRAM // ME_4AA4B28D02A1_main
