// View 4AA66B2C02FC VCMViews Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4C4432FA016A
%%Inner ME_4AA66B460175

ME ME_4AA66B2C02FC
 MEPROP UID '4AA66B2C02FC'
 MEPROP Name 'View'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_VCMViews ;
 %SUMMARY 'Представление' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4AA66AFA01B1' // Rubricator
 ;
 MELIST Children
   Seq: ( WL? 'ME_4C4432FA016A' // Strange
 WL? 'ME_4AA66B460175' // Rubricator
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_456EA3D2031C' // GblAdapterLib
 WL? 'ME_4677FF4B0036' // Data
 WL? 'ME_467A75D90346' // VT
 WL? 'ME_467A8734039C' // EVD
 WL? 'ME_4680E7D50168' // Everest Engine
 WL? 'ME_4682595B0268' // l3TreeInterfaces
 WL? 'ME_4790B4F00236' // AFW
 WL? 'ME_4790C3B8021E' // VCM
 WL? 'ME_4790D09A0378' // L3
 WL? 'ME_4797632D0273' // Everest
 WL? 'ME_4799D29F033F' // Implementation
 WL? 'ME_47E9EEC60260' // Model
 WL? 'ME_490838AA02D0' // Nemesis
 WL? 'ME_4954C0500033' // UserInteraction
 WL? 'ME_4A7C099B004F' // View
 WL? 'ME_4A92C59801C7' // View
 WL? 'ME_4AA7A7D903AE' // Rubricator
 WL? 'ME_4AB0997B00A2' // Common
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_4ABB680E0218' // Common$Lib
 WL? 'ME_4C6A65ED0374' // F1DocumentProcessing
 WL? 'ME_4E13416D0227' // VCM$Visual
 WL? 'ME_4E1352670215' // Nemesis$Tails
 WL? 'ME_4E2F0E1B03BB' // L3$Domain
 WL? 'ME_4E36644A0023' // Стандартные компоненты
 WL? 'ME_4F4B8F830023' // ExternalObjects
 WL? 'ME_533D53FF00C2' // Visual$ChromeLike
 WL? 'ME_53BA5A5D03A0' // TabInterface
 WL? 'ME_54B90AC6014B' // StringUtils
 WL? 'ME_55C4AEC801CA' // Graphics
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'

ENDME // ME_4AA66B2C02FC View
