// SituationFilter 4AA7A4E3032E VCMFormSetFactory Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4AA7A4E3032E_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4AA7A4E3032E' '4AA7A4E3032E.ms.model.script' ; // SituationFilter

 MEVIEW ME_4D80F0E80360_view
  MELINK Original WL 'ME_4D80F0E80360' '4AA7A4E3032E.ms.model.script' ; // cfSaveLoad_slqtFilters
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4D80F0E80360_view

 MEVIEW ME_22024086F671_view
  MELINK Original WL 'ME_22024086F671' '4AA7A4E3032E.ms.model.script' ; // SituationFilterCaptionLocalConstants
  MEPROP X 120
  MEPROP Y 10
 ENDMEVIEW // ME_22024086F671_view

 MEVIEW ME_FDEBC9EA7063_view
  MELINK Original WL 'ME_FDEBC9EA7063' '4AA7A4E3032E.ms.model.script' ; // cfSaveLoad_slqtFilters_Modal_slqtFilters_NeedMakeForm
  MEPROP X 230
  MEPROP Y 10
 ENDMEVIEW // ME_FDEBC9EA7063_view

 MEVIEW ME_842ABD7395D7_view
  MELINK Original WL 'ME_842ABD7395D7' '4AA7A4E3032E.ms.model.script' ; // cfAttributeSelect_utSingleSearch_Parent_utSingleSearch_NeedMakeForm
  MEPROP X 340
  MEPROP Y 10
 ENDMEVIEW // ME_842ABD7395D7_view

 MEVIEW ME_E8A4848313E4_view
  MELINK Original WL 'ME_E8A4848313E4' '4AA7A4E3032E.ms.model.script' ; // efTreeAttributeSelect_astNone_Parent_astNone_NeedMakeForm
  MEPROP X 450
  MEPROP Y 10
 ENDMEVIEW // ME_E8A4848313E4_view

 MEVIEW ME_D3C8F83B0BBB_view
  MELINK Original WL 'ME_D3C8F83B0BBB' '4AA7A4E3032E.ms.model.script' ; // enSelectedAttributes_utSelectedAttributes_Child_utSelectedAttributes_NeedMakeForm
  MEPROP X 560
  MEPROP Y 10
 ENDMEVIEW // ME_D3C8F83B0BBB_view

ENDMEDIAGRAM // ME_4AA7A4E3032E_main
