// Runner 4AC347B00177 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4AC347FD023D
%%Inner ME_4AC3488802F7

ME ME_4AC347B00177
 MEPROP UID '4AC347B00177'
 MEPROP Name 'Runner'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_48075C0E02DE' // AdapterTest
 ;
 MELIST Children
   Seq: ( WL? 'ME_4AC347FD023D' // TatAdapterTestCommandLine
 WL? 'ME_4AC3488802F7' // TatAdapterTest
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_48076E7F0260' // CoreObjects
 WL? 'ME_480865840083' // OperationsFramework
 WL? 'ME_4AB0C3C60310' // Sys
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "path prefix" '/Runner'
 UP intf.pas:PathOnly '\quality\test\garant6x\AdapterTest\Runner'

ENDME // ME_4AC347B00177 Runner
