// PrimStyleEditorContainer 4AC6402401E4 VCMContainer Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4AC6402401E4_diagrams

 MEDIAGRAM ME_4AC6402401E4_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4AC6402401E4' ; // PrimStyleEditorContainer

  MEVIEW ME_4C93455D0178_view
   MELINK Original WL 'ME_4C93455D0178' '4AC6402401E4.ms.model.script' ; // utStyleEditorContainer
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4C93455D0178_view

  MEVIEW ME_526A577D007B_view
   MELINK Original WL 'ME_526A577D007B' '4AC6402401E4.ms.model.script' ; // Parent
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_526A577D007B_view

  MEVIEW ME_526A5790016A_view
   MELINK Original WL 'ME_526A5790016A' '4AC6402401E4.ms.model.script' ; // Child
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_526A5790016A_view

  MEVIEW ME_526A57A500F3_view
   MELINK Original WL 'ME_526A57A500F3' '4AC6402401E4.ms.model.script' ; // Navigator
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_526A57A500F3_view

  MEVIEW ME_4AE06B82037F_view
   MELINK Original WL 'ME_4AE06B82037F' '4AC6402401E4.ms.model.script' ; // Make
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4AE06B82037F_view

  MEVIEW ME_526A556A020C_view
   MELINK Original WL 'ME_526A556A020C' '4AC6402401E4.ms.model.script' ; // DoUpdateCaption
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_526A556A020C_view

  MEVIEW ME_526A55940144_view
   MELINK Original WL 'ME_526A55940144' '4AC6402401E4.ms.model.script' ; // FormResize
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_526A55940144_view

  MEVIEW ME_526A55DF0164_view
   MELINK Original WL 'ME_526A55DF0164' '4AC6402401E4.ms.model.script' ; // vcmContainerFormCloseQueryEx
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_526A55DF0164_view

  MEVIEW ME_526A56B701E8_view
   MELINK Original WL 'ME_526A56B701E8' '4AC6402401E4.ms.model.script' ; // BackgroundPanel
   MEPROP X 200
   MEPROP Y 180
  ENDMEVIEW // ME_526A56B701E8_view

  MEVIEW ME_4AC640AE01E0_view
   MELINK Original WL 'ME_4AC640AE01E0' '4AC6402401E4.ms.model.script' ; // f_SettingsInfo
   MEPROP X 360
   MEPROP Y 180
  ENDMEVIEW // ME_4AC640AE01E0_view

  MELIST Views
   Seq: ( ME_4C93455D0178_view // utStyleEditorContainer
   ME_526A577D007B_view // Parent
   ME_526A5790016A_view // Child
   ME_526A57A500F3_view // Navigator
   ME_4AE06B82037F_view // Make
   ME_526A556A020C_view // DoUpdateCaption
   ME_526A55940144_view // FormResize
   ME_526A55DF0164_view // vcmContainerFormCloseQueryEx
   ME_526A56B701E8_view // BackgroundPanel
   ME_4AC640AE01E0_view // f_SettingsInfo
   )
  ; // Views
 ENDMEDIAGRAM // ME_4AC6402401E4_main

 MELIST Diagrams
  Seq: ( ME_4AC6402401E4_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4AC6402401E4_diagrams
