// TevStyleSearcher 4ADC80C703AF SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4ADC80C703AF_diagrams

 MEDIAGRAM ME_4ADC80C703AF_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4ADC80C703AF' '47F1F90A0391.ms.model.script' ; // TevStyleSearcher

  MEVIEW ME_4ADC80DC013E_view
   MELINK Original WL 'ME_4ADC80DC013E' '47F1F90A0391.ms.model.script' ; // IsStyleFound
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4ADC80DC013E_view

  MELIST Views
   Seq: ( ME_4ADC80DC013E_view // IsStyleFound
   )
  ; // Views
 ENDMEDIAGRAM // ME_4ADC80C703AF_main

 MELIST Diagrams
  Seq: ( ME_4ADC80C703AF_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4ADC80C703AF_diagrams
