// TnsOpenDocOnNumberData 4AE760FD0182 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4AE760FD0182_diagrams

 MEDIAGRAM ME_4AE760FD0182_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4AE760FD0182' '4A815BFF0168.ms.model.script' ; // TnsOpenDocOnNumberData

  MEVIEW ME_4AE761950144_view
   MELINK Original WL 'ME_4AE761950144' '4A815BFF0168.ms.model.script' ; // Create
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4AE761950144_view

  MEVIEW ME_4AE761DC0161_view
   MELINK Original WL 'ME_4AE761DC0161' '4A815BFF0168.ms.model.script' ; // Make
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4AE761DC0161_view

  MELIST Views
   Seq: ( ME_4AE761950144_view // Create
   ME_4AE761DC0161_view // Make
   )
  ; // Views
 ENDMEDIAGRAM // ME_4AE760FD0182_main

 MELIST Diagrams
  Seq: ( ME_4AE760FD0182_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4AE760FD0182_diagrams
