// DUnit 4B2A0D4A006F Library Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4B2A0D4A006F_diagrams

 MEDIAGRAM ME_4B2A0D4A006F_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4B2A0D4A006F' '4B2A0D4A006F.ms.model.script' ; // DUnit

  MEVIEW ME_4B2A0D6A0077_view
   MELINK Original WL 'ME_4B2A0D6A0077' '4B2A0D6A0077.ms.model.script' ; // Source
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4B2A0D6A0077_view

  MELIST Views
   Seq: ( ME_4B2A0D6A0077_view // Source
   )
  ; // Views
 ENDMEDIAGRAM // ME_4B2A0D4A006F_main

 MELIST Diagrams
  Seq: ( ME_4B2A0D4A006F_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4B2A0D4A006F_diagrams
