// ActiveElementHolder 4B4DFD69022E PureMixIn Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4B4DFD69022E_diagrams

 MEDIAGRAM ME_4B4DFD69022E_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4B4DFD69022E' '47C5207602D1.ms.model.script' ; // ActiveElementHolder

  MEVIEW ME_4A27CEB10364_view
   MELINK Original WL 'ME_4A27CEB10364' '47C5207602D1.ms.model.script' ; // ActiveElement
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4A27CEB10364_view

  MEVIEW ME_4B59A96702D9_view
   MELINK Original WL 'ME_4B59A96702D9' '47C5207602D1.ms.model.script' ; // ForceDrawFocusRect
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4B59A96702D9_view

  MELIST Views
   Seq: ( ME_4A27CEB10364_view // ActiveElement
   ME_4B59A96702D9_view // ForceDrawFocusRect
   )
  ; // Views
 ENDMEDIAGRAM // ME_4B4DFD69022E_main

 MELIST Diagrams
  Seq: ( ME_4B4DFD69022E_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4B4DFD69022E_diagrams
