// TnsUserProperty 4B5038B80195 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4B5038B80195_diagrams

 MEDIAGRAM ME_4B5038B80195_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4B5038B80195' ; // TnsUserProperty

  MEVIEW ME_4B503BEC02DB_view
   MELINK Original WL 'ME_4B503BEC02DB' '4B5038B80195.ms.model.script' ; // Make
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4B503BEC02DB_view

  MEVIEW ME_4B503E400115_view
   MELINK Original WL 'ME_4B503E400115' '4B5038B80195.ms.model.script' ; // Create
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4B503E400115_view

  MELIST Views
   Seq: ( ME_4B503BEC02DB_view // Make
   ME_4B503E400115_view // Create
   )
  ; // Views
 ENDMEDIAGRAM // ME_4B5038B80195_main

 MELIST Diagrams
  Seq: ( ME_4B5038B80195_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4B5038B80195_diagrams
