// TatChatWorker 4B683B57028D SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4B683B57028D_diagrams

 MEDIAGRAM ME_4B683B57028D_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4B683B57028D' '48078CC202EC.ms.model.script' ; // TatChatWorker

  MEVIEW ME_4B683B6501EB_view
   MELINK Original WL 'ME_4B683B6501EB' '48078CC202EC.ms.model.script' ; // TatChatConversation
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4B683B6501EB_view

  MEVIEW ME_4B69375C01D9_view
   MELINK Original WL 'ME_4B69375C01D9' '48078CC202EC.ms.model.script' ; // TatChatListenerFireFunction
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4B69375C01D9_view

  MEVIEW ME_4B6936A0011F_view
   MELINK Original WL 'ME_4B6936A0011F' '48078CC202EC.ms.model.script' ; // IatChatListener
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4B6936A0011F_view

  MEVIEW ME_4B6937C20205_view
   MELINK Original WL 'ME_4B6937C20205' '48078CC202EC.ms.model.script' ; // TatChatListener
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4B6937C20205_view

  MEVIEW ME_4B6925110286_view
   MELINK Original WL 'ME_4B6925110286' '48078CC202EC.ms.model.script' ; // Create
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4B6925110286_view

  MEVIEW ME_4B69364B0327_view
   MELINK Original WL 'ME_4B69364B0327' '48078CC202EC.ms.model.script' ; // StartConversation
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_4B69364B0327_view

  MEVIEW ME_4B6936590279_view
   MELINK Original WL 'ME_4B6936590279' '48078CC202EC.ms.model.script' ; // FinishConversation
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_4B6936590279_view

  MEVIEW ME_4B6938860170_view
   MELINK Original WL 'ME_4B6938860170' '48078CC202EC.ms.model.script' ; // OnChatNotification
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_4B6938860170_view

  MEVIEW ME_4B7021A30255_view
   MELINK Original WL 'ME_4B7021A30255' '48078CC202EC.ms.model.script' ; // GetContactListUIDs
   MEPROP X 200
   MEPROP Y 180
  ENDMEVIEW // ME_4B7021A30255_view

  MEVIEW ME_4B7023B703C5_view
   MELINK Original WL 'ME_4B7023B703C5' '48078CC202EC.ms.model.script' ; // AddUser
   MEPROP X 360
   MEPROP Y 180
  ENDMEVIEW // ME_4B7023B703C5_view

  MEVIEW ME_4B7023C7019B_view
   MELINK Original WL 'ME_4B7023C7019B' '48078CC202EC.ms.model.script' ; // DeleteUser
   MEPROP X 520
   MEPROP Y 180
  ENDMEVIEW // ME_4B7023C7019B_view

  MELIST Views
   Seq: ( ME_4B683B6501EB_view // TatChatConversation
   ME_4B69375C01D9_view // TatChatListenerFireFunction
   ME_4B6936A0011F_view // IatChatListener
   ME_4B6937C20205_view // TatChatListener
   ME_4B6925110286_view // Create
   ME_4B69364B0327_view // StartConversation
   ME_4B6936590279_view // FinishConversation
   ME_4B6938860170_view // OnChatNotification
   ME_4B7021A30255_view // GetContactListUIDs
   ME_4B7023B703C5_view // AddUser
   ME_4B7023C7019B_view // DeleteUser
   )
  ; // Views
 ENDMEDIAGRAM // ME_4B683B57028D_main

 MELIST Diagrams
  Seq: ( ME_4B683B57028D_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4B683B57028D_diagrams
