// TatChatMessage 4B6AE9CB00C2 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4B6AE9CB00C2_diagrams

 MEDIAGRAM ME_4B6AE9CB00C2_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4B6AE9CB00C2' ; // TatChatMessage

  MEVIEW ME_4B6AE9DB0325_view
   MELINK Original WL 'ME_4B6AE9DB0325' '4B6AE9CB00C2.ms.model.script' ; // IatChatMessage
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4B6AE9DB0325_view

  MEVIEW ME_4B7A9896024C_view
   MELINK Original WL 'ME_4B7A9896024C' '4B6AE9CB00C2.ms.model.script' ; // Make
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4B7A9896024C_view

  MEVIEW ME_4B6AE9ED0068_view
   MELINK Original WL 'ME_4B6AE9ED0068' '4B6AE9CB00C2.ms.model.script' ; // f_ChatMessage
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4B6AE9ED0068_view

  MELIST Views
   Seq: ( ME_4B6AE9DB0325_view // IatChatMessage
   ME_4B7A9896024C_view // Make
   ME_4B6AE9ED0068_view // f_ChatMessage
   )
  ; // Views
 ENDMEDIAGRAM // ME_4B6AE9CB00C2_main

 MELIST Diagrams
  Seq: ( ME_4B6AE9CB00C2_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4B6AE9CB00C2_diagrams
