// Dialogs 4B8E675402AB Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4B8E6793024B
%%Inner ME_4C37236E02A1
%%Inner ME_4D494D090395
%%Inner ME_4D494D3601A8
%%Inner ME_4D494DA003B6
%%Inner ME_4D99E1B401B5
%%Inner ME_4D99F7C003E0

ME ME_4B8E675402AB
 MEPROP UID '4B8E675402AB'
 MEPROP Name 'Dialogs'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4D4927B5008B' // VT$Core
 ;
 MELIST Children
   Seq: ( WL? 'ME_4B8E6793024B' // vtDialogsRes
 WL? 'ME_4C37236E02A1' // TvtSaveDialog
 WL? 'ME_4D494D090395' // vtVGSceneRes
 WL? 'ME_4D494D3601A8' // TvtVGButton
 WL? 'ME_4D494DA003B6' // vtF1InterfaceConst
 WL? 'ME_4D99E1B401B5' // vtDialogsResEx
 WL? 'ME_4D99F7C003E0' // vtDialogs
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_4799D29F033F' // Implementation
 WL? 'ME_4AB0997B00A2' // Common
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_4CFCE51A00B0' // Impl
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_4B8E675402AB Dialogs
