// vcmBaseMenuManagerRes 4B8F8EA1013C UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4B8F8EA1013C_diagrams

 MEDIAGRAM ME_4B8F8EA1013C_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4B8F8EA1013C' ; // vcmBaseMenuManagerRes

  MEVIEW ME_4B8F8EBA0081_view
   MELINK Original WL 'ME_4B8F8EBA0081' '4B8F8EA1013C.ms.model.script' ; // Local
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4B8F8EBA0081_view

  MELIST Views
   Seq: ( ME_4B8F8EBA0081_view // Local
   )
  ; // Views
 ENDMEDIAGRAM // ME_4B8F8EA1013C_main

 MELIST Diagrams
  Seq: ( ME_4B8F8EA1013C_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4B8F8EA1013C_diagrams
