// MixIns 4BCE9EA0028A Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4BCE9EF8033F

ME ME_4BCE9EA0028A
 MEPROP UID '4BCE9EA0028A'
 MEPROP Name 'MixIns'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 %SUMMARY 'Примеси' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4B30C5FF0172' '4B30C5FF0172.ms.model.script' // TestFormsTest
 ;
 MELIST Children
   Seq: ( WL 'ME_4BCE9EF8033F' '4BCE9EF8033F.ms.model.script' // FormProducer
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_4728A7020026' '4728A7020026.ms.model.script' // Types
 WL 'ME_47913B47006E' '47913B47006E.ms.model.script' // l3CoreObjects
 WL 'ME_4799D29F033F' '4799D29F033F.ms.model.script' // Implementation
 WL 'ME_47D0E1500033' '47D0E1500033.ms.model.script' // Implementation
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.ms.model.script' // Sys
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_4BCE9EA0028A MixIns
