// evTableCellUtils 4C3849220132 UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4C3849220132_diagrams

 MEDIAGRAM ME_4C3849220132_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4C3849220132' '4C3849220132.ms.model.script' ; // evTableCellUtils

  MEVIEW ME_4F44B12A0166_view
   MELINK Original WL 'ME_4F44B12A0166' '4C3849220132.ms.model.script' ; // evIsPointTextInCell
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4F44B12A0166_view

  MEVIEW ME_50F5119003E5_view
   MELINK Original WL 'ME_50F5119003E5' '4C3849220132.ms.model.script' ; // evMoreOrEqualOffset
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_50F5119003E5_view

  MEVIEW ME_50F516FA010B_view
   MELINK Original WL 'ME_50F516FA010B' '4C3849220132.ms.model.script' ; // evEqualOffset
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_50F516FA010B_view

  MEVIEW ME_5379A05600E1_view
   MELINK Original WL 'ME_5379A05600E1' '4C3849220132.ms.model.script' ; // evCanDeleteRow
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_5379A05600E1_view

  MEVIEW ME_4C38498D00D0_view
   MELINK Original WL 'ME_4C38498D00D0' '4C3849220132.ms.model.script' ; // evCheckCellWidth
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4C38498D00D0_view

  MEVIEW ME_4C384A440171_view
   MELINK Original WL 'ME_4C384A440171' '4C3849220132.ms.model.script' ; // evCheckCellWidth
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_4C384A440171_view

  MEVIEW ME_4C77545B0230_view
   MELINK Original WL 'ME_4C77545B0230' '4C3849220132.ms.model.script' ; // evHasFormulaOnly
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_4C77545B0230_view

  MEVIEW ME_4C7E0ABF0116_view
   MELINK Original WL 'ME_4C7E0ABF0116' '4C3849220132.ms.model.script' ; // evInEmptyTableCell
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_4C7E0ABF0116_view

  MEVIEW ME_4C8DF2F600EA_view
   MELINK Original WL 'ME_4C8DF2F600EA' '4C3849220132.ms.model.script' ; // evCloneCell
   MEPROP X 200
   MEPROP Y 180
  ENDMEVIEW // ME_4C8DF2F600EA_view

  MEVIEW ME_4CA1ECEB001A_view
   MELINK Original WL 'ME_4CA1ECEB001A' '4C3849220132.ms.model.script' ; // evCheckSingleContinueCell
   MEPROP X 360
   MEPROP Y 180
  ENDMEVIEW // ME_4CA1ECEB001A_view

  MEVIEW ME_4D38236B03AD_view
   MELINK Original WL 'ME_4D38236B03AD' '4C3849220132.ms.model.script' ; // evIsPointHeadCell
   MEPROP X 520
   MEPROP Y 180
  ENDMEVIEW // ME_4D38236B03AD_view

  MEVIEW ME_4D3823BB00DA_view
   MELINK Original WL 'ME_4D3823BB00DA' '4C3849220132.ms.model.script' ; // evCorrectTablePoint
   MEPROP X 680
   MEPROP Y 180
  ENDMEVIEW // ME_4D3823BB00DA_view

  MELIST Views
   Seq: ( ME_4F44B12A0166_view // evIsPointTextInCell
   ME_50F5119003E5_view // evMoreOrEqualOffset
   ME_50F516FA010B_view // evEqualOffset
   ME_5379A05600E1_view // evCanDeleteRow
   ME_4C38498D00D0_view // evCheckCellWidth
   ME_4C384A440171_view // evCheckCellWidth
   ME_4C77545B0230_view // evHasFormulaOnly
   ME_4C7E0ABF0116_view // evInEmptyTableCell
   ME_4C8DF2F600EA_view // evCloneCell
   ME_4CA1ECEB001A_view // evCheckSingleContinueCell
   ME_4D38236B03AD_view // evIsPointHeadCell
   ME_4D3823BB00DA_view // evCorrectTablePoint
   )
  ; // Views
 ENDMEDIAGRAM // ME_4C3849220132_main

 MELIST Diagrams
  Seq: ( ME_4C3849220132_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4C3849220132_diagrams
