// WarnTimeMachine 4C3B4FFE012A VCMOperations Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4C3B4FFE012A_diagrams

 MEDIAGRAM ME_4C3B4FFE012A_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4C3B4FFE012A' '498874B90391.ms.model.script' ; // WarnTimeMachine

  MEVIEW ME_4C7D34A903C5_view
   MELINK Original WL 'ME_4C7D34A903C5' '498874B90391.ms.model.script' ; // ShowInfo
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4C7D34A903C5_view

  MEVIEW ME_4C7D34DE02D2_view
   MELINK Original WL 'ME_4C7D34DE02D2' '498874B90391.ms.model.script' ; // TimeMachineOnOffNew
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4C7D34DE02D2_view

  MEVIEW ME_4C3B500B0126_view
   MELINK Original WL 'ME_4C3B500B0126' '498874B90391.ms.model.script' ; // ShowInfo
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4C3B500B0126_view

  MEVIEW ME_4C3B504A0202_view
   MELINK Original WL 'ME_4C3B504A0202' '498874B90391.ms.model.script' ; // TimeMachineOnOffNew
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4C3B504A0202_view

  MELIST Views
   Seq: ( ME_4C7D34A903C5_view // ShowInfo
   ME_4C7D34DE02D2_view // TimeMachineOnOffNew
   ME_4C3B500B0126_view // ShowInfo
   ME_4C3B504A0202_view // TimeMachineOnOffNew
   )
  ; // Views
 ENDMEDIAGRAM // ME_4C3B4FFE012A_main

 MELIST Diagrams
  Seq: ( ME_4C3B4FFE012A_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4C3B4FFE012A_diagrams
