// K232097143 4C6120070163 TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4C07AC6F036D_ME_4C6120070163_over
 MELINK Original WL 'ME_4C07AC6F036D' '4BE425C70228.ms.model.script' // GetNormalFontSize
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_4C07AC6F036D_ME_4C6120070163_over GetNormalFontSize

MEREF ME_4C08CF700318_ME_4C6120070163_over
 MELINK Original WL 'ME_4C08CF700318' '4BCE9EF8033F.ms.model.script' // FormExtent
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_4C08CF700318_ME_4C6120070163_over FormExtent

MEREF ME_4BEBF13B0076_ME_4C6120070163_G
 MELINK Original WL? 'ME_4BEBF13B0076' // TScrollTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4BEBF13B0076_ME_4C6120070163_G TScrollTest

%%InheritedBy ME_4BEBF13B0076 ME_4C6120070163

ME ME_4C6120070163
 MEPROP UID '4C6120070163'
 MEPROP Name 'K232097143'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '[$232097143]' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4C288F1202F8' // 7.6
 ;
 MELIST Inherits
   Seq: ( HWL ME_4BEBF13B0076_ME_4C6120070163_G // TScrollTest
 )
 ; // Inherits
 MELIST Overridden
   Seq: ( ME_4C07AC6F036D_ME_4C6120070163_over // GetNormalFontSize
 ME_4C08CF700318_ME_4C6120070163_over // FormExtent
 )
 ; // Overridden
 UP extprop:pas:TypeName 'TK232097143'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'K232097143'
 UP intf.pas:Path 'common\components\rtl\Garant\Daily\K232097143.pas'

ENDME // ME_4C6120070163 K232097143
