// TnsOwnedDocumentTagNodePrim 4C724FC1029F SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_467FCF9300AE_ME_4C724FC1029F_G
 MELINK Original WL? 'ME_467FCF9300AE' // TnsDocumentTagNodePrim
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_467FCF9300AE_ME_4C724FC1029F_G TnsDocumentTagNodePrim

MEREF ME_47AC6AEE0094_ME_4C724FC1029F_G
 MELINK Original WL? 'ME_47AC6AEE0094' // k2OwnedTagObject
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_47AC6AEE0094_ME_4C724FC1029F_G k2OwnedTagObject

%%InheritedBy ME_467FCF9300AE ME_4C724FC1029F
%%InheritedBy ME_47AC6AEE0094 ME_4C724FC1029F

ME ME_4C724FC1029F
 MEPROP UID '4C724FC1029F'
 MEPROP Name 'TnsOwnedDocumentTagNodePrim'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_467FC9F80281' // DocumentTagNodes
 ;
 MELIST Inherits
   Seq: ( HWL ME_467FCF9300AE_ME_4C724FC1029F_G // TnsDocumentTagNodePrim
 HWL ME_47AC6AEE0094_ME_4C724FC1029F_G // k2OwnedTagObject
 )
 ; // Inherits
 UP "author" 'Ëþëèí À.Â.'
 UP "no hands" True
 UP "started" '23.08.2010 14:39'
 UP extprop:pas:UnitName 'nsOwnedDocumentTagNodePrim'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'OwnedDocumentTagNodePrim'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\f1DocumentTagsImplementation\nsOwnedDocumentTagNodePrim.pas'

ENDME // ME_4C724FC1029F TnsOwnedDocumentTagNodePrim
