// VCMCustomization 4C8DD86C03C8 VCMSubsystem Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4C8DD86C03C8_diagrams

 MEDIAGRAM ME_4C8DD86C03C8_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4C8DD86C03C8' '4C8DD86C03C8.ms.model.script' ; // VCMCustomization

  MEVIEW ME_4C8DD8970344_view
   MELINK Original WL 'ME_4C8DD8970344' '4C8DD8970344.ms.model.script' ; // View
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4C8DD8970344_view

  MELIST Views
   Seq: ( ME_4C8DD8970344_view // View
   )
  ; // Views
 ENDMEDIAGRAM // ME_4C8DD86C03C8_main

 MELIST Diagrams
  Seq: ( ME_4C8DD86C03C8_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4C8DD86C03C8_diagrams
