// build 4CA0DCFB017A Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4CA0DD21015F
%%Inner ME_4CA1D0DD027A

ME ME_4CA0DCFB017A
 MEPROP UID '4CA0DCFB017A'
 MEPROP Name 'build'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4CA0BEBC011E' '4CA0BEBC011E.ms.model.script' // MTDOrb
 ;
 MELIST Children
   Seq: ( WL 'ME_4CA0DD21015F' '4CA0DD21015F.ms.model.script' // SecuritySrv_int
 WL 'ME_4CA1D0DD027A' '4CA1D0DD027A.ms.model.script' // SecuritySrv
 )
 ; // Children
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "path prefix" '/build'
 UP intf.pas:PathOnly '\common\components\rtl\external\MTDOrb\build'

ENDME // ME_4CA0DCFB017A build
