// K235058888 4CA1AB5B0396 TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4B8542C302E3_ME_4CA1AB5B0396_G
 MELINK Original WL? 'ME_4B8542C302E3' // TEVDtoBothNSRCWriterTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4B8542C302E3_ME_4CA1AB5B0396_G TEVDtoBothNSRCWriterTest

%%InheritedBy ME_4B8542C302E3 ME_4CA1AB5B0396

ME ME_4CA1AB5B0396
 MEPROP UID '4CA1AB5B0396'
 MEPROP Name 'K235058888'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '[$235058888]' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4C288F1202F8' // 7.6
 ;
 MELIST Inherits
   Seq: ( HWL ME_4B8542C302E3_ME_4CA1AB5B0396_G // TEVDtoBothNSRCWriterTest
 )
 ; // Inherits
 UP extprop:pas:TypeName 'TK235058888'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'K235058888'
 UP intf.pas:Path 'common\components\rtl\Garant\Daily\K235058888.pas'

ENDME // ME_4CA1AB5B0396 K235058888
