// TafwPreviewPageSpy 4CB6DFDE0374 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4CB6DFDE0374_diagrams

 MEDIAGRAM ME_4CB6DFDE0374_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4CB6DFDE0374' '474144E20301.ms.model.script' ; // TafwPreviewPageSpy

  MEVIEW ME_4CB6E3800078_view
   MELINK Original WL 'ME_4CB6E3800078' '474144E20301.ms.model.script' ; // IafwPagesLogger
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4CB6E3800078_view

  MEVIEW ME_4CB6E34302AD_view
   MELINK Original WL 'ME_4CB6E34302AD' '474144E20301.ms.model.script' ; // Exists
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4CB6E34302AD_view

  MEVIEW ME_4CB6E54D0386_view
   MELINK Original WL 'ME_4CB6E54D0386' '474144E20301.ms.model.script' ; // SetLogger
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4CB6E54D0386_view

  MEVIEW ME_4CB6E5690252_view
   MELINK Original WL 'ME_4CB6E5690252' '474144E20301.ms.model.script' ; // RemoveLogger
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4CB6E5690252_view

  MEVIEW ME_4CB6E596010B_view
   MELINK Original WL 'ME_4CB6E596010B' '474144E20301.ms.model.script' ; // LogPage
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4CB6E596010B_view

  MEVIEW ME_51ADB624017D_view
   MELINK Original WL 'ME_51ADB624017D' '474144E20301.ms.model.script' ; // IncCounterNumber
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_51ADB624017D_view

  MELIST Views
   Seq: ( ME_4CB6E3800078_view // IafwPagesLogger
   ME_4CB6E34302AD_view // Exists
   ME_4CB6E54D0386_view // SetLogger
   ME_4CB6E5690252_view // RemoveLogger
   ME_4CB6E596010B_view // LogPage
   ME_51ADB624017D_view // IncCounterNumber
   )
  ; // Views
 ENDMEDIAGRAM // ME_4CB6DFDE0374_main

 MELIST Diagrams
  Seq: ( ME_4CB6DFDE0374_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4CB6DFDE0374_diagrams
