// Core 4CC81FAC02D6 Views Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4CC81FAC02D6_diagrams

 MEDIAGRAM ME_4CC81FAC02D6_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4CC81FAC02D6' '4CC81FAC02D6.ms.model.script' ; // Core

  MEVIEW ME_4CC81FB7008B_view
   MELINK Original WL 'ME_4CC81FB7008B' '4CC81FAC02D6.ms.model.script' ; // RegionableControl
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4CC81FB7008B_view

  MELIST Views
   Seq: ( ME_4CC81FB7008B_view // RegionableControl
   )
  ; // Views
 ENDMEDIAGRAM // ME_4CC81FAC02D6_main

 MELIST Diagrams
  Seq: ( ME_4CC81FAC02D6_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4CC81FAC02D6_diagrams
