// Forms 4CDD1854020C VCMForms Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4CDD1854020C_diagrams

 MEDIAGRAM ME_4CDD1854020C_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4CDD1854020C' ; // Forms

  MEVIEW ME_4CDD18E80034_view
   MELINK Original WL? 'ME_4CDD18E80034' ; // HyperlinkToDocumentProducer
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4CDD18E80034_view

  MEVIEW ME_4CDD778501AA_view
   MELINK Original WL? 'ME_4CDD778501AA' ; // nsHyperlinkToDocumentProducerConst
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4CDD778501AA_view

  MELIST Views
   Seq: ( ME_4CDD18E80034_view // HyperlinkToDocumentProducer
   ME_4CDD778501AA_view // nsHyperlinkToDocumentProducerConst
   )
  ; // Views
 ENDMEDIAGRAM // ME_4CDD1854020C_main

 MELIST Diagrams
  Seq: ( ME_4CDD1854020C_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4CDD1854020C_diagrams
