// Tl3ProtoObjectPtrList 4CE5224102C0 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4CE5224102C0

ME ME_4CE5227E02EC
 MEPROP UID '4CE5227E02EC'
 MEPROP Name 'ItemType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4CE5224102C0 // Tl3ProtoObjectPtrList
 ;
 MELINK Target WL? 'ME_49E7754802A9' // Tl3ProtoObject
 ;

ENDME // ME_4CE5227E02EC ItemType

MEREF ME_47B57B7800A7_ME_4CE5224102C0_G
 MELINK Original WL? 'ME_47B57B7800A7' // l3ObjectPtrList
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_47B57B7800A7_ME_4CE5224102C0_G l3ObjectPtrList

MEREF ME_4A54DD4E036F_ME_4CE5224102C0_G
 MELINK Original WL? 'ME_4A54DD4E036F' // Tl3ProtoDataContainer
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4A54DD4E036F_ME_4CE5224102C0_G Tl3ProtoDataContainer

%%InheritedBy ME_47B57B7800A7 ME_4CE5224102C0
%%InheritedBy ME_4A54DD4E036F ME_4CE5224102C0

ME ME_4CE5224102C0
 MEPROP UID '4CE5224102C0'
 MEPROP Name 'Tl3ProtoObjectPtrList'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '—ÔËÒÓÍ ” ¿«¿“≈À≈… Ì‡ Tl3ProtoObject' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4A6D65B9022A' // Containers
 ;
 MELIST Inherits
   Seq: ( HWL ME_47B57B7800A7_ME_4CE5224102C0_G // l3ObjectPtrList
 HWL ME_4A54DD4E036F_ME_4CE5224102C0_G // Tl3ProtoDataContainer
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_4CE5227E02EC // ItemType
 )
 ; // Attributes
 UP "author" 'À˛ÎËÌ ¿.¬.'
 UP "no hands" True
 UP "started" '18.11.2010 15:56'
 UP extprop:pas:UnitName 'l3ProtoObjectPtrList'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ProtoObjectPtrList'
 UP intf.pas:Path 'common\components\rtl\Garant\L3\l3ProtoObjectPtrList.pas'

ENDME // ME_4CE5224102C0 Tl3ProtoObjectPtrList
