// Font 4D07AF060118 InnerTag Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4D07AF060118_diagrams

 MEDIAGRAM ME_4D07AF060118_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4D07AF060118' '484A470100DD.ms.model.script' ; // Font

  MEVIEW ME_4D07AF17020E_view
   MELINK Original WL 'ME_4D07AF17020E' '484A470100DD.ms.model.script' ; // ForeColor
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4D07AF17020E_view

  MELIST Views
   Seq: ( ME_4D07AF17020E_view // ForeColor
   )
  ; // Views
 ENDMEDIAGRAM // ME_4D07AF060118_main

 MELIST Diagrams
  Seq: ( ME_4D07AF060118_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4D07AF060118_diagrams
