// ColorSelectionForBaseSearch 4D07AEE70111 TagValue Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4D07AEE70111_diagrams

 MEDIAGRAM ME_4D07AEE70111_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4D07AEE70111' '484A470100DD.ms.model.script' ; // ColorSelectionForBaseSearch

  MEVIEW ME_4D07AF060118_view
   MELINK Original WL 'ME_4D07AF060118' '484A470100DD.ms.model.script' ; // Font
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4D07AF060118_view

  MELIST Views
   Seq: ( ME_4D07AF060118_view // Font
   )
  ; // Views
 ENDMEDIAGRAM // ME_4D07AEE70111_main

 MELIST Diagrams
  Seq: ( ME_4D07AEE70111_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4D07AEE70111_diagrams
