// K247300520 4D08F3E3023E TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4D0256A60243_ME_4D08F3E3023E_G
 MELINK Original WL? 'ME_4D0256A60243' // TAutoBlockTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4D0256A60243_ME_4D08F3E3023E_G TAutoBlockTest

%%InheritedBy ME_4D0256A60243 ME_4D08F3E3023E

ME ME_4D08F3E3023E
 MEPROP UID '4D08F3E3023E'
 MEPROP Name 'K247300520'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{RequestLink:247300520}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4D02571C01D0' // 7.7
 ;
 MELIST Inherits
   Seq: ( HWL ME_4D0256A60243_ME_4D08F3E3023E_G // TAutoBlockTest
 )
 ; // Inherits
 UP "author" 'Ëþëèí À.Â.'
 UP "no hands" True
 UP "started" '15.12.2010 19:59'
 UP extprop:pas:TypeName 'TK247300520'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'K247300520'
 UP intf.pas:Path 'common\components\rtl\Garant\Daily\K247300520.pas'

ENDME // ME_4D08F3E3023E K247300520
