// DocumentContainers 4D358BD90052 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4D358BD90052_diagrams

 MEDIAGRAM ME_4D358BD90052_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4D358BD90052' ; // DocumentContainers

  MEVIEW ME_4CE662B803DA_view
   MELINK Original WL 'ME_4CE662B803DA' '4D358BD90052.ms.model.script' ; // TnsDictionDocumentContainer
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4CE662B803DA_view

  MELIST Views
   Seq: ( ME_4CE662B803DA_view // TnsDictionDocumentContainer
   )
  ; // Views
 ENDMEDIAGRAM // ME_4D358BD90052_main

 MELIST Diagrams
  Seq: ( ME_4D358BD90052_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4D358BD90052_diagrams
