// DictionLike 4D358B9A01E5 VCMSubsystem Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4D358B9A01E5_diagrams

 MEDIAGRAM ME_4D358B9A01E5_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4D358B9A01E5' '4D358B9A01E5.ms.model.script' ; // DictionLike

  MEVIEW ME_4D358BAD038E_view
   MELINK Original WL 'ME_4D358BAD038E' '4D358BAD038E.ms.model.script' ; // DictionLikeDocumentProcessing
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4D358BAD038E_view

  MEVIEW ME_4F5DB66602DC_view
   MELINK Original WL 'ME_4F5DB66602DC' '4F5DB66602DC.ms.model.script' ; // View
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4F5DB66602DC_view

  MELIST Views
   Seq: ( ME_4D358BAD038E_view // DictionLikeDocumentProcessing
   ME_4F5DB66602DC_view // View
   )
  ; // Views
 ENDMEDIAGRAM // ME_4D358B9A01E5_main

 MELIST Diagrams
  Seq: ( ME_4D358B9A01E5_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4D358B9A01E5_diagrams
