// DictionLike 4D358B9A01E5 VCMSubsystem Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4D358BAD038E
%%Inner ME_4F5DB66602DC

ME ME_4D358B9A01E5
 MEPROP UID '4D358B9A01E5'
 MEPROP Name 'DictionLike'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_VCMSubsystem ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent WL? 'ME_4AC2470103B2' // F1 Встроенные продукты
 ;
 MELIST Children
   Seq: ( WL? 'ME_4D358BAD038E' // DictionLikeDocumentProcessing
 WL? 'ME_4F5DB66602DC' // View
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_456EA3D2031C' // GblAdapterLib
 WL? 'ME_4677E16A022A' // K2
 WL? 'ME_4680E7D50168' // Everest Engine
 WL? 'ME_4797632D0273' // Everest
 WL? 'ME_49549627008C' // LegalDomain
 WL? 'ME_4A92C561015D' // Common
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis'

ENDME // ME_4D358B9A01E5 DictionLike
