// Picture 4D38575C0033 VCMForms Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4AAFCFB0014B
%%Inner ME_4C8768010125
%%Inner ME_4AB12F7601D3
%%Inner ME_4C86319003CD

ME ME_4D38575C0033
 MEPROP UID '4D38575C0033'
 MEPROP Name 'Picture'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_VCMForms ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4A9F76D70283' // View
 ;
 MELIST Children
   Seq: ( WL? 'ME_4AAFCFB0014B' // PrimPicture
 WL? 'ME_4C8768010125' // PrimPictureOptions
 WL? 'ME_4AB12F7601D3' // PrimPictureInfo
 WL? 'ME_4C86319003CD' // PrimPictureInfoOptions
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4677FBA70343' // l3Interfaces
 WL? 'ME_467BAB7F021E' // vcmExternalInterfaces
 WL? 'ME_4683F37902CF' // vcmInterfaces
 WL? 'ME_473C3BEE0334' // l3Canvas
 WL? 'ME_476F78840219' // Messages
 WL? 'ME_47750CE700D0' // afwFacade
 WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_4799D29F033F' // Implementation
 WL? 'ME_47BB24D30205' // Стандартные примеси
 WL? 'ME_47D0E1500033' // Implementation
 WL? 'ME_47F2170002B2' // nsTypes
 WL? 'ME_47F260DC003F' // ns
 WL? 'ME_48F747EC0073' // Common
 WL? 'ME_495127DD017C' // Text
 WL? 'ME_4952683C007B' // Editor
 WL? 'ME_498874B90391' // Strange
 WL? 'ME_499192F203B4' // L10nInterfaces
 WL? 'ME_4991BD69025E' // DocumentDomainInterfaces
 WL? 'ME_4A8AD3C70195' // Result
 WL? 'ME_4AADF9450143' // Visual
 WL? 'ME_4AB0997B00A2' // Common
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_4AB0C3F60375' // Win
 WL? 'ME_4ABB68530117' // Printing
 WL? 'ME_4ACDBC26003C' // Source
 WL? 'ME_4AEEE2A40281' // Strange
 WL? 'ME_4B4DCD0B0295' // Common
 WL? 'ME_4CDABA8F024B' // Printing
 WL? 'ME_4DDA34AA023B' // Dialogs
 WL? 'ME_533D53FF00C2' // Visual$ChromeLike
 WL? 'ME_53A402C7010D' // TabbedInterfaceSupport
 WL? 'ME_54B90AC6014B' // StringUtils
 WL? 'ME_55C4AEC801CA' // Graphics
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_4D38575C0033 Picture
