// TOnPaintEvent 4D5EB67A030E Function Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4D5EB67A030E_diagrams

 MEDIAGRAM ME_4D5EB67A030E_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4D5EB67A030E' '4D550C220363.ms.model.script' ; // TOnPaintEvent

  MEVIEW ME_4D5EB68A03CA_view
   MELINK Original WL 'ME_4D5EB68A03CA' '4D550C220363.ms.model.script' ; // DoIt
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4D5EB68A03CA_view

  MELIST Views
   Seq: ( ME_4D5EB68A03CA_view // DoIt
   )
  ; // Views
 ENDMEDIAGRAM // ME_4D5EB67A030E_main

 MELIST Diagrams
  Seq: ( ME_4D5EB67A030E_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4D5EB67A030E_diagrams
