// TnsAnnotationHeaderTagNode 4D6E0C4A001F SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4D6E0C4A001F_diagrams

 MEDIAGRAM ME_4D6E0C4A001F_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4D6E0C4A001F' '491C3ADB03A5.ms.model.script' ; // TnsAnnotationHeaderTagNode

  MEVIEW ME_4D6E0CA20143_view
   MELINK Original WL 'ME_4D6E0CA20143' '491C3ADB03A5.ms.model.script' ; // Create
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4D6E0CA20143_view

  MEVIEW ME_4D6E0CDD033D_view
   MELINK Original WL 'ME_4D6E0CDD033D' '491C3ADB03A5.ms.model.script' ; // Make
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4D6E0CDD033D_view

  MELIST Views
   Seq: ( ME_4D6E0CA20143_view // Create
   ME_4D6E0CDD033D_view // Make
   )
  ; // Views
 ENDMEDIAGRAM // ME_4D6E0C4A001F_main

 MELIST Diagrams
  Seq: ( ME_4D6E0C4A001F_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4D6E0C4A001F_diagrams
