// ContextSearchInEVDDocument 4D8A25430335 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4D8A25430335_diagrams

 MEDIAGRAM ME_4D8A25430335_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4D8A25430335' '4D8A25430335.ms.model.script' ; // ContextSearchInEVDDocument

  MEVIEW ME_495137C70135_view
   MELINK Original WL 'ME_495137C70135' '4D8A25430335.ms.model.script' ; // TbsDocumentContextSearcher
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_495137C70135_view

  MEVIEW ME_4D18F1F2033A_view
   MELINK Original WL 'ME_4D18F1F2033A' '4D8A25430335.ms.model.script' ; // TnsFindIteratorNewFindPositionList
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4D18F1F2033A_view

  MEVIEW ME_4C9C918102BC_view
   MELINK Original WL 'ME_4C9C918102BC' '4D8A25430335.ms.model.script' ; // TnsFindIteratorNew
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4C9C918102BC_view

  MEVIEW ME_4CE6B3E90338_view
   MELINK Original WL 'ME_4CE6B3E90338' '4D8A25430335.ms.model.script' ; // TnsFindIteratorNewForAutoreferat
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4CE6B3E90338_view

  MEVIEW ME_4D18E8330139_view
   MELINK Original WL 'ME_4D18E8330139' '4D8A25430335.ms.model.script' ; // TnsFindPositionListList
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4D18E8330139_view

  MEVIEW ME_4D00EA5A02CF_view
   MELINK Original WL 'ME_4D00EA5A02CF' '4D8A25430335.ms.model.script' ; // TnsFindIteratorNewForDiction
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_4D00EA5A02CF_view

  MEVIEW ME_4D8A1D6700A0_view
   MELINK Original WL 'ME_4D8A1D6700A0' '4D8A25430335.ms.model.script' ; // TnsContextListForSearchViaEverestOwnSearcher
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_4D8A1D6700A0_view

  MEVIEW ME_4B61AB64033F_view
   MELINK Original WL 'ME_4B61AB64033F' '4D8A25430335.ms.model.script' ; // TnsFoundBlocksList
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_4B61AB64033F_view

  MEVIEW ME_4D8A2C1700FD_view
   MELINK Original WL 'ME_4D8A2C1700FD' '4D8A25430335.ms.model.script' ; // TnsFoundRangeCollector
   MEPROP X 200
   MEPROP Y 180
  ENDMEVIEW // ME_4D8A2C1700FD_view

  MEVIEW ME_4D8A35D7008B_view
   MELINK Original WL 'ME_4D8A35D7008B' '4D8A25430335.ms.model.script' ; // TnsFragmentListForSearchViaEverestOwnSearcher
   MEPROP X 360
   MEPROP Y 180
  ENDMEVIEW // ME_4D8A35D7008B_view

  MEVIEWLINK ME_4D18DA050339_viewlink
   MELINK Original WL 'ME_4D18DA050339' '4D8A25430335.ms.model.script' ;
   MELINK From ME_495137C70135_view ;
   MELINK To ME_4C9C918102BC_view ;
  ENDMEVIEWLINK // ME_4D18DA050339_viewlink

  MEVIEWLINK ME_4D18DA150120_viewlink
   MELINK Original WL 'ME_4D18DA150120' '4D8A25430335.ms.model.script' ;
   MELINK From ME_495137C70135_view ;
   MELINK To ME_4CE6B3E90338_view ;
  ENDMEVIEWLINK // ME_4D18DA150120_viewlink

  MEVIEWLINK ME_4D18DA1F0194_viewlink
   MELINK Original WL 'ME_4D18DA1F0194' '4D8A25430335.ms.model.script' ;
   MELINK From ME_495137C70135_view ;
   MELINK To ME_4D00EA5A02CF_view ;
  ENDMEVIEWLINK // ME_4D18DA1F0194_viewlink

  MEVIEWLINK ME_4D8A1DB30161_viewlink
   MELINK Original WL 'ME_4D8A1DB30161' '4D8A25430335.ms.model.script' ;
   MELINK From ME_495137C70135_view ;
   MELINK To ME_4D8A1D6700A0_view ;
  ENDMEVIEWLINK // ME_4D8A1DB30161_viewlink

  MEVIEWLINK ME_4D8A2C4C03AD_viewlink
   MELINK Original WL 'ME_4D8A2C4C03AD' '4D8A25430335.ms.model.script' ;
   MELINK From ME_495137C70135_view ;
   MELINK To ME_4D8A2C1700FD_view ;
  ENDMEVIEWLINK // ME_4D8A2C4C03AD_viewlink

  MEVIEWLINK ME_4D18F22D0216_viewlink
   MELINK Original WL 'ME_4D18F22D0216' '4D8A25430335.ms.model.script' ;
   MELINK From ME_4C9C918102BC_view ;
   MELINK To ME_4D18F1F2033A_view ;
  ENDMEVIEWLINK // ME_4D18F22D0216_viewlink

  MEVIEWLINK ME_4D18E87F00A1_viewlink
   MELINK Original WL 'ME_4D18E87F00A1' '4D8A25430335.ms.model.script' ;
   MELINK From ME_4D00EA5A02CF_view ;
   MELINK To ME_4D18E8330139_view ;
  ENDMEVIEWLINK // ME_4D18E87F00A1_viewlink

  MEVIEWLINK ME_4D8A36F30242_viewlink
   MELINK Original WL 'ME_4D8A36F30242' '4D8A25430335.ms.model.script' ;
   MELINK From ME_4D8A1D6700A0_view ;
   MELINK To ME_4D8A35D7008B_view ;
  ENDMEVIEWLINK // ME_4D8A36F30242_viewlink

  MELIST Views
   Seq: ( ME_495137C70135_view // TbsDocumentContextSearcher
   ME_4D18F1F2033A_view // TnsFindIteratorNewFindPositionList
   ME_4C9C918102BC_view // TnsFindIteratorNew
   ME_4CE6B3E90338_view // TnsFindIteratorNewForAutoreferat
   ME_4D18E8330139_view // TnsFindPositionListList
   ME_4D00EA5A02CF_view // TnsFindIteratorNewForDiction
   ME_4D8A1D6700A0_view // TnsContextListForSearchViaEverestOwnSearcher
   ME_4B61AB64033F_view // TnsFoundBlocksList
   ME_4D8A2C1700FD_view // TnsFoundRangeCollector
   ME_4D8A35D7008B_view // TnsFragmentListForSearchViaEverestOwnSearcher
   ME_4D18DA050339_viewlink // TbsDocumentContextSearcher -> TnsFindIteratorNew
   ME_4D18DA150120_viewlink // TbsDocumentContextSearcher -> TnsFindIteratorNewForAutoreferat
   ME_4D18DA1F0194_viewlink // TbsDocumentContextSearcher -> TnsFindIteratorNewForDiction
   ME_4D8A1DB30161_viewlink // TbsDocumentContextSearcher -> TnsContextListForSearchViaEverestOwnSearcher
   ME_4D8A2C4C03AD_viewlink // TbsDocumentContextSearcher -> TnsFoundRangeCollector
   ME_4D18F22D0216_viewlink // TnsFindIteratorNew -> TnsFindIteratorNewFindPositionList
   ME_4D18E87F00A1_viewlink // TnsFindIteratorNewForDiction -> TnsFindPositionListList
   ME_4D8A36F30242_viewlink // TnsContextListForSearchViaEverestOwnSearcher -> TnsFragmentListForSearchViaEverestOwnSearcher
   )
  ; // Views
 ENDMEDIAGRAM // ME_4D8A25430335_main

 MELIST Diagrams
  Seq: ( ME_4D8A25430335_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4D8A25430335_diagrams
