// TvtPopupForm 4D90583503C2 GuiControl Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4D90583503C2_diagrams

 MEDIAGRAM ME_4D90583503C2_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4D90583503C2' '4D90583503C2.ms.model.script' ; // TvtPopupForm

  MEVIEW ME_4F86D90400CD_view
   MELINK Original WL 'ME_4F86D90400CD' '4D90583503C2.ms.model.script' ; // TvtTailPosition
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4F86D90400CD_view

  MEVIEW ME_4FC76B5B0371_view
   MELINK Original WL 'ME_4FC76B5B0371' '4D90583503C2.ms.model.script' ; // TvtCurrentBounds
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4FC76B5B0371_view

  MEVIEW ME_4FC772F5013E_view
   MELINK Original WL 'ME_4FC772F5013E' '4D90583503C2.ms.model.script' ; // THackWinControl
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4FC772F5013E_view

  MEVIEW ME_4FC7733B0224_view
   MELINK Original WL 'ME_4FC7733B0224' '4D90583503C2.ms.model.script' ; // TvtPopupForm_Constants
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4FC7733B0224_view

  MEVIEW ME_4FC7711F014B_view
   MELINK Original WL 'ME_4FC7711F014B' '4D90583503C2.ms.model.script' ; // AdjustBalloonSize
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4FC7711F014B_view

  MEVIEW ME_4FC87D8002D6_view
   MELINK Original WL 'ME_4FC87D8002D6' '4D90583503C2.ms.model.script' ; // PanelGetSiteInfo
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_4FC87D8002D6_view

  MEVIEW ME_4FC7694303B7_view
   MELINK Original WL 'ME_4FC7694303B7' '4D90583503C2.ms.model.script' ; // CMVisibleChanged
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_4FC7694303B7_view

  MELIST Views
   Seq: ( ME_4F86D90400CD_view // TvtTailPosition
   ME_4FC76B5B0371_view // TvtCurrentBounds
   ME_4FC772F5013E_view // THackWinControl
   ME_4FC7733B0224_view // TvtPopupForm_Constants
   ME_4FC7711F014B_view // AdjustBalloonSize
   ME_4FC87D8002D6_view // PanelGetSiteInfo
   ME_4FC7694303B7_view // CMVisibleChanged
   )
  ; // Views
 ENDMEDIAGRAM // ME_4D90583503C2_main

 MELIST Diagrams
  Seq: ( ME_4D90583503C2_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4D90583503C2_diagrams
