// K259175668 4D940F400178 TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4BE051200169_ME_4D940F400178_impl
 MELINK Original WL 'ME_4BE051200169' '4BE04F030356.ms.model.script' // StringForSearch
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_4BE051200169_ME_4D940F400178_impl StringForSearch

MEREF ME_4BE0513800C9_ME_4D940F400178_impl
 MELINK Original WL 'ME_4BE0513800C9' '4BE04F030356.ms.model.script' // StringForReplace
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_4BE0513800C9_ME_4D940F400178_impl StringForReplace

MEREF ME_4D9411E703B8_ME_4D940F400178_G
 MELINK Original WL? 'ME_4D9411E703B8' // TWrongSearchTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4D9411E703B8_ME_4D940F400178_G TWrongSearchTest

%%InheritedBy ME_4D9411E703B8 ME_4D940F400178

ME ME_4D940F400178
 MEPROP UID '4D940F400178'
 MEPROP Name 'K259175668'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '[$259175668]' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4D02571C01D0' // 7.7
 ;
 MELIST Inherits
   Seq: ( HWL ME_4D9411E703B8_ME_4D940F400178_G // TWrongSearchTest
 )
 ; // Inherits
 MELIST Implemented
   Seq: ( ME_4BE051200169_ME_4D940F400178_impl // StringForSearch
 ME_4BE0513800C9_ME_4D940F400178_impl // StringForReplace
 )
 ; // Implemented
 UP extprop:pas:TypeName 'TK259175668'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'K259175668'
 UP intf.pas:Path 'common\components\rtl\Garant\Daily\K259175668.pas'

ENDME // ME_4D940F400178 K259175668
