// VCMWord 4DB94A660083 Impurity Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4DB94A660083_diagrams

 MEDIAGRAM ME_4DB94A660083_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4DB94A660083' ; // VCMWord

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_4DB94A660083_main

 MELIST Diagrams
  Seq: ( ME_4DB94A660083_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4DB94A660083_diagrams
