// TkwCompiledWordWorker 4DCBD50101CB SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4DCBD50101CB_diagrams

 MEDIAGRAM ME_4DCBD50101CB_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4DCBD50101CB' '54F079B5035C.ms.model.script' ; // TkwCompiledWordWorker

  MEVIEW ME_4DCBD660009C_view
   MELINK Original WL 'ME_4DCBD660009C' '54F079B5035C.ms.model.script' ; // RkwCompiledWordWorker
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4DCBD660009C_view

  MEVIEW ME_4DCBB0CD028D_view
   MELINK Original WL 'ME_4DCBB0CD028D' '54F079B5035C.ms.model.script' ; // Create
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4DCBB0CD028D_view

  MEVIEW ME_53DB7F940102_view
   MELINK Original WL 'ME_53DB7F940102' '54F079B5035C.ms.model.script' ; // WordToWork
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_53DB7F940102_view

  MELIST Views
   Seq: ( ME_4DCBD660009C_view // RkwCompiledWordWorker
   ME_4DCBB0CD028D_view // Create
   ME_53DB7F940102_view // WordToWork
   )
  ; // Views
 ENDMEDIAGRAM // ME_4DCBD50101CB_main

 MELIST Diagrams
  Seq: ( ME_4DCBD50101CB_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4DCBD50101CB_diagrams
