// TtfwWordWorker 4DCBD489023A SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4DCBD489023A_diagrams

 MEDIAGRAM ME_4DCBD489023A_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4DCBD489023A' '54F079B5035C.ms.model.script' ; // TtfwWordWorker

  MEVIEW ME_4DCBD67C0362_view
   MELINK Original WL 'ME_4DCBD67C0362' '54F079B5035C.ms.model.script' ; // CompiledWorkerClass
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4DCBD67C0362_view

  MEVIEW ME_4F219FA10268_view
   MELINK Original WL 'ME_4F219FA10268' '54F079B5035C.ms.model.script' ; // FillCompiledWorker
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4F219FA10268_view

  MEVIEW ME_4F41566A02E5_view
   MELINK Original WL 'ME_4F41566A02E5' '54F079B5035C.ms.model.script' ; // CompileWordWorker
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4F41566A02E5_view

  MEVIEW ME_5284D8180211_view
   MELINK Original WL 'ME_5284D8180211' '54F079B5035C.ms.model.script' ; // MakeCompiledWordWorker
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_5284D8180211_view

  MELIST Views
   Seq: ( ME_4DCBD67C0362_view // CompiledWorkerClass
   ME_4F219FA10268_view // FillCompiledWorker
   ME_4F41566A02E5_view // CompileWordWorker
   ME_5284D8180211_view // MakeCompiledWordWorker
   )
  ; // Views
 ENDMEDIAGRAM // ME_4DCBD489023A_main

 MELIST Diagrams
  Seq: ( ME_4DCBD489023A_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4DCBD489023A_diagrams
