// DocumentFilters 4DCD537F0284 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4DCD537F0284_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4DCD537F0284' '4DCD537F0284.ms.model.script' ; // DocumentFilters

 MEVIEW ME_4DCD5932009E_view
  MELINK Original WL 'ME_4DCD5932009E' '4DCD537F0284.ms.model.script' ; // Tf1MultilinkResolver
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4DCD5932009E_view

ENDMEDIAGRAM // ME_4DCD537F0284_main
