// Tl3GraphicContainerStack 4DD3CD0B0193 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4DD3CD0B0193_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4DD3CD0B0193' '473C3BEE0334.ms.model.script' ; // Tl3GraphicContainerStack

 MEVIEW ME_4DD3CE6A00B7_view
  MELINK Original WL 'ME_4DD3CE6A00B7' '473C3BEE0334.ms.model.script' ; // Exists
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4DD3CE6A00B7_view

ENDMEDIAGRAM // ME_4DD3CD0B0193_main
