// TnevTableRowBaseLine4Print 4DD77A940374 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4DD77A940374_diagrams

 MEDIAGRAM ME_4DD77A940374_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4DD77A940374' '47E3DF460095.ms.model.script' ; // TnevTableRowBaseLine4Print

  MEVIEW ME_4DDCC692014A_view
   MELINK Original WL 'ME_4DDCC692014A' '47E3DF460095.ms.model.script' ; // Make
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4DDCC692014A_view

  MELIST Views
   Seq: ( ME_4DDCC692014A_view // Make
   )
  ; // Views
 ENDMEDIAGRAM // ME_4DD77A940374_main

 MELIST Diagrams
  Seq: ( ME_4DD77A940374_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4DD77A940374_diagrams
