// TkwClickOnCommentHeader 4DE740FA0192 ScriptKeyword Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4DE740FA0192_diagrams

 MEDIAGRAM ME_4DE740FA0192_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4DE740FA0192' ; // TkwClickOnCommentHeader

  MEVIEW ME_4DE75634036A_view
   MELINK Original WL 'ME_4DE75634036A' '4DE740FA0192.ms.model.script' ; // f_Engine
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4DE75634036A_view

  MELIST Views
   Seq: ( ME_4DE75634036A_view // f_Engine
   )
  ; // Views
 ENDMEDIAGRAM // ME_4DE740FA0192_main

 MELIST Diagrams
  Seq: ( ME_4DE740FA0192_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4DE740FA0192_diagrams
