// AdapterTest$Target 4DE8C9A603C1 ExeTarget Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4DE8C9A603C1_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4DE8C9A603C1' '4DE8C9A603C1.ms.model.script' ; // AdapterTest$Target

 MEVIEW ME_4DE8C9DB02AD_view
  MELINK Original WL 'ME_4DE8C9DB02AD' '4DE8C9A603C1.ms.model.script' ; // TRunner
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4DE8C9DB02AD_view

ENDMEDIAGRAM // ME_4DE8C9A603C1_main
