// K266421641 4DFB445E0369 TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4DE4827600CA_ME_4DFB445E0369_G
 MELINK Original WL? 'ME_4DE4827600CA' // TArchiInsiderTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4DE4827600CA_ME_4DFB445E0369_G TArchiInsiderTest

%%InheritedBy ME_4DE4827600CA ME_4DFB445E0369

ME ME_4DFB445E0369
 MEPROP UID '4DFB445E0369'
 MEPROP Name 'K266421641'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '[$266421641]' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4DE7484A0315' // EditorTests
 ;
 MELIST Inherits
   Seq: ( HWL ME_4DE4827600CA_ME_4DFB445E0369_G // TArchiInsiderTest
 )
 ; // Inherits
 UP extprop:pas:TypeName 'TK266421641'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'K266421641'
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K266421641.pas'

ENDME // ME_4DFB445E0369 K266421641
