// TddAutoFitBehavior 4E0D97220074 Enum Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4E0D97220074_diagrams

 MEDIAGRAM ME_4E0D97220074_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4E0D97220074' '4E0D98F50163.ms.model.script' ; // TddAutoFitBehavior

  MEVIEW ME_4E0D972B0278_view
   MELINK Original WL 'ME_4E0D972B0278' '4E0D98F50163.ms.model.script' ; // afEqual
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4E0D972B0278_view

  MEVIEW ME_4E0D9732006C_view
   MELINK Original WL 'ME_4E0D9732006C' '4E0D98F50163.ms.model.script' ; // afContent
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4E0D9732006C_view

  MELIST Views
   Seq: ( ME_4E0D972B0278_view // afEqual
   ME_4E0D9732006C_view // afContent
   )
  ; // Views
 ENDMEDIAGRAM // ME_4E0D97220074_main

 MELIST Diagrams
  Seq: ( ME_4E0D97220074_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4E0D97220074_diagrams
