// StatusBar 4E159FE900E2 Views Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4E159FE900E2_diagrams

 MEDIAGRAM ME_4E159FE900E2_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4E159FE900E2' '4E159FE900E2.ms.model.script' ; // StatusBar

  MEVIEW ME_4E15A00502A3_view
   MELINK Original WL 'ME_4E15A00502A3' '4E15A00502A3.ms.model.script' ; // TvtStatusBar
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4E15A00502A3_view

  MELIST Views
   Seq: ( ME_4E15A00502A3_view // TvtStatusBar
   )
  ; // Views
 ENDMEDIAGRAM // ME_4E159FE900E2_main

 MELIST Diagrams
  Seq: ( ME_4E159FE900E2_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4E159FE900E2_diagrams
