// MixIns 4E1C0134031B Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4E1C0134031B_diagrams

 MEDIAGRAM ME_4E1C0134031B_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4E1C0134031B' ; // MixIns

  MEVIEW ME_4E1C016B0011_view
   MELINK Original WL? 'ME_4E1C016B0011' ; // DrawOutputSupport
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4E1C016B0011_view

  MEVIEW ME_4CC815A00031_view
   MELINK Original WL? 'ME_4CC815A00031' ; // SelectTablePart
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4CC815A00031_view

  MEVIEW ME_4CE1344403AC_view
   MELINK Original WL? 'ME_4CE1344403AC' ; // ClipboardOperations
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4CE1344403AC_view

  MEVIEW ME_4F72AE860228_view
   MELINK Original WL 'ME_4F72AE860228' '4E1C0134031B.ms.model.script' ; // TkwPrintDataSaver
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4F72AE860228_view

  MEVIEW ME_4FA3BB1500BA_view
   MELINK Original WL? 'ME_4FA3BB1500BA' ; // LinesDrawOutput
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_4FA3BB1500BA_view

  MELIST Views
   Seq: ( ME_4E1C016B0011_view // DrawOutputSupport
   ME_4CC815A00031_view // SelectTablePart
   ME_4CE1344403AC_view // ClipboardOperations
   ME_4F72AE860228_view // TkwPrintDataSaver
   ME_4FA3BB1500BA_view // LinesDrawOutput
   )
  ; // Views
 ENDMEDIAGRAM // ME_4E1C0134031B_main

 MELIST Diagrams
  Seq: ( ME_4E1C0134031B_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4E1C0134031B_diagrams
