// Информация об изменяющих документах 4E30242402C6 UseCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4E30242402C6_diagrams

 MEDIAGRAM ME_4E30242402C6_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4E30242402C6' '484FA67302D7.ms.model.script' ; // Информация об изменяющих документах

  MEVIEW ME_4E3024310248_view
   MELINK Original WL 'ME_4E3024310248' '484FA67302D7.ms.model.script' ; // Показывать историю изменений в документе
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4E3024310248_view

  MELIST Views
   Seq: ( ME_4E3024310248_view // Показывать историю изменений в документе
   )
  ; // Views
 ENDMEDIAGRAM // ME_4E30242402C6_main

 MELIST Diagrams
  Seq: ( ME_4E30242402C6_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4E30242402C6_diagrams
