// Отображение объектов 4E5BBA78010E Requirements Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4E5BBA78010E_diagrams

 MEDIAGRAM ME_4E5BBA78010E_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4E5BBA78010E' '4E5BBA78010E.ms.model.script' ; // Отображение объектов

  MEVIEW ME_4E5BBABD028A_view
   MELINK Original WL 'ME_4E5BBABD028A' '4E5BBABD028A.ms.model.script' ; // Базовые механизмы отображения объектов
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4E5BBABD028A_view

  MELIST Views
   Seq: ( ME_4E5BBABD028A_view // Базовые механизмы отображения объектов
   )
  ; // Views
 ENDMEDIAGRAM // ME_4E5BBA78010E_main

 MELIST Diagrams
  Seq: ( ME_4E5BBA78010E_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4E5BBA78010E_diagrams
