// MnevFormatInfo 4E71EA55027C Contract Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4E71EA55027C_diagrams

 MEDIAGRAM ME_4E71EA55027C_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4E71EA55027C' '4678209200A6.ms.model.script' ; // MnevFormatInfo

  MEVIEW ME_481060DE0339_view
   MELINK Original WL 'ME_481060DE0339' '4678209200A6.ms.model.script' ; // rLimitWidth
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_481060DE0339_view

  MELIST Views
   Seq: ( ME_481060DE0339_view // rLimitWidth
   )
  ; // Views
 ENDMEDIAGRAM // ME_4E71EA55027C_main

 MELIST Diagrams
  Seq: ( ME_4E71EA55027C_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4E71EA55027C_diagrams
