// archi$admin2$FAS 4E7724A8010E VCMProject Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4E7724A8010E_diagrams

 MEDIAGRAM ME_4E7724A8010E_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4E7724A8010E' ; // archi$admin2$FAS

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_4E7724A8010E_main

 MELIST Diagrams
  Seq: ( ME_4E7724A8010E_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4E7724A8010E_diagrams
