// archi$EverestLite$AMD 4E772D8A0136 Project Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4E772D8A0136_diagrams

 MEDIAGRAM ME_4E772D8A0136_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4E772D8A0136' '4E772D8A0136.ms.model.script' ; // archi$EverestLite$AMD

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_4E772D8A0136_main

 MELIST Diagrams
  Seq: ( ME_4E772D8A0136_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4E772D8A0136_diagrams
