// Требования к Администратору Архивариуса 4E7725120309 Requirements Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4E7725120309_diagrams

 MEDIAGRAM ME_4E7725120309_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4E7725120309' ; // Требования к Администратору Архивариуса

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_4E7725120309_main

 MELIST Diagrams
  Seq: ( ME_4E7725120309_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4E7725120309_diagrams
