// Требования к Серверу автоматизации 4E7727FE024B Requirements Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4E7727FE024B_diagrams

 MEDIAGRAM ME_4E7727FE024B_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_4E7727FE024B' ; // Требования к Серверу автоматизации

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_4E7727FE024B_main

 MELIST Diagrams
  Seq: ( ME_4E7727FE024B_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4E7727FE024B_diagrams
