// Плавающее окно 4E79FAA30127 UseCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4E79FAA30127_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4E79FAA30127' '4E79FA920283.ms.model.script' ; // Плавающее окно

 MEVIEW ME_4E79FAE60370_view
  MELINK Original WL 'ME_4E79FAE60370' '4E79FA920283.ms.model.script' ; // Плавающее окно должно уметь прятаться, а не только закрываться
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4E79FAE60370_view

ENDMEDIAGRAM // ME_4E79FAA30127_main
