// Плавающее оглавление документа 4E7AF98801BE UseCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4E7AF98801BE_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4E7AF98801BE' '484900780017.ms.model.script' ; // Плавающее оглавление документа

 MEVIEW ME_4E7A08BB02D8_view
  MELINK Original WL 'ME_4E7A08BB02D8' '484900780017.ms.model.script' ; // Окно оглавления в плавающем состоянии должно прятаться, а не закрываться
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4E7A08BB02D8_view

 MEVIEW ME_4E7A0C450082_view
  MELINK Original WL 'ME_4E7A0C450082' '484900780017.ms.model.script' ; // Должна быть кнопка закрытия окна
  MEPROP X 120
  MEPROP Y 10
 ENDMEVIEW // ME_4E7A0C450082_view

 MEVIEW ME_4E7A0C5700E2_view
  MELINK Original WL 'ME_4E7A0C5700E2' '484900780017.ms.model.script' ; // Должна быть кнопка на тулбаре, переключающая видимость окна оглавления
  MEPROP X 230
  MEPROP Y 10
 ENDMEVIEW // ME_4E7A0C5700E2_view

 MEVIEW ME_4E7A1E66014F_view
  MELINK Original WL 'ME_4E7A1E66014F' '484900780017.ms.model.script' ; // Видимость плавающего окна оглавления должна запоминаться в настройки
  MEPROP X 340
  MEPROP Y 10
 ENDMEVIEW // ME_4E7A1E66014F_view

 MEVIEW ME_4E7B39FF0082_view
  MELINK Original WL 'ME_4E7B39FF0082' '484900780017.ms.model.script' ; // Оглавление должно закрываться по Enter или двойному клику на элементе оглавления
  MEPROP X 450
  MEPROP Y 10
 ENDMEVIEW // ME_4E7B39FF0082_view

 MEVIEW ME_4E7B489F021A_view
  MELINK Original WL 'ME_4E7B489F021A' '484900780017.ms.model.script' ; // Оглавление должно закрываться если ткнули мышью в текст документа
  MEPROP X 560
  MEPROP Y 10
 ENDMEVIEW // ME_4E7B489F021A_view

ENDMEDIAGRAM // ME_4E7AF98801BE_main
