// WarningBaloon 4EA58A3903B4 VCMFinalForm Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4EA58A3903B4_diagrams

 MEDIAGRAM ME_4EA58A3903B4_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4EA58A3903B4' '4EA58A3903B4.ms.model.script' ; // WarningBaloon

  MEVIEW ME_D18A1AF77354_view
   MELINK Original WL 'ME_D18A1AF77354' '4EA58A3903B4.ms.model.script' ; // Ini_FormFactory_WarningBaloon
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_D18A1AF77354_view

  MELIST Views
   Seq: ( ME_D18A1AF77354_view // Ini_FormFactory_WarningBaloon
   )
  ; // Views
 ENDMEDIAGRAM // ME_4EA58A3903B4_main

 MELIST Diagrams
  Seq: ( ME_4EA58A3903B4_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4EA58A3903B4_diagrams
