// K329649989 4F1ECBA602E3 TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4DE4827600CA_ME_4F1ECBA602E3_G
 MELINK Original WL? 'ME_4DE4827600CA' // TArchiInsiderTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4DE4827600CA_ME_4F1ECBA602E3_G TArchiInsiderTest

%%InheritedBy ME_4DE4827600CA ME_4F1ECBA602E3

ME ME_4F1ECBA602E3
 MEPROP UID '4F1ECBA602E3'
 MEPROP Name 'K329649989'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:329649989}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4DE7484A0315' // EditorTests
 ;
 MELIST Inherits
   Seq: ( HWL ME_4DE4827600CA_ME_4F1ECBA602E3_G // TArchiInsiderTest
 )
 ; // Inherits
 UP extprop:pas:TypeName 'TK329649989'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'K329649989'
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K329649989.pas'

ENDME // ME_4F1ECBA602E3 K329649989
