// TkwCompiledFunction 4F3BEDFE0051 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4F3BEDFE0051_diagrams

 MEDIAGRAM ME_4F3BEDFE0051_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4F3BEDFE0051' '4DAEEA14018A.ms.model.script' ; // TkwCompiledFunction

  MEVIEW ME_4F3BEF910123_view
   MELINK Original WL 'ME_4F3BEF910123' '4DAEEA14018A.ms.model.script' ; // Local
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4F3BEF910123_view

  MEVIEW ME_4F3BEFCE01CA_view
   MELINK Original WL 'ME_4F3BEFCE01CA' '4DAEEA14018A.ms.model.script' ; // ResultVar
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4F3BEFCE01CA_view

  MELIST Views
   Seq: ( ME_4F3BEF910123_view // Local
   ME_4F3BEFCE01CA_view // ResultVar
   )
  ; // Views
 ENDMEDIAGRAM // ME_4F3BEDFE0051_main

 MELIST Diagrams
  Seq: ( ME_4F3BEDFE0051_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4F3BEDFE0051_diagrams
