// ExternalObjects 4F4B8F830023 Library Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_4F4B8F830023_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_4F4B8F830023' '4F4B8F830023.ms.model.script' ; // ExternalObjects

 MEVIEW ME_4F4B8FA60272_view
  MELINK Original WL 'ME_4F4B8FA60272' '4F4B8FA60272.ms.model.script' ; // Implementation
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4F4B8FA60272_view

ENDMEDIAGRAM // ME_4F4B8F830023_main
