// KeyWordsTest 4F606C3202C1 TestUnit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_4F606C5E035E

ME ME_4F606C3202C1
 MEPROP UID '4F606C3202C1'
 MEPROP Name 'KeyWordsTest'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_TestUnit ;
 %SUMMARY 'Тестирование ключевых слов.' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4DE765AE02EB' // ArchiInsiderTests
 ;
 MELIST Children
   Seq: ( WL? 'ME_4F606C5E035E' // K342859055
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_4DE3425B01DA' // ArchiScriptSupport
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP Version 0

ENDME // ME_4F606C3202C1 KeyWordsTest
