// afwSettingsPrim 4F6C6DF70131 Impurity Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_4F6C6DF70131

ME ME_4F6C6E180003
 MEPROP UID '4F6C6E180003'
 MEPROP Name 'IStringType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4F6C6DF70131 // afwSettingsPrim
 ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_4F6C6E180003 IStringType

ME ME_4F6C6E510230
 MEPROP UID '4F6C6E510230'
 MEPROP Name 'KeyType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4F6C6DF70131 // afwSettingsPrim
 ;
 MELINK Target WL 'ME_473D9E950032' '467823B7002C.ms.model.script' // TafwSettingId
 ;

ENDME // ME_4F6C6E510230 KeyType

ME ME_4F6C92190005
 MEPROP UID '4F6C92190005'
 MEPROP Name 'BooleanType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_4F6C6DF70131 // afwSettingsPrim
 ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_4F6C92190005 BooleanType

ME ME_4F6C6FAE02AC
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4F6C6DF70131 // afwSettingsPrim
 ;
 MELINK Target WL? 'ME_47878E0E0191' // l3String
 ;

ENDME // ME_4F6C6FAE02AC 

ME ME_4F6C6FB20013
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4F6C6DF70131 // afwSettingsPrim
 ;
 MELINK Target WL? 'ME_4773D64E036C' // l3Base
 ;

ENDME // ME_4F6C6FB20013 

ME ME_4F6C79D502AF
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_4F6C6DF70131 // afwSettingsPrim
 ;
 MELINK Target WL 'ME_4F6C79B10165' '4F6C5511015F.ms.model.script' // TafwAString
 ;

ENDME // ME_4F6C79D502AF 

ME ME_4F6C56D90012_ME_4F6C6DF70131
 MELINK Original WL 'ME_4F6C56D90012' '4AD58B6C0289.ms.model.script' // IStringTypeToIl3CString
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_4F6C56D90012_ME_4F6C6DF70131 IStringTypeToIl3CString

ME ME_4F6C651603A5_ME_4F6C6DF70131
 MELINK Original WL 'ME_4F6C651603A5' '4AD58B6C0289.ms.model.script' // SettingIDtoKeyType
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_4F6C651603A5_ME_4F6C6DF70131 SettingIDtoKeyType

ME ME_4F6C65E2024F_ME_4F6C6DF70131
 MELINK Original WL 'ME_4F6C65E2024F' '4AD58B6C0289.ms.model.script' // Il3CStringToAString
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_4F6C65E2024F_ME_4F6C6DF70131 Il3CStringToAString

ME ME_4F6C699E009A_ME_4F6C6DF70131
 MELINK Original WL 'ME_4F6C699E009A' '4AD58B6C0289.ms.model.script' // StringToPChar
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_4F6C699E009A_ME_4F6C6DF70131 StringToPChar

%%InheritedBy ME_4AD58B6C0289 ME_4F6C6DF70131

ME ME_4F6C6DF70131
 MEPROP UID '4F6C6DF70131'
 MEPROP Name 'afwSettingsPrim'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_Impurity ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent WL? 'ME_4F6C5511015F' // afwSettings
 ;
 MELIST Inherits
   Seq: ( WL? 'ME_4AD58B6C0289' // nsAbstractSettingsPrim
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_4F6C6E180003 // IStringType
 HWL ME_4F6C6E510230 // KeyType
 HWL ME_4F6C92190005 // BooleanType
 )
 ; // Attributes
 MELIST Implemented
   Seq: ( ME_4F6C56D90012_ME_4F6C6DF70131 // IStringTypeToIl3CString
 ME_4F6C651603A5_ME_4F6C6DF70131 // SettingIDtoKeyType
 ME_4F6C65E2024F_ME_4F6C6DF70131 // Il3CStringToAString
 ME_4F6C699E009A_ME_4F6C6DF70131 // StringToPChar
 )
 ; // Implemented
 MELIST Dependencies
   Seq: ( ME_4F6C6FAE02AC // l3String
 ME_4F6C6FB20013 // l3Base
 ME_4F6C79D502AF // TafwAString
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP extprop:pas:TypeName '_afwSettingsPrim_'
 UP extprop:pas:UnitName 'afwSettingsPrim.imp'
 UP intf.pas:Path 'common\components\gui\Garant\AFW\afwSettingsPrim.imp.pas'

ENDME // ME_4F6C6DF70131 afwSettingsPrim
