// Il3MouseWheelListener 4F79CE030257 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_4F79CE030257_diagrams

 MEDIAGRAM ME_4F79CE030257_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_4F79CE030257' '4677FBA70343.ms.model.script' ; // Il3MouseWheelListener

  MEVIEW ME_4F79D08A02C7_view
   MELINK Original WL 'ME_4F79D08A02C7' '4677FBA70343.ms.model.script' ; // MouseWheelListenerNotify
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4F79D08A02C7_view

  MELIST Views
   Seq: ( ME_4F79D08A02C7_view // MouseWheelListenerNotify
   )
  ; // Views
 ENDMEDIAGRAM // ME_4F79CE030257_main

 MELIST Diagrams
  Seq: ( ME_4F79CE030257_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_4F79CE030257_diagrams
