// TvcmModuleAction 4F82EFD20255 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_4F82EFD20255
 MEPROP UID '4F82EFD20255'
 MEPROP Name 'TvcmModuleAction'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_47E7617C0275' // Actions
 ;
 UP "finished" False
 UP extprop:pas:UnitName 'vcmModuleAction'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ModuleAction'
 UP intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Visual\NOT_FINISHED_vcmModuleAction.pas'

ENDME // ME_4F82EFD20255 TvcmModuleAction
