// TvcmEntityAction 4F82EFAB02D4 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_4F82EFAB02D4
 MEPROP UID '4F82EFAB02D4'
 MEPROP Name 'TvcmEntityAction'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_47E7617C0275' // Actions
 ;
 UP "finished" False
 UP extprop:pas:UnitName 'vcmEntityAction'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'EntityAction'
 UP intf.pas:Path 'common\components\gui\Garant\VCM\implementation\Visual\NOT_FINISHED_vcmEntityAction.pas'

ENDME // ME_4F82EFAB02D4 TvcmEntityAction
