// K370384889 4FCF0C2800FE TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4DE4827600CA_ME_4FCF0C2800FE_G
 MELINK Original WL? 'ME_4DE4827600CA' // TArchiInsiderTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4DE4827600CA_ME_4FCF0C2800FE_G TArchiInsiderTest

%%InheritedBy ME_4DE4827600CA ME_4FCF0C2800FE

ME ME_4FCF0C2800FE
 MEPROP UID '4FCF0C2800FE'
 MEPROP Name 'K370384889'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:370384889}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4F3271990289' // OEMTextTests
 ;
 MELIST Inherits
   Seq: ( HWL ME_4DE4827600CA_ME_4FCF0C2800FE_G // TArchiInsiderTest
 )
 ; // Inherits
 UP extprop:pas:TypeName 'TK370384889'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'K370384889'
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K370384889.pas'

ENDME // ME_4FCF0C2800FE K370384889
