// AbstractDocumentFormSetFactory 500932290106 VCMForms Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_500932290106_diagrams

 MEDIAGRAM ME_500932290106_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_500932290106' '500932290106.ms.model.script' ; // AbstractDocumentFormSetFactory

  MEVIEW ME_5009367A01C3_view
   MELINK Original WL 'ME_5009367A01C3' '5009367A01C3.ms.model.script' ; // AbstractDocument
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5009367A01C3_view

  MELIST Views
   Seq: ( ME_5009367A01C3_view // AbstractDocument
   )
  ; // Views
 ENDMEDIAGRAM // ME_500932290106_main

 MELIST Diagrams
  Seq: ( ME_500932290106_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_500932290106_diagrams
