// View 5009321B01F4 VCMViews Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_500932290106

ME ME_5009321B01F4
 MEPROP UID '5009321B01F4'
 MEPROP Name 'View'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_VCMViews ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4FF4121B0036' // F1 Document Processing
 ;
 MELIST Children
   Seq: ( WL? 'ME_500932290106' // AbstractDocumentFormSetFactory
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_4677FF4B0036' // Data
 WL? 'ME_47B9727603BE' // FormSets
 WL? 'ME_4A7C099B004F' // View
 WL? 'ME_4A92C59801C7' // View
 WL? 'ME_4D1B64E70031' // BusinessInterfaces
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP intf.pas:PathOnly '\garant6x\implementation\Garant\GbaNemesis\View'

ENDME // ME_5009321B01F4 View
