// TevTextInTableCorrector 502B789B03CA SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_502B789B03CA_diagrams

 MEDIAGRAM ME_502B789B03CA_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_502B789B03CA' '47ECACA70141.ms.model.script' ; // TevTextInTableCorrector

  MEVIEW ME_539003570066_view
   MELINK Original WL 'ME_539003570066' '47ECACA70141.ms.model.script' ; // InCell
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_539003570066_view

  MEVIEW ME_516524320112_view
   MELINK Original WL 'ME_516524320112' '47ECACA70141.ms.model.script' ; // f_WasStyle
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_516524320112_view

  MELIST Views
   Seq: ( ME_539003570066_view // InCell
   ME_516524320112_view // f_WasStyle
   )
  ; // Views
 ENDMEDIAGRAM // ME_502B789B03CA_main

 MELIST Diagrams
  Seq: ( ME_502B789B03CA_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_502B789B03CA_diagrams
