// ContextFilterParams 503CE9590299 Struct Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_503CE9590299_diagrams

 MEDIAGRAM ME_503CE9590299_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_503CE9590299' '48078CC202EC.ms.model.script' ; // ContextFilterParams

  MEVIEW ME_503CE9800087_view
   MELINK Original WL 'ME_503CE9800087' '48078CC202EC.ms.model.script' ; // ContextPlace
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_503CE9800087_view

  MEVIEW ME_503CE988004C_view
   MELINK Original WL 'ME_503CE988004C' '48078CC202EC.ms.model.script' ; // FindOrder
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_503CE988004C_view

  MEVIEW ME_503CE98E02F0_view
   MELINK Original WL 'ME_503CE98E02F0' '48078CC202EC.ms.model.script' ; // SearchArea
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_503CE98E02F0_view

  MELIST Views
   Seq: ( ME_503CE9800087_view // ContextPlace
   ME_503CE988004C_view // FindOrder
   ME_503CE98E02F0_view // SearchArea
   )
  ; // Views
 ENDMEDIAGRAM // ME_503CE9590299_main

 MELIST Diagrams
  Seq: ( ME_503CE9590299_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_503CE9590299_diagrams
