// TatWordOrderConverter 503E615E0377 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_503E615E0377

ME ME_503E63560357
 MEPROP UID '503E63560357'
 MEPROP Name 'FirstType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_503E615E0377 // TatWordOrderConverter
 ;
 MELINK Target WL 'ME_46A61C340026' '4677FBA70343.ms.model.script' // Tl3WordOrder
 ;

ENDME // ME_503E63560357 FirstType

ME ME_503E6367000F
 MEPROP UID '503E6367000F'
 MEPROP Name 'SecondType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_503E615E0377 // TatWordOrderConverter
 ;
 MELINK Target WL 'ME_45EEC3260222' '457450470167.ms.model.script' // FindOrder
 ;

ENDME // ME_503E6367000F SecondType

MEREF ME_503E3A040395_ME_503E615E0377_impl
 MELINK Original WL 'ME_503E3A040395' '503E2BCA01E8.ms.model.script' // InitConvertMap
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_503E3A040395_ME_503E615E0377_impl InitConvertMap

MEREF ME_503E66FA02FE_ME_503E615E0377_G
 MELINK Original WL? 'ME_503E66FA02FE' // atEnumToEnumConverter
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_503E66FA02FE_ME_503E615E0377_G atEnumToEnumConverter

%%InheritedBy ME_503E66FA02FE ME_503E615E0377

ME ME_503E615E0377
 MEPROP UID '503E615E0377'
 MEPROP Name 'TatWordOrderConverter'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_503E611303A1' // InteropWithL3
 ;
 MELIST Inherits
   Seq: ( HWL ME_503E66FA02FE_ME_503E615E0377_G // atEnumToEnumConverter
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_503E63560357 // FirstType
 HWL ME_503E6367000F // SecondType
 )
 ; // Attributes
 MELIST Implemented
   Seq: ( ME_503E3A040395_ME_503E615E0377_impl // InitConvertMap
 )
 ; // Implemented
 UP "singleton" True
 UP extprop:pas:UnitName 'atWordOrderConverter'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'atWordOrderConverter'
 UP intf.pas:Path 'quality\test\garant6x\AdapterTest\InteropWithL3\atWordOrderConverter.pas'

ENDME // ME_503E615E0377 TatWordOrderConverter
