// TatDocumentUnderControlOperation 504F1A8B004B SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_504F1A8B004B_diagrams

 MEDIAGRAM ME_504F1A8B004B_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_504F1A8B004B' '4808ADB9014E.ms.model.script' ; // TatDocumentUnderControlOperation

  MEVIEW ME_504F4705036A_view
   MELINK Original WL 'ME_504F4705036A' '4808ADB9014E.ms.model.script' ; // OpType
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_504F4705036A_view

  MEVIEW ME_504F47500265_view
   MELINK Original WL 'ME_504F47500265' '4808ADB9014E.ms.model.script' ; // TatOpTypeConverter
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_504F47500265_view

  MELIST Views
   Seq: ( ME_504F4705036A_view // OpType
   ME_504F47500265_view // TatOpTypeConverter
   )
  ; // Views
 ENDMEDIAGRAM // ME_504F1A8B004B_main

 MELIST Diagrams
  Seq: ( ME_504F1A8B004B_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_504F1A8B004B_diagrams
