// Autolink 5069A3DE03D5 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_505C064A02A4
%%Inner ME_552BF78902EE

ME ME_5069A3DE03D5
 MEPROP UID '5069A3DE03D5'
 MEPROP Name 'Autolink'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_47BC4FCB0115' '47BC4FCB0115.ms.model.script' // DT
 ;
 MELIST Children
   Seq: ( WL 'ME_505C064A02A4' '505C064A02A4.ms.model.script' // ddAutoLinkFilter
 WL 'ME_552BF78902EE' '552BF78902EE.ms.model.script' // ddAutoLinkServices
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_47913B47006E' '47913B47006E.ms.model.script' // l3CoreObjects
 WL 'ME_552BF68E0188' '552BF68E0188.ms.model.script' // AutoLink
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_5069A3DE03D5 Autolink
