// TnscTasksPanelOperationNode 508EBDA900AE SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_508EBDA900AE_diagrams

 MEDIAGRAM ME_508EBDA900AE_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_508EBDA900AE' '4D3424960025.ms.model.script' ; // TnscTasksPanelOperationNode

  MEVIEW ME_508FE2F30143_view
   MELINK Original WL 'ME_508FE2F30143' '4D3424960025.ms.model.script' ; // Create
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_508FE2F30143_view

  MEVIEW ME_508FE3110060_view
   MELINK Original WL 'ME_508FE3110060' '4D3424960025.ms.model.script' ; // Make
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_508FE3110060_view

  MELIST Views
   Seq: ( ME_508FE2F30143_view // Create
   ME_508FE3110060_view // Make
   )
  ; // Views
 ENDMEDIAGRAM // ME_508EBDA900AE_main

 MELIST Diagrams
  Seq: ( ME_508EBDA900AE_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_508EBDA900AE_diagrams
