// THintWindow 50C61B670302 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_50C61B670302_diagrams

 MEDIAGRAM ME_50C61B670302_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_50C61B670302' '47E11FC3021E.ms.model.script' ; // THintWindow

  MEVIEW ME_50C61BA40123_view
   MELINK Original WL 'ME_50C61BA40123' '47E11FC3021E.ms.model.script' ; // ActivateHint
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_50C61BA40123_view

  MEVIEW ME_50C61BD700BF_view
   MELINK Original WL 'ME_50C61BD700BF' '47E11FC3021E.ms.model.script' ; // IsHintMsg
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_50C61BD700BF_view

  MELIST Views
   Seq: ( ME_50C61BA40123_view // ActivateHint
   ME_50C61BD700BF_view // IsHintMsg
   )
  ; // Views
 ENDMEDIAGRAM // ME_50C61B670302_main

 MELIST Diagrams
  Seq: ( ME_50C61B670302_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_50C61B670302_diagrams
