// K421123801 50D961520067 TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4DE4827600CA_ME_50D961520067_G
 MELINK Original WL? 'ME_4DE4827600CA' // TArchiInsiderTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4DE4827600CA_ME_50D961520067_G TArchiInsiderTest

%%InheritedBy ME_4DE4827600CA ME_50D961520067

ME ME_50D961520067
 MEPROP UID '50D961520067'
 MEPROP Name 'K421123801'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:421123801}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4F4E055A0054' // ScrollTests
 ;
 MELIST Inherits
   Seq: ( HWL ME_4DE4827600CA_ME_50D961520067_G // TArchiInsiderTest
 )
 ; // Inherits
 UP extprop:pas:TypeName 'TK421123801'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'K421123801'
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K421123801.pas'

ENDME // ME_50D961520067 K421123801
