// EverestLiteInsiderTest 512DAFB70392 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_512DAFB70392_diagrams

 MEDIAGRAM ME_512DAFB70392_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_512DAFB70392' ; // EverestLiteInsiderTest

  MEVIEW ME_512DB031030F_view
   MELINK Original WL 'ME_512DB031030F' '512DAFB70392.ms.model.script' ; // TEverestLiteTestSuite
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_512DB031030F_view

  MELIST Views
   Seq: ( ME_512DB031030F_view // TEverestLiteTestSuite
   )
  ; // Views
 ENDMEDIAGRAM // ME_512DAFB70392_main

 MELIST Diagrams
  Seq: ( ME_512DAFB70392_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_512DAFB70392_diagrams
