// K437519030 5146A2E8011E TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4DE4827600CA_ME_5146A2E8011E_G
 MELINK Original WL? 'ME_4DE4827600CA' // TArchiInsiderTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4DE4827600CA_ME_5146A2E8011E_G TArchiInsiderTest

%%InheritedBy ME_4DE4827600CA ME_5146A2E8011E

ME ME_5146A2E8011E
 MEPROP UID '5146A2E8011E'
 MEPROP Name 'K437519030'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:437519030}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_5146A2BE012B' // TableResize
 ;
 MELIST Inherits
   Seq: ( HWL ME_4DE4827600CA_ME_5146A2E8011E_G // TArchiInsiderTest
 )
 ; // Inherits
 UP extprop:pas:TypeName 'TK437519030'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'K437519030'
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K437519030.pas'

ENDME // ME_5146A2E8011E K437519030
