// K437519082 5152EF6E00D7 TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4DE4827600CA_ME_5152EF6E00D7_G
 MELINK Original WL? 'ME_4DE4827600CA' // TArchiInsiderTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4DE4827600CA_ME_5152EF6E00D7_G TArchiInsiderTest

%%InheritedBy ME_4DE4827600CA ME_5152EF6E00D7

ME ME_5152EF6E00D7
 MEPROP UID '5152EF6E00D7'
 MEPROP Name 'K437519082'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:437519082}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4FA4C81D0313' // TableBoundariesAlignment
 ;
 MELIST Inherits
   Seq: ( HWL ME_4DE4827600CA_ME_5152EF6E00D7_G // TArchiInsiderTest
 )
 ; // Inherits
 UP extprop:pas:TypeName 'TK437519082'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'K437519082'
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K437519082.pas'

ENDME // ME_5152EF6E00D7 K437519082
