// TReallocMemTest 51643E02018F TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_51643E02018F

ME ME_51643E2202AA
 MEPROP UID '51643E2202AA'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MELINK Stereotype st_Test ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_51643E02018F // TReallocMemTest
 ;

ENDME // ME_51643E2202AA DoIt

MEREF ME_4B2A0DDE028B_ME_51643E02018F_G
 MELINK Original WL 'ME_4B2A0DDE028B' '4B2A0DCE03A9.ms.model.script' // TTestCase
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4B2A0DDE028B_ME_51643E02018F_G TTestCase

%%InheritedBy ME_4B2A0DDE028B ME_51643E02018F

ME ME_51643E02018F
 MEPROP UID '51643E02018F'
 MEPROP Name 'TReallocMemTest'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_51643DEB0153' // Emba
 ;
 MELIST Inherits
   Seq: ( HWL ME_4B2A0DDE028B_ME_51643E02018F_G // TTestCase
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_51643E2202AA // DoIt
 )
 ; // Operations
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP extprop:pas:UnitName 'ReallocMemTest'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ReallocMemTest'
 UP intf.pas:Path 'common\components\SandBox\ReallocMemTest.pas'

ENDME // ME_51643E02018F TReallocMemTest
