// K336666483 516E5E16001A TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4E847E770184_ME_516E5E16001A_G
 MELINK Original WL? 'ME_4E847E770184' // HTMLtoEVDTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4E847E770184_ME_516E5E16001A_G HTMLtoEVDTest

%%InheritedBy ME_4E847E770184 ME_516E5E16001A

ME ME_516E5E16001A
 MEPROP UID '516E5E16001A'
 MEPROP Name 'K336666483'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:336666483}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4F86C70700BD' // 7.8
 ;
 MELIST Inherits
   Seq: ( HWL ME_4E847E770184_ME_516E5E16001A_G // HTMLtoEVDTest
 )
 ; // Inherits
 UP extprop:pas:TypeName 'TK336666483'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'K336666483'
 UP intf.pas:Path 'common\components\rtl\Garant\Daily\K336666483.pas'

ENDME // ME_516E5E16001A K336666483
