// TddTable 519B719F0019 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_519B719F0019_diagrams

 MEDIAGRAM ME_519B719F0019_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_519B719F0019' '4F6843C101D1.ms.model.script' ; // TddTable

  MEVIEW ME_54EC750000EB_view
   MELINK Original WL 'ME_54EC750000EB' '4F6843C101D1.ms.model.script' ; // ClearRows
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_54EC750000EB_view

  MEVIEW ME_54EC65A701CE_view
   MELINK Original WL 'ME_54EC65A701CE' '4F6843C101D1.ms.model.script' ; // StartRow
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_54EC65A701CE_view

  MELIST Views
   Seq: ( ME_54EC750000EB_view // ClearRows
   ME_54EC65A701CE_view // StartRow
   )
  ; // Views
 ENDMEDIAGRAM // ME_519B719F0019_main

 MELIST Diagrams
  Seq: ( ME_519B719F0019_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_519B719F0019_diagrams
