// K382406560 51A489C8039F TestCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEREF ME_4DE4827600CA_ME_51A489C8039F_G
 MELINK Original WL? 'ME_4DE4827600CA' // TArchiInsiderTest
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4DE4827600CA_ME_51A489C8039F_G TArchiInsiderTest

%%InheritedBy ME_4DE4827600CA ME_51A489C8039F

ME ME_51A489C8039F
 MEPROP UID '51A489C8039F'
 MEPROP Name 'K382406560'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_TestCase ;
 MEPROP Kind kind_NormalClass
 %SUMMARY '{Requestlink:382406560}' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4F4E07A3011C' // SelectionTests
 ;
 MELIST Inherits
   Seq: ( HWL ME_4DE4827600CA_ME_51A489C8039F_G // TArchiInsiderTest
 )
 ; // Inherits
 UP extprop:pas:TypeName 'TK382406560'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'K382406560'
 UP intf.pas:Path 'archi\source\projects\Archi\Tests\K382406560.pas'

ENDME // ME_51A489C8039F K382406560
