// dt_Jour 51B6C800005F UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_51B6C83A03E4
%%Inner ME_5281F3A90273

FORWARD ME_51B6C800005F

ME ME_51B6C83A03E4
 MEPROP UID '51B6C83A03E4'
 MEPROP Name 'TAbstractJournal'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_51B6C800005F // dt_Jour
 ;
 UP "finished" False
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'AbstractJournal'

ENDME // ME_51B6C83A03E4 TAbstractJournal

ME ME_5281F3A90273
 MEPROP UID '5281F3A90273'
 MEPROP Name 'EdtBrokenFileLock'
 MEPROP Class class_Class
 MELINK Stereotype st_Exception ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_51B6C800005F // dt_Jour
 ;

ENDME // ME_5281F3A90273 EdtBrokenFileLock

ME ME_51B6C800005F
 MEPROP UID '51B6C800005F'
 MEPROP Name 'dt_Jour'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_UtilityPack ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL 'ME_519B797A0048' '519B797A0048.ms.model.script' // Servers
 ;
 MELIST Children
   Seq: ( HWL ME_51B6C83A03E4 // TAbstractJournal
 HWL ME_5281F3A90273 // EdtBrokenFileLock
 )
 ; // Children
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "finished" False
 UP intf.pas:Path 'common\components\rtl\Garant\DT\NOT_FINISHED_dt_Jour.pas'

ENDME // ME_51B6C800005F dt_Jour
