// TdestField 51D2776D03C3 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_51D2776D03C3_diagrams

 MEDIAGRAM ME_51D2776D03C3_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_51D2776D03C3' '51D2772B035B.ms.model.script' ; // TdestField

  MEVIEW ME_54E319220123_view
   MELINK Original WL 'ME_54E319220123' '51D2772B035B.ms.model.script' ; // FielsInsruction
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_54E319220123_view

  MEVIEW ME_54E3193201C2_view
   MELINK Original WL 'ME_54E3193201C2' '51D2772B035B.ms.model.script' ; // FormField
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_54E3193201C2_view

  MEVIEW ME_54E3193E00CB_view
   MELINK Original WL 'ME_54E3193E00CB' '51D2772B035B.ms.model.script' ; // FieldResult
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_54E3193E00CB_view

  MEVIEW ME_56AB2541006B_view
   MELINK Original WL 'ME_56AB2541006B' '51D2772B035B.ms.model.script' ; // f_Private
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_56AB2541006B_view

  MELIST Views
   Seq: ( ME_54E319220123_view // FielsInsruction
   ME_54E3193201C2_view // FormField
   ME_54E3193E00CB_view // FieldResult
   ME_56AB2541006B_view // f_Private
   )
  ; // Views
 ENDMEDIAGRAM // ME_51D2776D03C3_main

 MELIST Diagrams
  Seq: ( ME_51D2776D03C3_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_51D2776D03C3_diagrams
