// TddCharacterProperty 51DBBD99020C SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_51DBBD99020C
 MEPROP UID '51DBBD99020C'
 MEPROP Name 'TddCharacterProperty'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4F6843C101D1' // ddCommon
 ;
 UP "finished" False
 UP extprop:pas:UnitName 'ddCharacterProperty'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ddCharacterProperty'
 UP intf.pas:Path 'common\components\rtl\Garant\dd\NOT_FINISHED_ddCharacterProperty.pas'

ENDME // ME_51DBBD99020C TddCharacterProperty
