// l3PtrLoc 51DD56680275 UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_51DD56680275_diagrams

 MEDIAGRAM ME_51DD56680275_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_51DD56680275' '51DD56680275.ms.model.script' ; // l3PtrLoc

  MEVIEW ME_51DD567A01B5_view
   MELINK Original WL 'ME_51DD567A01B5' '51DD56680275.ms.model.script' ; // Tl3PtrLoc
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_51DD567A01B5_view

  MELIST Views
   Seq: ( ME_51DD567A01B5_view // Tl3PtrLoc
   )
  ; // Views
 ENDMEDIAGRAM // ME_51DD56680275_main

 MELIST Diagrams
  Seq: ( ME_51DD56680275_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_51DD56680275_diagrams
