// TddJustList 51F0DBD202B0 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_51F0DBD202B0_diagrams

 MEDIAGRAM ME_51F0DBD202B0_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_51F0DBD202B0' ; // TddJustList

  MEVIEW ME_51F0DBF402BE_view
   MELINK Original WL 'ME_51F0DBF402BE' '51F0DBD202B0.ms.model.script' ; // ItemType
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_51F0DBF402BE_view

  MELIST Views
   Seq: ( ME_51F0DBF402BE_view // ItemType
   )
  ; // Views
 ENDMEDIAGRAM // ME_51F0DBD202B0_main

 MELIST Diagrams
  Seq: ( ME_51F0DBD202B0_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_51F0DBD202B0_diagrams
