// TddAppConfigVersionManager 52149B620261 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_52149B620261_diagrams

 MEDIAGRAM ME_52149B620261_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_52149B620261' '4B990EDE031A.ms.model.script' ; // TddAppConfigVersionManager

  MEVIEW ME_52315563028B_view
   MELINK Original WL 'ME_52315563028B' '4B990EDE031A.ms.model.script' ; // FindHandler
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_52315563028B_view

  MEVIEW ME_5231558003C0_view
   MELINK Original WL 'ME_5231558003C0' '4B990EDE031A.ms.model.script' ; // AddHandler
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_5231558003C0_view

  MEVIEW ME_523155A20230_view
   MELINK Original WL 'ME_523155A20230' '4B990EDE031A.ms.model.script' ; // Upgrade
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_523155A20230_view

  MELIST Views
   Seq: ( ME_52315563028B_view // FindHandler
   ME_5231558003C0_view // AddHandler
   ME_523155A20230_view // Upgrade
   )
  ; // Views
 ENDMEDIAGRAM // ME_52149B620261_main

 MELIST Diagrams
  Seq: ( ME_52149B620261_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_52149B620261_diagrams
