// ddAppConfigTFrame 5214B0290288 UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_5214B0290288_diagrams

 MEDIAGRAM ME_5214B0290288_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_5214B0290288' '5214B0290288.ms.model.script' ; // ddAppConfigTFrame

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_5214B0290288_main

 MELIST Diagrams
  Seq: ( ME_5214B0290288_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_5214B0290288_diagrams
