// Samples 5226F61C0109 Library Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_5226F7CC03C6

ME ME_5226F61C0109
 MEPROP UID '5226F61C0109'
 MEPROP Name 'Samples'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Library ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_49B1511700CA' // Shared Delphi Core
 ;
 MELIST Children
   Seq: ( WL? 'ME_5226F7CC03C6' // Samples
 )
 ; // Children
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "finished" False
 UP "gui" 'rtl'
 UP "vendor" '/external/NotFinished/Borland/Delphi'
 UP intf.pas:PathOnly '\common\components\rtl\external\NotFinished\Borland\Delphi\Samples'

ENDME // ME_5226F61C0109 Samples
