// TnsSendTestRequestToLegalAdviceEvent 525542460297 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_525542460297_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_525542460297' '497EBA4301CA.ms.model.script' ; // TnsSendTestRequestToLegalAdviceEvent

 MEVIEW ME_5255425502CE_view
  MELINK Original WL 'ME_5255425502CE' '497EBA4301CA.ms.model.script' ; // Log
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_5255425502CE_view

ENDMEDIAGRAM // ME_525542460297_main
