// Tk2TypesByHandleList 5273AB0F00C2 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_5273AB0F00C2_diagrams

 MEDIAGRAM ME_5273AB0F00C2_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_5273AB0F00C2' '49A58A1A03C4.ms.model.script' ; // Tk2TypesByHandleList

  MEVIEW ME_5273AB82035F_view
   MELINK Original WL 'ME_5273AB82035F' '49A58A1A03C4.ms.model.script' ; // l3Items_NoSort
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5273AB82035F_view

  MEVIEW ME_5273AB3D0130_view
   MELINK Original WL 'ME_5273AB3D0130' '49A58A1A03C4.ms.model.script' ; // ItemType
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_5273AB3D0130_view

  MELIST Views
   Seq: ( ME_5273AB82035F_view // l3Items_NoSort
   ME_5273AB3D0130_view // ItemType
   )
  ; // Views
 ENDMEDIAGRAM // ME_5273AB0F00C2_main

 MELIST Diagrams
  Seq: ( ME_5273AB0F00C2_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_5273AB0F00C2_diagrams
