// vcmFormSetSupport 528C931303C3 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_5289C78503E2

ME ME_528C931303C3
 MEPROP UID '528C931303C3'
 MEPROP Name 'vcmFormSetSupport'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_4790C3B8021E' '4790C3B8021E.ms.model.script' // VCM
 ;
 MELIST Children
   Seq: ( WL 'ME_5289C78503E2' '5289C78503E2.ms.model.script' // vcmFormSetFormItemList
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_47913B47006E' '47913B47006E.ms.model.script' // l3CoreObjects
 WL 'ME_499EAAE502A8' '499EAAE502A8.ms.model.script' // vcmUserControls
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.ms.model.script' // Sys
 WL 'ME_528C93040132' '528C93040132.ms.model.script' // vcmBaseTypes
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_528C931303C3 vcmFormSetSupport
