// ElVclUtils 5298DAD101A6 UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_5298DAD101A6
 MEPROP UID '5298DAD101A6'
 MEPROP Name 'ElVclUtils'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_UtilityPack ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL? 'ME_48342A280198' // elClone
 ;
 UP "finished" False
 UP intf.pas:Path 'common\components\gui\Garant\Everest\NOT_FINISHED_ElVclUtils.pas'

ENDME // ME_5298DAD101A6 ElVclUtils
