// StringCache 529F102E0065 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_529F102E0065_diagrams

 MEDIAGRAM ME_529F102E0065_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_529F102E0065' '529F102E0065.ms.model.script' ; // StringCache

  MEVIEW ME_4E71FF0D011C_view
   MELINK Original WL 'ME_4E71FF0D011C' '529F102E0065.ms.model.script' ; // nevStringCacheHackBecauseMl3Uknown
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_4E71FF0D011C_view

  MEVIEW ME_4E71FB8302C6_view
   MELINK Original WL 'ME_4E71FB8302C6' '529F102E0065.ms.model.script' ; // nevStringCache
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_4E71FB8302C6_view

  MEVIEW ME_4E71FC4D02BF_view
   MELINK Original WL 'ME_4E71FC4D02BF' '529F102E0065.ms.model.script' ; // TnevStringCache
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_4E71FC4D02BF_view

  MEVIEW ME_4E5689DF037B_view
   MELINK Original WL 'ME_4E5689DF037B' '529F102E0065.ms.model.script' ; // TevParaString
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_4E5689DF037B_view

  MELIST Views
   Seq: ( ME_4E71FF0D011C_view // nevStringCacheHackBecauseMl3Uknown
   ME_4E71FB8302C6_view // nevStringCache
   ME_4E71FC4D02BF_view // TnevStringCache
   ME_4E5689DF037B_view // TevParaString
   )
  ; // Views
 ENDMEDIAGRAM // ME_529F102E0065_main

 MELIST Diagrams
  Seq: ( ME_529F102E0065_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_529F102E0065_diagrams
