// TevdF1HyperlinkCorrector 52E0A8490387 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_52E0A8490387_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_52E0A8490387' '47ECACA70141.ms.model.script' ; // TevdF1HyperlinkCorrector

 MEVIEW ME_52E0C4770010_view
  MELINK Original WL 'ME_52E0C4770010' '47ECACA70141.ms.model.script' ; // Constants
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_52E0C4770010_view

ENDMEDIAGRAM // ME_52E0A8490387_main
