// TGUIAppTester 52F255E702F0 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_52F255E702F0_diagrams

 MEDIAGRAM ME_52F255E702F0_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_52F255E702F0' '51309A4A02FB.ms.model.script' ; // TGUIAppTester

  MEVIEW ME_52F264E400E6_view
   MELINK Original WL 'ME_52F264E400E6' '51309A4A02FB.ms.model.script' ; // TResultsPlaces
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_52F264E400E6_view

  MEVIEW ME_52F264840382_view
   MELINK Original WL 'ME_52F264840382' '51309A4A02FB.ms.model.script' ; // GetResultsPlaces
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_52F264840382_view

  MEVIEW ME_52F2651C00F4_view
   MELINK Original WL 'ME_52F2651C00F4' '51309A4A02FB.ms.model.script' ; // MakeResults
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_52F2651C00F4_view

  MELIST Views
   Seq: ( ME_52F264E400E6_view // TResultsPlaces
   ME_52F264840382_view // GetResultsPlaces
   ME_52F2651C00F4_view // MakeResults
   )
  ; // Views
 ENDMEDIAGRAM // ME_52F255E702F0_main

 MELIST Diagrams
  Seq: ( ME_52F255E702F0_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_52F255E702F0_diagrams
