// csMessageManager 52FB9F99018D UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_52FB9F99018D_diagrams

 MEDIAGRAM ME_52FB9F99018D_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_52FB9F99018D' '52F8C298005C.ms.model.script' ; // csMessageManager

  MEVIEW ME_53A2EF4001B8_view
   MELINK Original WL 'ME_53A2EF4001B8' '52F8C298005C.ms.model.script' ; // TcsMessageManager
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_53A2EF4001B8_view

  MELIST Views
   Seq: ( ME_53A2EF4001B8_view // TcsMessageManager
   )
  ; // Views
 ENDMEDIAGRAM // ME_52FB9F99018D_main

 MELIST Diagrams
  Seq: ( ME_52FB9F99018D_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_52FB9F99018D_diagrams
