// DT_AskList 52FCB4700035 UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_52FCB4700035_diagrams

 MEDIAGRAM ME_52FCB4700035_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_52FCB4700035' ; // DT_AskList

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_52FCB4700035_main

 MELIST Diagrams
  Seq: ( ME_52FCB4700035_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_52FCB4700035_diagrams
