// Tk2ToolPrimList 53231C5401CE SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_53231C5401CE_diagrams

 MEDIAGRAM ME_53231C5401CE_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_53231C5401CE' '49A58A1A03C4.ms.model.script' ; // Tk2ToolPrimList

  MEVIEW ME_53231C0A0224_view
   MELINK Original WL 'ME_53231C0A0224' '49A58A1A03C4.ms.model.script' ; // ItemType
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_53231C0A0224_view

  MELIST Views
   Seq: ( ME_53231C0A0224_view // ItemType
   )
  ; // Views
 ENDMEDIAGRAM // ME_53231C5401CE_main

 MELIST Diagrams
  Seq: ( ME_53231C5401CE_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_53231C5401CE_diagrams
