// ChromeLikeControls 533D017702F1 Library Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_533D01A201A9
%%Inner ME_53F2D7B00186
%%Inner ME_533E6F73014E
%%Inner ME_54211E53007C

ME ME_533D017702F1
 MEPROP UID '533D017702F1'
 MEPROP Name 'ChromeLikeControls'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Library ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4677DDBD0193' // Shared Delphi
 ;
 MELIST Children
   Seq: ( WL? 'ME_533D01A201A9' // ChromeLikeWindowCaptionButtons
 WL? 'ME_53F2D7B00186' // ChromeLikeInterfaces
 WL? 'ME_533E6F73014E' // ChromeLikeTabSet
 WL? 'ME_54211E53007C' // ChromeLikeFormFrameDecorator
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4684F91300DD' // Vcl
 WL? 'ME_469F3E37025A' // Rtl
 WL? 'ME_4790B4F00236' // AFW
 WL? 'ME_4790D09A0378' // L3
 WL? 'ME_4B4DCCBF034F' // JEDI
 WL? 'ME_4CFCE4F203CE' // VGScene
 WL? 'ME_4E2F0E1B03BB' // L3$Domain
 WL? 'ME_550012C403C4' // L3$AFW
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "exec mode" 'concluded'
 UP "gui" 'gui'
 UP "ifndef" 'NoVGScene, NoVCM, NoTabs'
 UP "is namespace" True
 UP "UseNewGen" True
 UP "vendor" '/Garant'
 UP intf.pas:PathOnly '\common\components\gui\Garant\ChromeLikeControls'

ENDME // ME_533D017702F1 ChromeLikeControls
