// DbInfo 537F78280242 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_537F78410340
%%Inner ME_537F78F50118
%%Inner ME_537F79160044

FORWARD ME_537F78280242

FORWARD ME_537F78410340

ME ME_537F78AB01D1
 MEPROP UID '537F78AB01D1'
 MEPROP Name 'Number'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_537F78410340 // TdtFamilyInfo
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_537F78AB01D1 Number

ME ME_537F78B50368
 MEPROP UID '537F78B50368'
 MEPROP Name 'Name'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_537F78410340 // TdtFamilyInfo
 ;
 MELINK Target WL 'ME_476136D3010B' '4807744200AA.ms.model.script' // String
 ;

ENDME // ME_537F78B50368 Name

ME ME_537F78BF00E0
 MEPROP UID '537F78BF00E0'
 MEPROP Name 'Path'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_537F78410340 // TdtFamilyInfo
 ;
 MELINK Target WL 'ME_476136D3010B' '4807744200AA.ms.model.script' // String
 ;

ENDME // ME_537F78BF00E0 Path

ME ME_537F78CA0329
 MEPROP UID '537F78CA0329'
 MEPROP Name 'DocGroup'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_537F78410340 // TdtFamilyInfo
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_537F78CA0329 DocGroup

ME ME_537F78D6036A
 MEPROP UID '537F78D6036A'
 MEPROP Name 'Attributes'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_537F78410340 // TdtFamilyInfo
 ;
 MELINK Target WL 'ME_46A606AC03B2' '4807744200AA.ms.model.script' // Integer
 ;

ENDME // ME_537F78D6036A Attributes

%%InheritedBy ME_49E7754802A9 ME_537F78410340

ME ME_537F78410340
 MEPROP UID '537F78410340'
 MEPROP Name 'TdtFamilyInfo'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_537F78280242 // DbInfo
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.ms.model.script' // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_537F78AB01D1 // Number
 HWL ME_537F78B50368 // Name
 HWL ME_537F78BF00E0 // Path
 HWL ME_537F78CA0329 // DocGroup
 HWL ME_537F78D6036A // Attributes
 )
 ; // Attributes
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP extprop:pas:UnitName 'dtFamilyInfo'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'dtFamilyInfo'
 UP intf.pas:Path 'common\components\rtl\Garant\DT\dtFamilyInfo.pas'

ENDME // ME_537F78410340 TdtFamilyInfo

FORWARD ME_537F78F50118

ME ME_537F790300F8
 MEPROP UID '537F790300F8'
 MEPROP Name 'ItemType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_537F78F50118 // TdtFamilyInfoList
 ;
 MELINK Target HWL ME_537F78410340 // TdtFamilyInfo
 ;

ENDME // ME_537F790300F8 ItemType

ME ME_47B2C42A0163_ME_537F78F50118
 MELINK Original WL 'ME_47B2C42A0163' '47A74A5F0123.ms.model.script' // AssignItem
 ;
 MEPROP OpKind opkind_Implemented
 UP "ifdef" 'l3Items_NeedsAssignItem'
 UP "ifndef" 'l3Items_NoSort'
ENDME // ME_47B2C42A0163_ME_537F78F50118 AssignItem

ME ME_47B99D4503A2_ME_537F78F50118
 MELINK Original WL 'ME_47B99D4503A2' '47B45152003F.ms.model.script' // CompareExistingItems
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_47B99D4503A2_ME_537F78F50118 CompareExistingItems

%%InheritedBy ME_47B99E920196 ME_537F78F50118
%%InheritedBy ME_4A54DD4E036F ME_537F78F50118

ME ME_537F78F50118
 MEPROP UID '537F78F50118'
 MEPROP Name 'TdtFamilyInfoList'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_537F78280242 // DbInfo
 ;
 MELIST Inherits
   Seq: ( WL? 'ME_47B99E920196' // l3UncomparabeObjectRefList
 WL 'ME_4A54DD4E036F' '47913B47006E.ms.model.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_537F790300F8 // ItemType
 )
 ; // Attributes
 MELIST Implemented
   Seq: ( ME_47B2C42A0163_ME_537F78F50118 // AssignItem
 ME_47B99D4503A2_ME_537F78F50118 // CompareExistingItems
 )
 ; // Implemented
 UP extprop:pas:UnitName 'dtFamilyInfoList'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'dtFamilyInfoList'
 UP intf.pas:Path 'common\components\rtl\Garant\DT\dtFamilyInfoList.pas'

ENDME // ME_537F78F50118 TdtFamilyInfoList

ME ME_537F78280242
 MEPROP UID '537F78280242'
 MEPROP Name 'DbInfo'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_47BC4FCB0115' // DT
 ;
 MELIST Children
   Seq: ( HWL ME_537F78410340 // TdtFamilyInfo
 HWL ME_537F78F50118 // TdtFamilyInfoList
 WL? 'ME_537F79160044' // DT_DbInfo
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_4AB0C3C60310' // Sys
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_537F78280242 DbInfo
