// Containers 537F6D320018 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_537F6D320018_diagrams

 MEDIAGRAM ME_537F6D320018_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_537F6D320018' ; // Containers

  MEVIEW ME_537F6DA00036_view
   MELINK Original WL 'ME_537F6DA00036' '537F6D320018.ms.model.script' ; // TdtNumRange
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_537F6DA00036_view

  MEVIEW ME_537F6EED0090_view
   MELINK Original WL 'ME_537F6EED0090' '537F6D320018.ms.model.script' ; // TdtNumRangeList
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_537F6EED0090_view

  MEVIEW ME_537F6D3F0319_view
   MELINK Original WL? 'ME_537F6D3F0319' ; // Dt_containers
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_537F6D3F0319_view

  MEVIEWLINK ME_537F6F040072_viewlink
   MELINK Original WL 'ME_537F6F040072' '537F6D320018.ms.model.script' ;
   MELINK From ME_537F6EED0090_view ;
   MELINK To ME_537F6DA00036_view ;
  ENDMEVIEWLINK // ME_537F6F040072_viewlink

  MELIST Views
   Seq: ( ME_537F6DA00036_view // TdtNumRange
   ME_537F6EED0090_view // TdtNumRangeList
   ME_537F6D3F0319_view // Dt_containers
   ME_537F6F040072_viewlink // TdtNumRangeList -> TdtNumRange
   )
  ; // Views
 ENDMEDIAGRAM // ME_537F6D320018_main

 MELIST Diagrams
  Seq: ( ME_537F6D320018_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_537F6D320018_diagrams
