// TcsIdIOHandlerAdapter 538DB527006C SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_538DB527006C_diagrams

 MEDIAGRAM ME_538DB527006C_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_538DB527006C' '52FBB2FC0386.ms.model.script' ; // TcsIdIOHandlerAdapter

  MEVIEW ME_538DB5610283_view
   MELINK Original WL 'ME_538DB5610283' '52FBB2FC0386.ms.model.script' ; // Create
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_538DB5610283_view

  MELIST Views
   Seq: ( ME_538DB5610283_view // Create
   )
  ; // Views
 ENDMEDIAGRAM // ME_538DB527006C_main

 MELIST Diagrams
  Seq: ( ME_538DB527006C_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_538DB527006C_diagrams
