// Создание документов-объектов 53F32B070049 UseCase Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_53F32B070049_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_53F32B070049' '53F327E402A1.ms.model.script' ; // Создание документов-объектов

 MEVIEW ME_53F32C2B0360_view
  MELINK Original WL 'ME_53F32C2B0360' '53F327E402A1.ms.model.script' ; // Создание документа-объекта на основе BMP
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_53F32C2B0360_view

 MEVIEW ME_53F330B3028B_view
  MELINK Original WL 'ME_53F330B3028B' '53F327E402A1.ms.model.script' ; // Создание документа-объекта на основе jpg
  MEPROP X 120
  MEPROP Y 10
 ENDMEVIEW // ME_53F330B3028B_view

 MEVIEW ME_53F330D20290_view
  MELINK Original WL 'ME_53F330D20290' '53F327E402A1.ms.model.script' ; // Создание документа-объекта на основе txt
  MEPROP X 230
  MEPROP Y 10
 ENDMEVIEW // ME_53F330D20290_view

 MEVIEW ME_53F330ED0068_view
  MELINK Original WL 'ME_53F330ED0068' '53F327E402A1.ms.model.script' ; // Создание документа-обекта на основе rtf
  MEPROP X 340
  MEPROP Y 10
 ENDMEVIEW // ME_53F330ED0068_view

 MEVIEW ME_53F331070085_view
  MELINK Original WL 'ME_53F331070085' '53F327E402A1.ms.model.script' ; // Создание документа-объекта на основе doc
  MEPROP X 450
  MEPROP Y 10
 ENDMEVIEW // ME_53F331070085_view

 MEVIEW ME_53F332AE03DB_view
  MELINK Original WL 'ME_53F332AE03DB' '53F327E402A1.ms.model.script' ; // Создание документа-объекта на основе pdf
  MEPROP X 560
  MEPROP Y 10
 ENDMEVIEW // ME_53F332AE03DB_view

 MEVIEW ME_53F3362701E2_view
  MELINK Original WL 'ME_53F3362701E2' '53F327E402A1.ms.model.script' ; // Создание документа-объекта на основе tiff
  MEPROP X 670
  MEPROP Y 10
 ENDMEVIEW // ME_53F3362701E2_view

 MEVIEW ME_53F338B50231_view
  MELINK Original WL 'ME_53F338B50231' '53F327E402A1.ms.model.script' ; // Создание документа-объкта из PNG
  MEPROP X 780
  MEPROP Y 10
 ENDMEVIEW // ME_53F338B50231_view

ENDMEDIAGRAM // ME_53F32B070049_main
