// Tm3StorageHolderList 542E7AD00050 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_542E7AD00050

FORWARD ME_542E9D1B0264

ME ME_542E9D2B008F
 MEPROP UID '542E9D2B008F'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_542E9D1B0264 // Exists
 ;
 MELINK Target WL 'ME_46A603BB0391' '4807744200AA.ms.model.script' // Boolean
 ;

ENDME // ME_542E9D2B008F DoIt

ME ME_542E9D1B0264
 MEPROP UID '542E9D1B0264'
 MEPROP Name 'Exists'
 MEPROP Class class_Operation
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_542E7AD00050 // Tm3StorageHolderList
 ;
 MELIST Operations
   Seq: ( HWL ME_542E9D2B008F // DoIt
 )
 ; // Operations
 UP "is static" True

ENDME // ME_542E9D1B0264 Exists

FORWARD ME_542EA0C5023C

FORWARD ME_542EA0D4038A

ME ME_55547E7602B0
 MEPROP Name 'aFileName'
 MEPROP Class class_Parameter
 MELINK Target WL 'ME_498849D803A8' '4807744200AA.ms.model.script' // WideString
 ;

ENDME // ME_55547E7602B0 aFileName

ME ME_542EA0D4038A
 MEPROP UID '542EA0D4038A'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_542EA0C5023C // Drop
 ;
 MELIST Parameters
   Seq: ( ME_55547E7602B0 // aFileName
 )
 ; // Parameters

ENDME // ME_542EA0D4038A DoIt

ME ME_542EA0C5023C
 MEPROP UID '542EA0C5023C'
 MEPROP Name 'Drop'
 MEPROP Class class_Operation
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_542E7AD00050 // Tm3StorageHolderList
 ;
 MELIST Operations
   Seq: ( HWL ME_542EA0D4038A // DoIt
 )
 ; // Operations
 UP "is static" True

ENDME // ME_542EA0C5023C Drop

ME ME_555481D1035F
 MEPROP UID '555481D1035F'
 MEPROP Name 'DropAll'
 MEPROP Class class_Operation
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_542E7AD00050 // Tm3StorageHolderList
 ;
 UP "is static" True

ENDME // ME_555481D1035F DropAll

ME ME_542E829502B2
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_542E7AD00050 // Tm3StorageHolderList
 ;
 MELINK Target WL 'ME_47614B2901AE' '4678193C009C.ms.model.script' // Tl3Duplicates
 ;

ENDME // ME_542E829502B2 

MEREF ME_47A042E100E2_ME_542E7AD00050_over
 MELINK Original WL 'ME_47A042E100E2' '47913F4E02E0.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_47A042E100E2_ME_542E7AD00050_over InitFields

MEREF ME_53A03846011C_ME_542E7AD00050_G
 MELINK Original WL? 'ME_53A03846011C' // l3CriticalSectionHolder
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_53A03846011C_ME_542E7AD00050_G l3CriticalSectionHolder

MEREF ME_542E8D2902F1_ME_542E7AD00050_G
 MELINK Original WL? 'ME_542E8D2902F1' // Tm3StorageHolderListPrim1
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_542E8D2902F1_ME_542E7AD00050_G Tm3StorageHolderListPrim1

%%InheritedBy ME_53A03846011C ME_542E7AD00050
%%InheritedBy ME_542E8D2902F1 ME_542E7AD00050

ME ME_542E7AD00050
 MEPROP UID '542E7AD00050'
 MEPROP Name 'Tm3StorageHolderList'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_5486E32B0191' // StorageHolder
 ;
 MELIST Inherits
   Seq: ( HWL ME_53A03846011C_ME_542E7AD00050_G // l3CriticalSectionHolder
 HWL ME_542E8D2902F1_ME_542E7AD00050_G // Tm3StorageHolderListPrim1
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_542E9D1B0264 // Exists
 HWL ME_542EA0C5023C // Drop
 HWL ME_555481D1035F // DropAll
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_47A042E100E2_ME_542E7AD00050_over // InitFields
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_542E829502B2 // Tl3Duplicates
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "singleton" True
 UP extprop:pas:UnitName 'm3StorageHolderList'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'm3StorageHolderList'
 UP intf.pas:Path 'common\components\rtl\Garant\m3\m3StorageHolderList.pas'

ENDME // ME_542E7AD00050 Tm3StorageHolderList
