// Messages 544E0148010D Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_544E0148010D

FORWARD ME_544E079E0253

ME ME_544E07C6034D
 MEPROP UID '544E07C6034D'
 MEPROP Name 'TncsLoginMessage'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( HWL ME_544E079E0253 // TncsMessage
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_544E02580378' '484A470100DD.ms.model.script' // csLogin
 )
 ; // Implements
 UP extprop:pas:UnitName 'ncsLoginMessage'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsLoginMessage'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsLoginMessage.pas'

ENDME // ME_544E07C6034D TncsLoginMessage

FORWARD ME_544F977F036B

ME ME_544F98080257
 MEPROP UID '544F98080257'
 MEPROP Name 'ItemType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544F977F036B // TncsPriorityMessageList
 ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_544F98080257 ItemType

ME ME_5450AE6C031E
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544F977F036B // TncsPriorityMessageList
 ;
 MELINK Target WL 'ME_4E8C103D01B1' '4AB0997B00A2.ms.model.script' // Sign
 ;

ENDME // ME_5450AE6C031E 

ME ME_47B2C42A0163_ME_544F977F036B
 MELINK Original WL 'ME_47B2C42A0163' '47913B47006E.ms.model.script' // AssignItem
 ;
 MEPROP OpKind opkind_Implemented
 UP "ifdef" 'l3Items_NeedsAssignItem'
 UP "ifndef" 'l3Items_NoSort'
ENDME // ME_47B2C42A0163_ME_544F977F036B AssignItem

ME ME_47B99D4503A2_ME_544F977F036B
 MELINK Original WL 'ME_47B99D4503A2' '47BB24D30205.ms.model.script' // CompareExistingItems
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_47B99D4503A2_ME_544F977F036B CompareExistingItems

ME ME_544F977F036B
 MEPROP UID '544F977F036B'
 MEPROP Name 'TncsPriorityMessageList'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Список сортированый по приоритету и дате сообщения' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.ms.model.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_47B99E920196' '47913B47006E.ms.model.script' // l3UncomparabeObjectRefList
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_544F98080257 // ItemType
 )
 ; // Attributes
 MELIST Implemented
   Seq: ( ME_47B2C42A0163_ME_544F977F036B // AssignItem
 ME_47B99D4503A2_ME_544F977F036B // CompareExistingItems
 )
 ; // Implemented
 MELIST Dependencies
   Seq: ( ME_5450AE6C031E // Sign
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsPriorityMessageList'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsPriorityMessageList'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsPriorityMessageList.pas'

ENDME // ME_544F977F036B TncsPriorityMessageList

FORWARD ME_544E3C54031D

ME ME_545A157B02C2
 MEPROP UID '545A157B02C2'
 MEPROP Name 'Processing'
 MEPROP Class class_Attribute
 MELINK Stereotype st_property::Attribute ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_545A157B02C2 Processing

ME ME_544F981C03B5
 MEPROP UID '544F981C03B5'
 MEPROP Name 'f_Data'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 MELINK Target HWL ME_544F977F036B // TncsPriorityMessageList
 ;

ENDME // ME_544F981C03B5 f_Data

ME ME_544F98B70016
 MEPROP UID '544F98B70016'
 MEPROP Name 'f_DataReadyEvent'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 MELINK Target WL 'ME_491D9DB8010F' '4AB0997B00A2.ms.model.script' // TEvent
 ;

ENDME // ME_544F98B70016 f_DataReadyEvent

ME ME_5451F97902B8
 MEPROP UID '5451F97902B8'
 MEPROP Name 'SignalMessageReady'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;

ENDME // ME_5451F97902B8 SignalMessageReady

FORWARD ME_544E3DE3032D

ME ME_544E3E0101A1
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_544E3E0101A1 aMessage

ME ME_544E3DE3032D
 MEPROP UID '544E3DE3032D'
 MEPROP Name 'Push'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 MELIST Parameters
   Seq: ( ME_544E3E0101A1 // aMessage
 )
 ; // Parameters

ENDME // ME_544E3DE3032D Push

FORWARD ME_5452022F026A

ME ME_545220540371
 MEPROP Name 'aTimeOut'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_47BC524C0245' '4AB0C3C60310.ms.model.script' // LongWord
 ;
 MEPROP Value 'INFINITE'
 MELINK ValueType WL 'ME_483C21B0003E' '4AB0C3F60375.ms.model.script' // Timeouts
 ;
 UP extprop:pas:Value 'INFINITE'

ENDME // ME_545220540371 aTimeOut

ME ME_5452022F026A
 MEPROP UID '5452022F026A'
 MEPROP Name 'WaitForMessage'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 MELIST Parameters
   Seq: ( ME_545220540371 // aTimeOut
 )
 ; // Parameters

ENDME // ME_5452022F026A WaitForMessage

FORWARD ME_545202810200

ME ME_545202900301
 MEPROP Name 'theMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_out ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_545202900301 theMessage

ME ME_545202810200
 MEPROP UID '545202810200'
 MEPROP Name 'ExtractMessage'
 MEPROP Class class_Operation
 %SUMMARY 'Увеличивает счетчик theMessage! Требуется theMessage.Free' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 MELIST Parameters
   Seq: ( ME_545202900301 // theMessage
 )
 ; // Parameters

ENDME // ME_545202810200 ExtractMessage

ME ME_5450B0EF02BD
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_5450B0EF02BD 

ME ME_5450D0510367
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 MELINK Target WL 'ME_47614B2901AE' '4678193C009C.ms.model.script' // Tl3Duplicates
 ;

ENDME // ME_5450D0510367 

ME ME_5450D7950321
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544E3C54031D // TncsMessageQueue
 ;
 MELINK Target WL 'ME_54509FEC02EB' '47D0290B016D.ms.model.script' // l3CreateStringGUID
 ;

ENDME // ME_5450D7950321 

ME ME_479731C50290_ME_544E3C54031D
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_544E3C54031D Cleanup

ME ME_47A042E100E2_ME_544E3C54031D
 MELINK Original WL 'ME_47A042E100E2' '47913B47006E.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_544E3C54031D InitFields

ME ME_544E3C54031D
 MEPROP UID '544E3C54031D'
 MEPROP Name 'TncsMessageQueue'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.ms.model.script' // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_53A03846011C' '53A038340371.ms.model.script' // l3CriticalSectionHolder
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_545A157B02C2 // Processing
 HWL ME_544F981C03B5 // f_Data
 HWL ME_544F98B70016 // f_DataReadyEvent
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_5451F97902B8 // SignalMessageReady
 HWL ME_544E3DE3032D // Push
 HWL ME_5452022F026A // WaitForMessage
 HWL ME_545202810200 // ExtractMessage
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_544E3C54031D // Cleanup
 ME_47A042E100E2_ME_544E3C54031D // InitFields
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_5450B0EF02BD // FreeAndNil
 ME_5450D0510367 // Tl3Duplicates
 ME_5450D7950321 // l3CreateStringGUID
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsMessageQueue'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsMessageQueue'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsMessageQueue.pas'

ENDME // ME_544E3C54031D TncsMessageQueue

FORWARD ME_5452248C02B8

ME ME_5450EA090093
 MEPROP UID '5450EA090093'
 MEPROP Name 'Queue'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5452248C02B8 // TncsTransporterThread
 ;
 MELINK Target HWL ME_544E3C54031D // TncsMessageQueue
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_5450EA090093 Queue

FORWARD ME_5450EAAA0367

FORWARD ME_5450EAC70263

ME ME_5450EAE301E1
 MEPROP Name 'anQueue'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E3C54031D // TncsMessageQueue
 ;

ENDME // ME_5450EAE301E1 anQueue

ME ME_5450EAC70263
 MEPROP UID '5450EAC70263'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5450EAAA0367 // Create
 ;
 MELIST Parameters
   Seq: ( ME_5450EAE301E1 // anQueue
 )
 ; // Parameters

ENDME // ME_5450EAC70263 DoIt

ME ME_5450EAAA0367
 MEPROP UID '5450EAAA0367'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5452248C02B8 // TncsTransporterThread
 ;
 MELIST Operations
   Seq: ( HWL ME_5450EAC70263 // DoIt
 )
 ; // Operations

ENDME // ME_5450EAAA0367 Create

FORWARD ME_5459DB98029C

ME ME_5459DBA700DB
 MEPROP UID '5459DBA700DB'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5459DB98029C // TerminatedConnection
 ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;

ENDME // ME_5459DBA700DB DoIt

ME ME_5459DB98029C
 MEPROP UID '5459DB98029C'
 MEPROP Name 'TerminatedConnection'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5452248C02B8 // TncsTransporterThread
 ;
 MELIST Operations
   Seq: ( HWL ME_5459DBA700DB // DoIt
 )
 ; // Operations

ENDME // ME_5459DB98029C TerminatedConnection

ME ME_54523C2D01FF
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5452248C02B8 // TncsTransporterThread
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_54523C2D01FF 

ME ME_4911B69E037D_ME_5452248C02B8
 MELINK Original WL 'ME_4911B69E037D' '47913B47006E.ms.model.script' // DoExecute
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_4911B69E037D_ME_5452248C02B8 DoExecute

ME ME_479731C50290_ME_5452248C02B8
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_5452248C02B8 Cleanup

ME ME_5452248C02B8
 MEPROP UID '5452248C02B8'
 MEPROP Name 'TncsTransporterThread'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4911B24C01F6' '47913B47006E.ms.model.script' // Tl3ThreadContainer
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_5450EA090093 // Queue
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_5450EAAA0367 // Create
 HWL ME_5459DB98029C // TerminatedConnection
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_4911B69E037D_ME_5452248C02B8 // DoExecute
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_5452248C02B8 // Cleanup
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_54523C2D01FF // FreeAndNil
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsTransporterThread'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsTransporterThread'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsTransporterThread.pas'

ENDME // ME_5452248C02B8 TncsTransporterThread

FORWARD ME_5460B6230039

ME ME_545224C80036
 MEPROP UID '545224C80036'
 MEPROP Name 'IOHandler'
 MEPROP Class class_Attribute
 MELINK Stereotype st_property::Attribute ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5460B6230039 // TncsTransporterIOThread
 ;
 MELINK Target WL 'ME_538DDC890328' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAbstractAdapter
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_545224C80036 IOHandler

ME ME_545B3DEA0268
 MEPROP UID '545B3DEA0268'
 MEPROP Name 'ReleaseIOHandler'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5460B6230039 // TncsTransporterIOThread
 ;

ENDME // ME_545B3DEA0268 ReleaseIOHandler

ME ME_5460BE3D03E2
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5460B6230039 // TncsTransporterIOThread
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_5460BE3D03E2 

ME ME_479731C50290_ME_5460B6230039
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_5460B6230039 Cleanup

ME ME_5459DB98029C_ME_5460B6230039
 MELINK Original HWL ME_5459DB98029C // TerminatedConnection
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_5459DB98029C_ME_5460B6230039 TerminatedConnection

ME ME_5460B6230039
 MEPROP UID '5460B6230039'
 MEPROP Name 'TncsTransporterIOThread'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( HWL ME_5452248C02B8 // TncsTransporterThread
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_545224C80036 // IOHandler
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_545B3DEA0268 // ReleaseIOHandler
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_5460B6230039 // Cleanup
 ME_5459DB98029C_ME_5460B6230039 // TerminatedConnection
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_5460BE3D03E2 // FreeAndNil
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsTransporterIOThread'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsTransporterIOThread'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsTransporterIOThread.pas'

ENDME // ME_5460B6230039 TncsTransporterIOThread

FORWARD ME_54534F1A00BF

FORWARD ME_5453828F0059

ME ME_545382B4034A
 MEPROP UID '545382B4034A'
 MEPROP Name 'c_ReadTimeout'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5453828F0059 // ThreadTimeouts
 ;
 MEPROP Value 300
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value 300

ENDME // ME_545382B4034A c_ReadTimeout

ME ME_5453828F0059
 MEPROP UID '5453828F0059'
 MEPROP Name 'ThreadTimeouts'
 MEPROP Class class_Class
 MELINK Stereotype st_Constants ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 MELIST Attributes
   Seq: ( HWL ME_545382B4034A // c_ReadTimeout
 )
 ; // Attributes
 UP "spell names" False

ENDME // ME_5453828F0059 ThreadTimeouts

ME ME_5453795603AE
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 MELINK Target WL 'ME_47E150FF028A' '4AB0997B00A2.ms.model.script' // TStream
 ;

ENDME // ME_5453795603AE 

ME ME_5453795B02A8
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 MELINK Target WL 'ME_538DE3F001DC' '47913B47006E.ms.model.script' // Tl3TempMemoryStream
 ;

ENDME // ME_5453795B02A8 

ME ME_545388B80110
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_545388B80110 

ME ME_54538F000128
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 MELINK Target WL 'ME_4CDD241C0184' '47913B47006E.ms.model.script' // l3System
 ;

ENDME // ME_54538F000128 

ME ME_54539217001B
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_54539217001B 

FORWARD ME_54539F4702B1

ME ME_545B8147003C
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 MELINK Target HWL ME_54539F4702B1 // TncsMessageFactory
 ;

ENDME // ME_545B8147003C 

ME ME_546306C60283
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 MELINK Target WL 'ME_5461CFB8002C' '484A470100DD.ms.model.script' // TncsMessageKind
 ;

ENDME // ME_546306C60283 

FORWARD ME_548AC7FB0046

ME ME_548AC9510214
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 MELINK Target HWL ME_548AC7FB0046 // ncsProfile
 ;

ENDME // ME_548AC9510214 

ME ME_4911B69E037D_ME_54534F1A00BF
 MELINK Original WL 'ME_4911B69E037D' '47913B47006E.ms.model.script' // DoExecute
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_4911B69E037D_ME_54534F1A00BF DoExecute

ME ME_54534F1A00BF
 MEPROP UID '54534F1A00BF'
 MEPROP Name 'TncsReceiveThread'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( HWL ME_5460B6230039 // TncsTransporterIOThread
 )
 ; // Inherits
 MELIST Overridden
   Seq: ( ME_4911B69E037D_ME_54534F1A00BF // DoExecute
 )
 ; // Overridden
 MELIST Constants
   Seq: ( HWL ME_5453828F0059 // ThreadTimeouts
 )
 ; // Constants
 MELIST Dependencies
   Seq: ( ME_5453795603AE // TStream
 ME_5453795B02A8 // Tl3TempMemoryStream
 ME_545388B80110 // FreeAndNil
 ME_54538F000128 // l3System
 ME_54539217001B // TncsMessage
 ME_545B8147003C // TncsMessageFactory
 ME_546306C60283 // TncsMessageKind
 ME_548AC9510214 // ncsProfile
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsReceiveThread'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsReceiveThread'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsReceiveThread.pas'

ENDME // ME_54534F1A00BF TncsReceiveThread

FORWARD ME_5461D6C30025

ME ME_5461D95F00E6
 MEPROP UID '5461D95F00E6'
 MEPROP Name 'Message'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_5461D95F00E6 Message

ME ME_5461D977016B
 MEPROP UID '5461D977016B'
 MEPROP Name 'Reply'
 MEPROP Class class_Attribute
 MELINK Stereotype st_property::Attribute ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_5461D977016B Reply

ME ME_5463228D00A9
 MEPROP UID '5463228D00A9'
 MEPROP Name 'f_Event'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 MELINK Target WL 'ME_491D9DB8010F' '4AB0997B00A2.ms.model.script' // TEvent
 ;

ENDME // ME_5463228D00A9 f_Event

FORWARD ME_5461D8CE0020

FORWARD ME_5461D8D70179

ME ME_5461D8E50366
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_5461D8E50366 aMessage

ME ME_5461D8D70179
 MEPROP UID '5461D8D70179'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5461D8CE0020 // Create
 ;
 MELIST Parameters
   Seq: ( ME_5461D8E50366 // aMessage
 )
 ; // Parameters

ENDME // ME_5461D8D70179 DoIt

ME ME_5461D8CE0020
 MEPROP UID '5461D8CE0020'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 MELIST Operations
   Seq: ( HWL ME_5461D8D70179 // DoIt
 )
 ; // Operations

ENDME // ME_5461D8CE0020 Create

FORWARD ME_5463220800C9

ME ME_54633E840128
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5463220800C9 // RequestEvent
 ;
 MELINK Target WL 'ME_54509FEC02EB' '47D0290B016D.ms.model.script' // l3CreateStringGUID
 ;

ENDME // ME_54633E840128 

ME ME_5463220800C9
 MEPROP UID '5463220800C9'
 MEPROP Name 'RequestEvent'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 MELIST Dependencies
   Seq: ( ME_54633E840128 // l3CreateStringGUID
 )
 ; // Dependencies

ENDME // ME_5463220800C9 RequestEvent

FORWARD ME_546335030341

FORWARD ME_546335100360

ME ME_54633B0002A6
 MEPROP Name 'aTimeOut'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_47BC524C0245' '4AB0C3C60310.ms.model.script' // LongWord
 ;
 MEPROP Value 'INFINITE'
 MELINK ValueType WL 'ME_483C21B0003E' '4AB0C3F60375.ms.model.script' // Timeouts
 ;
 UP extprop:pas:Value 'INFINITE'

ENDME // ME_54633B0002A6 aTimeOut

ME ME_546335100360
 MEPROP UID '546335100360'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_546335030341 // WaitForReply
 ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 MELIST Parameters
   Seq: ( ME_54633B0002A6 // aTimeOut
 )
 ; // Parameters

ENDME // ME_546335100360 DoIt

ME ME_546335030341
 MEPROP UID '546335030341'
 MEPROP Name 'WaitForReply'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 MELIST Operations
   Seq: ( HWL ME_546335100360 // DoIt
 )
 ; // Operations

ENDME // ME_546335030341 WaitForReply

ME ME_5464AAB30031
 MEPROP UID '5464AAB30031'
 MEPROP Name 'AbortWait'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;

ENDME // ME_5464AAB30031 AbortWait

ME ME_5461FCBB01A1
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_5461FCBB01A1 

ME ME_5463354D01FF
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 MELINK Target WL 'ME_4CDD241C0184' '47913B47006E.ms.model.script' // l3System
 ;

ENDME // ME_5463354D01FF 

ME ME_479731C50290_ME_5461D6C30025
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_5461D6C30025 Cleanup

ME ME_5461D6C30025
 MEPROP UID '5461D6C30025'
 MEPROP Name 'TncsReplyDescription'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.ms.model.script' // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_5461D95F00E6 // Message
 HWL ME_5461D977016B // Reply
 HWL ME_5463228D00A9 // f_Event
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_5461D8CE0020 // Create
 HWL ME_5463220800C9 // RequestEvent
 HWL ME_546335030341 // WaitForReply
 HWL ME_5464AAB30031 // AbortWait
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_5461D6C30025 // Cleanup
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_5461FCBB01A1 // FreeAndNil
 ME_5463354D01FF // l3System
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsReplyDescription'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsReplyDescription'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsReplyDescription.pas'

ENDME // ME_5461D6C30025 TncsReplyDescription

FORWARD ME_5460A4DB018A

FORWARD ME_5464B4730055

ME ME_5465AB2B00CA
 MEPROP UID '5465AB2B00CA'
 MEPROP Name 'Connected'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 %SUMMARY 'Есть физический коннект' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_lnk
 MELINK Parent HWL ME_5464B4730055 // IncsTransporter
 ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 UP "pm" False

ENDME // ME_5465AB2B00CA Connected

ME ME_546608F101DE
 MEPROP UID '546608F101DE'
 MEPROP Name 'ClientID'
 MEPROP Class class_Attribute
 MELINK Stereotype st_property::Attribute ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_lnk
 MELINK Parent HWL ME_5464B4730055 // IncsTransporter
 ;
 MELINK Target WL 'ME_537F4A04037C' '52FBB2FC0386.ms.model.script' // TCsClientId
 ;
 UP "pm" False

ENDME // ME_546608F101DE ClientID

ME ME_5486B96A0025
 MEPROP UID '5486B96A0025'
 MEPROP Name 'Processing'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 %SUMMARY 'Есть полноценная обработка сообщений' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_lnk
 MELINK Parent HWL ME_5464B4730055 // IncsTransporter
 ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 UP "pm" False

ENDME // ME_5486B96A0025 Processing

ME ME_548FEF4F002E
 MEPROP UID '548FEF4F002E'
 MEPROP Name 'SessionID'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_lnk
 MELINK Parent HWL ME_5464B4730055 // IncsTransporter
 ;
 MELINK Target WL 'ME_476136D3010B' '4AB0C3C60310.ms.model.script' // String
 ;
 UP "pm" False

ENDME // ME_548FEF4F002E SessionID

FORWARD ME_5464B4E900DA

ME ME_5464B4F800B5
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_5464B4F800B5 aMessage

ME ME_5464B4E900DA
 MEPROP UID '5464B4E900DA'
 MEPROP Name 'Send'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_5464B4730055 // IncsTransporter
 ;
 MELIST Parameters
   Seq: ( ME_5464B4F800B5 // aMessage
 )
 ; // Parameters

ENDME // ME_5464B4E900DA Send

FORWARD ME_5464B52F02D5

ME ME_547C4DC000DF
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_547C4DC000DF aMessage

ME ME_547C4DC0010E
 MEPROP Name 'theReply'
 MEPROP Class class_Parameter
 MELINK Stereotype st_inout ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_547C4DC0010E theReply

ME ME_547C4DC0014D
 MEPROP Name 'aTimeOut'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_47BC524C0245' '4AB0C3C60310.ms.model.script' // LongWord
 ;
 MEPROP Value 'INFINITE'
 MELINK ValueType WL 'ME_483C21B0003E' '4AB0C3F60375.ms.model.script' // Timeouts
 ;
 UP extprop:pas:Value 'INFINITE'

ENDME // ME_547C4DC0014D aTimeOut

ME ME_5464B52F02D5
 MEPROP UID '5464B52F02D5'
 MEPROP Name 'WaitForReply'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_5464B4730055 // IncsTransporter
 ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 MELIST Parameters
   Seq: ( ME_547C4DC000DF // aMessage
 ME_547C4DC0010E // theReply
 ME_547C4DC0014D // aTimeOut
 )
 ; // Parameters

ENDME // ME_5464B52F02D5 WaitForReply

ME ME_5464B4730055
 MEPROP UID '5464B4730055'
 MEPROP GUID 'CE5512DA-5FA9-423C-A266-65F24CF2501C'
 MEPROP Name 'IncsTransporter'
 MEPROP Class class_Class
 MELINK Stereotype st_Facet ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 MELIST Attributes
   Seq: ( HWL ME_5465AB2B00CA // Connected
 HWL ME_546608F101DE // ClientID
 HWL ME_5486B96A0025 // Processing
 HWL ME_548FEF4F002E // SessionID
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_5464B4E900DA // Send
 HWL ME_5464B52F02D5 // WaitForReply
 )
 ; // Operations
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsTransporter'

ENDME // ME_5464B4730055 IncsTransporter

FORWARD ME_5464B37E01ED

ME ME_5464B4A20373
 MEPROP UID '5464B4A20373'
 MEPROP Name 'rMessage'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_ref
 MELINK Parent HWL ME_5464B37E01ED // TncsExecuteContext
 ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_5464B4A20373 rMessage

ME ME_5464B4B80072
 MEPROP UID '5464B4B80072'
 MEPROP Name 'rTransporter'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_ref
 MELINK Parent HWL ME_5464B37E01ED // TncsExecuteContext
 ;
 MELINK Target HWL ME_5464B4730055 // IncsTransporter
 ;

ENDME // ME_5464B4B80072 rTransporter

FORWARD ME_5464B3AA0087

FORWARD ME_5464B3B5000D

ME ME_5464B3D00211
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_5464B3D00211 aMessage

ME ME_5464B78E0275
 MEPROP Name 'aTransporter'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_5464B4730055 // IncsTransporter
 ;

ENDME // ME_5464B78E0275 aTransporter

ME ME_5464B3B5000D
 MEPROP UID '5464B3B5000D'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5464B3AA0087 // C
 ;
 MELIST Parameters
   Seq: ( ME_5464B3D00211 // aMessage
 ME_5464B78E0275 // aTransporter
 )
 ; // Parameters

ENDME // ME_5464B3B5000D DoIt

ME ME_5464B3AA0087
 MEPROP UID '5464B3AA0087'
 MEPROP Name 'C'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5464B37E01ED // TncsExecuteContext
 ;
 MELIST Operations
   Seq: ( HWL ME_5464B3B5000D // DoIt
 )
 ; // Operations

ENDME // ME_5464B3AA0087 C

ME ME_5464B37E01ED
 MEPROP UID '5464B37E01ED'
 MEPROP Name 'TncsExecuteContext'
 MEPROP Class class_Class
 MELINK Stereotype st_StaticObject ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 MELIST Attributes
   Seq: ( HWL ME_5464B4A20373 // rMessage
 HWL ME_5464B4B80072 // rTransporter
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_5464B3AA0087 // C
 )
 ; // Operations
 UP extprop:rc:SelfName 'ncsExecuteContext'

ENDME // ME_5464B37E01ED TncsExecuteContext

FORWARD ME_5460731E025E

FORWARD ME_54607DDC0159

ME ME_5464B3F4039B
 MEPROP Name 'aContext'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_5464B37E01ED // TncsExecuteContext
 ;

ENDME // ME_5464B3F4039B aContext

ME ME_54607DDC0159
 MEPROP UID '54607DDC0159'
 MEPROP Name 'Execute'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_5460731E025E // IncsExecutor
 ;
 MELIST Parameters
   Seq: ( ME_5464B3F4039B // aContext
 )
 ; // Parameters

ENDME // ME_54607DDC0159 Execute

ME ME_5460731E025E
 MEPROP UID '5460731E025E'
 MEPROP GUID 'A6EB1A21-7939-4C8E-B5BC-65A97C27D138'
 MEPROP Name 'IncsExecutor'
 MEPROP Class class_Class
 MELINK Stereotype st_Facet ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 MELIST Operations
   Seq: ( HWL ME_54607DDC0159 // Execute
 )
 ; // Operations
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsExecutor'

ENDME // ME_5460731E025E IncsExecutor

FORWARD ME_5460829B0384

FORWARD ME_546082B801F3

ME ME_5460A53E01D7
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_5460A53E01D7 aMessage

ME ME_546082B801F3
 MEPROP UID '546082B801F3'
 MEPROP Name 'MakeExecutor'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_5460829B0384 // IncsMessageExecutorFactory
 ;
 MELINK Target HWL ME_5460731E025E // IncsExecutor
 ;
 MELIST Parameters
   Seq: ( ME_5460A53E01D7 // aMessage
 )
 ; // Parameters

ENDME // ME_546082B801F3 MakeExecutor

ME ME_5460829B0384
 MEPROP UID '5460829B0384'
 MEPROP GUID 'EB847F25-81CC-421B-ADFF-D135A33AC78B'
 MEPROP Name 'IncsMessageExecutorFactory'
 MEPROP Class class_Class
 MELINK Stereotype st_Facet ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 MELIST Operations
   Seq: ( HWL ME_546082B801F3 // MakeExecutor
 )
 ; // Operations
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsMessageExecutorFactory'

ENDME // ME_5460829B0384 IncsMessageExecutorFactory

ME ME_5460C1A00144
 MEPROP UID '5460C1A00144'
 MEPROP Name 'PIncsMessageExecutorFactory'
 MEPROP Class class_Class
 MELINK Stereotype st_Typedef ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 MELIST Inherits
   Seq: ( HWL ME_5460829B0384 // IncsMessageExecutorFactory
 )
 ; // Inherits
 UP "isPointer" True
 UP extprop:rc:isAcceptableForScripts True

ENDME // ME_5460C1A00144 PIncsMessageExecutorFactory

FORWARD ME_5465A598039E

FORWARD ME_544A1FD802E9

ME ME_5451F5060233
 MEPROP Name 'aServerHost'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_476136D3010B' '4AB0C3C60310.ms.model.script' // String
 ;

ENDME // ME_5451F5060233 aServerHost

ME ME_5451F5060262
 MEPROP Name 'aServerPort'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A606AC03B2' '4AB0C3C60310.ms.model.script' // Integer
 ;

ENDME // ME_5451F5060262 aServerPort

ME ME_548FEFC000C2
 MEPROP Name 'aSessionID'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_476136D3010B' '4AB0C3C60310.ms.model.script' // String
 ;

ENDME // ME_548FEFC000C2 aSessionID

ME ME_544A1FD802E9
 MEPROP UID '544A1FD802E9'
 MEPROP Name 'Connect'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5465A598039E // IncsClientTransporter
 ;
 MELIST Parameters
   Seq: ( ME_5451F5060233 // aServerHost
 ME_5451F5060262 // aServerPort
 ME_548FEFC000C2 // aSessionID
 )
 ; // Parameters

ENDME // ME_544A1FD802E9 Connect

FORWARD ME_544A1FF00062

ME ME_547C1A5702EF
 MEPROP Name 'Immidiate'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 MEPROP Value False
 MELINK ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 UP extprop:pas:Value False

ENDME // ME_547C1A5702EF Immidiate

ME ME_544A1FF00062
 MEPROP UID '544A1FF00062'
 MEPROP Name 'Disconnect'
 MEPROP Class class_Operation
 %SUMMARY 'Immidiate = True - отрубить сразу'#13#10'Immidiate = False - дождаться завершения обмена послав ncsDisconnect и дождавшись ответа' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_5465A598039E // IncsClientTransporter
 ;
 MELIST Parameters
   Seq: ( ME_547C1A5702EF // Immidiate
 )
 ; // Parameters

ENDME // ME_544A1FF00062 Disconnect

ME ME_5464B4E900DA_ME_5465A598039E
 MELINK Original HWL ME_5464B4E900DA // Send
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5464B4E900DA_ME_5465A598039E Send

ME ME_5464B52F02D5_ME_5465A598039E
 MELINK Original HWL ME_5464B52F02D5 // WaitForReply
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5464B52F02D5_ME_5465A598039E WaitForReply

ME ME_5465AB2B00CA_ME_5465A598039E
 MELINK Original HWL ME_5465AB2B00CA // Connected
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_5465AB2B00CA_ME_5465A598039E Connected

ME ME_546608F101DE_ME_5465A598039E
 MELINK Original HWL ME_546608F101DE // ClientID
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_546608F101DE_ME_5465A598039E ClientID

ME ME_5486B96A0025_ME_5465A598039E
 MELINK Original HWL ME_5486B96A0025 // Processing
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_5486B96A0025_ME_5465A598039E Processing

ME ME_548FEF4F002E_ME_5465A598039E
 MELINK Original HWL ME_548FEF4F002E // SessionID
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_548FEF4F002E_ME_5465A598039E SessionID

ME ME_5465A598039E
 MEPROP UID '5465A598039E'
 MEPROP GUID 'CD83C556-C3C5-40FA-91B1-6C1CA7CF87D7'
 MEPROP Name 'IncsClientTransporter'
 MEPROP Class class_Class
 MELINK Stereotype st_Facet ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 MELIST Inherits
   Seq: ( HWL ME_5464B4730055 // IncsTransporter
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_544A1FD802E9 // Connect
 HWL ME_544A1FF00062 // Disconnect
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_5464B4E900DA_ME_5465A598039E // Send
 ME_5464B52F02D5_ME_5465A598039E // WaitForReply
 ME_5465AB2B00CA_ME_5465A598039E // Connected
 ME_546608F101DE_ME_5465A598039E // ClientID
 ME_5486B96A0025_ME_5465A598039E // Processing
 ME_548FEF4F002E_ME_5465A598039E // SessionID
 )
 ; // Implemented
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsClientTransporter'

ENDME // ME_5465A598039E IncsClientTransporter

FORWARD ME_5465A5AB0324

ME ME_5459E3150030
 MEPROP UID '5459E3150030'
 MEPROP Name 'Terminated'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 UP "pm" False

ENDME // ME_5459E3150030 Terminated

FORWARD ME_545335BF0283

ME ME_5492AD2202E7
 MEPROP Name 'IsMainSocket'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;

ENDME // ME_5492AD2202E7 IsMainSocket

ME ME_545335BF0283
 MEPROP UID '545335BF0283'
 MEPROP Name 'ProcessMessages'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 MELIST Parameters
   Seq: ( ME_5492AD2202E7 // IsMainSocket
 )
 ; // Parameters

ENDME // ME_545335BF0283 ProcessMessages

FORWARD ME_5459D46D01FE

ME ME_545CC00401A7
 MEPROP Name 'WaitForTermination'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 MEPROP Value True
 MELINK ValueType WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 UP extprop:pas:Value True

ENDME // ME_545CC00401A7 WaitForTermination

ME ME_5459D46D01FE
 MEPROP UID '5459D46D01FE'
 MEPROP Name 'Terminate'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 MELIST Parameters
   Seq: ( ME_545CC00401A7 // WaitForTermination
 )
 ; // Parameters

ENDME // ME_5459D46D01FE Terminate

FORWARD ME_549180E701E0

ME ME_54918100017A
 MEPROP Name 'aHandler'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_538DDC890328' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAbstractAdapter
 ;

ENDME // ME_54918100017A aHandler

ME ME_549180E701E0
 MEPROP UID '549180E701E0'
 MEPROP Name 'RegisterSendBackHandler'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 MELIST Parameters
   Seq: ( ME_54918100017A // aHandler
 )
 ; // Parameters

ENDME // ME_549180E701E0 RegisterSendBackHandler

ME ME_5464B4E900DA_ME_5465A5AB0324
 MELINK Original HWL ME_5464B4E900DA // Send
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5464B4E900DA_ME_5465A5AB0324 Send

ME ME_5464B52F02D5_ME_5465A5AB0324
 MELINK Original HWL ME_5464B52F02D5 // WaitForReply
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5464B52F02D5_ME_5465A5AB0324 WaitForReply

ME ME_5465AB2B00CA_ME_5465A5AB0324
 MELINK Original HWL ME_5465AB2B00CA // Connected
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_5465AB2B00CA_ME_5465A5AB0324 Connected

ME ME_546608F101DE_ME_5465A5AB0324
 MELINK Original HWL ME_546608F101DE // ClientID
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_546608F101DE_ME_5465A5AB0324 ClientID

ME ME_5486B96A0025_ME_5465A5AB0324
 MELINK Original HWL ME_5486B96A0025 // Processing
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_5486B96A0025_ME_5465A5AB0324 Processing

ME ME_548FEF4F002E_ME_5465A5AB0324
 MELINK Original HWL ME_548FEF4F002E // SessionID
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_548FEF4F002E_ME_5465A5AB0324 SessionID

ME ME_5465A5AB0324
 MEPROP UID '5465A5AB0324'
 MEPROP GUID '2DF810B8-EB59-4A34-8945-D6D35E58B03C'
 MEPROP Name 'IncsServerTransporter'
 MEPROP Class class_Class
 MELINK Stereotype st_Facet ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 MELIST Inherits
   Seq: ( HWL ME_5464B4730055 // IncsTransporter
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_5459E3150030 // Terminated
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_545335BF0283 // ProcessMessages
 HWL ME_5459D46D01FE // Terminate
 HWL ME_549180E701E0 // RegisterSendBackHandler
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_5464B4E900DA_ME_5465A5AB0324 // Send
 ME_5464B52F02D5_ME_5465A5AB0324 // WaitForReply
 ME_5465AB2B00CA_ME_5465A5AB0324 // Connected
 ME_546608F101DE_ME_5465A5AB0324 // ClientID
 ME_5486B96A0025_ME_5465A5AB0324 // Processing
 ME_548FEF4F002E_ME_5465A5AB0324 // SessionID
 )
 ; // Implemented
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsServerTransporter'

ENDME // ME_5465A5AB0324 IncsServerTransporter

FORWARD ME_5490036B0204

ME ME_5490037B017D
 MEPROP UID '5490037B017D'
 MEPROP Name 'ncs_skSend'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5490036B0204 // TncsSocketKind
 ;

ENDME // ME_5490037B017D ncs_skSend

ME ME_5490038D0132
 MEPROP UID '5490038D0132'
 MEPROP Name 'ncs_skReceive'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5490036B0204 // TncsSocketKind
 ;

ENDME // ME_5490038D0132 ncs_skReceive

ME ME_5490036B0204
 MEPROP UID '5490036B0204'
 MEPROP Name 'TncsSocketKind'
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5460A4DB018A // ncsMessageInterfaces
 ;
 MELIST Attributes
   Seq: ( HWL ME_5490037B017D // ncs_skSend
 HWL ME_5490038D0132 // ncs_skReceive
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts True

ENDME // ME_5490036B0204 TncsSocketKind

ME ME_5460A4DB018A
 MEPROP UID '5460A4DB018A'
 MEPROP Name 'ncsMessageInterfaces'
 MEPROP Class class_Class
 MELINK Stereotype st_UtilityPack ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Children
   Seq: ( HWL ME_5464B4730055 // IncsTransporter
 HWL ME_5464B37E01ED // TncsExecuteContext
 HWL ME_5460731E025E // IncsExecutor
 HWL ME_5460829B0384 // IncsMessageExecutorFactory
 HWL ME_5460C1A00144 // PIncsMessageExecutorFactory
 HWL ME_5465A598039E // IncsClientTransporter
 HWL ME_5465A5AB0324 // IncsServerTransporter
 HWL ME_5490036B0204 // TncsSocketKind
 )
 ; // Children
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsMessageInterfaces.pas'

ENDME // ME_5460A4DB018A ncsMessageInterfaces

FORWARD ME_5450E9A0034A

FORWARD ME_545201B70046

FORWARD ME_545201DF0064

ME ME_545201E602F7
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_545201E602F7 aMessage

ME ME_545201DF0064
 MEPROP UID '545201DF0064'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_545201B70046 // Send
 ;
 MELIST Parameters
   Seq: ( ME_545201E602F7 // aMessage
 )
 ; // Parameters

ENDME // ME_545201DF0064 DoIt

ME ME_54523F9A03D0
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_545201B70046 // Send
 ;
 MELINK Target WL 'ME_538DE3F001DC' '47913B47006E.ms.model.script' // Tl3TempMemoryStream
 ;

ENDME // ME_54523F9A03D0 

ME ME_54523FC602CF
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_545201B70046 // Send
 ;
 MELINK Target WL 'ME_47E150FF028A' '4AB0997B00A2.ms.model.script' // TStream
 ;

ENDME // ME_54523FC602CF 

ME ME_545201B70046
 MEPROP UID '545201B70046'
 MEPROP Name 'Send'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5450E9A0034A // TncsSendThread
 ;
 MELIST Operations
   Seq: ( HWL ME_545201DF0064 // DoIt
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_54523F9A03D0 // Tl3TempMemoryStream
 ME_54523FC602CF // TStream
 )
 ; // Dependencies

ENDME // ME_545201B70046 Send

ME ME_5450F0BE03BA
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5450E9A0034A // TncsSendThread
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_5450F0BE03BA 

ME ME_548AC9640012
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5450E9A0034A // TncsSendThread
 ;
 MELINK Target HWL ME_548AC7FB0046 // ncsProfile
 ;

ENDME // ME_548AC9640012 

ME ME_4911B69E037D_ME_5450E9A0034A
 MELINK Original WL 'ME_4911B69E037D' '47913B47006E.ms.model.script' // DoExecute
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_4911B69E037D_ME_5450E9A0034A DoExecute

ME ME_5450E9A0034A
 MEPROP UID '5450E9A0034A'
 MEPROP Name 'TncsSendThread'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( HWL ME_5460B6230039 // TncsTransporterIOThread
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_545201B70046 // Send
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_4911B69E037D_ME_5450E9A0034A // DoExecute
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_5450F0BE03BA // FreeAndNil
 ME_548AC9640012 // ncsProfile
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsSendThread'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsSendThread'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsSendThread.pas'

ENDME // ME_5450E9A0034A TncsSendThread

FORWARD ME_5453986402AC

ME ME_5450A0370225
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544E079E0253 // TncsMessage
 ;
 MELINK Target WL 'ME_54509FEC02EB' '47D0290B016D.ms.model.script' // l3CreateStringGUID
 ;

ENDME // ME_5450A0370225 

ME ME_53AC03EE01FD_ME_544E079E0253
 MELINK Original WL 'ME_53AC03EE01FD' '53B24DFD01FF.ms.model.script' // GetTaggedDataType
 ;
 MEPROP OpKind opkind_Implemented
 UP "is static" True
ENDME // ME_53AC03EE01FD_ME_544E079E0253 GetTaggedDataType

ME ME_47A042E100E2_ME_544E079E0253
 MELINK Original WL 'ME_47A042E100E2' '47913B47006E.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_544E079E0253 InitFields

ME ME_549413590379_ME_544E079E0253
 MELINK Original WL 'ME_549413590379' '53B15D5603E3.ms.model.script' // NeedSendRawDataAsBinary
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_549413590379_ME_544E079E0253 NeedSendRawDataAsBinary

ME ME_544E079E0253
 MEPROP UID '544E079E0253'
 MEPROP Name 'TncsMessage'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5453986402AC // ncsMessage
 ;
 MELIST Inherits
   Seq: ( WL 'ME_534572370056' '47913B47006E.ms.model.script' // Tl3Tag
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_53AC01CD0335' '53B15D5603E3.ms.model.script' // evdTagHolder
 WL 'ME_544E01AA03BA' '484A470100DD.ms.model.script' // csMessage
 )
 ; // Implements
 MELIST Implemented
   Seq: ( ME_53AC03EE01FD_ME_544E079E0253 // GetTaggedDataType
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_47A042E100E2_ME_544E079E0253 // InitFields
 ME_549413590379_ME_544E079E0253 // NeedSendRawDataAsBinary
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_5450A0370225 // l3CreateStringGUID
 )
 ; // Dependencies
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsMessage'

ENDME // ME_544E079E0253 TncsMessage

ME ME_5453989A0161
 MEPROP UID '5453989A0161'
 MEPROP Name 'TncsMessageClass'
 MEPROP Class class_Class
 MELINK Stereotype st_Typedef ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5453986402AC // ncsMessage
 ;
 MELIST Inherits
   Seq: ( HWL ME_544E079E0253 // TncsMessage
 )
 ; // Inherits
 UP "isClassRef" True
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsMessageClass'

ENDME // ME_5453989A0161 TncsMessageClass

ME ME_54649C7C00E7
 MEPROP UID '54649C7C00E7'
 MEPROP Name 'TncsInvalidMessage'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5453986402AC // ncsMessage
 ;
 MELIST Inherits
   Seq: ( HWL ME_544E079E0253 // TncsMessage
 )
 ; // Inherits
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsInvalidMessage'

ENDME // ME_54649C7C00E7 TncsInvalidMessage

FORWARD ME_547831BD02E5

FORWARD ME_547831D300BE

ME ME_547831E30313
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_547831E30313 aMessage

ME ME_547831D300BE
 MEPROP UID '547831D300BE'
 MEPROP Name 'Create'
 MEPROP Class class_Operation
 MELINK Stereotype st_ctor::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_547831BD02E5 // TncsReply
 ;
 MELIST Parameters
   Seq: ( ME_547831E30313 // aMessage
 )
 ; // Parameters

ENDME // ME_547831D300BE Create

ME ME_547831BD02E5
 MEPROP UID '547831BD02E5'
 MEPROP Name 'TncsReply'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5453986402AC // ncsMessage
 ;
 MELIST Inherits
   Seq: ( HWL ME_544E079E0253 // TncsMessage
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_547831D300BE // Create
 )
 ; // Operations
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsReply'

ENDME // ME_547831BD02E5 TncsReply

ME ME_547C1F31030C
 MEPROP UID '547C1F31030C'
 MEPROP Name 'TncsDisconnect'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5453986402AC // ncsMessage
 ;
 MELIST Inherits
   Seq: ( HWL ME_544E079E0253 // TncsMessage
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_547C1CD001E3' '484A470100DD.ms.model.script' // csDisconnect
 )
 ; // Implements
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsDisconnect'

ENDME // ME_547C1F31030C TncsDisconnect

ME ME_547C1F3F025A
 MEPROP UID '547C1F3F025A'
 MEPROP Name 'TncsDisconnectReply'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_5453986402AC // ncsMessage
 ;
 MELIST Inherits
   Seq: ( HWL ME_547831BD02E5 // TncsReply
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_547C1CE20205' '484A470100DD.ms.model.script' // csDisconnectReply
 )
 ; // Implements
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsDisconnectReply'

ENDME // ME_547C1F3F025A TncsDisconnectReply

ME ME_5453986402AC
 MEPROP UID '5453986402AC'
 MEPROP Name 'ncsMessage'
 MEPROP Class class_Class
 MELINK Stereotype st_UtilityPack ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Children
   Seq: ( HWL ME_544E079E0253 // TncsMessage
 HWL ME_5453989A0161 // TncsMessageClass
 HWL ME_54649C7C00E7 // TncsInvalidMessage
 HWL ME_547831BD02E5 // TncsReply
 HWL ME_547C1F31030C // TncsDisconnect
 HWL ME_547C1F3F025A // TncsDisconnectReply
 )
 ; // Children
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsMessage.pas'

ENDME // ME_5453986402AC ncsMessage

FORWARD ME_54539F0C00AD

ME ME_54539F2201C3
 MEPROP UID '54539F2201C3'
 MEPROP Name 'ItemType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54539F0C00AD // TncsMessageClassList
 ;
 MELINK Target HWL ME_5453989A0161 // TncsMessageClass
 ;

ENDME // ME_54539F2201C3 ItemType

ME ME_47B07CF403D0_ME_54539F0C00AD
 MELINK Original WL 'ME_47B07CF403D0' '47913B47006E.ms.model.script' // IsSameItems
 ;
 MEPROP OpKind opkind_Implemented
 UP "ifndef" 'l3Items_IsAtomic'
ENDME // ME_47B07CF403D0_ME_54539F0C00AD IsSameItems

ME ME_47B2C42A0163_ME_54539F0C00AD
 MELINK Original WL 'ME_47B2C42A0163' '47913B47006E.ms.model.script' // AssignItem
 ;
 MEPROP OpKind opkind_Implemented
 UP "ifdef" 'l3Items_NeedsAssignItem'
 UP "ifndef" 'l3Items_NoSort'
ENDME // ME_47B2C42A0163_ME_54539F0C00AD AssignItem

ME ME_47B99D4503A2_ME_54539F0C00AD
 MELINK Original WL 'ME_47B99D4503A2' '47BB24D30205.ms.model.script' // CompareExistingItems
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_47B99D4503A2_ME_54539F0C00AD CompareExistingItems

ME ME_54539F0C00AD
 MEPROP UID '54539F0C00AD'
 MEPROP Name 'TncsMessageClassList'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.ms.model.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_47B5782902DA' '47913B47006E.ms.model.script' // l3PtrList
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_54539F2201C3 // ItemType
 )
 ; // Attributes
 MELIST Implemented
   Seq: ( ME_47B07CF403D0_ME_54539F0C00AD // IsSameItems
 ME_47B2C42A0163_ME_54539F0C00AD // AssignItem
 ME_47B99D4503A2_ME_54539F0C00AD // CompareExistingItems
 )
 ; // Implemented
 UP extprop:pas:UnitName 'ncsMessageClassList'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsMessageClassList'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsMessageClassList.pas'

ENDME // ME_54539F0C00AD TncsMessageClassList

ME ME_54539F5D03D6
 MEPROP UID '54539F5D03D6'
 MEPROP Name 'f_List'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 MELINK Target HWL ME_54539F0C00AD // TncsMessageClassList
 ;

ENDME // ME_54539F5D03D6 f_List

FORWARD ME_545A23D30081

ME ME_545B868002AF
 MEPROP Name 'aClass'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_5453989A0161 // TncsMessageClass
 ;

ENDME // ME_545B868002AF aClass

ME ME_545A23D30081
 MEPROP UID '545A23D30081'
 MEPROP Name 'Register'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 MELIST Parameters
   Seq: ( ME_545B868002AF // aClass
 )
 ; // Parameters

ENDME // ME_545A23D30081 Register

FORWARD ME_545A23FB02E0

ME ME_545B86850353
 MEPROP Name 'aClass'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_5453989A0161 // TncsMessageClass
 ;

ENDME // ME_545B86850353 aClass

ME ME_545A23FB02E0
 MEPROP UID '545A23FB02E0'
 MEPROP Name 'UnRegister'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 MELIST Parameters
   Seq: ( ME_545B86850353 // aClass
 )
 ; // Parameters

ENDME // ME_545A23FB02E0 UnRegister

FORWARD ME_545A24130098

ME ME_545A242C01AB
 MEPROP Name 'aMessageTag'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_476136D3010B' '4AB0C3C60310.ms.model.script' // String
 ;

ENDME // ME_545A242C01AB aMessageTag

ME ME_545A24130098
 MEPROP UID '545A24130098'
 MEPROP Name 'Find'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 MELINK Target HWL ME_5453989A0161 // TncsMessageClass
 ;
 MELIST Parameters
   Seq: ( ME_545A242C01AB // aMessageTag
 )
 ; // Parameters

ENDME // ME_545A24130098 Find

FORWARD ME_54538B990208

ME ME_545B86710018
 MEPROP Name 'aStream'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_47E150FF028A' '4AB0997B00A2.ms.model.script' // TStream
 ;

ENDME // ME_545B86710018 aStream

ME ME_54538B990208
 MEPROP UID '54538B990208'
 MEPROP Name 'MakeFromEVD'
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;
 MELIST Parameters
   Seq: ( ME_545B86710018 // aStream
 )
 ; // Parameters

ENDME // ME_54538B990208 MakeFromEVD

FORWARD ME_54538F64032E

ME ME_545B8677028E
 MEPROP Name 'aData'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_534572370056' '47913B47006E.ms.model.script' // Tl3Tag
 ;

ENDME // ME_545B8677028E aData

ME ME_54538F64032E
 MEPROP UID '54538F64032E'
 MEPROP Name 'MakeFromTaggedData'
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;
 MELIST Parameters
   Seq: ( ME_545B8677028E // aData
 )
 ; // Parameters

ENDME // ME_54538F64032E MakeFromTaggedData

ME ME_545A292E0276
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_545A292E0276 

ME ME_545A2BAB00FD
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54539F4702B1 // TncsMessageFactory
 ;
 MELINK Target WL 'ME_47614B2901AE' '4678193C009C.ms.model.script' // Tl3Duplicates
 ;

ENDME // ME_545A2BAB00FD 

ME ME_479731C50290_ME_54539F4702B1
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_54539F4702B1 Cleanup

ME ME_47A042E100E2_ME_54539F4702B1
 MELINK Original WL 'ME_47A042E100E2' '47913B47006E.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_54539F4702B1 InitFields

ME ME_54539F4702B1
 MEPROP UID '54539F4702B1'
 MEPROP Name 'TncsMessageFactory'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.ms.model.script' // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_54539F5D03D6 // f_List
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_545A23D30081 // Register
 HWL ME_545A23FB02E0 // UnRegister
 HWL ME_545A24130098 // Find
 HWL ME_54538B990208 // MakeFromEVD
 HWL ME_54538F64032E // MakeFromTaggedData
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_54539F4702B1 // Cleanup
 ME_47A042E100E2_ME_54539F4702B1 // InitFields
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_545A292E0276 // FreeAndNil
 ME_545A2BAB00FD // Tl3Duplicates
 )
 ; // Dependencies
 UP "singleton" True
 UP extprop:pas:UnitName 'ncsMessageFactory'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsMessageFactory'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsMessageFactory.pas'

ENDME // ME_54539F4702B1 TncsMessageFactory

FORWARD ME_545CBE61008B

ME ME_545CC4210322
 MEPROP UID '545CC4210322'
 MEPROP Name 'l3Items_NoSort'
 MEPROP Class class_Class
 MELINK Stereotype st_Define ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_545CBE61008B // TncsServerTransporterList
 ;
 UP extprop:rc:SelfName 'Items_NoSort'

ENDME // ME_545CC4210322 l3Items_NoSort

ME ME_545CBE9103D8
 MEPROP UID '545CBE9103D8'
 MEPROP Name 'ItemType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_545CBE61008B // TncsServerTransporterList
 ;
 MELINK Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;

ENDME // ME_545CBE9103D8 ItemType

ME ME_545CBE61008B
 MEPROP UID '545CBE61008B'
 MEPROP Name 'TncsServerTransporterList'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.ms.model.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_47B57D830369' '47913B47006E.ms.model.script' // l3InterfaceRefList
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_545CBE9103D8 // ItemType
 )
 ; // Attributes
 MELIST Children
   Seq: ( HWL ME_545CC4210322 // l3Items_NoSort
 )
 ; // Children
 UP extprop:pas:UnitName 'ncsServerTransporterList'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsServerTransporterList'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsServerTransporterList.pas'

ENDME // ME_545CBE61008B TncsServerTransporterList

FORWARD ME_545CBED90193

ME ME_545CBF0E0186
 MEPROP UID '545CBF0E0186'
 MEPROP Name 'f_Data'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_545CBED90193 // TncsServerTransporterPool
 ;
 MELINK Target HWL ME_545CBE61008B // TncsServerTransporterList
 ;

ENDME // ME_545CBF0E0186 f_Data

FORWARD ME_545CBF760027

ME ME_545CBF9100D6
 MEPROP Name 'aTransporter'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;

ENDME // ME_545CBF9100D6 aTransporter

ME ME_545CBF760027
 MEPROP UID '545CBF760027'
 MEPROP Name 'Register'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_545CBED90193 // TncsServerTransporterPool
 ;
 MELIST Parameters
   Seq: ( ME_545CBF9100D6 // aTransporter
 )
 ; // Parameters

ENDME // ME_545CBF760027 Register

FORWARD ME_545CBF9602E1

ME ME_545CBF9B00D6
 MEPROP Name 'aTransporter'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;

ENDME // ME_545CBF9B00D6 aTransporter

ME ME_545CBF9602E1
 MEPROP UID '545CBF9602E1'
 MEPROP Name 'UnRegister'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_545CBED90193 // TncsServerTransporterPool
 ;
 MELIST Parameters
   Seq: ( ME_545CBF9B00D6 // aTransporter
 )
 ; // Parameters

ENDME // ME_545CBF9602E1 UnRegister

ME ME_545CBFA2006D
 MEPROP UID '545CBFA2006D'
 MEPROP Name 'TerminateAll'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_545CBED90193 // TncsServerTransporterPool
 ;

ENDME // ME_545CBFA2006D TerminateAll

ME ME_479731C50290_ME_545CBED90193
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_545CBED90193 Cleanup

ME ME_47A042E100E2_ME_545CBED90193
 MELINK Original WL 'ME_47A042E100E2' '47913B47006E.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_545CBED90193 InitFields

ME ME_545CBED90193
 MEPROP UID '545CBED90193'
 MEPROP Name 'TncsServerTransporterPool'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.ms.model.script' // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_53A03846011C' '53A038340371.ms.model.script' // l3CriticalSectionHolder
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_545CBF0E0186 // f_Data
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_545CBF760027 // Register
 HWL ME_545CBF9602E1 // UnRegister
 HWL ME_545CBFA2006D // TerminateAll
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_545CBED90193 // Cleanup
 ME_47A042E100E2_ME_545CBED90193 // InitFields
 )
 ; // Overridden
 UP extprop:pas:UnitName 'ncsServerTransporterPool'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsServerTransporterPool'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsServerTransporterPool.pas'

ENDME // ME_545CBED90193 TncsServerTransporterPool

FORWARD ME_5461D6FC00F7

ME ME_5461D7260382
 MEPROP UID '5461D7260382'
 MEPROP Name 'ItemType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5461D6FC00F7 // TncsReplyDecsriptionList
 ;
 MELINK Target HWL ME_5461D6C30025 // TncsReplyDescription
 ;

ENDME // ME_5461D7260382 ItemType

ME ME_47B2C42A0163_ME_5461D6FC00F7
 MELINK Original WL 'ME_47B2C42A0163' '47913B47006E.ms.model.script' // AssignItem
 ;
 MEPROP OpKind opkind_Implemented
 UP "ifdef" 'l3Items_NeedsAssignItem'
 UP "ifndef" 'l3Items_NoSort'
ENDME // ME_47B2C42A0163_ME_5461D6FC00F7 AssignItem

ME ME_47B99D4503A2_ME_5461D6FC00F7
 MELINK Original WL 'ME_47B99D4503A2' '47BB24D30205.ms.model.script' // CompareExistingItems
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_47B99D4503A2_ME_5461D6FC00F7 CompareExistingItems

ME ME_5461D6FC00F7
 MEPROP UID '5461D6FC00F7'
 MEPROP Name 'TncsReplyDecsriptionList'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.ms.model.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_47B99E920196' '47913B47006E.ms.model.script' // l3UncomparabeObjectRefList
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_5461D7260382 // ItemType
 )
 ; // Attributes
 MELIST Implemented
   Seq: ( ME_47B2C42A0163_ME_5461D6FC00F7 // AssignItem
 ME_47B99D4503A2_ME_5461D6FC00F7 // CompareExistingItems
 )
 ; // Implemented
 UP extprop:pas:UnitName 'ncsReplyDecsriptionList'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsReplyDecsriptionList'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsReplyDecsriptionList.pas'

ENDME // ME_5461D6FC00F7 TncsReplyDecsriptionList

FORWARD ME_54609BB100BB

ME ME_54609BE1031F
 MEPROP UID '54609BE1031F'
 MEPROP Name 'ItemType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54609BB100BB // TncsExecutorFactoryList
 ;
 MELINK Target HWL ME_5460829B0384 // IncsMessageExecutorFactory
 ;

ENDME // ME_54609BE1031F ItemType

ME ME_54609BB100BB
 MEPROP UID '54609BB100BB'
 MEPROP Name 'TncsExecutorFactoryList'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.ms.model.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_47B57D630029' '47913B47006E.ms.model.script' // l3InterfacePtrList
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_54609BE1031F // ItemType
 )
 ; // Attributes
 UP extprop:pas:UnitName 'ncsExecutorFactoryList'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsExecutorFactoryList'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsExecutorFactoryList.pas'

ENDME // ME_54609BB100BB TncsExecutorFactoryList

FORWARD ME_54607384020A

FORWARD ME_5464A0E40234

ME ME_5464A4DE0181
 MEPROP UID '5464A4DE0181'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5464A0E40234 // TncsInvalidExecutor
 ;

ENDME // ME_5464A4DE0181 Create

ME ME_5464A4E9009C
 MEPROP UID '5464A4E9009C'
 MEPROP Name 'Make'
 MEPROP Class class_Class
 MELINK Stereotype st_Factory ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5464A0E40234 // TncsInvalidExecutor
 ;
 MELIST Inherits
   Seq: ( HWL ME_5464A4DE0181 // Create
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5460731E025E // IncsExecutor
 )
 ; // Implements

ENDME // ME_5464A4E9009C Make

ME ME_54607DDC0159_ME_5464A0E40234
 MELINK Original HWL ME_54607DDC0159 // Execute
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_54607DDC0159_ME_5464A0E40234 Execute

ME ME_5464A0E40234
 MEPROP UID '5464A0E40234'
 MEPROP Name 'TncsInvalidExecutor'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.ms.model.script' // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5460731E025E // IncsExecutor
 )
 ; // Implements
 MELIST Operations
   Seq: ( HWL ME_5464A4DE0181 // Create
 HWL ME_5464A4E9009C // Make
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_54607DDC0159_ME_5464A0E40234 // Execute
 )
 ; // Implemented
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsInvalidExecutor'

ENDME // ME_5464A0E40234 TncsInvalidExecutor

FORWARD ME_547C1FB30097

ME ME_547C1FD9007B
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_547C1FB30097 // TncsDisconnectExecutor
 ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_547C1FD9007B 

ME ME_547C1FDD03A0
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_547C1FB30097 // TncsDisconnectExecutor
 ;
 MELINK Target HWL ME_547C1F31030C // TncsDisconnect
 ;

ENDME // ME_547C1FDD03A0 

ME ME_547C1FE10204
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_547C1FB30097 // TncsDisconnectExecutor
 ;
 MELINK Target HWL ME_547C1F3F025A // TncsDisconnectReply
 ;

ENDME // ME_547C1FE10204 

ME ME_54607DDC0159_ME_547C1FB30097
 MELINK Original HWL ME_54607DDC0159 // Execute
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_54607DDC0159_ME_547C1FB30097 Execute

ME ME_546082B801F3_ME_547C1FB30097
 MELINK Original HWL ME_546082B801F3 // MakeExecutor
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_546082B801F3_ME_547C1FB30097 MakeExecutor

ME ME_547C1FB30097
 MEPROP UID '547C1FB30097'
 MEPROP Name 'TncsDisconnectExecutor'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.ms.model.script' // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5460731E025E // IncsExecutor
 HWL ME_5460829B0384 // IncsMessageExecutorFactory
 )
 ; // Implements
 MELIST Implemented
   Seq: ( ME_54607DDC0159_ME_547C1FB30097 // Execute
 ME_546082B801F3_ME_547C1FB30097 // MakeExecutor
 )
 ; // Implemented
 MELIST Dependencies
   Seq: ( ME_547C1FD9007B // TncsMessage
 ME_547C1FDD03A0 // TncsDisconnect
 ME_547C1FE10204 // TncsDisconnectReply
 )
 ; // Dependencies
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsDisconnectExecutor'

ENDME // ME_547C1FB30097 TncsDisconnectExecutor

ME ME_54609BF500ED
 MEPROP UID '54609BF500ED'
 MEPROP Name 'f_List'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 MELINK Target HWL ME_54609BB100BB // TncsExecutorFactoryList
 ;

ENDME // ME_54609BF500ED f_List

ME ME_547C200B02EA
 MEPROP UID '547C200B02EA'
 MEPROP Name 'f_DisconnectExecutor'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 MELINK Target HWL ME_547C1FB30097 // TncsDisconnectExecutor
 ;

ENDME // ME_547C200B02EA f_DisconnectExecutor

FORWARD ME_5460830D0295

ME ME_546083260154
 MEPROP Name 'aFactory'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_5460829B0384 // IncsMessageExecutorFactory
 ;

ENDME // ME_546083260154 aFactory

ME ME_5460830D0295
 MEPROP UID '5460830D0295'
 MEPROP Name 'Register'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 MELIST Parameters
   Seq: ( ME_546083260154 // aFactory
 )
 ; // Parameters

ENDME // ME_5460830D0295 Register

FORWARD ME_5460832C0080

ME ME_5460832F028E
 MEPROP Name 'aFactory'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_5460829B0384 // IncsMessageExecutorFactory
 ;

ENDME // ME_5460832F028E aFactory

ME ME_5460832C0080
 MEPROP UID '5460832C0080'
 MEPROP Name 'UnRegister'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 MELIST Parameters
   Seq: ( ME_5460832F028E // aFactory
 )
 ; // Parameters

ENDME // ME_5460832C0080 UnRegister

FORWARD ME_5460AEC800B8

ME ME_5460B06B03DE
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_5460B06B03DE aMessage

ME ME_5460AEC800B8
 MEPROP UID '5460AEC800B8'
 MEPROP Name 'MakeExecutor'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 MELINK Target HWL ME_5460731E025E // IncsExecutor
 ;
 MELIST Parameters
   Seq: ( ME_5460B06B03DE // aMessage
 )
 ; // Parameters

ENDME // ME_5460AEC800B8 MakeExecutor

ME ME_5460A810027B
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_5460A810027B 

ME ME_5460C4460031
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 MELINK Target WL 'ME_47289B590038' '4678193C009C.ms.model.script' // PLong
 ;

ENDME // ME_5460C4460031 

ME ME_5464C855013F
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54607384020A // TncsMessageExecutorFactory
 ;
 MELINK Target WL 'ME_5461CFB8002C' '484A470100DD.ms.model.script' // TncsMessageKind
 ;

ENDME // ME_5464C855013F 

ME ME_479731C50290_ME_54607384020A
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_54607384020A Cleanup

ME ME_47A042E100E2_ME_54607384020A
 MELINK Original WL 'ME_47A042E100E2' '47913B47006E.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_54607384020A InitFields

ME ME_54607384020A
 MEPROP UID '54607384020A'
 MEPROP Name 'TncsMessageExecutorFactory'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.ms.model.script' // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_54609BF500ED // f_List
 HWL ME_547C200B02EA // f_DisconnectExecutor
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_5460830D0295 // Register
 HWL ME_5460832C0080 // UnRegister
 HWL ME_5460AEC800B8 // MakeExecutor
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_54607384020A // Cleanup
 ME_47A042E100E2_ME_54607384020A // InitFields
 )
 ; // Overridden
 MELIST Children
   Seq: ( HWL ME_5464A0E40234 // TncsInvalidExecutor
 HWL ME_547C1FB30097 // TncsDisconnectExecutor
 )
 ; // Children
 MELIST Dependencies
   Seq: ( ME_5460A810027B // FreeAndNil
 ME_5460C4460031 // PLong
 ME_5464C855013F // TncsMessageKind
 )
 ; // Dependencies
 UP "singleton" True
 UP extprop:pas:UnitName 'ncsMessageExecutorFactory'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsMessageExecutorFactory'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsMessageExecutorFactory.pas'

ENDME // ME_54607384020A TncsMessageExecutorFactory

FORWARD ME_5461D9EE0244

ME ME_5461DA210250
 MEPROP UID '5461DA210250'
 MEPROP Name 'f_List'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 MELINK Target HWL ME_5461D6FC00F7 // TncsReplyDecsriptionList
 ;

ENDME // ME_5461DA210250 f_List

FORWARD ME_54633EAE039A

FORWARD ME_54633EB6031C

ME ME_54633ECE02CA
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_54633ECE02CA aMessage

ME ME_54633EB6031C
 MEPROP UID '54633EB6031C'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54633EAE039A // FindDesc
 ;
 MELINK Target HWL ME_5461D6C30025 // TncsReplyDescription
 ;
 MELIST Parameters
   Seq: ( ME_54633ECE02CA // aMessage
 )
 ; // Parameters

ENDME // ME_54633EB6031C DoIt

ME ME_54633EAE039A
 MEPROP UID '54633EAE039A'
 MEPROP Name 'FindDesc'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 MELIST Operations
   Seq: ( HWL ME_54633EB6031C // DoIt
 )
 ; // Operations

ENDME // ME_54633EAE039A FindDesc

FORWARD ME_54630A1F0046

ME ME_54630A360321
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_54630A360321 aMessage

ME ME_54630A1F0046
 MEPROP UID '54630A1F0046'
 MEPROP Name 'SubmitReply'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 MELIST Parameters
   Seq: ( ME_54630A360321 // aMessage
 )
 ; // Parameters

ENDME // ME_54630A1F0046 SubmitReply

FORWARD ME_54630A3E001D

ME ME_54630A4F0322
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_54630A4F0322 aMessage

ME ME_54630A3E001D
 MEPROP UID '54630A3E001D'
 MEPROP Name 'SubmitMessage'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 MELIST Parameters
   Seq: ( ME_54630A4F0322 // aMessage
 )
 ; // Parameters

ENDME // ME_54630A3E001D SubmitMessage

ME ME_54630A7102CD
 MEPROP UID '54630A7102CD'
 MEPROP Name 'Clear'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;

ENDME // ME_54630A7102CD Clear

FORWARD ME_54630A80027D

ME ME_547C4DD20008
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_547C4DD20008 aMessage

ME ME_547C4DD20037
 MEPROP Name 'theReply'
 MEPROP Class class_Parameter
 MELINK Stereotype st_inout ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_547C4DD20037 theReply

ME ME_547C4DD20056
 MEPROP Name 'aTimeOut'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_47BC524C0245' '4AB0C3C60310.ms.model.script' // LongWord
 ;
 MEPROP Value 'INFINITE'
 MELINK ValueType WL 'ME_483C21B0003E' '4AB0C3F60375.ms.model.script' // Timeouts
 ;
 UP extprop:pas:Value 'INFINITE'

ENDME // ME_547C4DD20056 aTimeOut

ME ME_54630A80027D
 MEPROP UID '54630A80027D'
 MEPROP Name 'WaitForReply'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;
 MELIST Parameters
   Seq: ( ME_547C4DD20008 // aMessage
 ME_547C4DD20037 // theReply
 ME_547C4DD20056 // aTimeOut
 )
 ; // Parameters

ENDME // ME_54630A80027D WaitForReply

ME ME_5461FC9C0368
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_5461FC9C0368 

ME ME_5463131A0008
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 MELINK Target HWL ME_5461D6C30025 // TncsReplyDescription
 ;

ENDME // ME_5463131A0008 

ME ME_54634144025A
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 MELINK Target WL 'ME_4CDD241C0184' '47913B47006E.ms.model.script' // l3System
 ;

ENDME // ME_54634144025A 

ME ME_479731C50290_ME_5461D9EE0244
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_5461D9EE0244 Cleanup

ME ME_47A042E100E2_ME_5461D9EE0244
 MELINK Original WL 'ME_47A042E100E2' '47913B47006E.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_5461D9EE0244 InitFields

ME ME_5461D9EE0244
 MEPROP UID '5461D9EE0244'
 MEPROP Name 'TncsReplyWaiter'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.ms.model.script' // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_53A03846011C' '53A038340371.ms.model.script' // l3CriticalSectionHolder
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_5461DA210250 // f_List
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_54633EAE039A // FindDesc
 HWL ME_54630A1F0046 // SubmitReply
 HWL ME_54630A3E001D // SubmitMessage
 HWL ME_54630A7102CD // Clear
 HWL ME_54630A80027D // WaitForReply
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_5461D9EE0244 // Cleanup
 ME_47A042E100E2_ME_5461D9EE0244 // InitFields
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_5461FC9C0368 // FreeAndNil
 ME_5463131A0008 // TncsReplyDescription
 ME_54634144025A // l3System
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsReplyWaiter'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsReplyWaiter'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsReplyWaiter.pas'

ENDME // ME_5461D9EE0244 TncsReplyWaiter

FORWARD ME_546061CE03DA

ME ME_5461D7EA00E4
 MEPROP UID '5461D7EA00E4'
 MEPROP Name 'ReplyWaiter'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_546061CE03DA // TncsProcessThread
 ;
 MELINK Target HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_5461D7EA00E4 ReplyWaiter

ME ME_5464BDA603BD
 MEPROP UID '5464BDA603BD'
 MEPROP Name 'f_Transporter'
 MEPROP Class class_Attribute
 %SUMMARY '[weak] IncsTransporter' ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_546061CE03DA // TncsProcessThread
 ;
 MELINK Target WL 'ME_46A608F00301' '4AB0C3C60310.ms.model.script' // Pointer
 ;

ENDME // ME_5464BDA603BD f_Transporter

ME ME_5464BE030256
 MEPROP UID '5464BE030256'
 MEPROP Name 'Transporter'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_546061CE03DA // TncsProcessThread
 ;
 MELINK Target HWL ME_5464B4730055 // IncsTransporter
 ;
 UP "pm" True

ENDME // ME_5464BE030256 Transporter

FORWARD ME_5460680D0277

FORWARD ME_5460681B02B0

ME ME_5460681F01B0
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_5460681F01B0 aMessage

ME ME_5460681B02B0
 MEPROP UID '5460681B02B0'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 MELIST Parameters
   Seq: ( ME_5460681F01B0 // aMessage
 )
 ; // Parameters

ENDME // ME_5460681B02B0 DoIt

ME ME_54606E1A0207
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 MELINK Target WL 'ME_4CDD241C0184' '47913B47006E.ms.model.script' // l3System
 ;

ENDME // ME_54606E1A0207 

ME ME_5460734B00FE
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_5460734B00FE 

ME ME_546073DF01D8
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 MELINK Target HWL ME_54607384020A // TncsMessageExecutorFactory
 ;

ENDME // ME_546073DF01D8 

ME ME_5460797F01C3
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 MELINK Target HWL ME_5460731E025E // IncsExecutor
 ;

ENDME // ME_5460797F01C3 

ME ME_54784861030C
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 MELINK Target HWL ME_54649C7C00E7 // TncsInvalidMessage
 ;

ENDME // ME_54784861030C 

ME ME_54784865026A
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 MELINK Target WL 'ME_5461CFB8002C' '484A470100DD.ms.model.script' // TncsMessageKind
 ;

ENDME // ME_54784865026A 

ME ME_547848860360
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_5460680D0277 // ProcessMessage
 ;
 MELINK Target WL 'ME_4787A405013D' '4AB0C3C60310.ms.model.script' // Exception
 ;

ENDME // ME_547848860360 

ME ME_5460680D0277
 MEPROP UID '5460680D0277'
 MEPROP Name 'ProcessMessage'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_546061CE03DA // TncsProcessThread
 ;
 MELIST Operations
   Seq: ( HWL ME_5460681B02B0 // DoIt
 )
 ; // Operations
 MELIST Dependencies
   Seq: ( ME_54606E1A0207 // l3System
 ME_5460734B00FE // FreeAndNil
 ME_546073DF01D8 // TncsMessageExecutorFactory
 ME_5460797F01C3 // IncsExecutor
 ME_54784861030C // TncsInvalidMessage
 ME_54784865026A // TncsMessageKind
 ME_547848860360 // Exception
 )
 ; // Dependencies

ENDME // ME_5460680D0277 ProcessMessage

FORWARD ME_5464BDC203B1

FORWARD ME_5464BDCD0296

ME ME_5464BDEF00E1
 MEPROP Name 'anQueue'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E3C54031D // TncsMessageQueue
 ;

ENDME // ME_5464BDEF00E1 anQueue

ME ME_5464BDEF00F1
 MEPROP Name 'aTransporter'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_5464B4730055 // IncsTransporter
 ;

ENDME // ME_5464BDEF00F1 aTransporter

ME ME_5493FA0C0300
 MEPROP Name 'aWaiter'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;

ENDME // ME_5493FA0C0300 aWaiter

ME ME_5464BDCD0296
 MEPROP UID '5464BDCD0296'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5464BDC203B1 // Create
 ;
 MELIST Parameters
   Seq: ( ME_5464BDEF00E1 // anQueue
 ME_5464BDEF00F1 // aTransporter
 ME_5493FA0C0300 // aWaiter
 )
 ; // Parameters

ENDME // ME_5464BDCD0296 DoIt

ME ME_5464BDC203B1
 MEPROP UID '5464BDC203B1'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_546061CE03DA // TncsProcessThread
 ;
 MELIST Operations
   Seq: ( HWL ME_5464BDCD0296 // DoIt
 )
 ; // Operations

ENDME // ME_5464BDC203B1 Create

ME ME_5462046F018C
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_546061CE03DA // TncsProcessThread
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_5462046F018C 

ME ME_479731C50290_ME_546061CE03DA
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_546061CE03DA Cleanup

ME ME_4911B69E037D_ME_546061CE03DA
 MELINK Original WL 'ME_4911B69E037D' '47913B47006E.ms.model.script' // DoExecute
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_4911B69E037D_ME_546061CE03DA DoExecute

ME ME_546061CE03DA
 MEPROP UID '546061CE03DA'
 MEPROP Name 'TncsProcessThread'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( HWL ME_5452248C02B8 // TncsTransporterThread
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_5461D7EA00E4 // ReplyWaiter
 HWL ME_5464BDA603BD // f_Transporter
 HWL ME_5464BE030256 // Transporter
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_5460680D0277 // ProcessMessage
 HWL ME_5464BDC203B1 // Create
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_546061CE03DA // Cleanup
 ME_4911B69E037D_ME_546061CE03DA // DoExecute
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_5462046F018C // FreeAndNil
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsProcessThread'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsProcessThread'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsProcessThread.pas'

ENDME // ME_546061CE03DA TncsProcessThread

FORWARD ME_544A09EE005F

FORWARD ME_54917076009C

ME ME_5491708B03B6
 MEPROP UID '5491708B03B6'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_ref
 MELINK Parent HWL ME_54917076009C // TncsIOHandlerArray
 ;
 MELINK Target WL 'ME_538DDC890328' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAbstractAdapter
 ;

ENDME // ME_5491708B03B6 

ME ME_54917076009C
 MEPROP UID '54917076009C'
 MEPROP Name 'TncsIOHandlerArray'
 MEPROP Class class_Class
 MELINK Stereotype st_Vector ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELIST Inherits
   Seq: ( HWL ME_5490036B0204 // TncsSocketKind
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_5491708B03B6 // 
 )
 ; // Attributes
 UP "array type" 'dynamic'

ENDME // ME_54917076009C TncsIOHandlerArray

ME ME_5450AB4D02E2
 MEPROP UID '5450AB4D02E2'
 MEPROP Name 'SendQueue'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target HWL ME_544E3C54031D // TncsMessageQueue
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_5450AB4D02E2 SendQueue

ME ME_5450AB6A00A2
 MEPROP UID '5450AB6A00A2'
 MEPROP Name 'ReceiveQueue'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target HWL ME_544E3C54031D // TncsMessageQueue
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_5450AB6A00A2 ReceiveQueue

ME ME_5450EA6D02B3
 MEPROP UID '5450EA6D02B3'
 MEPROP Name 'SendThread'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target HWL ME_5450E9A0034A // TncsSendThread
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_5450EA6D02B3 SendThread

FORWARD ME_545225640060

ME ME_5491703C03A8
 MEPROP UID '5491703C03A8'
 MEPROP Name 'SocketKind'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_545225640060 // IOHandlers
 ;
 MELINK Target HWL ME_5490036B0204 // TncsSocketKind
 ;

ENDME // ME_5491703C03A8 SocketKind

ME ME_545225640060
 MEPROP UID '545225640060'
 MEPROP Name 'IOHandlers'
 MEPROP Class class_Attribute
 MELINK Stereotype st_property::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target WL 'ME_538DDC890328' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAbstractAdapter
 ;
 MELIST Attributes
   Seq: ( HWL ME_5491703C03A8 // SocketKind
 )
 ; // Attributes
 UP "pm" True

ENDME // ME_545225640060 IOHandlers

ME ME_54534F3D0029
 MEPROP UID '54534F3D0029'
 MEPROP Name 'ReceiveThread'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target HWL ME_54534F1A00BF // TncsReceiveThread
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_54534F3D0029 ReceiveThread

ME ME_546061ED0170
 MEPROP UID '546061ED0170'
 MEPROP Name 'ProcessThread'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target HWL ME_546061CE03DA // TncsProcessThread
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_546061ED0170 ProcessThread

ME ME_5461D7C4021A
 MEPROP UID '5461D7C4021A'
 MEPROP Name 'ReplyWaiter'
 MEPROP Class class_Attribute
 MELINK Stereotype st_readonly::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target HWL ME_5461D9EE0244 // TncsReplyWaiter
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_5461D7C4021A ReplyWaiter

ME ME_5465AB860254
 MEPROP UID '5465AB860254'
 MEPROP Name 'f_Connected'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;

ENDME // ME_5465AB860254 f_Connected

ME ME_5466092F01BB
 MEPROP UID '5466092F01BB'
 MEPROP Name 'f_ClientID'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target WL 'ME_537F4A04037C' '52FBB2FC0386.ms.model.script' // TCsClientId
 ;

ENDME // ME_5466092F01BB f_ClientID

ME ME_548FEF8F0026
 MEPROP UID '548FEF8F0026'
 MEPROP Name 'IntSessionID'
 MEPROP Class class_Attribute
 MELINK Stereotype st_property::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target WL 'ME_476136D3010B' '4AB0C3C60310.ms.model.script' // String
 ;
 UP "pm" True
 UP "reads field" True
 UP "writes field" True

ENDME // ME_548FEF8F0026 IntSessionID

ME ME_5491709C03AC
 MEPROP UID '5491709C03AC'
 MEPROP Name 'f_IOHandlers'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target HWL ME_54917076009C // TncsIOHandlerArray
 ;

ENDME // ME_5491709C03AC f_IOHandlers

FORWARD ME_54533B010030

FORWARD ME_54533B1701F2

ME ME_54533B2900CE
 MEPROP Name 'aValue'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;

ENDME // ME_54533B2900CE aValue

ME ME_54533B1701F2
 MEPROP UID '54533B1701F2'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54533B010030 // SetConnected
 ;
 MELIST Parameters
   Seq: ( ME_54533B2900CE // aValue
 )
 ; // Parameters

ENDME // ME_54533B1701F2 DoIt

ME ME_54533B010030
 MEPROP UID '54533B010030'
 MEPROP Name 'SetConnected'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_54533B1701F2 // DoIt
 )
 ; // Operations

ENDME // ME_54533B010030 SetConnected

ME ME_5459C7E00125
 MEPROP UID '5459C7E00125'
 MEPROP Name 'StartProcessing'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;

ENDME // ME_5459C7E00125 StartProcessing

FORWARD ME_5459C803038D

FORWARD ME_545B3E120323

ME ME_545B3E250102
 MEPROP Name 'WaitForThreads'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;

ENDME // ME_545B3E250102 WaitForThreads

ME ME_545B3E120323
 MEPROP UID '545B3E120323'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5459C803038D // StopProcessing
 ;
 MELIST Parameters
   Seq: ( ME_545B3E250102 // WaitForThreads
 )
 ; // Parameters

ENDME // ME_545B3E120323 DoIt

ME ME_5459C803038D
 MEPROP UID '5459C803038D'
 MEPROP Name 'StopProcessing'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_545B3E120323 // DoIt
 )
 ; // Operations

ENDME // ME_5459C803038D StopProcessing

FORWARD ME_5477033C03D0

ME ME_A6A7B60F1DF2
 MEPROP UID 'A6A7B60F1DF2'
 MEPROP Name 'DoIt'
 UP IsSummoned true
 MEPROP Class class_Operation
 %SUMMARY 'Сигнатура метода HandShake' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5477033C03D0 // HandShake
 ;

ENDME // ME_A6A7B60F1DF2 DoIt

ME ME_5477033C03D0
 MEPROP UID '5477033C03D0'
 MEPROP Name 'HandShake'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_A6A7B60F1DF2 // DoIt
 )
 ; // Operations

ENDME // ME_5477033C03D0 HandShake

FORWARD ME_549175C4030A

ME ME_549175D702CD
 MEPROP UID '549175D702CD'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_549175C4030A // HandShakeKind
 ;
 MELINK Target HWL ME_5490036B0204 // TncsSocketKind
 ;

ENDME // ME_549175D702CD DoIt

ME ME_549175C4030A
 MEPROP UID '549175C4030A'
 MEPROP Name 'HandShakeKind'
 MEPROP Class class_Class
 MELINK Stereotype st_abstractmethod ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_549175D702CD // DoIt
 )
 ; // Operations

ENDME // ME_549175C4030A HandShakeKind

FORWARD ME_5492C5F703AA

ME ME_8A8BAA04A4CE
 MEPROP UID '8A8BAA04A4CE'
 MEPROP Name 'DoIt'
 UP IsSummoned true
 MEPROP Class class_Operation
 %SUMMARY 'Сигнатура метода TransportStarted' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5492C5F703AA // TransportStarted
 ;

ENDME // ME_8A8BAA04A4CE DoIt

ME ME_5492C5F703AA
 MEPROP UID '5492C5F703AA'
 MEPROP Name 'TransportStarted'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_8A8BAA04A4CE // DoIt
 )
 ; // Operations

ENDME // ME_5492C5F703AA TransportStarted

ME ME_5450A0AC017E
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target WL 'ME_54509FEC02EB' '47D0290B016D.ms.model.script' // l3CreateStringGUID
 ;

ENDME // ME_5450A0AC017E 

ME ME_5450DC780347
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_5450DC780347 

ME ME_5463161F0105
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A09EE005F // TncsTransporter
 ;
 MELINK Target WL 'ME_5461CFB8002C' '484A470100DD.ms.model.script' // TncsMessageKind
 ;

ENDME // ME_5463161F0105 

ME ME_5464B4E900DA_ME_544A09EE005F
 MELINK Original HWL ME_5464B4E900DA // Send
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5464B4E900DA_ME_544A09EE005F Send

ME ME_5464B52F02D5_ME_544A09EE005F
 MELINK Original HWL ME_5464B52F02D5 // WaitForReply
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5464B52F02D5_ME_544A09EE005F WaitForReply

ME ME_5465AB2B00CA_ME_544A09EE005F
 MELINK Original HWL ME_5465AB2B00CA // Connected
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_5465AB2B00CA_ME_544A09EE005F Connected

ME ME_546608F101DE_ME_544A09EE005F
 MELINK Original HWL ME_546608F101DE // ClientID
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_546608F101DE_ME_544A09EE005F ClientID

ME ME_5486B96A0025_ME_544A09EE005F
 MELINK Original HWL ME_5486B96A0025 // Processing
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_5486B96A0025_ME_544A09EE005F Processing

ME ME_548FEF4F002E_ME_544A09EE005F
 MELINK Original HWL ME_548FEF4F002E // SessionID
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_548FEF4F002E_ME_544A09EE005F SessionID

ME ME_479731C50290_ME_544A09EE005F
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_544A09EE005F Cleanup

ME ME_47A042E100E2_ME_544A09EE005F
 MELINK Original WL 'ME_47A042E100E2' '47913B47006E.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_544A09EE005F InitFields

ME ME_544A09EE005F
 MEPROP UID '544A09EE005F'
 MEPROP Name 'TncsTransporter'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.ms.model.script' // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_53A03846011C' '53A038340371.ms.model.script' // l3CriticalSectionHolder
 HWL ME_5464B4730055 // IncsTransporter
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_5450AB4D02E2 // SendQueue
 HWL ME_5450AB6A00A2 // ReceiveQueue
 HWL ME_5450EA6D02B3 // SendThread
 HWL ME_545225640060 // IOHandlers
 HWL ME_54534F3D0029 // ReceiveThread
 HWL ME_546061ED0170 // ProcessThread
 HWL ME_5461D7C4021A // ReplyWaiter
 HWL ME_5465AB860254 // f_Connected
 HWL ME_5466092F01BB // f_ClientID
 HWL ME_548FEF8F0026 // IntSessionID
 HWL ME_5491709C03AC // f_IOHandlers
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_54533B010030 // SetConnected
 HWL ME_5459C7E00125 // StartProcessing
 HWL ME_5459C803038D // StopProcessing
 HWL ME_5477033C03D0 // HandShake
 HWL ME_549175C4030A // HandShakeKind
 HWL ME_5492C5F703AA // TransportStarted
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_5464B4E900DA_ME_544A09EE005F // Send
 ME_5464B52F02D5_ME_544A09EE005F // WaitForReply
 ME_5465AB2B00CA_ME_544A09EE005F // Connected
 ME_546608F101DE_ME_544A09EE005F // ClientID
 ME_5486B96A0025_ME_544A09EE005F // Processing
 ME_548FEF4F002E_ME_544A09EE005F // SessionID
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_544A09EE005F // Cleanup
 ME_47A042E100E2_ME_544A09EE005F // InitFields
 )
 ; // Overridden
 MELIST Children
   Seq: ( HWL ME_54917076009C // TncsIOHandlerArray
 )
 ; // Children
 MELIST Dependencies
   Seq: ( ME_5450A0AC017E // l3CreateStringGUID
 ME_5450DC780347 // FreeAndNil
 ME_5463161F0105 // TncsMessageKind
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsTransporter'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsTransporter'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsTransporter.pas'

ENDME // ME_544A09EE005F TncsTransporter

FORWARD ME_544A0A0D0239

FORWARD ME_549163F102D4

ME ME_549164000118
 MEPROP UID '549164000118'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_ref
 MELINK Parent HWL ME_549163F102D4 // TncsClientArray
 ;
 MELINK Target WL 'ME_54522A0E031D' '52FBB2FC0386.ms.model.script' // TncsTCPClient
 ;

ENDME // ME_549164000118 

ME ME_549163F102D4
 MEPROP UID '549163F102D4'
 MEPROP Name 'TncsClientArray'
 MEPROP Class class_Class
 MELINK Stereotype st_Vector ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELIST Inherits
   Seq: ( HWL ME_5490036B0204 // TncsSocketKind
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_549164000118 // 
 )
 ; // Attributes
 UP "array type" 'dynamic'

ENDME // ME_549163F102D4 TncsClientArray

FORWARD ME_544DF67C0075

ME ME_544DF69502E9
 MEPROP UID '544DF69502E9'
 MEPROP Name 'c_ClientConnectTimeout'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544DF67C0075 // TimeoutConsts
 ;
 MEPROP Value '10 * 1000'
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '10 * 1000'

ENDME // ME_544DF69502E9 c_ClientConnectTimeout

ME ME_544DF6C40248
 MEPROP UID '544DF6C40248'
 MEPROP Name 'c_ClientReadTimeout'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_544DF67C0075 // TimeoutConsts
 ;
 MEPROP Value '{$IFDEF CsDebug} 1000 * 1000 {$ELSE} 10 * 1000 {$ENDIF}'
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '{$IFDEF CsDebug} 1000 * 1000 {$ELSE} 10 * 1000 {$ENDIF}'

ENDME // ME_544DF6C40248 c_ClientReadTimeout

ME ME_544DF67C0075
 MEPROP UID '544DF67C0075'
 MEPROP Name 'TimeoutConsts'
 MEPROP Class class_Class
 MELINK Stereotype st_Constants ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'В миллисек' ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELIST Attributes
   Seq: ( HWL ME_544DF69502E9 // c_ClientConnectTimeout
 HWL ME_544DF6C40248 // c_ClientReadTimeout
 )
 ; // Attributes
 UP "spell names" False

ENDME // ME_544DF67C0075 TimeoutConsts

ME ME_544A21B400E4
 MEPROP UID '544A21B400E4'
 MEPROP Name 'f_TCPClients'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_ref
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELINK Target HWL ME_549163F102D4 // TncsClientArray
 ;

ENDME // ME_544A21B400E4 f_TCPClients

ME ME_54522FCE0023
 MEPROP UID '54522FCE0023'
 MEPROP Name 'TransportConnected'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;

ENDME // ME_54522FCE0023 TransportConnected

ME ME_545B400202AF
 MEPROP UID '545B400202AF'
 MEPROP Name 'SendTransportStatus'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELIST Inherits
   Seq: ( WL 'ME_545B3F72015E' '537F464A0198.ms.model.script' // TIdStatusEvent
 )
 ; // Inherits

ENDME // ME_545B400202AF SendTransportStatus

ME ME_5465A71E02F2
 MEPROP UID '5465A71E02F2'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;

ENDME // ME_5465A71E02F2 Create

ME ME_5465A72C00CA
 MEPROP UID '5465A72C00CA'
 MEPROP Name 'Make'
 MEPROP Class class_Class
 MELINK Stereotype st_Factory ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELIST Inherits
   Seq: ( HWL ME_5465A71E02F2 // Create
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5465A598039E // IncsClientTransporter
 )
 ; // Implements

ENDME // ME_5465A72C00CA Make

ME ME_5491684203A6
 MEPROP UID '5491684203A6'
 MEPROP Name 'ReceiveTransportStatus'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELIST Inherits
   Seq: ( WL 'ME_545B3F72015E' '537F464A0198.ms.model.script' // TIdStatusEvent
 )
 ; // Inherits

ENDME // ME_5491684203A6 ReceiveTransportStatus

FORWARD ME_549279980264

ME ME_2AABD500F271
 MEPROP UID '2AABD500F271'
 MEPROP Name 'DoIt'
 UP IsSummoned true
 MEPROP Class class_Operation
 %SUMMARY 'Сигнатура метода BeforeSendHandshake' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_549279980264 // BeforeSendHandshake
 ;

ENDME // ME_2AABD500F271 DoIt

ME ME_549279980264
 MEPROP UID '549279980264'
 MEPROP Name 'BeforeSendHandshake'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_2AABD500F271 // DoIt
 )
 ; // Operations

ENDME // ME_549279980264 BeforeSendHandshake

FORWARD ME_549279B300D5

ME ME_8B5B641F41AF
 MEPROP UID '8B5B641F41AF'
 MEPROP Name 'DoIt'
 UP IsSummoned true
 MEPROP Class class_Operation
 %SUMMARY 'Сигнатура метода BeforeReceiveHandshake' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_549279B300D5 // BeforeReceiveHandshake
 ;

ENDME // ME_8B5B641F41AF DoIt

ME ME_549279B300D5
 MEPROP UID '549279B300D5'
 MEPROP Name 'BeforeReceiveHandshake'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_8B5B641F41AF // DoIt
 )
 ; // Operations

ENDME // ME_549279B300D5 BeforeReceiveHandshake

ME ME_544DFC0D0116
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_544DFC0D0116 

ME ME_544E2CC40195
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELINK Target WL 'ME_4CDD241C0184' '47913B47006E.ms.model.script' // l3System
 ;

ENDME // ME_544E2CC40195 

ME ME_544E37D9032B
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELINK Target WL 'ME_544E35D90359' '537F464A0198.ms.model.script' // IdException
 ;

ENDME // ME_544E37D9032B 

ME ME_54522D8300D7
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELINK Target WL 'ME_538DB527006C' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAdapter
 ;

ENDME // ME_54522D8300D7 

ME ME_54534AD4014F
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELINK Target WL 'ME_538DDC890328' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAbstractAdapter
 ;

ENDME // ME_54534AD4014F 

ME ME_547C1F8E038F
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_547C1F8E038F 

ME ME_547C1F9501A1
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELINK Target HWL ME_547C1F31030C // TncsDisconnect
 ;

ENDME // ME_547C1F9501A1 

ME ME_547C1F9900B0
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A0A0D0239 // TncsClientTransporter
 ;
 MELINK Target HWL ME_547C1F3F025A // TncsDisconnectReply
 ;

ENDME // ME_547C1F9900B0 

ME ME_544A1FD802E9_ME_544A0A0D0239
 MELINK Original HWL ME_544A1FD802E9 // Connect
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_544A1FD802E9_ME_544A0A0D0239 Connect

ME ME_544A1FF00062_ME_544A0A0D0239
 MELINK Original HWL ME_544A1FF00062 // Disconnect
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_544A1FF00062_ME_544A0A0D0239 Disconnect

ME ME_5477033C03D0_ME_544A0A0D0239
 MELINK Original HWL ME_5477033C03D0 // HandShake
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5477033C03D0_ME_544A0A0D0239 HandShake

ME ME_549175C4030A_ME_544A0A0D0239
 MELINK Original HWL ME_549175C4030A // HandShakeKind
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_549175C4030A_ME_544A0A0D0239 HandShakeKind

ME ME_479731C50290_ME_544A0A0D0239
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_544A0A0D0239 Cleanup

ME ME_47A042E100E2_ME_544A0A0D0239
 MELINK Original WL 'ME_47A042E100E2' '47913B47006E.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_544A0A0D0239 InitFields

ME ME_544A0A0D0239
 MEPROP UID '544A0A0D0239'
 MEPROP Name 'TncsClientTransporter'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( HWL ME_544A09EE005F // TncsTransporter
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5465A598039E // IncsClientTransporter
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_544A21B400E4 // f_TCPClients
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_54522FCE0023 // TransportConnected
 HWL ME_545B400202AF // SendTransportStatus
 HWL ME_5465A71E02F2 // Create
 HWL ME_5465A72C00CA // Make
 HWL ME_5491684203A6 // ReceiveTransportStatus
 HWL ME_549279980264 // BeforeSendHandshake
 HWL ME_549279B300D5 // BeforeReceiveHandshake
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_544A1FD802E9_ME_544A0A0D0239 // Connect
 ME_544A1FF00062_ME_544A0A0D0239 // Disconnect
 ME_5477033C03D0_ME_544A0A0D0239 // HandShake
 ME_549175C4030A_ME_544A0A0D0239 // HandShakeKind
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_544A0A0D0239 // Cleanup
 ME_47A042E100E2_ME_544A0A0D0239 // InitFields
 )
 ; // Overridden
 MELIST Children
   Seq: ( HWL ME_549163F102D4 // TncsClientArray
 )
 ; // Children
 MELIST Constants
   Seq: ( HWL ME_544DF67C0075 // TimeoutConsts
 )
 ; // Constants
 MELIST Dependencies
   Seq: ( ME_544DFC0D0116 // FreeAndNil
 ME_544E2CC40195 // l3System
 ME_544E37D9032B // IdException
 ME_54522D8300D7 // TcsIdIOHandlerAdapter
 ME_54534AD4014F // TcsIdIOHandlerAbstractAdapter
 ME_547C1F8E038F // TncsMessage
 ME_547C1F9501A1 // TncsDisconnect
 ME_547C1F9900B0 // TncsDisconnectReply
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsClientTransporter'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsClientTransporter'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsClientTransporter.pas'

ENDME // ME_544A0A0D0239 TncsClientTransporter

FORWARD ME_544A0A21036B

FORWARD ME_5465A67802C1

FORWARD ME_5465A6860144

ME ME_5465A68D0008
 MEPROP Name 'anIOHandler'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_538DDC890328' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAbstractAdapter
 ;

ENDME // ME_5465A68D0008 anIOHandler

ME ME_549279210267
 MEPROP Name 'aSessionID'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_476136D3010B' '4AB0C3C60310.ms.model.script' // String
 ;

ENDME // ME_549279210267 aSessionID

ME ME_5465A6860144
 MEPROP UID '5465A6860144'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5465A67802C1 // Create
 ;
 MELIST Parameters
   Seq: ( ME_5465A68D0008 // anIOHandler
 ME_549279210267 // aSessionID
 )
 ; // Parameters

ENDME // ME_5465A6860144 DoIt

ME ME_5465A67802C1
 MEPROP UID '5465A67802C1'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544A0A21036B // TncsServerTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_5465A6860144 // DoIt
 )
 ; // Operations

ENDME // ME_5465A67802C1 Create

ME ME_5465A69A028C
 MEPROP UID '5465A69A028C'
 MEPROP Name 'IntMake'
 MEPROP Class class_Class
 MELINK Stereotype st_Factory ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544A0A21036B // TncsServerTransporter
 ;
 MELIST Inherits
   Seq: ( HWL ME_5465A67802C1 // Create
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5465A5AB0324 // IncsServerTransporter
 )
 ; // Implements

ENDME // ME_5465A69A028C IntMake

FORWARD ME_549195670058

FORWARD ME_549195830367

ME ME_54919595031C
 MEPROP Name 'anIOHandler'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_538DDC890328' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAbstractAdapter
 ;

ENDME // ME_54919595031C anIOHandler

ME ME_5492AB220174
 MEPROP Name 'IsMainSocket'
 MEPROP Class class_Parameter
 MELINK Stereotype st_out ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;

ENDME // ME_5492AB220174 IsMainSocket

ME ME_549195830367
 MEPROP UID '549195830367'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_549195670058 // Make
 ;
 MELINK Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 MELIST Parameters
   Seq: ( ME_54919595031C // anIOHandler
 ME_5492AB220174 // IsMainSocket
 )
 ; // Parameters

ENDME // ME_549195830367 DoIt

ME ME_549195670058
 MEPROP UID '549195670058'
 MEPROP Name 'Make'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544A0A21036B // TncsServerTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_549195830367 // DoIt
 )
 ; // Operations
 UP "is static" True

ENDME // ME_549195670058 Make

ME ME_5453360B0132
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A0A21036B // TncsServerTransporter
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_5453360B0132 

FORWARD ME_54917FF702A4

ME ME_5491802100DD
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_544A0A21036B // TncsServerTransporter
 ;
 MELINK Target HWL ME_54917FF702A4 // TncsServerTransporterPtrPool
 ;

ENDME // ME_5491802100DD 

ME ME_545335BF0283_ME_544A0A21036B
 MELINK Original HWL ME_545335BF0283 // ProcessMessages
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_545335BF0283_ME_544A0A21036B ProcessMessages

ME ME_5459D46D01FE_ME_544A0A21036B
 MELINK Original HWL ME_5459D46D01FE // Terminate
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5459D46D01FE_ME_544A0A21036B Terminate

ME ME_5459E3150030_ME_544A0A21036B
 MELINK Original HWL ME_5459E3150030 // Terminated
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_5459E3150030_ME_544A0A21036B Terminated

ME ME_5477033C03D0_ME_544A0A21036B
 MELINK Original HWL ME_5477033C03D0 // HandShake
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5477033C03D0_ME_544A0A21036B HandShake

ME ME_549175C4030A_ME_544A0A21036B
 MELINK Original HWL ME_549175C4030A // HandShakeKind
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_549175C4030A_ME_544A0A21036B HandShakeKind

ME ME_549180E701E0_ME_544A0A21036B
 MELINK Original HWL ME_549180E701E0 // RegisterSendBackHandler
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_549180E701E0_ME_544A0A21036B RegisterSendBackHandler

ME ME_479731C50290_ME_544A0A21036B
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_544A0A21036B Cleanup

ME ME_5492C5F703AA_ME_544A0A21036B
 MELINK Original HWL ME_5492C5F703AA // TransportStarted
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_5492C5F703AA_ME_544A0A21036B TransportStarted

ME ME_544A0A21036B
 MEPROP UID '544A0A21036B'
 MEPROP Name 'TncsServerTransporter'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( HWL ME_544A09EE005F // TncsTransporter
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5465A5AB0324 // IncsServerTransporter
 )
 ; // Implements
 MELIST Operations
   Seq: ( HWL ME_5465A67802C1 // Create
 HWL ME_5465A69A028C // IntMake
 HWL ME_549195670058 // Make
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_545335BF0283_ME_544A0A21036B // ProcessMessages
 ME_5459D46D01FE_ME_544A0A21036B // Terminate
 ME_5459E3150030_ME_544A0A21036B // Terminated
 ME_5477033C03D0_ME_544A0A21036B // HandShake
 ME_549175C4030A_ME_544A0A21036B // HandShakeKind
 ME_549180E701E0_ME_544A0A21036B // RegisterSendBackHandler
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_544A0A21036B // Cleanup
 ME_5492C5F703AA_ME_544A0A21036B // TransportStarted
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_5453360B0132 // FreeAndNil
 ME_5491802100DD // TncsServerTransporterPtrPool
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsServerTransporter'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsServerTransporter'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsServerTransporter.pas'

ENDME // ME_544A0A21036B TncsServerTransporter

ME ME_54634A7902A1
 MEPROP UID '54634A7902A1'
 MEPROP Name 'TncsLoginReply'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( HWL ME_547831BD02E5 // TncsReply
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_5461EDFB01EB' '484A470100DD.ms.model.script' // csLoginReply
 )
 ; // Implements
 UP extprop:pas:UnitName 'ncsLoginReply'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsLoginReply'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsLoginReply.pas'

ENDME // ME_54634A7902A1 TncsLoginReply

FORWARD ME_547C34C500F7

FORWARD ME_547C34E902C1

ME ME_547C34F1018C
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_547C34E902C1 // ncsServerRegister
 ;
 MELINK Target HWL ME_54539F4702B1 // TncsMessageFactory
 ;

ENDME // ME_547C34F1018C 

ME ME_547C34F5033B
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_547C34E902C1 // ncsServerRegister
 ;
 MELINK Target HWL ME_547C1F31030C // TncsDisconnect
 ;

ENDME // ME_547C34F5033B 

ME ME_547C34E902C1
 MEPROP UID '547C34E902C1'
 MEPROP Name 'ncsServerRegister'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_547C34C500F7 // nscMessagesReg
 ;
 MELIST Dependencies
   Seq: ( ME_547C34F1018C // TncsMessageFactory
 ME_547C34F5033B // TncsDisconnect
 )
 ; // Dependencies

ENDME // ME_547C34E902C1 ncsServerRegister

FORWARD ME_547C350000AA

ME ME_547C3509029E
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_547C350000AA // ncsClientRegister
 ;
 MELINK Target HWL ME_54539F4702B1 // TncsMessageFactory
 ;

ENDME // ME_547C3509029E 

ME ME_547C350E00F1
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_547C350000AA // ncsClientRegister
 ;
 MELINK Target HWL ME_547C1F3F025A // TncsDisconnectReply
 ;

ENDME // ME_547C350E00F1 

ME ME_547C350000AA
 MEPROP UID '547C350000AA'
 MEPROP Name 'ncsClientRegister'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_547C34C500F7 // nscMessagesReg
 ;
 MELIST Dependencies
   Seq: ( ME_547C3509029E // TncsMessageFactory
 ME_547C350E00F1 // TncsDisconnectReply
 )
 ; // Dependencies

ENDME // ME_547C350000AA ncsClientRegister

ME ME_547C34C500F7
 MEPROP UID '547C34C500F7'
 MEPROP Name 'nscMessagesReg'
 MEPROP Class class_Class
 MELINK Stereotype st_UtilityPack ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Operations
   Seq: ( HWL ME_547C34E902C1 // ncsServerRegister
 HWL ME_547C350000AA // ncsClientRegister
 )
 ; // Operations
 UP extprop:rc:SelfName 'MessagesReg'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\nscMessagesReg.pas'

ENDME // ME_547C34C500F7 nscMessagesReg

ME ME_548AC830032D
 MEPROP UID '548AC830032D'
 MEPROP Name 'g_SaveMessage'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 MELINK Target WL 'ME_548007530030' '47D0290B016D.ms.model.script' // Tl3StopWatch
 ;

ENDME // ME_548AC830032D g_SaveMessage

ME ME_548AC85F004C
 MEPROP UID '548AC85F004C'
 MEPROP Name 'g_LoadMessage'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 MELINK Target WL 'ME_548007530030' '47D0290B016D.ms.model.script' // Tl3StopWatch
 ;

ENDME // ME_548AC85F004C g_LoadMessage

ME ME_548AC871032C
 MEPROP UID '548AC871032C'
 MEPROP Name 'g_SendMessage'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 MELINK Target WL 'ME_548007530030' '47D0290B016D.ms.model.script' // Tl3StopWatch
 ;

ENDME // ME_548AC871032C g_SendMessage

ME ME_548AC87E031F
 MEPROP UID '548AC87E031F'
 MEPROP Name 'g_ReveiveMessage'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 MELINK Target WL 'ME_548007530030' '47D0290B016D.ms.model.script' // Tl3StopWatch
 ;

ENDME // ME_548AC87E031F g_ReveiveMessage

ME ME_548AC89000B2
 MEPROP UID '548AC89000B2'
 MEPROP Name 'g_WaitFile'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 MELINK Target WL 'ME_548007530030' '47D0290B016D.ms.model.script' // Tl3StopWatch
 ;

ENDME // ME_548AC89000B2 g_WaitFile

ME ME_54C1F62E02A0
 MEPROP UID '54C1F62E02A0'
 MEPROP Name 'g_ReceivePartFile'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 MELINK Target WL 'ME_548007530030' '47D0290B016D.ms.model.script' // Tl3StopWatch
 ;

ENDME // ME_54C1F62E02A0 g_ReceivePartFile

ME ME_54C216A50244
 MEPROP UID '54C216A50244'
 MEPROP Name 'g_SaveControl'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 MELINK Target WL 'ME_548007530030' '47D0290B016D.ms.model.script' // Tl3StopWatch
 ;

ENDME // ME_54C216A50244 g_SaveControl

ME ME_54C216BB03A8
 MEPROP UID '54C216BB03A8'
 MEPROP Name 'g_WriteFile'
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_548AC7FB0046 // ncsProfile
 ;
 MELINK Target WL 'ME_548007530030' '47D0290B016D.ms.model.script' // Tl3StopWatch
 ;

ENDME // ME_54C216BB03A8 g_WriteFile

ME ME_548AC7FB0046
 MEPROP UID '548AC7FB0046'
 MEPROP Name 'ncsProfile'
 MEPROP Class class_Class
 MELINK Stereotype st_UtilityPack ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Attributes
   Seq: ( HWL ME_548AC830032D // g_SaveMessage
 HWL ME_548AC85F004C // g_LoadMessage
 HWL ME_548AC871032C // g_SendMessage
 HWL ME_548AC87E031F // g_ReveiveMessage
 HWL ME_548AC89000B2 // g_WaitFile
 HWL ME_54C1F62E02A0 // g_ReceivePartFile
 HWL ME_54C216A50244 // g_SaveControl
 HWL ME_54C216BB03A8 // g_WriteFile
 )
 ; // Attributes
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsProfile.pas'

ENDME // ME_548AC7FB0046 ncsProfile

FORWARD ME_5492D7AC0214

ME ME_5492D7DE03B9
 MEPROP UID '5492D7DE03B9'
 MEPROP Name 'ItemType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_5492D7AC0214 // TncsServerTransporterPtrList
 ;
 MELINK Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;

ENDME // ME_5492D7DE03B9 ItemType

ME ME_5492D7AC0214
 MEPROP UID '5492D7AC0214'
 MEPROP Name 'TncsServerTransporterPtrList'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4A54DD4E036F' '47913B47006E.ms.model.script' // Tl3ProtoDataContainer
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_47B57D630029' '47913B47006E.ms.model.script' // l3InterfacePtrList
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_5492D7DE03B9 // ItemType
 )
 ; // Attributes
 UP extprop:pas:UnitName 'ncsServerTransporterPtrList'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsServerTransporterPtrList'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsServerTransporterPtrList.pas'

ENDME // ME_5492D7AC0214 TncsServerTransporterPtrList

ME ME_5492D81C00D8
 MEPROP UID '5492D81C00D8'
 MEPROP Name 'f_Data'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54917FF702A4 // TncsServerTransporterPtrPool
 ;
 MELINK Target HWL ME_5492D7AC0214 // TncsServerTransporterPtrList
 ;

ENDME // ME_5492D81C00D8 f_Data

FORWARD ME_5492D83203D7

ME ME_5492D83900EF
 MEPROP Name 'aTransporter'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;

ENDME // ME_5492D83900EF aTransporter

ME ME_5492D83203D7
 MEPROP UID '5492D83203D7'
 MEPROP Name 'Register'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54917FF702A4 // TncsServerTransporterPtrPool
 ;
 MELIST Parameters
   Seq: ( ME_5492D83900EF // aTransporter
 )
 ; // Parameters

ENDME // ME_5492D83203D7 Register

FORWARD ME_5492D8470118

ME ME_5492D84C01FA
 MEPROP Name 'aTransporter'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;

ENDME // ME_5492D84C01FA aTransporter

ME ME_5492D8470118
 MEPROP UID '5492D8470118'
 MEPROP Name 'UnRegister'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54917FF702A4 // TncsServerTransporterPtrPool
 ;
 MELIST Parameters
   Seq: ( ME_5492D84C01FA // aTransporter
 )
 ; // Parameters

ENDME // ME_5492D8470118 UnRegister

FORWARD ME_5492D85A0389

ME ME_5492D86002D4
 MEPROP Name 'aSessionID'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_476136D3010B' '4AB0C3C60310.ms.model.script' // String
 ;

ENDME // ME_5492D86002D4 aSessionID

ME ME_5492D85A0389
 MEPROP UID '5492D85A0389'
 MEPROP Name 'FindTransporter'
 MEPROP Class class_Operation
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54917FF702A4 // TncsServerTransporterPtrPool
 ;
 MELINK Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 MELIST Parameters
   Seq: ( ME_5492D86002D4 // aSessionID
 )
 ; // Parameters

ENDME // ME_5492D85A0389 FindTransporter

ME ME_479731C50290_ME_54917FF702A4
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_54917FF702A4 Cleanup

ME ME_47A042E100E2_ME_54917FF702A4
 MELINK Original WL 'ME_47A042E100E2' '47913B47006E.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_54917FF702A4 InitFields

ME ME_54917FF702A4
 MEPROP UID '54917FF702A4'
 MEPROP Name 'TncsServerTransporterPtrPool'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.ms.model.script' // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_53A03846011C' '53A038340371.ms.model.script' // l3CriticalSectionHolder
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_5492D81C00D8 // f_Data
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_5492D83203D7 // Register
 HWL ME_5492D8470118 // UnRegister
 HWL ME_5492D85A0389 // FindTransporter
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_54917FF702A4 // Cleanup
 ME_47A042E100E2_ME_54917FF702A4 // InitFields
 )
 ; // Overridden
 UP "singleton" True
 UP extprop:pas:UnitName 'ncsServerTransporterPtrPool'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsServerTransporterPtrPool'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsServerTransporterPtrPool.pas'

ENDME // ME_54917FF702A4 TncsServerTransporterPtrPool

FORWARD ME_547708500384

ME ME_5481A0B20013
 MEPROP UID '5481A0B20013'
 MEPROP Name 'f_QueryID'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_547708500384 // TncsCompatibilityClientTransporter
 ;
 MELINK Target WL 'ME_537F63760334' '52FBB2FC0386.ms.model.script' // TCsQueryId
 ;

ENDME // ME_5481A0B20013 f_QueryID

FORWARD ME_5481A0E30063

FORWARD ME_5481A0F10108

ME ME_5481A10903D0
 MEPROP Name 'aQueryID'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_537F63760334' '52FBB2FC0386.ms.model.script' // TCsQueryId
 ;

ENDME // ME_5481A10903D0 aQueryID

ME ME_5481A0F10108
 MEPROP UID '5481A0F10108'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_5481A0E30063 // Create
 ;
 MELIST Parameters
   Seq: ( ME_5481A10903D0 // aQueryID
 )
 ; // Parameters

ENDME // ME_5481A0F10108 DoIt

ME ME_5481A0E30063
 MEPROP UID '5481A0E30063'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_547708500384 // TncsCompatibilityClientTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_5481A0F10108 // DoIt
 )
 ; // Operations

ENDME // ME_5481A0E30063 Create

ME ME_5481A13200D2
 MEPROP UID '5481A13200D2'
 MEPROP Name 'Make'
 MEPROP Class class_Class
 MELINK Stereotype st_Factory ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_547708500384 // TncsCompatibilityClientTransporter
 ;
 MELIST Inherits
   Seq: ( HWL ME_5481A0E30063 // Create
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5465A598039E // IncsClientTransporter
 )
 ; // Implements

ENDME // ME_5481A13200D2 Make

ME ME_547708AE00EC
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_547708500384 // TncsCompatibilityClientTransporter
 ;
 MELINK Target WL 'ME_545C9ADE01F3' '52FBB2FC0386.ms.model.script' // cProtocolVersion
 ;

ENDME // ME_547708AE00EC 

ME ME_549279980264_ME_547708500384
 MELINK Original HWL ME_549279980264 // BeforeSendHandshake
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_549279980264_ME_547708500384 BeforeSendHandshake

ME ME_549279B300D5_ME_547708500384
 MELINK Original HWL ME_549279B300D5 // BeforeReceiveHandshake
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_549279B300D5_ME_547708500384 BeforeReceiveHandshake

ME ME_547708500384
 MEPROP UID '547708500384'
 MEPROP Name 'TncsCompatibilityClientTransporter'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( HWL ME_544A0A0D0239 // TncsClientTransporter
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_5481A0B20013 // f_QueryID
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_5481A0E30063 // Create
 HWL ME_5481A13200D2 // Make
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_549279980264_ME_547708500384 // BeforeSendHandshake
 ME_549279B300D5_ME_547708500384 // BeforeReceiveHandshake
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_547708AE00EC // cProtocolVersion
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsCompatibilityClientTransporter'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsCompatibilityClientTransporter'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsCompatibilityClientTransporter.pas'

ENDME // ME_547708500384 TncsCompatibilityClientTransporter

FORWARD ME_54E333CD0130

ME ME_54E33448033C
 MEPROP UID '54E33448033C'
 MEPROP Name 'IntSessionID'
 MEPROP Class class_Attribute
 MELINK Stereotype st_property::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target WL 'ME_476136D3010B' '4AB0C3C60310.ms.model.script' // String
 ;
 UP "pm" True
 UP "reads field" True
 UP "writes field" True

ENDME // ME_54E33448033C IntSessionID

ME ME_54E3346203DE
 MEPROP UID '54E3346203DE'
 MEPROP Name 'f_ClientID'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target WL 'ME_537F4A04037C' '52FBB2FC0386.ms.model.script' // TCsClientId
 ;

ENDME // ME_54E3346203DE f_ClientID

ME ME_54E3347301B2
 MEPROP UID '54E3347301B2'
 MEPROP Name 'f_Connected'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;

ENDME // ME_54E3347301B2 f_Connected

ME ME_54E334830061
 MEPROP UID '54E334830061'
 MEPROP Name 'IOHandler'
 MEPROP Class class_Attribute
 MELINK Stereotype st_property::Attribute ;
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target WL 'ME_538DDC890328' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAbstractAdapter
 ;
 UP "pm" True
 UP "reads field" True

ENDME // ME_54E334830061 IOHandler

FORWARD ME_54E334CD02E9

FORWARD ME_54E334DA0249

ME ME_54E334E6039D
 MEPROP Name 'aValue'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46A603BB0391' '4AB0C3C60310.ms.model.script' // Boolean
 ;

ENDME // ME_54E334E6039D aValue

ME ME_54E334DA0249
 MEPROP UID '54E334DA0249'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E334CD02E9 // SetConnected
 ;
 MELIST Parameters
   Seq: ( ME_54E334E6039D // aValue
 )
 ; // Parameters

ENDME // ME_54E334DA0249 DoIt

ME ME_54E334CD02E9
 MEPROP UID '54E334CD02E9'
 MEPROP Name 'SetConnected'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_54E334DA0249 // DoIt
 )
 ; // Operations

ENDME // ME_54E334CD02E9 SetConnected

ME ME_54E334F5028C
 MEPROP UID '54E334F5028C'
 MEPROP Name 'StartProcessing'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;

ENDME // ME_54E334F5028C StartProcessing

ME ME_54E3350B01CD
 MEPROP UID '54E3350B01CD'
 MEPROP Name 'StopProcessing'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;

ENDME // ME_54E3350B01CD StopProcessing

FORWARD ME_54E3353000D8

ME ME_3C2D040A2956
 MEPROP UID '3C2D040A2956'
 MEPROP Name 'DoIt'
 UP IsSummoned true
 MEPROP Class class_Operation
 %SUMMARY 'Сигнатура метода HandShake' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E3353000D8 // HandShake
 ;

ENDME // ME_3C2D040A2956 DoIt

ME ME_54E3353000D8
 MEPROP UID '54E3353000D8'
 MEPROP Name 'HandShake'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_3C2D040A2956 // DoIt
 )
 ; // Operations

ENDME // ME_54E3353000D8 HandShake

FORWARD ME_54E335560020

ME ME_6DE12A456230
 MEPROP UID '6DE12A456230'
 MEPROP Name 'DoIt'
 UP IsSummoned true
 MEPROP Class class_Operation
 %SUMMARY 'Сигнатура метода TransportStarted' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E335560020 // TransportStarted
 ;

ENDME // ME_6DE12A456230 DoIt

ME ME_54E335560020
 MEPROP UID '54E335560020'
 MEPROP Name 'TransportStarted'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_6DE12A456230 // DoIt
 )
 ; // Operations

ENDME // ME_54E335560020 TransportStarted

FORWARD ME_54E45D5E01D9

FORWARD ME_54E45D6B00CC

ME ME_54E45D780172
 MEPROP Name 'aMessage'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_54E45D780172 aMessage

ME ME_54E45D6B00CC
 MEPROP UID '54E45D6B00CC'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E45D5E01D9 // ProcessMessage
 ;
 MELIST Parameters
   Seq: ( ME_54E45D780172 // aMessage
 )
 ; // Parameters

ENDME // ME_54E45D6B00CC DoIt

ME ME_54E45D5E01D9
 MEPROP UID '54E45D5E01D9'
 MEPROP Name 'ProcessMessage'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_54E45D6B00CC // DoIt
 )
 ; // Operations

ENDME // ME_54E45D5E01D9 ProcessMessage

ME ME_54E45D4D0010
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target WL 'ME_47E150FF028A' '4AB0997B00A2.ms.model.script' // TStream
 ;

ENDME // ME_54E45D4D0010 

ME ME_54E45D500385
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target WL 'ME_538DE3F001DC' '47913B47006E.ms.model.script' // Tl3TempMemoryStream
 ;

ENDME // ME_54E45D500385 

ME ME_54E45D9A015E
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target HWL ME_548AC7FB0046 // ncsProfile
 ;

ENDME // ME_54E45D9A015E 

ME ME_54E45DB9021F
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_54E45DB9021F 

ME ME_54E45DD30091
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target HWL ME_54539F4702B1 // TncsMessageFactory
 ;

ENDME // ME_54E45DD30091 

ME ME_54E45DD6032B
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target WL 'ME_5461CFB8002C' '484A470100DD.ms.model.script' // TncsMessageKind
 ;

ENDME // ME_54E45DD6032B 

ME ME_54E45DEA009C
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target WL 'ME_4CDD241C0184' '47913B47006E.ms.model.script' // l3System
 ;

ENDME // ME_54E45DEA009C 

ME ME_54E4637B0261
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target HWL ME_54607384020A // TncsMessageExecutorFactory
 ;

ENDME // ME_54E4637B0261 

ME ME_54EC261601C5
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E333CD0130 // TncsSynchroTransporter
 ;
 MELINK Target WL 'ME_54EC25F3023A' '4AB0997B00A2.ms.model.script' // MillisecondsBetween
 ;

ENDME // ME_54EC261601C5 

ME ME_5464B4E900DA_ME_54E333CD0130
 MELINK Original HWL ME_5464B4E900DA // Send
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5464B4E900DA_ME_54E333CD0130 Send

ME ME_5464B52F02D5_ME_54E333CD0130
 MELINK Original HWL ME_5464B52F02D5 // WaitForReply
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5464B52F02D5_ME_54E333CD0130 WaitForReply

ME ME_5465AB2B00CA_ME_54E333CD0130
 MELINK Original HWL ME_5465AB2B00CA // Connected
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_5465AB2B00CA_ME_54E333CD0130 Connected

ME ME_546608F101DE_ME_54E333CD0130
 MELINK Original HWL ME_546608F101DE // ClientID
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_546608F101DE_ME_54E333CD0130 ClientID

ME ME_5486B96A0025_ME_54E333CD0130
 MELINK Original HWL ME_5486B96A0025 // Processing
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_5486B96A0025_ME_54E333CD0130 Processing

ME ME_548FEF4F002E_ME_54E333CD0130
 MELINK Original HWL ME_548FEF4F002E // SessionID
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_548FEF4F002E_ME_54E333CD0130 SessionID

ME ME_479731C50290_ME_54E333CD0130
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_54E333CD0130 Cleanup

ME ME_47A042E100E2_ME_54E333CD0130
 MELINK Original WL 'ME_47A042E100E2' '47913B47006E.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_54E333CD0130 InitFields

ME ME_54E333CD0130
 MEPROP UID '54E333CD0130'
 MEPROP Name 'TncsSynchroTransporter'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( WL 'ME_49E7754802A9' '47913B47006E.ms.model.script' // Tl3ProtoObject
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5464B4730055 // IncsTransporter
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_54E33448033C // IntSessionID
 HWL ME_54E3346203DE // f_ClientID
 HWL ME_54E3347301B2 // f_Connected
 HWL ME_54E334830061 // IOHandler
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_54E334CD02E9 // SetConnected
 HWL ME_54E334F5028C // StartProcessing
 HWL ME_54E3350B01CD // StopProcessing
 HWL ME_54E3353000D8 // HandShake
 HWL ME_54E335560020 // TransportStarted
 HWL ME_54E45D5E01D9 // ProcessMessage
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_5464B4E900DA_ME_54E333CD0130 // Send
 ME_5464B52F02D5_ME_54E333CD0130 // WaitForReply
 ME_5465AB2B00CA_ME_54E333CD0130 // Connected
 ME_546608F101DE_ME_54E333CD0130 // ClientID
 ME_5486B96A0025_ME_54E333CD0130 // Processing
 ME_548FEF4F002E_ME_54E333CD0130 // SessionID
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_54E333CD0130 // Cleanup
 ME_47A042E100E2_ME_54E333CD0130 // InitFields
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_54E45D4D0010 // TStream
 ME_54E45D500385 // Tl3TempMemoryStream
 ME_54E45D9A015E // ncsProfile
 ME_54E45DB9021F // FreeAndNil
 ME_54E45DD30091 // TncsMessageFactory
 ME_54E45DD6032B // TncsMessageKind
 ME_54E45DEA009C // l3System
 ME_54E4637B0261 // TncsMessageExecutorFactory
 ME_54EC261601C5 // MillisecondsBetween
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsSynchroTransporter'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsSynchroTransporter'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsSynchroTransporter.pas'

ENDME // ME_54E333CD0130 TncsSynchroTransporter

FORWARD ME_54E339B500F7

ME ME_54E33B0E00EE
 MEPROP UID '54E33B0E00EE'
 MEPROP Name 'f_TCPClient'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELINK Target WL 'ME_54522A0E031D' '52FBB2FC0386.ms.model.script' // TncsTCPClient
 ;

ENDME // ME_54E33B0E00EE f_TCPClient

ME ME_54E33A870172
 MEPROP UID '54E33A870172'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;

ENDME // ME_54E33A870172 Create

ME ME_54E33A920344
 MEPROP UID '54E33A920344'
 MEPROP Name 'Make'
 MEPROP Class class_Class
 MELINK Stereotype st_Factory ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELIST Inherits
   Seq: ( HWL ME_54E33A870172 // Create
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5465A598039E // IncsClientTransporter
 )
 ; // Implements

ENDME // ME_54E33A920344 Make

ME ME_54E33B3A02CB
 MEPROP UID '54E33B3A02CB'
 MEPROP Name 'TransportStatus'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELIST Inherits
   Seq: ( WL 'ME_545B3F72015E' '537F464A0198.ms.model.script' // TIdStatusEvent
 )
 ; // Inherits

ENDME // ME_54E33B3A02CB TransportStatus

ME ME_54E33B5E0245
 MEPROP UID '54E33B5E0245'
 MEPROP Name 'TransportConnected'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;

ENDME // ME_54E33B5E0245 TransportConnected

FORWARD ME_54E33EA40163

ME ME_9367E3A2B13B
 MEPROP UID '9367E3A2B13B'
 MEPROP Name 'DoIt'
 UP IsSummoned true
 MEPROP Class class_Operation
 %SUMMARY 'Сигнатура метода BeforeHandshake' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E33EA40163 // BeforeHandshake
 ;

ENDME // ME_9367E3A2B13B DoIt

ME ME_54E33EA40163
 MEPROP UID '54E33EA40163'
 MEPROP Name 'BeforeHandshake'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility ProtectedAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_9367E3A2B13B // DoIt
 )
 ; // Operations

ENDME // ME_54E33EA40163 BeforeHandshake

ME ME_54E33B1D023D
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELINK Target WL 'ME_538DB527006C' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAdapter
 ;

ENDME // ME_54E33B1D023D 

ME ME_54E33B220023
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELINK Target WL 'ME_538DDC890328' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAbstractAdapter
 ;

ENDME // ME_54E33B220023 

ME ME_54E34E64034C
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELINK Target WL 'ME_4CDD241C0184' '47913B47006E.ms.model.script' // l3System
 ;

ENDME // ME_54E34E64034C 

ME ME_54E34E6900C5
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELINK Target WL 'ME_544E35D90359' '537F464A0198.ms.model.script' // IdException
 ;

ENDME // ME_54E34E6900C5 

ME ME_54E34E6E01B7
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_54E34E6E01B7 

ME ME_54E34E7201A1
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELINK Target WL 'ME_538DDC890328' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAbstractAdapter
 ;

ENDME // ME_54E34E7201A1 

ME ME_54E34E770042
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_54E34E770042 

ME ME_54E34E7B0116
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELINK Target HWL ME_547C1F31030C // TncsDisconnect
 ;

ENDME // ME_54E34E7B0116 

ME ME_54E34E7F017D
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELINK Target HWL ME_547C1F3F025A // TncsDisconnectReply
 ;

ENDME // ME_54E34E7F017D 

ME ME_54E34E8302CE
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 ;
 MELINK Target WL 'ME_538DB527006C' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAdapter
 ;

ENDME // ME_54E34E8302CE 

ME ME_544A1FD802E9_ME_54E339B500F7
 MELINK Original HWL ME_544A1FD802E9 // Connect
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_544A1FD802E9_ME_54E339B500F7 Connect

ME ME_544A1FF00062_ME_54E339B500F7
 MELINK Original HWL ME_544A1FF00062 // Disconnect
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_544A1FF00062_ME_54E339B500F7 Disconnect

ME ME_54E3353000D8_ME_54E339B500F7
 MELINK Original HWL ME_54E3353000D8 // HandShake
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_54E3353000D8_ME_54E339B500F7 HandShake

ME ME_479731C50290_ME_54E339B500F7
 MELINK Original WL 'ME_479731C50290' '51612EBB02F5.ms.model.script' // Cleanup
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_479731C50290_ME_54E339B500F7 Cleanup

ME ME_47A042E100E2_ME_54E339B500F7
 MELINK Original WL 'ME_47A042E100E2' '47913B47006E.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_47A042E100E2_ME_54E339B500F7 InitFields

ME ME_54E339B500F7
 MEPROP UID '54E339B500F7'
 MEPROP Name 'TncsSynchroClientTransporter'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( HWL ME_54E333CD0130 // TncsSynchroTransporter
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5465A598039E // IncsClientTransporter
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_54E33B0E00EE // f_TCPClient
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_54E33A870172 // Create
 HWL ME_54E33A920344 // Make
 HWL ME_54E33B3A02CB // TransportStatus
 HWL ME_54E33B5E0245 // TransportConnected
 HWL ME_54E33EA40163 // BeforeHandshake
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_544A1FD802E9_ME_54E339B500F7 // Connect
 ME_544A1FF00062_ME_54E339B500F7 // Disconnect
 ME_54E3353000D8_ME_54E339B500F7 // HandShake
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_479731C50290_ME_54E339B500F7 // Cleanup
 ME_47A042E100E2_ME_54E339B500F7 // InitFields
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_54E33B1D023D // TcsIdIOHandlerAdapter
 ME_54E33B220023 // TcsIdIOHandlerAbstractAdapter
 ME_54E34E64034C // l3System
 ME_54E34E6900C5 // IdException
 ME_54E34E6E01B7 // FreeAndNil
 ME_54E34E7201A1 // TcsIdIOHandlerAbstractAdapter
 ME_54E34E770042 // TncsMessage
 ME_54E34E7B0116 // TncsDisconnect
 ME_54E34E7F017D // TncsDisconnectReply
 ME_54E34E8302CE // TcsIdIOHandlerAdapter
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsSynchroClientTransporter'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsSynchroClientTransporter'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsSynchroClientTransporter.pas'

ENDME // ME_54E339B500F7 TncsSynchroClientTransporter

FORWARD ME_54E33DBC0063

ME ME_54E33E0F03C2
 MEPROP UID '54E33E0F03C2'
 MEPROP Name 'f_QueryID'
 MEPROP Class class_Attribute
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_54E33DBC0063 // TncsSynchroCompatibilityClientTransporter
 ;
 MELINK Target WL 'ME_537F63760334' '52FBB2FC0386.ms.model.script' // TCsQueryId
 ;

ENDME // ME_54E33E0F03C2 f_QueryID

FORWARD ME_54E33E1A00B4

FORWARD ME_54E33E3D00DB

ME ME_54E33E3F01E1
 MEPROP Name 'aQueryID'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_537F63760334' '52FBB2FC0386.ms.model.script' // TCsQueryId
 ;

ENDME // ME_54E33E3F01E1 aQueryID

ME ME_54E33E3D00DB
 MEPROP UID '54E33E3D00DB'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E33E1A00B4 // Create
 ;
 MELIST Parameters
   Seq: ( ME_54E33E3F01E1 // aQueryID
 )
 ; // Parameters

ENDME // ME_54E33E3D00DB DoIt

ME ME_54E33E1A00B4
 MEPROP UID '54E33E1A00B4'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E33DBC0063 // TncsSynchroCompatibilityClientTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_54E33E3D00DB // DoIt
 )
 ; // Operations

ENDME // ME_54E33E1A00B4 Create

ME ME_54E33E23020D
 MEPROP UID '54E33E23020D'
 MEPROP Name 'Make'
 MEPROP Class class_Class
 MELINK Stereotype st_Factory ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E33DBC0063 // TncsSynchroCompatibilityClientTransporter
 ;
 MELIST Inherits
   Seq: ( HWL ME_54E33E1A00B4 // Create
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5465A598039E // IncsClientTransporter
 )
 ; // Implements

ENDME // ME_54E33E23020D Make

ME ME_54E355790184
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E33DBC0063 // TncsSynchroCompatibilityClientTransporter
 ;
 MELINK Target WL 'ME_545C9ADE01F3' '52FBB2FC0386.ms.model.script' // cProtocolVersion
 ;

ENDME // ME_54E355790184 

ME ME_54E33EA40163_ME_54E33DBC0063
 MELINK Original HWL ME_54E33EA40163 // BeforeHandshake
 ;
 MEPROP OpKind opkind_Overridden
ENDME // ME_54E33EA40163_ME_54E33DBC0063 BeforeHandshake

ME ME_54E33DBC0063
 MEPROP UID '54E33DBC0063'
 MEPROP Name 'TncsSynchroCompatibilityClientTransporter'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_54E33E0F03C2 // f_QueryID
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_54E33E1A00B4 // Create
 HWL ME_54E33E23020D // Make
 )
 ; // Operations
 MELIST Overridden
   Seq: ( ME_54E33EA40163_ME_54E33DBC0063 // BeforeHandshake
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_54E355790184 // cProtocolVersion
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsSynchroCompatibilityClientTransporter'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsSynchroCompatibilityClientTransporter'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsSynchroCompatibilityClientTransporter.pas'

ENDME // ME_54E33DBC0063 TncsSynchroCompatibilityClientTransporter

FORWARD ME_54E47AE90373

FORWARD ME_54E591B50054

FORWARD ME_54E591C00274

ME ME_54E591C4003C
 MEPROP Name 'anIOHandler'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_538DDC890328' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAbstractAdapter
 ;

ENDME // ME_54E591C4003C anIOHandler

ME ME_54E591C4005B
 MEPROP Name 'aSessionID'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_476136D3010B' '4AB0C3C60310.ms.model.script' // String
 ;

ENDME // ME_54E591C4005B aSessionID

ME ME_54E591C00274
 MEPROP UID '54E591C00274'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E591B50054 // Create
 ;
 MELIST Parameters
   Seq: ( ME_54E591C4003C // anIOHandler
 ME_54E591C4005B // aSessionID
 )
 ; // Parameters

ENDME // ME_54E591C00274 DoIt

ME ME_54E591B50054
 MEPROP UID '54E591B50054'
 MEPROP Name 'Create'
 MEPROP Class class_Class
 MELINK Stereotype st_Constructor ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_54E591C00274 // DoIt
 )
 ; // Operations

ENDME // ME_54E591B50054 Create

ME ME_54E591D102F6
 MEPROP UID '54E591D102F6'
 MEPROP Name 'IntMake'
 MEPROP Class class_Class
 MELINK Stereotype st_Factory ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELIST Inherits
   Seq: ( HWL ME_54E591B50054 // Create
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5465A5AB0324 // IncsServerTransporter
 )
 ; // Implements

ENDME // ME_54E591D102F6 IntMake

FORWARD ME_54E5920A003C

FORWARD ME_54E5921C031D

ME ME_54E5922801B3
 MEPROP Name 'anIOHandler'
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_538DDC890328' '52FBB2FC0386.ms.model.script' // TcsIdIOHandlerAbstractAdapter
 ;

ENDME // ME_54E5922801B3 anIOHandler

ME ME_54E5921C031D
 MEPROP UID '54E5921C031D'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E5920A003C // Make
 ;
 MELINK Target HWL ME_5465A5AB0324 // IncsServerTransporter
 ;
 MELIST Parameters
   Seq: ( ME_54E5922801B3 // anIOHandler
 )
 ; // Parameters

ENDME // ME_54E5921C031D DoIt

ME ME_54E5920A003C
 MEPROP UID '54E5920A003C'
 MEPROP Name 'Make'
 MEPROP Class class_Class
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELIST Operations
   Seq: ( HWL ME_54E5921C031D // DoIt
 )
 ; // Operations
 UP "is static" True

ENDME // ME_54E5920A003C Make

ME ME_54E47B4D01CC
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELINK Target WL 'ME_4ADC58F703CF' '4AB0C3C60310.ms.model.script' // FreeAndNil
 ;

ENDME // ME_54E47B4D01CC 

ME ME_54E48B7302B3
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELINK Target HWL ME_548AC7FB0046 // ncsProfile
 ;

ENDME // ME_54E48B7302B3 

ME ME_54E48B7C017B
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELINK Target WL 'ME_47E150FF028A' '4AB0997B00A2.ms.model.script' // TStream
 ;

ENDME // ME_54E48B7C017B 

ME ME_54E48BA50365
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELINK Target WL 'ME_538DE3F001DC' '47913B47006E.ms.model.script' // Tl3TempMemoryStream
 ;

ENDME // ME_54E48BA50365 

ME ME_54E48F40014E
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELINK Target HWL ME_544E079E0253 // TncsMessage
 ;

ENDME // ME_54E48F40014E 

ME ME_54E48F4A034D
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELINK Target HWL ME_54649C7C00E7 // TncsInvalidMessage
 ;

ENDME // ME_54E48F4A034D 

ME ME_54E48F55034E
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELINK Target HWL ME_547C1F31030C // TncsDisconnect
 ;

ENDME // ME_54E48F55034E 

ME ME_54E48F640365
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELINK Target HWL ME_547C1F3F025A // TncsDisconnectReply
 ;

ENDME // ME_54E48F640365 

ME ME_54E494630198
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELINK Target HWL ME_54539F4702B1 // TncsMessageFactory
 ;

ENDME // ME_54E494630198 

ME ME_54E49C38016A
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 ;
 MELINK Target WL 'ME_4CDD241C0184' '47913B47006E.ms.model.script' // l3System
 ;

ENDME // ME_54E49C38016A 

ME ME_545335BF0283_ME_54E47AE90373
 MELINK Original HWL ME_545335BF0283 // ProcessMessages
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_545335BF0283_ME_54E47AE90373 ProcessMessages

ME ME_5459D46D01FE_ME_54E47AE90373
 MELINK Original HWL ME_5459D46D01FE // Terminate
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_5459D46D01FE_ME_54E47AE90373 Terminate

ME ME_5459E3150030_ME_54E47AE90373
 MELINK Original HWL ME_5459E3150030 // Terminated
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" False
ENDME // ME_5459E3150030_ME_54E47AE90373 Terminated

ME ME_549180E701E0_ME_54E47AE90373
 MELINK Original HWL ME_549180E701E0 // RegisterSendBackHandler
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_549180E701E0_ME_54E47AE90373 RegisterSendBackHandler

ME ME_54E3353000D8_ME_54E47AE90373
 MELINK Original HWL ME_54E3353000D8 // HandShake
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_54E3353000D8_ME_54E47AE90373 HandShake

ME ME_54E47AE90373
 MEPROP UID '54E47AE90373'
 MEPROP Name 'TncsSynchroServerTransporter'
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_544E0148010D // Messages
 ;
 MELIST Inherits
   Seq: ( HWL ME_54E333CD0130 // TncsSynchroTransporter
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_5465A5AB0324 // IncsServerTransporter
 )
 ; // Implements
 MELIST Operations
   Seq: ( HWL ME_54E591B50054 // Create
 HWL ME_54E591D102F6 // IntMake
 HWL ME_54E5920A003C // Make
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_545335BF0283_ME_54E47AE90373 // ProcessMessages
 ME_5459D46D01FE_ME_54E47AE90373 // Terminate
 ME_5459E3150030_ME_54E47AE90373 // Terminated
 ME_549180E701E0_ME_54E47AE90373 // RegisterSendBackHandler
 ME_54E3353000D8_ME_54E47AE90373 // HandShake
 )
 ; // Implemented
 MELIST Dependencies
   Seq: ( ME_54E47B4D01CC // FreeAndNil
 ME_54E48B7302B3 // ncsProfile
 ME_54E48B7C017B // TStream
 ME_54E48BA50365 // Tl3TempMemoryStream
 ME_54E48F40014E // TncsMessage
 ME_54E48F4A034D // TncsInvalidMessage
 ME_54E48F55034E // TncsDisconnect
 ME_54E48F640365 // TncsDisconnectReply
 ME_54E494630198 // TncsMessageFactory
 ME_54E49C38016A // l3System
 )
 ; // Dependencies
 UP extprop:pas:UnitName 'ncsSynchroServerTransporter'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'ncsSynchroServerTransporter'
 UP intf.pas:Path 'common\components\rtl\Garant\cs\ncsSynchroServerTransporter.pas'

ENDME // ME_54E47AE90373 TncsSynchroServerTransporter

ME ME_544E0148010D
 MEPROP UID '544E0148010D'
 MEPROP Name 'Messages'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL 'ME_52F8C27F01AB' '52F8C27F01AB.ms.model.script' // cs
 ;
 MELIST Children
   Seq: ( HWL ME_544E07C6034D // TncsLoginMessage
 HWL ME_544F977F036B // TncsPriorityMessageList
 HWL ME_544E3C54031D // TncsMessageQueue
 HWL ME_5452248C02B8 // TncsTransporterThread
 HWL ME_5460B6230039 // TncsTransporterIOThread
 HWL ME_54534F1A00BF // TncsReceiveThread
 HWL ME_5461D6C30025 // TncsReplyDescription
 HWL ME_5460A4DB018A // ncsMessageInterfaces
 HWL ME_5450E9A0034A // TncsSendThread
 HWL ME_5453986402AC // ncsMessage
 HWL ME_54539F0C00AD // TncsMessageClassList
 HWL ME_54539F4702B1 // TncsMessageFactory
 HWL ME_545CBE61008B // TncsServerTransporterList
 HWL ME_545CBED90193 // TncsServerTransporterPool
 HWL ME_5461D6FC00F7 // TncsReplyDecsriptionList
 HWL ME_54609BB100BB // TncsExecutorFactoryList
 HWL ME_54607384020A // TncsMessageExecutorFactory
 HWL ME_5461D9EE0244 // TncsReplyWaiter
 HWL ME_546061CE03DA // TncsProcessThread
 HWL ME_544A09EE005F // TncsTransporter
 HWL ME_544A0A0D0239 // TncsClientTransporter
 HWL ME_544A0A21036B // TncsServerTransporter
 HWL ME_54634A7902A1 // TncsLoginReply
 HWL ME_547C34C500F7 // nscMessagesReg
 HWL ME_548AC7FB0046 // ncsProfile
 HWL ME_5492D7AC0214 // TncsServerTransporterPtrList
 HWL ME_54917FF702A4 // TncsServerTransporterPtrPool
 HWL ME_547708500384 // TncsCompatibilityClientTransporter
 HWL ME_54E333CD0130 // TncsSynchroTransporter
 HWL ME_54E339B500F7 // TncsSynchroClientTransporter
 HWL ME_54E33DBC0063 // TncsSynchroCompatibilityClientTransporter
 HWL ME_54E47AE90373 // TncsSynchroServerTransporter
 )
 ; // Children
 MELIST Depends
   Seq: ( WL 'ME_3DBFDB23006E' '3DBFDB23006E.ms.model.script' // Primitives
 WL 'ME_4678193C009C' '4678193C009C.ms.model.script' // l3Types
 WL 'ME_47913B47006E' '47913B47006E.ms.model.script' // l3CoreObjects
 WL 'ME_47D0290B016D' '47D0290B016D.ms.model.script' // l3Utils
 WL 'ME_484A470100DD' '484A470100DD.ms.model.script' // Standard
 WL 'ME_4AB0997B00A2' '4AB0997B00A2.ms.model.script' // Common
 WL 'ME_4AB0C3C60310' '4AB0C3C60310.ms.model.script' // Sys
 WL 'ME_4AB0C3F60375' '4AB0C3F60375.ms.model.script' // Win
 WL 'ME_52FBB2FC0386' '52FBB2FC0386.ms.model.script' // Core
 WL 'ME_537F464A0198' '537F464A0198.ms.model.script' // System
 WL 'ME_538DAE950337' '538DAE950337.ms.model.script' // Core
 WL 'ME_53A038340371' '53A038340371.ms.model.script' // MultiThread
 WL 'ME_53B15D5603E3' '53B15D5603E3.ms.model.script' // TagHolder
 )
 ; // Depends

ENDME // ME_544E0148010D Messages
