// ncsTCPClient 545229E7037D UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_545229E7037D_diagrams

 MEDIAGRAM ME_545229E7037D_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_545229E7037D' '52FBB2FC0386.ms.model.script' ; // ncsTCPClient

  MEVIEW ME_54522A0E031D_view
   MELINK Original WL 'ME_54522A0E031D' '52FBB2FC0386.ms.model.script' ; // TncsTCPClient
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_54522A0E031D_view

  MELIST Views
   Seq: ( ME_54522A0E031D_view // TncsTCPClient
   )
  ; // Views
 ENDMEDIAGRAM // ME_545229E7037D_main

 MELIST Diagrams
  Seq: ( ME_545229E7037D_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_545229E7037D_diagrams
