// Tm3BranchHandlePrim 5453AB7202EC SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_5453AB7202EC_diagrams

 MEDIAGRAM ME_5453AB7202EC_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_5453AB7202EC' ; // Tm3BranchHandlePrim

  MEVIEW ME_5453AD480340_view
   MELINK Original WL 'ME_5453AD480340' '5453AB7202EC.ms.model.script' ; // Tm3BranchHandlePrimData
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5453AD480340_view

  MEVIEW ME_5453ACB101F8_view
   MELINK Original WL 'ME_5453ACB101F8' '5453AB7202EC.ms.model.script' ; // Pm3BranchHandlePrim
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_5453ACB101F8_view

  MEVIEW ME_5453B699001A_view
   MELINK Original WL 'ME_5453B699001A' '5453AB7202EC.ms.model.script' ; // Tm3BranchHandlesManager
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_5453B699001A_view

  MEVIEW ME_5453AD5300BB_view
   MELINK Original WL 'ME_5453AD5300BB' '5453AB7202EC.ms.model.script' ; // Data
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_5453AD5300BB_view

  MELIST Views
   Seq: ( ME_5453AD480340_view // Tm3BranchHandlePrimData
   ME_5453ACB101F8_view // Pm3BranchHandlePrim
   ME_5453B699001A_view // Tm3BranchHandlesManager
   ME_5453AD5300BB_view // Data
   )
  ; // Views
 ENDMEDIAGRAM // ME_5453AB7202EC_main

 MELIST Diagrams
  Seq: ( ME_5453AB7202EC_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_5453AB7202EC_diagrams
