// TncsReceiveThread 54534F1A00BF SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_54534F1A00BF_diagrams

 MEDIAGRAM ME_54534F1A00BF_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_54534F1A00BF' '544E0148010D.ms.model.script' ; // TncsReceiveThread

  MEVIEW ME_5453828F0059_view
   MELINK Original WL 'ME_5453828F0059' '544E0148010D.ms.model.script' ; // ThreadTimeouts
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5453828F0059_view

  MELIST Views
   Seq: ( ME_5453828F0059_view // ThreadTimeouts
   )
  ; // Views
 ENDMEDIAGRAM // ME_54534F1A00BF_main

 MELIST Diagrams
  Seq: ( ME_54534F1A00BF_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_54534F1A00BF_diagrams
