// vcmMainMenuForChromeLikeTypes 545C53AA026E UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_545C53AA026E_diagrams

 MEDIAGRAM ME_545C53AA026E_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_545C53AA026E' '533D53FF00C2.ms.model.script' ; // vcmMainMenuForChromeLikeTypes

  MEVIEW ME_5477697F0366_view
   MELINK Original WL 'ME_5477697F0366' '533D53FF00C2.ms.model.script' ; // TvcmMenuForChromeLikeItem
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5477697F0366_view

  MELIST Views
   Seq: ( ME_5477697F0366_view // TvcmMenuForChromeLikeItem
   )
  ; // Views
 ENDMEDIAGRAM // ME_545C53AA026E_main

 MELIST Diagrams
  Seq: ( ME_545C53AA026E_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_545C53AA026E_diagrams
