// ResultDelivery 5465E6BB0264 Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_5465E6BB0264_diagrams

 MEDIAGRAM ME_5465E6BB0264_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_5465E6BB0264' ; // ResultDelivery

  MEVIEW ME_5465D93A0165_view
   MELINK Original WL? 'ME_5465D93A0165' ; // TalcuGetReadyToDeliveryTasksExecutor
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5465D93A0165_view

  MEVIEW ME_546B540E02D6_view
   MELINK Original WL? 'ME_546B540E02D6' ; // TalcuGetTaskDescriptionExecutor
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_546B540E02D6_view

  MEVIEW ME_54748E8A0085_view
   MELINK Original WL? 'ME_54748E8A0085' ; // TalcuTaskProgressExecutor
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_54748E8A0085_view

  MEVIEW ME_54759BE1037A_view
   MELINK Original WL? 'ME_54759BE1037A' ; // TalcuDeliveryResultExecutor
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_54759BE1037A_view

  MEVIEW ME_54759BFB02B4_view
   MELINK Original WL? 'ME_54759BFB02B4' ; // TalcuGetFilePartExecutor
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_54759BFB02B4_view

  MEVIEW ME_549AC018025D_view
   MELINK Original WL? 'ME_549AC018025D' ; // TalcuCorrectFolderExecutor
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_549AC018025D_view

  MELIST Views
   Seq: ( ME_5465D93A0165_view // TalcuGetReadyToDeliveryTasksExecutor
   ME_546B540E02D6_view // TalcuGetTaskDescriptionExecutor
   ME_54748E8A0085_view // TalcuTaskProgressExecutor
   ME_54759BE1037A_view // TalcuDeliveryResultExecutor
   ME_54759BFB02B4_view // TalcuGetFilePartExecutor
   ME_549AC018025D_view // TalcuCorrectFolderExecutor
   )
  ; // Views
 ENDMEDIAGRAM // ME_5465E6BB0264_main

 MELIST Diagrams
  Seq: ( ME_5465E6BB0264_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_5465E6BB0264_diagrams
