// TalcuGetReadyToDeliveryTasksExecutor 5465D93A0165 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_5465D93A0165_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_5465D93A0165' '5465E6BB0264.ms.model.script' ; // TalcuGetReadyToDeliveryTasksExecutor

 MEVIEW ME_5465DA310356_view
  MELINK Original WL 'ME_5465DA310356' '5465E6BB0264.ms.model.script' ; // Make
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_5465DA310356_view

ENDMEDIAGRAM // ME_5465D93A0165_main
