// zlibh 546F146A0008 UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_546F146A0008_diagrams

 MEDIAGRAM ME_546F146A0008_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_546F146A0008' '546F146A0008.ms.model.script' ; // zlibh

  MELIST Views
   Seq: ( )
  ; // Views
 ENDMEDIAGRAM // ME_546F146A0008_main

 MELIST Diagrams
  Seq: ( ME_546F146A0008_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_546F146A0008_diagrams
