// IevSubPanel 547CA1B10228 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_547CA1B10228_diagrams

 MEDIAGRAM ME_547CA1B10228_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_547CA1B10228' '547C9F6D029C.ms.model.script' ; // IevSubPanel

  MEVIEW ME_547CA1CA0126_view
   MELINK Original WL 'ME_547CA1CA0126' '547C9F6D029C.ms.model.script' ; // NeedDrawSub
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_547CA1CA0126_view

  MELIST Views
   Seq: ( ME_547CA1CA0126_view // NeedDrawSub
   )
  ; // Views
 ENDMEDIAGRAM // ME_547CA1B10228_main

 MELIST Diagrams
  Seq: ( ME_547CA1B10228_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_547CA1B10228_diagrams
