// evSubPanelTools 5480995800BA UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_5480995800BA_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_5480995800BA' '4B87B5720153.ms.model.script' ; // evSubPanelTools

 MEVIEW ME_4B87BB100265_view
  MELINK Original WL 'ME_4B87BB100265' '4B87B5720153.ms.model.script' ; // evInvalidateRect
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_4B87BB100265_view

ENDMEDIAGRAM // ME_5480995800BA_main
