// TaskSend 54855BDB033D Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_54855C2F0088
%%Inner ME_54855C4200D7
%%Inner ME_54855CA501E1
%%Inner ME_54B66DB30346
%%Inner ME_54B7B37003C6
%%Inner ME_54B7B3D203C6
%%Inner ME_5481B39101AF

ME ME_54855BDB033D
 MEPROP UID '54855BDB033D'
 MEPROP Name 'TaskSend'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_52F8C27F01AB' // cs
 ;
 MELIST Children
   Seq: ( WL? 'ME_54855C2F0088' // TncsSendTask
 WL? 'ME_54855C4200D7' // TncsSendTaskReply
 WL? 'ME_54855CA501E1' // ncsTaskSendReg
 WL? 'ME_54B66DB30346' // TncsGetPartialTaskDescription
 WL? 'ME_54B7B37003C6' // TncsGetPartialTaskDescriptionExecutor
 WL? 'ME_54B7B3D203C6' // TncsGetFilePartExecutor
 WL? 'ME_5481B39101AF' // TncsTaskSendExecutorFactory
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4678193C009C' // l3Types
 WL? 'ME_47913B47006E' // l3CoreObjects
 WL? 'ME_47D0290B016D' // l3Utils
 WL? 'ME_484A470100DD' // Standard
 WL? 'ME_4AB0997B00A2' // Common
 WL? 'ME_4AB0C3C60310' // Sys
 WL? 'ME_52F8C298005C' // Tasks
 WL? 'ME_544E0148010D' // Messages
 WL? 'ME_546457E203C0' // ResultDelivery
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Messages' 'Uses' )
 ; // DiagramsNames

ENDME // ME_54855BDB033D TaskSend
