// vtFlashWords 54EC8EE003AB ScriptKeywords Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_54EC8EE003AB_diagrams

 MEDIAGRAM ME_54EC8EE003AB_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_54EC8EE003AB' '54EC8EE003AB.ms.model.script' ; // vtFlashWords

  MEVIEW ME_54EC8F930357_view
   MELINK Original WL 'ME_54EC8F930357' '54EC8EE003AB.ms.model.script' ; // vtFlashWordsPack
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_54EC8F930357_view

  MELIST Views
   Seq: ( ME_54EC8F930357_view // vtFlashWordsPack
   )
  ; // Views
 ENDMEDIAGRAM // ME_54EC8EE003AB_main

 MELIST Diagrams
  Seq: ( ME_54EC8EE003AB_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_54EC8EE003AB_diagrams
