// ScriptEngine$L3 54EF440B0244 Library Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_54EF44350184
%%Inner ME_53B52E99013D
%%Inner ME_552CF42C0230
%%Inner ME_552D07E00278
%%Inner ME_5190B06F00C1

ME ME_54EF440B0244
 MEPROP UID '54EF440B0244'
 MEPROP Name 'ScriptEngine'
 MEPROP OriginalName 'ScriptEngine$L3'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Library ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_4ABCC25A0322' // Shared Delphi Low Level
 ;
 MELIST Children
   Seq: ( WL? 'ME_54EF44350184' // l3SimpleNodeWords
 WL? 'ME_53B52E99013D' // l3NodeWords
 WL? 'ME_552CF42C0230' // PictureEtalonsWorking
 WL? 'ME_552D07E00278' // Autolink
 WL? 'ME_5190B06F00C1' // FontKeywords
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_469F3E37025A' // Rtl
 WL? 'ME_4790D09A0378' // L3
 WL? 'ME_4E2F0E1B03BB' // L3$Domain
 WL? 'ME_54CF97B10370' // ScriptEngine$Core
 WL? 'ME_550012C403C4' // L3$AFW
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "defines" 'seDefine.inc'
 UP "gui" 'rtl'
 UP "ifndef" 'NoScripts'
 UP "UseNewGen" True
 UP intf.pas:PathOnly '\common\components\rtl\Garant\ScriptEngine'

ENDME // ME_54EF440B0244 ScriptEngine$L3
