// TafwTabInterfaceType 54EFFC7602E3 Enum Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_54EFFC7602E3_diagrams

 MEDIAGRAM ME_54EFFC7602E3_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_54EFFC7602E3' '467823B7002C.ms.model.script' ; // TafwTabInterfaceType

  MEVIEW ME_54EFFCB8027B_view
   MELINK Original WL 'ME_54EFFCB8027B' '467823B7002C.ms.model.script' ; // afw_titNoTabs
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_54EFFCB8027B_view

  MEVIEW ME_54EFFCCD0061_view
   MELINK Original WL 'ME_54EFFCCD0061' '467823B7002C.ms.model.script' ; // afw_titTabs
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_54EFFCCD0061_view

  MEVIEW ME_54EFFCD501F1_view
   MELINK Original WL 'ME_54EFFCD501F1' '467823B7002C.ms.model.script' ; // afw_titTabsDisabled
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_54EFFCD501F1_view

  MELIST Views
   Seq: ( ME_54EFFCB8027B_view // afw_titNoTabs
   ME_54EFFCCD0061_view // afw_titTabs
   ME_54EFFCD501F1_view // afw_titTabsDisabled
   )
  ; // Views
 ENDMEDIAGRAM // ME_54EFFC7602E3_main

 MELIST Diagrams
  Seq: ( ME_54EFFC7602E3_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_54EFFC7602E3_diagrams
