// InpharmControllers 550AA6E1017D VCMControllers Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_550AA6E1017D_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_550AA6E1017D' '550AA6E1017D.ms.model.script' ; // InpharmControllers

 MEVIEW ME_550AA7200370_view
  MELINK Original WL 'ME_550AA7200370' '550AA7200370.ms.model.script' ; // InpharmMainMenuControllerRealization
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_550AA7200370_view

ENDMEDIAGRAM // ME_550AA6E1017D_main
