// evCollapsedStylePainter 5514FB530333 Impurity Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_5514FB530333_diagrams

 MEDIAGRAM ME_5514FB530333_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_5514FB530333' '49DCBC09029B.ms.model.script' ; // evCollapsedStylePainter

  MEVIEW ME_5514FC280243_view
   MELINK Original WL 'ME_5514FC280243' '49DCBC09029B.ms.model.script' ; // DoDoDrawFrameText
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5514FC280243_view

  MELIST Views
   Seq: ( ME_5514FC280243_view // DoDoDrawFrameText
   )
  ; // Views
 ENDMEDIAGRAM // ME_5514FB530333_main

 MELIST Diagrams
  Seq: ( ME_5514FB530333_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_5514FB530333_diagrams
