// ThtDataProvider 5519351D01BE SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_5519351D01BE_diagrams

 MEDIAGRAM ME_5519351D01BE_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_5519351D01BE' '54F9AF550087.ms.model.script' ; // ThtDataProvider

  MEVIEW ME_551938260196_view
   MELINK Original WL 'ME_551938260196' '54F9AF550087.ms.model.script' ; // Create
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_551938260196_view

  MEVIEW ME_551938550022_view
   MELINK Original WL 'ME_551938550022' '54F9AF550087.ms.model.script' ; // Make
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_551938550022_view

  MEVIEW ME_5524D2E200C4_view
   MELINK Original WL 'ME_5524D2E200C4' '54F9AF550087.ms.model.script' ; // DoLongProcessNotify
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_5524D2E200C4_view

  MEVIEW ME_552514C803BB_view
   MELINK Original WL 'ME_552514C803BB' '54F9AF550087.ms.model.script' ; // DoProgressNotify
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_552514C803BB_view

  MELIST Views
   Seq: ( ME_551938260196_view // Create
   ME_551938550022_view // Make
   ME_5524D2E200C4_view // DoLongProcessNotify
   ME_552514C803BB_view // DoProgressNotify
   )
  ; // Views
 ENDMEDIAGRAM // ME_5519351D01BE_main

 MELIST Diagrams
  Seq: ( ME_5519351D01BE_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_5519351D01BE_diagrams
