// TdaProgressSubscriberList 552514FD0144 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_552514FD0144_diagrams

 MEDIAGRAM ME_552514FD0144_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_552514FD0144' ; // TdaProgressSubscriberList

  MEVIEW ME_5525151202E7_view
   MELINK Original WL 'ME_5525151202E7' '552514FD0144.ms.model.script' ; // ItemType
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5525151202E7_view

  MELIST Views
   Seq: ( ME_5525151202E7_view // ItemType
   )
  ; // Views
 ENDMEDIAGRAM // ME_552514FD0144_main

 MELIST Diagrams
  Seq: ( ME_552514FD0144_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_552514FD0144_diagrams
