// TtfwStringToEnumValue 553132CA032A SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_553132CA032A_diagrams

 MEDIAGRAM ME_553132CA032A_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_553132CA032A' ; // TtfwStringToEnumValue

  MEVIEW ME_55313331027C_view
   MELINK Original WL 'ME_55313331027C' '553132CA032A.ms.model.script' ; // Register
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_55313331027C_view

  MEVIEW ME_5531331902AE_view
   MELINK Original WL 'ME_5531331902AE' '553132CA032A.ms.model.script' ; // f_TypeInfo
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_5531331902AE_view

  MELIST Views
   Seq: ( ME_55313331027C_view // Register
   ME_5531331902AE_view // f_TypeInfo
   )
  ; // Views
 ENDMEDIAGRAM // ME_553132CA032A_main

 MELIST Diagrams
  Seq: ( ME_553132CA032A_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_553132CA032A_diagrams
