// TdaFieldDescriptionListPrim 5538E9AE0163 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_5538E9AE0163_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_5538E9AE0163' '552D07D0005E.ms.model.script' ; // TdaFieldDescriptionListPrim

 MEVIEW ME_5538ED590245_view
  MELINK Original WL 'ME_5538ED590245' '552D07D0005E.ms.model.script' ; // l3Items_NeedsBeforeFreeItem
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_5538ED590245_view

ENDMEDIAGRAM // ME_5538E9AE0163_main
