// TvtCalendarForm 554CBF5C01D8 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_554CBF5C01D8_diagrams

 MEDIAGRAM ME_554CBF5C01D8_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_554CBF5C01D8' '4AA8AB7B038F.ms.model.script' ; // TvtCalendarForm

  MEVIEW ME_554CC0890053_view
   MELINK Original WL 'ME_554CC0890053' '4AA8AB7B038F.ms.model.script' ; // f_Calendar
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_554CC0890053_view

  MEVIEW ME_554CC0BC01D9_view
   MELINK Original WL 'ME_554CC0BC01D9' '4AA8AB7B038F.ms.model.script' ; // f_DateFormat
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_554CC0BC01D9_view

  MEVIEW ME_554CC0D002D0_view
   MELINK Original WL 'ME_554CC0D002D0' '4AA8AB7B038F.ms.model.script' ; // DateText
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_554CC0D002D0_view

  MELIST Views
   Seq: ( ME_554CC0890053_view // f_Calendar
   ME_554CC0BC01D9_view // f_DateFormat
   ME_554CC0D002D0_view // DateText
   )
  ; // Views
 ENDMEDIAGRAM // ME_554CBF5C01D8_main

 MELIST Diagrams
  Seq: ( ME_554CBF5C01D8_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_554CBF5C01D8_diagrams
