// TkwSourcePointWord 556427250160 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_556427250160_diagrams

 MEDIAGRAM ME_556427250160_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_556427250160' ; // TkwSourcePointWord

  MEVIEW ME_556427DD0163_view
   MELINK Original WL 'ME_556427DD0163' '556427250160.ms.model.script' ; // Create
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_556427DD0163_view

  MEVIEW ME_556317770068_view
   MELINK Original WL 'ME_556317770068' '556427250160.ms.model.script' ; // f_SourceFileName
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_556317770068_view

  MEVIEW ME_556317C6033F_view
   MELINK Original WL 'ME_556317C6033F' '556427250160.ms.model.script' ; // f_SourceLine
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_556317C6033F_view

  MELIST Views
   Seq: ( ME_556427DD0163_view // Create
   ME_556317770068_view // f_SourceFileName
   ME_556317C6033F_view // f_SourceLine
   )
  ; // Views
 ENDMEDIAGRAM // ME_556427250160_main

 MELIST Diagrams
  Seq: ( ME_556427250160_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_556427250160_diagrams
