// vcmPopupControlWindowService 5587AAF10290 UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_5587AAF10290_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_5587AAF10290' '533D53FF00C2.ms.model.script' ; // vcmPopupControlWindowService

 MEVIEW ME_5587AB210223_view
  MELINK Original WL 'ME_5587AB210223' '533D53FF00C2.ms.model.script' ; // TvcmPopupControlWindowService
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_5587AB210223_view

ENDMEDIAGRAM // ME_5587AAF10290_main
