// ObjectFromLink 559E9DF3002D Interface Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_559E9DF3002D_diagrams

 MEDIAGRAM ME_559E9DF3002D_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_559E9DF3002D' '4570511E038A.ms.model.script' ; // ObjectFromLink

  MEVIEW ME_559EA0D2028B_view
   MELINK Original WL 'ME_559EA0D2028B' '4570511E038A.ms.model.script' ; // get_object
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_559EA0D2028B_view

  MEVIEW ME_559EA0DE038A_view
   MELINK Original WL 'ME_559EA0DE038A' '4570511E038A.ms.model.script' ; // get_object_type
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_559EA0DE038A_view

  MEVIEW ME_559EA10A018E_view
   MELINK Original WL 'ME_559EA10A018E' '4570511E038A.ms.model.script' ; // make
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_559EA10A018E_view

  MEVIEW ME_559EA12200C9_view
   MELINK Original WL 'ME_559EA12200C9' '4570511E038A.ms.model.script' ; // 
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_559EA12200C9_view

  MELIST Views
   Seq: ( ME_559EA0D2028B_view // get_object
   ME_559EA0DE038A_view // get_object_type
   ME_559EA10A018E_view // make
   ME_559EA12200C9_view )
  ; // Views
 ENDMEDIAGRAM // ME_559E9DF3002D_main

 MELIST Diagrams
  Seq: ( ME_559E9DF3002D_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_559E9DF3002D_diagrams
