// tfwCodeCompiler 55A4E9940396 Impurity Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_55A4E9940396_diagrams

 MEDIAGRAM ME_55A4E9940396_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_55A4E9940396' '54F079B5035C.ms.model.script' ; // tfwCodeCompiler

  MEVIEW ME_55A4EA4402A7_view
   MELINK Original WL 'ME_55A4EA4402A7' '54F079B5035C.ms.model.script' ; // RunCode
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_55A4EA4402A7_view

  MEVIEW ME_52D55DF500C4_view
   MELINK Original WL 'ME_52D55DF500C4' '54F079B5035C.ms.model.script' ; // Code
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_52D55DF500C4_view

  MELIST Views
   Seq: ( ME_55A4EA4402A7_view // RunCode
   ME_52D55DF500C4_view // Code
   )
  ; // Views
 ENDMEDIAGRAM // ME_55A4E9940396_main

 MELIST Diagrams
  Seq: ( ME_55A4E9940396_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_55A4E9940396_diagrams
