// ClassLikeMapping 55CCADD2013D Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_55CCAE000335
%%Inner ME_5619169603BE
%%Inner ME_561BAC4B0005

ME ME_55CCADD2013D
 MEPROP UID '55CCADD2013D'
 MEPROP Name 'ClassLikeMapping'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Unit ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_54CF97B10370' // ScriptEngine$Core
 ;
 MELIST Children
   Seq: ( WL? 'ME_55CCAE000335' // TtfwClassLike
 WL? 'ME_5619169603BE' // TtfwPropertyLike
 WL? 'ME_561BAC4B0005' // TtfwGlobalKeyWord
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_4767743E00E5' // TypInfo
 WL? 'ME_4DAF19F600C5' // tfwScriptingInterfaces
 WL? 'ME_4F3E3F5F0160' // PrimitiveWords
 WL? 'ME_54F079B5035C' // CompiledWords
 WL? 'ME_54F07F0302C2' // WordsList
 WL? 'ME_55BF29CB003B' // TypeInfoCache
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames

ENDME // ME_55CCADD2013D ClassLikeMapping
