// TddDoc2DocLinkRecList 55DF01D8011D SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_55DF01D8011D_diagrams

 MEDIAGRAM ME_55DF01D8011D_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_55DF01D8011D' '55DC6B0D020D.ms.model.script' ; // TddDoc2DocLinkRecList

  MEVIEW ME_55DF01EC01A9_view
   MELINK Original WL 'ME_55DF01EC01A9' '55DC6B0D020D.ms.model.script' ; // ItemType
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_55DF01EC01A9_view

  MELIST Views
   Seq: ( ME_55DF01EC01A9_view // ItemType
   )
  ; // Views
 ENDMEDIAGRAM // ME_55DF01D8011D_main

 MELIST Diagrams
  Seq: ( ME_55DF01D8011D_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_55DF01D8011D_diagrams
