// ddPipeOutInterfaces 5603ED3D011B Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_5603ED3D011B_diagrams

 MEDIAGRAM ME_5603ED3D011B_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_5603ED3D011B' '5603ED3D011B.ms.model.script' ; // ddPipeOutInterfaces

  MEVIEW ME_5603EDF40264_view
   MELINK Original WL 'ME_5603EDF40264' '5603ED3D011B.ms.model.script' ; // TddExportDocPart
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5603EDF40264_view

  MEVIEW ME_5603EF2E01F9_view
   MELINK Original WL 'ME_5603EF2E01F9' '5603ED3D011B.ms.model.script' ; // IddExportFilerDispatcherElem
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_5603EF2E01F9_view

  MEVIEW ME_560A366C00E1_view
   MELINK Original WL 'ME_560A366C00E1' '5603ED3D011B.ms.model.script' ; // TddFilerDispatcherMapKeyRecord
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_560A366C00E1_view

  MEVIEW ME_560A4D4F01AE_view
   MELINK Original WL 'ME_560A4D4F01AE' '5603ED3D011B.ms.model.script' ; // TddExportDivideBy
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_560A4D4F01AE_view

  MEVIEW ME_560A4DCA0199_view
   MELINK Original WL 'ME_560A4DCA0199' '5603ED3D011B.ms.model.script' ; // TddExportDivideBySet
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_560A4DCA0199_view

  MEVIEW ME_560BB87D0082_view
   MELINK Original WL 'ME_560BB87D0082' '5603ED3D011B.ms.model.script' ; // TddExportFileMaskPatternType
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_560BB87D0082_view

  MEVIEW ME_56419FA802B2_view
   MELINK Original WL 'ME_56419FA802B2' '5603ED3D011B.ms.model.script' ; // TddReportEmptyEvent
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_56419FA802B2_view

  MEVIEW ME_564C602B0373_view
   MELINK Original WL 'ME_564C602B0373' '5603ED3D011B.ms.model.script' ; // IddAnnoKindSortItem
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_564C602B0373_view

  MEVIEW ME_560BADDA015F_view
   MELINK Original WL 'ME_560BADDA015F' '5603ED3D011B.ms.model.script' ; // cExportFileMaskPatterns
   MEPROP X 200
   MEPROP Y 180
  ENDMEVIEW // ME_560BADDA015F_view

  MEVIEW ME_56126374035D_view
   MELINK Original WL 'ME_56126374035D' '5603ED3D011B.ms.model.script' ; // cDefaultFileMask
   MEPROP X 360
   MEPROP Y 180
  ENDMEVIEW // ME_56126374035D_view

  MEVIEW ME_561E0B7603E7_view
   MELINK Original WL 'ME_561E0B7603E7' '5603ED3D011B.ms.model.script' ; // Сообщения
   MEPROP X 520
   MEPROP Y 180
  ENDMEVIEW // ME_561E0B7603E7_view

  MELIST Views
   Seq: ( ME_5603EDF40264_view // TddExportDocPart
   ME_5603EF2E01F9_view // IddExportFilerDispatcherElem
   ME_560A366C00E1_view // TddFilerDispatcherMapKeyRecord
   ME_560A4D4F01AE_view // TddExportDivideBy
   ME_560A4DCA0199_view // TddExportDivideBySet
   ME_560BB87D0082_view // TddExportFileMaskPatternType
   ME_56419FA802B2_view // TddReportEmptyEvent
   ME_564C602B0373_view // IddAnnoKindSortItem
   ME_560BADDA015F_view // cExportFileMaskPatterns
   ME_56126374035D_view // cDefaultFileMask
   ME_561E0B7603E7_view // Сообщения
   )
  ; // Views
 ENDMEDIAGRAM // ME_5603ED3D011B_main

 MELIST Diagrams
  Seq: ( ME_5603ED3D011B_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_5603ED3D011B_diagrams
