// TddFileMaskArray 5604052B03E1 Vector Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_5604052B03E1_diagrams

 MEDIAGRAM ME_5604052B03E1_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_5604052B03E1' '50598FD9019C.ms.model.script' ; // TddFileMaskArray

  MEVIEW ME_5604054C0338_view
   MELINK Original WL 'ME_5604054C0338' '50598FD9019C.ms.model.script' ; // 
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5604054C0338_view

  MELIST Views
   Seq: ( ME_5604054C0338_view )
  ; // Views
 ENDMEDIAGRAM // ME_5604052B03E1_main

 MELIST Diagrams
  Seq: ( ME_5604052B03E1_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_5604052B03E1_diagrams
