// TddExportFilerDispatcherElem 560A5BC502D5 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_560A5BC502D5_diagrams

 MEDIAGRAM ME_560A5BC502D5_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_560A5BC502D5' '50598FD9019C.ms.model.script' ; // TddExportFilerDispatcherElem

  MEVIEW ME_560A5C2D0282_view
   MELINK Original WL 'ME_560A5C2D0282' '50598FD9019C.ms.model.script' ; // Create
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_560A5C2D0282_view

  MEVIEW ME_560A5D31009D_view
   MELINK Original WL 'ME_560A5D31009D' '50598FD9019C.ms.model.script' ; // Make
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_560A5D31009D_view

  MELIST Views
   Seq: ( ME_560A5C2D0282_view // Create
   ME_560A5D31009D_view // Make
   )
  ; // Views
 ENDMEDIAGRAM // ME_560A5BC502D5_main

 MELIST Diagrams
  Seq: ( ME_560A5BC502D5_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_560A5BC502D5_diagrams
