// TtfwWordInfoArray 56191601034C Vector Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_56191601034C_diagrams

 MEDIAGRAM ME_56191601034C_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_56191601034C' '4DAF19F600C5.ms.model.script' ; // TtfwWordInfoArray

  MEVIEW ME_5619160E020E_view
   MELINK Original WL 'ME_5619160E020E' '4DAF19F600C5.ms.model.script' ; // 
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5619160E020E_view

  MELIST Views
   Seq: ( ME_5619160E020E_view )
  ; // Views
 ENDMEDIAGRAM // ME_56191601034C_main

 MELIST Diagrams
  Seq: ( ME_56191601034C_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_56191601034C_diagrams
