// InsBaseSearchClassesListener 562626470198 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_562626470198_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_562626470198' '4A9F98B901A5.ms.model.script' ; // InsBaseSearchClassesListener

 MEVIEW ME_5626267C01CF_view
  MELINK Original WL 'ME_5626267C01CF' '4A9F98B901A5.ms.model.script' ; // NotifyClassesChanged
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_5626267C01CF_view

ENDMEDIAGRAM // ME_562626470198_main
