// TpgCommandExecutor 5694BA3500C4 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_5694BA3500C4_diagrams

 MEDIAGRAM ME_5694BA3500C4_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_5694BA3500C4' ; // TpgCommandExecutor

  MEVIEW ME_5694BA880236_view
   MELINK Original WL 'ME_5694BA880236' '5694BA3500C4.ms.model.script' ; // Create
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5694BA880236_view

  MEVIEW ME_5694BA4A0323_view
   MELINK Original WL 'ME_5694BA4A0323' '5694BA3500C4.ms.model.script' ; // Execute
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_5694BA4A0323_view

  MEVIEW ME_5694BA79022F_view
   MELINK Original WL 'ME_5694BA79022F' '5694BA3500C4.ms.model.script' ; // f_Connection
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_5694BA79022F_view

  MELIST Views
   Seq: ( ME_5694BA880236_view // Create
   ME_5694BA4A0323_view // Execute
   ME_5694BA79022F_view // f_Connection
   )
  ; // Views
 ENDMEDIAGRAM // ME_5694BA3500C4_main

 MELIST Diagrams
  Seq: ( ME_5694BA3500C4_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_5694BA3500C4_diagrams
