// MainMenuSection 56FE518A027D Interface Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_56FE518A027D_diagrams

 MEDIAGRAM ME_56FE518A027D_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_56FE518A027D' '4DD24BD40021.ms.model.script' ; // MainMenuSection

  MEVIEW ME_56FE51B601CF_view
   MELINK Original WL 'ME_56FE51B601CF' '4DD24BD40021.ms.model.script' ; // make
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_56FE51B601CF_view

  MEVIEW ME_56FE579901A9_view
   MELINK Original WL 'ME_56FE579901A9' '4DD24BD40021.ms.model.script' ; // get_items
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_56FE579901A9_view

  MEVIEW ME_570D16D600A2_view
   MELINK Original WL 'ME_570D16D600A2' '4DD24BD40021.ms.model.script' ; // get_news_section_index
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_570D16D600A2_view

  MEVIEW ME_571F72D303BC_view
   MELINK Original WL 'ME_571F72D303BC' '4DD24BD40021.ms.model.script' ; // get_banner
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_571F72D303BC_view

  MELIST Views
   Seq: ( ME_56FE51B601CF_view // make
   ME_56FE579901A9_view // get_items
   ME_570D16D600A2_view // get_news_section_index
   ME_571F72D303BC_view // get_banner
   )
  ; // Views
 ENDMEDIAGRAM // ME_56FE518A027D_main

 MELIST Diagrams
  Seq: ( ME_56FE518A027D_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_56FE518A027D_diagrams
