// TasksListHelper 57022BAA02E1 Facet Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_57022BAA02E1_diagrams

 MEDIAGRAM ME_57022BAA02E1_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_57022BAA02E1' '52F8C298005C.ms.model.script' ; // TasksListHelper

  MEVIEW ME_570230C7015F_view
   MELINK Original WL 'ME_570230C7015F' '52F8C298005C.ms.model.script' ; // Add
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_570230C7015F_view

  MEVIEW ME_570230E803CB_view
   MELINK Original WL 'ME_570230E803CB' '52F8C298005C.ms.model.script' ; // MakeTask
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_570230E803CB_view

  MELIST Views
   Seq: ( ME_570230C7015F_view // Add
   ME_570230E803CB_view // MakeTask
   )
  ; // Views
 ENDMEDIAGRAM // ME_57022BAA02E1_main

 MELIST Diagrams
  Seq: ( ME_57022BAA02E1_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_57022BAA02E1_diagrams
