// daSelectFieldIterator 5756AC490332 PureMixIn Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_5756AC490332_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_5756AC490332' '5432518A0316.ms.model.script' ; // daSelectFieldIterator

 MEVIEW ME_5756AC9B0213_view
  MELINK Original WL 'ME_5756AC9B0213' '5432518A0316.ms.model.script' ; // IterateTables
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_5756AC9B0213_view

ENDMEDIAGRAM // ME_5756AC490332_main
