// TcaArchiUser 57566B200124 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_57566B200124_diagrams

 MEDIAGRAM ME_57566B200124_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_57566B200124' '56A86AF40350.ms.model.script' ; // TcaArchiUser

  MEVIEW ME_57566B3E0317_view
   MELINK Original WL 'ME_57566B3E0317' '56A86AF40350.ms.model.script' ; // Create
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_57566B3E0317_view

  MEVIEW ME_57566B6802A7_view
   MELINK Original WL 'ME_57566B6802A7' '56A86AF40350.ms.model.script' ; // Make
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_57566B6802A7_view

  MEVIEW ME_57359E8903CF_view
   MELINK Original WL 'ME_57359E8903CF' '56A86AF40350.ms.model.script' ; // IsUsersEqual
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_57359E8903CF_view

  MELIST Views
   Seq: ( ME_57566B3E0317_view // Create
   ME_57566B6802A7_view // Make
   ME_57359E8903CF_view // IsUsersEqual
   )
  ; // Views
 ENDMEDIAGRAM // ME_57566B200124_main

 MELIST Diagrams
  Seq: ( ME_57566B200124_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_57566B200124_diagrams
