// TpgConnectionListenerList 5769249C0015 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_5769249C0015_diagrams

 MEDIAGRAM ME_5769249C0015_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_5769249C0015' '55D6CF3B014B.ms.model.script' ; // TpgConnectionListenerList

  MEVIEW ME_576924B2035C_view
   MELINK Original WL 'ME_576924B2035C' '55D6CF3B014B.ms.model.script' ; // ItemType
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_576924B2035C_view

  MELIST Views
   Seq: ( ME_576924B2035C_view // ItemType
   )
  ; // Views
 ENDMEDIAGRAM // ME_5769249C0015_main

 MELIST Diagrams
  Seq: ( ME_5769249C0015_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_5769249C0015_diagrams
