// TfstList 57691A62014A SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

ME ME_57691A62014A
 MEPROP UID '57691A62014A'
 MEPROP Name 'TfstList'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_497DDB0A0168' // List
 ;
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP "finished" False
 UP extprop:pas:UnitName 'fstList'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'fstList'
 UP intf.pas:Path 'garant6x\implementation\Garant\GbaNemesis\View\List\NOT_FINISHED_fstList.pas'

ENDME // ME_57691A62014A TfstList
