// F1Services 5795D66F0385 VCMContracts Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_5795D66F0385_diagrams

 MEDIAGRAM ME_5795D66F0385_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_5795D66F0385' '5795D66F0385.ms.model.script' ; // F1Services

  MEVIEW ME_5795D6DC01F8_view
   MELINK Original WL 'ME_5795D6DC01F8' '5795D66F0385.ms.model.script' ; // TChatService
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_5795D6DC01F8_view

  MEVIEW ME_57960D70013A_view
   MELINK Original WL 'ME_57960D70013A' '5795D66F0385.ms.model.script' ; // TDictionService
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_57960D70013A_view

  MEVIEW ME_579623590356_view
   MELINK Original WL 'ME_579623590356' '5795D66F0385.ms.model.script' ; // TInpharmService
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_579623590356_view

  MEVIEW ME_57971A530162_view
   MELINK Original WL 'ME_57971A530162' '5795D66F0385.ms.model.script' ; // TInternetAgentService
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_57971A530162_view

  MEVIEW ME_57971D8D0315_view
   MELINK Original WL 'ME_57971D8D0315' '5795D66F0385.ms.model.script' ; // TDayTipsService
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_57971D8D0315_view

  MEVIEW ME_57971EB50122_view
   MELINK Original WL 'ME_57971EB50122' '5795D66F0385.ms.model.script' ; // TDocumentListFromFileService
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_57971EB50122_view

  MEVIEW ME_579735A70273_view
   MELINK Original WL 'ME_579735A70273' '5795D66F0385.ms.model.script' ; // TMainMenuService
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_579735A70273_view

  MEVIEW ME_57973D75032B_view
   MELINK Original WL 'ME_57973D75032B' '5795D66F0385.ms.model.script' ; // TBaseSearchService
   MEPROP X 40
   MEPROP Y 180
  ENDMEVIEW // ME_57973D75032B_view

  MEVIEW ME_57975E0B00ED_view
   MELINK Original WL 'ME_57975E0B00ED' '5795D66F0385.ms.model.script' ; // TFiltersService
   MEPROP X 200
   MEPROP Y 180
  ENDMEVIEW // ME_57975E0B00ED_view

  MEVIEW ME_4AC0ABED023F_view
   MELINK Original WL 'ME_4AC0ABED023F' '5795D66F0385.ms.model.script' ; // InsFormCoordinates
   MEPROP X 360
   MEPROP Y 180
  ENDMEVIEW // ME_4AC0ABED023F_view

  MEVIEW ME_579764A6025C_view
   MELINK Original WL 'ME_579764A6025C' '5795D66F0385.ms.model.script' ; // TFoldersService
   MEPROP X 520
   MEPROP Y 180
  ENDMEVIEW // ME_579764A6025C_view

  MEVIEW ME_579F2C6901E2_view
   MELINK Original WL 'ME_579F2C6901E2' '5795D66F0385.ms.model.script' ; // TRubricatorService
   MEPROP X 680
   MEPROP Y 180
  ENDMEVIEW // ME_579F2C6901E2_view

  MEVIEW ME_579F4A7103CF_view
   MELINK Original WL 'ME_579F4A7103CF' '5795D66F0385.ms.model.script' ; // TSearchService
   MEPROP X 840
   MEPROP Y 180
  ENDMEVIEW // ME_579F4A7103CF_view

  MEVIEW ME_579F67B3020C_view
   MELINK Original WL 'ME_579F67B3020C' '5795D66F0385.ms.model.script' ; // TSettingsService
   MEPROP X 1000
   MEPROP Y 180
  ENDMEVIEW // ME_579F67B3020C_view

  MEVIEW ME_579F749600D6_view
   MELINK Original WL 'ME_579F749600D6' '5795D66F0385.ms.model.script' ; // TWorkJournalService
   MEPROP X 40
   MEPROP Y 320
  ENDMEVIEW // ME_579F749600D6_view

  MEVIEW ME_57A0977900D6_view
   MELINK Original WL 'ME_57A0977900D6' '5795D66F0385.ms.model.script' ; // TDocumentService
   MEPROP X 200
   MEPROP Y 320
  ENDMEVIEW // ME_57A0977900D6_view

  MEVIEW ME_57A1AEAB014E_view
   MELINK Original WL 'ME_57A1AEAB014E' '5795D66F0385.ms.model.script' ; // TMonitoringsService
   MEPROP X 360
   MEPROP Y 320
  ENDMEVIEW // ME_57A1AEAB014E_view

  MEVIEW ME_57A1C81101B6_view
   MELINK Original WL 'ME_57A1C81101B6' '5795D66F0385.ms.model.script' ; // TEditionsService
   MEPROP X 520
   MEPROP Y 320
  ENDMEVIEW // ME_57A1C81101B6_view

  MEVIEW ME_57A1D61C02F2_view
   MELINK Original WL 'ME_57A1D61C02F2' '5795D66F0385.ms.model.script' ; // TListService
   MEPROP X 680
   MEPROP Y 320
  ENDMEVIEW // ME_57A1D61C02F2_view

  MEVIEW ME_57A1F23D03CF_view
   MELINK Original WL 'ME_57A1F23D03CF' '5795D66F0385.ms.model.script' ; // TConsultationService
   MEPROP X 840
   MEPROP Y 320
  ENDMEVIEW // ME_57A1F23D03CF_view

  MEVIEW ME_57A200FC0211_view
   MELINK Original WL 'ME_57A200FC0211' '5795D66F0385.ms.model.script' ; // TUnderControlService
   MEPROP X 1000
   MEPROP Y 320
  ENDMEVIEW // ME_57A200FC0211_view

  MEVIEW ME_57A206CD032D_view
   MELINK Original WL 'ME_57A206CD032D' '5795D66F0385.ms.model.script' ; // TChangesBetweenEditionsService
   MEPROP X 40
   MEPROP Y 460
  ENDMEVIEW // ME_57A206CD032D_view

  MEVIEW ME_57A2DAC3021C_view
   MELINK Original WL 'ME_57A2DAC3021C' '5795D66F0385.ms.model.script' ; // TAACService
   MEPROP X 200
   MEPROP Y 460
  ENDMEVIEW // ME_57A2DAC3021C_view

  MEVIEW ME_24C3925F4EF1_view
   MELINK Original WL 'ME_24C3925F4EF1' '5795D66F0385.ms.model.script' ; // TstTMainMenuServiceChangeableMainMenuTypeItem
   MEPROP X 360
   MEPROP Y 460
  ENDMEVIEW // ME_24C3925F4EF1_view

  MEVIEW ME_4A3079312AF4_view
   MELINK Original WL 'ME_4A3079312AF4' '5795D66F0385.ms.model.script' ; // TstTDocumentServiceShowChangesInfoItem
   MEPROP X 520
   MEPROP Y 460
  ENDMEVIEW // ME_4A3079312AF4_view

  MEVIEWLINK ME_6F08D9B9BD8B_viewlink
   MELINK Original WL 'ME_6F08D9B9BD8B' '5795D66F0385.ms.model.script' ;
   MELINK From ME_579735A70273_view ;
   MELINK To ME_24C3925F4EF1_view ;
  ENDMEVIEWLINK // ME_6F08D9B9BD8B_viewlink

  MEVIEWLINK ME_4A39A78C3661_viewlink
   MELINK Original WL 'ME_4A39A78C3661' '5795D66F0385.ms.model.script' ;
   MELINK From ME_57A0977900D6_view ;
   MELINK To ME_4A3079312AF4_view ;
  ENDMEVIEWLINK // ME_4A39A78C3661_viewlink

  MEVIEWLINK ME_9ADA08A6B22A_viewlink
   MELINK Original WL 'ME_9ADA08A6B22A' '5795D66F0385.ms.model.script' ;
   MELINK From ME_24C3925F4EF1_view ;
   MELINK To ME_579735A70273_view ;
  ENDMEVIEWLINK // ME_9ADA08A6B22A_viewlink

  MEVIEWLINK ME_4F824EF30E04_viewlink
   MELINK Original WL 'ME_4F824EF30E04' '5795D66F0385.ms.model.script' ;
   MELINK From ME_4A3079312AF4_view ;
   MELINK To ME_57A0977900D6_view ;
  ENDMEVIEWLINK // ME_4F824EF30E04_viewlink

  MELIST Views
   Seq: ( ME_5795D6DC01F8_view // TChatService
   ME_57960D70013A_view // TDictionService
   ME_579623590356_view // TInpharmService
   ME_57971A530162_view // TInternetAgentService
   ME_57971D8D0315_view // TDayTipsService
   ME_57971EB50122_view // TDocumentListFromFileService
   ME_579735A70273_view // TMainMenuService
   ME_57973D75032B_view // TBaseSearchService
   ME_57975E0B00ED_view // TFiltersService
   ME_4AC0ABED023F_view // InsFormCoordinates
   ME_579764A6025C_view // TFoldersService
   ME_579F2C6901E2_view // TRubricatorService
   ME_579F4A7103CF_view // TSearchService
   ME_579F67B3020C_view // TSettingsService
   ME_579F749600D6_view // TWorkJournalService
   ME_57A0977900D6_view // TDocumentService
   ME_57A1AEAB014E_view // TMonitoringsService
   ME_57A1C81101B6_view // TEditionsService
   ME_57A1D61C02F2_view // TListService
   ME_57A1F23D03CF_view // TConsultationService
   ME_57A200FC0211_view // TUnderControlService
   ME_57A206CD032D_view // TChangesBetweenEditionsService
   ME_57A2DAC3021C_view // TAACService
   ME_24C3925F4EF1_view // TstTMainMenuServiceChangeableMainMenuTypeItem
   ME_4A3079312AF4_view // TstTDocumentServiceShowChangesInfoItem
   ME_6F08D9B9BD8B_viewlink // TMainMenuService -> TstTMainMenuServiceChangeableMainMenuTypeItem
   ME_4A39A78C3661_viewlink // TDocumentService -> TstTDocumentServiceShowChangesInfoItem
   ME_9ADA08A6B22A_viewlink // TstTMainMenuServiceChangeableMainMenuTypeItem -> TMainMenuService
   ME_4F824EF30E04_viewlink // TstTDocumentServiceShowChangesInfoItem -> TDocumentService
   )
  ; // Views
 ENDMEDIAGRAM // ME_5795D66F0385_main

 MELIST Diagrams
  Seq: ( ME_5795D66F0385_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_5795D66F0385_diagrams
