// TControlledObjectService 57A2146F017F Service Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_57A2146F017F_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_57A2146F017F' '579F7F680321.ms.model.script' ; // TControlledObjectService

 MEVIEW ME_B0C3E322EA56_view
  MELINK Original WL 'ME_B0C3E322EA56' '579F7F680321.ms.model.script' ; // MControlledObjectService
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_B0C3E322EA56_view

 MEVIEW ME_57A2148D0045_view
  MELINK Original WL 'ME_57A2148D0045' '579F7F680321.ms.model.script' ; // AddControlledObject
  MEPROP X 120
  MEPROP Y 10
 ENDMEVIEW // ME_57A2148D0045_view

 MEVIEW ME_57A2149F0242_view
  MELINK Original WL 'ME_57A2149F0242' '579F7F680321.ms.model.script' ; // DeleteControlledObject
  MEPROP X 230
  MEPROP Y 10
 ENDMEVIEW // ME_57A2149F0242_view

ENDMEDIAGRAM // ME_57A2146F017F_main
