// TpgLockedTablesList 57A835C502DB SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_57A835C502DB_diagrams

 MEDIAGRAM ME_57A835C502DB_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_57A835C502DB' ; // TpgLockedTablesList

  MEVIEW ME_57A835FC0228_view
   MELINK Original WL 'ME_57A835FC0228' '57A835C502DB.ms.model.script' ; // ItemType
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_57A835FC0228_view

  MELIST Views
   Seq: ( ME_57A835FC0228_view // ItemType
   )
  ; // Views
 ENDMEDIAGRAM // ME_57A835C502DB_main

 MELIST Diagrams
  Seq: ( ME_57A835C502DB_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_57A835C502DB_diagrams
