// TmsmModelElementMethodValue 57B2E68103BA StaticObject Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_57B2E68103BA_diagrams

 MEDIAGRAM ME_57B2E68103BA_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_57B2E68103BA' '57AB4243034B.ms.model.script' ; // TmsmModelElementMethodValue

  MEVIEW ME_57B2E73703A2_view
   MELINK Original WL 'ME_57B2E73703A2' '57AB4243034B.ms.model.script' ; // Compare
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_57B2E73703A2_view

  MEVIEW ME_57B2E78200E3_view
   MELINK Original WL 'ME_57B2E78200E3' '57AB4243034B.ms.model.script' ; // C
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_57B2E78200E3_view

  MELIST Views
   Seq: ( ME_57B2E73703A2_view // Compare
   ME_57B2E78200E3_view // C
   )
  ; // Views
 ENDMEDIAGRAM // ME_57B2E68103BA_main

 MELIST Diagrams
  Seq: ( ME_57B2E68103BA_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_57B2E68103BA_diagrams
