// Downloader 57BC0538037B Unit Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_57BC0538037B_diagrams

 MEDIAGRAM ME_57BC0538037B_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_57BC0538037B' '57BC0538037B.ms.model.script' ; // Downloader

  MEVIEW ME_57BC05FD03A1_view
   MELINK Original WL 'ME_57BC05FD03A1' '57BC0538037B.ms.model.script' ; // TnsDownloaderGUIService
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_57BC05FD03A1_view

  MEVIEW ME_57BC062801FF_view
   MELINK Original WL 'ME_57BC062801FF' '57BC0538037B.ms.model.script' ; // nsOpenOrSaveInternetFileDialog
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_57BC062801FF_view

  MEVIEW ME_57BC06F603E1_view
   MELINK Original WL 'ME_57BC06F603E1' '57BC0538037B.ms.model.script' ; // nsDownloader
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_57BC06F603E1_view

  MEVIEW ME_57BD366C02FD_view
   MELINK Original WL 'ME_57BD366C02FD' '57BC0538037B.ms.model.script' ; // nsDownloaderInterfaces
   MEPROP X 520
   MEPROP Y 40
  ENDMEVIEW // ME_57BD366C02FD_view

  MEVIEW ME_57BD790600B0_view
   MELINK Original WL 'ME_57BD790600B0' '57BC0538037B.ms.model.script' ; // nsDownloaderRes
   MEPROP X 680
   MEPROP Y 40
  ENDMEVIEW // ME_57BD790600B0_view

  MEVIEW ME_57BFDE5C014C_view
   MELINK Original WL 'ME_57BFDE5C014C' '57BC0538037B.ms.model.script' ; // TnsDownloaderThread
   MEPROP X 840
   MEPROP Y 40
  ENDMEVIEW // ME_57BFDE5C014C_view

  MEVIEW ME_57BFDE7402F0_view
   MELINK Original WL 'ME_57BFDE7402F0' '57BC0538037B.ms.model.script' ; // TnsDownloaderThreadList
   MEPROP X 1000
   MEPROP Y 40
  ENDMEVIEW // ME_57BFDE7402F0_view

  MEVIEWLINK ME_57BC05FD03A1_ME_57BC062801FF_uses::Dependency
   MELINK Original WL 'ME_57BC063D0132' '57BC0538037B.ms.model.script' ;
   MELINK From ME_57BC05FD03A1_view ;
   MELINK To ME_57BC062801FF_view ;
  ENDMEVIEWLINK // ME_57BC05FD03A1_ME_57BC062801FF_uses::Dependency

  MEVIEWLINK ME_57BC062801FF_ME_57BD366C02FD_uses::Dependency
   MELINK Original WL 'ME_57BD7AD302C1' '57BC0538037B.ms.model.script' ;
   MELINK From ME_57BC062801FF_view ;
   MELINK To ME_57BD366C02FD_view ;
  ENDMEVIEWLINK // ME_57BC062801FF_ME_57BD366C02FD_uses::Dependency

  MEVIEWLINK ME_57BC06F603E1_ME_57BD790600B0_uses::Dependency
   MELINK Original WL 'ME_57BD7AAF001F' '57BC0538037B.ms.model.script' ;
   MELINK From ME_57BC06F603E1_view ;
   MELINK To ME_57BD790600B0_view ;
  ENDMEVIEWLINK // ME_57BC06F603E1_ME_57BD790600B0_uses::Dependency

  MEVIEWLINK ME_57BC06F603E1_ME_57BD366C02FD_uses::Dependency
   MELINK Original WL 'ME_57BD7AC700E8' '57BC0538037B.ms.model.script' ;
   MELINK From ME_57BC06F603E1_view ;
   MELINK To ME_57BD366C02FD_view ;
  ENDMEVIEWLINK // ME_57BC06F603E1_ME_57BD366C02FD_uses::Dependency

  MEVIEWLINK ME_57BC06F603E1_ME_57BC05FD03A1_uses::Dependency
   MELINK Original WL 'ME_57BD7AED03C0' '57BC0538037B.ms.model.script' ;
   MELINK From ME_57BC06F603E1_view ;
   MELINK To ME_57BC05FD03A1_view ;
  ENDMEVIEWLINK // ME_57BC06F603E1_ME_57BC05FD03A1_uses::Dependency

  MEVIEWLINK ME_57BC06F603E1_ME_57BFDE7402F0_uses::Dependency
   MELINK Original WL 'ME_57BFDF8E0074' '57BC0538037B.ms.model.script' ;
   MELINK From ME_57BC06F603E1_view ;
   MELINK To ME_57BFDE7402F0_view ;
  ENDMEVIEWLINK // ME_57BC06F603E1_ME_57BFDE7402F0_uses::Dependency

  MEVIEWLINK ME_57BC06F603E1_ME_57BFDE5C014C_uses::Dependency
   MELINK Original WL 'ME_57C008A3000B' '57BC0538037B.ms.model.script' ;
   MELINK From ME_57BC06F603E1_view ;
   MELINK To ME_57BFDE5C014C_view ;
  ENDMEVIEWLINK // ME_57BC06F603E1_ME_57BFDE5C014C_uses::Dependency

  MEVIEWLINK ME_57BFDE5C014C_ME_57BC06F603E1_uses::Dependency
   MELINK Original WL 'ME_57BFE7010374' '57BC0538037B.ms.model.script' ;
   MELINK From ME_57BFDE5C014C_view ;
   MELINK To ME_57BC06F603E1_view ;
  ENDMEVIEWLINK // ME_57BFDE5C014C_ME_57BC06F603E1_uses::Dependency

  MEVIEWLINK ME_57BFDF7102A8_viewlink
   MELINK Original WL 'ME_57BFDF7102A8' '57BC0538037B.ms.model.script' ;
   MELINK From ME_57BFDE7402F0_view ;
   MELINK To ME_57BFDE5C014C_view ;
  ENDMEVIEWLINK // ME_57BFDF7102A8_viewlink

  MELIST Views
   Seq: ( ME_57BC05FD03A1_view // TnsDownloaderGUIService
   ME_57BC062801FF_view // nsOpenOrSaveInternetFileDialog
   ME_57BC06F603E1_view // nsDownloader
   ME_57BD366C02FD_view // nsDownloaderInterfaces
   ME_57BD790600B0_view // nsDownloaderRes
   ME_57BFDE5C014C_view // TnsDownloaderThread
   ME_57BFDE7402F0_view // TnsDownloaderThreadList
   ME_57BC05FD03A1_ME_57BC062801FF_uses::Dependency // TnsDownloaderGUIService -> nsOpenOrSaveInternetFileDialog
   ME_57BC062801FF_ME_57BD366C02FD_uses::Dependency // nsOpenOrSaveInternetFileDialog -> nsDownloaderInterfaces
   ME_57BC06F603E1_ME_57BD790600B0_uses::Dependency // nsDownloader -> nsDownloaderRes
   ME_57BC06F603E1_ME_57BD366C02FD_uses::Dependency // nsDownloader -> nsDownloaderInterfaces
   ME_57BC06F603E1_ME_57BC05FD03A1_uses::Dependency // nsDownloader -> TnsDownloaderGUIService
   ME_57BC06F603E1_ME_57BFDE7402F0_uses::Dependency // nsDownloader -> TnsDownloaderThreadList
   ME_57BC06F603E1_ME_57BFDE5C014C_uses::Dependency // nsDownloader -> TnsDownloaderThread
   ME_57BFDE5C014C_ME_57BC06F603E1_uses::Dependency // TnsDownloaderThread -> nsDownloader
   ME_57BFDF7102A8_viewlink // TnsDownloaderThreadList -> TnsDownloaderThread
   )
  ; // Views
 ENDMEDIAGRAM // ME_57BC0538037B_main

 MELIST Diagrams
  Seq: ( ME_57BC0538037B_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_57BC0538037B_diagrams
