// msmListAndTreeInterfaces 57C99A680247 Interfaces Category

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_57C99A680247_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_57C99A680247' '57C99A680247.ms.model.script' ; // msmListAndTreeInterfaces

 MEVIEW ME_57B2B0C602DF_view
  MELINK Original WL 'ME_57B2B0C602DF' '57C99A680247.ms.model.script' ; // ActionElementEvent
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_57B2B0C602DF_view

 MEVIEW ME_57B31D1000FA_view
  MELINK Original WL 'ME_57B31D1000FA' '57C99A680247.ms.model.script' ; // CurrentElementChangedEvent
  MEPROP X 120
  MEPROP Y 10
 ENDMEVIEW // ME_57B31D1000FA_view

 MEVIEW ME_57ADBA39026E_view
  MELINK Original WL 'ME_57ADBA39026E' '57C99A680247.ms.model.script' ; // ListChangedEvent
  MEPROP X 230
  MEPROP Y 10
 ENDMEVIEW // ME_57ADBA39026E_view

ENDMEDIAGRAM // ME_57C99A680247_main
