// l3PointerUtils 57CE8E0B0357 UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_57CE8E0B0357_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_57CE8E0B0357' '4A6D65B9022A.ms.model.script' ; // l3PointerUtils

 MEVIEW ME_57CE8E2403E7_view
  MELINK Original WL 'ME_57CE8E2403E7' '4A6D65B9022A.ms.model.script' ; // l3ComparePointers
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_57CE8E2403E7_view

ENDMEDIAGRAM // ME_57CE8E0B0357_main
