// TmsmDrawingViewController 57D00B730178 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_57D00B730178_diagrams

 MEDIAGRAM ME_57D00B730178_main
  MEPROP Name 'main'
  MELINK Original WL? 'ME_57D00B730178' ; // TmsmDrawingViewController

  MEVIEW ME_57D00BA4017F_view
   MELINK Original WL 'ME_57D00BA4017F' '57D00B730178.ms.model.script' ; // OwnViewClass
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_57D00BA4017F_view

  MEVIEW ME_57D00BB50061_view
   MELINK Original WL 'ME_57D00BB50061' '57D00B730178.ms.model.script' ; // ConcreteModel
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_57D00BB50061_view

  MEVIEW ME_57D0129300C3_view
   MELINK Original WL 'ME_57D0129300C3' '57D00B730178.ms.model.script' ; // InitContext
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_57D0129300C3_view

  MELIST Views
   Seq: ( ME_57D00BA4017F_view // OwnViewClass
   ME_57D00BB50061_view // ConcreteModel
   ME_57D0129300C3_view // InitContext
   )
  ; // Views
 ENDMEDIAGRAM // ME_57D00B730178_main

 MELIST Diagrams
  Seq: ( ME_57D00B730178_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_57D00B730178_diagrams
