// TmsmChangedElementsPrim 57E103E402B8 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

FORWARD ME_57E103E402B8

ME ME_57E104DC0358
 MEPROP UID '57E104DC0358'
 MEPROP Name 'ItemType'
 MEPROP Class class_Attribute
 MELINK Stereotype st_impurity_value::Attribute ;
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_abstract
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_57E103E402B8 // TmsmChangedElementsPrim
 ;
 MELINK Target WL 'ME_4DAEED140007' '4DAF19F600C5.ms.model.script' // TtfwWord
 ;

ENDME // ME_57E104DC0358 ItemType

FORWARD ME_57E1046B03CD

FORWARD ME_57E104730351

ME ME_57E1047B023C
 MEPROP Name 'anItem'
 MEPROP Class class_Parameter
 MELINK Target WL 'ME_4DAEED140007' '4DAF19F600C5.ms.model.script' // TtfwWord
 ;

ENDME // ME_57E1047B023C anItem

ME ME_57E104730351
 MEPROP UID '57E104730351'
 MEPROP Name 'DoIt'
 MEPROP Class class_Operation
 MEPROP Visibility PrivateAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_57E1046B03CD // Add
 ;
 MELIST Parameters
   Seq: ( ME_57E1047B023C // anItem
 )
 ; // Parameters

ENDME // ME_57E104730351 DoIt

ME ME_57E1046B03CD
 MEPROP UID '57E1046B03CD'
 MEPROP Name 'Add'
 MEPROP Class class_Operation
 MELINK Stereotype st_method ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_57E103E402B8 // TmsmChangedElementsPrim
 ;
 MELIST Operations
   Seq: ( HWL ME_57E104730351 // DoIt
 )
 ; // Operations

ENDME // ME_57E1046B03CD Add

ME ME_57E105090060
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_57E103E402B8 // TmsmChangedElementsPrim
 ;
 MELINK Target WL? 'ME_57CE8E0B0357' // l3PointerUtils
 ;

ENDME // ME_57E105090060 

ME ME_57E10548027C
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_57E103E402B8 // TmsmChangedElementsPrim
 ;
 MELINK Target WL? 'ME_57AA00BD022E' // TmsmModelElementMethodCaller
 ;

ENDME // ME_57E10548027C 

MEREF ME_47B2C42A0163_ME_57E103E402B8_impl
 MELINK Original WL 'ME_47B2C42A0163' '47A74A5F0123.ms.model.script' // AssignItem
 ;
 MEPROP OpKind opkind_Implemented
 UP "ifdef" 'l3Items_NeedsAssignItem'
 UP "ifndef" 'l3Items_NoSort'
ENDMEREF // ME_47B2C42A0163_ME_57E103E402B8_impl AssignItem

MEREF ME_47B99D4503A2_ME_57E103E402B8_impl
 MELINK Original WL 'ME_47B99D4503A2' '47B45152003F.ms.model.script' // CompareExistingItems
 ;
 MEPROP OpKind opkind_Implemented
ENDMEREF // ME_47B99D4503A2_ME_57E103E402B8_impl CompareExistingItems

MEREF ME_47A042E100E2_ME_57E103E402B8_over
 MELINK Original WL 'ME_47A042E100E2' '47913F4E02E0.ms.model.script' // InitFields
 ;
 MEPROP OpKind opkind_Overridden
ENDMEREF // ME_47A042E100E2_ME_57E103E402B8_over InitFields

MEREF ME_47B99E920196_ME_57E103E402B8_G
 MELINK Original WL? 'ME_47B99E920196' // l3UncomparabeObjectRefList
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_47B99E920196_ME_57E103E402B8_G l3UncomparabeObjectRefList

MEREF ME_4A54DD4E036F_ME_57E103E402B8_G
 MELINK Original WL? 'ME_4A54DD4E036F' // Tl3ProtoDataContainer
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_4A54DD4E036F_ME_57E103E402B8_G Tl3ProtoDataContainer

MEREF ME_57C5572B036F_ME_57E103E402B8_R
 MELINK Original WL? 'ME_57C5572B036F' // seCriticalSectionHolder
 ;
 MEPROP OpKind opkind_ReferencedType
ENDMEREF // ME_57C5572B036F_ME_57E103E402B8_R seCriticalSectionHolder

%%ImplementedBy ME_57C5572B036F ME_57E103E402B8

%%InheritedBy ME_47B99E920196 ME_57E103E402B8
%%InheritedBy ME_4A54DD4E036F ME_57E103E402B8

ME ME_57E103E402B8
 MEPROP UID '57E103E402B8'
 MEPROP Name 'TmsmChangedElementsPrim'
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent WL? 'ME_57AB4243034B' // ScriptCalling
 ;
 MELIST Inherits
   Seq: ( HWL ME_47B99E920196_ME_57E103E402B8_G // l3UncomparabeObjectRefList
 HWL ME_4A54DD4E036F_ME_57E103E402B8_G // Tl3ProtoDataContainer
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_57C5572B036F_ME_57E103E402B8_R // seCriticalSectionHolder
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_57E104DC0358 // ItemType
 )
 ; // Attributes
 MELIST Operations
   Seq: ( HWL ME_57E1046B03CD // Add
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_47B2C42A0163_ME_57E103E402B8_impl // AssignItem
 ME_47B99D4503A2_ME_57E103E402B8_impl // CompareExistingItems
 )
 ; // Implemented
 MELIST Overridden
   Seq: ( ME_47A042E100E2_ME_57E103E402B8_over // InitFields
 )
 ; // Overridden
 MELIST Dependencies
   Seq: ( ME_57E105090060 // l3PointerUtils
 ME_57E10548027C // TmsmModelElementMethodCaller
 )
 ; // Dependencies
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' )
 ; // DiagramsNames
 UP extprop:pas:UnitName 'msmChangedElementsPrim'
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'msmChangedElementsPrim'
 UP intf.pas:Path 'common\components\gui\Garant\msm\msmChangedElementsPrim.pas'

ENDME // ME_57E103E402B8 TmsmChangedElementsPrim
