// TarRemoteMultiClearAttributesHelper 57EBA2190344 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_57EBA2190344_diagrams

 MEDIAGRAM ME_57EBA2190344_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_57EBA2190344' '57CFC13E033D.ms.model.script' ; // TarRemoteMultiClearAttributesHelper

  MEVIEW ME_57EBA29A024A_view
   MELINK Original WL 'ME_57EBA29A024A' '57CFC13E033D.ms.model.script' ; // Create
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_57EBA29A024A_view

  MEVIEW ME_57EBA2840183_view
   MELINK Original WL 'ME_57EBA2840183' '57CFC13E033D.ms.model.script' ; // f_Message
   MEPROP X 200
   MEPROP Y 40
  ENDMEVIEW // ME_57EBA2840183_view

  MEVIEW ME_57EBA2FE02B3_view
   MELINK Original WL 'ME_57EBA2FE02B3' '57CFC13E033D.ms.model.script' ; // f_Reply
   MEPROP X 360
   MEPROP Y 40
  ENDMEVIEW // ME_57EBA2FE02B3_view

  MELIST Views
   Seq: ( ME_57EBA29A024A_view // Create
   ME_57EBA2840183_view // f_Message
   ME_57EBA2FE02B3_view // f_Reply
   )
  ; // Views
 ENDMEDIAGRAM // ME_57EBA2190344_main

 MELIST Diagrams
  Seq: ( ME_57EBA2190344_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_57EBA2190344_diagrams
