// Shared Delphi MVC 57EE6E2A01A5 Project Category

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_57E533C703E3
%%Inner ME_57B1DAE6030C
%%Inner ME_57B4295D0399

ME ME_57EE6E2A01A5
 MEPROP UID '57EE6E2A01A5'
 MEPROP Name 'Shared Delphi MVC'
 MEPROP IsSubRoot true
 MEPROP Class class_Category
 MELINK Stereotype st_Project ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELIST Children
   Seq: ( WL? 'ME_57E533C703E3' // msm$Events
 WL? 'ME_57B1DAE6030C' // msm$MVC
 WL? 'ME_57B4295D0399' // msm$MVC$DefaultRealization
 )
 ; // Children
 MELIST Depends
   Seq: ( WL? 'ME_3DBFDB23006E' // Primitives
 WL? 'ME_4677DDBD0193' // Shared Delphi
 WL? 'ME_49B1511700CA' // Shared Delphi Core
 WL? 'ME_4ABCC25A0322' // Shared Delphi Low Level
 WL? 'ME_4E5BC50E02E1' // Shared Delphi Требования к низкоуровневым библиотекам
 WL? 'ME_562E251101C2' // Shared Delphi Rtl
 )
 ; // Depends
 MESTRINGLIST DiagramsNames
   Seq: ( 'Main' 'Uses' )
 ; // DiagramsNames
 UP "defines" 'msm.inc'
 UP "force usage" True
 UP "Full MDP" False
 UP "root path suffix" '/components'
 UP "space key" 'SHD'
 UP "space name" 'Shared (delphi)'
 UP intf.pas:PathOnly '\common\components'

ENDME // ME_57EE6E2A01A5 Shared Delphi MVC
