// Ml3GetComponentFromPointHelper A24A217A2949 PureMixIn Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAMS ME_A24A217A2949_diagrams

 MEDIAGRAM ME_A24A217A2949_main
  MEPROP Name 'main'
  MELINK Original WL 'ME_A24A217A2949' '55001317029B.ms.model.script' ; // Ml3GetComponentFromPointHelper

  MEVIEW ME_77F02E022F3C_view
   MELINK Original WL 'ME_77F02E022F3C' '55001317029B.ms.model.script' ; // GetComponent
   MEPROP X 40
   MEPROP Y 40
  ENDMEVIEW // ME_77F02E022F3C_view

  MELIST Views
   Seq: ( ME_77F02E022F3C_view // GetComponent
   )
  ; // Views
 ENDMEDIAGRAM // ME_A24A217A2949_main

 MELIST Diagrams
  Seq: ( ME_A24A217A2949_main
  )
 ; // Diagrams
ENDMEDIAGRAMS // ME_A24A217A2949_diagrams
