// TChangeableMainMenuTypeValuesMapImpl C02C49E8D4C5 SimpleClass Class

INCLUDE 'ElementsRTTI.ms.dict'

MEDIAGRAM ME_C02C49E8D4C5_main
 MEPROP Name 'main'
 MELINK Original WL 'ME_C02C49E8D4C5' '5795D66F0385.ms.model.script' ; // TChangeableMainMenuTypeValuesMapImpl

 MEVIEW ME_DA1BF0A2D389_view
  MELINK Original WL 'ME_DA1BF0A2D389' '5795D66F0385.ms.model.script' ; // Make
  MEPROP X 10
  MEPROP Y 10
 ENDMEVIEW // ME_DA1BF0A2D389_view

ENDMEDIAGRAM // ME_C02C49E8D4C5_main
