// evStylesPrintAndExportFontSizeSettingRes C9ADD4944F97 UtilityPack Class

INCLUDE 'ElementsRTTI.ms.dict'

%%Inner ME_86E0B8C46D3A
%%Inner ME_2F2551498AA7
%%Inner ME_E7E820B69587
%%Inner ME_1F17EF4CC358

FORWARD ME_C9ADD4944F97

FORWARD ME_86E0B8C46D3A

ME ME_C71B2FC1ECE9
 MEPROP UID 'C71B2FC1ECE9'
 MEPROP Name 'KEY_PrintAndExportFontSize_pef8'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '8' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_86E0B8C46D3A // PrintAndExportFontSizeEnum
 ;

ENDME // ME_C71B2FC1ECE9 KEY_PrintAndExportFontSize_pef8

ME ME_3876AAB74D59
 MEPROP UID '3876AAB74D59'
 MEPROP Name 'KEY_PrintAndExportFontSize_pef9'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '9' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_86E0B8C46D3A // PrintAndExportFontSizeEnum
 ;

ENDME // ME_3876AAB74D59 KEY_PrintAndExportFontSize_pef9

ME ME_9CA0E0D7887C
 MEPROP UID '9CA0E0D7887C'
 MEPROP Name 'KEY_PrintAndExportFontSize_pef10'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '10' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_86E0B8C46D3A // PrintAndExportFontSizeEnum
 ;

ENDME // ME_9CA0E0D7887C KEY_PrintAndExportFontSize_pef10

ME ME_B6CE4E265167
 MEPROP UID 'B6CE4E265167'
 MEPROP Name 'KEY_PrintAndExportFontSize_pef11'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '11' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_86E0B8C46D3A // PrintAndExportFontSizeEnum
 ;

ENDME // ME_B6CE4E265167 KEY_PrintAndExportFontSize_pef11

ME ME_5477CF0BF037
 MEPROP UID '5477CF0BF037'
 MEPROP Name 'KEY_PrintAndExportFontSize_pef12'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '12' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_86E0B8C46D3A // PrintAndExportFontSizeEnum
 ;

ENDME // ME_5477CF0BF037 KEY_PrintAndExportFontSize_pef12

ME ME_D799DD1DC9F3
 MEPROP UID 'D799DD1DC9F3'
 MEPROP Name 'KEY_PrintAndExportFontSize_pef14'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '14' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_86E0B8C46D3A // PrintAndExportFontSizeEnum
 ;

ENDME // ME_D799DD1DC9F3 KEY_PrintAndExportFontSize_pef14

ME ME_0AA08BEA186F
 MEPROP UID '0AA08BEA186F'
 MEPROP Name 'KEY_PrintAndExportFontSize_pef16'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '16' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_86E0B8C46D3A // PrintAndExportFontSizeEnum
 ;

ENDME // ME_0AA08BEA186F KEY_PrintAndExportFontSize_pef16

ME ME_86E0B8C46D3A
 MEPROP UID '86E0B8C46D3A'
 MEPROP Name 'PrintAndExportFontSizeEnum'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_Enum ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Ключи для настройки "Использовать для экспорта и печати следующий размер шрифта"' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELIST Attributes
   Seq: ( HWL ME_C71B2FC1ECE9 // KEY_PrintAndExportFontSize_pef8
 HWL ME_3876AAB74D59 // KEY_PrintAndExportFontSize_pef9
 HWL ME_9CA0E0D7887C // KEY_PrintAndExportFontSize_pef10
 HWL ME_B6CE4E265167 // KEY_PrintAndExportFontSize_pef11
 HWL ME_5477CF0BF037 // KEY_PrintAndExportFontSize_pef12
 HWL ME_D799DD1DC9F3 // KEY_PrintAndExportFontSize_pef14
 HWL ME_0AA08BEA186F // KEY_PrintAndExportFontSize_pef16
 )
 ; // Attributes
 UP extprop:rc:isAcceptableForScripts True

ENDME // ME_86E0B8C46D3A PrintAndExportFontSizeEnum

FORWARD ME_B23AC4E8CF02

FORWARD ME_2F2551498AA7

FORWARD ME_1884DBA9EBBD

ME ME_B9D22C2482B9
 MEPROP Name 'aStrings'
 UP IsSummoned true
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_4683CEE9034C' '467823B7002C.ms.model.script' // IafwStrings
 ;

ENDME // ME_B9D22C2482B9 aStrings

ME ME_1884DBA9EBBD
 MEPROP UID '1884DBA9EBBD'
 MEPROP Name 'FillStrings'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 %SUMMARY 'Заполнение списка строк значениями' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_2F2551498AA7 // PrintAndExportFontSizeValuesMapHelper
 ;
 MELIST Parameters
   Seq: ( ME_B9D22C2482B9 // aStrings
 )
 ; // Parameters

ENDME // ME_1884DBA9EBBD FillStrings

FORWARD ME_401032D7711F

ME ME_63E9FE4A21B5
 MEPROP Name 'aDisplayName'
 UP IsSummoned true
 MEPROP Class class_Parameter
 MELINK Stereotype st_in ;
 MELINK Target WL 'ME_46780DA40383' '4677FBA70343.ms.model.script' // Il3CString
 ;

ENDME // ME_63E9FE4A21B5 aDisplayName

ME ME_401032D7711F
 MEPROP UID '401032D7711F'
 MEPROP Name 'DisplayNameToValue'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_static::Operation ;
 %SUMMARY 'Преобразование строкового значения к порядковому' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_2F2551498AA7 // PrintAndExportFontSizeValuesMapHelper
 ;
 MELINK Target HWL ME_86E0B8C46D3A // PrintAndExportFontSizeEnum
 ;
 MELIST Parameters
   Seq: ( ME_63E9FE4A21B5 // aDisplayName
 )
 ; // Parameters

ENDME // ME_401032D7711F DisplayNameToValue

ME ME_2F2551498AA7
 MEPROP UID '2F2551498AA7'
 MEPROP Name 'PrintAndExportFontSizeValuesMapHelper'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Утилитный класс для преобразования значений PrintAndExportFontSizeValuesMap' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELIST Operations
   Seq: ( HWL ME_1884DBA9EBBD // FillStrings
 HWL ME_401032D7711F // DisplayNameToValue
 )
 ; // Operations
 UP extprop:rc:isAcceptableForScripts True
 UPLINK SpelledFor HWL ME_B23AC4E8CF02 // PrintAndExportFontSizeValuesMap
 ;

ENDME // ME_2F2551498AA7 PrintAndExportFontSizeValuesMapHelper

FORWARD ME_E7E820B69587

ME ME_893287292E3C
 MEPROP UID '893287292E3C'
 MEPROP Name 'Make'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_factory::Operation ;
 %SUMMARY 'Фабричный метод для TPrintAndExportFontSizeValuesMapImplPrim' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_E7E820B69587 // TPrintAndExportFontSizeValuesMapImplPrim
 ;
 MELINK Target WL 'ME_46A5FCD303C1' '4677FBA70343.ms.model.script' // Il3IntegerValueMap
 ;

ENDME // ME_893287292E3C Make

ME ME_46A5EFE602DE_ME_E7E820B69587
 MELINK Original WL 'ME_46A5EFE602DE' '4677FBA70343.ms.model.script' // MapID
 ;
 MEPROP OpKind opkind_Implemented
 UP "pm" True
ENDME // ME_46A5EFE602DE_ME_E7E820B69587 MapID

ME ME_46A5F0130365_ME_E7E820B69587
 MELINK Original WL 'ME_46A5F0130365' '4677FBA70343.ms.model.script' // GetDisplayNames
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_46A5F0130365_ME_E7E820B69587 GetDisplayNames

ME ME_46A5F03800A2_ME_E7E820B69587
 MELINK Original WL 'ME_46A5F03800A2' '4677FBA70343.ms.model.script' // MapSize
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_46A5F03800A2_ME_E7E820B69587 MapSize

ME ME_46A5FCF900E0_ME_E7E820B69587
 MELINK Original WL 'ME_46A5FCF900E0' '4677FBA70343.ms.model.script' // DisplayNameToValue
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_46A5FCF900E0_ME_E7E820B69587 DisplayNameToValue

ME ME_46A5FD1B000D_ME_E7E820B69587
 MELINK Original WL 'ME_46A5FD1B000D' '4677FBA70343.ms.model.script' // ValueToDisplayName
 ;
 MEPROP OpKind opkind_Implemented
ENDME // ME_46A5FD1B000D_ME_E7E820B69587 ValueToDisplayName

%%ImplementedBy ME_46A5FCD303C1 ME_E7E820B69587

%%InheritedBy ME_4AE5CA2D0034 ME_E7E820B69587

ME ME_E7E820B69587
 MEPROP UID 'E7E820B69587'
 MEPROP Name 'TPrintAndExportFontSizeValuesMapImplPrim'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Класс для реализации мапы для PrintAndExportFontSizeValuesMap' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_abstract
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4AE5CA2D0034' '47913B47006E.ms.model.script' // Tl3CProtoObject
 )
 ; // Inherits
 MELIST Implements
   Seq: ( WL 'ME_46A5FCD303C1' '4677FBA70343.ms.model.script' // Il3IntegerValueMap
 )
 ; // Implements
 MELIST Operations
   Seq: ( HWL ME_893287292E3C // Make
 )
 ; // Operations
 MELIST Implemented
   Seq: ( ME_46A5EFE602DE_ME_E7E820B69587 // MapID
 ME_46A5F0130365_ME_E7E820B69587 // GetDisplayNames
 ME_46A5F03800A2_ME_E7E820B69587 // MapSize
 ME_46A5FCF900E0_ME_E7E820B69587 // DisplayNameToValue
 ME_46A5FD1B000D_ME_E7E820B69587 // ValueToDisplayName
 )
 ; // Implemented
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'PrintAndExportFontSizeValuesMapImplPrim'
 UPLINK SpelledFor HWL ME_B23AC4E8CF02 // PrintAndExportFontSizeValuesMap
 ;

ENDME // ME_E7E820B69587 TPrintAndExportFontSizeValuesMapImplPrim

FORWARD ME_1F17EF4CC358

ME ME_369351B72390
 MEPROP UID '369351B72390'
 MEPROP Name 'Make'
 UP IsSummoned true
 MEPROP Class class_Operation
 MELINK Stereotype st_factory::Operation ;
 %SUMMARY 'Фабричный метод для TPrintAndExportFontSizeValuesMapImpl' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_1F17EF4CC358 // TPrintAndExportFontSizeValuesMapImpl
 ;
 MELINK Target WL 'ME_46A5FCD303C1' '4677FBA70343.ms.model.script' // Il3IntegerValueMap
 ;

ENDME // ME_369351B72390 Make

%%InheritedBy ME_E7E820B69587 ME_1F17EF4CC358

ME ME_1F17EF4CC358
 MEPROP UID '1F17EF4CC358'
 MEPROP Name 'TPrintAndExportFontSizeValuesMapImpl'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_SimpleClass ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Класс для реализации мапы для PrintAndExportFontSizeValuesMap' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELIST Inherits
   Seq: ( HWL ME_E7E820B69587 // TPrintAndExportFontSizeValuesMapImplPrim
 )
 ; // Inherits
 MELIST Operations
   Seq: ( HWL ME_369351B72390 // Make
 )
 ; // Operations
 UP "singleton" True
 UP extprop:rc:isAcceptableForScripts True
 UP extprop:rc:SelfName 'PrintAndExportFontSizeValuesMapImpl'
 UPLINK SpelledFor HWL ME_B23AC4E8CF02 // PrintAndExportFontSizeValuesMap
 ;

ENDME // ME_1F17EF4CC358 TPrintAndExportFontSizeValuesMapImpl

FORWARD ME_1782647A5439

ME ME_77DC0A07D1F7
 MEPROP UID '77DC0A07D1F7'
 MEPROP Name 'pi_evStyles_PrintAndExportFontSize'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY 'Идентификатор настройки "Использовать для экспорта и печати следующий размер шрифта"' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_1782647A5439 // PrintAndExportFontSizeKey
 ;
 MEPROP Value '''Стили/Использовать для экспорта и печати следующий размер шрифта'''
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '''Стили/Использовать для экспорта и печати следующий размер шрифта'''

ENDME // ME_77DC0A07D1F7 pi_evStyles_PrintAndExportFontSize

ME ME_B15096317BFF
 MEPROP UID 'B15096317BFF'
 MEPROP Name 'dv_evStyles_PrintAndExportFontSize'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY 'Значение по-умолчанию настройки "Использовать для экспорта и печати следующий размер шрифта"' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_1782647A5439 // PrintAndExportFontSizeKey
 ;
 MEPROP Value 0
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value 0

ENDME // ME_B15096317BFF dv_evStyles_PrintAndExportFontSize

ME ME_1782647A5439
 MEPROP UID '1782647A5439'
 MEPROP Name 'PrintAndExportFontSizeKey'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_Constants ;
 MEPROP Kind kind_NormalClass
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELIST Attributes
   Seq: ( HWL ME_77DC0A07D1F7 // pi_evStyles_PrintAndExportFontSize
 HWL ME_B15096317BFF // dv_evStyles_PrintAndExportFontSize
 )
 ; // Attributes
 UP "spell names" False

ENDME // ME_1782647A5439 PrintAndExportFontSizeKey

FORWARD ME_300F056A3E29

ME ME_B24E06693035
 MEPROP UID 'B24E06693035'
 MEPROP Name 'PrintAndExportFontSize'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY 'Использовать для экспорта и печати следующий размер шрифта' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_300F056A3E29 // PrintAndExportFontSizeName
 ;
 MEPROP Value '''Использовать для экспорта и печати следующий размер шрифта'''
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '''Использовать для экспорта и печати следующий размер шрифта'''

ENDME // ME_B24E06693035 PrintAndExportFontSize

ME ME_300F056A3E29
 MEPROP UID '300F056A3E29'
 MEPROP Name 'PrintAndExportFontSizeName'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_LocalConst ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Имя настройки "Использовать для экспорта и печати следующий размер шрифта"' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELIST Attributes
   Seq: ( HWL ME_B24E06693035 // PrintAndExportFontSize
 )
 ; // Attributes
 UP "Need map interface" False
 UP "Need mapping support" False
 UP "spell names" False

ENDME // ME_300F056A3E29 PrintAndExportFontSizeName

FORWARD ME_0F54723B9097

ME ME_96A5C7144E3D
 MEPROP UID '96A5C7144E3D'
 MEPROP Name 'pef8'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '8' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_0F54723B9097 // PrintAndExportFontSizeValues
 ;
 MEPROP Value '''8'''
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '''8'''

ENDME // ME_96A5C7144E3D pef8

ME ME_4FD853DD65A8
 MEPROP UID '4FD853DD65A8'
 MEPROP Name 'pef9'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '9' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_0F54723B9097 // PrintAndExportFontSizeValues
 ;
 MEPROP Value '''9'''
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '''9'''

ENDME // ME_4FD853DD65A8 pef9

ME ME_97ECF91D50DB
 MEPROP UID '97ECF91D50DB'
 MEPROP Name 'pef10'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '10' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_0F54723B9097 // PrintAndExportFontSizeValues
 ;
 MEPROP Value '''10'''
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '''10'''

ENDME // ME_97ECF91D50DB pef10

ME ME_4024903E186B
 MEPROP UID '4024903E186B'
 MEPROP Name 'pef11'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '11' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_0F54723B9097 // PrintAndExportFontSizeValues
 ;
 MEPROP Value '''11'''
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '''11'''

ENDME // ME_4024903E186B pef11

ME ME_0B5C090928C4
 MEPROP UID '0B5C090928C4'
 MEPROP Name 'pef12'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '12' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_0F54723B9097 // PrintAndExportFontSizeValues
 ;
 MEPROP Value '''12'''
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '''12'''

ENDME // ME_0B5C090928C4 pef12

ME ME_086F24F76C26
 MEPROP UID '086F24F76C26'
 MEPROP Name 'pef14'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '14' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_0F54723B9097 // PrintAndExportFontSizeValues
 ;
 MEPROP Value '''14'''
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '''14'''

ENDME // ME_086F24F76C26 pef14

ME ME_965460DF7185
 MEPROP UID '965460DF7185'
 MEPROP Name 'pef16'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '16' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_0F54723B9097 // PrintAndExportFontSizeValues
 ;
 MEPROP Value '''16'''
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '''16'''

ENDME // ME_965460DF7185 pef16

%%InheritedBy ME_86E0B8C46D3A ME_0F54723B9097

ME ME_0F54723B9097
 MEPROP UID '0F54723B9097'
 MEPROP Name 'PrintAndExportFontSizeValues'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_LocalConst ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Значения для настройки "Использовать для экспорта и печати следующий размер шрифта"' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELIST Inherits
   Seq: ( HWL ME_86E0B8C46D3A // PrintAndExportFontSizeEnum
 )
 ; // Inherits
 MELIST Attributes
   Seq: ( HWL ME_96A5C7144E3D // pef8
 HWL ME_4FD853DD65A8 // pef9
 HWL ME_97ECF91D50DB // pef10
 HWL ME_4024903E186B // pef11
 HWL ME_0B5C090928C4 // pef12
 HWL ME_086F24F76C26 // pef14
 HWL ME_965460DF7185 // pef16
 )
 ; // Attributes
 UP "elements prefix" 'PrintAndExportFontSize'
 UP "Need map interface" True
 UP "Need mapping support" True
 UP "spell names" False
 UP extprop:pas:ElementPrefix 'PrintAndExportFontSize_'
 UP extprop:pas:ElementPrefixBase 'PrintAndExportFontSize'

ENDME // ME_0F54723B9097 PrintAndExportFontSizeValues

FORWARD ME_BE1983D4EE58

ME ME_D105A1C05DEA
 MEPROP UID 'D105A1C05DEA'
 MEPROP Name 'pef8'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '8' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef8''; rValue : ''8'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef8''; rValue : ''8'')'
 UPLINK Speller HWL ME_96A5C7144E3D // pef8
 ;

ENDME // ME_D105A1C05DEA pef8

ME ME_A387B5DB4FAC
 MEPROP UID 'A387B5DB4FAC'
 MEPROP Name 'pef9'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '9' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef9''; rValue : ''9'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef9''; rValue : ''9'')'
 UPLINK Speller HWL ME_4FD853DD65A8 // pef9
 ;

ENDME // ME_A387B5DB4FAC pef9

ME ME_BBC2ED4B38BC
 MEPROP UID 'BBC2ED4B38BC'
 MEPROP Name 'pef10'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '10' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef10''; rValue : ''10'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef10''; rValue : ''10'')'
 UPLINK Speller HWL ME_97ECF91D50DB // pef10
 ;

ENDME // ME_BBC2ED4B38BC pef10

ME ME_6B97D05C8650
 MEPROP UID '6B97D05C8650'
 MEPROP Name 'pef11'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '11' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef11''; rValue : ''11'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef11''; rValue : ''11'')'
 UPLINK Speller HWL ME_4024903E186B // pef11
 ;

ENDME // ME_6B97D05C8650 pef11

ME ME_691591BE9CC4
 MEPROP UID '691591BE9CC4'
 MEPROP Name 'pef12'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '12' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef12''; rValue : ''12'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef12''; rValue : ''12'')'
 UPLINK Speller HWL ME_0B5C090928C4 // pef12
 ;

ENDME // ME_691591BE9CC4 pef12

ME ME_8E8680B425B2
 MEPROP UID '8E8680B425B2'
 MEPROP Name 'pef14'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '14' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef14''; rValue : ''14'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef14''; rValue : ''14'')'
 UPLINK Speller HWL ME_086F24F76C26 // pef14
 ;

ENDME // ME_8E8680B425B2 pef14

ME ME_76A3781CCD06
 MEPROP UID '76A3781CCD06'
 MEPROP Name 'pef16'
 UP IsSummoned true
 MEPROP Class class_Attribute
 %SUMMARY '16' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 MEPROP Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef16''; rValue : ''16'')'
 MELINK ValueType WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;
 UP "AutoInc" False
 UP "forced type" 'none'
 UP "is define" False
 UP extprop:pas:Value '(rS : -1; rLocalized : false; rKey : ''PrintAndExportFontSize_pef16''; rValue : ''16'')'
 UPLINK Speller HWL ME_965460DF7185 // pef16
 ;

ENDME // ME_76A3781CCD06 pef16

ME ME_BE1983D4EE58
 MEPROP UID 'BE1983D4EE58'
 MEPROP Name 'LCImplPrintAndExportFontSizeValues'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_Constants ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Локализуемые строки PrintAndExportFontSizeValues' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELIST Attributes
   Seq: ( HWL ME_D105A1C05DEA // pef8
 HWL ME_A387B5DB4FAC // pef9
 HWL ME_BBC2ED4B38BC // pef10
 HWL ME_6B97D05C8650 // pef11
 HWL ME_691591BE9CC4 // pef12
 HWL ME_8E8680B425B2 // pef14
 HWL ME_76A3781CCD06 // pef16
 )
 ; // Attributes
 UP "elements prefix" 'str_PrintAndExportFontSize'
 UP "spell names" False
 UP extprop:pas:ElementPrefix 'str_PrintAndExportFontSize_'
 UP extprop:pas:ElementPrefixBase 'str_PrintAndExportFontSize'
 UPLINK Speller HWL ME_0F54723B9097 // PrintAndExportFontSizeValues
 ;

ENDME // ME_BE1983D4EE58 LCImplPrintAndExportFontSizeValues

ME ME_AECDBEE72B72
 MEPROP UID 'AECDBEE72B72'
 MEPROP Name 'pef8'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_B23AC4E8CF02 // PrintAndExportFontSizeValuesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'pef8'
 MELINK ValueType HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 UP extprop:pas:Value 'str_PrintAndExportFontSize_pef8'

ENDME // ME_AECDBEE72B72 pef8

ME ME_BA23E2F17A53
 MEPROP UID 'BA23E2F17A53'
 MEPROP Name 'pef9'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_B23AC4E8CF02 // PrintAndExportFontSizeValuesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'pef9'
 MELINK ValueType HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 UP extprop:pas:Value 'str_PrintAndExportFontSize_pef9'

ENDME // ME_BA23E2F17A53 pef9

ME ME_BBC252C642DC
 MEPROP UID 'BBC252C642DC'
 MEPROP Name 'pef10'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_B23AC4E8CF02 // PrintAndExportFontSizeValuesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'pef10'
 MELINK ValueType HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 UP extprop:pas:Value 'str_PrintAndExportFontSize_pef10'

ENDME // ME_BBC252C642DC pef10

ME ME_ABD420FB6EE9
 MEPROP UID 'ABD420FB6EE9'
 MEPROP Name 'pef11'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_B23AC4E8CF02 // PrintAndExportFontSizeValuesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'pef11'
 MELINK ValueType HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 UP extprop:pas:Value 'str_PrintAndExportFontSize_pef11'

ENDME // ME_ABD420FB6EE9 pef11

ME ME_92B160E34332
 MEPROP UID '92B160E34332'
 MEPROP Name 'pef12'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_B23AC4E8CF02 // PrintAndExportFontSizeValuesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'pef12'
 MELINK ValueType HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 UP extprop:pas:Value 'str_PrintAndExportFontSize_pef12'

ENDME // ME_92B160E34332 pef12

ME ME_76CE7A95FF36
 MEPROP UID '76CE7A95FF36'
 MEPROP Name 'pef14'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_B23AC4E8CF02 // PrintAndExportFontSizeValuesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'pef14'
 MELINK ValueType HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 UP extprop:pas:Value 'str_PrintAndExportFontSize_pef14'

ENDME // ME_76CE7A95FF36 pef14

ME ME_D97D50B050B7
 MEPROP UID 'D97D50B050B7'
 MEPROP Name 'pef16'
 UP IsSummoned true
 MEPROP Class class_Attribute
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MEPROP LinkType lt_agr
 MELINK Parent HWL ME_B23AC4E8CF02 // PrintAndExportFontSizeValuesMap
 ;
 MELINK Target WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 ;
 MEPROP Value 'pef16'
 MELINK ValueType HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 ;
 UP extprop:pas:Value 'str_PrintAndExportFontSize_pef16'

ENDME // ME_D97D50B050B7 pef16

%%ImplementedBy ME_86E0B8C46D3A ME_B23AC4E8CF02

%%InheritedBy ME_4B3B49B40262 ME_B23AC4E8CF02

ME ME_B23AC4E8CF02
 MEPROP UID 'B23AC4E8CF02'
 MEPROP Name 'PrintAndExportFontSizeValuesMap'
 UP IsSummoned true
 MEPROP Class class_Class
 MELINK Stereotype st_ConstantArray ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Карта преобразования локализованных строк PrintAndExportFontSizeValues' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_regular
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELIST Inherits
   Seq: ( WL 'ME_4B3B49B40262' '4B3B36EC03B2.ms.model.script' // Pl3StringIDEx
 )
 ; // Inherits
 MELIST Implements
   Seq: ( HWL ME_86E0B8C46D3A // PrintAndExportFontSizeEnum
 )
 ; // Implements
 MELIST Attributes
   Seq: ( HWL ME_AECDBEE72B72 // pef8
 HWL ME_BA23E2F17A53 // pef9
 HWL ME_BBC252C642DC // pef10
 HWL ME_ABD420FB6EE9 // pef11
 HWL ME_92B160E34332 // pef12
 HWL ME_76CE7A95FF36 // pef14
 HWL ME_D97D50B050B7 // pef16
 )
 ; // Attributes
 UP "Need map interface" True
 UP "Need mapping support" True

ENDME // ME_B23AC4E8CF02 PrintAndExportFontSizeValuesMap

ME ME_E786DF941FB7
 UP IsSummoned true
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELINK Target WL 'ME_4B3B3728004C' '4B3B36EC03B2.ms.model.script' // Tl3StringIDEx
 ;

ENDME // ME_E786DF941FB7 

ME ME_29DA0043F9A6
 UP IsSummoned true
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELINK Target WL 'ME_4E01D1E002AE' '4E01D1980071.ms.model.script' // Tl3MessageID
 ;

ENDME // ME_29DA0043F9A6 

ME ME_5227F8E24CB1
 UP IsSummoned true
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELINK Target WL 'ME_47878E0E0191' '47878E0E0191.ms.model.script' // l3String
 ;

ENDME // ME_5227F8E24CB1 

ME ME_0C886C14C09A
 UP IsSummoned true
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELINK Target WL 'ME_4787A405013D' '47877EB202FB.ms.model.script' // Exception
 ;

ENDME // ME_0C886C14C09A 

ME ME_BBC352822A79
 UP IsSummoned true
 MEPROP Class class_Dependency
 MELINK Stereotype st_uses::Dependency ;
 MELINK Parent HWL ME_C9ADD4944F97 // evStylesPrintAndExportFontSizeSettingRes
 ;
 MELINK Target WL 'ME_4AC1F98A0155' '4773D64E036C.ms.model.script' // l3FillChar
 ;

ENDME // ME_BBC352822A79 

%%ImplementedBy ME_4E314EC80391 ME_C9ADD4944F97

ME ME_C9ADD4944F97
 MEPROP UID 'C9ADD4944F97'
 MEPROP Name 'evStylesPrintAndExportFontSizeSettingRes'
 UP IsSummoned true
 MEPROP IsSubRoot true
 MEPROP Class class_Class
 MELINK Stereotype st_UtilityPack ;
 MEPROP Kind kind_NormalClass
 %SUMMARY 'Ресурсы для настройки "Использовать для экспорта и печати следующий размер шрифта"' ;
 MEPROP Visibility PublicAccess
 MEPROP Abstraction at_final
 MELINK Parent WL 'ME_47ECB2870309' '47ECB2870309.ms.model.script' // StyleTable
 ;
 MELIST Implements
   Seq: ( WL 'ME_4E314EC80391' '4E3160C802DA.ms.model.script' // Использовать для экспорта и печати следующий размер шрифта
 )
 ; // Implements
 MELIST Children
   Seq: ( HWL ME_86E0B8C46D3A // PrintAndExportFontSizeEnum
 HWL ME_2F2551498AA7 // PrintAndExportFontSizeValuesMapHelper
 HWL ME_E7E820B69587 // TPrintAndExportFontSizeValuesMapImplPrim
 HWL ME_1F17EF4CC358 // TPrintAndExportFontSizeValuesMapImpl
 )
 ; // Children
 MELIST Constants
   Seq: ( HWL ME_1782647A5439 // PrintAndExportFontSizeKey
 HWL ME_300F056A3E29 // PrintAndExportFontSizeName
 HWL ME_0F54723B9097 // PrintAndExportFontSizeValues
 HWL ME_BE1983D4EE58 // LCImplPrintAndExportFontSizeValues
 HWL ME_B23AC4E8CF02 // PrintAndExportFontSizeValuesMap
 )
 ; // Constants
 MELIST Dependencies
   Seq: ( ME_E786DF941FB7 // Tl3StringIDEx
 ME_29DA0043F9A6 // Tl3MessageID
 ME_5227F8E24CB1 // l3String
 ME_0C886C14C09A // Exception
 ME_BBC352822A79 // l3FillChar
 )
 ; // Dependencies
 UP extprop:rc:SelfName 'StylesPrintAndExportFontSizeSettingRes'
 UP intf.pas:Path 'common\components\gui\Garant\Everest\evStylesPrintAndExportFontSizeSettingRes.pas'

ENDME // ME_C9ADD4944F97 evStylesPrintAndExportFontSizeSettingRes
