"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\ADDIMG.ADMINGUIDE\AddImg.AdminGuide.hmxz "/tsk=Recent Publishes:AddImg.AdminGuide " "/tsk=Recent Publishes:AddImg_!DAILY "
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\ADJUSTTOPAGE.ADMINGUIDE\AdjustToPage.AdminGuide.hmxz "/tsk=Recent Publishes:AdjustToPage.AdminGuide" "/tsk=Recent Publishes:AdjustToPage_!DAYLY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\ADMINISTRATOR.ADMINGUIDE\Administrator.AdminGuide.hmxz "/tsk=Recent Publishes:Administrator.AdminGuide" "/tsk=Recent Publishes:Administrator_!DAILY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" "D:\MANUAL(CVS)\archi\source\MANUAL\APPOSITION BD.ADMINGUIDE\Archivarius.AppositionBD.hmxz" "/tsk=Recent Publishes:Archivarius.AppositionBD.AdminGuide" "/tsk=Recent Publishes:AppositionBD_!DAILY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\ARCHIVARIUS.OPERATION.INTRODUCTION\Archivarius.IntroductionOperation.hmxz "/tsk=Recent Publishes:Archivarius.IntroductionOperation" "/tsk=Recent Publishes:Archivarius.Inroduction_!DAILY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\ARCHIVARIUS.SETTING\Archivarius.Setting.AdminGuide.hmxz "/tsk=Recent Publishes:Archivarius.Setting.AdminGuide" "/tsk=Recent Publishes:Archivarius.Setting.AdminGuide_!DAILY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\ARCHIVARIUS.USERGUIDE\Archivarius.UserGuide.hmxz /tsk=FullBuild:Archivarius.UserGuide(federal) /tsk=FullBuild:Archivarius.UserGuide(regions) /tsk=FullBuild:Archivarius.UserGuide(r)_!DAILY
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\ALCU.ADMINGUIDE\Autopipeserver.AdminGuide.hmxz "/tsk=ManualGuide (*pdf):FederalPDF" "/tsk=ManualGuide (*pdf):RegionPDF" "/tsk=ManualGuide (*pdf):RegCHM" "/tsk=ManualGuide (*pdf):FederalPDF" "/tsk=ManualGuide (*pdf):AutoPipeServer_!DAILY" "/tsk=ManualGuide (*pdf):AutoPipeServer(chm)_!DAILY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\DBUTIL.ADMINGUIDE\DbUtil.AdminGuide.hmxz /tsk=FullBuild:DbUtil.AdminGuide(federal) /tsk=FullBuild:DbUtil.AdminGuide(regional) /tsk=FullBuild:DbUtil.AdminGuide(r)_!DAILY
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\DELPREFIX.ADMINGUIDE\Delprefix.AdminGuide.hmxz /tsk=DelPrefixBuild:Delprefix.AdminGuide /tsk=DelPrefixBuild:Delprefix.AdminGuide_!DAILY
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\DESCRIPT\Descript.hmxz "/tsk=Recent Publishes:Publish as CHM" "/tsk=Recent Publishes:!DAILY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\DICTSYNC.ADMINGUIDE\Dictsync.AdmingGuide.hmxz "/tsk=Recent Publishes:Dictsync.AdmingGuide" "/tsk=Recent Publishes:Dictsync.AdmingGuide_!DAILY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\FAQ\FAQ.hmxz /tsk=FAQ_Task:FAQ-Manual /tsk=FAQ_Task:FAQ_!DAILY
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\HYTECH.CORRECTIONTABLE\HyTech.CorrectionTable.AdminGuide.hmxz "/tsk=Recent Publishes:HyTech.CorrectionTable.AdminGuide" "/tsk=Recent Publishes:HyTech.CorrectionTable.AdminGuide_!DAILY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\KILLTR.ADMINGUIDE\KILLTR.UserGuide.hmxz "/tsk=Recent Publishes:KILLTR.UserGuide" "/tsk=Recent Publishes:KILLTR.UserGuide_!DAILY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\LISTIMPORT.ADMINGUIDE\ListImport.AdminGuide.hmxz "/tsk=Recent Publishes:ListImport.AdminGuide" "/tsk=Recent Publishes:ListImport.AdminGuide_!DAILY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\NSCRSPY.ADMINGUIDE\Nsrcspy.AdminGuide.hmxz /tsk=FullManual:CHM-MANUAL /tsk=FullManual:MANUAL-OLD-VERSION /tsk=FullManual:MANUAL-NEW-VERSION /tsk=FullManual:NSRCSPY.ADMINGUIDE_!DAILY /tsk=FullManual:NSRCSpy.AdminGuide(r)_!DAILY
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\NSRPLUS2NSR.ADMINGUIDE\NSRplus2nsr.AdminGuide.hmxz "/tsk=Recent Publishes:NSRplus2nsr.AdminGuide" "/tsk=Recent Publishes:NSRplus2nsr.AdminGuide_!DAILY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\PIPEOUT2.ADMINGUIDE\PipeOut2.AdminGuide.hmxz "/tsk=Recent Publishes:PipeOut2.AdminGuide" "/tsk=Recent Publishes:PipeOut2.AdminGuide_!DAILY"
"C:\Program Files (x86)\EC Software\HelpAndManual6\HELPMAN.EXE" D:\MANUAL(CVS)\archi\source\MANUAL\REGIONTOOL.ADMINGUIDE\RegionTool.AdminGuide.hmxz /tsk=RegionTool:RegionTool.AdminGuide /tsk=RegionTool:RegionTool.AdminGuide_!DAILY